Documentation/platforms/sim/sim/boards/sim/index.rst
Add documentation referring to sim:alsa defconfig, about how to mount host system files in the simulator using `hostfs` and playing them using the ALSA adapter.
Document already existing functionality.
Local build of the docs using `sphinx-build`.
=> Documentation: Add documentation about sim:alsa defconfig

boards/boardctl.c, boards/sim/sim/sim/src/sim_bringup.c, drivers/usbdev/Make.defs, drivers/usbdev/adb.c, drivers/usbdev/composite.c, drivers/usbdev/composite.h, drivers/usbdev/composite_desc.c, include/nuttx/usb/adb.h, include/nuttx/usb/composite.h, include/nuttx/usb/usbdev.h, include/sys/boardctl.h
Add board control for adb class. this PR is needed by PR[ #1881](https://github.com/apache/nuttx-apps/pull/1881)
ADB boardctl
sim:usbdev
=> usb: add adb boardctl

mm/mm_heap/mm_free.c, mm/mm_heap/mm_realloc.c
Block wrong address in advance before entering mempool.
None.
None.
=> mm_heap: check heap member in advance

fs/vfs/fs_open.c
fixed open error when driver not implement write
=> fs_open: add ioctl checkflag

drivers/mtd/mtd_config_fs.c
=> driver/mtdconfig_fs : return -ENOENT when delete non-existed key

boards/arm/cxd56xx/common/CMakeLists.txt, boards/arm/cxd56xx/common/src/Make.defs
Remove a build warning by target 'cxd56_audio.o' given more than once in the same rule.
Only for spresense board.
=> boards: cxd56xx: Fix duplicate make target

tools/ci/testlist/arm-08.dat, tools/ci/testlist/arm-10.dat, tools/ci/testlist/arm-12.dat
cmake: enable more stm32 builds in ci
ci
=> cmake: enable more stm32 builds in ci

include/nuttx/net/ip.h, net/local/local_sockif.c, net/procfs/net_tcp.c, net/procfs/net_udp.c, net/tcp/tcp_ioctl.c, net/udp/udp_ioctl.c
- net/procfs: Simplify logic for tcp/udp stats
1. Take out `net_ip_binding_laddr/raddr` macro
2. `INET6_ADDRSTRLEN` is long enough for all address buffer and no need to
add 0 to the end of buffer since `inet_ntop` will do so
- net: Add `FIOC_FILEPATH` ioctl support for tcp/udp/local sockets
- Example of `/proc/PID/group/fd`, which prints the file path:
```
FD  OFLAGS  TYPE POS       PATH
0   3       1    0         /dev/console
1   3       1    0         /dev/console
2   3       1    0         /dev/console
3   3       9    0         udp:[0.0.0.0:10197<->114.118.7.163:123, tx 0/16384, rx 0/16384, flg 1]
4   1027    9    0         tcp:[0.0.0.0:23<->0.0.0.0:0, tx 0/16384, rx 0/16384 + ofo 0, st 01, flg 31]
5   67      9    0         local:[md:ap]
```
Mainly: procfs …
=> net: Add `FIOC_FILEPATH` ioctl support for tcp/udp/local sockets

net/local/local.h, net/local/local_conn.c, net/local/local_netpoll.c
net_lock/unlock is a big lock and repleace it to internal pool lock to avoid the priority inversion problem.
local socket
Local test in project.
=> net: add poll lock for local socket poll

drivers/usbdev/composite_desc.c
Use the correct USB dual-speed descriptor when enabling IAD.
composite usbdev
BES board
=> composite: Use the correct USB dual-speed descriptor when enabling IAD

tools/ci/cibuild.sh
report here: https://github.com/apache/nuttx/pull/10107
```
+ brew install u-boot-tools ==> Fetching dependencies for u-boot-tools: openssl@3 ==> Fetching openssl@3
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/manifests/3.1.2-1 Already downloaded: /Users/runner/work/nuttx/nuttx/sources/tools/homebrew/downloads/d235bbcbe9c405bfbe837454515b9cb2793542891a2050e5948a94f596e2a51e--openssl@3-3.1.2-1.bottle_manifest.json ==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/blobs/sha256:2bea791e9eacc59e0a9099065f3229afaf2b68a9b7b3136ec508103985b1176c Already downloaded: /Users/runner/work/nuttx/nuttx/sources/tools/homebrew/downloads/d082c3abe2fd32b11d857fb7111adc0fc02a0b345044c07f2e7db7160f15300e--openssl@3--3.1.2.ventura.bottle.1.tar.gz ==> Fetching u-boot-tools
==> …
```
=> ci: Fix the openssl installation fail on macOS

libs/libm/newlib/include/math.h
Fix error:
```
nuttx/libs/libm/newlib/include/math.h:89:8: error: ‘_Thread_local’ does not name a type; did you mean ‘thread_local’?
89 | extern _Thread_local int _tls_gamma_signgam;
|        ^~~~~~~~~~~~~
|        thread_local
In file included from /mnt/nuttx/include/libcxx/math.h:300,
from /mnt/nuttx/include/libcxx/cmath:308,
from /mnt/nuttx/include/libcxx/charconv:79,
from libcxx/src/string.cpp:10:
/mnt/nuttx/libs/libm/newlib/include/math.h:89:8: error: ‘_Thread_local’ does not name a type; did you mean ‘thread_local’?
89 | extern _Thread_local int _tls_gamma_signgam;
```
ci
=> libm/newlib: fix newlib build error

include/nuttx/sched_note.h
SCHED_NOTE_IP address calculation error in some cases, refer to _THIS_IP_ implementation in linux https://elixir.bootlin.com/linux/latest/source/include/linux/instruction_pointer.h#L6
=> note: fix sched_note_begin address errr

net/netdev/netdev_ioctl.c
The call of `netdev_ifr_dev` is already simplified by commit fd53db56b6
`SIOCSIFMTU` case in `netdev_ifr_ioctl`
CI && `ifconfig eth0 mtu 1300`
=> net/netdev: Simplify handling of `SIOCSIFMTU`

drivers/sensors/sensor.c, include/nuttx/sensors/sensor.h
A sensor of this type measures the force on it, and additionally compares the force with one or more specified thresholds. The sensor can output the force value directly. Moreover, it's usually applied as a press key. In that case, when it detects a force greater than some given threshold, a corresponding event is reported.
=> feature: sensor: add force sensor

drivers/pipes/pipe.c, drivers/pipes/pipe_common.c, drivers/pipes/pipe_common.h
drivers/pipes: use circbuf to refine buffer model
N/A
CONFIG_EXAMPLES_PIPE  pipe test
=> drivers/pipes: use circbuf to refine buffer model

arch/arm/src/armv8-m/arm_exception.S
Fix usage fault on clang version 13.0.0 (-Ofast).
An INVSTATE UsageFault is raised if a LE instruction is executed and FPSCR.LTPSIZE does not read as four.
In armv8m the FPSCR[18:16] LTPSIZE field must be set to 0b100 for "Tail predication not applied" as it's reset value.
armv8-m exception
bes board compile with clang
=> armv8-m: the FPSCR[18:16] LTPSIZE field in exception_common

libs/libc/machine/arm64/gnu/arch_setjmp.S
ARM64: save and restore fpu regs in jmp only when ARCH_FPU enabled.
setjmp
=> arm64: save and restore fpu regs in jmp when ARCH_FPU enabled

arch/arm64/src/common/arm64_backtrace.c
Fixed arm64 backtrace support for other processes
arm64 backtrace
=> arch/arm64: Fixed arm64 backtrace support for other processes

arch/arm/src/armv6-m/Make.defs, arch/arm/src/armv6-m/arm_cpuinfo.c
add armv6-m cpuinfo
show cpuinfo under procfs/ for armv6
internel testing for armv6-m.
=> procfs: add armv6-m cpuinfo

include/nuttx/net/icmpv6.h
The `SIZEOF_ICMPV6_ECHO_REQUEST_S` and `SIZEOF_ICMPV6_ECHO_REPLY_S` macro are intended to be `8+n`, but actually becomes `10-1+n` and causes the packet sent by `ping6` one byte more than expected.
`ping6` command
`ping6` on sim with wireshark
=> net/icmpv6: Fix value of `SIZEOF_ICMPV6_ECHO_xxx_S`

arch/arm/src/common/arm_backtrace_sp.c
Should check the addr every time it changed to avoid crash in backtrace.
Should be None
Local project test
=> arm_backtrace_sp: check the addr after every operation to addr

arch/sim/src/sim/sim_framebuffer.c
add set/get_power operation for sim_framebuffer to avoid assert in fb_ioctl(cmd= FBIOSET_POWER/FBIOGET_POWER)
Should be None
local project test
=> sim: add set/get_power for sim_framebuffer.c

include/nuttx/note/noteram_driver.h
/home/baerg/code/NXOS/nuttx/include/nuttx/note/noteram_driver.h:100:61: error: unknown type name ‘bool’
100 | noteram_initialize(FAR const char *devpath, size_t bufsize, bool overwrite);
|                                                             ^~~~
/home/baerg/code/NXOS/nuttx/include/nuttx/note/noteram_driver.h:31:1: note: ‘bool’ is defined in header ‘<stdbool.h>’; did you forget to ‘#include <stdbool.h>’?
=> drivers/note: Fix missing header file compilation failure

net/netlink/netlink_sockif.c, net/utils/net_lock.c
remove [enter|leave]_critical_section and sched_[un]lock
none
none
=> net: remove [enter|leave]_critical_section and sched_[un]lock

binfmt/binfmt_exec.c
adding enter_critical_section to ensure non preemption in smp
none
none
=> binfmt: add enter_critical_section

drivers/power/supply/regulator.c, include/nuttx/power/consumer.h, include/nuttx/power/regulator.h
1.support always on
when add always on desc,the regulator is always enabled
2. support link to supply
when add supply desc,the regulator is linked to the parent regulator
a.if enable the regualtor, the parent regulator is enabled
b.if disable all child regulator, the parent regualtor is disabled
3.support lp mode and auto pm register
a.add new intf regulator_set_mode to manual set rehulator lower power mode;
b.when add auto lp desc,the regulator lp mode is controlled by  pm framework;
4.optimize the lock to support call the interface in idle task by pm
=> Regulator:add new features

graphics/CMakeLists.txt, graphics/nxglib/CMakeLists.txt, graphics/nxterm/CMakeLists.txt, libs/libnx/nxfonts/CMakeLists.txt, libs/libnx/nxmu/CMakeLists.txt
env:sim
enable  CONFIG_DRIVERS_VIDEO, CONFIG_VIDEO_FB, CONFIG_SIM_FRAMEBUFFER,  CONFIG_NX
=> cmake:enable nxlib cmake build,fix build break

net/icmpv6/icmpv6.h, net/icmpv6/icmpv6_autoconfig.c, net/icmpv6/icmpv6_neighbor.c, net/icmpv6/icmpv6_sendmsg.c, net/sixlowpan/sixlowpan_tcpsend.c, net/sixlowpan/sixlowpan_udpsend.c, net/tcp/tcp_conn.c, net/tcp/tcp_send_buffered.c, net/tcp/tcp_send_unbuffered.c, net/tcp/tcp_sendfile.c, net/udp/udp_sendto_buffered.c, net/udp/udp_sendto_unbuffered.c
The netdev of link-local address cannot be auto decided, and the link-local address should always be reguarded as address on local network.
The problem we met:
When using `icmpv6_autoconfig` with multiple netdev, the `icmpv6_neighbor` may take out wrong netdev with ip address already set, then it may send solicitation with wrong address (`dev->d_ipv6draddr`) on wrong device, and regard the link-local address as conflict (because `dev->d_ipv6draddr` exists on this network).
ICMPv6 neighbor / autoconfig
Manually: autoconfig on sim with 2 netdev
=> net/icmpv6: Fix `icmpv6_neighbor` for link-local address

drivers/input/keyboard_upper.c
Buffer nums is not multiplied by the structure size
=> drivers/input:Fix setting the number of keyboard driver buffers fails

drivers/usbdev/adb.c, drivers/usbdev/cdcacm.c, drivers/usbdev/composite.c, drivers/usbdev/pl2303.c, drivers/usbdev/rndis.c
1. a memory leak occurred when the usb uninitialize process was executed: 
In usbclass_unbind, DEV_FREEEP is called first, and later usbclass_freereq does not free memory due to ep NULL.
2.  composite devices are not automatically recognized by windows:
Description bMS_VendorCode is incorrectly configured. Change it to USB_REQ_GETMSFTOSDESCRIPTOR(0xee), which is the same as the request processing logic for GET_MS_DESCRIPTOR in the code.
USB
Test for BES board
=> usb: Fixed memory leak for usb uninitialize process

Documentation/components/drivers/character/note.rst, drivers/note/note_driver.c, drivers/note/noteram_driver.c, include/nuttx/note/note_driver.h, include/nuttx/note/noteram_driver.h, sched/init/nx_start.c, sched/task/task_setup.c
This PR moves the note formatting code from trace_dump into noteram and simplifies the noteram code.
Details:
Change 1: move trace_dump to noteram_driver.c
Change 2: replace the spaces in the name in tcb, there cannot be spaces in the thread name in atrace format
Change 3: remove task_context and get_taskname related code, we don't need it anymore
Change 4: simplify the logic of ringbuffer in noteram
The data returned by reading the /dev/note device is no longer binary data, but a formatted string, and it will only return one note record each time it is read
self-test + internal CI
=> drivers/note: move the note formatting code from trace_dump into noteram_drivers.c

include/nuttx/net/tun.h
to support cross-core tun device operations via rpmsgdev
Arm Cortex-M33
=> tun: move tun related macro definitions out of CONFIG_NET_TUN

boards/sim/sim/sim/src/sim_bringup.c, drivers/misc/rpmsgdev.c, drivers/misc/rpmsgdev.h, drivers/misc/rpmsgdev_server.c, include/nuttx/drivers/rpmsgdev.h
The default mode for Rpmsgdev is to read/write data as long as possible for caller, this mode does not apply to tun devices, tun devices can read and write only one complete ip packet at a time.
Cortex-M33
=> rpmsgdev: support single read/write mode device

drivers/usrsock/usrsock_rpmsg_server.c
req->usockid maybe < 0 or > CONFIG_NET_USRSOCK_RPMSG_SERVER_NSOCKS, if so , priv->pfds[req->usockid] will access invalid memory.
sim:local
=> usrsock_server: coverity fix for access invalid index

arch/sim/src/sim/sim_initialstate.c
In last PR #10128, the sizeof xcpt_reg_t is different on 32/64 bit platform. Fix it here
Report by https://github.com/apache/nuttx/pull/10178.
sim:smp
=> sim: use correct size to avoid buffer overflow

libs/libc/gdbstub/lib_gdbstub.c
gdbstub:fix typo
gdbstub
```
CC:  umm_heap/umm_zalloc.c gdbstub/lib_gdbstub.c:599:12: error: conflicting types for ‘gdb_hex2bin’; have ‘int(void *, size_t,  const void *, size_t)’ {aka ‘int(void *, long unsigned int,  const void *, long unsigned int)’}
599 | static int gdb_hex2bin(FAR void *buf, size_t buf_len,
|            ^~~~~~~~~~~
gdbstub/lib_gdbstub.c:102:16: note: previous declaration of ‘gdb_hex2bin’ with type ‘ssize_t(void *, size_t,  const void *, size_t)’ {aka ‘long int(void *, long unsigned int,  const void *, long unsigned int)’}
102 | static ssize_t gdb_hex2bin(FAR void *buf, size_t buf_len,
|                ^~~~~~~~~~~
gdbstub/lib_gdbstub.c: In function ‘gdb_write_memory’:
gdbstub/lib_gdbstub.c:1079:38: warning: passing argument 6 of ‘gdb_put_memory’ from incompatible …
```
=> gdbstub:fix typo

drivers/math/CMakeLists.txt, drivers/math/Kconfig, drivers/math/Make.defs, drivers/math/math.c, include/nuttx/math/fft.h, include/nuttx/math/math.h, include/nuttx/math/math_ioctl.h
Support fft in nuttx/math, in general, I add a math.h to support math accelerators, including the existed cordic and new coming fft. And the ability for supporting more.
nuttx/math
nuttx/math/cordic.h, nuttx/math/fft.h are framework for chips, I implemented and test the framework below.
cordic hardware accelerator tested with stm32g431rb, sf32lb5xx
fft hardware accelerator tested with sf32lb5xx
=> math api support FFT

include/nuttx/drivers/drivers.h
=> drivers: fix devascii_register warning

drivers/misc/rpmsgblk_server.c
drivers/misc/rpmsgblk: fix build break if CONFIG_DISABLE_PSEUDOFS_OPERATIONS
```
In function ‘rpmsgblk_unlink_handler’:
misc/rpmsgblk_server.c:340:36: error: ‘const struct block_operations’ has no member named ‘unlink’
340 |   msg->header.result = server->bops->unlink(server->blknode);
|
```
N/A
ci-check
=> drivers/misc/rpmsgblk: fix build break if CONFIG_DISABLE_PSEUDOFS_OPERATIONS

sched/pthread/pthread_create.c
old:
pthread_create:
init_priority = prio;
if (sched_priority < parent_prio)
sched_priority = parent_prio;    // don't need
pthread_start:
if (sched_priority > init_priority)
sched_priority = init_priority
pthread_create
VELA
=> pthread: remove unused temp change sched_priority

arch/arm/src/stm32h7/hardware/stm32_spi.h
It was the following compilation error if CONFIG_STM32H7_FMC=y:
`chip/hardware/stm32_spi.h:40:4: error: #error "Unsupported STM32 H7 sub family"`
It is related to #9796.
arm/stm32h7 (CONFIG_STM32H7_STM32H7X5XX)
./tools/configure.sh -l stm32h745i-disco:nsh (with CONFIG_STM32H7_FMC enabled)
=> arm/stm32h7: stm32h7x5: fixed typo on SPI header inclusion

mm/iob/iob_alloc.c
if there are two throttled wait, when iob_free occurs, one of wait will be awakened to execute iob_alloc_committed, but it will fail to execute, sem will be posted at this time, then another wait will be awakened. after the other wait thread is awakened, This step is repeated. the two threads are in the critical_section state and cannot be switched to other threads. then cpu will busy util timeout.
sim:local and cortex-m33 device
=> iob_alloc: change sem_post to count++

include/nuttx/sched.h, libs/libc/unistd/lib_vfork.c, sched/sched/sched_waitpid.c
This change corrects the -ECHILD error in the following situation:
First, in nuttx implement, vfork use waitpid to hang on the parent process, make it continue after child process ended.
https://github.com/apache/nuttx/blob/d98bfc3e49b55ad560907241cbd7e184cf7aac0a/libs/libc/unistd/lib_vfork.c#L66
Second, this waitpid will make sure child process ended and remove the child process info in nxsched_waitpid.
https://github.com/apache/nuttx/blob/d98bfc3e49b55ad560907241cbd7e184cf7aac0a/sched/sched/sched_waitpid.c#L361
In the end, if application call wait will find NO child process info in 
https://github.com/apache/nuttx/blob/d98bfc3e49b55ad560907241cbd7e184cf7aac0a/sched/sched/sched_waitpid.c#L264
In one world, it looks like vfork interface implement not support to wait vforked child process …
=> fix wait after vfork return error

binfmt/binfmt_execmodule.c, binfmt/elf.c, binfmt/libelf/libelf_init.c, include/nuttx/binfmt/binfmt.h, include/nuttx/binfmt/elf.h
From posix spec, if set-user-ID bit is set in the file permissions, then the effective user ID of the new process shall be set to the user ID of the new process image file.
Let's ignore whether ST_NOSUID is set on the mounted file system.
https://pubs.opengroup.org/onlinepubs/007904875/functions/exec.html
test step:
hello example build as a module and call geteuid and getegid API.
then set elf file set-user-ID bit in the host.
$ chmod +s apps/bin/hello
nsh> mount -t hostfs -o fs=. /data
nsh> ls -l /data/apps/bin/hello
-rwsrwsr-x    1000    1000    9264 /data/apps/bin/hello
nsh> /data/apps/bin/hello
geteuid:1000
getegid:1000
None
sim & pass CI
=> binfmt: support euid of process set from the file system

arch/arm/src/sama5/Kconfig, arch/arm/src/sama5/sam_mcan.c
Errors fixed relating to MCAN1, and to range checking, plus changes to Kconfig and driver code to improve clarity of "data" and "nominal" timing setup to better match the processor datasheet. The #define naming within the driver has been changed to better reflect this too, but the Kconfig names have been retained as-was to avoid problems with any existing builds.
None expected
Custom board with SAMA5D27C-D1M with 2x MCAN interfaces.
=> SAMA5D2 MCAN Error corrections plus changes to improve clarity

drivers/input/ads7843e.c, drivers/input/ft5x06.c, drivers/input/max11802.c, drivers/input/mxt.c, drivers/input/stmpe811_tsc.c, drivers/input/tsc2007.c
rm sched_[un]lock
We use enter_critical_section to protect the read and write of priv structures,
sched_lock is mainly used to prevent active context switching caused by nxsem_post.
We do not actively switch contexts when reading and writing priv structures,
so sched_lock can be removed.
none
none
=> drivers/input: rm sched_[un]lock

arch/arm/src/nrf52/Kconfig, arch/arm/src/nrf52/hardware/nrf52_twi.h
Added config option to enable timing bug workaround for NRF52 I2C. Erratum details at:
https://infocenter.nordicsemi.com/index.jsp?topic=%2Fstruct_nrf52%2Fstruct%2Fnrf52840_errata.html
[219] TWIM: I2C timing spec is violated at 400 kHz
Very sensitive I2C devices may fail to respond without this change.
Tested on Arduino Nano 33 BLE board.
=> Added config setting for NRF52 I2C timing bug workaround.

arch/arm/src/nrf52/hardware/nrf52_twi.h, arch/arm/src/nrf52/nrf52_i2c.c
Several register names were not quite correct.
No functional change.
Tested on Arduino Nano 33 BLE board.
=> Fixed NRF52 I2C register naming.

arch/arm/src/nrf52/hardware/nrf52_twi.h, arch/arm/src/nrf52/nrf52_i2c.c, arch/arm/src/nrf53/Kconfig, arch/arm/src/nrf53/hardware/nrf53_twi.h, arch/arm/src/nrf53/nrf53_i2c.c, arch/arm/src/nrf53/nrf53_usbd.c, arch/arm/src/nrf91/hardware/nrf91_twi.h, arch/arm/src/nrf91/nrf91_i2c.c
- arch/nrf52/nrf52_i2c.c: remove unnecessary include introduced in cc99d94cfd
- arch/nrf52/nrf52_twi.h: fix condition
- arch/nrf53: port d7aea88727 change from nrf52
- arch/{nrf53|nrf91}: port cc99d94cfd change from nrf52
- arch/nrf53: port 6e8f25ba3b change from nrf52
CI
=> Port recent changes in nrf52 to other Nordic chips

drivers/video/Kconfig, drivers/video/Make.defs, drivers/video/goldfish_fb.c
Nuttx Goldfish-FB driver is to communicate with Goldfish-FB in QEMU, and push the framebuffer data to the emulator for display on the screen.
Add Nuttx Goldfish-FB driver.
1. CONFIG_GOLDFISH_FB =1.
2. Run lvgldemo.
=> Driver/video: Add Nuttx Goldfish-FB driver

binfmt/builtin.c, fs/binfs/fs_binfs.c, include/nuttx/lib/builtin.h, libs/libc/builtin/Make.defs, libs/libc/builtin/lib_builtin_getgid.c, libs/libc/builtin/lib_builtin_getmode.c, libs/libc/builtin/lib_builtin_getuid.c
Implement I_SUID/I_SGID feature for binfs in the POSIX compliant way. If set-user-ID bit is set in the file permissions, then the effective user ID of process shall be set to UID of the new process image file.
test case:
hello example emulates to set uid and file set-user-ID bit, and call geteuid and getegid API.
UID = 2000
GID = 3000
MODE = 06555
nsh> ls -l /bin/hello
-r-sr-sr-x    2000    3000       0 hello
nsh> hello
geteuid:2000
getegid:3000
sim & pass CI
=> builtin: support uid/gid config for binfs app

cmake/nuttx_add_library.cmake
> [!NOTE]
complete the issue for this discussion https://github.com/apache/nuttx/issues/10191
cmake build
=> cmake:fix add_user_library module archive issue

arch/arm/src/nrf52/nrf52_i2c.c, arch/arm/src/nrf53/nrf53_i2c.c, arch/arm/src/nrf91/nrf91_i2c.c
arch/{nrf52|nrf53|nrf91}: handle I2C errors in interrupt mode
i2c bus scan with i2ctool works on nrf52840
=> arch/{nrf52|nrf53|nrf91}: handle I2C errors in interrupt mode

boards/sim/sim/sim/scripts/Make.defs
To make the address returned by backtrace and gdbstub match the symbol stored in elf.
Fix the link address of sim in a stable address
sim
sim64 sim32
=> arch/sim:add -Ttext-segment to load the image in the fixed address

arch/arm/src/stm32h7/hardware/stm32h7x3xx_pwr.h, arch/arm/src/stm32h7/stm32h7x3xx_rcc.c, arch/arm/src/stm32h7/stm32h7x7xx_rcc.c
arch/stm32h7: use correct name for bit 2 in STM32_PWR_CR3 register
ci
=> arch/stm32h7: use correct name for bit 2 in STM32_PWR_CR3 register

sched/semaphore/sem_trywait.c
* sched/semaphore: Remove restriction to use nxsem_trywait from ISR
It could be called from the interrupt handler because `nxsem_trywait` is non-blocking, although not recommended.
Enable applications to call this interface (with `CONFIG_DEBUG_ASSERTIONS` enabled) without problems. No impact for current implementations.
Internal CI testing + NuttX CI.
=> sched/semaphore: Remove restriction to use nxsem_trywait from ISR

arch/arm/src/armv7-a/arm_gicv2.c, arch/arm/src/armv7-a/arm_gicv2_dump.c, arch/arm/src/armv7-a/arm_timer.c, arch/arm/src/armv7-a/gic.h, arch/arm/src/armv7-r/CMakeLists.txt, arch/arm/src/armv7-r/Make.defs, arch/arm/src/armv7-r/arm_gicv2.c, arch/arm/src/armv7-r/arm_gicv2_dump.c, arch/arm/src/armv7-r/arm_timer.c, arch/arm/src/armv7-r/gic.h, arch/arm/src/tms570/Make.defs, arch/arm64/src/common/arm64_gicv2.c
from https://developer.arm.com/documentation/ihi0048/b.
and Sync armv7r gic/timer with armv7-a 
internal
=> arch/armv7-a: Update the macro definition in gic.h 

net/icmp/icmp_ioctl.c, net/icmpv6/icmpv6_ioctl.c, net/local/local_sockif.c, net/netdev/netdev_ioctl.c, net/rpmsg/rpmsg_sockif.c, net/tcp/tcp_ioctl.c, net/udp/udp_ioctl.c
Example of /proc/PID/group/fd in this case:
```
FD  OFLAGS  TYPE POS       PATH
3   3       9    0         icmp:[dev eth0, id 1, flg 1]
4   3       9    0         icmp6:[dev eth0, id 2, flg 1]
5   3       9    0         rpmsg:[ap:[test:0]<->remote] # server side
5   3       9    0         rpmsg:[remote<->ap:[test:0]] # client side
6   67      9    0         socket:[domain 16, type 2, proto 0] # sockets without FIOC_FILEPATH support
```
procfs `/proc/PID/group/fd` with icmp/rpmsg sockets and ioctl `FIOC_FILEPATH` for usrsock sockets.
Manually (`fdinfo` command)
=> net: Add `FIOC_FILEPATH` ioctl support for ICMP(v6)/RPMsg/Usrsock sockets

Kconfig, arch/arm/src/common/Toolchain.defs, arch/risc-v/src/common/Toolchain.defs, arch/sim/src/cmake/Toolchain.cmake, arch/xtensa/src/lx6/Toolchain.defs, arch/xtensa/src/lx7/Toolchain.defs, boards/sim/sim/sim/scripts/Make.defs
Detect use of large stack variables
partition/fs_gpt.c:384:5: warning: stack usage might be 288 bytes [-Wstack-usage=]
384 | int parse_gpt_partition(FAR struct partition_state_s *state,
=> toolchain: detect use of large stack variables

arch/arm/src/kinetis/hardware/kinetis_flexcan.h, arch/arm/src/s32k1xx/hardware/s32k1xx_flexcan.h, arch/arm/src/s32k3xx/hardware/s32k3xx_flexcan.h
The timing mask for the can's ctrl1 register excludes the propagation segment bits. This results in incorrect timing when configuring bitrate at runtime with SIOCSCANBITRATE when the bitrate to timeseg algorithm selects a different propseg value.
Incorrect can timing configuration when moving between rates at runtime. 
s32k1xx HW testing: moving between several speeds both in listen only and while actively participating on the network.
=> Fix: s32k1 s32k3 kinetis: add propseg to ctrl1 timing mask

drivers/usbdev/composite.c
In class disconnect, resetconfig will be performed based on configid, so configid should be cleared after disconnect.
composite usbdev
sim:usbdev
=> usbdev: clear configid after class disconnect

CMakeLists.txt, cmake/nuttx_add_dependencies.cmake, cmake/nuttx_export_header.cmake
In the original GNU Make build, we use `Make.defs` to add the global include path,
and the private include path of the application library is written in the `Makefile`.
In Nuttx CMake build, we achieve similar global functionality through this patch.
- `nuttx_export_header` for applications global header file export:
the export path is in the `build-directory/apps/include/target-name`.
all exported header files retain relative paths.
```cmake
set(INCDIRS foo/include)
nuttx_export_header(TARGET foo INCLUDE_DIRECTORIES ${INCDIRS})
#
```
-  `nuttx_add_dependencies` is the wrapper to achieve import
add the dependency by nuttx wrapping function, and automatically add its exported include path.
```cmake
nuttx_add_dependencies(TARGET bar DEPENDS foo)
``` 
`libtomcrypt` DEPENDSON `libtommath`
- …
=> cmake:new feature on enhance apps header cmake module

arch/arm/src/common/arm_backtrace_unwind.c
common/arm_backtrace_unwind.c:528:18: warning: 'ctrl.lr_addr' may be used uninitialized in this function [-Wmaybe-uninitialized]
fix warning
ci
=> arch/arm: Fix arm_backtrace_unwind.c -Wmaybe-uninitialized

drivers/serial/pty.c
add support to get and set local mode of pty. this patch is supplement to 64b51bbbf7e9434a6c789cfbdaa5e744f898bf0c
=> drivers/pty: Support get and set local mode of pty

fs/vfs/fs_fsync.c
This command is called only if the device is a block device or mtd device.
=> fs_fsync.c:Fix unknown command message in non-block device situations

drivers/audio/cxd56.c, drivers/audio/cxd56.h, drivers/audio/cxd56_src.c
Support CXD56 audio input for 192kHz sampleing rate, 24bit and 4channels.
refs #16249
Spresense Audio Functionality only
Test if nxplayer and nxrecorder work fine on Spresense board.
=> driver/audio/cxd56: Support 24bit, 192kHz and 4ch max

boards/arm/nrf52/arduino-nano-33ble-rev2/src/nrf52_autoleds.c, boards/arm/nrf52/arduino-nano-33ble-rev2/src/nrf52_userleds.c, boards/arm/nrf52/arduino-nano-33ble/src/nrf52_autoleds.c, boards/arm/nrf52/arduino-nano-33ble/src/nrf52_userleds.c
boards/arduino-nano-33ble{-rev2}: use bool for leds state
Cosmetic changes suggested by @pkarashchenko https://github.com/apache/nuttx/pull/10217#discussion_r1293893916
cosmetics
CI
=> boards/arduino-nano-33ble{-rev2}: use bool for leds state

tools/ci/docker/linux/Dockerfile
g++ need update to the new version for libcxx 15.0.7.
Docker
Pass CI
=> tools/ci: Update docker to ubuntu 22.04

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_ddr.c
This PR doesn't fix any bugs per se, it just cleans up the code and adds more configurability.
It allows removing another manual DDR training step and use the controller's own logic instead by a CONFIG flag. This PR removes the manual step by default.
Code cleanup, removal of dead code, adding one configuration option.
This has been tested on Aries m100pfsevp board, icicle board and on custom HW.
=> MPFS DDR training cleanups

include/nuttx/mm/mempool.h, mm/mempool/mempool_multiple.c
mempool:Use default alignment inside of blockalign
mempool
sim:nsh with `mm`
=> mempool:Use default alignment inside of blockalign

net/rpmsg/rpmsg_sockif.c
Support poll rpmsg socket fd with block mode
rpmsg socket
Local project
=> rpmsg_sockif: block poll shoud not set POLLERR

net/can/can_recvmsg.c
args can_id for recv_filter doesn't work properly
=> socketcan : fixed CAN ID cast error

drivers/misc/rpmsgdev.c
In a multi-core heterogeneous architecture, tun device nodes of protocol stack core can be accessed by other cores through ioctl
Arm Cortex-M33
=> rpmsgdev: add tun device ioctl support

mm/iob/iob_clone.c
make the function can correctly handle negative offset cases
sim:local
=> iob: iob_clone_partial support Negative offset

arch/arm/src/common/arm_hostfs.c, arch/arm64/src/common/arm64_hostfs.c, arch/risc-v/src/common/riscv_hostfs.c, arch/sim/src/sim/posix/sim_hostfs.c, arch/sim/src/sim/sim_cpuinfo.c, arch/sim/src/sim/win/sim_hostfs.c, arch/xtensa/src/common/xtensa_hostfs.c, fs/hostfs/hostfs.c, include/nuttx/fs/hostfs.h
Fix the bug that calling "fseek(fin, 0, SEEK_SET)" causes ENOSYS error under some simulator configurations.
=> hostfs:support SEEK_CUR

drivers/lcd/lcd_dev.c, drivers/lcd/lcd_framebuffer.c, include/nuttx/lcd/lcd.h
Some LCD vendors support unit test commands, we should passthrough the ioctl commands to drivers.
=> drivers/lcd : add ioctl passthrough for LCD driver

libs/libc/net/lib_getifaddrs.c
ifindex is also returned when obtain NIC information through getifaddrs.
sim:local
=> getifaddrs: set sin6_scope_id when IPv6 enable

net/inet/ipv6_setsockopt.c
Synchronize code differences from internal repositories to the community
sim:local
=> ipv6_setsockopt: remove redundant logic

include/sys/types.h, include/time.h
POSIX Standard: Primitive System Data Types
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_types.h.html
fix LTP buildonly case
pass CI
=> include: move clockid_t and time[r]_t define to sys/types.h

drivers/misc/rwbuffer.c
the  padblock code not aligned with physical alignment
it will read/write beyond the end of the partition when the block  is near the end of partition
=> ftl: fix ftl_flush will read/erase beyond the end of the partition

drivers/drivers_initialize.c, fs/fs_initialize.c, sched/clock/clock_initialize.c, sched/group/group_setupidlefiles.c, sched/group/group_setuptaskfiles.c, sched/init/nx_bringup.c, sched/init/nx_start.c, sched/irq/irq_initialize.c, sched/mqueue/mq_initialize.c, sched/semaphore/sem_initialize.c, sched/signal/sig_initialize.c, sched/task/task_init.c, sched/timer/timer_initialize.c
Add the startup process tracepoint
After enabling config_trace configuration, you can directly see the startup time
=> sched: add the startup process tracepoint

include/nuttx/net/icmp.h, net/icmp/icmp.h, net/icmp/icmp_conn.c, net/icmp/icmp_input.c, net/icmp/icmp_recvmsg.c, net/icmp/icmp_sendmsg.c, net/icmp/icmp_sockif.c, net/inet/inet_sockif.c
Since ICMPv6 has added SOCK_RAW, a SOCK_RAW related implementation has also been added for ICMP.
sim:local
=> icmp: add SOCK_RAW type support

net/arp/arp_send.c
If the arp query times out, the destination ip address is displayed to help locate the problem
sim:local
=> arp_wait: print dest ip address when receive wait timeout

net/local/local_recvmsg.c
Some programs use EAGAIN to determine whether all data has been read, so cancel the error print when the error code is EAGAIN.
sim:local
=> local_recvmsg: do not print error message when errno is EAGAIN

Documentation/quickstart/debugging.rst
According to `Documentation/guides/gdbwithpython.rst` and GDB's documentation, the `-ix` option "Execute commands from file `file` before loading the inferior (but after loading gdbinit files)", being the correct way of loading it to GDB. This was tested and verified with SIM.
Avoid confusion regarding using GDB with Python
NuttX CI + Documentation built locally with `sphinx-build`
=> Documentation: Fix command to load `nuttx/tools/gdb/__init__.py`

net/tcp/tcp.h, net/tcp/tcp_input.c, net/tcp/tcp_send_buffered.c, net/tcp/tcp_timer.c
net/tcp:Added tcp zero window probe timer support
https://www.rfc-editor.org/rfc/rfc1122#page-92
minor
=> net/tcp:Added tcp zero window probe timer support

arch/arm64/src/common/arm64_vectors.S
this is an old implementation for ARM64 trace, but will fail
compile when CONFIG_SCHED_INSTRUMENTATION_SWITCH is enabled.
Remove it, since it will never be used for trace framework.
None
PASS
=> arm64: remove unnecessary trace interface

sched/init/nx_smpstart.c
core0 may write the data used by other cpu, this will cause cache inconsistency. so need fulsh dcache before start other cpus.
smp
fvp-armv8r:nsh_smp boot
=> sched/smp: flush dcache before start other cpus

libs/libc/netdb/lib_gethostbyaddrr.c, libs/libc/netdb/lib_gethostentbynamer.c
lib_gethostbyaddrr.c: warning: label 'out_copyname' defined but not used [-Wunused-label] 204 | out_copyname:
=> fixed the unused variable caused warnning in lib_gethostbyaddrr

net/devif/devif_poll.c
=> devif/devif_poll :  d_len must positive before invoke callback

sched/sched/sched_timerexpiration.c
If we are running on a single CPU architecture, then we know interrupts are disabled and there is no need to explicitly call enter_critical_section(). However, in the SMP case, enter_critical_section() is required prevent multiple cpu to enter timer_start.
SMP
BES board
=> SMP: fix repeat entry timer_start

sched/signal/sig_dispatch.c
To determine whether a signal is real-time signal or standard signal, the POSIX standard https://www.man7.org/linux/man-pages/man7/signal.7.html defines a real-time signal between SIGRTMIN  and SIGRTMAX , which can store multiple copies, otherwise only one can be retained.
sim:ostest
=> sigqueue: add signal type judgment logic

arch/arm/Kconfig
select ARCH_HAVE_CPUINFO by default
cpuinfo
=> cpuinfo:armv6: select ARCH_HAVE_CPUINFO by default

net/tcp/tcp_netpoll.c
When do poll operation and the tcp connection state is TCP_ALLOCATED, eventset(POLLERR|POLLHUP) is return, causing the libuv poll_multiple_handles to fail. So we add the condition of TCP_ALLOCATED on calculating the `nonblock_conn`.
If a tcp connection is in the TCP_ALLOCATED state and nonblocking, we can do poll operation on it.
Use the libuv test case ` uv_run_tests poll_multiple_handles`.
=> net/tcp: Fix unreadable error when doing poll operation on tcp socket.

Documentation/guides/minidumpserver.rst, tools/minidumpserver.py
support xtensa esp32s3 arm-a thumb to use log create gdbserver
minidumpserver.py
1.use `./tools/configure.sh esp32s3-devkit:nsh` and disable ` NSH_DISABLE_MW`
2. make -j20
3. donwload to esp32s3
4. use `mw -1` on nsh
5. copy crash log save as logfile
```
up_dump_register:    PC: 42009cd8    PS: 00060820
up_dump_register:    A0: 82007d71    A1: 3fc8b6d0    A2: 3fc8b8e0    A3: 00000000
up_dump_register:    A4: ffffffff    A5: 00000000    A6: 00000001    A7: 00000000
up_dump_register:    A8: ffffffff    A9: 3fc8b690   A10: ffffffff   A11: 00000000
up_dump_register:   A12: 0000002d   A13: 0000002d   A14: 3fc8bb6d   A15: 0fffffff
up_dump_register:   SAR: 00000000 CAUSE: 0000001c VADDR: ffffffff
up_dump_register:  LBEG: 40055499  LEND: 400554a9  LCNT: fffffffc
dump_stack: User Stack: …
```
=> support xtensa esp32s3 arm-a thumb to use log create gdbserver

include/ctype.h, libs/libc/ctype/lib_isalnum.c, libs/libc/ctype/lib_isalpha.c, libs/libc/ctype/lib_isascii.c, libs/libc/ctype/lib_isblank.c, libs/libc/ctype/lib_iscntrl.c, libs/libc/ctype/lib_isdigit.c, libs/libc/ctype/lib_isgraph.c, libs/libc/ctype/lib_islower.c, libs/libc/ctype/lib_isprint.c, libs/libc/ctype/lib_ispunct.c, libs/libc/ctype/lib_isspace.c, libs/libc/ctype/lib_isupper.c, libs/libc/ctype/lib_isxdigit.c, libs/libc/ctype/lib_tolower.c, libs/libc/ctype/lib_toupper.c
libs/ctype/toupper_l: Implement function toupper_l instead of macro.
Use functions instead of macros to solve recursive execution problems
toupper_l will be replaced by toupper, resulting in infinite recursion, so implement toupper_l
crash stack:
```
0  std::__1::ctype_byname<char>::do_toupper (this=0xf3888120, c=49 '1') at libcxx/src/locale.cpp:1231 
1  0x005b8188 in std::__1::ctype<char>::toupper (__c=49 '1', this=0xf3888120) at nuttx/include/libcxx/__locale:667 
2  std::__1::ctype_byname<char>::do_toupper (this=0xf3888120, c=49 '1') at libcxx/src/locale.cpp:1231 
3  0x005b8188 in std::__1::ctype<char>::toupper (__c=49 '1', this=0xf3888120) at nuttx/include/libcxx/__locale:667 
4  std::__1::ctype_byname<char>::do_toupper (this=0xf3888120, c=49 '1') at libcxx/src/locale.cpp:1231 
5 …
```
=> libs/ctype/toupper_l: Implement function toupper_l instead of macro

drivers/pipes/pipe_common.c
drivers/pipes: fix busyloop issue when circbuf is full
pipecommon_poll always reutrn POLLOUT when the circbuf is full.
fix busyloop about pipe
daily test
=> drivers/pipes: fix busyloop issue when circbuf is full

arch/arm/src/common/Toolchain.defs, arch/arm64/src/Toolchain.defs, arch/risc-v/src/common/Toolchain.defs, arch/xtensa/src/lx6/Toolchain.defs, arch/xtensa/src/lx7/Toolchain.defs
When all C++ code is built using GCC 7.1 or a higher version, we can safely disregard warnings of the type "parameter passing for X changed in GCC 7.1."
Refer to : https://stackoverflow.com/questions/48149323/what-does-the-gcc-warning-project-parameter-passing-for-x-changed-in-gcc-7-1-m
gcc command line
ci
=> nuttx/arch:add -Wno-psabi to Toolchain.defs.

libs/libc/gpsutils/Make.defs
libc/gpsutils: merged into one target to fix the issue of parallel compilation
Because multiple dependencies behind the context are compiled in parallel, if they have dependencies on each other, it will cause compilation errors.
This PR is realted to https://github.com/apache/nuttx-apps/pull/1867
./tools/configure.sh lilygo_tbeam_lora_gps/gps &&  make -j8
=> libc/gpsutils: merged into one target to fix issue of parallel compile

tools/ci/docker/linux/Dockerfile
and change the default toolchain to riscv32-unknown-elf-, required by https://github.com/apache/nuttx/pull/8244.
riscv toolchain
ci
=> ci/Dockerfile: Update riscv toolchain to gcc13.2.0

drivers/net/netdev_upperhalf.c, drivers/virtio/virtio-net.c, include/nuttx/mm/iob.h, include/nuttx/net/netdev_lowerhalf.h, mm/iob/iob_update_pktlen.c, net/arp/arp_format.c, net/devif/devif_filesend.c, net/devif/devif_poll.c, net/devif/devif_send.c, net/devif/ipv4_input.c, net/devif/ipv6_input.c, net/icmp/icmp_reply.c, net/icmpv6/icmpv6_advertise.c, net/icmpv6/icmpv6_radvertise.c, net/icmpv6/icmpv6_reply.c, net/icmpv6/icmpv6_rsolicit.c, net/icmpv6/icmpv6_solicit.c, net/igmp/igmp_send.c, net/mld/mld_send.c, net/tcp/tcp_send.c, net/udp/udp_send.c, net/udp/udp_sendto_buffered.c
|             | 256B vs 1534B | 512B vs 1534B | 768B vs 1534B |
| :---------: | :-----------: | :-----------: | :-----------: |
|     Non-SMP |     ~85%      |     ~93%      |     ~96%      |
|  armv8a-SMP |     ~66%      |     ~84%      |     ~92%      |
| rv32/64-SMP |     ~52%      |     ~72%      |     ~83%      |
It seems we still get performance penalty on smaller IOBs, and may be affected more under SMP mode. It may be caused by critical sections in IOB operations.
- drivers/virtio-net: Add support to offload small IOBs
- netdev/upper: Add `netpkt_to_iov()` interface
- Some driver like virtio-net can offload fragmented IOBs, so an interface to support this feature is needed.
- mm/iob: Add support for increasing length in `iob_update_pktlen`
- drivers/virtio-net: Support different …
=> drivers/virtio-net: Add support to offload small IOBs

boards/arm/qemu/qemu-armv7a/src/qemu_bringup.c, boards/arm64/qemu/qemu-armv8a/src/qemu_bringup.c, boards/risc-v/qemu-rv/rv-virt/src/qemu_rv_appinit.c
- I noticed that device discovery for virtio-mmio devices does not work without bus=virtio-mmio-bus.x option. 
- Without this option, qemu assigns the virtio device into the virtio-mmio space in reverse order automatically.
- To fix this issue, we must specify the correct numbers for the target machines. (i.e. arm32/64->32, rv32/64->8)
- None
- Tested with qemu-7.2.4
=> boards: Fix QEMU_VIRTIO_MMIO_NUM

tools/ci/docker/linux/Dockerfile
Reverts apache/nuttx#10306 since some target fail to build here: https://github.com/apache/nuttx/pull/10345.
=> Revert "ci/Dockerfile: Update riscv toolchain to gcc13.2.0"

arch/risc-v/src/common/riscv_addrenv.c
1 page might not be enough, if the task has a bigger stack. Best effort is to allocate the default amount, however this won't work will all tasks either. See issue #5811 for more details.
Fixes system crash when not enough heap is allocated for new task's stack. Only affects builds with CONFIG_BUILD_KERNEL.
Target with processes whose stack size is > 1 page (4K)
=> riscv/riscv_addrenv.c: Allocate heap for default task stacksize

drivers/segger/CMakeLists.txt, tools/ci/testlist/arm-08.dat
cmake: drivers/segger support
nucleo-f446re/systemview
=> cmake: drivers/segger support

net/rpmsg/rpmsg_sockif.c
Use PRIx64 which defines the width correctly regardless or architecture.
Fixes build error:
rpmsg/rpmsg_sockif.c:610:57: error: format '%llx' expects argument of type 'long long unsigned int', but argument 4 has type 'uint64_t' {aka 'long unsigned int'} [-Werror=format=]
610 |       snprintf(conn->nameid, sizeof(conn->nameid), ":%llx", g_rpmsg_id++);
|                                                      ~~~^   ~~~~~~~~~~~~
|                                                         |             |
|                                                         |             uint64_t {aka long unsigned int}
|                                                         long long unsigned int
|                                                      %lx
Fix sprintf format to work when u64 is defined as …
=> rpmsg/rpmsg_sockif.c: Fix printf format for u64 type

arch/arm/src/common/Toolchain.defs, arch/xtensa/src/esp32/Make.defs, libs/libxx/libcxx.defs
Toolchain: strict GCC version check from GCC-12.2 to GCC-12
Toolchain related detection errors are still not resolved on GCC-12.3
N/A fix ci break
ci check
=> Toolchain: strict GCC version check from GCC-12.2 to GCC-12

tools/ci/docker/linux/Dockerfile
upgrade Renesas gcc toolchain to 8.3.0
Docker
Pass CI
=> tools/ci: Upgrade toolchain base to ubuntu 22.04 and Renesas gcc toolchain to 8.3.0

drivers/timers/pwm.c, include/nuttx/timers/pwm.h
Documentation for PWMIOC_SETCHARACTERISTICS ioctl command mentioned that this command will neither start nor stop the pulsed output. This however is incorrect as PWMIOC_SETCHARACTERISTICS command leads to pwm_start() function which starts the pulsed output.
While this might not be the correct behaviour (I would probably welcome the option to set PWM characteristics without starting the pulsed output) it is the way the PWM driver is coded for many architectures. Future enhancement might be to add function pwm_setchar() for example to just set characteristics without starting the PWM output. This would require quite a lot of work as we would have to change every PWM driver.
Just comments.
=> pwm: fix incorrect documentation for PWMIOC_SETCHARACTERISTICS IOCTL

tools/refresh.sh
This patch modify the script to update only the boards configs of an specific chip or only the boards of an specific architecture.
Examples:
refresh.sh add custom board verify
custom board:
```
./tools/refresh.sh --silent /xxx/xxx/configs/ap
./tools/refresh.sh --silent ../../xxx/configs/ap
```
refresh.sh
ci
=> tools/refresh.sh: Add option to refresh  custom board

LICENSE, include/nuttx/list.h
which was removed accidentally in: https://github.com/apache/nuttx/pull/1629
paper work
ci
=> include/nuttx/list.h: Restore the origin copyright notice

Kconfig, include/debug.h
Allows the debug behavior to be specified as part of the board, architecture or chip configuration. This is useful when using out-of tree custom board configurations.
Customise debug behaviour for boards.
Enable `CONFIG_ARCH_BOARD_DEBUG_H` and add `debug.h` to custom boards directory.
=> debug: Let boards define custom debug configuration.

boards/arm/cxd56xx/spresense/src/cxd56_charger.c, boards/arm/cxd56xx/spresense/src/cxd56_gauge.c
Fix the function definitions to match the prototype declarations.
=> boards: cxd56xx: Fix charger and gauge initialize functions

.github/workflows/build.yml
don't need waste time to build the source code if the patch only changes dockerfile.
ci
ci
=> github: Skip the build if the change is under tools/ci/docker/linux

libs/libxx/libcxx.cmake, libs/libxx/libcxxabi.cmake, openamp/open-amp.cmake
> this patch is a part of this  issue https://github.com/apache/nuttx/issues/10241
- delete the .git condition that cause duplication of fetching stage.
- replace custom_patch_target with PATCH_COMMAND.
- remove custom_patch_target dependencies.
related to:https://github.com/apache/nuttx-apps/pull/1993
fetch for the first time and compile repeated
=> cmake:replace custom_patch_target with PATCH_COMMAND

net/tcp/tcp_wrbuffer.c, net/udp/udp_wrbuffer.c
Using the macro places the buffers into .data section which means they will consume the full buffer size of flash / read only memory as well.
Place the buffers into .bss to avoid this case.
Free up read only memory from .data section
Build pass
=> net/xx/wrbuffer: Do not use SEM_INITIALIZER for buffers

arch/arm/src/samv7/sam_pwm.c, include/nuttx/timers/pwm.h
Many PWM drivers can set channel output polarity (logical low or high) in idle state. This is usually set with a dedicated
channel control register. This commit adds field `cpol` to `pwm_info_s` structure that allows the user to pass the information
of desired polarity to architecture layer from application layer. Already implemented PWMIOC_SETCHARACTERISTICS ioctl is
used for the change.
Possibility of polarity change is added to samv7 driver.
None for current drivers as the functionality is not implemented there..
Tested on SAMv7 mcu.
=> pwm: add option to set channel polarity with IOCTL

boards/arm/cxd56xx/common/src/cxd56_ak09912_scu.c, boards/arm/cxd56xx/common/src/cxd56_bmi160_scu.c, boards/arm/cxd56xx/common/src/cxd56_bmp280_scu.c, boards/arm/cxd56xx/drivers/sensors/ak09912_scu.c, boards/arm/cxd56xx/spresense/include/cxd56_ak09912.h, boards/arm/cxd56xx/spresense/include/cxd56_bmi160.h, boards/arm/cxd56xx/spresense/include/cxd56_bmp280.h, include/nuttx/sensors/ak09912.h, include/nuttx/sensors/bmi160.h, include/nuttx/sensors/bmp280.h, include/nuttx/sensors/fxos8700cq.h
Move SCU-specific sensors into spresense board to improve modularity.
Issue: https://github.com/apache/nuttx/issues/10240
Spresense board.
Build and work bmi160, bmp280 and ak09912 sensors.
=> sensors: Move SCU-specific sensors into spresense board

arch/xtensa/src/esp32/esp32_spi.c, arch/xtensa/src/esp32/esp32_wlan.c
1. Fix below build warning:
```
CC:  chip/esp32_spi.c chip/esp32_spi.c: In function 'esp32_spi_dma_exchange':
chip/esp32_spi.c:861:17: warning: implicit declaration of function 'kmm_malloc'; did you mean 'iob_alloc'? [-Wimplicit-function-declaration]
alloctp = kmm_malloc(total);
^~~~~~~~~~
iob_alloc
chip/esp32_spi.c:861:15: warning: assignment to 'uint8_t *' {aka 'unsigned char *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
alloctp = kmm_malloc(total);
^
chip/esp32_spi.c:880:15: warning: assignment to 'uint8_t *' {aka 'unsigned char *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
allocrp = kmm_malloc(total);
^
chip/esp32_spi.c:957:7: warning: implicit declaration of function 'kmm_free'; did you mean 'iob_free'? …
```
=> esp32: Fix build warning

net/inet/ipv4_setsockopt.c, net/inet/ipv6_setsockopt.c, net/udp/udp.h, net/udp/udp_finddev.c
refer to https://man7.org/linux/man-pages/man7/ip.7.html IP_MULTICAST_IF (since Linux 1.2)​
Set the local device for a multicast socket.  The argument​
for setsockopt(2) is an ip_mreqn or (since Linux 3.5)​
ip_mreq structure similar to IP_ADD_MEMBERSHIP, or an​
in_addr structure.  (The kernel determines which structure​
is being passed based on the size passed in optlen.)  For​
getsockopt(2), the argument is an in_addr structure.​
refer to https://man7.org/linux/man-pages/man7/ipv6.7.html IPV6_MULTICAST_IF​
Set the device for outgoing multicast packets on the​
socket.  This is allowed only for SOCK_DGRAM and SOCK_RAW​
socket.  The argument is a pointer to an interface index​
(see netdevice(7)) in an integer.
IP Multicast
testcase1:​
```
TEST_IMPL(udp_multicast_interface) {​
/* …
```
=> net:add IP_MULTICAST_IF & IPV6_MULTICAST_IF function implementation

fs/vfs/fs_fsync.c
Reason for revert: when block device enable bch proxy, it works like a char device, so fsync calling would be failed here
=> Revert commit 35602cc2effe923e8c9b635bfc5f11cea36f7ccb(fs_fsync.c:Fix unknown command message in non-block device situations)

net/tcp/tcp_send_buffered.c
Non-blocking sockets are almost never in the connected state when app try to get result of connect success through poll, to avoid confusion because of this error print, so downgrade the print level to warning.
sim:local
=> tcp_send_buffered: change Not connected message level from error to warning

drivers/sensors/Kconfig
sensors/Kconfig: fix wrong depends on SN_XXX
CI
=> sensors/Kconfig: fix wrong depends on SN_XXX

arch/risc-v/src/mpfs/mpfs_i2c.c
Calculate how long an I2C transation will take in microseconds, and use this as the timeout for mpfs_i2c_sem_waitdone.
The reason for doing this is not to keep an i2c bus reserved for the full 1 second timeout, if e.g. a sensor is not on the bus / is faulty and non-responsive. Reading the other sensors will be blocked for a relatively long time (1 second) in this case. This fixes such behavior.
Change fixed 1 second timeout to calculated ideal timeout
Out-of-tree target with multiple I2C sensors on same bus
=> mpfs/mpfs_i2c.c: Replace 1 second timeout with Time-on-Air based timeout

arch/arm/include/samv7/chip.h, arch/arm/src/samv7/Kconfig, arch/arm/src/samv7/sam_qspi_spi.c
Current implementation of QSPI in SPI mode was available only for MCUs that do not have standard SPI at all. MCUs with both QSPI and SPI can however also use QSPI in SPI mode and thus have one more SPI bus. This commit adds required defines and config options to support QSPI in SPI mode for all SAMv7 MCUs.
Tested on SAMv7 custom board.
=> samv7: allow usage of QSPI in SPI mode for all MCUs

drivers/note/noteram_driver.c
Exceeding the length limit may cause an error when using sched_note_printf
=> driver/note: fix trace dump: dump failed

sched/misc/assert.c
Fix the printing alignment of interrupt stack during assert.
before:
```
dump_tasks:    PID GROUP PRI POLICY   TYPE    NPX STATE   EVENT      SIGMASK          STACKBASE  STACKSIZE      USED   FILLED    COMMAND
dump_tasks:   ----   --- --- -------- ------- --- ------- ---------- -------- 0x2d04ea28      2048       608    29.6%    irq
dump_task:       0     0   0 FIFO     Kthread N-- Ready              0000000000000000 0x2d052af0      1016       520    51.1%    Idle_Task
dump_task:       1     1 224 RR       Kthread --- Waiting Semaphore  0000000000000000 0x2d054018      2008       304    15.1%    hpwork 0x2d050818
```
after:
```
dump_tasks:    PID GROUP PRI POLICY   TYPE    NPX STATE   EVENT      SIGMASK          STACKBASE  STACKSIZE      USED   FILLED    COMMAND
dump_tasks:   ----   --- …
```
=> assert: Fix the printing alignment of interrupt stack during assert

include/signal.h
The <signal.h> header shall define the symbolic constants of signal codes why the signal was generated.
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/signal.h.html
fix LTP buildonly case for si_code test
LTP & ci pass
=> signal: add more value defines of the siginfo si_code field

include/signal.h, libs/libc/signal/CMakeLists.txt, libs/libc/signal/Make.defs, libs/libc/signal/sig_interrupt.c
https://pubs.opengroup.org/onlinepubs/9699919799/functions/siginterrupt.html
LTP posix API need support siginterrupt for buildonly case
None
LTP buildonly case and ci pass
=> signal: add siginterrupt implementation

libs/libc/netdb/Kconfig
change the default NETDB_DNSCLIENT_MAXRESPONSE to the standard length
the size of the dns response buffer
https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-respsize-12
minor
=> change the default NETDB_DNSCLIENT_MAXRESPONSE to the standard length

net/local/local_fifo.c
net/local: fix visual studio Compiler Error C2057
expected constant expression
The context requires a constant expression, an expression whose value is known at compile time.
The compiler must know the size of a type at compile time in order to allocate space for an instance of that type.
Reference:
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2057?view=msvc-170
N/A
visual studio 2023 + cmake
=> net/local: fix visual studio Compiler Error C2057

include/nuttx/sched_note.h
Use sched_note_mark to view event markers/counter in perfetto
=> drivers/note: Add support for atrace mark/counter type

drivers/ioexpander/Kconfig, drivers/ioexpander/Make.defs, drivers/ioexpander/iso1h812g.c, drivers/ioexpander/iso1h812g.h, include/nuttx/ioexpander/iso1h812g.h
This commit adds support for galvanic isolated ISO1H812G SPI expander. Both single pin and multiple pin writes are supported.
New expander, none for current mainline.
Tested on samv7 custom board.
=> ioexpander: add support for ISO1H812G expander

sched/sched/sched_foreach.c
vfs:add sched_lock to sync avoid crash
If scheduling occurs in file_fsync,
fl_lock may be released, and an error may
occur when calling nxmutex_unlock
call nxsched_foreach
sim:nsh
=> vfs:add nxsched_foreach to sched_lock avoid crash

libs/libc/stdlib/lib_exit.c, sched/group/group_leave.c
Destroy task tls before _exit will be more reasonable.
There is an application model in our system, which is one main thread and some pool threads in one task.
These threads  are waiting for some work to do all the time.
This is currently exit sequence:
```
exit
_exit                     
group_kill_children   // kill threads in the task
nxtask_exithook       // 
group_leave         // call group_release after all of the members left the group
```       
The problem here is that all threads is killed by signal, which will lead to some resource hold by these threads is not released.
We can name this `task_tls_destruct()` is called **passively** to release task TLS.
What I'm trying to do is using the `task_tls_destruct()` to **actively** do something to cooperatively terminate all threads, …
=> move task tls destruct to before _exit

drivers/video/isx019.c
isx019 driver freezes by I2C access in the interrupt context.
This I2C access is intended to stop data output from FPGA.
Delete this I2C access for the following reasons.
- Data output from FPGA does not affect power consumption
- There are no problems in capture restart without data output stop
since restart is done by image data block first.
video/isx019
=> drivers/video: Fix an issue isx019 may freeze

drivers/ioexpander/Kconfig, drivers/ioexpander/Make.defs, drivers/ioexpander/iso1i813t.c, drivers/ioexpander/iso1i813t.h, include/nuttx/ioexpander/iso1i813t.h
This commit adds basic support for electrically isolated 8 bit expander. The expander communicates with the MCU via SPI interface. Both single and multiple pin read are supported.
New driver.
Tested on SAMv7 custom board.
=> ioexpander: add support for ISO1I813T expander

net/socket/bind.c
net/socket/bind: make sure that an address was provided
1. make sure that an address was provided on bind() call
2. correct the return value if bad socket handler
N/A
ci-check
=> net/socket/bind: make sure that an address was provided

drivers/mmcsd/mmcsd_sdio.c
Commit 50a8ec6 broke many mmc devices.  Only if the flag priv->caps & SDIO_CAPS_4BIT_ONLY was set, it migth work. Without the flag, the mmc clock is never set (mmcsd_widebus() call is terminated early stopping the clock).  This flag is probably not very generic because most mmc hw support 1, 4 and 8 bit modes.
JEDEC specifies a bus width selection procedure, but it's not implemented in this mmcsd_sdio.c driver.  Thus, it's not known whether the hw supports 1, 4 anf 8 bit modes or a combination of them.
However, with priv->caps & SDIO_CAPS_4BIT_ONLY the driver suddenly assigns priv->buswidth = MMCSD_SCR_BUSWIDTH_4BIT making it the only way to have the driver working.
Fix this by relaxing the above mentioned restrictions.
emmc devices are broken with the current driver
probably all emmc …
=> drivers/mmcsd: fix regression causing emmcsd not working

net/can/can_recvmsg.c
net/can: correct the return value if unsupported socket type
N/A
ci-check
=> net/can: correct the return value if unsupported socket type

boards/arm/samv7/common/src/sam_boot_image.c
Header file mpu.h was not included although mpu_control() function was used.
Fix compilation warnings.
CI pass.
=> samv7: include mpu.h in sam_boot_image.c to avoid compilation warnings

drivers/usrsock/usrsock_rpmsg_server.c
req->usockid may not be in a valid range when ret less than zero and not -EAGAIN.
Cortex-M33
=> usrsock_server: fix coverity for recvfrom handle

arch/risc-v/src/mpfs/mpfs_head.S, boards/risc-v/mpfs/icicle/scripts/ld-envm-opensbi.script, boards/risc-v/mpfs/icicle/scripts/ld-envm.script
SiFive document: "ECC Error Handling Guide" states:
"Any SRAM block or cache memory containing ECC functionality needs to be initialized prior to use. ECC will correct defective bits based on memory contents, so if memory is not first initialized to a known state, then ECC will not operate as expected. It is recommended to use a DMA, if available, to write the entire SRAM or cache to zeros prior to enabling ECC reporting. If no DMA is present, use store instructions issued from the processor."
Clean the cache at this early stage so no ECC errors will be flooding later.
If ECC reporting is turned on, it initially reports many pointless errors; for example if that's enabled in Linux. Uninitialized L2LIM area is where the trouble comes from.
L2 ECC reporting enabled, all Polarfire devices …
=> risc-v/mpfs: clear L2 before use

boards/Kconfig, drivers/usbdev/Kconfig, drivers/usbdev/adb.c, drivers/usbdev/cdcacm_desc.c, drivers/usbdev/cdcecm.c, drivers/usbdev/composite_desc.c, drivers/usbdev/pl2303.c, drivers/usbdev/rndis.c, drivers/usbdev/usbmsc.h, drivers/usbdev/usbmsc_desc.c
A usbdev has only one serial string, so use a unique macro to control it.
Delete the configurations for COMPOSITE_BOARD_SERIALSTR, PL2303_BOARD_SERIALSTR, CDCACM_BOARD_SERIALSTR, USBADB_BOARD_SERIALSTR, USBMSC_BOARD_SERIALSTR, and RNDIS_BOARD_SERIALSTR, and use BOARD_USBDEV_SERIALSTR for unification.
For boards that enable board serial string using COMPOSITE_BOARD_SERIALSTR, PL2303_BOARD_SERIALSTR, CDCACM_BOARD_SERIALSTR, USBADB_BOARD_SERIALSTR, USBMSC_BOARD_SERIALSTR, and RNDIS_BOARD_SERIALSTR, they need to be replaced with BOARD_USBDEV_SERIALSTR.
sim:usbdev and bes board
=> usbdev: Use BOARD_USBDEV_SERIALSTR config directly

drivers/sensors/apds9922.c, include/nuttx/sensors/apds9922.h
If both the ambient light sensor AND proximity sensor are enabled (and therefore registered as two independent devices) spinlock is required to ensure I2C bus transactions don't conflict
A simple #warning  has been added to notify the user
None - hopefuly will stop others wasting hours wondering why their app crashes!
Custom board with SAMA5D27C-D1M with 2x apds9922 devices fitted
=> APDS9922 - remove unnecessary spinlock, consolidate i2c read/write and fix incorrect variable declaration and other type errors

boards/arm/rp2040/common/src/rp2040_common_bringup.c, net/local/local_fifo.c
improve the speed and reduce the code size a little bit
code refactor
ci
=> Replace strlen with sizeof for kconfig string

arch/Kconfig, binfmt/elf.c, binfmt/libelf/Kconfig, binfmt/libelf/libelf.h, binfmt/libelf/libelf_load.c, binfmt/libelf/libelf_read.c, binfmt/libelf/libelf_sections.c, binfmt/libelf/libelf_uninit.c, include/nuttx/arch.h, include/nuttx/binfmt/elf.h
1. ELF_LOADTO_LMA
- Load all sections to LMA not VMA, so the startup code(e.g. start.S) need relocate .data section to the final address(VMA) and zero .bss section by self.
- For example, SiFli and Actions: Background: Device with small sram, Bootloader run in sram and psram, need boot to Application, with memory overlap and without XIP. VMA of .data is in "psram" and LMA in "rom", if not enable  `ELF_LOADTO_LMA` , ELF loader will load the section to VMA (will fill bootloader itself). For more details, please see Testing.1
2. ARCH_USE_COPY_SECTION
- This option enables architecture-specific memory copy for dynamic code loading. For example, Ambiq has MRAM regions for instruction which can't load by the memcpy directly.
Disabled by default
1. Enable `ELF_LOADTO_LMA` so that the ELF loader …
=> ELF Loader

arch/arm/src/stm32l4/stm32l4_sdmmc.c
Trying to make SDMMC work on STM32L4R5ZI, stumbled upon inconsistency (this gives warning on compilation).
`
chip/stm32l4_sdmmc.c:2606:40: warning: passing argument 1 of 'nxsem_wait_uninterruptible' from incompatible pointer type [-Wincompatible-pointer-types]
`
chip family: STM32L4, driver: SDMMC, function: stm32_eventwait
board: nucleo-l496zg
board: nucleo-l496zg with SDMMC driver.
Compiles. 
Unable to test execution.
=> fix argument of nxsem_wait_uninterruptible

binfmt/libelf/libelf_sections.c
The program headers are optional. see https://github.com/apache/nuttx/pull/10462
binfmt
boards: sim:elf
- with this patch
```
nsh> /data/data/hello
Hello, World!!
nsh> echo $?
0
```
- without this patch
```
NuttShell (NSH)
MOTD: username=admin password=Administrator
nsh> mount -t hostfs -o fs=. /data
nsh> /data/data/hello
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000055555556cb86 in nxtask_startup (entrypt=0x0, argc=1, argv=0x7ffff3ea3e60) at sched/task_startup.c:70
#2  0x000055555556654c in nxtask_start () at task/task_start.c:134
#3  0x0000555555570ae3 in pre_start () at sim/sim_initialstate.c:52
#4  0x0000000000000000 in ?? ()
```
=> binfmt: The program headers are optional.

drivers/clk/clk_mux.c, include/nuttx/clk/clk_provider.h
since only mux clk use this flag
clk driver
internal test
=> drivers/clk: Change CLK_SET_RATE_NO_REPARENT to CLK_MUX_SET_RATE_NO_REPARENT

drivers/timers/pcf85263.c
Add the missing semicolons
Fix compilation of this external RTC chip driver. Apart from this compilation error, the driver seems to work fine.
Enables using the driver
Tested with the RTC chip connected to a custom mpfs-based HW design running NuttX
=> drivers/timers/pcf85263.c: Fix compilation

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/hardware/mpfs_ihc.h, arch/risc-v/src/mpfs/mpfs_ihc.c, arch/risc-v/src/mpfs/mpfs_ihc_sbi.c, arch/risc-v/src/mpfs/mpfs_opensbi_trap.S, arch/risc-v/src/mpfs/mpfs_opensbi_utils.S
MPFS IHC has a few bugs. If encountered, the RPMSG bus gets stuck. While fixing the issues, better performance is also achieved though rewriting parts of the code.
All MPFS systems using IHC / RPMSG
Overnight testing with SW that utilizes all the RPMSG bandwidth
=> Mpfs IHC bugfixes and perf enhancements

drivers/timers/arch_alarm.c
When the system starts up, the hw count may not start counting from 0, which can cause the processing time of the first oneshot handler to be too long. Therefore, the current tick value should be set based on the hw count during initialization.
oneshot timer
bes board with oneshot timer
=> arch_alarm: change tick to g_current_tick

arch/arm/src/common/Toolchain.defs, arch/risc-v/src/common/Toolchain.defs, arch/xtensa/src/lx6/Toolchain.defs, arch/xtensa/src/lx7/Toolchain.defs, mm/Kconfig
Perform both read/write checks will increase firmware size and reduce performance greatly.
On a real wold project using cortex-m55, disable read checks reduces firmware by 1MB from 8MB.
Performance also improves significantly.
Disable kasan checks may not be a good idea since both read/write error are actual bugs. Only disable one of them when either size overflow or performance are really too slow to be realistic.
No.
Internal project and CI.
=> kasan: add option to disable read/write checks

arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_dsn.c, arch/risc-v/src/mpfs/mpfs_dsn.h, arch/risc-v/src/mpfs/mpfs_ethernet.c
This PR fixes two issues for ethernet support on MPFS
- Fix a possible deadlock
- Fix a case when several devices are connected to a single ethernet switch; generate a valid and unique locally administrated MAC address for every device from the SOC serial number.
Tested on both aries m100pfsevp and several custom devices
=> Mpfs ethernet updates

arch/sim/src/sim/posix/sim_x11framebuffer.c
LeakSanitizer: detected memory leaks in XStringListToTextProperty
Please ignore the XFree ci warning
=> sim/framebuffer: fix memory leak in XStringListToTextProperty

include/nuttx/sched_note.h
fix sched_note declaration inconsistency
=> drivers/note: fix sched_note declaration inconsistency

drivers/syslog/ramlog.c, drivers/syslog/syslog_rpmsg.c
driver/syslog: reset syslog buffer when syslog buffer include invalid data
When the machine is cold started, the psram area where the syslog buffer is located contains some random values, so it will cause loss of valid log.
daily test
=> driver/syslog: reset syslog buffer when syslog buffer include invalid character

libs/libc/stdio/lib_libfread_unlocked.c
Fix a bug the destination buffer is not updated.
It is caused by https://github.com/apache/nuttx/pull/10358.
stdio fread
=> libs/libc: Fix a fatal bug in fread

libs/libc/stdio/lib_fopen.c
libc/fopen: support fopen with mode 'm'
refs:
https://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html This is a fake implementation, in order for fopen to succeed, Because the complete mmap mapping the entire file will waste a lot of memory.
support fopen with m
daily test
=> libc/fopen: support fopen with mode 'm'

include/malloc.h, libs/libc/misc/Make.defs, libs/libc/misc/lib_mallopt.c
libc/mallopt: implement dummy mallopt
refs:
https://man.freebsd.org/cgi/man.cgi?query=malloc&apropos=0&sektion=3&manpath=SunOS+4.1.3&format=html
support dummy mallopt, let compile happy.
daily test.
=> libc/mallopt: implement dummy mallopt

arch/arm/src/samv7/Kconfig, arch/arm/src/samv7/sam_hsmci.c, boards/arm/samv7/common/src/sam_hsmci.c
Some SD card connectors do not have separate card detection pin. In that case card detection has to be done on CD/DAT3 data line. This means software (i.e. architecture level driver) has to take care of pin configuration switching (pin has to be set as data pin in case of transfer and as interrupt card detection pin when there is no action on data line).
This commit adds CD/DAT3 line card detection support for SAMv7 MCU.
New feature for SAMv7 MCU, does not affect other drivers.
Tested on custom SAMv7 board with 112C-TBAR-R02 connector.
=> samv7: add support for SD card detection from CD/DAT3 line

boards/arm64/rk3399/pinephonepro/src/Makefile, boards/arm64/rk3399/pinephonepro/src/pinephonepro_appinit.c, boards/arm64/rk3399/pinephonepro/src/pinephonepro_boardinit.c, boards/arm64/rk3399/pinephonepro/src/pinephonepro_bringup.c, boards/arm64/rk3399/pinephonepro/src/pinephonepro_reset.c
* Add support for board reset this fixes an issue where nsh `reboot` would hang
* Add new board reset file `boards/arm64/rk3399/pinephonepro/src/pinephonepro_reset.c`
* Rename function from `pinephone_bringup` to `pinephonepro_bringup` based on suggestion from @lupyuen 
See below
```txt
Tow-Boot TPL 2022.07
Channel 0: LPDDR4, 50MHz
BW=32 Col=10 Bk=8 CS0 Row=15 CS1 Row=15 CS=2 Die BW=16 Size=2048MB
Channel 1: LPDDR4, 50MHz
BW=32 Col=10 Bk=8 CS0 Row=15 CS1 Row=15 CS=2 Die BW=16 Size=2048MB
256B stride
lpddr4_set_rate: change freq to 400000000 mhz 0, 1
lpddr4_set_rate: change freq to 800000000 mhz 1, 0
Trying to boot from BOOTROM
Returning to boot ROM...
Tow-Boot SPL 2022.07
Trying to boot from SPI
NOTICE:  BL31: v2.6(release):
NOTICE:  BL31: Built : 00:00:00, Jan  1 1980
Tow-Boot 2022.07 …
```
=> Pinephone Pro: Add support for board reset.

drivers/usrsock/usrsock_rpmsg_server.c
nuttx/usrsock: fix rpmsg_usrsock memory leak when stop remote
=> nuttx/usrsock: fix rpmsg_usrsock memory leak when stop remote

crypto/chachapoly.c, crypto/poly1305.c, include/crypto/poly1305.h
apps/crypto/libtomcrypt/libtomcrypt/src/mac/poly1305/poly1305.c:90: multiple definition of `poly1305_init';
nuttx/crypto/poly1305.c:51: first defined here
=> crypto: fix multiple definition of `poly1305_init'

drivers/video/goldfish_camera.c, include/nuttx/sched.h, libs/libc/unistd/lib_vfork.c, sched/sched/sched_waitpid.c
Implement WNOWAIT specified by: https://pubs.opengroup.org/onlinepubs/9699919799/functions/waitid.html
and forward WNOWAIT in vfork instead passing release flag
sim:ostest
=> Fix wait error after vfork

fs/rpmsgfs/rpmsgfs.c
Revert "rpmsgfs: cache statfs result in case of deadlock"
we need to update statfs info when rpmsgfs happend.
This reverts commit 572d8650340550a467d4583eb7d5c2b184eb7475.
fix statfs for rpmsgfs
daily test
=> Revert "rpmsgfs: cache statfs result in case of deadlock"

include/aio.h
if fdcheck enabled, protected fd used to aio_fildes will overflow. Change to int and also follow posix spec:
https://pubs.opengroup.org/onlinepubs/7908799/xsh/aio.h.html
None
LTP aio case with fdcheck enabed
=> aio: change aio_fildes int type

arch/arm/src/armv7-m/arm_cache.c, arch/arm/src/armv8-m/arm_cache.c, arch/arm/src/samv7/sam_emac.c
Implement dcache clean as barrier (DSB + ISB) in write-through mode.
This change fixes the issue when SAMv7 GMAC sometimes does not start packet transmission. The issue is that EMAC_NCR_TSTART is written to EMAC_NCR register while tx descriptor is not delivered to memory.
Improve throughput of SAMv7 Ethernet. Should give positive influence on all devices based on armv7-m and armv8-m
Tested on custom board based on SAMv7. More testing from community is welcomed
=> arch/arm/armv[7|8]-m: implement dcache clean as barrier in write-through mode

tools/parsetrace.py
Remvoe function name filter
Some function names in C++ may fail to parse, and no filtering is required here. (anonymous namespace)::pool::free(void*) [clone .constprop.0]
=> tools/prasetrace: remvoe function name filter

drivers/input/button_upper.c
In the previous PR#10267, there was a problem that fsync would fail if the device node was registered as a BCH, so after revert that patch, the log level was modified to avoid reproducing the same problem (unknown command message in non-block device situations).
=> button_upper.c:Modify log level

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_ethernet.c, drivers/net/Kconfig, drivers/net/Make.defs, drivers/net/ksz9477.c, drivers/net/ksz9477_i2c.c, drivers/net/ksz9477_reg.h, include/nuttx/net/ksz9477.h
This adds an initial management driver for ksz9477 ethernet switch, and takes it into use in mpfs platform.
Implemented so far:
- I2C interface for switch management, basic register read and write functions and related HW errata
- Basic initialization code with chip detection
- Configure the switches' SGMII interface into PHY mode, if the host MAC is connected directly to the SGMII port of the switch
- Taken the initialization into use in mpfs ethernet driver, added configuration flags for MPFS to use instead of a standard MDIO PHY
This allows using ksz9477 switch to be used instead of an ethernet phy, allowing to make a network device with multiple ports
Tested on a custom HW design where Microchip PolarFire SOC is connected via SGMII and I2C to the switch ASIC.
=> Add initial ksz9477 switch support

include/nuttx/mmcsd.h
align with the Linux uapi definition
=> mmc: add timeout fields for mmc_ioc_cmd

drivers/sensors/sensor_rpmsg.c
1. using list_for_every_entry_safe to protect list foreach, avoid removing the entry during the process to cause crash.
2. Back up proxy content in advance to avoid use after free.
fix race condition
daily test
=> drivers/sensors: fix race condition about sensor rpmsg

tools/mkexport.sh
tools/mkexport: copy full library directly if library without path 
copy full library directly if library without path
N/A
ci-check
=> tools/mkexport: copy full library directly if library without path 

drivers/virtio/Kconfig, drivers/virtio/Make.defs, drivers/virtio/virtio-rpmb.c, drivers/virtio/virtio-rpmb.h, drivers/virtio/virtio.c
The RPMB partition cannot be accessed via standard block layer, but by a set of specific commands: WRITE, READ, GET_WRITE_COUNTER, and PROGRAM_KEY. Such a partition provides authenticated and replay protected access, hence suitable as a secure storage.
=> rpmb: add virtio rpmb support

net/inet/inet_sockif.c
Comment information and printing do not match the actual function.
sim:local
=> inet_sendto: correct error messages and remove the comment

net/rpmsg/rpmsg_sockif.c
conn->sendsize is used in rpmsg_socket_ept_cb() and rpmsg_socket_connect_internal(), the connected event may be missed as stated below:
1. in rpmsg_socket_connect_internal(), judge conn->sendsize == 0 and prepare to wait sendsem;
2. interrupt by rptun thread, rpmsg_socket_ept_cb() is called to update conn->sendsize and post the sendsem, but the no one wait rx sem yet, so not post (see rpmsg_socket_post());
3. return to rpmsg_socket_connect_internal() to wait the sendsem, but has miss the connected event.
So add recvlock in rpmsg_socket_connect_internal() also.
rpmsg socket
Tested in BES chip (Cortex-A7 Dual Core and Cortex-M33 Single Core)
=> rpmsg_sockif: add recvlock for conn->sendsize in connect

net/mld/mld_group.c, net/mld/mld_join.c, net/mld/mld_leave.c, net/mld/mld_mcastmac.c, net/mld/mld_report.c, net/mld/mld_send.c
MLD: add byte order conversion for ipv6 address printing
MLD debug
Tested in ESP32C3 chip
=> MLD: add byte order conversion for ipv6 address printing

drivers/sensors/CMakeLists.txt, drivers/sensors/Make.defs
- driver/sensors/: BMI270 fix compilation if sensor works in SPI mode
- cmake: add support for sensors/bmi270
thingy53
=> driver/sensors: BMI270 fix compilation if sensor works in SPI mode

boards/arm/cxd56xx/common/CMakeLists.txt, boards/arm/cxd56xx/common/src/Make.defs, boards/arm/cxd56xx/common/src/cxd56_bmi270_i2c.c, boards/arm/cxd56xx/common/src/cxd56_sensors.c, boards/arm/cxd56xx/spresense/include/board.h, boards/arm/cxd56xx/spresense/include/cxd56_bmi270.h, drivers/sensors/Kconfig, drivers/sensors/bmi270.c
Remove temporary heap allocation and fix memory leak.
Add spresense board-specific driver for bmi270.
bmi270 sensor
=> drivers/sensors: Remove unnecessary heap allocation for bmi270

tools/mkdeps.c
solve XXX string is too long when building in deep path
Allow deeper path of nuttx building  in pc
Pass vela CI
=> tools/mkdeps: increase MAX_BUFFER/MAX_EXPAND/MAX_SHQUOTE to 16384

arch/mips/src/pic32mx/pic32mx_gpio.c
pic32mx: sched_lock should replace with enter_critical_secion
none
=> pic32mx: sched_lock should replace with enter_critical_secion

include/nuttx/page.h
The logic of PAGESIZE and PAGEMASK is related to PAGESHIFT
So extract them as common logical parts
None
None
=> Extract PAGESIZE and PAGEMASK from definitions and seems as common macro

crypto/CMakeLists.txt, crypto/Kconfig, crypto/Makefile
since it's simpler to let linker remove the unused functions from the final image
crypto
ci
=> crypto: Remove CRYPTO_SW_AES and CRYPTO_BLAKE2S

drivers/clk/clk.c, drivers/clk/clk_divider.c
- Solve the risk of dividing by 0 when setting frequency points
- To solve the problem of unordered setting of div & mux, after solving the problem, the frequency will be set to mux first, and then div
clk driver
internal testing
=> Minor clk improvement

include/nuttx/mmcsd.h
align with mmc-utils definition:
https://git.kernel.org/pub/scm/utils/mmc/mmc-utils.git/tree/mmc_cmds.c#n2085
=> mmcsd: Rename mmc_rpmb_frame_s to rpmb_frame

mm/shm/shmget.c
Modification based on opengroup's description for shmget: "When the shared memory segment is created, it shall be initialized with all zero values."
Link to documentation page for shmget: https://pubs.opengroup.org/onlinepubs/9699919799/
XSI shared memory page's values are set to zero when `IPC_CREAT` is specified and the page doesn't already exist.
-
=> mm/shm/shmget: Zero allocated shared memory pages when created.

drivers/mtd/smart.c
fix the compiler error found by https://github.com/apache/nuttx/pull/10543
minor
ci
=> Fix error: mtd/smart.c:2800:12: error: variable 'mincount' set but not used [-Werror,-Wunused-but-set-variable]

fs/vfs/fs_eventfd.c, fs/vfs/fs_signalfd.c, fs/vfs/fs_timerfd.c
fs/vfs: fix dup issue for eventfd/signalfd/timerfd
add refs when called eventfd(), signalfd(), timerfd()
slove crash issue when fd is closed in child task.
daily test
=> fs/vfs: fix dup issue for eventfd/signalfd/timerfd

fs/procfs/fs_procfscritmon.c
found in https://github.com/apache/nuttx-apps/actions/runs/6143676193/job/16667713342?pr=2051
```Makefile
Error: procfs/fs_procfscritmon.c:184:10: error: variable 'remaining' set but not used [-Werror,-Wunused-but-set-variable]
``` 
CI
=> Fix error: procfs/fs_procfscritmon.c CI break

arch/arm/src/samv7/sam_qencoder.c, arch/arm/src/samv7/sam_tc.c
The typo s/.timid/.tcid prevents to compile NuttX with quadrature encoder configured for timer1 (CONFIG_SAMV7_TC1_QE) and s/SAM_TC789_BASE/SAM_TC678_BASE prevented use of the of the timer 2.
The  same70-xplained:netnsh configuration  with CONFIG_SAMV7_TC1_QE and or  CONFIG_SAMV7_TC2 set builds fail.
Build working after the fix. Testing on future hardware planed in the frame of SaMoCoN controller development
https://gitlab.fel.cvut.cz/otrees/motion/work-and-ideas/-/wikis/SaMoCon
=> arch/arm/samv7: fix typos in quadrature encoder and timer drivers

arch/xtensa/src/esp32s3/Kconfig, arch/xtensa/src/esp32s3/esp32s3_config.h, arch/xtensa/src/esp32s3/esp32s3_lowputc.c, arch/xtensa/src/esp32s3/esp32s3_lowputc.h, arch/xtensa/src/esp32s3/esp32s3_serial.c
This commit adds support of RS485 support in ESP32-S3 serial driver
Improve ESP32-S3 driver layer
Tested using ESP32-S3 based board with UART1 connected to UART2 of the same board with MAX486 based TTL to RS485 converter
=> arch/xtensa/esp32s3: add UART RS485 support

arch/arm/src/s32k1xx/hardware/s32k1xx_crc.h
Simple fix of a typo in arch/arm/src/s32k1xx/hardware/s32k1xx_crc.h
CRC_CTRL_TCRC_16BIT was defined twice instead of defining CRC_CTRL_TCRC_32BIT
This file is not included anywhere so it was never caught. It would create a duplicate define if it were to have been included.
I noticed this when including the file in some private code.
Verified correct bit offset in Section "24.3.1.4 CRC Control register (CTRL)" of the S32k1xx reference manual
=> Fixed typo in S32K CRC define

tools/showstack.sh
Add customizable ranking parameters.
None
Enable config:
`CONFIG_STACK_USAGE=y`
Print the top 10 stack usage numbers to the console:
```shell
./nuttx/tools/showstack.sh 10 nuttx
```
=> tools/showstack: add configurable rank parameters

drivers/usbdev/Kconfig, drivers/usbdev/adb.c
This PR is used to support fastboot driver,
The usage of fastboot APP Please refer https://github.com/apache/nuttx-apps/pull/2032 for more details.
Fastboot
BES board enable fastboot
=> usbdev: support usb adb fastboot

drivers/video/Kconfig, drivers/video/goldfish_camera.c
1. priority   = SCHED_PRIORITY_DEFAULT
2. stack_size = DEFAULT_TASK_STACKSIZE
goldfish camera driver
ci
=> drivers/video: Modify the properties of the goldfish camera driver kthread_create

boards/sim/sim/sim/scripts/Make.defs, tools/macar-qcs.sh
`'rcS'` will case files that has duplicate name been replaced. 
so on the Mac platform we use `'q'` instead of `'r'` to achieve an effect similar to '-P'
Fix the ci break reported here:
https://github.com/apache/nuttx/actions/runs/6154533695/job/16700095528?pr=10596
Mac sim-02 ci
=> sim:change Mac sim archive operate from replace to quick insertion

Documentation/guides/customapps.rst
Fix Spelling in guides documentation 3 section.
only documentation. not code.
i think this change not necessary to Test.
=> fix correct spell Cirectory -> directory

Documentation/quickstart/install.rst, README.md, libs/libc/zoneinfo/Makefile, tools/Config.mk
nuttx/build: Restore ARLOCK to improve compile speed in incremental case
To solve the issue of carrying object files from previous builds, Matias changed the archiving process to re-archive libapps.a on every compilation, if libapps.a carries more object files, incremental compilation will waste too many time in re-archiving, compared with the previous implement, this is a degradation of the build system.  Referring to mature engineering projects such as cmake, if there is configuration or source file changed, the best solution should be to reconfigure the environment.
Revert this PR to ensure the compilation speed during incremental compilation.
https://github.com/apache/nuttx/pull/1765
```
|  commit 34b34e2d4519956f9a61f5985aca29947c4b8b23 (tag: nuttx-20200914-172150)
|  Author: Matias …
```
=> nuttx/build: Restore ARLOCK to improve compile speed in incremental case

include/nuttx/queue.h
Split a single queue to two separate queues at node p.
None
```C
#define FAR 
#define NULL ((void *)0)
#include <stdio.h>
#include "queue.h"
struct node {
struct dq_entry_s *flink;
struct dq_entry_s *blink;
int val;
};
typedef struct node node_t;
void node_init(node_t *a, int val)
{
a->flink = NULL;
a->blink = NULL;
a->val = val;
}
int main(){
dq_queue_t q1, q2;
dq_init(&q1);
dq_init(&q2);
node_t a ,b,c,d;
node_init(&a, 1);
node_init(&b, 2);
node_init(&c, 3);
node_init(&d, 4);
dq_addlast(&a, &q1);
dq_addlast(&b, &q1);
dq_addlast(&c, &q1);
dq_addlast(&d, &q1);
// three testcases
// dq_split(dq_next(dq_peek(&q1)), &q1, &q2);
// dq_split(dq_peek(&q1), &q1, &q2);
// dq_split(dq_tail(&q1), &q1, &q2);
printf("q1:");
node_t *curr = q1.head;
while(curr){
printf("%d ", curr->val);
curr = …
```
=> Split a single queue to two separate queues at node p.

mm/mm_heap/mm.h, mm/mm_heap/mm_addfreechunk.c, mm/mm_heap/mm_brkaddr.c, mm/mm_heap/mm_checkcorruption.c, mm/mm_heap/mm_extend.c, mm/mm_heap/mm_foreach.c, mm/mm_heap/mm_free.c, mm/mm_heap/mm_initialize.c, mm/mm_heap/mm_mallinfo.c, mm/mm_heap/mm_malloc.c, mm/mm_heap/mm_malloc_size.c, mm/mm_heap/mm_memalign.c, mm/mm_heap/mm_memdump.c, mm/mm_heap/mm_realloc.c, mm/mm_heap/mm_shrinkchunk.c
Add macros to check if node/pre-node is alloced/free or not. Which is commonly used across mm/mm_heap.
Adjust macros to make sure it's started with `MM_` prefix.
Rename and code tidy-up only.
Internal CI and project testing.
=> Add helper macros in mm.h

arch/sim/Kconfig, arch/sim/src/sim/posix/sim_x11framebuffer.c, arch/sim/src/sim/sim_framebuffer.c, arch/sim/src/sim/sim_internal.h, arch/sim/src/sim/sim_lcd.c, drivers/video/Kconfig, drivers/video/fb.c, drivers/video/goldfish_fb.c, include/nuttx/video/fb.h
Refactor vsync queue and adapt to sim and goldfish modules.
In the new mechanism, the vendor driver does not need to create its own queue management mechanism. it is uniformly handled by the upper layer .
It also supports multiple file opening and polling for fb poll, such as polling for primary fb and overlay at the same time.
=> fb: add vsync queue mechanism

drivers/usrsock/usrsock_rpmsg_server.c
`tcp_poll_eventhandler` have logic after `poll_notify`, if we teardown poll inside poll callback without clearing revents, use-after-free will happen.
Minor, usrsock
Manually
=> usrsock_rpmsg_server: Clear revents for POLLHUP and POLLERR

sched/wqueue/kwork_inherit.c
aio client will queue asynchronous io requests to the worker threads. if PRIORITY_INHERITANCE is enabled, client thread's priority will be set to worker threads. There will be multi-boost/restore of worker threads' priority and assert the system.
No need priority multi-boot/restore to worker thread because client thread's priority is alway the same.
None
LTP aio case with CONFIG_PRIORITY_INHERITANCE=y and pass CI
=> sched: do not DEBUGASSERT for priority multi-boost

arch/arm/include/syscall.h, arch/arm/src/armv7-a/CMakeLists.txt, arch/arm/src/armv7-a/Make.defs, arch/arm/src/armv7-a/arm_cpu_psci.c, arch/arm/src/armv7-a/arm_cpu_psci.h, arch/arm/src/armv7-a/arm_smccc.S, arch/arm/src/common/CMakeLists.txt, arch/arm/src/common/Make.defs
include/arch/syscall.h: Assembler messages:
include/arch/syscall.h:133: Error: bad instruction `struct arm_smccc_res'
include/arch/syscall.h:134: Error: junk at end of line, first unrecognized character is `{'
include/arch/syscall.h:135: Error: bad instruction `unsigned long a0'
include/arch/syscall.h:136: Error: bad instruction `unsigned long a1'
include/arch/syscall.h:137: Error: bad instruction `unsigned long a2'
include/arch/syscall.h:138: Error: bad instruction `unsigned long a3'
include/arch/syscall.h:139: Error: bad instruction `unsigned long a4'
include/arch/syscall.h:140: Error: bad instruction `unsigned long a5'
include/arch/syscall.h:141: Error: bad instruction `unsigned long a6'
include/arch/syscall.h:142: Error: bad instruction `unsigned long a7'
include/arch/syscall.h:143: …
=> arm/psci: Fixed arm psci related compilation errors

libs/libc/stdio/lib_libfread_unlocked.c
If the gulp size in the stdio buffer is greater than the remaining user buffer size it will:
- Corrupt memory in dest (user memory) and
- Keep corrupting KERNEL memory via the stdio character buffer until the whole system crashes, as the 'remaining' count underflows
This patch fixes this behavior.
Fix fatal memory leak bug in lib_libfread
Read from file fails without this patch, works with it
=> stdio/lib_libfread: Fix buffer overflow issue

net/tcp/tcp_netpoll.c
Normally, `SO_ERROR` for disconn events will be set by `tcp_poll_eventhandler`, but when the socket is closed before poll, we should also set the `SO_ERROR`.
On Linux, `tcp_poll` returns `EPOLLERR` event when `sk->sk_err` has value but doesn't let `poll` fail (doesn't set `errno`). https://github.com/torvalds/linux/blob/v6.5/net/ipv4/tcp.c#L594-L596
Note: `sk->sk_err` can be get by socket option `SO_ERROR` on Linux, so `POLLERR` will always be together with `SO_ERROR`.
Common libs like curl may try to read `SO_ERROR` on `POLLERR`.
`tcp_pollsetup` and `SO_ERROR` only
Manually.
=> net/tcp: Set SO_ERROR for poll error in setup

Documentation/quickstart/configuring.rst, tools/configure.sh, tools/merge_config.py, tools/process_config.sh
I've added two scripts that can reference the config snippets in different ways
1. process_config allows the use of #include statements in defcnfig, which can reference other config files
2. merge_config supports merging multiple config files into one
./tools/merge_config.py -o defconfig .config1 .config2
=> Support defconfig merge

tools/Config.mk
Remove temporary archive lock file (xxx.a.lock) by make distclean
because the file may be generated by archive with flock command.
None
=> tools: Remove archive lock file in make distclean

net/devif/devif_callback.c
The previous logic will caused some tcp flow errors.
Cortex-M55
=> devif_callback: modify the code logic to conform to the comment

net/tcp/tcp_send_buffered.c
with nonblocking sockets, POLLOUT is returned when the application calls poll even if the send buffer is full
Cortex-M55
=> psock_tcp_cansend: return EWOULDBLOCK when send buffer is full

binfmt/CMakeLists.txt, binfmt/Makefile, binfmt/binfmt_exec.c, binfmt/binfmt_execmodule.c, include/nuttx/binfmt/binfmt.h
There is a problem when vfork() calls execv() (or execl()) to start a new application:  When the parent thread calls vfork() it receives and gets the pid of the vforked task, and *not*  the pid of the desired execv'ed application.
see  issue #3334
exec series funciton
sim
=> Exec: Support run exec in current task

net/tcp/tcp_conn.c
We may just free some TCP connections before monitor stopped, e.g. sacrificie a TCP conn in `tcp_alloc` will just call `tcp_free` and reuse the connection.  But we noticed that the TCP monitor is not released in `tcp_free` because it is mounted on `conn->connevents` instead of `conn->sconn.list` while `tcp_free` only release the latter.
`tcp_free` only.
Note: `tcp_stop_monitor` can be called multiple times without problem.
Manually
=> net/tcp: Stop monitor in `tcp_free`

arch/xtensa/src/esp32s3/esp32s3_psram_octal.c, arch/xtensa/src/esp32s3/esp32s3_psram_quad.c, arch/xtensa/src/esp32s3/esp32s3_spi_timing.c, arch/xtensa/src/esp32s3/esp32s3_spi_timing.h, arch/xtensa/src/esp32s3/esp32s3_spiflash_mtd.c, arch/xtensa/src/esp32s3/esp32s3_start.c, arch/xtensa/src/esp32s3/rom/esp32s3_spiflash.h
xtensa/esp32s3: SPI support psram and flash timing tuning
- Supports SPIRAM 80MHz clock speed
- config:
`./tools/configure.sh esp32s3-devkit:psram_octal`
Configure SPIRAM clock speed via `make menuconfig `
```
System Type  --->
SPI RAM Configuration  --->
Set RAM clock speed (40MHz clock speed)  ---> 
()  40MHz clock speed
(X) 80MHz clock speed
```
=> xtensa/esp32s3: SPI support psram and flash timing tuning

drivers/usbdev/composite.c, drivers/usbdev/composite.h, drivers/usbdev/composite_desc.c
Fix build error and warning when enable BOARD_USBDEV_SERIALSTR.
drivers/usbdev
on Spresense board.
=> usbdev: Fix build error with BOARD_USBDEV_SERIALSTR

libs/libc/libc.h
Provide the chip vendor the customized String operation approach under flat build mode.
Test under sf32lb5xx chip under flat mode with chip define memcpy.
=> Provide flat mode the chip string customization.

arch/xtensa/src/esp32s3/esp32s3_psram_octal.c, boards/xtensa/esp32s3/common/scripts/legacy_sections.ld
xtensa/esp32s3: Fix octal lines mode SPIRAM blocking issue
During  octal lines mode SPIRAM initialization, SPI flash operation may cause the system blocking, this issue can be fixed using this PR
`./tools/configure.sh esp32s3-devkit:psram_octal`
=> xtensa/esp32s3: Fix octal lines mode SPIRAM blocking issue

libs/libc/machine/Kconfig
simplify the option setting if the chip doesn't hardware limitation on user or kernel mode.
new option
ci
=> lib/machine: Add LIBC_PREVENT_xxx which select LIBC_PREVENT_XXX_[KERNEL|USER] automatically

drivers/lcd/Kconfig, drivers/lcd/memlcd.c
LVGL uses Byte-Per-Pixel Memory model for monochromatic displays. This option enables memlcd driver to be used with LVGL.
memlcd driver
LVGL with Sharp MEMLCD.
=> Adding Byte-Per-Pixel Memory model option to memlcd

drivers/lcd/lcd_dev.c
When using monochromatic LCD (Sharp MEMLCD) with LVGL, planeinfo.bpp is set to 1, thus calculating row_size gives 0, instead of actual row size.
lcd_dev driver
With LVGL and lcd_dev support on Sharp memlcd driver.
=> Fixing row_size calculation when bpp is equal 1 in lcd_dev driver

boards/sim/sim/sim/src/sim_bringup.c, drivers/usbdev/Kconfig, drivers/usbdev/Make.defs, drivers/usbdev/mtp.c, include/nuttx/usb/mtp.h
usbdev/mtp: support mtp class driver
support media transfer protocol (MTP) class driver
daily test
=> usbdev/mtp: support media transfer protocol (MTP) class driver

binfmt/binfmt_execmodule.c
The 'filename' parameter comes from user space and cannot be accessed after calling ret = addrenv_select(binp->addrenv, &binp->oldenv); as it changes the address environment and 'filename' points to who knows where. In this case, calling nxtask_init(filename...) will cause a crash.
Solve this by making a local copy before changing address environment IF argv = NULL. Why ? Because argv[0] contains the process name in this case and the argument vector is already copied into kernel memory, thus passing argv[0] to nxtask_init(argv[0]...) is safe.
Fix system crash when user creates a process with argv = NULL
CONFIG_BUILD_KERNEL=y
=> binfmt/binfmt_execmodule: Copy filename if CONFIG_BUILD_KERNEL and argv=NULL

include/nuttx/net/dns.h, libs/libc/netdb/CMakeLists.txt, libs/libc/netdb/Make.defs, libs/libc/netdb/lib_dns.h, libs/libc/netdb/lib_dnsquery.c, libs/libc/netdb/lib_dnsqueryfamily.c
Corresponds to the problem of name resolution with different IP address types in networks where only one of IPv4 or IPv6 can be used due to physical layer reasons (e.g., LTE networks).
DNS client.
=> libs:netdb: Restrict DNS query types

arch/risc-v/src/esp32c6/hardware/esp32c6_soc.h
Fix compilation of esp32c6 serial driver that was broken in c56aa7b527ddd4617950a03259f01859ad86af52
Bugfix
Pass RISC-V CI
=> arch/risc-v/esp32c6: fix compilation of esp32c6 serial driver

libs/libxx/Kconfig
libxx/libcxx: select PTHREAD_MUTEX_TYPES to support recursive mutex
fix recursive mutex issue for c++
local test
=> libxx/libcxx: select PTHREAD_MUTEX_TYPES to support recursive mutex

libs/libm/libmcs/Make.defs
Fix warnings:
```
1 warning generated.
CC:  libmcs/libmcs/libm/mathd/lrintd.c libmcs/libmcs/libm/mathd/lrintd.c:141:20: warning: implicit conversion from 'unsigned long long' to 'long' changes value from 9223372036854775808 to 0 [-Wconstant-conversion]             return __MIN_LONG;
            ~~~~~~ ^~~~~~~~~~
/mnt/yang/vela_keystore_sim/nuttx/libs/libm/libmcs/libmcs/libm/include/internal_config.h:50:24: note: expanded from macro '__MIN_LONG'     #define __MIN_LONG 0x8000000000000000L
                       ^~~~~~~~~~~~~~~~~~~
libmcs/libmcs/libm/mathd/lrintd.c:144:20: warning: implicit conversion from 'long long' to 'long' changes value from 9223372036854775807 to -1 [-Wconstant-conversion]             return __MAX_LONG;
            ~~~~~~ ^~~~~~~~~~ …
```
=> libm/libmcs: Fix clang build libmcs warning

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_dma_alloc.c, arch/risc-v/src/mpfs/mpfs_dma_alloc.h
The MPFS eMMC DMA has some requirements that are only fulfilled by enabling separate DMA access buffers (FAT DMA buffers) and by forcing indirect access to the media via FAT_FORCE_INDIRECT.
Why? Direct access to user buffers violates two things:
- Buffer alignment is not ensured
- Buffers are user memory (problematic in BUILD_KERNEL)
Fix DMA access with MPFS eMMC
mpfs
=> risc-v/mpfs: Add DMA buffer allocator for eMMC access

arch/sim/src/sim/posix/sim_alsa.c
sim/sim_alsa: reset alsa pcm device when snd_pcm_avail < 0
Xiaomi vela simulator 
Xiaomi Vela
=> sim/sim_alsa: reset alsa pcm device when snd_pcm_avail < 0

arch/risc-v/src/common/Toolchain.defs, tools/ci/docker/linux/Dockerfile
Try to upgrade toolchain for risc-v.
New feature introduced, e.g. KASAN works on risc-v with the new toolchain now.
New toolchain. docker image of CI need to update.
rv-virt:nsh
=> tools: Use GCC 13.2 from xPack for risc-v

libs/libxx/libcxx.defs
fix CI compilation issue reported on MACOS
Improve CI until `libcxx` is not upgraded
Pass CI
=> libs/libxx/libcxx: fix CI compilation issue reported on MACOS

libs/libc/locale/lib_iconv.c
Fixed a situation that would cause the fetched value to be out of range of the array in some cases.
Please ignore the follow nxstyle warning since the implementation require the special inclusion sequence:
```
Warning: /home/runner/work/nuttx/nuttx/nuttx/libs/libc/locale/lib_iconv.c:110:3: warning: #include outside of 'Included Files' section
```
None
None
=> lib_iconv.c:Fix possible out-of-bounds reads

sched/timer/timer_getoverrun.c
modify the default errno from ENOSYS to EINVAL can pass the ltp case: ltp_timer_getoverrun_speculative_6_1,
ltp_timer_getoverrun_speculative_6_2, ltp_timer_getoverrun_speculative_6_3
=> timer/timer_getoverrun: adjust the default errno from ENOSYS to EINVAL

tools/gdb/thread.py
fix typo
n/a
```
gdb -ix tools/gdb/__init__.py
```
=> gdb/thread.py: fix typo

arch/arm64/src/Toolchain.defs
add mcpu option for all Cortex CPU, from Spec of gcc
https://gcc.gnu.org/onlinedocs/gcc-12.3.0/gcc/AArch64-Options.html
None
testing with ostest for every option
=> arm64: add mcpu option for all Cortex CPU

net/tcp/tcp_timer.c
use after free when the number of retransmissions reached the maximum.
Cortex-M55
=> tcp: fix coverity warning for tcp_timer

arch/arm64/src/Toolchain.defs
when using new gcc verion like:
GNU ld (Arm GNU Toolchain 12.2.Rel1 (Build arm-12.24)) 2.39.0.20221210)
we will get link warning like:
aarch64-none-elf-ld: warning: XXX/nuttx has a LOAD segment with RWX permissions
The patch fix the warning through add link option --no-warn-rwx-segments
None
Testing with compile
=> arch/arm64: fix link RWX warning for NuttX arm64

drivers/drivers_initialize.c, drivers/serial/Kconfig, drivers/serial/Make.defs, drivers/serial/serial_dma.c, drivers/serial/uart_ram.c, include/nuttx/serial/uart_ram.h
add ram uart driver
It uses the memory block as the serial communication medium, which can communicate between different processes or different CPUs
Using the following configuration, the cross-core communication rate of 200MHz cortex-M55 is about 461KB/s
RAM_UART_BUFSIZE=1024
RAM_UART_POLLING_INTERVAL=100
new serial driver
ci
=> Add ram uart driver

drivers/power/supply/regulator_rpmsg.c
1.Change priv to client or server
2.Allocate memory for name in regulator_rpmsg_get
3.Lock/unlock regulator_list in regulator_rpmsg_server_s
regulator rpmsg
internal
=> supply/regulator: Refine rpmsg regulator

drivers/sensors/Kconfig
since the driver doesn't depend on userspace library(uORB) at all.
=> drivers/sensor: Remove the selection of UORB from Kconfig

sched/wdog/wd_start.c
In the 'wd_timer',the callback function executed by 'wd_expiration' could call wd_start,and g_wdtickbase might be updated.Subsequently, g_wdtickbase is incremented by the value of ticks, causing g_wdtickbase to be greater than the actual passage of time.
wdog
internal device
=> sched/wdog:change g_wdtickbase update situation.

tools/ci/docker/linux/Dockerfile
GCC13 have compatibility issue with libcxx (need libcxx 17+, which is not released yet).
Please refer to: https://github.com/llvm/llvm-project/issues/62396
Linux CI
esp32c3-devkit:cxx
=> tools: Switch riscv GCC to 12.3

include/nuttx/wqueue.h, sched/signal/sig_notification.c, sched/wqueue/kwork_cancel.c, sched/wqueue/kwork_thread.c, sched/wqueue/wqueue.h
wqueue: add work_cancel_sync() support
signal: use work_cancel_sync() to fix used after free
user thread:                             hpwork:
timer_create() with SIGEV_THREAD
timer_settime()
irq -> work_queue()                  add nxsig_notification_worker to Q
timer_delete()
nxsig_cancel_notification()
call nxsig_notification_worker()
work_cancel()
timer_free()
nxsig_notification_worker() used after free
root cause:
work_cancel() can't cancel work completely, the worker may alreay be running.
resolve:
use work_cancel_sync() API to cancel the work completely
work queue
BES board & SIM
=> signal: use work_cancel_sync() to fix used after free

include/nuttx/arch.h, sched/clock/clock_systime_ticks.c
Initialize tick to zero so the value returned is also reasonable even if failed to get current tick.
None
Internal CI and project
=> sched: return 0 from clock_systime_ticks if failed

tools/ci/cibuild.sh
Follow https://github.com/apache/nuttx/pull/10699
CI
CI
=> cibuild.sh: Using GCC from xPack for riscv

drivers/video/goldfish_camera.c
When the upper layer calls goldfish_camera_data_uninit, priv->capture_cb=NULL, but when there is data transmission in goldfish_camera_thread, priv->capture_cb will be called, which will cause a crash.
goldfish camera
inertnal test
=> drivers/video: Fix crash caused by priv->capture_cb = null

arch/xtensa/src/esp32s3/esp32s3_qspi.c, arch/xtensa/src/esp32s3/esp32s3_spi_slave.c
Fix below build error when enable `SPI_SLAVE` and `ESP32S3_SPI_DMA` or enable `ESP32S3_SPI_IO_QIO`
```
CC:  chip/esp32s3_spi_slave.c In file included from /home/u0228848401/workdir/contribution/royfengsss/nuttx/include/syslog.h:33,
from /home/u0228848401/workdir/contribution/royfengsss/nuttx/include/debug.h:41,
from chip/esp32s3_spi_slave.c:30:
chip/esp32s3_spi_slave.c: In function 'spislave_setup_rx_dma':
chip/esp32s3_spi_slave.c:907:21: error: expected expression before '_Bool'
false);
^~~~~
chip/esp32s3_spi_slave.c:906:21: error: called object 'length' is not a function or function pointer
length
^~~~~~
chip/esp32s3_spi_slave.c:901:12: note: declared here
uint32_t length = SPI_SLAVE_BUFSIZE - priv->rx_length;
^~~~~~
In file included from …
```
=> esp32s3: fix build error

tools/minidumpserver.py
minidump server doesn't stop while gdb client is stopping now
=> tools/minidumpserver: don't stop while gdb client is stopping

arch/sim/src/sim/sim_head.c, arch/sim/src/sim/sim_rptun.c, drivers/rptun/rptun.c, include/nuttx/rptun/rptun.h, openamp/0001-libmetal-add-metal_list_for_each_safe-support.patch, openamp/libmetal.cmake, openamp/libmetal.defs
rptun: add remote poweroff support
can use RPTUNIOC_STOP and RPTUNIOC_START causes remote powerdown or re powerup
=> add remote poweroff support

libs/libc/pthread/pthread_cleanup.c
Since TLS is only used within a single thread and requires no additional protection. https://github.com/apache/nuttx/issues/1137
=> pthread_cleanup: rm sched_[un]lock

include/nuttx/sched_note.h, libs/libc/gdbstub/lib_gdbstub.c
libs/libc: currect usage of getpid/gettid in library
N/A
ci-check
=> libs/libc: currect usage of getpid/gettid in library 

drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.c
The scan information will contain the channel information.
Cortex-M55 and bcm43xxx chipset
=> wifi: parse channel from IE when ctl_ch is 0

net/tcp/tcp_input.c
The previous iob_trimhead added dev->iob->io_offset, so if the input frame is not merged into the ofo segment, we need to reset dev->iob->io_offset so that the subsequent tcp_send can properly assemble packets.
Cortex-M55
=> tcp_ofosegs: prepare iob to reset io_offset

mm/iob/Kconfig
rndis header length is 36, L2 header is 14, IPv6 header is 40, tcp header is 56 when sack option count is 4(default max_ofosegs is 4). so the iob bufsize should greater than we need.
Cortex-M55
=> iob: limit the iob bufsize is sufficient to fill all L2/L3/L4 headers

arch/arm/src/cxd56xx/cxd56_rtc.c
Return EBUSY error for alarm setting before completion of RTC initialization.
=> arch: cxd56xx: Return error for RTC alarm setting before initialization

libs/libc/dlfcn/lib_dlopen.c, libs/libc/modlib/modlib_init.c, libs/libc/modlib/modlib_load.c, libs/libc/modlib/modlib_loadhdrs.c, libs/libc/modlib/modlib_read.c, libs/libc/modlib/modlib_uninit.c
1. libs/modlib: close fd when error happen
2. libs/modlib: avoid seeking in each reading
3. libs/modlib: avoid double free when call modlib_unload with erro
4. libc/mod: fix minor issue about description
daily  test
=> libc/modlib: fix minor issue about modlib

arch/risc-v/src/espressif/esp_libc_stubs.c, arch/risc-v/src/rv32m1/rv32m1_irq.c, boards/risc-v/c906/smartl-c906/scripts/Make.defs, boards/risc-v/k210/maix-bit/scripts/Make.defs, boards/risc-v/mpfs/icicle/scripts/Make.defs
Fix:
```
riscv-none-elf-ld: sotest.o: ABI is incompatible with that of the selected emulation:
target emulation `elf64-littleriscv' does not match `elf32-littleriscv'
riscv-none-elf-ld: failed to merge target specific data of file sotest.o
```
c906 only
CI
=> Fix CI failure on RISC-V

Documentation/platforms/arm/samv7/index.rst, arch/arm/src/samv7/Kconfig, arch/arm/src/samv7/Make.defs, arch/arm/src/samv7/sam_1wire.c, arch/arm/src/samv7/sam_1wire.h, arch/arm/src/samv7/sam_serial.c
SAMv7 does not have dedicated 1 wire driver but this can be emulated with UART/USART peripheral and some external HW (TX/RX connection etc). This adds support for 1 wire on SAMv7.
New SAMv7 driver.
Tested on SAMv7 MCU and DS2401 one wire device.
=> samv7: add support for 1 wire over UART/USART

drivers/net/rpmsgdrv.c
net_rpmsg_drv_init() bypass return value of netdev_register(). This should be taken into account.
net_rpmsg_drv_init() returns negated errno in case of netdev_register() failure.
Custom MPFS board
=> drivers/net/rpmsgdrv.c: Take netdev_register() return value into account

boards/sim/sim/sim/scripts/Make.defs, include/elf64.h, include/nuttx/lib/modlib.h, libs/libc/dlfcn/lib_dlclose.c, libs/libc/dlfcn/lib_dlopen.c, libs/libc/modlib/modlib_bind.c, libs/libc/modlib/modlib_globals.S, libs/libc/modlib/modlib_load.c, libs/libc/modlib/modlib_unload.c, sched/module/mod_insmod.c, sched/module/mod_rmmod.c, tools/build-globals.sh
* build-globals.sh
- Only look in the nuttx for external symbols used when loading dynamic shared objects
* include/elf64.h
- Correct the type of fields in the Elf64_Phdr structure
* libs/libc/dlfcn/lib_dlclose.c
- Distinguish between ET_DYN and other objects as the former has both text and data in a single allocation to reserve GOT offsets
* libs/libc/dlfcn/lib_dlopen.c
- Code formatting
* libs/libc/modlib/modlib_bind.c
- Distinguish between relocation entry sizes by section type
- Handle RELA style relocations
* libs/libc/modlib/modlib_globals.S
- Formatting fixes
- Symbols should not be weak - they exist or they don't
* include/nuttx/lib/modlib.h
- Add an inidcator to module_s to distinguish between ET_DYN and other
* libs/libc/modlib/modlib_load.c
- ET_DYN objects need to keep the …
=> Fix loading of ET_DYN type of shared objects

include/nuttx/net/ioctl.h, net/socket/net_sockif.c, net/socket/socket.c, net/tcp/Kconfig, net/udp/Kconfig, net/usrsock/Kconfig
Applications can prohibit Socket for INET by UsrSock by using the
ioctl command of SIOCDENYINETSOCK.
In this modification, we have added an interface to UsrSock that
queries whether or not the creation of Socket for INET is
prohibited.
This allows an application to choose which to use when both
UsrSock and, for example, rndis stacks are enabled.
UsrSock daemons
Spresense + wifi
=> net: Add new interface to tell usrsock available

arch/risc-v/src/common/riscv_pmp.c
PMPCFG_A_TOR region may have zero size. The pmp configuration currently fails for zero-sized TOR. This patch bypasses such a restriction.
Also replace log2ceil with LOG2_CEIL from lib/math32.h.
All risc-v TOR implementations are broken.
Risc-v TOR implentations
Polarfire soc
=> riscv/riscv_pmp.c: fix broken TOR checks

drivers/sensors/sensor.c
Solve the problem that when a user modifies the sampling rate, the difference between the generation and the mainline generation may be greater than the own sampling interval.
After this problem occurs, sensor_is_update() will continue to return true, resulting in a busy loop in the upper-layer application, so, need update user generation according to mainline generation.
fix bug
daily test
=> driver/sensor: Solve the busy loop problem caused by sampling problems

arch/arm/src/sama5/sam_pwm.c
Found a few old style ~08x type printf formatting issues causing compiler warnings
None
Compiles without warnings. Enabled pwm debug info and verified that the messages display correctly.
=> Fix historic %08x style printf format warnings

tools/gdb/memdump.py
Should always output the wrap line
gdb memdump
Local project with gdb memdump command
=> tools/gdb/memdump.py: fix the wrap line output indentation

drivers/wireless/ieee80211/bcm43xxx/bcmf_ioctl.h
These structures need to be aligned with the firmware, packed_struct will cause the scan information from Wi-Fi firmware  not to be parsed by broadcom Wi-Fi driver. Therefore, we need to remove the packed_struct of the structure associated with the scan information.
Cortex-M55 and bcm43xxx chipset
=> bcm_driver: revert packed attribute for scan structure

drivers/modem/alt1250/altcom_cmd.h
Fix bug that modem version could not be taken.
Only alt1250 driver
Test with spresense LTE board.
=> drivers/modem/alt1250: Fix bug that modem version could not be taken

drivers/modem/alt1250/altcom_hdlr_other.c
Fix bug that errno was not converted correctly.
Only alt1250 driver.
test with Spresense LTE board.
=> drivers/modem/alt1250: Fix bug that errno was not converted correctly

Kconfig, arch/arm/src/nrf53/nrf53_ipc.c, arch/arm/src/nrf53/nrf53_rptun.c, arch/arm/src/stm32h7/stm32_hsem.c, arch/arm/src/stm32h7/stm32_rptun.c, include/debug.h
debug: add support for IPC (interprocessor communication) debug messages
I'm not sure if IPC is a good name since this name is used for various things (inter-process communication, inter-processor communication, inter-partition communication and probably more). If anyone has a better idea for a name, I can change it.
CI
=> debug: add support for IPC (interprocessor communication) debug messages

drivers/power/supply/regulator.c, drivers/power/supply/regulator_rpmsg.c
1.fix regulator_register check rpmsg regulator which leads to recursion.
2.client get the regualtor which is enabled by server, will disable the regualtor.
3.regulator_rpmsg_server_unbind will disable regualtor which maybe used by other client.
4.regulator_rpmsg_server_unbind will be deadloop when the regulator is always_on;
5.regulator_rpmsg_client_destroy does not match server cpu name,may destory by stop other rptun dev
self test
=> Regulator:fix some issues about rpmsg regualtor

sched/clock/clock_gettime.c
Adding a judgment in the code that null return values are not referenced for dereference
Collecting CPU time of processes and threads through interfaces , and the verification of this function requires the activation of CONFIG_ SCHED_ CRITMONITOR switch
Open CONFIG_ SCHED_ CRITMONITOR , in hello_main Adding a Clock to the  Test Program Method calls corresponding to gettime to obtain the CPUtime of threads and processes
Test Code
```
{
struct timespec myts;
myts.tv_sec = 0;
myts.tv_nsec = 0;
if ((clock_gettime(CLOCK_THREAD_CPUTIME_ID, &myts)) < 0) {
perror("clock_gettime: CLOCK_THREAD_CPUTIME_ID: ");
exit(1);
}
else {
syslog(LOG_INFO,"clock_gettime succ type CLOCK_THREAD_CPUTIME_ID myts.tv_sec is [%d]",myts.tv_sec);
syslog(LOG_INFO,"clock_gettime succ …
```
=> sched/clock Add special handling for TCB null pointer cases

drivers/clk/clk.c, drivers/clk/clk_mux.c, drivers/clk/clk_rpmsg.c, include/nuttx/clk/clk_provider.h
1.check the rpmsg name when clk_register.
2.clk_get rpmsg clk print error:
clk/clk.c:1231:3: runtime error: null pointer passed as argument 2, which is declared to never be null 
3.fix some function miss keyword FAR.
4.clk_disable_unused may disable rpmsg clk which disable the clk that maybe used by others
rpmsg clk
self test
=> clk:fix some issues when use rpmsg clk

libs/libc/machine/arm/armv8-m/Kconfig, libs/libc/machine/arm/armv8-m/Make.defs, libs/libc/machine/arm/armv8-m/gnu/arch_strcpy.S
Assembly version of strcpy for armv8m.
Replace common strcpy if CONFIG_ARMV8M_STRCPY is enabled.
tested using a testcase designed for arch libc function, see https://github.com/apache/nuttx-apps/pull/1662
Also tested on Cortex-m33:
native C:
strcpy total(run 25 times) cpu cycles 8400
strcpy average cpu cycles 336
assembly:
strcpy total(run 25 times) cpu cycles 5750
strcpy average cpu cycles 230
=> armv8m/strcpy: add arch optimize version

arch/arm/src/cxd56xx/cxd56_gnss.c, arch/arm/src/lc823450/lc823450_ipl2.c, arch/arm/src/rtl8720c/ameba_hci.c, binfmt/libelf/libelf_init.c, binfmt/libnxflat/libnxflat_init.c, drivers/bch/bchdev_unregister.c, drivers/loop/losetup.c, drivers/mtd/filemtd.c, drivers/mtd/mtd_config.c, drivers/mtd/mtd_config_fs.c, drivers/net/slip.c, drivers/rptun/rptun.c, drivers/sensors/fakesensor_uorb.c, drivers/sensors/goldfish_gps_uorb.c, drivers/sensors/sensor_rpmsg.c, drivers/sensors/wtgahrs2_uorb.c, drivers/serial/ptmx.c, drivers/serial/pty.c, drivers/syslog/syslog_filechannel.c, drivers/video/goldfish_camera.c, drivers/wireless/bluetooth/bt_uart_shim.c, drivers/wireless/ieee80211/bcm43xxx/bcmf_core.c, drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.c, net/local/local_fifo.c, net/utils/net_snoop.c
to avoid the child process inherent file handle accidently.
=> enable O_CLOEXEC explicit

arch/arm/src/at32/at32f43xx_flash.c
According to the data sheet, the flash address to be erased is the flash base address plus the current sector offset address, but only the current sector offset address is written, so the flash base address needs to be added
=> Fix onchip flash erase fail

arch/sim/src/sim/posix/sim_hostmemory.c, arch/sim/src/sim/sim_internal.h, arch/sim/src/sim/sim_rptun.c
if not unlink shm, the shared memory object still exists in host /dev/shm after quit
if nuttx is started with administrator privileges, or if it is restarted with user
privileges, there will be a problem with the permission to open this shm file
sim_rptun
sim:rproxy and sim:rpserver
=> sim_rptun: unlink shm when quit

tools/parsememdump.py
In https://github.com/apache/nuttx/pull/9335, the sequence numbuer is added to the memory node, the memdump log changed also, so update the parsememdump.py script to keep in sync.
parsememdump.py
parse the dumped memory information.
=> parsememdump.py: support the sequence number parse

tools/Unix.mk
process substitution `>(..)` have different behaviors in different shells
unreliable execution order will lead to the problem of being unable to intercept errors. 
pipe are used here to ensure that `kwarning` is generated before the if statement.
kconfig warning
use CI build to test with and without kconfig warning separately.
=> Unix.mk:replace process substitution to pipe avoid out of order

drivers/sensors/Kconfig, drivers/sensors/Make.defs, drivers/sensors/goldfish_sensor_uorb.c, include/nuttx/sensors/goldfish_sensor.h
Implemented Goldfish Sensors:
Accelerometer
Gyroscope
MagneticField
AmbientTemperature
Proximity
Light
Pressure
RelativeHumidity
MagneticFieldUncalibrated
GyroscopeFieldUncalibrated
HeartRate
Unimplemented Goldfish Sensors:
(sensor type is not defined nuttx)
Orientation
HingeAngle0
HingeAngle1
HingeAngle2
WristTilt
Verification:
uorb_listener -r 1 sensor_accel
uorb_listener -r 1 sensor_mag
uorb_listener -r 1 sensor_gyro
uorb_listener -r 1 sensor_prox
uorb_listener -r 1 sensor_light
uorb_listener -r 1 sensor_humi
uorb_listener -r 1 sensor_baro
uorb_listener -r 1 sensor_temp
uorb_listener -r 1 sensor_hrate
new qemu goldfish driver
qemu goldfish
=> goldfish: add goldfish sensors driver

arch/arm/src/cxd56xx/cxd56_nxaudio_src.c, net/utils/net_snoop.c
to avoid opend files have random permission mode
=> refine: set file mode when oflags contains O_CREAT

libs/libc/netdb/lib_dnsquery.c, libs/libc/netdb/lib_gethostentbynamer.c
when ipv6 address filled the cache, the ipv4 address did not have a place to store it, causing the resolution to fail. so if IPV6 has already filled the buffer, rewrite ipv4 DNS results from half of the buffer.
sim:local
=> dns: fix dns failed when ipv4/6 dual stack enable

drivers/wireless/ieee80211/bcm43xxx/bcmf_ioctl.h
Revert WPA failure reason codes to the previous community version
Cortex-M33 and bcm43xxx chipset
=> bcm43xxx: revert part of the previous upstream code

arch/arm/src/nrf52/nrf52_pwm.c, arch/arm/src/nrf53/nrf53_pwm.c
arch/{nrf52|nrf53}/pwm: fix compilation for MULTICHAN not set
thingy53 with rgb leds
=> arch/{nrf52|nrf53}/pwm: fix compilation for MULTICHAN not set

drivers/spi/spi_slave_driver.c
driver/spi: avoid calling QPOLL to change rx_length and cause data loss
When the application calls poll and returns the POLLIN event, QPOLL will be called again during the read operation, causing rx_length to change and data to be lost.
Therefore, read only need to actively call qpoll to collect driver data when rx length is 0.
daily test
=> driver/spi: avoid calling QPOLL to change rx_length and cause data loss

net/local/local.h, net/local/local_accept.c, net/local/local_conn.c, net/local/local_sockif.c
local socket: fix accept used after free
```
==1729315==ERROR: AddressSanitizer: heap-use-after-free on address 0xf0501d60 at pc 0x032ffe43 bp 0xef4ed158 sp 0xef4ed148 READ of size 2 at 0xf0501d60 thread T0
#0 0x32ffe42 in nxsem_wait semaphore/sem_wait.c:94
#1 0x3548cf5 in _net_timedwait utils/net_lock.c:97
#2 0x3548f48 in net_sem_timedwait utils/net_lock.c:236
#3 0x3548f8c in net_sem_wait utils/net_lock.c:318
#4 0x350124d in local_accept local/local_accept.c:246
#5 0x3492719 in psock_accept socket/accept.c:149
#6 0x3492bcc in accept4 socket/accept.c:280
#7 0x662dc04 in accept net/lib_accept.c:50
#8 0x55c81ab in kvdb_loop kvdb/server.c:415
#9 0x55c860a in kvdbd_main kvdb/server.c:458
#10 0x33d968b in nxtask_startup sched/task_startup.c:70
#11 0x32ec039 in nxtask_start …
```
=> local socket: fix accept used after free

drivers/sensors/sensor.c, include/nuttx/sensors/sensor.h
drivers/sensors/: Add coordinate conversion function
convert from body coordinate system to right-hand
coordinate system.
Example:
Compared to the standard coordinate system,
the x-axis and y-axis are interchanged and have opposite directions,
the z-axis remains normal.
````
body coordinate   ---->     right-hand coordinate
+x               +y
|                |
|                |
|                |
|                |
-y<-------.                .------>+x
/                /
/                /
/                /
/                /
+z                +z
````
So for the above conversion, using "P3" to represent transformation relationships
The front is 1 0 2, which represents the y x z axis.
The standard order is 0 1 2, so y and x are interchanged.
The following -1 1 1 indicates the direction …
=> drivers/sensors/: Add coordinate conversion function

drivers/mmcsd/mmcsd_debug.c
=> Fix mmcsd/mmcsd_debug.c:110:9: error: format '%d' expects argument oftype 'int', but argument 3 has type 'long unsigned int'

libs/libc/netdb/Kconfig
Domain name has the similar layout as file path, so it's too small to use 32 bytes as the default value, and better to has the same default value as PATH_MAX which is 255.
default value of NETDB_DNSCLIENT_NAMESIZE
ci
=> lib/netdb: Change the default NETDB_DNSCLIENT_NAMESIZE to PATH_MAX

drivers/sensors/sensor_rpmsg.c
driver/sensors: fix sensor_rpmsg_ns_unbind_cb crash
==2787216==ERROR: AddressSanitizer: heap-use-after-free on address 0xf4702448 at pc 0x0136c544 bp 0x9f54d358 sp 0x9f54d348 READ of size 4 at 0xf4702448 thread T0
```
0 0x136c543 in rpmsg_destroy_ept open-amp/lib/rpmsg/rpmsg.c:357
1 0x1252b29 in sensor_rpmsg_ns_unbind_cb sensors/sensor_rpmsg.c:1216
2 0x1371de5 in rpmsg_virtio_ns_callback open-amp/lib/rpmsg/rpmsg_virtio.c:663
3 0x1371026 in rpmsg_virtio_rx_callback open-amp/lib/rpmsg/rpmsg_virtio.c:583 
4 0x137c105 in virtqueue_notification open-amp/lib/virtio/virtqueue.c:711 
5 0x1368604 in rproc_virtio_notified open-amp/lib/remoteproc/remoteproc_virtio.c:433 
6 0x1363abe in remoteproc_get_notification open-amp/lib/remoteproc/remoteproc.c:10
```
daily test
=> driver/sensors: fix sensor_rpmsg_ns_unbind_cb crash

tools/Unix.mk
terminal character redirection will cause curselib errors. 
the warning check has been completed before the menuconfig execution phase, so lets ignored here.
this is a supplementary change of https://github.com/apache/nuttx/pull/10763
fix the issue https://github.com/apache/nuttx/issues/10794
CI build
=> tools/Unix.mk:ignore Kconfiglib menuconfig module warning

libs/libc/gpsutils/Make.defs
Fix make[1]: *** No rule to make target '.header', needed by 'context‘ Stop.
local test
=> libc/gpsutils: fix compile error

drivers/mmcsd/mmcsd_sdio.c
=> Fix error: 'mmcsd_general_cmd_read' defined but not used

include/pthread.h, libs/libc/pthread/pthread_once.c
For programs with the dependencies logic in pthread_once callback , using global locks may cause deadlock:
```
task A
pthread_once()
|
|-> nxrmutex_lock(&g_lock);
-> init_routine(); // callback to wait task B
task B
pthread_once()
|
->nxrmutex_lock(&g_lock); // Deadlock
->init_routine(); // hold resource to wake up task A
```
pthread_once
internal
=> pthread_once: g_lock may lead deadlock

mm/mm_heap/mm_initialize.c
```
mm_heap/mm_initialize.c:69:11: warning: array subscript -1 is outside array bounds of 'void[2147483647]' [-Warray-bounds]
69 |       node->pid = MM_BACKTRACE_MEMPOOL_PID;
|           ^~
mm_heap/mm_initialize.c:64:9: note: at offset -16 into object of size [0, 2147483647] allocated by 'mm_memalign'
64 |   ret = mm_memalign(arg, alignment, size);
```
mm
arm64
=> mm:fix warning

arch/arm/src/armv7-a/arm_dataabort.c, arch/arm/src/armv7-a/arm_prefetchabort.c, arch/arm/src/armv7-a/arm_undefinedinsn.c, arch/arm/src/armv7-r/arm_dataabort.c, arch/arm/src/armv7-r/arm_prefetchabort.c, arch/arm/src/armv7-r/arm_undefinedinsn.c, arch/arm/src/armv8-r/arm_dataabort.c, arch/arm/src/armv8-r/arm_prefetchabort.c, arch/arm/src/armv8-r/arm_undefinedinsn.c
=> arch/arm: Fix  error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'}

sched/misc/assert.c
follow up the change: https://github.com/apache/nuttx/pull/10553
minor
ci
=> assert: Skip to include arch/board/board.h if CONFIG_ARCH_LEDS=n

sched/Kconfig
Fix some Kconfig dependency problems from #10063.
CONFIG_SCHED_CPULOAD_EXTCLK doesn't actually require tickless mode. As long as the platform provides external call to nxsched_process_cpuload(), it will work in either tickless or ticking mode.
Removed Kconfig dependency.
Instead, CONFIG_SCHED_CPULOAD_SYSCLK does require ticking mode to work, as documented in CONFIG_SCHED_CPULOAD help text.
Added the dependency to Kconfig also.
Fixes breaking of configurations using `CONFIG_SCHED_CPULOAD_EXTCLK`.
Automatically selects `SCHED_CPULOAD_EXTCLK` if tickless mode is enabled and selection was previously `SCHED_CPULOAD_SYSCLK`. It will behave the same: if there is no user code calling `nxsched_process_cpuload()`, cpu load will not be updated. But now the dependency is visible from Kconfig also. …
=> Fix dependencies of CONFIG_SCHED_CPULOAD_ settings

drivers/video/goldfish_fb.c
forget from patch:
```
commit bbf5b0bb6d970da9fbe91f40c8640551a3ecd29c
Author: jianglianfang <jianglianfang@xiaomi.com>
Date:   Tue Aug 15 19:47:14 2023 +0800
driver/video: adapting Goldfish FB to VSync optimized FB driver
The circbuf part is implemented by the fb driver, and goldfish needs to
delete the part related to circbuf and adapt to the interface of the fb
driver.
```
goldfish fb driver
internal ci
=> video/goldfish: Remove the vsync residual code

net/icmpv6/Kconfig, net/icmpv6/icmpv6_radvertise.c
Allows setting the advertised route lifetime, and also to set it to 0 for advertising only the prefix.
From RFC4861:
>   A router might want to send Router Advertisements without advertising
itself as a default router.  For instance, a router might advertise
prefixes for stateless address autoconfiguration while not wishing to
forward packets.  Such a router sets the Router Lifetime field in
outgoing advertisements to zero.
Default setting is the same 1800 as previously hardcoded value.
Tested on custom STM32F4 target communicating with Linux system.
With default settings NuttX appears as a default router in `ip -6 route` output.
By setting `CONFIG_NET_ICMPv6_ROUTER_LIFETIME=0` only the advertised prefix appears.
=> Add CONFIG_NET_ICMPv6_ROUTER_LIFETIME

net/local/local_conn.c
Allow the local udp socketpair function to use the local_release_fifos interface.
When CONFIG_NET_LOCAL_STREAM is disabled, the local udp socketpair can use the local_release_fifos
When CONFIG_NET_LOCAL_STREAM is disabled, we can close the fifo files created by the local udp socketpair.
=> net/local: Fix the problem that local udp socketpair cannot release fifo files.

arch/arm/src/sama5/Kconfig, arch/arm/src/sama5/sam_adc.c
SAMA5D2 uses XDMA not DMA and a few minor changes were required to get XDMA working for the ADC and TSD peripherals
DMA should now work
Custom board with SAM5D27C-D1G with 6 channels of ADC + touchscreen LCD
=> Sort SAMA5D2 adc/tsd dma

drivers/analog/lmp92001.c, drivers/ioexpander/ioe_dummy.c, drivers/ioexpander/iso1h812g.c, drivers/ioexpander/iso1i813t.c, drivers/ioexpander/mcp23x08.c, drivers/ioexpander/mcp23x17.c, drivers/ioexpander/pca9538.c, drivers/ioexpander/pca9555.c, drivers/ioexpander/pcf8574.c, drivers/ioexpander/pcf8575.c, drivers/ioexpander/skeleton.c, drivers/ioexpander/tca64xx.c, include/nuttx/ioexpander/ioexpander.h
- drivers/ioexpander: Add const to the pin array, forget in patch: https://github.com/apache/nuttx/pull/9529
- drivers/ioexpander: Add const to the value array of multiwritepin
ioexpander
internal test
=> Minor fix for ioexpander driver

Documentation/quickstart/install.rst
Update the GCC compiler to 10.3-2021.10 to be able to compile the latest NuttX version
Fix for error:
arm-none-eabi-g++: error: unrecognized command line option '-std=gnu++20'; did you mean '-std=gnu++2a'?
Documentation
compiled spresense (ARM)
=> Documentation: update gcc compiler to 10.3

drivers/segger/Kconfig, drivers/segger/serial_rtt.c
drivers/rtt: make RTT console optional
in case we want to use serial RTT to stream data without console support
nxscope stream over RTT
=> drivers/rtt: make RTT console optional

arch/arm/Kconfig, arch/arm/src/stm32/stm32_timerisr.c, sched/Kconfig, sched/clock/clock_adjtime.c
Prior pull request #9084 and issue #8858 added basic adjtime() support for the SAMv7 platform.
This pull request adds support for STM32 platform.
In addition I have made a few changes to the adjtime() configuration options:
1) Previously adjustments less than 1 microsecond per tick would be
completely ignored. Now they are applied over a shorter period at
a rate of 1 us per tick.
2) Previously CLOCK_ADJTIME_PERIOD was in units of 1/100th of second.
Change to milliseconds to be more generally useful unit.
Change setting name to CLOCK_ADJTIME_PERIOD_MS to make the unit change
easier to notice.
3) Previously CLOCK_ADJTIME_SLEWLIMIT was in percentage.
Most clock crystals have better accuracy than 1%, so the minimum slew
rate was excessive. Change to CLOCK_ADJTIME_SLEWLIMIT_PPM with setting …
=> Improve adjtime() functionality

arch/arm/src/nrf52/nrf52_tim_lowerhalf.c, arch/arm/src/nrf53/nrf53_tim_lowerhalf.c, arch/arm/src/nrf91/nrf91_tim_lowerhalf.c
arch/nrf{52|53|91}: fix timer for small intervals and correct CC overflow check
nrf52832-dk
=> arch/nrf{52|53|91}: fixes for timer

arch/Kconfig, arch/arm/Kconfig, drivers/sensors/Kconfig
- arch: add a flag indicating that the chip doesn't support DMA transfer from/to FLASH
- sensors: SENSORS_BMI270_LOAD_FROM_HEAP equals ARCH_DMA_NO_FLASH_TRANSFER
CI
=>  arch: add a flag indicating that the chip doesn't support DMA transfer from/to FLASH

include/nuttx/mm/kmap.h, mm/kmap/kmm_map.c
Fixes a bug in kmm_unmap; kernel mappings are found in the kernel's mapping list, not in the current process's list.
CONFIG_MM_KMAP only
MPFS + CONFIG_MM_KMAP=y
=> mm/kmap: Fix bug in kmm_unmap

boards/arm/stm32/nucleo-f446re/src/stm32_bringup.c, boards/arm/stm32/nucleo-f446re/src/stm32_userleds.c
Changes are made for the nucleo-f446re board.
- Initialize LED driver when `CONFIG_USERLED` is set, during late initialization. 
- Cleaned up `stm32_userleds.c`.
Make LED driver work when:
1. `CONFIG_ARCH_LEDS` is not set.
2. `CONFIG_USERLED` is set.
3. `CONFIG_BOARD_LATE_INITIALIZE` is set.
Using `nucleo-f446re:nsh` configuration as a starting point, apply the above-mentioned changes, and enable the LED Example. The LED blink as expected.
=> Initialize LED driver during late initialization for nucleo-f446re

Documentation/quickstart/install.rst
Update GCC 10.3 download link to match the curent location
Documentation
successful download
=> Documentation: update gcc download location

drivers/note/note_driver.c, drivers/note/notesnap_driver.c, drivers/rptun/rptun_ping.c, drivers/segger/note_sysview.c, fs/procfs/fs_procfscritmon.c, fs/procfs/fs_procfsproc.c, include/limits.h, include/nuttx/clock.h, include/nuttx/sched.h, sched/Kconfig, sched/clock/CMakeLists.txt, sched/clock/Make.defs, sched/clock/clock.h, sched/clock/clock_gettime.c, sched/clock/clock_initialize.c, sched/clock/clock_perf.c, sched/irq/irq.h, sched/irq/irq_attach.c, sched/irq/irq_dispatch.c, sched/irq/irq_procfs.c, sched/sched/sched_critmonitor.c, sched/wdog/wd_start.c, sched/wqueue/kwork_thread.c
perf_getime always returns an incremented cycle value If the hardware does not support perf event, it will use arch_alarm's up_perf_gettime.
convert up_perf_ api invocation to perf_ api.
new perf_ api
ci
=> timer: handle perf count overflow

arch/arm/src/at32/at32_adc.c, arch/arm/src/imxrt/imxrt_adc.c, arch/arm/src/samv7/sam_afec.c, arch/arm/src/stm32/stm32_adc.c, arch/arm/src/stm32f7/stm32_adc.c
- stm32{f7}/adc: always increase initialization counter when adc_setup called
- at32/adc: always increase initialization counter when adc_setup called
- imxrt/adc: always increase initialization counter when adc_setup called
- samv7/adc: always increase initialization counter when adc_setup called
The problem originally occurred in stm32_adc.c and has propagated to other architectures.
the `initialized` flag should be incremented every time adc_setup is called, otherwise the protective logic in adc_reset that is supposed to prevent resetting the ADC in use doesn't work properly.
The problem occurs when the ADC peripheral is shared by more than one different driver. In my case this is ADC upper-half driver and FOC lower-half driver.
only stm32 tested with b-g431b-esc1/foc_f32.
=> arch/{stm32|stm32f7|at32|samv7|imxrt}: fix for adc_setup

arch/arm/src/s32k1xx/Kconfig, arch/arm/src/s32k1xx/s32k1xx_serial.c
Enabling S32K1XX_LPUART_INVERT causes warning when building serial driver. This patch fixes it, and also
removes a duplicated menu entry in Kconfig.
Minor, affects configuration & build only.
```
tools/configure.sh s32k148evb:nsh
make menuconfig
```
Select
1. `System Type -> LPUART Configuration -> Signal Invert Support`
2. `Device Drivers -> Serial Driver Support -> Serial TERMIOS support`
```
make
```
Warning is printed:
```
chip/s32k1xx_serial.c:1350:20: warning: declaration of 'flags' shadows a previous local [-Wshadow]
1350 |         irqstate_t flags;
|                    ^~~~~
```
After the patch, the warning no longer appears. Also, after the patch it is no longer needed to enable TERMIOS support to have LPUART inversion, and the double "LPUART Configuration" menu entry is gone …
=> arch/arm/src/s32k1xx: Fix LPUART inversion warnings & config.

arch/arm/src/s32k1xx/hardware/s32k1xx_ftm.h, arch/arm/src/s32k1xx/s32k1xx_pwm.c
There are some warnings, mainly in printf-like format strings. This patch removed them.
No functional change, only affects the build process.
```
tools/configure.sh s32k148evb:nsh
make menuconfig
```
Select:
1. `Device Drivers -> Timer Driver Support -> PWM Driver Support`
2. `System Type -> S32K1XX Peripheral Selection -> FTM0`
3. `System Type -> S32K1XX Peripheral Selection -> S32K1XX FTM PWM Configuration -> FTM0 PWM`
```
make
```
Warnings are printed:
```
chip/s32k1xx_pwm.c:360:11: warning: format '%d' expects argument of type 'int', but argument 5 has type 'uint32_t' {aka 'const long unsigned int'} [-Wformat=]
360 |   pwminfo("FTM%d channel: %d frequency: %d duty: %08x\n",
|           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
361 |           priv->tpmid, priv->channel, …
```
=> arch/arm/src/s32k1xx: Fix warnings in PWM code.

arch/arm/src/stm32h7/stm32_oneshot.c
There are some format warnings in printf-linke format strings. This patch removes them.
No functional change, only affects the build process.
To show the warnings:
```
tools/configure.sh nucleo-h743zi2:nsh
make menuconfig
```
Select `System Type -> Timer Configuration -> TIM one-shot wrapper`
```
make
```
Before the patch, warnings are printed:
```
chip/stm32_oneshot.c:186:11: warning: format '%d' expects argument of type 'int', but argument 5 has type 'long int' [-Wformat=]
186 |   tmrinfo("chan=%d resolution=%d usec, USEC_PER_SEC:%d\n", chan, resolution,
|           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[...]
chip/stm32_oneshot.c:193:11: warning: format '%d' expects argument of type 'int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
193 | …
```
=> arch/arm/src/stm32h7/stm32_oneshot.c: Fix format warnings.

arch/Kconfig, arch/arm/src/at32/at32_start.c, arch/arm/src/nrf52/nrf52_start.c, arch/arm/src/nrf53/nrf53_start.c, arch/arm/src/nrf91/nrf91_start.c, arch/arm/src/stm32/stm32_start.c, arch/arm/src/stm32f0l0g0/stm32_start.c, arch/arm/src/stm32f7/stm32_start.c, arch/arm/src/stm32h7/stm32_start.c, arch/arm/src/stm32l4/stm32l4_start.c, arch/arm/src/stm32l5/stm32l5_start.c, arch/arm/src/stm32u5/stm32_start.c, arch/arm/src/stm32wb/stm32wb_start.c, arch/arm/src/stm32wl5/stm32wl5_start.c, boards/arm/lpc17xx_40xx/lx_cpu/src/lpc17_40_boardinitialize.c, boards/arm/s32k1xx/rddrone-bms772/src/s32k1xx_boot.c, boards/arm/s32k1xx/s32k144evb/src/s32k1xx_boot.c, boards/arm/s32k1xx/s32k146evb/src/s32k1xx_boot.c, boards/arm/s32k1xx/s32k148evb/src/s32k1xx_boot.c, boards/arm/s32k1xx/ucans32k146/src/s32k1xx_boot.c, boards/arm/s32k3xx/mr-canhubk3/src/s32k3xx_boot.c, boards/risc-v/esp32c3/esp32c3-devkit-rust-1/src/esp32c3_boot.c, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_boot.c
- arch/ add a flag indicating that we need up_perf_xxx
- arch/{all stm32 | all nordic | at32}: simplify the enable condition for up_perf_init
waiting for https://github.com/apache/nuttx/pull/10826
automatically initializes perf when needed
CI
=> arch: add a flag indicating that we need up_perf_xxx

arch/xtensa/src/esp32s2/Kconfig, arch/xtensa/src/esp32s2/esp32s2_config.h, arch/xtensa/src/esp32s2/esp32s2_lowputc.c, arch/xtensa/src/esp32s2/esp32s2_lowputc.h, arch/xtensa/src/esp32s2/esp32s2_serial.c
* xtensa/esp32s2: add UART RS485 support
Only ESP32S2
ESP32S2-Saola board with `esp32s2-saola-1:nsh` config with `UART 1` option enabled under the `System Type -> ESP32-S2 Peripheral Selection` and `RS-485 on UART1` option enabled under the `System Type -> UART Configuration`.
- Transmitter side tested with `echo "test" >> /dev/ttyS1` command(s) using nsh and serialblaster example under `Application Configuration -> Examples -> Serial Blaster example` using `serialblaster /dev/ttyS1` command with using a logic analyzer. [idf uart echo rs485](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/uart/uart_echo_rs485) example on another chip can be used as well. 
- Recieve side tested with serialrx example under `Application Configuration -> Examples -> Serial RX example` …
=> xtensa/esp32s2: add UART RS485 support

arch/xtensa/src/esp32/esp32_ble_adapter.c
* esp32/ble: Fix task_create_wrapper CPU core ID passed as argument
The registered `task_create_wrapper` receives the `core_id`, but
the current implementation ignores this parameter while calling
`esp_task_create_pinned_to_core`. This commit fixes this.
Enable the BLE adapter to select the CPU core used to create a task pinned to a specific core on SMP-enabled defconfigs.
Internal CI testing + ESP32-DevKitC.
=> esp32/ble: Fix task_create_wrapper CPU core ID passed as argument

arch/xtensa/include/esp32s3/irq.h, arch/xtensa/src/esp32s3/Kconfig, arch/xtensa/src/esp32s3/esp32s3_ble_adapter.c, arch/xtensa/src/esp32s3/esp32s3_irq.c, arch/xtensa/src/esp32s3/esp32s3_irq.h, arch/xtensa/src/esp32s3/esp32s3_spiflash.c, arch/xtensa/src/esp32s3/esp32s3_wireless.c, arch/xtensa/src/esp32s3/esp32s3_wireless.h, arch/xtensa/src/esp32s3/hardware/esp32s3_soc.h, boards/xtensa/esp32s3/common/scripts/legacy_sections.ld
* esp32s3/irq: Fix erroneous interrupt allocation for each CPU core
* esp32s3/ble: fix saving/restoring the interrupt status flags
* esp32s3/irq: Allow IRAM ISRs to run during SPI flash operation
* esp32s3/ble: enable the BLE interrupt during a SPI flash operation
This PR provides an interface to register ISRs that run from IRAM and keeps track of the non-IRAM interrupts. It enables, for instance, to avoid disabling all the interrupts during a SPI flash operation: IRAM-enabled ISRs are, then, able to run during these operations. One direct impact: it avoids BLE's packet losses while an SPI flash operation takes place.
Internal CI testing + NuttX CI + ESP32-S3-DevKitC-1 board;
=>  esp32s3/ble: enable the BLE interrupt during a SPI flash operation

libs/libxx/Kconfig
Fix an issue that gnu++20 option is always used.
By https://github.com/apache/nuttx/pull/8244#discussion_r1294750528, when libcxx is not used, gnu++17 should be retained.
=> libxx: Use gnu++20 option only if using libcxx

arch/risc-v/src/common/riscv_addrenv_utils.c, arch/risc-v/src/common/riscv_mmu.h
Use kernel page table flags if the mapped virtual address is in kernel space.
Minor fixe, impact to others should be nothing.
icicle + CONFIG_BUILD_KERNEL=y
=>  riscv_addrenv_utils.c: Determine page table flags by type of vaddr 

Documentation/platforms/risc-v/esp32c3/index.rst, Documentation/platforms/risc-v/esp32c6/index.rst, Documentation/quickstart/configuring.rst
* Currently, this toolchain is being used for NuttX CI testing and provides. features that weren't available in the old toolchain based on GCC 10.2;
* Fix search path for defconfig include list;
None.
`sphinx-build` locally.
=> Documentation: improve documentation for ESP32-C3/C6 and fix defconfig include list

arch/arm/src/stm32/stm32_serial.c
As specified in STM32G4 series reference manual(RM0440 v7.0) page 1643, PS or PCE bit can only be modified when USART is disabled.
Disable USART before changing any configuration and enable it after work done.
Tested in PX4 flight controller firmware
=> UART needs to be disabled before changing setup

drivers/sensors/Kconfig, drivers/sensors/Make.defs, drivers/sensors/max31865.c, include/nuttx/sensors/max31865.h
A digital converter for rtd
NuttShell (NSH) NuttX-12.2.1
nsh> 
nsh> ls /dev
/dev:
console
null
ram0
temp0
ttyS0
#define MAX31865_PATH "/dev/temp0"
{
int ret = 0;
int fd = 0;
float temp = 0.0f;
fd = open(MAX31865_PATH, O_RDONLY);
if (fd < 0)
{
perror("open max31865 fail");
return -1;
}
while (1)
{
sleep(1);
ret = read(fd, (float *)&temp, sizeof(temp));
if (ret < 0)
printf("read max31865 fail: %d\n", ret);
else
printf("temp: %.1f\n", temp);
}
return 0;
}
=> max31865:RTD-to-Digital Converter

include/sys/types.h
sys/types: supporting 32-bit IDs for gid_t/uid_t
N/A
ci-check
=> sys/types: supporting 32-bit IDs for gid_t/uid_t

drivers/video/fb.c, include/nuttx/video/fb.h
so the user could register fb device directly instead go through the sequence of up_fbinitialize/up_fbgetvplane
new api
ci
=> video/fb: Add fb_register_device

sched/misc/assert.c
In addition to printing out the thread name (task name in flat mode), print the parent process's name as well.
It is quite useful to know which process is the parent of a faulting thread, although this information can be read from the assert dump, in some cases the dump might be incomplete (due to e.g. stack corruption, which causes another exception and PANIC().)
CONFIG_BUILD_KERNEL=y only
icicle + CONFIG_BUILD_KERNEL=y
=> sched/assert.c: Print process name in assert dump

arch/xtensa/src/esp32s3/esp32s3_i2c.c
Apparently there is an error on the i2c handling of the esp32s3. When there is a bus error, the master will never be able to recover (not even after a reset, since the reset control was broken). If we need to send the 9 clk, we can use the i2c reset function.
This PR includes:
- the fix to the reset_fsmc (do as we do on the esp32c3 and as specified in the TRM).
- The improvement to not send 9 CLK every time we want to clear the fsm. 
The i2c on the esp32s3 is now much faster, as we don't need to send the 9 clocks on every transaction. We also recover from failed transactions, as the reset of the fsm is done correctly.
Only manual testing: after these changes I am able to do `i2c dev 1 7f` on my esp32-s3-eye and it will always find the IMU at address 12.
=> ESP32-S3 I2C improvements

arch/risc-v/src/common/pgalloc.h
All kernel memory is mapped paddr=vaddr, so it is trivial to give mapping for kernel memory. Only interesting region should be kernel RAM, so omit kernel ROM and don't allow re-mapping it.
Extend address range understood by riscv_pgvaddr
mpfs + CONFIG_BUILD_KERNEL
=> riscv-v/pgalloc.h: Return kernel vaddr for kernel RAM paddr

tools/size_report.py
NodeMixin have attribute called size and it is set property. Overwrite this property by _size but it will make report incompatible.
Create a new class NuttxDictExporter to renaming _size into size.
reference: https://github.com/c0fec0de/anytree/blob/27ff97eed4c09b4f0eb9ae61b45dd30b794a135c/anytree/node/nodemixin.py#L508
tools/sizereport
local test.
=> fix: TreeNode has same attribute with NodeMixin

net/usrsock/usrsock_sockif.c
=> net/usersock: Return -ENOSUPP directly if domain isn't equal to PF_INET/PF_INET6

arch/arm/src/common/Toolchain.defs, arch/arm64/src/Toolchain.defs, arch/xtensa/src/esp32/Make.defs, libs/libxx/libcxx.defs
When we build NuttX on macOS, it shows many `sed` messages (and the build still completes successfully):
```text
$ tools/configure.sh pinephone:nsh
$ make
sed: illegal option -- r
```
[(See the Complete Log)](https://gist.github.com/lupyuen/1c3f1f1d71993609bed3b31767595beb#file-pinephone-release-log-L282-L690)
This is due to the Makefiles executing `sed -r` which is not a valid option on macOS. [(As explained here)](https://github.com/apache/nuttx/pull/10655#issuecomment-1754168154)
This PR proposes to change `sed -r` to `sed -E` because:
1. `sed -E` on macOS is equivalent to `sed -r` on Linux [(See this)](https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed)
1. `sed -E` and `sed -r` are aliases according to the [GNU `sed` …
=> arm, arm64, xtensa, libxx: Change `sed -r` to `sed -E` to support macOS

net/icmpv6/icmpv6_sendmsg.c, net/inet/inet_sockif.c, net/udp/udp_finddev.c
Allow icmpv6 and udp to find the dev by the ifindex with s_boundto..
When the ipv6 socket was set SO_BINDTODEVICE, the icmpv6 and udp can 
find the dev by the ifindex with s_boundto.
In the sim, create two ethernet interfaces. Bind the ipv6 socket to eth1.
then, use ping6 or renew6 to send ipv6 packets, we can check that 
the conn is bound to device eth1 in icpmv6_sendmsg/sendto_next_transfer function.
=> net: allow icmpv6 and udp to find the dev by the ifindex with s_boundto.

libs/libc/misc/lib_memfd.c
lib_memfd: turn a runtime error into a linker error
none
none
=> lib_memfd: turn a runtime error into a linker error

drivers/note/note_driver.c, drivers/note/noteram_driver.c, include/nuttx/sched_note.h
Use sched_note_dump to record the original data to reduce calling printf during runtime
=> optimize note performance

arch/x86_64/src/intel64/intel64_head.S
`qemu-intel64` init does not work properly due to invalid stack initialization.
`g_idle_topstack` is a variable, it's content must be moved to `rsp`.
Deterministic behavior with `qemu-intel64:*` targets.
qemu-intel64:nsh
=> arch: x86_64: Fix idle stack assignment

drivers/syslog/ramlog.c
ramlog: remove sched_[un]lock and rl_nwaiters
none
none
=> ramlog: remove sched_[un]lock and rl_nwaiters

libs/libc/netdb/lib_dnsaddserver.c
We consider the setting successful when the nameserver we set already exists.
If the nameserver is exists, when we set the nameserver,  return OK, not the -EEXIST.
Use the netlib_set_ipv6dnsaddr interface to set the same dns nameserver twice or more, 
we will always get OK.
=> netdb: When set a dns nameserver which already exists, retrun OK

arch/sim/Kconfig, arch/sim/src/Makefile, arch/sim/src/sim/sim_internal.h, arch/sim/src/sim/sim_netdriver.c, arch/sim/src/sim/sim_wifidriver.c, drivers/net/Kconfig, tools/simwifi/README, tools/simwifi/dnsmasq.conf, tools/simwifi/hostapd.conf, tools/simwifi/hostapd_hwsim.conf, tools/simwifi/sim_wifi.sh, tools/simwifi/udhcpc.script, tools/simwifi/wpa_supplicant.conf, tools/simwifi/wpa_supplicant_hwsim.conf
Add the Sim WiFi function, which can provide the wifi operating on nuttx sim emulator,
and support two modes that simulate wifi, HWSIM and RNC(real network card).
- In the HWSIM mode, we simulates two wlan interfaces. The wlan0 is STA and
the wlan1 is AP. The wlan0 can connect to the wlan1 in the nuttx simulator.
- In the RNC mode, we can use the same wlan interface name on the nuttx simulator
to control the connection behavior of the real wireless card.
We can debug and verify the WiFi-related applications on the sim.
We insert a wireless network card named wlx1cbfce6e7f96, then do the following steps:
- Host: 
sudo ./tools/simwifi/sim_wifi.sh init eno1 RNC 
sudo ./tools/simwifi/sim_wifi.sh  rename  wlx1cbfce6e7f96 wlan0
- Sim:
ifup wlan0
wapi mode wlan0 2
wapi scan wlan0
wapi psk wlan0 …
=> sim/wifidriver: Support the sim wifi.

libs/libxx/Kconfig
Fix an issue that gnu++20 option is always used.
Essentially, when cxx is not used, gnu++17 should be retained.
RELEASE
NONE
=> {BP-10860} libxx: Use gnu++20 option only if using libcxx

arch/arm64/src/common/arm64_mmu.c
Only when SCTLR_ELn.WXN is set to 1, regions that are writable at ELn are treated as non-executable. Therefore, when SCTLR_ELn.WXN is set to 0, regions that are writable at ELn can be executed, so the writable attribute cannot be used to restrict the executable attribute.
arm64 mmu config
qemu-armv8a:nsh with mmu region attr set to (MT_NORMAL | MT_RW | MT_EXECUTE)
=> arm64: XN should only be set when the attribute MT_EXECUTE_NEVER is set

drivers/mtd/filemtd.c
In previous versions, during the teardown phase, the "open_blockdriver" would call the "mtd proxy" causing the "file mtd" node to be registered in the ftl. " node is registered in ftl. Therefore, we changed the behavior to find the corresponding inode by node name.
None
The local simulator environment is passed
=> filemtd:Fix teardown return error number EINVAL

arch/sim/src/sim/posix/sim_hostmisc.c
Summary
Simulator build fails on non-GLIBC platform #5621 #5623.
On platforms where the execinfo.h file is missing, the Gnulib substitute implementation is just a stub, and does nothing.
https://www.gnu.org/software/gnulib/manual/html_node/execinfo_002eh.html
Improve multiplatform code with __has_include.
https://gcc.gnu.org/onlinedocs/cpp/_005f_005fhas_005finclude.html
Impact
On Linux with glibc: There should be no impact.
On other platforms: Enable simulator compilation.
Testing
We tested on platform Alpine linux [sim:nsh on github](https://github.com/simbit18/nuttx-alpine) sim:lua
=> Update Fix more generic for platforms that do not have execinfo.h

libs/libdsp/lib_observer.c
- libdsp/lib_observer.c: use float numbers in all calculations
we want to use FPU instructions in calculations not __aeabi
optimization
b-g431b-esc1
=> libdsp/lib_observer.c: use float numbers for some calculations

sched/misc/assert.c
Execute the simple logic first to avoid rarely crash information when crash in backtrace again.
Show backtrace after the stack dump.
Internal project board with BES Cortex-A7 dual core and Cortex-M33 chip
=> assert: move the backtrace dump after the stack dump

arch/arm64/src/common/arm64_gicv3.c
target cpuid calculation error in arm64_gic_raise_sgi function.
arm64 sgi
qemu-armv8a:nsh_smp use up_trigger_irq trigger sgi to multi core.
=> arm64: target cpuid calculation error in arm64_gic_raise_sgi function

arch/arm64/src/common/arm64_cache.c
Before code is executed after being loaded into memory, it is necessary to ensure the consistency of I and D cache. The up_coherent_dcache function will flush the dache and invalidate the icache to ensure cache consistency.
ARM64 cache
=> arm64: support up_coherent_dcache function

arch/risc-v/src/mpfs/mpfs_entrypoints.c
Change bgtz t0, mpfs_opensbi_prepare_hart to tail-call to ensure there will be no link time error due to the jump offset being too large.
MPFS only
MPFS
=> mpfs/mpfs_entrypoints.c: Fix potential R_RISCV_JAL linker error

arch/risc-v/src/mpfs/mpfs_ethernet.c
This fixes two issues with RX/TX buffers and descriptors. A NULL de-reference and a memory leak.
MPFS only
MPFS
=> mpfs_ethernet.c: Fix RX/TX buffer and descriptor handling

arch/arm/include/samv7/sam_afec.h, arch/arm/src/samv7/sam_afec.c, include/nuttx/analog/ioctl.h
via ioctl one can make use of the samv7's afec internal gain amplifiers 
none
on custom board with current 0.000 ... 50 Amps, dynamic gain selection implemented
=> samv7: channel gain switching in aefc

libs/libc/machine/sparc/arch_elf.c
since sparc is 32bit arcch, FAR is useless
minor
ci
=> libc/machine: Remove FAR from sparc

drivers/math/CMakeLists.txt, drivers/math/Kconfig, drivers/math/Make.defs, drivers/math/math.c, include/nuttx/math/math.h, include/nuttx/math/math_ioctl.h, include/nuttx/math/mpi.h
add interface for MPI(Multiple Precision Integer) registration in /math/mpi
=> math/mpi: add mpi driver in math

Documentation/quickstart/install.rst
This PR:
- Adds `brew` install instructions for `ARM32` and `ARM64` toolchains for `macOS` users.
- `KConfig` build requireds `sudo` on `make install` to be able to write to `/usr/local/bin/kconfig`.
- Remove duplicate`x86_64` in path of `From arm.com`, and improved instructions.
- nit: `macOS` naming.
Adds simple instructions to allow `ARM` development for `macOS` users.
Sucessfull builds of:
`stm32f4discovery:nsh` using `gcc-arm-embedded`
`pinephone:nsh` using `gcc-aarch64-embedded`
=> Improve macOS install docs

arch/risc-v/src/mpfs/mpfs_head.S
Initially clear PMP for all harts, this fixes random warm reset issues.
MPFS only
MPFS
=> mpfs_head.S: Simplify clearing PMP

sched/group/group.h, sched/group/group_setupidlefiles.c, sched/init/nx_start.c
=> sched: Remove the unused tcb argument from group_setupidlefiles

arch/arm/src/stm32/stm32_eth.c
stm32_ifdown() holds critical section when calling stm32_ethreset(). That function used to call up_mdelay(10) while waiting for the ethernet peripheral reset to complete. This resulted in excessively long critical section time with interrupts disabled.
The actual expected delay is a few clock ticks of the 50 MHz clock domain. This commit changes polling interval to 1us and maximum to 10us.
RELEASE
RC1
=> {BP-10815} stm32_eth: Fix excessively long critical section in ifdown handler

sched/Kconfig
CONFIG_SCHED_CPULOAD_EXTCLK doesn't actually require tickless mode. As long as the platform provides external call to nxsched_process_cpuload(), it will work in either tickless or ticking mode.
Removed Kconfig dependency.
Instead, CONFIG_SCHED_CPULOAD_SYSCLK does require ticking mode to work, as documented in CONFIG_SCHED_CPULOAD help text.
Added the dependency to Kconfig also.
RELEASE
RC1
=> {BP-10816} Fix dependencies of CONFIG_SCHED_CPULOAD_ settings

arch/arm/src/s32k1xx/hardware/s32k1xx_ftm.h, arch/arm/src/s32k1xx/s32k1xx_pwm.c
There are some warnings, mainly in printf-like format strings. This patch removed them.
RELEASE
RC1
=> {BP-10844} arch/arm/src/s32k1xx: Fix warnings in PWM code.

arch/arm/src/s32k1xx/Kconfig, arch/arm/src/s32k1xx/s32k1xx_serial.c
Enabling S32K1XX_LPUART_INVERT causes warning when building serial driver. This patch fixes it, and also
removes a duplicated menu entry in Kconfig.
RELEASE
RC1
=> {BP-10846} arch/arm/src/s32k1xx: Fix LPUART inversion warnings & config

arch/arm/src/at32/at32_adc.c, arch/arm/src/imxrt/imxrt_adc.c, arch/arm/src/samv7/sam_afec.c, arch/arm/src/stm32/stm32_adc.c, arch/arm/src/stm32f7/stm32_adc.c
stm32{f7}/adc: always increase initialization counter when adc_setup called
at32/adc: always increase initialization counter when adc_setup called
imxrt/adc: always increase initialization counter when adc_setup called
samv7/adc: always increase initialization counter when adc_setup called
The problem originally occurred in stm32_adc.c and has propagated to other architectures.
the initialized flag should be incremented every time adc_setup is called, otherwise the protective logic in adc_reset that is supposed to prevent resetting the ADC in use doesn't work properly.
The problem occurs when the ADC peripheral is shared by more than one different driver. In my case this is ADC upper-half driver and FOC lower-half driver.
RELEASE
RC1
=> {BP-10847} arch/{stm32|stm32f7|at32|samv7|imxrt}: fix for adc_setup

arch/xtensa/src/esp32/esp32_ble_adapter.c
The registered `task_create_wrapper` receives the `core_id`, but the current implementation ignores this parameter while calling `esp_task_create_pinned_to_core`. This commit fix this.
RELEASE
RC1
=> {BP-10859} esp32/ble: Fix task_create_wrapper CPU core ID passed as argument

tools/size_report.py
NodeMixin have attrubute called size and it is set property. Overwrite this property by _size but it will make report incompatible.
Create a new class NuttxDictExporter to renaming _size into size.
RELEASE
RC1
=> {BP-10879} fix: TreeNode has same attribute with NodeMixin

arch/x86_64/src/intel64/intel64_head.S
qemu-intel64 init does not work properly due to invalid stack initialization.
g_idle_topstack is a variable, it's content must be moved to rsp.
RELEASE
RC1
=> {BP-10899} arch: x86_64: Fix idle stack assignment

drivers/mtd/filemtd.c
In previous versions, during the teardown phase, the "open_blockdriver" would call the "mtd proxy" causing the "file mtd" node to be registered in the ftl. " node is registered in ftl. Therefore, we changed the behavior to find the corresponding inode by node name.
RELEASE
RC1
=> {BP-10909} filemtd:Fix teardown return error number EINVAL

arch/risc-v/src/mpfs/mpfs_entrypoints.c
Change bgtz t0, mpfs_opensbi_prepare_hart to tail-call to ensure there will be no link time error due to the jump offset being too large.
RELEASE
RC1
=> {BP-10922} mpfs/mpfs_entrypoints.c: Fix potential R_RISCV_JAL linker error

arch/arm/src/stm32h7/stm32_oneshot.c
There are some format warnings in printf-linke format strings. This patch removes them.
RELEASE
RC1
=> {BP-10841} arch/arm/src/stm32h7/stm32_oneshot.c: Fix format warnings.

arch/arm64/src/common/arm64_gicv3.c, include/nuttx/arch.h, include/nuttx/sched.h, sched/Kconfig, sched/sched/CMakeLists.txt, sched/sched/Make.defs, sched/sched/sched_smp.c
The smp function call allows specifying a function to be executed by another core. The wait parameter can be used to choose whether to wait or not for the other core to finish executing, it should be noted that there should be no waiting operations in the executed function.
This PR include:
1. Add smp function call support in sched;
2. ARM64 support smp function call, other architectures will be added gradually;
NA
board: 
qemu-armv8a:nsh_smp enable CONFIG_SMP_CALL
test code:
```
int test_smp_call_func(void *arg)
{
syslog(0, "test_smp_call_func:%d\n", up_cpu_index());
syslog_flush();
return 0;
}
int test_smp_call(int argc, FAR char *argv[])
{
nxsched_smp_call_single(1, test_smp_call_func, NULL, false);
nxsched_smp_call_single(1, test_smp_call_func, NULL, true);
nxsched_smp_call(0xf, …
```
=> sched: support smp function call

arch/risc-v/src/common/addrenv.h
The end address was off by 1, making it overflow to 0 (0x100000000 represented by u32 value).
RELEASE
RC1
=> {BP-10838} riscv/addrenv: Fix the user VMA end address

arch/arm64/src/common/arm64_cpu_idle.S
- I noticed that irq is enabled explicitly in arm64_cpu_idle.S
- The code is unnecessary since tasks, including the idle task, are created with irq enabled in up_initial_state()
- Should be none
- qemu-armv8a:netnsh_smp_hv with qemu-7.2.4
=> arch: arm64: Remove unnecessary code in arm64_cpu_idle.S

sched/sched/sched_smp.c
Exit immediately when finished processing the current CPU if there are no other CPUs to be processed.
smp call
qemu-armv8a:nsh_smp smp_call test
=> sched: smp call exit immediately when cpuset change to 0.

boards/sim/sim/sim/scripts/Make.defs
In the sim environment, to facilitate debugging, support for generating nuttx.map is added.
=> nuttx:generate nuttx.map file when enable debug link map.

Kconfig, include/assert.h
debug/assert: decouple configuration of show file name feature
add new config CONFIG_ASSERTIONS_FILENAME to library call assert(3) to decouple with CONFIG_DEBUG_ASSERTIONS
| Function         |CONFIG                            | Show filename/line |
| ---              | ---                              | ---                |
|assert(), ASSERT()|CONFIG_ASSERTIONS_FILENAME=y      | Yes                |
|assert(), ASSERT()|CONFIG_ASSERTIONS_FILENAME=n      | No                 |
|DEBUGASSERT()     |CONFIG_DEBUG_ASSERTIONS_FILENAME=y| Yes                |
|DEBUGASSERT()     |CONFIG_DEBUG_ASSERTIONS_FILENAME=n| No                 |
Resolve issue: https://github.com/apache/nuttx/issues/10416
ci-check
=> debug/assert: decouple configuration of show file name feature

drivers/usrsock/usrsock_rpmsg.c, include/nuttx/net/usrsock.h
There is a risk that interfaces such as psock_ioctl/psock_setsockopt will cause paramete to be not four-byte aligned after calculating the offset, so align the length of the structure with parameters by four bytes.
sim:local
=> usrsock: Make the field of usrsock_request native alignment

Documentation/applications/testing/fmemopen/index.rst, Documentation/applications/testing/index.rst
Test tool for fmemopen() function added to documentation.
Docs only. Should be merged with [testing: add fmemopen function test tool](https://github.com/apache/nuttx-apps/pull/2155).
=> Documentation: add fmemopen test entry

net/icmpv6/icmpv6_rnotify.c, net/utils/net_ipv6_pref2mask.c
1. Both IPv6 addresses and net masks should be stored in network byte order
2. Fix last 2 bytes of mask applying (although it seldom triggers)
`icmpv6_setaddresses` and `net_ipv6_pref2mask`
Manually, CI
=> net/icmpv6: Fix net mask logic in `icmpv6_setaddresses`

arch/arm/src/imxrt/imxrt_lpi2c.c, arch/arm/src/s32k1xx/s32k1xx_lpi2c.c, arch/arm/src/s32k3xx/s32k3xx_lpi2c.c
Addresses https://github.com/apache/nuttx/issues/10853 as reported by @thebolt
Non DMA version of the ISR was terminating on  end of packet (EOP) or STOP but the sequences is EOP->STOP so we must acknowledge either but end on  EOP and STOP.
Non DMA driver was Broken
imx1170 px4 nxp_fmurt1170-v1
=> NXP I2C non-DMA end only on stop with end of packet

drivers/net/tun.c
When tun_txavail_work is running, switch to tun_close thread and priv->lock will be destroyed, then switch back to tun_txavail_work thread, an error will occur when nxmutex_unlock(&priv->lock).
The previous modified mode was found to have a deadlock(net_lock and tun_lock) problem after stress testing, revert the previous patch, the new implementation was fix the error and avoids the deadlock issue.
Cortex-M33
=> tun: Fix the error of calling tun_close when tun_txavail or tun_txavail_work is executed

net/local/local.h, net/local/local_sendpacket.c, net/local/local_sockif.c
For datagram unix sockets, the `SO_SNDBUF` value imposes an upper limit on the size of outgoing datagrams.
Note: We don't support to change the buffer size yet, so only add support to getsockopt now.
Refs: https://man7.org/linux/man-pages/man7/unix.7.html
`getsockopt` of local socket
CI
=> net/local: Support `SO_SNDBUF` option in `getsockopt`

arch/risc-v/src/litex/litex_emac.c, include/nuttx/net/mii.h
Adds support for using the microchip KSZ8061 ethernet PHY instead of the default DP83848C.
KSZ8061 is available to use on Litex, using custom hardware.
Custom hardware running Litex and using KSZ8061 PHY.
=> arch/risc-v/litex/litex_emac: Add support for KSZ8061 ethernet PHY.

arch/risc-v/include/litex/irq.h, arch/risc-v/src/litex/litex_gpio.c
Previously, GPIO interrupts were not correctly mapped to the peripheral base register responsible for the interrupt.
Change the IRQ number calculation so the interrupts work correctly on all GPIO peripheral bases.
Interrupts are mapped correctly when enabled on port index > 0.
Custom hardware using Litex.
=> arch/risc-v/litex/litex_gpio: Fix ISR dispatch when using higher GPIO indexes.

sched/clock/clock_adjtime.c, sched/group/group_create.c, sched/group/group_killchildren.c, sched/group/group_setupidlefiles.c, sched/group/group_setuptaskfiles.c, sched/pthread/pthread_detach.c, sched/task/task_delete.c
1. group/killchildren: replace syscall(2) to kernel api
syscall(2) cannot be called from kernel space
2. sched: fix the minor style issue
N/A
ci-check
=> group/killchildren: replace syscall(2) to kernel api

arch/arm/src/imxrt/imxrt_lpi2c.c, arch/arm/src/s32k1xx/s32k1xx_lpi2c.c, arch/arm/src/s32k3xx/s32k3xx_lpi2c.c
Related to https://github.com/apache/nuttx/issues/10853 & https://github.com/apache/nuttx/pull/11012
With DMA enabled on some I2C channels but not all the Non DMA channels were failing.
The cause was condition the status with only the enabled interrupts on non DMA chennels. This conditioning needs  to only happen in DMA enabled channels
Without this fix:  With DMA enabled on some I2C channels but not all the Non DMA channels were failing.
imx1170 PX4 nxp_fmurt1170-v1 (with I2C DMA on 1,2,3 and no DMA on 6)
=> NXP lpi2c DMA transaction only need the status conditioned 

tools/cfgdefine.c
fix 
In file included from cfgdefine.c:26:
cfgdefine.c: In function ‘skip_space’:
cfgdefine.c:91:26: warning: array subscript has type ‘char’ [-Wchar-subscripts]
91 |   while (*ptr && isspace(*ptr)) ptr++;
|                          ^~~~
cfgdefine.c: In function ‘find_name_end’:
cfgdefine.c:99:27: warning: array subscript has type ‘char’ [-Wchar-subscripts]
99 |   while (*ptr && (isalnum(*ptr) || *ptr == '_')) ptr++;
|                           ^~~~
cfgdefine.c: In function ‘find_value_end’:
cfgdefine.c:107:27: warning: array subscript has type ‘char’ [-Wchar-subscripts]
107 |   while (*ptr && !isspace(*ptr))
|                           ^~~~
cfgdefine.c:116:45: warning: array subscript has type ‘char’ [-Wchar-subscripts]
116 |           do ptr++; while (*ptr && !isspace(*ptr) && *ptr != …
=> tools/cfgdefine.c: Resolve compile warning array subscript has type 'char'

arch/Kconfig, arch/sim/src/sim/posix/sim_hostmemory.c, arch/sim/src/sim/sim_heap.c, arch/sim/src/sim/sim_internal.h, arch/sim/src/sim/sim_textheap.c, arch/sim/src/sim/win/sim_hostmemory.c, binfmt/libelf/libelf_addrenv.c, include/nuttx/arch.h, libs/libc/modlib/modlib_depend.c, libs/libc/modlib/modlib_init.c, libs/libc/modlib/modlib_load.c, libs/libc/modlib/modlib_symbols.c, libs/libc/modlib/modlib_unload.c, sched/module/mod_insmod.c, sched/module/mod_rmmod.c
1. simplify textheap logic for arch/sim
2. libs/modlib: remove duplicate dumpbuffer
3. add arch memory allocator for data section.
4. fix compile warning.
add up_dataheap_memalign, up_dataheap_free api
vela test
=> libs/modlib: optimize code and add arch api for allocating data section

Documentation/applications/testing/sd_bench/index.rst
Documentation to accompany new sd_bench test application.
Related to https://github.com/apache/nuttx-apps/pull/2164
Documentation.
Building documentation locally.
=> Documentation: Add entry for sd_bench tool.

libs/libxx/libcxx.defs
Silence two warnings when building libcxx with GCC 12.2.0 and std=c++2b:
libcxx/src/charconv.cpp_CXXFLAGS += -Wno-attributes
- Results from libcxx fallback to use __always_inline__ when exclude_from_explicit_instantiation isn't available.
libcxx/src/locale.cpp_CXXFLAGS += -Wno-attributes
- Results from the expansion of _LIBCPP_CLASS_TEMPLATE_INSTANTIATION_VIS. Should be fine to ignore.
Clean build when building libcxx.
GCC 12.2.0 riscv-gnu-toolchain with std=c++2b. `arty_a7:knsh` with cxxtest enabled.
=> libs/libcxx: Silence warnings when building libcxx.

include/assert.h
assert: rename __ASSERT to \_\_ASSERT\_\_ to avoid conflict
The definition of __ASSERT has special define in some OS and librarys, rename to \_\_ASSERT\_\_ to avoid conflict
N/A
ci-check
=> assert: rename __ASSERT to __ASSERT__ to avoid conflict 

arch/sim/src/sim/sim_wifidriver.c
Fix the simwifi scan error that Using the uninitialized buffer causes the out of bounds.
Add a terminator for the rbuf, and the simwifi scan can return the scan results.
The command 'wapi scan wlan0' works fine.
=> sim/wifidriver: Fix the scan error.

drivers/usbdev/Kconfig
drivers/usbdev: config USBDEV_TRACE_INITIALIDSET when disbale USBDEV_TRACE
because usbtrace is valid when enable USBDEV_TRACE or DEBUG_FEATURE && DEBUG_USB,
vela test
=> drivers/usbdev: config USBDEV_TRACE_INITIALIDSET when disbale USBDEV_TRACE

arch/sim/src/sim/sim_wifidriver.c
In the SIM emulator, allow the SIM-WiFi to connect the hidden SSID.
N/A
We can connect the hidden SSID, using the following steps:
1.`ifup wlan0`
2.`wapi mode wlan0 2`
3.`wapi psk wlan0 <flags>`
4.`wapi essid wlan0 <hidden_ssid>`
=> simwifi: Support that simwifi connects to the hidden ssid.

arch/risc-v/CMakeLists.txt, arch/risc-v/src/CMakeLists.txt, arch/risc-v/src/cmake/Toolchain.cmake, arch/risc-v/src/cmake/platform.cmake, arch/risc-v/src/common/CMakeLists.txt, arch/risc-v/src/qemu-rv/CMakeLists.txt, boards/risc-v/qemu-rv/rv-virt/CMakeLists.txt, boards/risc-v/qemu-rv/rv-virt/src/CMakeLists.txt, libs/libc/machine/risc-v/common/CMakeLists.txt, libs/libc/machine/risc-v/gnu/CMakeLists.txt, libs/libc/machine/risc-v/rv32/CMakeLists.txt, tools/ci/testlist/risc-v.dat
1. init RISC-V cmake build
2. enable rv32 smp rv64 smp ci cmake build
cmake currently does not support non-FlatBuild,
need disable ELF and LOADABLE when compiling other defconfigs
risc-v arch
```
$ cmake -B build -DBOARD_CONFIG=rv-virt/smp64  -GNinja  # for rv32:rv-virt/smp
$ cmake --build build -t menuconfig
```
=> cmake:init RISC-V cmake qemu-rv build

libs/libc/stdlib/lib_exit.c, tools/sethost.sh
fix
```shell
CPP: nuttx-names.in-> nuttx-names.dat
LD: nuttx
/usr/lib/gcc/x86_64-pc-msys/13.2.0/../../../../x86_64-pc-msys/bin/ld: nuttx.rel:/d/a/nuttx_windows/nuttx_windows/nuttxspace/nuttx/libs/libc/stdlib/lib_exit.c:48: multiple definition of `__dso_handle'; /usr/lib/gcc/x86_64-pc-msys/13.2.0/crtbegin.o:cygming-crtbeg:(.data+0x0): first defined here
```  
tools/sethost.sh: add for MSYS2 MSYS environment
none
We tested on platform MSYS2 and Alpine linux
=> libs/libc/stdlib/lib_exit.c: fix multiple definition of __dso_handle and sethost.sh: add MSYS environmen for msys2

arch/arm/src/stm32/stm32_otghsdev.c
Fix compile error
System does not crash when using USB.  Unsure of any other side-effects.
=> Fix #11005

binfmt/binfmt_execmodule.c, fs/inode/fs_files.c, fs/vfs/fs_dup.c, fs/vfs/fs_dup2.c, fs/vfs/fs_fcntl.c, include/nuttx/fs/fs.h, include/unistd.h, libs/libc/spawn/lib_psfa_adddup2.c, net/local/local_recvmsg.c, sched/task/task_create.c, sched/task/task_spawn.c
modify:
1. Ensure that the child task copies all fds of the parent task,
including those with O_CLOEXE.
2. Make sure spawn_file_action is executed under fd with O_CLOEXEC,
otherwise it will fail.
3. When a new task is activated or exec is called, close all fds
with O_CLOEXEC flags.
refs: https://man7.org/linux/man-pages/man2/dup.2.html
refs: https://man7.org/linux/man-pages/man2/dup.2.html
The two file descriptors do not share file descriptor flags (the
close-on-exec flag).  The close-on-exec flag (FD_CLOEXEC; see
fcntl(2)) for the duplicate descriptor is off.
Because popen no longer needs to rely on intermediate
tasks to start command tasks.
posix_spawn/exec_module/task_create/... with exec or start new task
Vela
=> Follow o_cloexe semantics when calling the exec function

arch/arm/src/imxrt/imxrt_serial.c, arch/arm/src/s32k1xx/s32k1xx_serial.c, arch/arm/src/s32k3xx/s32k3xx_serial.c
As reported by @danielappiagyei-bc [here](https://github.com/apache/nuttx/issues/10912) with more discussion [here](https://github.com/apache/nuttx/pull/11020)  
With TCD set to loop, there is a window where the
DMA has raised Done, but not reloaded the TCD, resetting
count and clearing Done.
In this window  imxrt_dmach_getcount could then return 0.
Resulting in imxrt_dma_nextrx returning RXDMA_BUFFER_SIZE.
Which is not a valid index in the FIFO.
Since the count will be set to RXDMA_BUFFER_SIZE. When the DMA
engine completes the TCD reload. The imxrt_dma_nextrx would
return 0. Therefore:
(RXDMA_BUFFER_SIZE - dmaresidual) % RXDMA_BUFFER_SIZE
accomplishes this.
Without this change serial data could be corrupted.
imxrt1170
=> NXP Serial overcome race where DMA has not fetched TCD again

arch/sim/src/sim/sim_wifidriver.c
Fix the error of the need length calculation when scanning.
N/A
When scanning in sim, we should not get an out-of-bounds error in `copy_scan_results`.
=> simwifi: Fix the error of the need length for scan bssinfo.

mm/mm_heap/mm_free.c
mm: both use spin_lock_irqxx() when operated delaylist
align with free_delaylist()
mm
SIM
=> mm: both use spin_lock_irqxx() when operated delaylist

tools/simwifi/sim_wifi.sh, tools/simwifi/udhcpc.script
Fix the problem that host wlan0 can not obtain IP, and when the defwan is wlan0, the sim can not access the Internet.
When the host wlan0 successfully connects to a WiFi, and obtains an IP address through udhcpc, the following operations will be performed.
- Set the IP for host wlan0.
- Add the dns server (8.8.8.8) to the file `/etc/resolv.conf`.
- Add an default route through the wlan0 interface.
All these configurations will be clean by the command `sim_wifi.sh clean`.
We can verify the changes using the following steps:
1. Set the defwan as wlan0. ` sudo ./toos/simwifi/sim_wifi.sh init wlan0 rnc`
2. In sim, configure the wlan0 and connects a WiFi.  Then access the Internet.
3. Check the configurations of HOST,  including the ip of wlan0, dns server in the `/etc/resolv.conf`, and the …
=> simwifi: host wlan0 obtains ip and set dns for wlan0 in the defwan wlan0

drivers/wireless/bluetooth/Kconfig
bluetooth rpmsg depends on RPTUN
CI
=> bluetooth rpmsg depends on RPTUN

drivers/can/can.c, include/nuttx/can/can.h
FYI @davids5 
As per [this issue](https://github.com/apache/nuttx/issues/3927) this PR adds new IOCTLs to manage queued writes to the CAN driver that prevent the driver being closed in the event of a CAN physical disconnect or other issues
None expected as no change to existing IOCTLs. But does need lower-half driver changes which I will submit for the SAMA5D2 mcan driver.
Custom board with a SAMA5D27C-D1G and 2x CAN interfaces. With the SAMA5 driver changes too the following tests were done:
1. Continuous CAN reads and writes set up using a test program.
2. The CAN transceiver on the board has a silent mode which can be enabled to stop TX data hitting the bus. Enabling this causes CAN transmission to stop as expected, and the text code then attempted to close the open CAN driver causing …
=> CAN. Add new ioctls

arch/arm/src/sama5/sam_mcan.c
As per issue [here](https://github.com/apache/nuttx/issues/3927) and [this PR](https://github.com/apache/nuttx/pull/11061/commits) here are the changes I needed to make for the SAMA5D2 processor to have this all work as required.
None to existing code.
As per other PR, on custom board with SAMA5D2C-D1G and 2x CAN interfaces
=> SAMA5D2 add new mcan ioctls

include/nuttx/net/netconfig.h
`NET_SOCK_TYPE` is used for ioctl sockets only, they can set `O_CLOEXEC` explicitly.
Do not inherit temporary fds created with `NET_SOCK_TYPE` for ioctl.
CI
=> net/netconfig: Enable SOCK_CLOEXEC for ioctl sockets

include/nuttx/fs/fs.h, include/stdio.h, include/wchar.h, libs/libc/libc.h, libs/libc/stdio/lib_clearerr.c, libs/libc/stdio/lib_fclose.c, libs/libc/stdio/lib_fflush.c, libs/libc/stdio/lib_fputc.c, libs/libc/stdio/lib_fputs.c, libs/libc/stdio/lib_fputwc.c, libs/libc/stdio/lib_freopen.c, libs/libc/stdio/lib_libfflush.c, libs/libc/stdio/lib_libflushall.c, libs/libc/stdio/lib_libfwrite.c, libs/libc/stdio/lib_putc.c, libs/libc/stdio/lib_puts.c, libs/libc/stdio/lib_putwchar.c, libs/libc/stdio/lib_wrflush_unlocked.c, libs/libc/stream/lib_stdoutstream.c, libs/libc/stream/lib_stdsostream.c
- libc/stdio: lib_fwrite_unlocked must call lib_fflush_unlocked with true 
- libc/stdio: Remove bforce from lib_fflush[_unlocked]
- stdio: Implement [clearerr|putc|fflush]_unlocked 
stdio function
ci
=> Improve stdio unlock version function

sched/task/spawn.h, sched/task/task_posixspawn.c, sched/task/task_spawn.c, sched/task/task_spawnparms.c
This removes the obsolete spawn_proxyatts() function, which was used to set the posix spawn proxy task's signal mask, among other things. Why does it need to be removed ? Now it changes the spawning process's (nsh in most cases) signal mask unexpectedly, while previously only the temporary proxy task was affected.
Fix the signal mask by setting it directly, much simpler this way.
posix_spawn(), fixes regression after https://github.com/apache/nuttx/pull/9100
rv-virt:knsh64 and MPFS (kernel mode)
=> sched/task: Remove spawn_proxyattrs as obsolete implementation 

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_entrypoints.c, arch/risc-v/src/mpfs/mpfs_opensbi.c
This removes "mpfs_opensbi_pmp_setup" and moves the logic to a lower level routine. Also an option to provide a board specific PMP configuration is given, instead of just opening up the entire SoC's memory for each hart.
MPFS and PMP configuration only.
MPFS
=> arch/mpfs: Add option for board specific PMP configuration

tools/configure.c, tools/sethost.sh
Add CONFIG_EXPERIMENTAL for configure windows native
We tested on platform MSYS2 and Alpine linux
=> tools/configure.c and tools/sethost.sh Add CONFIG_EXPERIMENTAL for configure windows native

include/spawn.h, libs/libc/spawn/CMakeLists.txt, libs/libc/spawn/Make.defs, libs/libc/spawn/lib_psa_destroy.c
When building with a c++ compiler and GCC 12.2.0, the following warning is emitted:
nuttx/include/spawn.h:178:40: warning: statement has no effect [-Wunused-value]
178 | #define posix_spawnattr_destroy(attr) (0)
Casting the attribute value to void has the same effect, whist silencing this warning.
Silence warning
- Build with `sim:ostest` to verify normal build.
- Build with custom application to verify build in our environemnt.
=> nuttx/include/spawn: Suppress compiler warning for posix_spawnattr_destroy.

arch/arm/src/s32k1xx/s32k1xx_flexcan.c, arch/arm/src/s32k3xx/s32k3xx_flexcan.c
This patch explicitly forces the srr bit to be recessive as per CAN specification  ISO 118898-1.
Tested on s32k1xx not FD, not tested on s32k3xx
=> FIX: s32kxxx flexcan doesn't set srr bit for extended frames

arch/sim/src/sim/sim_wifidriver.c
Because the Chinese essid obtained by wpa_cli is encoded. So, we directly use the essid saved in wifidev.
N/A
When we use the wapi to connect an AP with the Chinese characters, then we can use the command `wapi show wlanx` to see that the AP essid is correctly displayed.
=> simwifi: Support that get the connected Chinese essid.

drivers/usrsock/usrsock_rpmsg_server.c
In `drivers/rptun/rptun.c`, we have a `rptun_is_recursive` function, which lets rptun thread run recursively. Then the `usrsock_rpmsg_ept_cb` may be called inside `usrsock_rpmsg_ept_cb`, which can cause some unexpected behavior, so we add a queue to keep the order of incoming messages to reduce the complexity.
- usrsock_rpmsg_server: Save iov and remain per endpoint
- Prepare for keeping msg order, also helps sendto to work correctly on multiple endpoints.
- usrsock_rpmsg_server: Keep msg order in recursive call
Usrsock rpmsg server only.
Manually.
=> usrsock_rpmsg_server: Keep msg order in recursive call

arch/Kconfig, mm/Kconfig
Fixes bad dependency for kmm_map; kmap does not need ARCH_VMA_MAPPING => remove the dependency
Produces build error if MM_SHM is not enabled via:
```
#ifdef CONFIG_ARCH_VMA_MAPPING
```
Remove build error when enabling CONFIG_MM_KMAP without enabling CONFIG_MM_SHM
CI pass
=> mm/kmap: Fix bad dependency to ARCH_VMA_MAPPING

arch/risc-v/include/arch.h, arch/risc-v/src/common/riscv_addrenv.c
Fixes issue with page table addresses; virtual address is used when physical address should be used.
Also improve commenting on the architecture dependent address environment structure (it has confused me too many times -> add comment to remove confusion)
None, since all targets currently use vaddr=paddr for page pool, but it is good to fix this regardless.
rv-virt:knsh64
=> riscv_addrenv: Fix static page table mapping (paddr instead of vaddr)

arch/arm/src/cxd56xx/cxd56_gnss.c
Support to get gnss firmware version and fix typo.
=> arch: cxd56xx: Support to get gnss firmware version

arch/arm/src/stm32/Kconfig
-  arch/stm32: remove unused STM32_UART_RXDMA and STM32_UART_TXDMA flags
These flags are not used in the code.
SERIAL_HAVE_RXDMA and SERIAL_HAVE_TXDMA flags are used instead.
STM32_UART_TXDMA flag is not even defined in Kconfig
- arch/stm32: STM32_FOC_G4_ADCCHAN0_WORKAROUND depend on STM32G4
remove unused flags
CI
=> arch/stm32: cosmetic fixes

include/net/if.h, include/nuttx/ethtool.h, include/nuttx/net/ioctl.h
We reuse the linux platform code when adapting the matter library, in order to compile through, so first add the ethtool related definition
risc-v32 board
=> ioctl: add definitions related to ethtool

net/netdev/netdev_ioctl.c
some tools use this command to distinguish which device returned via getifaddrs() are wireless network device.
risc-v32 board and sim:local
=> ioctl: add SIOCGIWNAME support

arch/sim/src/sim/sim_netdriver.c
if the configured SIM_NETDEV_BUFSIZE < host MTU, there will be issues with access out of bounds
sim:linux private defconfig
=> sim_netdriver: some sim defconfig have problems when using the network

net/igmp/igmp.h, net/igmp/igmp_join.c, net/igmp/igmp_leave.c, net/inet/ipv4_setsockopt.c, net/netdev/netdev_ioctl.c, net/udp/udp.h, net/udp/udp_close.c, net/udp/udp_conn.c
add ref count for ipv4 multicast and leave the multicast group when close. behavior alignment with linux.
risc-v32 board and sim:local
=> udp: modify ipv4 multicast to allow different conn to join simultaneously

Documentation/applications/nsh/index.rst, Documentation/applications/nsh/running_apps.rst, Documentation/applications/tools/index.rst, Documentation/components/nxgraphics/nx.rst, Documentation/components/nxgraphics/nxfonts.rst, Documentation/guides/customapps.rst, Documentation/implementation/critical_sections.rst, Documentation/implementation/index.rst, Documentation/implementation/processes_vs_tasks.rst, Documentation/index.rst, Documentation/platforms/arm/stm32f4/boards/stm32f401rc-rs485/index.rst
- Documentation: fix warning
- Documentation: migrate "NuttX Graphics Subsystem (NX)" from wiki
- Documentation: migrate "Wide Font Support" from wiki
- Documentation: migrate "Running Applications from NSH" from wiki
- Documentation: migrate "Linux Processes vs NuttX Tasks" from wiki
- Documentation: migrate "apps/tools/mkromfsimg.sh" from wiki
- Documentation: CONFIG_USER_ENTRYPOINT was changed to CONFIG_INIT_ENTRYPOINT
- Documentation: migrate "SMP Critical Sections" from wiki
- Documentation: migrate "Critical Section Monitor" from wiki
local
=> Documentation: migrate some wiki pages

net/tcp/Kconfig, net/tcp/tcp.h, net/tcp/tcp_conn.c, net/tcp/tcp_seqno.c, net/utils/CMakeLists.txt, net/utils/Make.defs, net/utils/net_getrandom.c, net/utils/utils.h
- Patches included:
- net/tcp: Take out get random process as common function
- net/tcp: Support initial sequence number described in RFC 6528
Support initial sequence number described in RFC 6528
https://github.com/apache/nuttx/blob/eddcc0f51b9c8f6c7ff79d6f8d163ced13a66b45/net/tcp/Kconfig#L166-L170
TCP's initial sequence number, controlled by Kconfig option
Manually, CI
=> net/tcp: Support initial sequence number described in RFC 6528

Documentation/contributing/coding_style.rst
Copyright notice and author contact/information should not be included in file header anymore. Only standard Apache 2.0 licensing information should be used.
This should be correct remove, right?
Docs only.
=> documentation/contributing: remove copyright notice in file header

fs/inode/fs_files.c
- fs_files.c: make sure that fs_getfilep is not interrupted when holding mutex
this fixes the issue https://github.com/apache/nuttx/issues/6012
fix https://github.com/apache/nuttx/issues/6012
b-g431b-esc1
Not tested enough for SMP targets (only some basic tests on qemu sabre-6quad/smp configuration).
I would be grateful if someone could help me verify whether this change doesn't break the performance of SMP in accessing file system or has other unwanted effects.
=> fs_files.c: make sure that fs_getfilep is not interrupted when holding mutex

boards/xtensa/esp32s3/common/scripts/legacy_sections.ld
* esp32s3: Fix issue regarding IRAM-enabled ISRs by fixing the linker
After https://github.com/apache/nuttx/pull/11007/ was merged, the path for some files changed, requiring the linker to be fixed to make it run from the internal memory once again.
Make the IRAM-enabled interrupts run successfully once again.
Internal CI testing + ESP32-S3-DevKitC-1 v1.0
=> esp32s3: Fix issue regarding IRAM-enabled ISRs by fixing the linker

libs/libc/stdlib/lib_realpath.c
libc/realpath: allocate link buffer of pseudofs to save stack
The link buffer of pseudofs will occupy too much of stack, allocate from the heap to save the stack usage.
N/A
ci-check
=> libc/realpath: allocate link buffer of pseudofs to save stack

drivers/rptun/rptun.c, drivers/serial/uart_rpmsg.c
1. drivers/rptun: check the status before stop remote proc 
Race condition if the remote proc is stoped during initialization phase
```
| #0  0x0249f959 in rpmsg_destroy_ept (ept=0xffffffc0) at open-amp/lib/rpmsg/rpmsg.c:376
| #1  0x024a938c in rpmsg_deinit_vdev (rvdev=0xf2303a48) at open-amp/lib/rpmsg/rpmsg_virtio.c:971
| #2  0x02117e33 in rptun_dev_stop (rproc=0xf2303a04, stop_ns=true) at rptun/rptun.c:891
| #3  0x021181d8 in rptun_do_ioctl (priv=0xf2303a00, cmd=11010, arg=0) at rptun/rptun.c:922
| #4  0x02119722 in rptun_ioctl_foreach (cpuname=0x0, cmd=11010, value=0) at rptun/rptun.c:1086
| #5  0x0211b9df in rptun_poweroff (cpuname=0x0) at rptun/rptun.c:1378
| #6  0x02053aa6 in board_power_off (status=0) at sim/sim_head.c:206
| #7  0x0253d65c in boardctl (cmd=65283, arg=0) at …
```
=> drivers/rptun: check the status before stop remote proc 

arch/arm/src/CMakeLists.txt, arch/risc-v/src/CMakeLists.txt, drivers/misc/CMakeLists.txt, drivers/sensors/CMakeLists.txt, fs/vfs/CMakeLists.txt, libs/libc/gpsutils/CMakeLists.txt, libs/libc/machine/CMakeLists.txt, libs/libc/misc/CMakeLists.txt, libs/libc/string/CMakeLists.txt
Some compilation problems were encountered when the cmake compilation tool was used locally to adapt the Matter compilation.
After the compilation is complete and verified, the nuttx related changes are collated and submitted.
risc-v32 and sim:local
=> Solve some problems encountered during cmake compilation

Documentation/guides/index.rst, Documentation/guides/stm32ccm.rst, Documentation/guides/stm32nullpointer.rst, Documentation/implementation/bottomhalf_interrupt.rst, Documentation/implementation/index.rst, Documentation/reference/os/index.rst
- Documentation: migrate "STM32 Null Pointer Detection" from wiki 
- Documentation: migrate "STM32 CCM Allocator" from wiki
- Documentation: fix warning
- Documentation: migrate "Bottom-Half Interrupt Handlers" from wiki
local
=> Documentation: migrate more wiki pages 

arch/sim/src/sim/sim_wifidriver.c
Fix a compilation error, as follows：
sim/sim_wifidriver.c:569:31: warning: implicit declaration of function ‘hex2num’ [-Wimplicit-function-declaration]
569 |                         val = hex2num(*pos);
|                               ^~~~~~~
N/A
The SIM-WiFi can be compiled seccessfully.
=> simwifi: Fix a compile error.

arch/arm/src/stm32h7/stm32_serial.c
If using flow control with a high CTS the thread may be blocked forever on the second transmit attempt due to waiting on the txdma semaphore. The calling thread can then never make progress and release any resources it has taken, thus may cause a deadlock in other parts of the system.
The implementation differs in behavior from interrupt-driven TX and the STM32F7 TXDMA . It should not implicitly wait on a taken semaphore but return immediately and let the upper layers decide on what to do next.
See a more detailed analysis here: https://github.com/PX4/PX4-Autopilot/pull/22302
cc @davids5
=> stm32h7/serial: Do not wait on TXDMA semaphore

arch/sim/src/sim/posix/sim_hostmemory.c, arch/sim/src/sim/sim_heap.c, arch/sim/src/sim/sim_internal.h, arch/sim/src/sim/win/sim_hostmemory.c, fs/procfs/fs_procfsmeminfo.c, include/malloc.h, mm/mm_heap/mm.h, mm/mm_heap/mm_free.c, mm/mm_heap/mm_mallinfo.c, mm/mm_heap/mm_malloc.c, mm/mm_heap/mm_memalign.c, mm/mm_heap/mm_realloc.c, mm/tlsf/mm_tlsf.c
Add the usmblks field to mallinfo to record the maximum space allocated historically in the system
https://man7.org/linux/man-pages/man3/mallinfo.3.html#:~:text=mmap(2).-,usmblks,-This%20field%20is
=> mm: record the maximum system memory usage

boards/xtensa/esp32s3/common/scripts/legacy_sections.ld
This PR intends to fix the PSRAM support on ESP32S3 when Stack Smash Protection is enabled (CONFIG_STACK_CANARIES=1).
During PSRAM initialization and flash operations, the Cache needs to be disabled, so all data and code for the aforementioned scope is required to be placed in Internal RAM (DRAM and IRAM regions).
Only for PSRAM-enabled configurations on ESP32S3.
- Successful execution of `ramtest` in `esp32s3-devkit:psram_octal` with `CONFIG_STACK_CANARIES=1`
=> boards/esp32s3: Link stack checking function and data to SRAM when enable flash or PSRAM driver

boards/arm/sama5/sama5d2-xult/Kconfig, boards/arm/sama5/sama5d2-xult/src/sam_bringup.c, boards/arm/sama5/sama5d2-xult/src/sama5d2-xult.h
add support for onboard qspi flash with nxffs
depends on #11150 for qspi support
sama5d2-xult board qspi flash can be used as filesystem.
Tested on xult board.
=> sama5d2-xult: add support for QSPI flash and nxffs

include/nuttx/arch.h
arch/textheap: add _heapmember declare for text and data heap
It was accidentally deleted on PR:#11043
local test
=> arch/textheap: add _heapmember declare for text and data heap

libs/libm/newlib/Make.defs
Change newlib download site from ftp to more secure https.
None
Build pass with `CONFIG_LIBM_NEWLIB=y`
=> libm/newlib: Change the download site to https

arch/arm/src/imxrt/imxrt_serial.c, arch/arm/src/s32k1xx/s32k1xx_serial.c, arch/arm/src/s32k3xx/s32k3xx_serial.c
If using flow control with a high CTS the thread may be
blocked forever on the second transmit attempt due to waiting
on the txdma semaphore.  The calling thread can then never
make progress and release any resources it has taken, thus
may cause a deadlock in other parts of the system.
The implementation differs in behavior from interrupt-driven
TX. It should not implicitly wait on a taken semaphore but
return immediately and let the upper layers decide on what to
do next.
Prevent blocking
=> NXP Serial Do not wait on TXDMA semaphore

arch/arm/src/armv8-m/nvic.h
=> arch/armv8-m: Fix typo error for NVIC_SYSHCON_HARDFAULTPENDED

arch/xtensa/src/esp32s3/Kconfig, arch/xtensa/src/esp32s3/Make.defs, arch/xtensa/src/esp32s3/esp32s3_partition.c, arch/xtensa/src/esp32s3/esp32s3_partition.h, arch/xtensa/src/esp32s3/esp32s3_wifi_adapter.c, arch/xtensa/src/esp32s3/esp32s3_wireless.c, arch/xtensa/src/esp32s3/esp32s3_wireless.h, boards/xtensa/esp32s3/esp32s3-devkit/src/esp32s3_bringup.c
- Support partition and OTA device
- Support multiple PHY init data bin
If `CONFIG_ESP32S3_PHY_INIT_DATA_IN_PARTITION` and `CONFIG_ESP32S3_SUPPORT_MULTIPLE_PHY_INIT_DATA` are enabled, PHY initialization data (PHY initialization data is used for RF calibration) will be loaded from a partition, make sure that PHY data partition is included (type: 'data', subtype: 'phy').
The corresponding PHY init data type can be automatically switched according to the country code, China's PHY init data bin is used by default, country code can be modified through the wapi command: `wapi country <ifname> <country code>`.
Successful execution of `wapi country <ifname> <country code>` in `esp32s3-devkit:wifi` with `CONFIG_ESP32S3_PHY_INIT_DATA_IN_PARTITION=y` and …
=> xtensa/esp32s3: Support multiple PHY init data bin

arch/sim/src/sim/posix/sim_rawgadget.c, arch/sim/src/sim/sim_usbdev.c, drivers/usbdev/usbdev_fs.c
driver/usbdev: Solve some problems of USB hotplug
support sim raw usbdev hotplug simualtor
config: sim:usbdev 
conn 0
disconn 0
adb shell ls
=> driver/usbdev: Solve some problems of USB hotplug

mm/mm_heap/mm.h, mm/mm_heap/mm_free.c, mm/mm_heap/mm_malloc.c, mm/tlsf/mm_tlsf.c
since it's enough to protect per cpu delay list by disabling interrupt
code refactor
ci
=> mm: Remove mm_spinlock

boards/arm/stm32h7/linum-stm32h753bi/src/CMakeLists.txt, boards/arm/stm32h7/linum-stm32h753bi/src/Makefile, boards/arm/stm32h7/linum-stm32h753bi/src/stm32_bringup.c, boards/arm/stm32h7/linum-stm32h753bi/src/stm32_userleds.c
Summary
Added support to userleds on board LINUM-STM32H753BI
Impact
The user can enable and use LED driver.
Testing
Enabled LED driver on menuconfig and tested on application.
=> stm32h7/linum-stm32h753bi: Added suport to userlerds library.

arch/sim/src/sim/sim_heap.c
since it's enough to protect per cpu data with irq disabling
ci
=> arch/sim: Replace [enter|leave]_critical_section with up_irq_[save|restore]

fs/inode/fs_files.c, fs/procfs/fs_procfsproc.c, include/nuttx/fs/fs.h, include/nuttx/spinlock.h
1. fs/inode: improve the performance of get file pointer
Remove file locks and enter critical sections to protect file lists
2. fs/inode: minor change to save the code size
```
Before:
360641    7889    4064  372594   5af72 nuttx
After:
360313    7889    4064  372266   5ae2a nuttx
```
N/A
ci-check
=> fs/inode: improve the performance of get file pointer

drivers/note/note_driver.c, drivers/note/noteram_driver.c, include/nuttx/sched_note.h
When we record data and dump data, they are all executed within the system, and there is no need to consider the issue of big or small endianness.
sim:note
=> note: delete sched_note_flatten

arch/arm/src/rp2040/Kconfig, arch/arm/src/rp2040/rp2040_pwm.c, boards/arm/rp2040/common/src/rp2040_pwmdev.c
Currently, we cannot build with ```CONFIG_PWM_NCHANNELS=1```.  
Perhaps it has just never been tested...
=> rp2040: pwm: Fix errors at CONFIG_PWM_NCHANNELS=1

arch/arm/src/arm/arm_doirq.c, arch/arm/src/common/arm_internal.h
and remove the duplicated arm_doirq and arm_ack_irq prototype
no any functionality change
ci
=> arch/arm: Let's old arm's arm_doirq return register context like armv7-a

drivers/serial/serial.c
tcsendbreak is not a cancellation point -> remove cancel point logic from it.
Reference:
https://pubs.opengroup.org/onlinepubs/009695399/functions/xsh_chap02_09.html
POSIX standard compliance
None
=> uart_tcsendbreak: Remove cancel point, as tcsendbreak is not one

arch/arm/src/stm32/stm32_foc.c, arch/arm/src/stm32/stm32_foc.h, arch/arm/src/stm32f7/stm32_foc.c, arch/arm/src/stm32f7/stm32_foc.h
stm32/foc: add support for board-specific ioctl
CI
=> stm32/foc: add support for board-specific ioctl

arch/arm/src/stm32/stm32_adc.c
stm32/stm32_adc.c: protect irq_attach with refcounter
irq_attach should only be called once for ADCs that share a common interrupt handler. We can move irq_attach to just before interrupts are enabled.
fix occasional ADC irq handler overwrites for FOC dual motor configuration on stm32f4
odrive3.6
=> stm32/stm32_adc.c: protect irq_attach with refcounter

Documentation/platforms/risc-v/esp32c3/index.rst, Documentation/platforms/risc-v/esp32c6/index.rst, tools/ci/cibuild.sh, tools/ci/docker/linux/Dockerfile
- Upgraded to xpack-riscv-none-elf-gcc-12.3.0-2 to resolve symbol recognition issues in riscv-none-elf-gdb,
as reported in https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/issues/22.
- Expected to enhance toolchain stability with no negative side effects.
- Verified with rv-virt:netnsh and rv-virt:netnsh64 configurations
=> Documentation, tools: Bump xpack-riscv-none-elf-gcc to 12.3.0-2

arch/arm/src/stm32/stm32_foc.c, arch/arm/src/stm32/stm32_foc.h, arch/arm/src/stm32f7/stm32_foc.c, arch/arm/src/stm32f7/stm32_foc.h, boards/arm/stm32/b-g431b-esc1/src/stm32_foc.c, boards/arm/stm32/common/src/stm32_ihm07m1.c, boards/arm/stm32/common/src/stm32_ihm08m1.c, boards/arm/stm32/common/src/stm32_ihm16m1.c, boards/arm/stm32f7/steval-eth001v1/src/stm32_foc.c, drivers/motor/foc/foc_dev.c, drivers/motor/foc/foc_dummy.c, include/nuttx/motor/foc/foc.h, include/nuttx/motor/foc/foc_lower.h
- drivers/foc: get hardware information via lower-half interface
- drivers/foc: return scaling factor for phase currents and BEMF via ioctl  
These values are board-specific properties that must be known on the application side.
Until now, these values had to be hardcoded on the application side.
we can get rid of the hardcoded ADC scaling values on the app side.
This is also the first step to support configurable phase currents gain.
odriver3.6 board (not yet upstream)
=> drivers/foc: return scaling factor for phase currents and BEMF via ioctl

drivers/lcd/lcd_dev.c, include/nuttx/lcd/lcd_dev.h
In order to achieve better scalability, change the stride from pixel mode to byte mode.For example, in the case of RGB888 mode with 466 pixels in width and a 4-byte aligned buffer,it is only necessary to extend the buffer of one line from 1398 bytes to 1400 bytes, instead of extending it to 1404 bytes.
=> drivers/lcd: change lcd stride from pixel to bytes

fs/inode/fs_files.c
fs/inode: check file list before memcpy
The file list is NULL if task group initialized, check the validity of the file list before memcpy.
N/A
ci-check
=> fs/inode: check file list before memcpy

arch/arm/src/samv7/sam_timerisr.c, arch/arm/src/stm32/stm32_timerisr.c, drivers/timers/Kconfig, include/nuttx/arch.h, sched/Kconfig, sched/clock/clock.h, sched/clock/clock_adjtime.c, sched/clock/clock_initialize.c, sched/clock/clock_settime.c
Previous `adjtime()` implementation was limited to adjusting system timer tick period. This commit reimplements the internals to use a kernel watchdog timer. Platform-independent part of the code now works also for adjusting hires RTC and tickless timer rate.
Currently there are no in-tree architecture implementations for high-res RTC nor tickless timer adjustments, but the API is now available.
Other improvements:
- Support query of remaining adjustment by passing NULL to first argument of adjtime(). This matches Linux behavior.
- Improve resolution available for architecture driver, previously limited to 1 microsecond per tick. Now 1 nanosecond per second on API level.  For ARM SysTick based drivers the hardware resolution is 1 clock cycle per tick.
User code facing API is unchanged. …
=> Rewrite adjtime() implementation to work for RTC and tickless kernel

arch/sim/src/sim/sim_heap.c, mm/Kconfig, mm/mm_heap/mm.h, mm/mm_heap/mm_free.c, mm/mm_heap/mm_malloc.c, mm/tlsf/mm_tlsf.c
This configuration allows delaying the freeing of memory until the count of delayed memory nodes surpasses a specified limit. When used in conjunction with KASAN (Kernel Address Sanitizer), this enhances the ability to detect memory used-after-free issues.
No.
Enabling this feature may lead to increased memory fragmentation. Therefore, it is crucial to select a practical value for `CONFIG_MM_FREE_DELAYCOUNT_MAX`.
CI and internal project running monkey test with `CONFIG_MM_FREE_DELAYCOUNT_MAX` configured to 10000.
=> mm: free delay list when exceeding specified count

arch/arm/src/stm32/stm32_foc.c
- stm32/stm32_foc.c: rename some macros
change the names to be the same as for stm32f7/stm32_foc.c
Cosmetic change.
Copying changes from one implementation to another will be less prone to compilation errors
CI
=> stm32/stm32_foc.c: rename some macros

sched/semaphore/sem_holder.c
If the semaphore is shared, the holder has put its own mmapped address to pholder->sem. This means we must switch to the holder's address environment when going through the held semaphores list.
A better option would be to get the kernel mapped address for the semaphore's physical page, but that mechanism is not functional yet.
This fixes a full system crash when CONFIG_PRIORITY_INHERITANCE=y and CONFIG_BUILD_KERNEL=y and user makes shared semaphore via:
int semfd  = shm_open("sem", O_CREAT | O_RDWR, 0666); 
sem_t *sem = mmap(0, sizeof(sem_t), PROT_READ | PROT_WRITE, MAP_SHARED, semfd, 0);
Fixes system crash as mentioned above
MPFS target with kernel mode, priority inheritance and shared semaphores
=> sched/sem_holder.c: When accessing SEM_WAITLIST, use holder's addrenv

libs/libc/stdio/lib_libvscanf.c
On the arm64 platform, size_t needs to be set to the corresponding mode in sscanf, otherwise the format will be converted incorrectly
```
char header[5];
size_t size;
header[0] = '0';
header[1] = '0';
header[2] = '2';
header[3] = '1';
header[4] = 0;
fprintf(stderr, "header = \"%s\"\n", header);
if (sscanf(header, "%04zx", &size) != 1)
{   
return -EINVAL;
} 
fprintf(stderr, "size = %04zx\n", size); 
```
Unmodified test results
```
header = "0021"
size = deaddead00000021
```
Modified test results
```
header = "0021"                                                                                                                            
size = 0021 …
```
=> the bug of sscanf exception output in arm64 platform

sched/misc/assert.c
misc/assert: restore assertion registers to array of last registers
Some assertions in extreme cases will cause syslog to be unable to output logs normally, so this PR will restore the input registers into the array of last registers to ensure that we can also obtain some important informations.
N/A
ci-check
=> misc/assert: restore assertion registers to array of last registers

fs/fat/fs_fat32util.c
fs/fat: fix ubsan warning of shift-out-of-bounds 
```
ubsan_prologue: ================================================================================
ubsan_prologue: UBSAN: shift-out-of-bounds in fat/fs_fat32util.c:989:40
__ubsan_handle_shift_out_of_bounds: left shift of 268435455 by 4 places cannot be represented in type 'int'
ubsan_epilogue: ================================================================================
```
N/A
ci-check
=> fs/fat: fix ubsan warning of shift-out-of-bounds 

arch/arm/src/common/arm_exit.c, arch/arm64/src/common/arm64_exit.c, arch/avr/src/common/avr_exit.c, arch/hc/src/common/hc_exit.c, arch/mips/src/common/mips_exit.c, arch/misoc/src/lm32/lm32_exit.c, arch/misoc/src/minerva/minerva_exit.c, arch/or1k/src/common/or1k_exit.c, arch/renesas/src/common/renesas_exit.c, arch/risc-v/src/common/riscv_exit.c, arch/sparc/src/common/sparc_exit.c, arch/x86/src/common/x86_exit.c, arch/x86_64/src/common/x86_64_exit.c, arch/x86_64/src/common/x86_64_internal.h, arch/xtensa/src/common/xtensa_exit.c, arch/z16/src/common/z16_exit.c, arch/z80/src/common/z80_exit.c, include/nuttx/sched.h, sched/misc/CMakeLists.txt, sched/misc/Make.defs, sched/misc/dump.c
arch/dumponexit: unify dump on exit to common code
remove arch implement and move to common code
N/A
ci-check
=> arch/dumponexit: unify dump on exit to common code

libs/libc/stdio/lib_libvsprintf.c
Fix issue #11155 by handling 64 bit types.
=> Fix improper handling of 64 bit types for libvsprintf #11155

arch/arm/src/imx6/imx_cpuboot.c
avoid the unnecessary typedef
code refactor
ci
=> arch/imx6: Replace cpu_start_t with start_t

net/igmp/igmp_send.c
If the flag is not set, The flag is affected by the previously sent and received packets, L2 header may be filled with ipv6.
sim:local
=> igmp: call IFF_SET_IPv4 when igmp_send

binfmt/CMakeLists.txt, binfmt/Makefile, binfmt/binfmt.h, binfmt/binfmt_copyactions.c, binfmt/binfmt_execmodule.c, fs/inode/fs_files.c, include/nuttx/fs/fs.h, include/nuttx/sched.h, include/nuttx/spawn.h, sched/group/group.h, sched/group/group_setuptaskfiles.c, sched/init/nx_start.c, sched/task/task_create.c, sched/task/task_fork.c, sched/task/task_init.c, sched/task/task_spawn.c, sched/task/task_spawnparms.c
sched/taskfiles: skip unnecessary file open/close operations to improve performance
The task files should consult the "spawn action" and "O_CLOEXEC flags"
to determine further whether the file should be duplicated.
This PR will further optimize file list duplicating to avoid the performance
regression caused by additional file operations.
N/A
ci-check
=> sched/taskfiles: skip unnecessary file open/close operations to improve performance

Documentation/applications/testing/sd_bench/index.rst
Originally flagged in https://github.com/apache/nuttx-apps/pull/2164.
The help prompt usage output for sd_bench was inconsistent with that of the actual application. Amend this error.
Documentation is consistent with build application.
Locally build documentation.
=> Documentation: Fix sd_bench command help description.

arch/sim/src/sim/posix/sim_rawgadget.c
The halt operation may be causes the raw epread data segment lost, and usb ep_queue can handle when the usb buffer is full. so remove the relevant operations.
sim:local
=> usb_rawgadget: remove halt operation

include/nuttx/net/netdev.h, net/Kconfig, net/devif/ipv4_input.c, net/devif/ipv6_input.c, net/inet/inet_sockif.c, net/socket/Kconfig, net/udp/udp.h, net/udp/udp_callback.c, net/udp/udp_recvfrom.c
Adds support for timestamping received UDP packets, either in hardware or in kernel. Builds on the existing support of `SO_TIMESTAMP` for SocketCAN.
Implementation uses `CLOCK_REALTIME` for timestamping to match the behavior of Linux. This could be made configurable in future if needed.
When `CONFIG_NET_TIMESTAMP` is enabled, `setsockopt(..., SO_TIMESTAMP)` can be used to enable timestamping.
Software timestamping is supported on all platforms. This already removes any queuing latency, but threads with higher priority than network processing can delay timestamping.
Platforms where hardware support exists can define `ARCH_HAVE_NETDEV_TIMESTAMP` and store the timestamp to `d_rxtime` before calling `ipv4_input`/`ipv6_input`.
Tested on custom STM32F4 board with a ptpd version that has …
=> udp: Add support for SO_TIMESTAMP

arch/arm/src/stm32/Kconfig, arch/arm/src/stm32/stm32_eth.c
Adds support for hardware timestamping of received Ethernet packets. The timestamp is available to applications using socket option `SO_TIMESTAMP`.
Optionally, the Ethernet PTP timer can be used as system high-resolution RTC. In this mode it supports fine resolution rate adjustment.
Alternatively other time source for `CLOCK_REALTIME` can be used, and the PTP timestamps are converted by sampling the clocks and computing the difference. This results in a few microseconds of uncertainty.
Depends on pull request #11210 to be actually useful, but can be merged separately.
(Related: #10887, ping @xiaotailang ) 
Enabling `CONFIG_STM32_ETH_PTP` will start the PTP timer when Ethernet interface is brought up.
Enabling `CONFIG_STM32_ETH_PTP_RTC_HIRES` and `CONFIG_RTC_HIRES` enables the PTP timer as …
=> stm32: Add support for Ethernet packet timestamping and PTP timer

arch/arm/src/samd2l2/sam_dmac.c, arch/arm/src/samd2l2/sam_dmac.h
SAM_DMAC was not compiling out of the box and I found one inconsistency:
- aligned keyword is changed to aligned_data. 
- When setting the register CHINTENCLR in order to `Disable all channel interrupts`:
|0x4C    |CHINTENSET | 7:0    |        |        |        |        |        |SUSP    |TCMPL   |TERR    |
|--------|-----------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
|0x4D    |CHINTENSET | 7:0    |        |        |        |        |        |SUSP    |TCMPL   |TERR    |
Before:
```c
putreg8(1 << chndx, SAM_DMAC_CHINTENCLR);
```
if the number of channel (chndx) is above 3, it will do nothing, and above 7 it will set the next register  CHINTENSET with potential misbehavior.
I suppose the intent was to set the resister to 0000111 -> 0x07 or the …
=> sam_dmac: Fix compilation and fix SAM_DMAC_CHINTENCLR settings

drivers/net/skeleton.c
skeleton.c doesn't compile without this patch if ioctls are enabled
skeleton network driver cannot be used if ioctl feature (CONFIG_NETDEV_IOCTL) is true
The file compiles with this change. Code not actually executed yet,
=> skeleton.c doesn't compile without this patch if ioctls are enabled

drivers/mmcsd/mmcsd_sdio.c
just like what mmcsd_mmcinitialize do
ci
=> drivers/mmcsd: mmcsd_sdinitialize should save csd register into priv->csd

drivers/timers/rpmsg_rtc.c, drivers/timers/rtc.c
- drivers/rtc: Return -ENOTTY if lower half doesn't implement the corresponding callback
- drivers/rtc: Skip clock_synchronize if settime return positive value
- drivers/rtc/rpmsg: Move clock_synchronize rpmsg_rtc_server_settime 
minor
sim:rpsever and sim:rproxy
=> RTC driver improvement

arch/arm64/src/common/arm64_vectors.S
It will cause an incorrect sp value saved in context when saving X0 to sp.
=> arm64_vector: no need to save x0 to sp

arch/sim/src/sim/sim_wifidriver.c
If the SSID contains the special characters `\"'`, which would be added with escape character `\` by the wpa_supplicant.
So we need to remove the escape symbols. 
N/A
For the SSID that contains special characters，the scan results should be consistent with those set by the wireless router.
=> simwifi: Escapes the special characters of ssid in the scan results.

arch/arm/src/arm/arm_tcbinfo.c, arch/arm/src/armv6-m/arm_tcbinfo.c, arch/arm/src/armv7-a/arm_tcbinfo.c, arch/arm/src/armv7-m/arm_tcbinfo.c, arch/arm/src/armv7-r/arm_tcbinfo.c, arch/arm/src/armv8-m/arm_tcbinfo.c, arch/arm/src/armv8-r/arm_tcbinfo.c, arch/arm64/src/common/arm64_tcbinfo.c, arch/risc-v/src/common/riscv_tcbinfo.c, arch/sim/src/sim/sim_tcbinfo.c, arch/sparc/src/common/sparc_tcbinfo.c, arch/x86/src/common/x86_tcbinfo.c, arch/x86_64/src/common/x86_64_tcbinfo.c, arch/xtensa/src/common/xtensa_tcbinfo.c, include/nuttx/sched.h, libs/libc/gdbstub/lib_gdbstub.c, tools/gdb/thread.py, tools/jlink-nuttx.c
tcbinfo:remove total_num form tcbinfo. Can solve Mac os alignment problem
debug with jlink
`make -f tools/Makefile.host`
`cp tools/jlink-nuttx /opt/SEGGER/JLink_V786a/libnuttxplugin.so `
`JLinkGDBServer -if SWD -speed 5000 -device STM32F429ZI -NoGui 1 -rtos libnuttxplugin`
=> tcbinfo:remove total_num form tcbinfo.

arch/sim/src/sim/posix/sim_x11framebuffer.c
Convert depth 32 to depth 16 in sim_x11framebuffer
Display of sim
./tools/configure.sh -l sim:lvgl_fb
Color depth select 16: RGB565
CONFIG_SIM_FBBPP 16
please ignore the false nxstyle alarm:
```
Error: /home/runner/work/nuttx/nuttx/nuttx/arch/sim/src/sim/posix/sim_x11framebuffer.c:136:2: error: Mixed case identifier found
Error: /home/runner/work/nuttx/nuttx/nuttx/arch/sim/src/sim/posix/sim_x11framebuffer.c:137:2: error: Mixed case identifier found
Error: Process completed with exit code 1.
```
=> arch/sim: sim support 16bbp

arch/arm/src/tiva/common/tiva_sock_can.c, fs/spiffs/src/spiffs_vfs.c
fs/spiffs: correct mutex lock cycle of spiffs
This PR will fix the below issues:
1. double lock() on dup
2. use after free on unbind
N/A
ci-check
=> fs/spiffs: correct mutex lock cycle of spiffs 

fs/inode/fs_files.c
sched/taskspawn: fix spawn fail if enable FDCHECK
restore file descriptor before compare
N/A
ci-check
=> sched/taskspawn: fix spawn fail if enable FDCHECK

include/signal.h, sched/signal/sig_dispatch.c, sched/signal/sig_queue.c
Commit 9244b5a737c9222aa3df3eac167f76ce7e7e50b8 added support for non-standard field `si_user` that is useful for passing context pointers to signal handlers.
This commits makes it work for all signals, not just `SA_KERNELHAND`.
Previously `si_user` for normal signals was uninitialized garbage.
Does not affect existing working code. Makes it possible to use `si_user` for any signal (with the caveat that it is NuttX-specific).
Tested on custom STM32F4 board with simple code sending signal between two tasks.
=> sigaction: Expand si_user for non-kernel signals

arch/risc-v/src/mpfs/mpfs_ihc.c, arch/risc-v/src/mpfs/mpfs_ihc_sbi.c
Replace DEBUGASSERTs with sanity checks. DEBUGASSERT()s are not necessarily enabled at all, thus risking the functionality especially in that case. Remove PANICs as well.
Don't enable the ihc irq too early. If enabled, and the master is already up, the irq is being issued so that the system gets stuck or is severely slowed down. Master may be already up if this NuttX hart only is rebooted, for example.
IHC is supposed to work in parallel with Linux. In order to keep the whole system robust, remove all DEBUGASSERT()s and DEBUGPANIC()s from IHC. Replace them with more meaningful sanity checks.
IHC maybe already partly active, if one NuttX hart is rebooted, but Linux isn't. In that case, the system gets way too many interrupts before it even gets up to handle them. Thus, relocate the irq …
=> risc-v/mpfs: ihc: cleanup DEBUGASSERTs and irq enabling

include/nuttx/tls.h, sched/sched/CMakeLists.txt, sched/sched/Make.defs, sched/sched/sched.h, sched/sched/sched_get_tls.c, sched/task/task_cancelpt.c
PR #11165 causes an unnecessary regression; task_delete no longer works, if the deleted task is from another group.
The logic that prevents this comes from:
nxnotify_cancellation() ->
tls_get_info_pid() ->
nxsched_get_stackinfo()
Which checks for permissions, which does not make sense in this case since it is the kernel asking for the stack information.
Fix this by partially reverting 11165 and implementing a direct path for the kernel to query for any tasks TLS.
Fix the regression
rv-virt:nsh64 + ostest, test task_delete
=> task/pthread_cancelpt: Fix nxtask_delete from another task group

LICENSE, drivers/drivers_initialize.c, drivers/misc/Kconfig, drivers/misc/Make.defs, drivers/misc/optee.c, drivers/misc/optee_msg.h, include/nuttx/drivers/optee.h, include/nuttx/tee.h
The driver's main purpose is to support the porting of the open source component optee_client (https://github.com/OP-TEE/optee_client) to nttux.
The basic function of the driver module is to convert the REE application layer data and send it to the TEE through rpmsg.
The main functions include
1 driver registration.
we need to register a device driver(/dev/tee0) through optee_register function. 
2 open the driver
3 ioctl the driver
The ioctl command passes different parameters and commands, and interacts with the TEE through rpmsg. 
4 close the driver
=> driver/tee: add optee client driver module

libs/libm/libmcs/Make.defs, libs/libm/newlib/Make.defs, libs/libm/openlibm/Make.defs, tools/Config.mk
Fix an issue https://github.com/apache/nuttx/issues/11239
that math library header files are not exported by `make export`.
Create symbolic links of libmcs, newlib and openlibm header to nuttx/include.
Build check: pass
=> libm: Fix an issue that public header files are not exported

Documentation/platforms/arm/stm32f4/boards/stm32f401rc-rs485/index.rst, boards/arm/stm32/stm32f401rc-rs485/scripts/ld.script
Fix flash size for stm32f401rc.
Use the correct flash size.
=> stm32f401rc-rs485: Fix f401rc flash size

arch/risc-v/src/common/riscv_addrenv_pgmap.c, include/nuttx/arch.h, mm/kmap/kmm_map.c
After this, RISC-V fully supports the kmap interface.
Due to the current design limitations of having only a single L2 table per process, the kernel kmap area cannot be mapped via any user page directory, as they do not contain the page tables to address that range.
So a "kernel address environment" is added, which can do the mapping. The mapping is reflected to every process as only the root page directory (L1) is copied to users, which means every change to L2 / L3 tables will be seen by every user.
Finalize kmap feature for RISC-V target, no impact for others
Downstream project MPFS target with CONFIG_BUILD_KERNEL=y and MM_KMAP=y
=> mm/kmap: Finalize kmap implementation for RISC-V

sched/sched/sched_removereadytorun.c
sched: delete check when pick nexttcb in readytorun list
```
CPU0                     CPU1
1. feed0 thread             feed1 thread
(prio 1 affinity)        (prio 1 affinity)
2. nsh_main
sched_lock()
3. waitpid()                hello_main
4. ------                   hello exit()
5. ------                   exit()->exit_wakeup()->wakeup nsh ->
add_readytorun()->
nsh at schedlock state set g_cpu_schedlock
6. -----                    exit()->nxtask_exit()->remove_readytorun()
-> check g_cpu_schedlock -> pick idle1
7. waitpid() return         idle thread
8. sched_unlock             idle thread
```
The error is in step 6:
pick a idle thread to execute not feed1 thread.
resolve:
remove the schedlocked-check in remove_readytorun()
SMP scheduler
BES SMP board
=> sched: delete check when pick nexttcb in readytorun list

Documentation/platforms/arm/stm32h7/boards/linum-stm32h753bi/index.rst
Fix errors on linum-stm32h753bi
>  /home/rcsim/Workspace/learning/nuttx/nuttxspace/nuttx/Documentation/platforms/arm/stm32h7/boards/linum-stm32h753bi/index.rst:106: ERROR: Malformed table.
> Text in column margin in table line 2.
> 
> ====== =====
> UART4 PINS
> ====== =====
> TXD    PB9
> RXD    PB8
> DE     PA15
> ====== =====
> /home/rcsim/Workspace/learning/nuttx/nuttxspace/nuttx/Documentation/platforms/arm/stm32h7/boards/linum-stm32h753bi/index.rst:236: ERROR: Malformed table.
> Bottom/header table border does not match top border.
> 
> ======== =====
> GPIO     PINS
> ======== =====
> TS_RESET PI7
> TS_ISR   PH9
> ========  =====
> /home/rcsim/Workspace/learning/nuttx/nuttxspace/nuttx/Documentation/platforms/arm/stm32h7/boards/linum-stm32h753bi/index.rst:338: ERROR: Malformed table. …
=> Documentation: Fix errors on linum-stm32h753bi

tools/ci/cibuild.sh, tools/ci/docker/linux/Dockerfile
from https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/releases/tag/release-17.0.1
ci
ci
=> tools/ci: Upgrade clang arm toolchain to 17.0.1

tools/ci/cibuild.sh, tools/ci/testlist/macos.dat
and enable arm64 ci build on macOS
arm64 ci
ci
=> tools/ci: Upgrade macOS arm64 toolchain to 12.3.rel1

arch/risc-v/src/mpfs/mpfs_corespi.c
The divider should be rounded to the next full integer to ensure that the resulting SPI frequency is <= target frequency, i.e. the SPI is not overclocked.
Fix bug in mpfs corespi driver
MPFS with SPI sensors
=> mpfs/mpfs_corespi.c: Round up divider to prevent overlock of SPI

arch/arm/src/cxd56xx/cxd56_cisif.c, arch/sim/src/sim/sim_camera.c, drivers/video/goldfish_camera.c, drivers/video/video.c, include/nuttx/video/imgdata.h
To avoid losing the first frame, the set_buf needs to excute first. At the same time, imgdata->start_capture should excuted before the imgsensor->start_capture.
Video capture.
Testing in sim environment, camera  can run normally.
=> video.c: modify set_buf call seqence in start_capture function.

drivers/net/loopback.c
`netdev_register` will set `IFF_LOOPBACK` in `d_flags`, we should not just change it into `IFF_UP` only.
`d_flags` of `lo` device
Manually
=> net/loopback: Fix flags of lo device

libs/libc/machine/arm/armv8-m/gnu/arch_memchr.S, libs/libc/machine/arm/armv8-m/gnu/arch_memcpy.S, libs/libc/machine/arm/armv8-m/gnu/arch_memmove.S, libs/libc/machine/arm/armv8-m/gnu/arch_memset.S, libs/libc/machine/arm/armv8-m/gnu/arch_strcmp.S, libs/libc/machine/arm/armv8-m/gnu/arch_strcpy.S, libs/libc/machine/arm/armv8-m/gnu/arch_strlen.S
libc/arm: add support of PACBTI
Reference:
https://developer.arm.com/documentation/100748/0617/Security-features-supported-in-Arm-Compiler-for-Embedded/PACBTI-M-extension-mitigations-against-ROP-and-JOP-style-attacks
https://developer.arm.com/documentation/101754/0619/armclang-Reference/armclang-Command-line-Options/-mbranch-protection
N/A
ci-check
=> libc/arm: add support of PACBTI

boards/xtensa/esp32s3/common/scripts/mcuboot_sections.ld
* Bugfix of [this issue](https://github.com/apache/nuttx/issues/11279)
* xtensa/esp32s3: Fix esp32s3 mcuboot ota crash
Only ESP32S3
`esp32s3-devkit:wifi` config used with added these lines into rtc defconfig:
```
CONFIG_ESP32S3_HAVE_OTA_PARTITION=y
CONFIG_ESP32S3_STORAGE_MTD_OFFSET=0x250000
CONFIG_ESP32S3_STORAGE_MTD_SIZE=0x100000
CONFIG_ESP32S3_APP_FORMAT_MCUBOOT=y
```
=> xtensa/esp32s3: Fix esp32s3 mcuboot ota crash

libs/libc/stdio/lib_libvsprintf.c
Fix printf issue that -nan cannot be parsed correctly
Update libc with lib_libvsnprintf.c file
4290772992UL(-nan)
=> Fix -nan issue with f32

tools/ci/docker/linux/Dockerfile
so dynamically download and install the latest gn tools
sim:local
=> ci_sim: the version of gn obtained by apt install is too low

tools/Unix.mk, tools/Win.mk, tools/configure.c, tools/configure.sh, tools/refresh.sh
While simplifying some of the Simulator-based configurations, I found one area that could be improved - I added an extra layer to retrieve paths at compile time.
This means that we can extract the script and include paths to the common directory, and in common we only need to store some private files for configuration.
Added a layer of path searching, now common is placed in a flat directory with board, if there is no include / script stored in the board directory, then it will look in common.
Based on this change, the local board path accomplishes the desired goal and does not affect configurations such as sim:nsh
=> sh:Enhanced compilation system

tools/ci/docker/linux/Dockerfile
so using npm to upgrade the nodejs tool to the latest
sim:local
=> ci_sim: the version of nodejs obtained by apt install is too low

fs/inode/fs_files.c, fs/procfs/fs_procfsproc.c, include/nuttx/fs/fs.h
`/proc/<pid>/group/fd` should read the fds of `<pid>`, not current tcb.
Note: This problem exists between https://github.com/apache/nuttx/pull/11140 and this PR.
`/proc/<pid>/group/fd`
`fdinfo` command, which shows the same result for every thread before this patch.
=> fs/proc: Fix groupfd to get fd by group instead of current tcb

arch/arm/src/s32k3xx/s32k3xx_edma.c, arch/arm/src/s32k3xx/s32k3xx_edma.h, arch/arm/src/s32k3xx/s32k3xx_serial.c
Fixes stuttering output.
The use of the semaphore was causing blocking
on non blocking callers. This ensured that
the TX DAM would be restated, but when it
was switched to trywait in https://github.com/apache/nuttx/commit/8362e3147e8000ea70f622fd02fbcafbcfef1a2b, it left
data in the xmit queue unsent.
This solution removes the semaphore and restart
the DMA on completion if there is more data in
the xmit queue to be sent.
This prevents dma stop operations called of a completion
call back from rentering, the callback and ensures that
the call back will see the idle state.
Fixes issue with TXDMA  stuttering output.
nxp_mr-canhubk3_fmu
=> NXP S32K3xx Fixes stuttering output 

arch/arm/src/samv7/sam_emac.c
```
chip/sam_emac.c:3754:11: error: 'struct sam_emac_s' has no member named 'phytype'
3754 |   if (priv->phytype == SAMV7_PHY_KSZ8061)
|           ^~
make[3]: *** [Makefile:167: sam_emac.o] Error 1
```
Member phytype is available only if `CONFIG_NETDEV_PHY_IOCTL` and `CONFIG_ARCH_PHY_INTERRUPT` is set.
Build fix
Build pass.
=> samv7/sam_emac.c: fix compile error with unknown structure member

arch/arm/src/stm32h7/stm32_serial.c
Fixes stuttering output.
The use of the semaphore was causing blocking
on non blocking callers. This ensured that
the TX DAM would be restated, but when it
was switched to trywait in 660ac63b9244372e9fc5aeca10677aabc8f5e0db, it left
data in the xmit queue unsent.
This solution removes the semaphore and restart
the DMA on completion if there is more data in
the xmit queue to be sent.
Fixes stuttering output when TXDMA is enabled introduced by 660ac63b9244372e9fc5aeca10677aabc8f5e0db
px4_fmu-v6x
=> stm32h7:Serial refactor out tx dma semaphore

tools/ci/docker/linux/Dockerfile
fix build break:
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.so when searching for -lstdc++ /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.a when searching for -lstdc++ /usr/bin/ld: cannot find -lstdc++: No such file or directory /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.so when searching for -lstdc++ collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
sim:local
=> ci_sim01: install g++-multilib into docker to support libcxx

net/icmpv6/icmpv6.h, net/icmpv6/icmpv6_input.c, net/icmpv6/icmpv6_rnotify.c
When receiving Router Advertisement Message, if Managed Address Configuration flag is set, we should ignore the Autonomous Address-configuration flag, and obtain the IPv6 address via the stateful process.
The change will affect the process of obtaining IPv6 address.
We can use radvd to simulte the IPv6 server, and control the RA flags by turning on or off the `AdvManagedFlag` field.
- open the `NET_ICMPv6_AUTOCONF`;
- then, get the IPv6 address by `renew6`;
- and check the result with `ifconfig`;
The radvd configuration is as follows:
```
interface nuttx0 {
IgnoreIfMissing on;
AdvSendAdvert on;
MinRtrAdvInterval 200;
MaxRtrAdvInterval 600;
AdvOtherConfigFlag on;
AdvManagedFlag on;
AdvLinkMTU 1500;
prefix 2408:501:ffff:abc::/64 {
AdvOnLink on;
AdvAutonomous on;
AdvRouterAddr off; …
```
=> net/icmpv6:Optimize the process of obtaining the IPv6 address through RA.

arch/xtensa/src/esp32s3/esp32s3_qspi.c
QSPI disable DMA when sending command to slave.
=> xtensa/esp32s3: QSPI disable DMA when sending command to slave

arch/xtensa/src/esp32s3/esp32s3_gpio.c
GPIO clear pending interrupt status before enable IRQ.
=> xtensa/esp32s3: GPIO clear pending interrupt status before enable IRQ

arch/risc-v/src/mpfs/mpfs_head.S
In order to avoid linker truncation error (address unreachable), making it a tail call ensures this does not happen.
Small pre-emptive fix
None
=> mpfs_head.S: Change j/jal to tail call

arch/arm/src/efm32/efm32_usbdev.c, arch/arm/src/stm32/stm32_otgfsdev.c, arch/arm/src/stm32f7/stm32_otgdev.c, arch/arm/src/stm32h7/stm32_otgdev.c, arch/arm/src/stm32l4/stm32l4_otgfsdev.c, arch/xtensa/src/esp32s3/esp32s3_otg_device.c, drivers/usbdev/Kconfig, include/nuttx/usb/usbdev.h
The option `CONFIG_USBDEV_SOFINTERRUPT` has existed in architecture USB drivers for a long time now.
The implementation was not fully finished though, as Kconfig entry was missing and the interrupt handler did nothing.
Previously we had a local patch to call a custom callback function, used to synchronize clocks between USB devices.
This pull request adds a generally usable `usbdev_sof_irq()` callback that would be implemented by board logic.
No impact it `CONFIG_USBDEV_SOFINTERRUPT` is not enabled (as it typically wouldn't be, as it wasn't in Kconfig previously).
When it is enabled, `usbdev_sof_irq()` function must be added to board logic.
Tested on custom STM32H417 board.
Implementations for other hardware was added based on similar structure of code.
=> usbdev: Add callback for CONFIG_USBDEV_SOFINTERRUPT

arch/arm/src/samd2l2/sam_spi.c
According to SAMD21 Errata:
```text
1.7.2 Linked Descriptor
When at least one channel using linked descriptors is already active, enabling another DMA channel (with or without
linked descriptors) can result in a channel Fetch Error (FERR) or an incorrect descriptor fetch.
This occurs if the channel number of the channel being enabled is lower than the channel already active.
Workaround
When enabling a DMA channel while other channels using linked descriptors are already active, the channel number
of the new channel enabled must be greater than the other channel numbers.`
```
In the spi driver, in the description and in the code it is always Tx and then Rx except in one place where it is Rx and then Tx which could lead in the FERR according to Errata
I think it would be better to swap …
=> invert tx and rx in spi_dma_setup

tools/ci/docker/linux/Dockerfile
report here:
https://github.com/apache/nuttx-apps/actions/runs/7149109828/job/19470959712?pr=2225
regression by:
https://github.com/apache/nuttx/pull/11345
ci
ci
=> ci/docker: Fix " Could not find GN_EXECUTABLEXX using the following names: gn"

.github/workflows/docker_linux.yml, tools/ci/docker/linux/Dockerfile
- Revert "CI: Free space on worker building container", see:
https://github.com/apache/nuttx/pull/11343
- ci/docker: Revert the change about gn to unblock ci, reported here: 
https://github.com/apache/nuttx/actions/runs/7155266012/job/19483732190?pr=11360)
docker image
ci
=> Fix the issue about the generation of docker image

libs/libc/misc/lib_slcddecode.c, libs/libc/misc/lib_slcdencode.c
Binary nibble to/from ascii hex conversion was buggy on both lib_slcdencode and lib_slcddecode libraries.
This bug caused the slcd library to fail to decode 5-byte sequence command which have 'count' argument value bigger than 0x9.
=> lib_slcd: fix encode/decode of binary nibble to/from ascii hex

include/nuttx/virtio/virtio.h
Virtio driver can used this api to judge whether the this feature is supported by both virtio driver and device.
New Virtio API
New api, will be used by virtio driver(e.g., virtio-net, virtio-blk).
=> virtio.h: add virtio_has_feature api for virtio driver

fs/procfs/fs_procfscpuinfo.c
to avoid return the negative number
/proc/cpuinfo
internal
=> procfs/cpuinfo: Zero copylen in cpuinfo_read

arch/arm/src/stm32u5/hardware/stm32_exti.h
EXTI2,3,4 register offsets were the same as EXTICR1, possibly a typo. 
Possibly no impact, I do not see any use in nuttx or nuttx-apps.
Not tested.
=> stm32u5: fix EXTICR2,3,4 register offsets

tools/ci/docker/linux/Dockerfile
Minimize the size of the docker image
sim:matter
=> linux_Dockerfile: only copy gn binary into docker

arch/risc-v/src/common/riscv_mmu.c, arch/risc-v/src/common/riscv_mmu.h
Currently RISC-V NuttX supports 32-bit MMU Flags inside a Page Table Entry. This PR extends the MMU Flags to 64-bit, to support T-Head C906 Core and the new RISC-V Svpbmt Extension.
T-Head C906 uses Bits 59 to 63 in a Leaf Page Table Entry to configure the Memory Type: Cacheable / Bufferable / Strongly-Ordered. For the upcoming port of NuttX to PINE64 Ox64 BL808 SBC, we need to set the Memory Type to Strongly-Ordered for I/O Memory, which requires 64-bit MMU Flags. [Details of C906 MMU](https://lupyuen.github.io/articles/plic3#t-head-errata)
Newer RISC-V Cores will use the Svpbmt Extension to configure the Memory Type (Cacheable / Strongly-Ordered). Svpbmt uses Bits 61 to 62 in a Leaf Page Table Entry to define the Memory Type. This also requires 64-bit MMU Flags. [Details of …
=> riscv/mmu: Extend MMU Flags to 64-bit for T-Head C906 and Svpbmt

drivers/mtd/w25qxxxjv.c
Busy waiting in `w25qxxxjv_erase_sector()` was without `nxsig_usleep` and was causing the entire system to freeze for significant amount of time as sector erase takes some time.
This commit adds `nxsig_usleep` into busy waiting to prevent system lock. Sleep is set to sector erase time based on W25Q series datasheet.
Fix w25q driver.
Tested with W25Q01 NOR flash and custom board with SAMv7 MCU.
=> mtd/w25q: add nxsig_usleep to busy waiting in w25qxxxjv_erase_sector()

drivers/net/netdev_upperhalf.c, net/udp/udp_sendto_buffered.c
Commit 8a63d29c removed `devif_iob_send` from `udp_sendto_buffered` workflow, `devif_iob_send` drops too big packet. Now we still need a place to check the packet length, otherwise a packet larger than MTU may be sent to the net driver.
In case of similar problem happens somewhere else, this commit also adds a check in `netdev_upperhalf`, and count these cases into `NETDEV_TXERRORS`.
`udp_sendto_buffered`
iperf with UDP TX LEN larger than 1472, without `CONFIG_NET_IPFRAG` enabled.
=> net/udp: Add check when sending too big packet without IP frag

arch/risc-v/Kconfig, arch/risc-v/include/bl808/chip.h, arch/risc-v/include/bl808/irq.h, arch/risc-v/src/bl808/Kconfig, arch/risc-v/src/bl808/Make.defs, arch/risc-v/src/bl808/bl808_allocateheap.c, arch/risc-v/src/bl808/bl808_head.S, arch/risc-v/src/bl808/bl808_irq.c, arch/risc-v/src/bl808/bl808_irq_dispatch.c, arch/risc-v/src/bl808/bl808_memorymap.h, arch/risc-v/src/bl808/bl808_mm_init.c, arch/risc-v/src/bl808/bl808_mm_init.h, arch/risc-v/src/bl808/bl808_pgalloc.c, arch/risc-v/src/bl808/bl808_serial.c, arch/risc-v/src/bl808/bl808_serial.h, arch/risc-v/src/bl808/bl808_start.c, arch/risc-v/src/bl808/bl808_timerisr.c, arch/risc-v/src/bl808/chip.h, arch/risc-v/src/bl808/hardware/bl808_memorymap.h, arch/risc-v/src/bl808/hardware/bl808_plic.h, arch/risc-v/src/bl808/hardware/bl808_uart.h
This PR adds support for the Bouffalo Lab BL808 SoC, based on T-Head C906 64-bit RISC-V Core. This will be used by the upcoming port of NuttX for PINE64 Ox64 SBC.
Most of the code was derived from NuttX for Star64 JH7110. The UART Driver was derived from BL602 NuttX. [The source files are explained in the articles here](https://github.com/lupyuen/nuttx-ox64)
`Kconfig`: Added ARCH_CHIP_BL808 for BL808 SoC
`include/bl808/chip.h`: BL808 Definitions
`include/bl808/irq.h`: External Interrupts
`src/bl808/chip.h`: Interrupt Stack Macro
`src/bl808/bl808_allocateheap.c`: Kernel Heap
`src/bl808/bl808_head.S`: Linux Header and Boot Code
`src/bl808/bl808_irq.c`: Configure Interrupts
`src/bl808/bl808_irq_dispatch.c`: Dispatch Interrupts
`src/bl808/bl808_memorymap.h`: Memory Map …
=> arch/riscv: Add support for Bouffalo Lab BL808 SoC (T-Head C906)

arch/risc-v/src/common/riscv_pmp.c
The macro LOG2_CEIL is intended to be used in the pre-processor phase. If used run-time it will generate a massive amount of extra code (~3.5K) which is a problem, as the PMP configuration is quite often executed from a first stage bootloader with a limited amount of code memory.
Code size differences pre- and post:
```
envm:      112064 B     112384 B     99.72%
envm:      108952 B     112384 B     96.95%
```
Decrease code footprint of the PMP driver
MPFS
=> riscv_pmp.c: Revert LOG2_CEIL back to run-time log2ceil function

CMakeLists.txt
- cmake: NUTTX_COMMON_DIR must be set after .config definitions are included
otherwise NUTTX_COMMON_DIR is empty if CONFIG_ARCH_BOARD_COMMON is set from menuconfig
local build
=> cmake: fix NUTTX_COMMON_DIR

arch/risc-v/include/elf.h, binfmt/libelf/libelf_bind.c, include/nuttx/elf.h, libs/libc/machine/arm/arm/arch_elf.c, libs/libc/machine/arm/armv6-m/arch_elf.c, libs/libc/machine/arm/armv7-a/arch_elf.c, libs/libc/machine/arm/armv7-m/arch_elf.c, libs/libc/machine/arm/armv7-r/arch_elf.c, libs/libc/machine/arm/armv8-m/arch_elf.c, libs/libc/machine/arm64/arch_elf.c, libs/libc/machine/risc-v/arch_elf.c, libs/libc/machine/sim/arch_elf.c, libs/libc/machine/sim/arch_elf64.c, libs/libc/machine/sparc/arch_elf.c, libs/libc/machine/x86/arch_elf.c, libs/libc/machine/xtensa/arch_elf.c, libs/libc/modlib/modlib_bind.c
There is a problem with the current elf loader for risc-v: when a pair of PCREL_HI20 / LO12 relocations are encountered, it is assumed that these will follow each other immediately, as follows:
label:
auipc      a0, %pcrel_hi(symbol)    // R_RISCV_PCREL_HI20
load/store a0, %pcrel_lo(label)(a0) // R_RISCV_PCREL_LO12_I/S
With this assumption, the hi/lo relocations are both done when a hi20 relocation entry is encountered, first to the current instruction (addr) and to the next instruction (addr + 4).
However, this assumption is wrong. There is nothing in the elf relocation specification[1] that mandates this. Thus, the hi/lo relocation always needs to first fixup the hi-part, and when the lo-part is encountered, it needs to find the corresponding hi relocation entry, via the given "label". …
=> riscv/arch_elf.c: Handle PCREL_HI20/LO12_I/S relocations correctly

include/nuttx/net/netdev.h, net/icmpv6/icmpv6_input.c, net/icmpv6/icmpv6_reply.c, net/inet/ipv6_getsockname.c, net/netdev/netdev_ipv6.c, net/tcp/tcp_send.c, net/udp/udp_send.c
Previously ipv6 multi-address support decided packet source address based on its destination. This doesn't work if NuttX device has multiple addresses within same subnet. Replies will come from different address that the originator contacted, which causes warnings for ICMPv6 and stops TCP from working.
Instead when a packet is a response to existing connection, the source address should be based on the destination address used in the received packet.
[RFC6724](https://datatracker.ietf.org/doc/html/rfc6724#section-2) does not go much into detail on this, but says:
>   Although source and destination address selection is most typically
>   done when initiating communication, a responder also must deal with
>   address selection.  In many cases, this is trivially dealt with by an
> …
=> ipv6: Fix source address with many addresses in same network

libs/libc/machine/risc-v/arch_elf.c
As pointed out in #11322 there is a hardware design issue in RISC-V that affects RV64 relocations. The problem is with how address bits are loaded into registers via lui / auipc and sign extension.
If the hi20 relocation value happens to have its 32-bit sign bit set, i.e. value is 0x80000000 (but not negative! i.e. negative in 64-bit format) the relocation will fail, as the address is erroneously sign extended:
0x00000000_80000000 becomes 0xffffffff_80000000 which is not correct.
Also, make sure the correct opcode is used with PCREL_HI20, it expects AUIPC (not LUI). The C compiler will never emit such code but when hand- writing assembly code this can happen.
Fix two unlikely issues with risc-v elfloader
rv-virt:knsh64
=> riscv/arch_elf: Check for _HI20 relocation validity

arch/risc-v/src/common/riscv_pmp.c, include/nuttx/lib/math32.h, libs/libc/misc/CMakeLists.txt, libs/libc/misc/Make.defs, libs/libc/misc/lib_log2ceil.c, libs/libc/misc/lib_log2floor.c
Move log2ceil from riscv_pmp to libc. Also, implement log2floor for completeness.
These are the run-time alternative to the compile-time macros.
Move handy utility function to common code
CI pass
=> libs/log2ceil: Move implementation of log2ceil to a common place

drivers/net/CMakeLists.txt, drivers/net/Kconfig, drivers/net/Make.defs, drivers/net/wifi_sim.c, drivers/virtio/virtio-net.c, include/nuttx/net/wifi_sim.h
Add the virtual WiFi function on the emulator.
- The qemu wifi fucntion only supports the STA mode and the following operations:
```
wapi mode wlan0 2
wapi scan wlan0
wapi psk wlan0 password 3
wapi essid wlan0 wifi_name 1
wapi show wlan0
wapi disconnect wlan0
```
Support the virtual WiFi function.
- Eanble the virtual wifi function with the MACRO `CONFIG_DRIVERS_WIFI_SIM`;
- Configure the BSS file directory `CONFIG_WIFI_SIM_CONFDIR` with `/data/wifi`;
- Mount the BSS file to `/data/wifi` directory of the qemu via the fatfs. 
The contents of the BSS file are as follows:
```
ee:17:2f:b8:ab:18,2412,-36,[ESS],333,
38:17:c3:92:27:22,2437,-53,[WPA2-PSK-CCMP][ESS],MIOT,12345678
```
- After starting the emulator, we can do the following:
```
wapi mode wlan0 2
wapi scan wlan0
wapi psk wlan0 …
```
=> qemu/wifi: Add the virtual wifi function on the emulator.

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_ethernet.c
The hack just opens the entire SoC memory unconditionally, which is not a good idea.
Test features can be used ad-hoc, they don't need to be supported by the build.
Unused code removal
None
=> mpfs_ethernet.c: Remove DMA_ENABLE hack

arch/risc-v/src/mpfs/mpfs_usb.c
DMA directly to user (virtual) memory won't work, as the DMA engine(s) don't do address translations, i.e. they require a physical address.
Using kernel heap is fine as it is mapped vaddr=paddr. Also, the USB DMA engine does not have any alignment requirements.
MPFS USB driver with DMA
CI pass
=> mpfs_usb.c: Use kernel memory instead of user memory for DMA

arch/risc-v/src/esp32c3/esp32c3_wlan.c, arch/sim/src/sim/sim_wifidriver.c, arch/xtensa/src/esp32/esp32_wlan.c, arch/xtensa/src/esp32s3/esp32s3_wlan.c, drivers/net/netdev_upperhalf.c, drivers/net/wifi_sim.c, drivers/virtio/virtio-net.c, include/nuttx/net/netdev.h, include/nuttx/net/netdev_lowerhalf.h, net/netdev/netdev_carrier.c
Modify the logic for setting the IFF_RUNNING status of interfaces.
Refer to the logic of the `netif_carrier_on` on linux. 
https://github.com/torvalds/linux/blob/master/net/sched/sch_generic.c#L575
N/A
When we set the `eth0` interface with the commands `ifup eth0` （or `ifdown eth0`）continuously on emulator.
And no error is returned.
=> net/netdev: Modify the logic for setting the IFF_RUNNING status of interfaces.

net/tcp/tcp_send_buffered.c
When `CONFIG_NET_TCP_WRITE_BUFFERS` is enabled, iobs are used for both queuing data from application, and for assembling packets for sending. If there is a system-wide shortage of iobs, it could happen that there is not enough free space to form any packets to send. The buffers allocated for TCP data also can't be released until the packet is sent.
Normally this should be avoided by setting suitable values for `CONFIG_IOB_NBUFFERS` and `CONFIG_IOB_THROTTLE`. The default values are ok for light usage, but can run out when using multiple simultaneous TCP streams.
Before this commit, iob shortage would cause TCP connections to get stuck and eventually timeout. With this change, TCP stack sends smaller packets, eventually freeing some buffers from the write queue.
In normal usage no effect. …
=> tcp: Recover from iob shortage with TCP_WRITE_BUFFERS

cmake/menuconfig.cmake
cmake: restore old behavior for savedefconfig (changed in 375959eac1bbb26ce3450ba19c34953df33db7db)
savedefconfig shouldn't overwrite the original defconfig, but only create a new defconfig in the current directory. Otherwise, creating new configs based on existing ones becomes irritating, because every time we use savedefconfig, the original configuration is overwritten which is not the excepted behavior
savedefconfig behaves the same for cmake and make
=> cmake: restore old behavior for savedefconfig

libs/libxx/Kconfig, libs/libxx/__config_site, libs/libxx/libcxx.defs, libs/libxx/mbstate_t.patch, tools/ci/testlist/sim-01.dat
Related to https://github.com/apache/nuttx/pull/11269
Upgrade to LLVM version 17.0.6
Also set Nuttx libm as default math lib to prevent compilation failures
Tested with gcc version 12.3.Rel1 and 13.2.rel1
=> upgrade llvm version to 17.0.6

sched/sched/sched_timerexpiration.c
Remove KEEP_ALIVE_HACK to avoid waking up the device periodly. The workaround it's added by:
```
commit 6546fa39c7a292e919d1ea396d67bea8242f2c4b
Author: Gregory Nutt <gnutt@nuttx.org>
Date:   Tue Aug 12 11:12:00 2014 -0600
Tickless Stuff:  Back out the risky timer operations when the ready-to-run
list is modified. That is unsafe.  An ugly workaround is just to keep an
interval timer going all of the time with a minimum duration equal to the
timeslice interval.
```
But look like it doesn't needed anymore.
tickless with round robin
internal test
=> sched: Stop the sched timer when possible to save the power in tickless mode

tools/ci/cibuild.sh, tools/ci/docker/linux/Dockerfile
from https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads
arm/arm64 toolchain
ci
=> tools/ci: Upgrade arm/arm64 toolchain to 13.2.Rel1

tools/ci/cibuild.sh, tools/ci/docker/linux/Dockerfile, tools/ci/testlist/macos.dat
and add esp32c3-devkit:cxx to macOS ci
ci
ci
=> tools/ci: Upgrade riscv toolchain to v13.2.0

arch/arm/src/armv7-m/arm_dbgmonitor.c, arch/arm/src/armv8-m/arm_dbgmonitor.c
If jtag or swo is connected, there is no need to clear the `fpb` and `dwt` registers
arm/debug
stm32f429i-disco:gdbstub
set `__strat` and `up_idle` a breakpoint, both works, if jtag and swo connected, don't clear `fpb` and `dwt`
=> arm/debug:fix gdbstub clear fpb & dwt when already use jtag/swo bug

boards/xtensa/esp32/common/src/esp32_board_spiflash.c, boards/xtensa/esp32s2/common/src/esp32s2_board_spiflash.c, boards/xtensa/esp32s3/common/src/esp32s3_board_spiflash.c
* esp32<|s2|s3>_board_spiflash: Substitute fs messages to syslog
Once these messages are thrown during the system's bring-up, it is
advisable them to be output by the syslog considering the file
system initialization.
* esp32<|s2|s3>_board_spiflash: Fix error message about SmartFS init
The SmartFS partition needs to be formatted before being mounted.
Otherwise, it would throw an error message. The error message now
contains a suggestion to format the partition when such an error
is detected.
Avoid any confusion regarding the usage of the SmartFS file system on NuttX. This PR is intended to solve the reported error message in https://github.com/apache/nuttx/issues/11337
Internal CI testing + ESP32-S3-DevKitC-1 v1.6
=> esp32<|s2|s3>_board_spiflash: Fix error message about SmartFS init

arch/sim/src/sim/sim_lcd.c, drivers/lcd/lcd_dev.c, drivers/lcd/lcd_framebuffer.c, include/nuttx/lcd/lcd.h
The window opens when the lcd opens and closes when the lcd closes.
The opening and closing of the window has been associated with the opening and closing of fb, but the LCD has not yet been optimized. The window will only open when sim_x11openwindow is called, and similarly, the window will only close when sim_x11closewindow is called.
The window opens when the lcd opens and closes when the lcd closes.
Run lvgldemo with lcd.
=> sim_lcd: add open & close

libs/libxx/libcxx.cmake, tools/ci/testlist/sim-01.dat
support CMake build for llvm 17
relate to https://github.com/apache/nuttx/pull/11301#issuecomment-1855241323
CI build
=> cmake:build file support with libcxx 17.0.6

drivers/sensors/Kconfig, drivers/sensors/ms56xx_uorb.c
In order to obtain best accuracy over temperature range,   
particularly in low temperature, it is recommended to compensate the non-linearity over the temperature.
ref: ENG_DS_MS5611-01BA03_B3.pdf, ENG_DS_MS5607-02BA03_B4.pdf
=> sensors: mx56xx: Add support for second order compensation

arch/xtensa/src/esp32s3/Kconfig, arch/xtensa/src/esp32s3/esp32s3_rtc.c, arch/xtensa/src/esp32s3/esp32s3_rtc.h, arch/xtensa/src/esp32s3/esp32s3_start.c
Fixed bbpll not calibrated from bootloader issue
- Solve Wi-Fi may not work bug for bbpll not lock or not stable when enable RF.
- Improved timing tuning stability on ESP32-S3.
The root cause is as following:
- The Application won't re-calibrate the BBPLL clock if it's already enabled.
- Add a force-recalib function in the app startup code to make sure even if the patch is applied by OTA, the clock is still re-calibrated.
=> xtensa/esp32s3: Fixed bbpll not calibrated from bootloader issue

drivers/net/Kconfig, drivers/net/ksz9477.c, drivers/net/ksz9477_reg.h, include/nuttx/net/ksz9477.h
Add a static port-based VLAN configuration for KSZ9477 switch. This doesn't use the VLAN tagging, but is a switch's internal mechanism to simply configure if the packet forwarding is allowed from one port to another.
This enables restricting traffic between switch ports, based on the device's network topology
Tested on custom HW with mpfs + ksz9477 switch
=> drivers/net/ksz9477: Add simple port-based static VLAN configuration

cmake/menuconfig.cmake
Revert "cmake: restore old behavior for savedefconfig"
@raiden00pl I'm surprised why this commit was reverted. It maintains the same functionality as `tools/refresh.sh`. this change is a good improvement because overwriting the original `defconfig` to prevent developers from missing out on enabled or disabled features during the development process. If you find any changes in the `defconfig` after saving it, you should manually restore it, `git diff` will tell you what has happened. and also this feature prevents more junior developers from forgetting to save their own `defconfig`
This reverts commit 751bc1528a8e9f3bfbe1701619b4894f1d6dcb86.
N/A
ci-check
=> Revert "cmake: restore old behavior for savedefconfig"

drivers/virtio/virtio-net.c
Fix the compile error, log as follows:
```
CC:  virtio/virtio-net.c virtio/virtio-net.c: In function 'virtio_net_set_macaddr': 
virtio/virtio-net.c:595:17: error: invalid operands to binary % (have 'struct net_driver_s *' and 'int')
595 |             dev % 256
|                 ^
make[1]: *** [Makefile:107: virtio-net.o] Error 1
make: *** [tools/LibTargets.mk:101: drivers/libdrivers.a] Error 2
make: *** Waiting for unfinished jobs....
```
NA
No longer appears when recompiling.
=> virtio-net:Fix the compile error.

arch/arm64/src/common/arm64_gicv2.c
- I noticed that qemu-armv8a:netnsh_smp_hv does not detect GICv2 on Raspi4B (ubuntu 22.04 server + qemu-8.1.2)
- According to the GIC-400 TRM, it says that the architecture version can be obtained from GICC_IIDR (See Table 3-7)
- Should be none
- Tested with qemu-armv8a:netnsh_smp_hv on
- Raspi3B+ (ubuntu 22.04 server + qemu-8.1.2)
- Raspi4B (ubuntu 22.04 server + qemu-8.1.2)
- M1/MacBook Pro 2021 (macOS 13.6 + qemu-8.1.2)
=> arch: arm64: Fix GICv2 detection

tools/Config.mk
https://github.com/apache/nuttx/blob/a506f9fb709fa7d3d6646d6c9ffd2246ded8e377/tools/Config.mk#L41-L44
the verbosity option should only control silent mode and should not limit the type of shell
the patch should fix https://github.com/apache/nuttx/issues/11424#issuecomment-1865372001
CI build
=> tool/Config.mk:whether verbosity is enabled or not, should use bash

arch/arm/src/imxrt/imxrt_flexio.h
FlexIO hardware register are now defined in the driver header with a kconfig guard. This blocks other drivers from using the definitions.
This PR moves the kconfig guard lower to access them.
minor
imxrt
=> imxrt: flexio move ifdef guard lower

arch/xtensa/src/esp32s3/esp32s3_partition.c, arch/xtensa/src/esp32s3/esp32s3_partition.h, arch/xtensa/src/esp32s3/esp32s3_spiflash.c, arch/xtensa/src/esp32s3/esp32s3_spiflash.h
- Add `esp32s3_flash_encryption_enabled` API.
- Support reading encrypted partitions
=> xtensa/esp32s3: Support reading encrypted partitions

arch/risc-v/src/esp32c3/Kconfig, arch/xtensa/src/esp32/Kconfig, arch/xtensa/src/esp32s2/Kconfig, arch/xtensa/src/esp32s3/Kconfig
* espressif/mcuboot: Fix dependency of the Espressif's port MCUboot.
If the MCUboot (from the `nuttx-apps`) is selected, the Espressif's port of the MCUboot (on upstream MCUboot repository) is not used as the 2nd stage bootloader.
Avoid misuse of the MCUboot from the `nuttx-apps` repository on Espressif's SoCs
Internal CI testing + ESP32-DevKitC V4
=> espressif/mcuboot: Fix dependency of the Espressif's port MCUboot.

fs/fat/fs_fat32.c, fs/fat/fs_fat32util.c
Fix the issue where fat driver is not using the last two clusters in the file system.
The fat parameter fs->fs_nclusters is the maximum number of data clusters; this doesn't include the two in the beginning. Many checks in the fat driver treat the fs->fs_nclusters-1 as being the last accessible cluster, which is not right, the last accessible one is actually this number + 2 when the cluster count includes the two first ones.
Normally this is not an issue when writes are being done through the same driver, the last two clusters are just never used. But if the filesystem is modified by external driver, for example with a populated fat created with PC, or modifying the FS via USB-MSC, this leads to the fat driver not being able to read anything that uses the last two clusters.
For us this …
=> fs/fat: Fix number of data clusters usable for fat driver

arch/risc-v/src/common/riscv_mmu.h
fix typo in comment of mmu_get_region_size function
=> Update riscv_mmu.h to  fix typo in comment

arch/risc-v/include/mode.h
this adds CSR_TVEC definition for trap vector base address register to risc-v mode.h
None for existing RiscV ports
=> Update mode.h to add CSR_TVEC

include/nuttx/streams.h, libs/libc/stream/Make.defs, libs/libc/stream/lib_fileoutstream.c, libs/libc/stream/lib_lowoutstream.c
1. Add a global lowerout stream
which can simplify the steps of lib_sprintf writing data to the serial port
2. Add a file stream based on struct file
sim/nsh
=> libc/stream: add stream interface

net/local/local.h, net/local/local_accept.c, net/local/local_conn.c, net/local/local_connect.c, net/local/local_fifo.c, net/local/local_netpoll.c, net/local/local_recvmsg.c, net/local/local_release.c, net/local/local_sendmsg.c
move the accept logic into connect flow.
In order to successfully establish a blocking connection between the client and server on the same thread.
nonblock is not affected, and the block connect is now the same as the nonblock flow, other apis are not affected.
sim:local
=> net/local: make the call return of each process consistent with linux

fs/smartfs/smartfs_smart.c
```smartfs_rename()``` was stuck on the boards they need ```CONFIG_SMARTFS_ALIGNED_ACCESS```.
All of the boards they need ```CONFIG_SMARTFS_ALIGNED_ACCESS```
I tested with Raspberry Pi Pico W [like this](https://github.com/apache/nuttx/issues/11444).
=> fs: smartfs: Add necessary aligned access in smartfs_rename()

net/udp/udp_sendto_buffered.c
In this case, remote addr is all zero, and the length of the ip header is not recognized as ipv6_is_ipv4, This will cause problems in subsequent data filling.
sim:local
=> net/udp: set ipv6 remote addr before udpip_hdrsize

arch/arm64/CMakeLists.txt, arch/arm64/src/CMakeLists.txt, arch/arm64/src/cmake/Toolchain.cmake, arch/arm64/src/cmake/platform.cmake, arch/arm64/src/common/CMakeLists.txt, arch/arm64/src/qemu/CMakeLists.txt, boards/arm64/qemu/qemu-armv8a/CMakeLists.txt, boards/arm64/qemu/qemu-armv8a/src/CMakeLists.txt, libs/libc/machine/arm64/CMakeLists.txt, libs/libc/machine/arm64/gnu/CMakeLists.txt, tools/ci/testlist/other.dat
1. init arch arm64 CMake build
2. enable qemu-armv8a ci cmake build
arm64 arch
```
$ cmake -B build -DBOARD_CONFIG=qemu-armv8a:nsh -GNinja
$ cmake --build build -t menuconfig
$ qemu-system-aarch64 -cpu cortex-a53 -nographic -machine virt,virtualization=on,gic-version=3 -net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel ./nuttx
```
=> CMake:init arch arm64 CMake and qemu-armv8a build

drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.c, drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.h, drivers/wireless/ieee80211/bcm43xxx/bcmf_netdev.c
avoiding resource race conditions
cortex-m33 and bcm43xxx wifi chip
=> bcmf_driver: add ioctl_mutex to restrict ioctl from reentrant

tools/Unix.mk, tools/Win.mk
after the CI environment is upgraded to Ubuntu 22 and GNU make is upgraded to 4.3, 
`warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.` warning appears. 
**these warnings make it difficult to troubleshoot errors in github actions.**
this because when executing a shell in Make, the new shell created will not inherit the parallel environment of the parent shell(jobserver).
in our case:
```
$ make olddefconfig
```
CI warning
=> [Fix]CI warning in GNU make 4.3 'jobserver unavailable'

arch/sim/src/sim/CMakeLists.txt
sim: make the cmake version of hostfs build similar to the Makefile one
solve https://github.com/apache/nuttx/pull/11458#issuecomment-1870297510
=> sim: make the cmake version of hostfs build similar to the Makefile one

binfmt/libelf/libelf_bind.c, binfmt/libelf/libelf_symbols.c
log messages from binfmt are very much.
this is to adjust levels of a few based on debugging experiences. These non-critical logs were marked as errors. So we likely can adjust them as warnings so that real errors can stand out easily.
None as we can always adjust debug configs if we want see them.
checked with canmv230
=> adjust log levels of a few binfmt logs

arch/Kconfig
This is to align with ARCH_KMAP_VBASE by source codes. 
It also fixes CI warnings/errors reported by `tools/refresh.sh` for some KERNEL mode defconfigs.
None
=> add missing dependency to MM_KMAP for ARCH_KMAP_VBASE

include/nuttx/fs/hostfs.h, include/sys/types.h
it has been changed by https://github.com/apache/nuttx/pull/10303 without any explicit mentions. i suppose it was a mistake.
see https://github.com/apache/nuttx/pull/8201 and referenced PRs for previous discussions.
=> make 64-bit time_t back to unsigned

arch/arm/src/armv7-m/arm_exception.S, libs/libc/machine/arm/armv7-m/gnu/arch_memchr.S, libs/libc/machine/arm/armv7-m/gnu/arch_memcpy.S, libs/libc/machine/arm/armv7-m/gnu/arch_memmove.S, libs/libc/machine/arm/armv7-m/gnu/arch_memset.S, libs/libc/machine/arm/armv7-m/gnu/arch_strcmp.S, libs/libc/machine/arm/armv7-m/gnu/arch_strcpy.S, libs/libc/machine/arm/armv7-m/gnu/arch_strlen.S
Current armv7-m end up in `.text` without any way for the linker to relocate the symbol.
Symbol relocation is needed for example to run the interrupt handler from ITCM
Minimal compile hints
ARMV7M imxrt
=> armv7-m: Expose section name to allow relocation

arch/risc-v/src/bl808/bl808_timerisr.c
The implementation of the RISC-V Timer for BL808 SoC is incomplete. This PR implements the BL808 RISC-V Timer by calling OpenSBI. The code is derived from NuttX for RISC-V QEMU.
The implementation of `up_timer_initialize` with OpenSBI is [explained in this article](https://lupyuen.github.io/articles/nim#appendix-opensbi-timer-for-nuttx).
With this PR, `sleep` and other Timer Functions will work correctly on BL808 SoC, instead of hanging indefinitely.
No impact on other SoCs.
We tested with `ostest` on Ox64 BL808 SBC:
```bash
$ tools/configure.sh ox64:nsh
```
`ostest` hangs when accessing the RISC-V Timer:
```text
nsh> ostest
...
ostest_main: Started user_main at PID=7
(Hang)
```
[(NuttX Log)](https://gist.github.com/lupyuen/37d5d2d27ed10f37e6c586b715cc33ef)
`ostest` works correctly with …
=> risc-v/bl808: Implement Timer with OpenSBI

arch/arm/src/Makefile, arch/arm64/src/Makefile, arch/risc-v/src/Makefile, arch/sim/src/Makefile, arch/xtensa/src/Makefile, libs/libc/symtab/symtab_findbyvalue.c, tools/mkallsyms.py
1. support sorting symbol tables by name
2. libs: fix the problem that the address obtained in thumb mode cannot be executed.
In arm, the lowest bit of the instruction is 1, which is a thumb instruction, and 0, which is an arm instruction.
The nm command was used in mkallsym.sh before, and the result it will return will set the lowest bit of the thumb instruction to 0. 
There will be a one-byte deviation during binary search, so mkallsyms.py will also set the lowest bit to 0 according to the previous format.
```sh
arm-none-eabi-nm -Cn nuttx | grep hello
0801c384 T hello_main
arm-none-eabi-objdump nuttx -t |grep hello
0801c384 g F .text 0000004c hello_main
arm-none-eabi-readelf nuttx -s |grep hello
4558: 0801c385 76 FUNC GLOBAL DEFAULT 1 hello_main
```
However, in the following case, when …
=> support sorting symbol tables by name

drivers/mtd/CMakeLists.txt, drivers/mtd/Kconfig, drivers/mtd/Make.defs, drivers/mtd/at25ee.c, include/nuttx/eeprom/spi_xx25xx.h, include/nuttx/mtd/mtd.h
Adds MTD driver for AT25 SPI EEPROM devices, based on character driver code by @slorquet and the existing at24xx.c block driver code
None.
Custom board, SAMA5D27C-D1G with 32kbyte SPI EEPROM on board.
=> Add MTD for AT25 eeprom

drivers/virtio/virtio-mmio.c
Follow the linux does, ack the mmio irq as soon as possible to avoid miss interrupt.
Optimize the mmio interrupt ack
iperf with qemu-armv8a:netnsh
=> virtio-mmio: ack the interrupt as soon as possible

boards/arm64/qemu/qemu-armv8a/src/qemu_bringup.c
tmpfs can be used for the rpmsgfs test after the qemu rptun driver added.
Should be none
qemu-armv8a:netnsh with CONFIG_FS_TMPFS enable
=> qemu_bringup: add tmp fs mount for qemu-armv8a

net/local/local_sendmsg.c
When peer->lc_cfpcount == LOCAL_NCONTROLFDS,
Line 122: peer->lc_cfps[peer->lc_cfpcount++] = filep2; access out-of-range
Bug fix
The static code scanning tool scanned this issue.
=> local_sendmsg: fix peer->lc_cfps[] array out-of-range write

net/rpmsg/rpmsg_sockif.c
Follow the posix standard:
If no messages are available to be received and the peer has performed an orderly shutdown, recv() shall return 0.
rpmsg socket
sim:rpserver, rpproxy, and rpmsg socket example (EXAMPLES_RPMSGSOCKET)
=> rpmsg_sockif: recv/recvmsg return 0 when peer close

drivers/virtio/virtio-mmio.c
Not found the mmio device is a normal case, so should not print the error log.
This commit changes the log level to info when not found the mmio device.
Remove unnecessary error log
qemu-armv8a:netnsh with error log enable
=> virtio-mmio: avoid output error log when not found mmio device

arch/arm/src/goldfish/Kconfig, arch/arm/src/qemu/Kconfig
Add ARCH_CHIP_QEMU_TRUSTZONE to enable/disable the TrustZone support beacause qemu also support enable/disable Arm Security Extensions: https://qemu-project.gitlab.io/qemu/system/arm/virt.html when launch.
qemu chip 
qemu-armv7a:nsh
=> armv7a/qemu: add QEMU_TRUSTZONE config and default n

drivers/misc/rpmsgdev_server.c
Do nothing instead assert when poll notify is called after teardown.
rpmsgdev
sim:rpserver and sim:rpproxy
=> rpmsgdev_server: do not notify the client when the fds has teardown

sched/misc/assert.c
fix flags type, should be irqstate_t
should be none
qemu-armv8a:netnsh compile pass
=> assert: fix flags type, should be irqstate_t

arch/arm/src/sama5/sam_lcd.c
The SAMA5 lcd driver was missing option to set the PWM clock source for backlight dimming
None - uses new board-specific #define
Custom board with SAMA5D27C-D1G and 800x480 TFT LCD with dimmable backlight
=> SAMA5 - add LCD backlight PWM clock source selection

arch/risc-v/src/qemu-rv/qemu_rv_start.c
This contain revision for kernel mode startup logic:
- no need for SUM as it is taken care by `riscv_set_idleintctx()`
- fix the CLEAR_CSR() before setting MPP field
rv-virt kernel build
checked with `rv-virt/knsh32` and `rv-virt/knsh64`
=> risc-v/rv-virt: revise mstatus operations

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_mpu.c, arch/risc-v/src/mpfs/mpfs_mpu.h
MPUCFG registers are used to enforce memory protection for DMA master devices.
Add new driver
MPFS
=> mpfs_mpu: Add driver to set MPUCFG registers

arch/risc-v/include/litex/irq.h
The LITEX_LAST_IRQ looks like a typo and it blocks build of `arty_a7/knsh` configuration. 
This fixes the build issue but I have no such device for test.
risc-v/arty_a7 devices
can build but lack of devices for test
=> risc-v/litex: fix typo in litex/irq.h

net/can/can_callback.c
If we just clear the IOB when failed to queue, we'll leak it.
Minor, `iob_tryadd_queue` failure in `can_datahandler`.
CI
=> net/can: Release IOB when failed to queue in datahandler

drivers/virtio/virtio-mmio.c
The length of some config elements are not equal to 1,2,4,8, so we can't assert in virtio_mmio_config_read/write() direclty when length != 1,2,4,8
For example, in virtio_net_config from virtio spec v1.2
```
struct virtio_net_config {
u8 mac[6];
le16 status;
le16 max_virtqueue_pairs;
le16 mtu;
le32 speed;
u8 duplex;
u8 rss_max_key_size;
le16 rss_max_indirection_table_length;
le32 supported_hash_types;
};
```
The mac length is 6 and not equal to 1,2,4,8
Virtio Driver Config Read/Write
Virtio-Net with feature VIRTIO_NET_F_MAC
=> virtio-mmio: use byte to byte in read/write config when length != 1,2,4,8

arch/arm/src/imxrt/imxrt_enet.c, drivers/net/Kconfig, include/nuttx/net/mii.h
Support runtime phy selection based on a list    supplied by board.h
For Example:
```
#define BOARD_ETH0_PHY_LIST                   \
{                                        \
"LAN8742A",                      \
MII_PHYID1_LAN8742A,             \
MII_PHYID2_LAN8742A,             \
MII_LAN8740_SCSR,                \
0,                               \
0xffff,                          \
MII_LAN8720_SPSCR_10MBPS,        \
MII_LAN8720_SPSCR_100MBPS,       \
MII_LAN8720_SPSCR_DUPLEX,        \
22,                              \
},                                       \
{                                        \
"TJA1103",                       \
MII_PHYID1_TJA1103,              \
MII_PHYID2_TJA1103,              \
0xffff,                          \
18,                              \
0xffff, …
```
=> net:Add support for multi PHY and optionally use it on imxrt

boards/risc-v/k230/canmv230/scripts/Make.defs, boards/risc-v/k230/canmv230/scripts/ld-flat.script, boards/risc-v/k230/canmv230/scripts/ld-kernel.script, boards/risc-v/k230/canmv230/src/Makefile, boards/risc-v/k230/canmv230/src/canmv_init.c, boards/risc-v/k230/canmv230/src/romfs_stub.c
changes:
- under boards/risc-v/k230/canmv230/scripts/:
- Make.defs            add POSTBUILD actions
- ld-flat.script         minor reformating
- ld-kernel.script   minor reformating
- under boards/risc-v/k230/canmv230/src/:
- Makefile               add clean of generated ROMFS source
- canmv_init.c        use `ferr` and drop too late runtime warning
- romfs_stub.c       use const for romfs_img_len
The POSTBULD actions can warn stub ROMFS usage at build time, thus the too late warning in canmv_init.c can be removed. 
The cleaning of `libboard.a` in POSTBUILD can also ensure real ROMFS is in use, as some times weak_data is still in use.
risc-v canmv230 device 
tested with canmv230
=> risc-v/k230: revise CanMV230 kernel build support

boards/arm/stm32l4/nucleo-l432kc/include/board.h
Fix board configuration for USART2.
Currently users are not able to connect to USART2 using default NSH configuration as the board Nucleo-l432kc does not expose the PA15 on its connectors, so this commit make PA3 the default pin for USART2
Table 16 from UM1956 - User manual
Users will be able to connect to NSH using USART2 without any additional configuration.
- Build NSH config
- Connect to NSH via USART2
nsh> uname -a
NuttX 12.3.0 b516b29efc-dirty Jan  7 2024 19:25:49 arm nucleo-l432kc
nsh>
=> nucleo-l432kc: Fix board configuration for USART2

boards/arm/stm32h7/nucleo-h745zi/src/stm32_bringup.c
The share memory name should be same, and the cpuname is the remote cpu name.
board nucleo-h745zi
nucleo-h745zi:nsh_cm4_rptun and nucleo-h745zi:nsh_cm7_rptun
=> nucleo-h745zi/stm32_bringup.c: the cpuname should be the remote cpu name

fs/rpmsgfs/rpmsgfs.h, fs/rpmsgfs/rpmsgfs_client.c, fs/rpmsgfs/rpmsgfs_server.c
In order to avoid the different memory occupied by the structure on different systems, this PR unifies the data type of the structure so that it occupies the same memory on 64-bit, 32-bit systems and other systems.
Improved communication protocol consistency of rpmsgfs to help reduce potential communication errors.
Test in sim vela and 86panel.
=> rpmsgfs: synchronous message transfer format

net/tcp/tcp_conn.c, net/tcp/tcp_send_buffered.c, net/tcp/tcp_send_unbuffered.c, net/tcp/tcp_sendfile.c, net/udp/udp_sendto_buffered.c, net/udp/udp_sendto_unbuffered.c
If we only enable one of `CONFIG_NET_ARP_SEND` and `CONFIG_NET_ICMPv6_NEIGHBOR`, both IPv4 and IPv6 traffic will send ARP or NDP, which causes problem.
Example:
`CONFIG_NET_ARP_SEND=n`
`CONFIG_NET_ICMPv6_NEIGHBOR=y`
Wrong:
IPv4 traffic (`PF_INET`) goes into `icmpv6_neighbor`, which definitely causes problem.
Correct:
IPv4 traffic doesn't call anything(`CONFIG_NET_ARP_SEND=n`), IPv6 traffic calls `icmpv6_neighbor`(`CONFIG_NET_ICMPv6_NEIGHBOR=y`)
The behavior of `CONFIG_NET_ARP_SEND` and `CONFIG_NET_ICMPv6_NEIGHBOR`, especially when we only enable one of them.
Manually & CI
=> net: Only call `arp_send` for `PF_INET` and `icmpv6_neighbor` for `PF_INET6`

include/nuttx/net/neighbor.h, net/neighbor/neighbor_add.c, net/netdev/netdev_findbyaddr.c, net/route/Kconfig, net/route/net_alloc_ramroute.c, net/route/net_router.c, net/route/netdev_router.c, net/route/route.h
Support longest prefix match routing described as "Longest Match" in RFC 1812, Section 5.2.4.3, Page 75.
Introduced `prefixlen` to indicate the prefix length of currently founded route, and only looks up for longer prefix in all later steps.
Routing Table with Kconfig protected.
Manually & CI
=> net/route: Support longest prefix match for routing

arch/xtensa/src/esp32s2/esp32s2_spi_slave.c, arch/xtensa/src/esp32s3/esp32s3_spi_slave.c
Following up the 'Espressif HAL fullly integration for ESP32s2/s3' changes in https://github.com/apache/nuttx/pull/11428. There are still few interrupt type constants need update. Updated them to avoid the build error.
ESP32s2/s3 SPI slave mode
Pass the build
=> esp32[s2|s3] Following up update interrupt type constants.

drivers/mtd/rpmsgmtd.c, drivers/mtd/rpmsgmtd.h, drivers/mtd/rpmsgmtd_server.c
1. rpmsgmtd_geometry_s use fixed length struct to transfer between two cpus.
2. Strip geometry out of ioctl and add rpmsgmtd_geometry_handler function, it will be called to process the return message of rpmsgmtd_get_geometry().
Improved communication protocol consistency of rpmsgmtd to help reduce potential communication errors.
Test in sim vela and 86panel.
=> rpmsgmtd: use fixed length struct to transfer between two cpus

arch/arm/src/armv8-r/arm_gicv3.c
arm/armv8-r: fix compile warning
```
armv8-r/arm_gicv3.c: In function 'gic_validate_dist_version': armv8-r/arm_gicv3.c:730:9: warning: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
730 |   sinfo("GICD_TYPER = 0x%x\n", typer);
|         ^~~~~~~~~~~~~~~~~~~~~  ~~~~~
|                                |
|                                uint32_t {aka long unsigned int}
armv8-r/arm_gicv3.c:730:26: note: format string is defined here
730 |   sinfo("GICD_TYPER = 0x%x\n", typer);
|                         ~^
|                          |
|                          unsigned int
|                         %lx
```
N/A
fvp-armv8r-aarch32/nsh
=> arm/armv8-r: fix compile warning

drivers/rptun/Kconfig, drivers/rptun/rptun.c
Remove rptun work queue related unused code, currently only rptun thread is used.
Make code leaner.
Tested in sim vela and 86 panel.
=> rptun: remove rptun work queue related unused code

arch/arm/src/fvp-v8r-aarch32/fvp_boot.c
arm/fvp-v8r: fix arm_earlyserialinit() is not called correctly 
USE_EARLYSERIALINIT will depends on the definition in arm_internal.h
N/A
fvp-armv8r-aarch32/nsh
=> arm/fvp-v8r: fix arm_earlyserialinit() is not called correctly 

arch/arm/src/armv8-r/arm_head.S
arm/armv8-r: wfi secondary cores if SMP is disabled 
Check cpu affinity in single core mode to avoid secondary cores bootup
N/A
fvp-armv8r-aarch32
=> arm/armv8-r: wfi secondary cores if SMP is disabled 

arch/risc-v/src/mpfs/mpfs_usb.c
This is not the right place to modify DMA memory protection values.
Why not? These are designed to protect other AMP mode instances. Opening the entire SoC's memory for the USB DMA kind of defeats this purpose.
Also, the driver cannot know how to configure these registers correctly, only opening up the whole SoC "works".
Remove security hole
MPFS
=> mpfs_usb.c: Remove PMPCFG configuration from the driver

arch/risc-v/src/mpfs/mpfs_mpu.c, arch/risc-v/src/mpfs/mpfs_mpu.h
Add method to lock an MPUCFG entry. Locking means the value of the register cannot be changed until the SoC is reset.
Remove security hole
MPFS
=> mpfs_mpucfg.c: Add mpfs_mpu_lock()

arch/risc-v/src/nuttsbi/sbi_mtimer.c
Chips like K230 has ARCH_RV64 but only supports 32-bit MMIO. So using ARCH_RV_MMIO_BITS is more proper here.
Configs using NUTTSBI
build only check.
=> risc-v/nuttsbi: use ARCH_RV_MMIO_BITS for mtimer access selection

arch/xtensa/src/esp32s3/esp32s3_wifi_adapter.c
* esp32s3/wifi: Fix Wi-Fi connection to WPA3-SAE APs.
This commit fixes the connection issues while trying to connect to WPA3-SAE-secured Access Points (APs).
Reenable connecting to WPA3-SAE-secured APs.
Internal CI testing + ESP32-S3-DevKitC-1 v1.0 (WROOM-1)
=> esp32s3/wifi: Fix Wi-Fi connection to WPA3-SAE APs.
