- arch/arm/src/armv7-a/arm_timer.c
frequency 0 should not be set
none
none
> arch/timer: frequency 0 should not be set

- arch/sim/src/sim/sim_rptun.c
- drivers/input/uinput.c
rptun support panit & reset and fix uinput_rpmsg bug
None
> rptun support panit & reset and fix uinput_rpmsg bug

- drivers/input/Kconfig
- drivers/input/button_upper.c
use delay configurable watchdog to implement debounce
new functionality
> drivers/input: Implement the debounce in button_upper.c

- drivers/mmcsd/sdio.c
> fix byte_block_count error in byte mode

- drivers/serial/pty.c
follow up the change https://github.com/apache/nuttx/pull/8691
internal test
> filter out control character in pty echo

- drivers/segger/Kconfig
- drivers/segger/syslog_rtt.c
add rtt syslog channel configuration
> drivers/rtt: add rtt syslog channel configuration

- include/hex2bin.h
- libs/libc/hex2bin/lib_fhex2mem.c
- libs/libc/hex2bin/lib_hex2bin.c
- libs/libc/hex2bin/lib_hex2mem.c
libs/libc/hex2bin: enhance 64-bit compatibility
N/A
ci-check
> libs/libc/hex2bin: enhance 64-bit compatibility

- drivers/input/CMakeLists.txt
- drivers/input/Make.defs
- drivers/input/mouse_upper.c
- include/nuttx/input/mouse.h
Implement mouse driver lower upper
new upperhalf
> drivers/input:support mouse driver

- drivers/virtio/CMakeLists.txt
- drivers/virtio/Kconfig
- drivers/virtio/Make.defs
- drivers/virtio/virtio-snd.c
- drivers/virtio/virtio-snd.h
- drivers/virtio/virtio.c
playback test:
```
nxplayer
device /dev/audio/pcm0p
playraw /data/test.wav 2 16 44100
stop
```
record test:
```
nxrecorder
device /dev/audio/pcm0c
recordraw /data/rec.pcm 2 16 16000
stop
```
new feature
> audio:add virtio snd driver

- drivers/spi/spi_slave_driver.c
Use pollout and pollpri to distinguish different scenarios
> spi/slave: use POLLPRI to notify TX_COMPLETE.

- arch/arm/src/nrf91/Kconfig
Add TABs
Add comments
Remove spaces from Kconfig file
none
> arch/arm/src/nrf91/Kconfig: Fix Kconfig style

- drivers/power/battery/goldfish_battery.c
1.make g_goldfish_gauge_ops  init C89 compatible
2. fix align style
> fix g_goldfish_gauge_ops init C89 compatible and align style

- boards/Kconfig
Add TABs
remove the extra ---help--- in config ARCH_BOARD_METRO_M4
none
> boards/Kconfig: Fix Kconfig style

- drivers/input/keyboard_upper.c
circbuf needs to be released in failure case
keyboard input driver
ci
> drivers/input:fix circbuf leak

- arch/arm/src/imxrt/imxrt_serial.c
ISR was corrupting SR settings.
> imxrt:Serial Preserve all but W1C bit in SR

- boards/arm64/qemu/qemu-armv8a/README.txt
- boards/risc-v/qemu-rv/rv-virt/README.txt
Update virtio gpu usage for arm64 and rv-virt boards
> boards: update README for virtio gpu driver

- drivers/mtd/mtd_partition.c
need forward to the real mtd device driver
internal test
> nuttx/mtd: Add new functions part_isbad and part_markbad in mtd partition.

- crypto/cryptodev.c
- crypto/cryptosoft.c
- include/crypto/cryptodev.h
(1) fix problem that link the software implementation with CONFIG_CYRPTODEV
(2) reduce image size with CONFIG_CYRPTODEV
> crypto: remove software algorithm coupling in cryptodev

- drivers/sensors/sensor.c
driver/sensor: update nbuffer to upper state
daily test
> driver/sensor: update nbuffer to upper state

- Kconfig
- drivers/timers/capture.c
- include/debug.h
> driver/capture : add capture debug, fixed compile warning

- include/nuttx/audio/audio.h
> driver/audio: add format for AAC/MSBC/CVSD

- mm/mempool/mempool.c
mempool:add check for double free check for mempool free
mempool
> mempool:add check for double free check for mempool free

- libs/libc/spawn/lib_psfa_adddup2.c
lib_psfa_adddup2:fix mem leak when failed
lib_psfa_adddup2
> lib_psfa_adddup2:fix mem leak when failed

- include/nuttx/audio/audio.h
> nuttx/audio: Add AUDIO_CHANNELS_RANGE macro

- drivers/syslog/syslog_rpmsg.c
syslog_rpmsg: update check method when do flush()
daily test
> syslog_rpmsg: update check method when do flush()

- arch/arm/src/armv6-m/arm_cpuinfo.c
- arch/arm/src/armv7-a/arm_cpuinfo.c
- arch/arm/src/armv7-m/arm_cpuinfo.c
- arch/arm/src/armv7-r/arm_cpuinfo.c
- arch/arm/src/armv8-m/arm_cpuinfo.c
- arch/arm/src/armv8-r/arm_cpuinfo.c
- arch/xtensa/src/common/xtensa_cpuinfo.c
show cpufreq when hardware performance counting enabled
cpuinfo
> cpuinfo: show cpufreq when hardware performance counting enabled

- drivers/note/note_driver.c
- drivers/note/noteram_driver.c
- include/nuttx/sched_note.h
driver/note: dump irq handler address to trace
output irq address when trace output
daily test
> driver/note: dump irq handler address to trace

- mm/iob/iob_alloc.c
Correct the calculation of timeout time
ARM Cortex-M33
> iob: add elapse calc for iob_allocwait

- Documentation/guides/tasktraceuser.rst
- drivers/note/Kconfig
- drivers/note/noteram_driver.c
add noteram crash dump， Dump all content when a crash occurs
> note: add noteram crash dump

- arch/arm/src/common/arm_backtrace_sp.c
> Avoid hard fault when reading vectors in text section.

- arch/Kconfig
- arch/arm/src/armv7-a/arm_gicv2.c
- arch/arm/src/armv7-a/arm_timer.c
- arch/arm/src/armv7-r/arm_gicv2.c
- arch/arm/src/armv7-r/arm_timer.c
- arch/arm64/src/common/arm64_gicv2.c
update secure handling to gic
none
none
> arch/arm: update secure handling to gic

- crypto/cryptodev.c
- crypto/cryptosoft.c
- crypto/xform.c
- include/crypto/cryptodev.h
- include/crypto/xform.h
(1)update iv in each encryption process
(2)support aes-ofb/aes-cfb128/aes-cfb8
> crypto: update aes algorithm process

- include/nuttx/net/ioctl.h
- net/netdev/netdev_ioctl.c
send CMD to restart controller in state bus-off
> socket can : support ioctl cmd SIOCCANRECOVERY

- drivers/math/math.c
- include/nuttx/math/cordic.h
- include/nuttx/math/math.h
Sorry for I wrong closed the PR, and I can not reopen it. 
https://github.com/apache/nuttx/pull/10282
@raiden00pl @xiaoxiang781216
> Cordic api modify

- include/nuttx/sdio_slave.h
new sdio slave driver interface
should not, because no chip provides sdio slave driver yet.
ci
> Add the module of SDIO Slave

- tools/ci/cibuild.sh
- tools/ci/docker/linux/Dockerfile
update to the last arm released toolchain
12.2rel1 to 12.3rel1
ci
> tools/ci: Update arm toolchain to 12.3rel1 

- include/nuttx/list.h
and remove the comment to avoid containing the potential Linux GPL code. see discussion here: https://github.com/apache/nuttx/pull/6926
no real change
ci
> include/nuttx/list: Rewrite list_entry/list_first_entry/list_last_entry

- libs/libc/stdio/lib_libfread.c
This change improves the performance when using larger CONFIG_STDIO_BUFFER_SIZE values as it allows architecture specific, or optimized memcpy algorithms to be utilized.
Improved fread performance when using larger CONFIG_STDIO_BUFFER_SIZE. 
Using our platform, based on the arty-a7, and a stdio buffer of 4096:
Before this change:
```
Operation              Variant          Size         Mean         Max          Min          Throughput(s)    Repetitions  Handles      Status
file_write             sequential       1.00B        361.16us     1.18ms       352.02us     2.70KB           100          1            0
file_read              sequential       1.00B        448.54us     8.97ms       358.58us     2.18KB           100          1            0
file_write             sequential       64.00B …
```
> libc/libfread: Use memcpy to copy read-ahead buffer to caller buffer.

- arch/sim/Kconfig
- drivers/serial/Kconfig
- drivers/serial/Make.defs
- drivers/serial/uart_bth5.c
- include/nuttx/serial/uart_bth5.h
add bth5 driver
none
test pass with Realtek Bluetooth (rtl8723)
> serial/uart/h5: add bt h5 uart serial driver

- drivers/syslog/ramlog.c
- drivers/syslog/syslog_rpmsg.c
syslog & ramlog: add BOARDIOC_RESET_CAUSE for syslog & ramlog
syslog & ramlog
VELA
> syslog & ramlog update

- Documentation/quickstart/install.rst
> Documentation/quickstart/install.rst: update fix incorrect version

- cmake/nuttx_export_header.cmake
there is a incremental compile issue in the PR https://github.com/apache/nuttx/pull/10224
`COPY` will cause error when modify header files will not take effect.
so I separate the header files used for compilation from the exported targets.
same as  https://github.com/apache/nuttx/pull/10224
and `cmake --install build`
> cmake:export_header support origin link and export install

- boards/arm/nrf52/common/include/nrf52_lsm9ds1.h
- boards/arm/nrf52/common/src/CMakeLists.txt
- boards/arm/nrf52/common/src/Make.defs
- boards/arm/nrf52/common/src/nrf52_lsm9ds1.c
- boards/arm/nrf52/nrf52840-dk/src/nrf52_bringup.c
- drivers/sensors/lsm9ds1.c
nrf52840-dk: add lsm9ds1 sensor support
> nrf52840-dk: add lsm9ds1 sensor support

- include/alloca.h
libs/alloca: add alloca implement for MSVC
Reference:
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/alloca?view=msvc-170
N/A
visual studio 2023 + cmake
> libs/alloca: add alloca implement for MSVC

- drivers/power/supply/regulator.c
- include/nuttx/power/consumer.h
1.check the id when register, if the same, return NULL
2.add FAR to the regulator_get input param
> Regulator:check the id when register

- tools/mkexport.sh
- tools/toolchain.cmake.export
Add a CMake toolchain in the exported archive so that application can use it directly.
close #10402
> RFC: Add a toolchaine file for CMake in exported archive.

- tools/ci/cibuild.sh
Stabilize MACOS CI
Should improved CI pass rate
Pass CI
> tools/ci: ensure removing python and openssl related commands

- drivers/serial/serial.c
driver/serial: fix error echo about VT100 escape sequence
fix error echo about VT100
daily build
> driver/serial: fix error echo about VT100 escape sequence

- drivers/serial/uart_rpmsg.c
driver/serial: fix race condition about calling rxflowcontrol in mutli thread
fix race condition
daily test
> driver/serial: fix race condition about calling rxflowcontrol in mutli thread

- net/tcp/tcp_input.c
If the sack is enabled and the ofosegs has gap, after the received out of order packets are inserted into ofosegs and early return, so tcp cannot update the tx_unacked, peer received packets will retransmitted after the tcp_timer timeout.
So update tx_unacked first.
Cortex-M33
> tcp_input: update tx_unack before reorder_ofosegs

- Documentation/quickstart/configuring.rst
Add credentials on code blocks  Build & run
> Documentation/quickstart/configuring.rst: Add credentials for NSH session

- libs/libc/pwd/lib_pwd.h
> pwd: fix syntax error

- arch/risc-v/src/litex/litex_sdio.c
Wraps litex_eventwait in a critical section to handle the case that an event can occur before it's waited on.
Improves reliability of sdio driver. Related to #10478
Custom hardware based on the `arty-a7`, while using `fstest` on a mounted emmc device.
> arch/risc-v/litex/litex_sdio: Address race condition in eventwait.

- arch/sim/src/sim/sim_internal.h
- arch/sim/src/sim/sim_rptun.c
- boards/sim/sim/sim/src/sim_bringup.c
support configuring whether the master will automatically boot slave
sim_rptun
> nuttx/sim: support configuring whether the master will automatically boot slave

- sched/misc/deadlock.c
Optimize `collect_deadlock` implementation
N/A
Pass CI
> sched/misc: optimize collect_deadlock implementation

- libs/libm/libmcs/.gitignore
- libs/libm/newlib/.gitignore
- libs/libm/openlibm/.gitignore
> libm: ignore git submodules

- boards/arm/stm32/stm32f411e-disco/include/board.h
- boards/arm/stm32/stm32f411e-disco/src/Make.defs
- boards/arm/stm32/stm32f411e-disco/src/stm32_autoleds.c
- boards/arm/stm32/stm32f411e-disco/src/stm32_userleds.c
- boards/arm/stm32/stm32f411e-disco/src/stm32f411e-disco.h
- Add autoleds to STM32F411E-DISCO
- Add the 4 userleds to STM32F411E-DISCO
> Fixes f4 disco

- drivers/ioexpander/Kconfig
- drivers/ioexpander/Make.defs
- drivers/ioexpander/mcp23x08.c
- drivers/ioexpander/mcp23x08.h
Initial support to mcp23008
none
ProjectLab board
> mcp23008 Initial support

- arch/arm/src/cxd56xx/cxd56_cpu1signal.c
> cxd56xx: rm sched_[un]lock

- drivers/timers/arch_alarm.c
modify the default precision of up_perf_gettime to ns
> drivers/alarm: modify the default precision of up_perf_gettime to ns

- arch/sim/src/sim/posix/sim_alsa.c
fix Compiler Warning:initialization of ‘int (*)(struct audio_lowerhalf_s *, void *)’ from incompatible pointer type ‘int (*)(struct audio_lowerhalf_s *)’ [-Wincompatible-pointer-types]
> audio:add media session support for sim_alsa audio_ops_s interface

- boards/arm/stm32/stm32f411e-disco/src/Make.defs
- boards/arm/stm32/stm32f411e-disco/src/stm32_bringup.c
- boards/arm/stm32/stm32f411e-disco/src/stm32_buttons.c
- boards/arm/stm32/stm32f411e-disco/src/stm32f411e-disco.h
- Add user buttons to stm32f411e-disco board
> Draft: F411e disco buttons

- arch/arm/src/sama5/sam_hsmci.c
- arch/arm/src/samv7/sam_hsmci.c
sam_hsmci: rm sched_[un]lock
none
> sam_hsmci: rm sched_[un]lock

- net/can/can.h
- net/can/can_getsockopt.c
- net/can/can_recvmsg.c
- net/can/can_setsockopt.c
add error mask for CAN_RAW_ERR_FILTER
> socketcan : support error frame filter

- arch/arm/src/stm32/stm32_oneshot.c
- arch/arm/src/stm32h7/stm32_oneshot.c
- arch/arm/src/stm32l4/stm32l4_oneshot.c
- arch/arm/src/stm32wb/stm32wb_oneshot.c
- arch/mips/src/pic32mz/pic32mz_oneshot.c
> arm/oneshot: rm sched_[un]lock

- drivers/video/video.c
- libs/libc/machine/arm/armv7-a/Kconfig
- libs/libxx/libcxx.defs
- net/local/local_fifo.c
Fixed some compilation warnings and errors
Fixes compilation warnings and errors for CONFIG_DEBUG_OPTLEVEL="-O3"
> Fix warnings and error

- arch/arm/Kconfig
- arch/arm/include/goldfish/chip.h
- arch/arm/include/goldfish/irq.h
- arch/arm/src/goldfish/Kconfig
- arch/arm/src/goldfish/Make.defs
- arch/arm/src/goldfish/chip.h
- arch/arm/src/goldfish/goldfish_boot.c
- arch/arm/src/goldfish/goldfish_irq.c
- arch/arm/src/goldfish/goldfish_irq.h
- arch/arm/src/goldfish/goldfish_memorymap.c
- arch/arm/src/goldfish/goldfish_memorymap.h
- arch/arm/src/goldfish/goldfish_serial.c
- arch/arm/src/goldfish/goldfish_timer.c
Goldfish support for future expansion
> Goldfosh arm32

- net/can/can_recvmsg.c
can recv filter doesn't work when there is any CAN data already buffered in a read-ahead buffer
> socketcan/recv :  fixed recv filter not work in special case

- arch/sim/src/sim/posix/sim_alsa.c
- arch/sim/src/sim/posix/sim_hostmemory.c
- arch/sim/src/sim/posix/sim_hostmisc.c
- arch/sim/src/sim/sim_internal.h
To avoid system calls being interrupted when use host api
sim/posix api
> sim: To avoid system calls being interrupted when use host api

- mm/mempool/mempool.c
- mm/mm_heap/mm_free.c
- mm/tlsf/mm_tlsf.c
mm/heap: add coloration after free to detect use after free issue
debug user after free
daily test
> mm/heap: add coloration after free to detect use after free issue

- tools/checkpatch.sh
> tools: checkpach supports python files

- boards/x86_64/intel64/qemu-intel64/src/qemu_net.c
> boards/x86_64: Change up_netinitialize to x86_64_netinitialize

- arch/arm/Kconfig
- arch/arm/include/syscall.h
- arch/arm/src/common/CMakeLists.txt
- arch/arm/src/common/Make.defs
- arch/arm/src/common/arm_cpu_psci.c
- arch/arm/src/common/arm_cpu_psci.h
- arch/arm/src/common/arm_internal.h
- arch/arm/src/common/arm_smccc.S
- arch/arm/src/goldfish/Make.defs
- arch/arm/src/qemu/qemu_boot.c
support reboot / poweroff for qemu virt arm
> arm: support reboot / poweroff for qemu virt arm

- net/icmp/CMakeLists.txt
- net/icmpv6/CMakeLists.txt
- net/procfs/CMakeLists.txt
- net/tcp/CMakeLists.txt
update net CMakeLists.txt  to complement missing features
N/A
CI build
> cmake:complete missing changes during reforming for net

- drivers/usrsock/usrsock_rpmsg_server.c
A dead lock may happen before this patch:
- rptun thread (`usrsock_rpmsg_recvfrom_handler`):
- Gets all tx payload but waiting `net_lock` in `psock_recvfrom`
- net driver thread (higher priority):
- Receives a packet, holding `net_lock`, calling `usrsock_rpmsg_send_event`
- But no tx buffer left, so `rpmsg_send` blocks, and won't release `net_lock`
In short:
Rptun: Hold all `tx_payload_buffer` -> want `net_lock`
Driver: Hold `net_lock` -> want `tx_payload_buffer`
This patch use `net_lock` to combine `get_tx_payload` and `recvfrom` together, then:
- If it's waiting `net_lock`, tx payload will not be held, other threads may get tx buffer and do their work.
- If `net_lock` is got, it won't be disturbed before finish receiving, then tx payload won't have chance to be blocked before releasing. …
> usrsock_rpmsg_server: Add net_lock to combine get_tx_payload and recvfrom in recvfrom_handler

- boards/arm/qemu/qemu-armv7a/src/Makefile
- boards/arm/qemu/qemu-armv7a/src/qemu_bringup.c
- boards/arm64/qemu/qemu-armv8a/src/Makefile
- boards/arm64/qemu/qemu-armv8a/src/qemu_bringup.c
- tools/ci/cibuild.sh
qemu:fix ci error
qemu:nsh_gicv2 build
> qemu:fix ci error

- arch/sim/src/sim/posix/sim_alsa.c
- include/nuttx/audio/audio.h
> audio:add 24K sample rate support

- Documentation/applications/nsh/commands.rst
Updated the documentation for the date command.
Add Example.
Documentation only.
> Documentation/applications/nsh/commands.rst: Update date command

- binfmt/CMakeLists.txt
- binfmt/Makefile
- binfmt/binfmt_exec.c
- binfmt/binfmt_execmodule.c
- include/nuttx/binfmt/binfmt.h
Reverts apache/nuttx#10380 since the PR has an issue with CONFIG_DEBUG_ASSERTIONS=y
> Revert "Exec: Support run exec in current task"

- drivers/input/button_upper.c
After turning on the system by power button, the first press of the power button is ineffective.
Has been validated in the product
> input/button: First press pwrkey is ineffective

- drivers/power/pm/Kconfig
- drivers/power/pm/Make.defs
- drivers/power/pm/pm_runtime.c
- include/nuttx/power/pm_runtime.h
add  feature pm runtime  that can suspend/resume device by driver when system is running
none
self test
> support pm runtime function

- arch/arm/src/common/arm_backtrace_unwind.c
1. unwinder: fix unwind abort for uleb128 case
When unwind instruction is 0xb2,the subsequent instructions
are uleb128 bytes.
For now,it uses only the first uleb128 byte in code.
For vsp increments of 0x204~0x400,use one uleb128 byte like below:
0xc06a00e4 <unwind_test_work>: 0x80b27fac
Compact model index: 0
0xb2 0x7f vsp = vsp + 1024
0xac      pop {r4, r5, r6, r7, r8, r14}
For vsp increments larger than 0x400,use two uleb128 bytes like below:
0xc06a00e4 <unwind_test_work>: @0xc0cc9e0c
Compact model index: 1
0xb2 0x81 0x01 vsp = vsp + 1032
0xac      pop {r4, r5, r6, r7, r8, r14}
The unwind works well since the decoded uleb128 byte is also 0x81.
For vsp increments larger than 0x600,use two uleb128 bytes like below:
0xc06a00e4 <unwind_test_work>: @0xc0cc9e0c
Compact model index: 1
0xb2 …
> unwinder: fix unwind abort for uleb128 case

- arch/arm64/src/common/arm64_cpustart.c
fix arm64_start_cpu
INSTRUMENTATION
None
> fix arm64_start_cpu

- Documentation/platforms/arm/stm32h7/boards/nucleo-h745zi/index.rst
- Documentation/platforms/arm/stm32h7/index.rst
Documentation/stm32h7: supported chips and a brief description of dual-core
local build
> Documentation: update doc for stm32h7

- boards/sim/sim/sim/scripts/Make.defs
fix text-segment not taking effect
> sim: fix text-segment not taking effect

- arch/arm/src/samv7/sam_emac.c
- arch/arm/src/samv7/sam_ethernet.h
On boardlevel one can do reset, cable-check, diagnostics, check link quality and more on every link up
> samv7:add phy bordinit functionality

- include/nuttx/notifier.h
notifier: add BLOCKING_INIT_NOTIFIER_HEAD support
notifier
SIM
> notifier: add BLOCKING_INIT_NOTIFIER_HEAD support

- arch/arm64/src/Makefile
sync makefile build rules from arch/arm to fix some compile issue
None
Compile PASS
> arm64: sync make file rules from arch/arm

- net/rpmsg/rpmsg_sockif.c
rpmsg socket: add return value check.
rpmsg socket
SIM
> rpmsg socket: add return value check.

- arch/sim/src/sim/posix/sim_alsa.c
sim/alsa: add AUDIO_FMT_PCM query handler.
simulator
Xiaomi vela
> sim/alsa: add AUDIO_FMT_PCM query handler.

- drivers/clk/clk.c
- fs/procfs/fs_procfs.c
- include/nuttx/clk/clk_provider.h
procfs enrty add clock feature procfs operations
procfs
ci
> vela fs procfs add clock procfs entry

- arch/arm64/Kconfig
- arch/arm64/include/goldfish/chip.h
- arch/arm64/include/goldfish/irq.h
- arch/arm64/src/goldfish/Kconfig
- arch/arm64/src/goldfish/Make.defs
- arch/arm64/src/goldfish/chip.h
- arch/arm64/src/goldfish/goldfish_boot.c
- arch/arm64/src/goldfish/goldfish_boot.h
- arch/arm64/src/goldfish/goldfish_lowputc.S
- arch/arm64/src/goldfish/goldfish_serial.c
- arch/arm64/src/goldfish/goldfish_serial.h
- arch/arm64/src/qemu/qemu_boot.c
Goldfish support for future expansion
new arch/board
android emulator
> Goldfish arm64

- arch/arm64/Kconfig
- arch/arm64/src/common/arm64_cpu_psci.c
- arch/arm64/src/common/arm64_cpu_psci.h
support reboot / poweroff for qemu virt arm64
arm64 qemu
> arm64: support reboot / poweroff for qemu virt arm64

- drivers/mmcsd/mmcsd_sdio.c
- drivers/mmcsd/mmcsd_sdio.h
refer spec: https://www.jedec.org/sites/default/files/docs/JESD84-B51.pdf
> mmcsd: update cid reg layout

- drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.c
Some disconnected events will be missed
Cortex-M55
> wifi: Add handle type for disconnecting event

- include/nuttx/input/touchscreen.h
which is removed accidently in:
https://github.com/apache/nuttx/pull/9398
ci
> input/touchscreen: Bring up TSIOC_[SET|GET]CALIB macro

- drivers/sensors/Kconfig
- drivers/sensors/Make.defs
- drivers/sensors/goldfish_gps.c
- include/nuttx/sensors/goldfish_gps.h
Verification:
uorb_listener -r 1 sensor_gps
[   18.240000] [13] [  INFO] [ap]
Mointor objects num:2
[   18.240000] [13] [  INFO] [ap] object_name:sensor_gps, object_instance:0
[   18.240000] [13] [  INFO] [ap] object_name:sensor_gps, object_instance:1
[   18.240000] [13] [ ALERT] [ap] period_us = 1000000
[   19.010000] [13] [  INFO] [ap] sensor_gps:	timestamp: 19010000 (0 us ago) time_utc: 1689601925 latitude: 37.4210 longitude: -121.9150
[   19.010000] [13] [  INFO] [ap] sensor_gps:	altitude: 0.0000 altitude_ellipsoid: 0.0000 ground_speed: 145.3254 course: 166.2700
[   19.010000] [13] [  INFO] [ap] sensor_gps:	eph: nan epv: nan hdop: nan vdop: nan
[   20.020000] [13] [  INFO] [ap] sensor_gps:	timestamp: 20020000 (0 us ago) time_utc: 1689601926 latitude: 37.4210 longitude: -121.9150
[ …
> goldfish: add goldfish gps driver

- tools/minidumpserver.py
1. refactor code style and simplify parse method to make code more readable
2. change mem find algorithm to bi-search
> tools/minidumpserver: refactor codes

- drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.c
- drivers/wireless/ieee80211/bcm43xxx/bcmf_ioctl.h
Cortex-M55 and bcm43xxx chipset
> wireless/bcm43xxx: correct beacon loss behavior

- libs/libc/pthread/pthread_once.c
sched_[un]lock can not prohibit pre-emption in smp, https://github.com/apache/nuttx/issues/1137
none
> pthread_once: use rmutex replace sched_[un]lock 

- drivers/video/vnc/vnc_updater.c
sched_[un]lock can not prohibit pre-emption in smp, https://github.com/apache/nuttx/issues/1137
> vnc_updater: use [enter|leave]_critical_section replace sched_[un]lock

- drivers/wireless/ieee80211/bcm43xxx/Kconfig
- drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.c
- drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.h
- drivers/wireless/ieee80211/bcm43xxx/bcmf_ioctl.h
- drivers/wireless/ieee80211/bcm43xxx/bcmf_netdev.c
For Bluetooth wifi co-existence
Cortex-M55
> wireless/bcm43xxx: add Packet Traffic Arbitration Priority support

- drivers/spi/spi_slave_driver.c
driver/spi: call bind and unbind when user open or close to save power
daily test
> driver/spi: call bind and unbind when user open or close to save power

- arch/arm/src/sama5/sam_classd.c
A few incorrect printf formatters fixed up
None
> Fix printf format warnings

- libs/libc/wchar/CMakeLists.txt
- libs/libc/wchar/Make.defs
- libs/libc/wchar/lib_wcscat.c
- libs/libc/wchar/lib_wcschr.c
- libs/libc/wchar/lib_wcscpy.c
- libs/libc/wchar/lib_wcscspn.c
- libs/libc/wchar/lib_wcslcat.c
- libs/libc/wchar/lib_wcsncat.c
- libs/libc/wchar/lib_wcsncmp.c
- libs/libc/wchar/lib_wcsncpy.c
- libs/libc/wchar/lib_wcsrchr.c
add wchar api implementation: wcscpy, wcscat, wcslcat, wcsncat, wcsrchr, wcschr, wcsncpy, wcsncmp, wcsspn
> add wchar implementation

- tools/minidumpserver.py
support to extract log and list all possible dumps from a full log file
now user can parse a full log but not only the specific part of the full log.
if user pass a full log contains multi crash logs, they will get a `tui` like this:
```bash
0: [12/31 00:01:36] [50] [xp] up_dump_register: R0: 3c23a4e0 R1: 000
1: [12/31 00:01:36] [50] [xp] up_dump_register: R0: 000000e0 R1: 000
Dump number[0]:
```
input the index for what to parse and debug.
if there is only one available crash log in the full log, it will start the process straightly.
> tools/minudumpserver: support auto parse log file feature

- Kconfig
Kconfig: add ICS license option
CI
> Kconfig: add ICS license option

- tools/configure.sh
this is a solution to the https://github.com/apache/nuttx/issues/10253
> configure.sh:give a prompt when appsdir cannot be found

- boards/arm/sam34/arduino-due/include/board.h
- boards/arm/sam34/arduino-due/src/Makefile
- boards/arm/sam34/arduino-due/src/sam_bringup.c
- boards/arm/sam34/arduino-due/src/sam_spidev.c
Added the activation of SPI0 on arduino due.
> Add activation of SPI0 on arduino due

- arch/arm/src/common/arm_hostfs.c
- arch/arm64/src/common/arm64_hostfs.c
- arch/risc-v/src/common/riscv_hostfs.c
Fix regression reported here: https://github.com/apache/nuttx/pull/10758
> hostfs: mask bit fields of not support

- arch/arm/Kconfig
- arch/arm/src/goldfish/goldfish_boot.c
- arch/arm/src/qemu/qemu_boot.c
> arch/arm: Enable FPU on qemu and goldfish platforms

- tools/minidumpserver.py
support auto start GDB and execute some commands
like
```bash
./nuttx/tools/minidumpserver.py -l log.log -e vela_ap.elf -a arm --gdb prebuilts/gcc/linux/arm/bin/arm-none-eabi-gdb -i
```
it will start gdb (you provided) automatically and input some commands (with -i), and press Ctrl-C to stop.
> tools/minudumpserver: support auto start GDB and execute some commands

- arch/sim/Kconfig
- arch/sim/src/sim/sim_uart.c
> arch/sim: add sim uart_ram support

- include/nuttx/compiler.h
- mm/kasan/kasan.c
kasan: add builtin_return_address(0) to kasan
Kasan
BES board
> kasan: add builtin_return_address(0) to kasan

- drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.c
I added a function that I didn't use when I upstream another patch https://github.com/apache/nuttx/pull/10709. Delete it
sim:local
> bcm43xxx: remove unuse function

- drivers/power/pm/pm_changestate.c
check the domain in pm_querystate
self test
> pm:check the domain in pm_querystate

- arch/risc-v/src/esp32c3/esp32c3_crypto.c
- crypto/chachapoly.c
- crypto/cryptodev.c
- crypto/gmac.c
- crypto/xform.c
- include/crypto/chachapoly.h
- include/crypto/gmac.h
- include/crypto/xform.h
(1) remove size restriction for single hash operation
(2) support hash operation to update uint32_t data
> crypto/cryptodev: expansion hash operation

- include/nuttx/mm/mm.h
- mm/mempool/mempool.c
- mm/mm_heap/mm_mallinfo.c
- mm/mm_heap/mm_memdump.c
- mm/tlsf/mm_tlsf.c
mm: rewrite the memdump code for more readable
mm
SIM & BES board
> mm: rewrite the memdump code for more readable

- libs/libc/libc.csv
> libc: Add bsearch to libc.csv

- drivers/virtio/virtio-snd.c
qemu host virtio device don't support recvice the same cmd like start/stop twice
virtio sound
qemu
> audio:add state sync for virtio snd device

- include/nuttx/list.h
The function name comes from list.h inside Linux,
but rewrite from scratch to avoid the copyright issue.
Since many developers are familiar with Linux list API.
list.h
allwiner R528 and BES 2300.
> list: update list.h

- arch/arm/src/sama5/sam_tsd.c
If the main ADC trigger is set to SOftware trigger, the TSD can fail to trigger correctly in all circumstances.
The pressure reading was scaled 0-4096 (max to min) which I believe is back to front and should be 0 to UINT16_MAX (min to max)
None unless anyone is already making use of SAMA5 TSD pressure readings.
Custom board with SAMA5D27C-D1G and 800x480 TSD
> SAMA5 - TSD trigger and pressure scaling issues

- include/nuttx/dma/dma.h
> dma: support source/destination address auto step

- arch/arm/src/stm32l4/stm32l4_adc.c
- arch/arm/src/stm32l4/stm32l4_adc.h
Adds low level operations to start and stop DMA.
No impact is expected.
Tested on a custom board.
> STM32L4 ADC: Adds low level operations to start and stop DMA.

- arch/risc-v/src/mpfs/mpfs_corespi.c
This is a collection of tweaks / optimizations to the driver to limit CPU usage as well as interrupt processing times.
The changes are as follows:
- setfrequency is now no-op if the frequency does not change. Accessing MPFS_SPI_CONTROL requires synchronization to the FIC domain, which takes unnecessary time if nothing changes
- load/unload FIFO loops optimized so !buffer, priv->nbits and i==last are only tested once (instead of for every word written in loop).
- Disable the RX interrupt only once (again, FIC domain access is slow)
- In case a spurious MPFS_SPI_DATA_RX interrupt arrives, just wipe the whole RX FIFO, instead of trying to read it byte-by-byte
MPFS CoreSPI driver only
Multisensor application that uses CoreSPI, perf. impact is ~20% per sensor instance.
> mpfs/mpfs_corespi: Several speed optimizations to the FPGA driver

- arch/arm/src/arm/arm_tcbinfo.c
- arch/arm/src/armv6-m/arm_tcbinfo.c
- arch/arm/src/armv7-a/arm_tcbinfo.c
- arch/arm/src/armv7-m/arm_tcbinfo.c
- arch/arm/src/armv7-r/arm_tcbinfo.c
- arch/arm/src/armv8-m/arm_tcbinfo.c
- arch/risc-v/src/common/riscv_tcbinfo.c
- arch/sim/src/sim/sim_tcbinfo.c
- arch/x86_64/src/common/x86_64_tcbinfo.c
- arch/xtensa/src/common/xtensa_tcbinfo.c
to avoid compiler/linker remove it from the final image
minor
ci
> arch: add use_data to g_tcbinfo

- arch/arm/src/nrf52/nrf52_start.c
- arch/arm/src/nrf53/nrf53_start.c
- arch/arm/src/nrf91/nrf91_start.c
arch/nrf{52|53|91}: add support for up_perf
CI
> arch/nrf{52|53|91}: add support for up_perf

- arch/xtensa/src/esp32/esp32_irq.c
* esp32/irq: Fix erroneous interrupt allocation for each CPU core
When allocating a CPU interrupt, make sure to select the correct CPU core to query for it. Simply checking for the current CPU does not satisfy this requirement because the CPU allocation thread may be executed by the other core: it's necessary to stick with the intended CPU passed as 
an argument of the `esp32_setup_irq`.
Fix erroneous CPU allocation when SMP is enabled for ESP32.
Internal CI testing + ESP32-DevKitC.
> esp32/irq: Fix erroneous interrupt allocation for each CPU core

- arch/ceva/src/common/ceva_modifyreg16.c
- arch/ceva/src/common/ceva_modifyreg32.c
- arch/ceva/src/common/ceva_modifyreg8.c
spin_lock_irqsave() should be spin_lock_irqsave(NULL)
None
CI
> format: modify spin_lock_irqsave format

- libs/libc/misc/lib_memfd.c
as specified at:
https://man7.org/linux/man-pages/man2/memfd_create.2.html
memfd
internal
> lib/memfd: shm_unlink or unlink anonymous file

- arch/arm/src/armv7-a/arm_cpupause.c
- arch/arm/src/armv7-r/arm_cpupause.c
- arch/arm/src/cxd56xx/cxd56_cpupause.c
- arch/arm/src/lc823450/lc823450_cpupause.c
- arch/arm/src/rp2040/rp2040_cpupause.c
- arch/arm/src/sam34/sam4cm_cpupause.c
- arch/arm64/src/common/arm64_cpupause.c
- arch/risc-v/src/common/riscv_cpupause.c
- arch/sim/src/sim/sim_smpsignal.c
- arch/sparc/src/s698pm/s698pm_cpupause.c
- arch/xtensa/src/common/xtensa_cpupause.c
- include/nuttx/spinlock.h
- libs/libc/pthread/pthread_spinlock.c
- sched/irq/irq_csection.c
- sched/sched/sched.h
- sched/sched/sched_lock.c
- sched/sched/sched_unlock.c
align with Linux api naming.
new api
ci
> spinlock: Add spin_lock_init and spin_is_locked macro

- include/fixedmath.h
- libs/libdsp/lib_misc_b16.c
- libs/libdsp/lib_observer.c
- libs/libdsp/lib_observer_b16.c
- fixedmath: add abs and sign operations
- libdsp/lib_observe: fix typo and use b16sign()
- libds/lib_misc: use b16abs()
ci
> fixedmath: add abs and sign operations

- arch/risc-v/src/common/riscv_addrenv_pgmap.c
- include/nuttx/arch.h
- mm/kmap/kmm_map.c
This fixes several fatal issues with the kernel mapping interface. Highlights are in the commit messages.
kmm_map only (CONFIG_BUILD_KERNEL and CONFIG_MM_KMAP)
mpfs + CONFIG_BUILD_KERNEL
> mm/kmm_map: Fix several issues with the kmm_map interface

- arch/arm/src/sama5/sam_tsd.c
- drivers/input/ads7843e.c
- drivers/input/mxt.c
- drivers/input/tsc2007.c
- drivers/usbhost/usbhost_hidmouse.c
- drivers/usbhost/usbhost_xboxcontroller.c
Fix some typos in comments
none
none
> Fix some typos in comments

- arch/arm/src/mx8mp/Kconfig
Remove extra TABs
Add comments
none
> arch/arm/src/mx8mp/Kconfig: Fix Kconfig style

- arch/arm/src/phy62xx/types.h
- arch/arm/src/tlsr82/hardware/tlsr82_register.h
- arch/arm64/src/common/arm64_arch.h
- arch/risc-v/src/esp32c3/hardware/esp32c3_soc.h
- arch/xtensa/src/esp32/hardware/esp32_soc.h
- arch/xtensa/src/esp32s2/hardware/esp32s2_soc.h
- arch/xtensa/src/esp32s3/hardware/esp32s3_soc.h
- drivers/clk/clk.h
- drivers/lcd/max7219.c
- drivers/lcd/memlcd.c
- drivers/sensors/mpu60x0.c
- drivers/serial/serial_pl011.c
- drivers/video/max7456.c
- include/nuttx/bits.h
- include/nuttx/sensors/mpu9250.h
refine: move BIT Macro to nuttx/bits.h
none
none
> refine: move BIT Macro to nuttx/bits.h

- fs/vfs/fs_pseudofile.c
- Add munmap logic to pseudo fs to prevent munmap from ret EINVAL when called.
> add munmap logic to pseudofs

- drivers/note/note_driver.c
> drivers/note: Change 0/1 to false/true

- arch/arm/src/armv7-a/arm_cpupause.c
- arch/arm/src/armv7-r/arm_cpupause.c
- arch/arm/src/cxd56xx/cxd56_cpupause.c
- arch/arm/src/lc823450/lc823450_cpupause.c
- arch/arm/src/rp2040/rp2040_cpupause.c
- arch/arm/src/sam34/sam4cm_cpupause.c
- arch/arm64/src/common/arm64_cpupause.c
- arch/risc-v/src/common/riscv_cpupause.c
- arch/sim/src/sim/sim_smpsignal.c
- arch/sparc/src/s698pm/s698pm_cpupause.c
> cpu_pause.c: fix typo

- Kconfig
- drivers/motor/CMakeLists.txt
- drivers/motor/Kconfig
- drivers/motor/Make.defs
- drivers/motor/a4988.c
- drivers/motor/stepper.c
- include/debug.h
- include/nuttx/fs/ioctl.h
- include/nuttx/motor/a4988.h
- include/nuttx/motor/stepper.h
- include/nuttx/motor/stepper_ioctl.h
Add a stepper generic upper-half driver
Add a stepper A4988 lower-half driver
close #10903
> Add stepper interface

- include/nuttx/spinlock.h
- sched/Kconfig
- sched/irq/irq_spinlock.c
- sched/semaphore/spinlock.c
Implement rw spinlock
None
https://github.com/apache/nuttx-apps/pull/2076
But I think the test is not enough. It can't sure when reader get lock, the write have to spin.
Does anyone have good methods?
> rw spinlock

- drivers/motor/CMakeLists.txt
- drivers/motor/Kconfig
- drivers/motor/Make.defs
- drivers/motor/drv8825.c
- drivers/motor/stepper.c
- include/nuttx/motor/drv8825.h
- include/nuttx/motor/stepper.h
- include/nuttx/motor/stepper_ioctl.h
Add DRV8825 stepper driver
Change step frequency from step/ms to step/s
misc: cleanup status retrieval
Required to have a proper speed unit for the stepper example [PR](https://github.com/apache/nuttx-apps/pull/2118)
> Stepper: add DRV8825

- drivers/note/note_driver.c
- drivers/note/noteram_driver.c
- include/nuttx/note/note_driver.h
- include/nuttx/sched_note.h
Delete the event code left behind by previous modifications
> note: remove remaining event code

- arch/risc-v/src/common/pgalloc.h
- arch/risc-v/src/common/riscv_addrenv.c
Fixes two minor bugs related to SHM mappings
RELEASE
MR1
> {BP-10829} risc-v/addrenv: Fix two SHM related issues

- arch/arm/src/sama5/sam_tsd.c
- drivers/input/ads7843e.c
- drivers/input/mxt.c
- drivers/input/tsc2007.c
- drivers/usbhost/usbhost_hidmouse.c
- drivers/usbhost/usbhost_xboxcontroller.c
Fix some typos in comments
RELEASE
RC1
> {BP-10889} Fix some typos in comments

- arch/arm/src/armv7-a/arm_cpupause.c
- arch/arm/src/armv7-r/arm_cpupause.c
- arch/arm/src/cxd56xx/cxd56_cpupause.c
- arch/arm/src/lc823450/lc823450_cpupause.c
- arch/arm/src/rp2040/rp2040_cpupause.c
- arch/arm/src/sam34/sam4cm_cpupause.c
- arch/arm64/src/common/arm64_cpupause.c
- arch/risc-v/src/common/riscv_cpupause.c
- arch/sim/src/sim/sim_smpsignal.c
- arch/sparc/src/s698pm/s698pm_cpupause.c
> {BP-10908} cpu_pause.c: fix typo

- arch/sim/src/sim/posix/sim_hostmisc.c
Improve multiplatform code with __has_include.
RELEASE
RC1
> {BP-10910} Update Fix more generic for platforms that do not have execinfo.h

- arch/risc-v/src/common/riscv_addrenv_pgmap.c
- include/nuttx/arch.h
- mm/kmap/kmm_map.c
This fixes several fatal issues with the kernel mapping interface. Highlights are in the commit messages.
RELEASE
MR1
> {BP-10876} mm/kmm_map: Fix several issues with the kmm_map interface

- crypto/CMakeLists.txt
- crypto/Makefile
- crypto/bn.c
- crypto/cryptodev.c
- crypto/cryptosoft.c
- include/crypto/bn.h
- include/crypto/cryptodev.h
- include/crypto/cryptosoft.h
kernel supports asymmetric encryption RSA signature verification
> crypto/rsa_verify: export rsa verify via /dev/crypto

- include/dsp.h
- include/dspb16.h
- libdsp: update LP_FILTER comment
add note about filter time constant (tau)
None
CI
> libdsp: update LP_FILTER comment

- drivers/net/tun.c
When tun_txavail_work is running, switch to tun_close thread and priv->lock will be destroyed, then switch back to tun_txavail_work thread, an error will occur when nxmutex_unlock(&priv->lock).
Cortex-M33
> tun: Fix the error of calling tun_close when tun_txavail or tun_txavail_work is executed

- mm/mm_heap/mm_malloc.c
- sched/timer/timer_create.c
- sched/timer/timer_release.c
Replace enter_critical_section with spin_irqsave
Base on discussion #10981
mm
qemu-armv8a/nsh_smp
ostest
> Replace enter_critical_section with spin_irqsave

- include/nuttx/fs/fs.h
- libs/libc/stdio/lib_getdelim.c
- libs/libc/stdio/lib_libfflush.c
- libs/libc/stdio/lib_libfread_unlocked.c
- libs/libc/stdio/lib_libvsprintf.c
- libs/libc/stdio/lib_setvbuf.c
- libs/libc/stdio/lib_sprintf.c
- libs/libc/stdio/lib_vasprintf.c
- libs/libc/stdio/lib_vsprintf.c
- libs/libc/stdio/lib_vsscanf.c
to avoid the unnecessary casting
ci
> libc/stdio: Change FILE buffer field from "unsigned char *" to "char *"

- fs/inode/inode.h
- fs/vfs/fs_open.c
> fs: Change inode_checkflags to static function

- drivers/note/notesnap_driver.c
fix notesnap compilation failure
> note: fix notesnap compilation failure

- Documentation/applications/nsh/commands.rst
-  Documentation: format the NSH command list
command names will be more visible and look nicer
before:
after:
local
> Documentation: format the NSH command list 

- Documentation/applications/testing/sd_stress/index.rst
Adds documentation for new testing utility. See https://github.com/apache/nuttx-apps/pull/2150
Documentation.
Building documentation locally.
> Documentation: Add entry for sd_stress tool.

- sched/pthread/pthread_barrierwait.c
sched/pthread/barrierwait: replace syscall(2) to kernel api
syscall(2) cannot be called from kernel space
Regression: https://github.com/apache/nuttx/pull/9066
ci-check
> sched/pthread/barrierwait: replace syscall(2) to kernel api

- include/nuttx/audio/audio.h
add AUDIO_FMT_AMR macro
new macro
ci
> audio: add amr format support

- arch/arm/src/imxrt/imxrt_serial.c
Solves https://github.com/apache/nuttx/issues/10912
The DMA can bring in more rx data, than the number of
DMA completions call backs. The call backs happen on
idle, 1/2 and full events. But in between these events
the DMA can write more data to the buffers memory that
need to be brought in to the cache. (invalidate)
We do the invalidate on the reads from the fifo memory
if the the DMA as commited since the last read.
Without this change data was dropped at high baud rates. 
imxrt1170 px4 nxp_fmurt1170-v1
> imxrt:serial Ensure the cache is updated if the DMA has updated again

- fs/vfs/fs_rename.c
fs/rename: fix use after free issue about rename
fix use after free issue
local test
> fs/rename: fix use after free issue about rename

- arch/risc-v/src/litex/litex_emac.c
Add support for PHY interrupts in the architecture layer of the Litex emac driver. Boards need to add handling for interrupt lines, if supported.
Boards can use PHY interrupts when available.
Custom hardware running Litex.
> arch/risc-v/litex/litex-emac: Add support for phy interrupts.

- Documentation/components/drivers/block/index.rst
- Documentation/components/drivers/special/index.rst
- Documentation/components/drivers/special/lcd.rst
- Documentation/components/drivers/special/sensors.rst
- Documentation/components/drivers/special/video.rst
Documentation: migrate the rest of drivers readmes
> Documentation: migrate the rest of drivers readmes

- drivers/mtd/mtd_partition.c
driver/mtd: get mtd_geometry_s.model for mtd partition and optimize code
local test
> driver/mtd: get mtd_geometry_s.model for mtd partition and optimize code

- drivers/clk/Kconfig
- drivers/input/Kconfig
- drivers/ioexpander/Kconfig
- drivers/net/Kconfig
- drivers/power/supply/Kconfig
- drivers/rptun/Kconfig
- drivers/sensors/Kconfig
- drivers/serial/Kconfig
- drivers/syslog/Kconfig
- drivers/timers/Kconfig
- drivers/usrsock/Kconfig
- drivers/wireless/bluetooth/Kconfig
- fs/rpmsgfs/Kconfig
- net/rpmsg/Kconfig
Kconfigs: rename {Rpmsg|rpmsg} to RPMGS
cosmetics
> Kconfigs: rename {Rpmsg|rpmsg} to RPMGS

- libs/libc/aio/aio_return.c
- libs/libc/gdbstub/lib_gdbstub.c
- libs/libc/locale/lib_iconv.c
- libs/libc/misc/lib_err.c
- libs/libc/misc/lib_fdsan.c
- libs/libc/misc/lib_glob.c
- libs/libc/stdio/lib_remove.c
- libs/libc/stdlib/lib_strtold.c
- libs/libc/time/lib_localtime.c
- libs/libc/unistd/lib_getentropy.c
- libs/libc/uuid/lib_uuid_create.c
follow other code inside libc, please ignore:
```
Warning: /home/runner/work/nuttx/nuttx/nuttx/libs/libc/locale/lib_iconv.c:110:3: warning: #include outside of 'Included Files' 
```
ci
> libc: Change errno to set_errno and get_errno

- fs/inode/fs_inoderemove.c
- fs/inode/inode.h
since it's only be called by inode_remove now
ci
> fs/inode: Change inode_unlink to static function

- mm/iob/iob.h
- mm/iob/iob_add_queue.c
- mm/iob/iob_alloc.c
- mm/iob/iob_alloc_qentry.c
- mm/iob/iob_free.c
- mm/iob/iob_free_qentry.c
- mm/iob/iob_free_queue_qentry.c
- mm/iob/iob_initialize.c
- mm/iob/iob_remove_queue.c
- mm/mm_gran/mm_gran.h
- mm/mm_gran/mm_grancritical.c
- mm/mm_heap/mm.h
- mm/mm_heap/mm_free.c
- mm/mm_heap/mm_malloc.c
- mm/tlsf/mm_tlsf.c
- mm/tlfs: Replace the critical section with spin lock 
- mm/gran: Replace the critical section with spin lock 
- mm/iob: Replace the critical section with spin lock
improve the speed
ci
> mm: improve SMP performance

- drivers/power/pm/greedy_governor.c
pm: use pm_staytimeout() in greedy_governor_activity()
pm
SIM
> pm: use pm_staytimeout() in greedy_governor_activity()

- arch/arm/include/cxd56xx/gnss.h
- arch/arm/include/cxd56xx/gnss_type.h
- boards/arm/cxd56xx/common/CMakeLists.txt
- boards/arm/cxd56xx/common/src/Make.defs
- boards/arm/cxd56xx/common/src/cxd56_gnss_addon.c
- boards/arm/cxd56xx/drivers/sensors/Kconfig
- boards/arm/cxd56xx/drivers/sensors/Make.defs
- boards/arm/cxd56xx/drivers/sensors/cxd5610_gnss.c
- boards/arm/cxd56xx/spresense/Kconfig
- boards/arm/cxd56xx/spresense/include/board.h
- boards/arm/cxd56xx/spresense/include/cxd56_gnss_addon.h
- boards/arm/cxd56xx/spresense/src/cxd56_bringup.c
- include/nuttx/sensors/cxd5610_gnss.h
boards: cxd56xx: Add cxd5610 gnss driver
Only spresense board
> boards: cxd56xx: Add cxd5610 gnss driver

- arch/arm/src/s32k3xx/s32k3xx_serial.c
LPUART had data corruptions at high rate data, this was caused by a cache coherency issue.
This patch ensures the cache is updated if the DMA has updated again 
S32K3XX
PX4 & MR-CANHUBK344
> s32k3xx: serial ensure the cache is updated if the DMA has updated again

- arch/sim/src/sim/sim_wifidriver.c
The SSID can be configured with special symbols suach as single quotations, double quotations and backslashes, which need to be escaped.
N/A
We can verify the modification using the command `wapi essid wlan0 _!@'}"[|\_  1`. Then the simwifi should connect the AP whose ssid is _!@'}"[|\_ .
> simwifi: Transfer the special characters in ssid.

- include/nuttx/net/ip.h
- net/socket/net_fstat.c
- net/tcp/tcp_ioctl.c
- net/tcp/tcp_send.c
- net/udp/udp_ioctl.c
- net/udp/udp_send.c
Replace
```c
#if defined(CONFIG_NET_IPv4) && defined(CONFIG_NET_IPv6)
((domain) == PF_INET ? A : B)
#elif defined(CONFIG_NET_IPv4)
A
#else
B
#endif
```
Into
```c
net_ip_domain_select(domain, A, B)
```
Minor
Manually, CI
> net: Simplify getting value for different domain

- arch/sim/src/sim/sim_wifidriver.c
For scan results, parse and translate the Chinese ssid encoded by the wpa_cli. 
Because there is no pre-encoding length of the ssid, the ssid including the Chinese characters whose length is less than 32 after encoding cann't be translated.
For example, the ssid name is `word人`.  After encoding it is `world\xe4\xba\xba` and will not be decoded.
N/A
We can verify the modification  using the following steps:
- Configure an SSID containing Chinese characters (ssid_中文测试) on the AP and enable it.
- Configure the SIM-WiFi environment, then scan the AP on the sim and see the scan results.
We should be able to see in the scan results that the ssid name of ap is ssid_中文测试.
> simwifi: For scan results, parse and translate the Chinese ssid encoded by the wpa_cli.

- net/socket/socket.c
#9647 added the ability to do runtime selection of usrsock and fallback to kernel provided sockets, but the problem is that it currently requires the application side usrsock daemon to be running in order to respond with -ENOSYS or -ENOTSUP.
There is already code in usrsock that checks if there is an application side daemon listening and returns -ENETDOWN if nothing is listening.
Specifically in "usrsock_request" in drivers/usrsock/usrsock_dev.c
Enabling fallback to kernel socket with -ENETDOWN allows the application to not launch the usrsock daemon when not needed. Otherwise my application needs to keep the daemon running for the sole purpose of saying it's off wasting resources.
This was likely the original intention of original author based on the comment in "usrsock_sockif_setup" …
> Usrsock socket fallback with ENETDOWN

- sched/Kconfig
- sched/semaphore/spinlock.c
- sched/semaphore/spinlock.c: cosmetics
- sched/Kconfig: RW_SPINLOCK depends on SPINLOCK
CI
> rw spinlocks: cosmetic changes

- sched/signal/sig_nanosleep.c
sched: Check for zero sleep time and yield CPU if necessary
In Linux, sleep(0) will call schedule() to yield CPU.
In FreeBSD, sleep(0) will return immediately, it call select() to do sleep, and select() will return if timeout is 0.
Minor, only sleep(0) 
libuv
> sched: Check for zero sleep time and yield CPU

- drivers/mtd/mx25rxx.c
add support for MX25L25673G chip for mtd/mx25rxx driver
Tested with sama5-xult board
> mtd/mx25rxx: add support for MX25L25673G chip

- drivers/lcd/lcd_dev.c
- include/nuttx/lcd/lcd_dev.h
support stride for LCD putarea and getarea operation
> drivers/lcd: add stride support for LCD driver

- drivers/segger/Kconfig
drivers/segger/Kconfig: cosmetics
ci
> drivers/segger/Kconfig: cosmetics

- arch/sim/src/sim/sim_heap.c
- arch/sim/src/sim/sim_internal.h
- arch/sim/src/sim/win/sim_hostmemory.c
forget from https://github.com/apache/nuttx/pull/11043
no
ci
> arch/sim: Remove the wrong comment from up_allocate_heap

- include/nuttx/clock.h
> clock.h: use CONFIG_DEBUG_SCHED to test init ticks

- include/nuttx/list.h
list: search prev item in reverse order
no
internel test
> list: search prev item in reverse order

- fs/tmpfs/fs_tmpfs.c
> fs/tmpfs: fix an integer overflow

- arch/arm/src/sama5/sam_tsd.c
- boards/arm/stm32/mikroe-stm32f4/src/stm32_touchscreen.c
- boards/mips/pic32mx/pic32mx7mmb/src/pic32_touchscreen.c
- drivers/usbhost/usbhost_hidmouse.c
- drivers/usbhost/usbhost_xboxcontroller.c
remove sched_[un]lock in xxx_waitsample
> sched_lock refine: remove sched_[un]lock in xxx_waitsample

- drivers/video/Kconfig
- drivers/video/fb.c
In FBIO_WAITFORVSYNC mode, if vsync queue is full it should wait
until fb_sem_post.
fb FBIO_WAITFORVSYNC
CONFIG_FB_SYNC=y
run lvgldemo in sim
>  wait when the vsync queue is full in FBIO_WAITFORVSYNC

- drivers/misc/Make.defs
- drivers/misc/rpmsgblk.c
- drivers/misc/rpmsgblk.h
- drivers/misc/rpmsgblk_server.c
- fs/driver/driver.h
- include/nuttx/fs/fs.h
rpmsgblk function optimization
rpmsgblk
rpserver:
CONFIG_BCH=y
rpproxy:
CONFIG_BCH=y
CONFIG_ALLOW_MIT_COMPONENTS=y
CONFIG_TESTING_CMOCKA=y
CONFIG_DRIVER_TEST=y
cu to rpproxy and excute:
ls -l /dev/ram1
cmocka_driver_block -m /dev/ram1
rm /dev/ram1
back to rpserver:
rm /dev/ram1
> Rpmsgblk function optimization

- drivers/mtd/w25.c
Adds support to W25Q20CL memory.
None
Tested with W25Q20CL
> Adds support to W25Q20CL memory.

- Documentation/applications/graphics/nxwm/cnxconsole.rst
- Documentation/components/net/wqueuedeadlocks.rst
- Documentation/components/nxgraphics/nx.rst
- Documentation/guides/citests.rst
- Documentation/guides/stm32ccm.rst
- Documentation/guides/testingtcpip.rst
- Documentation/implementation/critical_sections.rst
- Documentation/implementation/processes_vs_tasks.rst
- Documentation/platforms/arm/imx6/boards/sabre-6quad/README.txt
- Documentation/platforms/arm/lpc17xx/boards/olimex-lpc1766stk/README.txt
- Documentation/platforms/arm/sama5/boards/sama5d3-xplained/README.txt
- Documentation/platforms/arm/sama5/boards/sama5d3x-ek/README.txt
- Documentation/platforms/arm/sama5/boards/sama5d4-ek/README.txt
- Documentation/platforms/arm/samv7/boards/same70-xplained/README.txt
- Documentation/platforms/arm/stm32h7/boards/linum-stm32h753bi/index.rst
- Documentation/platforms/avr/at32uc3/boards/avr32dev1/README.txt
- Documentation/platforms/mips/pic32mx/boards/mirtoo/README.txt
- Documentation/platforms/risc-v/rv32m1/boards/rv32m1-vega/README.txt
Fix some typos in Documentation.
Improves readability.
Visual.
> Documentation: Fix various typos

- mm/Kconfig
- mm/circbuf/circbuf.c
- mm/map/mm_map.c
- mm/mempool/mempool.c
- mm/mempool/mempool_multiple.c
- mm/mm_heap/mm.h
Fix some typos in comments and strings.
Improve readability.
Visual.
> mm: Fix some typos

- Documentation/Makefile
Documentation: turn warnings into errors
depends on https://github.com/apache/nuttx/pull/11277
fixes https://github.com/apache/nuttx/issues/11084
> Documentation: turn warnings into errors

- boards/arm/stm32h7/linum-stm32h753bi/src/linum-stm32h753bi.h
- boards/arm/stm32h7/linum-stm32h753bi/src/stm32_boot.c
- boards/arm/stm32h7/nucleo-h743zi/src/nucleo-h743zi.h
- boards/arm/stm32h7/nucleo-h743zi/src/stm32_boot.c
- boards/arm/stm32h7/nucleo-h743zi2/src/nucleo-h743zi2.h
- boards/arm/stm32h7/nucleo-h743zi2/src/stm32_boot.c
- boards/arm/stm32h7/nucleo-h745zi/src/nucleo-h745zi.h
- boards/arm/stm32h7/nucleo-h745zi/src/stm32_boot.c
- boards/arm/stm32h7/stm32h745i-disco/src/stm32_boot.c
- boards/arm/stm32h7/stm32h745i-disco/src/stm32h745i_disco.h
- boards/arm/stm32h7/stm32h747i-disco/src/stm32_boot.c
- boards/arm/stm32h7/stm32h747i-disco/src/stm32h747i-disco.h
fix config conflict
#if defined(CONFIG_NSH_LIBRARY) && !defined(CONFIG_BOARDCTL)
No Impact
None
> stm32h7: fix config conflict

- arch/xtensa/src/esp32s3/esp32s3_partition.h
esp32s3_partition.h: fix typos (S3S3 -> S3)
> esp32s3_partition.h: fix typos (S3S3 -> S3)

- .github/workflows/docker_linux.yml
Should hopefully fix the following error: https://github.com/apache/nuttx/actions/runs/7116873366
> free up runner disk space before build docker image

- .github/actions/free-disk-space/action.yaml
- .github/workflows/docker_linux.yml
- LICENSE
Relates to https://github.com/apache/nuttx/pull/11343
> free disk space action added to fix docker image build issue

- tools/ci/docker/linux/Dockerfile
Save the docker image size
Dockerfile
ci
> tools/ci: Skip copy gn temporary files

- arch/arm64/Kconfig
- arch/arm64/include/elf.h
- binfmt/libelf/libelf_coredump.c
coredump:support arm64 coredump
coredump for arm64
coredump wtih qemu arm64
> coredump:support arm64 coredump

- fs/mount/fs_gettype.c
fs_gettype:add zipfs magic
zpifs
sim
> fs_gettype:add zipfs magic

- sched/misc/assert.c
Print more information in assert
assert print
xtensa esp32s3
More information could help restore crash scene
> Print more information in assert

- drivers/virtio/virtio-gpu.c
- drivers/virtio/virtio-gpu.h
convert virito-gpu fb_register to virtio_gpu_fb_register
None
run lvgldemo with virtio-gpu
> virtio-gpu: convert virito-gpu fb_register to virtio_gpu_fb_register

- drivers/video/Kconfig
- drivers/video/goldfish_fb.c
- include/nuttx/video/goldfish_fb.h
The Goldfish FB register can be optimized by considering the need to pass in parameters for base and irq.
goldfish fb
None.
> drivers/goldfish_fb: optimize goldfish fb register

- drivers/syslog/ramlog.c
syslog/ramlog: improve ramlog performance
replace char copy to memcpy to improve the performance
N/A
ci-check
> syslog/ramlog: improve ramlog performance

- drivers/sensors/ms56xx_uorb.c
The threshold of second order compensation at very low temperature is **-15°C**.
Sorry for my mistake...
> sensors: mx56xx: Fix threshold and calculation

- include/nuttx/fs/hostfs.h
This fixes a regression in https://github.com/apache/nuttx/pull/10869
tested with sim/macos
> Fix hostfs after uid/gid changes

- arch/sim/src/sim/posix/sim_hostfs.c
- include/nuttx/fs/hostfs.h
fs: fix structure layout inconsistency in hostfs 
sim/nsh
> fix structure layout inconsistency in hostfs 

- arch/sim/src/sim/CMakeLists.txt
arch/sim/src/sim/CMakeLists.txt: update a few file names
cmake based build
> arch/sim/src/sim/CMakeLists.txt: update a few file names

- arch/sim/src/Makefile
- arch/sim/src/sim/CMakeLists.txt
- arch/sim/src/sim/sim_checkhostfstypes.c
sim: add assertions on hostfs copy of structures
> sim: add assertions on hostfs copy of structures

- arch/risc-v/include/irq.h
fix a few typos in comments
None
N/A
> arch/risc-v: fix a few typos in comments

- Documentation/platforms/risc-v/k230/boards/canmv230/index.rst
revise canmv230 docmentations to:
- fix hyper link syntax error.
- enrich command sample comments.
- update ostest info on kernel build.
None
N/A
> risc-v/k230: revise canmv230 docmentations

- CMakeLists.txt
- arch/sim/src/sim/CMakeLists.txt
Some fixes for sim/macOS + cmake + libcxx
a modified version of sim:libcxxtest on macOS.
(modified to workaround https://github.com/apache/nuttx/issues/11473)
> Some fixes for sim/macOS + cmake + libcxx

- tools/link.sh
> tools/link.sh: fix an incorrect variable

- .gitignore
Added ignore file .fakelnk fix make distclean for MSYS2 
none
CI
> .gitignore: Added ignore file .fakelnk

- Documentation/ReleaseNotes/NuttX-12.4.0
Add release notes for 12.4.0 release
RELEASE
NONE
> Documentation: add NuttX-12.4.0 release notes

- arch/arm/src/mx8mp/mx8mp_ecspi.c
mx8mp ecspi driver does not work properly: the interrupt is never enabled nor acknowledged and the timeout precision is too low to handle high frequency clock.
Fix the driver
Done on a LSM6DSR IMU.
For the record, I messed up with the previous PR (I think I commit a not up to date version of the driver).
> Fix mx8mp ecspi interruption management.

- drivers/rptun/rptun_ping.c
- include/nuttx/rptun/rptun.h
rptun ping: support data checksum and data transfer rate calculation.
Increased the accuracy of rptun ping function and facilitated viewing of data transfer rate.
tested in sim vela.
> rptun ping: support data checksum and data transfer rate calculation

- Documentation/ReleaseNotes/NuttX-12.4.0
Add release notes for 12.4.0 release
RELEASE
NONE
> {bp-11512} Documentation: add NuttX-12.4.0 release notes

- tools/ci/testrun/script/test_os/test_os.py
for apache/nuttx#11498 to pass ci, need revert after all commits are merged
None
ci pass
> tools/ci: revert tmp change

- boards/arm/sama5/sama5d3-xplained/src/sam_usb.c
Fix a USB mouse enumeration error.
usbhost_enumerate: ERROR: usbhost_classbind failed -22
> boards/sama5d3-xplained: Add USB mouse initialization.

- wireless/bluetooth/bt_ioctl.c
"bt bnep0 scan start" causes a lot of error messages to be printed when the buffer is full.
btnet_scan_callback: ERROR: Too many scan results                               
btnet_scan_callback: ERROR: Too many scan results                               
btnet_scan_callback: ERROR: Too many scan results                               
btnet_scan_callback: ERROR: Too many scan results                               
btnet_scan_callback: ERROR: Too many scan results                               
btnet_scan_callback: ERROR: Too many scan results                               
btnet_scan_callback: ERROR: Too many scan results                               
After this change only one message will appear for each start command.
nsh> bt bnep0 scan start …
> bluetooth: Prevent btsak from repeatedly showing the same error.

- Documentation/components/syscall.rst
- arch/arm/src/common/arm_initialize.c
- arch/arm64/src/common/arm64_initialize.c
- arch/ceva/src/common/ceva_doirq.c
- arch/renesas/src/common/renesas_initialize.c
- arch/z16/src/common/z16_initialize.c
- arch/z80/src/common/z80_initialize.c
fix some typos in comments or docs
None
N/A
> docs/comments: fix some typos

- drivers/usbhost/usbhost_bthci.c
Miscellaneous changes addressing feedback from xiaoxiang781216.
See #11552
> drivers/usbhost: Update USB bluetooth driver

- Documentation/components/drivers/special/usbhost.rst
- drivers/usbdev/cdcecm.c
- drivers/usbhost/usbhost_cdcmbim.c
- drivers/usbhost/usbhost_skeleton.c
This slightly revised the USB host documentation and fixed typos encountered in the document and some source files.
None
N/A
> usb: document revising and typos fixing

- Documentation/platforms/risc-v/k230/boards/canmv230/index.rst
- Documentation/platforms/risc-v/k230/index.rst
added brief features list for K230 chip
updated CanMV230 board docs for NUTTSBI config usage
Documents
N/A
> docs/k230: update documents

- drivers/note/note_driver.c
fix build with CONFIG_SCHED_INSTRUMENTATION_FUNCTION
only build tested
> fix build with CONFIG_SCHED_INSTRUMENTATION_FUNCTION

- arch/xtensa/src/esp32s3/esp32s3_dma.c
- arch/xtensa/src/esp32s3/esp32s3_dma.h
- arch/xtensa/src/esp32s3/esp32s3_spi.c
- arch/xtensa/src/esp32s3/esp32s3_spi.h
- Add APIs to release DMA channel resources
> xtensa/esp32s3: Add APIs to release DMA channel resources

- arch/arm/src/samv7/sam_dac.c
This commit refactors DAC driver. The functionality remains the same but driver start up is now done in dac_setup (after application called open function) instead of sam_dac_initialize (called from BSP). This ensures that driver does not take resources (timer, interrupt) until opened. Implementation of dac_shutdown is also provided, therefore the driver frees resources once closed.
This change is consistent with other drivers implementation.
Code re-factorization. Some compile warnings are removed.
Tested both DAC channels on SAMv7 evaluation kit board.
> samv7: refactor DAC driver

- Documentation/platforms/sim/sim/boards/sim/index.rst
- include/nuttx/spi/slave.h
- spi/slave.h: revise comments in pulic types section
- doc/sim.rst: minor formatting, add ways to escape cu
docs
checked with retext.
> docs: revising comments and documents

- arch/arm/src/xmc4/hardware/xmc4_ccu4.h
- arch/arm/src/xmc4/hardware/xmc4_scu.h
Add XMC4 CCU4 Registers to NuttX
> xmc4 ccu4 global registers

- boards/arm/cxd56xx/drivers/sensors/cxd5610_gnss.c
Support the output of geoidal heights for cxd5610 gnss driver.
Only spresense board
> boards: cxd56xx: Add geoid to cxd5610 gnss driver

- net/nat/ipv4_nat.c
We found some edge cases when actually using NAT, corresponding modifications:
1. Don't assert on IGMP inside ICMP, just ignore it.
2. Check we have full IP header inside ICMP payload before accessing it.
3. `inner_l4hdrbak` need to be `L4_MAXHDRLEN`, not `L4_MAXHDRLEN/2`.
Processing ICMP error message with NAT 
Manually (on actual Vela product) & CI
> net/nat: Fix ICMP Error MSG Processing

- Documentation/components/filesystem/fat.rst
- fs/fat/fs_fat32dirent.c
- fs/fat/fs_fat32util.c
Improved documentation of File Allocation Table (FAT) or VFAT.
Fixes #11655.
- `checkpatch` testing
- `make autobuild` testing to check errors and the output
> docs/fs/vfat: Improve VFAT documentation

- arch/risc-v/src/mpfs/mpfs_irq.c
It is possible that a PLIC IRQ is claimed but not completed at warm reset. This occurs at least if there is a fault in the middle of irq handler execution.
To recover from such situation, we can complete all IRQ:s in PLIC; this completes any already claimed IRQ, but has no effect on IRQs which are not claimed or not enabled.
Device driver initialization fixed at warm boot in some corner cases.
Tested on mpfs250 based hardware
> arch/risc-v/src/mpfs/mpfs_irq.c: Fix up_irqinitialize for warm reboot

- arch/arm/src/xmc4/CMakeLists.txt
- boards/arm/xmc4/xmc4800-relax/CMakeLists.txt
- boards/arm/xmc4/xmc4800-relax/src/CMakeLists.txt
Build xmc4800-relax using CMake
> build xmc4800-relax using CMake

- Documentation/components/filesystem/tmpfs.rst
This adds initial document for using TMPFS based on my short experience, hoping to save people's time on guessing how to use.
None
CI checks
> docs/tmpfs: add initial document

- Documentation/components/filesystem/rpmsgfs.rst
This patch adds simple steps on configuring and using the RPMsg file system with an example.
None
CI checks.
> docs/rpmsgfs: initial docs on RPMsg file system usage.

- arch/xtensa/src/esp32s3/esp32s3_spi_slave.c
Deinitialize ESP32-S3 SPI slave GDMA engine.
> Deinitialize ESP32-S3 SPI slave GDMA engine

- Documentation/platforms/arm/rp2040/boards/adafruit-feather-rp2040/index.rst
- Documentation/platforms/arm/rp2040/boards/adafruit-kb2040/index.rst
- Documentation/platforms/arm/rp2040/boards/raspberrypi-pico-w/index.rst
- Documentation/platforms/arm/rp2040/boards/raspberrypi-pico/index.rst
Fix NXPlayer name typo
N/A
N/A
> DOC: Fix NXPlayer name typo

- drivers/modem/alt1250/altcom_lwm2m_hdlr.c
Notice instance information of LwM2M server operation to application.
refs #16149
Alt1250 modem driver only
Test if Alt1250 daemon works fine on Spresense environment.
> driver/alt1250: Notice instance information

- boards/arm/cxd56xx/spresense/include/cxd56_bmi160.h
- include/nuttx/sensors/bmi160.h
Remove duplicated defnitions from bmi160.h.
Only for spresense board.
> sensors: Remove duplicated defnitions from bmi160.h

- arch/xtensa/src/esp32s3/esp32s3_spi.c
- Add the return value of SPI driver
> xtensa/esp32s3: Add the return value of SPI driver

- drivers/analog/hx711.c
Fix tare calculation and averaging when scale reports negative values.
More info in commit messages.
> Fix few issues in hx711 driver

- tools/ci/platforms/darwin.sh
mkdir wamrc -> mkdir -p wamrc
github
> tools/ci/platforms/darwin.sh: fix mkdir: wamrc: File exists

- arch/arm/src/common/arm_allocateheap.c
- arch/arm/src/goldfish/chip.h
- arch/arm/src/qemu/chip.h
goldfish & qemu: handle MMU table and CONFIG_RAM_END
goldfish & qemu
goldfish & qemu
> goldfish & qemu: handle MMU table and CONFIG_RAM_END

- arch/arm/src/cxd56xx/cxd56_cisif.c
set_buf() operation is changed to have the argument about format. Follow the change.
spresense camera
Tested with spresense
> arch: cxd56: Follow interface change of set_buf() operation

- arch/arm/src/nrf52/nrf52_spi.c
- arch/arm/src/nrf53/nrf53_spi.c
- arch/arm/src/nrf91/nrf91_spi.c
arch/nrf{52|53|91}/spi: fix error message
CI
> arch/nrf{52|53|91}/spi: fix error message

- CMakeLists.txt
- arch/arm/src/cmake/Toolchain.cmake
- arch/arm/src/common/Toolchain.defs
- arch/arm64/src/Toolchain.defs
- arch/arm64/src/cmake/Toolchain.cmake
- arch/avr/src/avr/Toolchain.defs
- arch/avr/src/avr32/Toolchain.defs
- arch/ceva/src/xc5/Toolchain.defs
- arch/ceva/src/xm6/Toolchain.defs
- arch/mips/src/mips32/Toolchain.defs
- arch/misoc/src/lm32/Toolchain.defs
- arch/misoc/src/minerva/Toolchain.defs
- arch/or1k/src/mor1kx/Toolchain.defs
- arch/risc-v/src/cmake/Toolchain.cmake
- arch/risc-v/src/common/Toolchain.defs
- arch/sim/src/cmake/Toolchain.cmake
- arch/sparc/src/sparc_v8/Toolchain.defs
- arch/x86_64/src/cmake/Toolchain.cmake
- arch/xtensa/src/lx6/Toolchain.defs
- arch/xtensa/src/lx7/Toolchain.defs
- boards/sim/sim/sim/scripts/Make.defs
- libs/libxx/Kconfig
Use C++ standard lib from gcc compiler
> use c++ standard lib that comes with gcc

- arch/xtensa/src/esp32s3/esp32s3_spiflash.c
Fix the issue of erasing a wide range of flash sectors.
The root cause is as following:
- In the `spi_flash_erase_range()` function, the interrupt is suppressed, if a large value is set on the size, the interrupt will be disabled for a long time, this may affect timers and other devices, this PR fixes this issue.
> xtensa/esp32s3: Fix the issue of erasing a wide range of flash sectors

- fs/inode/fs_files.c
- fs/vfs/fs_close.c
- fs/vfs/fs_dup2.c
- fs/vfs/fs_ioctl.c
- include/nuttx/fdcheck.h
- include/nuttx/fs/fs.h
- include/nuttx/fs/ioctl.h
- libs/libc/misc/lib_fdcheck.c
- libs/libc/misc/lib_fdsan.c
FS: enhance file_allocate_from_tcb() mulit-threads saftey & remove memcpy when close the fd
FS
BES boards
> FS: enhance file_allocate_from_tcb() mulit-threads saftey & remove memcpy when close the fd

- drivers/pipes/pipe.c
- net/local/local_fifo.c
it's simpler and safer than file_fcntl(F_SETFL)
internal test
> drivers/pipe: Change to the block mode by file_ioctl(FIONBIO)

- tools/minidumpserver.py
This patch adds rv64 targets support and checked with gdb-multiarch on Ubuntu. It also marks `-arch` parameter optional as it often can be learnt from ELF file.
minidumpserver.py
checked with CanMV230 device logs.
> tools/minidumpserver.py: add support for rv64

- net/local/local.h
- net/local/local_accept.c
- net/local/local_bind.c
- net/local/local_conn.c
- net/local/local_connect.c
- net/local/local_fifo.c
- net/local/local_listen.c
- net/local/local_netpoll.c
- net/local/local_recvmsg.c
- net/local/local_recvutils.c
- net/local/local_release.c
- net/local/local_sendmsg.c
- net/local/local_sendpacket.c
- net/local/local_sockif.c
- net/local: Fix minor issues found in code reading
- net/local: Skip poll_notify in local_event_pollsetup if no event happen 
- net/local: Fix the wrong direction of threshold setting 
local socket
internal test
> Fix the minor issue found in net/local

- tools/checkpatch.sh
Fix cmake-format wrong execution order
Improve users life
N/A
> Fix cmake-format wrong execution order

- drivers/mtd/Kconfig
- drivers/mtd/mtd_config_fs.c
> mt_config_fs : update nvs to support align size

- include/nuttx/mm/mm.h
- mm/Kconfig
- mm/mempool/mempool.c
- mm/mm_heap/mm_free.c
- mm/mm_heap/mm_initialize.c
- mm/mm_heap/mm_malloc.c
- mm/tlsf/mm_tlsf.c
mm: Using Macros Instead of Memory to Fill Labels
> mm: Using Macros Instead of Memory to Fill Labels

- tools/gdb/memdump.py
The method of passing in parameters to memdump is modified and the incoming address is added. After traversing the node to which the address belongs, the memdump command will end.
> memdump: Enhance memdump

- include/nuttx/fs/fs.h
- libs/libc/stdio/lib_fclose.c
- libs/libc/stdio/lib_fopen.c
- libs/libc/stdio/lib_libflushall.c
- sched/tls/task_initinfo.c
- sched/tls/task_uninitinfo.c
stdio/file: unify group file list to common single queue
unify group file list to common single queue
N/A
ci-check
> stdio/file: unify group file list to common single queue

- tools/ci/platforms/darwin.sh
> tools/ci/platforms/darwin.sh:  Removed pyyaml folder

- drivers/ioexpander/icjx.c
This commit implements functions `icjx_multireadpin` and `icjx_multiwritepin`. These functions can be used for multiple pin access (read/write) if `CONFIG_IOEXPANDER_MULTIPIN` is selected. This access is generally faster than one by one pin and may simplify user application.
Changes to general functions `icjx_read` and `icjx_write` were also required to provide support for multiple data send/receive.
Wider support for iC-JX expander
Tested on SAMv7 custom board with icjx.
> icjx: add support for multiple pin read/write

- include/nuttx/lcd/ft80x.h
- include/nuttx/usb/cdc.h
- include/nuttx/video/mipi_dsi.h
- include/nuttx/wireless/ioctl.h
Align the comments in the include directory
sim:local
> include: format alignment

- drivers/usbdev/cdcecm.c
> cdcecm: remove duplicate assignment statements

- arch/arm64/src/common/arm64_copystate.c
- arch/arm64/src/common/arm64_fpu.c
- arch/arm64/src/common/arm64_initialstate.c
Remove arithmetic on void *
Fixes compilation with -Werror
Tested to compile with -Werror enabled
> arch/arm64/src/common: Remove void * arithmetic

- arch/arm64/src/imx9/Kconfig
- arch/arm64/src/imx9/Make.defs
- arch/arm64/src/imx9/hardware/imx93/imx93_ccm.h
- arch/arm64/src/imx9/hardware/imx93/imx93_pll.h
- arch/arm64/src/imx9/hardware/imx9_ccm.h
- arch/arm64/src/imx9/hardware/imx9_lpit.h
- arch/arm64/src/imx9/hardware/imx9_lptmr.h
- arch/arm64/src/imx9/imx9_ccm.c
- arch/arm64/src/imx9/imx9_ccm.h
- arch/arm64/src/imx9/imx9_clockconfig.c
- arch/arm64/src/imx9/imx9_clockconfig.h
Adds CCM driver and some register definitions for the imx9 target
imx9 only
imx93-evk
> arm64/imx9: Add CCM (Clock Controller Module) driver

- arch/arm/src/stm32h7/stm32_adc.c
While doing a multiple channel ADC sample, it was possible for a race condition to occur. The fundamental issue is that the driver was explicitly clearing the EOC interrupt bit.  The EOC interrupt bit should only ever be cleared by reading the ADC_DR (Data Register). Here is what was happening:
1) ADC is triggered and the EOC interrupt fires.
2) Inside the ISR, one or more samples are read from the data register.  Each time a read occurs the EOC interrupt is cleared, but may immediately come back up because there is more data to read.
3) At some point, the EOC interrupt falls, but there are still more channels left to sample - that's okay, we will re-enter the interrupt when the EOC bit rises again.
4) We clear ALL interrupts, including the EOC interrupt, indiscriminately.  By doing this …
> stm32h7: Fix race condition in ADC interrupt handling

- drivers/video/isx012.c
- drivers/video/isx019.c
Store the i2c configuration in power on because they are not changed.
isx012 and isx019
Tested with spresense
> drivers/video: Make the I2C access more efficient

- arch/xtensa/src/esp32s3/esp32s3_spiflash_mtd.c
- Add 16-byte-align SPI-Flash encryption write
> xtensa/esp32s3: Add 16-byte-align SPI-Flash encryption write

- drivers/virtio/virtio-gpu.c
This revises comments and completes reclaiming buf param.
virtio-gpu driver
checked with r-virt/fb64
> virtio/gpu: minor revision on virtio_gpu_send_cmd()

- Documentation/ReleaseNotes/NuttX-12.5.0
Add release notes for 12.5.0 release
RELEASE
NONE
> {bp-12026} Documentation: add NuttX-12.5.0 release notes

- Documentation/ReleaseNotes/NuttX-12.5.0
Add release notes for 12.5.0 release
RELEASE
NONE
> Documentation: add NuttX-12.5.0 release notes

- boards/arm/rp2040/adafruit-feather-rp2040/configs/nshsram/defconfig
- boards/arm/rp2040/adafruit-kb2040/configs/nshsram/defconfig
- boards/arm/rp2040/pimoroni-tiny2040/configs/nshsram/defconfig
- boards/arm/rp2040/raspberrypi-pico-w/configs/nshsram/defconfig
- boards/arm/rp2040/waveshare-rp2040-lcd-1.28/configs/nshsram/defconfig
- This commit applies the fix in https://github.com/apache/nuttx/pull/12025
- None
- Build only
> boards: rp2040: Fix build errors for nshsram configurations

- drivers/net/lan9250.c
- Fix crash issue of sending packets by lan9250 driver under SMP and multi-thread
> drivers/net/lan9250: Fix crash issue of sending packets by lan9250 driver under SMP and multi-thread

- sched/sched/sched_addreadytorun.c
Fix issues of return values of nxsched_add_readytorun()
sabre-6quad:smp
> SMP: Fix issues of return values of nxsched_add_readytorun()

- Documentation/guides/customboards.rst
Corrects minor omission in Custom Boards guide
Clarity and correctness
> Correct error/omissions in Custom Boards guide

- arch/arm/src/samv7/sam_pwm.c
SAMV7's implementation `dcpol` option - setting the DPOLI bit.
> arch/arm/src/samv7/sam_pwm.c: adjust arch driver to DCPOL options

- boards/arm/rp2040/adafruit-feather-rp2040/configs/nshsram/defconfig
- boards/arm/rp2040/adafruit-kb2040/configs/nshsram/defconfig
- boards/arm/rp2040/pimoroni-tiny2040/configs/nshsram/defconfig
- boards/arm/rp2040/raspberrypi-pico-w/configs/nshsram/defconfig
- boards/arm/rp2040/waveshare-rp2040-lcd-1.28/configs/nshsram/defconfig
Summary:
- This commit applies the fix in https://github.com/apache/nuttx/pull/12025
Impact:
- None
Testing:
- Build only
> {Bp-12028} boards: rp2040: Fix build errors for nshsram configurations

- Documentation/components/net/index.rst
- Documentation/components/net/netdev.rst
- Documentation/components/net/netdriver.rst
Add docs for lower-half of netdriver
Documentation
N/A
> Documentation: Add docs for lower-half of netdriver

- Documentation/ReleaseNotes/NuttX-12.5.1
Add release notes for 12.5.1 release
RELEASE
NONE
> Documentation: add NuttX-12.5.1 release notes

- Documentation/ReleaseNotes/NuttX-12.5.1
Add release notes for 12.5.1 release
RELEASE
NONE
> {bp-12101} Documentation: add NuttX-12.5.1 release notes

- arch/risc-v/src/common/espressif/Kconfig
- arch/risc-v/src/common/espressif/esp_spiflash.c
- boards/risc-v/esp32c3/common/scripts/esp32c3_aliases.ld
- boards/risc-v/esp32c3/common/scripts/esp32c3_flat_memory.ld
- boards/risc-v/esp32c6/common/scripts/esp32c6_aliases.ld
- boards/risc-v/esp32c6/common/scripts/esp32c6_flat_memory.ld
- boards/risc-v/esp32h2/common/scripts/esp32h2_aliases.ld
- boards/risc-v/esp32h2/common/scripts/esp32h2_flat_memory.ld
Bugfixing for filesystems
- esp32[c3|h2|c6]: Bugfixes for filesystem errors
ESP32-C6 ESP32-C3 ESP32-H2
> esp32[c3|h2|c6]: Bugfixes for filesystem errors

- include/nuttx/fdcheck.h
- libs/libc/misc/lib_fdcheck.c
- libs/libc/stdio/lib_fopen.c
1 store fd in the high position
2 removing the pid information , as the tag information is sufficient.
> fdcheck: update fdcheck impl

- mm/map/vm_region.c
This is for easier grep searching.
None
CI checks
> mm/map: minor reformating vm_region.c

- sched/mqueue/mq_initialize.c
- sched/mqueue/msginternal.c
sched/mqueue: correct list parameter
1. correct list parameter
2. move global data to bss
N/A
ci-check
> sched/mqueue: correct list parameter

- arch/Kconfig
Adds missing dependency to MM_KMAP, revises comments.
None
CI checks
> arch/kconfig: minor revision for ARCH_KMAP_NPAGES

- drivers/analog/mcp48xx.c
Instead of one static dev and priv, allocate a dedicated one each time the init is invoked.
> enable support for multible devices of mcp48xx

- arch/arm/src/fvp-v8r-aarch32/Make.defs
- arch/arm64/src/goldfish/Make.defs
- arch/avr/src/at32uc3/at32uc3b_pinmux.h
- boards/arm/at32/at32f437-mini/src/Makefile
- boards/arm/gd32f4/gd32f450zk-aiotbox/scripts/Make.defs
- boards/arm/gd32f4/gd32f450zk-aiotbox/src/Makefile
- boards/arm/gd32f4/gd32f450zk-eval/src/Makefile
- boards/arm/gd32f4/gd32f470ik-eval/scripts/Make.defs
- boards/arm/gd32f4/gd32f470ik-eval/src/Makefile
- boards/arm/gd32f4/gd32f470zk-aiotbox/scripts/Make.defs
- boards/arm/gd32f4/gd32f470zk-aiotbox/src/Makefile
- boards/arm/imxrt/imxrt1064-evk/configs/knsh/Make.defs
- boards/arm/imxrt/imxrt1170-evk/configs/knsh/Make.defs
- boards/arm/phy62xx/phy6222/src/Makefile
- boards/arm/rp2040/raspberrypi-pico-w/src/Make.defs
- boards/arm/rp2040/waveshare-rp2040-lcd-1.28/scripts/Make.defs
- boards/arm/rp2040/waveshare-rp2040-lcd-1.28/src/Make.defs
- boards/arm/sama5/jupiter-nano/scripts/Make.defs
- boards/xtensa/esp32s3/esp32s3-box/src/esp32s3_board_lcd_st7789.c
fix Relative file path does not match actual file.
none
> fix nxstyle

- Documentation/guides/qemugdb.rst
Remove nuttx-gdbinit,use tools/gdb/__init__.py instead
Documentation
Use `tools/gdb/__init__.py ` as in the documentation
> Documentation:update qemugdb usage

- drivers/sensors/CMakeLists.txt
- drivers/sensors/Kconfig
- drivers/sensors/Make.defs
- drivers/sensors/adxl362_uorb.c
- include/nuttx/sensors/adxl362.h
sensors: add support for adxl362 accelerometer
thingy91
> sensors: add support for adxl362 accelerometer

- drivers/sensors/CMakeLists.txt
- drivers/sensors/Kconfig
- drivers/sensors/Make.defs
- drivers/sensors/bmm150_uorb.c
- include/nuttx/sensors/bmm150.h
- sensors: add support for bmm150 magnetometer
thingy53
> sensors: add support for bmm150 magnetometer

- tools/configure.sh
Revising the help message for `-L` option.
`tools/configure.sh -h` command
CI checks
> tools/configure.sh: revise help message

- drivers/net/netdev_upperhalf.c
To provide support for the received L3 network packets
sim:local
> netdev_upperhalf: add L3 packet handle

- arch/x86_64/Kconfig
- arch/x86_64/include/intel64/arch.h
- arch/x86_64/src/intel64/CMakeLists.txt
- arch/x86_64/src/intel64/Kconfig
- arch/x86_64/src/intel64/Make.defs
- arch/x86_64/src/intel64/intel64_cache.c
- arch/x86_64/src/intel64/intel64_check_capability.c
arch/intel64: add cache support
cache api supported
qemu and intel hw
> arch/intel64: add cache support

- net/udp/udp_input.c
We found previous multicast support (https://github.com/apache/nuttx/pull/12015) harms some unicast situation, and the `udp_input` should not dup packets for unicast. Now, we only pass broadcast / multicast packets into each listener and let the code under control of `CONFIG_NET_BROADCAST`.
Ref: https://github.com/torvalds/linux/blob/v6.8/net/ipv4/udp.c#L2219
UDP input
iperf2 on Vela
> net/udp_input: Only dup packets for broadcast / multicast.

- boards/arm/stm32/stm32f103-minimum/src/stm32_bringup.c
boards/stm32f103-minimum: fix i2c driver register
I2C should be registered when the I2C driver is enabled
stm32f103-minimum onboard I2C device
stm32f103-minimum
> boards/stm32f103-minimum: fix i2c driver register

- drivers/sensors/Kconfig
sensor BME680: Added if SENSORS_BME680
none
> drivers/sensors/Kconfig: Added if SENSORS_BME680 for common dependency

- drivers/serial/Kconfig-pl011
- drivers/serial/uart_pl011.c
serial/pl011: configurable clock frequency
move clock frequency into Kconfig
N/A
ci-check
> serial/pl011: configurable clock frequency

- Documentation/platforms/arm/stm32l4/boards/b-l475e-iot01a/index.rst
fix b_l475e_iot01a documentation board
fix documentation
> stm32l4/doc: fix b_l475e_iot01a documentation board

- include/nuttx/sched.h
Minor revision to better align the comments in <nuttx/sched.h>
None
CI checks
> nuttx/sched.h: aligning comments

- arch/arm/src/imxrt/imxrt_serial.c
In singlewire mode change ops so that before every transmission TXDIR is an output and on TC (transmission complete) switch TXDIR back to input.
Fixes singlewire transmission for imxrt
FMU-V6XRT
> imxrt: lpuart singlewire transfer support

- arch/xtensa/src/esp32s3/esp32s3_textheap.c
Perform I-D translation for extram as well.
Also, use macros from soc.h.
tested on esp32s3-devkit
> esp32s3: make textheap return i-bus address consistently

- net/icmpv6/icmpv6_autoconfig.c
release wait structure from the list when RS send failed
ICMPV6 RS & RA
Vela product test passed
> [icmpv6] fix resource leak of icmpv6

- Documentation/components/net/index.rst
- Documentation/components/net/netlink.rst
- include/netpacket/netlink.h
- net/arp/arp_table.c
- net/icmpv6/icmpv6_input.c
- net/neighbor/neighbor_add.c
- net/netlink/Kconfig
- net/netlink/netlink.h
- net/netlink/netlink_route.c
- net/route/net_add_fileroute.c
- net/route/net_add_ramroute.c
- net/route/net_del_fileroute.c
- net/route/net_del_ramroute.c
Support route/neigh/prefix netlink notify
Will send netlink msg when route/neigh/prefix changs
Passed the test under simulated environment
> Netlink route support

- drivers/net/tun.c
Add tx packets dump for tun
tcpdump
Vela product test passed
> [driver][tun]: add tx packets dump

- net/route/net_router.c
- net/route/netdev_router.c
Fix Mico definition bug
route cache
None
> [net][route] fix Mico definition bug

- net/icmpv6/icmpv6_rnotify.c
Add netlink notify when setting v6 address by RA
netlink & icmpv6
Tested pass in sim
> [ipv6][netlink] add netlink report when get ipv6 address by icmpv6

- Documentation/platforms/arm/stm32f4/boards/nucleo-f411re/index.rst
- Documentation/platforms/arm/stm32f4/boards/nucleo-f412zg/index.rst
ST Nucleo F401RE -> ST Nucleo F411RE
ST Nucleo F410RB -> ST Nucleo F412ZG
none
> doc: corrected board names

- net/tcp/tcp_send_buffered.c
tcp retransmit max timers need to close
TCP stack
Tested on sim and iperf3
1. open sim hostroute.sh
2. set filter on Ubuntu "sudo iptables -I FORWARD 1 -p tcp --dport 5201 --tcp-flags PSH PSH -j DROP"
3. running iperf3 cmd "iperf3 -c 120.26.1.167 -i 1 -t 20 -b 10m -u" and wireshark tcp packets dump 
4. then you will see PSH packet retransmit and tcp will not close after 8 times retransmit
Test verification results by this patch you will see TCP reset by nuttx
> net/tcp: fix tcp will not close when tcp retransmission reaches TCP_MAXRTX 

- boards/risc-v/esp32c3-legacy/esp32c3-devkit/Kconfig
- boards/xtensa/esp32/esp32-devkitc/Kconfig
- boards/xtensa/esp32/esp32-pico-kit/Kconfig
- boards/xtensa/esp32/ttgo_eink5_v2/Kconfig
- boards/xtensa/esp32/ttgo_t_display_esp32/Kconfig
- boards/xtensa/esp32s3/esp32s3-devkit/Kconfig
removed depends on PM from if PM block
none
> board: Kconfig esp32c3, esp32 and esp32s3 corrected PM block

- boards/risc-v/litex/arty_a7/Kconfig
> boards/risc-v/litex/arty_a7/Kconfig: Added if LITEX_SDIO for common dependency

- tools/ci/platforms/linux.sh
- tools/ci/platforms/ubuntu.sh
mkdir wamrc -> mkdir -p wamrc
none
github
> tools/ci/platforms: linux.sh and ubuntu.sh fix mkdir: wamrc: File exists

- arch/arm64/include/imx9/chip.h
- arch/arm64/src/imx9/hardware/imx93/imx93_memorymap.h
- arch/arm64/src/imx9/imx9_boot.c
Base addresses for ocram, flexspi peripheral area and s3mua, mmu mappings for flexspi and ocram
> Imx93 base addr

- drivers/motor/foc/foc_dummy.c
- include/dsp.h
- include/dspb16.h
- include/nuttx/mm/mm.h
- libs/libc/spawn/CMakeLists.txt
- libs/libdsp/lib_avg.c
- libs/libdsp/lib_foc.c
- libs/libdsp/lib_foc_b16.c
- libs/libdsp/lib_pmsm_model.c
- libs/libdsp/lib_pmsm_model_b16.c
- libs/libdsp/lib_svm.c
- libs/libdsp/lib_svm_b16.c
- net/arp/CMakeLists.txt
- net/ipfrag/Kconfig
fix various compilation errors
local
> fix various compilation errors

- Documentation/faq/index.rst
Add how to get application on NSH
Users will be able to add theirs applications into NSH
SIM
> DOC: Add how to get application on NSH

- net/netlink/netlink.h
- net/netlink/netlink_route.c
> netlink: fix IPV6 macro bug

- sched/group/group.h
- sched/group/group_join.c
- sched/pthread/pthread_create.c
sched/pthread: simplify pthread_create() branch logic
remove redundant branch logic
N/A
ci-check
> sched/pthread: simplify pthread_create() branch logic

- tools/minidumpserver.py
Need to distinguish between 32bit and 64bit registers, format the gdb reply message using struct.pack with correct format. '<I' is used for 32bit registers, '<Q' for 64bit
Now it's back to working for arm32 crash log parsing.
Tested with stm32f4 crash log.
> tools/minidumpserver: fix 32bit crash log parsing

- Documentation/applications/interpreters/wamr/index.rst
This briefs how to getting started with WAMR on NuttX.
None
- CI checks
> docs/wamr: initial guide

- drivers/1wire/1wire.c
- drivers/1wire/ds28e17.c
- drivers/contactless/mfrc522.c
- drivers/contactless/mfrc522.h
- drivers/contactless/pn532.c
- drivers/contactless/pn532.h
- drivers/motor/a4988.c
- drivers/motor/drv8825.c
- drivers/motor/stepper.c
- drivers/wireless/gs2200m.c
- include/nuttx/timers/oneshot.h
> Various minor fixes

- drivers/power/pm/pm_runtime.c
find in https://github.com/apache/nuttx/actions/runs/9528958904/job/26267252811?pr=12503
None
CI-test
> pm: pm_runtime fix header

- arch/arm64/src/common/arm64_gicv3.c
The need for DSB after reading `ICC_IAR1_EL1` register is clearly stated in `ARM GICv3 specification`.
For other changes I made, it's referred to linux source code.
[arch/arm64/include/asm/arch_gicv3.h](https://github.com/torvalds/linux/blob/master/arch/arm64/include/asm/arch_gicv3.h)
[drivers/irqchip/irq-gic-v3.c](https://github.com/torvalds/linux/blob/master/arch/arm64/include/asm/arch_gicv3.h)
Internal test.
> arch/arm64: add DSB ISB where necessary

- arch/risc-v/include/csr.h
- arch/risc-v/src/common/riscv_vectors.S
New CSRs about CLIC support for RISCV
Minor
VELA
> New CSRs about CLIC support for RISCV

- arch/risc-v/src/common/riscv_fpucmp.c
This revises up_fpucmp() to support rv64ilp32.
riscv
- local test with `rv-virt` target
- CI checks
> riscv/rv64ilp32: revise fpucmp

- drivers/video/v4l2_cap.c
Fix code scan by  converity.
NA
NA
> driver/video: fix code scan

- arch/arm/src/stm32f7/hardware/stm32_qspi.h
- arch/arm/src/stm32h7/hardware/stm32_qspi.h
- arch/arm/src/stm32h7/stm32_qspi.c
- arch/arm/src/stm32l4/hardware/stm32l4_qspi.h
- net/tcp/tcp_send_unbuffered.c
- net/udp/udp_conn.c
Please let me know if you need the commits in separate pull requests (I'm new at this).
udp_bind: there was an unmatch net_unlock()
tcp: fix non-compliant return value on error
stm32*: fix macro addresses (that doesn't seem to have been used)
It works for me.
> A few bugfixes

- drivers/power/pm/greedy_governor.c
- drivers/power/pm/pm.h
- drivers/power/pm/pm_activity.c
- drivers/power/pm/pm_lock.c
- drivers/power/pm/pm_register.c
- drivers/power/pm/pm_unregister.c
- drivers/power/pm/stability_governor.c
Make Concept more clear.
None.
CI-test
> pm: remove pm_lock spinlock wrapper

- drivers/serial/serial_gdbstub.c
- include/nuttx/gdbstub.h
- libs/libc/gdbstub/lib_gdbstub.c
Support gdbstub_debugpoint_add/remove smp call
GDBStub
VELA
> gdbstub:support gdbstub_debugpoint_add/remove smp call

- mm/mm_heap/mm_initialize.c
- mm/tlsf/mm_tlsf.c
Old commit did not handle the init.threshold
None.
CI-test
> mm: mm_threshold perfer from init

- libs/libc/gdbstub/lib_gdbstub.c
> gdbstub: fix typo

- arch/risc-v/include/irq.h
- arch/risc-v/src/common/riscv_exception.c
Allow chip to define the custom exception on demand.
Minor
VELA
> riscv: Improve exception and irq mapping

- libs/libc/gdbstub/lib_gdbstub.c
gdbstub: Minor style fix
None
CI
> gdbstub: Minor style fix

- drivers/motor/a4988.c
- drivers/motor/drv8825.c
Fix allocated memory test on step motor code
Fixes
N/A
> Fix allocated memory test

- arch/arm/src/armv6-m/arm_doirq.c
- arch/arm/src/armv7-a/arm_doirq.c
- arch/arm/src/armv7-m/arm_doirq.c
- arch/arm/src/armv7-r/arm_doirq.c
- arch/arm/src/armv8-m/arm_doirq.c
- arch/arm/src/armv8-r/arm_doirq.c
- arch/arm/src/tlsr82/tc32/tc32_doirq.c
- arch/arm64/src/common/arm64_doirq.c
- arch/ceva/src/common/ceva_doirq.c
- arch/risc-v/src/common/riscv_doirq.c
- arch/sim/src/sim/sim_switchcontext.c
- arch/sparc/src/sparc_v8/sparc_v8_doirq.c
- arch/xtensa/src/common/xtensa_irqdispatch.c
Reverts apache/nuttx#12596 since some issues happened
> Revert "irq: remove restore_critical_section in irq"

- LICENSE
- arch/Kconfig
- libs/libc/machine/Kconfig
- libs/libc/machine/x86_64/Kconfig
- libs/libc/machine/x86_64/Make.defs
- libs/libc/machine/x86_64/gnu/CMakeLists.txt
- libs/libc/machine/x86_64/gnu/arch_memcmp.S
- libs/libc/machine/x86_64/gnu/arch_memmove.S
- libs/libc/machine/x86_64/gnu/arch_memset_avx2.S
- libs/libc/machine/x86_64/gnu/arch_memset_sse2.S
- libs/libc/machine/x86_64/gnu/arch_stpcpy.S
- libs/libc/machine/x86_64/gnu/arch_stpncpy.S
- libs/libc/machine/x86_64/gnu/arch_strcat.S
- libs/libc/machine/x86_64/gnu/arch_strcmp.S
- libs/libc/machine/x86_64/gnu/arch_strcpy.S
- libs/libc/machine/x86_64/gnu/arch_strlen.S
- libs/libc/machine/x86_64/gnu/arch_strncmp.S
- libs/libc/machine/x86_64/gnu/arch_strncpy.S
- libs/libc/machine/x86_64/gnu/cache.h
- libs/libc/string/lib_stpcpy.c
libc/x86_64: port string functions from bionic
port optimized string functions for x86_64 from Bionic (BSD licensed)
hardware acceleration for x86_64
ostest on qemu
> libc/x86_64: port string functions from bionic

- arch/arm/src/sama5/sam_ohci.c
Fix typos in ohci driver comments.
None
Build and verify that usb drive still works.
> arch/arm/sama5: Fix typos in ohci driver comments.

- Documentation/applications/system/nxcodec/index.rst
Add Documentation/applications/system/nxcodec/index.rst
NA
```
cd Documentation
make html
```
> nxcodec: add .rst documentation

- fs/mnemofs/CMakeLists.txt
- fs/mnemofs/Make.defs
- fs/mnemofs/mnemofs.h
- fs/mnemofs/mnemofs_ctz.c
- fs/mnemofs/mnemofs_journal.c
- fs/mnemofs/mnemofs_master.c
Journal methods for mnemofs.
mnemofs can use its Journal
checkpatch and NAND flash virtual device.
> fs/mnemofs: Add journal methods.

- Documentation/ReleaseNotes/NuttX-12.6.0
Add release notes for 12.6.0 release
RELEASE
NONE
> {BP-12708} Documentation: add NuttX-12.6.0 release notes

- Documentation/ReleaseNotes/NuttX-12.6.0
Add release notes for 12.6.0 release
RELEASE
NONE
> Documentation: add NuttX-12.6.0 release notes

- Documentation/platforms/arm/nrf91/boards/nrf9160-dk/index.rst
- Documentation/platforms/arm/nrf91/index.rst
- boards/arm/nrf91/common/src/nrf91_boot_image.c
- boards/arm/nrf91/common/nrf91_boot_image.c: print message if no image found
- Documentation/nrf9160-dk: add comments about modem configuration
> Small improvements to nrf91

- tools/nxstyle.c
Looking through issues, I've found #12144.
I thought that it had an easy fix, but...
Throughout the code base I saw that comments can also be present on the same line as the if statement.
Although the documentation states that they are discouraged, it is still valid "syntax".
Also, nxstyle does not check for curly braces on for, (and now) if statements. Neither on switch case (but without parenthesis, won't be valid c syntax). So maybe for this case we need an common solution that I've not included in this PR.
Single line if statements will be print error.
Comments on the same line as the if statements will also print an error.
> tools: nxstyle if statement check

- tools/parsememdump.py
few not synced commit, and speed up the ./parsememdump.py
for common case, the script can run faster, possible >10 times faster.
CI & self-ubuntu host test.
> update newest parsememdump.py and speed it up by python kv cache and multi-thread.

- Documentation/guides/thread_local_storage.rst
Add missing blank line before the code block to
render it correctly.
Minor
CI
> doc: Fix code blocks in thread_local_storage.rst

- Kconfig
Kconfig/style: fix Kconfig style issue
fix this issue reviewed by PR:
https://github.com/apache/nuttx/pull/12667
https://github.com/apache/nuttx/pull/12667#discussion_r1699358220
N/A
ci-check
> Kconfig/style: fix Kconfig style issue

- .github/ISSUE_TEMPLATE/001_bug_report.yml
- .github/ISSUE_TEMPLATE/002_feature_request.yml
- .github/ISSUE_TEMPLATE/003_help.yml
- .github/workflows/issue_labeler.yml
Correct links:
- Bug report
- Feature request
- General Help
Added BSD keyword.
none
CI
> ISSUE_TEMPLATE: Fixed incorrect links for issue templates

- Documentation/platforms/arm64/zynq-mpsoc/boards/zcu111/index.rst
- Documentation/platforms/arm64/zynq-mpsoc/index.rst
Add documentation for Zynq MPSoC and ZCU111
Documentation/platforms
ci-check
> Documentation/platforms:add documentation for Zynq MPSoC and ZCU111

- Documentation/components/drivers/special/i2c.rst
- arch/arm/src/rp2040/rp2040_i2c_slave.c
- arch/arm/src/s32k1xx/s32k1xx_lpi2c_slave.c
- boards/arm/s32k1xx/rddrone-bms772/src/s32k1xx_smbus_sbd.c
- drivers/i2c/CMakeLists.txt
- drivers/i2c/Kconfig
- drivers/i2c/Make.defs
- drivers/i2c/i2c_driver.c
- drivers/i2c/i2c_slave_driver.c
- drivers/i2c/pca9540bdp.c
- drivers/i2c/tca9548a.c
- drivers/spi/spi_bitbang.c
- drivers/spi/spi_driver.c
- drivers/spi/spi_slave_driver.c
- drivers/spi/spi_transfer.c
- include/nuttx/i2c/i2c_master.h
- include/nuttx/i2c/i2c_slave.h
Optimize iic and spi parts and add iic slave drivers
iic and spi driver
iic and spi driver
> Optimize iic and spi parts and add iic slave drivers

- fs/tmpfs/fs_tmpfs.c
- net/local/local_conn.c
1. Fix the location of tmpfs pwrite write
2. Fixed some code check warnings
tmpfs
yes
> Fix the location of tmpfs pwrite write and Fixed some code check warnings

- Documentation/components/drivers/character/touchscreen.rst
- drivers/input/touchscreen_upper.c
- include/nuttx/input/touchscreen.h
Providing the capability for applications to exclusively handle touch events
touchscreen
ci-check
> drivers/touchscreen: add grab for touchscreen

- arch/xtensa/src/esp32/esp32_emac.c
arch/xtensa/esp32: 
- Replace nxsig_usleep() with up_udelay() to avoid context switching, and the actual time difference caused by the setting of TICK in nxsig_usleep() is quite large.
- Remove some unused code.
- Add nxmutex_lock() to ensure exclusive access during the device ioctl() process.
Only ESP32
esp32-ethernet-kit:ethernet
> arch/xtensa/esp32: replace nxsig_usleep() with up_udelay()

- drivers/net/tun.c
Remove unused variables in read & write
TUN device reading and writing functions
Test locally with test examples
> net/tun:Remove unused variables in read & write

- Documentation/applications/system/spi/index.rst
Doc: Fix broken SPI Tool documentation
Help users to use SPI Tool
N/A
> Doc: Fix broken SPI Tool documentation

- arch/xtensa/src/esp32s3/esp32s3_partition.c
> xtensa/esp32s3: partition name duplicate and free

- drivers/input/Kconfig
- drivers/input/Make.defs
- drivers/input/goldfish_events.c
- drivers/input/keyboard_upper.c
- drivers/virtio/virtio-input.c
- include/nuttx/input/goldfish_events.h
- include/nuttx/input/virtio-input-event-codes.h
add goldfish events driver
new goldfish driver
qemu
> Add goldfish events

- fs/inode/fs_inoderelease.c
> nuttx/fs:Rename node with inode.

- Documentation/quickstart/install.rst
Fix documentation typo and missing git package
Improvement
N/A
> doc: Fix documentation typo and missing git package

- arch/xtensa/src/common/xtensa_cache.c
Added up_get_dcache_size and up_get_icache_size common APIs
Support get cache size for xtensa
> xtensa_cache:add up_get_cachesize api

- boards/arm/stm32h7/linum-stm32h753bi/include/board.h
- boards/arm/stm32h7/linum-stm32h753bi/src/linum-stm32h753bi.h
- boards/arm/stm32h7/linum-stm32h753bi/src/stm32_bringup.c
- boards/arm/stm32h7/linum-stm32h753bi/src/stm32_lcd.c
The PR aim is the first step in adding support to LTDC to linum-stm32h753bi.
None
LVGL demo
> LTDC for Linum board

- libs/libc/unistd/lib_getrlimit.c
> getrlimit: implement RLIMIT_STACK return limit stack size

- drivers/virtio/Kconfig
- drivers/virtio/virtio-input.c
enable touch/kbd/mouse for virtio input
virtio input driver
qemu
> drivers/input: enable touch/kbd/mouse for virtio input

- drivers/net/netdev_upperhalf.c
When our netstack is replying packets when processing RX, the replied packets will be sent without considering of TX quota because we don't want to drop them. Now we may delay them by pushing them to a queue and send them later, which can always keep quota working.
The transmitting in receiving workflow.
Manually
> netdev/upper: Delay replied packets to prevent TX quota become negated

- net/utils/net_chksum.c
mod process of generating sum to solve checksum error
packet checksum
> net_chksum.c:mod process of generating sum to solve checksum error

- arch/x86/src/Makefile
- arch/x86_64/src/Makefile
> arch/EXTRA_LIBS: link all staging library.

- arch/sim/src/sim/sim_wifidriver.c
Add the netlink event of connect/disconnect for the simwifi function.
N/A
The app can receive the corresponding netlink event when the wifi is  connected successfully or disconnected.
> simwifi: Add the netlink event of connect/disconnect.

- libs/libc/unistd/lib_getcwd.c
Fix the Name in the function description.
None
None
> lib_getcwd:Fix the Name in the function description.

- arch/arm/include/armv7-a/irq.h
- arch/arm/include/armv7-r/irq.h
- arch/arm/include/armv8-r/irq.h
1. add up_irq_disable() function for armv7-a, armv7-r, armv8-r platform
2. these function are necessary for vendors
> Add irq disable func

- libs/libc/stdio/lib_fgetwc.c
- libs/libc/stdio/lib_fputwc.c
- libs/libc/stdio/lib_putwc.c
- libs/libc/stdio/lib_ungetwc.c
- libs/libc/wchar/lib_wcsstr.c
1. the potential bug are reported by Coverity check tools
2. the fixed function are putwc(), fgetwc(), ungetwc(), wcsstr(), fputwc()
> fix the potential bug of putwc, fgetwc, ungetwc, wcsstr, fputwc

- drivers/net/Kconfig
- drivers/net/wifi_sim.c
- drivers/virtio/virtio-net.c
Fixed several discovered issues when using the QEMU WiFi feature, which now requires syncing to the community.
Fixed the several issues with the QEMU WiFi function.
All modifications have been verified locally.
> Synchronize the modification of the WiFi problems in QEMU.

- Documentation/components/drivers/special/power/pm/index.rst
> pm: update document, add pm_idle interface for not-smp case

- drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.c
- drivers/wireless/ieee80211/bcm43xxx/bcmf_netdev.c
- net/tcp/tcp_send_buffered.c
Fix the compilation warnings
N/A
N/A
> Fix the compilation warnings

- arch/sim/src/sim/sim_wifidriver.c
- drivers/net/wifi_sim.c
- tools/simwifi/sim_wifi.sh
When using the simwifi function, solved some problems  and need to synchronize to the community.
N/A
Locally verified.
> Sync the modifications of the WiFi function in simulator.

- arch/arm/src/cxd56xx/cxd56_nxaudio.c
- arch/sim/src/sim/posix/sim_alsa.c
- drivers/audio/audio_null.c
- drivers/audio/cs4344.c
- drivers/audio/cs43l22.c
- drivers/audio/es8311.c
- drivers/audio/es8388.c
- drivers/audio/vs1053.c
- drivers/audio/wm8904.c
- drivers/audio/wm8994.c
- include/nuttx/audio/audio.h
add 12K sample rate support in sim_alsa.c
tested on vela sim.
> 12K sample rate support

- drivers/mtd/Kconfig
- drivers/mtd/mtd_nandram.c
- fs/mnemofs/mnemofs.c
- fs/mnemofs/mnemofs.h
- fs/mnemofs/mnemofs_blkalloc.c
- fs/mnemofs/mnemofs_fsobj.c
- fs/mnemofs/mnemofs_journal.c
- fs/mnemofs/mnemofs_lru.c
- fs/mnemofs/mnemofs_master.c
Mnemofs autoformat feature
Mnemofs can now initialize from an already formatted device.
NAND virtual device simulator and checkpatch.
> fs/mnemofs: Autoformat

- drivers/timers/capture.c
- include/nuttx/timers/capture.h
Description: Add the function of counting cap edges
> Capture adds the function of edges counting

- crypto/bn.c
- include/crypto/bn.h
Provide software algorithms to calculate inverse elements and greatest common divisor, which is useful to calculate of asymmetric encryption operation.
> crypto/bn: Provide software algorithms to calculate inverse elements and greatest common divisor

- include/debug.h
- libs/libc/sched/sched_dumpstack.c
Keep the log level consistent with assert
> Keep the log level consistent with assert

- include/sys/shm.h
sys/shm.h: add macro define for posix
> sys/shm.h: add macro define for posix

- Documentation/components/filesystem/mnemofs.rst
Add documentation about the new mnemofs design and the NAND flash structure.
Documentation for mnemofs.
> docs/fs/mnemofs: Update new design and NAND flash structure

- include/net/route.h
- libs/libc/net/lib_addroute.c
- libs/libc/net/lib_delroute.c
fix the stack-overflow bug
need to ci with apps
tested on sim
> netlib/route: add length for add/del route-func to reduce caller stack usage

- arch/xtensa/src/esp32s3/esp32s3_sdmmc.c
When CMD end up in error, after error response event, command done event will also be received.
If esp32s3_waitresponse returns on error response, the command done event of this command will disturb later command.
So CMDDONE should be waited in esp32s3_waitresponse even an error response is received.
arch/xtensa/src/esp32s3/esp32s3_sdmmc.c: the function returns after command done event is handled.
https://gist.github.com/Windrow14/19241fc1381013d8255d0df5d428c4e0
> arch/xtensa/src/esp32s3/esp32s3_sdmmc.c: wait for command done event also on error response

- boards/arm/imxrt/imxrt1064-evk/src/imxrt_boot_image.c
- boards/arm/nrf52/common/src/nrf52_boot_image.c
- boards/arm/nrf53/common/src/nrf53_boot_image.c
- boards/arm/nrf91/common/src/nrf91_boot_image.c
- boards/arm/samv7/common/src/sam_boot_image.c
Summary
After changing sp, following functions calling will result in unpredictable behavior in case of jumping.
Impact
boot of imxrt1064, nrf52, nrf53, nrf91,samv7
Testing
> boot: fix potential bl jump to app failed issue

- drivers/timers/pl031.c
fix settime and setalarm
qemu rtc.
qemu
> pl031:change mktime to timegm.

- drivers/rptun/rptun.c
optimization rptun.c format
rptun format
test in sim:rpserver, sim:rpproxy
> rptun.c: fix rptun.c format follow rpmsg virtio

- drivers/rpmsg/rpmsg.c
- drivers/rptun/rptun.c
move rptun/rpmsg_virtio onceinit judge logic to rpmsg_register and Reformat drivers/rpmsg/rpmsg.c
rpmsg service
test in sim vela
> rpmsg.c: move onceinit judge logic to common part

- drivers/mmcsd/mmcsd_sdio.c
- drivers/mmcsd/mmcsd_sdio.h
> mmcsd: add write ext csd reg support

- drivers/mtd/Kconfig
- drivers/mtd/mtd_config_fs.c
mtd_config_fs/Kconfig: update nvs block size and block number to configurable
> nvs: modify nvs block size and block numbers

- drivers/regmap/regmap.c
- include/nuttx/regmap/regmap.h
> drivers/regmap: add exit function interface.

- tools/nxstyle.c
* Previously, my check ensured that there is nothing after the last right parenthesis (if ')' encountered and pnest == 0 )
* Now this check is "split" in two parts, when an if statement is detected, the bif variable is set to true and at some condition is unset ( either an comment on the same line is detected, or the is statement finished -> pnest == 0)
* The actual check on the if statement is done at the end of the line
> fix: rework nxstyle if statement check

- drivers/timers/timer.c
support poll, we can poll_notify in interrupt.
timer_driver
qemu
> timer driver:support poll.

- drivers/usbdev/cdcacm.c
> cdcacm: align cdcacm_epconfigure function parameters

- Documentation/components/drivers/special/devmem.rst
- Documentation/components/drivers/special/index.rst
- drivers/drivers_initialize.c
- drivers/misc/Kconfig
- drivers/misc/Make.defs
- drivers/misc/dev_mem.c
- include/nuttx/drivers/drivers.h
The `devmem` driver provides an interface for accessing memory-mapped
I/O in an embedded system.
N/A
ci
> driver/mem:add Mem Driver.

- boards/xtensa/esp32/common/include/esp32_board_spislavedev.h
- boards/xtensa/esp32/common/src/Make.defs
- boards/xtensa/esp32/common/src/esp32_board_spislavedev.c
- boards/xtensa/esp32/esp32-devkitc/src/esp32_bringup.c
Add spi slave dev to esp32 xtensa
Add Feature
Building
> Add spi slave dev to esp32 xtensa

- sched/misc/assert.c
Increase the chance for _assert to work early in the boot
tested on esp32-devkitc with https://github.com/apache/nuttx/pull/13222
> Increase the chance for _assert to work early in the boot

- include/nuttx/wqueue.h
- sched/wqueue/kwork_cancel.c
- sched/wqueue/kwork_queue.c
- sched/wqueue/kwork_thread.c
- sched/wqueue/wqueue.h
add a feature:
dynamically create work queues
none
ostest
> dynamically create work queues

- Documentation/contributing/documentation.rst
User reported an issue caused by not clear documentation: https://github.com/apache/nuttx/issues/13232
Users will be able to build the documentation
N/A
> doc: Fix Documentation build procedure

- fs/mqueue/mq_open.c
This revises comments for `file_mq_open()`.
None
CI checks
> fs/mq_open: revise comments

- arch/xtensa/src/esp32/esp32_psram.c
No functional changes are intended.
> psram_cache_init: remove cosmetic differences between PRO/APP

- arch/xtensa/src/esp32/esp32_psram.c
> esp32_psram.c: Remove a seemingly stale comment

- arch/arm/src/common/arm_allocateheap.c
The old declare is quite confuzed as we already add lot of feature here.
This path make umm & kmm heap alloc function declare more clear,
and possible support FLAT build to enable kernel heap.
Before commit, kernel heap is not support in default arm_allocateheap.c
After commit, kernel heap is optional, and possible to enable as a independ heap only.
If did not enable kernel heap, should the same as before commit.
CI-test.
> arch/arm: support kernel heap in BUILD_FLAT mode

- include/nuttx/init.h
- sched/sched/sched_idletask.c
add OSINIT_TASK_READY to simplify some code writing
> init: add OSINIT_TASK_READY

- drivers/bch/bchdev_driver.c
Fix overflow when block device over 4GB
Bug Fix
Xiaomi Watch
> drivers/bch: fix uint32 overflow issue

- Documentation/applications/system/debugpoint/index.rst
See https://github.com/apache/nuttx-apps/pull/2549
New doc
None
> Documentation: Add usage guide for the debug command

- fs/inode/fs_files.c
fs/inode: using orig_row to ensure correct free logic.
fs/inode: free correct address
Bug Fix
Vela
> fs/files_extend: Bug Fix

- arch/arm/src/armv7-m/Toolchain.defs
- boards/arm/mps/mps2-an500/scripts/Make.defs
- boards/arm/mps/mps2-an500/scripts/ghs-flash.ld
1. add ghs linker script implementation for mps2-an500 platform
> greenhills support: add ghs linker script for mps2-an500 platform

- include/assert.h
This partly fixes esp32-devkitc:knsh.
Tested esp32-devkitc:knsh (with other local changes)
> Restore ASSERT/VERIFY semantics

- boards/xtensa/esp32/common/scripts/flat_memory.ld
found by GCC -Wundef
build tested
> esp32: fix a way to test a config

- .gitignore
Update .gitignore to include .aider* and fix newline issue,  https://aider.chat/
Minor
CI
> .gitignore: Update .gitignore to include .aider* and fix newline issue

- drivers/timers/arch_alarm.c
- drivers/timers/arch_timer.c
- include/nuttx/arch.h
- include/nuttx/clock.h
- include/nuttx/list.h
- include/nuttx/wdog.h
- sched/sched/sched.h
- sched/sched/sched_processtimer.c
- sched/sched/sched_timerexpiration.c
- sched/wdog/wd_cancel.c
- sched/wdog/wd_gettime.c
- sched/wdog/wd_initialize.c
- sched/wdog/wd_start.c
- sched/wdog/wdog.h
Refactor wdog module
This commit refactors the wdog module to use absolute time representation internally. The main improvements include:
1. Fixed recursive watchdog handling caused by calling wd_start within watchdog timeout callback function.
2. Simplified timer processing to improve performance and enhance code readability.
3. Improved accuracy of timers.
4. Reduced critical section and interrupt disable time, improving real-time performance.
Also,
add nxsched_get_next_expired() support
add API wd_cancel_irq() support
wdog & timers
BES board & SIM & qemu
> Refactor wdog module

- sched/irq/irq_csection.c
simplify code by using OSINIT_TASK_READY
none
ostest
> irq: simplify code by using OSINIT_TASK_READY

- Documentation/applications/system/fastboot/index.rst
Add guide for fastboot
Documentation/applications/system/fastboot
> Documentation: Add guide for fastboot

- include/netinet/ip.h
- include/nuttx/net/ip.h
Expose IPTOS_xxx to the application layer
> Expose IPTOS_xxx to the application layer

- Documentation/platforms/sim/index.rst
- Documentation/platforms/sim/network_linux.rst
- Documentation/platforms/sim/network_vpnkit.rst
Move the docs in boards of sim to common place.
doc
CI
> docs: Migrate network documentation of sim to Documentations

- crypto/cryptosoft.c
Implemented a simple exponentiation.
Provides software algorithms for modular exponentiation
N/A
ci
> crypto/rsa: add exp mod in software crypto

- arch/risc-v/src/common/riscv_mtimer.c
This commit fixed the issue where the hardware timer wraps around and causes the system to halt.
Tested on QEMU.
> arch/riscv: Fixed hardware timer warps-around issue

- include/nuttx/input/ff.h
modify FF_MAX to support 64-bit machine
> input/ff: modify FF_MAX to support 64-bit machine

- drivers/misc/dev_mem.c
Fix dev_mem
dev_mem
```
fastboot oem filedump /dev/mem 0 748544
fastboot get_staged mem1.txt
fastboot oem memdump 0x44000000 0xb6c00
fastboot get_staged mem2.txt
diff mem1.txt mem2.txt
```
> Fix dev_mem related

- fs/vfs/fs_rename.c
- libs/libc/stdio/lib_libvscanf.c
- libs/libc/stdlib/lib_checkbase.c
- libs/libc/stdlib/lib_strtoul.c
- libs/libc/string/lib_isbasedigit.c
rename, strtoul, sscanf
fs/libc/stdlib
> rename, strtoul & sscanf

- drivers/misc/rpmsgdev_server.c
- include/nuttx/drivers/rpmsgdev.h
Support server export and oneway polling
rpmsgdev
> rpmsgdev: Support server export and oneway polling

- drivers/mtd/ftl.c
Read the consecutive eraseblocks, in case that the next eraseblock is bad
ftl
> driver/ftl: Read the consecutive eraseblocks

- fs/procfs/fs_procfsproc.c
stack record bug fix
1. fix ps can't show stack used
2. fix the problem of missing the 0th data in statistics
qemu with an547
> stack recored bug fix

- arch/arm/src/armv6-m/arm_vectors.c
- arch/arm/src/armv7-m/arm_vectors.c
- arch/arm/src/armv8-m/arm_vectors.c
to fix issue about https://github.com/apache/nuttx/issues/12687
arm v6m,v7m,v8m
test passed on cortex m7 platform
> arch/arm-m: Clear lr before jump to __start

- drivers/drivers_initialize.c
- drivers/reset/Kconfig
- drivers/reset/Make.defs
- drivers/reset/core.c
- drivers/reset/reset_rpmsg.c
- include/nuttx/reset/reset-controller.h
drivers/reset: support rpmsg reset
support rpmsg reset on othre core.
Vela
> drivers/reset: support rpmsg reset

- drivers/virtio/virtio-pci-legacy.c
- drivers/virtio/virtio-pci-modern.c
- drivers: fix gcc14 errors for virtio
fix gcc14 errors for virtio
CI
> drivers: fix gcc14 errors for virtio

- include/obstack.h
- libs/libc/obstack/lib_obstack_grow.c
This API is defined by GNU and implemented in other LibCs, such as Musl.
Custom samv7 based board.
> libs/libc/obstack: implement ptr and int growing functions

- boards/arm/stm32/olimex-stm32-p407/scripts/memory.ld
- include/nuttx/clock.h
- include/nuttx/wdog.h
- include/signal.h
- sched/clock/clock_abstime2ticks.c
- sched/signal/sig_notification.c
- sched/timer/timer.h
- sched/timer/timer_create.c
- sched/timer/timer_getoverrun.c
- sched/timer/timer_settime.c
- sched/wdog/wd_start.c
Update posix timer 
sched/timer: Fix timer accuracy problems
signal: Add support for SIGEV_THREAD_ID and sigev_notify_thread_id
timer
bes board, sim
> Update posix timer 

- arch/arm/src/goldfish/Make.defs
- arch/arm/src/goldfish/goldfish_pgalloc.c
add kernel mode support for goldfish
goldfish
goldfish emulator
> goldfish:add kernel mode support

- fs/vfs/fs_read.c
> file_read: fix a bogus cast

- drivers/serial/pty.c
drivers/pty: support pty write to kill signal, like serial driver
support pty write to kill signal, like serial driver
adb shell test
> drivers/pty: support pty write to kill signal, like serial driver

- include/nuttx/fs/fs.h
> fs.h: fix a comment in file_operations

- include/nuttx/irq.h
- sched/irq/irq_csection.c
- sched/mqueue/mq_receive.c
- sched/mqueue/mq_timedreceive.c
- sched/semaphore/sem_clockwait.c
- sched/semaphore/sem_tickwait.c
- sched/semaphore/sem_wait.c
This reverts commit 1c5a0bf6ccf7500150c9a0a29a49a2f98bfdf224.
> Revert "irq: add [enter|leave]_critical_section_nonirq"

- Kconfig
- fs/littlefs/CMakeLists.txt
- fs/littlefs/Make.defs
- fs/romfs/CMakeLists.txt
- fs/romfs/Make.defs
- fs/rpmsgfs/CMakeLists.txt
- fs/rpmsgfs/Make.defs
add sched note for littlefs/romfs/rpmsgfs
sched note
> add sched note for littlefs/romfs/rpmsgfs

- Documentation/platforms/arm/stm32h7/boards/stm32h745i-disco/index.rst
Added STM32H745-DISCO RPTUN documentation
> doc: Add STM32H745I-DISCO RPTUN documentation

- Documentation/components/filesystem/index.rst
- Documentation/components/filesystem/inotify.rst
add more information to introduce inotify
> add inotify doc

- net/netlink/netlink.h
- net/netlink/netlink_conn.c
- net/netlink/netlink_sockif.c
Fix the bug that netlink receive wait does not hang up
> Fix the bug that netlink receive wait does not hang up

- boards/arm/qemu/qemu-armv7a/src/qemu_bringup.c
1. Add mounting of tmpfs
No
No
> arm/qemu: Add mounting of tmpfs

- arch/arm64/src/common/arm64_arch.h
- arch/arm64/src/common/arm64_exit.c
- arch/arm64/src/common/arm64_fatal.c
- arch/arm64/src/common/arm64_fatal.h
- arch/arm64/src/common/arm64_fpu.c
- arch/arm64/src/common/arm64_initialstate.c
- arch/arm64/src/common/arm64_internal.h
- arch/arm64/src/common/arm64_schedulesigaction.c
- arch/arm64/src/common/arm64_sigdeliver.c
- arch/arm64/src/common/arm64_syscall.c
- arch/arm64/src/common/arm64_vector_table.S
- arch/arm64/src/common/arm64_vectors.S
see the discussion https://github.com/apache/nuttx/pull/13520.
> Revert "Arm64 irq1"

- arch/risc-v/src/mpfs/mpfs_emmcsd.c
This is a set of changes for mpfs eMMC/SD driver, from TII repositories
Impacts only MPFS, improves performance and stability
Tested on several custom MPFS boards
> Mpfs emmcsd fixes

- arch/x86_64/src/common/x86_64_pci.c
- include/nuttx/pci/pci.h
1. pci add pci_read/write_io_qword support
2. x86_64_pci.c: x86_64_pci_read/write_io memory support
> Pci framework 0923

- drivers/pci/pci.c
- include/nuttx/pci/pci.h
1. add pci_map_bar_region
2. add pci_bus_map_region and pci_map_region macro
> Pci map bar

- arch/xtensa/src/esp32s3/esp32s3_partition.c
arch/xtensa/esp32s3: Adding an ioctl interface ota_invalidate_bootseq() to the ESP32-S3 partitions, by deleting the corresponding 
otadata, makes the boot sequence (ota_0/1) invalid.
Only esp32s3
Testing use esp32s3-devkitc
> xtensa/esp32s3: Adding the ioctl interface ota_set_bootseq()

- arch/x86_64/include/irq.h
- arch/x86_64/src/common/x86_64_pci.c
- arch/x86_64/src/intel64/intel64_irq.c
- drivers/pci/pci.c
- include/nuttx/arch.h
- include/nuttx/pci/pci.h
> add pci irq interface

- arch/xtensa/src/common/xtensa_macros.S
xtensa_macros.S: fix tab/space mismatches
just whitespace changes
compile-tested (with a lot of local mods)
> xtensa_macros.S: fix tab/space mismatches

- drivers/pci/CMakeLists.txt
- drivers/pci/Kconfig
- drivers/pci/Make.defs
- drivers/pci/pci_drivers.c
- drivers/pci/pci_drivers.h
- drivers/pci/pci_epf_test.c
- drivers/pci/pci_qemu_epc.c
- include/nuttx/pci/pci_ep_test.h
1. add qemu epc drv
2. add epf test drv
3. qemu epc add misx support
> Qemu epc and epf test drv

- libs/libc/stream/lib_syslograwstream.c
> syslogstream : init value for lib_syslograwstream_s.last_ch

- arch/risc-v/src/mpfs/mpfs_serial.c
Add RX flowcontrol feature for MPFS.
Disable RX interrupts and clear the fifo in case of full RX buffer. 
Enable RX interrupts in case of empty buffer.
Feature can be taken into use by CONFIG_SERIAL_IFLOWCONTROL.
arch/risc-v/src/mpfs/mpfs_serial.c
Tested with a custom MPFS board by generating traffic to UART. In stress testing we faced an issue where UART got frozen without rxflowcontrol. It never got out of uart_recvchars() while loop even when rxbuf got full.
> mpfs_serial.c: Add RX flowcontrol

- drivers/clk/clk.c
- drivers/clk/clk_rpmsg.c
- drivers/power/supply/regulator.c
- include/nuttx/clk/clk_provider.h
change from mutex to rmutex
add lock for listlock for regulator.
fix the problem when use regulator_enable
The regulator and driver/clk will be more safe.
CI-test
> optimize for the drivers/clk and regulator driver

- drivers/pci/CMakeLists.txt
- drivers/pci/Kconfig
- drivers/pci/Make.defs
- drivers/pci/pci_drivers.c
- drivers/pci/pci_drivers.h
- drivers/pci/pci_ep_test.c
- include/nuttx/pci/pci.h
- include/nuttx/pci/pci_ep_test.h
> pci: add pci endpoint test driver

- drivers/pci/pci_epf_test.c
- drivers/pci/pci_qemu_epc.c
- include/nuttx/pci/pci_epf.h
> multi function for Qemu EPC

- arch/arm64/Kconfig
- arch/arm64/include/qemu/chip.h
- arch/arm64/src/common/CMakeLists.txt
- arch/arm64/src/common/Make.defs
- arch/arm64/src/common/arm64_gic.h
- arch/arm64/src/common/arm64_gicv2.c
- arch/arm64/src/common/arm64_gicv2m.c
> arm64 support gicv2m for pci irq

- libs/libc/misc/lib_ftok.c
check the mkdir return value in ftok.
N/A
chip:cortexM7
> ftok:check mkdir return value.

- drivers/pci/pci_ep_test.c
- pci ep support msi/msi-x test
improve the test coverage
qemu pci rc/ep
> pci ep support msi/msi-x test

- audio/audio.c
- include/nuttx/audio/audio.h
add AUDIO_CALLBACK_IOERR handle and AUDIO_MSG_IOERR msg to user
none
none
> audio: add AUDIO_MSG_IOERR msg to meida service

- fs/mount/fs_mount.c
fs/mount: move mountpoint inode create after bind
This can avoid the issue of invalid inode access when bind is not yet completed.
Bug fix
Vela
> fs/mount: move mountpoint inode create after bind

- fs/vfs/fs_dup.c
fs/vfs: remove template filep to optimize dup operation
optimize dup code
Vela
> fs/vfs: remove template filep to optimize dup operation 

- arch/arm/src/armv7-m/Kconfig
- arch/arm/src/armv7-m/arm_systick.c
add config ARMV7M_SYSTICK_IRQ_THREAD，we can use irq_thread attach systick interrupt.
armv7m systick.
chip:cortexM7
> add Systick irq_attach_thread

- .github/workflows/build.yml
Undo the unintended changes for debug printing. I edited the wrong repo, I am deeply sorry about this.
None
None
> build.yml: Undo debug print

- libs/libc/dlfcn/lib_dlsym.c
fixed protected build issue: add more header to fixed protected build issue
NA
Test with flagchip protected build
> libc/dlsym: add more header to fixed protected build issue

- tools/testbuild.sh
Avoids in the skipping stage unnecessary configure and  refresh functions
CI
Time comparison
Without this PR
With this PR
> tools/testbuild.sh: Improved speed in the skipping stage

- arch/x86_64/src/intel64/intel64_map_region.c
- arch/x86_64/src/intel64: use legacy method to map memory <4GB
the new mapping method may not work when we have to map memory at the early boot stage
memory map for <4GB works at the early boot stage, when `mm_pgalloc()` is not yet supported
qemu
> arch/x86_64/src/intel64: use legacy method to map memory <4GB

- mm/mm_heap/mm_initialize.c
to remove the race condition and rename IDX to idx
No.
CI build pass.
> mm/heap: hold heap lock before access mm_nregions

- sched/task/task.h
- sched/task/task_fork.c
- sched/task/task_init.c
- sched/task/task_setup.c
task: merge nxtask_setup_name() before create_stack
After this patch up_create_stack() can do some
judgement with thread name
task
bes board
> task: merge nxtask_setup_name() before create_stack

- drivers/net/tun.c
to compatible with Linux convention
tun
ci
> drivers/net: Register "/dev/net/tun" as tun node too

- Documentation/platforms/arm/goldfish/goldfish_timer.rst
- Documentation/platforms/arm/goldfish/index.rst
- arch/arm/src/goldfish/goldfish_timer.c
- drivers/timers/Kconfig
- drivers/timers/Make.defs
- drivers/timers/goldfish_timer.c
- include/nuttx/timers/goldfish_timer.h
Add goldfish timer driver support
new driver, none
Goldfish
> Add goldfish timer driver support

- drivers/pci/pci_ep_test.c
1.pci: msi and msix irq need release irq
> pci: msi and msix irq need release irq

- fs/semaphore/sem_open.c
fs/semaphore: fix a minor issue with goto label
> fs/semaphore: fix a minor issue with goto label

- drivers/pci/pci.c
> release msi/msix irq clean capability struct

- arch/x86_64/src/common/x86_64_internal.h
- arch/x86_64/src/intel64/CMakeLists.txt
- arch/x86_64/src/intel64/Make.defs
- arch/x86_64/src/intel64/intel64_checkstack.c
- arch/x86_64/src/intel64/intel64_initialstate.c
- arch/x86_64/src/intel64/intel64_irq.c
- arch/x86_64/src/intel64/intel64_usestack.c
Add check stack function
no impact
stackcolor test
> arch/x86_64:Add check stack function

- net/rpmsg/rpmsg_sockif.c
Add SO_SNDBUF and SO_RCVBUF support for rpmsg socket
None
vela ci
> net/rpmsg: add SO_SNDBUF and SO_RCVBUF support

- net/rpmsg/rpmsg_sockif.c
Add shutdown support for rpmsg socket
none
vela ci
> Support shutdown

- arch/arm64/include/arch.h
- arch/arm64/src/common/arm64_arch.h
- drivers/coresight/CMakeLists.txt
- drivers/coresight/Make.defs
- drivers/coresight/coresight_common.c
- drivers/coresight/coresight_common.h
- drivers/coresight/coresight_etb.c
- drivers/coresight/coresight_etm4.c
- drivers/coresight/coresight_replicator.c
- drivers/coresight/coresight_tmc_core.c
- drivers/coresight/coresight_tmc_core.h
- drivers/coresight/coresight_tmc_etr.c
- include/nuttx/coresight/coresight.h
- include/nuttx/coresight/coresight_etm4.h
- include/nuttx/coresight/coresight_tmc.h
Support ETM4 and resolve some compilation errors
> drivers/coresight: ETM4 set up

- fs/vfs/fs_stat.c
fs: fix wrong config for FS_SHMFS
> fs: fix wrong config for FS_SHMFS

- include/netpacket/netlink.h
- net/netlink/netlink.h
- net/netlink/netlink_conn.c
- net/netlink/netlink_sockif.c
- [netlink: Format and algin netlink.h](https://github.com/apache/nuttx/commit/a940b7206d7936a64b10cb01f5ff44c7f192413a)
- [netlink: Remove the dead code in netlink_close](https://github.com/apache/nuttx/commit/f089f2e3d5213709b821d5fc4468ff77cc9e7a42)
code refectory only, no function change.
ci
> Netlink minor fix

- arch/x86_64/src/intel64/intel64_map_region.c
Map the new page table with read-write permissions
no impact
x86 goldfish
> arch/x86_64: Map the new page table with read-write permissions

- arch/Kconfig
- arch/x86_64/include/setjmp.h
- libs/libc/machine/x86_64/CMakeLists.txt
- libs/libc/machine/x86_64/Make.defs
- libs/libc/machine/x86_64/arch_setjmp_x86_64.S
Add the setjmp/longjmp function
no impact
ostest
> libs/x86_64:Add the setjmp/longjmp function

- libs/libc/stdio/lib_libvsprintf.c
long double need use the format of 'Lf'
None
sim
> long double need use the format of 'Lf'

- fs/vfs/fs_stat.c
fs: fix wrong config for FS_SHMFS
RELEASE
CI
> {Bp-13928} fs: fix wrong config for FS_SHMFS

- sched/wdog/wd_cancel.c
In the original implementation, if wdog is not ACTIVE, -EINVAL will be returned. The rp2040 i2c driver relies on this semantics to correctly release the semaphore.
Revert the wd_cancel semantics.
Tested on Raspberry Pi Pico.
> sched/wdog: Revert wd_cancel semantics

- arch/x86_64/src/intel64/intel64_createstack.c
create stack use the checkstack function
no impact
ostest
> arch/x86_64:Use the checkstack function

- arch/Kconfig
- arch/x86_64/src/intel64/CMakeLists.txt
- arch/x86_64/src/intel64/Make.defs
- arch/x86_64/src/intel64/intel64_perf.c
Add perf tool
no impact
perf test
> arch/x86_64:Add perf tool

- sched/wdog/wd_cancel.c
This commit fixed code style issue left by the previous patch.
None.
None.
> sched/wdog: Fix code style

- arch/arm64/Kconfig
- arch/arm64/include/qemu/chip.h
- arch/arm64/src/common/CMakeLists.txt
- arch/arm64/src/common/Make.defs
- arch/arm64/src/common/arm64_gic.h
- arch/arm64/src/common/arm64_gicv2.c
- arch/arm64/src/common/arm64_gicv2m.c
arm64 support gicv2m for pci irq
RELEASE
CI
> {Bp-12671} arm64 support gicv2m for pci irq

- arch/x86_64/src/intel64/intel64_irq.c
- arch/x86_64/intel64/intel64_irq.c: fix busy irq logic
use correct macro for cpu_set_t busy variable and remove obsolote check
also remove not needed #include <sched.h>
fix assert condition
CI
> arch/x86_64/intel64/intel64_irq.c: fix busy irq logic

- arch/arm64/include/irq.h
ARM64 CONTEXT REGS number is 36
> ARM64 CONTEXT REGS number is 36

- arch/x86_64/src/common/Toolchain.defs
> arch/x86_64:Fix build cxx warning.

- binfmt/libelf/libelf_ctors.c
- binfmt/libelf/libelf_dtors.c
Fix bugs that detected by Codesonar.
Load ELF files that do not contain constructor or destructor section.
not tested.
> binfmt/libelf: Fix return code

- sched/sched/sched_addreadytorun.c
> fix typo error

- arch/arm64/src/common/arm64_fork.c
PFU: do not cause execution of any instructions to be trapped
> PFU: do not cause execution of any instructions to be trapped

- binfmt/libelf/libelf_ctors.c
- binfmt/libelf/libelf_dtors.c
Fix return code in case of error in loading constructor and destructor section.
Detected by Codesonar 54667871, 54667873
RELEASE
CI
> {bp-14071} binfmt/libelf: Fix return code

- mm/Kconfig
If MM_KASAN judgment already exists
No
No
> mm/kconfig: Remove unnecessary dependencies

- arch/arm/src/goldfish/goldfish_boot.c
goldfish: sync with qemu do rpmsg_syslog init at goldfish
goldfish
goldfish
> goldfish: sync with qemu do rpmsg_syslog init at goldfish

- arch/x86_64/src/intel64/intel64_schedulesigaction.c
> x86_64: align some code

- arch/x86_64/src/intel64/Make.defs
Code style is consistent
no impact 
ostest
> arch/x86_64:Code style is consistent

- drivers/rptun/rptun.c
1. follow the nxstyle, change formot of rptun_init();
2. remove used wqueue header file;
rptun
> drivers/rptun: minor fix about rptun

- tools/showsize.sh
Use showsize.sh to show custom elf file top10 size tools/showsize.sh vela_ap.elf
tools/showsize.sh vela_audio.elf
showsize.sh
./tools/showsize.sh
> tools/showsize.sh: support pass custom nuttx executable

- fs/inode/fs_files.c
modify files_countlist comments
none
vela ci
> fs_file.c: modify files_countlist comments

- include/.gitignore
avoid git add incorrect files
No
CI
> include/.gitignore: add openlibm to gitignore

- libs/libc/uuid/lib_uuid_create.c
Try the hardware random number generators is better for uuid generator
uuid
qemu armv8a
> lib_uuid_create: try use hardware random number generators first

- include/nuttx/trace.h
> support trace_beginex and trace_endex

- net/can/can.h
- net/can/can_callback.c
- net/can/can_getsockopt.c
- net/can/can_recvmsg.c
- net/can/can_sendmsg.c
- net/can/can_setsockopt.c
- net/socket/getsockopt.c
- net/socket/setsockopt.c
like other protocols(e.g. ip, tcp, udp)
ci
> net/can: Save simple options to socket_conn_s

- drivers/misc/rpmsgdev_server.c
A use-after-free problem occurs when there are multiple remotes in the list `g_rpmsg` and the matching remote is not the last item in the list.
```
ap> testdev -d 2 -c "REMOTE_CPU" -l "/dev/LOCAL_DEV"
[ap] kasan_report: kasan detected a read access error, address at 0x3c3d4740,size is 4, return address: 0x2c33620f
[ap] kasan_show_memory: Shadow bytes around the buggy address:
[ap] kasan_show_memory:   0x3c3d46f0: cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc cc
[ap] kasan_show_memory:   0x3c3d4700: aa aa aa aa cc cc cc cc cc cc cc cc cc cc cc cc
[ap] kasan_show_memory:   0x3c3d4710: 40 47 3d 3c ed 61 33 2c 00 00 00 00 00 00 00 00
[ap] kasan_show_memory:   0x3c3d4720: 00 00 00 00 00 00 00 00 00 00 00 00 cc cc cc cc
[ap] kasan_show_memory:   0x3c3d4730: 55 55 55 55 38 00 00 00 02 2c 00 00 cc …
```
> misc/rpmsgdev: The private data should be freed only when endpoint is released

- arch/arm64/src/goldfish/CMakeLists.txt
- drivers/input/CMakeLists.txt
- drivers/misc/CMakeLists.txt
- drivers/power/battery/CMakeLists.txt
These newly added files are missing from cmake.
No impact on existing projects.
CI build pass.
> cmake: add newly added sources to cmake

- boards/arm64/fvp-v8r/fvp-armv8r/scripts/dramboot.ld
- boards/arm64/qemu/qemu-armv8a/scripts/dramboot.ld
1.boards/arm64: Add an impls section to the link script
> boards/arm64: Add an impls section to the link script

- drivers/mmcsd/mmcsd_sdio.c
add STATUS_SEND (CMD13) support
mmcsd
cortexM55
> mmcsd:add STATUS_SEND (CMD13) support

- net/tcp/tcp_input.c
According to RFC793, Section 3.4, Page 33.
In the SYN_SENT state, if receive a ACK without the SYN, 
we should reset the connection and retransmit the SYN.
N/A
Locally verified
> net/tcp: Reset the conn when receiving a ACK in the SYN_SENT state.

- include/nuttx/mmcsd.h
add postsleep fields for mmc_ioc_cmd
mmcsd
> mmcsd:add postsleep fields for mmc_ioc_cmd

- Documentation/platforms/arm/stm32f0/index.rst
- Documentation/platforms/arm/stm32l4/index.rst
Added documentation on STM32F0 and STML4 flashing/debugging.
Documentation.
Local testing: FreeBSD + sphinx build to html.
> DOC: Add information on STM32F0 and STM32L4 flashing/debugging.

- drivers/mmcsd/mmcsd_sdio.c
mmcsd:add reset card to idle state (CMD0) support
mmcsd
cortexM55
> mmcsd:add reset card to idle state (CMD0) support

- drivers/misc/rpmsgdev.c
- fs/vfs/fs_readlink.c
drivers/rpmsgdev: support get more battery info by rpmsgdev
get more battery info by rpmsgdev
Vela
> drivers/rpmsgdev: support get more battery info by rpmsgdev

- boards/x86/qemu/qemu-i486/scripts/qemu.ld
- boards/x86_64/intel64/qemu-intel64/scripts/qemu.ld
> nuttx/x86_64:Add _sinit and _einit initialization.

- arch/arm/src/armv6-m/arm_svcall.c
- arch/arm/src/armv7-m/arm_svcall.c
- arch/arm/src/armv8-m/arm_svcall.c
- arch/risc-v/src/common/riscv_swint.c
arm/riscv: remove redundant judgment
none
ci test
> arm/riscv: remove redundant judgment

- arch/arm/src/goldfish/goldfish_memorymap.c
- arch/arm/src/goldfish/goldfish_memorymap.h
1.arm/goldfish: add memory map for DDR region
> arm/goldfish: add memory map for DDR region

- drivers/mmcsd/sdio.c
> sdio_probe: set voltage use CMD5

- arch/arm/src/cmake/gcc.cmake
- arch/arm/src/common/Toolchain.defs
- libs/libxx/libcxx.cmake
resolve  https://github.com/apache/nuttx/pull/14159#discussion_r1798614702 comment
> Change the judgment of GCCVER version to greater equal.

- boards/arm/mps/mps2-an500/src/mps2_bringup.c
- boards/arm/mps/mps2-an521/src/mps2_bringup.c
- boards/arm/mps/mps3-an547/src/mps3_bringup.c
1. mps/bringup: Add initialization of tmpfs
> mps/bringup: Add initialization of tmpfs

- sched/misc/coredump.c
coredump.c: del multiple behavior
No
No
> coredump.c: del multiple behavior

- audio/audio.c
- include/nuttx/audio/audio.h
1. audio: add offload underflow msg state
No
No
> audio: add offload underflow msg state

- include/pwd.h
- include/shadow.h
- include/unistd.h
- libs/libc/libc.csv
- libs/libc/pwd/CMakeLists.txt
- libs/libc/pwd/Make.defs
- libs/libc/pwd/lib_find_pwdfile.c
- libs/libc/pwd/lib_getpwbuf.c
- libs/libc/pwd/lib_getpwbufr.c
- libs/libc/pwd/lib_getpwent.c
- libs/libc/pwd/lib_getpwnam.c
- libs/libc/pwd/lib_getpwnamr.c
- libs/libc/pwd/lib_getpwuid.c
- libs/libc/pwd/lib_getpwuidr.c
- libs/libc/pwd/lib_getspnam.c
- libs/libc/pwd/lib_getspnamr.c
- libs/libc/pwd/lib_pwd.h
- libs/libc/unistd/CMakeLists.txt
- libs/libc/unistd/Make.defs
- libs/libc/unistd/lib_crypt.c
- libs/libc/unistd/lib_crypt_r.c
- libs/libc/unistd/lib_getpass.c
Add some functions to pass tlpi example:
https://man7.org/tlpi/code/online/dist/users_groups/check_password.c.html
> pass tlpi example:check_password

- arch/arm/src/mps/Kconfig
1. select ARM_HAVE_MVE and ARCH_HAVE_FPU for mps platform
> select ARM_HAVE_MVE and ARCH_HAVE_FPU for mps platform

- include/nuttx/audio/audio.h
external/ffmpeg: add offloding audio recording with amr format.
> external/ffmpeg: add offloding audio recording with amr format.

- include/net/if.h
- net/netdev/netdev_ioctl.c
> add a flag of lin internal sleep/wakeup state

- Documentation/platforms/risc-v/esp32c3-legacy/index.rst
- Documentation/platforms/risc-v/esp32c3/index.rst
- Documentation/platforms/risc-v/esp32c6/index.rst
- Documentation/platforms/risc-v/esp32h2/index.rst
- Documentation/platforms/xtensa/esp32/index.rst
- Documentation/platforms/xtensa/esp32s2/index.rst
- Documentation/platforms/xtensa/esp32s3/index.rst
- tools/ci/docker/linux/Dockerfile
- tools/ci/platforms/darwin.sh
- tools/ci/platforms/linux.sh
- tools/ci/platforms/ubuntu.sh
- tools/esp32/Config.mk
- tools/esp32c3/Config.mk
- tools/esp32s2/Config.mk
- tools/esp32s3/Config.mk
- tools/espressif/Config.mk
Reverts apache/nuttx#14120
replace by https://github.com/apache/nuttx/pull/14267
> Revert "Update esptool version on docs and build system"

- drivers/mmcsd/mmcsd.h
- drivers/mmcsd/mmcsd_extcsd.h
- drivers/mmcsd/mmcsd_sdio.c
- drivers/mmcsd/mmcsd_sdio.h
include boot0,boot1,gp1,gp2,gp3,gp4,rpmb
mmcsd
cortex M55
> mmcsd: add multi partitions support

- arch/arm/src/Makefile
- arch/arm64/src/Makefile
- arch/avr/src/Makefile
- arch/ceva/src/Makefile
- arch/hc/src/Makefile
- arch/mips/src/Makefile
- arch/misoc/src/Makefile
- arch/or1k/src/Makefile
- arch/renesas/src/Makefile
- arch/risc-v/src/Makefile
- arch/sim/src/Makefile
- arch/sparc/src/Makefile
- arch/x86/src/Makefile
- arch/x86_64/src/Makefile
- arch/xtensa/src/Makefile
- arch/z16/src/Makefile
- arch/z80/src/Makefile
- tools/Make.defs
follow the same pattern as other Make.defs files
code refactor only'
ci
> tools: Rename apps-or-nuttx-Make.defs to Make.defs

- libs/libc/modlib/modlib_load.c
This fixes issue where empty and unallocated sections are left without a VMA. Some relocations depend on the section VMA being set even if there is no data there, as the binary can refer to the symbols. Linker defined symbols do not contain data -> they can produce empty sections.
This issue is seen when building a loadable file which declares _sctors / _sdtors linker defined symbols for ctor/dtor sections which are empty. crt0 references these symbols, so they need to be relocated, but the section VMA is not set -> they go outside of the addressable range of the user binary causing a potential crash.
Impact is on loadable files, such as .elf files.
rv-virt:knsh64 + modifications:
-CONFIG_BINFMT_ELF_EXECUTABLE=y
+CONFIG_HAVE_CXX=y
More about the subject can be found here …
> libs/modlib.c: Set VMA for empty and unallocated sections

- drivers/aie/ai_engine.c
- include/nuttx/aie/ai_engine.h
This pr improves the implementation of ai driver, especially solving these two problems.
1. it doesn't support multiple users or models,
2. kmm_alloc in INIT ioctl while no free, which could cuase leak.
There is no ai driver's user in community for now, welcome to new ideas.
Should test it with some NPU and its toolchain in the future.
> nuttx ai driver update

- LICENSE
- include/nuttx/compiler.h
- libs/libc/string/Kconfig
- libs/libc/string/lib_memccpy.c
- libs/libc/string/lib_memchr.c
- libs/libc/string/lib_memcmp.c
- libs/libc/string/lib_memcpy.c
- libs/libc/string/lib_memmove.c
- libs/libc/string/lib_memrchr.c
- libs/libc/string/lib_stpcpy.c
- libs/libc/string/lib_stpncpy.c
- libs/libc/string/lib_strcat.c
- libs/libc/string/lib_strchr.c
- libs/libc/string/lib_strchrnul.c
- libs/libc/string/lib_strcmp.c
- libs/libc/string/lib_strcoll.c
- libs/libc/string/lib_strcpy.c
- libs/libc/string/lib_strdup.c
- libs/libc/string/lib_strlen.c
- libs/libc/string/lib_strncmp.c
- libs/libc/string/lib_strncpy.c
- libs/libc/string/lib_strrchr.c
Merge the newlibc string into NuttX.This is jjohnstn@redhat.com response regarding copyright:
Hello,
Individual files in newlib either have a license in them or they fall under the first license found in the COPYING.NEWLIB file which is in the top level directory:
(1) Red Hat Incorporated
Copyright (c) 1994-2009  Red Hat, Inc. All rights reserved.
This copyrighted material is made available to anyone wishing to use,
modify, copy, or redistribute it subject to the terms and conditions
of the BSD License.   This program is distributed in the hope that
it will be useful, but WITHOUT ANY WARRANTY expressed or implied,
including the implied warranties of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.  A copy of this license is available at
http://www.opensource.org/licenses. Any Red Hat …
> Merge the newlibc string into NuttX.

- drivers/pci/pci.c
1.fix build error shift-count-overflow
> fix build error shift-count-overflow

- drivers/sensors/bmi160.c
- drivers/sensors/bmi160_base.h
- drivers/sensors/bmi160_uorb.c
1. fix some compile issue
2. fix Parameter passing error when use spi
bmi160 sensor
local test
> fix bmi160 some issue

- Documentation/guides/index.rst
- Documentation/guides/integrate_newlib.rst
- Documentation/guides/ipv6.rst
- Documentation/guides/logging_rambuffer.rst
- Documentation/guides/protected_build.rst
Migrated pages:
* NuttX Protected Build
* Integrating with Newlib
* IPv6
* Logging to a RAM buffer
None, just update the documentation
Build with `make autobuild`
> Doc migration 2

- AUTHORS
Ville Juven has submitted the ICLA and should be added to the AUTHORS file
AUTHORS
CI
> AUTHORS: add Ville Juven

- fs/fs_heap.c
- fs/fs_heap.h
- fs/tmpfs/fs_tmpfs.c
fs: add fs_heap_strndup, replace strndup with fs_heap_strndup
fix malloc/free inconsistency, stdndup and fs_heap_free mismatch
sim
> fs: add fs_heap_strndup, replace strndup with fs_heap_strndup

- arch/x86_64/src/intel64/intel64_handlers.c
Fix variable used before assignment
no impact
ostest
> arch/x86_64:Fix variable used before assignment

- arch/arm/src/armv8-r/arm_arch_timer.c
1. Enable timer and irq finally to make sure timer callback was already registered. When the CPU resets, the values of some generic timer registers are undefined. Enabling the timer interrupt in advance may cause the timer to trigger early while the timer callback is not yet registered. This results in the timer ISR being executed, which masks the timer interrupt. Since the timer callback is not registered at this point, the timer interrupt is not unmasked, further causing the system scheduler to hang.
2. Remove timer mask for one-shot timer and that's in isr, irq/fiq is disabled. Masking generic timer is not necessary, and it may introduce risks, otherwise, mask/unmask must be pair in all situations.
armv8_r generic timer init
ARM Cortex-R52
> arm/armv8-r: optimize generic timer initialization

- sched/sched/sched_cpuload.c
sched/cpuload: move g_cpuload_wdog to private chapter
coding style
N/A
ci-check
> sched/cpuload: move g_cpuload_wdog to private chapter

- Documentation/guides/index.rst
- Documentation/guides/renode.rst
Documentation: add some notes about running NuttX on Renode
none
> Documentation: add some notes about running NuttX on Renode

- Documentation/guides/renode.rst
Documentation: update notes about nrf52840 and Renode
none
local build
> Documentation: update notes about nrf52840 and Renode

- arch/arm/src/stm32/stm32_dumpgpio.c
fix print warnings for stm32_dumpgpio.c
fix build warnings
nucleo-f302r8
> arch/arm/stm32/stm32_dumpgpio.c: fix print warnings

- fs/shm/shmfs.c
- fs/shm/shmfs_alloc.c
Repair partial interface
shmfs
local shmfs test
> Shmfs bug fix

- mm/tlsf/mm_tlsf.c
mm: Complete remaining unused macros instead of memory to fill tags
None
mm: Complete remaining unused macros instead of memory to fill tags
> mm: Complete remaining unused macros instead of memory to fill tags

- AUTHORS
Felipe Moura Oliveira has submitted the ICLA and should be added to the AUTHORS file
AUTHORS
NONE
> AUTHORS: add Felipe Moura Oliveira

- libs/libc/machine/xtensa/CMakeLists.txt
> cmake(bugfix):add xtensa libc machine function build

- arch/xtensa/src/esp32s3/esp32s3_efuse_lowerhalf.c
fix the error reported here:
https://github.com/NuttX/nuttx/actions/runs/11630100298/job/32388417948
ci
> Fix Error: implicit declaration of function 'enter_critical_section'

- sched/sched/sched_roundrobin.c
If we need to handle a tcb that is running on another CPU, we need to process it through the smpcall method.
This commit fixes the regression from https://github.com/apache/nuttx/pull/13863
fix regression
ci ostest
> fix regression caused by remove sync pause

- include/netinet/if_ether.h
- include/nuttx/wireless/ieee80211/ieee80211.h
consistent with other operating systems
qemu:x86_64
> netinet/if_ether.h: move #define ETH_XXX into if_ether.h

- fs/vfs/fs_read.c
- fs/vfs/fs_write.c
The problem has been inherited from the original libc readv/writev implementation. However, now it's exposed in more situations because this implemenation is used to back read/write as well.
I expect this fixes the regressions observed on the Espressif CI. https://github.com/apache/nuttx/pull/13498#issuecomment-2448031197
Note that, even with this fix, these "compat" readv/writev implementations are still inheritedly broken. (E.g. consider that a data boundary happens to match one of iovec boundaries) However, this fix is enough for read/write, where iovcnt is always 1.
read/write on character devices or such.
Tested on esp32-devkitc, with https://github.com/apache/nuttx/pull/14479 and other changes.
> file_readv_compat/file_writev_compat: Fix partial success handling

- drivers/rf/dat-31r5-sp.c
- drivers/sensors/adt7320.h
- include/nuttx/rf/attenuator.h
- include/nuttx/rf/dat-31r5-sp.h
- include/nuttx/rf/ioctl.h
- include/nuttx/sensors/adt7320.h
Augusto Fraga Giachero has sumitted the ICLA and the license can be
replaced by the ASF License
LICENSE
NONE
> LICENSE: migrate licenses to ASF

- net/tcp/tcp_send_buffered.c
The current receive data needs to be handled by following tcp_recvhandler or tcp_data_event. Notify driver to send the message and marked as rexmit.
cortex-m33
> tcp: fix tcp can not retransmit timely when ACK with TCP_NEWDATA

- drivers/mtd/rammtd.c
- include/nuttx/mtd/mtd.h
Added `rammtd_uninitialize` API to manage rammtd
This will not have any impact on the existing environment, because it only adds a new uninitialized interface.
> rammtd:add rammtd_uninitialize

- arch/arm/Kconfig
- include/nuttx/atomic.h
- include/nuttx/lib/stdatomic.h
- include/nuttx/macro.h
- libs/libc/machine/Kconfig
- libs/libc/machine/arch_atomic.c
> Revert "arch_atomic : Introduce CONFIG_LIBC_ARCH_ATOMIC"

- arch/Kconfig
- arch/arm/Kconfig
- arch/arm64/Kconfig
- arch/xtensa/Kconfig
1. Modify the select the gcc compiler
None
None
> arch/toolchain: Add toolchain gcc

- libs/libc/gdbstub/lib_gdbstub.c
gdbstub:typo fix
gdbstub
build qemu with gdbstub
> gdbstub:typo fix

- drivers/pci/pci_epc.c
- drivers/pci/pci_epc_mem.c
- drivers/pci/pci_epf.c
- drivers/pci/pci_qemu_epc.c
- drivers/sensors/ds18b20_uorb.c
- drivers/sensors/fakesensor_uorb.c
- drivers/sensors/gnss_uorb.c
- drivers/sensors/hyt271_uorb.c
- drivers/sensors/mpu9250_uorb.c
- drivers/sensors/ms56xx_uorb.c
- drivers/sensors/sensor.c
- drivers/sensors/sensor_rpmsg.c
- drivers/sensors/sht4x.c
- drivers/sensors/usensor.c
- include/nuttx/pci/pci_epc.h
- include/nuttx/pci/pci_epf.h
- include/nuttx/sensors/bmp180.h
- include/nuttx/sensors/ds18b20.h
- include/nuttx/sensors/fakesensor.h
- include/nuttx/sensors/gnss.h
- include/nuttx/sensors/hyt271.h
- include/nuttx/sensors/mpu60x0.h
- include/nuttx/sensors/mpu9250.h
- include/nuttx/sensors/msa301.h
- include/nuttx/sensors/sensor.h
- include/nuttx/sensors/wtgahrs2.h
- drivers/pci: fix style issues in function headers 
- drivers/sensors: fix style issues in function headers 
only cosmetic style changes
none
> cosmetic changes in drivers/pci and drivers/sensors

- arch/arm64/src/common/arm64_cpustart.c
arm64: remove unused code
arm64
ci
> arm64: remove unused code

- boards/sim/sim/sim/scripts/Make.defs
> Revert "sim/m64:Fix ld error."

- Documentation/platforms/xtensa/esp32s3/boards/esp32s3-devkit/index.rst
esp32s3-devkit doc: Update the procedure after simple boot
doc only
tested on esp32s3 devkitc
> esp32s3-devkit doc: Update the procedure after simple boot

- cmake/nuttx_kconfig.cmake
the ${MENUCONFIG} file in the output directory is enough, as invoking nuttx_generate_kconfig() will generate this file in the output directory.
Since we are collecting these files recursively,
the nuttx_generate_kconfig() function of the parent directory will be called after all the subdirectories' nuttx_generate_kconfig() functions have been invoked.
This will correctly handle the situation where multiple directories need to generate kconfig menus.
creating a multi-level directory scenario
```
nuttx_add_subdirectory()
nuttx_generate_kconfig(MENUDESC "Level1")
nuttx_add_subdirectory()
nuttx_generate_kconfig(MENUDESC "Level2")
```
```
cmake -B build -DBOARD_CONFIG=nrf52832-dk:mcuboot_app -GNinja
cmake --build build -t menuconfig
```
The test results are normal and enter the multi-level …
> cmake:bugfix kconfig menu in cmake cannot be generated recursively

- mm/mm_gran/mm_grantable.c
The original code did the speedup only from the other direction (from end to start). If the starting GAT index has reservations, they are not skipped as a bunch, but instead the GAT is iterated bit-by-bit, causing a massive performance issue.
Fix this by:
- Skipping full GATs right away
- Skipping all of the reserved bits from the starting GAT as a bunch
Improves the granule allocator performance.
rv-virt:knsh64
rv-virt:ksmp64
MPFS with BUILD_KERNEL (GRAN=y)
> mm/gran: Speed optimize gran_match

- tools/gdb/__init__.py
- tools/gdb/gcore.py
- tools/gdb/lists.py
- tools/gdb/macros.py
- tools/gdb/memdump.py
- tools/gdb/stack.py
- tools/gdb/thread.py
- tools/gdb/utils.py
This PR is one of the series to upgrade GDB Plugin to a more powerful and robust tool.
This PR mainly fixes thread related command issues.
1. Fix online debugging running tasks, need to restore the registers correctly.
2. Add index, tid, pid information to `info threads` command
3. Fix `up` command to select correct frame before setting registers.
4. Use colourful output
For sake of avoiding merge conflicts, I also included a few new tools here. Use `help user-defined` to show all the commands. and `help 'command'` to show help message.
1. `listforentry` is used to iterate list elements.
2. `ps`
3. `memdump` enhancement
The code is formatted in the last commit since the CI code …
> GDB Plugin Upgrade Part1 - Thread related commands

- Documentation/components/drivers/special/syslog.rst
syslog.rst: mention the correct kconfig option
document only
> syslog.rst: mention the correct kconfig option

- audio/audio_comp.c
- drivers/drivers_initialize.c
- drivers/pipes/fifo.c
Fix typo and comment style in:
* audio/audio_comp.c
* drivers/drivers_initialize.c
* drivers/pipes/fifo.c
Typo fix only
CI
> Fix some minor style issues

- arch/risc-v/src/common/riscv_internal.h
Add function description for function prototype of `riscv_jump_to_user` to make it easier to read, and fix some inconsistent comment style in `riscv_internal.h`.
Comment only
GitHub CI
> arch/risc-v: Minor document improvement

- include/netinet/in.h
add add IN6_IS_ADDR_GLOBAL macro
fix LINKLOCAL macro bug
IPV6
None
> IPV6 macro

- libs/libc/machine/arch_atomic.c
use small lock in libs/libc/machine/arch_atomic.c
atomic
ci
> arch_atomic: use small lock in libs/libc/machine/arch_atomic.c

- libs/libxx/libcxxmini/CMakeLists.txt
- libs/libxx/libcxxmini/Make.defs
- libs/libxx/libcxxmini/libxx_dynamic_cast.cxx
- libs/libxx/libcxxmini/libxx_typeinfo.cxx
- libs/libxx/libcxxmini/libxx_typeinfo.h
reference:https://github.com/libcxxrt/libcxxrt/tree/master/src
libcxxmini
ci test
> libcxxmini: Add missing runtime related classes.

- tools/gdb/nuttxgdb/fs.py
- tools/gdb/nuttxgdb/protocols/fs.py
- tools/gdb/nuttxgdb/protocols/thread.py
- tools/gdb/nuttxgdb/protocols/value.py
- tools/gdb/nuttxgdb/utils.py
~This PR depends on previous PR to merge firstly. Please ignore the first commit that squashed of previous PR.~
Introduce `utils.Value` to replace `gdb.Value` and together with `Protocol` we can use `value.element` instead of `value["element"]` to access structure.
Make changes in `fs` module to use this feature.
Now we can access struct member directly and with type hinting.
Run `fdinfo` and it works same as before.
> nuttxgdb utils value update

- boards/risc-v/k210/maix-bit/src/CMakeLists.txt
> Fix path Error

- Documentation/applications/system/gcov/index.rst
> gcov: Add usage documentation

- drivers/sensors/gnss_uorb.c
Add suffix to macro of geofence index, just keep the same style(suffix)
N/A (internal used macro)
- NuttX CI
> drivers/sensors/gnss: Add suffix to macro of geofence index

- arch/arm/src/lc823450/lc823450_usbdev.c
lc823450_usbdev: use small lock in arch/arm/src/lc823450/lc823450_usbdev.c
lc823450_usbdev
ci
> lc823450_usbdev: use small lock in arch/arm/src/lc823450/lc823450_usbdev.c

- CMakeLists.txt
- Documentation/quickstart/install.rst
- tools/merge_config.py
Closes #14918
No functional impact
> install kconfiglib using apt repo

- libs/libbuiltin/libgcc/gcov.c
Some functions will insert these functions:
void __gcov_execve(void)
{
}
void __gcov_execv(void)
{
}
void __gcov_fork(void)
{
}
> gcc/gcov: Add instrumentation function

- arch/arm/src/rp23xx/rp23xx_usbdev.c
rp23xx: use small lock in arch/arm/src/rp23xx/rp23xx_usbdev.c
reason:
rp23xx
ci
> rp23xx: use small lock in arch/arm/src/rp23xx/rp23xx_usbdev.c

- drivers/virtio/virtio-mmio.c
…under label kasan
virtio: Fix the problem of incorrect setting of virtio queue address under label kasan
> virtio: Fix the problem of incorrect setting of virtio queue address under label kasan

- include/nuttx/usb/cdc.h
> Update cdc.h to fix typo in the comments

- drivers/devicetree/fdt_pci.c
- drivers/pci/pci.c
- drivers/pci/pci_ecam.c
- include/nuttx/pci/pci.h
fix pci dev alloc bridge mem error
> pci: fix pci dev alloc bridge mem error

- arch/arm/src/cxd56xx/cxd56_rtc.c
cxd56_rtc.c: use small lock in arch/arm/src/cxd56xx/cxd56_rtc.c
reason:
cxd56_rtc
ci ostest
> cxd56_rtc.c: use small lock in arch/arm/src/cxd56xx/cxd56_rtc.c

- arch/risc-v/src/litex/litex_serial.c
We hope to remove all instances of spin_lock_irqsave(NUL
litex_serial: use small lock in arch/risc-v/src/litex/litex_serial.c
litex_serial
ci
> litex_serial: use small lock in arch/risc-v/src/litex/litex_serial.c

- Documentation/guides/usingkernelthreads.rst
- arch/arm/src/rp2040/rp2040_adc.c
> Fix documentation

- binfmt/binfmt_execmodule.c
- drivers/devicetree/fdt.c
limits/path: replace CONFIG_PATH_MAX to PATH_MAX to ensure consistency
replace CONFIG_PATH_MAX to PATH_MAX to ensure consistency
N/A
ci-check
> limits/path: replace CONFIG_PATH_MAX to PATH_MAX to ensure consistency

- Documentation/applications/examples/ina226/index.rst
added example of doc ina226
none
CI
> docs: Fix example ina226

- binfmt/binfmt_execmodule.c
- drivers/devicetree/fdt.c
replace CONFIG_PATH_MAX to PATH_MAX to ensure consistency
RELEASE
CI
> {bp-15103} limits/path: replace CONFIG_PATH_MAX to PATH_MAX to ensure consistency

- Documentation/guides/usingkernelthreads.rst
- arch/arm/src/rp2040/rp2040_adc.c
> {bp-15101} Fix documentation

- arch/arm/src/cxd56xx/cxd56_rtc.c
> {bp-15092} cxd56_rtc.c: use small lock in arch/arm/src/cxd56xx/cxd56_rtc.c

- arch/xtensa/src/esp32s3/esp32s3_spiflash_mtd.c
g_work as singleton can be changed by context switching, but previous one async operation have not finished yet.
one additonal mutex is used for g_work to keep the sequence correctly.
reproduce and verified by below steps
1. Variable g_wrok is sent to work_queue() function and set value to this variable.
2. Another context changes g_work by call esp32_async_op during step 1. g_work of Step 1 is changed because g_work is singleton.
3. Step 1 hanges because g_work of step 1 are cleared by step 2.
> xtensa/esp32s3: add lock for async operation work

- Documentation/applications/testing/drivertest/index.rst
remove vela, add simple description
None, doc rst only.
ci-test
> document/drivertest: add more information in drivertest

- arch/risc-v/src/litex/litex_serial.c
> {bp-15097} litex_serial: use small lock in arch/risc-v/src/litex/litex_serial.c

- binfmt/binfmt_exec.c
binfmt/loadable: move binary_s to stack to avoid access allocator
binfmt/loadable: move binary_s to stack to avoid access allocator
Improve performance by reducing allocator accesses
sim/nsh
> binfmt/loadable: move binary_s to stack to avoid access allocator

- arch/risc-v/src/common/espressif/esp_mcpwm.c
- arch/xtensa/src/common/espressif/esp_mcpwm.c
esp/mcpwm: fix unpaired spin lock
N/A
Signed-off-by: chao an [anchao@lixiang.com](mailto:anchao@lixiang.com)
RELEASE
CI
> {bp-15127} esp/mcpwm: fix unpaired spin lock

- sched/semaphore/sem_trywait.c
- sched/semaphore/sem_wait.c
sem: remove the additional assignment.
reason:
running tcb->waitobj should be NULL
sem 
ci ostest
> sem: remove the additional assignment.

- include/cxx/cmath
same to pull request #12672 
I made a typo.
> fix a typo

- tools/macar-qcs.sh
Xiaomi has signed the SGA and we can migrate the license to ASF
LICENSE
CI
> tools/macar-qcs.sh: migrate license to ASF

- fs/inode/fs_files.c
fix comment in https://github.com/apache/nuttx/pull/15163
filep->f_refs
ci
> fs: fix comment in https://github.com/apache/nuttx/pull/15163

- libs/libc/misc/lib_pathbuffer.c
Avoid spinlock/mutex by using atomic
Use atomic_cmpxchg to ensure that in multithreaded situations, if someone releases the buffer, it can be applied for in time. And use atomic_ulong to save free_bitmap
Passed the file system related syscall test
> lib_pathbuffer.c:Use atomic instead of locks

- arch/arm/src/lc823450/lc823450_rtc.c
lc823450_rtc: use small lock in arch/arm/src/lc823450/lc823450_rtc.c
reason:
lc823450_rtc
ci
> lc823450_rtc: use small lock in arch/arm/src/lc823450/lc823450_rtc.c

- boards/sim/sim/sim/scripts/Make.defs
no functional changes are intended.
build tested sim:lua on macOS with a few local changes in apps.
> boards/sim/sim/sim/scripts/Make.defs: simplify a bit

- arch/arm/src/samv7/sam_gpio.c
some replacements were omitted.
reason:
fix regression from https://github.com/apache/nuttx/pull/15219
none
ci
> some replacements were omitted.

- arch/arm/src/tiva/tm4c/tm4c_gpio.c
> fix compile error

- wireless/bluetooth/bt_netdev.c
bluetooth: rm bd_bifup
bluetooth
ci
> bluetooth: rm bd_bifup

- arch/arm/src/samv7/sam_gpio.c
fix regression from https://github.com/apache/nuttx/pull/15219
RELEASE
CI
> {bp-15238} arch/samv7: some replacements were omitted.

- fs/procfs/fs_procfsmeminfo.c
procfs:add missing ',' to end of line
typo fix
> procfs:add missing ',' to end of line

- drivers/bch/bchdev_driver.c
Don't fail if the lowerhalf mtd driver doesn't support BIOC_FLUSH; This is normal - if the lowerhalf has nothing to do, it doesn't handle the IOCTL.
RELEASE
CI
> {bp-15259} drivers/bch/bchdev_driver.c: Fix BIOC_FLUSH

- include/unistd.h
- libs/libc/libc.csv
- libs/libc/unistd/lib_getcwd.c
add `get_current_dir_name` API implementation
has no impact on other module
has passed ostest
> nuttx: add get_current_dir_name implementation

- fs/socket/accept.c
At least on RISC-V, TCP server sockets were pretty much unusable on high load environments and kernel build.
User addresses passed to `accept()` would be accessed when the wrong MMU mappings were active. A crash would manifest when attempting to `accept()` for instance on a TCP server socket under significant load. The accept event handler would be called by the HP worker upon client connection. At this point, `accept_tcpsender()` would attempt to write to `addr` resulting in a page fault. Reproducibility would depend on the current system load (num tasks or CPU stress) but in loaded environments, it would crash almost 100% of the times.
I have not reproduced the issue on other boards/archs, but I think it should be applicable:
- `accept()` gets called by task A
- context is switched to …
> Map user memory passed to accept() in kernel build

- include/nuttx/mutex.h
- libs/libc/misc/lib_mutex.c
Add some clarification comments on the mutex api
no functional changes are intended.
> Add some clarification comments on the mutex api

- fs/socket/accept.c
Fixes an issue in kernel build where the user addresses passed to accept() would be accessed when the wrong MMU mappings were active. A crash would manifest when attempting to accept() on a TCP server socket for instance under significant load. The accept event handler would be called by the HP worker upon client connection. At this point, accept_tcpsender() would attempt to write to `addr` resulting in a page fault. Reproducibility would depend on the current system load (num tasks or CPU stress) but in loaded environments, it would crash almost 100% of the times.
It should be noted that Linux does this the other way around: it operates on kernel stack allocated data and once done, it copies them to user. This can also be a viable alternative, albeit with one extra copy and a little …
> {bp-15278} Map user memory passed to accept() in kernel build

- Documentation/ReleaseNotes/NuttX-12.7.0
- Documentation/ReleaseNotes/NuttX-12.8.0
add NuttX 12.8.0 Release notes
add NuttX 12.7.0 Release notes
RELEASE
NONE
> {bp-15373} Documentation: add NuttX 12.8.0 Release notes

- Documentation/ReleaseNotes/NuttX-12.7.0
- Documentation/ReleaseNotes/NuttX-12.8.0
add NuttX 12.8.0 Release notes
add NuttX 12.7.0 Release notes
Documentation
NONE
> Documentation: add NuttX 12.8.0 Release notes

- arch/sim/src/sim/sim_oneshot.c
> sim/oneshot: Remove redundant variables.

- include/nuttx/fs/fs.h
> Remove duplicate code

- arch/arm/src/armv7-a/Toolchain.defs
Changed the LLVM architecture type from thumbv7 to thumbv7a in Toolchain.defs to better match the ARMv7-A architecture specification. This change ensures proper code generation and optimization for Cortex-A series processors when using the Thumb instruction set.                            
The thumbv7 architecture type is a generic designation, while thumbv7a specifically targets the ARMv7-A architecture profile used in Cortex-A series processors. This change aligns the toolchain configuration with the actual hardware architecture being targeted.                             
Build system for armv7-a only …
> armv7-a/Toolchain.defs: Update LLVM arch type to thumbv7a

- arch/arm64/src/common/arm64_registerdump.c
> arm64: assert support dump sctlr_el1 register

- drivers/rptun/CMakeLists.txt
- drivers/rptun/Kconfig
- drivers/rptun/Make.defs
- drivers/rptun/rptun_bmp.c
- include/nuttx/rptun/rptun_bmp.h
Change rptun_secure to rptun_bmp to make it more general.
rptun_bmp
ci
> change rptun_secure to rptun_bmp

- drivers/sensors/goldfish_sensor_uorb.c
Add get_info function to goldfish to get basic information of sensor
Now goldfish sensor can get sensor basic information
goldfish uorb_listener
> goldfish sensor add get_info interface

- tools/refresh.sh
tools/refresh.sh: Should continue to refresh other configs when matching debug configs
See https://github.com/apache/nuttx/issues/15530
tools/refresh.sh
CI
> tools/refresh.sh: Should continue to refresh other configs when matching debug configs

- tools/refresh.sh
tools/refresh.sh: Add log for progress
e.g.
```
$ ./tools/refresh.sh --silent --defaults arch:risc-v
Normalizing all boards in arch: risc-v !
[1/227] Normalize arty_a7/nsh
[2/227] Normalize arty_a7/netnsh
[3/227] Normalize arty_a7/knsh
```
tools/refresh.sh
CI
> tools/refresh.sh: Add log for progress

- arch/renesas/src/rx65n/rx65n_usbdev.c
Use small lock to protect usbdev and endpoint in renesas.
nuttx/arch/renesas/src/rx65n/rx65n_usbdev.c
CI
> Use small lock to protect usbdev and endpoint in renesas.

- drivers/can/ctucanfd_pci.c
Corrected CAN FD messages sending in character driver mode. Assign CAN FD format flag in reception of CAN FD messages. Corrected some defines mismatches.
The overall state of this third party CTU CAN FD driver in NuttX is far from ideal. It would worth to consult and follow more closely our Linux kernel driver and even better RTEMS CAN/CAN FD stack design
https://canbus.pages.fel.cvut.cz/#cancan-fd-subsystem-and-drivers-for-rtems
Without these fixes, CAN FD messages are sent without FDF flag set and if combined with data
length longer than 8 bytes then it causes error reporting on QEMU side when sent to
host over SocketCAN and message is discarded.
Other errors cause incoming messages missing ch_edl flag set for FDF marked incoming
messages.
The code has been tested in QEMU …
> drivers/can: ctucanfd the first round of fixes - mainly for char dev

- sched/wqueue/kwork_queue.c
- sched/wqueue/kwork_thread.c
sched/wqueue: some minor improve to reduce sched_lock range
N/A
ci-check
> sched/wqueue: some minor improve to reduce sched_lock range 

- Documentation/applications/system/uorb/index.rst
forget in:
commit 71a37b4f2dec807c092db3a45e5678e48ec61f9f
Author: chao an <anchao.archer@bytedance.com>
Date:   Wed Jan 15 09:56:44 2025 +0800
Documentation: clean up of CONFIG_NSH_LINELEN define
minor
ci
> Documentation: Replace NSH_LINELEN with LINE_MAX

- arch/arm/src/cxd56xx/cxd56_timer.c
- arch/arm/src/lpc17xx_40xx/lpc17_40_timer.c
- arch/arm/src/lpc43xx/lpc43_timer.c
Use small lock to protect timer related resources in arch ARM.
arch/arm/src/lpc43xx/lpc43_timer.c
arch/arm/src/lpc17xx_40xx/lpc17_40_timer.c
arch/arm/src/cxd56xx/cxd56_timer.c
CI
>  Use small lock to protect resources related to timers in arch ARM.

- arch/arm/src/cxd56xx/cxd56_cpufifo.c
Use small lock to protect cpufifo related resources.
nuttx/arch/arm/src/cxd56xx/cxd56_cpufifo.c
CI
> Use small lock to protect resources related to cpufifo.

- libs/libc/gdbstub/lib_gdbstub.c
GDB has introduced binary memory read mode, which can improve memory read speed significantly.
See https://sourceware.org/pipermail/gdb-patches/2024-March/207238.html
https://github.com/apache/nuttx/commit/6eea3580c4d61d7362687b4b11d307f377599c8d
GDB use the newly introduced packet ‘x addr,length’ to read binary data.
The response starts with `b` to make it different than normal memory read reply.
More info can be found here https://sourceware.org/gdb/current/onlinedocs/gdb.html/Packets.html#Packets
https://github.com/apache/nuttx/commit/0e9ca65bf9423b84310e0d71104def15540e0e9a
1.  Checksum should be done regarding data on wire. Thus move checksum calculation directly to …
> Gdbstub support binary memory read

- fs/vfs/fs_read.c
- fs/vfs/fs_write.c
file_readv_compat: add a comment to explain limitations
no functional changes are intended.
> file_readv_compat: add a comment to explain limitations

- drivers/rpmsg/rpmsg_port_uart.c
drivers/rpmsg: update format string as the function `file_write()` may return negative `errno`.
drivers/rpmsg
CI
> drivers/rpmsg: update format string

- arch/arm/src/samv7/sam_tc_lowerhalf.c
The CPCSTOP has a negative effect on the periodic timer operation. This causes the timer of stop when and overrun occurs. Timer must be then restarted in the interrupt. However, as interrupts are not infinitely fast, this prolongs the next timeout.
I've been doing several experiments with control applications. The sampling was achieved by configuring a timer driver using the `TCIOC_NOTIFICATION` ioctl call. However, I spotted the achieved sampling frequency (using a simple SW counter in a high prio task) was smaller than the configured one. 
This was caused by a badly configured timer. In `sam_tc_lowerhalf.c`, it was assumed the timer stops and resets itself when an overrun occurs. The timer needed to be restarted in the overrun interrupt handler. This introduced a small but nonnegligible …
> arch/arm/src/samv7/sam_tc_lowerhalf.c: do not set the CPCSTOP bit

- drivers/sensors/Kconfig
drivers\sensors\Kconfig
Remove spaces from Kconfig files
Add TABs
local
> [Kconfig] Fix Kconfig style

- arch/risc-v/src/common/riscv_backtrace.c
This PR moves the boundary check when `CONFIG_ARCH_INTERRUPTSTACK>15` to inside the backtrace function.
Also updated the backtrace function to check the interrupt stack boundaries, allowing for future support of backtrace from IRQ.
Impact on user: NO.
Impact on hardware: Only RISC-V devices affected.
This was tested with two different test cases:
1. Using default ARCH_INTERRUPTSTACK=2048
2. ARCH_INTERRUPTSTACK=0 and CONFIG_INIT_STACKSIZE=4096.
Also ran a full CI test internally on all Espressif RISC-V devices and had no issues.
1. ./tools/configure.sh rv-virt:nsh
2. CONFIG_SCHED_BACKTRACE=y
3. CONFIG_FRAME_POINTER=y
4. Enable test app
5. make
About 4: Built a test app to validate and …
> arch/risc-v: move stack boundary check into backtrace

- arch/risc-v/src/mpfs/mpfs_irq.c
Enable interrupts on all cores, when enabling an external interrupt source.
Instead of enabling an interrupt on the calling hart, enable it on every hart. This should balance the interrupt load some, especially in cases where the interrupt source is enabled only once (which will almost certainly happen on CPU 0 only).
Impact is MPFS platform, SMP mode only.
Tested with downstream MPFS target, with SMP=y and SMP=n.
> mpfs/mpfs_irq.c: Enable interrupts on all harts

- arch/risc-v/src/mpfs/mpfs_irq.c
From Polarfire SoC TRM:
6.5.8 Interrupt Completion
To signal the completion of executing an interrupt handler, the processor core writes the received interrupt ID to the Claim/Complete register. The PLIC does not check whether the completion ID is the same as the last claim ID for that target. If the completion ID does not match an interrupt source that is currently enabled for the target, the completion is ignored.
The last paragraph clearly states that IRQ completion does not work for sources that have been disabled -> must ACK the completion before disable.
This fixes interrupt disabling for MPFS. The ordering of interrupt completion (writing to the claim register) and interrupt disable was simply wrong.
No other targets are affected.
Tested with downstream MPFS target with I2C driver …
> mpfs_irq.c: Interrupt claim must be cleared before disabling the source

- arch/tricore/src/cmake/ToolchainGnuc.cmake
- arch/tricore/src/cmake/ToolchainTasking.cmake
- boards/arm/csk6/csk6011a-nano/src/Makefile
- boards/arm/imx9/imx95-evk/scripts/Make.defs
- boards/arm/imx9/imx95-evk/src/Makefile
- libs/libc/machine/x86_64/gnu/CMakeLists.txt
- libs/libxx/uClibc++/system_configuration.h
fix Relative file path does not match actual file.
local
> [nxstyle] fix Relative files path

- tools/nxstyle.c
Simple fix for [15838](https://github.com/apache/nuttx/issues/15838)
*Note:* The comments are also treated as statement:
```c
case ':': /* error is thrown here */
{
do something
}
```
Can solve that corner case if needed also.
New style errors can be reported throughout the codebase.
Localy, running nxstyle over a wrongly formatted file.
If case statement continues on the same line an error will be generated
```
~/Projects/nxspace/nuttx/tools/nxstyle.c:1203:14: error: Case statement should be on a new line
```
> tools/nxstyle: handle case statement

- Documentation/applications/boot/nxboot/index.rst
This updates nxboot documentation with the last changes in nuttx-apps repository.
Documentation update only. This reflects https://github.com/apache/nuttx-apps/pull/3024 and should be merger after/with it.
> documentation/boot/nxboot: update nxboot documentation

- net/devif/ipv6_input.c
When a udp frame is processed without a listener a icmp frame is returned indicating that there is no listener. The PR enables sending this icmpv6 response over sixlowpan.
Solves #15972.
* Is new feature added? YES
* Impact on user (will user need to adapt to change)? NO
* Impact on build (will build process change)? NO - Changes are localized to the networking stack.
* Impact on hardware (will arch(s) / board(s) / driver(s) change)? NO - This is a software fix affecting network protocol handling.
* Impact on documentation (is update required / provided)? NO -  The fix addresses an undocumented edge case.
* Impact on security (any sort of implications)?  NO -  While the bug could disrupt communication, it did not introduce a direct security vulnerability. The fix further enhances …
> net: sixlowpan icmpv6 return from udp_input

- net/udp/udp_input.c
Ensure that the correct icmp(v6) response is generated from udp_input.
A incorrect icmp response could be generated when there is no listener on a udp port for a setup that uses ipv6, ipv4 and icmp. This would then block ipv6_input and halt any communication (reported in #15962). 
No changes for users.
Different setups of ipv6 + ipv4 and icmp/icmpv6 where tested and validated that no wrong package was returned.
Verified on esp32-devkitc.
> net/udp: correct icmp(v6) response from udp_input

- audio/audio_comp.c
audio/composite: merge composite instance allocate to one times
here is not need to allocate two times
N/A
enable CONFIG_AUDIO_COMP and playback music
> audio/composite: merge composite instance allocate to one times

- drivers/usbdev/cdcacm.c
fix issue https://github.com/apache/nuttx/issues/16004.
In cdcacm, USB req buf is directly used as serial buf, so the operation about buf status in ioctl is different from the original serial.
This change modifies the ioctl handling in cdcacm to properly track the state of the USB buffers, resolving an issue with incorrectly querying the number of bytes in the RX/TX buffers.
1. Get the number of bytes that may be read from the RX buffer
> Read the number of bytes in all pending bufs.
3. Get the number of bytes that have been written to the TX buffer
> Read the data of all buffers that are not in the free list
5. Get the number of free bytes in the TX buffer
> Read the data of all buffers in the free list
7. Empty the tx/rx buffers
> rx: Clear all data in pending buf and set buf to the out …
> driver/serial/cdcacm: Get the status of rx or tx buf by ioctl

- boards/arm/cxd56xx/common/CMakeLists.txt
- boards/arm/cxd56xx/common/src/Make.defs
- boards/arm/cxd56xx/common/src/cxd56_cxd5602pwbimu.c
- boards/arm/cxd56xx/spresense/Kconfig
- boards/arm/cxd56xx/spresense/include/board.h
- boards/arm/cxd56xx/spresense/include/cxd56_cxd5602pwbimu.h
- boards/arm/cxd56xx/spresense/src/cxd56_bringup.c
- drivers/sensors/CMakeLists.txt
- drivers/sensors/Kconfig
- drivers/sensors/Make.defs
- drivers/sensors/cxd5602pwbimu.c
- include/nuttx/sensors/cxd5602pwbimu.h
Add CXD5602PWBIMU driver for IMU Add-on board.
Only for Spresense board
Do work IMU Add-on board with Spresense.
> drivers/sensors: Add CXD5602PWBIMU driver for IMU Add-on board

- drivers/mtd/at45db.c
When writing to flash using the FTL driver over a at45db MTD flash device, eventually the ftl_flush function is called and it does an erase (MTD_ERASE) and then the write (MTD_BWRITE). Currently, the at45db driver (at45db.c), uses a write command 0x82 ("Main Memory Page Program through Buffer 1 with Built-In Erase") that also performs a built-in erase before the write. In summary, each time a write to flash is performed, **the page is erased twice** before it is written, first in the FTL driver and then in the MTD driver.
This PR is to change the page writes to avoid this double erase. Instead of using AT45DB_MNTHRUBF1 (0x82) command that includes a built-in erase, use AT45DB_WRBF1 (0x84) and AT45DB_BF1TOMN (0x88) commands to write the data to the SRAM buffer1 and to dump buffer1 to …
> driver/mtd/at45db.c: write to page without built-in erase

- net/can/can_callback.c
Fix timestamp in socket CAN. Right now the timestamp is only generated if there is no reader and the frame is stored in the read ahead list. This is solved by moving the timestamp generation before the code flow branch.
RELEASE
CI
> {bp-15952} net/can: fix timestamp

- include/nuttx/fs/uio.h
Fix code comment in `include/nuttx/fs/uio.h`.
RELEASE
CI
> {bp-15976} typo: fix incorrect doc

- net/udp/udp_input.c
Ensure that the correct icmp(v6) response is generated from udb_input.
RELEASE
CI
> {bp-15978} net/udp: correct icmp(v6) response from udp_input

- net/devif/ipv6_input.c
When a udp frame is processed without a listener a icmp frame is returned indicating that there is no listener. The PR enables sending this icmpv6 response over sixlowpan.
RELEASE
CI
> {bp-15980} net: sixlowpan icmpv6 return from udp_input

- tools/pynuttx/nxgdb/dmesg.py
nuttxgdb/dmesg.py:add use gdb dump rpmsg_syslog
(gdb) dmesg
RAM log:
[01/06 02:27:05] [ 1] [cp] reset mode:1
...
[01/06 02:27:05] [ 1] [cp] Dump board_reset backtrace: [01/06 02:27:05] [ 1] [cp] sched_dumpstack: backtrace| 1: 0x10a0d880 0x10a0a78e 0x10a0d8b6 0x10a0f29e 0x10a0f182 [01/06 02:27:05] [ 1] [cp] Time: Mon Jan  6 02:27:05 2025 ---END of RAMLOG
RPMSG syslog:
dumpstack: backtrace|10: 0x10a0d880 0x10a0a78e 0x10a110de 0x10a3a482 0x10a3c4fa 0x10a23358 0x10a4aaee 0x10a34a7c 
[01/06 02:27:05] [ 1] [cp] sched_dumpstack: backtrace|10: 0x10a2330a 0x10a0f1f4
[01/06 02:27:05] [ 1] [cp] sched_dumpstack: backtrace|11: 0x10a0d880 0x10a0a78e 0x10a110de 0x10a3a482 0x10a15152 0x10a0f182 
[01/06 02:27:05] [ 1] [cp] sched_dumpstack: backtrace|15: 0x10a0d880 0x10a0a78e 0x10a0d8b6 0x10a174d0 …
> nuttxgdb/dmesg.py:add use gdb dump rpmsg_syslog

- drivers/mtd/at45db.c
Using the FTL driver over a MTD flash device, when writing to flash, eventually the ftl_flush function is called and it does an erase (MTD_ERASE) and then the write (MTD_BWRITE). Currently, the at45db driver (at45db.c), uses a write command 0x82 ("Main Memory Page Program through Buffer 1 with Built-In Erase") that also performs a built-in erase before the write. In summary, each time a write to flash is performed, the page is erased twice before it is written, first in the FTL driver and then in the MTD driver.
This PR is to change the page writes to not use that built-in command.
RELEASE
CI
> {bp-16075} driver/mtd/at45db.c: write to page without built-in erase

- drivers/serial/serial.c
If the expected amount of data is not read during read, check again whether there is data in buffer(CDCACM... might have buffered data received). If so, continue processing the data. If not, then check the file or dev flags.
Serial read. Move the judgment of the file or dev flag to after the second check of the rx buffer data amount.
Tested on sim and raspberrypi-pico-2 board. 
When using cdcacm, if use usb req buf directly as the serial buf, execute the following code：
Before the fix, Refer to the comments in the code for the execution status.
After the fix, We can read the expected amount of data.
```
int bytes_available = 0;
int retval = ioctl(ttyacm_fd, FIONREAD, &bytes_available);
/* Collect 2 characters at a time to the buffer and
* print them out
*/
int bytes_to_read = 2;
if …
```
> driver/serial: Check again the RX buffer, then check file flags

- arch/arm/src/stm32h7/Kconfig
- arch/arm/src/stm32h7/stm32_ltdc.c
implement stm32h7 ltdc double buffer on layer 1
> feat(nuttx): implement stm32h7 ltdc double buffer on layer 1

- drivers/serial/uart_rpmsg.c
serial/uart_rpmsg: simplify initialization process of uart_rpmsg
Merge multiple heap allocate into one
N/A
sim/rpproxy;sim/rpserver
> drivers/serial/uart_rpmsg: simplify initialization process of uart_rpmsg

- drivers/serial/serial.c
The UART driver (cdcacm...) might have buffered data received, Just continue processing the RX queue if this happens. If not, then check the file or dev flags.
RELEASE
CI
> {bp-16086} driver/serial: Check again the RX buffer, then check file flags

- fs/littlefs/lfs_vfs.c
i couldn't find any documenation about this attribute. this comment is purely based on my reading of the code.
just a comment
nxstyle passed.
otherwise, not tested.
> add a comment on littlefs_attr_s to explain what it is

- arch/arm/src/imx6/imx_serial.c
Will Compile error if enable IMX6_UART2..5
RELEASE
CI
> {bp-16112} arch/arm/imx6: fix missed comma

- Documentation/ReleaseNotes/NuttX-12.9.0
Add release notes for 12.9.0 release
RELEASE
CI
> (bp-16144) Documentation: add NuttX-12.9.0 release notes

- Documentation/ReleaseNotes/NuttX-12.9.0
Add release notes for 12.9.0 release
RELEASE
CI
> Documentation: add NuttX-12.9.0 release notes

- fs/littlefs/lfs_vfs.c
Because sync is a rather expensive operation.
While I'm here, improve the comment after the recent discussion in https://github.com/apache/nuttx/pull/2913.
IMHO, we should not perform the sync even for O_TRUNC. But I'm not going to propose the change for now.
strictly speaking, this is a breaking change as it alters semantics a little.
> littlefs_open: sync the file only when O_TRUNC is specified

- drivers/wireless/bluetooth/bt_uart.c
- wireless/bluetooth/bt_hcicore.c
Bluetooth HCI and UART driver fixes.
RELEASE
CI
> {bp-16179} wireless/bluetooth: bt_hcicore and bt_uart related fixes

- CMakeLists.txt
Documentation: fix typo in comments
> Documentation: fix typo in comments

- arch/arm/src/stm32h5/stm32_adc.c
Properly configure internal channels on STM32H5 ADC when selected. The original had incorrect bit masks and configuration for internal channel defines. 
Original code by @ArrestedLightning https://github.com/ArrestedLightning/nuttx/tree/h5_adc_internal_ch
Fixes runtime bugs with ADC.
Board: Custom board.
Chip: STM32H563ZI
> arch/arm/stm32h5: Fix ADC internal channel configuration.

- arch/arm/src/stm32h5/stm32_start.c
Some hardware configurations require .bss and data initialization before being called.
Code and testing done by @ArrestedLightning. 
Just switches the order of initialization in the start file, to prevent errors.
Will fix runtime assertions with certain hardware configurations.
Board: Custom board
Tested processor: STM32H563ZI
> arch/arm/stm32h5: copy bss and initialized data before configuring hardware

- Documentation/applications/examples/elf/index.rst
Update the documentation to align with https://github.com/apache/nuttx-apps/pull/3062
user impact: none,
build process: none,
hardware: none,
documentation: update to align with nuttx-apps,
security: none,
compatibility: none
Only documentation update.
> Documentation/applications/examples/elf/index.rst: Update for PR #3062 in nuttx-apps

- Documentation/reference/user/02_task_scheduling.rst
- arch/avr/include/atmega/irq.h
- arch/avr/include/avr/irq.h
- arch/avr/src/atmega/Kconfig
- arch/avr/src/atmega/atmega_head.S
- arch/avr/src/avr/Kconfig
- arch/avr/src/avr/avr_initialstate.c
- arch/avr/src/avr/avr_registerdump.c
- arch/avr/src/avr/avr_schedulesigaction.c
- arch/avr/src/avr/avr_sigdeliver.c
- arch/avr/src/avr/excptmacros.h
- include/nuttx/compiler.h
These are fixes created by kr.git@kerogit.eu who also added support to AVRDB (that will come next)
Improvements
AVR8
> arch/avr: Fixes before adding support to AVRDB

- arch/xtensa/src/esp32s3/esp32s3_tickless.c
In tickless mode, timer start and be handled when timeout interrupt, but timer may has pending interrupt during the timer cancel, it will trigger interrupt when next timer start, cause next timer handle unexpected interrupt, which cause timed wait return with timeout but time not expired.
This patch checks if the timer real timeout when tickless_isr handle interrupt, if not timeout, then wait again, meanwhile modify several registers according reference manual.
Impact on user: NO. 
Impact on hardware: YES. Impacts ESP32S3 systimer.
Test with our internal project, …
> xtensa/esp32s3: fix tickless mode timer unexpect interrupt handle

- .asf.yaml
* We do not have "Settings" tab in the Apache's owned repository, thus we need to update `.asf.yaml` file with repository settings.
* No direct push to master branch is possible.
* Require status checks to pass before merge.
* Setup reviews parameters.
* Require signatures.
* Require conversation resolution.
* Require linear history.
* If all is fine here I will do the same update for nuttx-apps repo :-)
References:
[1] https://github.com/apache/infrastructure-asfyaml.
GitHub repository master branch protections.
* I am not really familiar with all these settings, please review if this is what we want/need.
* Particularly the "checks" part needs verification if these are valid names (@lupyuen @hartmannathan ?).
* Asked for review from asfinfra, looks okay.
> github: Setup protection for master branch.

- arch/arm/src/rp23xx/rp23xx_serial.c
Most of the code is the same, update to recent fixes see commits cb6ad9dfbd98c407c17aafcb7a1beb9b7e41d8c1, 204d88bcf31bbad30265296afd651b6fc9c339c7, c05ace557f2c3e2b47878cf09ef304f6f188573e
> arch/arm/rp23xx: update serial code to recent smp fixes from cxd56 serial code

- Documentation/platforms/arm/rp23xx/index.rst
DMA, FPU/DSP, watchdog, chip tags docs update
> Documentation: update rp23xx page for recent changes

- arch/arm/src/rp23xx/rp23xx_serial.c
spin lock/unlock introduced #16331 before sometimes got stuck on tx 
working serial on SMP config
Tested on pico2 nsh config and SMP (2 cores) config.
> arch/arm/rp23xx: remove spinlock from up_txint

- drivers/mmcsd/mmcsd_sdio.c
SD card may suffers from reading problems on some devices including esp32s3.
The root cause is, FIFO is not supported on it so far, so that SDIO_RECVSETUP does not work properly.
So the solution is to call SDIO_DMARECVSETUP instead of SDIO_RECVSETUP if  DMA is enabled.
Which is also aligning with all the other callings of "recvsetup" in mmcsd_sdio.c.
drivers/mmcsd/mmcsd_sdio.c: use SDIO_DMARECVSETUP instead of SDIO_RECVSETUP if  DMA is enabled in mmcsd_get_scr.
https://gist.github.com/Windrow14/19241fc1381013d8255d0df5d428c4e0
> drivers/mmcsd/mmcsd_sdio.c: use dma to receive setup if dma is enabled

- arch/sim/src/sim/sim_canchar.c
- arch/sim/sim_canchar.c: notify upper-half driver that tx done
add missing can_txdone() callback after message is send
fix problem with CAN character driver that stops sending frames after some time
simulator with custom CAN application
> arch/sim/sim_canchar.c: notify upper-half driver that tx done

- fs/vfs/fs_close.c
fix issue about  race condition:
fix bug about close
openVela monkey test
> fs/close: move inode to last to void race condition

- arch/xtensa/src/common/espressif/Kconfig
- drivers/video/Kconfig
- drivers/wireless/lpwan/Kconfig
Remove spaces from Kconfig files
Add comments
Add TABs
local
> [Kconfig]: Fix Kconfig style

- drivers/can/ctucanfd_pci.c
fix an unaligned pointer error for arm32 build:
```
ctucanfd_pci.c:1361:7: warning: converting a packed 'struct ctucanfd_frame_s'
pointer (alignment 1) to a 'uint32_t' {aka 'long unsigned int'} pointer (alignment 4)
may result in an unaligned pointer value [-Waddress-of-packed-member]
1361 |       ptr = (FAR uint32_t *)&rxframe;
```
fix build error for qemu-arm32
build custom CAN application on `qemu-armv7a`
> drivers/ctucanfd_pci.c: fix pointer unaligned GCC error

- sched/signal/sig_timedwait.c
nxsig_timeout calls nxsched_add_readytorun and up_switch_context, so must be in critical section.
nxsig_timeout is used as wdentry in nxsig_clockwait
See wd_expiration CALL_FUNC is not in critical section.
Also `nxsig_clockwait` description stated that should be called with critical section set, but it's not the case from
- nxsig_timedwait
- clock_nanosleep
- nxsig_nanosleep
> sched/timedwait: Ensure critical section for nxsig_timeout

- sched/wdog/wd_cancel.c
> Revert "sched/wdog/wd_cancel: Return 0 (OK) when cancelling an inactive wdog"

- tools/nxstyle.c
fix
error: Relative file path does not match actual file
Windows paths are different from Unix.
Added:
- realpath replacement macro.
-  my_strndup() Implementation of strndup() for Windows Native.
- backslash_to_slash() Replace backslashes \ to forward slashes /.
Used to verify the relative path of a file.
Impact on user: This PR fix error: Relative file path on Windows Native
locally Windows Native and Msys2
> tools/nxstyle.c: fix error Relative file path on Windows Native

- Documentation/conf.py
"edit on github " option in docs
Follow up from:
https://github.com/apache/nuttx/issues/16432#issuecomment-2907608665
> adding "edit on github" option in docs

- AUTHORS
Matteo Golin has submitted the ICLA and should be added to the AUTHORS file
AUTHORS
none
> AUTHORS: add Matteo Golin

- fs/smartfs/smartfs_smart.c
When writing to the next sector after the forward position has been written by seek, the old sector buffer is used, which may corrupt the file system. Therefore, the sector buffer must always be updated after a writing by seek.
smarfs file system when CONFIG_SMARTFS_USE_SECTOR_BUFFER=y
* Simple test case
```c
{
FILE *fp;
uint8_t buf[5];
uint8_t val = 0x55;
memset(buf, 0xaa, sizeof(buf));
fp = fopen("test.txt", "wb");
fwrite(&buf, 1, 4, fp); /* [aa aa aa aa] */ 
fseek(fp, 0, SEEK_SET);
fwrite(&val, 1, 1, fp); /* [55 aa aa aa] */ 
fseek(fp, 0, SEEK_END);
fwrite(&val, 1, 1, fp); /* [55 aa aa aa 55] */ 
fclose(fp);
fp = fopen("test.txt", "rb");
fread(&buf, 1, sizeof(buf), fp);
fclose(fp);
printf("buf[] = [%02x %02x %02x %02x %02x]\n",
buf[0], buf[1], …
```
> fs/smartfs: Fix a fatal bug about sector writing after seek

- tools/testbuild.ps1
Windows: cmake fix the redirect error stream on our CI
Impact on build: This PR fi redirect error stream on our CI
locally and GitHub
```
Configuration/Tool: sim\windows
2025-06-17 15:23:57
Cleaning...
Configuring...
CMake configuration completed successfully.
MSBuild version 17.13.15+18b3035f6 for .NET Framework
1>Checking Build System
Building Custom Rule D:/a/nuttx_test_pr/nuttx_test_
....
nx_bringup.c
instrument.c
irq_initialize.c …
```
> tools/testbuild.ps1: Windows fix the redirect error stream

- include/nuttx/streams.h
- libs/libc/stream/lib_libbsprintf.c
- libs/libc/stream/lib_libvscanf.c
- libc/stream: Add support for lib_scanf 
- libc: lib_oprintf reuse var instead value for string
add a new simple function and remove the code dup in lib_sbprintf. 
ci
> Minor improve to stream

- .github/workflows/check.yml
- tools/checkpatch.sh
- **check.yml**:
This PR add missing cvt2utf installation on our CI 
- **tools/checkpatch.sh**:
Added checking all necessary tools and installation info (more user-friendly)
locally and GitHub
https://github.com/simbit18/nuttx-testing-tools/actions/runs/15761777526/job/44429924962#step:3:91
> CI checkpatch: fix cvt2utf not found and add check of all necessary tools

- AUTHORS
add Rodrigo Sim and Filipe do Ó Cavalcanti to AUTHORS 
AUTHORS
CI
> AUTHORS: add new commiters 

- Documentation/ReleaseNotes/NuttX-12.10.0
Add release notes for 12.10.0 release
RELEASE
CI
> Documentation: add NuttX-12.10.0 release notes

- mm/kasan/generic.c
- mm/kasan/hook.c
- mm/kasan/sw_tags.c
kasan watchpoint: Fix judgment problem
kasan: Fix assert judgment condition to correctly detect out-of-bounds causing trampling.
kasan: Potential recursive registration shadow area error
None
ci
> mm/Kasan: Fixed some bugs

- arch/xtensa/src/common/espressif/esp_dedic_gpio.c
After common version update of Espressif devices, dedicated GPIO for Xtensa based espressif devices started to failed build. This MR fixes that 
* arch/xtensa: Fix dedicated GPIO build error
Fix dedicated GPIO build error for esp32[-s2|-s3]
Impact on user: No, it is a bugfix
```
make distclean && ./tools/configure.sh esp32s3-devkit:gpio && kconfig-tweak -d NDEBUG; kconfig-tweak -e CONFIG_ESPRESSIF_DEDICATED_GPIO &&  make olddefconfig && make -j && make download ESPTOOL_PORT=/dev/ttyUSB0 ESPTOOL_BAUD=115200 ESPTOOL_BINDIR=../esp-bins
```
[Same steps in dedicated GPIO PR](https://github.com/apache/nuttx/pull/16223)
Sample app I used:
```
#include <nuttx/config.h> …
```
> arch/xtensa: Fix dedicated GPIO build error for esp32[-s2|-s3]

- arch/arm/src/rp23xx/rp23xx_spi.c
As done by Pico Sdk is be better to unset SSPCR1.SSE bit before to modify Spi parameters (Mode, Frequency and Bits).
and runtime logs from before …
> arch/arm/rp23xx: spi unset peripheral before  to modify Spi parameters

- Documentation/platforms/arm/stm32h7/boards/weact-stm32h743/index.rst
Update documentation to include flashing instructions
Improvement!
make html
> Doc: Update weact-stm32h743 doc to include flashing instructions

- Documentation/guides/simulator.rst
- Documentation/platforms/sim/sim/boards/sim/README.txt
- Documentation/platforms/sim/sim/index.rst
- Documentation/quickstart/configuring.rst
Update documentation to reflect new process
Improvement
N/A
> Doc: update documentation to remove reference to login / MOTD

- arch/arm/src/rp2040/rp2040_gpio.h
This PR adds support for the RP2040's GPIO output override capabilities.
Users will be able to use the GPIO output override functions of this uC similarly to how the [official SDK](https://www.raspberrypi.com/documentation/pico-sdk/hardware.html#group_hardware_gpio_1ga829129eed5d42f3455e9da339219d814) does it.
These changes were tested on a Linux host, targeting a custom Cortex-M0+ (RP2040) board using NuttX v12.8.0 as the baseline. They were then manually ported to the current master branch.
> arch/arm/rp2040: Implement GPIO output override functionality

- drivers/spi/CMakeLists.txt
Add iCE40 driver #12012
Impact on build: This PR Aligned Cmake with Make
locally
> drivers/spi/CMakeLists.txt: Aligned Cmake with Make

- drivers/mtd/mtd_config_fs.c
Report the `POLLPRI` event if any configuration is updated.
Therefore, when any configuration is updated, we can detect this state and handle it accordingly.
- mtd/nvs
1. Selftest OK with RAMMTD NVS
3.  CI
> mtd/nvs: Trigger `POLLPRI` on config change

- drivers/mtd/mtd_config_fs.c
This patch will report events in the following scenarios:
1. Events that have changed but not been waited for before being added to the interest list.
2. Events that occur after `epoll_wait()` returns and before it is called again.
- mtd/nvs
1. Selftest OK
2. CI
> mtd/nvs: Save events if not waited

- arch/risc-v/src/common/espressif/esp_rmt.c
* risc-v/espressif/rmt: Update common source code functions
- Updates the common source code for the RMT peripheral used by Espressif's RISC-Vs SoCs. This enables newer SoCs to be supported in the future while maintaining backwards compatibility.
Testing can be performed using any of the `rmt` defconfig available for any of Espressif's RISC-V-based devices (ESP32-C3, ESP32-C6, or ESP32-H2). The behavior of the rmt peripheral didn't change, and this PR's results are the same of the results before it. This can be verified:
```
make -j …
```
> risc-v/espressif/rmt: Update common source code functions

- arch/risc-v/src/common/espressif/esp_mcpwm.c
* risc-v/espressif/mcpwm: Update common source code functions
- Updates the common source code for the MCPWM peripheral used by Espressif's RISC-Vs SoCs. This enables newer SoCs to be supported in the future while maintaining backwards compatibility.
Testing can be performed using any of the `motor` defconfigs available for any of Espressif's RISC-V-based devices (ESP32-C6, or ESP32-H2). The behavior of the MCPWM peripheral didn't change, and this PR's results are the same of the results before it. This can be verified:
```
make -j …
```
> risc-v/espressif/mcpwm: Update common source code functions

- drivers/can/ctucanfd_pci.c
refactor ctucanfd_pci.c to use netdev_uperhalf for SocketCAN
use common netdev_uperhalf interface, less code duplication
qemu-intel64 communication with host SocketCAN interface on Linux works with can-utils (cansend, candump, cangen)
> drivers/can/ctucanfd_pci.c: refactor to use netdev_uperhalf

- arch/risc-v/src/common/espressif/esp_sha.c
* risc-v/espressif/sha: Update common source code functions
- Updates the common source code for the SHA accelerator used by Espressif's RISC-Vs SoCs. This enables newer SoCs to be supported in the future while maintaining backwards compatibility.
Testing can be performed using any of the `crypto` defconfigs available for any of Espressif's RISC-V-based devices (ESP32-C3, ESP32-C6, or ESP32-H2). The behavior of the SHA accelerator didn't change, and this PR's results are the same as before it. This can be verified:
```
make -j distclean …
```
> risc-v/espressif/sha: Update common source code functions

- arch/risc-v/src/common/espressif/esp_ledc.c
* risc-v/espressif/ledc: Update common source code functions
- Updates the common source code for the LEDC peripheral used by Espressif's RISC-Vs SoCs. This enables newer SoCs to be supported in the future while maintaining backwards compatibility.
Testing can be performed using any of the `pwm` defconfigs available for any of Espressif's RISC-V-based devices (ESP32-C3, ESP32-C6, or ESP32-H2). The behavior of the LEDC peripheral didn't change, and this PR's results are the same as before it. This can be verified:
```
make -j distclean …
```
> arch/risc-v/espressif/ledc: Update common source code functions
