apache/nuttx

arch/risc-v/src/nuttsbi/sbi_internal.h, arch/risc-v/src/nuttsbi/sbi_start.c
Some devices have special preparations before entering S-mode, thus a hook is needed from NUTTSBI to give them the chance.
None
=> risc-v/nuttsbi: add device specific initialization hook

fs/partition/fs_mbr.c
When the MBR partition size exceeds 2 GiB, a 32-bit wrap-around occurs,
causing an error in the block count calculation.
* wrong
brw-rw-rw- 5150605312 mmcblk0
brw-rw-rw-  629145600 mmcblk0p1
brw-rw-rw-  225443840 mmcblk0p2 <--
* fixed
brw-rw-rw- 5150605312 mmcblk0
brw-rw-rw-  629145600 mmcblk0p1
brw-rw-rw- 4520411136 mmcblk0p2 <--
=> fs: partition: fs_mbr: fix for MBR block count calculation.

libs/libc/libc.csv
Fix qsort signature with unexpected quotation mark:
It should be:
```
"int(*)(FAR const void *,FAR const void *)"
```
instead of:
```
"int(*)(FAR const void *","FAR const void *)"
```
Minor
CI
=> libc.csv: Fix qsort signature with unexpected quotation mark

sched/task/task_activate.c, sched/task/task_exit.c
Task activation/exit logs are helpful for device bringup, especially when user space nsh prompt doesn't show up.
Putting them here also allows cleaning of logs in multiple `up_exit()` functions later.
None
Checked with rv-virt/nsh, rv-virt/knsh, canmv230/nsh etc.
=> sched/logging: add task activation/exit logs

drivers/rptun/Kconfig, drivers/rptun/rptun.c, drivers/rptun/rptun.h, drivers/rptun/rptun_ping.c, drivers/rptun/rptun_ping.h, include/nuttx/rptun/rptun.h, include/nuttx/rptun/rptun_ping.h
Decoupling rptun ping and rptun_virtio_device, rptun ping and rptun.
ping is not only rptun support, so move it to public part.
Decoupling ping and rptun, other transport layers can also call ping.
Tested in sim vela, 86panel.
=> decoupling rptun ping and rptun_virtio_device, rptun ping and rptun.

libs/libxx/libcxx.cmake
It seems libcxx needs C++20 from 12.0.0 to 17.0.6: https://github.com/llvm/llvm-project/commit/3b625060fc91598d28196e559196bfc7b9a929f9
But we're setting `CMAKE_CXX_STANDARD to 17`, errors on my side:
```
nuttx/libs/libxx/libcxx/src/include/to_chars_floating_point.h:122:46: error: ‘bit_cast’ is not a member of ‘std’
122 |     const _Uint_type _Uint_value    = _VSTD::bit_cast<_Uint_type>(_Value);
|                                              ^~~~~~~~
nuttx/libs/libxx/libcxx/src/memory_resource_init_helper.h:2:8: error: ‘constinit’ does not name a type
2 | static constinit ResourceInitHelper res_init _LIBCPP_INIT_PRIORITY_MAX;
|        ^~~~~~~~~
nuttx/libs/libxx/libcxx/src/memory_resource_init_helper.h:2:8: note: C++20 ‘constinit’ only available with ‘-std=c++20’ or ‘-std=gnu++20’
``` …
=> libcxx: Fix CMake compile with correct CMAKE_CXX_STANDARD

arch/arm/src/common/arm_exit.c, arch/avr/src/common/avr_exit.c, arch/hc/src/common/hc_exit.c, arch/mips/src/common/mips_exit.c, arch/misoc/src/lm32/lm32_exit.c, arch/misoc/src/minerva/minerva_exit.c, arch/or1k/src/common/or1k_exit.c, arch/renesas/src/common/renesas_exit.c, arch/risc-v/src/common/riscv_exit.c, arch/sim/src/sim/sim_exit.c, arch/sparc/src/common/sparc_exit.c, arch/x86/src/common/x86_exit.c, arch/x86_64/src/common/x86_64_exit.c, arch/xtensa/src/common/xtensa_exit.c, arch/z16/src/common/z16_exit.c, arch/z80/src/common/z80_exit.c
the log duplciates with the one in `sched/task_exit.c`
debugging logs
checked on rv-virt/nsh
=> arch/: remove duplicated task exit logging

arch/risc-v/src/cmake/Toolchain.cmake
1. risc-v/cmake: set llvm cputype only for LLVM based toolchain
```
remove LLVM_CPUTYPE from compile line
set llvm cputype only for LLVM based toolchain to avoid build break:
riscv64-unknown-elf-gcc: error: unrecognized command-line option '-mcpu=sifive-u54'
```
2. risc-v/cmake: configurable vendor ISA extensions
```
merge below commit into cmake:
1. risc-v/toolchain: configurable vendor ISA extensions
This option allows the platform to enable some vendor-customized ISA extensions,
E.g OpenHW, SiFive, T-Head.
SiFive Intelligence Extensions:
SiFive Vector Coprocessor Interface(VCIX): xsfvcp
SiFive FP32-to-int8 Ranged Clip Instructions: Xsfvfnrclipxfqf
SiFive Matrix Multiply Accumulate Instructions: Xsfvfwmaccqqq
SiFive Int8 Matrix Multiplication Instructions: XSFvqmaccqoq
Command Line: …
```
=> risc-v/cmake: set llvm cputype only for LLVM based toolchain

arch/xtensa/src/esp32s3/esp32s3_otg_device.c
ESP32-S3 USB OTG device can't call function esp32s3_pullup to notify USB host that it connects or disconnects.
=> xtensa/esp32s3: Fix USB pull-up and pull-down issue

fs/romfs/fs_romfs.h
which could save 4 bytes for each node
minor
internal test
=> fs/romfs: Move rn_child/rn_count before rn_namesize

arch/arm/src/sama5/sam_ehci.c
The logic of the conditional expression that determines whether the QH is a target QH or not is reversed in the process of canceling a transfer in INPROGRESS state.
Therefore, the QH in INPROGRESS state is not released and subsequent communication is not successful.
Checked with CDC-ACM driver and cu command.
=> arm: sama5: sam_ehci: fix transfer cancellation process.

arch/arm/src/stm32h7/stm32_serial.c
See https://github.com/PX4/PX4-Autopilot/issues/22599 for additional details.
If a TX DMA completion interrups a forground write.
The TX DMA completion can start a dma_send and it will
then followed by the forground write's dma_send
stoping the,then in progress DMA.
By atomicaly marking the tx dma busy, the forground
write will not perform the dma_send, and will only
enqueue the data. At the next TX dma completion any
data pending in the tx queue will be sent
Without this change, the TX could hang. 
See https://github.com/PX4/PX4-Autopilot/issues/22599#issuecomment-1900324175
px4_fmu-v6x and Mavlink
=> stm32h7:serial make TX DMA busy when there are an outstanding transaction

arch/risc-v/src/cmake/Toolchain.cmake, arch/risc-v/src/cmake/platform.cmake
Ubuntu stock toolchain complains about current CMake scripts.  This patch revises risc-v/cmake logic so that users of stock toolchain users can enjoy CMake system.
The change doesn't affect XPack toolchain uses and can fix issue #11573
risc-v cmake toolchain users
checked with `rv-virt/nsh(64` for both XPack and stock toolchain.
=> risc-v/cmake: add support for Ubuntu stock toolchain

arch/xtensa/include/esp32s3/irq.h, arch/xtensa/src/esp32s3/esp32s3_dma.h, arch/xtensa/src/esp32s3/esp32s3_spi.c
Fix esp32s3 spi dma transfer.
Fix esp32s3 spi dma transfer only transmit first byte and receive empty problem.
Base config: esp32s3-devkit:spi  
Changes: 
```
CONFIG_DEBUG_FEATURES=y
CONFIG_DEBUG_SPI=y
CONFIG_DEBUG_SPI_ERROR=y
CONFIG_DEBUG_SPI_INFO=y
CONFIG_DEBUG_SPI_WARN=y
CONFIG_ESP32S3_SPI2_CLKPIN=2
CONFIG_ESP32S3_SPI2_CSPIN=1
CONFIG_ESP32S3_SPI2_MISOPIN=41
CONFIG_ESP32S3_SPI2_MOSIPIN=42
CONFIG_ESP32S3_SPI3_CLKPIN=13
CONFIG_ESP32S3_SPI3_CSPIN=11
CONFIG_ESP32S3_SPI3_MISOPIN=12
CONFIG_ESP32S3_SPI3_MOSIPIN=14
CONFIG_ESP32S3_SPI_DMA=y
CONFIG_ESP32S3_SPI_DMATHRESHOLD=4
```
defconfig after edit : 
``` 
#
#
#
CONFIG_ARCH="xtensa"
CONFIG_ARCH_BOARD="esp32s3-devkit"
CONFIG_ARCH_BOARD_COMMON=y
CONFIG_ARCH_BOARD_ESP32S3_DEVKIT=y
CONFIG_ARCH_CHIP="esp32s3"
CONFIG_ARCH_CHIP_ESP32S3=y …
```
=> esp32s3/spi-dma: Fix spi dma transfer.

drivers/ioexpander/Kconfig, drivers/ioexpander/Make.defs, drivers/ioexpander/icjx.c, drivers/ioexpander/icjx.h, include/nuttx/ioexpander/icjx.h
This commit adds basic support for iC-JX expander in SPI mode. The expander is functional and supports both input and output pins.
There are still some more advance functionalities (filtering, adc, interrupt support) that are not implemented but I probably do not plan implementing. So I am sending this in basic variant, maybe someone in the future will follow up.
New expander.
Tested with custom SAMv7 board.
=> ioexpander: add support for iC-JX expander

Documentation/platforms/arm/samv7/index.rst, arch/arm/src/samv7/Kconfig, arch/arm/src/samv7/Make.defs, arch/arm/src/samv7/sam_serial_spi.c, arch/arm/src/samv7/sam_serial_spi.h
USART peripheral can work in SPI mode as well. This commit adds support for such functionality. Only 1 slave device is supported by the peripheral therefore board level does not have to ensure correct CS setup.
The usage of the peripheral is the same as with other SPI drivers.
New feature for SAMv7
Tested on custom board with SAMv7 MCU.
=> samv7: add support for SPI mode in USART peripheral

drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.c
Avoid incorrect NIC flag Settings
Cortex-M33 and bcm43xxx Wi-Fi chip
=> bcmf_driver:wlan interface status reset by unsolicited wpa packet

drivers/rpmsg/rpmsg.c, drivers/rptun/rptun.c, fs/rpmsgfs/rpmsgfs_server.c, include/nuttx/rpmsg/rpmsg.h
rpmsgfs: decoupling rpmsgfs server and rpmsg virtio.
create a new general api to make rpmsgfs work with virtio/spi/uart transport.
tested in sim vela and 86panel.
=> rpmsgfs: decoupling rpmsgfs server and rpmsg virtio.

arch/risc-v/src/mpfs/mpfs_corespi.c
After warm reset the interrupt source in the HW block is not explicitly cleared, thus once the interrupt source is enabled the old / stale interrupt fires immediately.
This causes a DEBUGASSERT() failure on line 808 mpfs_spi_unload_rx_fifo:
DEBUGASSERT(nwords > 0);
Fix minor bug, MPFS only
MPFS
=> mpfs_corespi: Fix firing of stale interrupt after warm reset

arch/arm/src/samv7/Kconfig
Commit 03e5c02 introduced option to have both standard SPI and QSPI in SPI mode on one system. However this change broke the appearance of QSPI driver configuration menu entry in menuconfig as it was dependent on `!SAMV7_QSPI_IS_SPI` (which is now true for all MCUs having standard SPI ability in QSPI driver).
This change makes sure the menu is correctly shown when QSPI driver used.
Just menuconfig
Menuconfig now shows the menu when it should.
=> samv7: fix QSPI DMA option not showing in menuconfig

drivers/rpmsg/rpmsg.c, drivers/rptun/rptun.c, include/nuttx/rpmsg/rpmsg.h
Ioctl is commom part in rpmsg, so extract rptun char to rpmsg/rpmsg.c.
The frameworks of rpmsg and rptun are clearer.
Tested in sim vela and 86 panel.
=> rptun: extract rptun char to rpmsg/rpmsg.c

tools/nxstyle.c
tools/nxstyle: can use ',' in the string when declaring it
code style check
velaos
=> tools/nxstyle: can use ',' in the string when declaring it

arch/xtensa/src/esp32s3/esp32s3_spi.c
- Add DMA peripheral to spi driver configuration
=> xtensa/esp32s3: Add DMA peripheral to spi driver configuration

arch/sim/src/sim/CMakeLists.txt
fix X11 compile failed with CMake
N/A
N/A
=> arch/sim: fix X11 compile failed

arch/risc-v/src/k230/CMakeLists.txt, boards/risc-v/k230/canmv230/CMakeLists.txt, boards/risc-v/k230/canmv230/src/CMakeLists.txt
Adding CMakeLists.txt files to support CMake build system. Note that only FLAT build works now due to limitations of current CMake build system.
None
checked with 'canmv230/nsh`
=> risc-v/canmv230: add CMake support

arch/risc-v/include/csr.h
This adds defintions for VS (vector extension) and XS (additional user-mode extension) fields for MSTATUS and SSTATUS registers.
None
Checked with canmv230
=> arch/risc-v: add status fields for VS and XS

drivers/wireless/ieee802154/mrf24j40/Kconfig, drivers/wireless/ieee802154/mrf24j40/mrf24j40.h
-  mrf24j40/Kconfig: add missing IEEE802154_MRF24J40_FREQUENCY option
-  mrf24j40: always use SPI MODE(0,0)
Other SPI modes are not supported. From doc:
"The MRF24J40 supports SPI (mode 0,0) which requires
that SCK idles in a low state."
=> mrf24j40: minor fixes

arch/arm/src/nrf52/nrf52_tim.c, arch/arm/src/nrf53/nrf53_tim.c, arch/arm/src/nrf91/nrf91_tim.c
arch/{nrf52|nrf53|nrf91}/tim.c: fix typo
fix offset for EVENT COMPARE0
=> arch/{nrf52|nrf53|nrf91}/tim.c: fix typo

Documentation/applications/nsh/commands.rst
1. Documentation: add `-h` option description for ls command
- Reference: https://github.com/apache/nuttx-apps/pull/1821
2. Documentation: add `uptime` command description
- Reference: https://github.com/apache/nuttx-apps/pull/1319
3. Documentation: add `expr` command description
- Reference: https://github.com/apache/nuttx-apps/pull/2268
4. Documentation: add `-u` and `+%format` description for date command
- Reference:
- https://github.com/apache/nuttx-apps/pull/745
- https://github.com/apache/nuttx-apps/pull/2273
Documentation only.
=> Documentation: update some command descriptions

boards/arm/gd32f4/gd32f450zk-eval/src/Makefile, boards/arm/gd32f4/gd32f450zk-eval/src/gd32f450z_eval.h, boards/arm/gd32f4/gd32f450zk-eval/src/gd32f4xx_appinit.c, boards/arm/gd32f4/gd32f450zk-eval/src/gd32f4xx_boot.c, boards/arm/gd32f4/gd32f450zk-eval/src/gd32f4xx_bringup.c, boards/arm/gd32f4/gd32f470ik-eval/src/Makefile, boards/arm/gd32f4/gd32f470ik-eval/src/gd32f470i_eval.h, boards/arm/gd32f4/gd32f470ik-eval/src/gd32f4xx_appinit.c, boards/arm/gd32f4/gd32f470ik-eval/src/gd32f4xx_boot.c, boards/arm/gd32f4/gd32f470ik-eval/src/gd32f4xx_bringup.c, boards/arm/gd32f4/gd32f470zk-eval/src/Makefile, boards/arm/gd32f4/gd32f470zk-eval/src/gd32f470z_eval.h, boards/arm/gd32f4/gd32f470zk-eval/src/gd32f4xx_appinit.c, boards/arm/gd32f4/gd32f470zk-eval/src/gd32f4xx_boot.c, boards/arm/gd32f4/gd32f470zk-eval/src/gd32f4xx_bringup.c
modified the execution logic of the board_late_initialize()，bringup(), which is consistent with the stm32 series.
Changed the initialization process for onboard peripherals
The GD32F450ZGT6 development board is normal
=> driver/gd32f4:modified the execution logic of the board_late_initialize()，bringup(), which is consistent with the stm32 series.

drivers/serial/serial.c, fs/vfs/fs_lseek.c, libs/libc/stdio/lib_fopen.c, libs/libc/string/lib_strcasestr.c, libs/libc/unistd/lib_getopt_common.c, libs/libc/wctype/lib_iswctype.c
compiler/tasking: fix unreachable code on tasking toolchain
```
ctc W544: ["serial/serial.c" 284/3] unreachable code
ctc W544: ["vfs/fs_lseek.c" 96/13] unreachable code
ctc W544: ["wqueue/kwork_thread.c" 210/32] unreachable code
ctc W544: ["stdio/lib_fopen.c" 327/19] unreachable code
ctc W544: ["stdio/lib_fopen.c" 404/13] unreachable code
ctc W544: ["string/lib_strcasestr.c" 120/3] unreachable code
ctc W544: ["unistd/lib_getopt_common.c" 156/21] unreachable code
ctc W544: ["unistd/lib_getopt_common.c" 216/21] unreachable code
ctc W544: ["wctype/lib_iswctype.c" 155/3] unreachable code
```
N/A
Tricore / Aurix Tasking TC397
=> compiler/tasking: fix unreachable code on tasking toolchain

drivers/sensors/bmi160.c
Remove warning due to variable type difference in format.
None
Build check
=> drivers/sensor: delete warning about argument type in bmi160

drivers/serial/serial.c, fs/inode/fs_inodesearch.c, libs/libc/obstack/lib_obstack_malloc.c, mm/map/mm_map.c
compiler/tasking: fix compiler warning on tasking
```
ctc W549: ["serial/serial.c" 877/37] condition is always true
ctc W549: ["inode/fs_inodesearch.c" 72/8] condition is always true
ctc W545: ["obstack/lib_obstack_malloc.c" 69/1] missing 'return'
ctc W545: ["obstack/lib_obstack_malloc.c" 82/1] missing 'return'
ctc E246: ["map/mm_map.c" 67/41] left side of '.' or '->' is not struct or union
ctc E260: ["map/mm_map.c" 67/25] not an lvalue
ctc E246: ["map/mm_map.c" 80/3] left side of '.' or '->' is not struct or union
ctc E260: ["map/mm_map.c" 80/3] not an lvalue
```
N/A
Tricore / Aurix Tasking TC397
=> compiler/tasking: fix compiler warning on tasking

include/nuttx/rpmsg/rpmsg_ping.h, include/nuttx/rptun/rptun.h
rptun: remove temporarily retained RPTUNIOC_xxx definitions.
remove temporary codes to make the code more concise.
tested in sim vela and 86 panel.
=> rptun: remove temporarily retained RPTUNIOC_xxx definitions.

arch/Kconfig
The RPTUN_PING option has been replaced by RPMSG_PING but this use for PERF_EVENTS is left behind, so replace it here as well.
PERF_EVENTS use cases
CI.
=> arch/Kconfig: replace RPTUN_PING with RPMSG_PING

arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_coremmc.c, arch/risc-v/src/mpfs/mpfs_coremmc.h, arch/risc-v/src/mpfs/mpfs_emmcsd.c, arch/risc-v/src/mpfs/mpfs_sdio.c, arch/risc-v/src/mpfs/mpfs_sdio.h, arch/risc-v/src/mpfs/mpfs_sdio_dev.h, boards/risc-v/mpfs/common/src/mpfs_emmcsd.c
Additional mpfs_sdio layer on top of mpfs_emmcsd and mpfs_coremmc block device drivers to let both block devices be enabled at the same time.
```
board_init ---> mpfs_sdio_dev ---+----> mpfs_coremmc
|
+----> mpfs_emmcsd
```
mpfs mmcsd block device drivers
mount sd-card / emmc
=> arch/risc-v/mpfs: wrapper for sdio device drivers

boards/risc-v/qemu-rv/rv-virt/src/qemu_rv_appinit.c
* This commit add mount point for tmpfs in the
board_app_initialize function.
* Don't mount procfs if it is not enabled in the kernel configuration.
rv-virt only, minor
CI
=> rv-virt: Guard mount point for procfs/tmpfs

include/threads.h
Fix typo in `mtx_timedlock` define: `pthread_mutex_timedwait` → `pthread_mutex_timedlock`.
None
Manual testing, linker error is gone
=> Fix typo in mtx_timedlock

arch/arm/src/armv7-a/CMakeLists.txt, arch/arm/src/armv7-a/Make.defs, arch/arm/src/armv7-a/arm_addrenv_pgmap.c, arch/risc-v/src/common/riscv_addrenv_pgmap.c, fs/shm/shmfs_alloc.c, include/nuttx/arch.h
When shmfs_truncate is called, it uses shmfs_alloc_object to create the
physical backing for the shm file. However, the allocated physical
memory returned by mm_pgalloc is not cleared when CONFIG_BUILD_KERNEL is
set, which is a clear POSIX violation:
https://pubs.opengroup.org/onlinepubs/9699919799/functions/truncate.html
"If the file was previously shorter than length, its size is increased,
and the extended area appears as if it were zero-filled."
For FLAT and PROTECTED modes zalloc is used, so the violation affects
KERNEL mode only.
Fix shmfs_truncate
MPFS + shmfs + kernel mode
=> fs/shmfs: Fix shmfs_truncate

fs/shm/shmfs.c, fs/vfs/fs_stat.c, include/nuttx/fs/fs.h
Fixes stat() system call for shmfs objects
fstat() now works as expected
mpfs + kernel mode with shmfs
=> fs/shmfs: Fix stat() system call for shmfs object

.gitignore, fs/fat/fs_fat32.h
The `DIRSEC_BYTENDX(f, i)` is supposed to have `DIRSEC_NDXMASK(f)` in its expansion instead of `DIRSEC_NDXMASK(fs)`. It went unnoticed in the codebase as `DIRSEC_BYTENDX(fs, idx)` is the way it is used, and it leads to a similar expansion as desired, and thus it has worked till now without any issues from this.
fs/vfat: Fix typo in the macro DIRSEC_BYTENDX
None
Build and Checkpatch
=> fs/vfat: Fix typo in the macro DIRSEC_BYTENDX

arch/risc-v/src/bl808/bl808_mm_init.c, arch/risc-v/src/common/riscv_mmu.h
Current mmu_flush_cache() hook lacks the `reg` param which is needed by some targets. So this PR adds the param and update existing targets using that hook.
bl808 devices
Build passes for `ox64/nsh`.
=> risc-v/common: add param to mmu_flush_cache interface

net/rpmsg/rpmsg_sockif.c
to align with the naming convention of getpeername.
no public side effect
ci
=> net/rpmsgsock: Rename rpmsg_socket_getconnname to rpmsg_socket_getpeername

Documentation/platforms/arm/rp2040/index.rst, arch/arm/src/rp2040/Kconfig, arch/arm/src/rp2040/rp2040_clock.c, arch/arm/src/rp2040/rp2040_gpio.h, boards/arm/rp2040/common/src/rp2040_common_initialize.c
Support clock output to GPIO. Can be used to clock external devices or debug on chip clocks with a logic analyser or oscilloscope.  RP2040 supports 4 clock outputs to pins 21, 23, 24, and 25.  See datasheet for clock sources and divider options.
Configured via Kconfig and initialized at boot.
Should not impact existing functionality.
Configure clock outputs and test with oscilloscope.
=> RP2040: Support Clock Outputs

boards/arm/cxd56xx/common/src/cxd56_alt1250.c, boards/arm/cxd56xx/spresense/src/cxd56_alt1250_power.c
Since there were some cases in which the current modem reset sequence did not reset the modem, the reset was ensured by executing power off and power on of the modem.
Only ALT1250 driver.
=> boards/arm/cxd56xx: Fix the modem reset sequence

arch/risc-v/src/mpfs/mpfs_i2c.c
This is a collection of corrections for MFPS i2c driver from TII repositories.
Correct some issues with concurrent bus access and stabilize i2c in different various error conditions
Tested on an MPFS250 based HW, where several i2c devices are connected to the same bus
=> Mpfs i2c fixes

boards/arm/stm32u5/nucleo-u5a5zj-q/CMakeLists.txt, boards/arm/stm32u5/nucleo-u5a5zj-q/src/CMakeLists.txt
CMake: arm/stm32u5: init stm32u5 cmake build
Test cmake build on nucleo-u5a5zj-q:
```
$ cmake -B build -DBOARD_CONFIG=nucleo-u5a5zj-q:nsh -GNinja
```
N/A
ci check
=> cmake: Fixed nucleo-u5a5zj-q

arch/arm/src/samv7/Make.defs, arch/arm/src/samv7/sam_systemreset.h, boards/arm/samv7/common/src/Make.defs, boards/arm/samv7/common/src/sam_reset.c
SAMv7 reset controller stores the cause of last reset in status register. These commits add function that allows the board to retrieve this information. This function should be called from board support layer either during initialization or based on incoming ioctl call (implemented in second commit).
Adding the `sam_get_reset_cause()` to `sam_systemreset.c` also resulted in always compiling this file by default and only putting `up_systemreset()` under `CONFIG_SAMV7_SYSTEMRESET` option.
Also header file `sam_systemreset.h` was created as it defines reset types in comfortable manner for future processing in board layer. This is done to avoid passing `boardctl` dependent structure to architecture layer.
New feature for SAMv7.
Tested on EVK board (only with power up, SW reset and pin reset …
=> samv7: add support for BOARDIOC_RESET_CAUSE command

arch/avr/include/avr32/types.h, boards/avr/at32uc3/avr32dev1/include/board.h, boards/avr/at32uc3/avr32dev1/scripts/avr32dev1.ld, libs/libc/assert/Make.defs
Dear NuttX community, Greetings!
I recently imported NuttX version 6.0 (and nsh) into a Microchip
Studio project [1] on Windows to figure out what was going wrong with
the avr32dev1 build. I also briefly checked NuttX version 10.
I worked with the assumption that the avr32 (avr32dev1) specific
changes to the codebase were minimal across NuttX releases.
For the initial proof of concept I used Microchip Studio version 7.0
(with the recent Microchip's ASF updates). I use avr32-gcc (4.4.7)
hosted here [2] for building NuttX for avr32dev1 on GNU/Linux.
Even with the Microchip Studio project, I had initial debug problems
with just stepping through the code a line at a time. I had to bring
in crt0, a trampoline stub and the linker file from one of my older
projects to really build on the …
=> avr32dev1: Fix compilation and nsh boot-up

drivers/rpmsg/rpmsg_ping.c
rpmsg_ping.c is blocking CI checks for RPTUN related patches like #11673. this patch simply fix the compilation issue of rpmsg_ping.c:
- line 191: overflow conversion from "long unsigned int" to "unsigned int"
- line 226: "sendlen" used uninitialized
Ths is to unblock RPTUN/RPMSG related pull requests
build check
=> rpmsg/rpmsg_ping: fix CI check issues

fs/mount/fs_mount.c
It seems that RPMSGFS is missed from the list that doesn't need block or MTD drivers. This attempts to add it.
None
Checked on CanMV230
=> fs/mount: add FS_RPMSGFS as cause of NODFS_SUPPORT

arch/xtensa/src/esp32s2/esp32s2_wdt.c, arch/xtensa/src/esp32s2/hardware/esp32s2_tim.h
ESP32S2 MWDT interrrupt trigger bugfix
Only ESP32S2
`esp32s2-saola-1:watchdog` config with customized irq handler added wdog example.
=> xtensa/esp32s2: Fix esp32s2 wdt interrupt bug

drivers/rptun/rptun.c
This patch add explicit initialization for variable `onceinit` before use.
RPTUN driver use cases, should be none as it is a minor improvement.
=> rptun/rptun_initialize: add explicit initialization for variable

Documentation/quickstart/compiling_cmake.rst
I used
··
cd nuttx
cmake -B build -DBOARD_CONFIG=stm32f401rc-rs485:nsh -GNinja
··
to config
and when following the instruction in this official websites I found the command to use cmake to build the target is wrong.
which is "cmake --build build -t menuconfig" also wrong the output dir "build/nuttx".
and by the way, In my practice I find the bin file and elf file is not in build/nuttx but in build/. So I changed these. But I'm not 100% sure that my fix is right as I'm a beginner, but what I fix works fine in my computer. This is my first PR to the public doc. My fix maybe totally wrong as I am not get into the nuttx, just following the instruction and encountered some mistakes.
thx for reviewing
=> fix typo error in quickstart compiling_cmake

tools/ci/testlist/sim-01.dat
This config failes CI check on `MacOS(sim-01)` in the past week. It blocks multiple PRs. This patch disables it tenatively so that to unblock PRs. 
The error looks like:
```
Error: /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach/vm_page_size.h:59:44: error: expected ';' after top level declarator
```
This issue blocks #11684, #11691 and once blocked  #11673, #11681 etc.
CI checks
CI check
=> citest/sim01: disable libcxxtest on macOS to unblock CI checks

arch/risc-v/src/k230/k230_hart.c, arch/risc-v/src/k230/k230_hart.h, boards/risc-v/k230/canmv230/scripts/ld-kernel.script
This patch revises `k230_hart.[ch]` by:
- revising big core boot and stop functions.
- making k230_hart_is_big() available in S-mode.
- adding more comments.
This patch also revises the `ld-kernel.script` so that to match the latest pgtable design.
k230 based devices
checked with CanMV230
=> risc-v/k230: revise k230 hart operations and kernel linker script.

Kconfig, include/debug.h
This patch adds debug macros for RPTUN/RPMSG related debug logging.
None
CI checks
=> rpmsg/debug: add debug configs and macros

arch/arm/src/stm32/stm32_pwm.c, arch/arm/src/stm32f7/stm32_pwm.c, arch/arm/src/stm32h7/stm32_pwm.c
Clear all PWM channel when STOP command is executed
I noticed when executing pwm STOP command in
multichannel mode, the channel still outputting.
This commit fixes this issue.
Now the PWM will stop correctly
stm32f4discovery
=> Fix STM32xx PWM STOP in multichannel mode

libs/libxx/0001-libcxx-remove-mach-time-h.patch, libs/libxx/libcxx.cmake, libs/libxx/libcxx.defs, tools/ci/testlist/sim-01.dat
Inclusion of `mach/mach_time.h` by `libcxx/src/chrono.cpp` breaks the build on latest MACOS dues to https://forums.developer.apple.com/forums/thread/746737. The interface from `mach/mach_time.h` is not referenced in `chrono.cpp` so it is safe to remove it
Get back sim:libcxxtest to GitHub CI
Pass CI
=> citest/sim01: fix sim:libcxxtest on macOS

drivers/rpmsg/rpmsg_ping.c
since clock_t may map to either 32-bit or 64-bit integer type, UINT_MAX may not be the maximum value of clock_t.
rpmsg ping
ci
=> rpmsg/ping: Replace UINT_MAX with CLOCK_MAX

arch/arm/src/nrf52/nrf52_rtc.h, arch/arm/src/nrf53/nrf53_rtc.h, arch/arm/src/nrf91/nrf91_rtc.h
- arch/arm/src/nrf{52|53|91}/xxx_rtc.h: include nuttx/irq.h
fixes undefined xcpt_t error that sometimes occurs
=> arch/arm/src/nrf{52|53|91}/xxx_rtc.h: include nuttx/irq.h

drivers/wireless/ieee802154/mrf24j40/mrf24j40_radif.c
mrf24j40: add support for IEEE802154_ATTR_PHY_REGDUMP
=> mrf24j40: add support for IEEE802154_ATTR_PHY_REGDUMP

libs/libc/assert/Make.defs, mm/kasan/Make.defs
toolchain/lto: enable lto flags only on GNU toolchain
Some commercial customized toolchains do not support these options
N/A
Tasking toolchain
=> toolchain/lto: enable lto flags only on GNU toolchain

drivers/virtio/virtio-mmio.c, drivers/virtio/virtio.c
Only call metal_init() once for virtio framework
Should be none
CI
=> virtio: move metal_init to the virtio_register_drivers()

arch/x86_64/src/common/Toolchain.defs, arch/x86_64/src/common/x86_64_initialize.c, arch/x86_64/src/common/x86_64_internal.h, arch/x86_64/src/intel64/Toolchain.defs, boards/x86_64/intel64/qemu-intel64/src/qemu_net.c
Commit 1:
Support config CONFIG_NETDEV_LATEINIT FOR X64_64
Commit 2:
intel64: move toolchain releated option to Toolchain.defs
Only code refactor, should be none
qemu-intel64:nsh
=> x86/x86_64: move common toolchain options to Toolchain.defs

boards/Kconfig, boards/arm/rp2040/raspberrypi-pico/include/board.h, boards/arm/rp2040/raspberrypi-pico/src/Make.defs, boards/arm/rp2040/raspberrypi-pico/src/rp2040_autoleds.c, boards/arm/rp2040/raspberrypi-pico/src/rp2040_bringup.c, boards/arm/rp2040/raspberrypi-pico/src/rp2040_pico.h, boards/arm/rp2040/raspberrypi-pico/src/rp2040_userleds.c
This commit adds support to autoleds and userleds for raspberrypi-pico board.
It uses the board LED connected to GPIO 25.
Users will be able to use the LED of raspberrypi pico
raspberrypi pico
=> boards/raspberrypi-pico: Add autoleds and userleds support

drivers/rpmsg/rpmsg.c, drivers/rptun/rptun.c, include/nuttx/fs/ioctl.h, include/nuttx/rpmsg/rpmsg.h, include/nuttx/rptun/rptun.h
rptun ioctl: Strip rpmsg ioctl and rptun ioctl.
need be merged together with https://github.com/apache/nuttx-apps/pull/2290.
rptun ioctl only handle RPTUNIOC_START, RPTUNIOC_STOP, RPTUNIOC_RESET, rpmsg ioctl handles the public ioctl commands part.
tested in sim vela.
=> rptun ioctl: Strip rpmsg ioctl and rptun ioctl.

arch/Kconfig, include/nuttx/compiler.h, tools/Config.mk, tools/incdir.c, tools/mkdeps.c
toolchain/tasking: add dependencies rules for tasking compiler
Tasking compiler uses customized compilation options for generating dependencies files
N/A
Tasking
=> toolchain/tasking: add dependencies rules for tasking compiler 

fs/fat/fs_fat32.c
When issuing an ioctl for a file that exists in a FAT32 file system, the FAT ioctl() is first executed, but it returns -ENOSYS in an attempt to pass through to the vfs.
Therefore, the ioctl of the VFS layer, which expects -ENOTTY, is not processed and an error occurs.
Nim file operations (write file to FAT filesystem) on NuttX.
=> fs: fat: fs_fat32: fix default return value of fat_ioctl().

Documentation/Makefile, Documentation/components/filesystem/fat.rst, Documentation/components/filesystem/index.rst, Documentation/known-warnings.txt, Documentation/reference/os/notifier.rst, fs/vfs/fs_syncfs.c
This commit adds VFS documentation, and details about the VFS interface.
Adds VFS docs.
Fixes small typo in VFAT docs.
Adds warnings-as-errors and warning-filter to sphinx-autobuild.
VFS Docs.
Sphinx build. Had some warnings for "duplicate declaration" of C functions, but it was necessary here as the additions explain VFS interface methods as well.
=> fs: Add VFS docs

include/nuttx/rpmsg/rpmsg.h
include/rpmsg/rpmsg.h: remove temporary define RPMSGIOC_START, RPMSGIOC_STOP, RPMSGIOC_RESET
remove temporary code.
tested in sim vela
=> include/rpmsg/rpmsg.h: remove temporary define 

arch/arm/src/cmake/platform.cmake, arch/risc-v/src/cmake/platform.cmake
cmake/toolchain: fix compiler warning on ARM32
```
-- Detecting CXX compile features
-- Detecting CXX compile features - done
arm-none-eabi-gcc: error:  -Wstrict-prototypes: No such file or directory
arm-none-eabi-gcc: error:  -Wstrict-prototypes: No such file or directory
-- Configuring done
-- Generating done
```
N/A
sabre-6quad/nsh
=> cmake/toolchain: fix compiler warning on ARM32

cmake/nuttx_add_library.cmake
when NuttX's CMake build system calls an external module that already supports CMake,
since `add_library` may have been called internally,
it needs to provide a way to add its internally defined target to the final link.
Usually used with Nuttx to include an external system that already supports CMake compilation
for example:
```CMake
add_subdirectory(${LVGL_CMAKELIST_DIR})
target_compile_options(lvgl PRIVATE ${CFLAGS})
nuttx_add_external_library(lvgl)
```
enhancement
no effect
CI
=> cmake:add target that define in external moduleCMakeLists.txt

fs/littlefs/CMakeLists.txt, fs/littlefs/Make.defs, fs/littlefs/lfs_getpath.patch, fs/littlefs/lfs_vfs.c
Add FIOC_FILEPATH to LFS ioctl
LFS ioctl adds FIOC_FILEPATH for file paths
local test PASS
=> fs/littlefs: Add to get the full path

fs/procfs/fs_procfsmeminfo.c, include/assert.h, mm/mm_heap/mm_foreach.c, mm/mm_heap/mm_mallinfo.c, mm/mm_heap/mm_memdump.c, sched/init/nx_bringup.c, sched/sched/sched_removeblocked.c
assert: change the do-while of assert to a conditional expression
According to the standard definition, assert should return a void expression
https://pubs.opengroup.org/onlinepubs/007904875/basedefs/assert.h.html
This patch involves two changes:
If you define the NDEBUG macro, assert does not use any parameters and directly returns a void expression.
assert should return a void expression and cannot use do-while statements.
If the following code , a compilation error will occur.
sim
=> assert: change the do-while of assert to a conditional expression

drivers/rptun/rptun.c, include/nuttx/rptun/rptun.h
In the previous patch, we moved rptun_panic and rptun_dump_all in rptun to rpmsg. In order to ensure CI pass, this two API in rptun is not removed. so we remove rptun_panic and rptun_dump_all in this patch.
remove redundant code.
tested in sim vela.
=> rptun ioctl: remove rptun_panic and rptun_dump_all

arch/x86_64/CMakeLists.txt, arch/x86_64/src/CMakeLists.txt, arch/x86_64/src/cmake/Toolchain.cmake, arch/x86_64/src/cmake/platform.cmake, arch/x86_64/src/common/CMakeLists.txt, arch/x86_64/src/intel64/CMakeLists.txt, boards/x86_64/intel64/qemu-intel64/CMakeLists.txt, boards/x86_64/intel64/qemu-intel64/src/CMakeLists.txt, libs/libc/machine/x86_64/CMakeLists.txt, libs/libc/machine/x86_64/Kconfig
arch/x86_64: add cmake support
qemu and intel64 hardware
=> arch/x86_64: add cmake support

arch/arm/src/stm32/stm32f30xxx_rcc.c
During removal of F1 related stuff, code that configures FLASH latency was removed, which rendered some of the F3 line unbootable.
It was done by mistake, since previous removed block was '#ifdef VALUE_LINE', and block with FLASH code was '#ifndef VALUE_LINE' and so it should not have been removed.
This partially reverts: b2399850375a452932bdf5c9f107be51d6d80237
Probably whole stm32f3 line
Tested on nucleof303re
=> stm32/stm32f30xxx_rcc.c: fix broken flash setup

net/pkt/Kconfig, net/pkt/pkt.h, net/pkt/pkt_conn.c, net/pkt/pkt_input.c, net/pkt/pkt_sockif.c
We're using the `sll_ifindex` inside `struct sockaddr_ll` to bind device, so we don't need to translate it into mac address, we can just match the index, which also let us bind to different type of devices other than Ethernet.
Ref: Linux also uses `ifindex` to find related device and note it down without mac addresses.
https://man7.org/linux/man-pages/man7/packet.7.html
https://github.com/torvalds/linux/blob/v6.7/net/packet/af_packet.c#L3328
https://github.com/torvalds/linux/blob/v6.7/net/packet/af_packet.c#L3264-L3265
Bind and input logic of packet socket.
Together with tcpdump https://github.com/apache/nuttx-apps/pull/2303, capturing both TUN and ETH.
=> net/pkt: Support binding to devices other than ETH

Documentation/platforms/risc-v/k230/boards/canmv230/index.rst, boards/risc-v/k230/canmv230/src/canmv_init.c
This patch update documents to reflect the fact that remote node is kicked off by master node. It also adds debug dump to aid the MISA reading issue investigation.
K230
=> risc-v/k230: update AMP related document

net/icmpv6/icmpv6_autoconfig.c, net/pkt/pkt_sendmsg.c
Fix minor problems when reading codes:
- `icmpv6_autoconfig`: Call `net_unlock` before return
- `pkt_sendmsg`: Return error for types other than `SOCK_RAW`
Minor, `icmpv6_autoconfig` and `pkt_sendmsg`
CI
=> net: Fix minor coding problems

fs/procfs/fs_procfsversion.c
Currently at runtime it is hard to know the exact build config of the current NuttX instance. Thus it is inconvenient when there are multiple configs for the same board. This patch attempts to solve the issue by adding build config to /proc/version.
/proc/version content
checked with CanMV230 and sim/nsh
=> fs/procfs: add build config to /proc/version

arch/x86_64/Kconfig, arch/x86_64/include/intel64/arch.h, arch/x86_64/src/intel64/CMakeLists.txt, arch/x86_64/src/intel64/Make.defs, arch/x86_64/src/intel64/intel64_systemreset.c, boards/x86_64/intel64/qemu-intel64/src/CMakeLists.txt, boards/x86_64/intel64/qemu-intel64/src/Makefile, boards/x86_64/intel64/qemu-intel64/src/qemu_reset.c
arch/intel64: add software reset support
qemu and intel64
=> arch/intel64: add software reset support

arch/x86_64/src/cmake/platform.cmake, libs/libm/newlib/0003-newlib-fix-compilation-for-x86.patch, libs/libm/newlib/CMakeLists.txt, libs/libm/newlib/Make.defs, libs/libm/newlib/sincosl.c
- newlib: fix support for x86
- newlib: fix compilation for sincosl
aggresive optimisation can replace occurrences of sinl() and cosl() with
sincosl(), but sincosl() is missing in newlib which causes error. So let's
use custom implementation here
alternative libm for x86_64
qemu
=> newlib: fix support for x86_64

arch/Kconfig, arch/x86_64/include/intel64/irq.h, arch/x86_64/src/intel64/CMakeLists.txt, arch/x86_64/src/intel64/Make.defs, arch/x86_64/src/intel64/intel64_fpucmp.c, arch/x86_64/src/intel64/intel64_handlers.c
- arch/intel64: enable FPU and implement up_fpucmp to pass ostest
enable FPU and implement up_fpucmp to pass ostest
With aggressive optimization enabled (-O2/-O3), ostest FPU test will fail. This is because the compiler will generate additional vector instructions between subsequent up_fpucmp() calls (loop vectorization somewhere in usleep() call), which will consequently overwrite the expected FPU context (XMM registers).
FPU ostest with CONFIG_DEBUG_FULLOPT=y needs https://github.com/apache/nuttx/pull/11782 to pass without errors
qemu and intel hardware
=> arch/intel64: enable FPU and implement up_fpucmp to pass ostest

arch/x86_64/src/common/Toolchain.defs
- x86_64/common/Toolchain.defs: change optimization to -Os for CONFIG_DEBUG_FULLOPT
change optimization to -Os for CONFIG_DEBUG_FULLOPT to be compatible with other architectures and add an option to select CONFIG_DEBUG_CUSTOMOPT
qemu and intel hardware
=> x86_64/common/Toolchain.defs: change optimization to -Os for FULLOPT

boards/x86_64/intel64/qemu-intel64/scripts/qemu.ld
- qemu-intel64: add .note.gnu.* to linker script
this prevents section overlap linker errors which sometimes occurs:
ld: section .rodata LMA [0000000000990000,00000000009c1f27] overlaps section .note.gnu.property LMA [000000000098ffe0,000000000099000f]
make[1]: *** [Makefile:114: nuttx.elf] Error 1
make and cmake build
=> qemu-intel64: add .note.gnu.* to linker script

Documentation/components/drivers/character/hx711.rst, Documentation/components/drivers/character/index.rst, boards/arm/stm32/stm32f411-minimum/Kconfig, boards/arm/stm32/stm32f411-minimum/src/CMakeLists.txt, boards/arm/stm32/stm32f411-minimum/src/Make.defs, boards/arm/stm32/stm32f411-minimum/src/stm32_bringup.c, boards/arm/stm32/stm32f411-minimum/src/stm32_hx711.c, boards/arm/stm32/stm32f411-minimum/src/stm32f411-minimum.h, drivers/analog/CMakeLists.txt, drivers/analog/Kconfig, drivers/analog/Make.defs, drivers/analog/hx711.c, include/nuttx/analog/hx711.h
Patch adds driver to support hx711 adc designed for weigh scales. Example initialization is added in stm32f411-minimum board.
Zero impact on other code.
=> Add driver for hx711 weight scale ADC

boards/arm/stm32/stm32f411-minimum/Kconfig
This is leak from another feature that was not yet meant to be pushed.
=> boards/stm32f411-minimum: remove non existing include in Kconfig

include/nuttx/tls.h
nuttx/tls: report warning if pthread enabled only
```
include/nuttx/tls.h:52:4: warning: #warning CONFIG_TLS_NELEM is not defined [-Wcpp]
52 | #  warning CONFIG_TLS_NELEM is not defined
|    ^~~~~~~
In file included from include/nuttx/sched.h:48,
from include/nuttx/arch.h:87,
from include/nuttx/userspace.h:35,
from include/nuttx/mm/mm.h:30,
from include/nuttx/kmalloc.h:34,
from sim_bringup.c:33:
include/nuttx/tls.h:52:4: warning: #warning CONFIG_TLS_NELEM is not defined [-Wcpp]
52 | #  warning CONFIG_TLS_NELEM is not defined
|    ^~~~~~~
```
N/A
sim/nsh + CONFIG_DISABLE_PTHREAD
=> nuttx/tls: report warning if pthread enabled only 

drivers/sensors/CMakeLists.txt, drivers/sensors/bmi160_base.c, drivers/sensors/bmi160_base.h
- sensors/bmi160: fix compilation errors
fix compilation errors about undefined reference to `bmi160_configspi'
reported on the mailing list
=> sensors/bmi160: fix compilation errors

arch/arm/src/fvp-v8r-aarch32/fvp_serial.c
arm/armv8-r: fix build break if disable CONFIG_UART_PL011
Common code should support the if PL011 is not enabled
N/A
ci-check
=> arm/armv8-r: fix build break if disable CONFIG_UART_PL011

arch/Kconfig, arch/x86_64/include/spinlock.h, arch/x86_64/src/intel64/CMakeLists.txt, arch/x86_64/src/intel64/Make.defs, arch/x86_64/src/intel64/intel64_testset.S
- arch/x86_64: add spinlock support
smp on qemu
=> arch/x86_64: add spinlock support

include/assert.h
assert/panic: disable panic message to save the code size
Requirement of nuttx as a minimum scheduler os.
Test build on Cortex-R52, fvp-armv8r-aarch32/nsh
Disable CONFIG_DEBUG_ASSERTIONS and without this change:
```
$ size nuttx
text	   data	    bss	    dec	    hex	filename
19484	    104	   1092	  20680	   50c8	nuttx
```
Disable CONFIG_DEBUG_ASSERTIONS and with this change:
```
$ size nuttx
text	   data	    bss	    dec	    hex	filename
17604	     80	    848	  18532	   4864	nuttx
```
=> assert/panic: disable panic message to save the code size

arch/xtensa/src/esp32/esp32_himem.c, arch/xtensa/src/esp32/esp32_spiflash.c, arch/xtensa/src/esp32/esp32_spiflash.h
- Fix issue of system blocking caused by Ext-SRAM-Cache MMU mapping when SPIRAM is used as a stack.
The root cause reference: https://github.com/apache/nuttx/pull/11779
=> xtensa/esp32: Fix issue of system blocking when SPIRAM is used as stack

cmake/nuttx_mkconfig.cmake
Current CMake build system has empty string for BASE_DEFCONFIG option. This patch fills "board/config" as value for it.
CMake
Checked with "sim/nsh"
=> build/cmake: fix empty BASE_DEFCONFIG

arch/arm/src/lc823450/lc823450_timer.c, arch/arm/src/lc823450/lc823450_usbdev.c, arch/arm/src/stm32h7/stm32_adc.c, arch/arm/src/stm32l4/stm32l4_adc.c, arch/risc-v/src/bl602/bl602_netdev.c, arch/risc-v/src/common/espressif/esp_hr_timer.c, arch/risc-v/src/esp32c3-legacy/esp32c3_rt_timer.c, arch/risc-v/src/k230/k230_rptun.c, arch/risc-v/src/mpfs/mpfs_ihc.c, arch/risc-v/src/rv32m1/rv32m1_gpio.c, arch/sim/src/sim/posix/sim_alsa.c, arch/sim/src/sim/sim_rptun.c, arch/xtensa/src/esp32/esp32_rt_timer.c, arch/xtensa/src/esp32/esp32_wlan.c, arch/xtensa/src/esp32s2/esp32s2_rt_timer.c, arch/xtensa/src/esp32s3/esp32s3_rt_timer.c, drivers/input/uinput.c, drivers/misc/rpmsgdev_server.c, drivers/power/battery/goldfish_battery.c, drivers/power/supply/regulator.c, drivers/sensors/sensor_rpmsg.c, drivers/timers/rpmsg_rtc.c, drivers/virtio/virtio.c, fs/vfs/fs_epoll.c, include/nuttx/list.h
nuttx/list: rename container_of to list_container_of from public header
Use private naming to avoid conflicts with user applications
```
In file included from libuv/src/unix/internal.h:25,
from libuv/src/unix/udp.c:23:
libuv/src/uv-common.h:57: warning: "container_of" redefined
57 | #define container_of(ptr, type, member) \
|
In file included from nuttx/include/nuttx/list.h:47,
from nuttx/include/nuttx/tls.h:40,
from nuttx/include/nuttx/sched.h:48,
from nuttx/include/nuttx/arch.h:87,
from nuttx/include/nuttx/userspace.h:35,
from nuttx/include/nuttx/mm/mm.h:30,
from nuttx/include/nuttx/kmalloc.h:34,
from nuttx/include/nuttx/lib/lib.h:31,
from nuttx/include/stdio.h:35,
from apps/system/libuv/libuv/include/uv.h:59,
from libuv/src/unix/udp.c:22:
nuttx/include/nuttx/nuttx.h:48: note: this is …
```
=> nuttx/list: rename container_of to list_container_of from public header

net/local/local.h, net/local/local_accept.c, net/local/local_conn.c, net/local/local_connect.c, net/local/local_recvmsg.c, net/local/local_sendmsg.c, net/local/local_sockif.c
- local: correct shutdown state when use UDP mode
- net/local: Remove the unused lc_psock from local_conn_s
- net/local: Initialize lc_crefs to 1
- net/local: Remove the check of SOCK_STREAM before local_stream_connect
- net/local: Add local_freectl to avoid the code duplicaton
local socket
internal testing
=> Minor local socket improvement

.github/workflows/build.yml
the check isn't really enabled and enforce before due to a mass of false alarm, but recently it break ci frequently, so it's better to remove it now.
ci
ci
=> ci: Remove the codecheck from build.yml

include/nuttx/sched.h, include/nuttx/tls.h, libs/libc/tls/tls_getinfo.c, sched/tls/task_initinfo.c, sched/tls/task_uninitinfo.c, sched/tls/tls.h
sched/tls: inline group info in flat mode to improve performance
inline group info in flat mode to improve the task create/destroy performance
N/A
nsh/sim
=> sched/tls: inline group info in flat mode to improve performance

Documentation/quickstart/organization.rst
Documentation: correct `CMakeList.txt` to `CMakeLists.txt`
Signed-off-by: Junbo Zheng <zhengjunbo1@xiaomi.com>
=> Documentation: correct `CMakeList.txt` to `CMakeLists.txt`

tools/ci/cibuild.sh, tools/ci/platforms/darwin.sh, tools/ci/platforms/linux.sh, tools/ci/platforms/msys2.sh, tools/ci/platforms/ubuntu.sh
This is an idea for tweaking how we build on GitHub and test locally. This will make it easier to maintain and make it easier to develop on new platforms. 
The proposed solution is based on the following changes:
- **cibuild.sh** -> Only detect platforms.
- **platforms** ->  Added a folder with scripts for each platform (installing toolchains, tools, etc.). 
darwin.sh, msys2.sh, linux.sh (Without the package management commands) and ubuntu.sh
Why each distribution has different packages (apt, apk, dnf, pacman, pkg) and each distribution has different versions of programs and  their dependencies.
We tested on the local platform MSYS2 and GitHub
=> tools/ci: Modify cibuild.sh to support new platforms

Documentation/components/filesystem/shmfs.rst, net/Kconfig
This patch adds simple document for the shared memory file system. 
It also fix typos fix in a other places.
None
CI checks
=> docs/comments: add simple document and fix typo

drivers/syslog/syslog_rpmsg.c
syslog_rpmsg: handle syslog_rpmsg_transfer() return value
in case of only update head
syslog rpmsg
SIM
=> syslog_rpmsg: handle syslog_rpmsg_transfer() return value

fs/procfs/fs_procfscpuload.c, include/nuttx/clock.h, include/nuttx/sched.h, sched/sched/sched.h, sched/sched/sched_cpuload.c
cpuload: remove ciritical_section() to fix recursive
cpuload: change cpuload type to clock_t
Recursive:
25 0x44000e5a in up_cpu_paused (cpu=cpu@entry=1) at armv7-a/arm_cpupause.c:120
26 0x440032f2 in enter_critical_section () at irq/irq_csection.c:275
27 0x44006f24 in nxsched_process_taskload_ticks (tcb=tcb@entry=0x442ba638 <g_idletcb+256>, ticks=0) at sched/sched_cpuload.c:104
28 0x44007310 in nxsched_suspend_critmon (tcb=tcb@entry=0x442ba638 <g_idletcb+256>) at sched/sched_critmonitor.c:303
29 0x44006ef0 in nxsched_suspend_scheduler (tcb=tcb@entry=0x442ba638 <g_idletcb+256>) at sched/sched_suspendscheduler.c:78
30 0x44000e5a in up_cpu_paused (cpu=cpu@entry=1) at armv7-a/arm_cpupause.c:120
31 0x440032f2 in enter_critical_section () at irq/irq_csection.c:275
32 0x44000f1a in …
=> cpuload: remove ciritical_section() to fix recursive

arch/arm/src/armv7-a/arm_perf.c, arch/arm/src/armv7-a/arm_timer.c, arch/arm/src/armv7-a/arm_timer.h, arch/arm/src/armv7-r/arm_perf.c, arch/arm/src/armv7-r/arm_timer.c, arch/arm/src/armv7-r/arm_timer.h, arch/arm/src/goldfish/goldfish_boot.c, arch/arm/src/qemu/qemu_boot.c
armv7-a/r: use arm_timer to setup perf
armv7-a timer:fix timer overflow
armv7a/r: use register cval to set timer
armv7-a/r: correct maxdelay calculating
armv7-a/r timer 
Qemu
=> armv7-a/r timer update

arch/x86_64/include/hpet.h, arch/x86_64/include/intel64/irq.h, arch/x86_64/src/intel64/CMakeLists.txt, arch/x86_64/src/intel64/Kconfig, arch/x86_64/src/intel64/Make.defs, arch/x86_64/src/intel64/intel64_hpet.c, arch/x86_64/src/intel64/intel64_hpet.h, arch/x86_64/src/intel64/intel64_oneshot.c, arch/x86_64/src/intel64/intel64_oneshot.h, arch/x86_64/src/intel64/intel64_oneshot_lower.c, boards/x86_64/intel64/qemu-intel64/src/qemu_bringup.c
arch/intel64: add HPET timer support as oneshot timer
qemu and intel64 hardware
=> arch/intel64: add HPET timer support as oneshot timer

boards/Board.mk
When using the common directory, some etc resources can be placed under common/etc to reduce the storage of duplicate resources.
The purpose of this change is to perform resource search logic during the compilation process without affecting the original makefile:
This expectation will first search whether the resource specified by the makefile is stored in the private src/etc. If it does not exist, it will then search whether the resource exists under common/etc.
If the resource does not exist under common/etc, the path will eventually be spliced ​​back to the original target (i.e. src/etc under the private path)
During the compilation process, the search logic for resource expansion
The local test passed.
Add the resource file (etc/test) that needs to be compiled in the configured …
=> Enhance board/board.mk compilation capabilities

arch/arm/src/common/arm_allocateheap.c, arch/arm/src/goldfish/chip.h, arch/arm/src/qemu/chip.h, arch/arm/src/stm32h7/stm32_sdmmc.c
arm: fix compile error
./common/arm_allocateheap.c:42:10: fatal error: mmu.h: No such file or directory
42 | #include "mmu.h"
|          ^~~~~~~
compilation terminated.
compile error
=> arm: fix compile error

tools/toolchain.cmake.export
Exported CMake toolchain file is broken when the target is linked against NuttX and another library that shall also be linked against NuttX too.
Ensure that NuttX libraries are linked at the end as they are the root of linkage dependency tree.
=> Fix broken exported CMake toolchain file link dependencies

Documentation/applications/testing/nand_sim/index.rst, drivers/mtd/Kconfig, drivers/mtd/Make.defs, drivers/mtd/mtd_nand.c, drivers/mtd/mtd_nandram.c, drivers/mtd/mtd_nandwrapper.c, include/nuttx/compiler.h, include/nuttx/mtd/nand.h, include/nuttx/mtd/nand_ram.h, include/nuttx/mtd/nand_wrapper.h
Adds virtual NAND Flash simulator
Adds virtual NAND Flash simulator.
Adds log wrapper methods for NAND Flash.
Adds documentation on NAND Flash.
Virtual NAND Flash
Basic file I/O with littlefs.
`checkpatch.sh` (gives error for multiple data definitions due to array of numbers separated by commas).
=> drivers/mtd/mtd_nandram: Adds virtual NAND Flash simulator

Documentation/platforms/arm/samv7/index.rst, arch/arm/src/samv7/sam_serial.c, arch/arm/src/samv7/sam_serial.h, arch/arm/src/samv7/sam_xdmac.c, arch/arm/src/samv7/sam_xdmac.h
This commit adds support for TX DMA transfers for USART peripheral. Code refactor in `sam_serial.h` was also required in order to have correct defines for all possible cases (both RX and TX DMA used, just one used, none used).
SAMv7 MCUs only
Tested on SAMv7 evaluation kit and on custom board with SAMv7 MCU.
=> samv7: add support for USART TX DMA transfers

include/sched.h
sched.h: fix CPU_EQUAL(s1, s2) write error
sched.h: add empty realize when NO CONFIG_SMP
SMP
QEMU
=> sched.h: fix CPU_EQUAL(s1, s2) write error

arch/xtensa/src/esp32s3/esp32s3_spiflash_mtd.c
These log messages are wrong if we use `CONFIG_FS_LARGEFILE`.
So we use the correct type specifiers.
Log messages are meaningful with `CONFIG_FS_LARGEFILE` set.
N/A
=> fix(esp32s3_spiflash_mtd): use correct type specifiers

sched/environ/env_dup.c
sched/environ: check envcp validity before hold sched_lock()
check envcp validity before hold sched_lock() to avoid unnecessary schedule lock
N/A
ci-check
=> sched/environ: check envcp validity before hold sched_lock()

drivers/sensors/ds18b20_uorb.c, drivers/sensors/hyt271_uorb.c, drivers/sensors/mpu9250_uorb.c, drivers/sensors/ms56xx_uorb.c, include/nuttx/tls.h, libs/libc/stdlib/lib_getprogname.c, sched/group/group_argvstr.c, sched/init/nx_start.c, sched/task/task_fork.c, sched/task/task_setup.c, sched/task/task_start.c
sched/task: save argument counter to avoid limit check
The maximum startup parameters have been checked accordingly in nxtask_setup_stackargs(),
let us save argument counter to avoid limit check.
N/A
ci-check
=> sched/task: save argument counter to avoid limit check

arch/arm/include/irq.h, arch/arm64/include/irq.h, arch/avr/include/irq.h, arch/ceva/include/irq.h, arch/hc/include/irq.h, arch/misoc/include/irq.h, arch/or1k/include/irq.h, arch/renesas/include/irq.h, arch/risc-v/include/irq.h, arch/sim/include/irq.h, arch/sparc/include/irq.h, arch/tricore/include/irq.h, arch/x86/include/irq.h, arch/x86_64/include/irq.h, arch/xtensa/include/irq.h, arch/z16/include/irq.h, arch/z80/src/ez80/switch.h, arch/z80/src/z180/switch.h, arch/z80/src/z80/switch.h
This fix some typos in comments.
None
CI checks
=> comments/docs: fix typos in comments

include/nuttx/sched.h
nuttx/sched: remove unused group link node
This change is missing from the below commit:
```
| commit 7cb1f3b3c008e4d16861b9ee214c7c8c5d445fbe
| Author: chao an <anchao@lixiang.com>
| Date:   Tue Mar 5 10:23:30 2024 +0800
|
|     sched/group: replace group_findbypid to task_getgroup
|
|     Task group could find from process id, replace group_findbypid to
|     task_getgroup to simplify the search logic
|
|     Signed-off-by: chao an <anchao@lixiang.com>
```
N/A
ci-check
=> nuttx/sched: remove unused group link node

sched/pthread/pthread_create.c
sched/pthread: fix memory leak of pthread_tcb_s
pthread tcb should be released appropriately
N/A
ci-check
=> sched/pthread: fix memory leak of pthread_tcb_s

fs/inode/fs_files.c, include/nuttx/fs/fs.h
fs/inode: add pre-allocated task files to avoid allocator access
Pre-allocated files to avoid allocator access during thread creation
phase, For functional safety requirements, increase
CONFIG_NFILE_DESCRIPTORS_PER_BLOCK could also avoid allocator access
caused by the file descriptor exceeding the limit.
For Task Termination, the time consumption will be reduced ~3us (Tricore TC397 300MHZ):
10.65(us) -> 7.35(us)
**NOTE:
This commit will not waste of extra heap, just pre-allocates the list of files for task_group.**
N/A
ci-check
=> fs/inode: add pre-allocated task files to avoid allocator access

binfmt/binfmt_execmodule.c, fs/procfs/fs_procfsproc.c, include/nuttx/list.h, include/nuttx/queue.h, include/nuttx/sched.h, sched/clock/clock_gettime.c, sched/group/group_create.c, sched/group/group_foreachchild.c, sched/group/group_join.c, sched/group/group_killchildren.c, sched/group/group_leave.c, sched/task/task_exithook.c
sched/group: change type of task group member to single queue
Change the type of task group member to single list chain to avoid accessing the memory allocator to improve the performance
N/A
ci-check
=> sched/group: change type of task group member to single queue

arch/xtensa/src/esp32s3/esp32s3_dma.c, arch/xtensa/src/esp32s3/esp32s3_dma.h, arch/xtensa/src/esp32s3/esp32s3_i2s.c, arch/xtensa/src/esp32s3/esp32s3_lcd.c, arch/xtensa/src/esp32s3/esp32s3_qspi.c, arch/xtensa/src/esp32s3/esp32s3_spi.c, arch/xtensa/src/esp32s3/esp32s3_spi_slave.c
- Configure DMA maximum buffer size based on access to different RAM
=> xtensa/esp32s3: Configure DMA maximum buffer size based on access to different RAM

arch/risc-v/src/common/espressif/esp_wdt.c, arch/risc-v/src/esp32c3-legacy/esp32c3_i2c.c, arch/risc-v/src/esp32c3-legacy/esp32c3_wdt_lowerhalf.c, arch/risc-v/src/mpfs/mpfs_i2c.c, arch/xtensa/src/esp32s2/esp32s2_wdt_lowerhalf.c, arch/xtensa/src/esp32s3/esp32s3_wdt_lowerhalf.c, boards/arm/cxd56xx/drivers/sensors/cxd5610_gnss.c
The cast of (uintptr_t) is not necessary, and it is better to use %p
ci
=> Replace PRIxPTR with %p and remove the cast of (uintptr_t)

binfmt/binfmt_execmodule.c, sched/group/group_killchildren.c
1. binfmt/task/member: remove invaild membership reverse
As long as the process id reversed between parent and child,
the process member ship will automatically reversed.
Fix Regression by PR #11848:
```
| commit ec08031e4bf01f0abc9e590484382c166d90915e
| Author: chao an <anchao@lixiang.com>
| Date:   Wed Mar 6 10:13:47 2024 +0800
|
|     sched/group: change type of task group member to single queue
|
|     Change the type of task group member to single list chain to
|     avoid accessing the memory allocator to improve the performance
|
|     Signed-off-by: chao an <anchao@lixiang.com>
```
2. sched/group: skip child wait if here is only self in member list
Skip the child wait if here is only self in member list,
since the members of the task group should be 1 if task exit.
Signed-off-by: …
=> binfmt/task/member: remove invaild membership reverse

arch/x86_64/src/common/x86_64_initialize.c, boards/x86_64/intel64/qemu-intel64/src/qemu_bringup.c
- qemu-intel64: move PCI initialization back to board logic
this partly revert 4123615621 which works OK for PCI serial and network cards but breaks QEMU EDU due to usage of sem and usleep in IDLE thread context. Another solution will be provided later.
qemu
=> qemu-intel64: move PCI initialization back to board logic

arch/x86_64/src/common/x86_64_initialize.c
- arch/x86_64: add addrenv support
- x86_64/x86_64_initialzie.c: remove up_calibratedelay
This function is not used anywhere.
For udelay calibration we have the calib_udelay app
qemu and intel hw
=> arch/x86_64: add addrenv support

arch/x86_64/Kconfig, arch/x86_64/src/cmake/Toolchain.cmake, arch/x86_64/src/common/Kconfig, arch/x86_64/src/common/Toolchain.defs
- arch/x86_64: add SSE instruction support
at default x86_64 supports SSE, SSE2, this commit adds support for SSE3, SSSE3, SSE41, SSE42 and SSE4A
qemu and intel hw
=> arch/x86_64: add SSE instruction support

arch/risc-v/src/k230/k230_hart.c, arch/risc-v/src/k230/k230_hart.h, arch/risc-v/src/k230/k230_userspace.c
This patch simplifies PMP handling using common APIs. It also uses `g_misa` variable to expose the MISA issue.
K230 devices
checked on CanMV230
=> riscv/k230: minor revision on PMP settings

arch/arm/src/nrf52/nrf52_spi.c, arch/arm/src/nrf53/nrf53_spi.c, arch/arm/src/nrf91/nrf91_spi.c
- arch/nrf{52|53|91}: fix typo
fix typo sndlock -> sndblock
- arch/nrf91: fix compilation for SPI
remove references to unsupported SPI freq and SPI4 which is not supported
CI
=> arch/nrf: fixes for SPI

arch/arm/src/samv7/Kconfig
ATSAMV7 MCUs allow usage of fault inputs for PWMs. However, there were typos in arch/arm/src/samv7/Kconfig that didn't allow for choosing inverted polarity of these inputs for PWM0 because of typos. PWM1 is fine.
=> SAMV7: fix typos in Kconfig PWM0 fault input selections - inv. polarity

include/nuttx/mm/map.h, include/nuttx/sched.h, sched/group/group.h, sched/group/group_create.c, sched/group/group_foreachchild.c, sched/group/group_leave.c, sched/init/nx_start.c, sched/pthread/pthread_create.c, sched/sched/sched_releasetcb.c, sched/task/task_fork.c, sched/task/task_init.c
sched/group: move task group into task_tcb_s to improve performance
move task group into task_tcb_s to avoid access allocator to improve performance
for Task Termination, the time consumption will be reduced ~2us (Tricore TC397 300MHZ):
15.97(us) -> 13.55(us)
In interval B:
N/A
ci-check
=> sched/group: move task group into task_tcb_s to improve performance

sched/group/group_leave.c, sched/sched/sched_releasetcb.c
sched/group: set clear flag if the group is not really needed
The delete flag is not synchronized with the life cycle of the group, if the flag set before waitpid(), the tcb will be mistakenly deleted by group_del_waiter(), use-after-free will happen.
Regression by:
```
| commit 29e50ffa7374fa4c473d8d4f8cb3506665443d3e (origin/master, origin/HEAD)
| Author: chao an <anchao@lixiang.com>
| Date:   Mon Mar 4 09:19:27 2024 +0800
|
|     sched/group: move task group into task_tcb_s to improve performance
|
|     move task group into task_tcb_s to avoid access allocator to improve performance
|
|     for Task Termination, the time consumption will be reduced ~2us (Tricore TC397 300MHZ):
|     15.97(us) -> 13.55(us)
|
|     Signed-off-by: chao an <anchao@lixiang.com>
```
N/A
rv-virt:ksmp64
=> sched/group: set clear flag if the group is not really needed

include/nuttx/mm/mempool.h, mm/Kconfig, mm/mm_heap/mm.h
This fixes minor typo in MM_DEFAULT_ALIGNMENT
None
CI checks
=> mm/kconfig: fix typo in MM_DEFAULT_ALIGNMENT

tools/minidumpserver.py
This patch supports quiting of minidumpserver along with gdb so that to reduce usage efforts.
minidumpserver.py users
CI chjecks
=> tools/minidumpserver.py: support quit with gdb

include/nuttx/sched.h, sched/pthread/pthread_findjoininfo.c
sched/pthread/join: remove unused joininfo
remove unused joininfo, minor issue found from code reading
N/A
ci-check
=> sched/pthread/join: remove unused joininfo

Documentation/platforms/risc-v/esp32c3/boards/esp32c3-generic/index.rst, Documentation/platforms/risc-v/esp32c3/index.rst, Documentation/platforms/risc-v/esp32c6/boards/esp32c6-devkit/index.rst, Documentation/platforms/risc-v/esp32c6/index.rst, Documentation/platforms/risc-v/esp32h2/boards/esp32h2-devkit/index.rst, Documentation/platforms/risc-v/esp32h2/index.rst
- docs/esp32c6: Remove sotest docs esp32c6
- docs/esp32c3: Add spiflash docs esp32c3
- docs/esp32c3: Remove sotest docs esp32c3
- docs/esp32h2: Add spiflash docs esp32h2
- docs/esp32h2: Remove sotest docs esp32h2
ESP32-H2, ESP32-C3, ESP32-C6
=> docs/esp32c6: Add spiflash docs for esp32c6

sched/pthread/pthread_completejoin.c, sched/pthread/pthread_join.c
sched/pthread: replace pthread_sem_give() to nxsem_post() to unify the post method
replace pthread_sem_give() to nxsem_post() to unify the post method
N/A
ci-check
=> sched/pthread: replace pthread_sem_give() to nxsem_post() to unify the post method

arch/arm/Kconfig, arch/arm/src/xmc4/Make.defs, arch/arm/src/xmc4/xmc4_ccu4.c, arch/arm/src/xmc4/xmc4_ccu4.h, arch/arm/src/xmc4/xmc4_tickless.c
**Add Tickless support of xmc4 chip.**
Unfortunately the xmc4 CCU (Compare/Capture Unit) can't be used to do a tickless feature via alarm (one freerun timer) because the compare value cannot be update on the flight (see shadow register in the RM). So I used two timers one freerun (for timing) and one oneshot timer (for interval). 
Notes : 
1. The XMC has 4 CCU and 4 slices of 16bits in each of them that can be concatenated to form a 64bits timer. A the beginning I though this concatenation feature could help me to avoid having max wait delay (or very very long one). But this concatenation doesn't really work as a 64 bits timers. Indeed, for instance, if you concatenate 2 slices. The second slice will increment its counter once the first one has finished its period. Meaning, you have two …
=> arch/xmc4 Add tickless support 

arch/xtensa/src/esp32/esp32_emac.c
- Fix wrong interrupt number: it should be `ESP32_IRQ_EMAC` instead of `priv->cpuint`
=> xtensa/esp32: Fix wrong interrupt number

arch/x86_64/src/common/Make.defs, arch/x86_64/src/intel64/Make.defs
arch/x86_64: move common Make.defs to common
cosmetic change to simplify intel64 Make.defs
CI
=> arch/x86_64: move common Make.defs to common

fs/mount/fs_mount.c, mm/mm_heap/mm.h
This patch contains  improvements to harden logic of nx_mount():
- currently some variables may not get populated by called functions, thus initialization is added.
- empty string device path is possible when multiple type of file systems are enabled.
It also revised comments for mm_heap/mm.h
file system mount operations
=> revise comments and harden nx_mount logic

arch/arm/src/stm32/stm32_serial.c
Onewire driver wants to use "struct up_dev_s *priv", which is extracted from "struct uart_dev_s" and "struct inode". But inode and uart dev are only declared when TERMIOS or BSDCOMPAT is also enabled. Without these driver fails to compile with missing declaration errors. Adding some additional "#if defined()" to these declarations fix the issue and driver compiles and works properly (tested with ds18b20 temp sensor).
=> stm32_serial.c: fix compilation of onewire driver mode

include/assert.h
This reverts commit 9b1c451f2f881077cd7d56f6496ea3c06ea30f17, introduced by [#11796](https://github.com/apache/nuttx/pull/11796)
Please note that the introduced change replaces the `PANIC` from the `_assert` to an infinite loop when `CONFIG_DEBUG_ASSERTIONS` is not selected. Although it prevents message logs (and saves code size), the `__assert`  (and `_assert`) function also calls other functions like `panic_notifier_call_chain` and `board_reset`, which would not occur if `CONFIG_DEBUG_ASSERTIONS` is not selected.
The correct approach to save code would be to disable some of the log messages on `sched/misc/assert.c` when `CONFIG_DEBUG_ASSERTIONS` is not selected or substitute `PANIC` to `DEBUGPANIC` when applicable.
Without it, it prevented important functions to run when panic'ed.
Local …
=> Revert "assert/panic: disable panic message to save the code size"

include/nuttx/sched.h, sched/group/group_create.c, sched/init/nx_start.c, sched/pthread/pthread.h, sched/pthread/pthread_completejoin.c, sched/pthread/pthread_create.c, sched/pthread/pthread_findjoininfo.c, sched/pthread/pthread_join.c, sched/pthread/pthread_release.c, sched/sched/sched_releasetcb.c, sched/task/CMakeLists.txt, sched/task/Make.defs, sched/task/task.h, sched/task/task_fork.c, sched/task/task_init.c, sched/task/task_join.c
sched/pthread/join: refactor pthread join to support join task
1. add support to join main task
```
| static pthread_t self;
|
| static void *join_task(void *arg)
| {
|   int ret;
|   ret = pthread_join(self, NULL);          <---  /* Fix Task could not be joined */
|   return NULL;
| }
|
| int main(int argc, char *argv[])
| {
|   pthread_t thread;
|
|   self = pthread_self();
|
|   pthread_create(&thread, NULL, join_task, NULL);
|   sleep(1);
|
|   pthread_exit(NULL);
|   return 0;
| }
```
2. Detach active thread will not alloc for additional join, just update the task flag.
3. Remove the return value waiting lock logic (data_sem),
the return value will be stored in the waiting tcb.
4. Revise the return value of pthread_join(), consistent with linux
e.g:
Joining a detached and canceled …
=> sched/pthread/join: refactor pthread join to support join task

drivers/net/tun.c
io_pktlen will incorrect when two packets are received in a row and the packet length decreases.
sim:local
=> tun: in tun_write, try to release iob before iob_prepare

net/tcp/tcp_input.c
return true even when window has not changed will cause delayed ack cannot take effect.
sim:local and cortex-m33
=> net/tcp: return true only when send window updates

arch/risc-v/src/k230/chip.h, arch/risc-v/src/k230/k230_hart.c
This patch fixes the issue that k230_hart_is_big() doesn't work in S-mode. It also adds convenient debug macros to ease debugging process
K230 devices
=> risc-v/k230: fix k230_hart_is_big issue

drivers/serial/pty.c, fs/driver/fs_unregisterdriver.c
fs/driver: using nx_unlink to call unlink ops to release some resource
if driver complete unlink ops, we need to call it to release some resource, otherwise, it will only remove inode.
release resource after unlink
adb test
=> fs/driver: using nx_unlink to call unlink ops to release some resource

binfmt/binfmt_loadmodule.c
binfmt/loadmodule: replace kmm_free() to lib_free()
replace kmm_free() to lib_free() unify alloc and free method
N/A
ci-check
=> binfmt/loadmodule: replace kmm_free() to lib_free()

include/nuttx/sched.h, sched/signal/sig_dispatch.c, sched/signal/sig_timedwait.c
sched/signal: move unblock signal info to stack
`struct tcb_s` will reduce by 24 bytes
N/A
ostest
=> sched/signal: move unblock signal info to stack

drivers/sensors/bmi270.c, include/nuttx/sensors/bmi270.h
- sensors/bmi270: fix accel and gyro data position
accel registers are DATA_8 to DATA_13
gyro registers are DATA_14 to DATA_19
CI
=> sensors/bmi270: fix accel and gyro data position

tools/Export.mk, tools/mkexport.sh, tools/toolchain.cmake.export
Add variables that describe NuttX current build (board, arch, chip)
Fix export: startups files are not added at link step
picopi:usbnsh with an external project
visual check on export archive files
=> Improve export by adding NuttX current target (arch, chip, board)

boards/arm/stm32/stm32f429i-disco/include/board.h, boards/arm/stm32/stm32f429i-disco/src/CMakeLists.txt, boards/arm/stm32/stm32f429i-disco/src/Make.defs, boards/arm/stm32/stm32f429i-disco/src/stm32_bringup.c, boards/arm/stm32/stm32f429i-disco/src/stm32_can.c, boards/arm/stm32/stm32f429i-disco/src/stm32f429i-disco.h
add CAN driver support
on fire development board
=> boards/arm/stm32/stm32f429i-disco add CAN driver support

LICENSE, boards/arm/rp2040/common/include/rp2040_uniqueid.h, boards/arm/rp2040/common/src/Make.defs, boards/arm/rp2040/common/src/rp2040_common_initialize.c, boards/arm/rp2040/common/src/rp2040_uniqueid.c
Implement uniqueid for RP2040 based boards.  Because the RP2040 does not have a bulit-in unique identifier, we use the id from the connected flash chip.  Most RP2040 based boards use a similar flash chip, so this is expected to work with most boards.
Since the code runs from flash, we cannot easily retrieve this ID at runtime (interrupts and additional SMP cores must be suspended, code must run from RAM during the retrieval).  Instead, we load the ID once during initialization and store it for later use.
Due to differences in flash chips and a configurable CONFIG_BOARDCTL_UNIQUEID_SIZE, we can't always guarantee uniqueness of the ID from flash.  To help address this, we seed a PRNG with the 8 byte flash id, then generate our board uniqueid from the PRNG output.  This should provide a high …
=> RP2040: Implement board_uniqueid()

tools/Export.mk
Fix a typo in my last PR that led to never use CONFIG_ARCH_CHIP in the export.
=> Fix Export.mk

include/nuttx/rwsem.h, sched/semaphore/sem_rw.c
The overhead of spinlok is less than mutext (mutex need to call enter_critical section.)
After this patch, `down_write_trylock` and `down_read_trylock` can be use in interrupt context.
semaphore
CI
=> sched:rw_sem: replace mutex with spinlock

.github/workflows/build.yml, tools/ci/platforms/darwin.sh
- function bloaty() Add  -D CMAKE_INSTALL_PREFIX="${NUTTXTOOLS}"/bloaty. 
Improves workflow execution time because it is now cached.
- Changed reference file to calculate the hash for key of actions/cache@v4. Now it is tools/ci/platforms/**darwin.sh**.
None
Pass CI  [test](https://github.com/simbit18/nuttx-testing-ci/actions/runs/8330882530)
=> tools/ci:  Fixed the cmake build and installation of Bloaty in the darwin.sh script.

drivers/can/Kconfig, drivers/can/Make.defs, drivers/can/sja1000.c, drivers/can/sja1000.h, include/nuttx/can/sja1000.h
This driver is based on ESP32 TWAI CAN drivers currently available in Nuttx, and captures the differences currently present across the TWAI drivers for easy future adaption to remaining ESP32 platforms with no loss of support/function. Also provides a generic SJA1000 CAN driver solution that is CPU-architecture independent.
- Low-level driver re-written to allow usage independent of CPU architecture, and support both SJA1000 and TWAI CAN controllers.
- Platform-specific settings abstracted away to be provided by board layer.
- Support for multiple instances of SJA1000 driver.
Tested on ESP32C3 (additional PR to follow with integration for ESP32C3).
=> drivers/can/sja1000: Add SJA1000 CAN driver support

arch/arm64/src/common/arm64_mmu.c
The page tables must be committed to system memory before we can proceed enabling the MMU. ISB() is not enough to do this.
Ensure the translation tables are in system memory (and not CPU cache) before enabling the MMU.
i.MX93
=> arm64_mmu: Add data synchronization barrier after page tables are written

arch/risc-v/src/common/riscv_exception.c, sched/group/group_killchildren.c
If an user process causes an illegal exception, we want to just kill the user process, not cause system panic. Add this functionality for the riscv_exception.
The group_killchildren is modified in a way that if the parent task is terminated forcefully, it also terminates all the children the same way; i.e. not via signal. This allows terminating all the children also from within an exception.
Also fix the _assert printout. Currently the assert prints out the information about the task to which we are returning from exception. This is not necessarily the same as the one that causes it.
Enable user-side crash on RISC-V platforms, e.g. illegal memory accesses w.o. crashing the whole system.
Tested on MPFS RISC-V platform, in CONFIG_BUILD_KERNEL.
=> Fix user task exception handling

sched/wqueue/kwork_cancel.c, sched/wqueue/kwork_inherit.c, sched/wqueue/kwork_queue.c, sched/wqueue/kwork_thread.c, sched/wqueue/wqueue.h
sched/wqueue: replace some global variables to macro
replace to macro will help to extend the scheduling implementation
N/A
ci-check
=> sched/wqueue: replace some global variables to macro

sched/irq/irq_csection.c, sched/paging/pg_miss.c, sched/paging/pg_worker.c, sched/pthread/pthread_create.c, sched/sched/sched.h, sched/sched/sched_addreadytorun.c, sched/sched/sched_cpuselect.c, sched/sched/sched_lock.c, sched/sched/sched_mergepending.c, sched/sched/sched_removereadytorun.c, sched/sched/sched_reprioritizertr.c, sched/sched/sched_setpriority.c, sched/sched/sched_suspend.c, sched/sched/sched_unlock.c, sched/signal/sig_dispatch.c, sched/signal/sig_suspend.c, sched/signal/sig_timedwait.c, sched/task/task_fork.c, sched/task/task_init.c, sched/task/task_restart.c, sched/task/task_setup.c
sched/tasklist: replace task status list with macro definition
replace to macro will help to extend the scheduling implementation
NOTE: This change will not affect code size or performance
N/A
ci-check
=> sched/tasklist: replace task status list with macro definition

drivers/segger/note_sysview.c, include/nuttx/sched.h, mm/mm_heap/mm_free.c, mm/mm_heap/mm_malloc.c, mm/tlsf/mm_tlsf.c, sched/irq/irq_spinlock.c, sched/misc/assert.c, sched/sched/sched.h, sched/sched/sched_getcpu.c
sched/cpu: replace up_cpu_index() to this_cpu()
In SMP mode, up_cpu_index()/this_cpu() are the same, both return the index of the physical core.
In AMP mode, up_cpu_index() will return the index of the physical core, and this_cpu() will always return 0
```
| #ifdef CONFIG_SMP
| #  define this_cpu()             up_cpu_index()
| #elif defined(CONFIG_AMP)
| #  define this_cpu()             (0)
| #else
| #  define this_cpu()             (0)
| #endif
```
N/A, plan to support AMP mode
ci-check
=> sched/cpu: replace up_cpu_index() to this_cpu()

arch/arm/src/stm32f7/stm32_foc.c
This fixes build error (Werror):
Error: chip/stm32_foc.c:1918:12: error: 'stm32_foc_info_get' defined but not used [-Werror=unused-function]
1918 | static int stm32_foc_info_get(struct foc_dev_s *dev, struct foc_info_s *info)
|            ^~~~~~~~~~~~~~~~~~
Fix build error
CI
=> stm32f7/stm32_foc.c: Set .info_get to foc_lower_ops

tools/ci/testlist/macos.dat
The cxx and wifi configurations are currently only present in  [esp32c3-legacy](https://github.com/apache/nuttx/tree/master/boards/risc-v/esp32c3-legacy/esp32c3-devkit/configs)
Changed esp32c3-devkit to esp32c3-legacy
[macOS log](https://github.com/apache/nuttx/actions/runs/8372730024/job/22924414032#step:7:1759)
find: boards/risc-v/esp32c3/esp32c3-devkit/configs/cxx: No such file or directory
find: boards/risc-v/esp32c3/esp32c3-devkit/configs/wifi: No such file or directory
Related to these changes #11620
none
=> tools/ci/testlist/macos.dat: fix path esp32c3-legacy

arch/arm64/src/common/arm64_head.S, boards/arm64/a64/pinephone/scripts/dramboot.ld, boards/arm64/fvp-v8r/fvp-armv8r/scripts/dramboot.ld, boards/arm64/imx8/imx8qm-mek/scripts/dramboot.ld, boards/arm64/imx9/imx93-evk/scripts/dramboot.ld, boards/arm64/qemu/qemu-armv8a/scripts/dramboot.ld, boards/arm64/rk3399/nanopi_m4/scripts/dramboot.ld, boards/arm64/rk3399/pinephonepro/scripts/dramboot.ld
As __start must be placed at a precise location, a separate, explicit input section is needed to guarantee this.
Why is this an issue ?
NuttX uses --entry=__start which puts __start in its correct location, but out-of-tree builds won't work, so it is more robust to use an explicit section for the startup code and enforce its placement in the linker script.
Fixes the location of __start; it must be placed precisely as it contains the image header, which must be placed at a specific location. Problem happens when out-of-tree build is used (PX4 is the example here).
imx93 evk
=> arm64_head.S: Add explicit input section for __start

include/nuttx/init.h, sched/init/nx_start.c, sched/irq/irq_csection.c, sched/sched/sched.h, sched/sched/sched_idletask.c
sched/init: move task list table from data to bss
sched/init: move idle task initialize to inline function
N/A, help to extend the multi-core implementation
N/A
ci-check
=> sched/init: move task list table from data to bss

boards/Kconfig, boards/arm/rp2040/raspberrypi-pico/include/board.h, boards/arm/rp2040/raspberrypi-pico/src/Make.defs, boards/arm/rp2040/raspberrypi-pico/src/rp2040_bringup.c, boards/arm/rp2040/raspberrypi-pico/src/rp2040_buttons.c, boards/arm/rp2040/raspberrypi-pico/src/rp2040_pico.h
Add buttons support example
Users will be able to use button on this board
"raspico"
=> boards/raspberrypi-pico: Add buttons support example

libs/libc/misc/Kconfig, libs/libc/misc/Make.defs, libs/libc/misc/lib_utsname.c
Don't include the build timestamp into final binary when the symbol CONFIG_LIBC_UNAME_DISABLE_TIMESTAMP is defined.
Users will be able to compile same board config twice and get same identical binary.
stm32f103-minimum:nsh
$ cmp /tmp/nuttx1.bin /tmp/nuttx2.bin
$
=> libc/uname: Add option to disable uname timestamp

CMakeLists.txt
CMAKE_CXX_STANDARD is repeatedly defined in the two files, nuttx/CMakeLists(14) and libs/libxx/libcxx.cmake(17), and is defined to different values. Matter needs to use the new features(std::is_signed_v) of c++17,so delete the definition in nuttx/CMakeLists and retain the definition in libs/libxx/libcxx.cmake.
sim:matter
=> CMake：Duplicate definition of CMAKE_CXX_STANDARD

arch/arm64/src/Makefile
On other platforms libarch.a contains the head object. Some projects depend on this fact so let's provide the head object in the archive here as well.
Adds arm64_head.o to libarch.a
readelf to confirm the object is there
=> arch/arm64: Add the head obj to libarch.a as well

arch/risc-v/include/arch.h, fs/mmap/fs_mmap.c
This patch revises comments in risc-v/arch.h and minor revision on fs_mmap.c
size increasion of `fs_mmap_()`
CI  checks
=> minor revision of risc-v/arch.h and fs_mmap.c

arch/risc-v/src/common/espressif/esp_lowputc.c
Fix esp32c6 strange characters on boot
Only ESP32-C6
`esp32c6-devkit:nsh` with and without `CONFIG_DEBUG_FEATURES` option. Also output followed with an serial analyzer.
=> arch/espressif: Fix esp32c6 strange characters on boot

include/nuttx/mm/kmap.h
Fix typo in comments for kmm_map() function.
None
CI checks.
=> mm/kmap.h: fix typo in comments

drivers/video/v4l2_cap.c, drivers/video/v4l2_core.c, drivers/video/video_framebuff.c, drivers/video/video_framebuff.h, include/nuttx/video/imgdata.h, include/nuttx/video/video.h
**V4l2 framework**
1. Make v4l2_ops_s to support the mutilple context
2. Add user define memory ops to v4l2_cap
**video_framebuff**
1. Replace critical section with spinlock
2. Hold mutex in video_framebuff_realloc_container
4. Remove the unnecessary vbuf_curr field
1. image capture
2. video capture
**Setup virtual video device**
```bash
sudo modprobe v4l2loopback
ffmpeg -f x11grab -r 30 -s 640x480 -i :0.0+0,0 -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video0
```
**Build nxcamera**
```bash
./tools/configure.sh -l sim:nxcamera
make 
```
**Run nxcamera in nsh**
```bash
nxcamera
input /dev/video
output /dev/fb0
stream 640 480 30 YU12
```
=> Video improvement

include/nuttx/spinlock.h, sched/irq/CMakeLists.txt, sched/irq/Make.defs, sched/irq/irq_spinlock.c
sched/irq: spinlock should not depends on SMP
spinlock should work independently without CONFIG_SMP
N/A
ci-check
=> sched/irq: spinlock should not depends on SMP

sched/signal/sig_dispatch.c, sched/signal/sig_timedwait.c
sched/signal: add sanity check for siginfo
add sanity check for siginfo to ensure whether there is really a consumer waiting for the signal, since the task state will not be changed appropriately if in cancel/killed case
Test Case:
https://github.com/linux-test-project/ltp/blob/master/testcases/open_posix_testsuite/conformance/interfaces/sigpause/1-1.c#L63
More information:
https://github.com/apache/nuttx/pull/11988
https://github.com/apache/nuttx/pull/11916
N/A
ltp test
=> sched/signal: add sanity check for siginfo

arch/xtensa/src/common/espressif/Make.defs, arch/xtensa/src/common/espressif/platform_include/sys/lock.h, arch/xtensa/src/esp32/esp32_libc_stubs.c, arch/xtensa/src/esp32s2/esp32s2_libc_stubs.c, arch/xtensa/src/esp32s3/Make.defs, arch/xtensa/src/esp32s3/esp32s3_libc_stubs.c, arch/xtensa/src/esp32s3/rom/esp32s3_libc_stubs.h
* esp32[|s2|s3]: Update libc stubs to properly acquire/release locks.
Avoid using global mutexes and recursive mutexes as the locking mechanism to be acquired/released. Instead, create a specific lock for each call if it does not exist.
Functions like `_lock_init` set only a global lock in NuttX (`g_nxlock_common`), which may result in erroneous behavior if another lock is intended to be used (from another function that calls it, for instance). A unique lock must be used instead.
Internal CI testing + ESP32-DevKitC V4 +ESP32-Saola-1 v1.2 + ESP32-S3-DevKitC-1 v1.0
=> esp32[|s2|s3]: Update libc stubs to properly acquire/release locks

arch/arm/src/stm32h7/stm32_serial.c
Fixed logic error as noted by @kk-thrane
Correct logic 
px4_fmu-v6x serial_test / gps / qgc
=> stm32h7:Serial Fix Logic error in up_dma_txavailable

arch/xtensa/src/esp32s3/esp32s3_spiflash.c
- Fix one page program span over 2 pages, one page program can't span over 2 pages.
=> xtensa/esp32s3: Fix one page program span over 2 pages

CMakeLists.txt, arch/arm/src/common/CMakeLists.txt, arch/risc-v/src/common/CMakeLists.txt, boards/arm/tiva/lm3s6965-ek/kernel/CMakeLists.txt
This patch refines protected-mode based on the current kernel libs SPLIT feature.
1. adjust link options for userspace elf
2. disable link option in Toolchain file for userspace elf
3. specify system libs and apps lib to only link with nuttx target in flat build mode
enbale protected-mode build
```bash
cmake -B build -DBOARD_CONFIG=lm3s6965-ek:qemu-protected
cmake --build build
qemu-system-arm -semihosting \  
-M lm3s6965evb \
-device loader,file=build/nuttx.bin,addr=0x00000000 \
-device loader,file=build/nuttx_user.bin,addr=0x00020000 \
-netdev user,id=user0 \
-nic user,id=user0 \
-serial mon:stdio -nographic
```
=> cmake:init protected-mode for CMake build

tools/minidumpserver.py
This adds support of multiple ELF files so that to help Kernel build dump analysis using both nuttx and app ELF files.
minidump tool user
checked with rv-virt 64 bit kernel build.
=> tools/minidump: support multiple ELF files

Documentation/platforms/xtensa/esp32s3/index.rst, arch/xtensa/src/esp32s3/Kconfig, arch/xtensa/src/esp32s3/Make.defs, arch/xtensa/src/esp32s3/esp32s3_aes.c, arch/xtensa/src/esp32s3/esp32s3_aes.h, arch/xtensa/src/esp32s3/hardware/esp32s3_aes.h, boards/xtensa/esp32s3/esp32s3-devkit/src/esp32s3_bringup.c
- Add ESP32-S3 AES driver
- `esp32s3-devkit:nsh`
- Enable `CONFIG_ESP32S3_AES_ACCELERATOR & CONFIG_ESP32S3_AES_ACCELERATOR_TEST` through `make menuconfig`
=> xtensa/esp32s3: Add ESP32-S3 AES driver

openamp/libmetal.cmake
This adds two missing patches so that to be in sync with libmetal.defs
None
checked with rv-virt
=> openamp/cmake: sync with libmetal.defs

include/nuttx/net/netdev.h, net/inet/ipv4_setsockopt.c, net/inet/ipv6_setsockopt.c, net/ipforward/ipv4_forward.c, net/ipforward/ipv6_forward.c, net/netdev/netdev_iob.c, net/udp/udp.h, net/udp/udp_conn.c, net/udp/udp_input.c, net/udp/udp_send.c
- net/netdev: Add netdev_iob_clone helper
- net/udp: Support deliver multicast packets back to local apps
- net/udp: Deliver data into multiple UDP conn bound to same port
UDP only:
- Support `IP_MULTICAST_LOOP`
- Support delivering data into multiple UDP conn bound to same port (to both receive multicast packets)
Vela test cases
=> net/udp: Slight improvement on multicast

drivers/video/isx019.c
Fix default_value of ioctl(VIDIOC_QUERYCTRL)(id=V4L2_CID_3A_STATUS) to AE operating and AWB operating, because both AE and AWB are automatical adjustment mode by default.
isx019
Tested with spresense
=> drivers/video/isx019: Fix default_value of 3A status

boards/Kconfig, boards/boardctl.c, include/sys/boardctl.h
board/control: add irq affinity control
add support for set an IRQ affinity to CPUs by software
N/A
ci-check
=> board/control: add irq affinity control

arch/risc-v/src/common/CMakeLists.txt
This fixes kernel mode regression caused by patch #12011
kernel mode cmake usage
checked with CanMV230
=> risc-v/cmake: revision for kernel mode

drivers/virtio/CMakeLists.txt
This adds drivers like virtio-gpu etc to cmake system to be in line with the makefile system.
cmake users
checked with rv-virt
=> virtio/cmake: sync with makefile system

boards/arm/rp2040/raspberrypi-pico/configs/nshsram/defconfig
- This commit fixes https://github.com/apache/nuttx/issues/11956.
- The issue was introduced by https://github.com/apache/nuttx/pull/6118.
- None
- Tested with raspberrypi-pico.
- NOTE: the ci should be fixed later.
=> boards: raspberrypi-pico: Fix nshsram build error

arch/arm/src/stm32f7/stm32_rtc.c, arch/arm/src/stm32h7/stm32_rtc.c, boards/arm/stm32h7/linum-stm32h753bi/src/Makefile, tools/ci/platforms/darwin.sh
ci/darwin: remove codechecker from install list
try to fix ci error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
codechecker 6.23.1 requires PyYAML==6.0.1, but you have pyyaml 5.4.1 which is incompatible.
```
arm/stm32f7: fix ci build break
1.
```
In file included from chip/stm32_rtc.c:31:
chip/stm32_rtc.c: In function 'rtchw_set_alrmar':
chip/stm32_rtc.c:761:11: warning: format '%x' expects argument of type 'unsigned int',
but argument 3 has type 'uint32_t' {aka 'volatile long unsigned int'} [-Wformat=]
761 |   rtcinfo("  ALRMAR: %08x\n", getreg32(STM32_RTC_ALRMAR));
|           ^~~~~~~~~~~~~~~~~~
chip/stm32_rtc.c:761:25: note: format string is defined …
```
=> ci/darwin: remove codechecker from install list

arch/risc-v/src/common/espressif/esp_irq.c
Bugfix which came from as [github issue](https://github.com/apache/nuttx/issues/11980)
* risc-v/espressif: Fix empty cpuint number
ESP32-C6, ESP32-H2 and ESP32-C3
=> risc-v/espressif: Fix empty cpuint number

include/nuttx/mm/map.h
This patch uses `struct mm_map_entry_s` instead of the non-existing  `struct mm_map_entry` for the  `flink` field definition, it also includes minor revision on comments.
None
CI checks
=> mm/map.h:  minor revision on comments and field defs

arch/arm/src/am335x/am335x_lcdc.c
The check `if (delta < 0)` in line 353 and 407 would always be false if delta were unsigned.
=> arch/arm/src/am335x: Fix incorrect signedness of variable

arch/arm/src/cxd56xx/cxd56_nxaudio.c, arch/arm/src/kinetis/kinetis_usbdev.c, binfmt/libelf/libelf_coredump.c
Fix accessing uninitialized local variables in several functions.
Specifically in elf_emit() and elf_emit_align(), ret was uninitialized if total was 0.
spresense:audio 
freedom-k28f:nshsdusb
=> all: Fix accessing uninitialized local variables

arch/arm/src/s32k3xx/s32k3xx_pin.c
=> arch/arm/src/s32k3xx: Fix incorrect check for invalid port or pin number

Documentation/guides/customapps.rst
As per [Issue 12002](https://github.com/apache/nuttx/issues/12002) corrects error/omission in CustomApps guide
Easier to understand
=> Correct error/omissions in Custom Apps guide

drivers/ioexpander/icjx.c, drivers/ioexpander/icjx.h, include/nuttx/ioexpander/icjx.h
iC-JX expander has NINT (not an interrupt) pin that goes to logical zero if interrupt occurs. This commit adds support for iC-JX options settings that allows to enable the interrupt for defined input pins.
The interrupt is handled in HP worker thread to avoid waiting for SPI transfers in interrupt context. Board has to configure interrupt event for GPIO pin connected to NINT.
iC-JX new functionality.
Tested on SAMv7 custom board with iC-JX expander conencted over SPI.
=> ioexpander/icjx: add support for change of input interrupts on NINT

include/nuttx/timers/pwm.h
`PWM_CPOL_xxxx` helper defines and `uint8_t cpol` in the `struct pwm_chan_s` have been added to define the polarity of the running PWM. The only driver that has supported it up to this day was the samv7's one.
However, as with SAMV7 when the channels get turned off, the output polarity of the PWM channel (even if it's not running) also depend on the `cpol` field. This may cause the following problem:
- a certain polarity during runtime is desired, the user sets it
- however when the PWM operation is turned off, a default value should be set (for example a logical zero). If the default value of the disabled channel is undefined, it can cause trouble (undesired high outputs, etc...).
This new attribute extends the `struct pwm_chan_s` (and `struct pwm_info_s`) that defines PWM's output value …
=> include/nuttx/timers/pwm.h: add dcpol attribute to pwm_chan_s

drivers/video/isx019.c
Because the exposure time and ISO sensitivity are adjusted automatically by default, the default value can not be defined.
So, return the value out of range as the default_value of ioctl(VIDIOC_QUERYCTRL).
=> {bp-11999} drivers/video/isx019: Fix the default_value of some parameters

drivers/video/isx019.c
Fix default_value of ioctl(VIDIOC_QUERYCTRL)(id=V4L2_CID_3A_STATUS) to AE operating and AWB operating, because both AE and AWB are automatical adjustment mode by default.
=> {bp-11994} drivers/video/isx019: Fix default_value of 3A status

include/nuttx/mm/kmap.h
Fix typo in comments for kmm_map() function.
=> {bp-11998} mm/kmap.h: fix typo in comments

arch/arm/src/stm32h7/stm32_serial.c
Fixed logic error as noted by @kk-thrane
Correct logic
px4_fmu-v6x serial_test / gps / qgc
=> {bp-11990} stm32h7:Serial Fix Logic error in up_dma_txavailable

arch/arm/src/s32k3xx/s32k3xx_pin.c
=> {bp-12046} arch/arm/src/s32k3xx: Fix incorrect check for invalid port or pin number

arch/arm/src/cxd56xx/cxd56_nxaudio.c, arch/arm/src/kinetis/kinetis_usbdev.c, binfmt/libelf/libelf_coredump.c
Prior to this commit, in elf_emit() and elf_emit_align(), ret was uninitialized if total was 0.
=> {bp-12045} all: Fix accessing uninitialized local variables

arch/arm/src/am335x/am335x_lcdc.c
The check `if (delta < 0)` in line 353 and 407 would always be false if delta were unsigned.
=> {bp-12047} arch/arm/src/am335x: Fix incorrect signedness of variable

boards/arm/rp2040/raspberrypi-pico/configs/nshsram/defconfig
Summary:
- This commit fixes https://github.com/apache/nuttx/issues/11956.
- The issue was introduced by https://github.com/apache/nuttx/pull/6118.
Impact:
- None
Testing:
- Tested with raspberrypi-pico.
- NOTE: the ci should be fixed later.
=> {bp-12024} boards: raspberrypi-pico: Fix nshsram build error

arch/xtensa/src/esp32s3/esp32s3_spiflash.c
One page program can't span over 2 pages.
=> {bp-12008} xtensa/esp32s3: Fix one page program span over 2 pages

arch/risc-v/src/common/espressif/esp_irq.c
Bugfix which came from as https://github.com/apache/nuttx/issues/11980
risc-v/espressif: Fix empty cpuint number
ESP32-C6, ESP32-H2 and ESP32-C3
=> {Bp-12036} risc-v/espressif: Fix empty cpuint number

sched/sched/sched_addreadytorun.c
Prior to this commit, doswitch is returned uninitialized if (task_state == TSTATE_TASK_ASSIGNED || task_state == TSTATE_TASK_RUNNING) && no context switch occurs
&& (cpu == me).
sabre-6quad:smp
=> {bp-12031} SMP: Fix returning uninitialized variable in nxsched_add_readytorun()

drivers/mtd/filemtd.c
1. filemtd adds markbad and isbad interfaces (dummy) to support nandflash file systems (like Yaffs).
2. The return value of the "file_erase" interface is changed to erase nblocks
filemtd extension
I used Yaffs as the test file system, which can now be mounted on a file through filemtd
=> filemtd supports Nand-like file systems

net/bluetooth/bluetooth_conn.c, net/can/can_conn.c, net/icmp/icmp_conn.c, net/icmpv6/icmpv6_conn.c, net/ieee802154/ieee802154_conn.c, net/netlink/netlink_conn.c, net/pkt/pkt_conn.c, net/tcp/tcp_conn.c, net/udp/udp_conn.c, net/usrsock/usrsock_conn.c
return NULL only when the total number is larger than configured value
net
ci
=> net: Fix max conn always one less than configured value

Documentation/components/net/nat.rst, net/nat/Kconfig, net/nat/ipv4_nat.c, net/nat/ipv4_nat_entry.c, net/nat/nat.h
NAT: Support "Symmetric NAT" besides current "Full Cone NAT"
The symmetric NAT limits one external port to be used with only one peer ip:port.
Note:
1. To avoid using too much `#ifdef`, we're always passing `peer_ip` and `peer_port` as arguments, but won't use them under full cone NAT, let the compiler optimize them.
2. We need to find port binding without peer ip:port, so don't add peer ip:port into hash key.
3. Symmetric NAT needs to *select another external port if a port is used by any other NAT entry*, this behavior is exactly the same as Full Cone NAT, so we don't need to change anything related to `ipv4_nat_port_inuse`.
net/nat module, with Konfig controlled.
Manually with methods in nat.rst
=> net/nat: Support Symmetric NAT

arch/arm/src/stm32h7/stm32_i2c.c
This fixes a very nasty bug in the I2C driver for STM32H7 MCUs if anyone tries sending a chunk of data larger than 255 bytes. 
For TC interrupt to be triggered NBYTES needs to be set before RELOAD is disabled, otherwise, an interrupt will never happen, and implemented logic for handling data larger than 255 bytes will not work.
=> stm32h7/stm32_i2c: fix sending large data over i2c

arch/arm/src/stm32h7/Kconfig, arch/arm/src/stm32h7/stm32_fdcan_sock.c
Fixed kconfig and debug register for stm32h7 
Enable debug messages for FDCAN for stm32h7
Enable fdcan debug messages.
=> stm32h7/fdcan: fixed kconfig and debug register

arch/sim/Kconfig
Missing ARCH_TOOLCHAIN_GNU option causes sim's kasan recursion
NO
NO
=> sim/kconfig: select ARCH_TOOLCHAIN_GNU

arch/arm64/src/imx9/imx9_flexio_pwm.c
This error was left in the original PR, I messed up with re-basing patches accross branches. The duty cycle is a 16.16 fixed point integer (ub16) between 0-1. 
Tested with logic analyzer & i.MX93EVK board.
=> arch/arm64/src/imx9/imx9_flexio_pwm.c: Fix wrong input scale

arch/arm/src/stm32h7/Kconfig, arch/arm/src/stm32h7/stm32_fdcan_sock.c
Fixed kconfig and debug register for stm32h7
Enable debug messages for FDCAN for stm32h7
Enable fdcan debug messages.
=> {bp-12083} stm32h7/fdcan: fixed kconfig and debug register

arch/arm/src/stm32h7/stm32_i2c.c
To trigger TC interrupt NBYTES needs to be set before RELOAD is disabled
This fixes a very nasty bug in the I2C driver for STM32H7 MCUs if anyone tries sending a chunk of data larger than 255 bytes.
For TC interrupt to be triggered NBYTES needs to be set before RELOAD is disabled, otherwise, an interrupt will never happen, and implemented logic for handling data larger than 255 bytes will not work.
=> {bp-12093} stm32h7/stm32_i2c: fix sending large data over i2c

net/bluetooth/bluetooth_conn.c, net/can/can_conn.c, net/icmp/icmp_conn.c, net/icmpv6/icmpv6_conn.c, net/ieee802154/ieee802154_conn.c, net/netlink/netlink_conn.c, net/pkt/pkt_conn.c, net/tcp/tcp_conn.c, net/udp/udp_conn.c, net/usrsock/usrsock_conn.c
return NULL only when the total number is larger than configured value
net 
ci
=> {bp12080 }net: Fix max conn always one less than configured value

net/can/can.h, net/can/can_conn.c, net/can/can_input.c
Because CAN is a broadcast protocol, each conn needs to be given independent data to avoid mutual interference.
sim:local
=> net/can: deliver data into multiple CAN conn bound to same dev

arch/arm/src/stm32f7/stm32f76xx77xx_rcc.c
Value was set with PLLSAI factor divisors instead of PLLI2S factor divisors.
Fix I2S clock
stm32f777 board
=> stm32f76xx77xx_rcc: Fix PLLI2S factor divisors

include/nuttx/sched.h, sched/pthread/pthread_completejoin.c, sched/pthread/pthread_detach.c, sched/pthread/pthread_join.c
sched/pthread: detached thread should destroy the join info
In order to ensure the detached thread obtain the correct return value from pthread_join()/pthread_cancel(), the detached thread will create joininfo to save the detached status after thread destroyed.  If there are too many of detached threads in the process group, the joininfo will consume too much memory. This is not friendly to embedded MCU devices.
This commit keep the semantics as #11898 was introduced, will no longer save joininfo for detached threads to avoid wasting memory.
Fix issue https://github.com/apache/nuttx/issues/12096
ostest / ci-check
=> sched/pthread: detached thread should destroy the join info

net/nat/ipv4_nat.c, net/nat/ipv4_nat_entry.c
1. Reduce getting `old_ip` in `ipv4_nat_ip_adjust`.
2. Some format change.
Minor
Manually
=> net/nat: Slightly optimize the IPv4 NAT

arch/arm64/src/Toolchain.defs
Just add -mcpu=cortex-a55 to compilation flags if  CONFIG_ARCH_CORTEX_A55 is defined.
Might impact only cortex-a55 targets
Tested on imx93 evk board
=> Add -mcpu=cortex-a55

arch/xtensa/src/esp32s3/Kconfig, arch/xtensa/src/esp32s3/esp32s3_gpio.c
1. ESP32S3 GPIO pin 19 or 20 by default connected to USB/JTAG controller. When using pin 19 or 20 as GPIO, disable USB/JTAG
2. arch/xtensa/src/esp32s3/Kconfig updated: I2S BCLK, WSPIN, DINPIN, DOUTPIN pin range changed to 0 48
pin 19, 20 can be used for other purposes.
pins > 33 can now be used for I2S0 and I2S1 in ESP32S3
Tested on ESP32S3-WROOM-1, ESP32S3-MINI-1
=> ESP32S3 configuring gpio pin 19 or 20 ( USB_D+/- ) for purposes other than USB/JTAG Controller and I2S pin selection range fixed

arch/risc-v/include/csr.h
This patch adds more debug related CSR definitions to arch/risc-v/include/csr.h.
These definitions are from the RISC-V Debug Specification Version 1.0 rc1 (https://github.com/riscv/riscv-debug-spec).
None, new register/opcode definition
CI
=> riscv: Add more debug related CSR definitions

sched/timer/timer_initialize.c
all other g_alloctimers being protect by spin_lock_irqsave
=> timer: use spin_lock_irqsave protect g_alloctimers

arch/risc-v/include/thead/c9xx_csr.h, arch/risc-v/src/c906/c906_head.S, arch/risc-v/src/c906/chip.h
Add T-HEAD CSR mapping file. This allow user to access T-HEAD CSR in the way of #12117.
=> arch/riscv: add T-HEAD CSR mapping

net/nat/nat.c, net/tcp/tcp_conn.c, net/udp/udp.h, net/udp/udp_conn.c, net/udp/udp_sendto_buffered.c, net/utils/utils.h
Optimize TCP/UDP port selection, and fix possibly dead loop.
Finish discussion in https://github.com/apache/nuttx/pull/12116#discussion_r1560851977
Note:
Linux also uses `EADDRINUSE` for failing in finding a portno, according to https://man7.org/linux/man-pages/man2/bind.2.html#ERRORS
TCP / UDP / NAT Port selection
Manually
- Set `CONFIG_NET_DEFAULT_MAX_PORT` close to `CONFIG_NET_DEFAULT_MIN_PORT`, and create several UDP sockets (iperf2 on Vela), we can get "udp_connect: ERROR: Failed to get a local port!" and "udp connect failed: Address already in use"
=> net: Optimize TCP/UDP port selection

sched/irq/irq_csection.c
1. The critical section does not prevent task scheduling
2. If the critical section is in sched_lock, there is no need to check, scheduling is not going to happen
3. If sched_lock is in the critical section, sched_unlock will also trigger scheduling without waiting for the exit of the critical section
4. After exiting the critical section, if there is an interrupt, the scheduling will be automatically triggered
5.
=> sched/irq: remove scheduling check in csection

net/nat/ipv4_nat.c, net/nat/ipv4_nat_entry.c, net/nat/ipv6_nat.c, net/nat/ipv6_nat_entry.c, net/nat/nat.h
- net/nat: Rename `struct ipv*_nat_entry` to `ipv*_nat_entry_t`
- I found `struct ipv*_nat_entry` is missing `_s` suffix, but the name is too long in some cases, so maybe `ipv*_nat_entry_t` could be better.
- net/nat: Remove unnecessary logic in inbound logic
- Finish https://github.com/apache/nuttx/pull/12116#discussion_r1560880897
Minor
CI
=> net/nat: Minor code optimizations

arch/risc-v/src/esp32c3-legacy/Kconfig, arch/risc-v/src/esp32c3-legacy/Make.defs, arch/risc-v/src/esp32c3-legacy/esp32c3_ice40.c, arch/risc-v/src/esp32c3-legacy/esp32c3_ice40.h, boards/risc-v/esp32c3-legacy/common/include/esp32c3_board_ice40.h, boards/risc-v/esp32c3-legacy/common/src/Make.defs, boards/risc-v/esp32c3-legacy/common/src/esp32c3_board_ice40.c, boards/risc-v/esp32c3-legacy/esp32c3-devkit/src/esp32c3_bringup.c, drivers/spi/Kconfig, drivers/spi/Make.defs, drivers/spi/ice40.c, include/nuttx/fs/ioctl.h, include/nuttx/spi/ice40.h
drivers/spi: Add support for FPGA iCE40 bitstream loading.
Allows loading of bitstream directly from filesystem, either using ioctl or directly by using e.g. "cp example_bitstream.bin /dev/ice40-0"
arch and board esp32c3-legacy: Add optional iCE40 FPGA loading support 
It should have no impact when CONFIG_SPI_ICE40 is not set (which is default)
Tested on ICE-V-Wireless board.
https://github.com/ICE-V-Wireless/ICE-V-Wireless
=> drivers/spi: Add support for FPGA iCE40 bitstream loading.

tools/configure.sh
This patch supports listing configs for a given board like
- `tools/configure.sh -L sama5`
- `tools/configure.sh -L rv-virt`
- `tools/configure.sh -L virt`
None
CI checks
=> tools/configure.sh: support listing configs for board

arch/arm/src/sama5/sam_adc.c, arch/arm/src/sama5/sam_tsd.c, arch/arm/src/sama5/sam_tsd.h
Ongoing work using the SAMA5(D2) touchscreen device demonstrated a number of shortcomings with the existing driver, as well as finding a few style errors.
The main issue was poor touch response as well as interactions with the ADC functions when used in conjunction with the TSD, so there are changes that improve that, although in the end not all may have been necessary but they do make the driver a little more flexible and more predictable in its behaviour.
Intended that the changes are benign and would not affect anyone using the driver already in a negative way
Custom board with a SAMA5D27C-D1G and 800x480 LCD with resistive touch.
=> Improvements relating to SAMA5 TSD driver

arch/risc-v/src/common/riscv_addrenv.c
This patch fixes [issue 12123](https://github.com/apache/nuttx/issue/12123) and [issue 11803](https://github.com/apache/nuttx/issue/11803) for RV32, where the walk should be limited to user space only.
RV32 kernel mode
rv-virt/knsh32 with DEBUG_ASSERTIONS enabled.
=> arch/risc-v: fix RV32 addrenv destroy issue

drivers/video/v4l2_cap.c, include/nuttx/video/video.h
since it is only used in v4l2_cap.c.
minor
ci
=> video: Move video_format_s from video.h to v4l2_cap.c

arch/arm64/src/common/Make.defs, arch/arm64/src/common/arm64_arch.h, arch/arm64/src/common/arm64_modifyreg16.c, arch/arm64/src/common/arm64_modifyreg32.c, arch/arm64/src/common/arm64_modifyreg8.c
These are needed by drivers
Add atomic modifyreg for arm64
imx93
=> arch/arm64: Add atomic modifyregXX

tools/uncrustify.cfg
This patch disables leading spaces removal for block comments so that to avoid changing well-formatted blocking comments.
Without this well-formmated leading blocking comments of C source files will be changed unwantedly as the leading spacs are removed, based on test use with uncrustify 0.72.0+dfsg1-2 on Ubuntu.
code formatter
CI checks
=> tools/uncrustify: disable leading space removal for block comment

arch/arm64/include/imx9/imx93_irq.h, arch/arm64/src/imx9/imx9_gpio.h, arch/arm64/src/imx9/imx9_gpioirq.c
The original assumption was that the interrupt numbers are divided
so that 16 pins from 1 port are handled by a single interrupt source.
So source 0 would handle pins 0-15 and source 1 would handle pins 16-31.
This assumption is wrong, each pin has two sources, thus there are two
interrupt lines for each pin.
The driver uses source 0, and leaves source 1 disabled.
Fix several bugs in the gpioirq driver
imx93
=> imx93_gpioirq: Fix the GPIO interrupt source names

arch/arm64/src/imx9/imx9_iomuxc.h
- Add missing include guard
- Add missing C++ guard
- Fix the initialization ordering in IOMUX_PADCFG macro. Why ? Becaused of:
imx9_iomuxc.h:54:3: error: designator order for field 'iomux_padcfg_s::dsyreg' does not match declaration order in 'iomux_padcfg_s'
54 |   }
|
Fix the header file
Build passes without errors
=> imx9_iomux.h: Fix issues with the header file

arch/risc-v/src/common/espressif/esp_start.c
Currently Simple Boot image have fixed 2 ROM segments and 2 RAM segments, then the parsing iterator must stop when all ROM segments are found.
Internal CI testing +
=> esp32[c3|c6|h2]: Fix simple boot map_rom_segments

arch/arm/src/samv7/Kconfig, arch/arm/src/samv7/sam_qencoder.c
The SAMV7's qencoder driver now supports the GETINDEX ioctl call which does not reset the internal Timer/Counter and returns the current position, position of the last index and the number of captured indexes to a struct qe_index_s pointer. Because the SAMV7's timers are 16bit, the extension to 32 bits must be done.
Select CONFIG_SAMV7_QENCODER_ENABLE_GETINDEX in the Kconfig to enable this functionality.
This driver does not obey the instructions given in the ATSAMV7 2023 datasheet because the recommended trigger resets the internal counter which is not desired. Instead, a capture into capture A and capture B registers is used. This way if an event happens (the rising edge of the index signal), the current counter's value is captured.
=> arch/arm/src/samv7/sam_qencoder.c: add support for GETINDEX ioctl call

arch/sim/src/sim/sim_wifidriver.c, tools/simwifi/sim_wifi.sh
The first patch is to close the nuttx0 node when executing the clean command（sudo ./tools/simwifi/sim_wifi.sh clean eno1）
The second patch is to solve the problem of not being able to find the  simwifi script for non native compiled versions
simwifi
**The first patch test case**：
wangchen@wangchen-OptiPlex-7080:~/complie/vela_dev_0415/nuttx$ sudo ./tools/simwifi/sim_wifi.sh init eno1 hwsim
init env
start bridge to eno1
[set_state] new state:SW_INIT
state:SW_INIT wlan_if:, br_if:nuttx0 wan_if:eno1
wangchen@wangchen-OptiPlex-7080:~/complie/vela_dev_0415/nuttx$ ifconfig
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 10.221.99.130  netmask 255.255.224.0  broadcast 10.221.127.255
inet6 fe80::862:7440:ebaa:de33  prefixlen 64  scopeid 0x20<link>
ether b0:7b:25:25:67:44 …
=> simwifi:Modify the existing implementation of the simwifi script

include/nuttx/compiler.h, include/stdlib.h, libs/libc/stdlib/CMakeLists.txt, libs/libc/stdlib/Make.defs, libs/libc/stdlib/lib_reallocarray.c
This commit adds support for `reallocarray` function. The functionality is the same as for standard `realloc`, but the function also checks for multiplication overflow and fails safely in case it occurs. This is not POSIX, however the function is part of standard C library.
=> libc: add support for reallocarray

arch/arm64/src/imx9/imx9_boot.c, arch/arm64/src/imx9/imx9_gpioirq.c
Add initialization of pin interrupt support to generic platform code.
Also, fix a bug in enabling the pin interrupt. The value of pinset.icr should not be shifted, as when it is tested below against e.g. GPIO_INT_LOWLEVEL which is already shifted to the correct position.
Pin interrupts are initialized.
imx93-evk
=> imx9_boot.c: Add initialization of pin interrupts

boards/arm/stm32/common/src/CMakeLists.txt
Add ds1307 to CMake build
User could use CMake to build boards with ds1307
N/A
=> boards/stm32: Add ds1307 to CMake build

include/netpacket/netlink.h, net/nat/ipv4_nat_entry.c, net/nat/ipv6_nat_entry.c, net/nat/nat.h, net/netlink/CMakeLists.txt, net/netlink/Kconfig, net/netlink/Make.defs, net/netlink/netlink.h, net/netlink/netlink_conn.c, net/netlink/netlink_netfilter.c, net/netlink/netlink_route.c, net/netlink/netlink_sockif.c
- net/netlink: Add `NETLINK_NETFILTER`'s `CONNTRACK` support
- net/netlink: Move netlink_add_terminator as public
- net/nat: Add foreach interface for entries
Now we only supports conntrack (`NF_NETLINK_CONNTRACK_*`) info from NAT entries, to let our apps in user space know the mapping status in NAT.
New netlink family (`NETLINK_NETFILTER`) support, only implemented conntrack, under control of `CONFIG_NETLINK_NETFILTER`
Together with userspace's `conntrack` command (https://github.com/apache/nuttx-apps/pull/2356), which behaves similar to Linux's one on NAT connections.
=> net/netlink: Add NETLINK_NETFILTER's CONNTRACK support

arch/Kconfig, mm/Kconfig
This treats kernel space virtual memory allocation based mappings similar to that of the user space:
- Add ARCH_KVMA_MAPPING to guard kernel mapping configs.
- Set dependency from MM_KMAP to ARCH_KVMA_MAPPING, as per commit 70de321de3f. 
None
CI checks
=> arch/kconfig: revise kernel mapping configs

arch/risc-v/include/csr.h
The CSR register definitions from RVV 1.0 spec: https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#vector-registers
None
CI
=> riscv: Add Vector CSRs to csr.h

sched/misc/CMakeLists.txt, sched/misc/Make.defs, sched/sched/CMakeLists.txt, sched/sched/Make.defs, sched/sched/sched_dumponexit.c
The dump.c is a part of sched module, so move it to sched directory.
code reorganization.
ci
=> sched: Move dump.c to sched_dumponexit.c

Documentation/platforms/arm64/imx9/boards/imx93-evk/README.txt
It is advisable to set bootdelay to 0 when using bootcmd to disable dcache on u-boot. Using bootdelay -1 will definitely work as it disables bootcmd altogether (and leaves the dcache enabled). This step is added to remove confusion.
Only documentation, but I think this information can save someone's time if they use imx9evk with u-boot and nuttx
None
=> imx93-evk/README.txt: Update instructions

drivers/misc/rwbuffer.c
when the offest from rwb->wrblockstart to startblock plus rwb->wrnblocks is greater than rwb->wralignblocks, it will be causing memory overflow since rwb->wrbuffer is allocated rwb.wrmaxblock(rwb.wralignblocks) blocks.
=> fix: the bug about rwbuffer causing mem overflow

Documentation/components/libs/libc/index.rst, Documentation/reference/os/conventions.rst
This fixes a few typos in conventions.rst and libc/index.rst.
None
CI checks
=> docs/os: fix typos

drivers/syslog/syslog_intbuffer.c, sched/misc/assert.c
purpose:
1 sched_lock is very time-consuming, and reducing its invocations can improve performance.
2 sched_lock is prone to misuse, and narrowing its scope of use is to prevent people from referencing incorrect code and using it
test:
compiling
running
=> sched_lock: we can remove these sched_lock,

boards/Kconfig, drivers/usbdev/composite.c, drivers/usbdev/mtp.c, include/nuttx/board.h, include/nuttx/usb/mtp.h
drivers/usbdev: fix complile break about mtp class
fix compile break
testing vela
=> drivers/usbdev: fix complile break about mtp class

arch/risc-v/src/common/riscv_internal.h
arch/risc-v: rename local variable name to avoid shadowed declaration
```
In file included from common/addrenv.h:33,
from common/riscv_initialstate.c:36:
common/riscv_initialstate.c: In function 'up_initial_state':
common/riscv_internal.h:136:16: warning: declaration of 'regval' shadows a previous local [-Wshadow]
136 |      uintptr_t regval; \
|                ^~~~~~
common/riscv_initialstate.c:74:12: note: in expansion of macro 'READ_CSR'
74 |   regval = READ_CSR(CSR_VLENB);
|            ^~~~~~~~
common/riscv_initialstate.c:63:13: note: shadowed declaration is here
63 |   uintptr_t regval;
|             ^~~~~~
```
N/A
ci-check
=> arch/risc-v: rename local variable name to avoid shadowed declaration

arch/x86_64/include/intel64/arch.h, arch/x86_64/src/intel64/intel64.h, arch/x86_64/src/intel64/intel64_handlers.c, arch/x86_64/src/intel64/intel64_irq.c, arch/x86_64/src/intel64/intel64_lowsetup.h, arch/x86_64/src/intel64/intel64_start.c
- intel64/intel64_irq.c: cosmetic change
- intel64: add header for intel64_lowsetup
- intel64/intel64_handlers.c: cosmetic changes
- intel64/arch.h: fix ist_t structure, there is no reserved5 field
None, cosmetic changes
CI
=> intel64: various cosmetic changes

drivers/misc/rwbuffer.c
issue: https://github.com/apache/nuttx/pull/12188
in rwb_wrflush():
memmove(rwb->wrbuffer + padblocks * rwb->blocksize, rwb->wrbuffer, rwb->wrnblocks * rwb->blocksize);
when the offest from rwb->wrblockstart to startblock plus rwb->wrnblocks is greater than rwb->wralignblocks, it will be causing memory overflow since rwb->wrbuffer is allocated rwb.wrmaxblock(rwb.wralignblocks) blocks.
fix:
Let us ensure that the wrblockstart in rwbuffer must be aligned according to wralignblocks after writing, so there is no need to perform memmove when flushing
fix rwbuffer overflow
=> drivers/misc/rwbuffer: fix rwbuffer overflow issue

arch/x86_64/src/common/x86_64_acpi.c
- x86_64_acpi.c: make sure that RSDP is mapped
rsdp memory may be not mapped when provided from multiboot2 header. For some reason the previous code worked on some machines.
qemu
=> x86_64_acpi.c: make sure that RSDP is mapped

include/inttypes.h, libs/libc/inttypes/CMakeLists.txt, libs/libc/inttypes/Make.defs, libs/libc/inttypes/lib_imaxdiv.c
imaxdiv() is in C99 and Open Group specifications, was missing from NuttX.
=> libs/libc/inttypes: add support for imaxdiv

arch/arm64/src/imx9/Kconfig, arch/arm64/src/imx9/imx9_boot.c
ARMv8.2-A has PSCI -> it also has support for system reset
Add support for system reset with imx9
imx9-evk:nsh
=> arch/imx9: Add PSCI (system reset) support

drivers/usbdev/Kconfig, drivers/usbdev/composite.c, drivers/usbdev/usbdev_fs.c, drivers/usbdev/usbdev_req.c
Solve some problems in usbdev fs see commit message for details.
usbdev fastboot/adb
testing vela
=> drivers/usbdev/fs: fix issue between adb/fastboot/mtp and usbdev fs

boards/xtensa/esp32s3/common/scripts/legacy_sections.ld
Fix ESP32-S3 legacy boot initialization.
=> xtensa/esp32s3: Add missing entries to iram.text from legacy_sections.ld

fs/tmpfs/fs_tmpfs.c, fs/tmpfs/fs_tmpfs.h
Added support for FIOC_FILEPATH in tmpfs. Now we can use ioctl to get the path of tmpfs corresponding to fd
```
ioctl(fd, FIOC_FILEPATH, &path)
```
tmpfs adds “ioctl” support
Local test PASS
=> tmpfs:Add ioctl access path function

arch/arm/src/armv7-a/crt0.c, arch/arm64/src/common/crt0.c, arch/risc-v/src/common/crt0.c, tools/Export.mk, tools/mkexport.sh, tools/toolchain.cmake.export
This fixes names of program entry and linker script files so that to support building kernel mode apps using CMake and exported package.  The behavior for flat/protected build modes is same as before.
CMake use cases
CI checks
=> cmake/export: fix kernel mode app building

arch/risc-v/src/bl808/bl808_head.S, arch/risc-v/src/common/riscv_common_memorymap.h, arch/risc-v/src/common/riscv_cpuidlestack.c, arch/risc-v/src/jh7110/jh7110_head.S, arch/risc-v/src/k210/k210_head.S, arch/risc-v/src/k230/k230_head.S, arch/risc-v/src/qemu-rv/qemu_rv_head.S
arch/risc-v: remove the hard code array of cpu idle stack
Do not limit the number of CPU idle stacks by hard code
N/A
rv-virt/smp, rv-virt/smp64,
=> arch/risc-v: remove the hard code array of cpu idle stack

fs/procfs/fs_procfsmeminfo.c
This makes `free` output line width to fit most terminals for easy reading.
None
`rv-virt/knsh32` `rv-virt/nsh64` plus CI checks
=> procfs/meminfo: fit line width in 80 chars

arch/x86_64/src/common/x86_64_acpi.c
- x86_64_acpi.c: avoid debug messages in acpi_init()
acpi_init() must be called early during boot, some system components may be unavailable at this stage, so debug messages won't work
qemu and hw
=> x86_64_acpi.c: avoid debug messages in acpi_init()

arch/arm/src/lpc17xx_40xx/lpc17_40_i2c.c
Fixes a potential state machine desynchronization in the I2C driver of LPC17xx & LPC40xx.
When the I2C driver needs to transmit a new message, [lpc17_40_i2c_start](https://github.com/apache/nuttx/blob/master/arch/arm/src/lpc17xx_40xx/lpc17_40_i2c.c#L223C12-L223C30) is called, that [waits on a semaphore](https://github.com/apache/nuttx/blob/master/arch/arm/src/lpc17xx_40xx/lpc17_40_i2c.c#L255) till the transaction is complete. This semaphore can be posted in two places, allowing the code to continue: when the transaction is [finished](https://github.com/apache/nuttx/blob/master/arch/arm/src/lpc17xx_40xx/lpc17_40_i2c.c#L279) and when there is a [timeout](https://github.com/apache/nuttx/blob/master/arch/arm/src/lpc17xx_40xx/lpc17_40_i2c.c#L296).
As it turns out, in some rare cases it is …
=> lpc17_40 i2c: Fix I2C driver state desynchronization.

tools/configure.sh
* Extends tools/configure.sh default appdir search paths.
* Search for apps in ../nuttx-apps and ../nuttx-apps.git locations.
* This allows -a parameter skip when nuttx-apps or nuttx-apps.git is used.
Signed-off-by Tomasz 'CeDeROM' CEDRO <tomek@cedro.info>
* This simple patch adds default search path for application code in `../nuttx-apps` and `../nuttx-apps.git` by `tools/configure.sh` script.
* When code is cloned with `git clone` the work dirs are usually `nuttx` / `nuttx.git` and `nuttx-apps` / `nuttx-apps.git`.
* This allows `-a` parameter skip in `tools/configure.sh` when `../nuttx-apps` or `../nuttx-apps.git` is used in addition to `../apps`.
Please verify :-)
=> Extend default appdir list.

arch/risc-v/src/common/riscv_testset.S
arch/riscv: replace atomic operations to AMO
RISC-V provided fetch-and-op style atomic primitives as they scale to highly parallel systems better than LR/SC or CAS. A simple microarchitecture can implement AMOs using the LR/SC primitives, provided the implementation can guarantee the AMO eventually completes. More complex implementations might also implement AMOs at memory controllers, and can optimize away fetching the original value when the destination is x0.
https://github.com/riscv/riscv-isa-manual/blob/main/src/a-st-ext.adoc
Co-authored-by: Petro Karashchenko <petro.karashchenko@gmail.com>
https://github.com/apache/nuttx/issues/6569
Closes #6569 
N/A
rv-virt/smp64  rv-virt/smp
=> arch/riscv: replace atomic operations to AMO

arch/risc-v/Kconfig, arch/risc-v/src/Makefile, arch/risc-v/src/common/CMakeLists.txt, arch/risc-v/src/common/Make.defs, arch/risc-v/src/common/riscv_cpustart.c, arch/risc-v/src/common/riscv_macros.S, arch/risc-v/src/common/supervisor/Make.defs, arch/risc-v/src/k230/k230_start.c, arch/risc-v/src/litex/litex_start.c, arch/risc-v/src/mpfs/mpfs_start.c, arch/risc-v/src/qemu-rv/qemu_rv_start.c
arch/risc-v: decouple Per-CPU scratch with ARCH_USE_S_MODE
In some special chipsets, multiple CPUs may be bundled in one hardware thread cluster, which results in hartid and cpuindex not being exactly the same. The new option will decouple Scratch-based Per-CPU storage with S-Mode to distinguish the real cpu index.
N/A
rv-virt/smp64
=> arch/risc-v: decouple Per-CPU scratch with ARCH_USE_S_MODE

arch/arm64/src/imx9/Kconfig, arch/arm64/src/imx9/hardware/imx93/imx93_ccm.h, arch/arm64/src/imx9/hardware/imx93/imx93_pll.h, arch/arm64/src/imx9/imx9_boot.c, arch/arm64/src/imx9/imx9_clockconfig.c, arch/arm64/src/imx9/imx9_clockconfig.h, boards/arm64/imx9/imx93-evk/include/board.h
This set of patches adds two things for iMX9:
- A way to set PLL frequencies
- A way to query PLL frequencies
The frequencies should be set during bootup, it is the responsibility of the second stage program loader (bootloader) to do this.
For most peripherals it is also important to know the root clock frequency, in order to calculate data rate for the peripheral.
Adds PLL support for iMX9
imx93-evk:nsh
=> imx9_clockconfig: Add way to change and ask for PLL frequency

arch/risc-v/src/qemu-rv/qemu_rv_start.c
arch/risc-v: fix break on kernel mode
merge conflicts lead to incorrect ifdef/endif scope
Regression by: https://github.com/apache/nuttx/pull/12220
N/A
ci-check
=>  arch/risc-v: fix break on kernel mode

arch/Kconfig
- arch/x86_64: enable CUSTOMOPT
allow to use CONFIG_DEBUG_CUSTOMOPT
=> arch/x86_64: enable CUSTOMOPT

boards/arm/stm32/common/src/stm32_bh1750.c
boards/arm/stm32/common/src/stm32_bh1750.c: fix include
should include i2c interface, not spi
ci
=> boards/arm/stm32/common/src/stm32_bh1750.c: fix include

drivers/sensors/adxl362_uorb.c, drivers/sensors/adxl372_uorb.c, drivers/sensors/bh1749nuc_uorb.c, drivers/sensors/bmi270_uorb.c, drivers/sensors/bmm150_uorb.c
- sensors/bh1749nuc_uorb.c: fix compilation when poll interface is disabled
- sensors/bmm150_uorb.c: fix compilation for poll interface
- drivers/adxl362_uorb: various fixes
- sensors/bmi270_uorb.c: fix condition for sensor stop
- sensors/adxl372_uorb: wait for data ready in thread
thingy53 and thingy91
=> drivers/sensors: various fixes for sensors

arch/risc-v/src/common/riscv_macros.S
Set right name for the parameter description of riscv_set_inital_sp.
This should improve https://github.com/apache/nuttx/pull/12178#discussion_r1581992407
=> arch/risc-v: Fix typo in riscv_set_inital_sp

drivers/sensors/bmi270_uorb.c
- sensors/bmi270_uorb.c: move init sequence to register function
otherwise default accel and gyro scale configured during registration is cleared
thingy53
=> sensors/bmi270_uorb.c: move init sequence to register function

arch/arm/src/samv7/Kconfig, arch/arm/src/samv7/sam_pwm.c
PWMx_CHy_LONLY options have been added to Kconfig, too. If LONLY is selected, it's not possible to use complementary outputs. If LONLY is not selected, it's possible to use H or complementary output. If configured correctly with cpol and dcpol attributes, a H-like behaviour can be achieved. May be useful when you run out of free MCU pins.
=> arch/arm/src/samv7/sam_pwm.c: option to enable only the L PWM outputs

net/icmpv6/icmpv6_autoconfig.c, net/icmpv6/icmpv6_neighbor.c
Skip neighbor solicitation on L3 Nic and skip IPv6 conflict detection on L3 Nic.
cortex-m33 and sim:local
=> Optimized the ipv6 sending of the Layer 3 NIC

net/tcp/tcp_getsockopt.c, net/tcp/tcp_setsockopt.c
TCP_NODELAY is an independent configuration and does not depend on TCP_KEEPALIVE
sim:local
=> tcp: decouple TCP_NODELAY and NET_TCP_KEEPALIVE

arch/arm/src/samv7/Kconfig, arch/arm/src/samv7/Make.defs, arch/arm/src/samv7/sam_qencoder.c, arch/arm/src/samv7/sam_qencoder.h
Option `CONFIG_SENSORS_QENCODER` might be configured even if SAMv7 qencoder over timer counter is not used (for example encoder over GPIO is selected with `CONFIG_SAMV7_GPIO_ENC`). This can cause compile warnings, also build of `sam_qencoder.c` file is unnecessary in that case.
New hidden option `CONFIG_SAMV7_QENCODER` is added and automatically selected if at least one timer counter is enabled for qencoder. Build is triggered on this option.
Fixes possible warnings (unused structures)
=> samv7: build sam_qencoder.c only if at least one timer counter is enabled

arch/xtensa/src/esp32s3/Kconfig
So that users can enable it.
This fixes a regression in "esp32s3: add simple boot support".
make oldconfig
=> esp32s3: give ESP32S3_APP_FORMAT_LEGACY a prompt

arch/risc-v/src/common/riscv_vpu.S
arch/risc-v: correct minor issues regarding comments
The comment in riscv_vpu.S should be vector not floating
https://github.com/apache/nuttx/pull/12184
N/A
ci-check
=> arch/risc-v: correct minor issues regarding comments

include/strings.h, libs/libc/string/lib_ffs.c, libs/libc/string/lib_ffsl.c, libs/libc/string/lib_ffsll.c, libs/libc/string/lib_fls.c, libs/libc/string/lib_flsl.c, libs/libc/string/lib_flsll.c
In the gcc-riscv compiler, __builtin_ffs will call ffs, and calling __builtin_ffs in ffs will cause recursion
__builtin_ffs --> ffs --> ffs --> ffs
Change ffs to an inline function, and compile ffs implemented by nuttx by default. Only call the implementation of nuttx when the compiler cannot provide an ffs implementation.
arm/riscv
=> libc/string: replace __builtin_ffsl with inline function

drivers/bch/bchdev_unregister.c, drivers/ioexpander/pcf8574.c, drivers/ioexpander/tca64xx.c, drivers/syslog/syslog_device.c, drivers/syslog/syslog_filechannel.c
purpose:
1 sched_lock is very time-consuming, and reducing its invocations can improve performance.
2 sched_lock is prone to misuse, and narrowing its scope of use is to prevent people from referencing incorrect code and using it
test:
compiling
running
=> driver: There is no need to use sched_[un]lock

arch/xtensa/src/esp32s3/hal.mk
Warning fix coming from [github](https://github.com/apache/nuttx/issues/12260)
Only ESP32-S3
=> arch/xtensa: Fix esp32s3 build warnings

arch/arm/src/imxrt/Kconfig, arch/arm/src/imxrt/imxrt_usdhc.c
With CONFIG_MMCSD_MULTIBLOCK_LIMIT not set. (No limit)
The DMA driver would overwrite the internal buffer.
By adding CONFIG_ARCH_HAVE_SDIO_PREFLIGHT and
CONFIG_FAT_DMAMEMORY we can insure alignment and
maximize performance using no CONFIG_MMCSD_MULTIBLOCK_LIMIT
Fixes hardfault if CONFIG_MMCSD_MULTIBLOCK_LIMIT !=1 and improves performance.  
px4_fmu-v6xrt
```
nsh> sd_bench
INFO  [sd_bench] Using block size = 4096 bytes, sync=0
INFO  [sd_bench]
INFO  [sd_bench] Testing Sequential Write Speed...
INFO  [sd_bench]   Run  0:  1332.81 KB/s, max write time: 115 ms (=  34.78 KB/s), fsync: 7 ms
INFO  [sd_bench]   Run  1:  1273.16 KB/s, max write time: 117 ms (=  34.19 KB/s), fsync: 9 ms
INFO  [sd_bench]   Run  2:  1462.41 KB/s, max write time: 10 ms (= 400.00 KB/s), fsync: 9 ms
INFO  [sd_bench] …
```
=> imxrt:Add DMA preflight Support

sched/wqueue/kwork_inherit.c
purpose:
1 sched_lock is very time-consuming, and reducing its invocations can improve performance.
2 sched_lock is prone to misuse, and narrowing its scope of use is to prevent people from referencing incorrect code and using it
test:
compiling
running
=> sched/wqueue: There is no need to use sched_[un]lock

cmake/nuttx_add_library.cmake
all targets that call `nuttx_add_kernel_library` will have the `__KERNEL__` macro definition added by default.
however, for example, when we build in FLAT mode, `libc` and other libraries should not need __KERNEL__ defined, only in `klibc` with Non-FLAT mode.
this patch distinguishes the target libraries that need to be `SPLIT`, solving this problem.
FLAT mode CMake build
CI
=> cmake:bugfix __KERNEL__ should not be defined with FLAT mode in libc, mm etc.

Documentation/platforms/risc-v/esp32c3/index.rst, Documentation/platforms/risc-v/esp32c6/index.rst
esp32[c3|c6]: Fix chipname on docs
ESP32-C3 and ESP32-C6
=> esp32[c3|c6]: Fix chipname on docs

arch/risc-v/src/common/riscv_addrenv_pgmap.c
The L2 table was not connected -> results in random crashes. Also add missing data sync barrier to the end.
Fix bug in riscv kmap
mpfs
=> riscv/pgmap: Fix bug in kernel page directory init

Documentation/platforms/risc-v/qemu-rv/boards/rv-virt/index.rst
Since SSTC is support by QEMU 7.2.9, kernel mode nuttx is no longer worked for older QEMU.
Add necessary requirement information for rv-virt board.
This should give some information for issues like #12275.
=> Documentation/rv-virt: add required minimal QEMU version information

sched/sched/sched_addreadytorun.c
test:
compiling
make distclean -j20; ./tools/configure.sh -l qemu-armv8a:nsh_smp ;make -j20 running qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic -machine virt,virtualization=on,gic-version=3 -net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel ./nuttx
=> scsched: sched: Simplify the scheduling logic in nxsched_add_readytorun() for SMP

arch/risc-v/src/bl602/bl602_allocateheap.c, arch/risc-v/src/bl602/bl602_head.S, arch/risc-v/src/bl602/bl602_start.c, boards/risc-v/bl602/bl602evb/scripts/ld.script
Although almost all board support allocating idle stack after ebss, bl602 have a different memory layout for idle stack. To unify them, make idle stack allocated from ebss for bl602. This will also improve #12265 as we can use `_ebss` for all board.
Although this patch should have no side effect. I have no idea about the memory layout of bl602. It seems the ld script of  this SoC describe a different memory layout from the [datasheet](https://github.com/bouffalolab/bl_docs/blob/main/BL602_DS/en/BL602_BL604_DS_1.6_en.pdf) from bouffalolab.
=> arch/risc-v: Make bl602 allocate idle stack after ebss

arch/arm/src/armv7-a/arm_initialstate.c, sched/sched/sched_addreadytorun.c
arch: armv7-a: Disable IRQ to make the A core policy consistent with the M core for TEE
=> tee: In tee, we need to disable the IRQ interrupt to make the A core policy consistent with the M core.

boards/arm/stm32l4/nucleo-l476rg/src/Makefile, boards/arm/stm32l4/nucleo-l476rg/src/stm32_appinit.c, boards/arm/stm32l4/nucleo-l476rg/src/stm32_bmp280.c, boards/arm/stm32l4/nucleo-l476rg/src/stm32_bmp280.h
This commit adds the support for the Bosch BMP280 pressure sensor to the ST Nucleo-L476RG board.
Nothing else is impacted.
It is tested on Nucleo-L476RG board and it is working fine.
=> Added support in Nucleo-L476RG board for BMP280 sensor.

include/strings.h, libs/libc/string/Make.defs, libs/libc/string/lib_bzero.c
Implement the bzero function as an alternative to macro expansion.
and support gcc FORTIFY_SOURCE features for nuttx libc
This function will use gcc's function
__builtin_dynamic_object_size and __builtin_object_size
Its function is to obtain the size of the object through compilation, so as to judge whether there are out-of-bounds operations in commonly used functions. It should be noted that the option -O2 and above is required to enable this function
cortex-m33
=> libc/lib_bzero:Add bzero prototype.

sched/task/task_init.c
This contains minor revision on nxtask_init() and comments.
None
- `rv-virt/knsh32` and `rv-virt/knsh64` with QEMU 6.2 on Ubuntu 22.04
- CI checks
=> sched/task: minor revision on task_init.c

arch/risc-v/src/common/espressif/esp_allocateheap.c, arch/risc-v/src/common/espressif/esp_head.S, arch/risc-v/src/common/espressif/esp_memorymap.h, arch/risc-v/src/common/espressif/esp_start.c, arch/risc-v/src/esp32c3-legacy/esp32c3_allocateheap.c, arch/risc-v/src/esp32c3-legacy/esp32c3_head.S, arch/risc-v/src/esp32c3-legacy/esp32c3_memorymap.h, arch/risc-v/src/esp32c3-legacy/esp32c3_start.c, boards/risc-v/esp32c3-legacy/common/scripts/kernel-space.ld, boards/risc-v/esp32c3-legacy/common/scripts/legacy_sections.ld, boards/risc-v/esp32c3-legacy/common/scripts/mcuboot_sections.ld, boards/risc-v/esp32c3-legacy/common/scripts/user-space.ld, boards/risc-v/esp32c3/common/scripts/esp32c3_legacy_sections.ld, boards/risc-v/esp32c3/common/scripts/esp32c3_mcuboot_sections.ld, boards/risc-v/esp32c3/common/scripts/esp32c3_simple_boot_sections.ld, boards/risc-v/esp32c6/common/scripts/esp32c6_legacy_sections.ld, boards/risc-v/esp32c6/common/scripts/esp32c6_simple_boot_sections.ld, boards/risc-v/esp32h2/common/scripts/esp32h2_legacy_sections.ld, boards/risc-v/esp32h2/common/scripts/esp32h2_simple_boot_sections.ld
ESP32 SoC use a static allocated array as idle stack. To fit the existed idle stack allocation, make idle stack allocated from ebss for the whole esp32 series.
This is also necessary for simplifying #12265
esp32c3-legacy, esp32c3, esp32c6, esp32h2
esp32c6-devkitC
=> arch/risc-v: Make esp32 SoCs allocate idle stack after ebss

arch/arm/src/samv7/Kconfig, arch/arm/src/samv7/sam_pwm.c
Make channels synchronous (i.e. share the same timebase) with the help of SAMV7_PWMx_CHy_SYNC defines. All the channels share the same timebase of channel 0, so this channel must be defined too.
Channels on SAMV7 now can be synchronized.
Should be none to old configs.
On my own BSP, oscilloscope probing.
=> arch/arm/src/samv7/sam_pwm.c: option to make channels synchronous

boards/arm/qemu/qemu-armv7a/src/qemu_bringup.c, boards/arm64/qemu/qemu-armv8a/src/qemu_bringup.c, drivers/devicetree/fdt.c, include/nuttx/fdt.h
Adds a common set of flattened device tree (FDT) utility functions which can be expanded on, as needed.
Ideally, other ports which have FDT support can use these functions, rather than having independent implementations at an architecture level.
FDT parsing utilities are available to any architecture which supports and enables libfdt, rather than needed to provide their own implementation.
FDT support in LiteX in custom drivers. https://github.com/apache/nuttx/pull/11939
=> drivers/devicetree: Add a set of commonly used FDT utilities.

arch/sparc/src/s698pm/s698pm_cpustart.c, include/nuttx/sched.h, sched/Kconfig, sched/sched/sched_resumescheduler.c
CONFIG_SCHED_RESUMESCHEDULER macro define error
we removed "select SCHED_RESUMESCHEDULER",
As SCHED_RESUMESCHEDULER is not a necessary feature in SMP,
turning it on by default may affect performance.
NULL
compiling
=> sched/sched: CONFIG_SCHED_RESUMESCHEDULER macro define error

drivers/ioexpander/Kconfig, drivers/ioexpander/icjx.c
There might be multiple expanders, one with interrupt used and other without. This commit fixes initial incorrect interrupt design by introducing ICJX_INT_ENABLE config option.
Also fixes naming of ICJX_MULTIPLE option.
This fixes unused functions compile warnings in case of some configuration choices.
=> icjx: use iC-JX interrupt config instead of the general one

cmake/nuttx_add_romfs.cmake
cmake/romfs: separate c flags to avoid compile fail
riscv-none-elf-gcc: warning:  -Wstrict-prototypes: linker input file unused because linking not done
riscv-none-elf-gcc: error:  -Wstrict-prototypes: linker input file not found: No such file or directory
N/A
ci-check
=> cmake/romfs: separate c flags to avoid compile fail 

sched/task/task_posixspawn.c
The posix_spawn: log appears even for NSH internal commands in kernel
build and duplicates a lot with the `task_spawn:` log, so drop it to
make DEBUG_SCHED_INFO more clear.
None
- rv-virt with QEMU 6.2 on Ubuntu 22.04
- CI checks
=> sched/posixspawn: disable tedious logging

sched/pthread/pthread_join.c
Adds null pointer check to error out route in pthread_join() as it
crashs ostest sometimes.
None
- rv-virt with QEMU 6.2 on Ubuntu 22.04
- CI checks
=> sched/pthread: pthread_join null pointer

sched/misc/assert.c
sched/misc: dump stack as platform bit width
before:
```
stack_dump: 0x8002ff80: 8003057b 00000000 00000000 00000000 00000002 00000000 80030068 00000000
stack_dump: 0x8002ffa0: 00000002 00000000 00000000 00000000 80030280 00000000 8000898e 00000000
stack_dump: 0x8002ffc0: 00000000 00000000 00000000 00000000 0000000b 00000000 0000000a 00000000
stack_dump: 0x8002ffe0: 8002a470 00000000 00000000 00000000 00000000 00000000 00000000 00000000
```
after:
```
stack_dump: 0x8002ff80: 000000008003057b 0000000000000000 0000000000000002 0000000080030068 0000000000000002 0000000000000000 0000000080030280 000000008000898e
stack_dump: 0x8002ffc0: 0000000000000000 0000000000000000 000000000000000b 000000000000000a 000000008002a470 0000000000000000 0000000000000000 0000000000000000
```
N/A
rv-virt/nsh64
=> sched/misc: dump stack as platform bit width

arch/risc-v/src/common/riscv_common_memorymap.h
The bc022f8cd8 introduces a static way to calculate idle stack address for risc-v platform. However, it uses the reverse order to access idle stack, which breaks boards with smp configuration.
Correct the idle stack order of g_cpux_idlestack.
This should fix #12265 (bc022f8cd8) and can close #12325
`rv-virt:smp64`, `rv-virt:ksmp64`
=> arch/risc-v: fix idle stack assign order

boards/xtensa/esp32/common/include/esp32_zerocross.h, boards/xtensa/esp32/common/src/Make.defs, boards/xtensa/esp32/common/src/esp32_zerocross.c, boards/xtensa/esp32/esp32-wrover-kit/src/esp32_bringup.c
The PR aims to add support for ESP32 device support for the Zero Cross driver.
None
Running apps/examples/zerocross.
=> Zero-Cross driver to ESP32

arch/xtensa/src/esp32s2/esp32s2_textheap.c, arch/xtensa/src/esp32s3/esp32s3_textheap.c
It seems like a wrong copy-and-paste from esp32c3. Actually, internal memory mapping varies among processors.
esp32s3: lightly tested with wamr aot
esp32s2: not tested (i have no hardware access)
=> esp32s3/esp32s2: Fix D_I_BUS_OFFSET

include/nuttx/mqueue.h, sched/mqueue/mq_timedreceive.c, sched/mqueue/mq_timedsend.c
sched/mqueue: add support of tick based send() and receive()
Add tick based send()/receive() to reduce the cost of time conversion
N/A
ci-check
=> sched/mqueue: add support of tick based send() and receive()

drivers/net/netdev_upperhalf.c, include/nuttx/net/netdev_lowerhalf.h
Some drivers may set too big quota by accident and consume all of our buffers, so we add a check when registering devices.
Upper half of netdev, add check for registering.
Manually: Locally changed quota of sim_netdriver and virtio-net to make sure the check works.
=> net/netdev: Check quota when registering lower-half devices

net/udp/udp_sendto_buffered.c
If NIC was down in func,the sendto_writebuffer_release will not release wrb cause setting "wrb->wb_iob = NULL" behind udp_wrbuffer_release
"sendto_eventhandler" in udp_sendto_buffered.c L382 - L390
```
if ((flags & NETDEV_DOWN) != 0)
{
ninfo("Device down: %04x\n", flags);
/* Free the write buffer at the head of the queue and attempt to setup
* the next transfer.
*/
sendto_writebuffer_release(conn);
return flags;
}
```
"sendto_writebuffer_release" in udp_sendto_buffered.c L158 - L160
```
wrb->wb_iob = NULL;
udp_wrbuffer_release(wrb);
```
UDP wrb
Passed on Vela product
=> [net][udp] fix udp wrb-iob leak when NIC was down

include/sys/socket.h
Third-party library lcm will use SCM_TIMESTAMP macro definition
sim:local
=> sys/socket.h: add the definition of SCM_TIMESTAMP

arch/xtensa/src/esp32s3/esp32s3_gpio.c
=> xtensa/esp32s3: pending interrupt should be clear while disable GPIO IRQ

arch/xtensa/src/esp32s3/esp32s3_textheap.c
While there constants are commented as "First and last words of the D/IRAM region", the _HIGH addresses are actually not in the corresponding region.
=> esp32s3_textheap.c: fix range checks

tools/nxstyle.c
nxstyle: Ignore long line for file path at line 2
Fixes issues like that reported on PR #12345 
local
=> nxstyle: Ignore long line for file path at line 2

boards/arm/stm32l4/nucleo-l476rg/src/Makefile, boards/arm/stm32l4/nucleo-l476rg/src/stm32_appinit.c, boards/arm/stm32l4/nucleo-l476rg/src/stm32_mpu9250.c, boards/arm/stm32l4/nucleo-l476rg/src/stm32_mpu9250.h
This commit adds the support for the Invensense MPU-9250 a 9-axis MotionTracking device that combines a 3-axis gyroscope, 3-axis accelerometer, 3-axis magnetometer to the ST Nucleo-L476RG board.
Nothing else is impacted.
It is tested on Nucleo-L476RG board with uorb listener and it is working fine.
=> Added support in Nucleo-L476RG board for MPU9250 sensor.

drivers/power/pm/activity_governor.c, drivers/power/pm/pm_changestate.c
Swap the sequence of domain state update and statechanged callback, 
Make sure inside statechanged callback can get the old domain state. 
Only have impact on activity governor, no other impacts.
CI-test and qemu-arm-v8a.
=> PM: change domain field state after callback done

drivers/power/pm/pm_initialize.c
In drivers/power/pm/pm_changestate.c pm_stats
fist time do 
```C
clock_systime_timespec(&ts);
clock_timespec_subtract(&ts, &dom->start, &ts);
```
if enabled RTC_HIRES, procfs will not start with 0.
pm_initialize will call clock_systime_timespec extra once, if PM_PROCFS enabled.
ci-test & qemu-v8a
=> pm: fix when RTC_HIRES enabled pm procfs err

boards/arm64/imx9/imx93-evk/src/imx9_i2c.c, boards/arm64/imx9/imx93-evk/src/imx9_spi.c
"ret" might be unused, which causes an error due to -Werror
Fix minor build issue
CI pass
=> boards/imx93-evk: Fix potential warning about unused variable

tools/minidumpserver.py
This is to follow up patch 12316
minidump tool usage with 64bit stack dump logs
- checked with `rv-virt/ksmp64`
- CI checks
=> tools/minidump: 64-bit dump support

drivers/power/pm/pm_changestate.c, drivers/power/pm/pm_procfs.c, drivers/power/pm/pm_register.c, include/nuttx/power/pm.h
Add more information in pm procfs, record when inside pm_prepall who cb->prepare ret failed.
Cost more time when Enabled pm_procfs and have prepare failed.
When procfs read and pmconfig can show more information.
CI test & qemu-v8a
=> pm: procfs add pm prapare fail stats

arch/arm/src/imxrt/imxrt117x_mpuinit.c
When writing/reading to SEMC without the peripheral enabled the 1170 could lockup.
Don't enable SEMC region if the peripheral is disabled.
Also make sure that ITCM is Read-only when executing from it.
imxrt1170
vmu_rt1170
=> imxrt: 1170 MPU config ensure no lockups can occur

arch/risc-v/src/common/espressif/Make.defs, arch/xtensa/src/esp32/Make.defs, arch/xtensa/src/esp32s3/Make.defs
* espressif: Enable setting the GIT_DEPTH to pull the submodules
* By default, submodules are cloned with `--depth=1`. This continues to be true if `DISABLE_GIT_DEPTH` environment variable is not defined (and it is not defined by default). But, if defined the submodules will be fully cloned (without the `--depth` parameter).
Some testing functionality requires fetching the whole repository (without the `--depth` option). This implementation enables it.
Internal CI testing with HW testing.
=> espressif: Add option to disable the GIT_DEPTH to pull submodules

boards/risc-v/mpfs/common/src/mpfs_composite.c, boards/risc-v/mpfs/common/src/mpfs_emmcsd.c, boards/risc-v/mpfs/common/src/mpfs_usb.c
Add partition parsing logic to emmcsd and support for configuring either CDCACM alone or both CDCACM and USBMSC for composite mode.
This synchronizes boards/mpfs/common emmcsd and usb composite initialization files with some of our downstream ones.
Only impacts mpfs targets
Tested on mpfs platform
=> boards/risc-v/mpfs/common/src: Update mpfs_emmcsd.c and mpfs_composite.c

drivers/misc/rwbuffer.c
There is no need to call rwb->rhreloade() when nblocks is 0, and some platform(eg: BES) has the limit that the parameter of len in pltatform flash read function cant't be 0.
pass in my case
=> fix: call rwb->rhreload() when nblocks > 0

arch/arm/include/stm32h7/chip.h, arch/arm/src/stm32h7/Kconfig, arch/arm/src/stm32h7/stm32_rcc.c, arch/arm/src/stm32h7/stm32h7x5xx_rcc.c
Adds compatibility with PX4 NuttX for use with JAE flight controllers.
Here are the changes:
・Added setting ARCH_CHIP_STM32H755II
・Add stm32h7x5xx_rcc.c
・Corrected so that STM32_PWR_CR3_SCUEN is not enabled when SMPS SUPPLY is not used.
=> add stm32h755II chip

arch/arm/src/armv8-r/arm_gicv3.c, arch/arm/src/imxrt/imxrt_flexspi.c, arch/arm/src/lc823450/lc823450_gpio.c, arch/arm/src/phy62xx/phyplus_timer_lowerhalf.c, arch/arm/src/rp2040/rp2040_clock.c, arch/arm/src/rp2040/rp2040_pio.c, arch/arm/src/rp2040/rp2040_pio_instructions.h, arch/arm/src/rp2040/rp2040_pll.c, arch/arm/src/rp2040/rp2040_xosc.c, arch/arm/src/tiva/common/tiva_pwm.c, arch/arm64/src/common/arm64_gicv3.c, arch/risc-v/src/bl602/bl602_os_hal.c, arch/risc-v/src/esp32c3-legacy/esp32c3_rt_timer.c, arch/xtensa/src/esp32/esp32_psram.c, arch/xtensa/src/esp32/esp32_rt_timer.c, arch/xtensa/src/esp32/esp32_tim_lowerhalf.c, arch/xtensa/src/esp32s2/esp32s2_rt_timer.c, arch/xtensa/src/esp32s2/esp32s2_spiram.c, arch/xtensa/src/esp32s3/esp32s3_psram_quad.c, crypto/bn.c, drivers/usbdev/usbdev_fs.c, include/assert.h, libs/libc/regex/regcomp.c, libs/libc/regex/regexec.c, mm/mm_heap/mm_checkcorruption.c, net/ipfrag/ipfrag.c, net/ipfrag/ipv4_frag.c, net/ipfrag/ipv6_frag.c
As defined by the C standard, if NDEBUG is defined, assert should do nothing but be simply defined as:
#define assert(ignore) ((void)0)
Reference link:
https://pubs.opengroup.org/onlinepubs/009695399/basedefs/assert.h.html
=> include: When defining NDEBUG, assert will implement alignment standards

tools/ci/docker/linux/Dockerfile
tools/docker: install file/tclsh tools：
fix CI compilation errors:
github/workspace/sources/apps/database/sqlite/sqlite/configure: line 5204: /usr/bin/file: No such file or directory /github/workspace/sources/apps/database/sqlite/sqlite/configure: line 10376: tclsh: command not found /github/workspace/sources/apps/database/sqlite/sqlite/configure: line 10812: tclsh: command not found /github/workspace/sources/apps/database/sqlite/sqlite/configure: line 10826: tclsh: command not found configure: WARNING: Can't find Tcl configuration definitions configure: WARNING: *** Without Tcl the regression tests cannot be executed *** configure: WARNING: *** Consider using --with-tcl=... to define location of Tcl *** make[4]: warning: -j0 forced in submake: resetting jobserver mode. …
=> tools/docker: install file/tclsh tools：

drivers/sensors/Kconfig, drivers/sensors/bh1749nuc.c, drivers/sensors/bh1749nuc_base.h, drivers/sensors/bh1749nuc_uorb.c, drivers/sensors/bmm150_uorb.c
- sensors/bh1749nuc_uorb.c: add sensor reset
- sensors/bh1749nuc_uorb.c: don't wait for VALID flag in fetch interface ￼…
- sensors/bh1749nuc: configure I2C frequency
- sensors/bmm150: configure I2C frequency
thingy53
=> sensors: improvements for bmm150 and bh1749nuc

boards/arm/stm32l4/nucleo-l476rg/include/board.h
CAN1 port pins switched to GPIO_CAN1_RX_1 (PA11) and GPIO_CAN1_TX_1 (PA12) on nucleo-l476rg board because collision with default I2C1 pins that are set.
On CAN1 board Nucleo-l476rg. Changed pins. Nowhere else.
Tested TX and RX sides using CAN example and connected other side to CAN sniffer trough PHY.  Working as it should.
=> Fixed collision between CAN1 and I2C1. Board nucleo-l476rg.

drivers/power/pm/pm.h, drivers/power/pm/pm_changestate.c, drivers/power/pm/pm_procfs.c
Update state up to now when pm procfs read
before fix, if domain active for 1min and stay same state for 1 hour, the procfs cannot dump the current holding time(report total 1 minute).
after fix, will add manually to the value inside stack,
ci-test and qemu arm-v8a.
=> pm_procfs: update state up to now when pm procfs read

sched/sched/sched_addreadytorun.c
sched: remove redundant variables "switched"
NONE
compiling
=> sched: remove redundant variables "switched"

arch/risc-v/src/common/riscv_exception.c
This guards `tcb->name` usage in `riscv_exception()`.
None
- rv-virt/knsh64
- CI checks
=> arch/riscv: guard tcb->name usage

sched/pthread/CMakeLists.txt, sched/pthread/Make.defs, sched/pthread/pthread_sem.c
Rename `pthread_initalize.c` as `pthread_sem.c` to be in line with the contents.
None
- Checkd with rv-virt/nsh rv-virt/knsh64
- CI checks
=> sched/pthread: rename pthread_initialize.c

include/sys/types.h
in arm64 Let's see how the following code looks like in assembly
volatile cpu_set_t g_cpu_set;
cpu_set_t set_cpu_set_t_set(int cpu) {
g_cpu_set &= ~(1 << cpu);
return g_cpu_set;
}
when
typedef volatile uint32_t cpu_set_t;
Dump of assembler code for function set_cpu_set_t_set:
0x0000000040288570 <+0>:	adrp	x2, 0x403ce000 <g_irqvector+1160>
0x0000000040288574 <+4>:	ldr	w3, [x2, #2368]
0x0000000040288578 <+8>:	mov	w1, #0x1
0x000000004028857c <+12>:	lsl	w1, w1, w0
0x0000000040288580 <+16>:	bic	w1, w3, w1
0x0000000040288584 <+20>:	str	w1, [x2, #2368]
0x0000000040288588 <+24>:	ldr	w0, [x2, #2368]
0x000000004028858c <+28>:	ret
when
typedef volatile uint8_t cpu_set_t;
Dump of assembler code for function set_cpu_set_t_set:
0x000000004028856c <+0>:	adrp	x2, 0x403ce000 <g_irqvector+1192> …
=> types: on some arch, execution speed can be accelerated

arch/arm/src/samv7/sam_1wire.c, arch/arm/src/samv7/sam_config.h, arch/arm/src/samv7/sam_lowputc.c
By default U(S)ART clocks are enabled in sam_lowput.c but configuration check from sam_config.h may override USART configuration and prevent clocks from been enabled.
This commit fix inconsistency in U(S)ART pinmux and clock configuration
Improve U(S)ART support for SAMv7
Pass CI
=> arch/arm/samv7: fix U(S)ART clock enable for 1-wire

drivers/power/pm/CMakeLists.txt, drivers/power/pm/Kconfig, drivers/power/pm/Make.defs, drivers/power/pm/pm_initialize.c, drivers/power/pm/stability_governor.c, include/nuttx/power/pm.h
only when first time change state can hold WFI for enough time thresh, allow second time goto target state,
suitable for the case when wakeup from sleep too slow, etc.
No impact for default case,
after manually pm_set_governor(PM_IDLE_DOMAIN, pm_stability_governor_initialize()), PM_IDLE_DOMAIN will detect if can stay in WFI for enough time then allow enter the target pm state.
qemu-v8a, and vendor specific platform.
=> PM: add stability governer

arch/xtensa/src/esp32s2/esp32s2_textheap.c, arch/xtensa/src/esp32s3/esp32s3_textheap.c
Unlike esp32, kmm memory is executable.
Tested wamr aot on esp32s3-devkitc.
esp32s2 part is not tested.
=> esp32s2/esp32s3 textheap: do not require RTC heap

arch/risc-v/src/common/riscv_pmp.c, arch/risc-v/src/mpfs/mpfs_mpu.c
Add check that the size is valid for NAPOT PMP configuration.
The size must be power-of-two according to the the PMP spec.
RISC-V PMP and MPFS MPUCFG
Custom MPFS board
=> RISC-V: Check that the size is valid for NAPOT

arch/arm/src/armv7-m/arm_mpu.c, arch/arm/src/armv7-m/mpu.h, arch/arm/src/armv7-r/arm_mpu.c, arch/arm/src/armv7-r/mpu.h, arch/arm/src/armv8-m/arm_mpu.c, arch/arm/src/armv8-m/mpu.h
CONFIG_MPU_RESET -> CONFIG_ARM_MPU_RESET to match what is in Kconfig
Will fix the code so the the MPU reset so it is compiled
px4_fmu-v6xrt (imxrt)
=> Rename CONFIG_MPU_RESET -> CONFIG_ARM_MPU_RESET  so the the MPU reset so it is compiled

drivers/power/pm/pm_changestate.c
Improve performance of pm procfs by decrease clock_systime_timespec call times.
Only decreased function execution time.
CI-test, arm-v7a board.
=> pm: do struct timespec copy to decrease api call times.

sched/mqueue/mq_timedsend.c
This fixes a memory leak in mq_timedsend.c encoutnered during ostest.
timed mqueue
- Local test with rv-virt/nsh
- CI checks
=> sched/mqueue: reclaim unsent message

drivers/analog/Kconfig
DAC driver uses CONFIG_DAC_FIFOSIZE, but this is not configurable from Kconfig. This adds the missing option and allows to set DAC FIFO size from the configuration.
New config option. No change in C code.
=> analog: add configuration option to set DAC FIFO size

include/nuttx/arch.h
The definition of nxsched_process_cpuload_ticks uses clock_t, which is portable across uint32_t and uint64_t timers, and works if CONFIG_SYSTEM_TIME64 is defined.
The correct parameter type is resolved when `CONFIG_SYSTEM_TIME64` is used.
`arch/litex` with CONFIG_SYSTEM_TIME64 and CONFIG_CPULOAD_PERIOD
=> nuttx/arch.h: Update parameter type to match definition.

boards/arm64/imx9/imx93-evk/scripts/ocramboot.ld
Temporary fix to unblock [CI errors](https://github.com/apache/nuttx/actions/runs/9251490607/job/25447280252) like:
```
Configuration/Tool: imx93-evk/bootloader
...
aarch64-none-elf-ld: /github/workspace/sources/nuttx/nuttx section `.rodata' will not fit in region `ocram'
aarch64-none-elf-ld: region `ocram' overflowed by 88 bytes
```
The ocram region has been enlarged.
CI checks
- CI checks
=> ci/blocker: temporary fix for imx9evk

sched/tls/task_uninitinfo.c
Fix build error with `CONFIG_PTHREAD_ATFORK` enabled
Just build error fix
Pass the build
=> tls: fix build error under CONFIG_PTHREAD_ATFORK enabled

arch/arm/src/samv7/Kconfig, arch/arm/src/samv7/Make.defs, arch/arm/src/samv7/sam_us.c, arch/arm/src/samv7/sam_us.h
Embedded flash can have user signature area on SAMv7. This is a 512 bytes large page whose data are not erased by asserting ERASE pin or by software ERASE command.
This commit adds arch to board interface for this area. It is possible to perform read, write and erase operation. `SAMV7_USER_SIGNATURE` option has to be set in the configuration.
New feature for SAMv7
Tested on SAMv7 evaluation kit with progmem and mcuboot.
=> samv7: add support for user signature area in embedded flash

tools/ci/testlist/msys2.dat
add build board qemu-v8a:nsh_smp 64-bit Arm Cortex-A53 Multi-Core
none
Test NuttX: Arm Cortex-A53 Multi-Core
**Arm64 Toolchain**
Download the latest ARM64 GCC toolchain prebuilt by ARM (arm-gnu-toolchain-13.2.rel1-mingw-w64-i686-aarch64-none-elf.zip)
https://github.com/apache/nuttx/blob/d0f893dfba82c4089eda4cc7c86cde653ecf839e/tools/ci/platforms/msys2.sh#L64
**Compiling**
./tools/configure.sh -g qemu-armv8a:nsh_smp ;make -j4
**Download xpack qemu arm** (xpack-qemu-arm-8.2.2-1-win32-x64.zip)
https://github.com/xpack-dev-tools/qemu-arm-xpack/releases/download/v8.2.2-1/xpack-qemu-arm-8.2.2-1-win32-x64.zip
**Running** 
qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic -machine virt,virtualization=on,gic-version=3 -net none -chardev stdio,id=con,mux=on -serial chardev:con -mon …
=> tools/ci/testlist: msys2.dat add qemu-v8a:nsh_smp

drivers/timers/Kconfig, drivers/timers/mcp794xx.c, include/nuttx/timers/mcp794xx.h
This commit adds configuration option `CONFIG_MCP794XX_DATETIME_UTC`. If set, the datetime is stored in UTC instead of local time. The default value is kept at local time to keep backwards compatibility with devices currently using the RTC.
MCP794XX supports digital trimming that periodically adds or subtracts clock cycles, resulting in small adjustments in the internal timing.This way inaccuracies of clock source can be compensated. 
New functionalities for mcp794xx.
Tested with SAMv7 and mcp794xx rtc.
=> mcp794xx: store datetime in UTC and add trimming support

libs/libc/libc.csv, syscall/syscall.csv
* libc.csv: Guard execv with LIBC_EXECFUNCS
* syscall.csv: Correct macro guard of setsockopt
Minor
Local machine
=> Fixes for symbol definition in libc.csv and syscall.csv

arch/arm/src/armv6-m/arm_exception.S, arch/arm/src/armv6-m/arm_initialstate.c, arch/arm/src/armv7-m/arm_exception.S, arch/arm/src/armv7-m/arm_initialstate.c, arch/arm/src/armv8-m/arm_exception.S, arch/arm/src/armv8-m/arm_initialstate.c
when changing the stack pointer, software must use an ISB instruction immediately after the MSR instruction. This ensures that instructions after the ISB instruction execute using the new stack pointer.
https://developer.arm.com/documentation/101928/0101/The-Cortex-M85-Processor--Reference-Material/Programmer-s-model/Core-registers/CONTROL-register?lang=en
" When changing the stack pointer, software must use an ISB instruction immediately after the MSR instruction. This ensures that instructions after the ISB instruction execute using the new stack pointer."
NULL
=> armv6/7/8-m: use ISB instruction immediately after the MSR instruction

CMakeLists.txt, arch/arm/src/cmake/Toolchain.cmake, arch/arm/src/cmake/platform.cmake, arch/arm64/src/cmake/Toolchain.cmake, arch/arm64/src/cmake/platform.cmake, arch/risc-v/src/cmake/Toolchain.cmake, arch/risc-v/src/cmake/platform.cmake, arch/sim/src/cmake/Toolchain.cmake, arch/x86_64/src/cmake/Toolchain.cmake, arch/x86_64/src/cmake/platform.cmake
> [!CAUTION]
> when repeatedly enabling and disabling string-controlled configurations, 
> the generated toolchain configuration may be incorrect.
```bash
cmake -B build -DBOARD_CONFIG=some-config-disable-cxx-exception
cmake --build build -t menuconfig
cmake --build build
```
> [!NOTE]  
>  Initialization compilation configuration 
> ![ebf3c9a9-117a-4923-9e87-5b2c7c7b79cd](https://github.com/apache/nuttx/assets/31881278/152cb3c9-343d-471f-9a34-dbb36b01a65e)
> [!WARNING]  
> After the modification
> we can tell that it has not taken effect
> ![56fc9334-ecde-4776-8cf0-deeb5022f55b](https://github.com/apache/nuttx/assets/31881278/29242f0d-4c42-45a2-a8f4-c96ebde70d6e)
I found that this was because the compilation options we used **STRINGS** to control in the `Toolchain file` did not work as …
=> cmake:bugfix CMake compilation options settings should not use strings

arch/risc-v/src/common/fork.S
Value of s0 (callee-saved) must be preserved through the call, use a0 (caller-saved) to calculate the original SP instead.
Fix bug in fork()
None
=> riscv-v/fork.S: Fix clobbering of s0 in fork()

include/crypto/curve25519.h, include/nuttx/net/netfilter/ip_tables.h
=> fix some gcc14 errors

arch/risc-v/include/irq.h, arch/risc-v/include/syscall.h, arch/risc-v/src/common/riscv_exception_common.S, arch/risc-v/src/common/riscv_fork.c, arch/risc-v/src/common/riscv_internal.h, arch/risc-v/src/common/riscv_percpu.c, arch/risc-v/src/common/riscv_percpu.h, arch/risc-v/src/common/riscv_swint.c, arch/risc-v/src/common/supervisor/riscv_syscall.S
This set of patches change how user service calls are executed:
Instead of using the common interrupt logic, execute the user service
call directly.
Why? When a user makes a service call request, all of the service call
parameters are already loaded into the correct registers, thus it makes
no sense to first clobber them and then reload them, which is what the
old logic does. It is much more effective to run the system call directly.
During a user system call the interrupts must be re-enabled, which the
new logic does as soon as we know the exception is a user service call
request.
This patch set does NOT change the behavior of reserved system calls (like
switch_context), only the user service call request is affected.
User system call logic basically rewritten to improve performance. …
=> riscv/syscall: Optimize user service call performance

Kconfig, arch/Kconfig
Kconfig: move LTO options to Build Setup menu
LTO is optimization option so it's more appropriate to place it in the same place as other optimization options
LTO options moved from "system Type" to Build Setup menu
local
=> Kconfig: move LTO options to Build Setup menu

arch/sim/Kconfig, arch/sim/src/sim/posix/sim_tapdev.c, arch/sim/src/sim/sim_netdriver.c, include/nuttx/net/netdev.h, net/Kconfig, net/icmp/icmp_sendmsg.c, net/icmpv6/icmpv6_sendmsg.c, net/netdev/netdev_iob.c, net/tcp/tcp_send_buffered.c, net/udp/udp.h, net/udp/udp_sendto_buffered.c, net/udp/udp_wrbuffer.c
Support the jumbo frame in the sim.
- First, support setting mtu on sim;
- Then, optimize the use of iob by jumbo frame packets, and pre-alloc an iob in the protocol stack for each jumbo frame packet, supporting the ICMP, UDP and TCP.
The sim can support the JUMBO frame packets.
- First, configure the options, 
```
CONFIG_SIM_NETDEV_MTU = 3000
CONFIG_NET_JUMBO_FRAME=y
```
- Then, we use the ICMP to test.
```
ping -s 3000 10.0.1.1
```
- Finally, capture packets on nuttx0 using the Wireshark. We should be able to see ICMP packets with the length of 3042 bytes.
=> Allow the sim to set the MTU of netdevice and support the jumbo frame.

boards/arm/cxd56xx/drivers/sensors/cxd5610_gnss.c
Add process to reset read position after read is complete to fix NMEA output with DC report.
=> boards: cxd56xx: Fix read position in cxd5610 gnss driver

drivers/serial/Kconfig-pl011, drivers/serial/uart_pl011.c, include/nuttx/serial/uart_pl011.h
I want to add the interface about clock and reset control for reducing power consumption.
I added the pl011_platform_shutdown() / _setup(), these functions are called when pl011_shutdown() / _setup() are called. 
The added interface is inteneded as bellows.
* The pl011_platform_shutdown() is for clock off and reset-asserted.
* The pl011_platform_setup() is for clock on and reset-de-asserted.
and
This PR includes as following fixes.
* bug fix about the function : pl011_txready().
* add the bitmask according to PL011 spec. (Although almost no problem)
The user of drivers/serial/uart_pl011.c
I think almost no impact as long as do not use CONFIG_UART_PL011_PLATFORMIF.
I checked following items with our out-of-tree Board directory, some apps and cxd32xx. (The PR of cxd32xx have not accepted …
=> drivers/serial/uart_pl011.c : add the interface about clock and reset control.

drivers/devicetree/fdt.c, include/nuttx/fdt.h
arch/risc-v/litex: add some litex specific FDT helpers.
These utilities remove some of the boilerplate needed for FDT parsing and device initialization. 
Litex port with device tree support. Further PRs to follow with driver support.
=> drivers/devicetree/fdt: add additional fdt parsing utilities

mm/mm_gran/mm_gran.h, mm/mm_gran/mm_graninit.c, mm/mm_gran/mm_grantable.h
GRAN_ALIGNED should check that the memory block's alignment (log2align) is correct, not that the memory block is aligned with the granule size.
This fixes DEBUGASSERT() in mm_granfree:
_assert: Assertion failed : at file: mm_gran/mm_granfree.c:49
The assertion triggers if granule size != alignment.
Fixes issue with granule allocator.
imx93-evk
=> mm/gran: Fix GRAN_ALIGNED() macro

boards/arm/lpc17xx_40xx/lpc4088-devkit/scripts/memory.ld, boards/arm/lpc17xx_40xx/lpc4088-quickstart/scripts/memory.ld, boards/arm/lpc17xx_40xx/open1788/scripts/memory.ld, boards/arm/sam34/sam3u-ek/scripts/memory.ld, boards/arm/stm32/stm3240g-eval/scripts/memory.ld, sched/mqueue/mq_initialize.c, sched/signal/sig_initialize.c
sched/signal: move signal structures pool to bss
sched/mqueue: move message queue buffer to bss
Decoupling with memory allocator
N/A
ostest
=> sched/signal: move signal structures pool to bss

arch/arm/src/xmc4/hardware/xmc4_memorymap.h, arch/arm/src/xmc4/hardware/xmc4_vadc.h, arch/arm/src/xmc4/xmc4_vadc.c, arch/arm/src/xmc4/xmc4_vadc.h
Added driver for XMC4[78] and XMC45 series VADC peripheral. 
Driver includes :
- Complete register map and bit fields detail for both series.
- VADC Group and Channel config handler for easy register programming. 
- Background Scan request source partial support but working conversion with basic configuration. 
Tested on a XMC4800 custom board with 3 channels of same group.
=> arch/xmc4 vadc driver - background request source partial support

Documentation/components/drivers/special/power/pm/index.rst, drivers/power/pm/activity_governor.c, drivers/power/pm/greedy_governor.c, drivers/power/pm/pm.h, drivers/power/pm/pm_activity.c, drivers/power/pm/pm_autoupdate.c, drivers/power/pm/pm_changestate.c, drivers/power/pm/pm_checkstate.c, drivers/power/pm/pm_governor.c, drivers/power/pm/pm_initialize.c, drivers/power/pm/pm_lock.c, drivers/power/pm/pm_procfs.c, drivers/power/pm/pm_register.c, drivers/power/pm/pm_unregister.c, drivers/power/pm/stability_governor.c, include/nuttx/power/pm.h
Remove the PM gloabal variables. make callback register to the domain directly.
To keep compatible, make default pm_register behaviour only register to the PM_IDLE_DOMAIN.
When CONFIG_PM_NDOMAINS==1, no impacts.
When CONFIG_PM_NDOMAINS > 1, the default pm_register will not able to get notification from domain 1 .. any more, have to change to the new pm_domain_register API.
Can make each power domain isolated. less confused when we have more powerdomain and do register action.
Also make each domain only take lock once is enough, don't have to care about global pm callback reg lock.
For more pm domain case, and SMP case, make more optimize possible.
CI & specific product code R&D self test done.
=> pm: remove pm global, make per domain isolated

arch/arm/src/armv7-m/arm_ramvec_initialize.c, arch/arm/src/armv7-m/arm_vectors.c, arch/arm/src/armv7-m/ram_vectors.h
Add the address alignment to keep the constraint of ARMv7-M architecture same as RAM vector.
ARMv7-M architecture describes the vector table address alignment as following.
The Vector table must be naturally aligned to a power of two whose alignment value is greater than or equal to (Number of Exceptions supported x 4), with a minimum alignment of 128 bytes.
I wonder why the implementation of arm_vectors.c does not follow this constraint of address alignment about ARMv7-M architecture. Although RAM vector is taken care about it.
I think, as the result it was done by linker script on each board. At our system, NuttX will be started by bootloader. To fix the address of entry point(__start) I set the address of entry point to beginning of binary, so the beginning of binary is not a vector …
=> arch/arm/src/armv7-m/arm_vectors.c : Add the address alignment.

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_entrypoints.c
Check return value of mpfs_board_pmp_setup() and
jump to mpfs_board_pmp_error() in case of error.
MPFS only
Custom MPFS board
=> risc-v/mpfs: Add error handling for PMP conf

include/nuttx/net/net.h, net/inet/ipv4_setsockopt.c, net/inet/ipv6_setsockopt.c, net/sixlowpan/sixlowpan_udpsend.c, net/tcp/tcp_conn.c, net/tcp/tcp_send.c, net/udp/udp_conn.c, net/udp/udp_send.c
uniform naming convention
sim:local
=> net/inet: Rename ttl to s_ttl in sconn

fs/semaphore/sem_open.c, include/nuttx/semaphore.h, include/sys/syscall_lookup.h, libs/libc/semaphore/sem_open.c, syscall/syscall.csv
pointer comparison is unsigned, when returning -errno will be converted to a large positive number, can not enter the error handling branch, therefore, the error code is returned directly and the sem is returned through the parameters.
sim:local and x86_64
=> sem_open: return error code, sem returned by parameter

boards/arm/rp2040/common/src/rp2040_common_bringup.c
Ensure proper error handling by adding return statements for error cases in various initialization functions.
RaspberryPico targets.
=> boards/raspberrypi-pico: Remove early return for error cases in initialization functions.

mm/mm_heap/mm_initialize.c, mm/mm_heap/mm_memalign.c, mm/mm_heap/mm_realloc.c
fix bug when realloc and mm_memalign used.
inside mm_mallinfo info.fordblks will not equals to heap->mm_curused.
before fix, the maxused shown in free command is not accurate.
after fix, already tested in cortex-a7 dual-core platform with maxused shown correct.
CI and cortex-a7 dual-core chip platform.
=> mm: fix mm_curused calculate err

drivers/timers/watchdog.c
change type cast directy void* to container of. in case of CONFIG_WATCHDOG_PANIC_NOTIFIER.
when config matched. the pm callback ptr will not correctly pointer to the struct watchdog_upperhalf_s it self.
CI-test
=> watchdog: fix idle callback maybe not upperhalf

drivers/1wire/1wire.c
pretty the code using container_of inside nuttx.h
No Impact.
CI-test.
=> driver/1wire: update pm callback use container_of

drivers/power/pm/pm_procfs.c
snprintf and procfs_memcpy don't have to do inside lock. move up the unlock code.
procfs time can take lock for shorter time.
CI test.
=> pm: shorten the pm procfs domain lock time.

fs/vfs/fs_lock.c
Better use nxsched_self() from outside of `sched/` module.
None
- CI checks
=> fs/lock: use nxsched_self for modularity

Documentation/platforms/arm/nrf53/boards/thingy53/index.rst, boards/arm/nrf53/common/include/nrf53_adxl362.h, boards/arm/nrf53/common/include/nrf53_bh1749nuc.h, boards/arm/nrf53/common/include/nrf53_bmi270.h, boards/arm/nrf53/common/include/nrf53_bmm150.h, boards/arm/nrf53/common/src/CMakeLists.txt, boards/arm/nrf53/common/src/Make.defs, boards/arm/nrf53/common/src/nrf53_adxl362.c, boards/arm/nrf53/common/src/nrf53_bh1749nuc.c, boards/arm/nrf53/common/src/nrf53_bmi270.c, boards/arm/nrf53/common/src/nrf53_bmm150.c, boards/arm/nrf53/thingy53/src/CMakeLists.txt, boards/arm/nrf53/thingy53/src/Make.defs, boards/arm/nrf53/thingy53/src/nrf53_bringup.c, boards/arm/nrf53/thingy53/src/nrf53_sensors.c, boards/arm/nrf53/thingy53/src/nrf53_spi.c, boards/arm/nrf53/thingy53/src/thingy53.h
boards/thingy53: add sensors support
Add support for sensros: ADXL362, BH1749NUC, BMI270, BMM150
=> boards/thingy53: add sensors support

arch/arm/src/xmc4/Make.defs, arch/arm/src/xmc4/xmc4_vadc.h
Linked to  #12425 
Added the new xmc4 vadc driver to the Make.defs file
On a custom XMC4800 board.
=>  arch/xmc4 vadc driver - background request source partial support (linked to #12425)

include/nuttx/lib/math32.h, sched/Kconfig, sched/init/nx_start.c
sched/Kconfig: add INITIAL_PID_LIMIT option
This adds the flexibility to configure pid hash table length. It allows to
provision the table right at once for cases where number of threads are
known at design time.
None
- Local test with `rv-virt/nsh` and `rv-virt/nsh64`
- CI checking
=> sched/kconfig: add PID_INITIAL_LENGTH

arch/arm/src/common/Toolchain.defs, arch/risc-v/src/common/Toolchain.defs, arch/xtensa/src/lx6/Toolchain.defs, arch/xtensa/src/lx7/Toolchain.defs, boards/arm64/qemu/qemu-armv8a/scripts/Make.defs, boards/sim/sim/sim/scripts/Make.defs
* arch/risc-v/src/common/Toolchain.defs
arch/xtensa/src/lx6/Toolchain.defs
arch/xtensa/src/lx7/Toolchain.defs
- Define SHMODULEFLAGS etc. for sotest/dynload
- Add --entry=__start to SHMODULEFLAGS
* boards/arm64/qemu/qemu-armv8a/scripts/Make.defs
boards/sim/sim/sim/scripts/Make.defs
- Define SHMODULEFLAGS etc. for sotest/dynload
=> Fix SHMODULEFLAGS so that we link dynamically correctly

net/local/local_bind.c, net/local/local_sockif.c
fixed bind can not return error when used same addr.
=> nuttx/net: fixed bind can not return error when used same addr.

arch/risc-v/Kconfig, arch/risc-v/include/inttypes.h, arch/risc-v/include/irq.h, arch/risc-v/include/limits.h, arch/risc-v/include/types.h, arch/risc-v/src/bl602/bl602_irq_dispatch.c, arch/risc-v/src/cmake/Toolchain.cmake, arch/risc-v/src/common/Toolchain.defs, arch/risc-v/src/common/espressif/esp_irq.c, arch/risc-v/src/common/riscv_doirq.c, arch/risc-v/src/common/riscv_exception.c, arch/risc-v/src/common/riscv_fork.c, arch/risc-v/src/common/riscv_fork.h, arch/risc-v/src/common/riscv_initialize.c, arch/risc-v/src/common/riscv_initialstate.c, arch/risc-v/src/common/riscv_internal.h, arch/risc-v/src/common/riscv_percpu.h, arch/risc-v/src/common/riscv_registerdump.c, arch/risc-v/src/common/riscv_schedulesigaction.c, arch/risc-v/src/common/riscv_sigdeliver.c, arch/risc-v/src/common/riscv_swint.c, arch/risc-v/src/common/supervisor/riscv_perform_syscall.c, arch/risc-v/src/esp32c3-legacy/esp32c3_irq.c, arch/risc-v/src/fe310/fe310_irq_dispatch.c, arch/risc-v/src/hpm6000/hpm_irq_dispatch.c, arch/risc-v/src/hpm6750/hpm6750_irq_dispatch.c, arch/risc-v/src/qemu-rv/qemu_rv_irq_dispatch.c, arch/risc-v/src/rv32m1/rv32m1_irq_dispatch.c, libs/libc/machine/risc-v/arch_elf.c
This supports running NuttX using 32bit pointers and 64-bit registers on 64-bit RISC-V devices, using the rv64ilp32 toolchain from the `ruyisdk/riscv-gnu-toolchain-rv64ilp32` Github repo. See [this page](https://yf13.github.io/nuttx/nuttx-rv64ilp32) for more details.
None
- Checked on qemu-system-riscv64ilp32
- CI checks
=> arch/risc-v: support rv64ilp32 ABI

include/nuttx/mm/iob.h, mm/iob/CMakeLists.txt, mm/iob/Make.defs, mm/iob/iob_get_queue_info.c, net/can/can.h, net/can/can_callback.c, net/can/can_getsockopt.c, net/can/can_setsockopt.c, net/can/can_sockif.c
If the CAN stack receiving packets fast, but the application layer reading packets slow. Then `conn->readahead` will continue to grow, leading to memory leaks. Finally CAN stack potentially starve out all IOB buffers.
To prevent IOB buffers leaks, users can restrict CAN socket buffer length.
Rename mm/iob/iob_get_queue_size.c to mm/iob/iob_get_queue_info.c
Discard subsequent CAN frame， when the CAN socket is full.
CAN socket can cache x packets. x = (NET_MAX_RECV_BUFSIZE + IOB_BUF_SIZE - 1)/IOB_BUF_SIZE
Set NET_MAX_RECV_BUFSIZE = 1024 when make-menuconfig.
CAN Socket could cache 6 packets.
Create a demo program as follows:
`
int main(int argc, char **argv)
{
int fd;
int buf_size;
struct ifreq ifr_can;
struct sockaddr_can can_addr_can;
fd = socket(PF_CAN, SOCK_RAW, CAN_RAW); …
=> net/can: Add SO_RCVBUF option for can socket

crypto/Kconfig
I've noticed a typo in menuconfig while trying out nuttx during the conference and fixed it
I don't expect this to have an impact on code because it is a string description in menuconfig.
menuconfig in the cryptography category now looks a bit better:
=> fix(Kconfig): spellcheck "randon" to "random"

arch/xtensa/src/esp32s3/Bootloader.mk
ESP32S3 bootloader.mk file has a typo error. In the file,  **CONFIG_ESP32S2_MCUBOOT_VERSION** config variable (in line 99) is declared, while the correct config variable for esp32s3 bootloader.mk file is **CONFIG_ESP32S3_MCUBOOT_VERSION** which is defined in the main "**.config**" file when the config is generated for ESP32S3-devkit board.
MCUBoot version variable is defined for ESP32S3 board only but file is calling ESP32S2 board version. Correct variable which is defined in .config file should be used.
./tools/checkpatch.sh script was run for arch/xtensa/src/esp32s3/Bootloader.mk and no errors were displayed.
=> arch/xtensa/src/esp32s3/Bootloader.mk: Correction for MCUBoot Version Config Variable 

arch/risc-v/Kconfig, arch/risc-v/include/sg2000/chip.h, arch/risc-v/include/sg2000/irq.h, arch/risc-v/src/sg2000/Make.defs, arch/risc-v/src/sg2000/chip.h, arch/risc-v/src/sg2000/hardware/sg2000_memorymap.h, arch/risc-v/src/sg2000/hardware/sg2000_plic.h, arch/risc-v/src/sg2000/sg2000_allocateheap.c, arch/risc-v/src/sg2000/sg2000_head.S, arch/risc-v/src/sg2000/sg2000_irq.c, arch/risc-v/src/sg2000/sg2000_irq_dispatch.c, arch/risc-v/src/sg2000/sg2000_memorymap.h, arch/risc-v/src/sg2000/sg2000_mm_init.c, arch/risc-v/src/sg2000/sg2000_mm_init.h, arch/risc-v/src/sg2000/sg2000_pgalloc.c, arch/risc-v/src/sg2000/sg2000_start.c, arch/risc-v/src/sg2000/sg2000_timerisr.c
This PR adds support for the SOPHGO SG2000 SoC, based on T-Head C906 64-bit RISC-V Core. This will be used by the upcoming port of NuttX for Milk-V Duo S SBC.
Most of the code was derived from NuttX for Ox64 BL808. [The source files are explained in the articles here](https://github.com/lupyuen/nuttx-sg2000)
`Kconfig`: Added ARCH_CHIP_SG2000 for SG2000 SoC
`include/sg2000/chip.h`: SG2000 Definitions
`include/sg2000/irq.h`: External Interrupts
`src/sg2000/chip.h`: Interrupt Stack Macro
`src/sg2000/sg2000_allocateheap.c`: Kernel Heap
`src/sg2000/sg2000_head.S`: Linux Header and Boot Code
`src/sg2000/sg2000_irq.c`: Configure Interrupts
`src/sg2000/sg2000_irq_dispatch.c`: Dispatch Interrupts
`src/sg2000/sg2000_memorymap.h`: Memory Map
`src/sg2000/sg2000_mm_init.c`, `sg2000_mm_init.h`: Memory …
=> arch/risc-v: Add support for SOPHGO SG2000 SoC (T-Head C906)

drivers/can/sja1000.c
Fix SJA1000 Rx buffer pointer issue.
On the SJA1000_FDTOL IP implementation of this controller, if a buffer release is performed with nothing in the Rx FIFO, the internal FIFO pointers wrap around and the controller never recovers.
This patch removes the call to release the buffer on initialisation which fixes this issue and should also be safe for all other implementations of this controller as a reset of the controller clears the FIFO. 
Any system using this common SJA1000 driver.
Built and tested on the [Digilent ARTY_A7](https://digilent.com/shop/arty-a7-artix-7-fpga-development-board/) development board with an [SJA1000_FDTOL](https://gitlab.fel.cvut.cz/canbus/zynq/sja1000-fdtol) IP core integrated.
=> drivers/can/sja1000: fix Rx buffer pointer issue

drivers/sensors/bmi270_base.c
Little typo in the spelling of Bosch.
None.
Not Applicable.
=> BMI270 typo fix

drivers/sensors/Make.defs
Fix apparent typo in makefile to build in the bmi270_uorb file.
Mirrors what has been done in the cmake environment.
Users of BMI270 UORB building with Make.
Build with CONFIG_SENSORS_BMI270_UORB=y.
Without patch - fails.
With patch - passes.
=> sensors/bmi270: fix bmi270_uorb build

arch/risc-v/include/elf.h, arch/risc-v/src/common/riscv_tcbinfo.c
Adds the missing elf_gregset_t type definition so pr_regs field can be resolved. Coredumps can be produced for both 32 and 64 bit targets.
Can produce coredumps for postmortem or runtime analysis.
`rv-virt:nsh` and `rv-virt:nsh64` with:
```
CONFIG_BOARD_COREDUMP_SYSLOG=y
CONFIG_ELF_COREDUMP=y
CONFIG_SYSTEM_COREDUMP=y
```
And our custom Litex based target which also uses `CONFIG_BUILD_KERNEL`. Although system coredump is not available in user context.
Using the same procedure outlined in: https://nuttx.incubator.apache.org/docs/latest/guides/coredump.html
Example gdb session:
```
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to …
```
=> arch/risc-v/include/elf.f: Support coredump for rv32 and rv64 targets.

arch/risc-v/src/common/riscv_internal.h, arch/risc-v/src/common/riscv_modifyreg32.c, arch/risc-v/src/k210/k210_fpioa.c, arch/risc-v/src/mpfs/mpfs_dsn.c, arch/risc-v/src/mpfs/mpfs_ethernet.c
This revises the MMIO register access methods for RV64ILP32 so that
to reach peripherals beyond rv64ilp32 compiler generated addresses.
risc-v
- local checks with rv-virt target
- CI checks
=> arch/risc-v: revise MMIO for rv64ilp32

arch/arm64/src/common/arm64_cpustart.c, arch/arm64/src/common/arm64_fatal.h, arch/arm64/src/common/arm64_gicv3.c
Use correct log level for errors.
No.
qemu
=> arch/arm64: use serr for error log

tools/ci/docker/linux/Dockerfile
Add prebuilt AVR32 GCC toolchain from ramangopalan
https://github.com/ramangopalan/avr32-gnu-toolchain-linux_x86
at32uc3a0: Initial work for SimpleMachines' Mizar32-A #11709
none
https://github.com/apache/nuttx/actions/runs/9537180645/job/26284964386
=> tools/ci/docker/linux/Dockerfile: add AVR32 GCC toolchain

arch/risc-v/src/common/riscv_mtimer.c, arch/risc-v/src/common/riscv_mtimer.h
This revises `mtime` and `mtimecmp` registers address types to support rv64ilp32 ABI.
risc-v port
- local checks with `rv-virt`
- CI checks
=> arch/risc-v: revise mtimer for rv64ilp32

drivers/can/sja1000.c
Fix a typo to the command register write that was introduced in 695381442584466727c5c74ec46a2ebc04d6ce11
Any system using this common SJA1000 driver.
Built and tested on the [Digilent ARTY_A7](https://digilent.com/shop/arty-a7-artix-7-fpga-development-board/) development board with an [SJA1000_FDTOL](https://gitlab.fel.cvut.cz/canbus/zynq/sja1000-fdtol) IP core integrated.
=> drivers/can/sja1000: fix cmd register write

arch/arm64/src/common/arm64_head.S, arch/arm64/src/common/arm64_internal.h
- 1. minor update to `boot_stage_puts`, save/restore LR out of the loop.
- 2. pointer to stack frame must be aligned.
No.
Internal project and qemu.
=> arm64: align stack pointer and misc update

arch/risc-v/src/k230/hardware/k230_memorymap.h, arch/risc-v/src/k230/k230_hart.c, arch/risc-v/src/k230/k230_irq.c, arch/risc-v/src/k230/k230_irq_dispatch.c
This adds initial support of rv64ilp32 for K230 device. It allows FLAT build to run on K230 devices.
k230 devices
- local test with CanMV230 device
- CI checks
=> risc-v/k230: initial rv64ilp32 support

arch/risc-v/include/types.h, arch/risc-v/src/common/riscv_internal.h, arch/risc-v/src/common/riscv_sbi.h, arch/risc-v/src/common/supervisor/riscv_sbi.c
To simplify processing, the existed SBI function code is just invoking the ecall and return the error value. This omits potential return value in "a1", which is defined in SBI doc. Add the "sbiret" struct so it can handle all the return value.
In addition, there are some minor improvement:
1. move the SBI related interface to a separate file to make it clean.
2. add all necessary SBI ecall interface macro until version 2.0.
3. add an utilty function to convert sbi error numner to standard error number.
This should have no impact.
`rv-virt/flats64`
[nuttx.log](https://github.com/user-attachments/files/15884815/nuttx.log)
=> arch/risc-v: Improve the SBI function handle

Documentation/platforms/risc-v/esp32c3-legacy/index.rst, Documentation/platforms/risc-v/esp32c3/index.rst, Documentation/platforms/risc-v/esp32c6/index.rst, Documentation/platforms/risc-v/esp32h2/index.rst, Documentation/platforms/xtensa/esp32/index.rst, Documentation/platforms/xtensa/esp32s2/index.rst, Documentation/platforms/xtensa/esp32s3/index.rst
This commit improves the documentation about Espressif's toolchain and debugging tools for the supported SoCs on NuttX.
None.
Local `make html` build as described in https://nuttx.apache.org/docs/latest/contributing/documentation.html
=> Documentation: Improve Espressif toolchain/debugger documentation

Documentation/components/net/index.rst, Documentation/components/net/ipfilter.rst, include/nuttx/net/netfilter/ip6_tables.h, include/nuttx/net/netfilter/ip_tables.h, include/nuttx/net/netfilter/x_tables.h, net/Kconfig, net/Makefile, net/devif/devif_poll.c, net/devif/ipv4_input.c, net/devif/ipv6_input.c, net/inet/ipv6_getsockopt.c, net/inet/ipv6_setsockopt.c, net/ipfilter/CMakeLists.txt, net/ipfilter/Kconfig, net/ipfilter/Make.defs, net/ipfilter/ipfilter.c, net/ipfilter/ipfilter.h, net/ipforward/ipv4_forward.c, net/ipforward/ipv6_forward.c, net/netfilter/CMakeLists.txt, net/netfilter/Kconfig, net/netfilter/Make.defs, net/netfilter/ip6t_sockopt.c, net/netfilter/ipt_filter.c, net/netfilter/ipt_sockopt.c, net/netfilter/iptables.h
- net: Support IP packet filter
- net/netfilter: Add filter table in iptables.
- net: Add set/getsockopt options compatible with ip6tables
- net/netfilter: Add filter table in ip6tables
- Documentation: Add docs for ipfilter
Add a firewall compatible with Linux's iptables and ip6tables, with chains at similar points in the packet processing path. More details and examples are in the doc.
```
NIC ──> ipv[46]_input ─┬─> ipv[46]_forward ──> [FORWARD CHAIN] ──> devif_poll_out ──> NIC
│                                                 ^
│                  ┌─>  tcp  ─┐                   │
│                  ├─>  udp  ─┤                   │
└─> [INPUT CHAIN] ─┼─> icmp  ─┼─> [OUTPUT CHAIN] ─┘
├─> icmp6 ─┤
└─>  ...  ─┘
```
Changes limited in `net/ipfilter`(firewall) …
=> net: Support packet filter (firewall) and corresponding iptables/ip6tables

drivers/power/pm/pm_runtime.c
isolate with pm_runtime and pm_domain, for further usage optimise.
there is critical_section inside rpm_changestate,
use seperate spinlock is not compatible.
before fix, #12503 will be blocked.
None.
CI-test
=> pm_runtime: lock use pm_runtime_lock

arch/arm/src/stm32h7/Kconfig, arch/arm/src/stm32h7/stm32_ethernet.c
- In some cases, an operational Ethernet MAC may have no PHY, for example when the system has a direct RMII MAC-to-MAC link.
- New config option STM32H7_NO_PHY
- With this option, PHY-specific code in the ethernet driver is not built
- This option is inherently incompatible with autonegotiation and speed and duplex settings must be compiled in
- With STM32H7_NO_PHY, a MAC-to-MAC link without any PHY can be used.  Without STM32H7_NO_PHY, no impact.
- Tested with STM32H7_NO_PHY with px4_fmu-v6s and an RMII MAC-to-MAC link
- Without STM32H7_NO_PHY - which is the default - it is reasonable to determine by inspection that this PR does not change the code from before the introduction of the option.
=> stm32h7: allow Ethernet MAC without PHY

fs/driver/fs_registerdriver.c
Add note mark when a new driver is registered. This can roughly show us how much time every driver initialization takes because normally all drivers are registered sequentially.
No
Internal project.
=> driver: add note when driver registers

sched/Kconfig, sched/signal/sig_action.c, sched/signal/signal.h
Currently the sigaction objects are never reclaimed after use, thus after running
`ostest` we will see used memory increasion.
This patch uses a configurable number of pre-allocated entries and reclaims dynamic
entries so that to reduce leakage.
Used memory reduced after running `ostest`.
- Checked with `rv-virt/nsh`  and  `rv-virt/nsh64`
- CI checks
=> sched/signal: reclaim sigaction

drivers/power/pm/greedy_governor.c, drivers/power/pm/pm.h, drivers/power/pm/pm_activity.c, drivers/power/pm/pm_initialize.c, drivers/power/pm/pm_lock.c, drivers/power/pm/stability_governor.c
As we always want to take critical_section, and it is not long time job, take mutex is not necessary, use spinlock_irq_save as a replace is better, dont't have to take global critial_section in pm.
If we did lots of job inside pm callback, will make the 2nd waiter change from  mutex wait to the spinlock wait. maybe have few side effect.
But we shall not make it happen. so only benifit from removed mutex operation.
Also global critical_section is not necessary here.
CI-test and cortex-M33 chip board.
=> pm: change pm lock from mutex to spinlock

arch/risc-v/include/inttypes.h, arch/risc-v/src/common/riscv_internal.h
This moves PRIxREG to inttypes.h to make it available for both kernel
and user spaces.
arch/risc-v
- local tests with `rv-virt`
- CI checks
=> arch/risc-v: move PRIxREG to inttypes.h

arch/arm/src/armv6-m/arm_sigdeliver.c, arch/arm/src/armv7-a/arm_sigdeliver.c, arch/arm/src/armv7-m/arm_sigdeliver.c, arch/arm/src/armv7-r/arm_sigdeliver.c, arch/arm/src/armv8-m/arm_sigdeliver.c, arch/arm/src/armv8-r/arm_sigdeliver.c, arch/arm64/src/common/arm64_sigdeliver.c, arch/risc-v/src/common/riscv_sigdeliver.c, arch/sparc/src/sparc_v8/sparc_v8_sigdeliver.c, arch/xtensa/src/common/xtensa_sigdeliver.c
cpu0                                               cpu1:
user_main
signest_test
sched_unlock
nxsched_merge_pending
nxsched_add_readytorun
up_cpu_pause  
arm_sigdeliver
enter_critical_section
Reason:
In the SMP, cpu0 is already in the critical section and waiting for cpu1 to enter the suspended state. However, when cpu1 executes arm_sigdeliver, it is in the irq-disabled state but not in the critical section. At this point, cpu1 is unable to respond to interrupts and is continuously attempting to enter the critical section, resulting in a deadlock.
Resolve:
adjust the logic, do not entering the critical section when interrupt-disabled.
NONE
test:
compiling
running
qemu-system-aarch64 …
=> signal: fix deadlock when sigdeliver call enter_critical_section

include/nuttx/mm/mempool.h, include/nuttx/mm/mm.h, mm/Kconfig, mm/mempool/mempool_multiple.c, mm/mm_heap/mm.h, mm/mm_heap/mm_free.c, mm/mm_heap/mm_initialize.c, mm/mm_heap/mm_mallinfo.c, mm/mm_heap/mm_malloc.c, mm/mm_heap/mm_malloc_size.c, mm/mm_heap/mm_memalign.c, mm/mm_heap/mm_memdump.c, mm/mm_heap/mm_realloc.c, mm/tlsf/mm_tlsf.c
make possible enable pool, but disabled in system heap. also compatible for further extra heap use/not use pool.
Now use MM_HEAP_MEMPOOL_THRESHOLD 
>0 Enable pool feature, and set umm/kmm pool threshold size.
==0 Enable pool feature, but disable the umm/kmm pool function.
<0 to indicate pool disabled.(default -1)
CI-test and Cortex-A7 Board.
=> mm: seperate mm_pool and mm_pool init

arch/risc-v/include/bl808/irq.h, arch/risc-v/src/bl808/Make.defs, arch/risc-v/src/bl808/bl808_courier.c, arch/risc-v/src/bl808/bl808_courier.h, arch/risc-v/src/bl808/bl808_irq.c, arch/risc-v/src/bl808/hardware/bl808_ipc.h, arch/risc-v/src/bl808/hardware/bl808_memorymap.h, boards/risc-v/bl808/ox64/src/bl808_appinit.c
This change implements a system for allowing the D0 core (which runs NuttX) to receive forwarded interrupts from the M0 core (the peripheral / wireless core). This is implemented using the IPC interrupt: when the M0 core receives an interrupt, it sends an IPC notification to the D0 core containing the IRQ number. This triggers an ISR on D0, which takes the message and dispatches the appropriate ISR using virtual interrupt identifiers within NuttX.
**Note: Currently, the boot system for NuttX on the BL808 depends on a piece of firmware originally meant for Linux support, named m0_lowload. The system described in this PR requires a somewhat modified version of this firmware to be flashed, which is available [here](https://github.com/henryrov/OBLFR/releases/tag/m0_lowload_nuttx_v1).**
This …
=> arch/risc-v/bl808: Add courier system driver

include/nuttx/tls.h, libs/libc/stdlib/lib_getprogname.c, sched/environ/env_dup.c, sched/group/group_argvstr.c, sched/group/group_create.c, sched/group/group_setuptaskfiles.c, sched/init/nx_start.c, sched/sched/sched.h, sched/sched/sched_get_tls.c, sched/task/task_create.c, sched/task/task_fork.c, sched/task/task_setup.c, sched/task/task_start.c, sched/tls/tls_initinfo.c
Current task group data is embedded in the task TCB, this is also used for kernel threads, which seems can share the `group` as they all live in kernel space.
This patch uses `tcb_s` for kthreads with a shared `group` instance. Thus the overhead is reduced when more kthreads are in use. 
Memory usage of group instance, i.e. `sizeof(task_group_s)`, on `rv-virt` device:
| config  | size |
| ------- | ---- |
| nsh     | 720  |
| nsh64   | 1160 |
| knsh32  | 248  |
| knsh64  | 440  |
Kernel memory footprints collected from attached logs:
| config | kthreads # | upstream | patched  | saved |
| ------ | ---------- | -------- | -------- | ----- |
| nsh    | 1          | 7044     | 7044     | 0     |
| nsh64  | 1          | 10344    | 10344    | 0     |
| knsh32 | 2          | 10348    | 9660 …
=> sched/tcb: use shared group for kthreads

arch/risc-v/src/nuttsbi/sbi_mexception.c, arch/risc-v/src/nuttsbi/sbi_mtrap.S
This adds MTVAL argument to sbi_mexception() so that to have a complete story about the exception. this is useful for debugging.
NUTTSBI exception
- local tesing with k230 device
- CI checks
=> riscv/nuttsbi: add MTVAL argument

mm/iob/iob_alloc.c, mm/iob/iob_free.c
- `g_iob_sem.semcount` must be equal to the total number of free IOBs. It can also be negative if there are no free IOBs and there are threads
waiting for an IOB.
- g_throttle_sem.semcount represents the number of IOBs available for throttled IOB allocations. Like any other semaphore, it should only go
negative if there is a thread waiting for it.
- Both semaphores are related to the same resource (free IOBs), hence, they must be incremented/decremented simultaneously:
- Whenever a IOB buffer is freed, if a thread is waiting for a non-throttled IOB or a thread is waiting for a throttled IOB and we have at least `CONFIG_IOB_THROTTLE` buffers available, the IOB is put in the committed list (`g_iob_committed`). Otherwise, it is put in the
common free list (`g_iob_freelist`).
- `g_iob_sem` is …
=> mm/iob: Simplify IOB alloc/free logic

include/nuttx/mm/mm.h, mm/kmm_heap/kmm_initialize.c, mm/mm_heap/mm_initialize.c, mm/tlsf/mm_tlsf.c, mm/umm_heap/umm_initialize.c
now allow enable pool for extra heap, and disable umm/kmm pool.
The mm_initialize now always init without pool, and replaced with mm_initialize_pool
CI-test and Cortex-A7 board
=> mm: add mm_initialize_pool, make pool more flexible

boards/arm/nrf91/common/src/nrf91_boot_image.c, include/nuttx/compiler.h
rename CMSE extension attribute macros to avoid conflicts with 3rd party code:
cmse_nonsecure_entry -> tz_nonsecure_netry
cmse_nonsecure_call -> tz_nonsecure_call
Code using these CMSE macros needs to be updated
CI
=> compiler.h: rename CMSE extension attribute macros

sched/init/nx_bringup.c, sched/sched/sched_releasetcb.c, sched/task/exit.c
This attempts to fix the regression issues in 12320.
Kernel builds using `AppBringup` thread.
- local checks on `rv-virt` using `knsh64 + BOARD_LATE_INITIALIZE`
- CI checks
=> sched/tcb: ammending patch 12320

openamp/.gitignore, openamp/libmetal.cmake, openamp/libmetal.defs, openamp/open-amp.cmake
- use `nuttx_add_external_library` to reuse OpenAMP CMake scripts for CMake build
- automatically detect `HAVE_STDATOMIC_H` with CMake
- add support for `64-bit` ATOMIC checks to both Makefile and CMake
CI test
=> cmake:reuse OpenAMP own CMake script for CMake build

arch/risc-v/src/esp32c3-legacy/esp32c3_wifi_adapter.c, arch/risc-v/src/esp32c3/esp_wifi_adapter.c, arch/risc-v/src/esp32c6/esp_wifi_adapter.c, arch/xtensa/src/esp32/esp32_wifi_adapter.c, arch/xtensa/src/esp32s3/esp32s3_wifi_adapter.c
* espressif: Fix error while evaluating Wi-Fi task ID
Use `nxsched_gettid` instead of `nxsched_getpid`. Previously each kernel thread was modeled as a task, so the pid is the same of the kthread id. Now, with shared kthread group (introduced by #12320), the pid of all kthreads will be 0 by design in shared group.
Fix Wi-Fi-related configurations that are failing.
=> espressif: Fix error while evaluating Wi-Fi task ID

arch/arm/src/imxrt/imxrt_clockconfig_ver2.c
For best stability it's better to run the core voltage at 1p15v 
imxrt11xx
Pixhawk V6X-RT
=> imxrt: imxrt11xx set core clock to 1p15v regardless of ocotp

sched/signal/sig_kill.c, sched/signal/sig_procmask.c, sched/signal/sig_queue.c, sched/signal/sig_tgkill.c
purpose:
1 sched_lock is very time-consuming, and reducing its invocations can improve performance. 2 sched_lock is prone to misuse, and narrowing its scope of use is to prevent people from referencing incorrect code and using it
test:
compiling
=> sched/signal: There is no need to use sched_[un]lock

drivers/net/Kconfig, drivers/net/ksz9477.c, drivers/net/ksz9477_reg.h, include/nuttx/net/ksz9477.h
Enables support for the port mirroring and snooping.
All the packets received on port A and/or transmitted on port B can be mirrored on the sniffer port.
ksz9477 driver only
Custom MPFS board
=> drivers/net/ksz9477: Add port mirroring support

arch/risc-v/src/bl808/Make.defs, arch/risc-v/src/bl808/bl808_gpio.c, arch/risc-v/src/bl808/bl808_gpio.h, arch/risc-v/src/bl808/hardware/bl808_memorymap.h
- This PR adds the GPIO Driver for BL808 SoC. This will be used by the upcoming LED Driver for Ox64 Board.
- The BL808 GPIO Driver was derived from the NuttX Driver for BL602 GPIO
- `hardware/bl808_memorymap.h`: GPIO Base Address
- `Make.defs`: Added GPIO Source Files
- `bl808_gpio.c`: GPIO Functions
- `bl808_gpio.h`: GPIO Declarations
- With this PR, NuttX for Ox64 will be able to access GPIO Pins
- This PR is needed for the upcoming LED Driver for Ox64 Board
- No impact on existing code, since the BL808 GPIO source files are not used by existing code
We tested the BL808 Driver on Ox64 Emulator. Rust Blinky blinks the Simulated LED correctly:
- [Test Log for Ox64 Emulator](https://github.com/rushabhvg/rushabhvg.github.io/blob/master/nuttx/GPIO%20and%20LED%20Driver/0121b39efe%20build_log.t …
=> risc-v/bl808: Add GPIO Driver

arch/x86_64/src/intel64/Kconfig, arch/x86_64/src/intel64/intel64_freq.c
- arch/intel64: get TSC frequency only when not provided from Kconfig
On ACRN hypervisor obtaining frequency from CPUID seems to be broken, so we have to specify this value from Kconfig.  If frequency autodetection is enabled but the returned data are incorrect - crash early.
handle properly broken cpuid data
x86 hardware
=> arch/intel64: get TSC frequency only when not provided from Kconfig

libs/libm/libm/lib_sincos.c, libs/libm/libm/lib_sincosf.c, libs/libm/libm/lib_sincosl.c, libs/libm/newlib/0004-newlib-disable-optmisation-for-sincos.patch, libs/libm/newlib/CMakeLists.txt, libs/libm/newlib/Make.defs, libs/libm/newlib/sincosl.c
- libm/libm: disable optimization for sincos
- libm/newlib: disable optimization for sincos
Disable sincos optimization otherwise gcc would generate infinite calls.
Refer to gcc bug 46926: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=46926
-fno-builtin-sin or -fno-builtin-cos can disable sincos optimization,
but these two options do not work inside optimize pragma in-file.
Thus we just enforce -O0 when compiling this file.
fix broken sincos when high optimization enabled
x86 with -O3
=> libm{libm|newlib}: fix broken sincos optimization for GCC

arch/x86_64/src/common/x86_64_initialize.c
arch/x86_64: addrenv should add offset only for RAM region
CI
=> arch/x86_64: addrenv should add offset only for RAM region

CMakeLists.txt
Fix cmake build failure that apps directory is not found when -DNUTTX_APPS_DIR is specified.
CMake build when -DNUTTX_APPS_DIR is specified.
=> cmake: Fix build failure when -DNUTTX_APPS_DIR is specified

Documentation/platforms/risc-v/esp32c3/index.rst, Documentation/platforms/risc-v/esp32c6/index.rst, Documentation/platforms/risc-v/esp32h2/index.rst, arch/risc-v/src/common/espressif/Kconfig, arch/risc-v/src/common/espressif/Make.defs, arch/risc-v/src/common/espressif/esp_dma.c, arch/risc-v/src/common/espressif/esp_dma.h, arch/risc-v/src/esp32c3/hal_esp32c3.mk, arch/risc-v/src/esp32c6/hal_esp32c6.mk, arch/risc-v/src/esp32h2/hal_esp32h2.mk
- esp32[c3|c6|h2]: Add GDMA support
ESP32-C3, ESP32-C6 and ESP32-H2
Tested with a custom app
=> esp32[c3|c6|h2]: Add GDMA support

arch/arm/src/cxd56xx/CMakeLists.txt, boards/arm/cxd56xx/common/CMakeLists.txt, boards/arm/cxd56xx/drivers/CMakeLists.txt, boards/arm/cxd56xx/drivers/audio/CMakeLists.txt, boards/arm/cxd56xx/drivers/sensors/CMakeLists.txt, boards/arm/cxd56xx/spresense/src/CMakeLists.txt, drivers/audio/CMakeLists.txt
* arch: cxd56xx: Add audio sources to CMakeLists.txt
* arch: cxd56xx: Add gnss source to CMakeLists.txt
* drivers/audio: Remove useless descriptions from CMakeLists.txt
* boards: cxd56xx: Fix CMakeLists.txt
* boards: cxd56xx: Add CMakeLists.txt for the specific drivers
Only for spresense board
=> Fix cmake for cxd56xx

arch/risc-v/src/common/riscv_pmp.c
This allows using 0 base and size as the special whole region in NAPOT format, as sometimes we need permissive entry at tail of PMP list.
PMP configuration
- local check on CanMV230
- CI checks
=> arch/riscv: add all region in NAPOT

include/sched.h
- include/sched.h: CPU_XXX macros can also be used without CONFIG_SMP
Allow CPU_XXX macros to be used without CONFIG_SMP=y
CI
=> include/sched.h: CPU_XXX macros can also be used without CONFIG_SMP

arch/arm64/include/fvp-v8r/irq.h, arch/arm64/include/goldfish/irq.h, arch/arm64/include/irq.h, arch/arm64/include/qemu/irq.h, arch/arm64/src/common/arm64_arch.h, arch/arm64/src/fvp-v8r/fvp_boot.c, arch/arm64/src/goldfish/goldfish_boot.c, arch/arm64/src/qemu/qemu_boot.c
arm64: inline up_cpu_index
reduce the time consumed by function call
compiling
=> arm64: inline up_cpu_index

arch/risc-v/src/nuttsbi/sbi_start.c
This fixes PMP size param in `sbi_start()` as it needs be POT per pull/#12398.
NUTTSBI uses
- local checks with canmv230/nsbi
- CI checks
=> arch/riscv: fix NuttSBI PMP config

arch/risc-v/src/common/riscv_exception.c
riscv_exception.c: Add missing comma in exception reasons array
Minor
=> riscv_exception.c: Add missing comma in exception reasons array

arch/x86_64/Kconfig, arch/x86_64/include/intel64/arch.h, arch/x86_64/src/intel64/intel64_irq.c
- arch/intel64: add support for inter-processor signaling
Add support for inter-processor signaling in x86_64 based on up_trigger_irq() interface. Preparations for SMP.
new x86 api
x86 smp
=> arch/intel64: add support for inter-processor signaling

openamp/0004-libmetal-atomic-enable-64-bit-atomic-by-toolchain-bu.patch, openamp/libmetal.cmake, openamp/libmetal.defs
libmetal/atomic: enable 64-bit atomic by toolchain builtin flags
Fix compile error:
```
arm-none-eabi-ld: (remoteproc_virtio.o): in function `metal_io_read':
metal/io.h:252: undefined reference to `__atomic_load_8'
arm-none-eabi-ld: (remoteproc_virtio.o): in function `metal_io_write':
metal/io.h:290: undefined reference to `__atomic_store_8'
```
Not all 32-bit architectures support 64bit atomic, gcc/clang
toolchains have built-in properties to indicate whether support atomic64:
```
| $ arm-none-eabi-gcc -march=armv7e-m  -dM -E - < /dev/null | grep SYNC
| #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1 1
| #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 1
| #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 1
```
N/A 
CI-CHECK
=> libmetal/atomic: enable 64-bit atomic by toolchain builtin flags

fs/procfs/fs_procfsproc.c, include/execinfo.h, libs/libc/misc/lib_execinfo.c, mm/mempool/mempool.c, mm/mm_heap/mm_memdump.c, mm/tlsf/mm_tlsf.c
Extract a common method to format backtrace.
No.
boards/arm64/qemu/qemu-armv8a/configs/nsh with related options enabled.
=> libc/execinfo: extract a common backtrace format function

CMakeLists.txt, cmake/nuttx_redefine_symbols.cmake
fix error:
```
[100%] Linking C executable nuttx
/usr/bin/ld: nuttx.rel: in function `uv_key_create': /home/data/vela/github/apps/system/libuv/libuv/src/unix/thread.c:846: undefined reference to `NXpthread_key_create' /usr/bin/ld: nuttx.rel: in function `uv_key_get':
/home/data/vela/github/apps/system/libuv/libuv/src/unix/thread.c:857: undefined reference to `NXpthread_getspecific' /usr/bin/ld: nuttx.rel: in function `uv_key_set':
/home/data/vela/github/apps/system/libuv/libuv/src/unix/thread.c:862: undefined reference to `NXpthread_setspecific' collect2: error: ld returned 1 exit status
```
this PR is needed by https://github.com/apache/nuttx-apps/pull/2426
CI
=> cmake:refine sim cmake redefine symbols

arch/Kconfig, arch/arm/src/common/arm_exit.c, arch/arm64/src/common/arm64_exit.c, arch/avr/src/common/avr_exit.c, arch/hc/src/common/hc_exit.c, arch/mips/src/common/mips_exit.c, arch/misoc/src/lm32/lm32_exit.c, arch/misoc/src/minerva/minerva_exit.c, arch/or1k/src/common/or1k_exit.c, arch/renesas/src/common/renesas_exit.c, arch/risc-v/src/common/riscv_exit.c, arch/sparc/src/common/sparc_exit.c, arch/tricore/src/common/tricore_exit.c, arch/x86/src/common/x86_exit.c, arch/x86_64/src/common/x86_64_exit.c, arch/xtensa/src/common/xtensa_exit.c, arch/z16/src/common/z16_exit.c, arch/z80/src/common/z80_exit.c, fs/inode/fs_files.c, fs/inode/inode.h, fs/procfs/fs_procfsproc.c, fs/vfs/fs_open.c, include/nuttx/fs/fs.h, sched/sched/sched_dumponexit.c, sched/task/task_exithook.c
~Add option to dump fdinfo when assert happens, as required in~
`file_ioctl` is required to get file path, thus not available in assert. Currently file list is only dumped on task exit.
https://github.com/apache/nuttx/pull/12532#issuecomment-2179500766
nxsched_dumponexit has been moved forward to task_exithook, in order to access the `group` before it's destroyed.
Example of crash log:
```
nsh> mw -1
_assert: Current Version: NuttX  12.5.1 a8d7f155b8 Jun 28 2024 23:19:10 arm64
_assert: Assertion failed panic: at file: /home/neo/projects/nuttx/nuttx/arch/arm64/src/common/arm64_fatal.c:375 task: nsh_main process: nsh_main 0x402a10a8
up_dump_register: stack = 0x4040a230
up_dump_register: x0:   0xffffffffffffffff  x1:   0x0
up_dump_register: x2:   0x4040a300          x3:   0x0 …
```
=> Fs backtrace tweak

arch/x86_64/include/irq.h
Use 32bit operations for id field in intel64_cpu_s which is int type.
This fixes an error that appears when enabling some debug options:
Error: operand size mismatch for `movq'`
CI
=> x86_64/irq.h: use 32bit operations in up_cpu_index()

libs/libc/stdlib/lib_mkstemp.c
As a reference, https://man7.org/linux/man-pages/man3/mkstemp.3.html
We should remove the read/write permission of other users for temp file.
should be lower permission risk.
CI-test
=> mkstemp: permission 0666 to 0600

arch/xtensa/src/esp32/esp32_openeth.c
When the PSRAM is enabled, we should not allocate the TX/RX buffers there, so we use kmm_calloc here, to make it into IRAM, so the ethernet controller can read bytes from it.
esp32-qemu-openeth works now with PSRAM enabled.
No testing is performed for these config
=> fix(esp32-qemu-openeth): allocate buffers in internal memory

libs/libc/stdio/lib_libvscanf.c, libs/libc/stdio/lib_libvsprintf.c
Will cause a ”switch_selector_expr_is_constant“ catched by coverity.
switch const may not good for compile optimize?
And put sizeof in #if look like not a good style.
when optimise levels enabled, will auto slim to a single value copy. No actual difference.
CI-test
=> libc: scanf, printf %z change switch const to if

arch/arm/src/armv6-m/arm_doirq.c, arch/arm/src/armv7-a/arm_doirq.c, arch/arm/src/armv7-m/arm_doirq.c, arch/arm/src/armv7-r/arm_doirq.c, arch/arm/src/armv8-m/arm_doirq.c, arch/arm/src/armv8-r/arm_doirq.c, arch/arm/src/tlsr82/tc32/tc32_doirq.c, arch/arm64/src/common/arm64_doirq.c, arch/ceva/src/common/ceva_doirq.c, arch/risc-v/src/common/riscv_doirq.c, arch/sim/src/sim/sim_switchcontext.c, arch/sparc/src/sparc_v8/sparc_v8_doirq.c, arch/xtensa/src/common/xtensa_irqdispatch.c
irq: remove restore_critical_section in irq
Only in the non-critical region， nuttx can the respond to the irq and not hold the lock When returning from the irq, there is no need to check whether the lock needs to be restored
compiling
=> irq: remove restore_critical_section in irq

sched/irq/irq_csection.c
irq: remove g_cpu_nestcount in restore_critical_section
because 'g_cpu_nestcount[me] > 0' will never happen, in this place
compiling
=> irq: remove g_cpu_nestcount in restore_critical_section

arch/arm/src/armv7-a/Kconfig, arch/arm/src/armv7-a/arm_cpupause.c, arch/arm/src/armv7-a/arm_cpustart.c, arch/arm/src/armv7-a/arm_gicv2.c, arch/arm/src/armv7-a/arm_head.S, arch/arm/src/armv7-a/gic.h, arch/arm/src/armv7-r/arm_cpupause.c, arch/arm/src/armv7-r/arm_cpustart.c, arch/arm/src/armv7-r/arm_gicv2.c, arch/arm/src/armv7-r/gic.h, arch/arm/src/armv8-r/arm_gic.h, arch/arm/src/armv8-r/arm_gicv3.c, arch/arm64/src/common/arm64_cpupause.c, arch/arm64/src/common/arm64_gic.h, arch/arm64/src/common/arm64_gicv2.c, arch/arm64/src/common/arm64_gicv3.c
During the boot phase, when we transition from tee smp to ap smp, we can use a busy waitflag to wait for the completion of the initialization of ap's core0
test:
compiling
running
=> tee smp support

cmake/nuttx_add_library.cmake
cmake/add_library: enable library install by default
enable library install by default to support nuttx export for cmake
```
$ cmake --install build  --prefix $PWD/build/staging/
-- Install configuration: ""
-- Installing: /home/archer/code/nuttx/n3/nuttx/build/staging/lib/libarch.a
-- Installing: /home/archer/code/nuttx/n3/nuttx/build/staging/lib/libbinfmt.a
-- Installing: /home/archer/code/nuttx/n3/nuttx/build/staging/lib/libdrivers.a
-- Installing: /home/archer/code/nuttx/n3/nuttx/build/staging/lib/libfs.a
-- Installing: /home/archer/code/nuttx/n3/nuttx/build/staging/lib/libc.a
-- Installing: /home/archer/code/nuttx/n3/nuttx/build/staging/lib/liblibcxxmini.a
-- Installing: /home/archer/code/nuttx/n3/nuttx/build/staging/lib/libmm.a
-- Installing: …
```
=> cmake/add_library: enable library install by default

boards/arm/rp2040/common/include/rp2040_max6675.h, boards/arm/rp2040/common/src/Make.defs, boards/arm/rp2040/common/src/rp2040_common_bringup.c, boards/arm/rp2040/common/src/rp2040_max6675.c
Add support to MAX6675, see: https://www.embeddedrelated.com/showarticle/1673.php
For users
RaspberryPi Pico
=> rp2040: Add support to MAX6675

arch/xtensa/src/esp32/Kconfig, arch/xtensa/src/esp32/esp32_openeth.c
This current driver does not handle well netpkts used in the write buffers.
I learned about this document:
https://github.com/apache/nuttx/blob/master/Documentation/components/net/netdriver.rst
After I ported and contributed the original driver.
However from the document, I understand these types of drivers are simpler to implement and I could simplify the driver and handle correctly the TCP write buffers.
ESP32-opencores mac can handle writebuffers correctly.
Only local testing. Now I can even run mbedtls' ssl_client2.
=> refactor(esp32-qemu-openeth): use lower half driver interface

arch/xtensa/src/esp32/esp32_emac.c
ESP32: emac initialization adding cpu id
Only ESP32
=> ESP32: emac initialization adding cpu id

arch/sim/Kconfig, arch/sim/src/sim/sim_head.c
sometimes ubsan work with asan trigger a mistake report, make it possible to export library with ubsan, and bypass runtime feature.
No-impact for default,
can disable ubsan malloc/etc. in kconfig after this commit.
CI-test
=> sim: make possible keep ubsan and bypass feature

arch/arm/src/imxrt/imxrt_clockconfig_ver2.c
Fixes PLL PFD not being updated because PFD_UPDATE needs to toggled instead of being set
Minimal
V6X-RT
=> imxrt: Correctly update PLL, bit has to toggled instead of being set

arch/arm/src/samv7/sam_mcan.c
Following error caused by incorrect naming of few defines.
```
chip/sam_mcan.c:415:7: warning: "MCAN1_NTSEG1" is not defined, evaluates to 0 [-Wundef]
415 | #  if MCAN1_NTSEG1 > 63
|       ^~~~~~~~~~~~
chip/sam_mcan.c:418:7: warning: "MCAN1_NTSEG2" is not defined, evaluates to 0 [-Wundef]
418 | #  if MCAN1_NTSEG2 > 15
|       ^~~~~~~~~~~~
chip/sam_mcan.c:421:7: warning: "MCAN1_NSJW" is not defined, evaluates to 0 [-Wundef]
421 | #  if MCAN1_NSJW > 15
```
Build passes.
=> samv7/sam_mcan.c: fix TSEG1, TSEG2 and SJW compile warnings for MCAN1

arch/arm64/src/imx9/Kconfig, arch/arm64/src/imx9/Make.defs, arch/arm64/src/imx9/hardware/imx9_flexspi.h, arch/arm64/src/imx9/imx9_flexspi.c, arch/arm64/src/imx9/imx9_flexspi.h, arch/arm64/src/imx9/imx9_flexspi_nor.c, arch/arm64/src/imx9/imx9_flexspi_nor.h
This adds an initial support for m25p nor flash devices, connected to the FlexSPI bus, for the IMX9. The support consists of two parts:
- flexspi bus driver, ported from imxrt, there are changes to clock configurations, base addresses etc.
- flexspi nor MTD driver, partly copied from imxrt board specific code, partly from m25p generic driver. Parts are quite heavily modified though
The idea is that NOR MTD driver part can be later expanded to support other than M25P parts, if needed.
The board configuration is not added to this PR, as connecting the NOR flash requires custom HW; this is not directly available.
Impacts only IMX9 targets, adds support for FlexSPI and M25P NOR flash connected as quad.
Tested on IMX93 EVK board, connecting an M25P device to the bottom connector, enabling the …
=> Imx9 support flexspi m25p nor

CMakeLists.txt, arch/sim/Kconfig, arch/sim/src/Makefile
arch/sim: add custom data section support
The link script of NuttX Simulator is generated through compilation
options. This PR will support configure special data sections in
kconfig to meet the support of 3rd party applications.
we need to follow the syntax of linker script. In 3rd-party applications, some data will be labeled as section:
```
| a.c:
| struct task_s a __attribute__((section(".data.custom.taska")));
| b.c:
| struct task_s b __attribute__((section(".data.custom.taskb")));
```
Data of the same type struct can be placed in a fixed location to reduce the overhead caused by searching:
```
|   .data           :
|   {
|     _custom_data_table_start = .;
|     KEEP(*(.data.custom.*))
|     _custom_data_table_end = .;
|   }
```
Such section declare can be configured via Kconfig in …
=> arch/sim: add custom data section support 

arch/sim/src/cmake/Toolchain.cmake
sim/cmake: enable garbage collection of unused input sections
enable --gc-sections for linker
enable -ffunction-sections -fdata-sections for compiler
N/A
ci-check
=> sim/cmake: enable garbage collection of unused input sections

fs/fat/fs_fat32.c, fs/fat/fs_fat32.h
fs/fat: Fix Fseek Bug When File Size Is Multiple of Cluster Size
Unbinding `ff_currentcluster` and `f_pos`:
1. Added `ff_pos` in `struct fat_file_s`.
2. Added function `fat_zero_cluster` for doing zeroing for gap between EOF and new position beyond EOF.
3. Added function `fat_get_sectors` for getting the sector where `f_pos` is located, allocating new cluster when `f_pos` is beyond EOF.
4. Modify function `fat_read`, and `fat_write` with above functions.
5. Remove redundant logics in `fat_seek` since now new cluster is allocated when writing instead of seeking.
Before this commit, `f_pos` has two uses, one is to record the current read and write position of the file, and the other is to avoid repeated traversal of the cluster chain when reading and writing files.
So `f_pos` must point to …
=> FAT:Fix Fseek Bug When File Size Is Multiple of Cluster Size

boards/Kconfig, boards/arm/rp2040/seeed-xiao-rp2040/include/board.h, boards/arm/rp2040/seeed-xiao-rp2040/src/Make.defs, boards/arm/rp2040/seeed-xiao-rp2040/src/rp2040_autoleds.c, boards/arm/rp2040/seeed-xiao-rp2040/src/rp2040_boardinitialize.c, boards/arm/rp2040/seeed-xiao-rp2040/src/rp2040_bringup.c, boards/arm/rp2040/seeed-xiao-rp2040/src/rp2040_gpio.c, boards/arm/rp2040/seeed-xiao-rp2040/src/rp2040_pico.h, boards/arm/rp2040/seeed-xiao-rp2040/src/rp2040_userleds.c
The PR aims to add support to USERLEDS. Also, I added two new GPIO which can be used as output, those pins are connected to the LED on board.
None
Ran `LED driver examples`
https://github.com/apache/nuttx/assets/41307385/581889dc-135a-495b-9798-aa3c6f121d99
=> Userleds support to seed-xiao-rp2040

Documentation/components/syscall.rst
This fixes a few typos in `syscall.rst`.
None
CI checks
=> syscall/docs: fix a few typos

Documentation/components/drivers/index.rst, drivers/drivers_initialize.c, drivers/note/note_initialize.c, include/nuttx/drivers/drivers.h, include/nuttx/note/note_driver.h, sched/init/nx_start.c
Add `drivers_early_initialize` for drivers not reply on system resource. `note_sysview_initialize` is one of them to allow note to work as early as possible.
No.
stm32f429i-disco with systemview.
=> drivers: add API for drivers early initialization

mm/ubsan/ubsan.c
When try to use local ubsan to bypass the ubsan in host native, find dynamic_type_cache_miss was not catched by default
can re-direct dynamic_type_cache_miss from native to local after merge.
CI-test, local ubuntu sim.
=> mm_ubsan: add implement for dynamic_type_cache_miss

arch/arm64/src/imx9/hardware/imx93/imx93_ccm.h, arch/arm64/src/imx9/imx9_ccm.c, arch/arm64/src/imx9/imx9_ccm.h, arch/arm64/src/imx9/imx9_clockconfig.c, boards/arm64/imx9/imx93-evk/include/board.h
This adds enablers for setting various clocks to some default values. Also, this provides helpers to grant nonsecure access to a number of clocks. Bootloader may utilize these to make the system boot in a deterministic manner.
In order to boot up the system from scratch, some clocks need initialization and default values.
Only imx9 bootloader
IMX9-EVK with NuttShell, including DDR training (to be integrated later)
=> arm64/imx9: ccm: add default clk init

mm/Kconfig, mm/ubsan/ubsan.c
The dummy string in sim_ubsan did not work as expected, redirect ubsan to local .c files works pretty good in my case, so commit a code to make it possible in Kconfig.
need a PANIC in __ubsan_handle_builtin_unreachable to make sure no_return;
No impact for default config.
after merge, possible redirect to local ubsan and disable all malloc/print etc, actions.
CI-test, local ubuntu sim environment.
=> mm_ubsan: add dummy to bypass runtime actions

.gitignore, Documentation/platforms/arm64/imx9/boards/imx93-evk/README.txt, tools/imx9/Config.mk, tools/imx9/Makefile.host
This does the following:
1. Fetches mkimage_imx8 (same used with imx9) source code
2. Fetches the ELE / AHAB binary
3. Extracts the ELE / AHAB binary
4. Compiles the mkimage with hostcc
5. Utilizes the mkimage tool to create a bootable SD image, combining the ELE / AHAB image with the NuttX bootloader
6. dd is used to prepend empty space in place of BL31
7. Outputs sdimage.img which is a bootable binary
8. Removes all binaries, sources code images that have been downloaded
This creates the steps necessary for creating a bootable bootloader image for SD card.
imx9 bootloader version
imx9-evkit, various bootloaders
=> tools/imx9: prepare bootable bootloader image

arch/arm/src/sama5/sam_mcan.c, arch/arm/src/samv7/Kconfig, arch/arm/src/samv7/sam_mcan.c, arch/arm/src/stm32/stm32_fdcan.c, drivers/can/can.c, include/nuttx/can/can.h
This commit moves `can_bytes2dlc` and `can_dlc2bytes` from kernel internal functions to API. These functions are necessary to convert bytes to dlc for CAN FD frames and has to be accessible from the application since `can_hdr_s` does not store message length in bytes but directly in dlc.
This adds field type to `canioc_bittiming_s` structure that allows to set/obtain bit timing for both CAN CC and CAN FD. `CANIOC_GET_BITTIMING` is now bidirectional: user specifies type field and gets other fields from the controller.
The commit also updates current CAN FD capable controllers using the ioctl. The type is not checked for classical CAN only controllers and nominal bit timing is returned regardless of type value. 
Larger RX/TX buffers might be required for both FD and FD_BSW modes. Default …
=> can: fixes and tweaks for CAN FD support

drivers/mtd/mtd_nandecc.c, fs/mnemofs/mnemofs.h, fs/mnemofs/mnemofs_blkalloc.c, fs/mnemofs/mnemofs_rw.c
Adds Block Allocator and Bad Block check logic to mnemofs.
- Block Allocator logic.
- Bad Block check logic.
mnemofs can use its block allocator.
checkpatch and NAND flash virtual device in simulator.
=> fs/mnemofs: Adds Block Allocator

arch/arm/include/armv8-r/irq.h, arch/arm/src/armv8-r/Kconfig, arch/arm/src/armv8-r/arm_arch_timer.h, arch/arm/src/armv8-r/arm_initialstate.c, arch/arm/src/armv8-r/arm_vectors.S, arch/arm/src/armv8-r/cp15_cacheops.h
arch/armv8-r: fix typos in config
replace ARMV7R to ARMV8R
N/A
cortex-r52
=> arch/armv8-r: fix typos in config

arch/arm/src/armv8-r/Kconfig, arch/arm/src/armv8-r/arm_gicv3.c
arch/armv8-r: new config to set SPIs Configuration to edge-triggered
Configure all SPIs(Shared Peripheral Interrupts) as edge-triggered by default
N/A
Cortex-R52
=> arch/armv8-r: new config to set SPIs Configuration to edge-triggered

CMakeLists.txt, Kconfig
cmake: strip file full path to save the code size
Cmake build provide absolute paths to compile files. If `__FILE__`
macros are used in the source code(ASSERT), the binary will be occupied
by many invalid paths.
If the compiler support preprocessing files and expand the "`__FILE__`"
and "`__BASE_FILE__`" macros as if the files resided in directory new instead.
This saves some memory, stops leaking user locations in binaries, makes
failure logs more deterministic and most importantly makes builds more
deterministic.  Debuggers usually have a path mapping feature to ensure
the files are still found.
Test config sabre-6quad/citest:
Before:
```
$ size build/nuttx
279309     908   13652  293869   47bed build/nuttx
[ 2] nsh_main: _assert: Assertion …
```
=> cmake: strip file full path to save the code size

arch/avr/src/avr32/avr_doirq.c, boards/avr/at32uc3/avr32dev1/src/avr32_bringup.c, tools/ci/testlist/other.dat
removed in the tools/ci/testlist/other.dat file the entries
-avr32dev1:nsh
-avr32dev1:ostest
avr32_bringup.c
Fix  Error: ./avr32_bringup.c:54:4: error: #warning "Not Implemented" #11709
comment out directive '#warning'
/* #warning "Not Implemented" */
avr_doirq.c
fix avr32/avr_doirq.c:117: error: assignment discards qualifiers from pointer target type
regs = g_current_regs; -> regs = (uint32_t *)g_current_regs;
We tested on GitHub
=> tools/ci: enable avr32dev1 build

arch/arm/src/armv8-r/arm_doirq.c
arch/armv8-r: update g_running_tasks before context switch
fix invalid running_task() in assertion logic
N/A
Cortex-R52
=> arch/armv8-r: update g_running_tasks before context switch

boards/risc-v/esp32c3/common/.gitignore, boards/risc-v/esp32c6/common/.gitignore, boards/risc-v/esp32h2/common/.gitignore, boards/xtensa/esp32/common/.gitignore, boards/xtensa/esp32s2/common/.gitignore, boards/xtensa/esp32s3/common/.gitignore
boards/esp32[c3|c6|h2|s2|s3]: Ignore etctmp in common board
None
CI
=> boards/esp32[c3|c6|h2|s2|s3]: Ignore etctmp in common board

include/cxx/cmath
add rint rintf expm1 expm1f to cmath, so that Eigen library build can be passed
there should be no impact
build with eigen passed
=> add rint and expm1 function to cmath from libm

fs/mnemofs/CMakeLists.txt, fs/mnemofs/Make.defs, fs/mnemofs/mnemofs.h, fs/mnemofs/mnemofs_fsobj.c, fs/mnemofs/mnemofs_util.c
Pitr methods and path methods.
Add:
- Pitr methods
- Path methods
in mnemofs
mnemofs can do path related work.
checkpatch and nand virtual device simulator.
=> fs/mnemofs: Add parent iterator and path methods.

arch/arm/src/samv7/sam_pwm.c, arch/arm/src/samv7/sam_serial.c
The following warning is fixed:
```
chip/sam_pwm.c:961:12: warning: unused variable 'regval' [-Wunused-variable]
961 |   uint32_t regval;
```
=> samv7: fix compile warning in PWM driver

fs/mnemofs/CMakeLists.txt, fs/mnemofs/Make.defs, fs/mnemofs/mnemofs.h, fs/mnemofs/mnemofs_ctz.c, fs/mnemofs/mnemofs_lru.c, fs/mnemofs/mnemofs_rw.c, fs/mnemofs/mnemofs_util.c
LRU methods and CTZ methods to mnemofs
mnemofs can use its LRU.
checkpatch and NAND flash virtual device.
=> fs/mnemofs: Add LRU and CTZ methods

arch/risc-v/Kconfig, arch/risc-v/include/csr.h, arch/risc-v/src/common/CMakeLists.txt, arch/risc-v/src/common/Make.defs, arch/risc-v/src/common/riscv_debug.c
Implement up_debugpoint_add/up_debugpoint_remove for riscv, based on RISCV Debug Spec 0.13.2
New feature
Tested on QEMU and ESP32-C3 with https://github.com/apache/nuttx-apps/pull/2422.
```
NuttShell (NSH) NuttX-12.5.1
nsh> debug
Testing breakpoints
==== Calling test_function ====
Add breakpoint at 0x80016592
Calling test_trigger
Pass: Breakpoint at 0x80016592 triggered
==== Calling test_data ====
Add read watchpoint at 0x800295cc
Pass: Read watchpoint at 0x800295cc triggered
==== Calling test_data ====
Add read watchpoint at 0x8002c6c0
Pass: Read watchpoint at 0x8002c6c0 triggered
==== Calling test_data ====
Add write watchpoint at 0x8002c6c0
Pass: Write watchpoint at 0x8002c6c0 triggered
==== Calling test_data ====
Add read/write watchpoint at 0x8002c6c0
Pass: Read watchpoint at …
```
=> riscv: Initial support for debug trigger module

boards/risc-v/k230/canmv230/src/CMakeLists.txt
This fixes the issue that CMake fails to detect apps ROMFS source due to lack of path. Now with this the `romfs_boot.c` in build folder will be built as part of the NuttX kernel image.
CMake uses for KERNEL mode k230 configs
- local checks with canmv230:nsbi
- CI checks
=> riscv/k230: fix apps ROMFS cmake

net/netfilter/ip6t_sockopt.c
Resolve compilation errors encountered during compilation in windows platform.
sim:local
=> net/netfilter: fix windows compile error

include/fcntl.h, include/sys/file.h, libs/libc/unistd/CMakeLists.txt, libs/libc/unistd/Make.defs, libs/libc/unistd/lib_flock.c
To solve some compilation issues encountered during the porting of third-party libraries, this function has been added.
qemu local:x64
=> libc/unistd: added an implementation of the lib_flock function

include/nuttx/net/ioctl.h
This definition was added in order to solve some compilation problems encountered when porting third-party libraries
qemu local:x64
=> ioctl.h: add SIOCATMARK definition to resolve compilation errors

net/devif/devif.h, net/devif/devif_send.c, net/pkt/pkt_sendmsg.c
Enable the pkt_sendmsg interface to send packets containing Layer 2 headers.
qemu x64
=> net/pkt: correct PF_PACKET family sending errors

include/sched.h
Resolve undefined compile-time issues encountered when porting third-party libraries.
qemu local:x64
=> sched.h: add SCHED_BATCH and SCHED_IDLE definition

include/sys/sysinfo.h
This definition was added in order to solve some compilation problems encountered when porting third-party libraries
qemu local:x64
=> sysinfo.h: add get_nprocs_conf/get_nprocs definition

arch/arm64/src/common/arm64_boot.c
[https://developer.arm.com/documentation/ddi0595/2021-09/AArch64-Registers/ICC-SRE-EL3--Interrupt-Controller-System-Register-Enable-register--EL3-?lang=en](url)
ICC_SRE_EL3 register is present only when GICv3 is implemented and EL3 is implemented. Otherwise, direct accesses to ICC_SRE_EL3 are UNDEFINED.
Some chip's interrupt controller is GIC-400(GICv2), there will an exception when accesses ICC_SRE_EL3 register.
Allwinner A64, Zynq MPSOC
ZCU111 board
=> arm64/arm64_boot.c: Fix exception caused by accesses to ICC_SRE_EL3 when GICv3 was not implemented

drivers/net/lan9250.c, include/nuttx/net/lan9250.h
- Add lan9250_ioctl and lan9250_uninitialize APIs
=> driver/net/lan9250: Add lan9250_ioctl and lan9250_uninitialize APIs

Documentation/platforms/arm/s32k1xx/index.rst, arch/arm/src/s32k1xx/Kconfig, arch/arm/src/s32k1xx/Make.defs, arch/arm/src/s32k1xx/s32k1xx_flexio_i2c.c, arch/arm/src/s32k1xx/s32k1xx_flexio_i2c.h, boards/arm/s32k1xx/ucans32k146/include/board.h, boards/arm/s32k1xx/ucans32k146/src/Makefile, boards/arm/s32k1xx/ucans32k146/src/s32k1xx_bringup.c, boards/arm/s32k1xx/ucans32k146/src/s32k1xx_clockconfig.c, boards/arm/s32k1xx/ucans32k146/src/s32k1xx_i2c.c, boards/arm/s32k1xx/ucans32k146/src/s32k1xx_periphclocks.c
Configures the FlexIO peripheral to emulate I2C.
Albeit with some limitations.
- Max I2C speed of 400KHz
- Max transfer of 12 bytes (Could be extended by utilizing EDMA)
- No abort on NACK reception, shifter simplies continues on
- No multi-master support
- No restart support
Minimal
NXP UCANS32K1, BMS772
=> s32k1xx: FlexIO i2c driver

arch/arm/src/xmc4/CMakeLists.txt, arch/arm/src/xmc4/Kconfig, arch/arm/src/xmc4/Make.defs, arch/arm/src/xmc4/hardware/xmc4_ccu4.h, arch/arm/src/xmc4/xmc4_clockconfig.h, arch/arm/src/xmc4/xmc4_clockutils.c, arch/arm/src/xmc4/xmc4_pwm.c, arch/arm/src/xmc4/xmc4_pwm.h
Added a pwm lower-half driver for xmc4 arch, using the CCU4 unit. 
PWM driver must be activated in config. 
Then activate the CCU4 Peripheral (System Type -> XMC4xxxx Peripheral support)
Then enable the module you want to use (System Type -> XMC4xxxx PWM Configuration)
As timer concatenation isn't supported yet, each CCU4 slice (channel) is used as a different PWM output.
The CCU41,CC40 and CCU40,CC40 slices aren't usable when tickless OS is enabled. 
No impact on other functionalities. 
Tested on a XMC4800 custom board.
=> arm/xmc4: pwm driver

fs/mnemofs/mnemofs.h, fs/mnemofs/mnemofs_master.c, fs/mnemofs/mnemofs_rw.c
Adds master node and r/w methods to mnemofs
mnemofs can use its master node and wider r/w methods.
checkpatch and NAND virtual flash device.
=> fs/mnemofs: Add master node and r/w methods

include/nuttx/sched.h
Original documentation link for riscv is broken,
so update to the correct link for all architectures.
Put the link around `reg_off` to avoid the long line warning from nxstyle.
No
CI
=> sched.h: Update doc link for tcbinfo_s

Documentation/guides/index.rst, Documentation/guides/thread_local_storage.rst
Explain the basic concept of thread local storage and the usage, limits of CONFIG_SCHED_THREAD_LOCAL.
New document
CI
=> doc: Add a simple guide for thread local storage

arch/arm/src/rp2040/Kconfig
Under arch/arm/src/rp2040/Kconfig, pwm-multichan is defined the same as the global one. Rename the RP2040-specific PWM_MULTICHAN definition to avoid confusion with the global PWM_MULTICHAN.
Only the RP2040 prefix is added
=> /rp2040 Rename the RP2040-specific PWM_MULTICHAN definition

arch/tricore/src/common/tricore_csa.c, arch/tricore/src/common/tricore_svcall.c, include/nuttx/compiler.h
1. arch/tricore: synchronize instruction/data following MTCR/MFCR
Some barrier are necessary to avoid compiler optimizations
2. compiler/tasking: fix build break after inline spinlock change
Regression by:
```
| commit a4fece3450be99fbca5815558dec9374d4ee04e3
| Date:   Wed Jul 3 15:10:49 2024 +0800
|
|     spin_lock: inline spin_lock
```
N/A
tc397
=> arch/tricore: synchronize instruction/data following MTCR/MFCR

cmake/menuconfig.cmake
cmake/boards: fix build break on custom board
Special string filters can be ignored normally
```
Loaded configuration '.config'
Minimal configuration saved to 'defconfig.tmp'
gmake[3]: *** [CMakeFiles/savedefconfig.dir/build.make:73: CMakeFiles/savedefconfig] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:17869: CMakeFiles/savedefconfig.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:17876: CMakeFiles/savedefconfig.dir/rule] Error 2
gmake: *** [Makefile:208: savedefconfig] Error 2
```
N/A
ci-check
=> cmake/boards: fix build break on custom board

Documentation/quickstart/compiling_cmake.rst
This adds more out-of-tree usage examples of CMake for FLAT, PROTECTED
and KERNEL configs.
help more developers enjoy CMake build system
- local check with .rst viewer
- CI checks
=> cmake/docs: add out-of-tree examples

arch/risc-v/src/common/riscv_exception_common.S, arch/risc-v/src/common/riscv_fork.c
This amends pull #12435 and attempts to fix issue #12635 of PROTECTED build vfork failure since commit e6973c764cd531.
Investigation revealed two separate issues:
- The optimized `dispatch_syscall` now requires TP to be prepared, which normally isn't a problem. But for the very first run of the forked child, it was zero. So we need prepare it for the forked child specially before its first run.
- When returning from exception, the SP restored from stack normally works, As forked child stack is copied from parent, thus restored SP from child stack actually points to the parent stack area! So if child executes ealier that parent reaches the waitpid, parent will crash later due to corrupted stack. Unfortunately this is true with PROTECTED build now.
riscv devices
- Local checks with …
=> arch/riscv: fix trap sp restore logic

arch/risc-v/src/bl808/bl808_mm_init.c, arch/risc-v/src/sg2000/sg2000_mm_init.c
This PR configures the BL808 and SG2000 MMU (inside T-Head C906) to cache the the Kernel Text, Data and Heap.  We set the MMU Flags (Shareable, Bufferable and Cacheable) as [explained in this article](https://lupyuen.github.io/articles/plic3#appendix-mmu-caching-for-t-head-c906).
This PR fixes the Slow Memory Access for NuttX Kernel on BL808 and SG2000: https://github.com/apache/nuttx/issues/12696. In the next PR, we will fix the Slow Memory Access for NuttX Apps, by caching the User Text and Data.
`arch/risc-v/src/bl808/bl808_mm_init.c`: Added MMU Flags (Shareable, Bufferable and Cacheable) for BL808 Kernel Text, Data and Heap
`arch/risc-v/src/sg2000/sg2000_mm_init.c`: Added MMU Flags (Shareable, Bufferable and Cacheable) for SG2000 Kernel Text, Data and Heap
This PR only affects Kernel …
=> risc-v/bl808, sg2000: Configure MMU to cache Kernel Text, Data and Heap (T-Head C906)

.github/workflows/build.yml, tools/testbuild.sh
**tools/testbuild.sh**
added option -N Use CMake with Ninja as the backend.
updated help.
added date to print startup board
````
Cmake in present: nucleo-l152re/nsh,CONFIG_ARM_TOOLCHAIN_GNU_EABI
Configuration/Tool: nucleo-l152re/nsh,CONFIG_ARM_TOOLCHAIN_GNU_EABI
2024-07-16 14:39:57
````
added HOST=Msys
**github/workflows/build.yml**
added option -N job docker
ci
=> tools/testbuild.sh:  add option -N use CMake with Ninja

arch/risc-v/src/common/riscv_allocateheap.c
The common `up_allocate_heap` is a strong symbol, which leads to error when building with CONFIG_DEBUG_LINK_WHOLE_ARCHIVE. Make `up_allocate_heap` weak function to mitigate this problem.
This should mitigate #12603.
`rv-virt/flats64`
=> arch/risc-v: make common up_allocate_heap weak symbol

CMakeLists.txt, arch/tricore/CMakeLists.txt, arch/tricore/src/CMakeLists.txt, arch/tricore/src/cmake/Toolchain.cmake, arch/tricore/src/cmake/platform.cmake, arch/tricore/src/cmake/tc3xx.cmake, arch/tricore/src/common/CMakeLists.txt, arch/tricore/src/tc3xx/CMakeLists.txt, boards/tricore/tc3xx/tc397/CMakeLists.txt, boards/tricore/tc3xx/tc397/src/CMakeLists.txt, libs/libc/machine/tricore/CMakeLists.txt
tricore/cmake: add support of cmake build for tricore
Toolchain Upstream:
https://github.com/EEESlab/tricore-gcc-toolchain-11.3.0
CMake command:
```
$ cmake -B build -DBOARD_CONFIG=tc397/nsh -GNinja
```
N/A
tc397/nsh
=> tricore/cmake: add support of cmake build for tricore

arch/xtensa/src/esp32s3/esp32s3_qspi.c
arch/xtensa/esp32s3: Deinitialize ESP32-S3 QSPI GDMA engine.
Correctly releasing channels after using QSPI is crucial to 
prevent issues caused by multiple requests that may lead 
to DMA channel resource conflicts.
Only ESP32s3
esp32s3-devkit
=> arch/xtensa/esp32s3: Deinitialize ESP32-S3 QSPI GDMA engine.

arch/xtensa/src/esp32s3/esp32s3_textheap.c
esp32s3_textheap.c: fix a build error w/o CONFIG_ESP32S3_SPIRAM
build tested
=> esp32s3_textheap.c: fix a build error w/o CONFIG_ESP32S3_SPIRAM

arch/risc-v/src/common/riscv_ipi.h
According to the riscv-aclint doc, writing 0 to SSWI address has no effect. Remove this unnecessary write for S mode.
Link: https://github.com/riscv/riscv-aclint/blob/main/riscv-aclint.adoc
`rv-virt:flats64`
=> arch/risc-v: does not clear IPI address in S mode

drivers/mtd/mtd_config_fs.c
in nvs_startup, when update for powerloss data write, data_wra should move NVS_ALIGN_SIZE
=> NVS: fix align size

include/nuttx/spinlock.h
error msg
/home/hujun5/downloads1/vela_sim/nuttx/include/nuttx/spinlock.h: In function 'bool spin_trylock_wo_note(volatile spinlock_t*)': /home/hujun5/downloads1/vela_sim/nuttx/include/nuttx/spinlock.h:401:22: error: 'atomic_ushort' was not declared in this scope; did you mean 'std::__1::atomic_ushort'?
401 |     atomic_load((FAR atomic_ushort *)&lock->tickets.next);
|                      ^~~~~~~~~~~~~
|                      std::__1::atomic_ushort
/home/hujun5/downloads1/vela_sim/nuttx/include/libcxx/__atomic/aliases.h:33:7: note: 'std::__1::atomic_ushort' declared here
33 | using atomic_ushort = atomic<unsigned short>;
|       ^~~~~~~~~~~~~
/home/hujun5/downloads1/vela_sim/nuttx/include/nuttx/spinlock.h:401:37: error: expected primary-expression before ')' token
401 | …
=> fix compile error

sched/init/nx_bringup.c, sched/sched/sched_releasetcb.c, sched/task/exit.c
This patch attempts to fix regressions reported for pull# 12320.
RELEASE
NONE
=> {BP-12553} sched/tcb: fix 12320 regression

Documentation/guides/customapps.rst
NuttX generates the app main name from Kconfig symbol
xxxx_PROGNAME. The documentation was defining manually
the entry point as custom_hello(int char, char *argv[])
and pointing CONFIG_INIT_ENTRYPOINT="custom_hello".
The right thing to do is creating the application entry
point as "int main(int char, char *argv[])" and the build
system will add "_main" to the PROGNAME.
Users will be able to start their application correctly
Raspico
=> Doc: Fix CustomApps/CustomHello example

Documentation/platforms/arm/stm32h7/boards/linum-stm32h753bi/index.rst
Fix a small issue found on Linum-STM32H753BI Documentation.
Doc fix
N/A
=> Fix pin LTDC_B0, should be PJ12 instead of PF0

sched/Kconfig
In the "--help--" text of `sched/Kconfig` `CONFIG_INIT_ENTRYPOINT`, document that "main" should include "argc" and "argv" to avoid the issue discussed in the email thread "[basically, I get an error when I do make](https://lists.apache.org/thread/9j2s3647ysdhy204g4ombn4o09bn11c1)" started 18 Jul 2024.
Improve documentation and hopefully prevent others from running into the same compilation problem.
None.
=> sched: Improve Kconfig help of INIT_ENTRYPOINT

drivers/usbdev/usbdev_fs.c
The unsigned type is always greater than or equal to 0
=> usbdev: delete unsigned comparison with 0

boards/arm/rp2040/common/src/rp2040_common_bringup.c, drivers/sensors/CMakeLists.txt, drivers/sensors/Kconfig, drivers/sensors/Make.defs, drivers/sensors/sht4x.c, include/nuttx/sensors/ioctl.h, include/nuttx/sensors/sht4x.h
This PR introduces a new driver for the SHT4x family of temperature and humidity sensors that operate over the I2C protocol. It provides a POSIX interface for all of the sensor's features: reading data, serial number, performing a reset and operating the sensor's heater within the safe usage limits.
This PR also closes #12665.
An easier interface for future developers to interact with this family of sensors, rather than having to write their own driver.
In order to test the driver, I performed a series of basic checks on all of the implemented functionality.
- First, I performed a simple `read` of the device driver path from the command line using `cat` to ensure that the character driver interface works as expected.
- I performed a command line write with `echo` to see that no write …
=> Add support for the Sensirion SHT4x temperature and humidity sensor

.github/workflows/build.yml
Starting November 30, 2024, GitHub Actions customers will no longer be able to use v3 of actions/upload-artifact or actions/download-artifact.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
**Breaking change using V4**
Due to how Artifacts are created in this new version, it is no longer possible to upload to the same named Artifact multiple times.
https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes
Currently in our workflow each type of runner processing work (Linux, Mac and Windows) in the artifacts generates a single file with all jobs.
**Solution present in this PR**
modified
https://github.com/apache/nuttx/blob/17aec1328a6c993d4cb8009fb2ac1893103ba936/.github/workflows/build.yml#L171C18-L171C27
**name: linux-builds …
=> build.yml: Updated the workflow to use version v4 of the actions/upload-artifact and actions/download-artifact.

.github/workflows/doc.yml
Starting November 30, 2024, GitHub Actions customers will no longer be able to use v3 of actions/upload-artifact or actions/download-artifact.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
This PR removes the following warning annotations:
The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/upload-artifact@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
Improvements
Uploads are significantly faster, upwards of 90% improvement in worst case scenarios.
https://github.com/actions/upload-artifact?tab=readme-ov-file#improvements
CI
=> doc.yml: Updated the workflow to use version v4 of the actions/upload-artifact

Documentation/contributing/making-changes.rst
The Documentation was missing the commit log message examples
New developer will get better idea how to format their PR, as commented there:
https://github.com/apache/nuttx/pull/12747
N/A
=> doc: Include commit log examples

arch/risc-v/src/common/riscv_exception_common.S, arch/risc-v/src/common/riscv_fork.c
Summary
This amends pull https://github.com/apache/nuttx/pull/12435 and attempts to fix issue https://github.com/apache/nuttx/issues/12635 of PROTECTED build vfork failure since commit https://github.com/apache/nuttx/commit/e6973c764cd5314aa4d6ccfadaebdd715f2dd709.
Investigation revealed two separate issues:
The optimized dispatch_syscall now requires TP to be prepared, which normally isn't a problem. But for the very first run of the forked child, it was zero. So we need prepare it for the forked child specially before its first run.
When returning from exception, the SP restored from stack normally works, As forked child stack is copied from parent, thus restored SP from child stack actually points to the parent stack area! So if child executes ealier that parent reaches the waitpid, …
=> {bp-12717} arch/riscv: fix trap sp restore logic

arch/risc-v/src/nuttsbi/sbi_start.c
This fixes PMP setting for open everything before going S-mode, which has been broken since pull/12398.
RELEASE
CI
=> {bp-12546} arch/riscv: fix PMP in sbi_start()

Documentation/contributing/making-changes.rst
The releasenotes tools can use proper commit titles and automate commit sorting
DOC
NONE
=> doc: improve commit log examples

arch/risc-v/src/common/riscv_pmp.c
This allows using 0 base and size to depict the whole region.
RELEASE
CI
=> {bp-12579} riscv/pmp: add all region in NAPOT

boards/arm64/imx9/imx93-evk/src/Makefile
adds cleanup of `imx9-sdimage.img` upon distclean to unblock CI system.
CI checks
- local check with imx93-evk:bootloader
- CI checks
=> boards/imx93-evk: add sdimage cleanup

arch/arm/src/common/arm_backtrace_fp.c, arch/arm/src/common/arm_backtrace_sp.c, arch/arm/src/common/arm_backtrace_unwind.c, arch/arm/src/tlsr82/tc32/tc32_backtrace.c, arch/arm64/src/common/arm64_backtrace.c, arch/risc-v/src/common/riscv_backtrace.c, arch/xtensa/src/common/xtensa_backtrace.c, include/nuttx/arch.h, sched/sched/sched_backtrace.c
when trying to show information at task quit and thread still running, try dump callstack found maybe some problem.
Need this patch to solve dump exiting thread callstack. need another patch to fix dump running thread stack.
Can dump the exiting thread after patch.
CI & qemu-armv7a & SMP armv7a board.
=> up_backtrace: fix maybe backtrace the exiting thread

libs/libc/dlfcn/lib_dlclose.c
dlfcn: Fix indent issue in lib_dlclose.c
Minor
CI
=> dlfcn: Fix indent issue in lib_dlclose.c

arch/arm/src/nrf53/nrf53_start.c, arch/arm/src/nrf91/nrf91_start.c, boards/arm/nrf91/nrf9160-dk/configs/miniboot_s/defconfig, boards/arm/nrf91/nrf9160-dk/configs/modem_ns/defconfig
-  boards/arm/nrf91/nrf9160-dk: disable FPU for modem example  
it looks like FPU doesn't work in non-secure environment now
- arch/arm/{nrf53|nrf91}: enable fpu if CONFIG_ARCH_FPU=y
enable fpu if CONFIG_ARCH_FPU=y, the previous condition depended on CONFIG_ARCH_HAVE_FPU=y
=> nrf9160-dk: disable FPU for modem example 

include/dlfcn.h, libs/libc/dlfcn/CMakeLists.txt, libs/libc/dlfcn/Make.defs, libs/libc/dlfcn/lib_dladdr.c, tools/nxstyle.c
Implement a stub for dladdr() to avoid build errors with some applications that use dladdr().
The API definition is from:
1. https://man7.org/linux/man-pages/man3/dladdr.3.html
2. https://pubs.opengroup.org/onlinepubs/9799919799.2024edition/functions/dladdr.html
New API
Local machine
=> dlfcn: Add stub for dladdr

CMakeLists.txt
This allows PROTECTED mode userspace linker script to be preprocessed so
that to use defs in <nuttx/config.h> and avoid hardcoded values.
PROTECTED mode cmake uses
- local testing
- CI checks
=> build/cmake: add user_ldscript preprocessing

arch/arm/src/common/arm_backtrace_unwind.c
Expand the backtrace search scope,
Similarly, the problem that the idle thread's lr is a random value can be fixed
fix it https://github.com/apache/nuttx/issues/12687
arm unwind
qemu use an547
=> arm_backtrace_unwind:Make the backtrace search the entire stack as much as possible

.github/workflows/build.yml
**job msys2** fix
https://github.com/apache/nuttx/actions/runs/10140159746/job/28034852319?pr=12787#step:4:1
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
python-xyz', where xyz is the package you are trying to
install.
If you wish to install a non-MSYS2-packaged Python package,
create a virtual environment using 'python -m venv path/to/venv'.
Then use path/to/venv/bin/python and path/to/venv/bin/pip.
note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 66[8](https://github.com/apache/nuttx/actions/runs/10140159746/jo …
=> build.yml: fix error: externally-managed-environment

drivers/mtd/Kconfig
There was no comment next to this menu option and the option wouldn't be displayed in menu.
Enable user to select W25_SLOWREAD option in menuconfig for W25
start menuconfig, see if you can select,  select it, build code with that conditioned code in.
=> mtd/Kconfig: fix W25_SLOWREAD menu item.

arch/risc-v/src/qemu-rv/qemu_rv_head.S
This revises qemu_rv_head.S to avoid loading the mhartid again as
it has already in a0 register upon entry.
qemu-rv devices
- local checks on rv-virt with configs: `nsh`, `nsh64`, `flats`, `flats64`, `knsh32`, `knsh64`, `smp`, `smp64`, `ksmp64` etc.
- CI checks
=> riscv/qemu-rv: skip reloading mhartid

drivers/mtd/Kconfig, drivers/mtd/w25.c
- Allows optionally to separate traces from potentially irrelevant fs syslog traces it would go with currently.
If user wants, can enable W25_DEBUg to not mix W25 specific dbg traces with fs traces, which can be very verbose and
irrelevant.
Optional
Menuconfig select, rebuild, run, see log
=> w25c: add W25_DEBUG sub-menu config option and update debug traces.

arch/arm/src/xmc4/CMakeLists.txt, arch/arm/src/xmc4/Make.defs, arch/arm/src/xmc4/xmc4_i2c.c, arch/arm/src/xmc4/xmc4_i2c.h
Added the lower-half driver for the i2c_master.h NuttX driver in arch/xmc4.
The XMC4 allows 6 I2C bus to be initialized with baudrate up to 400k. Each Bus is associated to a channel of an USIC module.
**Modified Files in arch/arm/xmc4:**
`include/xmc4_i2c.h`: Removed hardware/xmc4_i2c.h include.
`src/Make.defs`: Added source files for xmc4_i2c
`src/CMakeList.txt`: Added source files for xmc4_i2c
**New Files in arch/arm/xmc4:**
`src/xmc4_i2c.c`: New lower-half i2c master driver.
Enable USIC in System Type → XMC4xxx Peripheral Support 
Set I2C protocol in System Type → XMC4xxx USIC Configuration → USICX Channel Y Configuration
/!\ I2C bus reset isn't supported yet.
No impact on other functionalities.
Tested on a custom xmc4800 board.
=> arch/xmc4 : i2c master lower-half driver

tools/testbuild.sh
Added the ability to store compilation artifacts for cmake after a job.
CI
=> tools/testbuild.sh: added store compilation artifacts for cmake

arch/x86_64/include/intel64/irq.h, arch/x86_64/src/intel64/intel64_rtc.c, arch/x86_64/src/intel64/intel64_tsc_tickless.c, arch/x86_64/src/intel64/intel64_tsc_timerisr.c
- arch/intel64/irq.h: rename rdtsc macros
rename _rdtsc macro to rdtsc to avoid conflict with external code rename rdtsc macro to rdtscp to be the same as asm instruction used
CI
=> arch/intel64/irq.h: rename rdtsc macros

Documentation/platforms/risc-v/qemu-rv/boards/rv-virt/index.rst, arch/risc-v/Kconfig, arch/risc-v/include/csr.h, arch/risc-v/include/mode.h, arch/risc-v/src/common/CMakeLists.txt, arch/risc-v/src/common/Make.defs, arch/risc-v/src/common/riscv_aia.h, arch/risc-v/src/common/riscv_aplic.c, arch/risc-v/src/common/riscv_imsic.c, arch/risc-v/src/common/riscv_internal.h, arch/risc-v/src/qemu-rv/chip.h, arch/risc-v/src/qemu-rv/hardware/qemu_rv_aplic.h, arch/risc-v/src/qemu-rv/hardware/qemu_rv_clint.h, arch/risc-v/src/qemu-rv/qemu_rv_irq.c, arch/risc-v/src/qemu-rv/qemu_rv_irq_dispatch.c
Advanced Interrupt Architecture (AIA) introduces flexiable interrupt controll for RISC-V. It includes three parts: 
1. AIA CSRs
2. Incoming Message Signaled Interrupt Controller (IMSIC) 
3. Advanced Platform-Level Interrupt Controller (APLIC).
`rv-virt`
`rv-virt:nsh`
[nuttx32-m-aia.log](https://github.com/user-attachments/files/16426457/nuttx32-m-aia.log)
[nuttx32-m-aplic.log](https://github.com/user-attachments/files/16426458/nuttx32-m-aplic.log)
[nuttx32-m-imsic.log](https://github.com/user-attachments/files/16426459/nuttx32-m-imsic.log)
`rv-virt:smp64`
[nuttx64-m-aia.log](https://github.com/user-attachments/files/16426461/nuttx64-m-aia.log)
[nuttx64-m-aplic.log](https://github.com/user-attachments/files/16426462/nuttx64-m-aplic.log) …
=> arch/risc-v: introduce AIA support

libs/libm/libm/lib_copysign.c, libs/libm/libm/lib_copysignl.c
Use `signbit(y)` instead of `y < 0` to fix the result of copysign/copysignl: https://alive2.llvm.org/ce/z/kjNLyh
```
copysign(+0.0, -0.0) returns +0.0. It should be -0.0.
copysign(+0.0, NaN with signbit) returns +0.0. It should be -0.0.
```
I found this bug while working on my LLVM middle-end optimization patch https://github.com/llvm/llvm-project/pull/101324. Don't worry about the potential performance regression. I will file another PR in LLVM to handle this pattern :)
Fix the implementation of copysign/copysignl.
x86 with -O3
=> libm/copysign: respect signed zero/NaN handling in copysign

fs/spiffs/src/spiffs_vfs.c
According to the POSIX standard, `fstat` should return 0 (`OK`) on success. This PR changed the underlying `spiffs` implementation to follow the POSIX standard.
Make it consistent with POSIX compliant!
=> fs/spiffs: Return OK on `spiffs_fstat` success

arch/risc-v/src/common/riscv_debug.c, include/nuttx/arch.h
Steppoint can be implemented by icount(instruction count) from RISC-V debug extension, but it may not implemented in all RISC-V cores.
Unfortunately, the currently supported RISC-V cores do not implement it.
New feature
Local machine
=> riscv/debug: Add support for steppoint

arch/x86_64/src/intel64/CMakeLists.txt, arch/x86_64/src/intel64/Kconfig, arch/x86_64/src/intel64/Make.defs, arch/x86_64/src/intel64/intel64_hpet_alarm.c, arch/x86_64/src/intel64/intel64_oneshot.c, arch/x86_64/src/intel64/intel64_oneshot.h, arch/x86_64/src/intel64/intel64_oneshot_lower.c, boards/x86_64/intel64/qemu-intel64/src/qemu_bringup.c
arch/intel64: add support for HPET as system clock
qemu and intel HW
=> arch/intel64: add support for HPET as system clock

sched/task/task_fork.c
Two things need to be done when vfork'ing:
- Must attach to parent's address environment (the addrenv is shared)
- Must allocate a kernel stack (where would the register context go otherwise)
Note that this code assumes the address environment is shared, since we don't support fork() which would _clone_ the address environment instead.
Fix vfork() for BUILD_KERNEL
rv-virt:knsh64 + ostest pass
=> task_fork.c: Fix vfork for BUILD_KERNEL

arch/risc-v/src/k230/k230_start.c
Fixes regression from https://github.com/apache/nuttx/pull/12220
Error: chip/k230_start.c:80:13: error: 'k230_copy_init_data' defined but not used [-Werror=unused-function]
80 | static void k230_copy_init_data(void)
|             ^~~~~~~~~~~~~~~~~~~
Fix build error
Build passes
Gates merge of: https://github.com/apache/nuttx/pull/12812
=> k230_start.c: Fix condition for k230_copy_init_data()

arch/risc-v/src/common/espressif/esp_spi.c
These symbols only used in esp_spi.c and too simple to conflict with others, so mark them as static:
- cfg
- ctx
- dev_cfg
- timing_param
Minor
CI
=> riscv/espressif: Mark private data as static in esp_spi.c

arch/arm/src/arm/arm_vectors.S
Fix some bugs found while trying run modern NuttX on an old board.
NuttX builds and runs on my board but most of the board support is not in the repo.
=> arm: Make ARMv5 boards work again

arch/arm/src/xmc4/xmc4_i2c.c
The critical section was declared at the wrong place (no compilation error during checks ?).
The critical section wasn't properly left in certain cases.
Tested on  a XMC4800 custom board
=> arch/xmc4 : Fixed critical section in i2c_transfer

tools/mkfsdata.py
Script `tools/mkfsdata.pl` was written in Perl. This language is no longer popular. It may be a great idea to rewrite it in Python.
This is my variant.
The script fully behaves as the original one. And I have added arguments to configure it.
Not shure:
- how to correctly license
- do I need to delete the original mkfsdata.pl
- did I put 'PROGMEM' correctly in an 'unsigned static constant character' (line 64)
- do I need to update the usage script on the example/web-server
=> Rewrite mkfsdata.pl script on python 

.github/ISSUE_TEMPLATE/001_bug_report.yml, .github/ISSUE_TEMPLATE/002_feature_request.yml, .github/ISSUE_TEMPLATE/003_help.yml, .github/ISSUE_TEMPLATE/config.yml, .github/workflows/issue_labeler.yml
**-Template**
Bug report
Report a bug to improve NuttX stability
Feature request
Request an enhancement for NuttX
General Help
Get general support regarding NuttX
Of course, others can be added. !!! :)
**-Action**
An action for automatically labelling issues
**Keywords**
Keywords are present in the dropdowns (the user can select more than one option) of the form Bug report and are:
- Linux, Mac, Windows, Other
- all, arm, arm64, avr, ceva, hc, mips, misoc, openrisc, renesas, risc-v, simulator, sparc, tricore, x86, x86_64, xtensa, z16, z80
- Applications, Api, Board support, Build System, Configuring, Debugging, Drivers, File System, Installing, Kconfig, Kernel, Memory Management, Native port, Networking, OS Components, Posix, Sensors, Specific Peripheral
**To work, the labels must have …
=> Issues: Added Issue templates

drivers/serial/Kconfig-16550, drivers/serial/uart_16550.c
To avoid breaking other configs, the default value 2 is equal to the original hard coded value.
I use this feature to set trigger level 0 otherwise NuttShell cannot see one keystroke.
=> drivers/serial: Make the 16550 rx trigger level configurable

drivers/lcd/Kconfig, drivers/lcd/ssd1680.c, drivers/lcd/ssd1680.h
Add configuration and driver support for the SSD1681 1.54 inch e-paper display, including the necessary waveforms and settings for proper operation. This extends the existing SSD1680 e-paper driver to accommodate the new display module.
The changes involve updates to the Kconfig file for additional configuration options, modifications to the driver implementation in ssd1680.c to include SSD1681 specific logic, and updates to the header file ssd1680.h to reflect the added support.
New feature
Custom board
=> driver/ssd1680: Add support for 1.54 inch e-paper display

tools/D.defs, tools/Rust.defs
Rust/D support for RISC-V is broken after https://github.com/apache/nuttx/pull/11549,
since the target triple is quite different bewteen Rust/D toolchain and GCC,
only few RISC-V targets are supported by Rust toolchain now, so it's better to
construct target triple in Rust.defs/D.defs for RISC-V.
Minor
Local machine
=> tools/[Rust|D]: Fix build break for RISC-V

arch/x86_64/src/intel64/intel64_cpu.c, arch/x86_64/src/intel64/intel64_irq.c, include/nuttx/spinlock.h, sched/irq/irq_spinlock.c
1. spinlock: inline no trace implement to remove duplicate logic
minor changes to remove duplicate logic
2. splinlock: fix typo of sched_note_spinlock_unlock()
should be sched_note_spinlock_unlock() not sched_note_spinlock_unlocked()
3. spinlock: inline irqsaved spinlock
Reference pull request: https://github.com/apache/nuttx/pull/12599
4. spinlock: compile spinlock only if CONFIG_SPINLOCK is enabled
Regression by: https://github.com/apache/nuttx/pull/12599
N/A
ci-check
=> spinlock: inline no trace implement to remove duplicate logic

arch/risc-v/src/common/supervisor/riscv_sbi.c
Fixes RV32 `riscv_sbi_get_time()` when NuttSBI is used.
rv32 up_udelay when NuttSBI is used
- local checks with rv-virt:nsbi
- CI checks
=> riscv/nsbi: fix up_udelay for rv32

libs/libc/pwd/CMakeLists.txt
Hello NuttX community :)!
This PR fixes erroneous assignment of lib_pwd_globals.c previously guarded by CONFIG_LIBC_PASSWD_FILE. Original Make.defs file has this in CSRCS scope.
As an example - sim:adb build worked only with Make based build system - now it's also possible to proceed with CMake based build.
Hard to estimate.
Local build of sim:adb and fiddling around adb client with sim:adb simulator.
=> build: Fix libc/pwd CMakeLists.txt

binfmt/libelf/libelf_load.c
Set sh_addr for regions that are not allocated. Some relocations might depend on this.
The fault in my case occurs when setting CONFIG_HAVE_CXX=y. In this case, the .ctor and .dtor sections do not get allocated, but the crt code depends on linker defined symbols _sctors/_ectors etc. These generate PC relative relocations and thus, the .ctor and .dtor output sections need an output VMA even though nothing is there. Otherwise the relocations will point to god knows where (in my case to address 0).
The problem results in full system crash later:
elf_symvalue: Other: 00000000+00000001=00000001
up_relocateadd: PCREL_HI20 at c00002dc [00000417] to sym=0x80409e80 st_value=1
_calc_imm: offset=-3221226203: hi=-786432 lo=-731
up_relocateadd: ERROR: PCREL_HI20 at c00002dc bad:ffffffff40000000 …
=> binfmt/elf_loadfile: Set sh_addr even if SHF_ALLOC == 0

tools/ci/docker/linux/Dockerfile, tools/ci/platforms/msys2.sh, tools/ci/platforms/ubuntu.sh
This PR updates the Docker Image for NuttX CI, so that it builds Rust Apps correctly for QEMU RISC-V 64-bit. We add the Rust Target for `riscv64gc-unknown-none-elf` to the Docker Image.
In the next PR, we will call the Updated Docker Image to [compile the Rust App `leds_rust`](https://github.com/apache/nuttx/pull/12852), at every run of NuttX CI. This will validate whether Rust Apps are built correctly for QEMU RISC-V 64-bit.
`tools/ci/docker/linux/Dockerfile`: Add Rust Target `riscv64gc-unknown-none-elf` for Docker CI
`tools/ci/platforms/ubuntu.sh`: Same as above, but for Ubuntu CI
`tools/ci/platforms/msys2.sh`: Same as above, but for MSYS2 CI
No impact on existing CI, since the Rust Target `riscv64gc-unknown-none-elf` is not used by existing code.
We tested the CI Docker Image by …
=> tools/ci: Add Rust Target for QEMU RISC-V 64-bit

arch/risc-v/src/common/fork.S, arch/risc-v/src/common/riscv_fork.c, arch/risc-v/src/common/riscv_fork.h
This fixes riscv fp/gp issues in fork.
vfork() when FP or GP are used.
- local checks with rv-virt:nsh, rv-virt:flats64 etc.
- CI checks
=> riscv/fork: fix fp/gp handling

include/nuttx/spinlock.h
spinlock: add support of spin_trylock_irqsave()
trylock spinlock in critical section:
```
bool spin_trylock_irqsave(FAR volatile spinlock_t *lock, irqstate_t flags);
bool spin_trylock_irqsave_wo_note(FAR volatile spinlock_t *lock, irqstate_t flags);
```
N/A
ci-check
=>  spinlock: add support of spin_trylock_irqsave()

CMakeLists.txt
This fixes build issues encountered when using Ubuntu stock gcc-riscv64-unknown-elf 10.2 toolchain for PROTECTED target like `rv-virt:pnsh`: 
```
boards/risc-v/qemu-rv/rv-virt/kernel/rv_virt_userspace.c:25:10: fatal error: nuttx/config.h: No such file or directory
```
cmake PROTECTED
- local checks with rv-virt:pnsh, rv-virt:pnsh64, canmv230:pnsh etc.
- CI checks
=> build/cmake: fix system include dir for PROTECTED mode

arch/risc-v/src/qemu-rv/CMakeLists.txt, boards/arm/tiva/lm3s6965-ek/scripts/memory.ld, boards/risc-v/qemu-rv/rv-virt/CMakeLists.txt, boards/risc-v/qemu-rv/rv-virt/kernel/CMakeLists.txt, boards/risc-v/qemu-rv/rv-virt/src/CMakeLists.txt
This adds cmake scripts for NuttSBI and PROTECTED builds.
PROTECTED check should be done with pull/12022.
N/A
- local checks with rv-virt target and `nsbi`, `nsbi64`, `pnsh`, `pnsh64` etc.
- CI checks
=> boards/rv-virt: cmake for pnsh and nsbi

arch/xtensa/src/esp32s3/esp32s3_rtc.c, arch/xtensa/src/esp32s3/esp32s3_rtc.h, arch/xtensa/src/esp32s3/hardware/esp32s3_rtccntl.h
- For some reasons, the bootloader will set CPU source to BBPLL and enable it, but there are calibration issues, so we need turn off the BBPLL and do calibration again to fix the issue.
- Corresponding issue link: https://github.com/espressif/esp-idf/commit/89cc9084ab5d889761cb5eff7560a2661236842a
=> xtensa/esp32s3: Update the rtc code to fix system blocking issue

boards/arm/tiva/lm3s6965-ek/scripts/memory.ld
This completes kflash size adjustion in pull/12868 by fixing the uflash origin, otherwise the linked program may go beyond valid flash range.
lm3s6965-ek/qemu-protected
- CI checks
=> boards/lm3s6965-ek: fix memory.ld for PROTECTED

CMakeLists.txt
FetchContent_Populate is depracated starting from CMake 3.30. Setting this policy to OLD allows clean (no warnings) CMake builds for configurations that rely on CMake fetch content feature.
If we want to keep up with CMake versioning - FetchContent_Populate is deprecated in 3.30 - and it's gonna be disabled in future version.
https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_populate
Local builds (or rather configure steps) using CMake 3.30.2 
Was there any specific reason for calling FetchContent_Populate instead of FetchContent_MakeAvailable?
=> build: set CMake policy to allow FetchContent_Populate

arch/arm/src/stm32wl5/hardware/stm32wl5_rcc.h
The RCC_PLLCFG_PLLP define was missing an argument in it's definition.
Would not compile if STM32WL5_PLLCFG_PLLP_ENABLED was set on stm32wl5 architecture.
Built and ran on a board with a stm32wl5.
=> fix stm32wl5_rcc.h: Add the missing argument to RCC_PLLCFG_PLLP define.

boards/arm/tiva/lm3s6965-ek/scripts/memory.ld
This reverts both 2afdcfb6a6 and 0a0af89de9 to restore the 128K kflash design as the implementation depends on that to work, checked with:
```
$ qemu-system-arm -M lm3s6965evb -nographic -device loader,file=nuttx.bin,addr=0x0 -device loader,file=nuttx_user.bin,addr=0x2000
```
Thanks to patch 12873, 128K uflash is enough now for `qemu-protected`.
lm3s6965-ek device
- local check with lm3s6965-ek:qemu-protected
- CI checks
=> board/lm3s6965-ek: restore 128K kflash

arch/risc-v/Kconfig, arch/risc-v/src/common/riscv_macros.S
arch/riscv: add cluster local hartid
Some RV chips (mpfs, jh7110, qemu-rv etc) have hart clusters and globally numbered mhartids. Clusters with single hart or SMP support can be managed by one NuttX instance. Currently NuttX expects to use cluster-local ids.
This allows us to get local ids by offsetting mhartids with provisioned base hartid for each cluster.
Note that there are chips (e.g. k230) that use cluster-local ids directly, so this is not needed for them.
None
CI checks
=> arch/riscv: add cluster local hartid

arch/arm/include/armv6-m/irq.h, arch/arm/include/armv7-a/irq.h, arch/arm/include/armv7-m/irq.h, arch/arm/include/armv7-r/irq.h, arch/arm/include/armv8-m/irq.h, arch/arm/include/armv8-r/irq.h, arch/arm/include/irq.h, arch/arm/include/tlsr82/irq.h
1. the up_getsp() function is needed by "__builtin_frame_address", and the "__builtin_frame_address" is a gcc builtin function, which is bound to gcc specific platform, so we provide a new implementaiton of up_getsp(), which make the up_getsp() is independent from specific compiler.
=> greenhills support: add up_getsp() implementation to adapting greenhills compiler

arch/arm/include/spinlock.h, arch/arm/include/syscall.h, arch/arm/src/armv6-m/barriers.h, arch/arm/src/armv7-a/barriers.h, arch/arm/src/armv7-m/arm_exception.S, arch/arm/src/armv7-m/arm_saveusercontext.S, arch/arm/src/armv7-m/barriers.h, arch/arm/src/armv7-r/barriers.h, arch/arm/src/armv8-m/barriers.h, arch/arm/src/armv8-r/barriers.h, arch/arm/src/common/gnu/fork.S, arch/arm64/include/spinlock.h, arch/ceva/include/spinlock.h, arch/risc-v/include/spinlock.h, arch/x86_64/include/spinlock.h, libs/libc/machine/arm/gnu/arch_setjmp.S, libs/libc/modlib/modlib_globals.S
1. fix the asm grammer error when build with greenhills compiler
=> greenhills support: fix the asm build error for adapting to greenhills compiler

arch/arm/src/armv8-m/arm_hardfault.c, arch/arm/src/armv8-m/arm_memfault.c, arch/arm/src/armv8-m/arm_securefault.c
armv8-m/arm_securefault.c:72:11: warning: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
72 |   sfalert("\tCFSR: %08x HFSR: %08x DFSR: %08x\n", getreg32(NVIC_CFAULTS),
|           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warnning fix
armv8-m
qemu mps3an547
=> armv8-m:fix log warnning

mm/kasan/kasan.c
kasan bug fix
kasan
Using write checks alone can still trigger read check errors, so this needs to be fixed
=> kasan:fix bug write error is recognized as read error

binfmt/libelf/libelf_coredump.c, include/elf.h, include/nuttx/coredump.h, sched/init/nx_bringup.c, sched/misc/assert.c, sched/misc/coredump.c
Coredump enhancement, optimized prompt statements
1. In some architectures, registers cannot be copied using memcpy. However, reading the register contents by uintptr is supported.
2. Optimized the message prompts after successfully or unsuccessfully using coredump.
coredump
vela & qemu wtih mpsan547 use coredump
=> Coredump enhancement, optimized prompt statements

arch/risc-v/src/qemu-rv/Kconfig, arch/risc-v/src/qemu-rv/hardware/qemu_rv_memorymap.h
This adds cluster specific configs for PLIC, CLINT and ACLINT devices. The guard `QEMU_RV_CLUSTER` helps to avoid refreshing existing defconfig.
None
CI checks
=> riscv/qemu-rv: add cluster PLIC/CLINT configs

arch/sim/src/cmake/Toolchain.cmake
macOS board -> sim  
fix ->  ld: unknown options: --gc-sections
added -> add_link_options(-Wl,-dead_strip)
none
CI
=> arch/sim/src/cmake/Toolchain.cmake: macOS fix unknown options: --gc-sections

libs/libc/misc/CMakeLists.txt, libs/libc/misc/Make.defs
when building incrementally, the ustname time information is wrong.
this patch fix phoney target mismatch issue, always rebuild ustname.
=> [bugfix] keep the incrementally compiled version time updated

arch/sim/src/cmake/Toolchain.cmake, fs/CMakeLists.txt, libs/libc/machine/arm/armv7-a/CMakeLists.txt, libs/libc/machine/arm/armv7-m/CMakeLists.txt, libs/libc/machine/arm/armv7-r/CMakeLists.txt, libs/libc/machine/arm/armv8-m/CMakeLists.txt
1. Fix SIM `-fsanitize=address` not effective at linking stage
2. Fix missing include directory path for fs
3. Fix enable `ARCH_STRING_FUNCTION` CMake build fail, add missing libc/machine/ sources
CI build
=> [bugfix] cmake:fix a few issues during CMake build

cmake/nuttx_add_application.cmake
for sources that have implemented _**`multiple`**_ prog_main in main src, 
there is a situation where we don't need to add source files 
BUT need to register. 
this patch support nuttx `nuttx_add_application` method is enhanced so that it can be registered without entering SRCS.
```c
/**
demo_main.c
has two builtin function
**/
int main(int argc, char *argv[])
{
do_start();
}
int demo_stop_main(int argc, char *argv[])
{
do_stop();
}
``` 
```cmake
nuttx_add_application(NAME demo_start SRCS demo_main.c)
nuttx_add_application(NAME demo_stop)
``` 
linkage: https://github.com/apache/nuttx-apps/pull/2478
CI build
=> [cmake] add_application supports only registration but not compilation

CMakeLists.txt, libs/libc/assert/CMakeLists.txt
it was wrong in https://github.com/apache/nuttx/pull/12423/files#r1618852245 
`EXTRA_FLAGS` is useful in LTO for pass option to lto linker
error massage:
```shell
[1131/1132] Linking C executable nuttx
FAILED: nuttx 
: && arm-none-eabi-gcc  --specs=nosys.specs   -Wl,--entry=__start -nostdlib -Wl,--gc-sections -Wl,--cref -Wl,-Map=nuttx.map CMakeFiles/nuttx.dir/empty.c.obj -o nuttx  -Wl,--script=ld.script.multi.tmp  -Wl,--start-group  arch/libarch.a  binfmt/libbinfmt.a  drivers/libdrivers.a  fs/libfs.a  libs/libc/libc.a  mm/libmm.a  sched/libsched.a  boards/libboard.a  apps/libapps.a  apps/external/android/libandroid.a  apps/builtin/libapps_builtin.a  apps/system/nsh/libapps_nsh.a  apps/system/nsh/libapps_sh.a  apps/examples/hello/libapps_hello.a …
```
=> [bugfix] fix CMake build block when enable  LTO

include/nuttx/serial/uart_16550.h
serial/uart_16550: include stdint.h in uart_16550.h
stdint.h is needed in uart_16550.h for some types, e.g. uint32_t,
uintptr_t. Otherwise there will be building issue unless that stdint.h
is added before uart_16550.h by all files which needs uart_16550.h.
Signed-off-by: Jinliang Li <lijinliang1@lixiang.com>
N/A
ci-check
=> serial/uart_16550: include stdint.h in uart_16550.h

arch/arm/src/armv8-r/cp15.h
Add some cp15 definitions for mpu configuration
arm/armv8-r: add cp15 ops for mpu
Add some cp15 definitions for mpu configuration
Signed-off-by: Jinliang Li <lijinliang1@lixiang.com>
N/A
ci-check
=> arm/armv8-r: add cp15 ops for mpu

arch/arm/src/armv8-r/arm_head.S
arm/armv8-r: invalidate d-cache on boot
Pass CP15_CACHE_INVALIDATE argument with r1 register to cp15_dcache_op_level.
cache level is 0(L1 D-Cache) with r0 register.
prototype:
void cp15_dcache_op_level(uint32_t level, int op)
Signed-off-by: Jinliang Li <lijinliang1@lixiang.com>
N/A
Cortex-R52
=> arm/armv8-r: invalidate d-cache on boot

Kconfig, cmake/nuttx_generate_outputs.cmake, tools/Unix.mk
make/disassembly: generate disassembly file
Create the nuttx.asm in the disassembly format using the objdump program.
NOTE:
'>', objdump doesn't take arguments for output file,
but result is printed to standard out, and is redirected.
Signed-off-by: fanjiangang <fanjiangang@lixiang.com>
N/A
ci-check
=> make/disassembly: generate disassembly file

arch/xtensa/src/common/espressif/platform_include/sys/lock.h
Enabling CONFIG_PRIORITY_INHERITANCE config causes a build error
Based on Nuttx OS reserve memory for mutex struct.
Pass build based on
- CONFIG_PRIORITY_INHERITANCE y
- CONFIG_SEM_PREALLOCHOLDERS 0/8
=> xtensa/esp32s3: reserve memory for a mutex struct depending on the OS

mm/map/vm_region.c
Fixes build error:
map/vm_region.c: In function 'vm_map_region':
map/vm_region.c:128:16: error: pointer of type 'void *' used in arithmetic [-Werror=pointer-arith]
128 |   return vaddr + (MM_PGMASK & paddr);
|                ^
Fix build error
Build / CI pass
=> mm/map/vm_region.c: Fix usage of void* arithmetics

drivers/virtio/virtio-net.c, include/nuttx/virtio/virtio.h
According to Virtual I/O Spec:
When using legacy interfaces, transitional drivers which have not negotiated `VIRTIO_F_ANY_LAYOUT` MUST use a single descriptor for the `struct virtio_net_hdr` on both transmit and receive, with the network data in the following descriptors.
https://docs.oasis-open.org/virtio/virtio/v1.2/cs01/virtio-v1.2-cs01.html#x1-2280006 (Section 5.1.6.6)
Virtio-Net on environments without `VIRTIO_F_ANY_LAYOUT`.
Manually.
=> drivers/virtio-net: Support VIRTIO_F_ANY_LAYOUT

drivers/clk/clk.h
When try build with arm64 or x86_64, will report a warning, do pointer wrapper
None.
CI-test & arm64 environment
=> clk: fix reg operation not compatible with 64bit

drivers/power/pm/pm_register.c, drivers/power/pm/pm_unregister.c
As we changed the defintion of pm_register/unregister, possible the domain is not a correct value. will cause data abort. use debug assert to expose problems before real aceess wrong memory.
None
CI test
=> pm: add debug_assert for cb register/unregister api

drivers/mtd/mtd_nandram.c, fs/mnemofs/mnemofs.c, fs/mnemofs/mnemofs.h, fs/mnemofs/mnemofs_blkalloc.c, fs/mnemofs/mnemofs_ctz.c, fs/mnemofs/mnemofs_fsobj.c, fs/mnemofs/mnemofs_journal.c, fs/mnemofs/mnemofs_lru.c, fs/mnemofs/mnemofs_master.c, fs/mnemofs/mnemofs_rw.c, fs/mnemofs/mnemofs_util.c
- Fixes the journal log read and write size and overlap issues
- Fixes rw return value issue.
mnemofs can now store logs properly, and flush properly.
nsh:sim and checkpatch.
=> fs/mnemofs: Fix journal log rw issue, rw size issue

drivers/video/CMakeLists.txt, drivers/video/Kconfig, drivers/video/Make.defs, drivers/video/goldfish_gpu_fb.c, include/nuttx/video/goldfish_gpu_fb.h
In order to better use the Android goldfish emulator, a GPU FB driver has been added. This allows the goldfish emulator  side to achieve more flexible display effects, such as UI skins.
framebuffer driver
ci-test
=> drivers/video: add goldfish gpu fb

fs/rpmsgfs/rpmsgfs_client.c
When handling errors through ioctl, the error returned by the server is always 0 on the client, because cookie.result is not assigned, the error returned should be in msg->result
If the server handles an error, the error result returned by the cookie can be correctly handled by the client
=> rpmsgfs_client:Fix error return exception

fs/hostfs/hostfs.c, fs/hostfs/hostfs.h
1. hostfs supports getting the path information of an opened fd through ioctl
2. When the command is not supported, -ENOTTY should be returned
hostfs support get filepath
=> Hostfs support get filepath by ioctl

libs/libc/pthread/pthread_condattr_init.c
pass ltp case: open_posix_testsuite/conformance/interfaces/pthread_condattr_getpshared/2-1.c
Reference:
https://pubs.opengroup.org/onlinepubs/009696899/functions/pthread_mutexattr_getpshared.html
none
ltp case test
=> libs: fix the default value of process-shared attribute

include/nuttx/mm/mempool.h, mm/mempool/mempool.c, mm/mempool/mempool_multiple.c
the mempool_alloc and mempool_free function are duplicate with the mempool method that provided in optee_os, in order to port optee_os, so we rename the mempool related functions in nuttx
=> mm/mempool: rename the mempool_alloc and mempool_free function

arch/risc-v/src/qemu-rv/Kconfig, arch/risc-v/src/qemu-rv/Make.defs, arch/risc-v/src/qemu-rv/qemu_rv_irq.c, arch/risc-v/src/qemu-rv/qemu_rv_rptun.c, arch/risc-v/src/qemu-rv/qemu_rv_rptun.h, boards/risc-v/qemu-rv/rv-virt/src/qemu_rv_appinit.c
This adds RPTUN related kconfig for `qemu-rv` chip.
None
- local check with `rv-virt` device.
- CI checks
=> riscv/qemu-rv: add RPTUN support

fs/rpmsgfs/rpmsgfs_client.c, fs/rpmsgfs/rpmsgfs_server.c, fs/vfs/fs_fcntl.c, fs/vfs/fs_ioctl.c, include/nuttx/fs/ioctl.h
There is now support for locking files on the server side via rpmsgfs. The main changes are:
1. move filelock call from fcntl to ioctl, use ioctl FIOC_XXXLK to lock server-side files.
2. because there are blocking operations in the file lock, the client side can only do a polling request to find out if the server is currently blocked.
1. The file lock call has changed
2. rpmsgfs support cross-core filelock
Local test Pass
=> Rpmsgfs support filelock

libs/libc/misc/lib_fdcheck.c
reason: ioctl will use the fl_lock file lock, causing context switching, further leading to the failure of g_fdcheck_lock protection
$ make
=> fdcheck: fix race condition in fdcheck

tools/parsetrace.py
Traceback (most recent call last):
File nuttx/tools/parsetrace.py, line 29, in <module>
from pycstruct import pycstruct
ModuleNotFoundError: No module named 'pycstruct'
=> tools/parsetrace.py:fix parsetrace script error.

drivers/input/goldfish_events.c
input: fix goldfish input and lvgl input device name mismatch problem
goldfish event input
goldfish event input
=> input: fix goldfish input and lvgl input device name mismatch problem

drivers/note/noteram_driver.c
=> nuttx/note:fix missing the last character when printing custom labels.

fs/mmap/fs_rammap.c
mmap/fs_rammap.c: In function ‘unmap_rammap’:
mmap/fs_rammap.c:117:20: warning: ‘newaddr’ may be used uninitialized [-Wmaybe-uninitialized]
117 |       entry->vaddr = newaddr;
|       ~~~~~~~~~~~~~^~~~~~~~~
mmap/fs_rammap.c:56:13: note: ‘newaddr’ was declared here
56 |   FAR void *newaddr;
|             ^~~~~~~
=> fs/mmap: Fix build warning with [-Wmaybe-uninitialized].

net/pkt/pkt_sockif.c
pkt_sockcaps returns SOCKCAP_NONBLOCKING to indicate that pkt supports nonblock configuration.
x86_64 board.
=> net/pkt: fix issue that set nonblock by fcntl does not take effect

include/netinet/in.h
solve the compiling problem of the third-party library, add IN6_IS_ADDR_MC_LINKLOCAL and IN6_IS_ADDR_SITELOCAL definitions.
qemu:local
=> netinet/in.h: add macro definitions to resolve compilation errors

net/icmpv6/icmpv6_input.c
When CONFIG_NETDB_RESOLVCONF is enabled, CONFIG_NETDB_DNSSERVER_NAMESERVERS will undefined, could cause net/icmpv6/icmpv6_input.c build error. just add one nameserver to avoid overwrite ipv4 nameserver.
qemu:local
=> net/icmpv6/icmpv6_input.c: fix undefined build error

Documentation/platforms/xtensa/esp32s3/index.rst, arch/xtensa/src/esp32s3/Kconfig, arch/xtensa/src/esp32s3/Make.defs, arch/xtensa/src/esp32s3/esp32s3_sdmmc.c, arch/xtensa/src/esp32s3/hardware/esp32s3_sdmmc.h, arch/xtensa/src/esp32s3/hardware/esp32s3_soc.h, boards/xtensa/esp32s3/common/include/esp32s3_board_sdmmc.h, boards/xtensa/esp32s3/common/src/Make.defs, boards/xtensa/esp32s3/common/src/esp32s3_board_sdmmc.c, boards/xtensa/esp32s3/esp32s3-devkit/src/esp32s3_bringup.c, boards/xtensa/esp32s3/esp32s3-eye/src/esp32s3_bringup.c, boards/xtensa/esp32s3/esp32s3-korvo-2/src/esp32s3_bringup.c, drivers/mmcsd/Kconfig, drivers/mmcsd/mmcsd.h, drivers/mmcsd/mmcsd_sdio.c, drivers/mmcsd/mmcsd_sdio.h, include/nuttx/sdio.h
*Following commits are in a series. They have dependencies on commit(s) before them, so cannot be put in separate pull requests.*
[1/7] mmcsd: fix unable to switch eMMC device to 4-bit bus width mode
All eMMC devices support 4-bit bus width, so we should mark the device as supporting 4-bit bus width after detecting that the device type is eMMC.
[2/7] mmcsd: optimize macros for setting EXT_CSD
CMD6 can use these macros to set any writable EXT_CSD field, not just the bus width, so optimize these macro definitions to make them general.
[3/7] mmcsd: support MMC high speed SDR mode
According to the eMMC specification, in Backwards Compatibility with legacy MMC card mode, the frequency of the SD clock must be 0-26 MHZ; in high speed SDR mode, it must be 0-52MHZ. So we should switch to high …
=> [drivers/mmcsd|arch/xtensa/src/esp32s3|boards/xtensa/esp32s3]ESP32S3 Emmc Support
