apache/nuttx

arch/risc-v/src/qemu-rv/CMakeLists.txt

This adds CMake support of RPTUN devices for QEMU-RV chip.
None
- local checks with QEMU-RV
- CI checks

riscv/qemu-rv: add RPTUN cmake

---

tools/minidumpserver.py

stack dump add new region `show stacks`, but this script is not support now this is fixed with adding check condition for all lines contains stack word

minidumpserver: fix parsing bug

---

arch/sim/src/sim/sim_head.c

==263401==ERROR: AddressSanitizer: stack-use-after-return on address 0xf515f260 at pc 0x042434f0 bp 0x9ac24e78 sp 0x9ac24e68 WRITE of size 4 at 0xf515f260 thread T0
#0 0x42434ef in nxsem_get_value semaphore/sem_getvalue.c:65
#1 0x413110d in work_thread wqueue/kwork_thread.c:195
#2 0x412c4f6 in nxtask_start task/task_start.c:129
#3 0x427b1fc in pre_start sim/sim_initialstate.c:52
Address 0xf515f260 is located in stack of thread T0 at offset 32 in frame
#0 0x928c9e3 in host_settimer sim/posix/sim_hosttime.c:104
This frame has 1 object(s):
[32, 48) 'it' (line 105) <== Memory access at offset 32 is inside this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
(longjmp and C++ exceptions *are* supported)

nuttx/sim:By default, stack-use-after-return is not checked when enabling SIM_ASAN.

---

drivers/wireless/ieee80211/bcm43xxx/bcmf_sdio.c

may busyloop when frequently turn up/down wlan NIC 
Wifi
Test on vela product

[driver][bcm43xxx] reset tx_seq of sido-bus when ifdown wlan-if

---

include/nuttx/audio/audio.h

used in vela compress audio devices
tested on vela sim.

nuttx/audio: add AUDIOIOC_GETPOSITION ioctl

---

include/assert.h

check COMPILE_TIME_ASSERT before define
https://github.com/apache/nuttx/pull/12947  has not been reviewed yet
N/A
ci-check

assert: check COMPILE_TIME_ASSERT before define

---

.pre-commit-config.yaml
Documentation/contributing/coding_style.rst

Follows discussion on issue #12912
Allows the uses of the pre-commit tool for quicker style checking.
A single addition would be necessary, which is a file called .pre-commit-config.yaml on the root directory.
Other than that, a documentation entry.
Tested locally. No impacts on CI or builds.

tools: add improved pre-commit tool

---

arch/risc-v/src/esp32c3/esp_wifi_adapter.c

Fix a typo on password setting where station password was set instead of AP password. Issue reported in #13014 
Fix wrong password setting.
Test passing on internal CI.

arch/risc-v/esp32c3: fix AP password memcpy typo

---

boards/arm/stm32/common/src/stm32_ds1307.c

Fix DS1307 initialization for common STM32 logic
Users will be able to build using DS1307 and STM32 common logic.
- Add DS1307 on bringup for testing board (STM32 based board).
- Enable Common Logic and DS1307 related configs (CONFIG_RTC_DS1307, etc).
- Build and test on the testing board.

arm: Fix DS1307 initialization for common STM32 logic

---

net/pkt/pkt_sendmsg.c

net/pkt: fix raw socket send data length is insufficient
Using EXAMPLES_NETPKT (data length 128byte) for verification, it was found that the data length is insufficient, exactly missing 14 bytes (i.e., the length of the Ethernet header).
Before the modification, the data length was 14 bytes short. 
After the modification, the data length is correct.

net/pkt: fix raw socket send data length is insufficient

---

libs/libc/stdio/lib_remove.c

When the deleted path is a file, the return value of get_errno is -EISDIR, so in Condition Two
```
(get_errno() ! = EPERM && /* .... . try to remove it. */
rmdir(path) ! = 0)
```
The judgment holds directly, so it can't actually execute to rmdir
None

lib_remove:Repair the logical judgment

---

net/tcp/tcp_timer.c

solve Problem of tcp parameter calculation exceeding the boundary
curl download files

solve Problem of tcp parameter calculation exceeding the boundary

---

net/tcp/tcp_input.c

The Bluetooth network on N62 does not retransmit packet, so no packet retransmition if we drop one, we will drop packet when tcp_close_eventhandler is register and invoke by tcp_input. then we will always early return and never stop, the peer will only close the connection if we send reset packet.
precondition:
close -> register tcp_close_eventhandler;
tcp_input -> tcp_callback(TCP_NEWDATA) -> devif_conn_event -> tcp_close_eventhandler -> flags &= ~TCP_NEWDATA -> NOT entry tcp_data_event -> conn->recvreq NOT increase
old flow:
tcp_input -> tcp->seqno greater than conn->rcvseq -> tcp_send(TCP_ACK)
with this patch:
tcp_input -> tcp->seqno greater than conn->rcvseq -> !TCP_ESTABLISHED -> case TCP_FIN_WAIT_1 -> dev->d_len greater than 0 -> tcp_reset
Tcp conn
Test on vela product

tcp_input: if tcp->req > recvreq, send ack only when state is TCP_ESTABLISHED

---

drivers/net/wifi_sim.c

fix wifi sim compile warning
wifi sims

wifi_sim.c:fix compile warning

---

net/icmp/icmp_sockif.c

There may be situations where another thread is operating on the icmp socket while releasing it. To prevent exceptions, add netlock  to protect socket release operations
icmp ref counts

icmp:add net_lock to protect icmp connection

---

fs/procfs/fs_procfs.c

will at lease lead to extra code size cost, also possible dataabort.
Before fix, if not enabled mempool, should manually select the CONFIG_FS_PROCFS_EXCLUDE_MEMPOOL
after fix, if mempool is not enabled globally, the mempool entry will not able to enabled
CI-test

procfs/mempool: fix did not remove when pool not enabled

---

net/icmpv6/icmpv6_autoconfig.c
net/icmpv6/icmpv6_input.c

There are two changes here：
- One is to set the gateway for the stateful mode;
- The other is to allow both stateful mode and stateless mode to obtain the IPv6 addresses at the same time.
N/A
After using the `renew6` command to obtain the IPv6 address, 
and check the obtained IPv6 address by the `ifconfig` command.

Modify the IPV6 address acquisition method and the gateway settings.

---

arch/arm/include/armv7-a/irq.h

the reason for this fix:
According to the current design on the armv7-a platform, only fiq is processed in TEE, while irq and fiq are processed in REE. If we enable the irq function in TEE, when we process some signal-related scenarios in TEE, such as the ostest sighand testcase, this testcase will call up_irq_enable() to enable irq interrupt in the arm_sigdeliver() function. After the signal processing logic is executed, irq will be disabled again.
During the interval of enabling irq, some external device irq interrupts will be enabled, but these external device irqs do not have corresponding handlers registered in TEE, so an "unexpected irq isr exception" will be triggered. Therefore, a better implementation is to keep the original implementation of the up_irq_enable() function, that …

armv7a/irq: enable fiq in tee, enable irq in ap

---

net/netdev/netdev_ioctl.c

When our apps call getifaddrs on lo frequently, the loopback device will failed in SIOCGIFHWADDR and print too many error logs.
netdev ioctl

netdev/ioctl: Setting log level to warning on SIOCGIFHWADDR failure

---

drivers/net/netdev_upperhalf.c
drivers/virtio/virtio-net.c
include/nuttx/net/netdev_lowerhalf.h

Add reclaim callback and use it in virtio-net
- netdev_lowerhalf: add reclaim callback in netdev_ops_s
- drivers/virtio-net: Use reclaim in ops to finish TODO
Clear a TODO in virtio-net
Manually with QEMU, no effect on speed.

netdev/lower: Add reclaim callback and use it in virtio-net

---

CMakeLists.txt
cmake/nuttx_add_application.cmake
cmake/nuttx_add_library.cmake
cmake/nuttx_allsyms.cmake
cmake/nuttx_generate_headers.cmake
cmake/nuttx_generate_outputs.cmake

Add two intermediate targets to control the correct build timing order
`nuttx_post`:
custom target nuttx_post_build execution timing of a may be confused with other post-build processing.
occasional cause errors:
```shell
[1209/1210] cd /home/work/cmake_out && arm-none-eabi-objcopy -O binary nuttx nuttx.bin && arm-none-eabi-objcopy -O binary nuttx vela_core1.bin && cp nuttx vela_core1.elf && cp nuttx.hex vela_core1.hex && cp nuttx.map vela_core1.mapfile
FAILED: boards/exclude_board/CMakeFiles/nuttx_post_build /home/work/cmake_out/boards/exclude_board/CMakeFiles/nuttx_post_build
cd /home/work/cmake_out && arm-none-eabi-objcopy -O binary nuttx nuttx.bin && arm-none-eabi-objcopy -O binary nuttx vela_core1.bin && cp nuttx vela_core1.elf && cp nuttx.hex vela_core1.hex && cp nuttx.map …
```

[cmake] add nuttx_post and app_context inter targets for timing control

---

libs/libc/misc/CMakeLists.txt
libs/libc/misc/Make.defs
libs/libc/misc/lib_getnprocs.c

1.Remove the macro definition of getnproc in sysinfo
2.New get_nprocs_conf and get_nprocs interfaces, return CONFIG_SMP_NCPUS, return 1 when not defined
From macro implementation to function implementation

libc/msic:Implement get_nprocs API

---

drivers/modem/alt1250/altcom_hdlr_pin.c

Disable the PIN feature in ALT1250 because the SIM may accidentally become unusable.
Only ALT1250 driver.

drivers/modem/alt1250: Disable the PIN feature in ALT1250

---

net/tcp/tcp_send_buffered.c

After setting the retransmission flag, we need to set the `dupack` counter to 0.
N/A
Locally verified.

net/tcp: reset the dupack counter.

---

drivers/net/Kconfig
drivers/net/netdev_upperhalf.c
include/nuttx/net/netdev_lowerhalf.h

supports the protocol stack to trigger the NIC driver to reclaim pkt resources.
add polling mode support for netdev_upperhalf tx/rx
qemu:x86_64

netdev_upperhalf: add polling mode support for tx/rx

---

arch/sim/src/sim/sim_framebuffer.c
drivers/video/fb.c
drivers/video/goldfish_fb.c
include/nuttx/video/fb.h

add fb_vsync_pollnotify for sim and goldfish_fb
when the vsync comes, fb drivers should call fb_vsync_pollnotify to notify POLLPRI, so that users can catch the synchronization time of vsync and do something
users can catch the synchronization time of vsync
None

add fb_vsync_pollnotify

---

arch/arm/src/armv7-m/arm_mpu.c
arch/arm/src/armv8-m/arm_mpu.c

From cortex spec, when setting up the MPU, execute  a DSB instruction and then an ISB instruction to ensure that all subsequent memory taking effect. 
arm mpu programming
testing in lm3s6965-ek:qemu-protected

arm/armv[7|8]-m: add syn barrier for MPU ops

---

drivers/power/pm/pm_activity.c

critical_section is not compatible with irq disabled, have to delay the wd_start after spin_unlock_irqrestore.
before fix, pm_wakelock_staytimeout will cause a dead lock directly,
after fix, wd_start will be delay a little bit.
CI-test & qemu test-case

pm_activity: fix deadlock with spinlock and critcal_section

---

fs/rpmsgfs/rpmsgfs.c

f_type should be set RPMSGFS_MAGIC when mount through rpmsgfs
or  "df -h" will show
rpmsgfs_statfs result

rpmsgfs: set fs type to rpmsgfs when mount through rpmsgfs

---

boards/arm/stm32l4/nucleo-l432kc/include/board.h

As per board documentation, USART2 can be configured to use PA15 to access the virtual COM port via a USB port.
Accessing NSH via USB port (virtual COM) is a preferred solution, therefore this reverts commit 60236ce94d310935bd9f9663b19454b86fa45957 and fixes the issue reported by https://github.com/apache/nuttx/issues/13061.
Users can access NSH via a virtual COM port (USART2).
- Configure nucleo-l432kc:nsh 
- Build and flash the board
- Use minicom or picocom to access NSH via virtual COM.

nucleo-l432kc: Revert the USART2 config to be use by virtual COM port

---

drivers/power/pm/CMakeLists.txt
drivers/power/pm/Make.defs
drivers/power/pm/pm_idle.c
include/nuttx/power/pm.h

pm process should be done by chip specific, but we can provide a standard flow, then vendor & chip can only focus on handle different state change.
No impact for default.
new chip, new vendor can use pm_idle standard workflow as a optional.
CI-test & arm-v7m chip self-test.

pm: add pm_idle, up_idle only handle pm state execution

---

include/time.h
include/wchar.h
libs/libc/stdio/lib_libvscanf.c
libs/libc/stdio/lib_libvsprintf.c
libs/libc/stdlib/Kconfig
libs/libc/stdlib/lib_srand.c
libs/libc/stdlib/lib_strtold.c
libs/libc/time/lib_difftime.c
libs/libc/wchar/lib_wcstod.c
libs/libc/wchar/lib_wcstof.c
libs/libc/wchar/lib_wcstold.c

Enclosed floating-point related functions using macros to be more compatible with chips that do not have an FPU.
use float fuction
vela & qmue arm64 with out fpu

libc:Add macro restrictions to code that uses floating point numbers

---

drivers/power/pm/pm_runtime.c

If the sched.h not included by header already inside .c will cause sched_idletask not defined
None
CI-test

pm_runtime: fix missing header

---

sched/init/nx_smpstart.c

Fix a typo in comments of `nx_idle_trampoline`.
None
- CI checks

docs: fix typo in nx_smpstart.c

---

arch/sim/Kconfig
arch/sim/src/sim/posix/sim_alsa.c

add offload buffer size config and fix.
tested on vela sim.

nuttx/audio: add offload buffer size config

---

Documentation/guides/gdbserver.rst
Documentation/guides/index.rst
tools/gdbserver.py
tools/minidumpserver.py

1. Optimized the usage logic to use a different port if the current port is occupied.
2. Added support for loading a raw format memory file into minidump to facilitate debugging. By saving memory in raw format and using minidump to restore it as a gdb session on the host, debugging is made easier.
3. Added support for minidump to write register values.
4. Improved the socket interaction speed of minidump
5. support `info thread` and `thread` command in gdb
6. support coredump load
7. change name, `minidumpserver.py` to `gdbserver.py`
minidumpserver.py
qemu mps3an547 with crash, and use gdb read raw memory, then use minidump to pasre it.

Enhanced minidumpserver.py

---

include/nuttx/mm/mempool.h
mm/mempool/mempool.c
mm/mempool/mempool_multiple.c
tools/gdb/memdump.py
tools/gdb/utils.py

Reimplemented the mempool traversal function and fixed some existing bugs in the mempool.
Re-implementation:
The previous implementation could not effectively handle the use of memdump in an SMP environment because syslog would create race conditions under SMP. Therefore, instead of traversing the linked list, we directly traverse the entire memory address space. This approach avoids race conditions in an SMP environment and makes debugging easier.
bug fix:
1. fix bug when deinit mpool, wrong parameters used
2. Need check mpool is NULL
3. need unposion memory when deinit
4. fix bug when free a alignment address
5. fix mempool memdump address incorrect printing
6. fix memdump leak will hang on spinlock
mempool
vela & qmue mpsan547 mm testing with mempool

Reimplemented the mempool traversal function and fixed some existing bugs in the mempool

---

crypto/cryptodev.c
crypto/cryptosoft.c
include/crypto/cryptodev.h

The upper can copy the context through dup2(fd1, fd2), which is useful in hashing operations for network.
Provides the ability to copy the encryption context, which can save an intermediate state of encryption

crypto: import the ability to clone session

---

libs/libc/obstack/lib_obstack_vprintf.c

obstack_printf and obstack_vprintf should terminate the C string with null byte but lib_vsprintf doesn't do it. It must be done on top of that unless we get unterminated string.
This also includes minor tweak to use obstack_1grow directly instead of calling obstack_puts.
This is fix to be consistent with GlibC behavior.
Tested on samv7 eval kit against custom code.

libs/libc/obstack: correctly append null byte at the end of string

---

arch/sim/Kconfig
arch/sim/src/sim/sim_camera.c
arch/sim/src/sim/sim_decoder.c
arch/sim/src/sim/sim_encoder.c
drivers/video/v4l2_cap.c

1. Fix build warning & sign extension
2. sim_camera: rename video to camera
NA
1. [nxcamera](https://nuttx.apache.org/docs/latest/applications/system/nxcamera/index.html)
2. [nxcodec](https://nuttx.apache.org/docs/latest/applications/system/nxcodec/index.html)

video: fix warning & update sim camera

---

sched/irq/irq_attach.c

sched/irq: correct critical section to spin lock
Regression by https://github.com/apache/nuttx/pull/12281:
```
| commit 2ee8aa6f2b4ae5384f7dc984f467702d5f3fbf40
| Date:   Thu Jan 11 11:27:31 2024 +0800
|
|     sched: we use spin_lock_irqsave replace enter_critical_section to protect g_irqvector
|
|     enter_critical_section may be called before os initialized
|
|     Signed-off-by: hujun5 <hujun5@xiaomi.com>
```
N/A
ci-check

sched/irq: correct critical section to spin lock 

---

fs/vfs/fs_lock.c
include/nuttx/fs/fs.h
include/nuttx/lib/lib.h
libs/libc/misc/CMakeLists.txt
libs/libc/misc/Kconfig
libs/libc/misc/Make.defs
libs/libc/misc/lib_pathbuffer.c

1. Add lib_get_pathbuffer / lib_put_pathbuffer instead of temporary variable.
2. Reduce stack size. Getting the tmp buffer through the lib_get_pathbuffer function reduces the declaration of temporary variables
3. Fix an unsynchronized lock acquisition by closelk in multi-threaded scenarios. Ensure atomic behavior when acquiring lock status.
4. Optimized additional performance overhead due to closelk in the close phase (even if the fd doesn't use fslock)
Optimizing performance:
Before: Time taken to close the file: 33984 nsec
After: Time taken to close the file: 23744 nsec
Improvement of about 10 msec
Optimizing fslock

Fslock optimize

---

arch/arm/src/armv7-m/arm_mpu.c
arch/arm/src/armv7-m/mpu.h
arch/arm/src/armv7-r/arm_mpu.c
arch/arm/src/armv7-r/mpu.h
arch/arm/src/armv8-m/arm_mpu.c
arch/arm/src/armv8-m/mpu.h
arch/arm64/src/common/arm64_mpu.c
arch/arm64/src/common/arm64_mpu.h
arch/xtensa/src/common/mpu.h
arch/xtensa/src/common/xtensa_mpu.c

In the current NuttX MPU implementation, it is not possible to reconfigure a region that has already been set. Therefore, the purpose of this MPU upgrade is to enhance the ability of NuttX MPU to more accurately adjust the region.
The main interfaces are
```
void mpu_modify_region(unsigned int region, uinptr_t base, size_t size, uint32_t flags);
void mpu_clear_region(unsigned int region).
```
And change the g_region at the beginning to a bitmap to indicate whether each region has been allocated or not.
update mpu for:
armv7m
armv8m
armv7r
arm64
xtensa

MPU update

---

CMakeLists.txt

Resolved compile warning
cl : command line  warning D9002: ignoring unknown option '-fmacro-prefix-map=
None
local and GITHUB
cmake -B vs2022 -DBOARD_CONFIG=sim/windows -G "Visual Studio 17 2022" -A Win32

CMakeLists.txt: warning D9002 on Windows + msvc

---

crypto/cryptodev.c
crypto/cryptosoft.c
crypto/xform.c
include/crypto/cryptodev.h
include/crypto/xform.h

1. export poly1305 and ripemd160 algorithm via /dev/crypto
2. implemented software process in cryptosoft.c

nuttx/crypto: support poly1305 and ripemd160 algorithm

---

include/nuttx/lib/lib.h
libs/libc/stdlib/lib_realpath.c

add a new api 
FAR char *lib_realpath(FAR const char *path, FAR char *resolved, bool notfollow);
Add the **nofollow** parameter to choose whether to resolve the path if it is a symbolic link.

api:add lib_realpath function

---

drivers/video/fb.c

changed circbuf_write assert to warning. On some hardware devices, crashes may occur due to assert, which is something  we do not expect.  Changing it to 'warning' may be better.
fb
fb demo

video/fb: changed circbuf_write assert to warning

---

arch/sim/src/sim/posix/sim_x11framebuffer.c
arch/sim/src/sim/sim_framebuffer.c
tools/nxstyle.c

It can only read the contents of the first buffer, so fblen should be changed to ensure that it can read the second buffer as well.
sim
run sim lvgl
cat  /dev/fb0 >/data/frame.raw
transfer frame.raw to rgb32 png

sim: read the second buffer

---

drivers/net/Kconfig
include/nuttx/net/netdev.h
net/netdev/CMakeLists.txt
net/netdev/Make.defs
net/netdev/netdev_stats.c
net/netdev/netdev_unregister.c

Work for every network device using `CONFIG_NETDEV_STATISTICS`.
Log style:
```
<interface>:T{done}/{total},R({v4}+{v6})/{total} {Protocol}:T{tx},R{rx},D{drop}
```
Example:
```
wlan0:T10/10,R(10+20)/31 TCP:T0,R0,D0 UDP:T0,R10,D0 ICMP:T0,R0,D0 ICMP6:T0,R0,D0
````
Log for netdev controlled by `NETDEV_STATISTICS_LOG_PERIOD`, no print if there's no traffic.
Manually on both SIM and products.

net/netdev: Add periodic log for netdev statistics

---

drivers/serial/uart_rpmsg.c

data copy to nbuffer should start from data + length

fix:uart_rpmsg_dmareceive 

---

drivers/bch/bchlib_cache.c
drivers/bch/bchlib_setup.c

When the buffer to be written is aligned according to the erase block size and its size is a multiple of the erase block size，
we do not need to alloc the bch->buffer

bch:alloc bch->buffer when offset not aligned

---

fs/notify/inotify.c
fs/vfs/fs_lock.c
include/search.h
libs/libc/search/hcreate_r.c

Add free func hook for user to deallocate memory
The memory of entry->key && entry->data are allocated by user,
and should be freed by user.

Bugfix hcreate

---

fs/rpmsgfs/rpmsgfs_client.c

msg->buf has different type with struct stat, so can not memcpy directly.
rpmsgfs
test in sim:rpserver, sim:rpproxy

rpmsgfs: fix out of bounds access caused by data transmission farmat

---

drivers/syslog/syslog_rpmsg.c

syslog_rpmsg: Ensure the syslog ept is ready when rpmsg_send
none

syslog_rpmsg: Ensure the syslog ept is ready when rpmsg_send

---

libs/libc/assert/CMakeLists.txt
libs/libc/assert/Make.defs
libs/libc/assert/lib_stackchk.c

compile stackchk function by default

libc: compile stackchk function by default

---

drivers/input/touchscreen_upper.c

In touch_event, circbuf is operated, and there is a lack of protection here.

input: fix touchevent race condition

---

fs/procfs/fs_procfscritmon.c

Command "critmon" has some format errors and information errors, such as:
After bug fix:
config is:
N/A
Execute "critmon" in nsh

[BugFix]Command "critmon" error

---

arch/sim/Kconfig
arch/sim/src/sim/sim_head.c

There is a false positive in asan of gcc-13, we need to mask it to ensure that other parts work properly
sanitizer_common/sanitizer_common_interceptors.inc:
// FIXME: under ASan the call below may write to freed memory and corrupt
// its metadata. See
// https://github.com/google/sanitizers/issues/321.
==572161==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0xed3d3f00 at pc 0xef46af64 bp 0xed3d3de8 sp 0xed3d39bc
WRITE of size 128 at 0xed3d3f00 thread T0
#0 0xef46af63 in __interceptor_pthread_sigmask ../../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:4419
#1 0x5486aa7d in up_irq_save sim/posix/sim_hostirq.c:97

suppress libasan checks

---

include/nuttx/mutex.h
libs/libc/misc/lib_mutex.c

This part of the change is a precondition for changing the implementation of pthread_mutex from a semaphore to a mutex lock.
nxmutex api enhancements, the changes are as follows
Modify nxmutex_breaklock/restorelock parameter from bool to int
int nxmutex_restorelock(FAR mutex_t *mutex, FAR unsigned int *locked);
int nxmutex_breaklock(FAR mutex_t *mutex, FAR unsigned int *locked);
Add the following api:
nxmutex_get_holder, nxrmutex_get_holder
nxmutex_clocklock, nxrmutex_clocklock,
nxrmutex_is_recursive, nxrmutex_is_recursive
ostest and internal tests

nxmutex api enhance

---

audio/Kconfig
include/nuttx/audio/audio.h

- nuttx/audio: add opus format support 
- nuttx/audio: Add amr and opus format control switches 
- nuttx/audio: ap_buffer_s add nsamples Field for non-pcm formats
new flags
ci and internal test

Audio upstream

---

arch/arm/Kconfig
arch/arm/src/qemu/CMakeLists.txt
arch/arm/src/qemu/Make.defs
arch/arm/src/qemu/qemu_idle.c

This adds WFI based `qemu_idle.c` to avoid busy loops.
arm/qemu device
- local check with `qemu-armv7a`
- CI checks

arm/qemu: enable WFI in `up_idle`

---

net/ipfrag/ipv6_frag.c

modify the type of the ipv6 parameters to solve runtime error
ipv6 ping

modify the type of the ipv6 parameters to solve runtime error

---

arch/sim/Kconfig
arch/sim/src/sim/posix/sim_x11framebuffer.c
arch/sim/src/sim/sim_framebuffer.c
arch/sim/src/sim/sim_internal.h
arch/sim/src/sim/sim_lcd.c

Some hardware devices use discontinuous framebuffers, which needs SIM to support for simulating discontinuous framebuffers.
sim
sim fb

sim: Support to use of non-consecutive framebuffers

---

sched/signal/sig_dispatch.c

When a low-priority thread sends a kill signal to a high-priority thread, the high-priority thread will exit and release tcb. When the thread returns to the low-priority thread, it will access the released stcb.

sched/signal: fix pthread_kill use after free

---

drivers/can/can.c
include/nuttx/can.h
include/nuttx/can/can.h

1. Some macro definitions have already been defined in other header files, redundant macro definitions have been removed in include/nuttx/can.h.
2. Align some code.
3. Remove no use struct (can_response_s) and some variables.
CAN protocol stack.
Brush the modified system to the CAN development board, and the CAN communication between the development board and peripherals is normal.

can:  CAN code optimization

---

arch/arm/include/spinlock.h

arm/spinlock: up_testset() sould not depends on SMP
up_testset() sould not depends on SMP
N/A
ci-check

arm/spinlock: up_testset() sould not depends on SMP 

---

drivers/mtd/mtd_partition.c

mtd:use part->name as partition name when CONFIG_MTD_PARTITION_NAMES set
part->name will be set at  mtd_setpartitionname

mtd:use part->name as partition name when CONFIG_MTD_PARTITION_NAMES set

---

crypto/cryptodev.c
crypto/cryptosoft.c
crypto/poly1305.c
include/crypto/cryptodev.h

1. Fix copy iv direction error in symmetric encryption
2. Fix type in rsa verify
3. Fix false positive '-Wstringop-overflow' warning in poly1305 file

nuttx/crypto: fix wrong implementation in crypto module 

---

sched/misc/assert.c

1. When recursing in Assert, the system is reset
2. Actively suspend other CPUs when ASSERT occurs in SMP cases
3. Support all files of dump after Assert

Enhance ASSERT

---

drivers/pipes/pipe.c
drivers/pipes/pipe_common.c
drivers/pipes/pipe_common.h
include/nuttx/fs/ioctl.h
net/local/local.h
net/local/local_bind.c
net/local/local_conn.c
net/local/local_connect.c
net/local/local_fifo.c
net/local/local_recvmsg.c
net/local/local_recvutils.c
net/local/local_sendmsg.c
net/local/local_sendpacket.c
net/local/local_sockif.c

For udp localsocket current implementation,the sent information only carries the packet info.
The receiver receives the information,it don't know who the information comes from.
Thus the receiver doesn't know who to send the response message to.
We add sender's binding path info in the information,the receiver knows who sent the information
based on the parsed information.
The receiver knows who to send the response message to.
localsocket
refer to the https://xiaomi.f.mioffice.cn/wiki/wikk4f0am50AewzAGVhE2iMVpnw chapter 57 the test case

localsocket improvment

---

arch/risc-v/src/k210/CMakeLists.txt
boards/risc-v/k210/maix-bit/CMakeLists.txt
boards/risc-v/k210/maix-bit/src/CMakeLists.txt

This adds initial cmake support for `maix-bit` device.
None
- local check with QEMU
- CI checks

board/maix-bit: initial cmake support

---

boards/risc-v/esp32c6/common/include/esp_board_mfrc522.h
boards/risc-v/esp32c6/common/src/Make.defs
boards/risc-v/esp32c6/common/src/esp_board_mfrc522.c
boards/risc-v/esp32c6/esp32c6-devkitm/src/esp32c6_bringup.c

This patch adds support to use rfid card reader MFRC522 on SPI2 for esp32c6-devkitm board
New feature
1-  Enable SPI2;
2 - Contactless device drive;
3 - Rfid_readuid example app;
4 - Build;
5 - Flash;
6 - Run example.

boards/risc-v/esp32c6/esp32c6-devkitm: Add support to RFID MFRC522

---

boards/xtensa/esp32s3/common/src/esp32s3_lan9250.c
boards/xtensa/esp32s3/esp32s3-devkit/src/esp32s3-devkit.h

boards/esp32s3_lan9250: deinitialize the ethernet device lan9250 for esp32s3.
Add a board-level deinit call interface for ESP32-S3 LAN9250.
esp32s3-devkit:eth_lan9250

boards/esp32s3_lan9250: deinitialize the ethernet device lan9250

---

arch/xtensa/src/esp32s3/esp32s3_qspi.c

Some spi slave device set address with special command, no address required in read command, so separate address and command setting.
esp32s3 qspi
esp32s3-devkit

xtensa/esp32s3: Separate address and command flag for QSPI DMA transfer

---

include/fcntl.h

include/fcntl.h: add O_LARGEFILE flags

include/fcntl.h: add O_LARGEFILE flags

---

net/tcp/tcp_input.c
net/tcp/tcp_send.c

Interrupt the tcp_timer loop when idle, add it when starting work
TCP network / retransmit
Retransmission test on SIM with iperf3 (ps: iperf3 -u at the start and end have TCP stat exchange ,so during the testing TCP timer will be canceled)
[SIM] iperf3 -c 120.26.1.167 -u -t 20 -i 1
[Ubuntu during iperf3 test ] iptables -I FORWARD -p tcp --dport 5201 -j DROP
we can see packets with tcpdump at end of iperf3 and it will retransmit 8 times and can closed.
we also can see tcp timer canceled during iperf3 test by adding debug msg.

net/tcp_timer: fix tcp_timer idle loop and retransmission bug

---

libs/libc/machine/arch_atomic.c

add ghs header file support using to fix the following link error:
[elxr] (error #412) unresolved symbols: 
__sync_synchronize 	from libopenamp.a(io.o)

greenhills support: add the "__sync_synchronize" func impl

---

include/nuttx/wireless/wireless.h

1. add DTIM/PWSAVE for low power device requirements.
2. move COUNTRY/PTAPRIO to private id area.
3. add SIOCGIWPMKSA  for fast wifi connect requirement.
N/A
tested on vela product

Private requirement for wapi

---

libs/libc/assert/Make.defs

fix the unrecognized no-lto link options, the detailed warning info are:
ccarm: Warning: Unknown option "-fno-lto" passed to linker
CC:  assert/lib_stackchk.c ccarm: Warning: Unknown option "-fno-lto" passed to linker

greenhills support: fix the build options warning

---

fs/shm/shmfs_alloc.c

[Desc]:
1. We need to check the parameter passed to the kmm_zalloc(size_t) function. 
2. If it exceeds the limit of size_t, we need to return an error directly to avoid further errors.

[fs][shmfs]:Avoid an integer overflow

---

drivers/net/netdev_upperhalf.c
include/nuttx/net/netdev.h
net/devif/ipv4_input.c
net/icmp/Kconfig
net/icmp/icmp_input.c
net/icmp/icmp_reply.c
net/icmp/icmp_sendmsg.c
net/icmpv6/Kconfig
net/icmpv6/icmpv6_advertise.c
net/icmpv6/icmpv6_input.c
net/icmpv6/icmpv6_radvertise.c
net/icmpv6/icmpv6_reply.c
net/icmpv6/icmpv6_rsolicit.c
net/icmpv6/icmpv6_sendmsg.c
net/icmpv6/icmpv6_solicit.c
net/igmp/Kconfig
net/igmp/igmp_input.c
net/igmp/igmp_send.c
net/inet/Kconfig
net/inet/ipv4_build_header.c
net/mld/mld_send.c
net/tcp/Kconfig
net/tcp/tcp_input.c
net/tcp/tcp_send.c
net/utils/net_ipchksum.c

If the hardware supports checksum or not, the checksum calculation function for the TCP/UDP/ICMP/ICMPv6 network protocol stack can be turned on/off through macro configuration.
By setting the default macro switches, the original code execution process is not affected.
NA

modify for offload checksum and add macro with tcp/icmp/icmpv6/igmp checksum

---

.gitignore
drivers/ioexpander/gpio.c
drivers/net/netdev_upperhalf.c
drivers/spi/spi_transfer.c
include/nuttx/ioexpander/gpio.h
include/nuttx/mqueue.h
include/nuttx/net/netdev.h
libs/libc/modlib/modlib_bind.c
libs/libc/modlib/modlib_globals.S

1. fix the macro misuse warning on ghs compiler
2. fix the enum type misuse warning
3. update the .gitignore rule to exclude the ghs build intermediate files out

greenhills support: fix the build warning while support greenhills build

---

fs/CMakeLists.txt
fs/Kconfig
fs/Makefile
fs/fs_heap.c
fs/fs_heap.h
fs/fs_initialize.c
fs/shm/shmfs_alloc.c
fs/tmpfs/fs_tmpfs.c
fs/vfs/fs_pseudofile.c

For some case, need large files from tmpfs or shmfs, will lead to high pressure on memory fragments, add a fs_heap to optional support indepent heap for memory fragments issue will benifit.
No impact for default case.
If enabled FS_HEAPSIZE, will use a mm_initialize to manage the shm/tmpfs/pseudofile memory
CI and Cortex-A7 smp chip.

fs: add fs_heap, support shm/tmpfs/pseudofile with indepent heap

---

drivers/serial/ptmx.c

If failed in pty_register2, it is possible to enter unregister_driver function, which eventually calls ptmx_minor_free, resulting in mutex conflict.

pty: use mutex to protect alloc minor

---

arch/sim/src/sim/sim_heap.c
fs/procfs/Kconfig
fs/procfs/Make.defs
fs/procfs/fs_procfs.c
fs/procfs/fs_procfspressure.c
include/nuttx/mm/mm.h
mm/mm_heap/mm_mallinfo.c
mm/tlsf/mm_tlsf.c
mm/umm_heap/umm_calloc.c
mm/umm_heap/umm_malloc.c
mm/umm_heap/umm_memalign.c
mm/umm_heap/umm_realloc.c
mm/umm_heap/umm_zalloc.c

This is a memory monitoring interface implemented with reference to Linux's PSI (Pressure Stall Information),
which can send notifications when the system's remaining memory is below the threshold.
The following example code sets two different thresholds.
When the system memory is below 10MB, a notification is triggered.
When the system memory is below 20 MB, a notification (POLLPRI event) is triggered every 1s.
```
{
struct pollfd fds[2];
int ret;
if (argc == 2)
{
char *ptr = malloc(1024*1024*atoi(argv[1]));
printf("Allocating %d MB\n", atoi(argv[1]));
ptr[0] = 0;
return 0;
}
fds[0].fd = open("/proc/pressure/memory", O_RDWR);
fds[1].fd = open("/proc/pressure/memory", O_RDWR);
fds[0].events = POLLPRI;
fds[1].events = POLLPRI;
dprintf(fds[0].fd, "%llu …
```

Add memory pressure monitoring

---

include/sys/socket.h

Rework solution from https://github.com/apache/nuttx/pull/8285 according to https://pubs.opengroup.org/onlinepubs/009695399/basedefs/sys/socket.h.html
Should be none
Pass CI

sys/socket: implement compiler agnostic sockaddr_storage alignment

---

tools/ci/docker/linux/Dockerfile
tools/ci/platforms/darwin.sh
tools/ci/platforms/ubuntu.sh

> could you create a new patch to enable hello_swift ci?
> 
>   * [**"Building the Docker Image for NuttX CI"**](https://lupyuen.github.io/articles/pr#appendix-building-the-docker-image-for-nuttx-ci)
> 
>  * [**"Downloading the Docker Image for NuttX CI"**](https://lupyuen.github.io/articles/pr#appendix-downloading-the-docker-image-for-nuttx-ci)
cc: @lupyuen @xiaoxiang781216 
---
Based on #12858, add another languages support on tool/ci.
- **Docker**
- **CI - platforms**
- brew install: zig, ldc2 - swift only v5 :face_exhaling: 
- apt-get install: ldc2
- msys2: no have Swift, D or Zig toolchain. Swift is unstable for Windows (MSVC only)
Tarballs are preferable for Zig and Swift6.

tools/ci: Add more bindings apps for QEMU RISC-V.

---

drivers/video/fb.c

fb:add select overlay FB_NO_OVERLAY. It is expected that select_overlay can switch from overlay to main plane.
fb overlay
fb demo

fb:add select overlay FB_NO_OVERLAY

---

net/ipfrag/ipfrag.c

If the device's CPU resources are scarce and unable to execute the ip_fragin_timerwork callback in a timely manner, this assert will be triggered. This is a normal scenario that can occur. The logic should be modified to wait for the ip_fragin_timerwork to be executed if it has not been executed yet.
cortex-m33 board

ipfrag: remove assert for actual product reasons

---

net/tcp/tcp_input.c

when tcp socket stays in TCP_FIN_WAIT_1 or TCP_FIN_WAIT_2,not actively calling tcp_close_eventhandler,can reuslt in some TCP socket being set to a closed state,but nofosegs are not directly released,leading to IOB resource leakage.
TCP 
solve the problem

tcp_close.c:when tcp socket stays in TCP_FIN_WAIT_1 or TCP_FIN_WAIT_2,calling tcp_close_eventhandler releases received packets

---

drivers/input/goldfish_events.c

fix goldfish events x64 unresponsive interrupt issue
goldfish driver
qemu

drivers: Fix goldfish events x64 unresponsive interrupt issue

---

drivers/net/tun.c
include/nuttx/net/ioctl.h

Add `TUNSETCARRIER` ioctl, then we may change the carrier state of TUN dynamically. Note that we don't need an ioctl for getting carrier, it can be done by `SIOCGIFFLAGS` already.
Ref: https://github.com/torvalds/linux/blob/v6.10/drivers/net/tun.c#L3374-L3380
Extra note: `_SIOC(0x003F)` is used by https://github.com/apache/nuttx/pull/13160, so use `_SIOC(0x0040)` here.
Support `TUNSETCARRIER` for TUN/TAP
Manually

net/tun: Support changing carrier state of TUN/TAP

---

arch/arm/src/armv7-a/arm_timer.c

If the frequency is too high, count * NSEC_PER_SEC will be overflow.
armv7-a arm_timer.
qemu

armv7-a timer:fix timer overflow.

---

arch/arm/include/cxd56xx/scu.h
arch/arm/src/cxd56xx/cxd56_scu.c

Add offset setting for sensor data to be written to SCU math function.
Fix comments in function descriptions.
Only for spresense.

arch: cxd56xx: Fix SCU sensor data format

---

arch/arm/Kconfig
arch/arm/src/cxd56xx/cxd56_i2c.c

Add ARCH_HAVE_I2CRESET configration to ARCH_CHIP_CXD56XX and implement i2c reset function.
Only for spresense

arch: cxd56xx: Add logic for i2c reset

---

drivers/ioexpander/gpio.c

fix the pointless comparison build warning, the detailed warning info are :
"ioexpander/gpio.c", line 529: warning #186-D: pointless comparison of
unsigned integer with zero
if (pintype < GPIO_INPUT_PIN || pintype >= GPIO_NPINTYPES)
^

greenhills support: fix the pointless comparison build warning

---

arch/arm64/Kconfig

The format is always 64-bits
Fix elf file format
imx9

arm64/imx9: Force 64-bit ELF format

---

drivers/timers/rtc.c

We should set alarminfo->active to false immediately, because we may continue to set it in the alarm expiration.
N/A

rtc alarm:fix doesn't call nxsig_notification

---

boards/arm/gd32f4/gd32f450zk-eval/src/gd32f4xx_at24.c

Prior to this commit, i2c and at24 may be used uninitialized on line 113, 117, 129, and 143 when gd32_at24_wr_test() is called the second time because these two variables are not static. I don't think making them static is the correct fix because i2c is released at the end of this function. Fixed by removing the `if (!initialized)` condition surrounding the initialization of i2c and at24, making them initialized at every call to this function.
gd32f450zk-eval:i2c0testnsh

gd32f4xx_at24: Fix uninitialized use of local variables i2c and at24

---

arch/arm64/src/common/arm64_checkstack.c

Need to instantiate the correct address environment when reading from user stack, otherwise the result is very likely a crash
Fix crash when ARCH_ADDRENV=y

arm64_checkstack.c: Fix traversing of user stack when ARCH_ADDRENV=Y

---

drivers/timers/Kconfig
drivers/timers/rpmsg_rtc.c

When ipc is busy, g_basetime may be inconsistent
on different cores.
rpmsg_rtc
ci

rpmsg_rtc:Update g_basetime from rpmsg.

---

.github/workflows/build.yml
CMakeLists.txt
arch/arm/src/cmake/platform.cmake
boards/CMakeLists.txt
cmake/nuttx_create_symlink.cmake
cmake/nuttx_kconfig.cmake
cmake/nuttx_sethost.cmake
tools/ci/testlist/msys2.dat

I took inspiration and expanded from this PR #11608 to support new platforms (same as make).
Currently concerns only arm.
tools/ci/testlist/msys2.dat: 
At the moment I only added the board nucleo-l152re:nsh
.github/workflows/build.yml: 
Enabled cmake for msys2
We tested on the local platform MSYS2 and GitHub (docker, darwin and MSYS2)

Cmake: [arch arm] added initial support for MSYS2 

---

include/nuttx/irq.h
sched/irq/CMakeLists.txt
sched/irq/Make.defs
sched/irq/irq.h
sched/irq/irq_attach.c
sched/irq/irq_attach_thread.c
sched/irq/irq_chain.c

purpose:
To improve the real-time performance of the system, we prefer to perform as few operations as possible within the interrupt function. We have designed an interrupt thread for each interrupt, where all the operations that are not necessary to be handled in the interrupt function are delegated to be processed by the interrupt thread. Up_enable_irq will be invoked after isrthread started.
$ make

irq: add isr thread

---

fs/mmap/fs_mmap.c
fs/mmap/fs_munmap.c
sched/environ/env_getenv.c
sched/environ/env_setenv.c

1. [env]:Fixed spacing and typo issues in code comment descriptions
2. [FS]:Fixed spacing and typo issues in code comment descriptions

Fixed spacing and typo issues in code comment descriptions

---

fs/nfs/rpc_clnt.c

- I noticed that nfsmount does not work due to the recent changes on sockaddr_storage alignment.
- None
- Tested with sabre-6quad:netnsh_smp (QEMU)

fs: nfs: Fix nfsmount error

---

arch/arm/src/cxd56xx/cxd56_nxaudio.c
arch/sim/src/sim/posix/sim_alsa.c
drivers/audio/audio_null.c
drivers/audio/cs4344.c
drivers/audio/cs43l22.c
drivers/audio/es8311.c
drivers/audio/es8388.c
drivers/audio/vs1053.c
drivers/audio/wm8904.c
drivers/audio/wm8994.c

use ac_controls.hw to get the correct sample rate intead of ac_controls.b

drivers/audio: fix samp rate conversion issue

---

arch/arm/src/common/Toolchain.defs

fix the build options warning that report by ghs compiler, the detailed warning info:
Warning: Unknown option "-fno-optimize-sibling-calls" ignored.  Did you mean "-mno-long-calls"?

greenhills support:  fix the build option warning

---

arch/risc-v/Kconfig
arch/risc-v/src/common/riscv_addrenv.c
arch/risc-v/src/common/riscv_exception.c
arch/risc-v/src/common/riscv_mmu.h

This PR configures the T-Head MMU to cache the the User Text, Data and Heap. We enable the MMU Flags for Shareable, Bufferable and Cacheable, as [explained in this article](https://lupyuen.github.io/articles/plic3#appendix-mmu-caching-for-t-head-c906).
This PR fixes the Slow Memory Access for NuttX Apps on BL808 and SG2000 SoCs: https://github.com/apache/nuttx/issues/12696. With this fix, SG2000 NuttX CoreMark jumps from 21 to 2,422. (Close to SG2000 Debian CoreMark)
We introduce a Kconfig Option: `ARCH_MMU_EXT_THEAD` ("System Type > Enable T-Head MMU extension support"). Enabling this Kconfig Option will configure the T-Head MMU to cache the User Text, Data and Heap.
This PR enables the MMU cache for only SG2000 SoC (Milk-V Duo S SBC). The next PR will apply the same settings to BL808 …

risc-v/mmu: Configure T-Head MMU to cache User Text, Data and Heap

---

arch/arm/include/armv6-m/irq.h
arch/arm/include/armv7-m/irq.h
arch/arm/include/armv8-m/irq.h
arch/arm/src/armv6-m/arm_svcall.c
arch/arm/src/armv7-m/arm_svcall.c
arch/arm/src/armv8-m/arm_svcall.c

In protected build mode, the syscall returns without setting correct value for the CONTROL register, which causes the userspace threads working in the privileged mode after syscall.

protected build: userspace threads will unexpectly work in privileged mode after syscall

---

arch/Kconfig
arch/arm64/Kconfig

Unify the elf file format for the whole arm64 architecture
Remove copy&paste
CI pass

arch/arm64: Move ELF_64BIT selection to arch/Kconfig

---

drivers/power/relay/relay.c

Fixed system function call failure due to return errcode error

nuttx/drivers:Modify errcode returned by relay_ioctl

---

CMakeLists.txt
libs/libc/wqueue/CMakeLists.txt

There are 2 CMake compile errors during the protected build mode. One is forget to add library for nuttx_user, another is the wrong macro used when compile wqueue.

CMake: fix CMake compile errors during the protected build mode

---

boards/risc-v/esp32c3-legacy/common/scripts/legacy_sections.ld
boards/risc-v/esp32c3-legacy/common/scripts/mcuboot_sections.ld
boards/risc-v/esp32c3/common/scripts/esp32c3_legacy_sections.ld
boards/risc-v/esp32c6/common/scripts/esp32c6_legacy_sections.ld
boards/risc-v/esp32h2/common/scripts/esp32h2_legacy_sections.ld
boards/xtensa/esp32/common/scripts/legacy_sections.ld
boards/xtensa/esp32/common/scripts/mcuboot_sections.ld
boards/xtensa/esp32/common/scripts/simple_boot_sections.ld
boards/xtensa/esp32s2/common/scripts/mcuboot_sections.ld
boards/xtensa/esp32s2/common/scripts/simple_boot_sections.ld
boards/xtensa/esp32s3/common/scripts/legacy_sections.ld
boards/xtensa/esp32s3/common/scripts/mcuboot_sections.ld

This commit ensures that RTC data is properly allocated in the RTC segment in the linker. This fixes the reported problem about using the legacy bootloader and RTC.
Fix the reported bug.
Internal CI testing + ESP32-S3 DevKitC-1 v1.0

espressif: Fix build with RTC

---

arch/arm64/src/imx9/imx9_usdhc.c

priv->rxbuffer does not exist when CONFIG_ARM64_DCACHE_DISABLE=y so references to it will create a build error -> flag / remove accesses to it.
Fix build error
Build passes
Also fix a few typos just for fun.

imx9_usdhc.c: Fix build error when CONFIG_ARM64_DCACHE_DISABLE=y

---

Documentation/Pipfile
Documentation/conf.py
Documentation/introduction/inviolables.rst
Documentation/introduction/resources.rst
Documentation/legacy_README.md

- Documentation: replace m2r2 with myst-parser
sphinx recommends myst-parser for markdown conversion: https://www.sphinx-doc.org/en/master/usage/markdown.html
m2r2 is not supported for Python versions >= 3.12 so we can't build Documentation for example on latest Arch Linux
by the way myst-parser detected a bad link to SECURITY.md that is now fixed
local build on Arch and python 3.12.3

Documentation: replace m2r2 with myst-parser

---

tools/ci/docker/linux/Dockerfile

Trying to reduce the size of the docker image, I found folders to be deleted.
- improved bloaty building.
- added rm -rf nuttx-tools
- added rm -rf renesas-tools
@xiaoxiang781216  @kassane For now, I have commented Swift from the  Dockerfile because the package is too large.
#13186
CI

tools/ci/docker/linux/Dockerfile: image cleaned of unnecessary folders

---

drivers/net/Kconfig
include/nuttx/net/ioctl.h
include/nuttx/net/netdev.h
net/netdev/CMakeLists.txt
net/netdev/Make.defs
net/netdev/netdev.h
net/netdev/netdev_notify_recvcpu.c
net/tcp/tcp.h
net/tcp/tcp_recvfrom.c
net/udp/udp.h
net/udp/udp_recvfrom.c

If the device supports RSS/ARFS functionality, the network protocol stack can enable NETDEV_RSS, then pass CPU ID and hash value of TCP/UDP packets to the hardware device for use.
The NETDEV_RSS macro is disabled by default, so it has no impact on the original process.
NA

support rss/arfs with device

---

tools/ci/testlist/arm-09.dat

CI: drop stm3240g-eval:knxwm for now
cf. https://github.com/apache/nuttx/issues/13246

CI: drop stm3240g-eval:knxwm for now

---

drivers/mtd/mtd_config_fs.c

when gc, move data requires byte alignment

mtd/nvs: fix align size

---

include/nuttx/wqueue.h
sched/wqueue/kwork_thread.c

These interfaces are used when we assign interrupt handling of the same priority to the corresponding priority work queues.
none
ostest

wqueue: add interface work_queue_priority_wq and work_queue_priority

---

arch/xtensa/src/esp32/esp32_spiram.c

esp32: cache_sram_mmu_set: update the correct register bits
tested on esp32-devkitc.
(no observable differences though)

esp32: cache_sram_mmu_set: update the correct register bits

---

arch/arm/src/armv8-r/arm_gicv3.c

armv8-r/gicv3: correct cpu index of irouter
interrupt routing cpu should be index not cpuset
N/A
ci-check

armv8-r/gicv3: correct cpu index of irouter

---

cmake/nuttx_kconfig.cmake

Fixing the correct .config path during the setconfig process.
changed ${NUTTX_DIR} -> ${CMAKE_BINARY_DIR}
see https://github.com/apache/nuttx/pull/13175#issuecomment-2320360957
@anchao It should now be corrected.
local

cmake/nuttx_kconfig.cmake: fixed the correct .config path in the buid folder

---

arch/xtensa/src/esp32/esp32_cpustart.c
arch/xtensa/src/esp32/esp32_spiram.c

NuttX uses PSRAM, possibly using the APP_CPU cache MMU, way before starting the APP_CPU in up_cpu_start(). Flushing the cache when launching the APP_CPU can cause data corruptions on PSRAM.
Eg. mm_heap structures if the PSRAM is added to a heap.
tested on esp32-devkitc with https://github.com/apache/nuttx/pull/13222 and some other local changes.

esp32: enable APP_CPU cache earlier

---

arch/risc-v/src/common/espressif/esp_hr_timer.c
arch/xtensa/src/esp32/esp32_rt_timer.c
arch/xtensa/src/esp32s3/esp32s3_rt_timer.c

* espressif: Fix deadlock in RT timer caused by critical section
This commit fixes a deadlock in `esp32s3-devkit:sta_softap` defconfig: `spin_lock_irqsave` was being used to enter a critical section that calls `nxsem_post`. In this case, it's recommended to use `[enter|leave]_critical_section` to avoid deadlocks when a context switch may happen, for instance.
Fix bug on `esp32s3-devkit:sta_softap`
Internal CI testing + ESP32-S3 DevKitC-1 v1.0

espressif: Fix deadlock in RT timer caused by critical section

---

tools/ci/docker/linux/Dockerfile

The docker image has not been updated we currently use that one from 25 days ago.
It seems that the error encountered is due to an incomplete download. It will probably work fine if downloaded again..
https://github.com/apache/nuttx/actions/runs/10619683045/job/29437799464#step:7:1339
28.31
28.31 gzip: stdin: unexpected end of file
28.31 tar: Unexpected EOF in archive
28.32 tar: Unexpected EOF in archive
28.32 tar: Error is not recoverable: exiting now
#13235
CI

tools/ci/docker/linux/Dockerfile: Restarting the Docker-Linux workflow

---

drivers/syslog/syslog_channel.c
fs/procfs/fs_procfsproc.c
libs/libc/time/lib_gmtime.c
sched/misc/assert.c

sched/policy: move g_policy from data to rodata
global/variables: add g_ prefix to some global variables
N/A
ci-check

sched/policy: move g_policy from data to rodata

---

sched/event/event_post.c

sched/event: clear pending events before enable the scheduler
enable the scheduler may cause the context to switch to a high-priority task,
which will failure to clear pending events correctly.
N/A
ci-check

sched/event: clear pending events before enable the scheduler

---

.github/workflows/docker_linux.yml
tools/ci/docker/linux/Dockerfile

tools/ci/docker/linux/Dockerfile
revert from --strip-components=1 to --strip-components 1
.github/workflows/docker_linux.yml
added -> workflow_dispatch:
Manual execution of a workflow
https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow
CI

tools/ci/docker/linux/Dockerfile: Restarting the Docker-Linux workflow a new attempt

---

sched/sched/sched_gettcb.c
sched/task/task_setup.c

When a large number of threads are created in SMP, malloc in nxtask_assign_pid may cause thread switching and create new threads. This may lead to accessing invalid pointers.

Fix task_setup race condition

---

drivers/usbdev/pl2303.c
drivers/usbdev/rndis.c

Fix the regression from https://github.com/apache/nuttx/pull/13190

rndis: correct usb descriptor

---

arch/arm/src/armv8-r/arm_gicv3.c
arch/arm64/src/common/arm64_gicv3.c

arm/gicv3: set routing affinity before enable IRQ
In corner case, the pending ISR will be triggered immediately
after enable the IRQ, this PR will setting CPU affinity first
to avoid routing the unexpected IRQ to other CPUs.
N/A
ci-check

arm/gicv3: set routing affinity before enable IRQ

---

arch/xtensa/src/esp32/esp32_psram.c

I have no idea what this setting is.
I'm just blindly trying to follow whatever esp-idf does.
the esp-idf counterpart:
https://github.com/espressif/esp-idf/blob/6e5414b6c4f265a0adfb56a15fbfbe6beb1f8373/components/esp_psram/esp32/esp_psram_impl_quad.c#L702-L712 https://github.com/espressif/esp-idf/blob/6e5414b6c4f265a0adfb56a15fbfbe6beb1f8373/components/esp_psram/esp32/esp_psram_impl_quad.c#L136-L147
tested on esp32-devkitc. (no noticeable behavior differences)

esp32: psram_set_cs_timing: sync with esp-idf

---

arch/Kconfig
sched/irq/irq.h
sched/irq/irq_attach.c

dynaminc create g_irqmap to reduce the use of data segments
CONFIG_ARCH_NUSER_INTERRUPTS should be one more than the number of IRQs actually used
none
ostest

irq: dynaminc create g_irqmap

---

tools/ci/docker/linux/Dockerfile

remove the leftover `wget` as curl is used
triggers a host not found on my machine

tools/ci/docker/linux/Dockerfile: fix cmake download

---

arch/xtensa/src/esp32/esp32_spiram.c
arch/xtensa/src/esp32/esp32_userspace.c

DPORT_APP_CACHE_MASK_DRAM1 is already a mask.
tested on esp32-devkitc.
the esp32_userspace.c bit is totally untested.

esp32: fix seemingly wrong calculations

---

arch/risc-v/include/syscall.h
arch/risc-v/src/common/CMakeLists.txt
arch/risc-v/src/common/Make.defs
arch/risc-v/src/common/riscv_exception.c
arch/risc-v/src/common/supervisor/CMakeLists.txt
arch/risc-v/src/common/supervisor/Make.defs
arch/risc-v/src/common/supervisor/riscv_perform_syscall.c
arch/risc-v/src/common/supervisor/riscv_sbi.c
arch/risc-v/src/common/supervisor/riscv_syscall.S

This reverts commit 6986cd4105 as it breaks critical section as shown by the test in [this comment](https://github.com/apache/nuttx/pull/12864#issuecomment-2325779041)
riscv
- local checks on `rv-virt:netnsh`
- checks by @tmedicci on esp32c6 targets
- CI checks

arch/riscv: revert pull#12864

---

Documentation/platforms/arm/stm32h7/boards/stm32h745i-disco/index.rst

Added STM32H745I-DISCO documentation for dual-core support.

doc: Add STM32H745I-DISCO dual-core documentation

---

arch/arm/src/armv6-m/arm_schedulesigaction.c
arch/arm/src/armv7-a/arm_schedulesigaction.c
arch/arm/src/armv7-m/arm_schedulesigaction.c
arch/arm/src/armv7-r/arm_schedulesigaction.c
arch/arm/src/armv8-m/arm_schedulesigaction.c
arch/arm/src/armv8-r/arm_schedulesigaction.c
arch/arm64/src/common/arm64_schedulesigaction.c
arch/ceva/src/common/ceva_schedulesigaction.c
arch/risc-v/src/common/riscv_schedulesigaction.c
arch/sparc/src/sparc_v8/sparc_v8_schedulesigaction.c
arch/x86_64/src/intel64/intel64_schedulesigaction.c
arch/xtensa/src/common/xtensa_schedsigaction.c

After the up_cpu_pause call completes, it guarantees that other CPUs have fully stopped.
none 
ostest
$ make

arch: remove unused up_cpu_pausereq waiting

---

arch/arm/src/armv8-r/arm_gicv3.c
arch/arm64/src/common/arm64_gicv3.c

arm/giv3: add g_ prefix to some global variables
N/A
ci-check

arm/giv3: add g_ prefix to some global variables

---

tools/ci/docker/linux/Dockerfile

Normally ccache places the temporary files in `~/.ccache`, when invoking the container with
`-u <uid>:<gid>`
as e.g. Jenkins does, this might result in a invalid/unknown home folder. Thus ccache tries to write to `/.ccache` which doesn't exist and the user doesn't have any permissions.
Explicitly set `CCACHE_DIR` to a folder with appropriate permissions.
Before:
```bash
cd /tmp
touch test.c
arm-none-eabi-gcc -c test.c
```

tools/ci/docker/linux/Dockerfile: fix ccache when running container as user

---

libs/libm/libm/lib_log.c
libs/libm/libm/lib_logf.c

Fix epsilon relaxation in `log` and `logf`.
Per description on how it should work:
```
To avoid looping forever in particular corner cases, every LOG_MAX_ITER the error criteria is relaxed by a factor LOG_RELAX_MULTIPLIER.
```
but actually as soon as first `LOG_MAX_ITER` number of cycles is reached the epsilon was getting doubled with each next cycle.
Improve native `libm`
Tried few cases, but needs more testing

libs/libm: fix epsilon relaxation in log and logf

---

arch/xtensa/src/esp32s3/esp32s3_qspi.c
arch/xtensa/src/esp32s3/esp32s3_qspi.h

When esp32s3 read from slave device through qspi, the data input signal has timing delay compared to clock signal, the higher the SPI frequency, the more impact to SPI sampling data, cause to receive wrong data.
esp32s3 has SPI timing compensation for this Scenario, add interface qspi driver to set timing compensation for the delay.
No impact
Build with esp32s3-devkit, test with project board.

xtensa/esp32s3: Add timing delay set interface for QSPI

---

tools/mksymtab.c

Make mksymtab.c to support C structure.
when I import a structure not a function, it can't be used.
[NAME],[HEADER],[COND],[RETTYPE],[PARM1]
if PARM1 is available, it is a function,
if not, it is a structure.
```
"kHAPAccessoryServerTransport_IP","../../apps/netutils/homekit/HomeKitADK/HAP/HAP.h","defined(CONFIG_NETUTILS_HOMEKIT)","const HAPIPAccessoryServerTransport"
```

mksymtab.c support for structure

---

sched/sched/sched_smp.c

smp call handler add up_cpu_paused_[save|restore]
Since smp call handler may lead to context switching, we need to update the context information by calling up_cpu_paused_[save|restore].
none
ostesting

smp: smp call handler add up_cpu_paused_[save|restore]

---

arch/arm/src/armv8-r/Toolchain.defs
arch/arm/src/cmake/armv8-r.cmake

armv8-r/r52: add neon support into compiler line
1. correct the armv8-r fpu flag from vfpv3-d16 to fpv5-sp-d16
2. add neon support
This commit updates the build script to specify the FPU type of
`fpv5-sp-d16` when the processor is configured with a single-precision
FPU, and `neon-fp-armv8` when the processor is configured with a
double-precision + Advanced SIMD-capable FPU.
Note that the `fp-armv8` FPU type is an alias for double-precision FPv5
with 32 double-precision registers (refer to the GCC
`gcc/config/arm/arm-cpus.in` for more details); NEON is always
specified in case of a double-precision configuration because the
Cortex-R52 can only be configured as such.
Reference:
https://developer.arm.com/Processors/Cortex-R52
Instruction set:
Arm and Thumb-2. Supports DSP instructions and a …

armv8-r/r52: add neon support into compiler line

---

net/can/can_recvmsg.c

Before we use pstate, we should check if it is NULL.
none
ostest

can: Before we use pstate, we should check if it is NULL.

---

tools/ci/docker/linux/Dockerfile

add install subversion to linux dockerfile
- tools/ci/docker/linux/Dockerfile
NA
NA

ci-docker: add subversion to linux dockerfile

---

sched/sched/sched_setaffinity.c

Make sure that affinity mask is valid
none
ostest

sched: add DEBUGASSERT to assure that affinity not zero

---

include/nuttx/spinlock.h

spin_initialize is often used to release a lock,
and if we don't include a memory barrier,
it may lead to the lock being released prematurely.
none
ostest

spinlock: spin_initialize should add memory barrier

---

arch/arm/src/armv7-a/arm_gicv2.c
arch/arm/src/armv7-r/arm_gicv2.c
arch/arm/src/armv8-r/arm_gicv3.c
arch/arm/src/cxd56xx/cxd56_cpupause.c
arch/arm/src/lc823450/lc823450_cpupause.c
arch/arm/src/rp2040/rp2040_cpupause.c
arch/arm/src/sam34/sam4cm_cpupause.c
arch/arm64/src/common/arm64_gicv2.c
arch/arm64/src/common/arm64_gicv3.c
arch/risc-v/src/common/riscv_cpupause.c
arch/sim/src/sim/posix/sim_hostirq.c
arch/sim/src/sim/posix/sim_hostsmp.c
arch/sim/src/sim/sim_internal.h
arch/sim/src/sim/sim_smpsignal.c
arch/sparc/src/s698pm/s698pm_cpupause.c
arch/x86_64/src/intel64/intel64_cpupause.c
arch/xtensa/src/common/xtensa_cpupause.c
arch/xtensa/src/esp32/esp32_intercpu_interrupt.c
arch/xtensa/src/esp32s3/esp32s3_intercpu_interrupt.c
include/nuttx/arch.h
include/nuttx/sched.h
sched/Kconfig
sched/sched/CMakeLists.txt
sched/sched/Make.defs

reason:
enable smp_call in all smp arch
In subsequent implementations, we will replace up_cpu_pause with smp_call.
none
ostest

smp: enable smp_call in all smp arch

---

arch/arm/src/nrf91/CMakeLists.txt
include/pthread.h
sched/pthread/pthread.h
sched/pthread/pthread_condclockwait.c
sched/pthread/pthread_condwait.c
sched/pthread/pthread_mutex.c
sched/pthread/pthread_mutexconsistent.c
sched/pthread/pthread_mutexdestroy.c
sched/pthread/pthread_mutexinconsistent.c
sched/pthread/pthread_mutexinit.c
sched/pthread/pthread_mutextimedlock.c
sched/pthread/pthread_mutextrylock.c
sched/pthread/pthread_mutexunlock.c

Since pthread_mutex is implemented by sem, it is impossible to see in ps who holds the lock and causes the wait.
Replace semaphore with mutex implementation to solve the above problems
It depends on https://github.com/apache/nuttx/pull/13104
ostest & ltp

sched: change pthread_mutex implementation from sem to mutex

---

drivers/mmcsd/mmcsd_sdio.c

In some usage scenarios, read and write tasks will be performed during interruptions. If sleep is used at this time, it will cause a timeout crash. Therefore, a macro is added to determine whether it is currently interrupted to select sleep/delay.
Replace nxsig_usleep with up_udelay in interrupts in mmcsd_sdio.c

mmcsd_sdio:Fix performing read and write in irq

---

fs/hostfs/hostfs.c

The strcpy function is dangerous because it does not check the length of the
ci

fs/hostfs: Replace strcpy with memcpy

---

boards/Kconfig
boards/boardctl.c
include/sys/boardctl.h
libs/libc/pthread/Kconfig
libs/libc/pthread/pthread_spinlock.c

BOARDIOC_SPINLOCK can support the combined semantics of disabling interrupts (irq), trylock, and spinlock.
none
ostest

boardcrtl: change BOARDCTL_TESTSET to BOARDIOC_SPINLOCK

---

libs/libm/libm/lib_log.c
libs/libm/libm/lib_logf.c

The previous attempt to fix `log` and `logf` operation in https://github.com/apache/nuttx/pull/13294 was wrong.
This is a second attempt that reverts previous change and applied relaxation only if `epsilon` calculation is evaluated to `DBL_EPSILON`/`FLT_EPSILON` case.
Should fix https://github.com/apache/nuttx/issues/13286
Tested few value returned by Nuttx libm `log` and compared with values returned by compiler version of `log`.

libs/libm/libm: apply epsilon relax factor only if epsilon is small

---

include/nuttx/irq.h
sched/Kconfig
sched/irq/CMakeLists.txt
sched/irq/Make.defs
sched/irq/irq_attach_wqueue.c

irq with the same priority share the same wqueue
reason:
1 We place interrupt handling functions of the same priority into the work queue corresponding
to that priority, allowing high-priority interrupts to preempt low-priority ones,
thus ensuring the real-time performance of high-priority interrupts.    
2 The sole purpose of the interrupt handler is to wake
up the work queue of the corresponding priority and execute the interrupt handling function.    
3 Compared to the functionality of isr threads, this
approach saves more memory, particularly when the number of interrupts is large.
OS Real-time Capability
ostest

irq: irq with the same priority share the same wqueue

---

include/nuttx/lin.h
include/nuttx/net/net.h

Add lin.h adn lin bus-type
Add lin.h for socket lin.
New feature
Write LIN master and slave programs, flash them to two development boards respectively, and test LIN transceiver business.

socketlin : add lin.h and lin bus-type

---

arch/x86_64/Kconfig
arch/x86_64/src/intel64/intel64_head.S

Activating the CONFIG_ARCH_PVHBOOT configuration enables the loading of the nuttx.elf binary using the QEMU -kernel command-line option.
This change facilitates the direct booting of the NuttX operating system within a QEMU virtual machine, enhancing development and testing workflows for the x86_64 architecture.
The functionality has been verified on an x86_64 Ubuntu 22.04 machine. NuttX can be successfully booted using the following command: `sudo qemu-system-x86_64 -enable-kvm -cpu host -m 2G -kernel nuttx.elf -nographic -serial mon:stdio`.

arch/x86_64: Support QEMU PVH ELF loader

---

boards/x86_64/intel64/qemu-intel64/scripts/qemu.ld

- qemu-intel64: simplify linker script
simplify linker script for qemu-intel64 - remove not needed AT instructions
qemu-intel64/nsh

qemu-intel64: simplify linker script

---

arch/x86_64/include/intel64/irq.h

RDTSCP instruction reads the current value of the processor’s time-stamp counter (a 64-bit MSR) into the EDX:EAX registers, and it also reads the value of the IA32_TSC_AUX MSR (address C0000103H) into the ECX register. However, the current RDTSCP implementation does not provide a hint for the compiler that ECX has been changed, resulting in register corrupted and subtle errors.
Bug Fixed.

arch/x86_64: Fix wrong RDTSCP implementation

---

arch/xtensa/src/common/xtensa_swint.c

```
common/xtensa_swint.c:442:24: error: passing argument 1 of 'up_dump_register' discards 'volatile' qualifier from pointer target type [-Werror=discarded-qualifiers]
442 |       up_dump_register(CURRENT_REGS);
|                        ^~~~~~~~~~~~
```
Tested on esp32-devkitc

xtensa: Appease a GCC warning

---

arch/x86_64/include/intel64/io.h
arch/x86_64/include/intel64/irq.h
arch/x86_64/include/irq.h
arch/x86_64/src/intel64/intel64_cache.c
arch/x86_64/src/intel64/intel64_check_capability.c
arch/x86_64/src/intel64/intel64_cpu.c
arch/x86_64/src/intel64/intel64_freq.c
arch/x86_64/src/intel64/intel64_handlers.c
arch/x86_64/src/intel64/intel64_idle.c
arch/x86_64/src/intel64/intel64_initialstate.c
arch/x86_64/src/intel64/intel64_regdump.c
arch/x86_64/src/intel64/intel64_systemreset.c
arch/x86_64/src/intel64/intel64_tsc_tickless.c
arch/x86_64/src/intel64/intel64_tsc_timerisr.c

- arch/x86_64: convert all `asm()` to `__asm__()`
asm() is not supported by -std=c99
depends on https://github.com/apache/nuttx/pull/13317
CI

arch/x86_64: convert all asm() to __asm__

---

boards/arm/stm32/common/include/stm32_amg88xx.h
boards/arm/stm32/common/src/CMakeLists.txt
boards/arm/stm32/common/src/Make.defs
boards/arm/stm32/common/src/stm32_amg88xx.c
boards/arm/stm32/nucleo-f429zi/src/stm32_appinitialize.c
drivers/sensors/CMakeLists.txt
drivers/sensors/Kconfig
drivers/sensors/amg88xx.c
include/nuttx/sensors/amg88xx.h
include/nuttx/sensors/ioctl.h

New driver for [amg88xx](https://industrial.panasonic.com/cdbs/www-data/pdf/ADI8000/ADI8000C66.pdf) sensor with basic capabilities.
Currently supports the following ioctl commands:
*SNIOC_SET_OPERATIONAL_MODE* : toggles sleep mode
*SNIOC_SET_FRAMERATE* : toggles between 1 and 10 fps.
*SNIOC_SET_MOVING_AVG* : unique to this sensor, sets moving average, for more details check sensor datasheet
For the moment the sensor interrupt functionality is missing, this driver supports getting data from the sensor in pooling mode.
Small changes for nucleo-f429zi board config to enable the sensor driver.
Locally, with an example app which is part of nuttx-apps and logic analyzer.

Add amg88xx driver

---

include/nuttx/irq.h
sched/irq/irq_csection.c
sched/mqueue/mq_receive.c
sched/mqueue/mq_timedreceive.c
sched/mqueue/mq_timedsend.c
sched/semaphore/sem_clockwait.c
sched/semaphore/sem_tickwait.c
sched/semaphore/sem_wait.c

In some non-irq scenarios, we can simplify
the implementation of critical sections to improve performance.
$ make

irq: add [enter|leave]_critical_section_nonirq

---

sched/sched/sched_setpriority.c

If the type of tcb is TSTATE_TASK_ASSIGNED, removing it using nxsched_remove_not_running and then putting it back into the queue may result in a context switch.
```
$ make
```

sched/sched: simplify the implementation of the function nxsched_readytorun_setpriority

---

drivers/bch/bchlib_read.c
drivers/bch/bchlib_write.c
drivers/mtd/filemtd.c
include/nuttx/drivers/drivers.h
include/nuttx/mtd/mtd.h

drivers/mtd/bch: fix size_t overflow when offset > 4GB
Bug Fix
Vela

drivers/mtd/bch: fix size_t overflow when offset > 4GB

---

fs/inode/fs_inoderelease.c
fs/inode/fs_inoderemove.c
fs/inode/fs_inodereserve.c
fs/mount/fs_mount.c
fs/mqueue/mq_open.c
fs/mqueue/mq_unlink.c
fs/semaphore/sem_close.c
fs/semaphore/sem_open.c
fs/semaphore/sem_unlink.c
fs/shm/shm_open.c
fs/shm/shm_unlink.c
include/nuttx/fs/fs.h

fs/inode: using inode reference to indicate unlink and simply code 
Change inode i_crefs's initial value to 1, and release inode resource when i_crefs is zero.
Remove inode flags: FSNODEFLAG_DELETED
Vela

fs/inode: using inode reference to indicate unlink and simply code 

---

sched/group/group_setuptaskfiles.c
sched/init/nx_start.c
sched/sched/sched.h

sched/group/setuptask_file: duplicate idle task fd for kernel thread.
The file descriptors of kernel threads should be clean and should not be generated based on user threads. Instead, an idle thread hould be chosen.
Clean the file descriptors of kernel threads 
Vela

sched/group/setuptask_file: duplicate idle task fd for kernel thread

---

libs/libc/netdb/Kconfig
libs/libc/netdb/lib_dnsaddserver.c
libs/libc/netdb/lib_dnsforeach.c

prevent the server list in resolv.conf from increasing indefinitely. 
the one that is overwritten is always the one configured first.
sim:local

netdb: Make NETDB_DNSSERVER_NAMESERVERS effective for NETDB_RESOLVCONF

---

drivers/spi/spi_slave_driver.c

Revert "Fix unwanted flush in the SPI slave driver"
Because if priv->rx_length is zero , need to call SPIS_CTRLR_QPOLL to receive new data from lower half and update priv->rx_length.
This reverts commit 6cb649ecf6d537383eadb71a8a7ce780959ee8ad.
Bug fix for spislave read
Vela

Revert "Fix unwanted flush in the SPI slave driver"

---

fs/procfs/fs_procfs.c
fs/smartfs/smartfs_procfs.c

If we activate SMARTFS and go to _/proc/fs/smartfs_, we will get a kernel panic:
[dump.txt](https://github.com/user-attachments/files/16936111/dump.txt)
In it we will see _smartfs_dup: Dup 0x3fc8ce1e->0x3fc8c8d0_, the **smartfs_dup** function was called, but not from _smartfs_proc.c_, but from _smartfs_smart.c_
The 'g_smartfs_operations'
`extern const struct mountpt_operations g_smartfs_operations;` was declare into:
- fs/mount/fs_mount.c
- fs/procfs/fs_procfs.c
The function **g_smartfs_operations** was renamed to **g_smartfs_procfs_operations** into file _fs/procfs/fs_procfs.c_.
`cd /proc/fs/smartfs`
and
`cat status`

smartfs procfs: fix double declare g_smartfs_operations

---

audio/CMakeLists.txt
audio/Makefile
audio/audio.c
audio/audio_comp.c
audio/pcm_decode.c

Most tools used for compliance and SBOM generation use SPDX identifiers.
This change brings us a step closer to an easy SBOM generation.
Compliance
NONE

audio: migrate to SPDX identifier

---

cmake/menuconfig.cmake
cmake/nuttx_add_application.cmake
cmake/nuttx_add_dependencies.cmake
cmake/nuttx_add_library.cmake
cmake/nuttx_add_module.cmake
cmake/nuttx_add_romfs.cmake
cmake/nuttx_add_subdirectory.cmake
cmake/nuttx_add_symtab.cmake
cmake/nuttx_allsyms.cmake
cmake/nuttx_create_symlink.cmake
cmake/nuttx_export_header.cmake
cmake/nuttx_generate_headers.cmake
cmake/nuttx_generate_outputs.cmake
cmake/nuttx_kconfig.cmake
cmake/nuttx_mkconfig.cmake
cmake/nuttx_mkversion.cmake
cmake/nuttx_parse_function_args.cmake
cmake/nuttx_redefine_symbols.cmake
cmake/nuttx_sethost.cmake
cmake/nuttx_source_file_properties.cmake
cmake/savedefconfig.cmake
cmake/symtab.c.in

Most tools used for compliance and SBOM generation use SPDX identifiers 
This change brings us a step closer to an easy SBOM generation.
SBOM
CI

cmake: migrate to SPDX identifier

---

drivers/pipes/pipe_common.c
fs/vfs/fs_fcntl.c
include/fcntl.h
include/nuttx/fs/ioctl.h
net/local/local.h
net/local/local_conn.c
net/local/local_connect.c
net/local/local_fifo.c
net/local/local_recvmsg.c
net/local/local_sendmsg.c
net/local/local_sendpacket.c
net/local/local_sockif.c

allows user programs to modify pipe size via fcntl(F_SETPIPE_SZ), but not larger than CONFIG_DEV_PIPE_MAXSIZE,
lets a user program modify the size of the local_socket buffer via setsockopt(SO_SNDBUF/SO_RCVBUF).
sim:local

local_socket: add SO_SNDBUF & SO_RCVBUF support

---

drivers/virtio/virtio-blk.c

Coredump need call the block read/write ops in interrupt Not consider the ops called in thread and intterupt simultaneously. Only used for coredump now.
New feature
qemu armv7a with coredump blkdev

virtio-blk: support called read/write in interrupt

---

arch/arm/src/kinetis/kinetis_enet.c
arch/arm/src/lpc17xx_40xx/lpc17_40_ethernet.c
arch/arm/src/lpc54xx/lpc54_ethernet.c
arch/arm/src/rtl8720c/amebaz_netdev.c
arch/mips/src/pic32mx/pic32mx_ethernet.c
arch/misoc/src/common/misoc_net.c
arch/risc-v/src/litex/litex_emac.c
drivers/net/enc28j60.c
drivers/net/netdev_upperhalf.c
drivers/net/tun.c
drivers/net/w5500.c
include/nuttx/net/netdev.h
net/netdev/netdev_stats.c
net/procfs/netdev_statistics.c

- net/netstatistics: add tx/rx bytes statistics for dev
- netdev/statistics: Add bytes for netdev statistics log
We can see them in ifconfig:
```
ap> ifconfig
wlan0   Link encap:Ethernet HWaddr 42:64:7f:b3:12:03 at UP mtu 1500
inet addr:10.0.1.2 DRaddr:10.0.1.1 Mask:255.255.255.0
inet6 DRaddr: ::
RX: Received Fragment Errors   Bytes
00000b9b 00000000 00000000 21daf5
IPv4     IPv6     ARP      Dropped
00000a33 00000137 00000031 00000000
TX: Queued   Sent     Errors   Timeouts Bytes
00000ac4 00000ac4 00000000 00000000 1a2103
Total Errors: 00000000
```
Now the periodic log looks like:
```
wlan0:T2758/2758(1712845B),R(2613+311)/2973(2219171B) ...
```
Add bytes for netdev statistics.
Manually, like examples above.

netdev/statistics: Add bytes for netdev statistics

---

arch/arm/src/xmc4/xmc4_spi.c

The input stage DX0 is used for MISO signal. The register DX0CR select the pinmux input signal (DX0A, DX0B, ..., DX0G).
Currently only one input signal was possible for all active SPI channel due to global BOARD_SPI_DX define. 
I added the suport for individual BOARD_SPIx_DX for each SPI channel. 
```
/* USIC1 CH0 is used as SPI2
*
*  MOSI - P0.5
*  MISO - P0.4
*  SCLK - P0.11
*/
#define BOARD_SPI2_DX USIC_DXA
#define GPIO_SPI2_MOSI (GPIO_U1C0_DOUT0_2 | GPIO_PADA2_STRONGMEDIUM | GPIO_OUTPUT_CLEAR)
#define GPIO_SPI2_MISO (GPIO_U1C0_DX0A)
#define GPIO_SPI2_SCLK (GPIO_U1C0_SCLKOUT_1 | GPIO_PADA2_STRONGMEDIUM)
```
It is retro-compatible with previous BOARD_SPI_DX define, so old code won't break. 
Tested on custom XMC4800 board.

arch/xmc4 : Add input pin DX0 selection for multiple SPI channel

---

tools/ci/docker/linux/Dockerfile

Add subversion to install list ensure linux docker can use svn command to download source code.
Add subversion to final images
NA
NA

Dockerfile: add subversion to final images

---

arch/risc-v/src/litex/litex_irq_dispatch.c
arch/risc-v/src/litex/litex_serial.c

Fix a couple of regressions in the litex:arty_a7 build.
- Fixes a failing build, due to missing `nuttx/spinlock.h`
- Fixes a warning produced by the out of date `uintptr_t` type used.
Building with the `arty_a7:knsh` configuration.

arch/risc-v/litex: Fix the litex arty_a7 build

---

fs/inode/fs_files.c
include/nuttx/fs/fs.h
sched/group/group_leave.c

fs/inode: add reference to protect filelist of group
Before this PR, when we perform a reboot command, the sync() function is called to synchronize all the file descriptors (fds) of tasks. 
**However, if there are tasks exiting at this time, it can lead to the issue of file handles being used after they have been freed. Therefore, we need to add references (refs) to protect this list from being released.**
protect filelist.
Vela

group/filelist: add reference to protect filelist of group

---

drivers/misc/rwbuffer.c

drivers/rwbuffer: Set nblocks 0 after direct using wrflush(skip rwbuffer)
improve rwbuffer write performance.
Vela

drivers/rwbuffer: Bug fix: Set nblocks 0 after direct using wrflush

---

mm/kasan/CMakeLists.txt

This enables CMake based build for sim:ostest. Flags which are set by set_source_files_properties are not reflected in final build. Changing these to target_compile_options makes CMake build runnable.
CMake based build for sim:ostest now runs.
Local build and playing around sim:ostest

build: fix memory manager compile options for CMake

---

openamp/CMakeLists.txt
openamp/Makefile
openamp/libmetal.cmake
openamp/libmetal.defs
openamp/open-amp.cmake
openamp/open-amp.defs

Most tools used for compliance and SBOM generation use SPDX identifiers This change brings us a step closer to an easy SBOM generation.
SBOM
CI

openamp: migrate to SPDX identifier

---

arch/arm64/src/common/arm64_vector_table.S

The expression "sub    x0,  x0, #8 * XCPTCONTEXT_GP_REGS" is void,
as the next instruction overwrites x0 anyway.
Remove dead code
CI pass

arm64_vector_table.S: Remove unnecessary instruction

---

arch/arm64/src/common/arm64_addrenv.c

Make sure the user L1 page is updated to system memory when the kernel mappings are copied.
Also, flush the I-cache when switching address environments.
Fix potential cache issue when making copy of kernel page tables
CI Pass

arm64_addrenv.c: Flush kernel page table copy to user mappings

---

arch/arm64/src/common/crt0.c

The stack alignment requirement is 16-bytes, not 8-bytes.
Fix bug in ARM64 crt0

arm64/crt0.c: Fix stack alignment when executing signal trampoline

---

video/CMakeLists.txt
video/Makefile
video/videomode/CMakeLists.txt
video/videomode/Make.defs
video/videomode/edid_dump.c
video/videomode/edid_parse.c
video/videomode/vesagtf.c
video/videomode/videomode_dump.c
video/videomode/videomode_lookup.c
video/videomode/videomode_sort.c

Most tools used for compliance and SBOM generation use SPDX identifiers This change brings us a step closer to an easy SBOM generation.
SBOM
CI

video: migrate to SPDX identifier

---

arch/risc-v/Kconfig
arch/risc-v/src/common/riscv_exception_common.S
arch/risc-v/src/common/riscv_initialstate.c
arch/risc-v/src/common/riscv_internal.h
arch/risc-v/src/common/riscv_saveusercontext.S

This patch unifies the extended context save/restore for RISC-V, allowing the customized context save/restore to be used, for example, the extended context in rv32m1.
Minor
Notice: I can apply the changes to rv32m1, but I don't have such board to verify it, so leave it unchanged for now.

riscv: Unify the extended context save/restore

---

arch/arm64/include/irq.h
arch/arm64/src/common/arm64_vectors.S

Use SPSR_ELx value to determine whether interrupts need to be re-enabled when running user system call
User system calls only
- qemu-armv8a:knsh
- downstream imx9 target with kernel mode

 arm64/syscall: (Re-)enable interrupts only if they were previously enabled

---

arch/arm64/include/irq.h
arch/arm64/src/common/arm64_initialstate.c
arch/arm64/src/common/arm64_pthread_start.c
arch/arm64/src/common/arm64_task_start.c

There is a tiny possibility that when a process is started a trap is taken which causes a context switch. This moves the kernel stack unexpectedly and the task start logic no longer works.
Fix this by recording the initial context location, and use that to trampoline into the user process with interrupts disabled. This ensures the context stays intact AND the kernel stack is fully unwound before the user process starts.
Fixes a rare crash when a task / process is starting
- qemu-armv8a:knsh
- downstream imx9 target with kernel mode

arm64/task/pthread_start: Fix rare issue with context register location

---

syscall/CMakeLists.txt
syscall/Makefile
syscall/proxies/CMakeLists.txt
syscall/proxies/Make.defs
syscall/stubs/CMakeLists.txt
syscall/stubs/Make.defs
syscall/syscall_names.c
syscall/syscall_stublookup.c
syscall/syscall_wraps.h
syscall/wraps/CMakeLists.txt
syscall/wraps/Make.defs

Most tools used for compliance and SBOM generation use SPDX identifiers This change brings us a step closer to an easy SBOM generation.
SBOM
CI

syscall: migrate to SPDX identifier

---

arch/risc-v/src/litex/litex_irq_dispatch.c

Attempt to service all interrupts pending in the PLIC's claim register. Ideally, this is more efficient than switching context for each interrupt received.
Slightly better performance under heavy interrupt loading.
Custom platform -  application with around 2000 interrupts / second.
`arty_a7:knsh` - builds and runs.

arch/risc-v/src/litex: Claim all pending PLIC interrupts.

---

net/ipfrag/ipfrag.c

ipfrag/ipfraq.c: In function 'ip_fragin_timerwork':
ipfrag/ipfrag.c:314:44: warning: 'interval' may be used uninitialized in this function [-Wmaybe-uninitialized]314if (delay < REASSEMBLY_TIMEOUT_TICKS - interval)

ipfrag:fix warnig

---

drivers/serial/uart_pl011.c

serial/uart_pl011: default syslog needs to check flow control in up_putc
default syslog needs to check flow control in up_putc(), otherwise
up_puts() will lose character if the hardware fifo is full.
N/A
ci-check

serial/uart_pl011: default syslog needs to check flow control in up_putc

---

arch/arm64/Kconfig
arch/arm64/src/common/arm64_arch.h

Enforcing the default 48-bit VA for everyone also implies a 4 page table translation system. However, if less than 40 bits are needed, a full translation table level can be dropped, making the translations faster.
Thus, make this into a configurable option, instead of enforcing the same address widht for everyone.
Make it possible to define the VA range per target, instead of a global value
CI pass
The main motivation for doing this is to provide an option to drop page table levels from the translation table walk. Using more than 39 bits enforces using all 4 page table levels, making the translations slower due to the longer table walk.
Many users could be fine with much less than 48 bits, so let's not enforce this.

arm64/Kconfig: Make the ARM64_PA/VA_BITS a true Kconfig variable

---

drivers/pci/CMakeLists.txt

cmake: add support for PCI
PCI framework can be build with cmake
local build and CI

cmake: add support for PCI

---

drivers/serial/uart_16550.c

serial/uart_16550: remove up_putc spinlock
putc atomicity should be guaranteed by common code rather than add similar hack to lower half driver
N/A
ci-check

serial/uart_16550: remove up_putc spinlock

---

arch/arm64/src/imx9/imx9_lowputc.c
arch/arm64/src/imx9/imx9_lowputc.h

- Small typo / copy-paste error fixes for imx9 lpuart driver
- Enable calling initialization function from C++ (PX4) code
Only on IMX9
Tested on a custom i.MX93 based HW

imx9 / LPUART fixes

---

arch/arm64/src/imx9/imx9_lpi2c.c

Clean up the interrupt-driven logic in the driver; handle error cases properly, remove dead code and simplify logic.
This is a small refactor and cleanup for imx9 lpi2c driver, which was originally copied from imxrt.
This fixes several issues with imx9 lpi2c driver. In particular,
- The original driver had some race conditions with irq handling logic
- The original driver didn't work with some longer message sequences
Tested on a custom i.MX93 hardware with several i2c devices on several busses.

arch/arm64/src/imx9/imx9_lpi2c.c: Cleanups and error fixes

---

libs/libc/misc/Kconfig
libs/libc/misc/lib_crc32.c

For the very small flash/ram chip, crc32 table is not prefer, and we current don't have option to disable crc32 table.
No inpact for default case.
Optional enable crc32 slow to disable crc32 table.
CI-test, Cortex-M33 board.

libc/misc/crc32: crc32 add slow mode, optional decrease size

---

arch/x86_64/src/common/Kconfig
arch/x86_64/src/intel64/intel64_idle.c

Using the HLT instruction in VM usually traps into the Hypervisor and releases CPU control. This will result in real-time performance degradation. Using the NOP or MWAIT instruction for an IDLE loop can reduce energy consumption while not trapping into the Hypervisor.
Avoid VM Exit.
Tested on x86 NUC12 and x86 QEMU.

arch/x86_64: Add ARCH_X86_64_IDLE_NOP and ARCH_X86_64_IDLE_MWAIT

---

arch/arm64/src/imx9/Kconfig
arch/arm64/src/imx9/hardware/imx93/imx93_ccm.h
arch/arm64/src/imx9/hardware/imx9_blk_ctrl.h
arch/arm64/src/imx9/imx9_ccm.c
arch/arm64/src/imx9/imx9_enet.c

This is a collection of imx9 ethernet fixes:
- Allow configuring of ethernet reflock direction; this is needed for RMII designs
- Configure ethernet clock to 125MHz
IMX9 only
Tested on a custom i.MX93 board with RMII PHY

Imx9 ethernet fixes

---

arch/arm64/src/imx9/Make.defs
arch/arm64/src/imx9/imx9_boot.c
arch/arm64/src/imx9/imx9_system_ctl.c
arch/arm64/src/imx9/imx9_system_ctl.h

System reset conttoller to powercycle ml and media blocks and disable power-isolation
Adds supporting functions for system reset controller
Only for imx9
Functions tested on a custom i.MX93 board

arch/arm64/imx9: Add system reset controller

---

arch/risc-v/src/common/riscv_mtimer.c

riscv_mtimer: modify riscv_mtimer_current to reduce precision lost
riscv timer

riscv_mtimer: modify riscv_mtimer_current to reduce precision lost

---

include/sys/mman.h

This commit add MADV_HUGEPAGE and MADV_NOHUGEPAGE definitions for madvise. Notice that none of these flags have been implemented yet.
Improve compatibility with C programs for Linux.
Tested on QEMU.

fs/mmap: Add MADV_HUGEPAGE definitions

---

fs/mmap/fs_mmap.c
include/sys/mman.h

According to the mmap(2) specification, anonymous pages should be initialized to zero unless the MAP_UNINITIALIZED is specified.
Anonymous memory allocated by mmap without MAP_UNINITIALIZED will be initialized to zero.
Tested on x86_64 QEMU and x86_64 NUC12.

fs/mmap: Ensure anonymous pages are initialized to zero

---

include/nuttx/streams.h
libs/libc/stream/lib_syslograwstream.c

stream/syslograw: remove support for iob buffer in syslog
IOB buffer participates in the calculation of the congestion strategy in the protocol stack, if the iob buffer is exhausted or there are too many syslog printing tasks, the behavior of the protocol stack and log printing will unable to determined, this PR will remove support for iob buffer in syslog
N/A
ci-check

stream/syslograw: remove support for iob buffer in syslog

---

drivers/video/fb.c
include/nuttx/video/fb.h

Some devices need to clear the fb panbuf when waking up from sleep to 
avoid outputting residual buffers from before sleeping
framebuffer driver
ci-test

drivers/fb: add panbuffer clear ioctl

---

arch/x86_64/include/irq.h
arch/x86_64/src/common/x86_64_pci.c
arch/x86_64/src/intel64/intel64_irq.c
drivers/pci/Kconfig
drivers/pci/pci.c
drivers/pci/pci_qemu_edu.c
include/nuttx/pci/pci.h
include/nuttx/pci/pci_regs.h

-  drivers/pci: add MSI/MSI-X support 
Add support for MSI and MSI-X in PCI framework
-  arch/x86_64/intel64: add MSI/MSI-X support
Add MSI and MSI-X support for intel64
-  drivers/pci_qemu_edu: add MSI test
Add simple MSI test for QEMU PCI EDU device so we can verify if MSI works correctly
Tested with QEMU and PCI EDU device:
```
qemu-system-x86_64 -m 2048M -cpu host -enable-kvm -kernel nuttx.elf -nographic -serial mon:stdio -device edu -device pci-testdev
```
QEMU EDU device MSI test fragment:
```
pci_qemu_edu_probe: MSI TEST
pci_qemu_edu_probe: MSI TEST: Attaching MSI 64 to 0x100917277
pci_qemu_edu_test_intx: Identification: 0x010000edu
pci_qemu_edu_test_intx: Triggering interrupt with value 0xdeadbeef
pci_qemu_edu_interrupt: Received value: 0xdeadbeef
pci_qemu_edu_test_intx: TEST PASS …
```

Add MSI/MSI-X support for intel64

---

drivers/spi/spi_slave_driver.c
include/nuttx/spi/slave.h

spi_slave: keep consistent with the parameter of the spi_slave_receive function declaration
CODE size_t   (*receive)(FAR struct spi_slave_dev_s *sdev, FAR const void *data, size_t nwords);
spi slave

spi_slave: change length to nwords

---

.github/workflows/build.yml

This PR modifies NuttX CI and GitHub Actions, to comply with ASF Policy. Right now, every NuttX Pull Request will trigger 24 Concurrent Jobs (GitHub Runners), executing them in parallel: https://lupyuen.github.io/articles/ci
According to ASF Policy: We should run at most 15 Concurrent Jobs: https://infra.apache.org/github-actions-policy.html
Thus we'll cut down the Concurrent Jobs from 24 down to 15. That's 12 Linux Jobs, 2 macOS, 1 Windows. (Each job takes 30 mins to 2 hours)
(1) Right now our "Linux > Strategy" is a flat list of 20 Linux Jobs, all executed in parallel...
```yaml
matrix:
boards: [arm-01, arm-02, arm-03, arm-04, arm-05, arm-06, arm-07, arm-08, arm-09, arm-10, arm-11, arm-12, arm-13, other, risc-v-01, risc-v-02, sim-01, sim-02, xtensa-01, xtensa-02]
```
(2) We change …

build.yml: Limit the GitHub Runners

---

include/pthread.h
include/sys/mman.h
include/sys/resource.h
libs/libc/unistd/lib_getrlimit.c

Added dummy implementations for `shm_open` and `shm_unlink`.
Added a dummy implementation for `pthread_setaffinity_np` when `CONFIG_SMP` is disabled.
Added definitions for `RLIMIT_RTPRIO` and `RLIMIT_RTTIME`.
Dummy implementations for `shm_open` and `shm_unlink` are now available.
`pthread_setaffinity_np` is supported in configurations with `CONFIG_SMP` disabled.
`RLIMIT_RTPRIO` and `RLIMIT_RTTIME` are now defined.
Tested on x86 QEMU and NUC12.

Add dummy implementations for `shm_open` `pthread_setaffinity_np` and `RLIMIT_RTPRIO`

---

arch/arm64/src/imx9/imx9_lpi2c.c

Check remaining data count, just in case an extra RX interrupt occurs after receiving a message
This was left out of previous imx9 i2c fixes. It is better to always check the data counter before writing to receive buffer. A spurious interrupt after a receive would cause memory corruption.
Imx9 I2C only
Tested on a custom IMX93 board

arch/arm64/src/imx9/imx9_lpi2c.c: Ignore spurious RX interrupts

---

arch/x86_64/include/hpet.h
arch/x86_64/src/intel64/Kconfig
arch/x86_64/src/intel64/intel64_hpet.c
arch/x86_64/src/intel64/intel64_oneshot.c

- arch/intel64/hpet: add FSB interrupts support and support for 32-bit mode   
These are changes to make HPET work with ACRN hypervisor:
- FSB interrupt delivery (which works like PCI MSI)
- 32-bit mode support
[DONE] Depends on https://github.com/apache/nuttx/pull/13391
intel HW

intel64: Improvements for HPET

---

arch/x86_64/src/intel64/intel64_oneshot_lower.c

arch/x86_64/intel64: fix compilation errors in intel64_oneshot_lower.c
clock_time2ticks and clock_ticks2time macros changes but this file was not update
local compilation with HPET enabled

arch/x86_64/intel64: fix compilation errors in intel64_oneshot_lower.c

---

.gitignore
arch/x86_64/Kconfig
arch/x86_64/src/Makefile
arch/x86_64/src/common/multiboot1.S
arch/x86_64/src/common/multiboot1.ld

The NuttX x86 architecture has previously supported multiboot2. However, it was discovered that attempting to load x86-64 format ELF files with a multiboot2 header using the qemu `-kernel` command would result in an error. multiboot1 is suggested by QEMU. However, multiboot1 only allows x86-32 format ELF files. To address this limitation, we have developed a simple x86_32 bootloader. This bootloader is designed to copy the `nuttx.bin` file to the designated memory address (`0x100000`) and then transfer control to NuttX by executing a jump instruction (`jmp 0x100000`).
`CONFIG_ARCH_MULTIBOOT1 = y` enables x86-64 NuttX binary wrapper(NuttX32) loaded in multiboot1 protocol.
Tested on x86_64 QEMU 2.10.

arch/x86_64: Add elf32 multiboot1 wrapper for NuttX binary

---

arch/x86_64/src/common/Toolchain.defs
arch/x86_64/src/intel64/Kconfig

Intel CET (Control-flow Enforcement Technology) is a hardware enhancement aimed at mitigating the Retpoline vulnerability, but it may impact CPU branch prediction performance. This commit added ARCH_INTEL64_DISABLE_CET, which can disable CET completely with compilation option `-fcf-protection=none`.
`ARCH_INTEL64_DISABLE_CET = y` will remove `endbr64` instructions from function entries.
Tested on x86 QEMU, with assembly code examined using `objdump -S`

arch/x86_64: Add ARCH_INTEL64_DISABLE_CET

---

arch/arm/src/armv7-m/arm_systick.c
arch/arm/src/armv8-m/arm_gen_nonsecfault.c
arch/arm/src/armv8-m/arm_securefault.c
arch/arm/src/armv8-m/arm_systick.c

arm generate busfault & recursive bug fix
This PR contains two:
armv7/8-m: change enter_critical_section to up_irq_save
caused critical_monitor will gettime, that will caused
enter_critical_seciton recursive
armv8m: support busfault forward to TEE in REE handler mode
armv7/8m systick & armv8m TEE
bes board

arm generate busfault & recursive bug fix

---

drivers/pci/Kconfig
drivers/pci/pci_uio_ivshmem.c

1. Change pci uio ivshmem driver from pci bus based tp pci-ivshmem bus based;
2. Add the interrupt support by usin the pci_ivshmem API;
New feature
x86_64 platform with pci_uio_ivhsmem enabled

pci/pci_uio_ivshmem: pci uio ivshmem msix interrupt support

---

.gitignore

- add .gdb_history to .gitignore
.gdb_history is created next to NuttX ELF when we working with pwndbg GDB plug-in
better user experience when work with pwndbg
none

add .gdb_history to .gitignore

---

drivers/syslog/ramlog.c

ramlog: unify the lock to critical section
ramlog: workaround the unsafe critical section
```
thread1:                           thread2:
ramlog_addbuf()
enter_critical_section()
ramlog_pollnotify()
foreach rl_list
--> switch out
ramlog_file_close
enter_critical_section()
list_delete()
leave_critical_section()
<--- switch back
rl_list error
leave_critical_section()
```
ramlog
bes board

ramlog bug fix

---

arch/sim/src/Makefile
arch/sim/src/sim/CMakeLists.txt
arch/sim/src/sim/posix/sim_hostmemory.c
arch/sim/src/sim/sim_internal.h
arch/sim/src/sim/sim_rpmsg_virtio.c
arch/sim/src/sim/sim_rptun.c
arch/sim/src/sim/sim_uart.c
arch/sim/src/sim/win/sim_hostmemory.c
drivers/pci/pci_drivers.c
drivers/rpmsg/CMakeLists.txt
drivers/rpmsg/Kconfig
drivers/rpmsg/Make.defs
drivers/rpmsg/rpmsg.c
drivers/rpmsg/rpmsg_ping.c
drivers/rpmsg/rpmsg_virtio.c
drivers/rpmsg/rpmsg_virtio_ivshmem.c
drivers/rptun/rptun_ivshmem.c
include/nuttx/rpmsg/rpmsg.h
include/nuttx/rpmsg/rpmsg_virtio.h
include/nuttx/rpmsg/rpmsg_virtio_ivshmem.h

Rpmsg VirtIO is a new Rpmsg Transport Layer Implementation.
Different to the Rptun, rpmsg virtio do not use the remoteproc implementation in OpenAMP to save the code size, so it can be used in chips with low resources.
1.    drivers/rpmsg: fix the race condtion about rpmsg_device_created
xxx_rpmsg_device_created may be called repeatedly.
rptun thread                            app thread
rptun_dev_start                         xxx_rpmsg_init
...                                     rpmsg_register_callback
priv->...= rpmsg_ns_unbind;
priv->..= rptun_notify_wait;
if (ns_unbind_cb)
(switch app thread)                             device_created()
xxx_rpmsg_device_created
metal_list_add_tail(g_cb);
...
rpmsg_device_created();
cb->device_created
xxx_rpmsg_device_created;
2. …

Rpmsg VirtIO Transport support and releated patches

---

drivers/pci/pci_drivers.c
drivers/virtio/CMakeLists.txt
drivers/virtio/Kconfig
drivers/virtio/Make.defs
drivers/virtio/virtio-pci-legacy.c
drivers/virtio/virtio-pci-modern.c
drivers/virtio/virtio-pci.c
drivers/virtio/virtio-pci.h
include/nuttx/virtio/virtio-pci.h

VirtIO PCI Transport Support for NuttX.
Now NuttX can use already implemented virtio-drivers to driver the virtio-pci based virtio device without any modifications to the these drivers.
1.    virtio-pci: fix set virtio device features error
Should assgin back the feature to the vdev->features
2.    virtio-pci.c: polling mode support
1. Some platforms do not support interrupt mode (PCI_MSI/MSIX),
so add polling mode support, so these platforms can also use virtio-pci;
2. In some cases, we do not want to use the interrupt for virtio driver
to avoid time jitter, so add the polling mode support;
3. If CONFIG_DRIVERS_VIRTIO_PCI_POLLING_PERIOD <= 0, interrupt mode.
if CONFIG_DRIVERS_VIRTIO_PCI_POLLING_PERIOD > 0, polling mode.
3.    virtio-pci: extract common part of virtio pci modern and …

VirtIO PCI Transport Support for NuttX

---

CMakeLists.txt
arch/arm/src/cmake/platform.cmake
cmake/nuttx_add_library.cmake
cmake/nuttx_allsyms.cmake
cmake/nuttx_generate_headers.cmake
cmake/nuttx_generate_sim_ld.cmake

This patch refactors and enhances the cmake content:
change the extra library from a file to an import target;
this will avoid differences in the handling of static libraries
between different versions of cmake and different platforms.
after unifying as a target, extra libraries can be
handled as the same as other compiled libraries by call `nuttx_add_extra_library`
merge the arch header file into `BINARY_DIR/include/arch`
fix SIM start crash on Ubuntu22,
becase the previous CMake linker script has missing handling of
C++ global constructor sections in the new Glibc version on ubuntu22
it will cause a prior c++ constructor call error:
```
0x00000000400317f6 in nxsched_get_stackinfo (pid=0, stackinfo=0x7fffffffdbc0) at /media/nuttx/sched/sched/sched_get_stackinfo.c:101
0x000000004002de0d …
```

cmake(refactor):Refactor extra_lib tagert,build include_arch path,refine sim link script target

---

arch/xtensa/src/esp32s3/esp32s3_i2c.c

The measured I2C frequency a little bit more 100KHz when the setting is 100KHz, i2c protocol require <= 100KHz, so adjust I2C clock setting (reference to esp-idf).
ESP32S3 I2C
Test with esp32s3-devkit

xtensa/esp32s3: Adjust I2C clock timing

---

libs/libc/modlib/modlib_bind.c

In file "nuttx/libs/libc/modlib/modlib_bind.c", line656 not check return value of lib_malloc(), and line661 not free dyn.
N/A
CI

[Bug-Fix] Resource leaks

---

drivers/mtd/CMakeLists.txt
drivers/sensors/CMakeLists.txt
libs/libc/regex/CMakeLists.txt
libs/libm/libm/CMakeLists.txt
libs/libm/libmcs/CMakeLists.txt
libs/libm/openlibm/CMakeLists.txt

1. add missing libc regex CMake support
2. support openlibm cmake build
3. add libmcs cmake build
4. add mtd driver dhara cmake build
5. fix lim CMake config prefix missing

cmake:support openlibm,dhara,libmcs,lic regex CMake build scripts

---

drivers/ioexpander/Kconfig
drivers/ioexpander/gpio.c
include/nuttx/ioexpander/gpio.h

1. support poll for gpio device to monitor interrupt happen.
2. using CONFIG_DEV_GPIO_NSIGNALS and CONFIG_DEV_GPIO_NPOLLWAITERS to config code.
support poll for gpio device
vela

drivers/gpio: support poll gpio device and optimize code to save memory

---

sched/misc/coredump.c

just ignore obsolete core file to save latest one
coredump
test it passed on cortext m7

coredump: just save latest core file

---

sched/pthread/pthread_mutextimedlock.c
sched/pthread/pthread_mutexunlock.c

pthread_mutx: remove unused critical_secton lock
Caused the 'nlocks' are remove from mutex, so
here don't need do critical_secton lock like nxmutex_lock
pthread
bes board

pthread_mutx: remove unused critical_secton lock

---

drivers/mtd/ftl.c

For automotive systems, memory allocation actions are not allowed during runtime
Memory allocation is no longer delayed until write operations in the system
fc7300 (cortex M7)

ftl: should pre-allocate eblock for car case

---

arch/arm/src/armv7-a/arm_cpustart.c
arch/arm/src/armv7-a/arm_gicv2.c
arch/arm/src/armv7-a/gic.h
arch/arm/src/armv7-a/smp.h
arch/arm/src/armv7-r/smp.h

armv7-a/r gic related update
```
arm_gicv2: cpu 0 wait other cpu gic init done
After move the SGI irq to group1, other cpu can't response the
sgi request from cpu0 when its gic not initialized.
So let cpu0 wait until all other cpus gic initialize done.
```
```
armv7-a/r: check gic init wait done when using sgi
In SMP mode, qemu/goldfish platform, cpu0 use up_cpu_start()
to start others cpus.
But in previous patch(mathion ahead), arm_gic_initialize() will
wait others cpus start, so deadlocked!
Resolve:
Move the wait logic when use using sgi
```
armv7a gic
bes board & qemu

armv7-a gic related update

---

drivers/usbdev/Kconfig
drivers/usbdev/cdcacm.c
drivers/usbdev/composite.c

1. add CDCACM_BULKOUT_REQLEN to config bulkout req len to optimize performance.
2. remove unnecessary mdelay because remain req info had beed push to serial buffer, and 
this mdelay causes cpu busy wait, affects other process running.
3. warnning fix
minor
Vela

drivers/usbdev: minor update for cdcacm

---

libs/libc/time/lib_localtime.c

libc/time: add g_lcl_lock to protect local context in localsub
```
0x0c1561f8 in localsub (tmp=0x3c887088, offset=0, timep=0x3c887078) at time/lib_localtime.c:1993
localtime_r (timep=0x3c887078, timep@entry=0x3c887088, tmp=0x3c887088, tmp@entry=0x3c887098) at time/lib_localtime.c:2819
0x0c1225c8 in nx_vsyslog (priority=7, fmt=0x2c6d9700 <error: Cannot access memory at address 0x2c6d9700>,
ap=0x3c887170, ap@entry=0x3c887178) at syslog/vsyslog.c:135
0x0c152068 in vsyslog (priority=priority@entry=7,
fmt=fmt@entry=0x2c6d9700 <error: Cannot access memory at address 0x2c6d9700>, ap=ap@entry=...) at syslog/lib_syslog.c:68
0x0c152098 in syslog (priority=priority@entry=7, fmt=0x2c6d9700 <error: Cannot access memory at address 0x2c6d9700>) at syslog/lib_syslog.c:100
```
Bug Fix
Vela

libc/time: add g_lcl_lock to protect local context in localsub

---

boards/arm/stm32h7/nucleo-h743zi/src/stm32_boot_image.c

After changing sp, following functions calling will result in unpredictable behavior in case of jumping
stm32h7/nucleo-h743zi

nucleo-h745zi: fix potential bl jump to app failed issue

---

Documentation/platforms/arm/rp2040/boards/raspberrypi-pico-w/README.txt
Documentation/platforms/arm/rp2040/boards/raspberrypi-pico/README.txt

The build instructions for the Pi Pico(s) now reflect the steps required using SDK version 2.0.0.
The build instructions now work when followed.
Closes #13483. 
Performed a clean build following the new instructions and was able to successfully build.

Update Raspberry Pi Pico and Pico W docs for new SDK version 2.0.0

---

fs/mount/fs_mount.c
fs/romfs/fs_romfsutil.c

fs/mount: add ftl proxy to mount block filesystem on mtd device
auto proxy for mtd device when mount block fs
Vela

fs/mount: add ftl proxy to mount block filesystem on mtd device

---

boards/Kconfig
boards/boardctl.c
include/nuttx/board.h
include/sys/boardctl.h

This interface may be used by application specific logic to start
specified slave cpu core under the pseudo AMP case which is different
with armv7-a/armv8-a SMP. Support for this function is required by
board-level logic if CONFIG_BOARDCTL_START_CPU is selected.
None
fc7300 (cortex M7)

boardctl: add board control api to start slave core

---

fs/vfs/fs_ioctl.c
fs/vfs/fs_poll.c

the type of geo_nsectors is blkcnt_t
vfs

vfs:fix a type mismatch issue and a typo

---

drivers/rpmsg/CMakeLists.txt
drivers/rpmsg/Kconfig
drivers/rpmsg/Make.defs
drivers/rpmsg/rpmsg.c
drivers/rpmsg/rpmsg_port.c
drivers/rpmsg/rpmsg_port.h
drivers/rpmsg/rpmsg_port_spi.c
drivers/rpmsg/rpmsg_port_spi_slave.c
drivers/rpmsg/rpmsg_port_uart.c
drivers/rpmsg/rpmsg_router.h
drivers/rpmsg/rpmsg_router_edge.c
drivers/rpmsg/rpmsg_router_hub.c
drivers/rpmsg/rpmsg_virtio.c
drivers/rptun/rptun.c
include/nuttx/rpmsg/rpmsg.h
include/nuttx/rpmsg/rpmsg_port.h
include/nuttx/rpmsg/rpmsg_router.h
include/nuttx/rpmsg/rpmsg_virtio.h
include/nuttx/rptun/rptun.h

Three new rpsmg transport layers support:
- Rpmsg Port SPI
- Rpmsg Port UART
- Rpmsg Router
1.    rpmsg_port_spi: set mreq to high to trigger next transmission
rpmsg_port_spi_connect can not be used here because peer may have not finished
the last transmission which will keep the sreq gpio in high level, and it will
read an error data frame.
2.    rpmsg_port_spi/slave: reorder rpmsg_port_initialize and rpmsg_port_spi_init hardware
Because the data transmision may has been started before
rpmsg_port_initialize(), this should be not allowed.
3.    rpmsg_port_spi: add pending logic for rpmsg port spi
To handle the situation that there is a req from peer side when
current transfer is not finished.
4.    rpmsg_port_spi: add nbits to spicfg
Support more spi config paramters for Rpmsg Port …

New Rpmsg Transports: Rpmsg Port SPI, Rpmsg Port Uart and Rpmsg Router Transport Support

---

drivers/misc/optee.c
libs/libc/netdb/lib_dnsbind.c
libs/libc/time/lib_localtime.c

enable O_CLOEXEC explicitly to avoid fd leak
optee, netdb, localtime

enable O_CLOEXEC explicitly to avoid fd leak

---

include/nuttx/wqueue.h
sched/wqueue/kwork_cancel.c
sched/wqueue/kwork_notifier.c

one:
wqueue: teardown should cancel the work already in wqueue
the other one:
```
wqueue: workaound g_notifier_pending list unsafe
Situation:
thread1                             thread2
work_notifier_signal
enter_critical_section
dq_peek(&g_notifier_pending)
dq_rem(&g_notifier_pending)
work_queue()
// switch -->                 work_notifier_teardown
enter_critical_section
dq_rem(&g_notifier_pending)
leave_critical_section
<--- switch back
error occured
leave_critical_section
Workaound:
used sched_lock() to prevent the switch
```
wqueue
bes board, net

wqueue bug fix

---

libs/libc/netdb/lib_gethostbyaddr.c
libs/libc/netdb/lib_gethostbyaddrr.c
libs/libc/netdb/lib_gethostbyname.c
libs/libc/netdb/lib_gethostbyname2.c
libs/libc/netdb/lib_gethostbyname2r.c
libs/libc/netdb/lib_gethostbynamer.c
libs/libc/netdb/lib_gethostentbynamer.c
libs/libc/netdb/lib_getnameinfo.c
libs/libc/netdb/lib_getservbyname.c
libs/libc/netdb/lib_getservbynamer.c
libs/libc/netdb/lib_getservbyport.c
libs/libc/netdb/lib_getservbyportr.c
libs/libc/netdb/lib_netdb.c

Since it already checked by Make.defs and CMakeLists.txt
No
CI

libc/netdb: Remove unnecessary CONFIG_LIBC_NETDB checks

---

libs/libc/obstack/lib_obstack_vprintf.c

The commit c4d8d937d5953930ba00a6f40ce3fdd17273f68e added null byte for obstack_vprintf and thus to obstack_printf. I probably lost my marbles but the same test I run previously now won't append null byte at the end and this "fix" now causes regressions in code using obstack.
Reverse of the previous invalid assumption.
For the reference this is the testing code:
```
#define _GNU_SOURCE
#include <obstack.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#define obstack_chunk_alloc malloc
#define obstack_chunk_free free
static void print(struct obstack *obs, const char *fmt, ...) {
va_list arg;
va_start(arg, fmt);
obstack_vprintf(obs, fmt, arg);
va_end(arg);
}
int main(int argc, char *argv[]) {
struct obstack obs;
obstack_init(&obs);
obstack_printf(&obs, "this %s", "text "); …
```

libs/libc/obstack: revert invalid null byte append to obstack_vprintf

---

arch/arm/src/cxd56xx/cxd56_sph.c
arch/arm/src/cxd56xx/cxd56_uart0.c

Fix an issue of driver open failure caused by the following commit that changes the initial value of inode reference.
43d0d95f81 fs/inode: using inode reference to indicate unlink and simply code
https://github.com/apache/nuttx/pull/13331

arch: cxd56xx: Fix issue by update of inode reference

---

arch/risc-v/Kconfig
arch/risc-v/src/common/riscv_exception.c

The number of exception for risc-v is 16 (0 ~ 15)
for the machine ISA version 1.12 or earlier, the number of exception is 20 (0 ~ 19) from the ISA version 1.13. And maybe changed in the future.
Using a dedicated option to control the exception number to allow the earlier version chip with customized exception number (e.g. 16 ~ 19 used) to define the exception reason string correctly.
Minor

risc-v: Add a new option to control exception reason

---

arch/arm/src/armv7-a/arm_addrenv.c
arch/arm/src/armv7-a/arm_addrenv_utils.c

Hello, World!!
ap> [    2.566000] [ 1] arm_addrenv_destroy_region: listlen=1
vaddr=80000000
[    2.566000] [ 1] gran_free: granmask:0xfff, gatmask:0x10000,
gatidx:0x8, priv->gat[gatidx]:0xffffffff granno:0x110 [mem:0x48110000
free_size:0x1000]
[    2.566000] [ 1] gran_free: granmask:0xfff, gatmask:0x8000,
gatidx:0x8, priv->gat[gatidx]:0xfffeffff granno:0x10f [mem:0x4810f000
free_size:0x1000]
[    2.567000] [ 1] arm_addrenv_destroy_region: listlen=1 vaddr=80100000
[    2.567000] [ 1] gran_free: granmask:0xfff, gatmask:0x40000,
gatidx:0x8, priv->gat[gatidx]:0xfffe7fff granno:0x112 [mem:0x48112000
free_size:0x1000]
[    2.567000] [ 1] gran_free: granmask:0xfff, gatmask:0x20000,
gatidx:0x8, priv->gat[gatidx]:0xfffa7fff granno:0x111 [mem:0x48111000
free_size:0x1000]
[    2.568000] [ 1] …

arm_addrenv:fix app crash when enable shm in kernel mode

---

fs/inode/fs_files.c

Dump the list of files when the file description runs out
Output detailed logs when file description runs out
CI-CHECK

fs: Dump the list of files when the file description runs out

---

fs/inode/fs_files.c
include/nuttx/fs/fs.h
sched/misc/assert.c

fs/dump: correct SCHED_DUMP_ON_EXIT to DUMP_ON_EXIT
1. correct SCHED_DUMP_ON_EXIT to DUMP_ON_EXIT
2. dump file list only if DUMP_ON_EXIT enabled
N/A
ci-check

fs/dump: correct SCHED_DUMP_ON_EXIT to DUMP_ON_EXIT

---

drivers/serial/uart_pci_16550.c

- serial/pci_16550: make sure that interrupts are disabled during init
Make sure that interrups are disabled during initialization.
This is a proper fix for an unexpected MSI interrupt for PCI serial driver.
intel64 hw

serial/pci_16550: make sure that interrupts are disabled during init

---

fs/inode/fs_files.c
fs/mmap/CMakeLists.txt
fs/mmap/Make.defs
fs/mmap/fs_anonmap.c
fs/mmap/fs_mmap.c
fs/mmap/fs_msync.c
fs/mmap/fs_munmap.c
fs/mmap/fs_rammap.c
fs/mmap/fs_rammap.h
include/nuttx/fs/fs.h
include/nuttx/mm/map.h
include/sys/syscall_lookup.h
syscall/syscall.csv

**Why is this change necessary**
In some external test cases (such as FIO), they use the msync interface provided by the system to ensure that the rammap data can actually be written to the file system. Currently, mmap in NuttX does not provide this interface, so msync is implemented.
**Changes**
This mainly adds fs_msync.c under fs/mmap. And makes some adjustments to rammap.c and anonmap.c
**Implementation details**
Each mmap corresponds to an mm_map entry. The priv.p of each entry is used to save filep + type (the lower three bits of each priv.p represent type).
At each msync, the lower three bits of type need to be restored to filep and the data written
Refer to https://github.com/apache/nuttx/pull/5997 and implement an msync based on the current mmap
Follow …

Support msync

---

fs/vfs/fs_dup2.c

file_ioctl failed, but close success, inode need release
NULL
qemu

fs_dup2 bug fix, memleak

---

Documentation/implementation/critical_sections.rst
fs/procfs/fs_procfscritmon.c
fs/procfs/fs_procfsproc.c
include/nuttx/sched.h
sched/Kconfig
sched/clock/clock_gettime.c
sched/irq/irq_csection.c
sched/irq/irq_dispatch.c
sched/sched/sched.h
sched/sched/sched_critmonitor.c
sched/sched/sched_lock.c
sched/sched/sched_unlock.c

For current version. there will be a large performance loss after SCHED_CRITMONITOR is enabled. We have few feature based on SCHED_CRITMONITOR, isolating thread running time-related functions, CPU load can be run with less overhead.
Also we add a caller record in preemption & csection, to help evaluate / optimize.
To make statistic more accurate, when sched happend, we cut the sched_monitor caculation up to now.
Now we can enable the cpuload based on critimon and disable other critmon cost, will be a low-cost cpuload evaluate method.
We can now see who make largest elapsed time from preemption/cserction.
When sched happend, the elapsed time now seperate to two different thread.
CI-test. and arm v7a smp board, etc.

Critmon optimize, make possible open cpuload based on critmon and disable critical section & sched_lock to save cost.

---

drivers/mmcsd/mmcsd.h
drivers/mmcsd/mmcsd_sdio.c

I will add RPMB functionality support in the next patch, and RPMB read/write operations must use cmd23, so we have this current modification because some sd cards don't support cmd23 or support cmd23 indicated by bit33 in scr
emmc / sd
cortext M55

mmcsd: make a compatibility change for cmd12 and cmd23

---

arch/Kconfig
include/nuttx/sched.h
sched/Kconfig
sched/sched/CMakeLists.txt
sched/sched/Make.defs
sched/sched/sched_dumponexit.c

Change DUMP_ON_EXIT to CONFIG_SCHED_DUMP_ON_EXIT and move it to the sched directory
Fix the bug in https://github.com/apache/nuttx/pull/13118, It uses undefined macros

sched: move DUMP_ON_EXIT to sched

---

libs/libc/uio/CMakeLists.txt

libc: add missing preadv/pwritev in CMakeLists.txt

---

libs/libc/machine/arm/armv8-m/gnu/arch_memcpy.S

armv8-m:arch libc function need save ip register use pacbti
bug fix， somewhere will change ip
vela

armv8-m:arch libc function need save ip register use pacbti

---

drivers/bch/Kconfig
fs/vfs/fs_open.c

BCH: Add readonly configuration for BCH devices
NONE
CI-CHECK

BCH: Add readonly configuration for BCH devices

---

arch/arm/include/arm/irq.h
arch/arm/include/armv6-m/irq.h
arch/arm/include/armv7-a/irq.h
arch/arm/include/armv7-m/irq.h
arch/arm/include/armv7-r/irq.h
arch/arm/include/armv8-m/irq.h
arch/arm/include/armv8-r/irq.h
arch/arm/include/irq.h
arch/arm/include/tlsr82/irq.h
arch/arm/src/armv7-a/arm_cpuhead.S
arch/arm/src/armv7-a/arm_head.S
arch/arm/src/armv7-r/arm_cpuhead.S
arch/arm/src/armv7-r/arm_head.S
arch/arm/src/armv8-r/arm_head.S
arch/arm/src/common/arm_initialize.c
arch/arm64/include/irq.h
arch/arm64/src/common/arm64_arch.h
arch/arm64/src/common/arm64_backtrace.c
arch/arm64/src/common/arm64_copystate.c
arch/arm64/src/common/arm64_cpustart.c
arch/arm64/src/common/arm64_fork.c
arch/arm64/src/common/arm64_fpu.c
arch/arm64/src/common/arm64_head.S
arch/arm64/src/common/arm64_initialize.c
arch/arm64/src/common/arm64_initialstate.c
arch/arm64/src/common/arm64_registerdump.c
arch/arm64/src/common/arm64_schedulesigaction.c
arch/arm64/src/common/arm64_vectors.S

using percpu storage for g_current_regs or leveraging interrupt status
registers to determine if code is running within an interrupt context can enhance performance.
The benefits are very significant.
Before the modification, if we needed to obtain the interrupt status, it required three steps:
1 Obtain the CPU index
2 Access the global variable
4 Disable/Enable interrupts
This process involved at least 7 CPU instructions.
However, now it only requires a single CPU instruction.
none
ostest

Accelerate access to interrupt status

---

CMakeLists.txt
Documentation/components/libs/libc/index.rst
Documentation/quickstart/install.rst
Kconfig
binfmt/Kconfig
cmake/nuttx_add_application.cmake
tools/Unix.mk

maintains the same semantics as Kernel’s module build and compatible with Kconfiglib implementation.
The problem of kconfiglib not being able to use tri-states is this:
linux is here https://github.com/torvalds/linux/commit/6dd85ff178cd76851e2184b13e545f5a88d1be30
The module option is extracted from one of the triate three states into a MODULE keyword.
Kconfiglib supports the default implementation of module to be MODULE for compatibility with the linux kernel, and triate degenerates into bool two states
Refer to this code: https://github.com/ulfalizer/Kconfiglib/blob/061e71f7d78cb057762d88de088055361863deff/kconfiglib.py#L4274-L4284
kconfiglib can support <m>
relate apps patch: https://github.com/apache/nuttx-apps/pull/2577

modify BUILD_LOADABLE to MODULES which backwards-compatible Kernel

---

drivers/can/sja1000.c

Drop driver dependency on `__builtin` functions
Improve portability
Pass CI

can/sja1000: drop driver dependency on __builtin functions

---

arch/arm/src/samv7/Kconfig
arch/arm/src/samv7/Make.defs
arch/arm/src/samv7/hardware/sam_uart.h
arch/arm/src/samv7/sam_lin.h
arch/arm/src/samv7/sam_lin_sock.c
include/nuttx/can.h

Initial support of LIN over SocketCAN interface for SAMv7
New feature
Tested communicating LIN master to slave on a custom SAMv7 based board with 2 LIN interfaces

arch/arm/samv7: Initial support of LIN over SocketCAN interface

---

include/nuttx/streams.h
libs/libc/stdio/CMakeLists.txt
libs/libc/stdio/Make.defs
libs/libc/stdio/README.md
libs/libc/stdio/lib_libbsprintf.c
libs/libc/stdio/lib_libvscanf.c

Introducing support for structure serialization and deserialization:
* `lib_libbsprintf`  This function is mainly used to output the contents of the input structure. Most standards follow the standards of printf and scanf. For detailed parameters, see:
* https://en.cppreference.com/w/c/io/fprintf
* https://en.cppreference.com/w/c/io/fscanf
* special formatting:
* Float use `%hf`, and double for all others.
* The char array is specified with `%.xs`. for example: `char t[30]` is specified with `%.30s`, `char a [20]` with `%.20s`.
* `%u` is unsigned int.
* `%d` is int.
* When using `%f` to format a double data type, the double is truncated to 6 decimal places by default.
* It is recommended that the `char[]` array be placed at the end of the structure to prevent parameter configuration …

libs/libc/stdio/*printf *scanf:Add string serialization and deserialization functions

---

drivers/sensors/usensor.c

- Error Log: (job: https://github.com/apache/nuttx/actions/runs/10931837648/job/30347585490)
```
/tools/ccache/bin/cc -D__KERNEL__ -D__NuttX__ -I/github/workspace/sources/nuttx/openamp/open-amp/lib/include -I/github/workspace/sources/apps/system/argtable3/argtable3/src -I/github/workspace/sources/apps/system/uorb -I/github/workspace/sources/nuttx/sched -I/github/workspace/sources/nuttx/openamp/open-amp/lib -I/github/workspace/sources/nuttx/drivers/virtio -I/github/workspace/sources/nuttx/drivers -isystem /github/workspace/sources/nuttx/include -isystem /github/workspace/sources/nuttx/build/include -fno-common -g -m32 -fomit-frame-pointer -ffunction-sections -fdata-sections -Wstrict-prototypes -fdiagnostics-color=always -Wall -Wshadow -Wundef -DNDEBUG …
```

Fix build error of drivers/sensors/usensor.c

---

fs/mmap/fs_rammap.c

fix the greenhills build warning on enum data type manage.
the following are the detailed warning info:
CC:  obstack/lib_obstack_printf.c "mmap/fs_rammap.c", line 126: warning #188-D: enumerated type mixed with
another type
enum mm_map_type_e type = (uintptr_t)entry->priv.p & 3;
^
In greenhills compiler, do not allow enum mixed with another type, so we need to perform cast between enum and the truly used data type.
has no impact on the function
has passed the full ostest with gcc/greenhills compiler

greenhills support: fix the enumerated type mixed using warning

---

drivers/mmcsd/mmcsd_sdio.c

Cleaning...
Configuring...
Disabling CONFIG_ARM_TOOLCHAIN_GNU_EABI
Enabling CONFIG_ARM_TOOLCHAIN_GNU_EABI
Error: mmcsd/mmcsd_sdio.c:1419:12: error: 'mmcsd_setblockcount' defined but not used [-Werror=unused-function]
1419 | static int mmcsd_setblockcount(FAR struct mmcsd_state_s *priv,
|            ^~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:103: mmcsd_sdio.o] Error 1
make[1]: Target 'libdrivers.a' not remade because of errors.
make: *** [tools/LibTargets.mk:101: drivers/libdrivers.a] Error 2
make: Target 'all' not remade because of errors.
build break
ci test

mmcsd: fix a build error

---

drivers/sensors/adxl362_uorb.c
drivers/sensors/adxl372_uorb.c
drivers/sensors/bh1749nuc_uorb.c
drivers/sensors/bme680_uorb.c
drivers/sensors/bmi270_uorb.c
drivers/sensors/bmm150_uorb.c
drivers/sensors/bmp180_uorb.c
drivers/sensors/bmp280_uorb.c
drivers/sensors/ds18b20_uorb.c
drivers/sensors/hyt271_uorb.c
drivers/sensors/lsm9ds1_uorb.c
drivers/sensors/ltr308_uorb.c
drivers/sensors/mpu9250_uorb.c
drivers/sensors/ms56xx_uorb.c

New member added to `struct sensor_ops_s`, and type changed, but not update all existed code, for details, please see "Related change" below.
- Error 1:
```
1153  Building NuttX...
1154Error: sensors/bme680_uorb.c:428:3: error: initialization of 'int (*)(struct sensor_lowerhalf_s *, struct file *, long unsigned int)' from incompatible pointer type 'int (*)(struct sensor_lowerhalf_s *, struct file *, int,  long unsigned int)' [-Werror=incompatible-pointer-types]
1155  428 |   bme680_control    /* control */
1156      |   ^~~~~~~~~~~~~~
```
- Error 2:
```
Error: sensors/ms56xx_uorb.c:145:20: error: initialization of 'int (*)(struct sensor_lowerhalf_s *, struct file *, uint32_t *)' {aka 'int (*)(struct sensor_lowerhalf_s *, struct file *, unsigned int *)'} from incompatible pointer type 'int …
```

nuttx/uorb: Fix build error

---

.github/workflows/labeler.yml

Add workflow that assigns labels based on the PR's size.
Based on https://github.com/marketplace/actions/pull-request-size-labeler
This is an external action, but it's used also in Apache Mynewt-nimble project, so I think it's ok: https://github.com/apache/mynewt-nimble/blob/master/.github/workflows/labeler.yml
This allows easy filtering of PR by the size of changes
Each PR will have a label assigned depending on its size: 
xs_label: 'Size: XS', max size = 10
s_label: 'Size: S', max size = 100
m_label: 'Size: M', max size = 500
l_label: 'Size: L', max size = 1000
xl_label: 'Size: XL', > 1000
tested on my private nuttx repo here https://github.com/raiden00pl/nuttx/pulls

github/workflows: add PR size labeler

---

Kconfig

After  https://github.com/apache/nuttx/pull/13452  this commit, the three-state `<m>` in kernel mode cannot be selected when using kconfig-frontend
Because kconfiglib recognizes `MODULE` configuration but not `modules` attributes,
and kconfig-frontend is compatible with the latest `modules` attributes of Linux,
we can only use the old version to use `MODULE` configuration **PLUS** `options modules` to be compatible with both.
this is a patch for https://github.com/apache/nuttx/pull/13452
qemu-armv8a:knsh with kconfig-frontend
qemu-armv8a:knsh with kconfiglib

[Bugfix]Kconfig:ensure compatibility between kconfig-frontend and kconfiglib in kernel build

---

arch/risc-v/src/litex/litex_ticked.c

The tick count should be manually set as there is no guarantee that the previous boot stage hasn't modified this count since reset.
The fist timer expiry is always set to the tick count.
arty_a7:knsh

arch/risc-v/src/litex_ticked: Set initial tick count to known value.

---

.github/workflows/build.yml
arch/risc-v/src/common/espressif/Make.defs
arch/risc-v/src/esp32c3-legacy/Make.defs
arch/xtensa/src/esp32/Make.defs
arch/xtensa/src/esp32s2/Make.defs
arch/xtensa/src/esp32s3/Make.defs
tools/Config.mk
tools/Unix.mk
tools/configure.sh
tools/testbuild.sh

The simple improvement is designed to speed up compilation and reduce download errors on github and local.
Added a folder nxtmpdir for storing third-party packages
nuttxworkspace
|
|- nuttx
|- apps
|- nxtmpdir
tools/Unix.mk:
added nxtmpdir folder creation
tools/configure.sh:
added option -S creates the nxtmpdir folder for third-party packages.
For now I added in the folder this package
ESP_HAL_3RDPARTY_URL = https://github.com/espressif/esp-hal-3rdparty.git
ARCH
arch/xtensa/src/esp32/Make.defs
arch/xtensa/src/esp32s2/Make.defs
arch/xtensa/src/esp32s3/Make.defs
arch/risc-v/src/common/espressif/Make.defs
arch/risc-v/src/esp32c3-legacy/Make.defs
but you can also add other packages (maybe also of apps)
@no1wudi @tmedicci
CI

CI: Improvement to speed up compilation and reduce download errors.

---

libs/libc/tls/tls_cleanup.c

unsigned_compare: This greater-than-or-equal-to-zero comparison without a signed value is always true. ndx >= 0U
NONE
ci-check

Fix greater-than-or-equal-to-zero issue

---

drivers/i2c/i2c_driver.c

i2c: Optimize access to private data，this is code cleanup. Access to private data is optimized to remove unwanted variables
NONE
Local iic testing

i2c: Optimize access to private data

---

.github/ISSUE_TEMPLATE/001_bug_report.yml
.github/ISSUE_TEMPLATE/002_feature_request.yml
.github/ISSUE_TEMPLATE/003_help.yml
.github/workflows/issue_labeler.yml

This change adds a specifier to github labels created with "new issue":
- for labels related to architecture specifier is "Arch: xxx"
- for labels related to issue type specifier is "Type: xxx"
- for labels related to host OS type specifier is "OS: xxx"
- for labels related to issue area type specifier is "Area: xxx"
with this PR the labels will be more readable and they'll be displayed grouped according to the specifier. 
After the PR is merged, the labels in github need to be updated accordingly (label name and color): https://github.com/apache/nuttx/labels
Related issue (doesn't solve it completely):  https://github.com/apache/nuttx/issues/13522
tested on private repo and below is the result (https://github.com/raiden00pl/nuttx/issues)
I just chose random colors for the above test

github: add specifier to github issue labels

---

sched/pthread/pthread_mutex.c

add deadlock check
pthread mutex
sim & qmue ust pthread mutex

pthread_mutex:add deadlock assert

---

drivers/sensors/sensor_rpmsg.c

Bug fix, After the ap core subscribes to the 25hz batch 120ms data of the sensor core, it switches to the cp core and subscribes to the 50hz batch 120ms sensor core data. At this time, the data subscribed by the AP will be abnormally lost (12.5hz). Mainly because ap subscribes to sensor core data earlier than cp. The subscription of cp will be broadcast to the ap core at the same time, and the corresponding "path" already exists under "/dev/uorb" of ap. Thus the ap will create a "stub".
There are some restrictions on the creation of "stub" to avoid this situation.
Cross-core communication and persistent topics
- build
PC:ubuntu2004, X86,SIM
rpserver and rpproxy open uorb config
```
./build.sh nuttx/boards/sim/sim/sim/configs/rpserver -j16
./build.sh …
```

sensor_rpmsg.c:Fix that "stub" will be created when local core only has subscribers.

---

Documentation/quickstart/debugging.rst
tools/gdb/gcore.py

Modify elf with nxgcore and call gcore:
(gdb) nxgcore --help
usage: [-h] [-o OUTPUT] [-t OBJCOPY] [-r MEMRANGE]
options:
-h, --help            show this help message and exit
-o OUTPUT, --output OUTPUT
Gcore output file
-t OBJCOPY, --objcopy OBJCOPY
Select the appropriate architecture for the objcopy
tool
-r MEMRANGE, --memrange MEMRANGE
examples:
(gdb) nxgcore -t arm-none-eabi-objcopy -r 0x40200000,0x48000000,0x07

gdb plugin: Encapsulate the gdb native command gcore as nxgcore

---

arch/risc-v/src/common/riscv_doirq.c
arch/risc-v/src/common/riscv_internal.h
arch/risc-v/src/common/riscv_schedulesigaction.c
arch/risc-v/src/common/riscv_swint.c
arch/risc-v/src/common/supervisor/riscv_perform_syscall.c

Why
When a context switch occurs currently, the context before the interrupt is fetched from the global variable g_current_regs and then stored in the corresponding tcb->xcp.regs. Subsequently, the new context is assigned to g_current_regs. When returning from the interrupt context, the context is retrieved from g_current_regs and used.
In reality, we do not necessarily require this intermediate variable g_current_regs to accomplish a context switch. Eliminating it avoids multiple assignments, especially during multiple context switches within interrupts, which can lead to repeated assignments.
All we need is to work directly with the context of the currently running task. This approach enhances the speed of context switching, reduces the code base, and optimizes signal handling logic. By …

riscv: g_current_regs is only used to determine if we are in irq

---

include/nuttx/streams.h

1. bug fix，lzf.h header file reference adds macro package
1. Libc LZF Modules
PC：Ubuntu 20.04，X86，SIM，GCC 13.1
Configure lzf 
```
./tools/configure.sh sim:nsh
./nuttx 
```

lzf:Add macro judgment to header file reference.

---

arch/xtensa/include/irq.h
boards/xtensa/esp32s3/common/scripts/legacy_sections.ld
boards/xtensa/esp32s3/common/scripts/mcuboot_sections.ld
boards/xtensa/esp32s3/common/scripts/simple_boot_sections.ld

Jira Task ID: _ NUT-1183_
* esp32s3: Fix faulty `esp32s3-devkit:stack` example
This defconfig is an example of the recorded stack and it became faulty recently after the implementation of the `up_current_regs` functions (https://github.com/apache/nuttx/pull/13423). The `noinstrument_function` directive must be used to prevent it from being looped when instrumentation is enabled. Also, this commit places `sched/instrument/stack_record.c` in IRAM.
Make `esp32s3-devkit:stack` example work again.
Internal CI testing + ESP32-S3-DevKitC-1 v1.0
Just build it and run `cat /proc/0/stack`.

esp32s3: Fix faulty `esp32s3-devkit:stack` example

---

arch/arm64/include/arch.h
arch/arm64/src/common/arm64_addrenv.c
arch/arm64/src/common/arm64_addrenv_perms.c
arch/arm64/src/common/arm64_addrenv_pgmap.c
arch/arm64/src/common/arm64_addrenv_utils.c
arch/arm64/src/common/arm64_mmu.c
arch/arm64/src/common/arm64_mmu.h
arch/arm64/src/common/arm64_pgalloc.c

The original code made the incorrect assumption that the amount of
translation levels is 3, but this is incorrect. The amount of levels is 4
and the amount of levels that are utilized / in use is set dynamically
from the amount of VA bits in use.
Support for 4 level translations in ARM64 address environments
QEMU + iMX93 with kernel mode

arm64_addrenv: Add support for 4 level MMU translations

---

drivers/sensors/sensor.c
drivers/sensors/sensor_rpmsg.c

- Bug fix. When the remote core publishes a message, the subscribed cores will receive the message. When the subscribed core publishes a new message, it will take away the message published by the remote core, so all stublist information needs to be updated.
- Sensor cross-core communication.
```
/****************************************************************************
* apps/examples/hello/hello_main.c
*
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements.  See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.  The
* ASF licenses this file to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance with the
* License.  You may …
```

 sensor:Fixed the problem of user information lag in cross-core communication "stublist".

---

arch/arm64/src/common/arm64_internal.h
arch/arm64/src/common/arm64_pthread_start.c
arch/arm64/src/common/arm64_task_start.c
arch/arm64/src/common/arm64_vectors.S

The aforementioned functions can/will fail if the C compiler decides to use the stack for the incoming entrypt/etc. parameters.
Fix this issue by converting the jump to user part into pure assembly, ensuring the stack is NOT used for the parameters.
Fix system crash when user process enters userspace
QEMU + IMX9 with kernel mode

arm64_task/pthread_start: Convert the C / inline ASM code to assembly

---

Documentation/components/net/socketcan.rst

can: Add g_ prefix to can_dlc_to_len and len_to_can_dlc.
continue work of f76c2ed83b2b5804ca1275363b954f925492c52d
detail: Add g_ prefix to can_dlc_to_len and len_to_can_dlc to
follow NuttX coding style conventions for global symbols,
improving code readability and maintainability.
N/A
ci-check

can: Add g_ prefix to can_dlc_to_len and len_to_can_dlc.

---

boards/arm/stm32/olimex-stm32-p407/scripts/memory.ld
include/nuttx/signal.h
sched/signal/sig_dispatch.c
sched/signal/sig_kill.c
sched/signal/sig_notification.c
sched/signal/sig_queue.c
sched/signal/signal.h
sched/timer/timer_create.c

This commit simplified the implementation for SIGEV_THREAD_TID and added the missing siginfo initializer.
POSIX timer with SIGEV_THREAD_TID flag.
Tested on QEMU using rt-tests/cyclictest.

sched/signal: Simplified Implementation for SIGEV_THREAD_TID

---

drivers/syslog/CMakeLists.txt
drivers/syslog/Make.defs

drivers/syslog: compile syslog_device.c if console/char/file channel enabled
Add conditional compilation to syslog_device.c
N/A
ci-check

drivers/syslog: compile syslog_device.c if console/char/file channel enabled

---

fs/vfs/fs_chstat.c
fs/vfs/fs_fchstat.c

fs/chmod/fchmod/lchmod: only set permissions by mode_t and ignore othjer bits
test case:
int main(void)
{
struct stat buf;
int ret;
stat("test1.t", &buf);
printf("test1.t st.mode:%x\n", buf.st_mode);
stat("test.t", &buf);
printf("test.t st.mode:%x\n", buf.st_mode);
ret = chmod("test1.t", buf.st_mode);
if (ret == 0)
{
stat("test1.t", &buf);
printf("test1.t st.mode:%x\n", buf.st_mode);
}
return 0;
}
>>
test1.t st.mode:81b4
test.t st.mode:81fd
test1.t st.mode:81fd

fs/chmod/fchmod/lchmod: only set permissions by mode_t and ignore othjer bits

---

fs/inode/fs_files.c
fs/mmap/Kconfig
fs/mmap/fs_rammap.c

bug fix
1. Should call fs_putfilep put fs reference when call files_fget complete
2. FS_RAMMAP depends on FS_REFCOUNT and remove useless macro
all CONFIG_FS_REFCOUNT and CONFIG_DUMP_ON_EXIT config, A reference count exception exists. Procedure
open CONFIG_FS_REFCOUNT and CONFIG_DUMP_ON_EXIT，call files_dumplist

File reference count bug fix

---

arch/arm/src/sama5/sam_mcan.c

Noted a compiler warning - perhaps as a result of moving to newer gcc version or changes to NuttX gcc compiler options:
```
chip/sam_mcan.c:1562:14: warning: 'ret' may be used uninitialized [-Wmaybe-uninitialized]
1562 |   while (ret < 0);
```
None - no detrimental effect as a result of the warning had been noted, but obviously needed to be cleaned up/fixed
Custom board with SAMA5D27C-D1G

SAMA5 sam_mcan.c unitialized variable

---

arch/Kconfig
arch/x86_64/Kconfig
arch/x86_64/src/common/Toolchain.defs
arch/x86_64/src/intel64/CMakeLists.txt
arch/x86_64/src/intel64/Make.defs
arch/x86_64/src/intel64/intel64_backtrace_fp.c
arch/x86_64/src/intel64/intel64_handlers.c
arch/x86_64/src/intel64/intel64_initialstate.c
arch/x86_64/src/intel64/intel64_regdump.c

Add FP backtrace function
The code for an exception was written, and after execution, it can print the correct backtrace.

arch/x86_64:Add FP backtrace function

---

arch/arm64/src/common/arm64_arch.h
arch/arm64/src/common/arm64_exit.c
arch/arm64/src/common/arm64_fatal.c
arch/arm64/src/common/arm64_fatal.h
arch/arm64/src/common/arm64_fpu.c
arch/arm64/src/common/arm64_initialstate.c
arch/arm64/src/common/arm64_internal.h
arch/arm64/src/common/arm64_schedulesigaction.c
arch/arm64/src/common/arm64_sigdeliver.c
arch/arm64/src/common/arm64_syscall.c
arch/arm64/src/common/arm64_vector_table.S
arch/arm64/src/common/arm64_vectors.S

Arm64 irq1

---

sched/pthread/pthread_mutex.c

Revert "pthread_mutex:add deadlock assert"
EDEADLK alreay checked in:
https://github.com/apache/nuttx/blob/master/sched/pthread/pthread_mutextimedlock.c#L112-L127
https://github.com/apache/nuttx/blob/master/sched/pthread/pthread_mutex.c#L195-L201
This reverts commit 112cc083d30047b160fbeda753a26b88362cdf70.
N/A
ci-check

Revert "pthread_mutex:add deadlock assert"

---

drivers/misc/rpmsgdev_server.c

Fix invalid pointer error when there are more than one remotes
- Log
```
[ap] arm_busfault: PANIC!!! Bus Fault:
[ap] arm_busfault:        IRQ: 5 regs: 0x3c434e44
[ap] arm_busfault:        BASEPRI: 00000000 PRIMASK: 00000000 IPSR: 00000005 CONTROL: 00000004
[ap] arm_busfault:        CFSR: 00008200 HFSR: 00000000 DFSR: 00000000 BFAR: 00000000 AFSR: 00040000
[ap] arm_busfault: Bus Fault Reason:
[ap] arm_busfault:        Precise data bus error
[ap] dump_assert_info: Current Version: NuttX ****** ***** *** 12.3.0 ********** Sep 23 2024 18:35:50 arm
[ap] dump_assert_info: Assertion failed panic: at file: armv8-m/arm_busfault.c:113 task: testdev process: testdev 0x2c86ca75
```
- Backtrace
```
backtrace_unwind
/workspace/nuttx/arch/arm/src/common/arm_backtrace_unwind.c:632
sched_backtrace …
```

misc/rpmsgdev: Fix invalid pointer error

---

Documentation/components/drivers/special/syslog.rst
arch/arm/src/armv7-m/arm_itm_syslog.c
arch/arm/src/armv8-m/arm_itm_syslog.c
drivers/syslog/syslog.h
drivers/syslog/syslog_channel.c
drivers/syslog/syslog_consolechannel.c
drivers/syslog/syslog_devchannel.c
drivers/syslog/syslog_filechannel.c
drivers/syslog/syslog_initialize.c
include/nuttx/syslog/syslog.h

syslog/channel: rename syslog_channel() to syslog_channel_register()
Change syslog API naming more reasonable:
1. rename syslog_channel() to syslog_channel_register()
2. rename syslog_channel_remove() to syslog_channel_unregister()
N/A
ci-check

syslog/channel: rename syslog_channel() to syslog_channel_register()

---

drivers/modem/alt1250/alt1250.c

Fix issue where the program would get stuck
if an unsupported ALTCOM packet was sent.
Only ALT1250 driver.

drivers/modem/alt1250: Fix issue where the program would get stuck

---

cmake/nuttx_add_library.cmake

avoid duplicate definitions of target when
`nuttx_add_extra_library` is called between different models at the same time
```shell
CMake Error at cmake/nuttx_add_library.cmake:220 (add_library):
add_library cannot create imported target
"_home_data_prebuilts_gcc_linux_arm_bin____lib_gcc_arm_none_eabi_13_2_1_thumb_v7ve_simd_hard_libgcc_a"
because another target with the same name already exists.
Call Stack (most recent call first):
cmake/nuttx_add_library.cmake:208 (nuttx_library_import)
cmake/nuttx_toolchain.cmake:103 (nuttx_add_extra_library)
arch/arm/src/cmake/platform.cmake:76 (nuttx_find_toolchain_lib)
CMakeLists.txt:416 (include)
CMake Error at cmake/nuttx_add_library.cmake:220 (add_library):
add_library cannot create imported target …
```

cmake(bugfix):make sure the extra_lib only added once

---

sched/mqueue/mq_rcvinternal.c
sched/mqueue/mq_sndinternal.c
sched/mqueue/msgrcv.c
sched/mqueue/msgsnd.c
sched/paging/pg_miss.c
sched/sched/sched.h
sched/sched/sched_removereadytorun.c
sched/semaphore/sem_wait.c
sched/signal/sig_suspend.c
sched/signal/sig_timedwait.c
sched/task/task_exit.c

In the scenario of active waiting, context switching is inevitable, and we can eliminate redundant judgments.
code size
before
size nuttx
262848   49985   63893  376726   5bf96 nuttx
after
size nuttx
263324   49985   63893  377202   5c172 nuttx
reduce code size by  -476
$ make

sched: add nxsched_remove_self

---

net/usrsock/usrsock.h
net/usrsock/usrsock_close.c
net/usrsock/usrsock_conn.c
net/usrsock/usrsock_event.c

Clear usockid when USRSOCK_EVENT_ABORT is received.
When usrsock receives a USRSOCK_EVENT_ABORT, it determines that the usrsock daemon's socket is closed. Then usrsock clears the usockid.
usrsock

net/usrsock: Clear usockid when USRSOCK_EVENT_ABORT is received

---

libs/libc/misc/lib_pathbuffer.c

libc/pathbuffer: fix build warning on tasking
```
[263/1096] Building C object libs/libc/CMakeFiles/c.dir/misc/lib_pathbuffer.c.obj
ctc W574: ["libs/libc/misc/lib_pathbuffer.c" 144/3] 'return' with an expression in function returning void
```
Commit:
https://github.com/apache/nuttx/pull/12969/files#diff-6cd9ed22f42280c9ebc90642c0b44fbc0d1d90c7e58700110ceefd229d79b02aR144
N/A
ci-check

libc/pathbuffer: fix build warning on tasking

---

arch/tricore/src/common/tricore_doirq.c
arch/tricore/src/common/tricore_svcall.c

arch/tricore: fix build error on tricore
ctc E333: ["arch/tricore/src/common/tricore_svcall.c" 123/23] incompatible types at assignment
ctc E333: ["arch/tricore/src/common/tricore_doirq.c" 98/39] incompatible types at argument #2
Regression by:
https://github.com/apache/nuttx/pull/13423
N/A
ci-check

arch/tricore: fix build error on tricore

---

drivers/rpmsg/rpmsg.c

1. Using safe list iterating in rpmsg_device_created()
2. Fix a typo error of rpmsg_device_destory()
- Log
```
[ap] kasan_report: kasan detected a read access error, address at 0x40b7ae78,size is 8, return address: 0x402a3c50
[ap] kasan_show_memory: Shadow bytes around the buggy address:
[ap] kasan_show_memory:   0x40b7ae20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ap] kasan_show_memory:   0x40b7ae30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ap] kasan_show_memory:   0x40b7ae40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ap] kasan_show_memory:   0x40b7ae50: 20 af b7 40 00 00 00 00 c0 17 2a 40 00 00 00 00
[ap] kasan_show_memory:   0x40b7ae60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ap] kasan_show_memory:   0x40b7ae70: 00 00 00 00 00 00 00 00[b0 f7 b3 40 00 00 …
```

drivers/rpmsg: Using safe list iterating in rpmsg_device_created() to fix list access after delete error

---

CMakeLists.txt
arch/arm/src/cmake/platform.cmake
arch/arm64/src/cmake/platform.cmake
arch/risc-v/src/cmake/platform.cmake
arch/tricore/src/cmake/platform.cmake
arch/x86_64/src/cmake/platform.cmake

CMake/preprocess: fix typo PREPROCES -> PREPROCESS
correct the marco define from PREPROCES to PREPROCESS
N/A
ci-check

CMake/preprocess: fix typo PREPROCES -> PREPROCESS

---

arch/arm/src/armv6-m/arm_svcall.c
arch/arm/src/armv7-m/arm_svcall.c
arch/arm/src/armv8-m/arm_svcall.c

we should use tcb->xcp.regs instead of up_current_regs() as the basis for judging whether to call restore_critical_section.
This commit fixes the regression from https://github.com/apache/nuttx/pull/13444
arm6-m
arm7-m
arm8-m
ostest

arm: we should use tcb->xcp.regs instead of up_current_regs()

---

net/tcp/tcp_timer.c

The conn->keeptimer units is decisecond，but its unit is treated as half-second in the tcp_timer & tcp_get_timeout function.
This question was asked here:
https://github.com/apache/nuttx/issues/13493
Only affects the TCP keepalive mechanism.
Local packet capture verification.

net/tcp: Fix TCP keepalive time unit misuse problem

---

drivers/mmcsd/mmcsd_sdio.c

This corrects the setting widebus for SD cards, which was recently broken in 4f7f751d2adaa.
The if checking the priv->caps, priv->buswidth and IS_MMC has been wrong for some time. The proper logic is that for MMC only the priv->caps is checked. For SD card, both priv->caps and priv->buswidth need to be checked.
SD-cards with 4-bit bus
Tested on i.MX93 and MPFS platforms

drivers/mmcsd/mmcsd_sdio.c: Fix setting SDIO_WIDEBUS for SD cards

---

tools/ci/platforms/msys2.sh

Bumps esptool from 4.7.0 to 4.8.0.
Switch wget to cURL tool for:
arm_gcc_toolchain()
arm64_gcc_toolchain()
riscv_gcc_toolchain()
sparc_gcc_toolchain()
xtensa_esp32_gcc_toolchain()
xtensa_esp32s2_gcc_toolchain()
xtensa_esp32s3_gcc_toolchain()
Used git clone --depth 1 a shallow clone with a history truncated to reduce the clone size for:
gen_romfs()
kconfig_frontends()
CI
[GitHUB](https://github.com/simbit18/nuttx-testing-ci/actions/runs/11033341894/job/30644357880)
local msys2

ci/platforms/msys2.sh: update esptool version and switch Wget to cURL tool

---

arch/arm/src/xmc4/hardware/xmc4_eru.h
arch/arm/src/xmc4/hardware/xmc4_eru_pinmap.h
arch/arm/src/xmc4/hardware/xmc4_posif.h

Added for futur lower-half driver developpement work, the register map of ERU and POSIF peripherals. 
From the Ref. Manuals for both XMC45 and XMC4[7-8] arch.
- added `hardware/xmc4_eru.h` : The register map of the Event Request Unit
- added `hardware/xmc4_eru_pinmap.h` : Helpers define to link pin to ERU inputs.
- added `ardware/xmc4_posif.h` : The register map of the Position Interface Unit
No impact
Compile correctly

[arm/xmc4] added register description for ERU and POSIF peripherals

---

arch/risc-v/src/common/riscv_initialstate.c

The logical CPU index should be retrieved with up_cpu_index(); the riscv_mhartid() returns the actual hart id of the SoC.
For mpfs target for example, NuttX can run on a single HART, for example on mhartid 2, but there is still just one logical CPU for the NuttX.
risc-v target with more than 1 hart, NuttX running on some other than hartid 0
Tested on mpfs platform, running NuttX on hart 2

arch/risc-v/src/common/riscv_initialstate.c: Fix stack pointer in coloration

---

drivers/rpmsg/rpmsg.c

drivers/rpmsg: replace metal_list_for_each to safety version
replace metal_list_for_each to safety version to avoid invalid access to deleted node in destory flow
N/A
ci-check

drivers/rpmsg: replace metal_list_for_each to safety version

---

arch/risc-v/src/mpfs/hardware/mpfs_mpucfg.h

Now all registers are defined
Add some missing MPFS MPU config register definitions. This is a cherry-pick from TII repositories.
Only MPFS
Tested on custom MPFS boards

mpfs_mpucfg.h: Add missing MPUCFG registers

---

arch/risc-v/src/mpfs/mpfs_entrypoints.c
arch/risc-v/src/mpfs/mpfs_entrypoints.h
arch/risc-v/src/mpfs/mpfs_opensbi.c

These are opensbi related fixes for MPFS platform, mainly to support custom bootloaders. 
- Provides a function which nuttx-based bootloader can call to obtain info whether the SW running on a hart is controlled by opensbi
- Uses sbi_types.h to have compatible types when initializing opensbi from within the mpfs.
MPFS w. opensbi only
Tested on custom mpfs hw

Mpfs opensbi fixes

---

Documentation/components/drivers/special/syslog.rst
arch/arm/Kconfig
arch/arm/src/armv7-m/arm_itm_syslog.c
arch/arm/src/armv8-m/arm_itm_syslog.c
boards/arm/stm32/clicker2-stm32/src/stm32_appinit.c
drivers/segger/syslog_rtt.c
drivers/syslog/Kconfig
drivers/syslog/ramlog.c
drivers/syslog/syslog.h
drivers/syslog/syslog_channel.c
drivers/syslog/syslog_chardev.c
drivers/syslog/syslog_consolechannel.c
drivers/syslog/syslog_devchannel.c
drivers/syslog/syslog_device.c
drivers/syslog/syslog_filechannel.c
drivers/syslog/syslog_flush.c
drivers/syslog/syslog_putc.c
drivers/syslog/syslog_rpmsg.c
drivers/syslog/syslog_stream.c
drivers/syslog/syslog_write.c
include/nuttx/segger/rtt.h
include/nuttx/syslog/ramlog.h
include/nuttx/syslog/syslog.h
include/nuttx/syslog/syslog_rpmsg.h

syslog/channel: add constant attribute if SYSLOG_IOCTL is not enabled
move all private channel define from data to rodata
N/A
ci-check

syslog/channel: add constant attribute if SYSLOG_IOCTL is not enabled

---

fs/mmap/fs_rammap.c

**Why is this change necessary**
When restoring rammap fpos, we check the return value to avoid potential problems caused by no error return if the restore fails.
**Changes**
Check when restoring fpos to ensure the restoration is correct
**Is a new feature added?**: NO
**Impact on build**: NO
**Impact on hardware**:NO, this change does not specifically target any particular hardware architectures or boards.
**Impact on documentation**: NO,This patch does not introduce any new features
**Impact on compatibility**: This implementation aims to be backward compatible. No existing functionality is expected to be broken.
ostest OK
```
End of test memory usage:
VARIABLE  BEFORE   AFTER
======== ======== ========
arena     3fffff8  3fffff8
ordblks …
```

fs_rammap:Check last fileseek restore fpos

---

arch/risc-v/src/common/riscv_cpuindex.c
arch/risc-v/src/common/riscv_fpucmp.c

If CONFIG_SMP is not enabled, riscv_cpuindex.c will not be compiled anyway.
And for CONFIG_ARCH_FPU, if it's not enabled, riscv_fpucmp.c will not be compiled.
So we can remove the unnecessary macro guard for up_cpu_index() and up_fpucmp().
Minor
CI

riscv: Remove some unnecessary macro guards

---

audio/pcm_decode.c

- I noticed that caps is not correctly initialized.
- None
- Tested with spresense:wifi_smp + nxplayer

audio: Fix caps initialization in pcm_enqueuebuffer()

---

tools/ci/platforms/linux.sh
tools/ci/platforms/ubuntu.sh

Switch wget to cURL tool for:
arm_gcc_toolchain()
arm64_gcc_toolchain()
riscv_gcc_toolchain()
sparc_gcc_toolchain()
xtensa_esp32_gcc_toolchain()
xtensa_esp32s2_gcc_toolchain()
xtensa_esp32s3_gcc_toolchain()
wasi_sdk()
Used git clone --depth 1 a shallow clone with a history truncated to reduce the clone size for:
kconfig_frontends()
CI

ci/platforms: linux.sh ubuntu.sh switch Wget to cURL tool

---

tools/ci/platforms/darwin.sh

Switch wget to cURL tool for:
arm_gcc_toolchain()
arm64_gcc_toolchain()
gperf()
riscv_gcc_toolchain()
sparc_gcc_toolchain()
xtensa_esp32_gcc_toolchain()
wasi_sdk()
Used git clone --depth 1 a shallow clone with a history truncated to reduce the clone size for:
kconfig_frontends()
added ninja installation
CI
[my repository](https://github.com/simbit18/nuttx-testing-ci/actions/runs/11049176986/job/30694258680)

ci/platforms/darwin.sh: switch Wget to cURL tool

---

crypto/CMakeLists.txt
crypto/Makefile

greenhills: fix the arc4random_buf implicit declaration build error
the detailed build error are:
"nuttx/include/crypto/curve25519.h", line 44: error #223-D:
function arc4random_buf declared implicitly
arc4random_buf(secret, CURVE25519_KEY_SIZE);
^
2. has tested on gcc/ghs compiler

greenhills support: fix the arc4random build error

---

arch/arm/src/common/gnu/arm_signal_handler.S

fix the arm_signal_handler.S build error with greenhills compiler
the detailed build error are:
```
[asarm] (error #2067) 
nuttx/arch/arm/src/common/gnu/arm_signal_handler.S 35: unknown instruction
.syntax unified
--^
[asarm] (error #2067) 
nuttx/arch/arm/src/common/gnu/arm_signal_handler.S 70: unknown instruction
.thumb_func
--^
[asarm] (error #2230) 
nuttx/arch/arm/src/common/gnu/arm_signal_handler.S 72: bad directive
.type up_signal_handler , function
----------------------------^
```
2. has tested on ghs and gcc compiler

greenhills support: fix the arm_signal_handler.S build error

---

arch/arm64/src/imx8/imx8qm_lowputc.S

Function `arm64_lowputc` corrupted the x1 register which is used in function `boot_stage_puts`.
System hangs when early print is enabled.
`imx8qm-mek` board.

imx8qm-mek: Fix early print

---

drivers/bch/bchdev_driver.c

Passing `BIOC_FLUSH` to block driver to ensure that changes transfers ("flushes") to the block device.
**Background**
There was a problem when executing the `fastboot flash <PARTITION> <IMAGE>` command, if reset the device immediately after the flash is completed, there is a certain probability that the data is not written to the flash.
The patch([nuttx-apps/6ac7cbf4d263e8bf6fa39eb0e070b0bbb47fe3a0](https://github.com/apache/nuttx-apps/commit/6ac7cbf4d263e8bf6fa39eb0e070b0bbb47fe3a0))  call `fsync()` after flash completed to fix, but the problem still exists.
**About fsync() (glibc) FSYNC(2):**
fsync()  transfers  ("flushes")  all modified in-core data of (i.e., modified buffer cache pages for) the file referred to by the file descriptor fd to the disk device (or other permanent storage …

BCH: Passing `BIOC_FLUSH` to block driver

---

arch/arm64/src/common/arm64_arch.h
arch/arm64/src/common/arm64_fatal.c
arch/arm64/src/common/arm64_fatal.h
arch/arm64/src/common/arm64_vector_table.S
arch/arm64/src/common/arm64_vectors.S

1. Summary
The original implement for exception handler is very simple and
haven't framework for breakpoint/watchpoint routine or brk instruction.
I refine the fatal handler and add framework for debug handler to
register or unregister. this is a prepare for watchpoint/breakpoint implement
2. add arm64_current_el to obtain current EL]

arm64: refine the fatal handler

---

arch/arm/src/armv7-m/Toolchain.defs
arch/arm/src/common/Toolchain.defs

1. add cortex-m platform support in Makefile build for greenhills compiler
2. add greenhills specific compiler optimization build option: Osize
2. has tested on ghs and gcc compiler

greenhills support: add cortex-m4 Makefile support for ghs compiler

---

fs/vfs/fs_fcntl.c
libs/libc/modlib/modlib_bind.c
libs/libc/pthread/pthread_mutexattr_setprotocol.c
libs/libc/search/hcreate.c

1. fix the moblib_bind variable uninit misra issue
2. remove the unreached dead code in  pthread_mutexattr_setprotocol
3. fix using the uninit value misra issue in hcreate
4. fix the ret value not check erro on fs_fcntl
5. has checked on ghs and gcc compiler

fix the misra check issues

---

drivers/can/can.c
include/nuttx/can/can.h

Merge cd_error and rx_overflow into rx_error so the error could dispath to each client without interference
test with the borad uesd cortex-M7 architecture.

Merge cd_error and rx_overflow into rx_error.

---

arch/arm/src/arm/arm_doirq.c
arch/arm/src/armv6-m/arm_doirq.c
arch/arm/src/armv7-a/arm_doirq.c
arch/arm/src/armv7-a/arm_syscall.c
arch/arm/src/armv7-m/arm_doirq.c
arch/arm/src/armv7-r/arm_doirq.c
arch/arm/src/armv7-r/arm_syscall.c
arch/arm/src/armv8-m/arm_doirq.c
arch/arm/src/armv8-r/arm_doirq.c
arch/arm/src/armv8-r/arm_syscall.c
arch/arm/src/common/arm_switchcontext.c
arch/arm64/src/common/arm64_doirq.c
arch/arm64/src/common/arm64_switchcontext.c
arch/arm64/src/common/arm64_syscall.c
arch/ceva/src/common/ceva_doirq.c
arch/ceva/src/common/ceva_switchcontext.c
arch/risc-v/src/common/riscv_doirq.c
arch/risc-v/src/common/riscv_switchcontext.c
arch/x86/src/qemu/qemu_handlers.c
arch/x86_64/src/common/x86_64_switchcontext.c
arch/x86_64/src/intel64/intel64_handlers.c
arch/xtensa/src/common/xtensa_irqdispatch.c
arch/xtensa/src/common/xtensa_switchcontext.c

arch: change nxsched_suspend/resume_scheduler() called position
for the citimon stats:
```
thread 0:                     thread 1:
enter_critical (t0)
up_switch_context
note suspend thread0 (t1)
thread running
IRQ happen, in ISR:
post thread0
up_switch_context
note resume thread0 (t2)
ISR continue f1
ISR continue f2
...
ISR continue fn
leave_critical (t3)
```
You will see, the thread 0, critical_section time is: (t1 - t0) + (t3 - t2)
BUT, this result contains f1 f2 .. fn time spent, it is wrong to tell user thead0 hold the critical lots of time but actually not belong to it.
Resolve:
change the nxsched_suspend/resume_scheduler to real hanppends
critmon
qemu
./tools/configure.sh mps2-an500:nsh -j8

arch: change nxsched_suspend/resume_scheduler() called position

---

cmake/nuttx_add_romfs.cmake

The current romfs cmake method **only** supports adding relative paths to the etc path.
```cmake
list(APPEND RCSRCS etc/init.d/rcS etc/init.d/rc.sysinit)
list(APPEND RCRAWS etc/media/media.conf)
nuttx_add_romfs(
NAME
etc
MOUNTPOINT
etc
RCSRCS
${RCSRCS}
RCRAWS
${RCRAWS}
PATH
${CMAKE_CURRENT_BINARY_DIR}/etc)
``` 
This patch supports adding romfs files with absolute paths at any location.
Because different boards on the same chip platform may have common board-level configurations, a common romfs file needs to be added
Usage after this patch:
```cmake
add_board_rcsrcs(${CMAKE_CURRENT_SOURCE_DIR}/etc/build.prop)
add_board_rcraws(${CMAKE_CURRENT_SOURCE_DIR}/etc/video_config.json)
nuttx_add_romfs(
NAME
etc
MOUNTPOINT
etc
RCSRCS
etc/srcfile
RCRAWS
etc/rawfile
PATH …
```

cmake(feat): Add support for etc files with absolute paths in romfs CMake module

---

arch/risc-v/include/irq.h
arch/risc-v/src/common/riscv_fork.c
arch/risc-v/src/common/riscv_swint.c

There was an error in the fork() routine when system calls are in use: the child context is saved on the child's user stack, which is incorrect, the context must be saved on the kernel stack instead.
The result is a full system crash if (when) the child executes on a different CPU which does not have the same MMU mappings active.
Only the RISC-V platform with CONFIG_LIB_SYSCALL=y is affected.
rv-virt:knsh64
rv-virt:ksmp64

riscv_fork.c: Fix vfork() for kernel mode + SMP

---

drivers/mmcsd/mmcsd_sdio.c

If CMD6 is sent again before last transmission is complete, a timeout error will be encountered.
impact cmd6 command continuous execution
test it passed on bes1600 (Cortext M55)

mmcsd: fix cmd6 timeout error when repeat called，if CMD6 is sent again before last transmission is complete, a timeout error will be encountered

---

fs/smartfs/smartfs.h
fs/smartfs/smartfs_smart.c

The `FIOC_FILEPATH` ioctl call is required if smartfs is to be used together with inotify monitoring system. This partially implements the call support to smartfs file system.
The call currently does not work correctly if subdirectories are in the file's path. For example `/dir/file` will be returned correctly, but `/dir/subdir/file` will exclude the `subdir` part and return only `/dir/file`. The full support is complicated due to the SmartFS design.
The correct procedure would be to take the inode's path obtained by inode_getpath and let SmartFS recursively get the full path from the file. However, SmartFS entries do not keep the information about their parents and it is not possible to obtain the full path by going backwards. The file system currently takes the advantage of knowing the …

smartfs: add partial support for FIOC_FILEPATH ioctl

---

libs/libc/libc.h

**Why is this change necessary**
Fixed the problem of multiple define appearing in arch_xxx.S after opening kasan
The reason is that libc.h needs to check whether CONFIG is enabled before the corresponding macro is enabled
Error scene:
```
arm-none-eabi-ld: /home/crafcat7/SSD/xxx/xxx-dev/nuttx/staging/libc.a(arch_libc.o): in function `memmove:
/home/crafcat7/SSD/xxx/xxx-dev/nuttx/libs/libc/machine/arch_libc.c:146: multiple definition of memmove`; /home/crafcat7/SSD/xxx/xxx-dev/nuttx/staging/libc.a(arch_memmove.o):/home/crafcat7/SSD/xxx/xxx-dev/nuttx/libs/libc/machine/arm/armv8-m/gnu/arch_memmove.S:56: first defined here
```
**Changes**
add `#include<nuttx/config.h>` in libc.h
**Is a new feature added?**: NO
**Impact on build**: YES,This is a fix for compilation-related issues
**Impact on …

libc.h:Fixed the problem of multiple define appearing in arch_xxx.S

---

drivers/pci/pci_epc.c
drivers/pci/pci_epc_mem.c
drivers/pci/pci_epf.c
include/nuttx/pci/pci_epc.h
include/nuttx/pci/pci_epf.h

1.pci_epf_device_s and pci_epc_ctrl_s add priv data
2.pci epf use epc_node link to epc
3.pci epc mem use virtual mem
4.pci_epf_driver_s use FAR const struct pci_epf_ops_s *ops

Pci ep 0926

---

boards/risc-v/qemu-rv/rv-virt/src/qemu_rv_appinit.c

Follow other boards, use CONFIG_LIBC_TMPDIR from Kconfig instead of hardcode it here.
Minor
CI

boards/qemu-rv: Correct tmpfs mount path to use CONFIG_LIBC_TMPDIR

---

drivers/pci/pci.c

1. pci.c：fix ops not implement after calling panic err
2. pci.c: fix judge err in pci_connect_irq
3. pci.c: add error handle for pci_alloc_bus/device

Pci framework 0926

---

drivers/analog/adc.c
include/nuttx/analog/adc.h

add adc_receive_batch for adc_dma and memcpy data directly without channel at msglen is 4
The channel and data data of the vendor layer are no longer transmitted to the fifo of the nuttx layer through a loop, but all data is transferred to the fifo at one time, which can save time.

add function of adc_receive_batch

---

arch/xtensa/src/common/xtensa_switchcontext.c

xtesa: fix lost save & restore states caused by merge code
this is caused by:
35c8c80a00a99ff0e19d51eaa74165bd830a36f8
https://github.com/apache/nuttx/pull/13651
xtensa
Test pass in QEMU:
./tools/configure.sh -E esp32-devkitc:nsh
qemu-system-xtensa -nographic -machine esp32 -drive file=nuttx.merged.bin,if=mtd,format=raw -drive file=qemu_efuse.bin,if=none,format=raw,id=efuse -global driver=nvram.esp32.efuse,property=drive,value=efuse

xtesa: fix lost save & restore states caused by merge code

---

drivers/pci/pci.c
drivers/pci/pci_ecam.c
drivers/pci/pci_qemu_test.c
include/nuttx/pci/pci_regs.h

1.pci.c: fix warning when CONFIG_PCI_ASSIGN_ALL_BUSES=n
2.pci.c: fix pci 32bit warning
3.toolchain/ghs: Fix ?? "trigraphs not allowed" warnings
4.pci_qemu_test.c: fix compiler warning
5.change all devfn type to unsigned int
6.one pci device should only associate with one driver

Pci fixbug

---

arch/risc-v/src/common/riscv_doirq.c
arch/risc-v/src/common/riscv_exit.c
arch/risc-v/src/common/riscv_internal.h
arch/risc-v/src/common/riscv_sigdeliver.c
arch/risc-v/src/common/riscv_swint.c
arch/risc-v/src/common/supervisor/riscv_perform_syscall.c

This commit fixes the regression from https://github.com/apache/nuttx/pull/13561
In order to determine whether a context switch has occurred, we can use g_running_task to store the current regs. This allows us to compare the current register state with the previously stored state to identify if a context switch has taken place.
riscv
rv-virt:knsh
rv-virt:knsh64
rv-virt:smp

riscv: use g_running_task store current regs

---

include/nuttx/compiler.h

fix the armv7-m/irq register variable usage error
the detailed build error info are:
```
CXX:  libcxxmini/libxx_new.cxx "nuttx/include/arch/armv7-m/irq.h", line 594: error #3422:
use of the "register" storage class specifier is not allowed
register uint32_t sp;
^
"nuttx/include/arch/armv7-m/irq.h", line 594: error #3422:
use of the "register" storage class specifier is not allowed
register uint32_t sp;
^
"nuttx/include/arch/armv7-m/irq.h", line 594: error #3422:
use of the "register" storage class specifier is not allowed
register uint32_t sp;
^
make[1]: *** [Makefile:69: libxx_delete_sized.o] Error 1 make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:69: libxx_deletea_sized.o] Error 1 make[1]: *** [Makefile:69: libxx_new.o] Error 1
"nuttx/include/arch/armv7-m/irq.h", …
```

greenhills support: fix the register variable usage error

---

libs/libxx/CMakeLists.txt
libs/libxx/Makefile

Fixed https://github.com/apache/nuttx/issues/13648
The problem is that when LIBCXXTOOLCHAIN ​​is enabled, LIBCXXMINI is included in the compilation. This causes a conflict between the void* operator new in the toolchain and the LIBCXXMINI.
When LIBCXXTOOLCHAIN ​​is enabled in the configuration, the version provided by the toolchain should be used.
```
P:➜  nuttx git:(4cec713dbf) LC_ALL=C make
CC:  chip/stm32_gpio.c chip/stm32_gpio.c:41:11: note: '#pragma message: CONFIG_STM32_USE_LEGACY_PINMAP will be deprecated migrate board.h see tools/stm32_pinmap_tool.py'
41 | #  pragma message "CONFIG_STM32_USE_LEGACY_PINMAP will be deprecated migrate board.h see tools/stm32_pinmap_tool.py"
|           ^~~~~~~
CXX:  libcxxmini/libxx_new.cxx libcxxmini/libxx_new.cxx:72:11: error: redefinition of …
```

libxx:fix build error when enable LIBCXXTOOLCHAIN

---

fs/procfs/fs_procfs.c

when try to cat a dirctory, will cause a crash.
ap> cat pm
================================================================= ==30235==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf436edd9 at pc 0x03338a48 bp 0x9d1b6ca8 sp 0x9d1b6c98 READ of size 1 at 0xf436edd9 thread T0
#0 0x3338a47 in strncmp string/lib_strncmp.c:42
#1 0x371af87 in pm_get_file_index power/pm/pm_procfs.c:174
#2 0x371b066 in pm_open power/pm/pm_procfs.c:207
#3 0x3640d20 in procfs_open procfs/fs_procfs.c:419
#4 0x359bce2 in file_vopen vfs/fs_open.c:240
#5 0x359c431 in nx_vopen vfs/fs_open.c:312
#6 0x359cb53 in open vfs/fs_open.c:465
#7 0x33bccc9 in nsh_catfile /apps/nshlib/nsh_fsutils.c:140
#8 0x33b28cc in cmd_cat /apps/nshlib/nsh_fscmds.c:556
#9 0x33a434f in nsh_command /apps/nshlib/nsh_command.c:1164
#10 …

procfs:fix cat dir cause crash

---

libs/libm/openlibm/0003-nuttx-openlibm-Fix-openlibm-M_PI-undeclared-error.patch
libs/libm/openlibm/Make.defs

1. nuttx/libm: Move define __BSD_VISIBLE to openlibm_math.h
1. has no impact on current implementation

nuttx/libm: Move define __BSD_VISIBLE to openlibm_math.h

---

arch/sim/src/sim/sim_smpsignal.c
sched/init/nx_smpstart.c
sched/sched/sched_smp.c

sched_smp:sync refcount before enqueue smp call queue
sched_smp:adjust the critical section to protect refcount from multi cores access
fix build error when sim SMP
CC:  sim/sim_smpsignal.c init/nx_smpstart.c: In function ‘nx_idle_trampoline’:
init/nx_smpstart.c:68:21: warning: unused variable ‘tcb’ [-Wunused-variable]
68 |   FAR struct tcb_s *tcb = this_task_inirq();
|                     ^~~
sim/sim_smpsignal.c: In function ‘host_cpu_started’:
sim/sim_smpsignal.c:271:17: warning: unused variable ‘tcb’ [-Wunused-variable]
271 |   struct tcb_s *tcb = this_task();
sim/sim_smpsignal.c:249:33: error: ‘cpu’ undeclared (first use in this function)
249 |   restore_critical_section(tcb, cpu);
|                                 ^~~
SMP call more safe,
SIM able to enable SMP
CI test

sched optimise for sim, CONFIG_SCHED_INSTRUMENTATION to CONFIG_SCHED_INSTRUMENTATION_SWITCH

---

arch/CMakeLists.txt

fix the arch_interface archive error with greenhills cmake build
the detailed build error are:
```
: && cxarm cr arch/libarch_interface.a  arch/CMakeFiles/arch_interface.dir/arm/src/common/gnu/arm_signal_handler.S.obj  && echo arch/libarch_interface.a && : [elxr] (error #16) cannot find file cr
```
2. has tested on ghs and gcc compiler

greenhills support: fix the arch_interface archive error

---

include/nuttx/pci/pci_regs.h

fix the ?? "trigraphs not allowed" build warnings with greenhills compiler
the detailed build warning are:
```
"/mnt/yang/qixinwei_vela_warnings_04_23/nuttx/include/nuttx/pci/pci_regs.h", line 263: warning #1695-D:
trigraphs not allowed
#define  PCI_PM_CTRL_DATA_SEL_MASK        0x1e00  /* Data select (??) */
^
"/mnt/yang/qixinwei_vela_warnings_04_23/nuttx/include/nuttx/pci/pci_regs.h", line 264: warning #1695-D:
trigraphs not allowed
#define  PCI_PM_CTRL_DATA_SCALE_MASK      0x6000  /* Data scale (??) */
^
"/mnt/yang/qixinwei_vela_warnings_04_23/nuttx/include/nuttx/pci/pci_regs.h", line 266: warning #1695-D:
trigraphs not allowed
#define PCI_PM_PPB_EXTENSIONS             6       /* PPB support extensions (??) */
^
"/mnt/yang/qixinwei_vela_warnings_04_23/nuttx/include/nuttx/pci/pci_regs.h", …
```

greenhills support: Fix ?? "trigraphs not allowed" warnings

---

arch/xtensa/src/common/xtensa.h
arch/xtensa/src/common/xtensa_cpupause.c
arch/xtensa/src/common/xtensa_irqdispatch.c
arch/xtensa/src/common/xtensa_schedsigaction.c
arch/xtensa/src/common/xtensa_swint.c
arch/xtensa/src/common/xtensa_switchcontext.c

Why
When a context switch occurs currently, the context before the interrupt is fetched from the global variable g_current_regs and then stored in the corresponding tcb->xcp.regs. Subsequently, the new context is assigned to g_current_regs. When returning from the interrupt context, the context is retrieved from g_current_regs and used.
In reality, we do not necessarily require this intermediate variable g_current_regs to accomplish a context switch. Eliminating it avoids multiple assignments, especially during multiple context switches within interrupts, which can lead to repeated assignments.
All we need is to work directly with the context of the currently running task. This approach enhances the speed of context switching, reduces the code base, and optimizes signal handling logic. By …

xtensa: g_current_regs is only used to determine if we are in irq,

---

include/nuttx/timers/timer.h

fix the nuttx/timers timer.h build error with greenhills compiler
the detailed error info are:
```
"/mnt/yang/qixinwei_commit/nuttx/include/nuttx/timers/timer.h", line 257: error #223-D:
function DEBUGASSERT declared implicitly
DEBUGASSERT(lower->ops->tick_getstatus);
```
2. has tested on ghs and gcc compiler

greenhills support: Fix green hills build timer.h error

---

sched/Kconfig

1. disable RW_SPINLOCK by default

nuttx/sched: Disable RW_SPINLOCK by default

---

Documentation/platforms/arm/stm32f3/index.rst
Documentation/platforms/arm/stm32f4/index.rst
Documentation/platforms/arm/stm32f7/index.rst

* Information on how to flash NuttX firmware to STM32F[3,4,7] target were missing and asked by new users.
* Example on how to flash/reset/debug is now added to the docs.
* Documentation: added information on how to flash nuttx firmware to STM32F[3,4,7].
Local Sphinx build: OK.

DOC: STM32F3 add example flashing information.

---

libs/libm/libm/lib_powf.c

1. fix the powf function param incompatible error

nuttx/libm: Fix powf wrong if first parameter is negative

---

arch/sim/src/sim/sim_oneshot.c

when CONFIG_PM and CONFIG_CPULOAD_ONESHOT are defined sim_cancel may assert:
sim_cancel may assert:
[429492.185400] [ 0] [ EMERG] [ap] _assert: Current Version: NuttX ap 12.3.0 5ffeb16111-dirty Dec 4 2023 14:32:27 sim
[429492.185400] [ 0] [ EMERG] [ap] _assert: Assertion failed : at file: sim/sim_oneshot.c:367 task: Idle_Task process: Kernel 0x323254d
[429492.185400] [ 0] [ EMERG] [ap] backtrace:
[429492.185400] [ 0] [ EMERG] [ap] [ 0] [<0xf7941ad5>] _fini+0xf0753010/0xf8e1155b
[429492.185400] [ 0] [ EMERG] [ap] [ 0] [<0x71def50>] host_backtrace+0x41/0x72
[429492.185400] [ 0] [ EMERG] [ap] [ 0] [<0x65b68bd>] up_backtrace+0x126/0x2f8
[429492.185400] [ 0] [ EMERG] [ap] [ 0] [<0x6554ceb>] sched_backtrace+0x70/0x8a
[429492.185400] [ 0] [ EMERG] [ap] [ 0] [<0x37585d2>] …

sim:fix oneshot sim_cancel assert

---

arch/xtensa/src/esp32s3/esp32s3_tim.c

On ESP32S3, only timer group 0 is initialized.
This MR fixes timer group 1 initialization.
Allows use of timers 3 and 4 on ESP32S3.
Timer example with timers 1-4 using the `timers` defconfig.
Internal CI testing.

arch/xtensa/esp32s3: fix timer group 1 initialization

---

fs/vfs/fs_epoll.c
fs/vfs/fs_poll.c

fs/poll: add debug log for poll/epoll failed
N/A
Vela

fs/poll: add debug log for poll/epoll failed

---

drivers/power/pm/CMakeLists.txt
drivers/serial/serial.c
include/nuttx/power/pm_runtime.h

add runtimepm in cmake
when CONFIG_SERIAL_PM_ACTIVITY_PRIORITY == 0 disable pm_activity
add extern C for public api
runtime pm able to use in cxx, runtimepm able to use in cmake
CI-test

pm & runtime pm bugfix 

---

drivers/note/note_driver.c
drivers/note/noteram_driver.c
drivers/syslog/ramlog.c
include/nuttx/sched_note.h

The noteram have bugs.
when ramnote flush, we should reset the tail of reader.
make noteram aligned, fix un-aligned write operation report by coverity.
Bug fixed after patch
CI-test

fix bugs about noteram about alignment, fix the tail of reader did not reset when flush.

---

drivers/sensors/sensor.c
drivers/sensors/sensor_rpmsg.c

drivers/sensors: bug fix about sensor and sensor rpmsg driver
bug fix
Vela

drivers/sensors: bug fix about sensor and sensor rpmsg driver

---

arch/xtensa/src/esp32s3/Kconfig
boards/xtensa/esp32s3/common/src/esp32s3_lan9250.c
drivers/net/lan9250.c
include/nuttx/net/lan9250.h

arch/xtensa/esp32s3: 
1. Configure the number of universal management (IEEE) MAC addresses when there are multiple interfaces.
2. Optimize Lan9250 to adapt to ESP32S3 universal MAC address.
This PR refers to PR[#8993](https://github.com/apache/nuttx/pull/8993)
The defconfig settings have not been modified.
Provide universal mac addresses support for esp32s3 LAN9250.
esp32s3-devkit:eth_lan9250

boards/esp32s3_lan9250: configure ethernet universally MAC address

---

drivers/devicetree/CMakeLists.txt
drivers/devicetree/Make.defs
drivers/devicetree/fdt_pci.c
include/nuttx/fdt.h

So the borad level do not need implement the
pci_ecam_register_from_fdt() again and again.

devicetree/fdt_pci: implement the fdt_pci_ecam_register()

---

arch/arm/src/armv7-a/arm_timer.c
arch/arm/src/armv7-r/arm_timer.c

Only one timer will be effective at a time.In the current implementation of NuttX's timer handling, only a single global timer is necessary. Having an excessive number of timers can lead to additional performance overhead and logical errors, especially when operating in SMP (Symmetric Multi-Processing) tickless mode.
armv7a/r
./tools/configure.sh -l qemu-armv7a:smp

armv7a/r: fix use arch-timer in SMP

---

crypto/cryptodev.c
include/crypto/cryptodev.h

1. The crypto driver implements the poll interfaces
2. Provides a new cmd to obtain asynchronous results
3. Adds krp flags to indicate that this operation is an asynchronous operation
The above new functions can be used to implement the asynchronous call function of the crypto driver.
Currently, only asymmetric encryption functions are used because they generally take a long time.
N/A
ci & add new crypto testcase https://github.com/apache/nuttx-apps/pull/2616

nuttx/crypto: export asynchronous calling process

---

drivers/pipes/pipe_common.c
drivers/pipes/pipe_common.h

drivers/pipes: using rmutex to protect pipe and avoid deadlock
The backtrace when bug occurs:(signal break current stack, and write pipe in signal handler)
```
nxsem_wait
nuttx/sched/semaphore/sem_wait.c:176
nxmutex_lock
nuttx/libs/libc/misc/lib_mutex.c:204 (discriminator 2) pipecommon_write
nuttx/drivers/pipes/pipe_common.c:538 (discriminator 2) file_write
nuttx/fs/vfs/fs_write.c:91
write
nuttx/include/unistd.h:523 (discriminator 2)
nxsig_deliver
nuttx/sched/signal/sig_deliver.c:170 (discriminator 4) arm_sigdeliver
nuttx/arch/arm/src/armv7-a/arm_sigdeliver.c:107
irq_waitlock
nuttx/sched/irq/irq_csection.c:204
nxsem_post
nuttx/sched/semaphore/sem_post.c:86 (discriminator 2) nxmutex_unlock
nuttx/libs/libc/misc/lib_mutex.c:339 (discriminator 2) pipecommon_poll …
```

drivers/pipes: using rmutex to protect pipe and avoid deadlock

---

net/devif/devif.h
net/devif/devif_callback.c

modified reason:tcp_shutdown_monitor releases the callback related to the TCP connection. the callback is to be executed nextly by devif_dev_event, therefore devif_dev_event have no access to it
devif_dev_event
solve problem

devif:fix issue about devif_callback being released wrongly,resulting in no access to it

---

Documentation/components/drivers/index.rst
Documentation/implementation/device_drivers.rst
Documentation/implementation/drivers_design.rst
Documentation/implementation/index.rst

Migrate  a few more pages from wiki to Documentation.
Migrated pages are drivers related:
https://cwiki.apache.org/confluence/display/NUTTX/Driver+Types
https://cwiki.apache.org/confluence/display/NUTTX/Upper+Half+and+Lower+Half+Drivers
https://cwiki.apache.org/confluence/display/NUTTX/Device+Drivers+vs.+Bus+Drivers+and+GPIO+Drivers
Update Documentation only

Documentation: migrating a few more pages from wiki

---

drivers/misc/rpmsgdev.c
drivers/misc/rpmsgdev.h

misc/rpmsgdev: add new cmd support for rpmsg device.
FIOC_FILEPATH: get path from remote device
BATIOC_GET_PROTOCOL/BATIOC_OPERATE/BATIOC_STATE: get battery info from remote charger
N/A
Vela

misc/rpmsgdev: add new cmd support for rpmsg device

---

tools/nxstyle.c

Add the new symbol `NativeSymbol` to the white list, and update the comments about the symbols that are from WAMR project.
Minor
CI, local

nxstyle: Add NativeSymbol to white list

---

arch/arm64/Kconfig
arch/arm64/src/common/arm64_arch.h
arch/arm64/src/common/arm64_cpustart.c
arch/arm64/src/common/arm64_gicv3.c
arch/arm64/src/common/arm64_head.S

arm64: changing the startup of arm64 SMP from serial to parallel
arm64
before
262624   49985   63638  376247   5bdb7 nuttx
after
262176   49921   63630  375727   5bbaf nuttx
size -520
ostest

arm64: changing the startup of arm64 SMP from serial to parallel

---

include/nuttx/timers/timer.h

fix a small error in Non-Gnu compiler build
"/mnt/xxxx/nuttx/include/nuttx/timers/timer.h", line 257: error #223-D:
function DEBUGASSERT declared implicitly
DEBUGASSERT(lower->ops->tick_getstatus);
None
Green hills build

nuttx/timers: Fix green hills build timer.h error

---

libs/libc/dirent/lib_fdopendir.c

**Why is this change necessary?**
When we enable fdsan and use the fdopendir interface, because we do not update the fdsan tag in the interface, this will cause a PANIC caused by fdsan
**Changes**
Update fdsan tag in lib_fdopendir.c
```
#ifdef CONFIG_FDSAN
android_fdsan_exchange_owner_tag(fd, 0,
android_fdsan_create_owner_tag(ANDROID_FDSAN_OWNER_TYPE_DIR,
(uintptr_t)dir));
#endif
``` …

lib_fdopendir.c:Fix crash in fdopendir caused by fdsan

---

arch/arm64/src/common/arm64_fork_func.S

FORK_REG_LR,FORK_REG_SP should save the func local stack not the last func stack
not the last func stack

arm64 fork: FORK_REG_LR,FORK_REG_SP should save the func local stack

---

arch/xtensa/src/common/xtensa_cpupause.c

Register: smp
Register: nsh
Register: sh
Register: getprime
Register: ostest
Espressif HAL for 3rd Party Platforms: b4c723a119344b4b71d69819019d55637fb570fd common/xtensa_cpupause.c: In function 'xtensa_pause_handler': common/xtensa_cpupause.c:240:3: warning: implicit declaration of function 'xtensa_savestate'; did you mean 'xtensa_setps'? [-Wimplicit-function-declaration]
240 |   xtensa_savestate(tcb->xcp.regs);
|   ^~~~~~~~~~~~~~~~
|   xtensa_setps
common/xtensa_cpupause.c:243:3: warning: implicit declaration of function 'xtensa_restorestate'; did you mean 'xtensa_context_restore'? [-Wimplicit-function-declaration]
243 |   xtensa_restorestate(tcb->xcp.regs);
|   ^~~~~~~~~~~~~~~~~~~
|   xtensa_context_restore

fix compile error:

---

libs/libm/libm/lib_pow.c
libs/libm/libm/lib_powf.c
libs/libm/libm/lib_powl.c

This PR applies the pattern of calculation used for `pow` and `powf` to `powl`
Has no impact on current implementation
Pass CI

nuttx/libm: Fix powl wrong if first parameter is negative

---

Documentation/implementation/simulation.rst

Some codeblock in `implementation/simulation.rst` had code that wasn't correctly align, which result in the code not being in the code block.
Update Documentation only

Documentation: Fix code block in implementation/simulation.rst

---

Documentation/contributing/documentation.rst

Remove navigating to the Documentation folder in the section description for building the documentation, and add it to the first building steps. Also remove the command to `cd Documentation` in the second steps, which is necessary to properly install the dependencies to build the documentation.
Update Documentation only

Documentation: clarifying the workflow of building the documentation

---

Documentation/guides/citests.rst

Add `<>` for user defined variable in the command to run CI test locally. This makes it more obvious that the user needs to change those to execute the command.
Update Documentation only

Documentation: improve command doc to run CI test locally

---

tools/btdecode.sh

Allow to provide the path to elffile instead of hardcoding 'nuttx'.
E.g.
```
./nuttx/tools/btdecode.sh aarch64-none-elf-addr2line crash.log build/nuttx
```
No
Tested with crash log generated from arm64.
```
./nuttx/tools/btdecode.sh aarch64-none-elf-addr2line crash.log build/nuttx
Backtrace for task 5:
0x00000000402a1318: cmd_mw at nsh_dbgcmds.c:259
0x000000004029d47c: nsh_command at nsh_command.c:1259
0x000000004029c964: nsh_execute at nsh_parse.c:874
(inlined by) nsh_parse_command at nsh_parse.c:2840
0x000000004029ca50: nsh_parse at nsh_parse.c:2996
0x000000004029b018: nsh_session at nsh_session.c:246
0x000000004029aabc: nsh_consolemain at nsh_consolemain.c:79
0x00000000402945ac: nsh_main at nsh_main.c:80
0x0000000040298104: nxtask_startup at task_startup.c:70 (discriminator 1) …
```

tools/btdecode.sh: add optional elf file parameter

---

drivers/usbdev/cdcecm.c
drivers/usbdev/cdcncm.c

drivers/usbdev: don't send setconfig response for xxxx_setup with composite, so need call composite_ep0submit, like cdcacm and so on
Bug fix
Vela

drivers/usbdev: don't send setconfig response for xxxx_setup with composite

---

arch/risc-v/src/common/CMakeLists.txt
arch/risc-v/src/common/Make.defs

Support customize idle loop by CONFIG_ARCH_IDLE_CUSTOM as other architectures.
Then user can provide their own `up_idle()` function with CONFIG_ARCH_IDLE_CUSTOM enabled.
build system
CI

risc-v: Support customize idle loop

---

arch/arm/src/armv7-m/arm_mpu.c
arch/arm/src/armv7-r/arm_mpu.c
arch/arm/src/armv8-m/arm_mpu.c

Error: armv7-m/arm_mpu.c:211:13: error: function declaration isn't a prototype [-Werror=strict-prototypes]
211 | static void mpu_reset_internal()
|             ^~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:168: arm_mpu.o] Error 1
mpu
Compile only

armv7/8-m/r: fix build warning

---

Documentation/guides/devicetree.rst
Documentation/guides/index.rst

Add fdt description document to introdunce a libfdt modules and how to use it.
help developers to know how to use libfdt in NuttX.

fdt: add fdt description document

---

arch/xtensa/src/common/xtensa_saveusercontext.c

Currently, without the change, when assert in interrupt handler, it will show the registers are all zeros.
This PR tries to save these registers.
Try to trigger an __assert in interrupt handler.

xtensa: fix up_saveusercontext in interrupt context

---

arch/x86_64/src/Makefile
arch/x86_64/src/common/multiboot1.S
arch/x86_64/src/common/multiboot1.ld
arch/x86_64/src/intel64/intel64_head.S
boards/x86_64/intel64/qemu-intel64/scripts/qemu.ld

In the previous implementation, we had to copy the entire NuttX to ensure that the executable runs at the correct address. Additionally, we were not loading the .realmode section, which led to issues with SMP booting.
This commit reimplemented the NuttX32 multiboot1 wrapper:
1. Fixed the issue of SMP AP booting.
2. Reduced memory copy overhead. We only need to copy .realmode section now.
3. Move the multiboot1 header to intel64_head.S.
x86_64 boot.
Tested on x86_64 qemu.

arch/x86_64: Reimplement the NuttX32 multiboot1 wrapper.

---

arch/arm/src/armv7-a/arm_gicv2m.c
arch/arm64/src/common/arm64_gicv2m.c
arch/x86_64/src/common/x86_64_pci.c
arch/x86_64/src/intel64/intel64_hpet.c
arch/x86_64/src/intel64/intel64_irq.c
drivers/pci/pci.c
drivers/pci/pci_ecam.c
include/nuttx/arch.h
include/nuttx/pci/pci.h

no real functionality change, code refactor only
pci msi
qemu pci/ep

pci alloc msi irq support new interface

---

net/arp/arp_send.c
net/arp/arp_table.c

If arp search fails once, subsequent searches for the ip will directly return failure, and sends an asynchronous arp request to try to update arp table in the future. In this way, the psock_sendmsg interface will not block for a long time each time because arp cannot be obtained.
This scenario is triggered when a udp socket frequently attempts to access an ip address that does not exist on the LAN.
sim:local

net/arp: modify some flow of arp return failure

---

drivers/analog/adc.c
include/nuttx/analog/adc.h

allocating fifosize on demand to optimize memory ,no need to seting adc_fifosize unified
Allocate fifosize on demand to optimize memory & Fix the situation where af_channel is still being read after it is released

add function of allocating fifosize on adc separately

---

sched/sched/sched_smp.c

1. Fix the unlock order https://github.com/apache/nuttx/commit/f859c03325958de48f1c23c64adee538de07572a
2. Replace critical section with spinlock
3. Bypass sched_lock from interrupt context
Now can call nxsched_smp_call from interrupt context. It's will be used to call function on all foreign CPUs from assert handler in order to stop all CPUs.
arm64 qemu with ostest https://github.com/apache/nuttx-apps/pull/2628
1. Build
` cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -Bbuild -GNinja -DBOARD_CONFIG=boards/arm64/qemu/qemu-armv8a/configs/nsh_smp nuttx`
2. Launch
`qemu-system-aarch64 -smp 4 -cpu cortex-a53 -semihosting -nographic -machine virt,virtualization=on,gic-version=3 -net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel build/nuttx -s`
3. Run …

Add support for smp_call from interrupt context

---

drivers/can/can.c

since routines called by IRQ need to be protected in SMP too.

can: Add more critical section to fix the race condition

---

drivers/reset/core.c

fix build warning when CONFIG_RESET_RPMSG is not set but CONFIG_RESET is set
will not have build error
build when set CONFIG_RESET=y but CONFIG_RESET_RPMSG=n

reset: fix build warning when CONFIG_RESET_RPMSG is not set

---

drivers/sensors/gnss_uorb.c

1. drivers/sensors/gnss: notify user when new data ready
2. drivers/sensors/gnss: using new buffer lock avoid 
3. drivers/sensors/gnss: check invalid nmea to avoid prasebuffer overflow
Bug fix 
Vela

drivers/gnss-uorb: bug fix about gnss data lost and deadlock

---

drivers/serial/serial.c

Print a log when user manually force panic the board.
No.
Tested on qemu, log is correctly printed out.
```
nsh> [CPU0] _assert: Current Version: NuttX  12.6.0 216f535472-dirty Sep 30 2024 15:34:51 arm64
[CPU0] _assert: Assertion failed Force panic by user.: at file: /drivers/serial/serial.c:2084 task(CPU0): CPU0 IDLE process: Kernel 0x4028cdac
```

serial: add message for FORCE_PANIC

---

fs/romfs/fs_romfs.c
fs/tmpfs/fs_tmpfs.c
include/nuttx/fs/ioctl.h

in tmpfs/romfs, we can get file real xip address to execute program
romfs & tmpfs
qemu with mps3 an547

fs/ioctl:add FIOC_XIPBASE to get file xip address

---

arch/sim/src/nuttx-names.in

add NXSYMBOLS for  pthread_gettid_np pthread_self
enable sim:smp can boot
This commit fixes the regression from https://github.com/apache/nuttx/pull/12561
sim
ostest (but signest_test can still fail for other reason not cause by https://github.com/apache/nuttx/pull/13616)

sim: add NXSYMBOLS for  pthread_gettid_np pthread_self

---

include/nuttx/init.h
sched/Kconfig
sched/misc/assert.c

This PR first tidies up the assert handler process by moving the dump information to standalone functions. The OSINIT_PANIC state has been added to indicate a fatal error has occurred, and any further asserts in this state will trigger a direct board reset. Lastly, smp_call is used to notify all other CPUs about the assert, saving all registers to g_last_regs so the main CPU can log them.
Previously, only crashes on the main CPU included register information. Now, we have the ability to inspect the states of other CPUs as well.
Tested with arm64 qemu and internal projects.
Need PR https://github.com/apache/nuttx/pull/13737 to function properly.
1. Build `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -Bbuild -GNinja -DBOARD_CONFIG=boards/arm64/qemu/qemu-armv8a/configs/nsh_smp nuttx
`
2. Run …

Suspend and dump all CPU registers from assert

---

include/ctype.h
libs/libc/ctype/lib_ctype.c

When compiling `MSVC` after  https://github.com/apache/nuttx/pull/12230., a strange compilation error will occur.
```shell
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\uchar.h(36,112): error C2143: syntax error: 缺少“)”(在“常数”的前面) [D:\jenkins_home\github\nuttx\vs2022\sched\sched.vcxproj]
(“../../sched/task/task_setup.c”)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\uchar.h(36,112): error C2143: syntax error: 缺少“{”(在“常数”的前面) [D:\jenkins_home\github\nuttx\vs2022\sched\sched.vcxproj]
(“../../sched/task/task_setup.c”)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\uchar.h(36,112): error C2059: syntax error:“常数” [D:\jenkins_home\github\nuttx\vs2022\sched\sched.vcxproj]
(“../../sched/task/task_setup.c”)
C:\Program Files (x86)\Windows …
```

ctype.h(bugfix):move locale macro define into lib_ctype file

---

drivers/usbdev/Kconfig
drivers/usbdev/cdcacm.c
drivers/usbdev/cdcacm_desc.c

With CDCACM_HAVE_EPINTIN, you can configure whether cdcacm uses interrupt endpoint.
Interrupt endpoint is enabled as default and can be disabled when hardware endpoint resources are stretched. 
PS: linux as a usbhost does not support disabling interrupt endpoints.
windows as usb host, it works properly.
Linux as usb host, the interrupt endpoint must be enable

cdcacm: config to enable or disable interrupt endpoint

---

drivers/mmcsd/mmcsd_sdio.c

Rename mmcsd_read_csd to mmcsd_read_extcsd,  since it really read extcsd register not csd register and remove the temp buffer inside it.
mmcsd
cortex m55

drivers/mmcsd: Rename mmcsd_read_csd to mmcsd_read_extcsd

---

arch/xtensa/src/esp32s3/esp32s3_spi_slave.c

Slave receive more than half buffer size, for example, Master and Slave buffer size is 32K, Master send more than 16K data through DMA every time, the first 16K data received by Slave is correct, but the data received afterward is wrong .
This because after Slave receiving data, it update data offset in the buffer, but not update DMA buffer Link List.
ESP32S3 SPI
Test with two esp32s3-devkit, one as master, another as slave.

xtensa/esp32s3: add setup rx dma after slave receive data

---

arch/x86_64/src/intel64/intel64_cpupause.c

In x86_64, g_current_regs is still used for context switching.
This commit fixes the regression from https://github.com/apache/nuttx/pull/13616
x86_64
qemu-intel64:smp (signest_test will Occasional failure not caused by https://github.com/apache/nuttx/pull/13616)

x86_64: we should call x86_64_restorestate/x86_64_savestate

---

include/sys/select.h

Support defining OPEN_MAX freely to allow increasing it from 256
This allows setting CONFIG_LIBC_OPEN_MAX into values greater than 256
Simplifies the header file, makes it possible to configure higher maximum number of open FDs
Tested on MPFS platform in CONFIG_BUILD_KERNEL configuration with more than 256 open file descriptors.

include/sys/select.h: Define __SELECT_NUINT32 in generic way

---

arch/xtensa/src/common/xtensa.h
arch/xtensa/src/common/xtensa_cpupause.c
arch/xtensa/src/esp32/esp32_intercpu_interrupt.c
arch/xtensa/src/esp32s3/esp32s3_intercpu_interrupt.c

add parameters to xtensa_pause_handler
nxsched_smp_call_handler need these parameters
xtensa
esp32s3-devkit:smp(ostest)

xtensa: add parameters to xtensa_pause_handler

---

arch/arm64/src/a64/Make.defs
arch/arm64/src/a64/a64_timer.c
arch/arm64/src/common/arm64_arch_timer.c
arch/arm64/src/common/arm64_cpustart.c
arch/arm64/src/fvp-v8r/Make.defs
arch/arm64/src/fvp-v8r/fvp_timer.c
arch/arm64/src/goldfish/Make.defs
arch/arm64/src/goldfish/goldfish_timer.c
arch/arm64/src/imx8/Make.defs
arch/arm64/src/imx8/imx8_timer.c
arch/arm64/src/imx9/Make.defs
arch/arm64/src/imx9/imx9_timer.c
arch/arm64/src/qemu/CMakeLists.txt
arch/arm64/src/qemu/Make.defs
arch/arm64/src/qemu/qemu_timer.c
arch/arm64/src/rk3399/Make.defs
arch/arm64/src/rk3399/rk3399_timer.c
arch/arm64/src/zynq-mpsoc/Make.defs
arch/arm64/src/zynq-mpsoc/zynq_timer.c

Similar to arch/arm, let chip implement their own up_timer_initialize. By default the `arm64_oneshot_initialize` timer is used.
There should be no impact. It simply move the timer to chip level code.
Tested with qemu arm64
```
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -Bbuild -GNinja -DBOARD_CONFIG=boards/arm64/qemu/qemu-armv8a/configs/nsh_smp nuttx
qemu-system-aarch64 -smp 2 -cpu cortex-a53 -semihosting -nographic -machine virt,virtualization=on,gic-version=3 -net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel build/nuttx -s
ostest &
```

Allow each chip to use its own timer

---

arch/arm/include/cxd56xx/crashdump.h
arch/risc-v/src/bl602/bl602_start.c
arch/risc-v/src/common/riscv_exception.c
arch/xtensa/src/common/xtensa_assert.c
binfmt/libelf/libelf_coredump.c
boards/arm/cxd56xx/common/src/cxd56_crashdump.c
boards/arm/stm32/nucleo-f429zi/src/stm32_bbsram.c
boards/arm/stm32f7/nucleo-144/src/stm32_bbsram.c
boards/renesas/rx65n/rx65n-grrose/src/rx65n_sbram.c
boards/renesas/rx65n/rx65n-rsk2mb/src/rx65n_sbram.c
drivers/note/note_driver.c
drivers/note/notelog_driver.c
drivers/note/noteram_driver.c
drivers/segger/note_sysview.c
drivers/serial/serial.c
drivers/syslog/Kconfig
drivers/syslog/vsyslog.c
fs/procfs/fs_procfsproc.c
include/nuttx/sched.h
libs/libc/gdbstub/lib_gdbstub.c
sched/misc/assert.c
sched/sched/sched_dumponexit.c
sched/task/task_activate.c
sched/task/task_exit.c

Introduce `get_task_name` to streamline code by replacing (#if #else #endif) with a cleaner implementation.
For debug log, instead of printing nothing, now it will print "noname".
CI test should be enough for this change.

task: use get_task_name where possible

---

Documentation/platforms/arm/samv7/boards/same70-xplained/README.txt
Documentation/platforms/arm/samv7/boards/samv71-xult/README.txt
Documentation/platforms/arm/stm32f1/boards/cloudctrl/index.rst
Documentation/platforms/arm/stm32f1/boards/fire-stm32v2/index.rst
Documentation/platforms/arm/stm32f1/boards/hymini-stm32/index.rst
Documentation/platforms/arm/stm32f1/boards/shenzhou/index.rst
Documentation/platforms/arm/stm32f1/boards/stm3210e-eval/index.rst
Documentation/platforms/arm/stm32f1/boards/stm32_tiny/index.rst
Documentation/platforms/arm/stm32f1/boards/stm32f103-minimum/index.rst
Documentation/platforms/arm/stm32f2/index.rst
Documentation/platforms/arm/stm32f3/index.rst
Documentation/platforms/arm/stm32f4/index.rst
Documentation/platforms/arm/stm32f7/index.rst
drivers/can/Kconfig
drivers/can/can.c
include/nuttx/can/can.h

support to independent set TX/RX FIFO size

chardriver upperCAN: support to independent set TX/RX FIFO size.

---

binfmt/binfmt_coredump.c
binfmt/elf.c
include/nuttx/binfmt/binfmt.h
include/nuttx/binfmt/elf.h
include/nuttx/coredump.h
include/nuttx/memoryregion.h
libs/libc/misc/lib_memoryregion.c
sched/misc/coredump.c

Add a coreudmp api to watch custom variables
coredump
qemu with mps3 an547 syslog coredump
if we want add some variables in coredump
we can use `coredump_add_memory_region(&var, sizeof(var))`

coredump:Add a coreudmp api to watch custom variables

---

arch/arm/src/common/Toolchain.defs
arch/arm/src/tlsr82/Toolchain.defs
arch/arm64/src/Toolchain.defs
arch/arm64/src/cmake/Toolchain.cmake
arch/risc-v/src/cmake/Toolchain.cmake
arch/risc-v/src/common/Toolchain.defs

Remove the judgment of GCCVER and add compilation options directly. If there is a problem that the compiler cannot recognize the compilation options, add it separately.

nuttx/arch: Remove GCCVER and add compilation options directly.

---

drivers/can/can.c
include/nuttx/can/can.h

add the ability that control CAN transceiver state in nuttx.
add can controller state setting and getting in uppercan.

add the ability that control CAN transceiver and controller state.

---

arch/arm64/src/common/arm64_arch.h
arch/arm64/src/common/arm64_exit.c
arch/arm64/src/common/arm64_fpu.c
arch/arm64/src/common/arm64_fpu_func.S
arch/arm64/src/common/arm64_initialstate.c
arch/arm64/src/common/arm64_internal.h
arch/arm64/src/common/arm64_pthread_start.c
arch/arm64/src/common/arm64_schedulesigaction.c
arch/arm64/src/common/arm64_sigdeliver.c
arch/arm64/src/common/arm64_syscall.c
arch/arm64/src/common/arm64_task_start.c
arch/arm64/src/common/arm64_vector_table.S
arch/arm64/src/common/arm64_vectors.S

Fix FPU and exception handling for ARM64 by:
- Saving and restoring FPU state on every exception / interrupt
- Switching to the interrupt stack, when executing the exception handler / interrupt service routine
This is a continuation of: https://github.com/apache/nuttx/pull/13520
@GUIDINGLI and @lipengfei28 Did the initial patches, which are adapted for CONFIG_BUILD_KERNEL / CONFIG_LIB_SYSCALL, which were implemented by me. The goal is to merge this work without breaking either one.
Impact is on ARM64 platform only. The impacted parts are the exception and ISR handling.

arm64/SMP: Fix FPU and exception handling for ARM64

---

sched/sched/sched_timerexpiration.c

wd_timer handler will change current task, so need process scheduler before wd timer handler, Ensure that the current task is not updated before the RR process.
RR sched with tickless
Test with sabre-6quad, config CONFIG_RR_INTERVAL

sched: process scheduler before wd_timer handler

---

drivers/lcd/Kconfig
drivers/lcd/st7735.c

Add option to invert display as required by some panels.
No.
Chip 0.96inch 80x160 ips display with below configuration
```
CONFIG_LCD_ST7735=y
CONFIG_LCD_ST7735_XRES=80
CONFIG_LCD_ST7735_YRES=160
CONFIG_LCD_ST7735_XOFFSET=26
CONFIG_LCD_ST7735_YOFFSET=1
CONFIG_LCD_ST7735_BGR=y
CONFIG_LCD_ST7735_INVCOLOR=y
CONFIG_LCD_ST7735_BPP=16
CONFIG_LCD_ST7735_SPIMODE=0
```

lcd/st7735: add option to invert display color

---

Documentation/ReleaseNotes/NuttX-12.7.0

Add release notes for 12.7.0 release
NOTE
Ddue to the quality of commit titles new unsorted sections were added. 
If the titles and commit descriptions will improve those sections will disappear in future releases.
Release
CI

Documentation: add NuttX-12.7.0 release notes

---

arch/arm/src/cmake/clang.cmake
arch/arm/src/cmake/gcc.cmake
arch/arm/src/cmake/ghs.cmake
arch/arm64/src/cmake/Toolchain.cmake
arch/risc-v/src/cmake/Toolchain.cmake
arch/sim/src/cmake/Toolchain.cmake

1. cmake incorrectly identifies the --param xxx option and needs to be changed to --param=xxx
2. Add arm64 support kasan
No
No

cmake: Fix some errors when using kasan

---

arch/arm/src/common/CMakeLists.txt
arch/arm/src/common/ghs/lib_dummy.c

1. since the pow() function that defined in libmath_sd.a is depend on the
__gh_set_errno() function, and the __gh_set_errno() function provided in
libsys.a, in order to use the pow() function, we need to add dependency
of libsys.a
2. but the libsys.a will introduce an extra ".syscall" section, and the
".syscall" is mainly used for syscall actions that provided by
greenhills compiler. but since nuttx has syscall implementation, so we
choose to not depend on the greenhills's libsys.a lib. and the final implementation
are to add dummy "__gh_set_errno" implementation in arch/arm/src/common/ghs/lib_dummy.c
will work as we expect.
2. has tested on ghs/gcc compiler

greenhills support: fix the pow() function calculate error

---

arch/arm/src/at32/at32_can.c
arch/arm/src/lpc17xx_40xx/lpc17_40_can.c
arch/arm/src/sama5/sam_can.c
arch/arm/src/sama5/sam_mcan.c
arch/arm/src/samv7/sam_mcan.c
arch/arm/src/stm32/stm32_can.c
arch/arm/src/stm32/stm32_fdcan.c
arch/arm/src/stm32f7/stm32_can.c
arch/arm/src/stm32l4/stm32l4_can.c
drivers/can/Kconfig
drivers/can/can.c
drivers/can/mcp2515.c
include/nuttx/can/can.h

add tx_confirm ability in upperCAN driver.
need merge with https://github.com/apache/nuttx-apps/pull/2635
test with flagchip

char driver CAN: add tx_confirm ability in upperCAN driver.

---

arch/arm64/src/imx9/imx9_usbdev.c
drivers/usbdev/cdcacm.c
drivers/usbdev/pl2303.c

This corrects some USB cache operations on imx9 platform, as well as with some generic buffer overflow issues in cdcacm and pl2303
Fixes random crashes / instability
Tested on i.MX93 platform

Imx9 usb fixes

---

drivers/rptun/CMakeLists.txt
drivers/rptun/Make.defs

1. Add cmake support for rptun_serure;
2. Move rptun_secure.c before rptun_ivshmem.c in Make.defs to follow the order in Kconfig.
rptun secure support cmake
CI

drivers/rptun: add cmake support for rptun_secure

---

arch/risc-v/src/common/riscv_doirq.c
arch/risc-v/src/common/riscv_exit.c
arch/risc-v/src/common/riscv_internal.h
arch/risc-v/src/common/riscv_sigdeliver.c
arch/risc-v/src/common/riscv_swint.c
arch/risc-v/src/common/supervisor/riscv_perform_syscall.c

This commit fixes the regression from https://github.com/apache/nuttx/pull/13561
In order to determine whether a context switch has occurred, we can use g_running_task to store the current regs. This allows us to compare the current register state with the previously stored state to identify if a context switch has taken place.
RELEASE
CI

{bp-13585} riscv: use g_running_task store current regs

---

arch/risc-v/include/irq.h
arch/risc-v/src/common/riscv_fork.c
arch/risc-v/src/common/riscv_swint.c

Summary
There was an error in the fork() routine when system calls are in use: the child context is saved on the child's user stack, which is incorrect, the context must be saved on the kernel stack instead.
The result is a full system crash if (when) the child executes on a different CPU which does not have the same MMU mappings active.
Impact
RELEASE
Testing
CI

{bp-13633} riscv_fork.c: Fix vfork() for kernel mode + SMP

---

arch/arm64/include/irq.h
arch/arm64/src/common/arm64_copystate.c
arch/arm64/src/common/arm64_fork.c

Since FPU is now always saved into the current process stack location upon exception entry, there is no need to keep fpu_regs (or saved_fpu_regs) in the TCB.
Removal of dead code from ARM64

arm64_fpu: Remove fpu_regs from the TCB

---

arch/sim/src/sim/sim_rpmsg_virtio.c
drivers/rpmsg/rpmsg_virtio.c
drivers/rpmsg/rpmsg_virtio_ivshmem.c
include/nuttx/rpmsg/rpmsg_virtio.h

use reserved[2] in struct resource_table as the command, avoid the resource table format do not follow the standard.
rpmsg virtio
qemu-armv7a with rpmsg_virtio enabled

rpmsg_virtio: move rpmsg virtio cmd definition before the resource table

---

.github/workflows/build.yml

This PR proposes to enhance the CI Workflow, to skip the unnecessary NuttX Builds. Currently, NuttX Devs wait for the CI Builds to complete across All Architectures (Arm32, Arm64, RISC-V, Xtensa), even though they modified a Single Architecture. With this PR, the CI Workflow will build only the Modified Architecture.
The solution uses the Arch Labels for PRs. We target only the Simple PRs: One Arch Label + One Size Label (e.g. "Arch: risc-v, Size: XS")
- If "Arch: arm / arm64" is the only non-size label, then we build `other`, `arm-01`, `arm-02`, ...
- If "Arch: risc-v" is the only non-size label, then build `risc-v-01`, `risc-v-02`
- If "Arch: xtensa" is the only non-size label, then build `xtensa-01`, `xtensa-02`
- The above rules apply when the PR is Created or Modified
- When the PR …

build.yml: Skip the CI Builds that don't match the Arch Label

---

sched/group/group_killchildren.c

In protected build, kernel cannot call usersapce interface, so change pthread_kill to tkill.
pthread exit
ostest passed on the sabre-6quad:knsh_smp board

sched/group: replace the pthread interface used in the kernel

---

fs/inode/fs_files.c

fs/file: bug fix about fdcheck can't assert
while running fdcheck_test_common there should be assertion failed
This PR is dup with https://github.com/apache/nuttx/pull/13209, let's close https://github.com/apache/nuttx/pull/13209, thanks~
fdcheck ready
Vela

fs/file: bug fix about fdcheck can't assert

---

arch/arm/src/cxd56xx/cxd56_gnss.c

Fix a compile error when CONFIG_CXD56_GNSS_CEP_ON_SPIFLASH is enabled.
Only for spresense

arch: cxd56xx: Fix gnss compile error

---

arch/arm/include/cxd56xx/pm.h
boards/arm/cxd56xx/spresense/src/cxd56_sdcard.c

Fix an issue not to enter cold sleep by SD Card detection interrupt.
Only for spresense

boards: cxd56xx: Fix an issue not to enter cold sleep

---

.github/workflows/build.yml

When building a branch like `releases/12.7`, the CI Workflow incorrectly checks out the `master` branch of `nuttx-apps`, instead of `releases/12.7`. This PR fixes a typo in `apps_ref`, to check out the correct branch.
This will fix the Apps Build for NuttX Releases.
None

build.yml: Check out the correct branch of nuttx-apps

---

arch/x86_64/include/intel64/irq.h
arch/x86_64/src/intel64/intel64_irq.c

arch/intel64: fix IRQ conflict with GOLDFISH
Also move MSI IRQ definition to place where other IRQ definitions are.
x86_64 can be used with android goldfish. No impact on user.
CI

arch/intel64: fix IRQ conflict with GOLDFISH

---

arch/x86_64/src/common/addrenv.h

arch/x86_64/addrenv.h: fix MMU flags for USER region
fix typo
kernel build with x86_64 (not yet upstream)

arch/x86_64/addrenv.h: fix MMU flags for USER region

---

arch/x86_64/src/intel64/intel64_cpustart.c

colorize IDLE stack for AP cores in x86_64
`CONFIG_STACK_COLORATION=y` works also for AP cores IDLE stack 
qemu

arch/intel64: colorize IDLE stack for AP cores

---

arch/x86_64/src/intel64/intel64_cpuidlestack.c
arch/x86_64/src/intel64/intel64_head.S
arch/x86_64/src/intel64/intel64_schedulesigaction.c

- arch/x86_64/intel64/intel64_head.S: move initial RSP for AP cores below regs area
move initial RSP for AP cores below regs area.
otherwise IDLE thread for AP cores can be corrupted.
XCP region now match regs allocation in up_initial_state()
-  arch/intel64_cpuidlestack.c: stack_alloc should point to stack base not stack top
- arch/x86_64/intel64/intel64_schedulesigaction.c: properly align signal handler stack for vector operations
various fixes for problems observed with high optimization enabled and SMP
qemu with smp test and ostest

arch/intel64: various fixes for stack alignment

---

Documentation/components/drivers/special/sensors.rst
Documentation/components/drivers/special/sensors/adt7320.rst
Documentation/components/drivers/special/sensors/adxl345.rst
Documentation/components/drivers/special/sensors/adxl362.rst
Documentation/components/drivers/special/sensors/adxl372.rst
Documentation/components/drivers/special/sensors/aht10.rst
Documentation/components/drivers/special/sensors/ak09912.rst
Documentation/components/drivers/special/sensors/lsm330.rst
Documentation/components/drivers/special/sensors/mpl115a.rst
Documentation/components/drivers/special/sensors/sht4x.rst

This PR adds a new folder to the documentation for sensor drivers where each driver can receive its own sub-page. This is useful to list the `SNIOC_*` ioctl commands that the sensor driver implements and the arguments it takes. It can also list programming examples.
This PR comes from InSpace by the way!
This should make the drivers more usable/approachable because there will be further documentation available to users. The hope is that now that the folder exists, as new drivers are added people can add their documentation here too simultaneously (and hopefully add documentation for the existing drivers!).
In this PR I added an example of what I think would be an improvement for sensor docs based on the SHT4x sensor.
I had noticed that it was difficult to see what support existed for …

Create a documentation folder to list sensor drivers

---

arch/arm/src/common/Toolchain.defs
arch/arm/src/tlsr82/Toolchain.defs

[Bug fix]： https://github.com/apache/nuttx/issues/13776
Due to the https://github.com/apache/nuttx/commit/394a967263f35ba72363994ba03ae8929d5e4974, which directly added ARCHOPTIMIZATION += --param=min-pagesize=0, some compiler environments with lower versions could not recognize this compilation option. Therefore, I am submitting this current fix patch.

nuttx/arch: Fix the issue where the compiler cannot recognize min-pagesize=0.

---

drivers/mmcsd/mmcsd.h
drivers/mmcsd/mmcsd_sdio.c

mmcsd: move block driver register to probe stage in order to read ext_csd reg
mmcsd
cortext M55

mmcsd: move block driver register to probe stage in order to read ext_csd reg

---

fs/vfs/CMakeLists.txt

nuttx/fs/vfs/fs_lock.c:39:10: fatal error: sched/sched.h: No such file or directory
39 | #include "sched/sched.h"
|          ^~~~~~~~~~~~~~~
cmake sim:local

fs_lock: fix cmake build error

---

include/nuttx/init.h
sched/init/nx_smpstart.c
sched/init/nx_start.c
sched/sched/sched.h
sched/sched/sched_addreadytorun.c
sched/sched/sched_lock.c
sched/sched/sched_mergepending.c
sched/sched/sched_process_delivered.c
sched/sched/sched_removereadytorun.c
sched/sched/sched_setpriority.c
sched/sched/sched_unlock.c
sched/task/task_exit.c

1 To improve efficiency, we mimic Linux's behavior where preemption disabling is
only applicable to the current CPU and does not affect other CPUs.
2 In the future, we will implement "spinlock+sched_lock", and use it extensively.
Under such circumstances, if preemption is still globally disabled, it will seriously impact
the scheduling efficiency.
3 We have removed g_cpu_lockset and used irqcount in order to eliminate the dependency of
schedlock on critical sections in the future, simplify the logic, and further enhance the
performance of sched_lock.
4 We set lockcount to 1 in order to lock scheduling on all CPUs during startup, without
the need to provide additional functions to disable scheduling on other CPUs.
5 Cpu (1-n) must wait for cpu0 to enter the idle state before enabling …

change nxsched_islocked_global to nxsched_islocked_tcb

---

sched/sched/sched_suspend.c

In the kernel, we are planning to remove all occurrences of up_cpu_pause as one of the steps to simplify the implementation of critical sections. The goal is to enable spin_lock_irqsave to encapsulate critical sections, thereby facilitating the replacement of critical sections(big lock) with smaller spin_lock_irqsave(small lock)
nxsched_suspend
$ make
$ qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic -machine virt,virtualization=on,gic-version=3
-net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel ./nuttx

sched: replace sync pause with async pause for nxsched_suspend

---

sched/sched/sched_setpriority.c

In the kernel, we are planning to remove all occurrences of up_cpu_pause as one of the steps to simplify the implementation of critical sections. The goal is to enable spin_lock_irqsave to encapsulate critical sections, thereby facilitating the replacement of critical sections(big lock) with smaller spin_lock_irqsave(small lock)
setpriority
$ make
$ qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic -machine virt,virtualization=on,gic-version=3
-net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel ./nuttx

sched: replace sync pause with async pause for setpriority

---

sched/task/task_restart.c

In the kernel, we are planning to remove all occurrences of up_cpu_pause as one of the steps to simplify the implementation of critical sections. The goal is to enable spin_lock_irqsave to encapsulate critical sections, thereby facilitating the replacement of critical sections(big lock) with smaller spin_lock_irqsave(small lock)
nxtask_restart
$ make
$ qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic -machine virt,virtualization=on,gic-version=3
-net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel ./nuttx

sched: replace sync pause with async pause for nxtask_restart

---

fs/vfs/fs_lock.c

Fixed the problem of releasing the bucket prematurely in multi-threaded flock scenarios by https://github.com/apache/nuttx/issues/13821
**How to reproduce the problem**
A thread setlk
B thread setlk_wait
A thread releases lock but fails to determine if nwaiter causes the bucket to be released prematurely post B thread causes crash due to heap use after free
We can …

fs_lock:Check the nwaiter when deleting a bucket

---

drivers/pci/pci_ivshmem.c
drivers/pci/pci_uio_ivshmem.c
drivers/rpmsg/rpmsg_virtio_ivshmem.c
drivers/vhost/vhost.c
drivers/virtio/virtio.c

- pci/ivshmem: Skip unregistering ivshmem driver
- rpmsg/ivshmem: Skip unregistering ivshmem driver 
- pci/ivshmem: Check drv isn't NULL before calling remove
- driver/vhost: Check driver isn't NULL before calling remove 
- driver/virtio: Check driver isn't NULL before calling remove 
- driver/vhost: vhost_register_device should set priv before inovking probe
- driver/vhost: Check driver is NULL before calling probe
- driver/vhost: Call metal_init in vhost_register_drivers 
minor bug fix
internal

Minor fix for virtio/vhost/rpmsg subsystem

---

drivers/serial/CMakeLists.txt

- drivers/serial/CMakeLists.txt: add missing files
add missing files: uart_bth5.c and uart_ram.c
missing files for cmake build
CI

drivers/serial/CMakeLists.txt: add missing files

---

arch/arm/src/nrf52/nrf52_gpio.c
arch/arm/src/nrf53/nrf53_gpio.c
arch/arm/src/nrf91/nrf91_gpio.c

- arch/arm/nrf{52|53|91}: fix read GPIO state for outputs
when GPIO is configured as output, we have to read output state register instead of input register
read GPIO state for outputs works correctly
tested on nrf52840 but should work the same for all Nordic chips

arch/arm/nrf{52|53|91}: fix read GPIO state for outputs

---

drivers/vhost/vhost-rng.c
drivers/virtio/Kconfig
drivers/virtio/virtio-blk.c
drivers/virtio/virtio-gpu.c
drivers/virtio/virtio-input.c
drivers/virtio/virtio-mmio.c
drivers/virtio/virtio-net.c
drivers/virtio/virtio-rng.c
drivers/virtio/virtio-rpmb.c
drivers/virtio/virtio-serial.c
drivers/virtio/virtio-snd.c
include/nuttx/virtio/virtio-mmio.h
include/nuttx/virtio/virtio.h

1.    virtio devices: update virtqueue operate buffer add lock API
1. Use the virtqueue_xxx_lock() api;
2. Add spinlock for some virtio and vhost drivers that do not
use spinlock to protect the virtqueues;
2.    virtio/virtio-net: add spinlock for the virtqueue
virtqueues are used in irq and thread, so add spinlock to protect
them.
3.    virtio/virtio-net: calculate the correct buffer number
Avoid exceed the virtqueue length limit when adding buffer to the
virtqueue.
4.    virtio-rpmb.c: add spin lock for virtqueue add/get buffer
Virtqueeus are used in both user thread and interrupt, so add spinlock
to proetect them.
5.    virtio-serial.c: add spin lock for virtqueue add/get buffer
Virtqueeus are used in both user thread and interrupt, so add spinlock
to proetect them.
6.    virtio-blk.c: …

VirtIO/Vhost Drivers: bug fix and new feature support

---

arch/arm/src/common/arm_exit.c
arch/arm64/src/common/arm64_exit.c
arch/avr/src/common/avr_exit.c
arch/hc/src/common/hc_exit.c
arch/mips/src/common/mips_exit.c
arch/misoc/src/lm32/lm32_exit.c
arch/misoc/src/minerva/minerva_exit.c
arch/or1k/src/common/or1k_exit.c
arch/renesas/src/common/renesas_exit.c
arch/risc-v/src/common/riscv_exit.c
arch/sim/src/sim/sim_exit.c
arch/sparc/src/common/sparc_exit.c
arch/tricore/src/common/tricore_exit.c
arch/x86/src/common/x86_exit.c
arch/x86_64/src/common/x86_64_exit.c
arch/xtensa/src/common/xtensa_exit.c
arch/z16/src/common/z16_exit.c
arch/z80/src/common/z80_exit.c
sched/pthread/pthread_exit.c
sched/task/exit.c
sched/task/task_exit.c
sched/task/task_exithook.c
sched/task/task_terminate.c

In the kernel, we are planning to remove all occurrences of up_cpu_pause as one of the steps to simplify the implementation of critical sections. The goal is to enable spin_lock_irqsave to encapsulate critical sections, thereby facilitating the replacement of critical sections(big lock) with smaller spin_lock_irqsave(small lock)
nxtask_terminate
$ make

sched: replace sync pause with async pause for nxtask_terminate

---

libs/libxx/libcxx.cmake
libs/libxx/libcxx.defs
libs/libxx/libcxxmini.cmake
libs/libxx/libcxxmini.defs

Remove the judgment of GCCVER and add CXXFLAGS directly. If there is a problem that the compiler cannot recognize the compilation options, add it separately.

nuttx/libxx: Simplify compilation warnings for passing CXXFLAGS.

---

arch/risc-v/src/k230/k230_rptun.c
arch/risc-v/src/mpfs/mpfs_ihc.c
arch/risc-v/src/qemu-rv/qemu_rv_rptun.c
drivers/clk/clk_rpmsg.c
drivers/input/uinput.c
drivers/ioexpander/ioe_rpmsg.c
drivers/misc/rpmsgblk.c
drivers/misc/rpmsgblk_server.c
drivers/misc/rpmsgdev.c
drivers/misc/rpmsgdev_server.c
drivers/mtd/rpmsgmtd.c
drivers/mtd/rpmsgmtd_server.c
drivers/net/rpmsgdrv.c
drivers/power/supply/regulator_rpmsg.c
drivers/reset/reset_rpmsg.c
drivers/sensors/sensor_rpmsg.c
drivers/serial/uart_rpmsg.c
drivers/syslog/syslog_rpmsg.c
drivers/syslog/syslog_rpmsg_server.c
drivers/timers/rpmsg_rtc.c
drivers/usrsock/usrsock_rpmsg.c
drivers/usrsock/usrsock_rpmsg_server.c
drivers/wireless/bluetooth/bt_rpmsghci.c
drivers/wireless/bluetooth/bt_rpmsghci_server.c
fs/rpmsgfs/rpmsgfs_client.c
fs/rpmsgfs/rpmsgfs_server.c
include/nuttx/rpmsg/rpmsg.h
net/rpmsg/rpmsg_sockif.c

misc/rpmsgblk.c:616:29: warning: implicit declaration of function ‘rpmsg_virtio_get_buffer_size’; did you mean ‘rpmsg_get_rx_buffer_size’? [-Wimplicit-function-declaration]
616 |   if (MAX(msglen, rsplen) > rpmsg_virtio_get_buffer_size(priv->ept.rdev))
|                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
|                             rpmsg_get_rx_buffer_size
No impact
CI

 rpmsgblk.c: fix compile warning

---

arch/risc-v/src/k230/k230_rptun.c
arch/risc-v/src/mpfs/mpfs_ihc.c
arch/risc-v/src/qemu-rv/qemu_rv_rptun.c
drivers/clk/clk_rpmsg.c
drivers/input/uinput.c
drivers/ioexpander/ioe_rpmsg.c
drivers/misc/rpmsgblk.c
drivers/misc/rpmsgblk_server.c
drivers/misc/rpmsgdev.c
drivers/misc/rpmsgdev_server.c
drivers/mtd/rpmsgmtd.c
drivers/mtd/rpmsgmtd_server.c
drivers/net/rpmsgdrv.c
drivers/power/supply/regulator_rpmsg.c
drivers/reset/reset_rpmsg.c
drivers/sensors/sensor_rpmsg.c
drivers/serial/uart_rpmsg.c
drivers/syslog/syslog_rpmsg.c
drivers/syslog/syslog_rpmsg_server.c
drivers/timers/rpmsg_rtc.c
drivers/usrsock/usrsock_rpmsg.c
drivers/usrsock/usrsock_rpmsg_server.c
drivers/wireless/bluetooth/bt_rpmsghci.c
drivers/wireless/bluetooth/bt_rpmsghci_server.c
fs/rpmsgfs/rpmsgfs_client.c
fs/rpmsgfs/rpmsgfs_server.c
include/nuttx/rpmsg/rpmsg.h
net/rpmsg/rpmsg_sockif.c

1.    syslog/syslog_rpmsg.c: the last log may be lost when it crashes
At line 236, we may set the null terminate to the priv->buffer,
when flushing the priv->buffer, we should use up_putc() instead up_nputs()
to ensure all the data has been output, because up_nputs() will check
the null terminate but up_putc() not.
2.    syslog/syslog_rpmsg.c: out of memory
3.    syslog_rpmsg: fix coding style
Follow the nxstyle
4,    syslog/syslog_rpmsg.c: improve syslog_rpmsg performance
use copy buffer instead of single assignment
Rpmsg syslog

Rpmsg syslog: update rpmsg syslog

---

.github/workflows/arch.yml

This PR continues to enhance the CI Workflow, to skip the unnecessary NuttX Builds. The changes in this PR will not take effect until the next PR, which will switch `build.yml` to use the rules in this PR.
In this PR, we refactor the CI Build Rules into a separate Reusable Workflow `arch.yml`. The original rules were migrated to `arch.yml`:
- We target only the Simple PRs: One Arch Label + One Size Label (e.g. "Arch: risc-v, Size: XS")
- For "Arch: risc-v": Build `risc-v-01`, `risc-v-02`
- For "Arch: xtensa": Build `xtensa-01`, `xtensa-02`
- The above rules apply when the PR is Created or Modified
- When the PR is Merged: All targets shall be built
New and Updated Rules:
- For "Arch: arm": Build `arm-01`, `arm-02`, ...
- For "Arch: arm64": Build `other`
- For "Arch: simulator": Build …

CI: Refactor the Build Rules based on Arch Labels

---

arch/arm/src/cxd56xx/cxd56_sdhci.c

The mmcsd driver has been updated to require SDIO_CAPS_4BIT to be explicitly specified for SD card 4-bit support.
Only for spresense board.
Test on spresesense board with SD card.

arch: cxd56xx: Add SD card 4-bit capability

---

.github/workflows/build.yml

This PR continues to enhance the CI Workflow, to skip the unnecessary NuttX Builds. The PR will update the CI Build Workflow `build.yml`, to call the Refactored Build Rules in `arch.yml` (which is a Reusable Workflow).
The original rules were migrated from `build.yml` to `arch.yml`:
- We target only the Simple PRs: One Arch Label + One Size Label (e.g. "Arch: risc-v, Size: XS")
- For "Arch: risc-v": Build `risc-v-01`, `risc-v-02`
- For "Arch: xtensa": Build `xtensa-01`, `xtensa-02`
- The above rules apply when the PR is Created or Modified
- When the PR is Merged: All targets shall be built
This PR applies the New and Updated Rules defined in `arch.yml`:
- For "Arch: arm": Build `arm-01`, `arm-02`, ...
- For "Arch: arm64": Build `other`
- For "Arch: simulator": Build `sim-01`, `sim-02`
- …

CI: Apply the Refactored Build Rules based on Arch Labels

---

sched/mqueue/mq_initialize.c
sched/mqueue/mq_send.c
sched/mqueue/mqueue.h

Change mqueue_msg_s to a dynamic array so that mqueue msg can be malloc based on the msg size
of the current data when applied dynamically.
NA
Test config:
boards/arm/imx6/sabre-6quad/configs/nsh
Test case:
ostest pass

mq: change mqueue msg mail to dynamic array

---

arch/risc-v/src/esp32c3-legacy/esp32c3_ble_adapter.c
arch/risc-v/src/esp32c3-legacy/esp32c3_wifi_adapter.c
arch/risc-v/src/esp32c3/esp_wifi_adapter.c
arch/risc-v/src/esp32c6/esp_wifi_adapter.c
arch/xtensa/src/esp32/esp32_ble_adapter.c
arch/xtensa/src/esp32/esp32_wifi_adapter.c
arch/xtensa/src/esp32s2/esp32s2_wifi_adapter.c
arch/xtensa/src/esp32s3/esp32s3_ble_adapter.c
arch/xtensa/src/esp32s3/esp32s3_wifi_adapter.c

esp32: fix esp32 wifi bug caused scan failed
tools/configure.sh esp32c3-generic:wifi
wapi scan wlan0
has no return result after couple times
rootcause:
mq_timedsend() return failed because the time valid check error. the ts_nsec is bigger than 1000000000.
esp_update_time() hasn't consider of the ns > 1s after the adding calculation
This PR fix the issue which described by:
https://github.com/apache/nuttx/pull/13814
esp32
tools/configure.sh esp32c3-generic:wifi

esp32: fix esp32 wifi bug caused scan failed

---

drivers/serial/uart_rpmsg.c

1.    serial/uart_rpmsg: should init the lock before call rpmsg_register_callback
To avoid init the lock after this lock has been used.
2.    drivers/uart_rpmsg: add recv lock when received the data from peer
The recv buffer is used both in user thread and rpmsg ept->callback
thread, so add recv lock to protect the recv buffer.
3.    driver/uart_rpmsg: clear transmit buffer when remote exception occurred
Make uart rpmsg work normally when restart the remote core
uart rpmsg

uart_rpmsg: some bugs fixed

---

fs/romfs/fs_romfs.c
fs/romfs/fs_romfsutil.c

to avoid the resource leak
romfs
internal

fs/romfs: Call block_operations::close when romfs_bind fail

---

boards/risc-v/esp32c6/common/scripts/esp32c6_sections.ld

Fixes linker issues on ESP32C6 when WiFi was built with MCUBoot. This issue caused `imgtool` to show a massive file size due to linking problems.
This follows the bug report on #13611 
Thanks for the assist @almir-okato 
Modifies linker script for ESP32C6.
Internal CI testing.

riscv/esp32c6: fix rtc text section and wifi ram placement

---

arch/arm/src/stm32/stm32_can_sock.c
arch/arm/src/stm32/stm32_fdcan_sock.c
arch/arm/src/stm32f7/stm32_can_sock.c

- arch/arm/stm32{|f7}/socketcan: fix debugassert for extid frames
fix debugassert for extid frames, we have to remove CAN_EFF_FLAG bit from the expression
fix debugassert expression
stm32 with `cansend` command

arch/arm/stm32{|f7}/socketcan: fix debugassert for extid frames

---

Documentation/components/filesystem/inotify.rst
fs/notify/inotify.c
fs/notify/notify.h
fs/vfs/fs_close.c
fs/vfs/fs_truncate.c

`IN_MODIFY` event should occur on file modification, which includes truncate. This is consistent with the inotify usage on Linux.
Close operation on file should lead to `IN_CLOSE_WRITE` or `IN_CLOSE_NOWRITE` notifications. This commits adds the notification support. Notifying on close is a little bit trickier as a lower layer may not have the full file path after successful close and inode release. Calling notification before close is not a solution since close might
not end successfully. 
The solution is to obtain and buffer the path before calling close and then pass the buffered path to the notify_close. This required the change in `notify_close` function arguments: `filep` is no longer required, path and `oflags` are passed instead.
Inotify now reports notification on close and …

inotify: support truncate and close calls

---

drivers/devicetree/CMakeLists.txt
drivers/devicetree/Make.defs
drivers/devicetree/fdt_virtio_mmio.c
include/nuttx/fdt.h

devicetree/fdt_virtio_mmio: implement the fdt_virtio_mmio_devices_register()
So the borad level do not need implement the
register_virtio_devices_from_fdt() again and again.
New function
qemu armv7a

Fdt mmio: add common fdt mmio virtio device register function

---

arch/arm/src/armv7-a/arm_cache.c
arch/arm/src/armv7-a/cp15_cacheops.h
arch/arm/src/armv7-m/arm_cache.c
arch/arm/src/armv7-r/arm_cache.c
arch/arm/src/armv7-r/cp15_cacheops.h
arch/arm/src/armv8-m/arm_cache.c
arch/arm/src/armv8-r/arm_cache.c
arch/arm/src/armv8-r/cp15_cacheops.h
arch/arm64/src/common/arm64_cache.c
arch/x86_64/src/intel64/intel64_cache.c
arch/xtensa/src/common/xtensa_cache.c

cache: do cache_invalidate_all before enable dcache
Align the behavior of enable dcache:
Before enable dcache, we must do cache_invalidate_all()
cache enable
Bes board

cache: do cache_invalidate_all before enable dcache

---

arch/sim/src/sim/sim_head.c
arch/sim/src/sim/sim_idle.c
arch/sim/src/sim/sim_sectionheap.c
arch/sim/src/sim/sim_uart.c
include/nuttx/compiler.h

sim bug fix:
sim: fix context-switch when do wdog callback()
sim/gcov: Fix conflicts between fprofile-orderate and __asan_default_options
arch/sim: dataheap should disable exec permission
arch/sim: fix uart could lose log
sim
sim

sim bug fix

---

drivers/note/CMakeLists.txt
drivers/note/Kconfig
drivers/note/Make.defs
drivers/note/note_driver.c
drivers/note/note_initialize.c
drivers/note/noterpmsg.h
drivers/note/noterpmsg_driver.c
drivers/note/noterpmsg_server.c

drivers/note: suport rpmsg transfer channel for note, some note api need to adapte for rpmsg.
We can transfer note content through rpmsg
New feature
CI

drivers/note: suport rpmsg transfer channel for note,some note api

---

drivers/timers/arch_timer.c
sched/init/nx_start.c

timer & nx_start small bug fix:
1. sched: swap setting for g_npidhash
in case of crash in kmm_zalloc, and crash dump use
nxsched_foreach()
2. timer: set g_timer.lower after TIMER_START()
in case of up_perf_gettime() get non-start value
none
bes board & sim

timer & nx_start small bug fix

---

fs/rpmsgfs/rpmsgfs_client.c
fs/rpmsgfs/rpmsgfs_server.c

1.    rpmsgfs/rpmsgfs_client: init the priv->wait before register rpmsg callback
Should init the priv->wait before rpmsg_register_callback() because
rpmsgfs_ns_bound() may has been called before rpmsg_register_callback()
returned.
2.    rpmsgfs: add tty fd ioctl(TCGETS/TCSETS) support
rpmsgfs client ioctl support TCDRN/TCFLSH/TCGETS/TCSETS
3.    rpmsgfs_server: add error log for rpmsgfs server ept callback
Because the rpmsg_virtio will assert when endpoint callback return
error, so add more error log to the rpmsgfs server to help to locate
the root cause.
4.    rpmsgfs: remove memcpy in rpmsgfs open/close
improve the rpmsgfs performance
rpmsg fs
sim:rpserver and rpproxy with procfs

Rpmsg fs: rpmsgfs bug fix and enhancement

---

boards/arm/s32k3xx/mr-canhubk3/src/s32k3xx_tja1153.c
drivers/wireless/ieee80211/bcm43xxx/bcmf_netdev.c
include/net/if.h
net/netdev/netdev_ioctl.c

turn off interface by checking IFF_UP flag isn't set: https://github.com/apache/nuttx/issues/1838
improve the compatibility
internal

net: Remove IFF_DOWN flag to compatible with Linux/*BSD

---

arch/arm/src/arm/arm_syscall.c
arch/arm/src/common/arm_exit.c
arch/arm64/src/common/arm64_exit.c
arch/avr/src/common/avr_exit.c
arch/hc/src/common/hc_exit.c
arch/mips/src/common/mips_exit.c
arch/misoc/src/lm32/lm32_exit.c
arch/misoc/src/minerva/minerva_exit.c
arch/or1k/src/common/or1k_exit.c
arch/renesas/src/common/renesas_exit.c
arch/risc-v/src/common/riscv_exit.c
arch/sim/src/sim/sim_exit.c
arch/sparc/src/common/sparc_exit.c
arch/tricore/src/common/tricore_exit.c
arch/x86/src/common/x86_exit.c
arch/x86_64/src/common/x86_64_exit.c
arch/xtensa/src/common/xtensa_exit.c
arch/z16/src/common/z16_exit.c
arch/z80/src/common/z80_exit.c
sched/sched/sched_suspendscheduler.c

arch: fix the sched parameter update when exiting
The nxsched_resume_scheduler api will be call inside syscall if used, and don't have to be in up_exit.
tcb is already freed in up_exit/nxtask_exit before up_exit/nxsched_resume_scheduler
and if we make mempool threshold larger than tcb size, the delay free feature will also not work.
will cause a used after free, catched by qemu-armv7a project defconfig kasan.
exit
bes board & sim

arch: fix the sched parameter update when exiting

---

arch/x86_64/src/intel64/intel64_schedulesigaction.c

This commit fixes the regression from https://github.com/apache/nuttx/pull/13768
qemu-intel64:nsh
ostest

x86_64: fix regression

---

sched/signal/sig_default.c

In protected build, kernel cannot call usersapce interface.
1. change pthread_exit to nx_pthread_exit.
2. add kernel tls cleanup.
NA
sabre-6quad:nsh and sabre-6quad:knsh with ostest pass

sched/signal: change pthread_exit to nx_pthread_exit

---

drivers/clk/clk_rpmsg.c
drivers/misc/rpmsgblk.c
drivers/misc/rpmsgblk_server.c
drivers/mtd/rpmsgmtd_server.c
drivers/net/rpmsgdrv.c
drivers/note/noterpmsg_driver.c
drivers/power/supply/regulator_rpmsg.c
drivers/rpmsg/rpmsg_ping.c
drivers/sensors/sensor_rpmsg.c
drivers/serial/uart_rpmsg.c
drivers/syslog/syslog_rpmsg.c
drivers/usrsock/usrsock_rpmsg.c
drivers/usrsock/usrsock_rpmsg_server.c
drivers/wireless/bluetooth/bt_rpmsghci.c
drivers/wireless/bluetooth/bt_rpmsghci_server.c
fs/rpmsgfs/rpmsgfs_client.c
fs/rpmsgfs/rpmsgfs_server.c

Otherwise, the tx buffer will be discarded and can no longer be obtained
All the rpmsg services

rpmsg services: should release the tx buffer when rpmsg_send_nocopy failed

---

drivers/net/e1000.c

In scenarios that require high time accuracy, we do not want an interrupt from the NIC to interrupt the current task, so add support for polling mode.
qemu:x64

e1000: add polling mode support for tx/rx

---

mm/Kconfig

1. It is recommended to use 1 on qemu and 16 or even 32 on the device.
No
No

mm/kconfig: set the default alignment of global variable out-of-bounds detection is 1

---

fs/mount/fs_mount.c

zipfs:zipfs not need mtd drivers
zipfs mount
sim:zipfs
do mount a zipfs

zipfs:zipfs not need mtd drivers

---

fs/vfs/fs_open.c

Adjusted the opening of a directory node through open to check the parameters passed in.
Reference https://man7.org/linux/man-pages/man2/open.2.html
> EISDIR pathname refers to a directory and the access requested involved writing (that is, O_WRONLY or O_RDWR is set).
**Is a new feature added?**: NO
**Impact on build**: NO
**Impact on hardware**: NO, this change does not specifically target any particular hardware architectures or boards.
**Impact on documentation**: NO,This patch does not introduce any new features
**Impact on compatibility**: This implementation aims to be backward compatible. No existing functionality is expected to be broken.
After this adjustment, we cannot open a directory  with write behavior oflags by open

fs_open:Adjust the definition of the open path

---

drivers/usbdev/cdcacm.c

nrdq is already set 0 in resetconfig.  This is needed to prevent nrdq going under 0, that will cause assert later.

usbdev/cdcacm: Fix read queue counter in shutdown

---

fs/inode/fs_files.c

**Why is this change necessary?**
When the device reboot through reboot_notify to notify the task fsync time, if there is a task in the exit process, there may be priority robbed off the phenomenon, and at this time the group->tg_filelist crefs has been 0, resulting in the ASSERT
**Changes**
Optimized the logic of files_getlist
```
FAR struct filelist *list;
if (tcb->group != NULL)
{
list = &tcb->group->tg_filelist;
if (list->fl_crefs > 0)
{
list->fl_crefs++;
return list;
}
}
return NULL;
```
**Impact on compatibility:** This implementation …

files_getlist:Handling the situation when tcb's grouplist is empty

---

net/netdev/netdev_ifconf.c

gcc7.1 adds truncation warning, netdev_ifconf.c fix snprintf truncation warnings.
Minor
Nuttx CI & Vela CI.

fix snprintf truncation warnings

---

boards/Kconfig
include/nuttx/streams.h
libs/libc/net/lib_base64.c
libs/libc/stream/CMakeLists.txt
libs/libc/stream/Kconfig
libs/libc/stream/Make.defs
libs/libc/stream/lib_base64outstream.c
libs/libc/stream/lib_hexdumpstream.c
sched/misc/coredump.c
tools/coredump.py

This PR added base64 encoded stream support, and use it as coredump output stream.
The output log size theoretically is smaller than hexdump. Thus could save some time if dump is large.
No impact on existing projects.
Tested on qemu.
```
tools/configure.sh mps3-an547:nsh
```
Enable coredump support
```patch
diff --git a/boards/arm/mps/mps3-an547/configs/nsh/defconfig b/boards/arm/mps/mps3-an547/configs/nsh/defconfig
index 54f5e21f223..3726188d41a 100644
--- a/boards/arm/mps/mps3-an547/configs/nsh/defconfig
+++ b/boards/arm/mps/mps3-an547/configs/nsh/defconfig
@@ -16,6 +16,8 @@ CONFIG_ARCH_INTERRUPTSTACK=2048
CONFIG_ARCH_STACKDUMP=y
CONFIG_ARMV8M_SYSTICK=y
CONFIG_ARMV8M_USEBASEPRI=y
+CONFIG_BOARD_COREDUMP_BASE64STREAM=y
+CONFIG_BOARD_COREDUMP_SYSLOG=y
CONFIG_BUILTIN=y
CONFIG_CMSDK_UART0=y …
```

Add base64 support to coredump to reduce syslog output size

---

drivers/video/Kconfig
drivers/video/goldfish_gpu_fb.c

We need to configure the priority of FB Vsync thread to prevent nxcamera from preempting scheduling without sleep, which currently causes issues with Goldfish x86_64's default FIFO scheduling.
goldfish gpu fb
goldfish gpu fb

driver: add GOLDFISH_GPU_FB_PRIORITY for goldfish_gpu_fb_vsync_thread

---

drivers/video/fb.c

Some drivers may not implement certain ioctls, but applications may still call these ioctl functions for consistency. In this case, to avoid an assertion, return ENOTTY.
framebuffer driver
CI-test

drivers/fb: use ENOTTY to replace assert

---

fs/inode/inode.h

/home/neo/projects/vela/nuttx/fs/vfs/fs_dup2.c: In function 'file_dup3': /home/neo/projects/vela/nuttx/fs/inode/inode.h:73:35: error: implicit declaration of function '_SCHED_GETTID' [-Werror=implicit-function-declaration]
73 |           int n = sched_backtrace(_SCHED_GETTID(), \
|                                   ^~~~~~~~~~~~~
/home/neo/projects/vela/nuttx/fs/vfs/fs_dup2.c:177:3: note: in expansion of macro 'FS_ADD_BACKTRACE'
177 |   FS_ADD_BACKTRACE(filep2);

fs: fix compile break

---

sched/misc/deadlock.c

Fix deadlock detection.
1. If mutext has no holder(`NXMUTEX_NO_HOLDER `), stop the check.
2. Fix tcb is waiting for sem, we are unable to detect deadlock, ignore this case
3. Rewrite the code with better naming and comments, to make it more readable.
```
bug:
thread 1: get mutexA
wait a sem
thread 2: wait mutexA
This situation will be mistakenly judged as a deadlock.
```
No impact.
```
tools/configure.sh mps3-an547:nsh
> qemu-system-arm -M mps3-an547 -m 2G -nographic -kernel nuttx -gdb tcp::1127 -serial pty
QEMU 6.2.0 monitor - type 'help' for more information
(qemu) char device redirected to /dev/pts/4 (label serial0)
> minicom -D /dev/pts/4
> hello &
```
CONFIG_ARCH_DEADLOCKDUMP=y
CONFIG_TTY_FORCE_PANIC=y
```
Modify the hello_main.c to create a deadlock example.
```c
#include …

Deadlock detect fix

---

drivers/note/notesnap_driver.c

1. clang atomic no support other type:
modify .index type size_t --- atomic_int
modify .dumping type bool --- atomic_bool

notesnap_driver.c: modify struct notesnap_s member type

---

boards/arm/nrf52/nrf52840-dk/src/nrf52_highpri.c
boards/arm/stm32/viewtool-stm32f107/src/stm32_highpri.c

The case want to determine if a interrupt with higher priority the interrupt preemption occurred,
but up_interrupt_context indicates that we self inside interrupt/handedr mode.
As we previously did not handle the ramvector interrupt correctly, after update breaked the case.
We should use a more clear private function is_nesting_interrupt.
https://github.com/apache/nuttx/issues/13831
RELEASE
CI

{Bp-13895} board/arm/nrf52: fix use up_interrupt_context to is_nesting_interrupt

---

drivers/sensors/usensor.c

- Fixed the error of container_of  incoming member.
- N/A
PC:Ubuntu 2004, x86 GCC 13.1, SIM
order: uorb_listener -n 10 sensor_accel_uncal

usensor.c:fix container_of member error.

---

libs/libxx/0001-libcxx-fix-ld-errors.patch
libs/libxx/libcxx.cmake
libs/libxx/libcxx.defs
libs/libxx/libcxxabi.cmake
libs/libxx/libcxxabi.defs

enable LIBSUPCXX:
text	   data	    bss	    dec	    hex	filename
93080	    592	   5472	  99144	  18348	nuttx/nuttx
enable LIBCXXABI:
before:
text	   data	    bss	    dec	    hex	filename
126468	    352	   5960	 132780	  206ac	nuttx/nuttx
after:
text	   data	    bss	    dec	    hex	filename
68048	    352	   5960	  74360	  12278	nuttx/nuttx

libcxxabi: Optimize cxx code size.

---

include/nuttx/signal.h
sched/timer/timer.h
sched/timer/timer_settime.c

This commit removed the empty struct to fix compilation errors for the MSVC compiler.
Fixed compilation errors for the MSVC compiler
Tested with the MSVC compiler.

sched/signal: Fix compilation errors for MSVC.

---

Documentation/reference/os/events.rst
fs/Kconfig
fs/Makefile
fs/event/CMakeLists.txt
fs/event/Kconfig
fs/event/Make.defs
fs/event/event.h
fs/event/event_close.c
fs/event/event_open.c
fs/semaphore/sem_open.c
include/nuttx/event.h
include/nuttx/fs/fs.h

This extension for the event group, to establish a connection between named event groups and a task. The task may reference the event group associated with a VFS-based name. Then the event group can be used in subsequent calls to nxevent_wait() or nxevent_post().
This is an extension to [12802](https://github.com/apache/nuttx/pull/12802) 
none, add OS interface 
vela

fs: support VFS-based named event group

---

arch/arm/src/goldfish/goldfish_timer.c
drivers/devicetree/fdt.c
drivers/devicetree/fdt_pci.c
include/nuttx/fdt.h

drivers/devicetree/fdt: get 'reg' property
Original code can only deal with single 'address & size' cell
Add function dealing with multiple 'address & size' cell
Add function getting 'bankwidth' property, for cfi-flash device
devicetree/fdt: fix fdt_get_reg_size() get wrong size
fdt, new API
vela qemu

drivers/devicetree/fdt: get 'reg' property

---

boards/boardctl.c
sched/misc/assert.c

This change adds cache flushing for debug purposes. Normally, cache operations are unnecessary since the system reboots. However, flushing the cache is required when the system crashes, allowing us to retain the entire memory after rebooting into the bootloader, where a full memory dump and further analysis can be performed.
Should be minimal.
This feature was tested on an internal project. When the system crashes, it reboots into the bootloader and uses USB to transfer the full memory to the host for inspection.

board_reset: flush cache before reset

---

include/nuttx/sched_note.h

Change inline functions to macros to unify code style
none
sim/note

note: change sched_note_counter to a macro

---

include/nuttx/mutex.h
libs/libc/misc/Kconfig
libs/libc/misc/lib_mutex.c
sched/misc/assert.c

add backtrace dump support for mutex hold task, for debugging the situation where tasks exit while holding the lock.
test by ci and real devices.

misc/assert: add backtrace dump support for mutex hold task

---

include/net/if.h
include/nuttx/net/ioctl.h
net/netdev/Kconfig
net/netdev/netdev_ioctl.c

Let the application layer use ioctl to switch the status of the lin/can network and obtain the current status of the lin/can network.
Only the function of status acquisition/delivery is added to can/lin
Test passed

This patch is to allow the application layer to use ioctl to send can/lin status control information to the driver layer.

---

fs/mqueue/mq_unlink.c

mq: correct inode release in mq_inode_release()
Cause mq_inode_release() realize refs--,
So not only inode->i_crefs <= 1 needs refs--, but also all the mq_inode_release() should refs--
mq_unlink
bes board & sim

mq: correct inode release in mq_inode_release()

---

drivers/misc/dev_mem.c

misc/dev_mem.c:203:24: error: comparison between two arrays [-Werror=array-compare]
203 |   bool merge = (_edata == _sbss);
|                        ^~
misc/dev_mem.c:203:24: note: use '&_edata[0] == &_sbss[0]' to compare the addresses
dev mem
qmeu armv8a

misc/dev_mem: fix compile error in aarch64

---

arch/sim/src/sim/posix/sim_hostsmp.c
arch/sim/src/sim/sim_doirq.c
arch/sim/src/sim/sim_internal.h
include/nuttx/irq.h

This commit fixes the regression from https://github.com/apache/nuttx/pull/13716
sim
sim:smp
ostest

sim: fix sim smp boot regression

---

fs/vfs/fs_rename.c

fs/vfs: Avoid calling stat with oldrelpath twice in mountptrename
and return error directly if stat return failure

fs/vfs: Avoid calling stat with oldrelpath twice in mountptrename

---

net/netdev/netdev_ioctl.c

netdev_wifr_ioctl SIOCGIWNAME cmd, need to filter out non-802.11 interfaces
Minor
Manual test on vela

case SIOCGIWNAME: add filter out non-802.11 interfaces

---

sched/group/group_continue.c
sched/group/group_killchildren.c
sched/group/group_suspendchildren.c

purpose:
1 sched_lock is very time-consuming, and reducing its invocations can improve performance. 2 sched_lock is prone to misuse, and narrowing its scope of use is to prevent people from referencing incorrect code and using it
test:
compiling
sched/group
arm64 arm

sched/group: There is no need to use sched_[un]lock

---

CMakeLists.txt
cmake/nuttx_remove_compile_options.cmake

add global moudle `nuttx_remove_compile_options()`. define custom board toolchain introduction.
Because CMake does not support the reverse operation of `add_compile_options`, 
the design logic of CMake is that if an option needs to be deleted, it should not be added in the first place.
However our arch scenario has a series of common configurations. When there is a customized board that needs to rewrite such configurations, it will face obstacles.
In Makefile, we can re-override variables such as CFLAGS. So this patch provides a CMake module to do the same thing
```cmake
nuttx_remove_compile_options(-march -mabi)
#
``` 
For custom board,  can create a Toolchain file in the` NUTTX_BOARD_ABS_DIR/cmake` directory and expand the compilation options.
custom board

cmake(Enhancement):enhance compile options for custom toolchain,implement the REVERSE opt of `add_compile_options()`

---

drivers/mmcsd/mmcsd.h
drivers/mmcsd/mmcsd_procfs.c
drivers/mmcsd/mmcsd_sdio.c

mmcsd: add multi partitions prototype implementation
this is a patch to make a ready for supporting  boot0, boot1, gp1, gp2, gp3, gp4, rpmb partitions 
mmcsd
cortex M55

mmcsd: add multi partitions prototype implementation

---

fs/inode/fs_foreachinode.c
fs/inode/fs_inodefind.c
fs/inode/fs_inodefree.c
fs/inode/fs_inodegetpath.c
fs/inode/fs_inoderemove.c
fs/inode/fs_inodereserve.c
fs/inode/fs_inodesearch.c
fs/inode/inode.h

In `fs/inode` directory, the variable name `FAR struct inode *node` is named inconsistently, with some using `node` and others using `inode`. To facilitate understanding, we will standardize the naming to `FAR struct inode *inode`.

nuttx/fs:Rename node with inode.

---

tools/checkpatch.sh

patches ending with cmake should be checked.
Currently, any non-cmake files containing cmake keywords will be checked.
solve https://github.com/apache/nuttx/pull/13913 check ci failed
check workflow

[bugfix]checkpatch.sh:Fix checking for wrong cmake files

---

drivers/usbdev/usbdev_fs.c

usb: If usb3.0, set the ep0 sssize to cfgdescsize

---

tools/mkdeps.c

When the compilation file is a full path, the Make.dep target cannot correctly generate dependencies, causing incremental compilation to fail.
Check g_altpath. If only the CURRENT path is included, the obj target use its own full path, otherwise just use the filename.
add default value current path for obj-path.
Make Make.dep to correctly generate targets with paths
build with qemu-armv8a:nsh

[bugfix]tools/mkdeps.c:add options for gen full path object target

---

arch/arm/src/armv7-a/arm_gicv2m.c
arch/arm64/src/common/arm64_gicv2m.c
drivers/pci/pci_qemu_epc.c

1.qemu_epc_get_msi: flag should use msi enable flag
2.The gicv2m spinlock init status should unlocked

Pci fixbugs

---

include/sched.h
include/sys/syscall_lookup.h
sched/sched/CMakeLists.txt
sched/sched/Make.defs
sched/sched/sched_getcpu.c
syscall/syscall.csv

this_cpu is logical core number, up_cpu_index is physical core number.
In SMP, this_cpu and up_cpu_index are same.
In AMP, we can also use sched_getcpu API to know physical core id on which the function is called.
relate to https://github.com/apache/nuttx/pull/13886
None
Vela

sched: export sched_getcpu API in AMP mode

---

libs/libc/fdt/Make.defs

In current code, compiling with menuconfig updated for the third time will fail due to "Directory not empty" error.
```
...
extracting: fdt/dtc-1.7.0/version_gen.h.in
inflating: fdt/dtc-1.7.0/yamltree.c
mv: cannot move 'fdt/dtc-1.7.0' to 'fdt/dtc/dtc-1.7.0': Directory not empty
make[1]: *** [fdt/Make.defs:31: dtc] Error 1
make: *** [tools/Unix.mk:452: libs/libc/.context] Error 2
(failed reverse-i-search)`git comm': ^Ct checkout xtensa-1.22.x
```
This is because the first `mv fdt/dtc-1.7.0 fdt/dtc` did a directory rename as expected, the second `mv fdt/dtc-1.7.0 fdt/dtc` moves one folder into another folder.
So we need to remove old `fdt/dtc` before `mv`command to fix this issue.
Remove old directory so that "mv" can succeed instead of triggering "Directory not empty" error.
Bug fixed.
``` …
```

libs/libc/fdt/Make.defs: cannot move due to directory not empty bugfix

---

arch/x86_64/src/cmake/Toolchain.cmake
arch/x86_64/src/common/Toolchain.defs

Resolve weak symbol compilation relocation errors
no impact
Can be compiled through

arch/x86_64: Resolve weak symbol compilation relocation errors

---

arch/x86_64/src/intel64/intel64_head.S

We need to simulate the behavior of the call instruction, which by default pushes 8 bytes of the RIP. Otherwise, the function's stack won't be 16-byte aligned.
no impact
SMP can start

arch/x68_64: properly align ap boot stack for vector operations

---

.github/labeler.yml

This PR changes the Labeling of PRs so that the Architecture (arm, risc-v, xtensa, ...) is specified in the Board Label. Previously the CI Workflow would set Generic Board Labels like "Area: Board support". Now it will set the Arch-Specific Board Label like "Board: arm".
The Board Label will be used by the upcoming CI Build Rules to skip unnecessary builds. So "Board: arm" will enable only the builds for `arm-01` to `arm-14`. This is explained here: https://github.com/apache/nuttx/issues/13775
No impact, since the current label "Area: Board support" is not used by the CI Build Rules.
The Updated CI Workflow shall be synced to `nuttx-apps` repo in the next PR.
We tested the Board Labeling by creating Board PRs for each Arch:
- [Arm32 PR](https://github.com/lupyuen5/label-nuttx/pull/30) is …

CI: Set PR Label to the Arch-Specific Board

---

fs/littlefs/CMakeLists.txt
fs/romfs/CMakeLists.txt
fs/rpmsgfs/CMakeLists.txt

Fix to compile parameters not taking effect When cmake version is greater than 3.18
https://cmake.org/cmake/help/latest/command/set_source_files_properties.html
New in version 3.18: By default, source file properties are only visible to targets added in the same directory (CMakeLists.txt). Visibility can be set in other directory scopes using one or both of the following options:
DIRECTORY <dirs>...
The source file properties will be set in each of the <dirs> directories' scopes. CMake must already know about each of these source directories, either by having added them through a call to [add_subdirectory()](https://cmake.org/cmake/help/latest/command/add_subdirectory.html#command:add_subdirectory) or it being the top level source directory. Relative paths are treated as relative to the …

Fix to compile parameters not taking effect When cmake version is greater than 3.18

---

boards/arm/stm32/stm32f429i-disco/configs/fb/defconfig

The default bpp is STM32_LTDC_L1_L8, when TM32_FB_CMAP=y,and The default bpp is STM32_LTDC_L1_RGB565 when TM32_FB_CMAP=n. The color-format bpp  of stm32f429i is 16, so we should be disable TM32_FB_CMAP, otherwise fb demo will result in an error.
stm32f429i fb demo
run fb dmeo on stm32f429i

stm32f429i-disco: disable TM32_FB_CMAP

---

arch/arm64/src/common/Make.defs
arch/arm64/src/common/arm64_mpu.c
arch/arm64/src/common/arm64_mpu.h
mm/mempool/mempool_multiple.c
mm/mm_heap/mm_free.c
mm/mm_heap/mm_memalign.c
mm/mm_heap/mm_realloc.c

1. add TBI setting to r82 when use SW_TAG
2. exclude mpu from sanitize for SMP mode
3. fix mempool crash when use KASAN SW_TAG
4. Fix mempool tag kasan error
No
No

mm: Resolve a series of issues caused by opening the software tag kasan

---

include/nuttx/queue.h
net/local/local_release.c

we should get next waiter before acceptor released
sim:local with kasan

local_sock: fix accept use-after-free

---

arch/sim/src/sim/sim_head.c
arch/sim/src/sim/sim_idle.c
arch/sim/src/sim/sim_sectionheap.c
arch/sim/src/sim/sim_uart.c
include/nuttx/compiler.h

sim bug fix:
sim: fix context-switch when do wdog callback()
sim/gcov: Fix conflicts between fprofile-orderate and __asan_default_options
arch/sim: dataheap should disable exec permission
arch/sim: fix uart could lose log
RELEASE
CI

{Bp-13878} sim bug fix

---

drivers/power/battery/goldfish_battery.c

GOLDFISH_BATTERY_WRITE will enable qemu to generate an interrupt, and a status value will be set in the interrupt. If Vela does not respond to this interrupt, we will not receive the interrupt in the future. Here, we need to ensure that we enable Vela's interrupt first, and then enable qemu to generate an interrupt
no impact
x86 goldfish

drivers/battery: Fix Goldfish Battery x64 unresponsive interrupt issue

---

.github/workflows/build.yml

When building a branch like `releases/12.7`, the CI Workflow incorrectly checks out the `master` branch of `nuttx-apps`, instead of `releases/12.7`. This PR fixes a typo in `apps_ref`, to check out the correct branch.
RELEASE
CI

{Bp-13806} build.yml: Check out the correct branch of nuttx-apps

---

drivers/misc/rpmsgdev.c
drivers/misc/rpmsgdev_server.c

Rpmsg dev server always open the real char device with nonblock mode, so let client try to read/wrtie the read device every read/write operation.
rpmsg dev

misc/rpmsgdev: fix block mode read/write bug in rpmsgdev

---

Documentation/platforms/arm64/qemu/boards/qemu-armv8a/README.txt
arch/arm64/src/common/arm64_backtrace.c
arch/arm64/src/common/arm64_cache.c
arch/arm64/src/common/arm64_checkstack.c
arch/arm64/src/common/arm64_mmu.h
arch/arm64/src/common/arm64_mpu.c
arch/arm64/src/common/arm64_mpu.h
arch/arm64/src/common/arm64_vectors.S

arch/arm64: Add the interface for icache and dcache.
arch/arm64: Fixed arm64_cache_get_info obtaining cache.
arm64_checkstack: fix crash, optimize the stack color, sync with arm
arm64: fix backtrace failed
arm64-r/mpu: add TBI setting to r82 when use SW_TAG
@pussuw 
Removed un-used function arm64_exception_context_save(), how do you think ?
arm64
xiaomi armv8r board & qemu

ARM64 bug fix

---

arch/x86_64/src/common/CMakeLists.txt
arch/x86_64/src/common/Make.defs

Configure arch delay using CONFIG_ALARM_ARCH
no impact
ostest

arch/x86_64:Configure arch delay using CONFIG_ALARM_ARCH

---

drivers/timers/arch_alarm.c
drivers/timers/arch_timer.c
include/nuttx/arch.h

Arch_alarm and arch_timer add up_ndelay interface
no impact
ostest

drivers/timers:Arch_alarm and arch_timer add up_ndelay interface

---

include/nuttx/queue.h
net/local/local_release.c

we should get next waiter before acceptor released
RELEASE
CI

{Bp-13906} local_sock: fix accept use-after-free

---

drivers/serial/Kconfig
drivers/serial/Kconfig-16550
drivers/serial/serial.c
drivers/serial/serial_dma.c
drivers/serial/serial_io.c
drivers/serial/uart_16550.c
drivers/serial/uart_pl011.c
include/nuttx/sched.h
include/nuttx/serial/serial.h
include/nuttx/serial/uart_16550.h
include/nuttx/signal.h
sched/signal/sig_tgkill.c

update some bug fix,and functional improvements
Fix system apps cu_main() ctrl + c crash bug:
1. fix cu ctrl+c crash.
2. use nxsig_tgkill instead of nxsig_kill
Fix syslog can't output after serial setup:
3. serial/pl011: fix can't up_putc() after setup
Fix poll crash:
4. serial.c: should protect the fds when calling poll_notify
Fix PCI serial driver init crash:
5. make sure that interrupts are disabled during init
This is a proper fix for an unexpected MSI interrupt for PCI serial driver.
Feature enhancements --- force panic feature use two ctrl+c
6. support force panic only when repeat the panic char
Feature enhancements --- Add new option
7.  Add 16550_DLF_SIZE option for DesignWare UART.
serial
vela

serial:update some bug fix,and functional improvements

---

.github/workflows/build.yml
tools/ci/testlist/risc-v-01.dat
tools/ci/testlist/risc-v-02.dat
tools/ci/testlist/risc-v-03.dat
tools/ci/testlist/risc-v-04.dat
tools/ci/testlist/risc-v-05.dat
tools/ci/testlist/risc-v-06.dat

To speed up the CI Workflow, this PR splits the CI Build Jobs for RISC-V into smaller jobs. Each job will now complete within 1 hour.
__Before the PR:__ There are 2 jobs for RISC-V, each requiring more than 1.5 hours
- `risc-v-01` (1 hour 42 mins): BL602, Ox64, ESP32-C3 / C6 / H2
- `risc-v-02` (1 hour 41 mins): K230, Icicle, QEMU, RV32M1-Vega
__After the PR:__ The build is spread across 6 jobs for RISC-V, each job completes within 1 hour
- `risc-v-01` (19 mins): BL602, Ox64
- `risc-v-02` (44 mins): ESP32-C3
- `risc-v-03` (45 mins): ESP32-C6, ESP32-H2
- `risc-v-04` (31 mins): K230, Icicle
- `risc-v-05` (41 mins): QEMU CITest
- `risc-v-06` (38 mins): Rest of QEMU, RV32M1-Vega
Following the same convention as the Arm32 Build Jobs, the above jobs are sorted by Target Name. Performance of the …

CI: Split the RISC-V Build Jobs into smaller jobs

---

drivers/clk/clk_rpmsg.c
drivers/ioexpander/ioe_rpmsg.c
drivers/misc/rpmsgblk_server.c
drivers/misc/rpmsgdev_server.c
drivers/mtd/rpmsgmtd_server.c
drivers/power/supply/regulator_rpmsg.c
drivers/reset/reset_rpmsg.c
drivers/sensors/sensor_rpmsg.c
drivers/syslog/syslog_rpmsg_server.c
drivers/timers/rpmsg_rtc.c
drivers/usrsock/usrsock_rpmsg_server.c
drivers/wireless/bluetooth/bt_rpmsghci_server.c
fs/rpmsgfs/rpmsgfs_server.c

use ept_release_cb to destory rpmsg services server dile resource to avoid the used-after-free issue
All the rpmsg services

nuttx/drivers: add ept_release_cb for destroy server resource

---

sched/sched/sched.h
sched/sched/sched_removereadytorun.c
sched/sched/sched_reprioritizertr.c
sched/sched/sched_setpriority.c
sched/sched/sched_suspend.c
sched/task/task_restart.c
sched/task/task_terminate.c

after
269732   51065   63335  384132   5dc84 nuttx
before
269784   51065   63335  384184   5dcb8 nuttx
size -52
sched
ci ostest

sched: remove param in nxsched_remove_readytorun

---

arch/x86_64/src/intel64/intel64_check_capability.c

cpuid expect 32 bit variables
no impact
ostest

arch/x86_64: cpuid expect 32 bit variables

---

arch/x86_64/src/intel64/intel64_idle.c

idle convert all asm() to __asm__()
asm() is not supported by -std=c99, __asm__() is more portable
no impact
ostest

arch/x86_64: idle convert all asm() to __asm__()

---

arch/risc-v/src/common/espressif/esp_irq.c

Correct the alert message in `esp_setup_irq()` if
irq number allocation fails, the parameter number is not matched with format specifier.
riscv/espressif
esp32c3

risc-v/espressif: Fix alert message in `esp_setup_irq()`

---

arch/x86_64/src/Makefile

Add allsymbol functionality
no impact
open backtrace and then when the crash occurs, you can see the symbols.

arch/x86_64:Add allsymbol functionality

---

arch/x86_64/src/Makefile
arch/x86_64/src/common/Toolchain.defs

LD: nuttx.elf
ld:in function `std::__1::ios_base::imbue(std::__1::locale const&)': 
nuttx/libs/libxx/libcxx/src/ios.cpp:129: undefined reference to `_Unwind_Resume'

x86_64:Fix ld error.

---

arch/x86_64/src/common/x86_64_udelay.c
arch/x86_64/src/intel64/CMakeLists.txt
arch/x86_64/src/intel64/Make.defs
arch/x86_64/src/intel64/intel64_tsc_ndelay.c

Add nanosecond delay interface to TSC
no impact
ostest

arch/x86_64:Add nanosecond delay interface to TSC

---

include/nuttx/serial/uart_16550.h

fix bug, regincr is used multiple times
uart_16550
Milk-V Duo S

uart_16550:fix bug, regincr is used multiple times

---

arch/x86_64/src/intel64/intel64_irq.c

if we two step to set interrupt trigger and disable interrupt, acrn will inject #GP exception
add acrn ioapic init support
no impact
ostest

x64: add acrn ioapic init support

---

arch/sim/src/sim/sim_smpsignal.c
sched/init/nx_smpstart.c
sched/sched/sched_smp.c

sched_smp:sync refcount before enqueue smp call queue
sched_smp:adjust the critical section to protect refcount from multi cores access
fix build error when sim SMP
CC: sim/sim_smpsignal.c init/nx_smpstart.c: In function ‘nx_idle_trampoline’:
init/nx_smpstart.c:68:21: warning: unused variable ‘tcb’ [-Wunused-variable]
68 | FAR struct tcb_s *tcb = this_task_inirq();
| ^~~
sim/sim_smpsignal.c: In function ‘host_cpu_started’:
sim/sim_smpsignal.c:271:17: warning: unused variable ‘tcb’ [-Wunused-variable]
271 | struct tcb_s *tcb = this_task();
sim/sim_smpsignal.c:249:33: error: ‘cpu’ undeclared (first use in this function)
249 | restore_critical_section(tcb, cpu);
| ^~~
RELEASE
CI

{Bp-13688} sched optimise for sim, CONFIG_SCHED_INSTRUMENTATION to CONFIG_SCHED_INSTRUMENTATION_SWITCH

---

include/nuttx/init.h
sched/init/nx_smpstart.c
sched/init/nx_start.c
sched/sched/sched.h
sched/sched/sched_addreadytorun.c
sched/sched/sched_lock.c
sched/sched/sched_mergepending.c
sched/sched/sched_process_delivered.c
sched/sched/sched_removereadytorun.c
sched/sched/sched_setpriority.c
sched/sched/sched_unlock.c
sched/task/task_exit.c

1 To improve efficiency, we mimic Linux's behavior where preemption disabling is
only applicable to the current CPU and does not affect other CPUs.
2 In the future, we will implement "spinlock+sched_lock", and use it extensively.
Under such circumstances, if preemption is still globally disabled, it will seriously impact
the scheduling efficiency.
3 We have removed g_cpu_lockset and used irqcount in order to eliminate the dependency of
schedlock on critical sections in the future, simplify the logic, and further enhance the
performance of sched_lock.
4 We set lockcount to 1 in order to lock scheduling on all CPUs during startup, without
the need to provide additional functions to disable scheduling on other CPUs.
5 Cpu (1-n) must wait for cpu0 to enter the idle state before enabling …

{Bp-13716} change nxsched_islocked_global to nxsched_islocked_tcb

---

sched/pthread/pthread_create.c

When a high-priority pthread is created, ptcb may be released after nxtask_activate.
pthread_create
sim board pipe test pass

sched/pthread: save pid before task activate

---

Documentation/platforms/arm/samv7/boards/same70-xplained/README.txt
Documentation/platforms/arm/samv7/boards/samv71-xult/README.txt
Documentation/platforms/arm/stm32f1/boards/cloudctrl/index.rst
Documentation/platforms/arm/stm32f1/boards/fire-stm32v2/index.rst
Documentation/platforms/arm/stm32f1/boards/hymini-stm32/index.rst
Documentation/platforms/arm/stm32f1/boards/shenzhou/index.rst
Documentation/platforms/arm/stm32f1/boards/stm3210e-eval/index.rst
Documentation/platforms/arm/stm32f1/boards/stm32_tiny/index.rst
Documentation/platforms/arm/stm32f1/boards/stm32f103-minimum/index.rst
Documentation/platforms/arm/stm32f2/index.rst
Documentation/platforms/arm/stm32f3/index.rst
Documentation/platforms/arm/stm32f4/index.rst
Documentation/platforms/arm/stm32f7/index.rst
arch/arm/src/at32/at32_can.c
arch/arm/src/lpc17xx_40xx/lpc17_40_can.c
arch/arm/src/sama5/sam_can.c
arch/arm/src/sama5/sam_mcan.c
arch/arm/src/samv7/sam_mcan.c
arch/arm/src/stm32/stm32_can.c
arch/arm/src/stm32/stm32_fdcan.c
arch/arm/src/stm32f7/stm32_can.c
arch/arm/src/stm32l4/stm32l4_can.c
drivers/can/Kconfig
drivers/can/can.c
drivers/can/mcp2515.c
include/nuttx/can/can.h

multi backport
https://github.com/apache/nuttx/pull/13647
https://github.com/apache/nuttx/pull/13718
https://github.com/apache/nuttx/pull/13760
https://github.com/apache/nuttx/pull/13762
https://github.com/apache/nuttx/pull/13758
RELEASE
CI

{Bp-13658} char driver CAN: add tx_confirm ability in upperCAN driver.

---

sched/sched/sched_removereadytorun.c

sched: fix omitted merging the pending queue regression
This commit fixes the regression from https://github.com/apache/nuttx/pull/13995
sched
ci

sched: fix omitted merging the pending queue regression

---

arch/x86_64/src/intel64/intel64_tsc_tickless.c

This commit fixed up_timer.
x86_64 up_timer.
Tested on x86_64 qemu/kvm.

arch/x86_64: Fix up_timer_start.

---

tools/gcov.sh

1. gcov.sh supports generating device-side code coverage
2.tools/gcov: ignore lcov error
none
sim

tools: gcov.sh supports generating device-side code coverage

---

fs/procfs/fs_procfsproc.c
include/nuttx/sched.h
sched/group/CMakeLists.txt
sched/group/Make.defs
sched/group/group_argvstr.c
sched/misc/assert.c
sched/task/CMakeLists.txt
sched/task/Make.defs
sched/task/task_argvstr.c

~Make sure `tcb` still exist when we access members of it.~
As discussed below, function `group_argvstr`  should be renamed to `nxtask_argvstr` because it's no longer depends on group.
Also current caller to `group_argvstr` is procfs and assert handler. Both of them are now have `enter_critical_section ` protected, thus we don't need to add guard inside `group_argvstr` .
PR is updated accordingly.
Should be minimal.
Tested on internal projects that has frequent task create/destroy and a periodic call to procfs.

group: access group in critical section

---

arch/arm/src/armv7-a/arm_perf.c
arch/arm/src/armv7-m/arm_perf.c
arch/arm/src/armv7-r/arm_perf.c
arch/arm/src/armv8-m/arm_perf.c
arch/arm/src/armv8-r/arm_perf.c
arch/arm64/src/common/arm64_perf.c
arch/risc-v/src/esp32c3-legacy/esp32c3_perf.c
arch/xtensa/src/common/xtensa_perf.c
drivers/timers/arch_alarm.c
drivers/timers/arch_timer.c
include/nuttx/arch.h
sched/clock/clock_perf.c

1. arch/perf: modify the return value of up_perf_gettime to clock_t
2. clock/perf: add critical section protection
none
sim

arch/perf: modify the return value of up_perf_gettime to clock_t

---

include/execinfo.h
libs/libc/misc/CMakeLists.txt
libs/libc/misc/Kconfig
libs/libc/misc/Make.defs
libs/libc/misc/lib_backtrace.c

sched: support backtrace record
record backtraces into a global buffer to reduce memory usage for the same backtrace
none
sim

sched: support backtrace record

---

arch/arm/src/cmake/clang.cmake
arch/arm/src/common/Toolchain.defs

1. The option also supports the latest version of ARM clang18

makefile/clang: Compare versions for upward compatibility

---

drivers/sensors/usensor.c

usensor.c:fix container_of member error.
RELEASE
CI

{bp-13945} usensor.c:fix container_of member error.

---

libs/libc/machine/arm64/arch_elf.c

1. Use address addition and subtraction, no longer as the return value of the address. Tags must be removed before calculation

libc/machine: Fix the error caused by tag kasan

---

net/local/local.h
net/local/local_accept.c
net/local/local_conn.c
net/local/local_connect.c
net/local/local_fifo.c
net/local/local_sockif.c

The argument addr is a pointer to a sockaddr structure. This structure is filled in with the address of the peer socket, as known to the communications layer.
sim:local

net/local: fix the return address is incorrect when accept

---

sched/environ/env_dup.c
sched/environ/env_getenv.c
sched/environ/env_setenv.c
sched/environ/env_unsetenv.c
sched/task/task_exithook.c
sched/task/task_fork.c

purpose:
1 sched_lock is very time-consuming, and reducing its invocations can improve performance. 2 sched_lock is prone to misuse, and narrowing its scope of use is to prevent people from referencing incorrect code and using it
test:
compiling
sched
arm64 arm

sched: There is no need to use sched_[un]lock

---

.github/workflows/arch.yml

This PR extends the CI Build Rules to eliminate more unnecessary builds. We use the Board Label for PRs:
- Previously: "Arch: arm" will build only `arm-01` to `arm-14`
- Now: "Board: arm" will also build `arm-01` to `arm-14`
- This applies only to Simple PRs: One Arch Label + One Board Label + One Size Label, like "Arch: arm, Board: arm, Size: L"
- If Arch Label and Board Label are both present: They must be the same. Otherwise All Targets shall be built.
- Works with Arm32, Arm64, RISC-V, Simulator, x86_64 and Xtensa
The updated code is explained here: https://github.com/apache/nuttx/issues/13775
Simple PRs targeting One Single Board and/or Arch shall complete the CI Build a lot quicker now.
The Updated CI Workflow shall be synced to `nuttx-apps` repo in the next PR.
We tested by …

CI: Skip the CI Builds that don't match the Board Label 

---

fs/vfs/fs_poll.c

fs poll optimize:
fs: Set the poll return value according to the man manual
The man manual describes that poll only has EFAULT, EINTR, EINVAL, and ENOMEM return values.
If a file returns an error, the POLLERR event should be set and OK should be returned
https://man7.org/linux/man-pages/man2/poll.2.html
When using libuv to poll the socket, the socket poll returned an EBUSY error, causing libuv to abort.
The expected logic should be to return OK, allowing libuv to notify the event listener that the POLLERR event occurred.
fs/vfs: result_independent_of_operands
timeout is a type of int
in MSEC2TICK, timeout may be multiplied by USEC_PER_MSEC
and the result may be out of range of int
Besides, this will induce following ERROR while running simulator:
vfs/fs_poll.c:498:38: runtime error: …

fs poll optimize

---

drivers/serial/pty.c
drivers/serial/serial.c

getline function support backspace
None
sim,qemu,arm64

Getline support backspace

---

fs/romfs/Kconfig
fs/romfs/fs_romfs.c
fs/romfs/fs_romfs.h
fs/romfs/fs_romfsutil.c

part 1 of romfs extend to enable format function
This is  part 1 of a series of patchs. 
To enhance the write capabilities of ROMFS, enabling it to perform simple file creation, writing, and deletion operations while maintaining compatibility with the original ROMFS format used in open-source ROMFS.
Feature is enabled by CONFIG_FS_ROMFS_WRITEABLE  Kconfig 
When CONFIG_FS_ROMFS_WRITEABLE is enabled 
We  can use **-o rw**  to enable writable 
cmoka_fs_test
cmoka_syscall_test

part 1 of romfs extend to enable format function

---

sched/Kconfig
sched/clock/clock.h
sched/clock/clock_initialize.c
sched/sched/sched_cpuload.c
sched/sched/sched_critmonitor.c
sched/sched/sched_processtimer.c
sched/sched/sched_timerexpiration.c

1. sched/cpuload: fix SMP situation CPULOAD statistics are inaccurate
2. sched: fix the inaccurate cpuload statistics issue
sim

sched/cpuload: fix SMP situation CPULOAD statistics are inaccurate

---

arch/x86_64/src/common/Toolchain.defs

X86_64: Add libcxx availability macros.

---

drivers/rpmsg/rpmsg_ping.c
include/nuttx/rpmsg/rpmsg_ping.h

-    rpmsg_ping.c: fix msg data memset length
The range of memset exceeds the size of the buffer
-    rpmsg_ping.c: change msg cmd type for more compatible
Use bit mask method to represent the command, because it's more
convenient to express multiple characteristics simultaneously.
-    rpmsg_ping.c: improve log level to LOG_EMERG
Usually rpmsg ping logs are needed during testing,
but too many other module logs can easily overwrite it,
so improve the rpmsg ping log level, later we can setlogmask to
a higher log level to mask other modules' logs.
-    rpmsg_ping.c: change check data to fluctuation value
We can found the error happend packet more accurately based
on the data value.
rpmsg ping
sim:rpserver and rpproxy

Rpmsg ping: improve the rpmsg ping

---

arch/x86_64/src/intel64/intel64_regdump.c

modify addr limit to support 64 bits addr backtrace
no impact 
ostest

x64: modify addr limit to support 64 bits addr backtrace

---

arch/x86_64/src/common/Toolchain.defs
arch/x86_64/src/intel64/Kconfig

With aggresive optimization enabled (-O3), ostest FPU test will fail.This is because the compiler will generate additional vector instructions between subsequent up_fpucmp() calls (loop vectorization somewhere in usleep() call), which will consequently overwrite the expected FPU context (XMM registers).The compilation option -fno-tree-vectorize can avoid this issue.
no impact
ostest

arch/x86_64:Add configuration to disable vectorization optimization

---

arch/x86_64/src/intel64/intel64_cpustart.c

This patch fixed SMP startup for ACRN Hypervisor.
Fix SMP startup for ACRN Hypervisor
no impact
ostest

arch/x86_64: Fix SMP startup for ACRN Hypervisor

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

* As the number of PRs increases noticeably improvements in review process are necessary.
* Some PRs introduce important and necessary updates but laconic descriptions makes it hard to understand slowing down the review process.
* Some PRs does not fully comply with Contributing guidelines: does not provide sufficient descriptions in commit title / message, does not provide sufficient PR Summary / Impact / Testing information, bundles various functional changes in a single PR, etc. This makes hard to track down changes.
* Some PRs seems to be work-in-progress not yet ready for review.
* I propose minor PR template update with reference to Contributing Guidelines and hints on what information is usually expected in each PR section.
* I propose small updates to Contributing Guidelines and …

Update GitHub Pull Request Template.

---

fs/littlefs/CMakeLists.txt
fs/littlefs/Make.defs
fs/littlefs/lfs_getsetattr.patch
fs/littlefs/lfs_vfs.c

add functions for littlefs : 
static int     littlefs_fchstat(FAR const struct file *filep, 
FAR const struct stat *buf, int flags);
static int     littlefs_chstat(FAR struct inode *mountpt,
FAR const char *relpath,
FAR const struct stat *buf, int flags);
littlefs_vfs  
NuttxSyscallTestSuites
NuttxFsTestSuites

Add support fchstat and chstat  function for littlefs

---

sched/group/group_setuptaskfiles.c
sched/init/nx_start.c
sched/sched/sched.h

Revert "sched/group/setuptask_file: duplicate idle task fd for kernelthreads
let's using shared group for kthreads, see #12320
This reverts commit 4e24eec7b607e4a6a7eca0fae9c58f02dc72e002.
Remove unnecessary code
Vela

Revert "sched/group/setuptask_file: duplicate idle task fd for kernelthreads

---

arch/x86_64/src/common/Toolchain.defs

Just sync with other architecture.
change the build result from nuttx.elf to nuttx
no impact
ostest

x86/x86_64: change the build result from nuttx.elf to nuttx

---

libs/libm/newlib/Make.defs

Remove not needed warning suppression. 
Since there's no warning presents now.
No impact, CI check will confirm if there's warnings.
Tested with internal CI and reports no warnings.

libm/newlib: remove -Wno-maybe-uninitialized

---

arch/x86_64/src/common/x86_64_internal.h

Change extern g_intstackalloc to g_isrstackalloc
no impact
ostest

arch/x86_64:Change extern g_intstackalloc to g_isrstackalloc

---

mm/Kconfig

mempool is always be compiled, so when enable BACKTRACE but not enable memdpool, the MM_HEAP_MEMPOOL_BACKTRACE_SKIP is not defined mempool_add_backtrace() will compiled failed.
mempool
CI

mm/Kconfig: fix build error when MM_BACKTRACE > 0 and disable mempool

---

sched/semaphore/sem_holder.c

Fix system crash when set CONFIG_PRIORITY_INHERITANCE=y
1.
set CONFIG_PRIORITY_INHERITANCE=y
set CONFIG_SEM_PREALLOCHOLDERS=0 or CONFIG_SEM_PREALLOCHOLDERS=8
```
#24 0x4dcab71 in __assert assert/lib_assert.c:37
#25 0x4d6b0e9 in nxsem_destroyholder semaphore/sem_holder.c:602
#26 0x4d80cf7 in nxsem_destroy semaphore/sem_destroy.c:80
#27 0x4d80db9 in sem_destroy semaphore/sem_destroy.c:120
#28 0x4dcb077 in nxmutex_destroy misc/lib_mutex.c:122
#29 0x4dc6611 in pipecommon_freedev pipes/pipe_common.c:117
#30 0x4dc7fdc in pipecommon_close pipes/pipe_common.c:397
#31 0x4ed4f6d in file_close vfs/fs_close.c:78
#32 0x6a91133 in local_free local/local_conn.c:184
#33 0x6a92a9c in local_release local/local_release.c:129
#34 0x6a91d1a in local_subref local/local_conn.c:271
#35 0x6a75767 in local_close …
```

Fix system crash when set CONFIG_PRIORITY_INHERITANCE=y

---

Documentation/platforms/risc-v/esp32c3-legacy/index.rst
Documentation/platforms/risc-v/esp32c3/index.rst
Documentation/platforms/risc-v/esp32c6/index.rst
Documentation/platforms/risc-v/esp32h2/index.rst
Documentation/platforms/xtensa/esp32/index.rst
Documentation/platforms/xtensa/esp32s2/index.rst
Documentation/platforms/xtensa/esp32s3/index.rst
tools/ci/docker/linux/Dockerfile
tools/ci/platforms/darwin.sh
tools/ci/platforms/linux.sh
tools/ci/platforms/ubuntu.sh
tools/esp32/Config.mk
tools/esp32c3/Config.mk
tools/esp32s2/Config.mk
tools/esp32s3/Config.mk
tools/espressif/Config.mk

Follows #13824
This PR updates all esptool version references from development to latest.
A second issue regarding older esptool versions causing the build to silently fail will be addressed in a different PR due to test requirements.
Espressif devices documentation and `pip install` sections of the build system.
Internal CI build.

Update esptool version on docs and build system

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

* Fix CONTRIBUTING.md github link reference.
* Full URL is provided to avoid relative/fork reference issues.
* Minor update on full contributing documentation.
* PR template.
* Contributing Guidelines links.
* Local testing and GitHub with this PR.

Contributing and PR template fix.

---

tools/nxstyle.c

apps/wireless/wapi/src/util.c 
nxstyle check find error
error: Mixed case identifier found

white list: add cJSON

---

drivers/serial/serial_dma.c
drivers/serial/serial_io.c

serial: use nxsig_tgkill instead of nxsig_kill
Caused nxsig_tgkill is for the one thread, nxsig_kill for the group
ctrl + c
sim

serial: use nxsig_tgkill instead of nxsig_kill

---

drivers/timers/CMakeLists.txt
drivers/timers/goldfish_timer.c

goldfish fix forget clear interrrpt, add in cmake
before fix, the goldfish timer possible keep loop in handler,
after fix, behavior like normal timer.
CI-test, goldfish simulator armv7a.

goldfish fix forget clear interrrpt, add in cmake

---

mm/mm_heap/mm_malloc.c
sched/misc/assert.c

dump more information when CONFIG_MM_DUMP_DETAILS_ON_FAILURE enabled,
flush log before coredump.
more log when do diagnostic in mass-production projects.
CI-test. cortex-m33 board.

dump more information when CONFIG_MM_DUMP_DETAILS_ON_FAILURE enabled, flush log before coredump

---

arch/arm/src/sama5/sam_udphs.c

When trying CDC/NCM I found that a debug assert was triggered. Initially I commented out the offending DEBUGASSERT and found the code worked just fine.
I don't know why the assert was placed there - perhaps with other uses of this driver there would always be data in the receive queue - so I moved the assignment to the places that actually needed and used the variable. 
I have checked that not only CDC/NCM (now) works but also that RNDIS still behaves as before, so it seems like a "safe" fix.
None expected, but maybe reviewers with USB and DMA knowledge can comment.
Custom board with SAMA5D27C-D1G, using either CDC/NCM or RNDIS connectivity.

SAMA5D2. Fix DEBUGASSERT triggered in sam_updhs.c

---

mm/Kconfig
mm/kasan/sw_tags.c

When dynamically loading, the read-only data of arm64 architecture is accessed through PC offset. When opening the tag kasan, because the PC value does not have a tag, accessing the read-only data will be detected with a tag mismatch error.
No
No

mm/sw_tags: add config for no longer checking for tags 0

---

net/local/local_recvmsg.c
net/local/local_sendmsg.c

local_socket: corrent send/recv return value after shutdown
local socket
sim

local_socket: corrent send/recv return value after shutdown

---

include/nuttx/spinlock.h
sched/irq/irq_spinlock.c

sched/spinlock: remove nesting spinlock support
developers must be careful to hold spinlocks and ensure all of protected code is under control, so remove support for nested spinlocks to improve performance.
N/A
ci-check

sched/spinlock: remove nesting spinlock support

---

arch/sim/include/irq.h

114 up_interrupt_context () at /home/zhhyu/source/vela/dev/nuttx/include/arch/irq.h:163
115 stack_monitor_enter (this_fn=0x400145dc <up_current_regs>, call_site=0x4002d5c7 <__cyg_profile_func_enter+120>, arg=0x0) at instrument/stack_monitor.c:63
116 0x000000004002d5c7 in __cyg_profile_func_enter (this_fn=0x400145dc <up_current_regs>, call_site=0x4002d5c7 <__cyg_profile_func_enter+120>) at misc/lib_instrument.c:68
117 0x00000000400156c7 in up_current_regs () at instrument/stack_monitor.c:62
118 up_interrupt_context () at /home/zhhyu/source/vela/dev/nuttx/include/arch/irq.h:163
119 stack_monitor_enter (this_fn=0x400145dc <up_current_regs>, call_site=0x4002d5c7 <__cyg_profile_func_enter+120>, arg=0x0) at instrument/stack_monitor.c:63
120 0x000000004002d5c7 in __cyg_profile_func_enter …

sim: fix crash caused by function recursion

---

libs/libc/machine/arm64/arch_elf.c

Use address addition and subtraction, no longer as the return value of the address. Tags must be removed before calculation
RELEASE
CI

{Bp-14050} libc/machine: Fix the error caused by tag kasan

---

arch/Kconfig

nuttx/arch:Enabling ARCH_MATH_H is required when compiling sim with the 13.2 version of the toolchain

---

drivers/pci/pci_ivshmem.c
include/nuttx/pci/pci_ivshmem.h

ivshmem based driver can use this api to judge weather current ivshmem device support irq or not, and use polling mode or irq mode to process the event.
ivshmem based drivers
qemu armv8a and rptun-ivshmem

pci_ivshmem.c: ivshmem_support_irq API support

---

include/nuttx/lin.h

To add specific error types about the lin module, first determine the error frame flag, classify the error in data[0], and indicate the specific error in data[1~4]. When there is a problem with the lin module communication, it is convenient to locate the problem in time.
*Changes will change the format of lin error frames*
*It has been verified in multiple development versions*

add lin error flags to lin.h

---

include/nuttx/pci/pci.h

1. optimize the macro, add () for the marco arguments;
2. add pci_write_mmio_qword() and pci_read_mmio_qword() api;
PCI
qemu-armv8a

pci.h: add pci_write/read_mmio_qword support

---

sched/signal/sig_action.c

nxsig_action will use tcb group when group release, so need clear tcb group after group_release.
[ap] dump_assert_info: Assertion failed : at file: signal/sig_action.c:205 task: ofonod process: Kernel 0xec89d5
[ap] sched_dumpstack: backtrace:
[ap] sched_dumpstack: [29] [<0x66e2e2>] backtrace_unwind+0x105/0x108
[ap] sched_dumpstack: [29] [<0x660272>] sched_backtrace+0x41/0x48
[ap] sched_dumpstack: [29] [<0x61c4dc>] sched_dumpstack+0x33/0x80
[ap] sched_dumpstack: [29] [<0x6023e4>] _assert+0x19b/0x39c
[ap] sched_dumpstack: [29] [<0x61b7e4>] __assert+0x7/0x10
[ap] sched_dumpstack: [29] [<0x6071a2>] nxsig_action+0x119/0x248
[ap] sched_dumpstack: [29] [<0x6072d8>] sigaction+0x7/0x24
[ap] sched_dumpstack: [29] [<0x66a072>] signal+0x4d/0x80
[ap] sched_dumpstack: [29] [<0x100fd36>] …

sched/group: clear tcb group after group_release

---

arch/arm/src/armv8-r/arm_gic.h
arch/arm/src/common/arm_internal.h

1. arm/armv8-r: add implements of arm_get_mpid()
2. arch/arm: fix the bug of armv8-r macro GET_MPIDR
should be core not cpu
Signed-off-by: fanjiangang <fanjiangang@lixiang.com>
N/A
armv8-r SMP

arm/armv8-r: add implements of arm_get_mpid()

---

Documentation/guides/debuggingflash_nuttxonarm.rst
Documentation/guides/index.rst

Migrate debugging/flashing NuttX with hw debbuger documentation from Confluence to official documentation
Simply migrate the [https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=139629444](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=139629444) page
None, it only updates the documentation
I've tested the documentation generation by writing it with the autobuild feature

Doc: Migrate debugging/flashing NuttX with hw debugger

---

arch/arm/src/arm/arm_undefinedinsn.c
arch/arm/src/armv7-a/arm_undefinedinsn.c
arch/arm/src/armv7-r/arm_undefinedinsn.c
arch/arm/src/armv8-r/arm_undefinedinsn.c

Need to save the regs firstly in case syslog triggers another crash. Otherwise we may loose the register contents for the first exception.
Now we have better chance to catch root cause for termination.
Test on armv7-a qemu.
Modify hello_main.c to inject the fault.
```c
{
printf("Hello, World!!\n");
static const uint32_t instruction = 0x12345678;
((void (*)(void))&instruction)();
return 0;
}
```
Compile and Execute:
```
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -Bbuild -GNinja -DBOARD_CONFIG=boards/arm/qemu/qemu-armv7a/configs/nsh nuttx
ninja -C build
qemu-system-arm -cpu cortex-a7 -nographic -machine virt,virtualization=off,gic-version=2 -net none -chardev stdio,id=con,mux=on -serial chardev:con -mon chardev=con,mode=readline -kernel build/nuttx -gdb …
```

arch: set current regs firstly in undefinedinsn

---

libs/libc/netdb/lib_dnsforeach.c

struct sockaddr_in
{
sa_family_t     sin_family;
in_port_t       sin_port;
struct in_addr  sin_addr;
uint8_t         sin_zero[8];
};
sin_zero is probably a random number.
struct sockaddr_in6
{
sa_family_t     sin6_family;
in_port_t       sin6_port;
uint32_t        sin6_flowinfo;
struct in6_addr sin6_addr;
uint32_t        sin6_scope_id;
};
sin6_flowinfo and sin6_scope_id is probably a random number.
Random numbers cause the same server configuration check failed, so let's initialize it.
local:sim

netdb: fix may add duplicate DNS servers

---

tools/configure.sh

tools/configure.sh: add relative path
support #include "../ap/defconfig" in defconfig
defconfig compile
sim:nsh

tools/configure.sh: add relative path

---

boards/arm/mps/mps2-an500/CMakeLists.txt
boards/arm/mps/mps2-an500/src/CMakeLists.txt
boards/arm/mps/mps2-an521/CMakeLists.txt
boards/arm/mps/mps2-an521/src/CMakeLists.txt
boards/arm/mps/mps3-an547/CMakeLists.txt
boards/arm/mps/mps3-an547/src/CMakeLists.txt

1. mps2-an500:add mps2-an500 cmake build
2. mps2-an521:add mps2-an521 cmake build
3. mps3-an547:add mps3-an547 cmake build
4. fix comments

mps/cmake: add cmake build

---

libs/libc/misc/lib_utsname.c

1. In order to directly read the version information of the current file from elf or bin files, memory files, etc., for easy debugging and one-to-one correspondence.
None
None

libc/lib_utsname: Store version number for debugging and preventing optimization

---

arch/arm/src/armv8-r/arm_gicv3.c

armv8-r/gicv3: disable 64bits access gic 64bits registers
When neon is enabled, compiler may optimize 64bits access to vstr, that
will cause data aborts.
Split 64bits access to double 32bits access for GIC_IROUTER/GICR_TYPER,
just like linux.
Signed-off-by: Jinliang Li <lijinliang1@lixiang.com>
N/A
ci-check

armv8-r/gicv3: disable 64bits access gic 64bits registers

---

Documentation/guides/debuggingflash_nuttxonarm.rst

Documentation: cosmetic fixes to follow documentation convention
https://nuttx.apache.org/docs/latest/contributing/documentation.html#headings
none
CI

Documentation: cosmetic fixes to follow documentation convention

---

arch/Kconfig

Revert "nuttx/arch:Enabling ARCH_MATH_H is required when compiling sim with the 13.2 version of the toolchain"

---

arch/arm/src/cmake/clang.cmake

1. The -c parameter should not be added during the link phase, otherwise the link will fail.
2. If it is the clang compiler, its toolchain library should use --print-file-name to find it, otherwise an error will occur
No
NO

arm/cmake: fix cmake compile error

---

.github/workflows/check.yml

To avoid the following CI error:
```
This environment is externally managed
--> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See /usr/share/doc/python3.12/README.venv for more information.
```
Fixes current checks CI.
See the checks CI run.

[FIX CI] ci: use venv for check

---

.github/workflows/build.yml

CI in the msys2 environment, the CMake ninja generator will have a problem with parameters being too long
Msys2
Ci build

build.yml[bugfix]:disable CMake Ninja for Msys2

---

arch/arm/src/armv7-m/arm_systick.c

The parameter of the irq_attach_thread function is not allowed to be empty after update, otherwise will crash.

systick:when isr_handle is NULL will be crash.

---

include/nuttx/arch.h

MSI-like interrupts delivery can be used also for other devices than PCI, e.g HPET
MSI alloc API should be always available
no impact
and runtime …

include/nuttx/arch.h: MSI alloc API should be always available

---

sched/sched/sched_backtrace.c

fix when dump running thread in other-core
sched_backtrace
@jasonbu  give some testing info

sched_backtrace: fix when dump running thread in other-core

---

include/netpacket/vm_sockets.h
include/sys/socket.h
libs/libc/netdb/lib_getaddrinfo.c

Add AF_VSOCK address family support, This is the vsock framework preparation patch.
No, new feature
CI

net/vsock: add AF_VSOCK address family

---

net/netdev/netdev_default.c

Referring to Linux,if there is only a loopback network device and the destination address does not belong to the loopback address, then the loopback network devices is not selected
Referring to Linux,if there is only a loopback network device and the destination address does not belong to the loopback address, then the loopback network devices is not selected
loopback network device

netdev:In netdev_default,If there is only one loopback network devices, it returns NULL
