apache/nuttx

- drivers/input/ff_upper.c
There will be compilation errors about undefined reference to
`enter_critical_section'. Fixed by include irq.h
N/A
Test in vela
> drivers/input: fix complie err about undefined

- net/igmp/igmp_group.c
- net/igmp/igmp_leave.c
1.when dev is down,the driver don't wait msg
2.when igmp_grpfree is excuted,it need cancel the work in the LPWORK
3.the modification is to solve the deadlock caused by work cancel not releasing netlock 
igmp
> fix igmp group issue

- fs/inode/fs_files.c
- include/nuttx/fs/fs.h
- sched/sched/sched_dumponexit.c
sched: delete the dump file list when the thread exits 
Accessing the filelist of other tasks when the thread exits may cause a crash
sim
> sched: delete the dump file list when the thread exits

- arch/x86_64/src/cmake/platform.cmake
- cmake/nuttx_add_romfs.cmake
- cmake/nuttx_toolchain.cmake
1. fix x86_64 cmake build platform.cmake option typo
2. remove unsue cmake options setting in romfs
3. add EXTRA_FLAGS support
Bugfix and Enhancement,
No impact on current
ubuntu sim
CI build
> cmake(refine):fix cmake options typo and add EXTRA_FLAGS support

- sched/instrument/CMakeLists.txt
- sched/instrument/Make.defs
- sched/instrument/instrument.c
- sched/instrument/stack_monitor.c
sched/instrument: rename stack_record.c to stack_monitor.c to align with gprof naming convention.
> sched/instrument: rename stack_record.c to stack_monitor.c

- drivers/i2c/i2c_slave_driver.c
- drivers/ipcc/ipcc_read.c
- drivers/ipcc/ipcc_write.c
driver/i2c/ipcc: Post sempahore only when it's value is smaller than one to avoid waking up the waiting thread redundantly.
avoid semphore count overflow
vela
> driver/i2c/ipcc: Post sempahore only when it's value is smaller than one

- tools/ci/docker/linux/Dockerfile
- tools/ci/platforms/darwin.sh
- tools/ci/platforms/linux.sh
- tools/ci/platforms/msys2.sh
- tools/ci/platforms/ubuntu.sh
1. Add Python tool 'install CI' to MSYS2 platform
2. CI Python Add Package Construction
3. https://github.com/apache/nuttx/pull/14055 patch can't merge because docker file should be merged so it can take effect
NO
NO
> CI: CI Docker adds Python package installation

- include/nuttx/spinlock.h
- include/pthread.h
We should not directly include arch/spinlock.h as it may cause compilation errors in C++.
Instead, we should use nuttx/spinlock.h.
none
ci
> pthread: We should not directly include arch/spinlock.h

- arch/x86_64/src/common/x86_64_pci.c
- drivers/pci/pci.c
- include/nuttx/pci/pci.h
```c
In file included from pci/pci.c:30:
pci/pci.c: In function 'pci_setup_device':
pci/pci.c:449:66: warning: right shift count >= width of type [-Wshift-count-overflow]
449 |           pci_write_config_dword(dev, base_address_1, res->start >> 32);
|                                                                  ^~
pci/pci.c: In function 'pci_presetup_bridge':
pci/pci.c:541:51: warning: right shift count >= width of type [-Wshift-count-overflow]
541 |                              ctrl->mem_pref.start >> 32);
|                                                   ^~
pci/pci.c: In function 'pci_postsetup_bridge':
pci/pci.c:604:57: warning: right shift count >= width of type [-Wshift-count-overflow]
604 |                              (ctrl->mem_pref.start - 1) >> 32);
| …
```
> drivers/pci: fix pci framework warning in 32bit chip

- libs/libm/newlib/Make.defs
VELAPLATFO-38120
Resolve the issue of inability to compile when opening newlib
Change-Id: Iaf3baf568aa608944bf25e9260455bded5493ebc
Declaration of adding depth
no impact
used for verification (arch, board:config, …
> libc/newlib:Declaration of adding depth

- libs/libm/openlibm/0004-libs-libc-Openlibm-adds-exp10-and-exp10f-function-im.patch
- libs/libm/openlibm/Make.defs
Openlibm adds exp10 and exp10f function implementations
no impact
ostest
> libs/libc:Openlibm adds exp10 and exp10f function implementations

- mm/Kconfig
- mm/mm_heap/mm_initialize.c
- mm/tlsf/mm_tlsf.c
The minimum size of mempool can be configured through CONFIG_MM_MPOOL_MINISIZE
add the minimum size configuration of mempool
no impact
and …
> mempool: add the minimum size configuration of mempool

- drivers/misc/optee.c
drivers/optee: Return error if optee_recv return prematurely
optee
ci
> drivers/optee: Return error if optee_recv return prematurely

- include/nuttx/i3c/device.h
1.Changed the i3c_priv_xfer's member to flags from rnw
> Changed the i3c_priv_xfer's member to flags from rnw

- drivers/mtd/mtd_config_fs.c
mtd/nvs: Trigger recovery process in nvs_startup when mtd driver return -EBADMSG
> mtd/nvs: Trigger recovery process in nvs_startup

- arch/arm64/include/arch.h
- arch/xtensa/src/common/xtensa_saveusercontext.c
- include/nuttx/macro.h
- include/nuttx/nuttx.h
- sched/init/nx_bringup.c
#define STRINGIFY(x)" conflicts with https://github.com/mborgerding/kissfft define
> nuttx:move "#define STRINGIFY(x)" to nuttx/macro.h

- include/nuttx/spinlock.h
- sched/irq/irq_spinlock.c
This reverts commit 5aa13bc490ea2e5a0d7462dd0131f9218a35f56a, Related to https://github.com/apache/nuttx/issues/14167
I found that this submission would cause ci warning, So should we revert it first?
```
machine/arch_atomic.c: In function ‘__atomic_load_2’:
machine/arch_atomic.c:51:22: warning: infinite recursion detected [-Winfinite-recursion]
51 |   type weak_function __atomic_load_##n (FAR const volatile void *ptr, \
|                      ^~~~~~~~~~~~~~
machine/arch_atomic.c:354:1: note: in expansion of macro ‘LOAD’
354 | LOAD(2, uint16_t)
| ^~~~
In file included from /home/crafcat7/SSD/vela/nuttx.git/nuttx/include/nuttx/atomic.h:84,
from /home/crafcat7/SSD/vela/nuttx.git/nuttx/include/nuttx/fs/fs.h:40,
from /home/crafcat7/SSD/vela/nuttx.git/nuttx/include/nuttx/sched.h:47,
from …
```
> Revert "sched/spinlock: remove nesting spinlock support"

- libs/libc/machine/arch_atomic.c
libc/atomic: decoupling atomic and spinlock to avoid recursion
1. use irq save in AMP mode
2. use critical section in SMP mode
N/A
gcc14 with sim/smp
> libc/atomic: decoupling atomic and spinlock to avoid recursion

- libs/libc/machine/arm/gnu/arch_setjmp.S
because r4 is an callee saved register, shouldn't modify before saving into stack.
> use r1-r3 as tmp register

- sched/sched/sched_suspendscheduler.c
sched: fix nxsched_suspend_scheduler regression
This commit fixes the regression from https://github.com/apache/nuttx/pull/13877
sched
ci
> sched: fix nxsched_suspend_scheduler regression

- include/netpacket/rpmsg.h
- net/rpmsg/rpmsg_sockif.c
1.  add rpmsg_socket_ept_release for free connection
to  Fix possible use-after-free issues when closing
2.  sendsize should be protected by sendlock
3.  remove backlog=-1 because patch1 has removed
4. Minor cleanups
Simplify the message process in rpmsg_socket_send_single and fix the style issue
5. use hash to handle rp_name
expand the user's rpname size
hash when exceed RPMSG_SOCKET_NAME_LEN due to the limitation of eptname
none
sim
> rpmsg_sockif: add some modifaction for rpsocket

- arch/arm/src/cmake/gcc.cmake
- arch/arm/src/common/Toolchain.defs
- libs/libxx/libcxx.cmake
- libs/libxx/libcxx.defs
- tools/Config.mk
> Unify the definition of GCCVER and remove duplicate code.

- drivers/note/Kconfig
- drivers/note/Make.defs
- drivers/note/note_driver.c
- drivers/note/note_initialize.c
- drivers/note/notectl_driver.c
- drivers/note/notelog_driver.c
- drivers/note/noteram_driver.c
- drivers/note/noterpmsg_driver.c
- drivers/note/notesnap_driver.c
- drivers/note/notestream_driver.c
- drivers/segger/note_rtt.c
- drivers/segger/note_sysview.c
- include/nuttx/note/note_driver.h
- include/nuttx/note/noteram_driver.h
- include/nuttx/sched_note.h
- include/nuttx/streams.h
1. note:support filter for each note channel
2. drivers/note:add the api of sched_note_add 
3. noteram_driver.c:noteram_dump_printf function replaced with lib_bsprintf.
4. drivers/note:add the poll function for noteram
5.  fix bugs
none
sim
> note enhance

- include/nuttx/spinlock.h
- sched/irq/irq_spinlock.c
since https://github.com/apache/nuttx/pull/14200 fix the dead lock.
we reapply https://github.com/apache/nuttx/pull/14190
none
Target(s): sim/smp
After that, there will be no warnings for compilation
make distclean -j20; ./tools/configure.sh -l sim:smp;make -j20
Copy files
Select CONFIG_HOST_LINUX=y
Refreshing...
CP: arch/dummy/Kconfig to /home/hujun5/downloads1/vela_sim/nuttx/arch/dummy/dummy_kconfig
CP: boards/dummy/Kconfig to /home/hujun5/downloads1/vela_sim/nuttx/boards/dummy/dummy_kconfig
LN: platform/board to /home/hujun5/downloads1/vela_sim/apps/platform/dummy
LN: include/arch to arch/sim/include
LN: include/arch/board to /home/hujun5/downloads1/vela_sim/nuttx/boards/sim/sim/sim/include
LN: drivers/platform to …
> Reapply "sched/spinlock: remove nesting spinlock support"

- boards/risc-v/esp32c6/esp32c6-devkitc/src/esp32c6_boot.c
- boards/risc-v/esp32c6/esp32c6-devkitm/src/esp32c6_boot.c
This PR allow esp32c6 devkit c and esp32c6 devkit m to start different app than nsh when CONFIG_BOARD_LATE_INITIALIZE is necessary
It is now possible to compile the project when CONFIG_BOARD_LATE_INITIALIZE is enabled
Go to master branch, follow steps below: 
You will face compilation issue. 
Go to this branch, try again, now it is possible compile.
> ESP32C6-DevKit C/M Add necessary Import to compilation

- Documentation/guides/changing_systemclockconfig.rst
- Documentation/guides/index.rst
Migrate the Changing the System Clock Configuration documentation from the Confluence wiki to the official documentation
Simply migrate the [https://cwiki.apache.org/confluence/display/NUTTX/Changing+the+System+Clock+Configuration](https://cwiki.apache.org/confluence/display/NUTTX/Changing+the+System+Clock+Configuration) page
None, it only updates the documentation
I've tested the documentation generation by writing it with the autobuild feature
> Doc: Migrate changing the system clock configuration

- Documentation/guides/index.rst
- Documentation/guides/usingkernelthreads.rst
Migrate page Using Kernel Threads from Confluence wiki to official wiki
Migrate [Using Kernel Threads](https://cwiki.apache.org/confluence/display/NUTTX/Using+Kernel+Threads) to official wiki
None, just update wiki
Build doc with `make autobuild`
> Doc: Migrate Using Kernel Threads

- arch/xtensa/src/esp32s3/esp32s3_wifi_adapter.c
- arch/xtensa/src/esp32s3/esp32s3_wlan.c
xtensa/esp32s3: add wapi support for getting country code commands on ESP32-S3
Only esp32s3
Testing use esp32s3-devkitc
```
nsh> wapi show wlan0
wlan0 Configuration:
IP: 10.0.0.2
NetMask: 255.255.255.0
Frequency: 2412
Flag: WAPI_FREQ_AUTO
Channel: 1
Frequency: 2412
ESSID:
Flag: WAPI_ESSID_OFF
Mode: WAPI_MODE_MANAGED
AP: ff:ff:ff:ff:ff:ff
BitRate: 0
Flag: WAPI_BITRATE_AUTO
TxPower: 20
Flag: WAPI_TXPOWER_DBM
Sense: -128
Country: CN
```
> xtensa/esp32s3: add support for getting country code

- include/nuttx/spinlock.h
- include/pthread.h
- libs/libc/machine/arch_atomic.c
- sched/irq/irq_spinlock.c
Revert "pthread: We should not directly include arch/spinlock.h as it may cause compilation errors in C++."
Revert "sched/spinlock: remove nesting spinlock support"
Revert "libc/atomic: decoupling atomic and spinlock to avoid recursion"
Further work(without this feature could be closed):
https://github.com/apache/nuttx/pull/14200
N/A
ci-check
> Revert "libc/atomic: decoupling atomic and spinlock to avoid recursion"

- Documentation/guides/armv7m_runtimestackcheck.rst
- Documentation/guides/index.rst
Migrate the ARMv7-M run time stack checking documentation page from the Confluence wiki to the official documentation.
Simply migrate the [https://cwiki.apache.org/confluence/display/NUTTX/ARMv7-M+Run+Time+Stack+Checking](https://cwiki.apache.org/confluence/display/NUTTX/ARMv7-M+Run+Time+Stack+Checking) page
None, it only updates the documentation
I've tested the documentation generation by writing it with the autobuild feature
> Doc: Migrate ARMv7-M run time stack checking doc

- arch/x86_64/src/Makefile
Adjust the position of the nm command to execute it 
no impact
qemu ostest
> x86/x86_64:Adjust the position of the nm command to execute it after NuttX is generated

- arch/arm64/src/common/arm64_mpu.c
```
common/arm64_mpu.c:355:13: error: format '%llX' expects argument of type 'long long unsigned int', but argument 4 has type 'long unsigned int' [-Werror=format=]
355 |       _info("MPU-%d, 0x%08llX-0x%08llX SH=%llX AP=%llX XN=%llX\n", i,
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
common/arm64_mpu.c:355:29: note: format string is defined here
355 |       _info("MPU-%d, 0x%08llX-0x%08llX SH=%llX AP=%llX XN=%llX\n", i,
|                        ~~~~~^
|                             |
|                             long long unsigned int
|                        %08lX
common/arm64_mpu.c:355:13: error: format '%llX' expects argument of type 'long long …
```
> arch/arm64: fix build warnings

- arch/x86_64/src/cmake/Toolchain.cmake
> arch/x86_64:Add CXX configuration for enabling x86_64 support for C++ applications.

- drivers/segger/config/SEGGER_SYSVIEW_Conf.h
- drivers/segger/note_sysview.c
Avoid another layer of function call to get time.
Minor code refactor, should have no impact.
> drivers/segger: inline note_sysview_get_timestamp

- mm/mempool/mempool.c
- sched/misc/assert.c
We have `BACKTRACE_BUFFER_SIZE ` now, thus use it direct for buffers to hold backtrace.
Minor code refactor, no impact.
> Use BACKTRACE_BUFFER_SIZE to declare backtrace buffer

- sched/misc/coredump.c
for (; cinfo.regions[memsegs].start <
cinfo.regions[memsegs].end; memsegs++);
coredump
fc7300
> coredump: fix bug that memsegs got invalid value

- .github/linters/setup.cfg
- tools/checkpatch.sh
1.  Config multi line output to mode 3, so isort and black can agree with
each other:
```
3 - Vertical Hanging Indent
from third_party import (
lib1,
lib2,
lib3,
lib4,
)
```
2. Exit with error if python code needs to format
No impact.
CI build pass.
> Py code check update

- arch/arm/src/armv7-m/Kconfig
- arch/arm/src/armv7-m/arm_systick.c
irq_attach_wqueue replace irq_attach_thread
reason:
using a shared same priority queue can reduce memory consumption.
isrthread
ci test
> irq: irq_attach_wqueue replace irq_attach_thread

- Documentation/guides/disabling_stackdumpdebug.rst
- Documentation/guides/include_files_board_h.rst
- Documentation/guides/index.rst
- Documentation/guides/specialstuff_in_nuttxheaderfiles.rst
This PR migrate 3 other pages from the Confluence wiki to the official wiki:
- Disabling the Stack Dump During Debugging 
- Including files in board.h
- Why can't I put my special stuff in NuttX header files?
None, update the wiki
Build with `make autobuild`
> Doc: migration 1

- arch/arm/src/armv7-a/arm_smpcall.c
- arch/arm/src/armv7-r/arm_smpcall.c
- arch/arm64/src/common/arm64_smpcall.c
sched: fix nxsched_process_delivered did not call hook
add some hook will not affect function
ostest
> sched: fix nxsched_process_delivered did not call hook

- Documentation/guides/index.rst
- Documentation/guides/kernel_threads_with_custom_stacks.rst
Migrate
https://cwiki.apache.org/confluence/display/NUTTX/Kernel+Threads+with+Custom+Stacks to official wiki
Migrate Kernel Threads with Custom Stacks to official wiki
None, update the doc
Build with `make autobuild`
> Doc: Migrate Kernel Threads with Custom Stacks

- libs/libc/modlib/modlib_bind.c
- libs/libc/modlib/modlib_insert.c
modlib bug fix
1. allow 64bit elf load
2. so need export symbols, exec elf don't need export symbols
modlib
`rv-virt:knsh`  and `rv-virt:knsh64` with ostest and getprime, pass it
> modlib:bug fix,allow 64bit elf load and if sym is NULL not load symbol

- arch/sim/src/sim/posix/sim_hostirq.c
Sometimes asan may generate some false positives, so it is temporarily turned off.
> nuttx/sim:Remove asan check in up_irq_save().

- arch/arm/src/armv7-a/arm_addrenv_shm.c
nuttx/arch/arm/src/armv7-a/arm_addrenv_shm.c:77:(.text.up_shmat+0x2e): undefined reference to `shminfo'
shm
ci
> shm:fix build error

- include/nuttx/elf.h
nuttx/include/nuttx/elf.h:118:1: error: unknown type name 'bool'
118 | bool up_checkarch(FAR const Elf_Ehdr *hdr);
| ^~~~
nuttx/include/nuttx/elf.h:30:1: note: 'bool' is defined in header '<stdbool.h>'; did you forget to '#include <stdbool.h>'?
29 | #include <arch/elf.h>
+++ |+#include <stdbool.h>
30 |
> nuttx/elf.h: Fix build error with unknown type name 'bool'.

- arch/x86_64/src/cmake/platform.cmake
- libs/libc/dlfcn/CMakeLists.txt
- libs/libc/dlfcn/Make.defs
- libs/libc/dlfcn/lib_dlfind_object.c
Add _dl_find_object() function, because when cxx_exception configuration is enabled, a link error occurs and that function cannot be found.
ld: /usr/lib/gcc/x86_64-linux-gnu/13/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `_Unwind_Find_FDE':
(.text+0x250c): undefined reference to `_dl_find_object'
> nuttx/libc:Add _dl_find_object and dl_iterate_phdr function.

- CMakeLists.txt
systemmap and usermap depends nuttx_post(in protected build mode)
avoiding time order confusion
fixed a bug where the map file was executed before compilation.
qemu protected build
> cmake(bugfix):add dependencies for nuttx_post ensure time order

- arch/arm/src/cmake/gcc.cmake
The warning printout of the CI log will slow down our ability to locate the real problem
toolchain file variable is global scope
dont need set parent scope
clear warning:
```shell
CMake Warning (dev) at /github/workspace/sources/nuttx/arch/arm/src/cmake/gcc.cmake:69 (set):
Cannot set "GCCVER": current scope has no parent.
Call Stack (most recent call first):
/github/workspace/sources/nuttx/arch/arm/src/cmake/Toolchain.cmake:56 (include)
/github/workspace/sources/nuttx/build/CMakeFiles/3.26.0/CMakeSystem.cmake:6 (include)
/github/workspace/sources/nuttx/build/CMakeFiles/CMakeScratch/TryCompile-ZJVOZO/CMakeLists.txt:5 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.
``` 
clear generator warning 
cmake -B build -DBOARD_CONFIG=qemu-armv7a:nsh
> cmake(clear warning):toolchain file do not need set parent scope

- libs/libxx/__config_site
LD: nuttx
arm-none-eabi-ld: warning: net_sendfile.o: missing .note.GNU-stack section implies executable stack
arm-none-eabi-ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
arm-none-eabi-ld: warning: nuttx/nuttx has a LOAD segment with RWX permissions
arm-none-eabi-ld: apps/staging/libfeature.a(feature_framework.cpp.frameworks.base.feature_1.o): in function `std::__1::__throw_length_error[abi:un170006](char const*)':
> gnu++20:fix ld error.

- libs/libc/stdio/lib_libvsprintf.c
use sim32 print 0x8000000000000000 to reproduce this problem
stdio/lib_libvsprintf.c:1018:17: runtime error: negation of -9223372036854775808 cannot be represented in type 'long long int'; cast to an unsigned type to negate this value to itself
#0 0x3326a86 in vsprintf_internal stdio/lib_libvsprintf.c:1018
#1 0x332926b in lib_vsprintf stdio/lib_libvsprintf.c:1363
#2 0x3777978 in vfprintf stdio/lib_vfprintf.c:52
#3 0x671b3a0 in printf stdio/lib_printf.c:44
#4 0x37abc0c in hello_main /data/project/code/vela-pt/apps/examples/hello/hello_main.c:38
#5 0x33201d3 in nxtask_startup sched/task_startup.c:70
#6 0x3208ecb in nxtask_start task/task_start.c:134
#7 0x3357a49 in pre_start sim/sim_initialstate.c:52
printf
sim nsh
> vsprintf:fix bug when print int64 0x8000000000000000

- boards/sim/sim/sim/scripts/Make.defs
/usr/bin/ld: nuttx.rel: relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
> sim/m64:Fix ld error.

- openamp/open-amp.cmake
since we disable find_package(libmetal) so we need to set open_amp target include dirs link to metal target
bugfix for open_amp cmake build
qemu build pass
> cmake(bugfix):disable proxy and service source in open-amp

- arch/arm64/include/arch.h
- arch/arm64/include/irq.h
- arch/arm64/src/common/arm64_cpustart.c
- arch/arm64/src/common/arm64_doirq.c
- arch/arm64/src/common/arm64_fatal.c
- arch/arm64/src/common/arm64_registerdump.c
- fs/procfs/fs_procfstcbinfo.c
- include/nuttx/arch.h
- libs/libc/time/lib_localtime.c
- net/utils/net_snoop.c
- sched/init/nx_start.c
- sched/sched/sched.h
- sched/sched/sched_addreadytorun.c
- sched/sched/sched_mergepending.c
- sched/sched/sched_process_delivered.c
- sched/sched/sched_profil.c
- sched/sched/sched_removereadytorun.c
We can utilize percpu storage to hold information about the             
current running task. If we intend to implement this feature, we would  
need to define two macros that help us manage this percpu information   
effectively.
up_this_task: This macro is designed to read the contents of the percpu 
register to retrieve information about the current        
running task.This allows us to quickly access             
task-specific data without having to disable interrupts,  
access global variables and obtain the current cpu index. 
up_update_task: This macro is responsible for updating the contents of  
the percpu register.It is typically called during       
initialization or when a context switch occurs to ensure
that the percpu register reflects the information of the
newly running …
> percpu reg store this_task

- libs/libc/misc/lib_err.c
- libs/libc/stdio/Kconfig
- libs/libc/stdio/lib_libvsprintf.c
- libs/libc/symtab/Kconfig
1. This is a new function that implements the method of printing the serialized data of the structure in a similar way to %pV %pS.
2. Add LIBC_PRINT_EXTENSION option to control the opening of %p*, which is closed by default
None. This is a new parameter parsing and does not affect existing parameters.
```
pc: ubuntu 20.04,x86, SIM
void orb_info(FAR const char *format, FAR const char *name,
FAR const void *data)
{
struct lib_stdoutstream_s stdoutstream;
struct va_format vaf;
vaf.fmt = format;
vaf.va  = (va_list *)data;
lib_stdoutstream(&stdoutstream, stdout);
lib_sprintf(&stdoutstream.common, "%s(now:%" PRIu64 "):%pB\n",
name, orb_absolute_time(), &vaf);
}
```
order: `uorb_listener -n 10 sensor_accel_uncal`
out:
```
Mointor objects num:1
object_name:sensor_accel_uncal, object_instance:0 …
```
> lib_libvsprintf.c: add Add support for %pB parameter.

- include/nuttx/coredump.h
Configuration/Tool: teensy-2.0/nsh
In file included from
/github/workspace/sources/nuttx/include/nuttx/coredump.h:35:0,
from
/github/workspace/sources/nuttx/sched/misc/coredump.h:28,
from ./init/nx_bringup.c:54:
/github/workspace/sources/nuttx/include/nuttx/elf.h:31:22: fatal error: arch/elf.h: No such file or directory
non arm arch
ci build
> elf:fix a ci error

- .github/workflows/check.yml
Add Black, isort and Flake8 to `check` linter. This follows issues found in #14319 .
A previous modification was done on master #14176 but missed those packages.
Installs Python linter packages to this release.
Running tests on this PR.
@lupyuen @jerpelea
> ci: add Python linter to check

- include/sched.h
- sched/sched/sched_resumescheduler.c
add #define CPU_SETSIZE in sched.h to pass tlpi example: https://man7.org/tlpi/code/online/dist/procpri/t_sched_getaffinity.c.html
> add #define CPU_SETSIZE in sched.h

- arch/Kconfig
- arch/arm/src/armv6-m/arm_cpuinfo.c
- arch/arm/src/armv7-a/arm_cpuinfo.c
- arch/arm/src/armv7-a/arm_fpuconfig.S
- arch/arm/src/armv7-m/arm_cpuinfo.c
- arch/arm/src/armv7-r/arm_cpuinfo.c
- arch/arm/src/armv7-r/arm_fpuconfig.S
- arch/arm/src/armv8-m/arm_cpuinfo.c
- arch/arm/src/armv8-r/arm_cpuinfo.c
- arch/arm/src/armv8-r/arm_fpuconfig.S
- arch/xtensa/src/common/xtensa_cpuinfo.c
- sched/sched/sched.h
- sched/sched/sched_cpuload.c
- sched/sched/sched_critmonitor.c
1.Add the default CPU frequency configuration.
2.arm/fpu: FPU is supported when the TEE is enabled
3.cpuload: add nxsched_update_critmon() to handle thread busyloop
used for verification (arch, board:config, ..), …
> cpuinfo: Decouple the fetch cpuinfo from up_perf_getfreq

- arch/arm/src/armv7-a/arm_tcbinfo.c
armv7-a:adjust gdb register order
debug
Register arrangement inside gdb armv7a,
use coredump with armv7-a qemu and gdbstub pass it.
```
(gdb) maint print remote-registers
Name         Nr  Rel Offset    Size  Type            Rmt Nr  g/G Offset
r0            0    0      0       4 uint32_t              0           0
r1            1    1      4       4 uint32_t              1           4
r2            2    2      8       4 uint32_t              2           8
r3            3    3     12       4 uint32_t              3          12
r4            4    4     16       4 uint32_t              4          16
r5            5    5     20       4 uint32_t              5          20
r6            6    6     24       4 uint32_t              6          24
r7            7    7     28       4 uint32_t …
```
> armv7-a:adjust gdb register order

- arch/arm/src/sama5/sam_adc.c
Compiler warning relating to unused variable has been fixed. It is a specific use case when the ADC is software triggered and with no ADC REGDEBUG in use.
Might be a better/cleaner fix but this works at least.
None - it is a benign fix that simply cleans up the compilation
On a custom board equipped with a SAMA5D27C-D1G using the ADC peripheral in SW TRIGGER mode.
> SAMA5 fix compiler warning in sam_adc.c

- boards/arm/s32k3xx/mr-canhubk3/src/s32k3xx_tja1153.c
- drivers/wireless/ieee80211/bcm43xxx/bcmf_netdev.c
- include/net/if.h
- net/netdev/netdev_ioctl.c
turn off interface by checking IFF_UP flag isn't set: https://github.com/apache/nuttx/issues/1838
RELEASE
CI
> {Bp-13842} net: Remove IFF_DOWN flag to compatible with Linux/*BSD

- mm/iob/iob.h
- mm/iob/iob_add_queue.c
- mm/iob/iob_alloc.c
- mm/iob/iob_alloc_qentry.c
- mm/iob/iob_free.c
- mm/iob/iob_free_qentry.c
- mm/iob/iob_free_queue_qentry.c
- mm/iob/iob_initialize.c
- mm/iob/iob_remove_queue.c
`g_iob_sem.semcount` is both manually changed in iob source code and api
nxsem_xxx.
nxsem related API uses critical_section to ensure sem value is modified
correctly. If iob using spin lock and modify sem value in the same time,
it's not safe.
This PR revert the spin lock change and uses critical section to align
with what nxsem uses.
iob can work correctly.
Originally tested with iperf2 tool. cc @wangchen61698
> Revert "mm/iob: Replace the critical section with spin lock"

- libs/libc/stream/lib_stdoutstream.c
lib_stdoutstream:need return write size
bugfix
qmue with mps3 an547
Previously, the return value would cause some code to fall into an infinite loop.
> lib_stdoutstream:need return write size

- .github/linters/setup.cfg
- tools/checkpatch.sh
Summary
Config multi line output to mode 3, so isort and black can agree with
each other:
3 - Vertical Hanging Indent
from third_party import (
lib1,
lib2,
lib3,
lib4,
)
Exit with error if python code needs to format
Impact
No impact.
Testing
CI build pass.
> {Bp-14253} Py code check update

- .github/workflows/check.yml
Summary
ci: add Python linter to check
[FIX CI] ci: use venv for check #14176 
To avoid the following CI error:
This environment is externally managed
--> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See /usr/share/doc/python3.12/README.venv for more information.
Impact
Fixes current checks CI.
Testing …
> {Bp-14323} ci: add Python linter to check

- net/usrsock/usrsock_event.c
The original process was to change conn->resp.result to 0 in usrsock_handle_response when receiving tcp ack status conn->state was USRSOCK_CONN_STATE_CONNECTING during the event USRSOCK_EVENT_SENDTO_READY. However, in exceptional circumstances, usrsock_handle_response was processed late, and conn->resp.result was not yet 0, resulting in the inability to change conn->connected status to connected when processing the USRSOCK_EVENT_SENDTO_READY event. Therefore, the modification method is to also change the conn->connected status to connected when the conn->state is USRSOCK_CONN_STATE_CONNECTING and the event is USRSOCK_EVENT_SENDTO_READY.
NA
NA
> modify for set conn status with connected when receive event USRSOCK_EVENT_SENDTO_READY

- Kconfig
- include/nuttx/compiler.h
Add an option to disable compilation of floating point
libs/libc
qmue with mps3an547
some platform can't use float
> Kconfig:Add an option to disable compilation of floating point

- tools/gdbserver.py
gdbserver.py optimization
1. support xtensa arch use coredump pase thread
2. skip load elf symbol if just use log file
gdbserver.py
crash with qemu mps3an547 with log, and use gdbserver.py debug it.
> gdbserver.py optimization

- .github/labeler.yml
.github/labler.yml: fix condition for Area: Bluetooth
I noticed that this PR https://github.com/apache/nuttx/pull/14311 hasn't a label assigned
fix typo
none
> .github/labler.yml: fix condition for Area: Bluetooth

- arch/arm/src/armv7-m/CMakeLists.txt
In this PR, we add the missing source files required by the MPS-AN500 prototyping board when building with Cmake.
Broken building for the mps2-an500 board using cmake.
The cmake build system
> mps2-an500: add missing source file

- drivers/serial/serial_cmsdk.c
serial/serial_cmsdk.c: In function 'uart_cmsdk_ioctl': serial/serial_cmsdk.c:544:10: warning: 'ret' may be used uninitialized in this function [-Wmaybe-uninitialized]
544 |   return ret;
|          ^~~
> drivers/serial: fix cmsdk serial driver warning

- mm/Kconfig
1. Group related configurations together.
2. Use `if endif` for GRAN(Granule Allocator) module.
3. Fix typos and misleading hints
4. Add necessary depends on 
- ~MM_HEAP_BIGGEST_COUNT depends on !FS_PROCFS_EXCLUDE_MEMDUMP~
- FS_PROCFS_EXCLUDE_MEMPOOL depends on MM_HEAP_MEMPOOL_THRESHOLD > 0    - 
Should be minimal since most of the change is to adjust order.
build process, hardware, documentation, security, …
> mm/Kconfig: adjust config options order and fix typos

- binfmt/Kconfig
- libs/libc/modlib/Kconfig
- sched/Kconfig
since bootloader may call modlib functions directly to load elf firmware without binfmt, dlfcn or module.
BTW, this patch also remove the duplicated selecttion
> libc/modlib: Make modlib selectable from defconfig

- mm/mm_heap/mm_free.c
- mm/mm_heap/mm_initialize.c
- mm/mm_heap/mm_malloc.c
- mm/mm_heap/mm_memalign.c
- mm/tlsf/mm_tlsf.c
1. Hold lock when access mm struct field from sched_note_heap.
2. Fix kasan reported error when delay free feature is enabled. See comments in code.
```
/* If delay free is enabled, a memory node will be freed twice.
* The first time is to add the node to the delay list, and the second
* time is to actually free the node. Therefore, we only colorize the
* memory node the first time, when `delay` is set to true.
*/
```
~3. Remove CONFIG_MM_MAP_COUNT_MAX option. User should take care of it.~ It causes `ltp_interfaces_mmap_24_1` test to fail, remove this patch for now.
Bug fixes should have no impact on existing projects.
Local tested with qemu.
```
tools/configure.sh mps3-an547:nsh
```
Change CONFIG_MM_REGIONS = 1 to reduce the heap size, in order to make kasan faster.
Enable
``` …
```
> Memory delay free kasan error fix and  memory note fix

- arch/sim/src/sim/sim_offload.c
sim/posix/sim_offload.c:369:18: runtime error: left shift of 255 by 24 places cannot be represented in type 'int'
#0 0x3a146c2  (/home/qiaohj/disk1/work/vela/nuttx/nuttx+0x3a146c2)
#1 0x3a0ecb0  (/home/qiaohj/disk1/work/vela/nuttx/nuttx+0x3a0ecb0)
#2 0x3a1193a  (/home/qiaohj/disk1/work/vela/nuttx/nuttx+0x3a1193a)
#3 0x3a13141  (/home/qiaohj/disk1/work/vela/nuttx/nuttx+0x3a13141)
#4 0x39fc3ef  (/home/qiaohj/disk1/work/vela/nuttx/nuttx+0x39fc3ef)
#5 0x38ca7f2  (/home/qiaohj/disk1/work/vela/nuttx/nuttx+0x38ca7f2)
#6 0x39fc6cf  (/home/qiaohj/disk1/work/vela/nuttx/nuttx+0x39fc6cf)
> sim/alsa: fix runtime warning.

- include/nuttx/lib/stdatomic.h
Fixed build issue:
error: expected '=', ',', ';', 'asm' or '__attribute__' before 'atomic_wchar_t'
NA
flagchip protected build success and ostest pass
> lib/stdatomic: include stddef.h in atomic.h

- libs/libc/string/CMakeLists.txt
- libs/libm/libm/CMakeLists.txt
libs/xxx/CMakeLists.txt: add cmake compile support
Add the lib_bzero.c files to the build use it's API
Add the floating point math C files to the build to use it's API
Test in vela
> libs/xxx/CMakeLists.txt: add cmake compile support

- arch/x86_64/src/intel64/intel64_head.S
- boards/x86_64/intel64/qemu-intel64/scripts/qemu.ld
The segment of the Xen PVH boot protocol was not specified during linking and was placed before .loader.text, causing the boot to fail
Resolving NUC Boot Failure Issue
no impact
used for verification (arch, …
> arch/x86_64: Resolving NUC Boot Failure Issue

- sched/signal/sig_findaction.c
- sched/task/task_setup.c
Use spinlock repalce sched_[un]lock in some place
In SMP, sched_lock cannot prevent concurrent access
none
ci ostest
> sched: Use spinlock repalce sched_[un]lock in some place

- arch/arm64/src/imx8/imx8_boot.c
This pull request is aimed at resolving an issue where unauthorized writes to the `cntfrq_el0` register occur during the system boot process when the system is not operating in EL3 (Exception Level 3) mode. The `cntfrq_el0` register is a read-only register in lower exception levels, and any writes to it can lead to unpredictable behavior. 
This commit addresses the issue of unauthorized writes to cntfrq_el0 during boot when not in EL3 mode.
Tested on QEMU-virt/armv8a
> imx8qm-mek: Resolve boot issue for non-EL3 environments

- include/nuttx/queue.h
In the previous design, this member may be cleared or not cleared,
which results in the API's side effects not being a clear property.
> include: queue.h: Make flink clear after sq_rem

- sched/sched/sched_critmonitor.c
sched: remove duplicate functions
nxsched_critmon_cpuload has two identical implementations
sim
> sched: remove duplicate functions

- arch/arm/src/common/Toolchain.defs
- libs/libxx/libcxx.defs
expr: syntax error: unexpected argument "12"
expr: syntax error: unexpected argument "12"
No
No
> bug/fix: Makefile expression error caused

- include/nuttx/coredump.h
- sched/misc/coredump.c
1. need close blk dev when do coredump finsh
2. fix memory region bug
3. measure the system's running time in milliseconds unit
coredump
qmue use coredump
> coredump bug fix

- net/can/can_sendmsg.c
- net/devif/devif_poll.c
- net/netdev/netdev_default.c
This PR fixes two issues with socketcan
1. Don't select CAN device as "default" netdev (e.g. in netdev_findbyaddr()). This causes sending IP data to socket can drivers.
3. Fix cmsg data (timeout timestamp) appending to socket can messages. This has broken at some point, I am not sure how/why:
- First, copy the cmsg (timeout time stamp) data into IOB together with the data in can_sendmsg.c/psock_send_eventhandler . Set the d_sndlen to message+timestamp length, and d_len to the actual data length.
- Second, in devif_poll, iob_copyout the max of (d_len, d_sndlen) to pass the data to the can drivers.
This PR has been tested in imx9 platform, with two network interfaces 1) ethernet, 2) can.
> Socketcan fixes

- arch/sim/src/sim/sim_offload.c
- include/nuttx/audio/audio.h
1. Current 8 bits data cannot represent sample rate bigger than 255,change samplerate data type from uint8_t to uint32_t to expand sample rate range. 
2. Set real sample rate and encode method separately, according to different pcm data format.
Enhance current audio capacity.
Build success in Sim.
> Expand samplerate bits from 8 to 32, enchance encode capacity in sim offload.

- libs/libc/misc/lib_circbuf.c
In circbuf_get_read/writeptr, when circbuf is full, off == pos, and *size = off - pos = 0. So add circbuf_is_full() condition to return correct *size.
circbuf
qemu armv8a
> circbuf: fix circbuf_get_read/writeptr return *size = 0 when circbuf full

- LICENSE
- libs/libc/time/CMakeLists.txt
- libs/libc/time/Make.defs
- libs/libc/time/lib_strptime.c
The community deleted strptime due to license reasons, and we replaced it with musl.
Re-add the strptime.c file so that the system has the ability to convert and process date strings.
In order to ensure the correctness and stability of the changes, we have taken the following steps to verify:
Code review: First, we conducted a detailed review of the changed code to ensure that the code was logically correct, had no syntax errors, and complied with the project's coding specifications.
Integration testing: We then integrated the changed code with the rest of the project and ran comprehensive integration tests to ensure that the entire system was functioning properly.
> Add strptime

- arch/sim/src/sim/sim_heap.c
The default heap management in nuttx returns a valid memory address when malloc(0).
In sim_heap, malloc(0) returns NULL, aligning the behavior of sim_heap with mm_heap
The man manual describes malloc as follows:
https://man7.org/linux/man-pages/man3/malloc.3.html
The malloc() function allocates size bytes and returns a pointer to the allocated memory.  
The memory is not initialized.  If size is 0, then malloc() returns a unique pointer value that can later
be successfully passed to free().
sim
> sim/heap: malloc returns a valid pointer when allocating 0 bytes.

- Documentation/components/drivers/character/can.rst
- drivers/can/Kconfig
- drivers/can/mcp2515.c
- include/nuttx/can/can.h
nuttx/can.h: support timestamp for can frame
and update "can.rst" file for add struct timeval ch_ts info.
NULL.
tested on the board with cortex-M architecture.
> nuttx/can.h: support timestamp for can frame.

- drivers/pci/pci.c
*When PCIe device have msix and not msi capability in qemu devices, we can not config MSI capability.*
> Fix disable msi when msi capability not exist issue

- arch/arm/include/armv8-r/cp15.h
armv8-r/cp15: fix the problem of op1 operand confusion in ICC_SGI1R
Reference:
https://developer.arm.com/documentation/100026/0103/Generic-Interrupt-Controller/GIC-programmers-model/CPU-Interface-Registers
CRn   Op1    CRm    Op2
ICC_SGI0R  -     2     c12     -
ICC_SGI1R  -     0     c12     -
Signed-off-by: fanjiangang <fanjiangang@lixiang.com>
N/A
ci-check
> armv8-r/cp15: fix the problem of op1 operand confusion in ICC_SGI1R

- libs/libc/stdio/lib_libbsprintf.c
libs: remove lib_libbsprintf automatic line wrapping
> libs: remove lib_libbsprintf automatic line wrapping

- fs/rpmsgfs/rpmsgfs.c
fs/rpmsgfs[bug fix]: return real err value when open failed
get real errno for rpmsgfs open failed
Ci
> fs/rpmsgfs[bug fix]: return real err value when open failed

- drivers/can/CMakeLists.txt
- drivers/can/Kconfig
- drivers/can/Make.defs
- drivers/can/can.c
- drivers/can/can_sender.c
- include/nuttx/can/can.h
- include/nuttx/can/can_sender.h
Linked list-based priority sorting function for sending messages.
This PR introduces a new priority-based sending mechanism for the CAN protocol stack, addressing the need for deterministic message delivery in time-critical applications. The change modifies the CAN driver files to implement a linked list-based priority queue for outgoing CAN frames.
The priority of a CAN frame is determined by CAN ID. This allows applications to prioritize critical messages, ensuring they are transmitted ahead of less important ones, even under high bus load.
New Feature: Adds priority-based sending for CAN frames.
User Impact: YES. Users can now enable and configure priority sending using Kconfig options.
Build Impact: YES. To enable priority sending, users must select the CAN_TXPRIORITY during build …
> nuttx/can: support to Send message priority sorting function.

- tools/esp32/Config.mk
- tools/esp32c3/Config.mk
- tools/esp32s2/Config.mk
- tools/esp32s3/Config.mk
- tools/espressif/Config.mk
- tools/espressif/check_esptool.py
**Summary**
Add a Python script to check if esptool is installed and if its version is up-to-date (see minimum version at ESPTOOL_MIN_VERSION on .mk files).
This fixes build issues as reported in https://github.com/apache/nuttx/issues/13824.
**Impact**
New Python script added. Stops build if esptool version is below 4.8.
Script runs for ESP32, S2, S3, C3, C6.
**Testing**
Tested locally and on internal CI with Python3.8+.
**NOTE**
backported https://github.com/apache/nuttx/pull/14176 to fix the CI
> {Bp-14267} tools/espressif: add esptool version check to Espressif build system

- LICENSE
- libs/libc/string/lib_memmem.c
- libs/libc/string/lib_strstr.c
Use CONFIG_ALLOW_MIT_COMPONENTS to control the implementation of strstr and memmem.
memmem();
> libc/memmem:porting open source memmem to Nuttx.

- arch/xtensa/include/esp32s3/partition.h
- arch/xtensa/src/esp32s3/esp32s3_partition.c
- arch/xtensa/src/esp32s3/esp32s3_spiflash.c
- arch/xtensa/src/esp32s3/esp32s3_spiflash.h
arch/esp32s3/partition: Inspect if the MTD partition (factory/ota_0/ota_1) is mapped as text.
Relocate the enum ota_img_ctrl_e and ota_img_bootseq_e to a directory visible to the application.
Only esp32s3
Testing use esp32s3-devkitc
> xtensa/esp32s3: inspect if partition mapped as text

- libs/libxx/libcxx.cmake
- libs/libxx/libcxxabi.cmake
> libxx: Globally reference the header file of libcxxabi.

- audio/audio.c
To prevent the completion event from being reported and then executing stop, it will fail.
> audio: remove started from audio_complete

- arch/risc-v/src/common/riscv_cpustart.c
Some spurious interrupt might wake WFI, ensure we got woken by IPI before continuing CPU boot.
RISC-V SMP only, there should be no change to functionality
rv-virt:ksmp64
> riscv/cpustart: Ensure we receive Soft IRQ / IPI before booting CPU

- libs/libc/stdlib/Kconfig
- libs/libc/unistd/CMakeLists.txt
- libs/libc/unistd/Make.defs
- libs/libc/unistd/lib_getcwd.c
since getcwd() can be implemented correctly without using environ
extend getcwd usage
ci
> libc: Make getcwd() work even CONFIG_DISABLE_ENVIRON is enabled

- arch/arm64/src/imx9/Kconfig
- arch/arm64/src/imx9/imx9_flexcan.c
This is an addition to imx9 flexcan driver to make "self receive disable" flag to be configurable. This feature can be used to make can block not receive what it sent itself.
It can be configured for upper layers if the self-sent frames are received or not.
Tested on a custom imx93 board, setting the flag on and off, sending frames and monitored if they are also received or not.
> imx9/flexcan: Make self reception disable to be configurable

- .github/workflows/doc.yml
This change to the Documentation workflow adds the `paths` filter so that the GitHub workflow is only run whenever a path matching `Documentation/**` is modified. It also removes the PDF building step, which is not necessary since Documentation is built on the NuttX website.
Note from @cederom: We got final warning from Apache on exceeding CI usage and need find savings! This subject is discussed on dev@ mailing list.
This will reduce the number of unnecessary Documentation workflow runs being performed for PRs that do not modify the documentation and thus do not require a rebuild. It also removes unnecessary building of PDF documents, which speeds up the workflow.
Since building the Documentation takes about 13 minutes on average, this should considerably reduce the amount of time the …
> ci: documentation workflow optimizations.

- mm/mempool/mempool.c
- mm/mempool/mempool_multiple.c
Fix memory pool backtrace minor issues.
1. Should use `backtrace_format` to format backtrace now.
2. Default to turn of recording backtrace if `CONFIG_MM_BACKTRACE_DEFAULT ` is disabled. 
Fix memory pool de-init. 
Mark dict pointer as NULL after free, in case misuse of it.
Minor fixes, should have no impact.
and runtime logs from before …
> `mempool` backtrace fix and de-init fix

- arch/arm/src/samv7/sam_serial.c
- include/nuttx/serial/tioctl.h
The `TIOCSLINID` was initially added by https://github.com/apache/nuttx/pull/5043, but now after https://github.com/apache/nuttx/pull/11002 it is not needed. 
Code clean-up and should be none
Pass CI
> serial: remove 'TIOCSLINID'

- arch/Kconfig
- arch/risc-v/include/irq.h
- arch/risc-v/src/common/riscv_cpuindex.c
- arch/risc-v/src/common/riscv_cpustart.c
- arch/risc-v/src/common/riscv_internal.h
- arch/risc-v/src/common/riscv_ipi.h
- arch/risc-v/src/common/riscv_macros.S
- arch/risc-v/src/common/riscv_mhartid.S
- include/nuttx/arch.h
- include/nuttx/sched.h
Implement hartid<->cpuid mapping for RISC-V. This is necessary for some
platforms which cannot use 1:1 mapping between logical and physical CPU /
core IDs. One example is MPFS where hart0 cannot be used for NuttX SMP as
it is a less capable "monitor" core (E51) compared to the application
cores hart1...3 (E54).
Why not just use a generic offset then? We also need the physical hart ID
for many things:
- Communication between harts (IPI)
- External interrupt acknowledgment (interrupt claim for specific CPU)
- Communication to SBI
Thus, create procedures that can do this translation:
- The default mapping is still logical=physical.
- Another flavor is to use the existing CONFIG_ARCH_RV_HARTID_BASE config
variable, which is just a simple offset
- The final flavor is to overload hartid<->cpuid …
> arch/riscv: Add cpuid mapping (hartid<->cpuid)

- libs/libc/stdio/Kconfig
See the discussion in https://github.com/apache/nuttx/pull/13536
> Discourage the use of LIBC_PRINT_EXTENSION

- arch/arm/src/common/arm_exit.c
- arch/arm64/src/common/arm64_exit.c
- arch/avr/src/common/avr_exit.c
- arch/hc/src/common/hc_exit.c
- arch/mips/src/common/mips_exit.c
- arch/misoc/src/lm32/lm32_exit.c
- arch/misoc/src/minerva/minerva_exit.c
- arch/or1k/src/common/or1k_exit.c
- arch/renesas/src/common/renesas_exit.c
- arch/risc-v/src/common/riscv_exit.c
- arch/sim/src/nuttx-names.in
- arch/sim/src/sim/sim_exit.c
- arch/sim/src/sim/sim_idle.c
- arch/sparc/src/common/sparc_exit.c
- arch/tricore/src/common/tricore_exit.c
- arch/x86/src/common/x86_exit.c
- arch/x86_64/src/common/x86_64_exit.c
- arch/xtensa/src/common/xtensa_exit.c
- arch/z16/src/common/z16_exit.c
- arch/z80/src/common/z80_exit.c
- sched/pthread/pthread_exit.c
- sched/sched/sched_setpriority.c
- sched/sched/sched_suspend.c
- sched/task/exit.c
- sched/task/task_exit.c
- sched/task/task_exithook.c
- sched/task/task_terminate.c
multiple backports
https://github.com/apache/nuttx/pull/13728
https://github.com/apache/nuttx/pull/13731
https://github.com/apache/nuttx/pull/13734
https://github.com/apache/nuttx/pull/13753
https://github.com/apache/nuttx/pull/13777
Release
fix issue https://github.com/apache/nuttx/issues/13830
CI & local test
> {Bp-sim] multiple backports to fix sim 

- arch/risc-v/src/common/riscv_cpuindex.c
The offset was supposed to assume hartid > cpuid, so when converting from hartid we must subtract the offset to get the cpuid and vice versa.
Only RISC-V with SMP and CONFIG_ARCH_RV_HARTID_BASE != 0
rv-virt:ksmp64
MPFS (unpublished SMP target)
> riscv_cpuindex.c: Fix usage of CONFIG_ARCH_RV_HARTID_BASE

- libs/libc/modlib/modlib_symbols.c
In file included from modlib/modlib_symbols.c:34:
modlib/modlib_symbols.c: In function 'modlib_symvalue': modlib/modlib_symbols.c:432:41: error: pointer of type 'void *' used in arithmetic [-Werror=pointer-arith]
432 |               (uintptr_t)(sym->st_value + symbol->sym_value));
|                                         ^
make[1]: *** [Makefile:156: bin/modlib_symbols.o] Error 1
Fixes build error in modlib. No other modules affected.
Build pass.
> modlib/modlib_symbols.c: Fix usage of void* arithmetics

- arch/Kconfig
- arch/arm/Kconfig
- arch/arm/src/armv6-m/Make.defs
- arch/arm/src/armv7-m/Make.defs
- arch/arm/src/armv8-m/Make.defs
- arch/arm/src/cxd56xx/CMakeLists.txt
- arch/arm/src/cxd56xx/Make.defs
- arch/arm/src/cxd56xx/cxd56_vectors.c
- arch/arm/src/lc823450/Make.defs
- arch/arm/src/lc823450/lc823450_vectors.c
- arch/arm/src/rp2040/Make.defs
- arch/arm/src/rp2040/rp2040_vectors.c
- arch/arm/src/sam34/Kconfig
- arch/arm/src/sam34/Make.defs
- arch/arm/src/sam34/sam_vectors.c
When sig dispatch do up_schedule_sigaction, need to make a new frame to run arm_sigdeliver. But the exception_direct cannot handle xcp.regs as we are using c-function exception handler.
Need to use exception_common to handle SMP call.
issue from https://github.com/apache/nuttx/pull/13606#issuecomment-2406601519
@masayuki2009 please review the update, and see it at your environments also work as expected.
use chip specific vector cxd56_vectors to make CXD56_IRQ_SMP_CALL not use c-call version exception handler.
can pass the self-test in Spresense CPU=3 case.
for self-test, the _vector still in .map, maybe we should add option to make unique between cxd56_vectors and _vectors.
CI-test.
```bash
./tools/configure.sh -l spresense/smp 
kconfig-tweak --set-val CONFIG_SMP_NCPUS 3
make -j …
```
> arm/cxd56: use chip specific vectors to allow smpcall update regs

- .github/workflows/arch.yml
When we submit or update a Complex PR that affects All Architectures (Arm, RISC-V, Xtensa, etc): CI Workflow shall run only half the jobs. Previously CI Workflow will run `arm-01` to `arm-14`, now we will run only `arm-01` to `arm-07`.
When the Complex PR is Merged: CI Workflow will still run all jobs `arm-01` to `arm-14`
Simple PRs with One Single Arch / Board will build the same way as before: `arm-01` to `arm-14`
This is explained here: https://github.com/apache/nuttx/issues/14376
Note that this version of `arch.yml` has diverged from `nuttx-apps`, since we are unable to merge https://github.com/apache/nuttx/pull/14377
When we submit or update a Complex PR: CI Workflow shall run only half the jobs: `arm-01` to `arm-07` (instead of `arm-01` to `arm-14`)
No changes to the CI Workflow …
> CI: Skip jobs arm-08 to arm-14 when a Complex PR is created / updated

- .github/workflows/arch.yml
- .github/workflows/build.yml
This PR disables all CI Jobs for macOS and Windows, to reduce GitHub Cost. Details here: https://github.com/apache/nuttx/issues/14376
CI Jobs for macOS and Windows will no longer run, until we find a way to manage their costs.
We tested the skipping of macOS and Windows jobs: https://github.com/lupyuen5/label-nuttx/actions/runs/11379543159
> CI: Disable all jobs for macOS and Windows

- tools/parsetrace.py
- Fix usage of non-existing variable `args.out`.
- Fix dump trace not writing to the output file.
- Fix path provided through `-o` getting ignored and always using the default output filename.
Executed the script with a text trace file and verified the output file got the `tracing_mark_write` addresses replaced by their symbol names from the ELF file.
> tools: fix parsetrace.py output

- libs/libc/string/Kconfig
* Changes in https://github.com/apache/nuttx/pull/13180 contained a typo `libs/libc/string/Kconfig` that broke initial `./tools/configure.sh`.
* Here goes the typo fix.
* Thank you @lupyuen for the hint! :-)
* Initial Configure / Build.
* FreeBSD 13.3 AMD64.
* Before fix:
```
% ./tools/configure.sh -B nucleo-l432kc:nsh
Copy files
Select CONFIG_HOST_BSD=y
Refreshing...
CP: arch/dummy/Kconfig to /XXX/nuttx.git/arch/dummy/dummy_kconfig
CP: boards/dummy/Kconfig to /XXX/nuttx.git/boards/dummy/dummy_kconfig
LN: platform/board to /XXX/nuttx-apps.git/platform/dummy
LN: include/arch to arch/arm/include
LN: include/arch/board to /XXX/nuttx.git/boards/arm/stm32l4/nucleo-l432kc/include
LN: drivers/platform to /XXX/nuttx.git/drivers/dummy
LN: include/arch/chip to …
```
> libc: Fix typo in libc/string/Kconfig.

- tools/esp32s3/Config.mk
this # would be parsed by make as a start of a comment.
bulild tested on macOS (ignoring https://github.com/apache/nuttx/issues/14390)
gmake version:
```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
This program built for i386-apple-darwin11.3.0
```
> tools/esp32s3/Config.mk: fix "unterminated call to function" error

- tools/checkpatch.sh
Flag --diff will output the changes content.
Flag --check-only will return exit code. It can be used together with --diff.
Run isort again to format the code in place, to make the behavior same as before.
If isort check fails, now CI will report error.
Tested on CI and it detects py format issue correctly.
> tools/checkpatch: fix isort doesn't return error

- arch/risc-v/src/common/riscv_cpuindex.c
- arch/risc-v/src/common/riscv_internal.h
Return 0 for CPU ID for any hart ID, and return the current Hart ID for any CPU ID. At least these values are somewhat usable / meaningful in non-SMP configurations.
RISC-V and non-SMP only.
MPFS SMP and non-SMP targets
> ricv/riscv_cpuid: Return meaningful values for CPU/Hart ID when SMP=no

- libs/libc/tls/task_tls_destruct.c
So It's easy to find TASK_TLS_ELEM not enough error.
> libc: Add debug assert to prevent tls allocation failure

- cmake/menuconfig.cmake
- tools/testbuild.sh
Renamed savedefconfig -> refreshsilent name more consistent with the refresh stage for cmake on github.
Added new savedefconfig to fix
https://github.com/apache/nuttx/issues/14281
1. config with CMake
cmake -B build -DBOARD_CONFIG=nucleo-l152re:nsh
2. change any config with menuconfig
cmake --build build -t menuconfig
For example  Disable CONFIG_EXAMPLES_HELLO
3. savedefconfig use cmake
cmake --build build -t savedefconfig
now the build directory has the updated defconfig file
> cmake: Renamed savedefconfig with refreshsilent

- sched/timer/timer_setitimer.c
The change is necessary to optimize the `setitimer` implementation by removing an unnecessary conditional branch that checks for the existence of an `itimer` within the task's group before creating one. This simplification enhances code readability and potentially improves performance by reducing the overhead of redundant checks. 
This change affects the kernel's timer subsystem by streamlining the `setitimer` function. Users should experience no direct impact, but the system's efficiency in managing timers may improve slightly. The build process remains unchanged, and there are no hardware or documentation changes required. Security and compatibility are not affected by this change. The main impact is on the internal logic of the `setitimer` function.
Tested on QEMU/x86_64 and …
> sched/timer: Simplify setitimer implementation.

- .github/workflows/arch.yml
When we submit or update a Complex PR that affects All Architectures (Arm, RISC-V, Xtensa, etc): CI Workflow shall run only half the jobs for RISC-V, Xtensa and Simulator:
- `risc-v-01` to `03`
- `xtensa-01`
- `sim-01`
When the Complex PR is Merged: CI Workflow will still run all jobs for RISC-V, Xtensa and Simulator:
- `risc-v-01` to `06`
- `xtensa-01` to `02`
- `sim-01` to `02`
Simple PRs with One Single Arch / Board will build the same way as before:
- `risc-v-01` to `06`
- `xtensa-01` to `02`
- `sim-01` to `02`
We hope to lower drastically our usage of GitHub Runners before the ASF Deadline, as explained here: https://github.com/apache/nuttx/issues/14376
When we submit or update a Complex PR: CI Workflow shall run only half the jobs for RISC-V, Xtensa and Simulator:
- `risc-v-01` to …
> CI: Skip half of RISC-V, Xtensa and Simulator targets when a Complex PR is created / updated

- CMakeLists.txt
- arch/arm/src/cmake/gcc.cmake
- cmake/nuttx_toolchain.cmake
enable warning info output with color font decorate
has no impact on current build procedure
has tested on gnu compiler
> cmake: fix the fdiagnostics-color handle issue

- boards/arm/stm32l4/nucleo-l432kc/include/board.h
- boards/arm/stm32l4/nucleo-l432kc/src/Makefile
- boards/arm/stm32l4/nucleo-l432kc/src/nucleo-l432kc.h
- boards/arm/stm32l4/nucleo-l432kc/src/stm32_appinit.c
- boards/arm/stm32l4/nucleo-l432kc/src/stm32_dac.c
* Nucleo-L432KC board was missing internal MCU DAC initialization code.
* DAC is now available on PA4/A3 and /dev/dac0 when enabled.
* Updated info on ADC inputs (PA6/A5,PA7/A6) depending on configuration.
* Most boards have pins hadrcoded in `*.h` and `*.c` files, here too, would be nice to have them configurable via Kconfig, but there is no generic mechanism for that yet?
boards / nucleo-l432kc can now use DAC.
* Build host: FreeBSD 13.3 AMD64.
* Test setup: oscilloscope on A4, generator on A5 nucleo pins.
* Before: DAC was not available even though enabled in the config.
* After: DAC is available as `/dev/dac0` and controllable with example `dac` application.
```
nsh> uname -a
NuttX 12.7.0-RC0 a94c099b7d-dirty Oct 19 2024 06:44:25 arm nucleo-l432kc
nsh> ls /dev
/dev:
adc0
console
dac0 …
```
> boards/nucleo-l432kc: Add internal DAC code.

- .github/workflows/arch.yml
- .github/workflows/build.yml
- tools/ci/testlist/arm64-01.dat
- tools/ci/testlist/other.dat
- tools/ci/testlist/x86_64-01.dat
This PR creates the new CI Build Jobs `arm64-01` and `x86_64-01`. The new jobs will split and offload the Arm64 and x86_64 Build Targets from `other`. This will reduce our usage of GitHub Runners, to comply with the ASF Policy for GitHub Actions. (Recently we see more PRs for Arm64 and x86_64)
__Before the Split:__ Simple PRs (One Arch and/or One Board) for Arm64 and x86_64 require almost 1 hour for CI Build
- `other` (57 mins): AVR, SPARC, x86, PinePhone, QEMU Arm64, QEMU x86_64
__After the Split:__ Simple PRs for Arm64 and x86_64 will complete under 30 mins
- `other` (24 mins): AVR, SPARC, x86
- `arm64-01` (29 mins): PinePhone, QEMU Arm64
- `x86_64-01` (9 mins): QEMU x86_64
To skip more unnecessary builds: Our Build Rules `arch.yml` shall ignore the label "Area: Documentation", so that …
> CI: Split the Build Jobs for Arm64 and x86_64

- arch/arm/src/samv7/sam_spi_slave.c
- arch/arm/src/stm32h7/stm32_spi_slave.c
- arch/risc-v/src/common/espressif/esp_spi_slave.c
- arch/risc-v/src/esp32c3-legacy/esp32c3_spi_slave.c
- arch/xtensa/src/esp32/esp32_spi_slave.c
- arch/xtensa/src/esp32s2/esp32s2_spi_slave.c
- arch/xtensa/src/esp32s3/esp32s3_spi_slave.c
drivers/spi_slave: call SPIS_DEV_NOTIFY when rx or tx complete for all spi slave driver
This PR is related to issue:https://github.com/apache/nuttx/issues/14369
call notify interface to notify userspace when read or write block
local
> drivers/spi_slave: call SPIS_DEV_NOTIFY when rx or tx complete for all spi slave driver

- .github/workflows/arch.yml
This PR updates the Build Rules `arch.yml` to build only these Arm32 Targets when we create or update a Complex PR:
- arm-01, arm-03, arm-05, arm-06, arm-07, arm-09, arm-11
No changes for Simple PRs (arm-01 to arm-14) and for Merging PRs (also arm-01 to arm-14).
This will improve our breadth of CI Checks across Arm32 Targets, as explained here: https://github.com/apache/nuttx/issues/14376
We build only these Arm32 Targets when we create or update a Complex PR:
- arm-01, arm-03, arm-05, arm-06, arm-07, arm-09, arm-11
No changes for Simple PRs and for Merging PRs.
Creating a Complex PR will build only arm-01, arm-03, arm-05, arm-06, arm-07, arm-09, arm-11
- https://github.com/lupyuen5/label-nuttx/actions/runs/11426738940
Creating a Simple PR will build arm-01 to arm-14
- …
> CI: Build only Arm32 Targets arm-01 / 03 / 05 / 06 / 07 / 09 / 11 for Complex PRs

- drivers/pci/pci_ecam.c
struct pci_ops_s defined uint32，unified data structure
> Fix make warn as error in pci drivers

- drivers/syslog/Kconfig
- drivers/syslog/ramlog.c
since the conversion is moved to common layer after: https://github.com/apache/nuttx/pull/14362
Remove the duplicated code
ci
> ramlog: Remove RAMLOG_CRLF config and related code

- drivers/syslog/Kconfig
enable LF to CRLF config as default
log output
selftest
> syslog: enable LF to CRLF config as default

- arch/sim/src/cmake/Toolchain.cmake
SIM arch does not need to execute find_program
this should fix issue https://github.com/apache/nuttx/issues/14413
cmake -B build -DBOARD_CONFIG=sim/libcxxtest -GNinja
cmake --build build
> cmake(bugfix):Fixed the issue that the host toolchain version cannot be specified

- fs/nxffs/nxffs_dump.c
If CONFIG_FS_LARGEFILE is enabled, the off_t is 64bit. And if you enable CONFIG_DEBUG_FS the gcc report compile error like this: 
> nxffs/nxffs_dump.c:161:30: error: format '%li' expects argument of type 'long int', but argument 3 has type 'off_t' {aka 'long long int'} [-Werror=format=]
So use PRIiOFF instead of PRIi32.
Just impact fs nxffs debug.
Test with esp32c6-Devkitc board.
> fs/nxffs: Fix syslog formats compile error

- libs/libxx/libcxx.cmake
- libs/libxx/libcxx.defs
fix https://github.com/apache/nuttx/issues/14412 warning
Why didn’t we have this problem before? Because we have recently optimized cxx, and related source files will not be compiled when CXX_EXCEPTION is turned off.
enable CONFIG_LIBCXX and disable CONFIG_CXX_EXCEPTION
ci-test
> libcxx: Ignore compile warnings.

- arch/arm/src/cmake/gcc.cmake
- arch/arm64/src/cmake/Toolchain.cmake
- arch/risc-v/src/cmake/Toolchain.cmake
There are some errors in cmake's definition of GCCVER, which causes cmake to not find the definition of GCCVER when compiling. https://github.com/apache/nuttx/issues/14412 This has been fixed.
libcxx
ci test
> fix GCCVER cmake define.

- .github/ISSUE_TEMPLATE/001_bug_report.yml
- .github/ISSUE_TEMPLATE/002_feature_request.yml
- .github/ISSUE_TEMPLATE/003_help.yml
- .github/workflows/issue_labeler.yml
Not all labels are added because there is no match with the label name.
issue_labeler.yml
os: Linux -> os: linux
001_bug_report.yml
Type: bug -> Type: Bug
Corrected label in links
002_feature_request.yml
Type: enhancement -> Type: Enhancement
Corrected label in links
003_help.yml
Type: question -> Community: Question
Corrected label in links
CI
https://github.com/simbit18/nuttx-testing-templates/issues
> ISSUE_TEMPLATE: fix missing labels

- boards/arm/stm32f7/nucleo-f722ze/src/CMakeLists.txt
- boards/arm/stm32f7/nucleo-f746zg/src/CMakeLists.txt
- boards/arm/stm32f7/nucleo-f767zi/src/CMakeLists.txt
fix this error (for nucleo-f746zg nucleo-f722ze nucleo-f767zi)
CMake Error at boards/arm/stm32f7/nucleo-f746zg/src/CMakeLists.txt:76 (endif):
Flow control statements are not properly nested.
CMake Error at boards/arm/stm32f7/nucleo-f746zg/src/CMakeLists.txt:76 (endif):
Flow control statements are not properly nested.
-- Configuring incomplete, errors occurred!
https://github.com/simbit18/nuttx_test_pr/actions/runs/11442005741/job/31831476469#step:7:359
Allows you to build nuttx with cmake for nucleo-f746zg nucleo-f722ze nucleo-f767zi
ci
> boards/arm/stm32f7: removed extra endif() from cmakefile for nucleo-f746zg nucleo-f722ze nucleo-f767zi

- boards/risc-v/esp32c6/common/src/esp_board_spiflash.c
Added structure for partition initialization. 
Purpose of integration with MCUboot and ESP32C6.
RISC-V/ESP32
./tools/configure.sh esp32c6-devkitc:mcuboot_nsh
> Adding partitioning support for OTA

- tools/esp32s3/Config.mk
* tools/esp32s3/Config.mk: fix "printf:\`': invalid format character"
The error was introduced by #14393, which was intended to fix this line for MacOS. This commit makes this line dependent on the host OS to avoid any compilation errors.
Fix compile issues related to the legacy bootloader of the ESP32-S3 on both Linux and MacOS. CI didn't get the error because `CONFIG_ESP32S3_MERGE_BINS` is not tested.
Internal CI testing + ESP32-S3-DevKitC-1 v1.0 board (esp32s3-devkit:knsh + `CONFIG_ESP32S3_MERGE_BINS=y`).
> tools/esp32s3/Config.mk: fix "printf:`\': invalid format character"

- .github/workflows/build.yml
- tools/ci/testlist/sim-01.dat
- tools/ci/testlist/sim-02.dat
- tools/ci/testlist/sim-03.dat
CI Build Job sim-01 has become the bottleneck for compiling Complex PRs. This PR splits sim-01 and adds sim-03.
__Before the Split:__ Simulator Jobs take up to 1.5 hours to complete
- sim-01 (1 hour 31 mins): adb, citest, lvgl, matter
- sim-02 (28 mins): posix_test, sqlite
__After the Split:__ Simulator Jobs will complete within 1 hour
- sim-01 (58 mins): adb, citest
- sim-02 (35 mins): lvgl, matter
- sim-03 (28 mins): posix_test, sqlite
This will help us comply with the ASF Policy for GitHub Actions, as explained here: https://github.com/apache/nuttx/issues/14376
When we create or modify a Complex PR, the CI Checks for Simulator will complete earlier. CI Job sim-01 will no longer be the bottleneck for compiling Complex PRs. 
__Timings Before the Split:__ …
> CI: Split the targets in sim-01 and add sim-03

- arch/arm/src/qemu/qemu_memorymap.c
- arch/arm/src/qemu/qemu_memorymap.h
add memory map for DDR region
fix arm-v7a/knsh boot dataabort on arm_addrenv_utils.c first time memset after arm_pgvaddr.
will dataabort before fix.
```
[    0.008000] arm_dataabort: Data abort. PC: 00606d42 DFAR: 48000000 DFSR: 00000805
[    0.008000] dump_assert_info: Current Version: NuttX  12.7.0-RC0 e00fbc5557d-dirty Oct 21 2024 20:26:19 arm
[    0.008000] dump_assert_info: Assertion failed panic: at file: armv7-a/arm_dataabort.c:161 task: Idle_Task process: Kernel 0x600c05
[    0.008000] up_dump_register: R0: 48000000 R1: 00000000 R2: 48000400  R3: 48000000
[    0.008000] up_dump_register: R4: 48000000 R5: 0000000b R6: 00000000  FP: 40205e00
[    0.008000] up_dump_register: R8: 00000000 SB: 80000000 SL: 0000a108 R11: 0000015f
[    0.008000] up_dump_register: IP: 00000028 SP: …
```
> arm: fix dataabort on qemu-armv7a:knsh

- fs/mnemofs/Kconfig
- fs/mnemofs/mnemofs.c
- fs/mnemofs/mnemofs.h
- fs/mnemofs/mnemofs_master.c
Add logs and extra logs to mnemofs VFS methods for bind and unbind.
Adds logs (`MFS_LOG` and `MFS_EXTRA_LOG`) to mnemofs, and implements them in `mnemofs_bind` and `mnemofs_unbind`.
- Better debugging using the improved logs.
- **Build Impact**: No.
- **User Impact**: Better logs to report in case of crashes.
- **Documentation**: The code printing the logs also serve as section-wise docs.
I confirm that changes are verified on local setup and works as intended:
Build Host(s): OS (Linux), CPU(Intel), compiler(GCC 13).
Target(s): arch(sim), sim:mnemofs.
Logs before:
```
nsh> mount -t mnemofs -o forceformat /dev/nand /hi
binfs_stat: Entry
find_blockdriver: pathname="/dev/nand"
find_blockdriver: /dev/nand is a MTD
mnemofs_bind: Mnemofs bind.
nand_wrapper: [UPPER 1 | ioctl] Command: 1537, Arg …
```
> fs/mnemofs: Add logs to bind and unbind.

- sched/task/task_exit.c
The comment about the CPU index remaining stable is incorrect. There is no guarantee the task does not yield during the exit process, meaning the CPU can most definitely change. Also, there is no reason why it should not be allowed to change -> refresh current CPU ID whenever is used.
This fixes a full system crash during process exit when the CPU changes and we query the current task from the old CPU.
Fix task/process exit logic, when CONFIG_SMP=y. No other parts are affected.
qemu-rv:ksmp64
Unpublished MPFS SMP target
> sched/task_exit.c: Refresh current CPU instead of relying on stale value

- net/local/local_conn.c
now the lc_path of the client will not be the same as that of the server. therefore, accept->peer = NULL will not be set when the client release the conn, then when release accept conn, set
client->peer(accept->peer->peer) = NULL will cause used after free.
sim:local
> net/local: fix used after free

- arch/sim/src/sim/sim_uart.c
LF to CRLF has been converted in syslog framework
rm LF to CRLF convertion
syslog
selftest
> sim_uart: rm LF to CRLF convertion

- include/ctype.h
- libs/libc/ctype/lib_ctype.c
libcxx: fix compile error
from ServiceManager.cpp:17:
/home/ligd/platform/dev/apps/external/android/frameworks/native/libs/binder/ndk/include_cpp/android/binder_to_string.h:71:24: error: expected nested-name-specifier before numeric constant
71 |     template <typename _U>
|                        ^~
/home/ligd/platform/dev/apps/external/android/frameworks/native/libs/binder/ndk/include_cpp/android/binder_to_string.h:71:24: error: expected ‘>’ before numeric constant
In file included from /home/ligd/platform/dev/apps/external/android/frameworks/native/libs/binder/aidl/android/os/ConnectionInfo.h:3,
from /home/ligd/platform/dev/apps/external/android/frameworks/native/libs/binder/aidl/android/os/IServiceManager.h:3,
from /home/ligd/platform/dev/apps/external/android/frameworks/native/libs/bi …
> libcxx: fix compile error

- arch/arm64/src/common/arm64_vectors.S
use 33-bit (+/-4GB) pc-relative addressing to load the address of arm64_fatal_handle
Some project，the vector table in TCM， but the arm64_fatal_handle in ddr，this case 
vector table may be far away form arm64_fatal_handle
> arhc/arm64: vector table may be far away form arm64_fatal_handle

- boards/sim/sim/sim/scripts/Make.defs
sim: fix asan address space conflict
Modify the starting position of the elf segment to 0x5000000
==2561587==Shadow memory range interleaves with an existing memory mapping. ASan cannot proceed correctly. ABORTING. ==2561587==ASan shadow was supposed to be located in the [0x1ffff000-0x3fffffff] range. ==2561587==Process memory map follows:
sim
> sim: fix asan address space conflict

- arch/arm64/src/Toolchain.defs
1. --param asan-instrument-reads=0 and --param asan-instrument-writes=0 is supported in arm64, they have been added in other  arch toolchain.defs
> arm64/toolchains:Add the following kasan compilation options

- arch/arm64/src/common/arm64_perf.c
1. remove unused variable 'cpu_freq'
> remove unused variable 'cpu_freq'

- arch/arm/src/cmake/gcc.cmake
- arch/arm/src/common/Toolchain.defs
Add --no-warn-rwx-segments in case of RAM boot mode to linker to suppress the below warning:
"nuttx has a LOAD segment with RWX permissions"
Suppress the warning message "nuttx has a LOAD segment with RWX permissions" in case of RAM boot mode is selected.
RAM MODE: BOOT_RUNFROMEXTSRAM/BOOT_RUNFROMISRAM/BOOT_RUNFROMSDRAM/BOOT_COPYTORAM
"nuttx has a LOAD segment with RWX permissions" is suppressed
Tested on company internal's project, BOOT_RUNFROMISRAM is selected. I can't find a proper board to reproduce the issue in master.
> arm/build: suppress LOAD RWX linker warning

- arch/arm64/src/imx9/imx9_lpspi.c
This PR corrects the 9-16 bit transfers on IMX9 LPSPI, where buffer lengths were handled wrong. The driver was originally tested only on 8-bit transfers.
Additionally, this syncs the driver with TII branch by adding a small optimization for cache invalidation.
Impacts only imx9 platform and lpspi when using >8 bit transfers
Tested on custom imx93 board, connected to adis16470 IMU via SPI, using 16-bit transfers.
> Imx9 lpspi fixes

- boards/sim/sim/sim/scripts/Make.defs
LD:  nuttx
nuttx.rel: in function `ff_dct32_float_sse2':
(.text+0x66f9e): relocation truncated to fit: R_X86_64_32S against symbol `ff_cos_32' defined in .bss.ff_cos_32 section in nuttx.rel
(.text+0x66fa7): relocation truncated to fit: R_X86_64_32S against symbol `ff_cos_32' defined in .bss.ff_cos_32 section in nuttx.rel
(.text+0x672a6): relocation truncated to fit: R_X86_64_32S against symbol `ff_cos_16' defined in .bss.ff_cos_16 section in nuttx.rel
(.text+0x672ae): relocation truncated to fit: R_X86_64_32S against symbol `ff_cos_16' defined in .bss.ff_cos_16 section in nuttx.rel
nuttx.rel: in function `ff_imdct_calc_sse':
(.text+0x67905): relocation truncated to fit: R_X86_64_32S against symbol `ff_cos_64' defined in .bss.ff_cos_64 section in nuttx.rel
(.text+0x67948): relocation …
> nuttx/sim: Fix m64 build error.

- sched/task/task_exit.c
I noticed that sched_note_stop() is never called for tasks that exit normally. This patch fixes a regression from #13728 ; there is a missing call to sched_note_stop() in task_exit().
Fixes the scheduler instrumentation when a task exits. Nothing else is affected.
Private MPFS target with sched note driver.
> task_exit.c: Add missing sched_note_stop()

- drivers/serial/Kconfig
- libs/libc/gdbstub/lib_gdbstub.c
gdbstub:remove ARCH_HAVE_DEBUG depends
gdbstub
build wtih qmeu use gdbstub
> gdbstub:remove ARCH_HAVE_DEBUG depends

- include/nuttx/coredump.h
- sched/misc/coredump.c
coredump_add_memory_region need use flags
coredump
CI
> coredump: coredump_add_memory_region need use flags

- .github/workflows/arch.yml
CI Build Job sim-02 was disabled to reduce our usage of GitHub Runners, to comply with ASF Policy: https://github.com/apache/nuttx/issues/14376#issuecomment-2427837859
However this causes the Scheduled Merge Job to fail, due to reduced CI Checks: https://github.com/NuttX/nuttx/actions/runs/11490041505/job/31980056690#step:7:465
This PR re-enables sim-02 when we create or update a Complex PR.
When we create or update a Complex PR, the CI Workflow will now run sim-02, for improved CI Checking.
Creating a Complex PR now executes sim-02: https://github.com/lupyuen5/label-nuttx/actions/runs/11490590600?pr=82
> CI: Enable sim-02 build when we create or update a Complex PR

- drivers/mmcsd/mmcsd_sdio.c
Before setting the buswidth , check whether caps has the capability
mmcsd_sdio
local test
> mmcsd: SDIO_CAPS_4BIT_ONLY set buswidth MMCSD_SCR_BUSWIDTH_4BIT

- Documentation/applications/examples/spislv_test/index.rst
This documentation refers to PR: https://github.com/apache/nuttx-apps/pull/2765
> Writing documentation related to SPI slave.

- arch/sim/src/sim/CMakeLists.txt
sim/cmake: compatible when nuttx COMPILE_OPTIONS is not set yet
#14440 
when COMPILE_OPTIONS is not set, cmake will report an error: 
HOST_COMPILE_OPTIONS-NOTFOUND
as we only want to do item remove. so let's skip the remove procedure at this case.
@simbit18 I did not try the win host and re-produce the problem, please help me verify if it will work, I will do verify later.
fix bug when msvc build.
CI-test & ubuntu sim:nsh.
> when COMPILE_OPTIONS is not set, skip the REMOVE_ITEM in ${HOSTSRCS}, fix msvc reported case.

- drivers/usbdev/cdcncm.c
Minor debug printf formatter error resulting in compiler warning.
It compiles without warning when using this driver. The driver was - and is - working OK for me.
> Fix CDCNCM driver printf formatter compiler warning

- arch/arm/src/cmake/gcc.cmake
- arch/arm/src/common/Toolchain.defs
- arch/arm64/src/Toolchain.defs
- arch/arm64/src/cmake/Toolchain.cmake
- arch/risc-v/src/cmake/Toolchain.cmake
- arch/risc-v/src/common/Toolchain.defs
LD: nuttx
flash:      284272 B       512 KB     54.22%
sram1:       13296 B         2 MB      0.63%
sram2:          0 GB         2 MB      0.00%
CP: nuttx.hex
CP: nuttx.bin
> kconfig: Add link parameters that can print remaining memory information

- arch/arm/src/sama5/sam_sfc.c
Updated sam_sfc.c to call EFUSEIOC_MASK rather than EFUSEIOC_SAMA5_MASK - this error must have slipped through my original testing and submission of the SMA5 SFC functionality, or a later change to EFUSE IOCTL naming messed it up.
Allows correct compilation
Limited to compilation as no code I have or could find calls this IOCTL
> sam_sfc.c incorrect EFUSEIOC name used

- arch/arm/src/armv8-r/arm_doirq.c
arm/armv8-r: fix unable to switch context in ISR context
Regression by https://github.com/apache/nuttx/pull/13651:
```
| commit 35c8c80a00a99ff0e19d51eaa74165bd830a36f8
| Author: ligd <liguiding1@xiaomi.com>
| Date:   Fri Jul 26 23:14:13 2024 +0800
|
| arch: change nxsched_suspend/resume_scheduler() called position
```
N/A
CI-CHECK
> arm/armv8-r: fix unable to switch context in ISR context

- arch/arm/include/armv8-r/cp15.h
- arch/arm/src/armv8-r/arm_head.S
- arch/arm/src/armv8-r/sctlr.h
1. init HSCTLR to enable i-cache/d-cache for EL2
2. init HACTLR to enable all access to implementation defined registers for EL1.
3. add dsb/isb before switch to EL1 from EL2
Init HSCTLR and HACTLR at EL2.
armv8-r:  Control EL2 cache switch.   Enable access IMPLEMENT DEFINED register from EL1.
ARM Cortex-R52
> arm/armv8-r: init HSCTLR and HACTLR for EL2

- arch/arm/src/armv8-r/arm_gicv3.c
- arch/arm64/include/irq.h
- arch/arm64/src/common/arm64_gicv3.c
arm/gicv3: replace this_cpu() to up_cpu_index()
If the core id needs to be included in the hardware register
calculation, up_cpu_index() should be used instead of this_cpu().
N/A
ci-check
> arm/gicv3: replace this_cpu() to up_cpu_index()

- include/nuttx/mm/kasan.h
- mm/kasan/hook.c
mm/kasan: extern kasan API only MM_KASAN is enabled
this PR will fix `g_region_init` is incorrectly linked to the image if MM_KASAN is not enabled.
N/A
CI-CHECK
> mm/kasan: extern kasan API only MM_KASAN is enabled

- arch/arm/src/stm32/stm32_allocateheap.c
User may set CONFIG_MM_REGIONS=1 on purpose to disable CCM. This is a completely normal system config and should not be treated as error.
I found this problem trying to run Renode with stm32f4discovery/nsh but Renode doesn't support CCM so we have to disable it
User can select CONFIG_MM_REGIONS=1
stm32f4discovery/nsh on HW and Renode
> arch/arm/stm32: convert error to warning when CCM is not enabled

- arch/x86_64/src/cmake/Toolchain.cmake
- arch/x86_64/src/common/Toolchain.defs
Fix the linker warning based on these two commits:
ld: warning: fork.o: missing .note.GNU-stack section implies executable stack
ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
commit 36ac81211454 ("sim: Fixes the following linker warning:"),
commit b5d640acc5b3 ("fix Cygwin/MSYS2  ld: unrecognized option '-z'")
> qemu-intel64: Fixes the linker 'noexecstack' warning

- arch/arm/src/stm32h7/Kconfig
- arch/arm/src/stm32h7/stm32h7x3xx_rcc.c
- arch/arm/src/stm32h7/stm32h7x7xx_rcc.c
arch/arm/stm32h7: add workaround for Renode
Add an option to disable busy wait PWR_CSR1_ACTVOSRDY during boot which doesn't work with Renode simulation
workaround to run `nucleo-h743zi/nsh` on Renode
`nucleo-h743zi/nsh` on Renode
> arch/arm/stm32h7: add workaround for Renode

- crypto/random_pool.c
- drivers/crypto/dev_urandom.c
- drivers/vhost/vhost-rng.c
- include/nuttx/random.h
- include/stdlib.h
- include/sys/syscall_lookup.h
- libs/libc/libc.csv
- libs/libc/stdlib/CMakeLists.txt
- libs/libc/stdlib/Make.defs
- libs/libc/stdlib/lib_arc4random.c
- libs/libc/unistd/lib_getentropy.c
- libs/libc/uuid/lib_uuid_create.c
- net/tcp/tcp_seqno.c
- net/utils/CMakeLists.txt
- net/utils/Make.defs
- net/utils/utils.h
- syscall/syscall.csv
fill the buffer with getrandom instead random pool and move the implementation to from crypto to libc
Make arc4random_buf always available
ci
> libc: Refine the arc4random_buf implementation

- fs/fs_heap.c
- fs/fs_heap.h
- fs/shm/shmfs_alloc.c
Add fs heap memalign API and use it for shm.
For kernel builds, shared memory is automatically aligned to page size.
For flat and protected builds, we align the memory size to the CPU cache
line size.
Failure to align memory properly could result in partial data read/write
by the CPU and peripherals, potentially causing data corruption during
cache flushes or invalidations.
All share memory will be aligned. 
Tested on internal project that uses arm-v7a, and share memory is allocated for GPU usage.
> Use memalign to align share memory to CPU cache line size

- Documentation/guides/index.rst
- Documentation/guides/signal_events_interrupt_handlers.rst
- Documentation/guides/signaling_sem_priority_inheritance.rst
- Documentation/guides/smaller_vector_tables.rst
Migrate pages:
* Signaling Events from Interrupt Handlers
* Signaling Semaphores and priority inheritance 
* Smaller Vector Tables 
None, only update documentation
Build with `make autobuild`
> Doc migration 4

- .gitignore
Use VSCode + clangd plugin to develop the code, the clangd will save the metadata into .cache directory, it is about the compile_commands.json:
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=True
Add the .cache into .gitignore for friendly clangd development environment.
> .gitignore: Add the .cache directory generated by clangd

- libs/libc/stdlib/lib_arc4random.c
by replacing clock_systime_ticks with clock
fix the build break reported by:
https://github.com/NuttX/nuttx/actions/runs/11540264972/job/32129220872#step:7:101
ci
> libc: Fix lib_arc4random.c:111:(.text.arc4random_buf+0x26): undefined reference to `clock_systime_ticks'

- Kconfig
- arch/arm/src/cmake/clang.cmake
- arch/arm/src/common/Toolchain.defs
- libs/libbuiltin/.gitignore
- libs/libbuiltin/CMakeLists.txt
- libs/libbuiltin/Kconfig
- libs/libbuiltin/Makefile
- libs/libbuiltin/bin/Makefile
- libs/libbuiltin/compiler-rt/.gitignore
- libs/libbuiltin/compiler-rt/CMakeLists.txt
- libs/libbuiltin/compiler-rt/Make.defs
- libs/libbuiltin/kbin/Makefile
- tools/Directories.mk
- tools/FlatLibs.mk
- tools/KernelLibs.mk
- tools/LibTargets.mk
- tools/ProtectedLibs.mk
1. enable CONFIG_BUILTIN_COMPILER_RT  to built libclang_rt.builtins-xxx.a and no longer use the compiler's built-in
2. Modify clang version acquisition to get two decimal points
3. It has been ported to support four architectures: ARM, ARM64, RISCV, and x86_64, among which ARM has been validated
4. Align the ported compile-rt library with the clang version downloaded by ci to 17.0.1
There is a problem with testbuild.sh, which causes the config I uploaded using the clang compiler to fail verification. I will fix this problem in the next patch and upload a defconfig that supports compiling this builtin.
> clang:libclang_rt.builtins-xxx.a supports builtin

- arch/arm/src/stm32/Kconfig
fix Kconfig error related to STM32_HAVE_HRTIM1_PLLCLK
```
CMake Warning at cmake/nuttx_kconfig.cmake:171 (message):
Kconfig Configuration Error: warning: STM32_HAVE_HRTIM1_PLLCLK (defined at
arch/arm/src/stm32/Kconfig:8109) has direct dependencies STM32_HRTIM &&
ARCH_CHIP_STM32 && ARCH_ARM with value n, but is currently being y-selected
by the following symbols
```
fix kconfig error
CI
> arch/arm/stm32/Kconfig: fix Kconfig error

- fs/nfs/nfs_vfsops.c
Fixes the following issues:
- When opening a NFS file in append mode, its file pointer was at offset 0 instead of the end of file.
- When creating a NFS file, the response read pointer wasn't advanced after reading the attributes_follows bool, which caused the attributes to be off by 4 bytes. For example, the file size read the GID.
NFS now has a more correct behavior, closer to other file systems.
Simulator, with a NFS mount (`nsh> nfsmount 10.0.1.1 /nfs /export udp`) and the following test program:
```c
int main(int argc, FAR char *argv[]) {
for (int i = 0; i < 5; i++) {
FILE *f = fopen("/nfs/test.txt", "a");
long start_pos = ftell(f);
fseek(f, 0, SEEK_END);
long size = ftell(f);
fseek(f, start_pos, SEEK_SET);
const char* data = "Hello World";
fwrite(data, strlen(data), 1, f);
long …
```
> fs/nfs: fix offset in append mode and attributes after create

- net/usrsock/usrsock_sockif.c
supports the usrsock client to subscribe netlink events, so that it can detect events such as link connection changes.
cortex-m33
> net/usrsock: usrsock supports offload netlink

- fs/mnemofs/mnemofs.c
- fs/mnemofs/mnemofs.h
- fs/mnemofs/mnemofs_fsobj.c
- Fix bug which prevents mkdir for depth > 3 (bug present in `mfs_get_patharr`).
- Better logs for mnemofs
- Improve logging macro `MFS_LOG` and `MFS_EXTRA_LOG`
- Add logs for `mfs_get_patharr` and `next_child`.
The former change is necessary as `mkdir` worked for mnemofs only upto 3 items in the requested path, but failed for anything more.
The latter change is required to provide better logs for mnemofs.
- `mkdir` for any number of items in the path.
- Better debugging using the improved logs.
- Build Impact: No.
- User Impact: Better logs to report in case of crashes and no errors while creating directories with depth more than 3.
- Documentation: The code printing the logs also serve as section-wise docs.
I confirm that changes are verified on local setup and works as intended:
- …
> fs/mnemofs: Fix mkdir for depth > 3 bug, better logs

- CMakeLists.txt
toolchain/tasking: fix build break on tasking toolchain
1. Tasking only support preprocess link script on linker phase
2. Remove executable suffix (.elf)
N/A
Tasking tc397
> toolchain/tasking: fix build break on tasking toolchain

- include/netinet/if_ether.h
adapts to third-party code compilation. in the process of porting EtherCAT, we encounter some situations where the structure is not defined, or the returned data types do not match the expectations. Refer to the EtherCAT implementation of other systems and add relevant definitions.
sim:local
> include/netinet/if_ether.h: add ethhdr definition

- include/netinet/arp.h
current sizeof(struct sockaddr_in) is 66
arp/arp_table.c:241:28: runtime error: member access within misaligned address 0xe5f134e6 for type 'struct sockaddr_in', which requires 4 byte alignment 0xe5f134e6: note: pointer points here
00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00
^
#0 0x543287c1 in arp_get_arpreq arp/arp_table.c:241
#1 0x5432a11f in arp_snapshot arp/arp_table.c:574
#2 0x5435f0be in netlink_fill_arptable netlink/netlink_route.c:547
#3 0x5435ffca in netlink_get_neighbor netlink/netlink_route.c:715
#4 0x54360116 in netlink_get_neighborlist netlink/netlink_route.c:743
#5 0x54363b20 in netlink_route_sendto netlink/netlink_route.c:1382
#6 0x542ef1b1 in netlink_sendmsg netlink/netlink_sockif.c:625
#7 0x542be94d in psock_sendmsg …
> arp.h: make struct arpreq four-byte aligned

- arch/arm64/src/imx9/hardware/imx9_lpuart.h
- arch/arm64/src/imx9/imx9_lowputc.c
- arch/arm64/src/imx9/imx9_lpuart.c
The driver was originally copied from imxrt platform, but while doing some more thorough testing there has been issues found.
This PR cleans up the imx9 lpuart driver code, fixes hardware flow control and enables using RX and TX fifos in interrupt mode.
Only on imx9 lpuart
Tested on custom imx9 hardware, using 6 uarts with different baud rates, flow control setups and dma setups.
> Imx9 uart cleanups and flow control

- arch/xtensa/src/esp32s3/esp32s3_partition.c
If device encryption is not enabled by eFuse, and partiton mark as encrypted flag, then encrypted MTD is used.
That is no problem in write and read operation, but failed while using spi_flash_mmap(...) since de-encrypt is not processed.
So, back to use non-encrypted MTD following API Guide: If flash encryption is not enabled, the flag "encrypted" has no effect
> xtensa/esp32s3: enable encrypted flag based on partition and device

- arch/xtensa/src/esp32s3/Make.defs
- arch/xtensa/src/esp32s3/esp32s3_reset_reasons.c
- arch/xtensa/src/esp32s3/esp32s3_reset_reasons.h
xtensa/esp32s3: add esp32s3 reset reasons interface
Only esp32s3
Reset the S3-dev using different reset methods and read the reset reasons using the interface `soc_reset_reason_t esp32s3_reset_reasons(int cpu)`;
> xtensa/esp32s3: add esp32s3 reset reasons interface

- sched/semaphore/sem_destroy.c
- sched/semaphore/sem_holder.c
- sched/semaphore/sem_post.c
- sched/semaphore/sem_recover.c
- sched/semaphore/sem_reset.c
- sched/semaphore/sem_trywait.c
- sched/semaphore/sem_wait.c
- sched/semaphore/sem_waitirq.c
- sched/semaphore/semaphore.h
Add sem_wait fast operations, use atomic to ensure atomicity of semcount operations, and do not depend on critical section.
Test with robot board:
before modify:
nxmutex_lock cost: 78 ns
nxmutex_unlock cost: 82 ns
after modify:
nxmutex_lock cost: 28 ns
nxmutex_unlock cost: 14 ns
semaphore
bes board with monkey test pass
sabre-6quad:smp with ostest pass
> sem: change sem wait to atomic operation

- mm/mm_heap/mm_memalign.c
This adds debug log support for mm_memalign to help track memory issues. The logging is guarded with DEBUG_MM_INFO and is off by default.
DEBUG_MM_INFO usages
- local checks with `rv-virt:knsh` and `rv-virt:knsh64`
- CI checks
> mm/mm_memalign: add debugging log

- tools/coredump.py
python api change
tmpfile.rename(args.output)
^^^^^^^^^^^^^^
AttributeError: '_io.BufferedRandom' object has no attribute 'rename'. Did you mean: 'name'?
coredump.py
run coredump.py in ubuntu22.04 and ubuntu 24.04
> coredump.py:bug fix python file not have rename

- tools/process_config.sh
we should process repeat define CONFIG when used #include “XXX/deconfig” mode
> Fix config repeat define in include deconfig mode

- arch/arm/src/cmake/clang.cmake
- arch/arm/src/cmake/gcc.cmake
- arch/arm/src/cmake/ghs.cmake
- arch/risc-v/src/cmake/Toolchain.cmake
- arch/sim/Kconfig
- arch/sim/src/cmake/Toolchain.cmake
- arch/tricore/src/cmake/ToolchainGnuc.cmake
- arch/tricore/src/cmake/platform.cmake
- arch/tricore/src/common/ToolchainGnuc.defs
- arch/x86_64/src/cmake/Toolchain.cmake
- boards/sim/sim/sim/scripts/Make.defs
- sched/Kconfig
- tools/Config.mk
1. CONFIG_ARCH_COVERAGE has been replaced by CONFIG_SCHED_GCOV
2. Delete the SIM-specific GCOV_ALL configuration and change it to a universal configuration for all architectures
Enable CONFIG_SYSTEM_GCOV and CONFIG_SCHED_GCOV, CONFIG_SCHED_GCOV_ALL, nsh run "gcov -d /data " can generate gcda files for all files, that is, code coverage analysis generates files
> gcov: Fix typographical errors

- libs/libbuiltin/Kconfig
- libs/libbuiltin/compiler-rt/CMakeLists.txt
- libs/libbuiltin/compiler-rt/InstrProfilingPlatform.c
- libs/libbuiltin/compiler-rt/Make.defs
- tools/nxstyle.c
1. clang: Support compiling rt.profile library
```
1. Since the implementation of gcov has changed since clang17, versions before clang17 need to use the libunwind.a file
```
2. llvm gcov supports interrupt code coverage detection, as shown below
for the code coverage analysis of armv8-m/arm_doirq.c:
```
-:    0:Source:armv8-m/arm_doirq.c
-:    0:Graph:./arm_doirq.gcno
-:    0:Data:./arm_doirq.gcda
-:    0:Runs:1
-:    0:Programs:1
-:    1:/****************************************************************************
-:    2: * arch/arm/src/armv8-m/arm_doirq.c
-:    3: *
-:    4: * Licensed to the Apache Software Foundation (ASF) under one or more
-:    5: * contributor license agreements.  See the NOTICE file distributed with
-:    6: * this work for additional information regarding …
```
> clang: support gcov ARM LLVM clang supports code coverage detection

- include/nuttx/atomic.h
**Why is this change necessary?**
On some compiler platforms, although it is a standard after C11, it does not provide an ATOMIC toolchain implementation, so we can use this macro to determine whether it supports toolchain atomic
**Changes:**
add check !defined(__STDC_NO_ATOMICS__)
If the macro constant __STDC_NO_ATOMICS__(C11) is defined by the compiler, the header <stdatomic.h>, the keyword _Atomic, and all of the names listed here are not provided.
refer to:https://en.cppreference.com/w/c/atomic  
**Impact on compatibility:** This …
> nuttx/atomic.h:Add use condition for using stdatomic.h

- arch/risc-v/src/mpfs/mpfs_shead.S
Add riscv_macros to mpfs_shead to get definition for riscv_set_inital_sp macro
Impact is only mpfs_shead.S, i.e. MPFS kernel mode build and CONFIG_SMP=y
Build passes when CONFIG_SMP=y
> mpfs/smp: Add riscv_macros to mpfs_shead

- include/obstack.h
- libs/libc/obstack/lib_obstack_make_room.c
This primarily fixes allocated memory overrun due to invalidly calculated limit of the chunk. The function here allocates chunk of size that includes required header. The error was that size of the chunk was invalidly again added when limit was being calculated. This was causing memory overrun and issues especially with object growing (reallocation).
The secondary fix here is to the algorithm that rounds the required size to the multiple of chunk size. In short chunk size must be reduced by one to get the correct mask. The condition that was generating the mask was also invalid because it must perform shift with at most one less than number of bits (not bytes).
The stability fix.
Tested on custom samv7 board. I have also proof tested the rounding mechanism with following code:
```
size_t …
```
> libs/libc/obstack: fix allocated chunk overrun due to invalid limit

- arch/risc-v/src/common/supervisor/riscv_perform_syscall.c
The sched_note calls were missing from riscv_perform_syscall().
Fixes tiny regression, related to task instrumentation. Only RISC-V and BUILD_KERNEL=y are affected.
Sched note works again!
> riscv/syscall: Fix sched_note instrumentation for BUILD_KERNEL

- tools/mkdeps.c
update MAX_BUFFER/MAX_EXPAND/MAX_SHQUOTE for deeper compilation paths in real condition
support build nuttx in more deeper compilation paths.
PASS Vela CI
> tools/mkdeps: increase MAX_BUFFER from 16384 to 65536

- arch/ceva/include/irq.h
- arch/or1k/include/irq.h
- arch/risc-v/include/irq.h
- arch/sim/include/irq.h
- arch/sparc/include/irq.h
reason:
Replace "inline" with "inline_function" for "up_interrupt_context" to ensure consistency with other arch
ceva or1k risc-v sim sparc
ci ostest
> irq: force inline up_interrupt_context

- libs/libc/netdb/lib_dns.h
- libs/libc/netdb/lib_dnsbind.c
- libs/libc/netdb/lib_dnsquery.c
* Implement DNS query over TCP
* Implement TCP fallback on responses with the TC bit set
References:
* https://www.ietf.org/rfc/rfc2181.txt
* http://www.dnsflagday.net/2020/
dns resolver
tested on esp32-devkitc wifi
against "@166.84.7.99 2048.size.dns.netmeister.org" from this article: https://www.netmeister.org/blog/dns-size.html
> DNS: Implement TCP fallback

- arch/arm64/src/imx9/imx9_lpuart.c
This is a partial revert / fix for regression from 44d1811
I just made a silly bug while cleaning up the code earlier. Correcting it here.
TCGETS was returning wrong parity bits, causing wrong uart configuration occasionally when user was doing tcgets+tcsets.
Tested on custom imx9 board
> arch/arm64/src/imx9/imx9_lpuart.c: Fix parity get in TCGETS

- fs/shm/shm_open.c
fs/shm: support shm_open with flags O_TRUNC
bug fix
testcase:
https://fossies.org/linux/posixtestsuite/conformance/interfaces/shm_open/25-1.c
> fs/shm: support shm_open with flags O_TRUNC

- include/sys/socket.h
sys/socket: use __attribute__((packed)) to avoid changes in the size of struct sockaddr_storage due to struct alignment.
Referencing [RFC 2553#section-3.10](https://datatracker.ietf.org/doc/html/rfc2553#section-3.10) and the [POSIX standard documentation](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/sys/socket.h.html).
Defines the maximum size of the structure, which is typically 128 bytes. But the current output structure size (sizeof(struct sockaddr_storage)) is 136, which does not match this.
This discrepancy can also lead to the following potential issues:
1.An increase in the .bss segment size.
2.Functions may experience alignment issues, such as getifaddrs(&ifap) being unable to read the correct IP address.
The data passed to struct sockaddr_in is shifted, causing …
> sys/socket: fix struct sockaddr_storage alignment issue

- Documentation/applications/boot/nxboot/index.rst
This commit adds documentation entry for NuttX based bootloader nxboot. The bootloader implementation is in apps repository, see [boot: add NuttX bootloader with update and recovery support](https://github.com/apache/nuttx-apps/pull/2809)
Documentation entry only.
Documentation builds succesfully.
> docs: add nxboot documentation entry

- mm/tlsf/mm_tlsf.c
error: ‘nodesize’ undeclared (first use in this function)
518 |       memset(mem, MM_FREE_MAGIC, nodesize);
tlsf/mm_tlsf.c:1288:10: warning: unused variable ‘newsize’ [-Wunused-variable]
1288 |   size_t newsize;
sim
> mm: fix tlsf compiler error

- libs/libc/unistd/lib_getoptargp.c
- libs/libc/unistd/lib_getopterrp.c
- libs/libc/unistd/lib_getoptindp.c
- libs/libc/unistd/lib_getoptoptp.c
Fixed tasking build issue：
CC:  pthread/pthread_mutexattr_getrobust.c artc I800: creating archive libsched.a
CC:  unistd/lib_getopterrp.c ctc W505: ["unistd/lib_getoptargp.c" 48/29] implicit declaration of function "getoptvars"
ctc W577: ["unistd/lib_getoptargp.c" 48/39] calling a function without a prototype
ctc W524: ["unistd/lib_getoptargp.c" 48/27] conversion of integer to pointer at assignment
ctc E212: ["unistd/lib_getoptargp.c" 49/13] access to incomplete type
ctc W523: ["unistd/lib_getoptargp.c" 49/13] pointers to different types at return
NA
tc397:nsh build success
> libc/unistd: fixed tasking build issue

- arch/xtensa/CMakeLists.txt
- arch/xtensa/src/CMakeLists.txt
- arch/xtensa/src/cmake/Toolchain.cmake
- arch/xtensa/src/cmake/platform.cmake
- arch/xtensa/src/common/CMakeLists.txt
implement CMake build of xtensa arch
new features and forward compatibility
```
configure:cmake -B build -DBOARD_CONFIG=iss-hifi4:nsh 
build:cmake --build build
run:xt-run build/nuttx
```
> cmake:implement CMake build of xtensa arch

- drivers/audio/vs1053.c
- drivers/sensors/fxos8700cq.c
This commit added the missing headers for some drivers.
This commit should fix compilation errors for `freedom-k64f:demo` and `mikroe-stm32f4:fulldemo`.
Tested.
> drivers: Fix the missing headers.

- .github/workflows/arch.yml
This PR enables the CI Builds for msys2, msvc, arm-08, arm-10, arm-13 for Complex PRs. We disable the CI Builds for arm-01, arm-09, arm-11.
This will help to fix the recent breakage of builds: https://github.com/apache/nuttx/issues/14598
When we create or update a Complex PR: CI Workflow will now build msys2, msvc, arm-08, arm-10, arm-13 (instead of arm-01, arm-09, arm-11)
No changes to Simple PRs.
Creating a Complex PR will now build msys2, msvc, arm-08, arm-10, arm-13 (instead of arm-01, arm-09, arm-11):
https://github.com/lupyuen5/label-nuttx/actions/runs/11638217458
Creating a Simple Arm32 PR will build arm-01 to arm-14, like before:
https://github.com/lupyuen5/label-nuttx/actions/runs/11638211712
> CI: Enable builds for msys2, msvc, arm-08, arm-10, arm-13 for Complex PRs

- include/pthread.h
- libs/libc/pthread/pthread_condinit.c
- sched/pthread/pthread_condclockwait.c
- sched/pthread/pthread_condsignal.c
- sched/pthread/pthread_condwait.c
We decouple semcount from business logic by using an independent counting variable, which allows us to remove critical sections in many cases.
pthread_cond
ci ostest
**Build Host:**
* OS: Ubuntu 20.04
* CPU: x86_64 
* Compiler: GCC 9.4.0
$ make
> pthread_cond remove csection  and sched_lock

- libs/libc/machine/CMakeLists.txt
**Why is this change necessary?**
This issue comes from https://github.com/apache/nuttx/pull/14570. In the previous Atomic implementation https://github.com/apache/nuttx/pull/13044, we have removed the CONFIG_LIBC_ARCH_ATOMIC macro, so arch_atomic.c should always be compiled.
We can compile the nucleo-f072rb/nsh configuration through cmake
```
[ 98%] Building C object …
```
> libc/machine/CMakeLists: should alaways build arch_atomic.c

- net/tcp/Kconfig
- net/tcp/tcp_netpoll.c
1.set NET_TCP_NPOLLWAITERS default value from 1 to 2
2. add warning of different events having same event bit
TCP  number of poll to the same fd
> tcp:set NET_TCP_NPOLLWAITERS default value to 2 & add warning of different events having same event bit

- net/netlink/netlink.h
- net/netlink/netlink_conn.c
- net/netlink/netlink_notifier.c
1.Fix the bug that netlink receive wait does not hang up
2.add tls cleanup protection to protect waitsem in netlink_get_response
netlink
> Fix the bug and add tls cleanup  in that netlink 

- boards/xtensa/esp32s3/esp32s3-box/src/esp32s3_board_touchsceen_gt911.c
- boards/xtensa/esp32s3/esp32s3-box/src/esp32s3_board_touchsceen_tt21100.c
- drivers/net/ksz9477_reg.h
- include/nuttx/lin.h
- include/sys/socket.h
since the different compiler express the packed structure in the different way.
fix ci error reported here:
https://github.com/apache/nuttx/actions/runs/11643419979/job/32424162791?pr=14605
ci
> Replace __attribute__((packed)) with [begin|end]_packed_struct

- arch/arm/src/cmake/Toolchain.cmake
- arch/arm/src/cmake/armclang.cmake
- arch/arm/src/cmake/armv7-m.cmake
- arch/arm/src/cmake/armv7-m_armclang.cmake
Complete CMake arm toolchain configuration
No effect on the currently used gcc and clang compilers
Testing with ARM IDE
> cmake(build):add the specified armclang compiler to the cmake  Toolchain file

- drivers/serial/serial.c
- include/nuttx/sched.h
remove nxsched_lock_irq/nxsched_unlock_irq
nxsched_lock_irq has the same functionality as sched_lock
sched_lock
ci ostest
> remove nxsched_lock_irq/nxsched_unlock_irq

- fs/mnemofs/mnemofs.c
- fs/mnemofs/mnemofs.h
- fs/mnemofs/mnemofs_fsobj.c
- fs/mnemofs/mnemofs_lru.c
This PR fixes:
- Renamed `struct mfs_fsdirent` to `struct mfs_fsdirent_s` to follow the C Contributing Guidelines for styling.
- Update `mnemofs_open` return value to `-ENOTDIR` when ancestor is a file.
- Update `mnemofs_rmdir` return value to `-ENOTDIR` when path is not a directory.
- Better logs for file and dir operations including `mnemofs_open`, `mnemofs_close`, `mnemofs_read`, `mnemofs_write`, `mnemofs_seek`, `mnemofs_opendir`, `mnemofs_readdir`, `mnemofs_rewinddir`, `mnemofs_mkdir`, `mnemofs_rmdir`, `mnemofs_stat`.
- Renamed `mfs_lru_updatedinfo` to `mfs_lru_getupdatedinfo` to make it easier to understand.
The change is necessary to ensure proper return values of various file system operations and to improve readability of code through better logs and better identifiers.
- Proper …
> fs/mnemofs: Fix open and rmdir return value and seek out of bounds.

- sched/misc/assert.c
Don't compile dump_task logic if CONFIG_DEBUG_ALERT=n. With _alert() disabled this logic does nothing, but the compiler is not smart enough to optimize this code.
on minimal stm32f3 configuration it saves 396B of flash.
Before this change:
```
flash:       17560 B        64 KB     26.79%
sram:        2556 B        16 KB     15.60%
```
After this change:
```
flash:       17164 B        64 KB     26.19%
sram:        2556 B        16 KB     15.60%
```
free some flash memory 
nucleo-f302r8
> sched/misc/assert.c: don't compile dump_task logic if CONFIG_DEBUG_ALERT=n

- drivers/syslog/CMakeLists.txt
don't include syslog files if CONFIG_SYSLOG=n
sync with make build system
local build
> cmake: don't include syslog files if CONFIG_SYSLOG=n

- drivers/sensors/adxl362_uorb.c
- drivers/sensors/adxl372.c
- drivers/sensors/adxl372_uorb.c
- drivers/sensors/bmg160.c
- drivers/sensors/bmi270_base.h
- drivers/sensors/bmm150_uorb.c
- drivers/sensors/l3gd20_uorb.c
- drivers/sensors/lis3dh.c
- drivers/sensors/lis3dsh.c
- drivers/sensors/lis3mdl.c
- drivers/sensors/lsm330_spi.c
- drivers/sensors/mlx90393.c
- drivers/sensors/msa301.c
- drivers/sensors/t67xx.c
- drivers/video/max7456.c
- include/nuttx/fs/fs.h
- include/nuttx/fs/ioctl.h
- include/nuttx/streams.h
by moving geometry and partition_info_s to include/fs/ioctl.h
Fix ci error reported here:
https://github.com/apache/nuttx/actions/runs/11643419979/job/32424162668?pr=14605
ci
> fs: Fix mtd/sector512.c:554:19: error: incomplete definition of type 'struct partition_info_s'

- libs/libc/stream/lib_blkoutstream.c
- libs/libc/stream/lib_mtdoutstream.c
- libc/blkoutstream: Replace stream->geo.geo_sectorsize with sectorsize 
- libc/blkoutstream: Remove the redundant check and compute 
- libc/blkoutstream: Zero the cache to avoid random data
- libc/mtdoutstream: Replace stream->geo.erasesize with erasesize 
- libc/mtdoutstream: Remove the redundant check and compute 
- libc/mtdoutstream: Fix the in insufficient erase in byte write case
blkoutstream and mtdoutstream
internal test
> Minor improve blkoutstream and mtdoutstream

- .github/workflows/build.yml
Due to the [recent cost-cutting](https://github.com/apache/nuttx/issues/14376), we are no longer running PR Merge Jobs in the `nuttx` and `nuttx-apps` repos. For this to happen, I am now running a script on my computer that will cancel any PR Merge Jobs that appear: [kill-push-master.sh](https://github.com/lupyuen/nuttx-release/blob/main/kill-push-master.sh)
This PR disables PR Merge Jobs permanently, so that we no longer need to run the script. This prevents our CI Charges from over-running, in case the script fails to operate properly.
Some NuttX Developers may wish to run the PR Merge Jobs in their repos. They will have to re-enable the job in `build.yml`:
```yaml
on: ...
push: ...
branches:
- master
```
Or they may rename the Default Branch from `master` to `releases/master` branch. …
> CI: Disable the CI Build on push to master branch

- Documentation/contributing/index.rst
- Documentation/contributing/releases.rst
This PR adds a documentation page under the "Contributing" section of the NuttX docs which contains the NuttX release process documentation from Alin Jerpelea's gist: https://gist.github.com/jerpelea/67895da8797f040ba3b113280fdcd57b
This contributes a step forward towards the issues discussed in #14062. The release process is now documented centrally on the NuttX website and can be modified there as a single source of information for new contributors to see how releases are made.
There is still more information which could be added, like the information in Lup's comment on #14062, but I am opening this PR to get the documentation which already exists in a consolidated form included on the website.
I performed a local build of the documentation, ensured there were no errors and visually …
> Document release process

- .github/workflows/build.yml
When compiling the Release Branch of `nuttx-apps`, our CI Workflow `build.yml` checks out the Master Branch of `nuttx` repo, which is incorrect. This happens due to a typo in `build.yml`: https://github.com/apache/nuttx/issues/14513
This PR fixes the typo in `build.yml` to checkout the correct branch of `nuttx` repo.
When compiling the Release Branch of `nuttx-apps`, our CI Workflow `build.yml` now checks out the Release Branch of `nuttx` repo.
No changes when compiling the Master Branch of `nuttx` and `nuttx-apps` repos.
__Before the PR:__ Fetch-Source Log shows that CI is incorrectly checking out the Master Branch of `nuttx` repo (instead of `releases/12.7`): https://github.com/apache/nuttx-apps/actions/runs/11518661640/job/32069568370#step:3:66
```text
/usr/bin/git checkout --progress …
```
> CI: Check out the correct branch of nuttx repo when compiling nuttx-apps

- arch/arm64/src/Toolchain.defs
arm64: fix compile failed when build ELF apps
aarch64-none-elf-gcc -c -D_LDBL_EQ_DBL -fno-common -Wall -Wstrict-prototypes -Wshadow -Wundef -Werror -Wno-attributes -Wno-unknown-pragmas -Wno-psabi "-O3" -fno-strict-aliasing -fno-omit-frame-pointer -fno-optimize-sibling-calls -fstack-protector-all -fsanitize=kernel-address --param asan-globals=1 -ffunction-sections -fdata-sections "-g3" -mcpu=cortex-a53 -isystem /home/ligd/platform/trunk/nuttx/include -D__NuttX__  -pipe -I /home/ligd/platform/trunk/apps/crypto/mbedtls/include -I /home/ligd/platform/trunk/apps/crypto/mbedtls/mbedtls/include -I /home/ligd/platform/trunk/apps/crypto/openssl_mbedtls_wrapper/include -I /home/ligd/platform/trunk/apps/external/android/frameworks/native/libs/binder/include_rpc_unstable -I …
> arm64: fix compile failed when build ELF apps

- include/nuttx/timers/oneshot.h
- include/nuttx/timers/timer.h
If the timer driver is not support both getstatus and tick_getstatus, 
we should not raise a panic, return -ENOSYS will prefer.
#7494 
#13606 
#14514 
when timer driver no support for get status, will no longer panic, just return a -ENOSYS.
CI-test & local stm32h7
> timers: Replace DEBUGASSERT with the error code, reopen from #12484

- sched/sched/sched_setaffinity.c
reason:
In smp, It's possible that in a scenario where CONFIG_SMP_DEFAULT_CPUSET is set to 1, when taskA is created with a relatively low priority, it gets added to the g_readytorun queue with an affinity of 0x1. Meanwhile, CPUs 1~n are in an idle state.
Subsequently, when we attempt to change the affinity property of taskA using nxsched_set_affinity, the scheduling mechanism might not be triggered due to the lack of a proper condition check. This can result in taskA remaining unscheduled and therefore unable to run.
nxsched_set_affinity
Build Host:
OS: Ubuntu 20.04
CPU: x86_64
Compiler: GCC 9.4.0
$ make
$ qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic
-machine …
> sched/sched: change the judgment condition for nxsched_set_affinity

- arch/x86_64/src/cmake/Toolchain.cmake
- arch/x86_64/src/common/Toolchain.defs
x86_64: fix compile warning
In function ‘void* std::__1::__libcpp_operator_new(_Args ...) [with _Args = {long unsigned int}]’,
inlined from ‘void* std::__1::__libcpp_allocate(size_t, size_t)’ at /home/ligd/platform/trunk/nuttx/include/libcxx/new:294:31,
inlined from ‘_Tp* std::__1::allocator<_Tp>::allocate(size_t) [with _Tp = char]’ at /home/ligd/platform/trunk/nuttx/include/libcxx/__memory/allocator.h:114:62,
inlined from ‘constexpr std::__1::__allocation_result<typename std::__1::allocator_traits<_Alloc>::pointer> std::__1::__allocate_at_least(_Alloc&, size_t) [with _Alloc = allocator<char>]’ at /home/ligd/platform/trunk/nuttx/include/libcxx/__memory/allocate_at_least.h:55:27,
inlined from ‘void std::__1::basic_string<_CharT, _Traits, _Allocator>::__grow_by_and_replace(size_type, …
> x86_64: fix compile warning

- sched/wqueue/kwork_notifier.c
Be consistent with the datatype used for the 'key'. As the API in
in the .h file uses int, I chose to replace uint32_t with int
everywhere.
This change ensures that work_notifier_setup() will not return a
negative value indicating error to the caller, when in fact the
notifier was correctly setup. This would happen when
work_notifier_setup() had been called 0x8000000 times, and that
many keys allocated.
work_notifier_setup() is used in TCP, UDP, Netlink and IOB code.
> sched/wqueue: fix work_notifier_setup() false failure

- net/netlink/netlink_notifier.c
- net/netlink/netlink_sockif.c
Make sure the return value is zero on success - as described in the
documentation of the function.
It doesn't look like the "error" affected any code.
> net/netlink: fix netlink poll return value on success

- sched/task/exit.c
It's found that in some board config/build, the macro expansion of `enter_critical_section` is not correct.
Add irq.h to avoid macro expansion problem in exit.c
none
sim build & run
> sched: add header irq.h to exit.c

- AUTHORS
**Summary** 
add the missing authors that have submitted ICLA
**Impact**
Authors
**Testing**
None
> AUTHORS: add missing authors with submitted ICLA

- tools/Unix.mk
- tools/process_config.sh
fixed this error for macos after the PR #14552
```
Configuration/Tool: stm32f4discovery/nsh,CONFIG_ARM_TOOLCHAIN_GNU_EABI
2024-11-04 05:53:44
Cleaning...
Configuring...
sed: -I or -i may not be used with stdin
sed: -I or -i may not be used with stdin
sed: -I or -i may not be used with stdin
sed: -I or -i may not be used with stdin
sed: -I or -i may not be used with stdin
sed: -I or -i may not be used with stdin
sed: -I or -i may not be used with stdin
sed: -I or -i may not be used with stdin
sed: -I or -i may not be used with stdin
sed: -I or -i may not be used with stdin
sed: -I or -i may not be used with stdin
``` …
> macos: fix “sed: -I or -i may not be used with stdin”

- include/nuttx/net/netconfig.h
- libs/libc/net/lib_indextoname.c
- libs/libc/net/lib_nametoindex.c
- net/inet/inet.h
- net/socket/net_sockif.c
When using the minimal CONFIG_NET configuration for SocketCAN. 
Ifup would fail with the following error code.
Fixes `psock_socket: ERROR: socket address family unsupported: 2`
This was caused because AF_INET got defined but `inet_sockif()` would return `NULL` because either `ICMP`, `TCP` or `UDP` dependency didn't met. This patch changes the `ifdef` logic for `AF_INET` and `AF_INET6` to include those checks so that other `SOCK_FAMILY` will work with minimal IPv4 or IPv6 config.
Net
Tested on MR-CANHUBK344 net config
> net: inet.h match inet_sockif.c definition

- libs/libc/modlib/modlib_load.c
* libs/modlib: Load data using `up_textheap_data_address`
Some chips have different memory addressing spaces for the same region. This is true, for instance, for ESP32-S3: the same memory region can be accessed using the data bus or the data bus using different address ranges. The instruction bus, however, requires word-aligned access. That being said, it is recommended to use the data bus while copying sections to the text heap to avoid any illegal access using the instruction bus address which will be later used to run the program.
Fix https://github.com/apache/nuttx/issues/14487
Internal CI testing + ESP32-S3-DevKitC-1 v1.0:
Build steps:
```
make -j distclean && ./tools/configure.sh esp32s3-devkit:elf && make flash ESPTOOL_PORT=/dev/ttyUSB0 -s -j$(nproc) && minicom -D /dev/ttyUSB0
``` …
> libs/modlib: Load data using `up_textheap_data_address`

- drivers/net/Kconfig
- drivers/net/igc.c
This commit added the device ID to support Intel I226V Ethernet controller.
Intel I226V Ethernet controller works fine after the device ID added.
Tested on an Intel i9-13900 x86/64 machine with I226V.
> net/igc: Support Intel I226V.

- include/nuttx/net/netconfig.h
- net/inet/inet.h
- net/inet/inet_sockif.c
- net/socket/net_sockif.c
`HAVE_INET_SOCKETS` define wasn't included by netconfig.h causing renew to fail.
Thanks for pointing out @masayuki2009 
Moved preprocessor defintions to `include/nuttx/net/netconfig.h` so that `AF_INET` gets defined.
Btw could we impove CI coverage as well to test if we get a DHCP address using qemu?
Fixes broken inet
mr-canhubk344
> net: fix inet #14634 regression

- drivers/pipes/Kconfig
Such as DBus, it maybe more than 1 thread to poll one dev, if that will make poll fail
and runtime logs from before and after change is highly …
> Enable DEV_PIPE_NPOLLWAITERS default value 4 for adapte APP

- binfmt/binfmt.h
- binfmt/builtin.c
- binfmt/elf.c
- binfmt/nxflat.c
Most tools used for compliance and SBOM generation use SPDX identifiers This change brings us a step closer to an easy SBOM generation.
SBOM
NONE
> binfmt: migrate to SPDX identifier

- tools/ci/cibuild.sh
fixed this warning for msys2
```
Configuration/Tool: nucleo-l152re/nsh,CONFIG_ARM_TOOLCHAIN_GNU_EABI
2024-11-05 06:12:26
Cleaning...
Configuring...
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent …
```
> msys2: fix make[3]: warning: jobserver unavailable: using -j1.

- arch/arm64/src/imx9/imx9_edma.c
Warm boot might fail if edma4 channel mux is
not written to default value
if dma_free is not called during crash/warm reset, dma does not work this register is not zeroed
used for verification (arch, board:config, …
> arch/arm64/imx9: Clear edma4 mux conf before set

- include/nuttx/sched.h
- libs/libc/gdbstub/lib_gdbstub.c
- sched/misc/assert.c
- sched/sched/sched_backtrace.c
- sched/sched/sched_profil.c
- sched/sched/sched_roundrobin.c
- sched/sched/sched_setpriority.c
- sched/sched/sched_smp.c
- sched/sched/sched_suspend.c
- sched/signal/sig_dispatch.c
- sched/task/task_restart.c
- sched/task/task_terminate.c
reason:
The old implementation of the SMP call, even when using the "no wait" parameter, could still result in waiting, if invoking it within a critical section may lead to deadlocks. Therefore, in order to implement a truly asynchronous SMP call strategy, we have added nxsched_smp_call_async.
https://github.com/apache/nuttx-apps/pull/2822
https://github.com/apache/nuttx/pull/14656
These two pull requests (PRs) must be merged together.
smp call
ci ostest
**Build Host:**
* OS: Ubuntu 20.04
* CPU: x86_64 
* Compiler: GCC 9.4.0
$ make …
> smpcall: add nxsched_smp_call_async and nxsched_smp_call_single_async

- arch/xtensa/src/esp32/esp32_spiram.c
- arch/xtensa/src/esp32s3/esp32s3_spiram.c
ci: Fix ci problem
https://github.com/apache/nuttx/pull/14656 missing changes
and https://github.com/apache/nuttx-apps/pull/2825
> ci: Fix ci problem

- include/nuttx/uorb.h
Add GNSS firmware version for `struct sensor_gnss`.
e.g. Some test apps may need getting firmware version.
uORB/Topic/sensor_gnss - New member `firmware_ver` added.
Tested with tool "uorb_listener" with patch https://github.com/apache/nuttx-apps/pull/2826
```
uorb_listener -n 20 sensor_gnss
```
> nuttx/uorb.h: Add GNSS firmware version for `struct sensor_gnss`

- drivers/pipes/pipe_common.c
The write should return even in case of O_NONBLOCK if at least some bytes were written.
The previous state where always all bytes were written was breaking a common combination with poll, because poll would signal POLLOUT and some bytes would really be consumed but write could still block afterwards. That would prevent from execution returning to the poll loop again.
None the less it is also the standard C library behavior for the write function.
This could have impack on any code that uses pipes and fifos and relies on this non-standard behavior or `write` always writing all bytes. But it is non-standard behavior and thus considered to be a bug in my eyes.
Tested with the following code that after this change works:
```C
// Must be longer than CONFIG_DEV_PIPE_SIZE
const char *text = …
```
> drivers/pipes: return after short write if buffer is full

- sched/sched/sched_smp.c
smpcall: we directly call the function to handle local smpcall
some arch do not support issuing interrupts to the local CPU.
This commit fixes the regression from https://github.com/apache/nuttx/pull/14656
smpcall
ci ostest
**Build Host:**
* OS: Ubuntu 20.04
* CPU: x86_64 
* Compiler: GCC 9.4.0
$ make
> smpcall: we directly call the function to handle local smpcall

- arch/arm/src/stm32h5/Kconfig
Transferred ethernet/MAC Kconfig options for stm32h7 to stm32h5. The IP for the ethernet peripheral is identical between the two chips, so the h5 implementation will start off the same as the h7 implementation. 
This also cleaned up some leftover comments in the Kconfig, such as the AHB peripheral menu section comments. 
Before porting the stm32h7 ethernet driver to the stm32h5, need to add the configuration options to the Kconfig. This just copied over the options but renamed STM32H7 to STM32H5. 
The change currently does not effect hardware as there are no H5 ethernet drivers implemented. This allows the menuconfig to set the proper options for when ethernet support is added for the H5. 
Not much to test other than going through the menuconfig and comparing to the H7. I ran the arm-13 …
> arch/stm32h5: H5 add ethernet options to Kconfig

- drivers/crypto/pnt/pnt_se05x_api.c
- drivers/crypto/se05x.c
- set_enable_pin can be set to NULL for the boards where the enable pin(ENA) of the SE05x cannot be controlled. Before it resulted in se05x_register() function to return an error.
- Fixed error handling in se05x_register(). The return value of pnt_se05x_open() was not considered which could lead to heap problems. Also error labels are introduced for unwinding to reduce complexity.
crypto/se05x
ucans32k146:se05x
please ignore the 'Mixed case identifier found'. This is detected on the usage of external code.
> crypto/se05x: Allow set_enable_pin to be NULL and fix error handling

- fs/driver/CMakeLists.txt
- fs/driver/Make.defs
- fs/driver/fs_blockmerge.c
- include/nuttx/fs/fs.h
Usage example for merging the factory partition and reserve partition into the merge partition:
register_merge_blockdriver("/dev/merge", "/dev/factory", "/dev/reserve", NULL)
FS
test on bes platform
> fs: add merge partitions support

- arch/arm64/src/imx9/imx9_flexcan.c
This corrects the imx9 can bus driver in case of warm reboot, where the flexcan block might be already initialized
Impacts only imx9 canbus when doing warm reboot
Tested on a imx93 board
> imx9/flexcan: Add disable/enable cycle

- arch/arm64/src/imx9/imx9_flexspi.c
- arch/arm64/src/imx9/imx9_flexspi_nor.c
Pick imx9 flexspi_nor driver updates from TII repositories.
This PR updates imx9 flexspi driver to support larger devices with 4-byte addressing, and increases the speed.
Tested with a custom imx93 board and with imx93-evk with a M25P_MT25Q512 flash device connected to Flex-SPI.
> Imx9 flexspi updates

- mm/mm_gran/mm_grantable.c
mm_gran/mm_grantable.c:187:6: error: 'r.sidx' may be used uninitialized
Warning fix only
CI build pass.
> mm/mm_gran: fix compile warnings

- arch/arm64/src/common/arm64_gicv3.c
This patch is necessary to optimize the handling of SGI (Software Generated Interrupts) in a virtualized environment on ARM64 architecture. The original implementation required reading the IGROUPR0 register each time an SGI was sent, which, due to the GIC Redistributor being a purely emulated device, caused a VM exit. This VM exit leads to significant performance degradation. The patch addresses this issue by replacing the read operation with a predefined value set during the initialization in `gicv3_cpuif_init`, assuming that this value remains unmodified post-initialization.
The change primarily affects the performance of virtualized environments by reducing the number of VM exits caused by SGI handling. Users running virtual machines on ARM64 hardware should experience improved …
> arch/arm64: Optimized SGI to avoid VM exit.

- tools/ci/platforms/darwin.sh
Now you can use any of these runners
macos-13
https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
or 
macos-14 (arm64)
https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
added autoconf
needed to build kconfig_frontends on macos-14
bloaty
speeded build with cmake + ninja
if we upgrade to macos-14 we need to remember to clear the caches (macOS-tools-xxxxxxxx) first
https://github.com/apache/nuttx/actions/caches
tested only on github workflow with only [macos] because **sim01, sim02, sim03 are broken !!!**
macos-13
[github macos-13](https://github.com/simbit18/nuttx-testing-ci/actions/runs/11724256583/job/32657844203)
macos-14 …
> tools/ci/platforms/darwin.sh: Port NuttX CI Job to macOS-14

- include/nuttx/wqueue.h
- sched/Kconfig
- sched/irq/CMakeLists.txt
- sched/irq/Make.defs
- sched/irq/irq_attach_wqueue.c
- sched/wqueue/kwork_thread.c
isrthread: add configuring the stack of an isrthread as static
reason:
we configure the isr thread stack as static to allow for more flexible placement of the stack.
isrthread 
https://github.com/apache/nuttx/pull/14686
https://github.com/apache/nuttx-apps/pull/2828
These two pull requests (PRs) must be merged together.
ci ostest
> isrthread: add configuring the stack of an isrthread as static

- arch/risc-v/src/common/supervisor/riscv_syscall.S
There is an enormous error in the system call dispatch logic; if a task is inside a critical section (local interrupts disabled) there is a chance that during a context switch when the task resumes, local interrupts are erroneously ENABLED. This obviously leads to unexpected crashes and such.
This happens when the CPU status has Previous Interrupt Enable (PIE) set to 1, even though Interrupt Enable (IE) is set to 0.
When the system call returns via ERET, the CPU sets PIE->IE and if PIE=1 interrupts get enabled.
This is fixed easily by explicitly CLEARING PIE from the register save area, if IE=0 when the system call was started.
RISC-V kernel mode only. Fixes a very well hidden bug in context switching.
ostest:
- rv-virt:knsh64
- rv-virt:ksmp64
Downstream MPFS target with:
- BUILD_KERNEL=y …
> riscv_syscall.S: Fix a massive bug in syscall dispatch logic

- libs/libxx/uClibc++/Make.defs
The SSL Cert for git.busybox.net has just expired today. This PR switches the uClibc++ download to cxx.uclibc.org.
This PR will fix the build for sim:cxxtest.
Tested OK on Ubuntu: https://gist.github.com/nuttxpr/4b41b2ab5839f15a7c796ef07fffe31b
```bash
$ tools/configure.sh sim:cxxtest
$ make
$ ./nuttx
```
> libs/uClibc++: Fix the Download URL for uClibc++

- libs/libxx/uClibc++/CMakeLists.txt
The SSL Cert for git.busybox.net has just expired today. This PR switches the uClibc++ download to cxx.uclibc.org for CMake.
This PR will fix the CMake build for sim:cxxtest.
Tested OK on Ubuntu: https://gist.github.com/nuttxpr/2117937562cdace45c6830796d264964
```bash
$ cmake -B build -DBOARD_CONFIG=sim:cxxtest
$ ./build/nuttx 
```
> libs/uClibc++: Fix the Download URL for uClibc++ (CMake)

- arch/arm/src/stm32h5/stm32h5xx_rcc.c
The naming scheme in board.h changed from STM32H5_ to STM32_. As a result we needed to adjust the naming of the STM32H5_BOARD_USExxx variables in stm32h5xx_rcc.c. Also made changes to allow the enabling of all 3 of HSI, CSI, or HSE in stm32_stdclockconfig. Lastly, the HSIDIV bits in RCC_CR were not being cleared before being set. Added logic to clear these bits.
defined CSIRDY_TIMEOUT
See above. Updated naming from board.h in stm32h5xx_rcc.c. Allowed enabling of all 3 of HSI, CSI, and HSE. HSIDIV is now cleared before being set. 
STM32H5 chips
Tested different values of HSIDIV. Confirmed settings with debugger and a successful boot to the Nuttx shell. Enabled CSI while still …
> Update BOARD_USExxx naming, input clock selection, and setting of HSIDIV

- cmake/nuttx_add_romfs.cmake
This patch solves two problems of adding romfs raw directory: 
1. refactored the directory adding logic to fix the problem that the directory could not be added
2. board content should overwrite common content
bugfix
cmake -B build -DBOARD_CONFIG=sim:nsh
build pass
> cmake(bugfix):fix directory not being successfully added when adding romfs

- fs/vfs/fs_pseudofile.c
fs/vfs: Fix initialization of `g_pseudofile_ops`
- Config: sim:nsh with PIPES enabled.
- Log
```
CC:  driver/fs_registerblockdriver.c vfs/fs_pseudofile.c:99:3: warning: initialization of ‘ssize_t (*)(struct file *, const struct uio *)’ {aka ‘long int (*)(struct file *, const struct uio *)’} from incompatible pointer type ‘int (*)(struct inode *)’ [-Wincompatible-pointer-types]
99 |   pseudofile_unlink,   /* unlink */
|   ^~~~~~~~~~~~~~~~~
vfs/fs_pseudofile.c:99:3: note: (near initialization for ‘g_pseudofile_ops.readv’)
```
Related: https://github.com/apache/nuttx/pull/13498
**Will close if there already has patch to fix this.**
fs/vfs/fs_pseudofile.c
1. Selftest: sim:nsh
2. NuttX CI
> fs/vfs: Fix initialization of `g_pseudofile_ops`

- boards/arm/phy62xx/phy6222/scripts/flash.ld
The Linker Script for phy6222 was garbled due to the SPDX Update. This PR removes the garbled text.
- https://github.com/apache/nuttx/pull/14704
This PR will fix the build error for phy6222: https://github.com/NuttX/nuttx/actions/runs/11760431178/job/32760999540#step:7:1092
None
> arm/phy6222: Fix the garbled Linker Script

- arch/xtensa/src/esp32/Kconfig
- include/nuttx/wireless/bluetooth/bt_hci.h
- wireless/bluetooth/Kconfig
- wireless/bluetooth/bt_conn.c
- wireless/bluetooth/bt_hcicore.c
This PR aims to improve and fix the core functionalities of the Bluetooth stack.
Initially, I tried to connect to the NuttX device (a ESP32 device using the esp32-devkitC:ble menu configuration) via Bluetooth and attempted to read the services/characteristics that it was contains. I noticed that the connection did not work, because the NuttX device (the host layer) was not receiving  any ACL packets (containing my requests for these services) from the controller layer. Therefore, the device running NuttX was not replying to my requests and connection failed.
I found a fix for this issue: the 'Controller to Host Flow Control' parameter has to be set to 0. This fixed the issue of packets not arriving in the host layer. With this setup, I got a successful connection. I decided to create an …
> Bluetooth: improved pairing process and host layer now successfully receives ACL packets

- tools/rp2040/Config.mk
1. The pre-installed "picotool" should not depend on `PICO_SDK_PATH`
2. Perhaps we should compile "picotool" from `PICO_SDK_PATH` if it was not found in `$PATH`
boards/arm/rp2040/*
1. Selftest
```bash
LD: nuttx 
Generating: nuttx.uf2 
Done.
LD: nuttx 
Building: picotool 
Generating: nuttx.uf2 
Done.
LD: nuttx 
PICO_SDK_PATH/picotool must be specified/installed for flash boot
```
2. NuttX CI
> tools/rp2040: Building picotool if necessary

- boards/sim/sim/sim/scripts/Make.defs
after #14466, add -mcmodel=medium witch is not supported in clang.
-mcmodel=large, should both support  gcc & clang.
case sim:nsh break in makefile.
change from -mcmodel=medium to -mcmodel=large maybe cause larger codesize? not sure if it's a critical index.
sim:nsh in macos will ready to work with both make and cmake after fix.
ci-test, local macos with cmake sim:nsh & makefile sim:nsh.
> fix macos sim nsh break, fix no -mcmodel=medium in clang.

- include/nuttx/wdog.h
- sched/sched/sched_processtimer.c
reason:
when CONFIG_CLOCK_TIMEKEEPING=y, compiler error may report
In file included from /home/hujun5/downloads1/vela_sim/nuttx/include/nuttx/sched.h:42,
from /home/hujun5/downloads1/vela_sim/nuttx/include/nuttx/arch.h:89,
from boardctl.c:33:
/home/hujun5/downloads1/vela_sim/nuttx/include/nuttx/irq.h:261:12: error: conflicting types for 'enter_critical_section'; have 'irqstate_t(void)' {aka 'long unsigned int(void)'}
261 | irqstate_t enter_critical_section(void) noinstrument_function;
|            ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/hujun5/downloads1/vela_sim/nuttx/include/nuttx/wqueue.h:37,
from /home/hujun5/downloads1/vela_sim/nuttx/include/nuttx/addrenv.h:39,
from /home/hujun5/downloads1/vela_sim/nuttx/include/nuttx/sched.h:40: …
> fix compiler error when CONFIG_CLOCK_TIMEKEEPING=y

- arch/arm/src/armv6-m/arm_svcall.c
- arch/arm/src/armv7-a/arm_syscall.c
- arch/arm/src/armv7-m/arm_svcall.c
- arch/arm/src/armv7-r/arm_syscall.c
- arch/arm/src/armv8-m/arm_svcall.c
- arch/arm/src/armv8-r/arm_syscall.c
when build with greenhills_202354(support  naked_function attribute), the naked_function should only contains the basic asm statements, so if the naked_function contains the statements that using to accept params from C lang runtime, then following build error will reported:
```
error #101112: Only basic asm expressions are allowed for functions
with __attribute__((naked)): dispatch_syscall
```
has no impact on other toolchain
2. has tested on ghs and gcc toolchains
> GreenHills support: fix the naked_function function non-compatible issue with arm_svcall

- arch/arm/src/qemu/CMakeLists.txt
fix the up_idle multiple definition build error
has no impact on other module
has passed ostest
> nuttx/qemu: Fix funciton up_idle multiple definition

- arch/arm/include/armv6-m/irq.h
- arch/arm/include/armv7-a/irq.h
- arch/arm/include/armv7-m/irq.h
- arch/arm/include/armv7-r/irq.h
- arch/arm/include/armv8-m/irq.h
- arch/arm/include/armv8-r/irq.h
- arch/arm/include/irq.h
- arch/arm64/include/irq.h
when we build mbedtls in vela with ghs compiler, the mbedtls need to access __ARM_ARCH and __ARM_FEATURE_DSP, and to construct the inline asm code based on these two macros.
With ghs compiler, these two macros are not defined, and will be evaluated as 0 by default, and thus will using to wrong inline asm code, in order to handle this issue, we need to add conversion between the ghs and gcc with __ARM_ARCH, __ARM_FEATURE_DSP
Has no impact with current gcc toolchain and other toolchain
2. has tested with ghs and gcc compiler
> GreenHills Support: add __ARM_ARCH, __ARM_FEATURE_DSP macro definition when build with ghs compiler

- include/nuttx/compiler.h
With greenhills version older than 202354, the __attribute__((naked)) cannot handled by greenhills compiler, and will report warning:
```
"/home/guoshichao/work_profile/vela_os/vela_car_6/nuttx/arch/arm/src/armv7-m/arm_svcall.c", line 79: warning #1097-D:
unknown attribute "naked"
static void dispatch_syscall(void) naked_function;
^
```
We need to ignore these warning when we build with old version GHS compiler
Has no impact on other toolchain
2. has tested in ghs and gcc compiler
> GreenHills support: fix the naked_function attr cannot handle warning with old version GHS compiler

- arch/risc-v/src/cmake/Toolchain.cmake
- arch/risc-v/src/common/Toolchain.defs
Suppress the warning message "nuttx has a LOAD segment with RWX permissions" in case of RAM boot mode is selected. RAM MODE: BOOT_RUNFROMEXTSRAM/BOOT_RUNFROMISRAM/BOOT_RUNFROMSDRAM/BOOT_COPYTORAM
Similar to https://github.com/apache/nuttx/pull/14474
RISC-V GCC 12+
Local machine
> riscv: Suppress LOAD RWX linker warning

- tools/ci/cibuild.sh
- tools/ci/platforms/darwin_arm64.sh
added shell script darwin_arm64.sh  for macOS Apple Silicon
updated toolchains for macOS on Apple Silicon
- arm64
- aarch64
- xpack-riscv
- xtensa-esp32
https://github.com/apache/nuttx/pull/14691
tested only on github workflow with only [macos]
macos-14
[github macos-14](https://github.com/simbit18/nuttx_test_pr/actions/runs/11777681978/job/32802632203)
> [darwin] CI macos-14 : updated toolchains for macOS Apple Silicon

- drivers/serial/serial.c
- drivers/syslog/syslog_channel.c
This would avoid the undesirable intertactions with the serial driver described in https://github.com/apache/nuttx/issues/14662.
Although I'm not entirely happy with this fix because it assumes the particular implementations of up_putc/up_nputc and its association to the serial devices, I haven't come up with better ideas for now.
An alternative is to place some serializations inside the target specific serial (and/or whatever provides up_putc api) implementaitons. But it isn't too attractive to put potentially complex logic into the low-level machinaries, especially when we have a lot of similar copies of it.
Another alternative is to deprecate up_putc. (at least for the purpose of syslog.) But it seems at least some of users are relying on what the current implementation provides …
> SYSLOG_DEFAULT: wrap up_putc/up_nputs calls with critical section

- sched/Kconfig
arm-none-eabi-g++: error: -pg and -fomit-frame-pointer are incompatible
arm-none-eabi-g++: error: -pg and -fomit-frame-pointer are incompatible
> gprof: Add a configuration dependency

- arch/arm/Kconfig
- include/nuttx/atomic.h
- include/nuttx/lib/stdatomic.h
- include/nuttx/macro.h
- libs/libc/machine/Kconfig
- libs/libc/machine/arch_atomic.c
Some armv7-m-based SoCs do not work with atomic instructions, even though armv7-m supports them.
To avoid using atomic instructions generated by gcc, CONFIG_LIBC_ARCH_ATOMIC is newly introduced with which arch_atomic.c is linked explicitly.
However, the function names need to be changed to avoid build errors, since the functions described in stdatomic.h are gcc built-in and inlined when the code is compiled.
CONFIG_ARCH_CHIP_CXD32XX.
About ARCH_CHIP_CXD32XX, the build is passed and ostest is passed, but the board is out-of-tree.
About raspberrypi-pico:nsh, the build is passed. (not executed)
About spresense:smp, the build is passed. (not executed)
tool-chain version:
```
arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10.3-2021.10) 10.3.1 20210824 (release)
Copyright (C) 2020 Free Software …
```
> arch_atomic : Introduce CONFIG_LIBC_ARCH_ATOMIC

- drivers/misc/rpmsgdev.c
the msg count is not changed while iov len is increased. which may cause the buffer reply by server is bigger than msg count.
we should break the loop when the read length is bigger than zero.
rpmsg device client
qemu
> drivers/misc: fix rpmsgdev read overflow

- drivers/misc/rpmsgdev_server.c
when client read and poll wait buffer from server side and server side may poll notify more than one times, then rpmsgdev in client side will call "rpmsgdev_poll_setup(priv, 0, false);" twice which will cause assert crash in rpmsgdev_server.c
rpmsgdev driver
qemu
> drivers/misc: fix rpmsg dev poll assert crash

- net/icmpv6/icmpv6_linkipaddr.c
In the context of cellular networks, lladdr should use the interface identifiers from PDN.
cortex_m33
> net:Compatible with cellular network cards of lladdr generation

- libs/libbuiltin/Kconfig
- libs/libbuiltin/Makefile
- libs/libbuiltin/compiler-rt/CMakeLists.txt
- libs/libbuiltin/compiler-rt/InstrProfilingPlatform.c
- libs/libbuiltin/compiler-rt/Make.defs
- tools/Directories.mk
- tools/FlatLibs.mk
- tools/KernelLibs.mk
- tools/ProtectedLibs.mk
1.  Organize make.defs and eliminate compilation warnings'
2.  Supports separate builtin rt.builtins or rt.profile
None
1. enable CONFIG_COMPILER_RT_BUILTINS to builtin rt.builtins instead of the toolchain's own
2. enable CONFIG_COMPILER_RT_PROFILE to builtin rt.profile instead of the toolchain's own
> libbuitin/compiler_rt: Supports separate builtin rt.builtins or rt.profile

- fs/v9fs/CMakeLists.txt
This PR is a fix for the problem that v9fs does not correctly include virtio-9p.c in the compilation when compiled with cmake.
**Change:**
change `CONFIG_DRIVERS_VIRTIO_9P` -> `CONFIG_V9FS_VIRTIO_9P`
After this PR, virtio-9p can be compiled normally under cmake
> v9fs/CMakeLists.txt:Fix the problem that virtio-9p is not compiled 

- include/nuttx/clock.h
Fix typo errors in include/nuttx/clock.h
none
ci ostest
> Fix typo errors in include/nuttx/clock.h

- boards/arm/sam34/sam4e-ek/src/sam_ili9325.c
- boards/arm/sam34/sam4e-ek/src/sam_ili9341.c
- boards/arm/samv7/samv71-xult/src/sam_ili9488.c
- boards/arm/stm32/shenzhou/src/stm32_ili93xx.c
- boards/arm/stm32/stm3210e-eval/src/stm32_lcd.c
- boards/arm/stm32/stm3220g-eval/src/stm32_lcd.c
- boards/arm/stm32/stm3240g-eval/src/stm32_lcd.c
- drivers/lcd/mio283qt2.c
- drivers/lcd/mio283qt9a.c
- drivers/lcd/ra8875.c
- drivers/lcd/ssd1289.c
* It seems that they assume up_putc() and syslog() outputs to the same device. Depending on the system and configurations, it's wrong.
* They are wrapped with "#if 0" and unused.
Fixes https://github.com/apache/nuttx/issues/14694
> Remove "dumprun" functions from various LCD drivers

- arch/arm64/src/common/arm64_vectors.S
fix the bug
#0  udelay_coarse (microseconds=63000) at timers/arch_alarm.c:65
#1  up_ndelay (nanoseconds=nanoseconds@entry=250000000) at timers/arch_alarm.c:429
#2  0x00000000402b130c in up_udelay (microseconds=microseconds@entry=250000) at timers/arch_alarm.c:414
#3  0x00000000402b136c in up_mdelay (milliseconds=milliseconds@entry=250) at timers/arch_alarm.c:399
#4  0x000000004029db88 in reset_board () at misc/assert.c:787
#5  _assert (filename=filename@entry=0x40e29d18 "common/arm64_fatal.c", linenum=linenum@entry=549, msg=0x0, regs=regs@entry=0x0) at misc/assert.c:814
#6  0x00000000402d84e8 in __assert (filename=filename@entry=0x40e29d18 "common/arm64_fatal.c", linenum=linenum@entry=549, msg=<optimized out>) at assert/lib_assert.c:38
#7  0x00000000402907a4 in arm64_fatal_handler …
> arch/arm64: bug fix,arm64_fatal_handler need regs parms

- libs/libc/modlib/gnu-elf.ld
modlib:need add ctors to init_array and dtors to fini_array
modlib
esp32 with qemu run module, and pass it
> modlib:need add ctors to init_array and dtors to fini_array

- arch/risc-v/Kconfig
`ARCH_HAVE_RAMFUNCS` has no actual effect on the ESP32-C3, but ESP32-C3 has RAM functions, so select it to mark that is OK, and then we can also suppress the RWX memory region warning with https://github.com/apache/nuttx/pull/14724
Minor
> arch/risc-v: Add ARCH_HAVE_RAMFUNCS option for ESP32-C3

- CMakeLists.txt
- cmake/nuttx_add_application.cmake
- cmake/nuttx_add_dependencies.cmake
- cmake/nuttx_extensions.cmake
[Enhancement]
1. Wrapped CMake native method is nuttx_cmake module,
It can be quickly called in the build system
2. Add sanity check for commonly called functions
**This will make our build system simpler and more modern :-)**
e.g:
```cmake
if(CONFIG_LIB_FOO)
set(FLAGS -Werror)
set(INCDIR ${CMAKE_CURRENT_LIST_DIR}/include)
file(GLOB CSRCS ${CMAKE_CURRENT_LIST_DIR}/*.c)
set(CSRCS ${CSRCS})
if(CONFIG_AAA)
list(APPEND CSRCS a.c)
endif()
if(CONFIG_BBB)
list(APPEND CSRCS b.c)
endif()
if(CONFIG_OPT)
list(APPEND FLAGS -Os)
endif()
nuttx_add_library(foo STATIC)
target_sources(foo PRIVATE ${CSRCS})
target_compile_options(foo PRIVATE ${FLAGS})
target_include_directories(foo PRIVATE ${INCDIR})
endif()
``` 
```python
nuttx_library_ifdef(CONFIG_LIB_FOO foo)
nuttx_wildcard_sources(./*.c) …
```
> cmake(enhance):add NuttX CMake extensions module

- cmake/nuttx_add_romfs.cmake
- drivers/serial/CMakeLists.txt
[Bugfix]
1. add missing driver/serial CMake build source
2.  keeping intermediate products of romfs target in the binary directory helps debugging
bugfix
CI check
> cmake(bugfix):add missing source file for driver/serial and keep romfs cmake intermediate 

- boards/arm/stm32/olimex-stm32-p407/scripts/memory.ld
Just increase the ksram and usram to avoid compilation issue.
Fix kmodule build
Local building only
> arm/olimex-stm32-p407: Fix kmodule board profile

- fs/mount/fs_automount.c
Fixed CI Break caused by https://github.com/apache/nuttx/pull/14632
```
==================================================================================== Configuration/Tool: spresense/example_camera,CONFIG_ARM_TOOLCHAIN_GNU_EABI 2024-11-12 12:24:37
Cleaning...
Configuring...
Disabling CONFIG_ARM_TOOLCHAIN_GNU_EABI
Enabling CONFIG_ARM_TOOLCHAIN_GNU_EABI
mount/fs_automount.c: In function 'automount_initialize': Error: mount/fs_automount.c:816:7: error: 'return' with no value, in function returning non-void [-Werror=return-type]
816 |       return;
|       ^~~~~~
In file included from mount/fs_automount.c:43:
/github/workspace/sources/nuttx/include/nuttx/fs/automount.h:176:11: note: …
```
> fs_automount:fix ci break

- arch/arm64/include/irq.h
- arch/arm64/src/common/arm64_exit.c
- arch/arm64/src/common/arm64_internal.h
- arch/arm64/src/common/arm64_sigdeliver.c
- arch/arm64/src/common/arm64_syscall.c
sys_call2(SYS_switch_context, (uintptr_t)rtcb, (uintptr_t)tcb) 
sys_call1(SYS_restore_context, (uintptr_t)next)
> arch/arm64: syscall SYS_switch_context and SYS_restore_context use tcb as parm

- arch/arm64/src/imx9/Make.defs
- arch/arm64/src/imx9/hardware/imx93/imx93_memorymap.h
- arch/arm64/src/imx9/hardware/imx9_trdc.h
- arch/arm64/src/imx9/imx9_boot.c
- arch/arm64/src/imx9/imx9_trdc.c
- arch/arm64/src/imx9/imx9_trdc.h
- boards/arm64/imx9/imx93-evk/include/imx9_trdc_config.h
Example trdc header for bootloader build
This is needed when building bootloader for imx9-evk
and runtime logs from before and after change is …
> boards/arm64/imx9/imx93-evk: add trdc header

- arch/xtensa/src/common/xtensa_switchcontext.c
`up_interrupt_context` is more smp friendly
context switch
`esp32s3-devkit:smp` ostest
> xtensa: use up_interrupt_context() to determine if in interrupt context

- boards/arm/stm32/stm32f103-minimum/scripts/ld.script
> boards/stm32f103-minimum: fix unaligned pointer to .data section in ld.script

- fs/procfs/fs_procfsversion.c
The procfsversion should be under control of `FS_PROCFS_EXCLUDE_VERSION`
```diff
#sim:nsh
- CONFIG_FS_PROCFS_EXCLUDE_PROCESS=y
```
```
LD:  nuttx
/usr/bin/ld: nuttx.rel:(.rodata.g_procfs_entries+0xc8): undefined reference to `g_version_operations'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:429: nuttx] Error 1
make: *** [tools/Unix.mk:551: nuttx] Error 2
```
fs/procfs
1. Selftest: Using `sim:nsh` with `CONFIG_FS_PROCFS_EXCLUDE_PROCESS` disabled
2. NuttX CI
> fs/procfs: The procfsversion should be under control of `FS_PROCFS_EXCLUDE_VERSION`

- cmake/nuttx_add_application.cmake
the `link_library` of the static target will cause PRIVATE to be inherited to nuttx, resulting in duplicate linking and definition problems. because all target static libraries will eventually be linked, there is no need to specify it explicitly.
```shell
ld --start-group libapp1.a libapp2.a libarch.a libboard.a --end-group libapp1.a 
``` 
If the static definition exceeds the linker group, there is a risk of multiple definition errors.
should be compatible with all cmake build configurations
cmake -B build -DBOARD_CONFIG=qemu-armv7a:nsh
build pass
> cmake(bugfix):remove no need target_link_library in static target

- arch/arm/src/stm32h5/hardware/stm32_adc.h
This change defines macros for the ADC register map from ST document RM0481.
Added a file to `nuttx/arch/arm/src/stm32h5/hardware` to add register definitions for the STM32H5 ADC peripheral. It is based on the map defined in ST reference manual RM0481  
This change lays the groundwork for future implementation of ADC driver for the STM32H5. This file addition should not impact anything at the moment. 
No testing was done other than building the `nucleo-h563zi:nsh` configuration successfully and getting to the nuttshell. All STM32H5 files passed Nxstyle check.
> arch/stm32h5: Add ADC hardware register file

- tools/gdbserver.py
Add arm64 support.
Fixed the merging issue that removed 64bit register parser.
Parse tcb info from elf file instead of user provided(crash log, memory dump or coredump) file in case user provided is corrupted.
New feature added, and now less error prone to corruption.
Tested with arm64 qemu generated crash log.
```bash
python3 nuttx/tools/gdbserver.py -e build/nuttx -l crash.log -a arm64 -g gdb-multiarch
```
> Add arm64 support for gdbserver.py tool

- libs/libxx/libcxx/CMakeLists.txt
- libs/libxx/libcxxabi/CMakeLists.txt
PR https://github.com/apache/nuttx/pull/14668 caused a build error after adjusting the layout.
This commit fixes this problem
```
/home/data/vela/github/nuttx/libs/libxx/libcxxabi/libcxxabi/src/cxa_exception.h:47:10: error: 'unexpected_handler' in namespace 'std' does not name a type
47 |     std::unexpected_handler unexpectedHandler;
|          ^~~~~~~~~~~~~~~~~~
/home/data/vela/github/nuttx/libs/libxx/libcxxabi/libcxxabi/src/cxa_exception.h:85:10: error: 'unexpected_handler' in namespace 'std' does not name a type
85 |     std::unexpected_handler unexpectedHandler;
|          ^~~~~~~~~~~~~~~~~~
/home/data/vela/github/nuttx/libs/libxx/libcxxabi/libcxxabi/src/cxa_exception.h:121:65: error: static assertion failed: propagationCount has wrong negative offset
121 | …
```
> cmake(bugfix):fix libcxx build error cause by layout changed

- include/pthread.h
- libs/libc/pthread/pthread_condinit.c
- sched/pthread/pthread_condbroadcast.c
- sched/pthread/pthread_condclockwait.c
- sched/pthread/pthread_condsignal.c
- sched/pthread/pthread_condwait.c
pthread_cond_broadcast use wait_count for judement
This commit fixes the comment from https://github.com/apache/nuttx/pull/14581
pthread_cond
ostest
> pthread_cond_broadcast use wait_count for judement

- boards/arm/sama5/sama5d4-ek/src/at25_main.c
- include/nuttx/streams.h
- libs/libc/obstack/lib_obstack_vprintf.c
- libs/libc/stream/lib_base64outstream.c
- libs/libc/stream/lib_blkoutstream.c
- libs/libc/stream/lib_bufferedoutstream.c
- libs/libc/stream/lib_fileoutstream.c
- libs/libc/stream/lib_hexdumpstream.c
- libs/libc/stream/lib_lowoutstream.c
- libs/libc/stream/lib_lzfcompress.c
- libs/libc/stream/lib_meminstream.c
- libs/libc/stream/lib_memoutstream.c
- libs/libc/stream/lib_memsistream.c
- libs/libc/stream/lib_memsostream.c
- libs/libc/stream/lib_mtdoutstream.c
- libs/libc/stream/lib_nullinstream.c
- libs/libc/stream/lib_nulloutstream.c
- libs/libc/stream/lib_rawinstream.c
- libs/libc/stream/lib_rawoutstream.c
- libs/libc/stream/lib_rawsistream.c
- libs/libc/stream/lib_rawsostream.c
- libs/libc/stream/lib_stdinstream.c
- libs/libc/stream/lib_stdoutstream.c
- libs/libc/stream/lib_stdsistream.c
- libs/libc/stream/lib_stdsostream.c
- libs/libc/stream/lib_syslograwstream.c
- libs/libc/stream/lib_syslogstream.c
- libs/libc/stream/lib_zeroinstream.c
int is not reliable when we use same code for cross platform.
replace with off_t,size_t,ssize_t should prefer.
offset int -> offset, len int -> size_t, ret int -> ssize_t
Also we should readback sector/block before operate to new sector/block,
for user only update partial case.
stream will able to support FS_LARGEFILE better cover >4GB devices.
if user use blk/mtd stream to update partial, the old data will be kept back.
CI-test, local arm-v8m prject, qemu-armv8a, ubutun sim:nsh
> update stream relative, fix mtd&blk stream readback before block update. decrese int use in stream to handle FS_LARGEFILE

- arch/arm/src/samv7/sam_afec.c
This commit adds a max_pins field into the private struct. AFEC0 has 11, AFEC1 has 12. The 12th pin of AFEC0 is an internal pin connected to a temperature sensor, which we don't use.
On local HW. A voltage was applied to the AFEC1_AF11 and then successfully measured.
> arch/arm/src/samv7/sam_afec.c: AFEC1 actually has 12 physical inputs

- boards/sim/sim/sim/scripts/Make.defs
avoid SIM compilation post build issues on other platforms
this should fix issue https://github.com/apache/nuttx/issues/14773#issuecomment-2476484040
bugfix
```
./tools/configure.sh -l sim:nsh
make -j12
```
```
LD:  nuttx
Pac SIM with dynamic libs..
'/lib/x86_64-linux-gnu/libpthread.so.0' -> 'sim-pac/libs/libpthread.so.0'
'/lib/x86_64-linux-gnu/librt.so.1' -> 'sim-pac/libs/librt.so.1'
'/lib/x86_64-linux-gnu/libz.so.1' -> 'sim-pac/libs/libz.so.1'
'/lib/x86_64-linux-gnu/libc.so.6' -> 'sim-pac/libs/libc.so.6'
'/lib64/ld-linux-x86-64.so.2' -> 'sim-pac/ld-linux-x86-64.so.2'
SIM elf with dynamic libs archive in nuttx.tgz
```
> build(bugfix):pac sim elf ONLY in Linux platform

- libs/libc/misc/lib_backtrace.c
We could call backtrace from mm module and access to kasan protected mm_node.backtrace field. Disable kasan check for backtrace_format.
`memdump` can work correctly without being caught by kasan.
Tested with qemu arm64 with DEBUG_MM and mm backtrace enabled.
Now memdump will work correctly.
> libc/misc: do not sanitize backtrace_format

- include/pthread.h
- libs/libc/pthread/pthread_barrierinit.c
- sched/pthread/pthread_barrierwait.c
reason:
We decouple semcount from business logic by using an independent counting variable, which allows us to remove critical sections in many cases.
pthread_barrier_wait
Build Host:
OS: Ubuntu 20.04
CPU: x86_64
Compiler: GCC 9.4.0
$ make
$ qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic
-machine virt,virtualization=on,gic-version=3
-net none -chardev stdio,id=con,mux=on -serial chardev:con
> pthread: remove enter_critical_section in pthread_barrier_wait

- drivers/segger/stream_rtt.c
after this patch, stream decreased int, use more size_t off_t ssize_t
#14778 
and 
the segger/stream_rtt get warning after change, 
#14796 
as it's a stream implement outside of libs/libc/stream, it's not coverd in previous patch.
fix warning.
ci-test, local sim:segger.
> segger/stream_rtt: fix warning after stream update

- drivers/can/sja1000.c
can/sja100: leave critical section properly
leave critical section properly before return
N/A
ci-check
> can/sja100: leave critical section properly

- arch/arm/src/stm32h5/stm32h5xx_rcc.c
- boards/arm/stm32h5/nucleo-h563zi/include/board.h
The PLL clock configuration was simplified on the assumption the clocks are correctly set in the board.h file. Instead of seperate conditions for register components, assume the relevant PLL registers are fully defined in board.h. This should result in easier to understand defines in board.h and simpler code flow in the standard clock configuration function.
Changes were mad in the board file alongside changing the arch files. Changes to board/stm32h5:
- PLL1 has been configured to use integer instead of fractional mode to reach the 250 MHz target. PLL2 and PLL3 configurations were removed since they are currently unused in the H5 configuration.
- PLL1 output was verified by testing for changes in serial baud rate.
*Note: Please adhere to [Contributing …
> arch/stm32h5: Simplify PLL configuration.

- libs/libc/misc/lib_pathbuffer.c
Summary:
Change nxmutex to spinlock to fix bug:
```
_assert
|
->dump_fatal_info
|
->dump_tasks
|
->dump_filelist
|
->files_dumplist
|
->lib_get_pathbuffer
|
->nxmutex_lock      <-- hold mutex on assert will trigger an nested exception
```
Test cases based on local qemu environment passed
> lib_pathbuffer: change nxmutex -> spinlock

- sched/sched/sched_backtrace.c
- sched/sched/sched_setpriority.c
- sched/sched/sched_suspend.c
- sched/signal/sig_dispatch.c
- sched/task/task_restart.c
in smp_call handle we only change TCB_FLAG_CPU_LOCKED bit of tcb->flag
change unrelated changes to tcb->flag fields, may cause error
smp call
ci ostest
> in smp_call handle we only change TCB_FLAG_CPU_LOCKED bit of tcb->flag

- sched/misc/assert.c
Don't compile `dump_assert_info()` logic if `CONFIG_DEBUG_ALERT=n`.
With `_alert()` disabled this logic does nothing, but the compiler is not smart enough to optimize this code.
On minimal stm32f3 configuration it saves 220B of flash.
save some space for systems not using `_alert()`
nucleo-f302r8
> sched/misc/assert.c: don't compile dump_assert_info logic if CONFIG_DEBUG_ALERT=n

- sched/pthread/pthread_condbroadcast.c
remove sched_lock in pthread_cond_broadcast
reason:
Since pthread_cond_broadcast is already protected by a mutex, even if sem_post causes a context switch, it will not affect the count of wait_count.
pthread cond_wait
ci ostest
> remove sched_lock in pthread_cond_broadcast

- mm/iob/iob.h
- mm/iob/iob_add_queue.c
- mm/iob/iob_alloc.c
- mm/iob/iob_alloc_qentry.c
- mm/iob/iob_free.c
- mm/iob/iob_free_qentry.c
- mm/iob/iob_free_queue_qentry.c
- mm/iob/iob_initialize.c
- mm/iob/iob_navail.c
- mm/iob/iob_remove_queue.c
- mm/iob/iob_statistics.c
reason:
We decouple semcount from business logic
by using an independent counting variable,
which allows us to remove critical sections in many cases.
mm/iob
test by https://github.com/apache/nuttx-apps/pull/2849
Build Host:
OS: Ubuntu 20.04
CPU: x86_64
Compiler: GCC 9.4.0
$ make
$ qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic
-machine virt,virtualization=on,gic-version=3
-net none -chardev stdio,id=con,mux=on -serial chardev:con
> mm/iob: remove csection

- drivers/analog/ads1255.c
- include/nuttx/analog/adc.h
since the common driver shouldn't have the prefix 'up_'
ci
> drivers/adc: Rename up_ads1255initialize to ads1255_initialize

- drivers/timers/arch_alarm.c
and timers/arch_alarm.c:150:51: error: 'ticks' may be used uninitialized
fix compiler warning
ci
> Fix timers/arch_alarm.c:109:3: error: 'now' may be used uninitialized

- arch/arm/include/syscall.h
In the GreenHills compiler, the predefined macros for thumb mode detection are different from those in the GCC compiler. The judgment needs to be made through __THUMB_AWARE__ and __THUMB2_AWARE__.
If the wrong macros are used in GreenHills, it will be impossible to determine whether the current mode is thumb mode or not. Consequently, the wrong **SYS_smhcall** will be used, and then a compilation error will occur.
Has no impact on current implementation
2. has tested on GHS and GCC compiler
> GreenHills support: add thumb mode detection support for ghs compiler

- .github/linters/setup.cfg
- arch/sim/src/sim/win/sim_hostfs.c
- drivers/note/noteram_driver.c
- drivers/reset/core.c
- drivers/sensors/bmi160_uorb.c
- libs/libxx/.gitignore
- sched/misc/assert.c
- sched/sched/sched_releasetcb.c
- sched/misc: Remove the dup inclusion of nuttx/irq.h in assert.c 
- sensors/bmi160_uorb.c: Fix the typo error 
- note/noteram_driver: Remove the unused variable j 
- sim/win: Replace nuttx_mode_t with int
- .github/linters: Ignore E704 warning 
minor
ci
> minor code refactor

- arch/arm64/include/arch.h
- arch/arm64/include/irq.h
```
time/lib_localtime.c: In function 'tz_lock':
time/lib_localtime.c:396:7: error: 'tpidr_el1' undeclared (first use in this function)
396 |   if (up_interrupt_context() || (sched_idletask() && OSINIT_IDLELOOP()))
|       ^~~~~~~~~~~~~~~~~~~~
```
arm64
ci
> arm64: fix compile failed 'tpidr_el1' undeclared

- net/udp/udp_callback.c
*The valule of g_netstats.udp.drop has been increased in net_dataevent() function,
while it is increased in udp_datahandler().*
*The statistical count of lost packets is twice the actual count of lost packets..*
**
> fix: remove duplicated statistics of upd.drop

- drivers/serial/serial.c
- drivers/syslog/syslog_channel.c
Reapply "SYSLOG_DEFAULT: wrap up_putc/up_nputs calls with critical section" with a fix.
original change https://github.com/apache/nuttx/pull/14722
a revert https://github.com/apache/nuttx/pull/14751
- esp32-devkitc:wifi_smp (smp)
- esp32s3-devkit:smp (ostest, smp)
(with https://github.com/apache/nuttx/pull/14755 and a few other unrelated local patches)
> Reapply "SYSLOG_DEFAULT: wrap up_putc/up_nputs calls with critical section" with a fix

- sched/group/group_signal.c
group_signal_handler: Remove a redundant check.
We know tcb is not NULL here as we have a DIAGASSERT on it immediately above.
no functional changes are expected.
esp32s3-devkitc:smp
> group_signal_handler: Remove a redundant check

- drivers/power/pm/pm_idle.c
This reverts commit 731af5b42fb20d62b57e79eb52b3fbbeac38eecb.
Now we already support sched_lock for per cpu/tcb,
And as we should support post like API in pm callbacks, should do sched_lock to avoide scheduler problems.
Before percpu/tcb lock ready, when smp case, multi-core do sched_lock will cause a dead lock. This pr revert the workaround patch.
pm_idle behavior as expect do sched_lock/sched_unlock.
CI-test, qemu-armv8a.
> Revert "drivers/pm: pm_smp remove sched_lock", should do sched_lock before pm ops and WFI.

- arch/xtensa/src/esp32/esp32_serial.c
- arch/xtensa/src/esp32s3/esp32s3_serial.c
- drivers/syslog/syslog_channel.c
- fs/vfs/fs_read.c
- fs/vfs/fs_write.c
a few comment fixes.
no functional changes are expected.
build tested.
> a few comment fixes

- boards/arm/stm32/nucleo-f4x1re/src/stm32_adc.c
fix typo, should include ADC file, not PWM file
fix typo
none
> boards/arm/stm32/nucleo-f4x1re/src/stm32_adc.c: fix typo

- boards/arm/stm32/nucleo-f4x1re/src/stm32_adc.c
- boards/arm/stm32/nucleo-f4x1re/stm32_adc.c: remove dependency on AJOYSTICK
remove dependency on AJOYSTICK, ADC can be used without analog joystick, so there is no reason to depends on it
adc can be used without AJOYSTICK enabled
CI
> boards/arm/stm32/nucleo-f4x1re/stm32_adc.c: remove dependency on AJOYSTICK

- arch/arm/Kconfig
- In https://github.com/apache/nuttx/pull/14465, atomic_compare_exchange_weak_explicit() was newly introduced in semaphore. However, cxd56xx has an issue with the API if SMP is enabled (see up_testset2 in cxd56_testset.c).
- This commit fixes the issue by using LIBC_ARCH_ATOMIC.
- Only cxd56xx SoCs in SMP mode.
- Tested with spresense:smp, spresense:wifi_smp
- NOTE: If DEBUG_ASSERTIONS is enabled assert would be happend. I think this might be another issue.
> arch: cxd56xx: Fix cxd56xx for SMP

- include/nuttx/mm/iob.h
- mm/iob/iob.h
- mm/iob/iob_alloc.c
- mm/iob/iob_alloc_qentry.c
- mm/iob/iob_free.c
- mm/iob/iob_free_qentry.c
- mm/iob/iob_initialize.c
- mm/iob/iob_navail.c
- mm/iob/iob_statistics.c
mm/iob: fix some comment in https://github.com/apache/nuttx/pull/14764
reason:
Since we decoupled counting and sem count,
we changed the meanings of three key global variables:
g_iob_count: A positive number indicates the available number
of IOBs, while a negative number indicates the number of waiters in iob_alloc (when throttle == false).
g_throttle_wait: Represents the number of waiters in
iob_alloc (when throttle == true), and it will not be negative.
g_qentry_wait: Represents the number of waiters for
qentry, and it will not be negative.
iob 
iob test
> fix some comment in https://github.com/apache/nuttx/pull/14764

- .github/workflows/build.yml
CI Test will sometimes run for 6 hours (before getting auto-terminated by GitHub):
- https://github.com/apache/nuttx/issues/14808
- https://github.com/apache/nuttx/issues/14680
This is a problem because:
- It will increase our usage of GitHub Runners. Which may overrun the [GitHub Actions Budget](https://infra.apache.org/github-actions-policy.html) allocated by ASF.
- Suppose right after CI Test there's another build. If CI Test runs for all 6 hours, then the build after CI Test will never run.
For this PR: We assume that Every CI Job (e.g. risc-v-05) will complete normally within 2 hours. If any CI Job exceeds 2 hours: This PR will kill the CI Test Process `pytest` and allow the next build to run.
CI Test will no longer run beyond 2 hours. When the CI Test is killed after 2 hours: The CI …
> CI: Kill CI Test after 2 hours

- arch/arm/src/armv7-m/Kconfig
- arch/arm/src/armv8-m/Kconfig
- arch/arm/src/efm32/efm32_start.c
- boards/arm/efm32/efm32gg-stk3700/include/board.h
1. arm/efm32: fix regression by PR #14810
2. arm/cortex-m: itm syslog should select SYSLOG_REGISTER
3. arm/efm: fix build warning
```
chip/efm32_start.c:150:3: warning: implicit declaration of function 'itm_syslog_initialize';
did you mean 'syslog_initialize'? [-Wimplicit-function-declaration]
150 |   itm_syslog_initialize();
|   ^~~~~~~~~~~~~~~~~~~~~
|   syslog_initialize
```
4. arm/efm32: fix build break caused by undeclared error
Old upstream from @acassis:
https://github.com/acassis/nuttx/blob/d97227eddd96713870875f33b6a4a2ebad10db0b/nuttx/configs/efm32gg-pnbfano/include/board.h
```
chip/efm32_clockconfig.c:860:24: error: 'BOARD_SWOPORT_LOCATION' undeclared (first use in this function);
did you mean 'BOARD_UART0_ROUTE_LOCATION'?
860 |   regval |= ((uint32_t)BOARD_SWOPORT_LOCATION <<
| …
```
> arm/efm32: fix regression by PR#14810

- fs/littlefs/Kconfig
- fs/littlefs/lfs_vfs.c
This PR is mainly from the discussion of https://github.com/apache/nuttx/pull/14479
In the current littlefs for NuttX, because the attr function is introduced, we can get/set file attributes through the interface `lfs_file_getattr` / `lfs_file_setattr` . But this requires that the mkfs tool also needs to write the file attributes when creating the file, otherwise the fstat interface will return -2
**Changes**
Therefore, in littlefs_fstat we ignore the error message for -ENOENT, and when it returns we assume that it is a file with no attributes set.
At the same time, a new macro `CONFIG_FS_LITTLEFS_ATTR_UPDATE` is introduced to determine whether to write the file attributes each time the file is created, which depends on `FS_LITTLEFS_ATTR_MAX` > 0
**Impact …
> Support enabling/disabling attr attribute in littlefs for nuttx

- arch/risc-v/src/mpfs/mpfs_irq.c
On MPFS PolarFire, when we recently rebased to use the latest from NuttX, some of the functionality was broken. After reviewing, we noticed mpfs_irq.c no longer defaults the global interrupt priorities (removed in https://github.com/apache/nuttx/pull/14397), and this creates issues where interrupts are missed. Adding this back in.  
Tested with SMP on MPFS PolarFire.
> arch/risc-v/src/mpfs/mpfs_irq.c: Default global interrupt priorities

- sched/addrenv/addrenv.c
The performance penalty in SMP mode is too big for taking the big kernel lock simply to bump the address environment reference counter; fix this by using the compiler provided atomic macros.
Improve context switch performance / handling of the address environment reference counter.
rv-virt:ksnh64
rv-virt:ksmp64
MPFS + BUILD_KERNEL
> addrenv/addrenv.c: Use atomic_ functions to handle the reference counter

- sched/irq/irq.h
Remove dead code (g_cpu_irqsetlock does not exist any more)
Absolutely none.
None.
> irq/irq.h: Remove extern of non-existent global

- boards/xtensa/esp32/esp32-2432S028/src/Make.defs
- boards/xtensa/esp32/esp32-audio-kit/src/Make.defs
- boards/xtensa/esp32/esp32-devkitc/src/Make.defs
- boards/xtensa/esp32/esp32-ethernet-kit/src/Make.defs
- boards/xtensa/esp32/esp32-lyrat/src/Make.defs
- boards/xtensa/esp32/esp32-pico-kit/src/Make.defs
- boards/xtensa/esp32/esp32-sparrow-kit/src/Make.defs
- boards/xtensa/esp32/esp32-wrover-kit/src/Make.defs
- boards/xtensa/esp32/lilygo_tbeam_lora_gps/src/Make.defs
- boards/xtensa/esp32/ttgo_eink5_v2/src/Make.defs
- boards/xtensa/esp32/ttgo_lora_esp32/src/Make.defs
- boards/xtensa/esp32/ttgo_t_display_esp32/src/Make.defs
- boards/xtensa/esp32s2/esp32s2-kaluga-1/src/Make.defs
- boards/xtensa/esp32s2/esp32s2-saola-1/src/Make.defs
- boards/xtensa/esp32s2/franzininho-wifi/src/Make.defs
- boards/xtensa/esp32s3/esp32s3-box/src/Make.defs
- boards/xtensa/esp32s3/esp32s3-devkit/src/Make.defs
- boards/xtensa/esp32s3/esp32s3-eye/src/Make.defs
- boards/xtensa/esp32s3/esp32s3-korvo-2/src/Make.defs
- boards/xtensa/esp32s3/esp32s3-lcd-ev/src/Make.defs
- boards/xtensa/esp32s3/esp32s3-lhcbit/src/Make.defs
- boards/xtensa/esp32s3/esp32s3-meadow/src/Make.defs
Remove duplicate board Make.defs.
In PR https://github.com/apache/nuttx/pull/14805 we found board Make.defs
will be included twice, so remove one of them.
ESP32 board
esp32-devkitc:sotest build success.
> xtensa/esp32: Remove duplicate board Make.defs

- arch/risc-v/include/spinlock.h
It should be a bit more efficient to do compared to the LR/SC pair.
Atomic test&set can be implemented with AMOSWAP, this way should be a bit more efficient even.
rv-virt:ksmp64
MPFS with SMP (not released yet)
> risc-v/up_testset: Implement test-and-set with AMOSWAP

- net/udp/udp.h
- net/udp/udp_callback.c
- net/udp/udp_notifier.c
- net/udp/udp_recvfrom.c
- net/udp/udp_txdrain.c
Due to abnormal application exit,so add tls cleanup to protect udp process
udp
> add tls cleanup toprotect udp

- sched/addrenv/addrenv.c
addrenv_give should return the new reference counter (after subtraction) instead of the old one.
Fix regression from: https://github.com/apache/nuttx/pull/14859
rv-virt:knsh32
> sched/addrenv.c: Fix usage of atomic_fetch_sub

- arch/xtensa/src/esp32s3/esp32s3_partition.c
esp32s3_partition.c: Appease a compiler warning (-Wdiscarded-qualifiers)
no functionality changes are intended.
build tested.
> esp32s3_partition.c: Appease a compiler warning (-Wdiscarded-qualifiers)

- sched/sched/sched_unlock.c
sched_unlock: remove redundant/stale logic and comment
no functional changes are intended.
esp32s3-devkitc
> sched_unlock: remove redundant/stale logic and comment

- arch/arm64/src/imx9/imx9_lpspi.c
- arch/arm64/src/imx9/imx9_lpspi.h
Hardware initialization is based refcount, not
spi enable bit and add interface to unitialize bus
and runtime logs from before and after change …
> arch/arm64/imx9/lspi: improve spi initialization

- net/tcp/tcp.h
- net/tcp/tcp_callback.c
- net/tcp/tcp_connect.c
- net/tcp/tcp_recvfrom.c
- net/tcp/tcp_send_buffered.c
- net/tcp/tcp_send_unbuffered.c
This PR addresses an issue where abnormal application exits were causing crash in the TCP/IP stack due to tcp conn will be used after free.   
tcp_send / tcp_recv / tcp_connect
Impact on user: YES (Applications using TCP will now have improved stability on abnormal exit).
Impact on documentation: YES (Documentation should be updated to describe the new TLS cleanup mechanism and how it prevents issues on application exit)
Impact on security: Potentially YES (If the abnormal exit was exploitable, this fix might improve security. Explain clearly).
Impact on compatibility: NO (If this is true, state it explicitly)
Target: sim and others product by monkey
Log:  see " pthread is being canceled, need to cleanup cb",and device didn't crash
> Add tls cleanup to protect tcp

- arch/arm/src/stm32h5/hardware/stm32_tim.h
This commit adds register definitions for advanced, basic, and general purpose timers. Formatting convention was taken from the H7 hardware timer header.
Added hardware register definitions for all timers on the STM32H5 chip. 
Lays the groundwork for adding timer support for the STM32H5 in the future. 
Checked that the nutshell was building and running without issue. No compilation errors or warnings. 
Host OS: Ubuntu 24.04 on WSL 2 (Windows 11)
Compiler: arm-none-eabi-gcc (15:13.2.rel1-2) 13.2.1 20231009
Target:
- Arch: STM32H5
- Chip: STM32H563ZIT6U
- Board: Nucleo-H563ZI
- Config: nucleo-h563zi:nsh
> arch/stm32h5: Add timer register hardware file

- boards/sim/sim/sim/scripts/Make.defs
This reverts commit 56c920ce5d65145368e364eb1a679d93d2cf74d1.
ci test
> Revert "sim/make: fix macos sim:nsh make break, no -mcmodel in clang"

- arch/arm/src/rp23xx/rp23xx_start.c
Fix a boot sequence error in last PR. Was trying to match that of RP2040 and modified it at the last minute... Thought it would do no harm but I was wrong :(
Fix boot hang
Now booting properly
> fix(rp2350): should copy data before init clock

- arch/arm/src/armv6-m/arm_svcall.c
the stub-function entry address is stored in r4, we should branch to the stub-function with blx r4, not r5.
this patch using to fix the issue of: https://github.com/apache/nuttx/issues/14862
1. impact on armv6-m platform
> armv6-m: fix the incorrect stub-function entry address of svc call

- libs/libc/net/lib_getifaddrs.c
getifaddrs support returning multiple IPv6 addresses
getifaddrs
Tested on vela product
> getifaddrs support returning multiple IPv6 addresses

- include/nuttx/net/netconfig.h
- net/procfs/net_procfs.c
- net/procfs/net_udp.c
- net/procfs/procfs.h
- net/tcp/tcp.h
- net/udp/udp.h
Now (after https://github.com/apache/nuttx/pull/14634 and https://github.com/apache/nuttx/pull/14650) the `HAVE_PFINET(6)_SOCKETS` depends on `NET_TCP/UDP_HAVE_STACK`, which is previously defined in `net/` folder and cannot be included. Considering many places use this check, maybe moving them to `netconfig.h` could be better.
Before: IPv4 + TCP, without ICMP -> `HAVE_PFINET_SOCKETS` is undefined, we cannot use TCP socket (error is `EAFNOSUPPORT`)
After: IPv4 + TCP, without ICMP -> `HAVE_PFINET_SOCKETS` is defined, we can use TCP socket
QEMU with `CONFIG_NET_IPv4` & `CONFIG_NET_TCP` enabled but `CONFIG_NET_ICMP_SOCKET` disabled.
> net: Move NET_TCP/UDP_HAVE_STACK to netconfig.h

- tools/gdb/lists.py
- tools/gdb/macros.py
- tools/gdb/memdump.py
- tools/gdb/requirements.txt
- tools/gdb/stack.py
- tools/gdb/thread.py
- tools/gdb/utils.py
This PR is based on https://github.com/apache/nuttx/pull/14843 to minimize conflicts. I will rebase once that one is merged. The changes are from commit 679e38df843b869207cc6c6701851a1206a2312b.
In this PR, @anjiahao1 introduces a powerful tool to automatically detect memory leak based on offline core dump or online gdb connection. There are follow up commits that optimizes memleak detection speed.
The memfrag from @Gary-Hobson is used to calculate memory fragmentation rate, so we can have a relatively unified number to check the fragmentation rate.
The memmap from @Gary-Hobson  can visually show the memory status.
This PR also includes miscellaneous bug fixes for utils module …
> GDB Plugin Upgrade part2: memory leak detection and other memory tools

- arch/x86/src/Makefile
- arch/x86/src/common/Toolchain.defs
1. Add kasan compilation options
2. Modify the link process to support symbol tables and kasan global variables cross-border detection
> x86-64: Support symbol table and kasan global variables cross-border detection

- tools/gdb/fs.py
- tools/gdb/lists.py
- tools/gdb/memdump.py
- tools/gdb/thread.py
- tools/gdb/utils.py
In this PR, we introduces several fs related tools. 
This PR is based on part1/2 to minimize conflicts. I'll rebase once they are merged. For now please review commits by commits.
New tools added:
1. mount: similar to device side, mount lists all the mount point.
2. `foreach_inode` print all the inode and its information
```
go through each inode and print its structure info
in the form like below:
├── i_name: bin, i_ino: 51
│   i_parent: , i_peer: data, i_child: , i_crefs: 1, i_flags: 3
│   ......(other info)
│   ├── i_name: audio, i_ino: 5
│   │   i_parent: dev, i_peer: binder, i_child: mixer......
```
3. `fdinfo` print all the file opened in each task
```
(gdb) fdinfo
PID: 0 …
```
> GDB Plugin Upgrade part3: fs related tools

- .github/workflows/arch.yml
Presently, Simple x86 PRs will run All CI Checks (across all Architectures), as reported here: https://github.com/apache/nuttx/pull/14885#issuecomment-2492555557
This PR fixes the CI Build Rules, so that Simple x86 PRs will run only One Single CI Job: `other`.
When we create or update a Simple x86 PR: Only CI Job `other` shall be executed.
No impact on other PRs.
We tested the updated Build Rules `arch.yml`:
- Arch x86 PR: Will build `other` only <br> https://github.com/lupyuen5/label-nuttx/actions/runs/11963675871
- Board x86 PR: Will build `other` only <br>  https://github.com/lupyuen5/label-nuttx/actions/runs/11963676750
- Arch x86, Board x86 PR: Will build `other` only <br>  https://github.com/lupyuen5/label-nuttx/actions/runs/11963708940
__Regression Test:__
- Arch x86_64 PR: Will …
> CI: Run CI Job `other` only for Simple x86 PR

- tools/gdb/net.py
- tools/gdb/utils.py
Add network related tool, contributed by @wengzhe 
`netstat`: networks statistics.
New feature.
Tested with qemu.
1. Compile:
```
tools/configure.sh lm3s6965-ek:qemu-flat
```
Make sure `+CONFIG_DEBUG_SYMBOLS_LEVEL="-g3"` is changed to level3.
2. Run
```
qemu-system-arm -semihosting \
-M lm3s6965evb \
-device loader,file=nuttx.bin,addr=0x00000000 \
-nic user,id=user0,hostfwd=tcp::10023-:23 \
-serial mon:stdio -nographic -s
```
3. Connect from GDB
```
gdb-multiarch nuttx -ex "tar rem:1234" -ex "source tools/gdb/__init__.py"
```
4. Test
Connect to telnetd in qemu from host: `telnet localhost 10023`.
Run `netstats` from gdb.
```
(gdb) netstats
IOB:       size    ntotal     nfree …
```
> GDB Plugin Upgrade part4: net related tools

- arch/x86_64/src/Makefile
- arch/x86_64/src/common/Toolchain.defs
Sorry for this commit: 6cd43777c3b6cf6480383a8f0401c976fc4731b3
This is the real x86-64 modification, and that patch is x86
Fortunately, except for the error in the comment, the actual architecture is supported
> x86-64: Added KASan compilation options

- .gitignore
- boards/arm64/imx9/imx93-evk/src/Makefile
- tools/imx9/Config.mk
- tools/imx9/Makefile.host
Fetch fspi header and fcb generation script,
using mkimage generate nor bootable image.
compile bootloader using -mstrict-align
and runtime logs …
> tools/imx9: Add norimage support to bootloader

- fs/littlefs/CMakeLists.txt
- fs/littlefs/Kconfig
- fs/littlefs/Make.defs
Hopefully, It's more user-friendly than the current method, which is just an overridable make variable. It would also help to make some features (and their associated local patches) conditional on littlefs version in future.
Also, update CMakeLists.txt to use the same littlefs version as Makefile.
this changes littlefs version for cmake users.
esp32s3-devkit:toywasm
> fs/littlefs: Add a kconfig to override littlefs version

- .github/workflows/build.yml
You need to disable the msys2 cache from the GitHub action because we moved the Scheduled Merge Jobs to a new  [NuttX Mirror Repo](https://github.com/NuttX/nuttx) and approaching total cache storage limit !!!
[Nuttx caches](https://github.com/apache/nuttx/actions/caches)
[msys2 GitHub Action cache](https://github.com/msys2/setup-msys2?tab=readme-ov-file#cache)
CI
[Github](https://github.com/simbit18/nuttx_test_pr/actions/runs/11974407888)
> build.yml: disable the msys2 cache from the GitHub action

- arch/arm64/include/irq.h
- arch/arm64/src/common/arm64_backtrace.c
- arch/arm64/src/common/arm64_registerdump.c
- include/nuttx/sched.h
arm64: remove up_set_current_regs/up_current_regs
reason:
up_set_current_regs initially had two functions:
1: To mark the entry into an interrupt state.
2: To record the context before an interrupt/exception. If we switch to a new task, we need to store the upcoming context regs by calling up_set_current_regs(regs).
Currently, we record the context in other ways, so the second function is obsolete. Therefore, we need to rename up_set_current_regs to better reflect its actual meaning, which is solely to mark an interrupt.
arm64 arch
ostest
> arm64: remove up_set_current_regs/up_current_regs

- arch/arm64/include/irq.h
- arch/arm64/src/common/arm64_exit.c
- arch/arm64/src/common/arm64_internal.h
- arch/arm64/src/common/arm64_sigdeliver.c
arm64: syscall SYS_switch_context and SYS_restore_context use 0 para
reason:
simplify context switch
sys_call0(SYS_switch_context)
sys_call0(SYS_restore_context)
size nuttx
before 
504644   54968   81085  640697   9c6b9 nuttx
after
504360   54968   81085  640413   9c59d nuttx
size reduce -284
arm64
ostest
> arm64: syscall SYS_switch_context and SYS_restore_context use 0 para

- tools/gdb/nuttxgdb/lists.py
This PR includes minor bug fixes to list iterator and introduced more powerful iteration commands.
1. `foreach list` command now can iterate any type of `list`. E.g
```
(gdb) foreach list -n next &g_msgfree
0: {prev = 0x40286200 <g_msgpool+280>, next = 0x4028628c <g_msgpool+420>}
1: {prev = 0x40286e30 <g_msgfree>, next = 0x40286318 <g_msgpool+560>}
(gdb) foreach list "(struct list_node *) 0x40286e30"
0: {prev = 0x40286200 <g_msgpool+280>, next = 0x4028628c <g_msgpool+420>}
1: {prev = 0x40286e30 <g_msgfree>, next = 0x40286318 <g_msgpool+560>}
(gdb) foreach list g_active_tcp_connections.head -n flink -c "struct tcp_conn_s" -m "sconn"
13:14:07 [1047/1047]
0 @ *(struct tcp_conn_s …
```
> nuttxgdb list function enhancement

- tools/gdb/nuttxgdb/net.py
1. 
Make netstats work without socket import
We may get normal IPv4 address print like 10.10.0.1:5001 and a longer
IPv6 like fc000000000000000000000000000001:5001
2.
Add command 'netcheck' for checks on network stack
No impact.
Tested on qemu using same setup as https://github.com/apache/nuttx/pull/14913. 
Do `telnet localhost 10023` on host to have a real connection to check by this tool.
```
(gdb) netcheck
IOB check: PASS
(gdb)
```
> nuttxgdb net module update

- tools/gdb/nuttxgdb/fs.py
- tools/gdb/nuttxgdb/gcore.py
- tools/gdb/nuttxgdb/macros.py
- tools/gdb/nuttxgdb/memdump.py
- tools/gdb/nuttxgdb/net.py
- tools/gdb/nuttxgdb/profile.py
- tools/gdb/nuttxgdb/stack.py
- tools/gdb/nuttxgdb/thread.py
- tools/gdb/nuttxgdb/utils.py
This PR mainly update the utils module and minor bug fixes.
1. Added `Backtrace` to better handle converting addresses to symbols.
2. Enhancement to `offset_of` and `container_of`, now support string as argumment
3. added helper `sizeof`, both str and gdb.Type are accepted.
4. Added enum function to map C enum to python Enum class
```
in C:
enum color_e {
RED = 1,
GREEN = 2,
};
in python:
COLOR = utils.enum("enum color_e", "COLOR")
print(COLOR.GREEN.value) # --> 2
RED = COLOR(1)
```
6. Added `ArrayIterator` to access array elements
7. Added crash log parsing for `addr2line` command, now you can use `addr2line -f crash.log` or `addr2line -f crash.log -p 123 ` for specified PID. …
> nuttxgdb utils module update

- Documentation/Pipfile
- Documentation/Pipfile.lock
This PR bumps the version of docutils from 0.18.1 to 0.19, as requested by dependabot:
- https://github.com/apache/nuttx/pull/14910
Documentation builds correctly. Dependency on tornado is no longer required after updating to docutils 0.19.
Tested OK by inspecting the Generated HTML at `Documentation/_build/html/components/index.html`
> Documentation: Bump docutils from 0.18.1 to 0.19

- tools/gdb/nuttxgdb/__init__.py
Minor update to gdbinit.
1. Guide user to source `gdb/gdbinit.py` instead of the original `gdb/__init__.py`
2. Ignore commands that has error and continue to register the remaining commands. This normally happen when some modules are disabled.
3. Show backtrace of why the command failed to register.
No.
Tested with qemu arm64.
```
(gdb) source nuttx/tools/gdb/nuttxgdb/__init__.py
Use nuttx/tools/gdb/gdbinit.py instead%
```
Now it will exit and print error message.
Manually introduce an error in fs.py and it can correctly report.
```
Ignore module: fs, error: unterminated string literal (detected at line 33) (fs.py, line 33)
Traceback (most recent call last):
File …
```
> nuttxgdb: add error hint to gdbinit

- tools/gdb/nuttxgdb/debug.py
- tools/gdb/requirements.txt
The `nuttxgdb` is getting more features, we need a better way to debug python code.
In this PR, we include `debugpy` from https://github.com/microsoft/debugpy
Usage:
(gdb) debugpy
Waiting for connection at localhost:5678
In VSCode, add new configuration in launch.
```
{
"name": "Python Debugger: Remote Attach",
"type": "debugpy",
"request": "attach",
"connect": {
"host": "localhost",
"port": 5678
}
}
```
and launch.
No.
Tested on locally.
> gdb/debug: add debugpy to debug python code

- arch/arm/src/goldfish/goldfish_boot.c
- arch/arm/src/qemu/qemu_boot.c
hujun5@hujun5-OptiPlex-7070:~/downloads1/vela_sim/nuttx$ make -j12 chip/qemu_boot.c: In function 'up_cpu_start':
chip/qemu_boot.c:102:3: warning: implicit declaration of function 'sched_note_cpu_start' [-Wimplicit-function-declaration]
102 |   sched_note_cpu_start(this_task(), cpu);
|   ^~~~~~~~~~~~~~~~~~~~
chip/qemu_boot.c:102:24: warning: implicit declaration of function 'this_task' [-Wimplicit-function-declaration]
102 |   sched_note_cpu_start(this_task(), cpu);
|                        ^~~~~~~~~
none
ci
> fix some build error

- include/gcov.h
- libs/libbuiltin/compiler-rt/coverage.c
1. Supports gcc standard output interface "__gcov_dump"
2. Add "__gcov_dump_to_memory" to dump gcov data directly to memory
3. mps/gcov: gcov app is enabled by default
Compile "`boards/arm/mps/mps3-an547/configs/gcov`", find the module that needs code coverage analysis, add the parameter` "-fprofile-instr-generate -fcoverage-mapping"`, run `qemu-system-arm -M mps3-an547 -nographic -kernel ./nuttx/nuttx`, execute the app that calls __llvm_profile_dump or nsh run `"gcov -d /tmp/xxx ",` if you set the dump to memory, read the memory in your own way, such as gdb. If you use the default dump to file, please dump the file to the host, and finally use the …
> Clang/gcov: Enhance clang gcov dump

- drivers/note/note_driver.c
- drivers/note/notelog_driver.c
- drivers/note/notesnap_driver.c
- drivers/segger/note_sysview.c
- fs/procfs/fs_procfscritmon.c
- fs/procfs/fs_procfsproc.c
- include/nuttx/note/note_driver.h
- include/nuttx/sched.h
- include/nuttx/sched_note.h
- sched/Kconfig
- sched/sched/sched_critmonitor.c
- sched/sched/sched_lock.c
- sched/sched/sched_unlock.c
spelling: fix spelling typo premption -> preemption
spelling: fix spelling typo premp -> preemp
N/A
ci-check
> spelling: fix spelling typo premption -> preemption

- arch/risc-v/src/esp32c3/esp_coex_adapter.c
- arch/risc-v/src/esp32c6/esp_coex_adapter.c
- arch/xtensa/src/esp32/esp32_cpustart.c
- arch/xtensa/src/esp32/esp32_wifi_adapter.c
- arch/xtensa/src/esp32s2/esp32s2_wifi_adapter.c
- arch/xtensa/src/esp32s3/esp32s3_cpustart.c
- arch/xtensa/src/esp32s3/esp32s3_wifi_adapter.c
- include/nuttx/spinlock.h
- libs/libc/pthread/pthread_spinlock.c
- mm/mempool/mempool.c
spinlock: use spin_lock_init replace spin_initialize
reason:
1: spin_lock_init and spin_initialize have similar functionalities.
2: spin_lock and spin_unlock should be called in matching pairs.
spinlock
ci ostest
> spinlock: use spin_lock_init replace spin_initialize

- Documentation/guides/gdbwithpython.rst
- Documentation/guides/qemugdb.rst
- Documentation/platforms/risc-v/qemu-rv/boards/rv-virt/index.rst
- Documentation/quickstart/debugging.rst
Now we should load tools/gdb/gdbinit.py script
Update documentation to use correct script.
No.
Documentation locally build pass.
> Documentation: fix nuttxgdb related commands

- fs/littlefs/CMakeLists.txt
- fs/littlefs/Kconfig
- fs/littlefs/Make.defs
fs/littlefs: make CONFIG_FS_LITTLEFS_VERSION include the "v" prefix
To allow other tags/branches like "devel" and even sha256 hash.
littlefs
build tested
(although i haven't tested CMakeFiles.txt locally because i couldn't find a defconfig working on macOS.)
> fs/littlefs: make CONFIG_FS_LITTLEFS_VERSION include the "v" prefix

- arch/risc-v/src/common/espressif/esp_rmt.c
- arch/xtensa/src/common/espressif/esp_rmt.c
common/espressif/esp_rmt.c: In function 'rmt_set_tx_thr_intr_en': common/espressif/esp_rmt.c:654:48: error: passing argument 1 of 'spin_lock_irqsave' makes pointer from integer without a cast [-Werror=int-conversion]
654 |       flags = spin_lock_irqsave(g_rmtdev_common.rmt_spinlock);
|                                 ~~~~~~~~~~~~~~~^~~~~~~~~~~~~
|                                                |
|                                                spinlock_t {aka unsigned char}
/home/hujun5/downloads1/vela_sim/nuttx/include/nuttx/spinlock.h:617:55: note: expected 'volatile spinlock_t *' {aka 'volatile unsigned char *'} but argument is of type 'spinlock_t' {aka 'unsigned char'}
617 | irqstate_t spin_lock_irqsave(FAR volatile spinlock_t *lock)
| …
> fix build error

- arch/arm64/include/irq.h
- arch/arm64/src/common/arm64_schedulesigaction.c
- arch/arm64/src/common/arm64_sigdeliver.c
arm64: change name saved_reg to saved_regs
reason:
saved_regs is more meaningful and used by all other arch
none
ci
> arm64: change name saved_reg to saved_regs

- drivers/note/noterpmsg_driver.c
noterpmsg: Remove enter_critical_section from the sched_note module to avoid recursive calls.
note
ci ostest
> note: Remove enter_critical_section from the sched_note module

- tools/ci/platforms/darwin.sh
- tools/ci/platforms/darwin_arm64.sh
- tools/ci/platforms/linux.sh
- tools/ci/platforms/msys2.sh
- tools/ci/platforms/ubuntu.sh
add toolchains for macOS on Apple Intel
xtensa-esp32s2
xtensa-esp32s3
add toolchains for macOS on Apple Silicon
xtensa-esp32s2
xtensa-esp32s3
add install for ubuntu.sh
xtensa-esp32s2
xtensa-esp32s3
add install for linux.sh
xtensa-esp32s2
xtensa-esp32s3
github macos-13 and macos-14
macOS on Apple Silicon and Intel  esp32s3
```
Configuration/Tool: esp32s3-devkit/cxx
2024-11-25 12:39:41
Cleaning...
Configuring...
Normalize esp32s3-devkit/cxx
================================================================= …
```
> [ci] platforms: added toolchains

- sched/irq/irq_csection.c
use spin_lock_wo_note replace spin_lock in csection
reason:
spin_lock_wo_note/spin_unlock_wo_note  should be called in matching pairs.
This commit fixes the regression from https://github.com/apache/nuttx/pull/13933
leave_critical_section use cpu_irqlock_clear which alse use spin_unlock_wo_note
in https://github.com/apache/nuttx/pull/13933
I overlooked some changes, resulting in a mismatch in spinlock calls
critical section
ci ostest
> use spin_lock_wo_note replace spin_lock in csection

- include/nuttx/spinlock.h
- sched/irq/irq_spinlock.c
spinlock: remove recursive locks with write_lock_irqsave/read_lock_irqsave
reason:
1 There is a similar PR, https://github.com/apache/nuttx/pull/14079,
2 Currently, no one is using recursive locks with write_lock_irqsave/read_lock_irqsave.
3 Nested spinlock is harmful, prone to abuse and leading to a decline in code quality and performance 
4 Nested spinlock is also not available in Linux.
5 In our future plans, nested usage of enter_critical_section and spin_lock_irqsave will also be removed.
spinlock
ci
> spinlock: remove recursive locks with write_lock_irqsave/read_lock_irqsave

- libs/libc/machine/arm/CMakeLists.txt
- libs/libc/machine/arm/Kconfig
- libs/libc/machine/arm/Make.defs
- libs/libc/machine/arm/armv8-r/CMakeLists.txt
- libs/libc/machine/arm/armv8-r/Kconfig
- libs/libc/machine/arm/armv8-r/Make.defs
- libs/libc/machine/arm/armv8-r/arch_elf.c
- libs/libc/machine/arm/armv8-r/gnu/acle-compat.h
- libs/libc/machine/arm/armv8-r/gnu/arch_memchr.S
- libs/libc/machine/arm/armv8-r/gnu/arch_memcpy.S
- libs/libc/machine/arm/armv8-r/gnu/arch_memmove.S
- libs/libc/machine/arm/armv8-r/gnu/arch_memset.S
- libs/libc/machine/arm/armv8-r/gnu/arch_strcmp.S
- libs/libc/machine/arm/armv8-r/gnu/arch_strlen.S
Optimize libc string apis(memcpy/memset/memmove/memchr/strcmp/strlen) with arm32 assembly instruction including vfp and neon. Add arch releated elf parsing
optimize armv8r cortex-r52 libc apis.
armv8r cpu libc apis.
Use arm32 assemble / neon instructions to optimize libc apis (memcpy/memset/memmove/memchr/strcmp/strlen) 
Tested on armv8r cortex-r52 cpu.
> armv8-r/libc: optimize libc string apis with asm

- include/nuttx/streams.h
- libs/libc/hex2bin/lib_hex2bin.c
- libs/libc/misc/lib_kbddecode.c
- libs/libc/misc/lib_slcddecode.c
- libs/libc/stdio/lib_libvscanf.c
- libs/libc/stdio/lib_vsscanf.c
- libs/libc/stream/lib_stdinstream.c
- libs/libc/stream/lib_stdsistream.c
EOF is libc definition, not the stream definition, we should use errno to handle the stream getc EOF case.
As we have lots of backend to support stream, which necessary to get errno.
first find in #14778, casing scanftest break  
at " %4c%n" case.
then scanf use INT_MAX cause meminstream EOF break.
sscanf will do strlen firsttime, and then meminstream.
filestream/blkstream/mtdstream will able to handle the errno.
CI-test, local sim:citest test.
> stream_getc: use lib_stream_eof instead of EOF

- boards/xtensa/esp32s3/esp32s3-devkit/src/esp32s3_bringup.c
Treat return value that greater than zero as succ.
`parse_mtd_partition()` may return value that greater than zero when succ.
e.g: board_spiflash_init() => init_storage_partition() => parse_mtd_partition() 
boards/xtensa/esp32s3
1. Selftest: `esp32s3-devkit:adb` with `CONFIG_TXTABLE_PARTITION` enabled.
2. NuttX CI
> boards/xtensa/esp32s3: Treat return value that greater than zero as succ

- arch/risc-v/src/common/espressif/esp_mcpwm.c
- arch/xtensa/src/common/espressif/esp_mcpwm.c
espressif/mcpwm: fix compile error
continue work of PR #14938
N/A
ci-check
> espressif/mcpwm: fix compile error

- sched/sched/sched_addreadytorun.c
- sched/sched/sched_critmonitor.c
- sched/sched/sched_mergepending.c
- sched/sched/sched_setpriority.c
sched/lockcount: replace all lockcount check to nxsched_islocked_tcb()
replace all lockcount check to nxsched_islocked_tcb()
N/A
ci-check
> sched/lockcount: replace all lockcount check to nxsched_islocked_tcb()

- fs/partition/fs_txtable.c
Panic occured if no txtable was found in last eraseblock of MTD device and `CONFIG_TXTABLE_DEFAULT_PARTITION` was disabled
Backtrace
```
sched_dumpstack
/workspace/nuttx/libs/libc/sched/sched_dumpstack.c:71
dump_assert_info
/workspace/nuttx/sched/misc/assert.c:718
xtensa_user_panic
/workspace/nuttx/arch/xtensa/src/common/xtensa_assert.c:188 (discriminator 1)
xtensa_user
??:?
_xtensa_user_handler
/workspace/nuttx/arch/xtensa/src/common/xtensa_user_handler.S:194
??
??:0
parse_txtable_partition
/workspace/nuttx/fs/partition/fs_txtable.c:136
parse_partition
/workspace/nuttx/fs/partition/fs_partition.c:165
parse_mtd_partition
/workspace/nuttx/fs/partition/fs_partition.c:291
```
fs/partition/txtable:
1. Selftest
2. NuttX CI
> fs/partition/txtable: Fix panic when no txtable was found in last eraseblock

- include/gcov.h
- libs/libbuiltin/libgcc/gcov.c
CC:  gcov.c gcov.c: In function 'gcov_stdout_dump':
gcov.c:146:50: error: passing argument 3 of '__gcov_info_to_gcda' from incompatible pointer type [-Werror=incompatible-pointer-types]
146 |       __gcov_info_to_gcda(info, stdout_filename, stdout_dump, NULL, &arg);
|                                                  ^~~~~~~~~~~
|                                                  |
|                                                  void (*)(const void *, size_t,  void *) {aka void (*)(const void *, long unsigned int,  void *)}
In file included from gcov.c:25:
/mnt/vela/github/NX/nuttx/include/gcov.h:139:44: note: expected 'void (*)(const void *, unsigned int,  void *)' but argument is of type 'void (*)(const void *, size_t,  void *)' {aka 'void (*)(const void *, long unsigned int,  void …
> Fix compilation errors

- drivers/pipes/pipe_common.c
Reverts apache/nuttx#14667 since it breaks the POSIX spec, please see the discussion in the original pr.
> Revert "drivers/pipes: return after short write if buffer is full"

- arch/arm/src/rp23xx/rp23xx_irq.c
- arch/x86_64/src/intel64/intel64_irq.c
sched: replace up_cpu_index with this_cpu
Make this_cpu is arch independent and up_cpu_index do that. In AMP mode, up_cpu_index() may return the index of the physical core.
sched
ci ostest
> sched: replace up_cpu_index with this_cpu

- arch/x86_64/src/intel64/intel64_cpustart.c
- arch/x86_64/src/intel64/intel64_irq.c
- arch/x86_64/intel64: up_disable_irq should work from any CPU
simplify interrupt logic and allow any CPU to disable interrupt, not only CPU that enabled it.
up_disable_irq works from any CPU, not just the one that previously enabled a given interrupt
qemu
> arch/x86_64/intel64: up_disable_irq should work from any CPU

- arch/x86_64/src/intel64/intel64_head.S
- arch/x86_64/src/intel64/intel64_lowsetup.c
- arch/x86_64/src/intel64/intel64_start.c
- arch/x86_64/intel64: fix revoke_low_memory
Fix revoke_low_memory, problem found by Xiangzhen Ouyang.
g_pt_low mapping is removed during revoke_low_memory so we can't access this memory area with 1:1 mapping.
This logic has been broken for a long time, but for some reason it worked without any crash at boot.
fix broken code
qemu and intel HW
> arch/x86_64/intel64: fix revoke_low_memory

- arch/risc-v/src/common/riscv_ipi.h
From the RISV-V Privileged Spec v1.10 (3.1.14 MIP/MIE):
Only the bits corresponding to lower-privilege software interrupts (USIP, SSIP), timer interrupts (UTIP, STIP), and external interrupts (UEIP, SEIP) in mip are writable through this CSR address; the remaining bits are read-only.
Thus, it is futile to write to the M-mode status bit via the CSR, only access via RISCV_IPI is valid.
RISC-V SMP only.
rv-virt:smp64
rv-virt:smp
rv-virt:ksmp64
> riscv/riscv_ipi.h: Do not write to CSR_MIP.MSIP as it is read-only

- arch/arm64/src/imx9/imx9_flexspi_nor.c
libc memcpy cannot access fspi memory space correctly remove unnecessary debugassert and cache operations
and runtime logs from before and after …
> arch/arm64/imx9/imx9_flexspi: Replace memcpy by while loop

- arch/arm64/src/imx9/imx9_edma.c
Avoid spurious interrupts on reboot
On warm reboot it is possible that there is old interrupt pending.
> arch/arm64/imx9: Clear DMA channel interrupts on init

- arch/arm/src/armv7-a/arm_smpcall.c
- arch/arm/src/armv7-r/arm_smpcall.c
- arch/arm64/src/common/arm64_smpcall.c
- arch/x86_64/src/intel64/intel64_smpcall.c
remove redundant scheduling records
reason:
Since the scheduling records have already been moved to the interrupt exit in this submission, we need to delete the original records' locations. This commit fixes the regression from https://github.com/apache/nuttx/pull/13651
scheduling records
ci ostest
> remove redundant scheduling records

- arch/xtensa/src/esp32s3/esp32s3_lowputc.c
esp32s3: don't clear pending interrupts on eg. up_putc
Fixes https://github.com/apache/nuttx/issues/14872
esp32s3
esp32s3-devkitc
> esp32s3: don't clear pending interrupts on eg. up_putc

- tools/gdb/nuttxgdb/rpmsg.py
(gdb)rpmsg_service
g_rpmsg_cb:
rpmsg_cb_s at        ns_match                                 ns_bind
-------------        --------                                 -------
0xf4e00ac0           0x44708225 <rpmsg_rtc_server_ns_match>   0x4470874c <rpmsg_rtc_server_ns_bind>
0xf4e27b20           0x440c8fd6 <syslog_rpmsg_ns_match>       0x440c966a <syslog_rpmsg_ns_bind>
0xf4e27af0           0x0                                      0x0
g_rpmsg:
Endpoint at          Name                 local Addr   dest Addr    cb                                       ns_bound_cb                              ns_unbind_cb
-----------          ----                 ----------   ---------    --                                       -----------                              ------------
0xf2302ac0           NS …
> nuttxgdb/rpmsg.py:dump rpmsg_service message

- arch/arm64/src/imx9/imx9_boot.c
MMU init must be after ddrinit.
Initialization order is wrong, mmu init must be after dram init.
> arch/arm64/imx9: Boot, move mmu init to correct place

- arch/arm64/src/common/arm64_exit.c
- arch/arm64/src/common/arm64_sigdeliver.c
- arch/arm64/src/common/arm64_syscall.c
arm64: remove g_running_tasks[this_cpu()] = NULL
reason:
We hope to keep g_running_tasks valid forever.
arm64
ci ostest
> arm64: remove g_running_tasks[this_cpu()] = NULL

- drivers/lcd/Kconfig
- drivers/lcd/st7789.c
ST7789 fills the display with 0xffff color during its initialization. This color may or may not be overwritten by a higher layer (framebuffer or lcd driver for example). The color remains on the display until application UI is started if not overwritten by the higher layer before.
This commit adds configuration option `LCD_ST7789_DEFAULT_COLOR` that allows to set the default background color. This may avoid shining display with, for example, white color for an extensive amount of time. The default value is set to `0xffff` previously hard-coded in the driver, therefore current implementations will not notice the change.
New configuration option, none to current implementations.
Tested with SPI connected ST7789 on SAMv7 MCU based custom board.
> st7789: add configuration option to set default background color

- Documentation/platforms/arm/mps/boards/mps3-an547/index.rst
mps3an547 doc update
In the new version of QEMU (9.20), the UART RX interrupt and TX interrupt have been swapped. Adjustments need to be made using menuconfig.
see it https://github.com/qemu/qemu/commit/5a558be93ad628e5bed6e0ee062870f49251725c
noting
use latest qemu
> mps3an547 doc update

- arch/arm/include/arm/irq.h
- arch/arm/include/armv7-a/irq.h
- arch/arm/include/armv7-r/irq.h
- arch/arm/include/armv8-r/irq.h
- arch/arm/include/tlsr82/irq.h
- arch/arm/src/common/arm_initialize.c
- arch/arm/src/common/arm_internal.h
arm/isr: move up_set_interrupt_context() to chip define
up_set_interrupt_context() is chip specific implement, move this function to correct place
N/A
ci-check
> arm/isr: move up_set_interrupt_context() to chip define

- arch/arm64/src/cmake/Toolchain.cmake
They should be a relationship of choice:
ifeq ($(CONFIG_ARCH_CORTEX_A53),y)
ARCHCPUFLAGS += -mcpu=cortex-a53
else ifeq ($(CONFIG_ARCH_CORTEX_A55),y)
ARCHCPUFLAGS += -mcpu=cortex-a55
else ifeq ($(CONFIG_ARCH_CORTEX_A57),y)
ARCHCPUFLAGS += -mcpu=cortex-a57
else ifeq ($(CONFIG_ARCH_CORTEX_A72),y)
ARCHCPUFLAGS += -mcpu=cortex-a72
else ifeq ($(CONFIG_ARCH_CORTEX_R82),y)
ARCHCPUFLAGS += -mcpu=cortex-r82
else ifeq ($(CONFIG_ARCH_ARMV8A),y)
ARCHCPUFLAGS += -march=armv8-a
else ifeq ($(CONFIG_ARCH_ARMV8R),y)
ARCHCPUFLAGS += -march=armv8-r
endif
what Host was used for build (OS, CPU, compiler, …
> arm64/toolchain: Cmake alignment makefile writing

- arch/xtensa/include/irq.h
- arch/xtensa/src/common/xtensa_assert.c
- arch/xtensa/src/common/xtensa_backtrace.c
- arch/xtensa/src/common/xtensa_initialize.c
- arch/xtensa/src/common/xtensa_irqdispatch.c
- arch/xtensa/src/common/xtensa_registerdump.c
reason:
up_set_current_regs initially had two functions:
1: To mark the entry into an interrupt state.
2: To record the context before an interrupt/exception. If we switch to a new task, we need to store the upcoming context regs by calling up_set_current_regs(regs).
Currently, we record the context in other ways, so the second function is obsolete. Therefore, we need to rename up_set_current_regs to better reflect its actual meaning, which is solely to mark an interrupt.
xteansa
ci ostest
> xtensa: remove up_set_current_regs/up_current_regs

- arch/renesas/src/rx65n/Kconfig
- boards/Kconfig
- include/nuttx/board.h
- include/nuttx/streams.h
- libs/libc/stream/lib_blkoutstream.c
- libs/libc/stream/lib_mtdoutstream.c
- sched/init/nx_bringup.c
- sched/misc/assert.c
- sched/misc/coredump.c
Pervious coredump to device based on blk geo information, and not easy to extend,
we changed it to seek api, so the coredump to device should more common, and also possible to mtd directly.
for the small device should be more effeciency.  As we don't have to use blk/bch/ftl/mtd. both code size and memory will be decreasd.
Also as we removed the geo information requirments, the alloc of g_blockinfo can be removed.
should work with 
https://github.com/apache/nuttx-apps/pull/2871
if want using coredump to blk/mtd -> reboot -> restore to filesystem -> adb/ymodem/.. this kind of workflow.
Kept the compatible with 
```C
board_crashdump
```
API  by BOARD_CRASHDUMP_CUSTOM, and it's a choice which exclusive with coredump syslog/blk/mtd.
Should compatible with the current running project/defconfig. …
> crashdump change to choice, add coredump to mtd support based on mtdout stream.

- arch/risc-v/src/mpfs/Kconfig
- arch/risc-v/src/mpfs/Make.defs
- arch/risc-v/src/mpfs/mpfs_head.S
- arch/risc-v/src/mpfs/mpfs_start.c
rmpfs IPI (Inter-processor Interrupts) are not cleared at boot currently. It's possible they're set at boot time, which then breaks the boot logic; harts1-4 should stay at wfi loop until they're released by an IPI. 
In addition, clocks don't need to be reset if they're already set. Let the use configure whether the system clocks are already set or not.
If there's a chain of NuttX OS:es, for example, one NuttX that jumps to the next, the IPI fired at the 1st NuttX will make the follow-up NuttX proceed before it's released. Thus, clear the IPIs in like manner the interrupts are turned off at boot.
Various mpfs based products with more than one NuttX OSs following each other. The 1st one sets the clokcs, while the 2nd doesn't alter them.
> MPFS boot enhancements

- arch/arm/src/cxd56xx/cxd56_clock.c
cxd56xx: use small lock in arch/arm/src/cxd56xx/cxd56_clock.c
cxd56xx
ci
> cxd56xx: use small lock in arch/arm/src/cxd56xx/cxd56_clock.c

- arch/arm64/src/common/arm64_syscall.c
arm64: change some format
fix the comment in https://github.com/apache/nuttx/pull/14980
arm64
ci ostest
> arm64: change some format

- arch/arm/src/nrf91/nrf91_modem_gnss.c
- drivers/sensors/fakesensor_uorb.c
- drivers/sensors/gnss_uorb.c
- include/nuttx/sensors/gnss.h
Supports setting `nbuffer` for each gnss topic separately to avoid resource waste.
- drivers/sensors/gnss: Different nbuffer for each topic
- nrf91: Support using different nbuffer for each topic
/sensors/gnss
nrf91 updated.
NuttX CI
> drivers/sensors/gnss: Different nbuffer for each topic

- drivers/usbmisc/Kconfig
- drivers/usbmisc/Make.defs
- drivers/usbmisc/stusb4500.c
- include/nuttx/usb/stusb4500.h
Right now it is only possible to change the delivered power on the fly by
1. selecting PDO2 slot
2. write to POO2
3. renegotiate power by sw reset command
Create a basic driver to negotiate power delivery with walladapter using STM STUSB4500 chip.
This is a standalone driver that does not change any other code. It may be selected, or not via kconfig.
New feature. No impact to any existing user or application expected.
Tested on custom board.
> draft driver for STUSB4500

- libs/libc/stdio/lib_puts.c
`puts("");` did not print a newline. The standard
behavior is to print a newline even if the string
is empty.
From `man 3 puts` on Linux:
> puts() writes the string s and a trailing newline to stdout.
Tests that have `puts("")` may fail if they compare stdout against an expected result.
`sim:nsh`
```c
puts("");
```
Should print a newline to `stdout`. Currently, nothing is printed.
Edit: Only an issue for the `CONFIG_FILE_STREAM` implementation. When disabled, a newline is included correctly.
> libc/puts: newline was omitted for empty string

- arch/arm/src/imxrt/imxrt_serial.c
imxrt_serial: use small lock in arch/arm/src/imxrt/imxrt_serial.c
imxrt_serial
ci ostest
> imxrt_serial: use small lock in arch/arm/src/imxrt/imxrt_serial.c

- arch/xtensa/src/common/xtensa_exit.c
- arch/xtensa/src/common/xtensa_irqdispatch.c
xtensa: remove g_running_tasks[this_cpu()] = NULL
reason:
We hope to keep g_running_tasks valid forever.
xtensa
esp32s3-devkit:smp
ci ostest
> xtensa: remove g_running_tasks[this_cpu()] = NULL

- drivers/video/fb.c
Reported by code static check:
```bash
overflow_const: Expression i - 1UL, which is equal to 18446744073709551615, where i is known to be equal to 0, underflows the type that receives it, an unsigned integer 64 bits wide.
```
Use `ssize_t` type to preserve sign.
None.
sim/fb
> video/fb: fix integer overflow issue

- arch/arm/src/max326xx/max32660/max32660_wdt.c
max32660_wdt: use small lock in arch/arm/src/max326xx/max32660/max32660_wdt.c
reason:
we plan to remove all instances of spin_lock_irqsave(NULL)
max32660_wdt
ci
> max32660_wdt: use small lock in arch/arm/src/max326xx/max32660/max32660_wdt.c

- mm/mm_heap/mm_foreach.c
- tools/gdb/gdbinit.py
- tools/gdb/nuttxgdb/memleak.py
- tools/gdb/nuttxgdb/mm.py
- tools/gdb/nuttxgdb/thread.py
1. Unload all existing nuttxgdb modules when souce gdbinit.py. This allows to make changes in .py take effect immediately.
2. Fix memdump busy loop when nodesize is zero due to corruption. This will happen on C code too.
3. Fix thread command. Make sure pid is a valid number and take task that is running into consideration when fetch registers.
Mainly bug fix. No impact.
Tested on qemu: `tools/configure.sh lm3s6965-ek:qemu-flat`.
Make sure g3 is used: `+CONFIG_DEBUG_SYMBOLS_LEVEL="-g3"` 
Turn on `+CONFIG_DEBUG_MM=y` to use memdump.
```
qemu-system-arm -semihosting \                      -M lm3s6965evb \ …
```
> nuttxgdb minor fix

- arch/arm/src/samv7/sam_us.c
EEFC read sequence requires read length in words instead of bytes, therefore bytes given by the user has to be recalculated to words. The calculation however had a mistake in brackets and was just adding 1 to buflen instead of recalculating it to 4 byte words. This caused global array `g_page_buffer` to overflow for some reads.
This fixes the calculation.
Read sequence now uses correct number of words to be read, avoiding potential overflow in `g_page_buffer` array.
Tested on custom SAMv7 board. Previous overflow was causing an inconsistency in affecting other global variables.
> samv7: fix bytes to words calculation in user signature read

- CMakeLists.txt
- cmake/nuttx_add_romfs.cmake
1.make the generation sequence of etc romfs no longer bound to the board 
unify all add_raws calls after traversing all directories.
```
process_all_directory_romfs()
```
2.RCRAWS RCSRCS can be added from any directory
3.enable dynamic files, files generated during the compilation process,
and ensure the correct time order
```
add_dynamic_rcraws(SRCS dyn_file DEPENDS gen_dyn_file_target)
```
In order to be compatible with the old `nuttx_add_romfs`, we retain `nuttx_add_romfs`.
If you use this enhancement method, please **do not call nuttx_add_romfs**
Use `add_board_rcsrcs` and `add_board_rcraws` instead
custom board build pass
> cmake(enhance):Enhance romfs so that RAWS files can be added in any location

- arch/xtensa/src/common/xtensa.h
- arch/xtensa/src/common/xtensa_exit.c
- arch/xtensa/src/common/xtensa_sigdeliver.c
- arch/xtensa/src/common/xtensa_swint.c
- arch/xtensa/src/common/xtensa_switchcontext.c
- arch/xtensa/src/esp32/esp32_cpustart.c
- arch/xtensa/src/esp32s3/esp32s3_cpustart.c
xtensa: syscall SYS_switch_context and SYS_restore_context use 0 para
reason:
simplify context switch
sys_call0(SYS_switch_context)
sys_call0(SYS_restore_context)
size nuttx
before
187620    1436  169296  358352   577d0 nuttx
after
187576    1452  169280  358308   577a4 nuttx
size reduce -44
xtensa
ci ostest 
esp32s3-devkit:smp
> xtensa: syscall SYS_switch_context and SYS_restore_context use 0 para

- arch/risc-v/include/irq.h
- arch/risc-v/src/common/riscv_backtrace.c
- arch/risc-v/src/common/riscv_doirq.c
- arch/risc-v/src/common/riscv_exception.c
- arch/risc-v/src/common/riscv_initialize.c
- arch/risc-v/src/common/riscv_registerdump.c
- arch/risc-v/src/common/supervisor/riscv_perform_syscall.c
reason:
up_set_current_regs initially had two functions:
1: To mark the entry into an interrupt state.
2: To record the context before an interrupt/exception. If we switch to a new task, we need to store the upcoming context regs by calling up_set_current_regs(regs).
Currently, we record the context in other ways, so the second function is obsolete. Therefore, we need to rename up_set_current_regs to better reflect its actual meaning, which is solely to mark an interrupt.
riscv
ci ostest
> riscv: remove up_set_current_regs/up_current_regs

- arch/arm/src/stm32h5/hardware/stm32h5xxx_spi.h
This file is heavily based on the STM32H7 implementation. CFG1_BPASS and UDRCFG were the main differences.
This file is essentially a copy of stm32h7x3xx_spi.h. Other changes include changing the STM32_SPI_CLK_MAX to 120 MHz, removed CR2_TSER definition, modified CFG1_UDRCFG bits, added CFG1_BPASS, added CFG2 RDIOM and RDIOP bits, removed TSERF bits, added I2S definitions.  
This will only impact STM32H5 boards. 
No testing yet. The STM32H563 and STM32H743 reference manuals were compared. Differences noted above and implemented in the H5 SPI Hardware file.
> First commit of STM32H5 SPI Hardware file.

- arch/arm/src/stm32h5/hardware/stm32_fdcan.h
Adding the STM32H5 FDCAN Hardware definitions. The register set is identical to the STM32G4. No major changes other than changing G4 to H5 and removing ifdef requirement for STM32G4.
Hardware definitions of the FDCAN registers for the STM32H5. The implementation is identical to the STM32G4 and that will be used as a base for all upcoming STM32H5 FDCAN development. 
STM32H5 products only. 
No testing. Compared the reference manuals for the STM32G474RE with the STM32H563ZI. Other than the number of FDCAN interfaces, the register sets are identical. More changes may come with more development of the FDCAN driver.
> Add STM32H5 FDCAN Hardware File

- include/nuttx/lib/float.h
* float.h: Define FLT_ROUNDS if not defined by toolchain previously
This value is necessary to build third-party applications on NuttX.
If not defined previously by the toolchain, define it at NuttX's `lib/float.h`.
None for current NuttX's applications. Enables building third-party apps that rely on this macro.
Internal CI testing + NuttX's CI
> float.h: Define FLT_ROUNDS if not defined by toolchain previously

- drivers/can/can_sender.c
The feature of preventing the same ID frame rotation should be done in the lowerhalf or hardware, otherwise it may cause some problems. The CAN protocol stack only ensures that message is written into the hardware in the order of application layer packets, and does not care hardware sending order. This patch just remove this feature from CAN stack.
When the application layer sends frames faster than Hardware and the can_id of frames is the same, the CAN protocol stack will directly hand over frames to Hardware and no longer prevent it from being sent.
The application layer sends CAN frames with same can_id, constructs a scenario where the sending queue is full, and manually adds log information to record the frame in sending queue. Print the frame.can_id information for each frame as …
> com/can: Remove unnecessary judgment logic

- arch/arm/src/cxd56xx/cxd56_nxaudio_src.c
cxd56xx: use small lock in arch/arm/src/cxd56xx/cxd56_nxaudio_src.c
reason:
We hope to remove all instances of spin_lock_irqsave(NULL). Improve performance.
cxd56xx
ci ostest
> cxd56xx: use small lock in arch/arm/src/cxd56xx/cxd56_nxaudio_src.c

- arch/risc-v/src/cmake/platform.cmake
- arch/tricore/src/cmake/platform.cmake
* libm: Do not link the toolchain's libm unless explicitly selected
Fix CMake-based build system to include the toolchain's libm only when `CONFIG_LIBM_TOOLCHAIN` is selected. Before this PR, if the user selected `CONFIG_LIBM_NEWLIB`, for instance, the build system would still link the toolchain's libm functions instead of the ones provided by newlib.
Fix error of not using newlib's libm.
Internal CI testing + rv-virt:nsh.
To test it using `rv-virt:nsh` (`cmake -B build -DBOARD_CONFIG=rv-virt:nsh -GNinja`), enable `CONFIG_LIBM_NEWLIB` and use the following application:
```
nooptimiziation_function
{
double x = 1.0;
double y = 2.0;
double z = 3.0;
double result = fma(x, y, z);
printf("result: %f\n", result);
return 0;
}
```
Build with CMake (`cmake …
> libm: Do not link the toolchain's libm unless explicitly selected

- arch/arm64/src/cmake/platform.cmake
- arch/xtensa/src/cmake/platform.cmake
This PR applies the same changes of https://github.com/apache/nuttx/pull/15036 for other architectures.
* libm: Do not link the toolchain's libm unless explicitly selected
Fix CMake-based build system to include the toolchain's libm only when `CONFIG_LIBM_TOOLCHAIN` is selected. Before this PR, if the user selected `CONFIG_LIBM_NEWLIB`, for instance, the build system would still link the toolchain's libm functions instead of the ones provided by newlib.
Fix error of not using newlib's libm.
Internal CI testing + rv-virt:nsh.
To test it using `rv-virt:nsh` (`cmake -B build -DBOARD_CONFIG=rv-virt:nsh -GNinja`), enable `CONFIG_LIBM_NEWLIB` and use the following application:
```
nooptimiziation_function
{
double x = 1.0;
double y = 2.0;
double z = 3.0; …
```
> libm: Do not link the toolchain's libm unless explicitly selected [2]

- arch/arm/src/arm/arm_doirq.c
- arch/arm/src/armv7-a/arm_doirq.c
- arch/arm/src/dm320/dm320_decodeirq.c
- arch/arm/src/imx1/imx_decodeirq.c
- arch/arm/src/lpc31xx/lpc31_decodeirq.c
- arch/arm64/src/common/arm64_doirq.c
- arch/avr/src/avr32/avr_doirq.c
- arch/hc/src/common/hc_doirq.c
- arch/mips/src/mips32/mips_doirq.c
- arch/mips/src/pic32mx/pic32mx_decodeirq.c
- arch/mips/src/pic32mz/pic32mz_decodeirq.c
- arch/misoc/src/lm32/lm32_doirq.c
- arch/misoc/src/minerva/minerva_doirq.c
- arch/renesas/src/common/renesas_doirq.c
- arch/risc-v/src/common/riscv_doirq.c
- arch/risc-v/src/common/supervisor/riscv_perform_syscall.c
- arch/sparc/src/sparc_v8/sparc_v8_doirq.c
- arch/tricore/src/common/tricore_doirq.c
- arch/x86/src/qemu/qemu_handlers.c
- arch/x86_64/src/intel64/intel64_handlers.c
- arch/xtensa/src/common/xtensa_irqdispatch.c
- arch/z80/src/common/z80_doirq.c
- sched/addrenv/addrenv.c
Ensure that the transmission parameter of addrenv_switch is not NULL
reason:
avoid obtaining this_task multiple times.
addrenv
ci ostest
> addrenv: Ensure that the transmission parameter of addrenv_switch is not NULL

- drivers/timers/arch_alarm.c
- drivers/timers/arch_timer.c
- include/nuttx/arch.h
drivers/timers: export arch timer api to support higher resolution
Before:
`[  384.149000] [CPU0] [ 5] Hello World!`
After:
`[  384.149947] [CPU0] [ 5] Hello World!`
N/A
ci-check
> drivers/timers: export arch timer api to support higher resolution

- arch/arm/src/lc823450/lc823450_symbols.ld
- The file includes symbol information provided by ON Semiconductor.
- The license information is the same as lc823450_sdc.c
- None
- lc823450-xgevk:rndis (build only)
> arch: lc823450: Add missing license info to lc823450_symbols.ld

- drivers/virtio/virtio-mmio.c
In the source code of qemu or linux, there is a check for the virtio version
```
/* Check device version */
priv->version = readl(priv->base + VIRTIO_MMIO_VERSION);
if (priv->version < 1 || priv->version > 2) {
debug("(%s): version %d not supported!\n",
udev->name, priv->version);
return 0;
}
/* Check device ID */
uc_priv->device = readl(priv->base + VIRTIO_MMIO_DEVICE_ID);
if (uc_priv->device == 0) {
/*
* virtio-mmio device with an ID 0 is a (dummy) placeholder
* with no function. End probing now with no error reported.
*/
return 0;
}
```
what Host was used for build (OS, CPU, …
> virtio: Add virtio version check

- Kconfig
- arch/tricore/src/common/ToolchainGnuc.defs
- arch/tricore/src/common/ToolchainTasking.defs
- arch/x86/src/common/Toolchain.defs
- tools/D.defs
- tools/Rust.defs
- tools/Swift.defs
> debug symbol level: Use config instead

- arch/avr/src/avr/avr_doirq.c
- arch/avr/src/avr32/avr_doirq.c
- arch/hc/src/common/hc_doirq.c
- arch/or1k/src/common/or1k_doirq.c
- arch/renesas/src/common/renesas_doirq.c
- arch/sim/src/sim/sim_doirq.c
- arch/x86/src/qemu/qemu_handlers.c
- arch/x86_64/src/intel64/intel64_handlers.c
- arch/xtensa/src/common/xtensa_assert.c
- arch/z16/src/common/z16_doirq.c
- arch/z16/src/z16f/z16f_sysexec.c
- arch/z80/src/common/z80_doirq.c
remove redundant judgments *running_task != NULL
reason:
In irq, g_running_tasks is always valid.
arch
ci ostest
> remove redundant judgments *running_task != NULL

- arch/arm/src/common/Toolchain.defs
- arch/xtensa/src/esp32/Kconfig
- include/nuttx/atomic.h
This PR fixed EPS32 issue after enable https://github.com/apache/nuttx/pull/14465
Use arch atomic when enable iram heap.
S32C1I instructions may target cached, cache-bypass, and data RAM memory locations. S32C1I instructions are not permitted to access memory addresses in data ROM, instruction memory or the address region allocated to the XLMI port. Attempts to direct the S32C1I at these addresses will cause an exception.
ESP32 iram heap
esp32-devkit:sotest boot success
> arch/xtensa: use arch atomic when enable iram heap

- arch/risc-v/src/common/riscv_doirq.c
- arch/risc-v/src/common/supervisor/riscv_perform_syscall.c
This commit fixes the regression from https://github.com/apache/nuttx/pull/14984
riscv
ostest rv-virt:knsh
> riscv: Some judgments are missing

- arch/arm64/src/Toolchain.defs
arm64/toolchain: Fix toolchain judgment after opening lto
> arm64/toolchain: Fix toolchain judgment after opening lto

- boards/arm64/qemu/qemu-armv8a/scripts/dramboot.ld
```
CPP:  /mnt/vela/github/NX/nuttx/boards/arm64/qemu/qemu-armv8a/scripts/dramboot.ld-> /mnt/vela/github/NX/nutLD: nuttx
Please update the link script, section ['.kasan.global'] cannot be found
`.eh_frame' referenced in section `.text.frame_dummy' of /mnt/vela/github/Toolchains/arm64-gcc-13/bin/../lib/gcc/aarch64-none-elf/13.2.1/crtbegin.o: defined in discarded section `.eh_frame' of /mnt/vela/github/Toolchains/arm64-gcc-13/bin/../lib/gcc/aarch64-none-elf/13.2.1/crtbegin.o
`.eh_frame' referenced in section `.text.frame_dummy' of /mnt/vela/github/Toolchains/arm64-gcc-13/bin/../lib/gcc/aarch64-none-elf/13.2.1/crtbegin.o: defined in discarded section `.eh_frame' of /mnt/vela/github/Toolchains/arm64-gcc-13/bin/../lib/gcc/aarch64-none-elf/13.2.1/crtbegin.o
```
*Update this section, where …
> arm64/lto: Fix link error after opening lto

- drivers/net/netdev_upperhalf.c
- include/nuttx/net/netdev_lowerhalf.h
- wireless/bluetooth/bt_conn.c
Change netdev_lower_quota_load to macro
netdev
sim:citest pass
> drivers/net: change netdev_lower_quota_load to macro

- mm/mm_gran/mm_grantable.c
The search algorithm does not work with the ctz approach at all, if there is a free range of granules that does not fit a specific allocation (i.e. the granule allocation is fragmented) it will cause an infinite loop as the algorithm will try to find free space from the same (free) starting granule, causing an infinite loop.
The clz approach works for all cases, it will find the last used granule and the search will continue from the next free granule.
Also, offsetting a full GAT must be sizeof(gat[0] - 1), which is 31 in this case. The reason is that the upper level search function increments the value by +1.
Impact is on granule allocator only. The patch fixes an infinite loop caused by memory fragmentation.
IMX9
> mm_grantable.c: Fix infinite loop due to memory fragmentation

- tools/kasan_global.py
../../../mm/kasan/global.c:58:44: error: type of 'g_global_region' does not match original declaration [-Werror=lto-type-mismatch]
58 | extern const struct kasan_global_region_s *g_global_region[];
|                                            ^
kasan_globals.tmp:3:21: note: 'g_global_region' was previously declared here
3 | const unsigned long g_global_region[] = {
|                     ^
lto1: all warnings being treated as errors
and runtime logs …
> kasan/globals: fix compile error

- drivers/audio/wm8776.c
- drivers/audio/wm8776.h
wm8776: use small lock in drivers/audio/wm8776.c
reason:
wm8776
ci
> wm8776: use small lock in drivers/audio/wm8776.c

- libs/libxx/libcxxabi/CMakeLists.txt
> libcxxabi: Soft link the libcxxabi header file to nuttx/include

- Documentation/platforms/arm/goldfish/goldfish_timer.rst
- arch/arm/src/arm/arm_syscall.c
- arch/arm/src/armv7-r/arm_syscall.c
- arch/arm/src/armv8-r/arm_syscall.c
- arch/arm/src/goldfish/goldfish_timer.c
- arch/arm/src/moxart/moxart_16550.c
- arch/arm/src/s32k1xx/s32k1xx_flexio_i2c.c
- arch/arm/src/samv7/sam_lin_sock.c
- arch/arm64/src/goldfish/goldfish_rtc.c
- arch/risc-v/src/common/espressif/esp_temperature_sensor.c
- arch/risc-v/src/common/espressif/esp_timer.c
- arch/sim/src/sim/sim_heap.c
- arch/xtensa/src/common/espressif/esp_temperature_sensor.c
- arch/xtensa/src/esp32/esp32_spiram.c
- arch/xtensa/src/esp32s3/esp32s3_spiram.c
- boards/arm/mps/mps3-an547/src/mps3_bringup.c
- boards/arm/rp23xx/common/src/rp23xx_uniqueid.c
- libs/libc/machine/arm64/arch_elf.c
- libs/libc/machine/sim/arch_elf64.c
since these arch doesn't distinguish between near and far pointers
minor code refactor only
ci
> Remove FAR from 32/64bit arch

- arch/arm/include/armv7-a/cp15.h
- arch/arm/include/armv7-a/irq.h
- arch/arm/include/armv7-r/cp15.h
- arch/arm/include/armv7-r/irq.h
- arch/arm/include/armv8-r/cp15.h
- arch/arm/include/armv8-r/irq.h
- arch/arm/src/armv7-a/arm_scu.c
- arch/arm/src/armv7-r/arm_scu.c
This is continue work of https://github.com/apache/nuttx/pull/13726
We can utilize percpu storage to hold information about the current running task. If we intend to implement this feature, we would need to define two macros that help us manage this percpu information effectively.
up_this_task: This macro is designed to read the contents of the percpu register to retrieve information about the current running task.This allows us to quickly access
task-specific data without having to disable interrupts, access global variables and obtain the current cpu index.
up_update_task: This macro is responsible for updating the contents of the percpu register.It is typically called during
initialization or when a context switch occurs to ensure that the percpu register reflects the information of …
> armv7-a/armv7-r/armv8-r: percpu reg store this_task

- drivers/virtio/virtio-mmio.c
CC:  virtio/virtio-mmio.c virtio/virtio-mmio.c: In function 'virtio_mmio_config_virtqueue': virtio/virtio-mmio.c:346:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
346 |       addr = (uint64_t)kasan_reset_tag((FAR void *)vq->vq_ring.desc);
|              ^
virtio/virtio-mmio.c:350:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
350 |       addr = (uint64_t)kasan_reset_tag((FAR void *)vq->vq_ring.avail);
|              ^
virtio/virtio-mmio.c:354:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
354 |       addr = (uint64_t)kasan_reset_tag((FAR void *)vq->vq_ring.used)
build process, hardware, documentation, security, …
> virtio: fix compile error

- fs/tmpfs/fs_tmpfs.c
fs/tmpfs: Skip any slash at the beginning of relpath
`tmpfs_stat()` fails when relpath start with slash.
Host
```
$ adb -s 1234 pull /tmp/subdir
adb: warning: skipping special file '/tmp/subdir/uname' (mode = 0o0)
/tmp/subdir/: 0 files pulled. 1 file skipped.
```
Device
```
state_process_list (411): stat failed </tmp/subdir//uname> -1 22
```
Ref: https://github.com/apache/nuttx/blame/master/libs/libc/stdlib/lib_realpath.c#L111
tmpfs
1. Selftest with `esp32s3-devkit:adb` with `TMPFS` enabled.
2. NuttX CI
> fs/tmpfs: Skip any slash at the beginning of relpath

- boards/sim/sim/sim/CMakeLists.txt
avoid SIM compilation post build issues on other platforms
same fix for build with make
https://github.com/apache/nuttx/pull/14800
mpact on user: No changes to user-facing functionality
Github
https://github.com/simbit18/nuttx_test_pr/actions/runs/12234376258/job/34123525452
> build(CMAKE): fix pac sim elf ONLY in Linux platform

- fs/tmpfs/fs_tmpfs.c
`tmpfs_stat()` fails when relpath start with slash.
Log
Host
$ adb -s 1234 pull /tmp/subdir
adb: warning: skipping special file '/tmp/subdir/uname' (mode = 0o0)
/tmp/subdir/: 0 files pulled. 1 file skipped.
Device
state_process_list (411): stat failed </tmp/subdir//uname> -1 22
Ref: https://github.com/apache/nuttx/blame/master/libs/libc/stdlib/lib_realpath.c#L111
tmpfs
Selftest with esp32s3-devkit:adb with TMPFS enabled.
NuttX CI
> {bp-15077} fs/tmpfs: Skip any slash at the beginning of relpath

- include/mqueue.h
The Open Group Base Specification IEEE Std 1003.1-2024 states that
> The `<mqueue.h>` header shall define `O_RDONLY`, `O_WRONLY`, `O_RDWR`, `O_CREAT`, `O_EXCL`, and `O_NONBLOCK` as described in [`<fcntl.h>`](https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/fcntl.h.html).
_https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/mqueue.h.html_
It also states that:
> The `<mqueue.h>` header shall define the `struct timespec` structure as described in [`<time.h>`](https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/time.h.html).
_https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/mqueue.h.html_
The way the `mqueue.h` include file is defined right now …
> [POSIX][Bug] `mqueue.h`: Include file does not conform the standard

- arch/arm/src/max326xx/max32660/max32660_rtc.c
max32660_rtc: use small lock in arch/arm/src/max326xx/max32660/max32660_rtc.c
reason:
max32660_rtc
ci
> max32660_rtc: use small lock in arch/arm/src/max326xx/max32660/max32660_rtc.c

- arch/arm/src/s32k3xx/s32k3xx_serial.c
reason:
s32k3xx_serial: use small lock in arch/arm/src/s32k3xx/s32k3xx_serial.c
s32k3xx_serial
ci
> s32k3xx_serial: use small lock in arch/arm/src/s32k3xx/s32k3xx_serial.c

- arch/arm/src/lc823450/lc823450_dma.c
lc823450_dma: use small lock in arch/arm/src/lc823450/lc823450_dma.c
reason:
lc823450_dma
ci ostest
> lc823450_dma: use small lock in arch/arm/src/lc823450/lc823450_dma.c

- arch/arm/src/cxd56xx/cxd56_rtc.c
arm/cxd56xx: Add g_ prefix to rtc spin lock
continue work of a68b00206bb5205f2b8372867b49665cac54fd00
```
| commit a68b00206bb5205f2b8372867b49665cac54fd00
| Date:   Mon Dec 9 20:48:09 2024 +0800
|
|     cxd56_rtc.c: use small lock in arch/arm/src/cxd56xx/cxd56_rtc.c
|
|     reason:
|     We hope to remove all instances of spin_lock_irqsave(NULL).
|
|     Signed-off-by: hujun5 <hujun5@xiaomi.com>
```
N/A
ci-check
> arm/cxd56xx: Add g_ prefix to rtc spin lock

- include/nuttx/lib/lib.h
- libs/libc/misc/CMakeLists.txt
- libs/libc/misc/Kconfig
- libs/libc/misc/Make.defs
- libs/libc/misc/lib_pathbuffer.c
libs/libc: add a option to disable path buffer by default
If the current platform does not require a large PATH_MAX size support and toolchain supports alloca(),
we could turn off this option to improve performance.
N/A
ci-check
> libs/libc: add a option to disable path buffer by default

- drivers/syslog/Kconfig
FORMAT_MICROSECOND depends on format is not required.
We shall remove the depend on, and allow open microsecond in syslog
able to open SYSLOG_TIMESTAMP_FORMAT_MICROSECOND with user specific time format
CI-test, local arm-v8m board.
> syslog: allow microsecond on user specific time format

- include/nuttx/net/netconfig.h
Add CONFIG_NET_USRSOCK & CONFIG_NET_IPv4 & CONFIG_NET_IPv6 to support communicating in slave core
The pr is the modification to this pr(the https://github.com/apache/nuttx/pull/14634)
communicating in slave core
> netconfig.h:modify netconfig to support communicating in slave core

- arch/xtensa/src/esp32/esp32_partition.c
- arch/xtensa/src/esp32s3/esp32s3_partition.c
Non-encrypted mtd can not be used for encrypted device.
Even without SPI Flash encryption,
encrypted MTD also can be used to read no-encrypted data.
For non-encrypted device, the performance impact is slightly only for partiton offset.
The encrypted/non-encrypted read/write are still using encrypted/non-encrypted MTD.
Same behavior as esp32_partition_init(...).
Tested by using os cases.
> xtensa/esp32: encrypted MTD for partition offset

- libs/libbuiltin/libgcc/gcov.c
(.text.ltp_interfaces_sem_unlink_2_2_main+0xd8): undefined reference to `__gcov_execlk'
> gcov.c: Add necessary instrumentation functions

- arch/arm/src/s32k3xx/s32k3xx_serial.c
> {bp-15096} s32k3xx_serial: use small lock in arch/arm/src/s32k3xx/s32k3xx_serial.c

- arch/arm/src/lc823450/lc823450_dma.c
> {bp-15093} lc823450_dma: use small lock in arch/arm/src/lc823450/lc823450_dma.c

- boards/sim/sim/sim/CMakeLists.txt
avoid SIM compilation post build issues on other platforms
same fix for build with make
https://github.com/apache/nuttx/pull/14800
RELEASE
CI
> {bp-15091} build(CMAKE): fix pac sim elf ONLY in Linux platform

- arch/arm/src/max326xx/max32660/max32660_rtc.c
> {bp-15094} max32660_rtc: use small lock in arch/arm/src/max326xx/max32660/max32660 rtc

- boards/arm/mx8mp/verdin-mx8mp/src/mx8mp_ina219.c
- boards/arm/rp2040/common/src/rp2040_ina219.c
- boards/arm/stm32/common/src/stm32_apds9960.c
- boards/arm/stm32/common/src/stm32_ina219.c
- boards/arm/stm32/common/src/stm32_veml6070.c
- boards/risc-v/esp32c3-legacy/common/src/esp32c3_board_apds9960.c
- boards/xtensa/esp32/common/src/esp32_board_apds9960.c
- ina219
- apds9960
- veml6070
these sensors use i2c serial communication protocol
Github
https://github.com/simbit18/nuttx_test_pr/actions/runs/12238181261
> [sensors]: Removed the unnecessary inclusion of spi header files

- net/tcp/tcp_timer.c
when tcp retransmission only double conn->timer in Karn(tcp_timer.c L602), after retransmission in Jacobson M is is now rtt test will become a negative value.
```
signed char m;
m = conn->rto - conn->timer; // M is now rtt test
/* This is taken directly from VJs original code in his paper */
m = m - (conn->sa >> 3);
conn->sa += m;              //conn->sa is a negative value
if (m < 0)
{
m = -m;
}
m = m - (conn->sv >> 2);
conn->sv += m;
conn->rto = (conn->sa >> 3) + conn->sv; //rto
```
For example,we lost one ack packet, we will set conn->timer = 6 by backoff，conn->rto still 3. After retransmission we will Do RTT estimation, then will get
```
conn->sa = 253
conn->rto = 46
```
Then if any packets lost it will wait for a long time before triggering a retransmission.
- The issue of abnormal …
> net/tcp_timer: fix tcp RTO abnormally large after retransmission occurs

- Documentation/guides/renode.rst
- Documentation/guides/zerolatencyinterrupts.rst
- Documentation/platforms/arm/stm32f3/boards/stm32f3discovery/index.rst
- Documentation/platforms/arm/stm32l1/boards/stm32ldiscovery/index.rst
since the basepri is always used without any configuration
continue clean up from https://github.com/apache/nuttx/pull/15073
ci
> Documentation: Remove CONFIG_ARMV7M_USEBASEPRI from code base

- libs/libc/unistd/CMakeLists.txt
- libs/libc/unistd/Make.defs
- libs/libc/unistd/lib_chdir.c
- libs/libc/unistd/lib_fchdir.c
libc/chdir: chdir/fchdir should not depend on environment variables
This PR will still allow basic shell operations such as cd/ls/pwd to be used even when the environment is disabled.
Depends on: https://github.com/apache/nuttx-apps/pull/2885
sim/nsh  and enable  CONFIG_DISABLE_ENVIRON
before:
```
$ ./build/nuttx 
NuttShell (NSH) NuttX-10.4.0
nsh> ls
nsh: ls: missing required argument(s)
nsh> cd
nsh: cd: command not found
nsh> pwd
nsh: pwd: command not found
nsh> ls /
/:
bin/
data/
dev/
etc/
proc/
tmp/
nsh> 
```
after:
```
$ ./build/nuttx 
NuttShell (NSH) NuttX-10.4.0
nsh> ls
/:
bin/
data/
dev/
etc/
proc/
tmp/
nsh> cd
nsh> cd /data
nsh> pwd
/data
nsh> ls /
/:
bin/
data/
dev/
etc/
proc/
tmp/
nsh> 
```
> libc/chdir: chdir/fchdir should not depend on environment variables

- Documentation/guides/zerolatencyinterrupts.rst
This is a follow-up to 366c8a5d942e45259f69da0e467a2874761499e4 (PR #15102).
This is a follow-up to PR #15102, which is itself a follow-up to several PRs: PR #15073, PR #15086. Previously, there were two alternative implementations for enabling and disabling interrupts on ARM Cortex M3/M4 (armv7m, armv8m) architectures: PRIMASK or BASEPRI. BASEPRI is better than PRIMASK in that it is a superset of PRIMASK functionality. Previously there was a Kconfig option, CONFIG_ARMV7M_USEBASEPRI, to choose which implementation was used, and conditional logic in the code. This Kconfig and alternative PRIMASK implementation were removed and BASEPRI is always used now.
This follow-up tweaks …
> Documentation: Tweak text about Zero Latency Interrupts

- net/tcp/tcp_timer.c
when tcp retransmission only double conn->timer in Karn(tcp_timer.c L602), after retransmission in Jacobson M is is now rtt test will become a negative value.
```
signed char m;
m = conn->rto - conn->timer; // M is now rtt test
/* This is taken directly from VJs original code in his paper */
m = m - (conn->sa >> 3);
conn->sa += m;              //conn->sa is a negative value
if (m < 0)
{
m = -m;
}
m = m - (conn->sv >> 2);
conn->sv += m;
conn->rto = (conn->sa >> 3) + conn->sv; //rto
```
For example,we lost one ack packet, we will set conn->timer = 6 by backoff，conn->rto still 3. After retransmission we will Do RTT estimation, then will get
```
conn->sa = 253
conn->rto = 46
```
Then if any packets lost it will wait for a long time before triggering a retransmission.
Test method.
We can …
> {bp-15118} net/tcp_timer: fix tcp RTO abnormally large after retransmission occurs

- Documentation/applications/testing/drivertest/index.rst
- Documentation/guides/renode.rst
- Documentation/guides/zerolatencyinterrupts.rst
- Documentation/platforms/arm/stm32f3/boards/stm32f3discovery/index.rst
- Documentation/platforms/arm/stm32l1/boards/stm32ldiscovery/index.rst
this patch includes
https://github.com/apache/nuttx/pull/15102
https://github.com/apache/nuttx/pull/15121
https://github.com/apache/nuttx/pull/15122
RELEASE
CI
> [bp-15102} update documentation

- arch/arm/src/cxd56xx/cxd56_rtc.c
continue work of a68b00206bb5205f2b8372867b49665cac54fd00
| commit a68b00206bb5205f2b8372867b49665cac54fd00
| Date:   Mon Dec 9 20:48:09 2024 +0800
|
|     cxd56_rtc.c: use small lock in arch/arm/src/cxd56xx/cxd56_rtc.c
|
|     reason:
|     We hope to remove all instances of spin_lock_irqsave(NULL).
|
|     Signed-off-by: hujun5 <hujun5@xiaomi.com>
RELEASE
CI
> {bp-15105} arm/cxd56xx: Add g_ prefix to rtc spin lock

- arch/arm64/src/imx9/imx9_usdhc.c
Invalidate cache when dma transfer is ready
Read operation gives sometimes invalid data, this fixes that issue
> arch/arm64/imx9: Fix usdhc dma receive

- arch/xtensa/src/common/espressif/platform_include/sys/lock.h
* xtensa/esp32s3: Update the reserved size for struct __lock
After https://github.com/apache/nuttx/pull/15075, the static assertion at `nuttx/arch/xtensa/src/esp32s3/esp32s3_libc_stubs.c` was being triggered when building any of the ESP32-S3's defconfigs. This PR updates the reserved size to reflect the changes recently introduced.
Fix building any of the ESP32-S3's defconfigs and closes https://github.com/apache/nuttx/issues/15137
Internal CI testing + NuttX's upstream CI.
> xtensa/esp32s3: Update the reserved size for struct __lock

- tools/ci/platforms/darwin.sh
- tools/ci/platforms/darwin_arm64.sh
added LLVM toolchain for Arm on Apple Intel
release-17.0.1
added LLVM toolchain for Arm on Apple Silicon
release-19.1.1
github  [macOS-14,  macOS-13 (arm-08)]
https://github.com/simbit18/nuttx_test_pr/actions/runs/12277626847/job/34257527992
```
Configuration/Tool: nucleo-f207zg/nsh,CONFIG_ARM_TOOLCHAIN_CLANG
2024-12-11 14:35:07
Cleaning...
Configuring...
Disabling CONFIG_ARM_TOOLCHAIN_GNU_EABI
Enabling CONFIG_ARM_TOOLCHAIN_CLANG
chip/stm32_gpio.c:43:11: note: '#pragma message: …
```
> [ci] macOS platforms: added LLVM toolchain for Arm

- drivers/bch/bchdev_driver.c
drivers/bch: Drivers may not support command `BIOC_FLUSH`.
Calling `bchlib_flushsector()` maybe enough on some devices.
- drivers/bch (e.g. `fsync()` on bch device may returns failure without this patch)
- Selftest with `fsync()`
- NuttX CI
> drivers/bch: Drivers may not support command `BIOC_FLUSH`

- include/nuttx/binfmt/binfmt.h
binfmt/modlib: reduce size of binary_s if CONFIG_LIBC_MODLIB is disabled
Test on nsh/sim
before:
sizeof(struct binary_s): 216
after:
sizeof(struct binary_s): 56(-160)
N/A
nsh/sim
> binfmt/modlib: reduce size of binary_s if CONFIG_LIBC_MODLIB is disabled

- fs/inode/fs_files.c
fs/inode: refresh tcb after each file sync() is completed
After tcb is destroyed, it is very dangerous to back reference tcb through file.
This commit will perform file operations while ensuring the validity of tcb during
fsync, with will avoid tcb check in each subsystem.
N/A
ci-check
> fs/inode: refresh tcb after each file sync() is completed

- fs/procfs/fs_procfsproc.c
procfs:fix cmdline overflow bug
procfs
use a too long command, and us ps wiil crash, this pr fix it.
> procfs:fix cmdline overflow bug

- include/nuttx/clock.h
- sched/clock/clock.h
- sched/clock/clock_systime_ticks.c
- sched/clock/clock_systime_timespec.c
This is continue work of https://github.com/apache/nuttx/pull/15038
sched/clock: call up_timer_gettime() to get higher resolution
driver/timers: remove wall clock diff from lower half
Some SOC chipsets use global clock generator to unify the time of each MCU,
that means after MCUs is start-up, the timer will not start counting from 0.
this PR will record the wall timer of global timer and recalculate the ticks.
Impact
N/A
Testing
ci-check
> sched/clock: call up_timer_gettime() to get higher resolution

- sched/clock/clock.h
- sched/clock/clock_initialize.c
sched/clock: cleanup g_system_ticks reference if arch timer is enabled
continue work of: https://github.com/apache/nuttx/pull/15139
N/A
ci-check
> sched/clock: cleanup g_system_ticks reference if arch timer is enabled

- fs/shm/shmfs_alloc.c
POSIX requires that the shm objects are zero-initialized. This has been broken in some earlier commits (starting from 9af5fc5d09724a5d300bc07ce85b9ba5c01ffadd)
Also fix the flat build memory allocation to allocate both object data and payload in the same chunk (as the comment also suggests). This saves allocations and memory in a system with lots of shm objects.
This PR fixes errors in applications, which run in "CONFIG_BUILD_FLAT", and assume that newly allocated shared memory is zero-initialized.
This also reduces memory consumption in smaller devices, when each shared memory object is allocated in a single chunk as originally.
The errors were introduced earlier when the SHM allocations were cache-line aligned.
This corrects SHM allocation to return zero-initialized memory
Tested on an …
> fs/shm/shmfs_alloc.c: Allocate zero-initialized memory in flat build

- arch/arm64/src/imx9/imx9_usdhc.c
Invalidate cache when dma transfer is ready
RELEASE
CI
> {bp-15144} arch/arm64/imx9: Fix usdhc dma receive

- arch/xtensa/src/common/espressif/platform_include/sys/lock.h
After https://github.com/apache/nuttx/pull/15075, the static assertion at `nuttx/arch/xtensa/src/esp32s3/esp32s3_libc_stubs.c` was being triggered when building any of the ESP32-S3's defconfigs. This commit updates the reserved size to reflect the changes introduced by the related PR.
RELEASE
CI
> {bp-15143} xtensa/esp32s3: Update the reserved size for struct __lock

- arch/arm/src/cxd56xx/cxd56_i2c.c
Fix a bug that I2C driver can not transfer after TX abort error. It caused by remaining NO_STOP flag status.
refs #17381
I2C bus devices with SPRESENSE
Tested on SPRESENSE
> arch: cxd56xx: Fix not restart after TX error

- Documentation/components/drivers/special/pci/index.rst
- drivers/can/CMakeLists.txt
- drivers/can/Kconfig
- drivers/can/Make.defs
- drivers/can/ctucanfd.h
- drivers/can/ctucanfd_pci.c
- drivers/can/kvaser_pci.c
- drivers/can/sja1000.h
- drivers/pci/pci_drivers.c
- include/nuttx/can/ctucanfd_pci.h
- include/nuttx/can/kvaser_pci.h
-  drivers/can: add Kvaser PCI card driver (qemu only)  
https://www.qemu.org/docs/master/system/devices/can.html#examples-how-to-use-can-emulation-for-sja1000-based-board
- drivers/can: add CTU CAN FD driver (qemu only) 
https://www.qemu.org/docs/master/system/devices/can.html#ctu-can-fd-support-examples
- Documentation: add PCI CAN cards doc
We can now simulate CAN networks on Linux host with `vcan`. 
qemu x86_64 and qemu arm32 with host canutils
It works now only with QEMU, for physical cards there is missing bus timings configuration ignored by QEMU implementation.
> Add support for PCI CAN cards for QEMU: Kvaser and CTU CAN FD

- fs/fat/fs_fat32util.c
Some bytes in boot sector might be corrupted for some reason. When this happens, the Nuttx system will crash due to dividing zero. It is better to return a mounting error, instead of crashing the system.
```
nsh> mount -t vfat /dev/mmcsd1 /mnt
nsh> dd if=/dev/mmcsd1 of=/mnt/file bs=32 count=1
32bytes copied, 0 usec, 4294967295 KB/s
nsh> hexdump /mnt/file
/mnt/file at 00000000:
0000: eb 58 90 4e 55 54 54 58 20 20 20 00 02 20 20 00 .X.NUTTX   ..  .
0010: 02 00 00 00 00 f8 00 00 3f 00 ff 00 00 00 00 00 ........?.......
nsh> dd if=/dev/mmcsd1 of=/dev/mmcsd1 bs=1 count=1 skip=11 seek=13
1bytes copied, 0 usec, 4294967295 KB/s
nsh> dd if=/dev/mmcsd1 of=/mnt/file bs=32 count=1
32bytes copied, 0 usec, 4294967295 KB/s
nsh> hexdump /mnt/file
/mnt/file at 00000000:
0000: eb 58 90 4e 55 54 54 58 20 20 …
```
> fs/fat/fs_fat32util.c: fix potential exception due to dividing zero during mounting when fat is corrupted

- binfmt/binfmt_exec.c
binfmt/exec: initialize binary_s to empty to avoid invaild access
Included 
https://github.com/apache/nuttx/pull/15124
RELEASE
CI
> {bp-15160} binfmt/exec: initialize binary_s to empty to avoid invaild access

- fs/fat/fs_fat32util.c
- fs/shm/shmfs_alloc.c
POSIX requires that the shm objects are zero-initialized. This has been broken in some earlier commits (starting from https://github.com/apache/nuttx/commit/9af5fc5d09724a5d300bc07ce85b9ba5c01ffadd)
Also fix the flat build memory allocation to allocate both object data and payload in the same chunk (as the comment also suggests). This saves allocations and memory in a system with lots of shm objects.
This PR fixes errors in applications, which run in "CONFIG_BUILD_FLAT", and assume that newly allocated shared memory is zero-initialized.
This also reduces memory consumption in smaller devices, when each shared memory object is allocated in a single chunk as originally.
The errors were introduced earlier when the SHM allocations were cache-line aligned.
NOTE
included …
> {bp-15159} fs/shm/shmfs_alloc.c: Allocate zero-initialized memory in flat build

- include/nuttx/clock.h
- sched/clock/clock.h
- sched/clock/clock_initialize.c
- sched/clock/clock_systime_ticks.c
- sched/clock/clock_systime_timespec.c
sched/clock: cleanup g_system_ticks reference if arch timer is enabled
Included: 
https://github.com/apache/nuttx/pull/15139
RELEASE
CI
> {bp-15151} sched/clock: cleanup g_system_ticks reference if arch timer is enabled

- arch/arm/src/cxd56xx/cxd56_i2c.c
Fix a bug that I2C driver can not transfer after TX abort error. It caused by remaining NO_STOP flag status.
RELEASE
CI
> {bp-15166} arch: cxd56xx: Fix not restart after TX error

- tools/ci/platforms/darwin.sh
fix a few errors i observed with a local run of "./cibuild.sh -i".
"./cibuild.sh -i" on my environment. (macOS 15.1.1, x86-64, xcode 16.1)
> fix a few tools/ci/cibuild.sh failures on my environment (macOS 15.1.1, x86-64, xcode 16.1)

- arch/risc-v/src/common/riscv_percpu.c
Since the SCRATCH register is used to store the percpu pointer, which should not be accessed by other CPUs, we can replace the critical section with irqsave/irqrestore.
RISCV percpu
ostest
> riscv_percpu: Replace critical section with irqsave/irqrestore

- fs/inode/fs_files.c
- include/nuttx/fs/fs.h
- tools/gdb/nuttxgdb/protocols/fs.py
> remove fl_crefs

- arch/arm64/src/imx9/hardware/imx9_tpm.h
Macro contains one closing bracket too much
> arm64/imx9: tpm: fix TPM_FILTER_CHXFVAL_MASK macro

- tools/ci/platforms/darwin.sh
hopefully this can fix build failure on macos-13. (see below)
```
[470/495] Linking CXX executable bloaty
FAILED: bloaty
: && /Applications/Xcode_15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -W -Wall -Wno-sign-compare -fdiagnostics-color=always -O2 -g1 -isysroot /Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -mmacosx-version-min=13.7 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/bloaty.dir/src/main.cc.o -o bloaty  liblibbloaty.a  third_party/protobuf/cmake/libprotoc.a  third_party/re2/libre2.a  third_party/capstone/libcapstone.a  /Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/lib/libz.tbd …
```
> tools/ci/platforms/darwin.sh: bump bloaty version

- CMakeLists.txt
fixed
```
[1025/1027] Generating System.map
FAILED: System.map C:/nuttxgit/nuttx/build/System.map cmd.exe /C "cd /D C:\nuttxgit\nuttx\build && arm-none-eabi-nm nuttx | grep -v '(compiled)|($)|( [aUw] )|(..ng$)|(LASH[RL]DI)' | sort > System.map"
```
local 
```
C:\nuttxgit\nuttx>cmake -B build -DBOARD_CONFIG=nucleo-l152re:nsh -GNinja
--   CMake:  3.27.1
--   Ninja:  1.11.1
--   Board:  nucleo-l152re
--   Config: nsh
--   Appdir: C:/nuttxgit/apps
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- The ASM compiler identification is GNU …
```
> [cmake] windows native: fixed FAILED: System.map

- arch/arm/src/imxrt/imxrt_serial.c
- arch/arm/src/s32k3xx/s32k3xx_serial.c
- arch/arm64/src/imx9/imx9_lpuart.c
The features CONFIG_IMXRT_LPUART_SINGLEWIRE and CONFIG_IMXRT_LPUART_INVERT will get build errors when CONFIG_SERIAL_TERMIOS or CONFIG_SERIAL_TIOCSERGSTRUCT are not enabled.
This happens because INVERT and SINGLEWIRE rely on variables that are only declared when TERMIOS or TIOCSERGSTRUCT are enabled.
Fixed by making those vars available in all cases.
arm/imxrt, arm/s32k3xx, arm64/imx9
> lpuart: fix build errors for SINGLEWIRE and INVERT without SERIAL_TERMIOS

- drivers/sensors/Make.defs
Build fails when enabling CONFIG_SENSORS_BMM150. This happens because "bmm150.c" is added to the CSRCS but that file does not exist.
Solved it by removing the part that adds bmm150.c. The driver is available in bmm150_uorb.c and that is correctly added to CSRCS on https://github.com/apache/nuttx/blob/fce4f2b3ee849edeb224bf2815f8633df25edfc8/drivers/sensors/Make.defs#L299
> sensors: fix Make.defs for bmm150

- fs/inode/fs_files.c
- include/nuttx/fs/fs.h
use atomic to protect f_refs
fix regresion from https://github.com/apache/nuttx/pull/14801
fs refs
ci ostest
> use atomic to protect f_refs

- arch/arm64/src/imx9/hardware/imx9_tpm.h
Macro contains one closing bracket too much
RELEASE
CI
> {bp-15184} arm64/imx9: tpm: fix TPM_FILTER_CHXFVAL_MASK macro

- CMakeLists.txt
fixed
[1025/1027] Generating System.map
FAILED: System.map C:/nuttxgit/nuttx/build/System.map cmd.exe /C "cd /D C:\nuttxgit\nuttx\build && arm-none-eabi-nm nuttx | grep -v '(compiled)|($)|( [aUw] )|(..ng$)|(LASH[RL]DI)' | sort > System.map"
RELEASE
CI
> {bp-15185} windows native: fixed FAILED: System.map

- drivers/sensors/Make.defs
Build fails when enabling CONFIG_SENSORS_BMM150. This happens because "bmm150.c" is added to the CSRCS but that file does not exist.
Solved it by removing the part that adds bmm150.c. The driver is available in bmm150_uorb.c and that is correctly added to CSRCS on
[nuttx/drivers/sensors/Make.defs](https://github.com/apache/nuttx/blob/fce4f2b3ee849edeb224bf2815f8633df25edfc8/drivers/sensors/Make.defs#L299)
Line 299 in [fce4f2b](https://github.com/apache/nuttx/commit/fce4f2b3ee849edeb224bf2815f8633df25edfc8)
CSRCS += bmm150_uorb.c
RELEASE
CI
> {bp-15182} sensors: fix Make.defs for bmm150

- include/nuttx/can/can.h
delete "begin_packed_struct" and "end_packed_struct" qualifiers of  struct can_msg_s
for resolving the problem that is data address not alignment!
the reason of the problem is forcing to use uint32 to access cm_data, then system will crash.
system will normally run.
Infineon Tricore TC4XX board.
> delete "begin_packed_struct" and "end_packed_struct"

- libs/libxx/Kconfig
libxx: Make LIBCXXABI default for sim/macOS
Fix build errors like:
https://github.com/apache/nuttx/issues/14774
build tested (with https://github.com/apache/nuttx/pull/15209 and a few local changes)
macOS 15.2
x86-64
Xcode 16.1
> libxx: Make LIBCXXABI default for sim/macOS

- include/nuttx/can/can.h
delete "begin_packed_struct" and "end_packed_struct" qualifiers of struct can_msg_s
for resolving the problem that is data address not alignment!
the reason of the problem is forcing to use uint32 to access cm_data, then system will crash.
RELEASE
CI
> {bp-15207} nuttx/can.h: delete "begin_packed_struct" and "end_packed_struct" qualifier

- include/nuttx/lib/lib.h
- libs/libc/misc/CMakeLists.txt
- libs/libc/misc/Kconfig
- libs/libc/misc/Make.defs
- libs/libc/misc/lib_pathbuffer.c
Avoid spinlock/mutex by using atomic
Use atomic_cmpxchg to ensure that in multithreaded situations, if someone releases the buffer, it can be applied for in time. And use atomic_ulong to save free_bitmap
includes 
https://github.com/apache/nuttx/pull/15104
RELEASE
CI
> {bp-15198} lib_pathbuffer.c:Use atomic instead of locks

- libs/libc/stdlib/lib_bsearch.c
- libs/libc/stdlib/lib_qsort.c
remove the advertising clause
3. All advertising materials mentioning features or use of this software must
display the following acknowledgement: This product includes software
developed by the University of California, Berkeley and its contributors.
permitted by Berkley amendment
https://ipira.berkeley.edu/sites/default/files/amendment_of_4-clause_bsd_software_license.pdf
following example from NETBSD and OPENBSD
https://github.com/NetBSD/src/commit/eb7c1594f145c931049e1fd9eb056a5987e87e59
https://github.com/openbsd/src/commit/6580fee3295c971a919cc04bfc3598c5f8bcd2b1
LICENSE
CI
> libs/libc/stdlib: update BSD 4 -> 3 clause license headers.

- boards/sim/sim/sim/scripts/Make.defs
sim: Fix build errors on macOS
macOS 15.2
x86-64
Xcode 16.1
```
ld: warning: disabling chained fixups because of unaligned pointers
ld: illegal text-relocation in '_main'+0x1F (/Users/yamamoto/git/nuttx/nuttx/arc
h/sim/src/nuttx.rel) to '_g_argc'
```
> sim: Fix build errors on macOS

- arch/risc-v/src/esp32c3-legacy/esp32c3_rtc.c
esp32c3_rtc: use small lock in arch/risc-v/src/esp32c3-legacy/esp32c3_rtc.c
reason:
esp32c3_rtc
ci
> esp32c3_rtc: use small lock in arch/risc-v/src/esp32c3-legacy/esp32c3_rtc.c

- arch/arm/src/max326xx/max32660/max32660_rtc.c
max32660_rtc: change spinlock name g_lock -> g_rtc_lock
none
ci
> max32660_rtc: change spinlock name g_lock -> g_rtc_lock

- arch/xtensa/src/esp32s3/esp32s3_rtc.c
esp32s3_rtc: use small lock in arch/xtensa/src/esp32s3/esp32s3_rtc.c
reason:
esp32s3_rtc
ci
> esp32s3_rtc: use small lock in arch/xtensa/src/esp32s3/esp32s3_rtc.c

- arch/arm/src/at32/at32_gpio.c
- arch/arm/src/eoss3/eoss3_gpio.c
- arch/arm/src/nuc1xx/nuc_gpio.c
- arch/arm/src/sam34/sam4l_gpio.c
- arch/arm/src/sam34/sam_gpio.c
- arch/arm/src/samv7/sam_gpio.c
- arch/arm/src/stm32/stm32_gpio.c
- arch/arm/src/stm32f0l0g0/stm32_gpio.c
- arch/arm/src/stm32f7/stm32_gpio.c
- arch/arm/src/stm32h5/stm32_gpio.c
- arch/arm/src/stm32h7/stm32_gpio.c
- arch/arm/src/stm32l4/stm32l4_gpio.c
- arch/arm/src/stm32l5/stm32l5_gpio.c
- arch/arm/src/stm32u5/stm32_gpio.c
- arch/arm/src/stm32wb/stm32wb_gpio.c
- arch/arm/src/stm32wl5/stm32wl5_gpio.c
- arch/arm/src/tiva/cc13xx/cc13xx_gpio.c
- arch/arm/src/tiva/lm/lm3s_gpio.c
- arch/arm/src/tiva/lm/lm4f_gpio.c
- arch/arm/src/tiva/tm4c/tm4c_gpio.c
- arch/hc/src/m9s12/m9s12_gpio.c
- arch/mips/src/pic32mx/pic32mx_gpio.c
- arch/mips/src/pic32mz/pic32mz_gpio.c
- arch/risc-v/src/bl602/bl602_gpio.c
gpio: use small lock to protect configgpio
reason:
gpio
ci
> gpio: use small lock to protect configgpio

- arch/arm/src/armv6-m/arm_exception.S
- arch/arm/src/armv7-a/arm_vectors.S
- arch/arm/src/armv7-m/arm_exception.S
- arch/arm/src/armv8-m/arm_exception.S
- arch/risc-v/src/common/riscv_exception_common.S
use cfi in irq asm function, make a debug frame
debug, if do backtrace in irq
test code hello_main
```
{
uint32_t *p = 0xdeedbeff;
*p = 0xffffff;
printf("%p\n %x\n", p, *p);
return 0;
}
```
qemu mps3-an547 hello_main :
Triggering an exception, and gdb backtrace is:
before:
```
(gdb) bt
#0  0x0001168a in systick_getstatus (lower_=0x100010c <g_systick_lower>, status=0x1000a30 <g_intstackalloc+1600>)
at /home/ajh/work/vela_system/nuttx/arch/arm/src/armv8-m/arm_systick.c:142
#1  0x000122f4 in current_usec () at /home/ajh/work/vela_system/nuttx/drivers/timers/arch_timer.c:105 
#2  0x0001234c in udelay_accurate (microseconds=250000) at /home/ajh/work/vela_system/nuttx/drivers/timers/arch_timer.c:115 
#3  0x000124bc in up_udelay (microseconds=250000) at …
```
> arm-m armv7a riscv32 :use cfi in irq asm function, make a debug frame

- libs/libc/stdlib/lib_bsearch.c
- libs/libc/stdlib/lib_qsort.c
remove the advertising clause
3. All advertising materials mentioning features or use of this software must
display the following acknowledgement: This product includes software
developed by the University of California, Berkeley and its contributors.
permitted by Berkley amendment
https://ipira.berkeley.edu/sites/default/files/amendment_of_4-clause_bsd_software_license.pdf
following example from NETBSD and OPENBSD
https://github.com/NetBSD/src/commit/eb7c1594f145c931049e1fd9eb056a5987e87e59
https://github.com/openbsd/src/commit/6580fee3295c971a919cc04bfc3598c5f8bcd2b1
RELEASE
CI
> {bp-15197} libs/libc/stdlib: remove BSD-4 clause code

- boards/sim/sim/sim/scripts/Make.defs
macOS 15.2
x86-64
Xcode 16.1
```
ld: warning: disabling chained fixups because of unaligned pointers
ld: illegal text-relocation in '_main'+0x1F (/Users/yamamoto/git/nuttx/nuttx/arc
h/sim/src/nuttx.rel) to '_g_argc'
```
RELEASE
CI
> {bp-15209} sim: Fix build errors on macOS

- arch/arm/src/imx9/hardware/imx95/imx95_edma.h
- arch/arm/src/imx9/imx9_edma.c
imx95: Fix eDMA compilation
Also clarify that the imx95 uses eDMA5 instead of eDMA4 (imx93 has eDMA4)
imx95
imx95-19x19-evk
> imx95: Fix eDMA compilation

- arch/risc-v/src/esp32c6/esp_wifi_adapter.c
- arch/xtensa/src/esp32/esp32_wifi_adapter.c
- arch/xtensa/src/esp32s2/esp32s2_wifi_adapter.c
- arch/xtensa/src/esp32s3/esp32s3_wifi_adapter.c
Fix a situation where WiFi Access Point password was wrongly copied to WiFi Station configuration instead, when crypto algorithm IW_ENCODE_ALG_NONE was not used.
Solves the issue on the following SoCs: ESP32, ESP32S2, ESP32S3, ESP32C6.
Internal CI testing.
> Fix for WiFi AP password wrongly stored on some Espressif devices

- include/nuttx/addrenv.h
- include/nuttx/mm/kmap.h
- mm/kmap/kmm_map.c
- sched/addrenv/addrenv.c
- sched/semaphore/sem_holder.c
- sched/semaphore/sem_waitirq.c
As semaphores reside in user virtual memory, there are some cases where accessing said semaphore needs a trick where
the mappings are changed to the semaphore's owner process. Using addrenv_select was a quick kludge fix for the issue
and it seemed to work. However, this is not the case in one exception; an interrupt level context switch.
Using addrenv_select() from interrupt context causes random crashes due to usage of this_task(). If an interrupt level
context switch occurs, this_task() will point to the NEXT task that will be executed once the interrupt returns. Temporarily
mapping this task's address environment to access e.g. the semaphore in question will obviously fail. Just get rid of this
kludge fix and properly address the issue once and for all.
Both sem_waitirq and …
> sem: Replace addrenv_select with kmm_map for sem_waitirq/sem_holder

- arch/xtensa/src/esp32/esp32_rtc.c
- arch/xtensa/src/esp32s2/esp32s2_rtc.c
esp32_rtc: use small lock in arch/xtensa/src/esp32s2/esp32s2_rtc.c
reason:
esp32_rtc
ci
> esp32_rtc: use small lock in arch/xtensa/src/esp32s2/esp32s2_rtc.c

- arch/risc-v/src/esp32c6/esp_wifi_adapter.c
- arch/xtensa/src/esp32/esp32_wifi_adapter.c
- arch/xtensa/src/esp32s2/esp32s2_wifi_adapter.c
- arch/xtensa/src/esp32s3/esp32s3_wifi_adapter.c
Fix a situation where WiFi Access Point password was wrongly copied to WiFi Station configuration instead, when crypto algorithm IW_ENCODE_ALG_NONE was not used.
RELEASE
CI
> {bp-15241} Fix for WiFi AP password wrongly stored on some Espressif devices

- arch/arm/src/tiva/tm4c/tm4c_gpio.c
Create version.h
CC:  chip/tm4c/tm4c_gpio.c chip/tm4c/tm4c_gpio.c: In function 'tiva_configgpio': chip/tm4c/tm4c_gpio.c:793:11: warning: implicit declaration of function 'spin_lock_irqsave' [-Wimplicit-function-declaration]
793 |   flags = spin_lock_irqsave(&g_configgpio_lock);
|           ^~~~~~~~~~~~~~~~~
CC:  nsh_parse.c chip/tm4c/tm4c_gpio.c:844:3: warning: implicit declaration of function 'spin_unlock_irqrestore' [-Wimplicit-function-declaration]
844 |   spin_unlock_irqrestore(&g_configgpio_lock, flags);
RELEASE
CI
> {bp-15240} fix compile error

- drivers/input/uinput.c
- include/nuttx/input/uinput.h
Xiaomi has submitted the SGA and the license can be migrated to ASF
LICENSE
CI
> drivers/input/uinput: migrate to ASF license

- include/nuttx/wireless/bluetooth/bt_buf.h
- wireless/bluetooth/bt_hcicore.c
bt_buf: use small lock to protect bt_bufferlist_s
reason:
bt_buf
ci
> bt_buf: use small lock to protect bt_bufferlist_s

- drivers/syslog/syslog_intbuffer.c
syslog/intbuffer: some improve for intbuffer
1. add static for internal function
2. add FAR for pointer prototype
N/A
ci-check
> syslog/intbuffer: some improve for intbuffer

- wireless/bluetooth/bt_buf.c
bt_buf: use small lock in wireless/bluetooth/bt_buf.c
reason:
bt_buf
ci
> bt_buf: use small lock in wireless/bluetooth/bt_buf.c

- arch/arm64/src/common/arm64_cache.c
arm64/cache: add i/dcache check to avoid build break
```
arch/arm64/src/common/arm64_cache.c:344:35: error: macro "up_get_icache_linesize" passed 1 arguments, but takes just 0
344 | size_t up_get_icache_linesize(void)
|                                   ^
```
N/A
disable i/dcache
> arm64/cache: add i/dcache check to avoid build break

- arch/arm/src/cxd32xx/cxd32_irq.c
- arch/arm/src/cxd32xx/cxd32_uart.c
- arch/arm/src/cxd56xx/cxd56_gpioint.c
- arch/arm/src/cxd56xx/cxd56_irq.c
- arch/arm/src/cxd56xx/cxd56_uart.c
cxd: use small lock
reason:
cxd32_uart
ci
> cxd: use small lock

- tools/gcov.sh
1. Add "-s" to specify the path to collect gcno files
2. Add "-a" to specify the path to collect gcda files.
3. Add "-x" for copy-only operation
> gcov/script: Enhanced gcov script

- arch/arm/src/common/arm_modifyreg16.c
- arch/arm64/src/common/arm64_modifyreg16.c
- arch/avr/src/common/avr_modifyreg16.c
- arch/ceva/src/common/ceva_modifyreg16.c
- arch/hc/src/common/hc_modifyreg16.c
- arch/mips/src/common/mips_modifyreg16.c
- arch/misoc/src/common/misoc_modifyreg16.c
- arch/or1k/src/common/or1k_modifyreg16.c
- arch/sparc/src/common/sparc_modifyreg16.c
- arch/x86/src/common/x86_modifyreg16.c
- arch/x86_64/src/common/x86_64_modifyreg16.c
- arch/xtensa/src/common/xtensa_modifyreg16.c
modifyreg16: use small lock in modifyreg16
reason:
modifyreg16
ci
> modifyreg16: use small lock in modifyreg16

- libs/libbuiltin/libgcc/CMakeLists.txt
- libs/libbuiltin/libgcc/Make.defs
- libs/libbuiltin/libgcc/gcov.c
gcov: Fix gcov fork() issue:
1.  After code coverage is enabled, fork will be replaced by __gcov_fork
gcov: Prevent pile insertion recursion
gcov: Disable stack checking
```
When enable CONFIG_STACK_CANARIES, in general, the stack check in the __gcov_fork function is:
" return fork();
18: e59f3020 ldr r3, [pc, #32] @ 40 <__gcov_fork+0x40>
1c: e5932000 ldr r2, [r3]
20: e59d3004 ldr r3, [sp, #4]
24: e0332002 eors r2, r3, r2
28: e3a03000 mov r3, #0
2c: 1a000002 bne 3c <__gcov_fork+0x3c>"
r3 is obtained by taking the value of sp offset. But after opening thumb, the second comparison value in
"8c6: 4a06 ldr r2, [pc, #24] @ (8e0 <__gcov_fork+0x30>)
8c8: 6811 ldr r1, [r2, #0]
8ca: …
```
> gcc/gcov: fix problems with fork

- arch/arm/src/tiva/tm4c/tm4c_ethernet.c
- arch/renesas/src/rx65n/rx65n_eth.c
- boards/arm/at32/at32f437-mini/src/at32_ethernet.c
- boards/arm/imxrt/imxrt1020-evk/src/imxrt_ethernet.c
- boards/arm/imxrt/imxrt1050-evk/src/imxrt_ethernet.c
- boards/arm/imxrt/imxrt1060-evk/src/imxrt_ethernet.c
- boards/arm/imxrt/imxrt1064-evk/src/imxrt_ethernet.c
- boards/arm/imxrt/imxrt1170-evk/src/imxrt_ethernet.c
- boards/arm/imxrt/teensy-4.x/src/imxrt_ethernet.c
- boards/arm/sam34/sam4e-ek/src/sam_ethernet.c
- boards/arm/sama5/jupiter-nano/src/sam_ethernet.c
- boards/arm/sama5/sama5d2-xult/src/sam_ethernet.c
- boards/arm/sama5/sama5d3-xplained/src/sam_ethernet.c
- boards/arm/sama5/sama5d3x-ek/src/sam_ethernet.c
- boards/arm/sama5/sama5d4-ek/src/sam_ethernet.c
- boards/arm/samv7/same70-xplained/src/sam_ethernet.c
- boards/arm/samv7/samv71-xult/src/sam_ethernet.c
- boards/arm/stm32/stm32f4discovery/src/stm32_ethernet.c
remove big lock in arch_phy_irq
reason:
arch_phy_irq
ci
> remove big lock in arch_phy_irq

- crypto/xform.c
Most tools used for compliance and SBOM generation use SPDX identifiers
This change brings us a step closer to an easy SBOM generation.
LICENSE
CI
> crypto/xform: migrate to SPDX identifier

- arch/arm64/src/common/arm64_cache.c
arch/arm64/src/common/arm64_cache.c:344:35: error: macro "up_get_icache_linesize" passed 1 arguments, but takes just 0
344 | size_t up_get_icache_linesize(void)
|                                   ^
Feishu-Id: 4956395133
RELEASE
CI
> {bp-15265} arm64/cache: add i/dcache check to avoid build break

- crypto/xform.c
NOTE
The code was reported as GPL by FOSS ID
and Xiaomi scanned the file xform.c with Black Duck Security and it showed that the license was BSD-3-Clause and no risk was reported.
Since there is no clause on the license it was concluded as 0BSD
Refference
https://github.com/apache/nuttx/pull/15252
RELEASE
CI
> {bp-15252} crypto/xform.c: migrate to SPDX identifier

- libs/libbuiltin/libgcc/CMakeLists.txt
- libs/libbuiltin/libgcc/Make.defs
- libs/libbuiltin/libgcc/gcov.c
gcov: Fix gcov fork() issue:
1. After code coverage is enabled, fork will be replaced by __gcov_fork
gcov: Prevent pile insertion recursion
gcov: Disable stack checking
When enable CONFIG_STACK_CANARIES, in general, the stack check in the __gcov_fork function is:
" return fork();
18: e59f3020 ldr r3, [pc, #32] @ 40 <__gcov_fork+0x40>
1c: e5932000 ldr r2, [r3]
20: e59d3004 ldr r3, [sp, #4]
24: e0332002 eors r2, r3, r2
28: e3a03000 mov r3, #0
2c: 1a000002 bne 3c <__gcov_fork+0x3c>"
r3 is obtained by taking the value of sp offset. But after opening thumb, the second comparison value in
"8c6: 4a06 ldr r2, [pc, #24] @ (8e0 <__gcov_fork+0x30>)
8c8: 6811 ldr r1, [r2, #0]
8ca: 687a ldr r2, [r7, #4]
8cc: 4051 eors r1, r2"
is obtained through r7. Since r7 stores the stack address at this time, …
> {bp-15258} gcc/gcov: fix problems with fork

- arch/arm/src/common/arm_modifyreg32.c
- arch/arm/src/common/arm_modifyreg8.c
- arch/arm64/src/common/arm64_modifyreg32.c
- arch/arm64/src/common/arm64_modifyreg8.c
- arch/avr/src/common/avr_modifyreg32.c
- arch/avr/src/common/avr_modifyreg8.c
- arch/ceva/src/common/ceva_modifyreg32.c
- arch/ceva/src/common/ceva_modifyreg8.c
- arch/hc/src/common/hc_modifyreg32.c
- arch/hc/src/common/hc_modifyreg8.c
- arch/mips/src/common/mips_modifyreg32.c
- arch/mips/src/common/mips_modifyreg8.c
- arch/misoc/src/common/misoc_modifyreg32.c
- arch/misoc/src/common/misoc_modifyreg8.c
- arch/or1k/src/common/or1k_modifyreg32.c
- arch/or1k/src/common/or1k_modifyreg8.c
- arch/risc-v/src/common/riscv_modifyreg32.c
- arch/sparc/src/common/sparc_modifyreg32.c
- arch/sparc/src/common/sparc_modifyreg8.c
- arch/x86/src/common/x86_modifyreg32.c
- arch/x86/src/common/x86_modifyreg8.c
- arch/x86_64/src/common/x86_64_modifyreg32.c
- arch/x86_64/src/common/x86_64_modifyreg8.c
- arch/xtensa/src/common/xtensa_modifyreg32.c
- arch/xtensa/src/common/xtensa_modifyreg8.c
- arch/z80/src/z180/z180_modifiyreg8.c
modifyreg[8|32]: use small lock in modifyreg[8|32]
reason:
modifyreg
ci
> modifyreg[8|32]: use small lock in modifyreg[8|32]

- arch/arm/src/stm32/stm32_i2c_v2.c
- arch/arm/src/stm32f0l0g0/stm32_i2c.c
- arch/arm/src/stm32f7/stm32_i2c.c
- arch/arm/src/stm32h5/stm32_i2c.c
- arch/arm/src/stm32u5/stm32_i2c.c
This PR expend the fix done under 'stm32h7/stm32_i2c: fix sending large data over i2c #12093' to all stm32 chips
To trigger TC interrupt NBYTES needs to be set before RELOAD is disabled similar to previous commit done on stm32h7 
I could test it on stm32f7 board that required to send large data. But don't have other boards to test it too.
> stm32_i2c: fix sending large data over i2c

- arch/risc-v/src/common/espressif/esp_wlan.c
Long term (1 hour) IPERF test was failing for ESP32C3 and ESP32C6 when running as server.
The failure happened on debug assertion related to IOB, as shown below.
```
[dut-0]  626.25- 631.26 sec    1376256 Bytes    2.20 Mbits/sec
[dut-1] dump_assert_info: Current Version: NuttX  10.4.0 e7f3a53706 Dec 10 2024 09:53:08 risc-v
[dut-1] dump_assert_info: Assertion failed iobq->qh_tail: at file: iob/iob_add_queue.c:73 task: wifi process: Kernel 0x40001720
[dut-1] up_dump_register: EPC: 420038aa
[dut-1] up_dump_register: A0: 3fc8ed70 A1: 00000049 A2: 3c0b6c04 A3: 00000000
```
Analyzing the IOB status at this assertion, it was found that in this backtrace sequence, wlan_recvframe did not have a spinlock as expected (this is present on Xtensa devices). This caused unexpected behavior as some IOBs …
> arch/risc-v/espressif: add missing spinlock to wlan_recvframe

- drivers/sensors/sensor.c
- include/nuttx/uorb.h
This patch adds support for velocity measurement sensors. I plan to use it as a generic speed type to be used for Renesas FS3000 (Air Velocity Flow).
Related PR: https://github.com/apache/nuttx-apps/pull/2908
Now uORB will support Velocity sensors
Tested with FS3000 air velocity flow sensor
> drivers/sensors: Add Velocity sensor type to UORB

- arch/arm/src/imx9/imx9_lpuart.c
- arch/arm64/src/imx9/imx9_lpuart.c
imx9_lpuart: use small lock in arch/arm(64)/src/imx9/imx9_lpuart.c
reason:
imx9_lpuart
ci
> imx9_lpuart: use small lock in arch/arm(64)/src/imx9/imx9_lpuart.c

- arch/arm/src/imx9/imx9_flexcan.c
- boards/arm/at32/at32f437-mini/src/at32_ethernet.c
- boards/arm/imxrt/imxrt1020-evk/src/imxrt_ethernet.c
- boards/arm/imxrt/imxrt1050-evk/src/imxrt_ethernet.c
- boards/arm/imxrt/imxrt1060-evk/src/imxrt_ethernet.c
- boards/arm/imxrt/imxrt1064-evk/src/imxrt_ethernet.c
- boards/arm/imxrt/teensy-4.x/src/imxrt_ethernet.c
- boards/arm/sama5/sama5d2-xult/src/sam_ethernet.c
- boards/arm/sama5/sama5d3x-ek/src/sam_ethernet.c
- boards/arm/samv7/same70-xplained/src/sam_ethernet.c
- boards/arm/samv7/samv71-xult/src/sam_ethernet.c
- boards/arm/stm32/stm32f4discovery/src/stm32_ethernet.c
imx9_flexcan: use small lock in arch/arm/src/imx9/imx9_flexcan.c
reason:
imx9_flexcan
ci
> imx9_flexcan: use small lock in arch/arm/src/imx9/imx9_flexcan.c

- arch/risc-v/src/common/espressif/esp_hr_timer.c
- arch/risc-v/src/common/espressif/esp_hr_timer.h
- arch/risc-v/src/common/espressif/esp_rtc.c
esp_rtc: use small lock in arch/risc-v/src/common/espressif/esp_rtc.c
reason:
esp_rtc
ci
> esp_rtc: use small lock in arch/risc-v/src/common/espressif/esp_rtc.c

- mm/iob/Kconfig
- net/icmp/Kconfig
- net/icmpv6/Kconfig
Refresh config dependency of `NET_READAHEAD`:
ICMP(v6) uses IOB queue as readahead, but TCP/UDP don't now.
Kconfig dependency only.
CI
> net: Refresh config dependency of NET_READAHEAD

- include/nuttx/uorb.h
The `struct sensor_gnss_satellite.cf`(carrier frequency) can be parsed from `GSV.signal_id`(e.g. NMEA 0183 v4.11) and `struct sensor_gnss_satellite.constellation`(sv_type)
uorb:gnss_satellite
NuttX CI
> nuttx/uorb.h: Add carrier frequency for GNSS Satellite

- include/limits.h
- include/signal.h
- include/sys/fcntl.h
- include/sys/mount.h
- include/sys/prctl.h
- include/sys/resource.h
- include/sys/sem.h
- include/sys/signal.h
- include/sys/socket.h
- include/sys/types.h
- include/wait.h
1. add sa_restorer to struct sigaction
2. add RLIMIT_NICE field definition
3. add LINE_MAX limits field definition
4. add PR_SET_DUMPABLE field definition
5. add SA_NOMASK field definition
6. extend mount flag definition
7. add include/sys/signal.h header to make the LTP linux kernel testcases can run on nuttx
8. add SOL_PACKET support
9. add wait.h header to make the LTP linux kernel testcase can run on nuttx
10. add sys/sem.h header to make the LTP linux kernel testcase can run on nuttx
11. add sys/fcntl.h  header to make the LTP linux kernel testcase can run on nuttx
has passed ostest
> Add LTP linux kernel testcases support

- arch/sim/src/sim/sim_initialize.c
- cmake/nuttx_mkconfig.cmake
- drivers/audio/Kconfig
- drivers/audio/Make.defs
- drivers/audio/audio_fake.c
- include/nuttx/audio/audio_fake.h
- tools/cfgdefine.c
This is a new feature, adding a fake driver to easily debug and test in sim or qemu environment. It simulates a real audio driver by reading and writing files.  With it, you can conveniently customize and define various capture or playback audio drivers for debugging or automated testing.
YES, New feature add.
CI
> nuttx/audio: add fake audio driver.

- arch/arm/src/imx6/imx_serial.c
Initialization of g_uart1priv was missing a comma after SP_UNLOCKED. This failure was causing a CI build failure for another pull request by me. I fixed this so that I can move on with the other pull request. 
The other pull request is this: https://github.com/apache/nuttx/pull/15271
> Added comma to fix undefined bits struct member

- Documentation/guides/port_arm_cm4.rst
This patch fixes spelling typos in port_arm_cm4.rst
Signed-off-by: Masanari Iida <standby24x7@gmail.com>
> Documentation/guides: Fix typos in port_arm_cm4.rst

- arch/xtensa/src/esp32s3/esp32s3_rtc_lowerhalf.c
- arch/z16/src/z16f/z16f_serial.c
- arch/z80/src/z8/z8_serial.c
- boards/arm/max326xx/max32660-evsys/src/max326_button.c
- boards/arm/stm32/stm32f4discovery/src/stm32_gs2200m.c
- drivers/i2c/i2c_bitbang.c
- drivers/power/supply/act8945a.c
- drivers/serial/uart_pci_16550.c
- drivers/serial/uart_pl011.c
- drivers/wireless/bluetooth/bt_uart_shim.c
- include/nuttx/serial/uart_16550.h
use small lock in following files
arch/xtensa/src/esp32s3/esp32s3_rtc_lowerhalf.c
arch/z16/src/z16f/z16f_serial.c
arch/z80/src/z8/z8_serial.c
boards/arm/max326xx/max32660-evsys/src/max326_button.c boards/arm/stm32/stm32f4discovery/src/stm32_gs2200m.c drivers/i2c/i2c_bitbang.c
drivers/power/supply/act8945a.c
drivers/serial/uart_pci_16550.c
drivers/serial/uart_pl011.c
drivers/wireless/bluetooth/bt_uart_shim.c
arch/xtensa/src/esp32s3/esp32s3_rtc_lowerhalf.c
arch/z16/src/z16f/z16f_serial.c
arch/z80/src/z8/z8_serial.c
boards/arm/max326xx/max32660-evsys/src/max326_button.c boards/arm/stm32/stm32f4discovery/src/stm32_gs2200m.c drivers/i2c/i2c_bitbang.c
drivers/power/supply/act8945a.c
drivers/serial/uart_pci_16550.c
drivers/serial/uart_pl011.c
drivers/wireless/bluetooth/bt_uart_shim.c
ci
> use small lock in following files

- drivers/sensors/CMakeLists.txt
- drivers/sensors/Kconfig
- drivers/sensors/Make.defs
- drivers/sensors/fs3000_uorb.c
This driver add uORB sensor support to Renesas FS3000 sensor.
Users will be able to use FS3000 sensor on NuttX
using US082-FS3000EVZ  module
> drivers/sensors: Add support to Renesas FS3000 Air Velocity Flow

- arch/or1k/src/mor1kx/mor1kx_serial.c
- arch/risc-v/src/bl602/bl602_serial.c
- arch/risc-v/src/common/espressif/esp_lowputc.c
- arch/risc-v/src/common/espressif/esp_lowputc.h
- arch/risc-v/src/common/espressif/esp_tickless.c
- arch/risc-v/src/esp32c3-legacy/esp32c3_idle.c
- arch/risc-v/src/esp32c3-legacy/esp32c3_lowputc.c
- arch/risc-v/src/esp32c3-legacy/esp32c3_lowputc.h
- arch/risc-v/src/esp32c3-legacy/esp32c3_rtc_lowerhalf.c
- arch/risc-v/src/fe310/fe310_gpio.c
use small lock in following file
arch/or1k/src/mor1kx/mor1kx_serial.c
arch/risc-v/src/bl602/bl602_serial.c
arch/risc-v/src/common/espressif/esp_lowputc.c
arch/risc-v/src/common/espressif/esp_lowputc.h
arch/risc-v/src/common/espressif/esp_tickless.c
arch/risc-v/src/esp32c3-legacy/esp32c3_idle.c
arch/risc-v/src/esp32c3-legacy/esp32c3_lowputc.c
arch/risc-v/src/esp32c3-legacy/esp32c3_lowputc.h
arch/risc-v/src/esp32c3-legacy/esp32c3_rtc_lowerhalf.c arch/risc-v/src/fe310/fe310_gpio.c
arch/or1k/src/mor1kx/mor1kx_serial.c
arch/risc-v/src/bl602/bl602_serial.c
arch/risc-v/src/common/espressif/esp_lowputc.c
arch/risc-v/src/common/espressif/esp_lowputc.h
arch/risc-v/src/common/espressif/esp_tickless.c
arch/risc-v/src/esp32c3-legacy/esp32c3_idle.c
arch/risc-v/src/esp32c3-legacy/esp32c3_lowputc.c …
> use small lock in following file

- net/tcp/tcp_recvfrom.c
malloc a new iob to handle psock_send_eventhandler when tcp_recvhandler calls tcp_newdata to clear dev->d_iob
tcp_recvhandler
> tcp_recvfrom.c:resolve issue in tcp_recvhandler

- include/nuttx/wireless/ieee80211/ieee80211.h
Some macros used in the ieee80211.h header were missing definitions when attempting to build on Arch Linux. It appears this is a system difference between Arch Linux and Ubuntu. The definitions were:
- `hweight8`
- `cpu_to_le16`
- `le32_to_cpu`
- `BIT`
This PR replaces the `cpu_to_le16` and `le32_to_cpu` references with their equivalent definitions `htole16` and `le32toh` from `sys/endian.h`. I have also included definitions of `hweight8` and `BIT` at the top of the file if they are found to be undefined.
Now, users on Arch Linux can compile the IEEE802.11 header. This resolves issue #13704.
After implementing these changes, I built the `raspberrypi-pico-w:telnet` configuration and connected to my home network successfully. I was able to ping other devices on my network.
> Fixed IEEE802.11 build on Arch Linux

- tools/gcov.py
Due to the makefile, the relative paths of the files are different, and it is impossible to use existing tools such as gcov and lcov to specify a base compilation path for them.
The solution for Linux is to copy a copy of the source code from the compilation environment to the test environment, and there is a place that is consistent with the absolute path of the compilation environment.
This solution is to pass in the "-b" parameter to directly modify the info file generated by lcov. The search path will be executed in the next step of genhtml
what Host was used for build (OS, CPU, …
> gcov: Solve the problem of incorrect report generation caused by different compilation and test environments

- arch/arm/src/imxrt/imxrt_wdog.c
- arch/arm/src/kinetis/kinetis_edma.c
- arch/arm/src/lc823450/lc823450_dvfs2.c
- arch/arm/src/lc823450/lc823450_timer.c
- arch/arm/src/lpc54xx/lpc54_lowputc.c
- boards/arm/stm32/stm32f4discovery/src/stm32_gs2200m.c
use small lock in:
arch/arm/src/imxrt/imxrt_wdog.c
arch/arm/src/kinetis/kinetis_edma.c
arch/arm/src/lc823450/lc823450_dvfs2.c
arch/arm/src/lc823450/lc823450_timer.c
arch/arm/src/lpc54xx/lpc54_lowputc.c
none
ci
> use small lock 

- net/tcp/tcp_netpoll.c
Remove the DEBUGASSERT of the same event of the same fd in tcp_pollsetup.
In libuv, if the real_timeout in the uv__io_poll is less than 0, the poll logic will be entered directly by the uv__run_timers, which will trigger the ASSERT. It seems that the situation of first epoll and then poll for the same fd is used in libuv, and the case is allowed in Linux.
We can perform the epoll and then poll operations on the same tcp fd.
I just used the app, which accessed an http web page through the fetch interface for testing. In this process, the application established a tcp connection by calling libuv and libcurl.
After the modification, this test can pass.
> net: Change the DEBUGASSERT to WARNING log for the tcp_pollsetup.

- arch/arm/src/tiva/common/tiva_hciuart.c
- arch/arm/src/tms570/tms570_lowputc.c
- arch/arm/src/xmc4/xmc4_serial.c
- arch/arm64/src/a64/a64_serial.c
- arch/mips/src/pic32mx/pic32mx_serial.c
- arch/mips/src/pic32mz/pic32mz_serial.c
- arch/risc-v/src/c906/c906_serial.c
- arch/risc-v/src/fe310/fe310_serial.c
- arch/risc-v/src/hpm6750/hpm6750_serial.c
- arch/risc-v/src/k210/k210_serial.c
- arch/sparc/src/bm3803/bm3803-serial.c
- arch/sparc/src/bm3823/bm3823-serial.c
use small lock in following files:
arch/arm/src/tiva/common/tiva_hciuart.c
arch/arm/src/tms570/tms570_lowputc.c
arch/arm/src/xmc4/xmc4_serial.c
arch/arm64/src/a64/a64_serial.c
arch/mips/src/pic32mx/pic32mx_serial.c
arch/mips/src/pic32mz/pic32mz_serial.c
arch/risc-v/src/c906/c906_serial.c
arch/risc-v/src/fe310/fe310_serial.c
arch/risc-v/src/hpm6750/hpm6750_serial.c
arch/risc-v/src/k210/k210_serial.c
arch/sparc/src/bm3803/bm3803-serial.c
arch/sparc/src/bm3823/bm3823-serial.c
arch/arm/src/tiva/common/tiva_hciuart.c
arch/arm/src/tms570/tms570_lowputc.c
arch/arm/src/xmc4/xmc4_serial.c
arch/arm64/src/a64/a64_serial.c
arch/mips/src/pic32mx/pic32mx_serial.c
arch/mips/src/pic32mz/pic32mz_serial.c
arch/risc-v/src/c906/c906_serial.c
arch/risc-v/src/fe310/fe310_serial.c …
> use small lock in following files:

- libs/libc/stdio/lib_libvsprintf.c
The POSIX standard states that the `syslog()` function generates the body from the message and arguments the same way as `printf()`,
> except that the additional conversion specification `%m` shall be recognized;
*https://pubs.opengroup.org/onlinepubs/009695399/functions/syslog.html*
What most of the implementations do is to leverage the processing to `vsprintf` internals, to reduce code duplicity. This means the `%m` modifier is present on almost all `printf` implementations. Take the following code snippet as an example: https://onlinegdb.com/YdR9pU6KS.
Therefore, the underlying library must also be updated for `syslog` to support such a specification.
All the code using `vsprintf` underneath will have the ability to use the `%m` modifier, which is a wrapper for `%s` and …
> [POSIX][Bug] syslog: Add support for `%m` modifier

- net/bluetooth/bluetooth_conn.c
- net/can/can_conn.c
- net/devif/devif_callback.c
- net/icmp/icmp_conn.c
- net/icmpv6/icmpv6_conn.c
- net/ieee802154/ieee802154_conn.c
- net/ipforward/Kconfig
- net/ipforward/ipfwd_alloc.c
- net/netlink/netlink_conn.c
- net/pkt/pkt_conn.c
- net/tcp/Kconfig
- net/tcp/tcp_conn.c
- net/tcp/tcp_wrbuffer.c
- net/udp/Kconfig
- net/udp/udp_conn.c
- net/udp/udp_wrbuffer.c
- net/usrsock/usrsock_conn.c
- net/utils/CMakeLists.txt
- net/utils/Make.defs
- net/utils/net_bufpool.c
- net/utils/utils.h
- net: Add buffer pool to replace connection allocation
- net: Optimize ipfwd and wrbuffer by buffer pool
Our net socket connection allocations are powerful but redundant because they're implemented once in each protocol.  This is not good for further optimizing and extending to other allocations, so maybe we can add a common implementation for the usage.
1. We add a `struct net_bufpool_s` as pool descriptor, which may use a little bit more memory than previous implementation (~28Bytes).
2. We share same functions between pools, so code size may shrink under some scenarios.
Mainly on SIM.
- tcp/udp/icmp/devif_callback tested with different configs, both conn and wrbuffer pools.
- Other pools share exactly the same logic, not tested very carefully.
> net: Add buffer pool to replace connection allocation

- libs/libc/machine/arch_libc.c
libc/machine: fix config error
> libc/machine: fix config error

- libs/libc/stdio/lib_libvsprintf.c
Reverts apache/nuttx#15320
It seems the `syslog` and `vsprintf` calls are being used from both user and kernel space, causing some builds to fail and introducing some uncertainty and potential new failures when running in non-flat builds.
CC/ @yamt @patacongo @fdcavalcanti @acassis @xiaoxiang781216
> Revert "[POSIX][Bug] syslog: Add support for `%m` modifier"

- drivers/serial/uart_pl011.c
fix regresion from https://github.com/apache/nuttx/pull/15301
uart_pl011
> fix a deadlock

- drivers/net/netdev_upperhalf.c
When `CONFIG_NETDEV_RSS` is disabled, `NETDEV_THREAD_COUNT` will be 1, and we should not access `upper->sem[cpu]` with `cpu > 0`.
Netdev upperhalf with `CONFIG_NETDEV_RSS=n` and SMP enabled.
QEMU with virtio-net and SMP, which may randomly block on sending without this patch.
> netdev/upper: Fix wrong CPU when RSS is disabled

- arch/sim/src/sim/sim_decoder.c
- drivers/video/v4l2_m2m.c
The actual return value of get_bufsize is struct v4l2_format.fmt.pix.sizeimage, and the sizeimage type is uint32_t, so change it to uint32_t
CI has overflow of int type：【CID 1578530: (#1 of 1): INTEGER_OVERFLOW】
CI and Execute nxcodec without error
> v4l2m2m: modify return value of g_bufsize to uint32_t

- include/limits.h
- libs/libc/misc/lib_pathbuffer.c
- sched/Kconfig
add LINE_MAX and modify lib_pathbuffer
1. Due to the continuous expansion of functions under the app, the 2k stack of many programs can no longer meet the requirements. If malloc is used frequently, memory fragmentation may occur, and we need an interface to optimize the use of stack and avoid memory fragmentation.
2. There are many similar configurations in the code：
config SYSTEM_CLE_CMD_HISTORY_LEN
config SYSTEM_CLE_CMD_HISTORY_LINELEN
CONFIG_NSH_LINELEN
HELP_LINELEN
PROCFS_LINELEN
The future plan is to remove these configurations and use LINE_MAX
Optimize the use of stacks
local test
> add LINE_MAX and modify lib_pathbuffer

- drivers/net/e1000.c
drivers/e1000: malloc size error， priv->mta is uint32_t
> drivers/e1000: malloc size error

- sched/event/event_post.c
- sched/event/event_wait.c
sched/event: init deleted node to avoid null pointer reference
nxevent_tickwait() will remove the node in failure case(EINTR). If the node
has been deleted in the nxevent_post(), NULL pointer reference will
be triggered after semaphore wait.
N/A
ostest/ci-check
> sched/event: init deleted node to avoid null pointer reference

- include/netinet/arp.h
- net/arp/arp_table.c
- net/netdev/netdev_ioctl.c
the same variable type in linux is char, in order to avoid modifying the third-party library code when porting the third-party library code.
sim:local and cortex-m33
> include/netinet/arp.h: change the type of arp_dev from uint8_t to char

- arch/sim/src/sim/posix/sim_alsa.c
Set paused = false when closing to prevent the app from executing the pause command and then executing close, which will cause paused = true when starting the second time and no frame will be displayed
Execute pause, then execute close, and no frame will be output when starting for the second time
test sim
> sim_alsa: set paused to false when executing close

- drivers/sensors/gnss_uorb.c
drivers/sensors/gnss: Fix deactivate failure when using both topic and device
Deactivate lower driver fails when both uORB topic and driver device are subscribed and opened. (crefs has increased to 2)
drivers/sensors/gnss:
1. Selftest with customized board.
2. NuttX CI
> drivers/sensors/gnss: Fix deactivate failure when using both topic and device

- arch/arm64/src/common/arm64_cpustart.c
arm64: fix tpidr maybe null
Before the MPU initialization, the up_update_task(this_cpu()) function is called at a time when hardware cache coherency is not yet enabled. In certain critical scenarios, Core 1 reads a zero value for tcb from the global variable g_assignedtask and stores this zero value into the tpidr register. This results in subsequent interrupt handlers reading a zero tcb, causing an exception.
arm64
> arm64: fix tpidr maybe null

- arch/arm/src/imxrt/Kconfig
- arch/arm/src/imxrt/imxrt_flexspi.c
- arch/arm/src/imxrt/imxrt_flexspi.h
- arch/arm/src/imxrt/imxrt_periphclks.h
Allows the driver to use the FlexSPI instance where it's currently executing from.
- By not reinitializing the peripheral
- Making prefetch configurable so that when doing transfer the AHB won't trigger conflicting transfers.
Also fixes clock config for IMXRT106X devices with FlexSPI2.
Minimal, it's behind a kconfig variable
MIMXRT1064 based platform implementing LittleFS on the same flash where XIP occurs.
> imxrt: FlexSPI allow RWW and transfer on XIP device

- arch/xtensa/include/syscall.h
- arch/xtensa/src/common/xtensa_dispatch_syscall.S
- arch/xtensa/src/common/xtensa_int_handlers.S
- arch/xtensa/src/common/xtensa_irqdispatch.c
- arch/xtensa/src/common/xtensa_signal_handler.S
- arch/xtensa/src/common/xtensa_user_handler.S
- arch/xtensa/src/esp32/esp32_irq.c
- arch/xtensa/src/esp32s2/esp32s2_irq.c
- arch/xtensa/src/esp32s3/esp32s3_irq.c
- libs/libc/machine/xtensa/arch_setjmp.S
Currently xtensa arch porting is using software interrupt (through write `intset` register) to trigger context switch.
But this put a strict requirement to the chip configuration: 
there must be a software interrupt, it's priority is less or equal to XCHAL_EXCM_LEVEL;
and it's priority must be greater than XCHAL_SYSCALL_LEVEL (the XCHAL_SYSCALL_LEVEL is not a cadence macro, it just means normal hardware interrupt priority).
Since the xtensa arch is very flexible, the chip designer might have not noticed above requirement in chip design phase.
And if the chip has been taped out without this requirement, there is no posibility to port nuttx to the chip.
This PR will try to change the software interrupt to `syscall` instruction.
The `syscall` instruction is a synchronous exception, and is …
> Change the software interrupt to syscall instruction

- sched/semaphore/sem_holder.c
Must use critical section here, otherwise the free holder list will leak, causing either a crash due to holder->htcb = NULL, or the free holder list becomes (erroneously) empty even though most of the holder entries are free.
Fix g_freeholders list integrity.
rv-virt:knsh64
rv-virt:ksmp64
MPFS target with > 100 threads and processeds, PI=yes, SMP=yes
> nxsem_destroyholder: Use critical section when destroying holder(s)

- arch/arm/src/efm32/efm32_leserial.c
- arch/arm/src/gd32f4/gd32f4xx_serial.c
- arch/arm/src/imxrt/imxrt_edma.c
- arch/arm/src/stm32u5/stm32_serial.c
There were two simple errors when running ci tests on pull #15351. These errors were unrelated to that pull. After investigating I found two simple errors. 
1. The len variable was likely a typo that should have been the function argument, ien. 
2. The spinlock_t lock was defined in a section dependent on CONFIG_SERIAL_TERMIOS. However, the spinlock_t lock was used in code that did not require the SERIAL_TERMIOS config. Therefore errors resulted. I moved this definition to a general section of the up_dev_s type. 
Re-built Nuttx with fixes. No build errors after changes.
> Fixed errors in CI build tests for pull request #15351

- arch/arm64/src/common/arm64_cpustart.c
Before the MPU initialization, the up_update_task(this_cpu()) function is called at a time when hardware cache coherency is not yet enabled. In certain critical scenarios, Core 1 reads a zero value for tcb from the global variable g_assignedtask and stores this zero value into the tpidr register. This results in subsequent interrupt handlers reading a zero tcb, causing an exception.
RELEASE
CI
> {bp-15338} arm64: fix tpidr maybe null

- arch/risc-v/src/common/espressif/esp_lowputc.c
- arch/risc-v/src/common/espressif/esp_lowputc.h
- include/nuttx/wireless/ieee80211/ieee80211.h
- libs/libc/machine/arch_libc.c
included
https://github.com/apache/nuttx/pull/15309
https://github.com/apache/nuttx/pull/15328
https://github.com/apache/nuttx/pull/15350
RELEASE
CI
> {bp-15350} fix compile error

- include/threads.h
Replace _SCHED_GETTID by pthread_self()
Update all thrd_ defines to actual function definitions
RELEASE
CI
> {bp-15277} include/threads.h: Replace thrd_ defines by actual function definitions

- mm/iob/Kconfig
- net/icmp/Kconfig
- net/icmpv6/Kconfig
ICMP(v6) uses IOB queue as readahead, but TCP/UDP don't now.
RELEASE
CI
> {bp-15286} net: Refresh config dependency of NET_READAHEAD

- arch/arm/src/stm32/stm32_i2c_v2.c
- arch/arm/src/stm32f0l0g0/stm32_i2c.c
- arch/arm/src/stm32f7/stm32_i2c.c
- arch/arm/src/stm32h5/stm32_i2c.c
- arch/arm/src/stm32u5/stm32_i2c.c
To trigger TC interrupt NBYTES needs to be set before RELOAD is disabled similar to previous commitdone on stm32h7 510b6221ca61b4209ffcf97fbaf64df8528e4870
RELEASE
CI
> {bp-15288} stm32_i2c: fix sending large data over i2c

- arch/risc-v/src/common/espressif/esp_wlan.c
Long term (1 hour) IPERF test was failing for ESP32C3 and ESP32C6 when running as server.
The failure happened on debug assertion related to IOB, as shown below.
[dut-0]  626.25- 631.26 sec    1376256 Bytes    2.20 Mbits/sec
[dut-1] dump_assert_info: Current Version: NuttX  10.4.0 e7f3a53706 Dec 10 2024 09:53:08 risc-v
[dut-1] dump_assert_info: Assertion failed iobq->qh_tail: at file: iob/iob_add_queue.c:73 task: wifi process: Kernel 0x40001720
[dut-1] up_dump_register: EPC: 420038aa
[dut-1] up_dump_register: A0: 3fc8ed70 A1: 00000049 A2: 3c0b6c04 A3: 00000000
Analyzing the IOB status at this assertion, it was found that in this backtrace sequence, wlan_recvframe did not have a spinlock as expected (this is present on Xtensa devices). This caused unexpected behavior as some IOBs were …
> {bp-15294} arch/risc-v/espressif: add missing spinlock to wlan_recvframe

- net/tcp/tcp_recvfrom.c
malloc a new iob to handle psock_send_eventhandler when tcp_recvhandler calls tcp_newdata to clear dev->d_iob
RELEASE
CI
> {bp-15287} tcp_recvfrom.c:resolve issue in tcp_recvhandler

- net/bluetooth/bluetooth_conn.c
- net/can/can_conn.c
- net/devif/devif_callback.c
- net/icmp/icmp_conn.c
- net/icmpv6/icmpv6_conn.c
- net/ieee802154/ieee802154_conn.c
- net/ipforward/Kconfig
- net/ipforward/ipfwd_alloc.c
- net/netlink/netlink_conn.c
- net/pkt/pkt_conn.c
- net/tcp/Kconfig
- net/tcp/tcp_conn.c
- net/tcp/tcp_wrbuffer.c
- net/udp/Kconfig
- net/udp/udp_conn.c
- net/udp/udp_wrbuffer.c
- net/usrsock/usrsock_conn.c
- net/utils/CMakeLists.txt
- net/utils/Make.defs
- net/utils/net_bufpool.c
- net/utils/utils.h
patches included:
net: Add buffer pool to replace connection allocation
net: Optimize ipfwd and wrbuffer by buffer pool
Our net socket connection allocations are powerful but redundant because they're implemented once in each protocol. This is not good for further optimizing and extending to other allocations, so maybe we can add a common implementation for the usage.
RELEASE
CI
> {bp-15285} net: Add buffer pool to replace connection allocation

- net/tcp/tcp_netpoll.c
In libuv, if the real_timeout in the uv__io_poll is less than 0, the poll logic will be entered directly by the uv__run_timers, which will trigger the ASSERT. It seems that the situation of first epoll and then poll for the same fd is used in libuv.
RELEASE
CI
> {bp-15312} net: Remove the DEBUGASSERT of the same event of the same fd in tcp_pollsetup.

- drivers/net/netdev_upperhalf.c
When `CONFIG_NETDEV_RSS` is disabled, `NETDEV_THREAD_COUNT` will be 1, and we should not access `upper->sem[cpu]` with `cpu > 0`.
RELEASE
CI
> {bp-15333} netdev/upper: Fix wrong CPU when RSS is disabled

- sched/event/event_post.c
- sched/event/event_wait.c
nxevent_tickwait() will remove the node in failure case(EINTR). If the node has been deleted in the nxevent_post(), NULL pointer reference will be triggered after semaphore wait.
RELEASE
CI
> {bp-15346} sched/event: init deleted node to avoid null pointer reference

- drivers/sensors/gnss_uorb.c
Deactivate lower driver fails when both uORB topic and driver device are subscribed and opened.
RELEASE
CI
> {bp-15342} drivers/sensors/gnss: Fix deactivate failure when using both topic and device

- arch/sim/src/sim/posix/sim_alsa.c
Set paused = false when closing to prevent the app from executing the pause command and then executing close, which will cause paused = true when starting the second time and no frame will be displayed
RELEASE
CI
> {bp-15341} sim_alsa: set paused to false when executing close

- drivers/net/e1000.c
drivers/e1000: malloc size error， priv->mta is uint32_t
RELEASE
CI
> {bp-15340} drivers/e1000: malloc size error

- include/nuttx/atomic.h
When CONFIG_LIBC_ARCH_ATOMIC is defined, the atomic_fetch_x interface conflicts with the atomic_fetch_x interface in libcxx. Therefore, it has been changed to a inline function.
CONFIG_LIBC_ARCH_ATOMIC 
eps32c3 board
> arch_atomic: change atomic_fetch_x interface to inline function

- arch/arm/src/stm32h5/Kconfig
- arch/arm/src/stm32h5/Make.defs
- arch/arm/src/stm32h5/stm32_qspi.c
- arch/arm/src/stm32h5/stm32_qspi.h
- arch/arm/src/stm32h5/stm32h5xx_rcc.c
This is an implementation of QSPI for the STM32H5, using the OCTOSPI peripheral. The driver is an adaptation of the STM32H7 QSPI driver, with changes made to accommodate differences in the STM32H5 OCTOSPI register set vs the STM32H7 QSPI registers. 
This will only impact the STM32H5 driver and only if QSPI is enabled. 
Testing was completed using the existing w25q driver as well as utilizing the nxffs file system. Additionally, a logic scope was used to verify correct operation of the QSPI interface. Attached are images of measurements taken with the logic scope and a brief functional test utilizing the w25q driver and nxffs. 
[qspi_func_test.txt](https://github.com/user-attachments/files/18254399/qspi_func_test.txt)
> Add STM32H5 QSPI Driver

- arch/arm/src/efm32/efm32_leserial.c
- arch/arm/src/gd32f4/gd32f4xx_serial.c
- arch/arm/src/imxrt/imxrt_edma.c
- arch/arm/src/stm32u5/stm32_serial.c
chip/efm32_leserial.c: In function 'efm32_restoreuartint': Error: chip/efm32_leserial.c:329:37: error: 'len' undeclared (first use in this function); did you mean 'ien'?
329 |   efm32_restoreuartint_nolock(priv, len);
|                                     ^~~
|                                     ien
RELEASE
CI
> {bp-15353} fix compile error

- Documentation/guides/fully_linked_elf.rst
- Documentation/guides/partially_linked_elf.rst
- Documentation/guides/updating_release_system_elf.rst
Add a migration warning to the update release system and the elf programs documentation pages. This is just to add a paper trail from where the documentation originate in case of error during the migration process.
Add warning section in the documentation to refer to the original wiki page in the official wiki. But nothing special
Build and validated locally with `make autobuild`
> Doc: add migration warning to updating release system and elf programs

- fs/littlefs/lfs_vfs.c
littlefs 2.10.0 and later rejects empty paths.  use "/" instead.
tested with esp32s3-devkit:toywasm.
> littlefs: fix EINVAL on path operations with littlefs 2.10.0

- arch/arm/src/at32/at32_gpio.c
- arch/arm/src/eoss3/eoss3_gpio.c
- arch/arm/src/nuc1xx/nuc_gpio.c
- arch/arm/src/sam34/sam4l_gpio.c
- arch/arm/src/sam34/sam_gpio.c
- arch/arm/src/samv7/sam_gpio.c
- arch/arm/src/stm32/stm32_gpio.c
- arch/arm/src/stm32f0l0g0/stm32_gpio.c
- arch/arm/src/stm32f7/stm32_gpio.c
- arch/arm/src/stm32h5/stm32_gpio.c
- arch/arm/src/stm32h7/stm32_gpio.c
- arch/arm/src/stm32l4/stm32l4_gpio.c
- arch/arm/src/stm32l5/stm32l5_gpio.c
- arch/arm/src/stm32u5/stm32_gpio.c
- arch/arm/src/stm32wb/stm32wb_gpio.c
- arch/arm/src/stm32wl5/stm32wl5_gpio.c
- arch/arm/src/tiva/cc13xx/cc13xx_gpio.c
- arch/arm/src/tiva/lm/lm3s_gpio.c
- arch/arm/src/tiva/lm/lm4f_gpio.c
- arch/arm/src/tiva/tm4c/tm4c_gpio.c
- arch/hc/src/m9s12/m9s12_gpio.c
- arch/mips/src/pic32mx/pic32mx_gpio.c
- arch/mips/src/pic32mz/pic32mz_gpio.c
- arch/risc-v/src/bl602/bl602_gpio.c
> {bp-15219} gpio: use small lock to protect configgpio

- arch/xtensa/src/esp32/esp32_spiflash.c
g_work as singleton can be changed by context switching, but previous one async operation have not finished yet.
adapt based on: 10a1d17a85a325f30c08e358a27c03d133a30ee3
one additonal mutex is used for g_work to keep the sequence correctly.
reproduce and verified by below steps
Variable g_wrok is sent to work_queue() function and set value to this variable.
Another context changes g_work by call esp32_async_op during step 1. g_work of Step 1 is changed because g_work is singleton.
Step 1 hanges because g_work of step 1 are cleared by step 2.
> xtensa/esp32: add lock for async operation work

- include/nuttx/mm/mempool.h
- include/nuttx/mm/mm.h
- mm/mm_heap/mm.h
mm: Unified memory management alignment length
> mm: Unified memory management alignment length

- arch/arm/src/imxrt/imxrt_edma.c
An extra `lock` appears in imxrt_edma due to 2 conflicting PRs:
- https://github.com/apache/nuttx/pull/15352
- https://github.com/apache/nuttx/pull/15353
This PR removes the extra `lock` in imxrt_edma.
This PR will fix the imxrt_edma errors reported by nuttx-dashboard.org
`teensy-4.x:lcd-4.1` fails to build due to duplicate `lock`:
https://github.com/NuttX/nuttx/actions/runs/12545164788/job/34978997451#step:7:749
```text
Configuration/Tool: teensy-4.x/lcd-4.1,CONFIG_ARM_TOOLCHAIN_GNU_EABI
Error: chip/imxrt_edma.c:148:14: error: duplicate member 'lock'
148 |   spinlock_t lock;                /* Spinlock */
|              ^~~~
```
`imxrt1064-evk:lvgl` also fails to build due to duplicate `lock`:
https://github.com/NuttX/nuttx/actions/runs/12545164788/job/34978997451#step:7:814
```text …
```
> arm/imxrt: Remove extra lock from imxrt_edma

- arch/arm/src/gd32f4/gd32f4xx_serial.c
An extra `lock` appears in gd32f4xx_serial due to 2 conflicting PRs:
- https://github.com/apache/nuttx/pull/7011
- https://github.com/apache/nuttx/pull/15352
This PR removes the extra `lock` in gd32f4xx_serial.
This PR will fix the gd32f4xx_serial errors reported by nuttx-dashboard.org
Before this PR: `gd32f470zk-eval:nsh` fails to build due to duplicate `lock`
https://github.com/NuttX/nuttx/actions/runs/12539724506/job/34966149597#step:7:998
```text
Configuration/Tool: gd32f470zk-eval/nsh,CONFIG_ARM_TOOLCHAIN_GNU_EABI
Error: chip/gd32f4xx_serial.c:174:19: error: duplicate member 'lock'
174 |   spinlock_t      lock;          /* Spinlock */
|                   ^~~~
```
After this PR: `gd32f470zk-eval:nsh` builds successfully in Docker …
> arm/gd32f4: Remove extra lock from gd32f4xx_serial

- arch/x86_64/src/common/x86_64_internal.h
- arch/x86_64/src/common/x86_64_switchcontext.c
- arch/x86_64/src/intel64/intel64_handlers.c
- arch/x86_64/src/intel64/intel64_schedulesigaction.c
- arch/x86_64/src/intel64/intel64_smpcall.c
with other functionalities removed.
Change-Id: Ic4bdf0e28c2cc0ec462a7c941f7a7cf2b1b53313
g_current_regs is only used to determine if we are in irq,
with other functionalities removed.
no
used for verification …
> arch/x86_64:g_current_regs is only used to determine if we are in irq,

- include/netpacket/packet.h
* netpacket/sockaddr_ll: Add valid packet types for sll_pkttype
Add valid packet types for the sll_pkttype member of the `struct sockaddr_ll`. These definitions are commonly used by third-party libraries.
Enable using the socket module of Python (WIP). No impact on existing configs.
> netpacket/sockaddr_ll: Add valid packet types for sll_pkttype

- net/tcp/tcp_input.c
when accept conn receives TCP_RESET, only accept conn itself should handle the event, and there is no need to notify the listening conn. otherwise, the server's poll will return with POLLERR and POLLHUP. this may cause some applications to execute incorrect logic in the future.
cortex-m33 board.
> tcp_input: remove tcp_callback(ABORT) when accept conn recv TCP_RESET

- arch/risc-v/include/irq.h
- arch/risc-v/src/common/riscv_cpuindex.c
Inline the short function to provide better performance.
RISCV Only
Local machine & CI
> arch/risc-v: inline up_cpu_index if RISCV_PERCPU_SCRATCH is not enabled

- arch/x86_64/include/irq.h
- arch/x86_64/src/intel64/intel64_backtrace_fp.c
- arch/x86_64/src/intel64/intel64_cpustart.c
- arch/x86_64/src/intel64/intel64_regdump.c
By default in SMP, obtaining this_task requires disabling interrupts, obtaining the current CPU index, accessing a global variable, and re-enabling interrupts. Storing this_task in percpu makes retrieval faster.
arch/x86_64: this_task is stored in the CPU private data
no impact
ostest
*Update this section with details on how did you verify the …
> arch/x86_64: this_task is stored in the CPU private data

- fs/v9fs/client.c
The V9FS brought by the last PR https://github.com/apache/nuttx/pull/13001 enhances the distributed application capabilities of NuttX. It is currently applicable to the scenario of QEMU and host as transparent file systems (similar to hostfs), and its performance is excellent.
I encountered some minor implementation problems during use, so I reorganized the following code logic:
- Protocol encapsulation process
- Type size
- Function interface return value
- Compatibility of different interfaces
This prepares V9FS to be compatible with more different scenarios in the future, for example, we can use sockets to make distributed file systems.
Next, I will also prepare a document guide to submit
It has no impact, mainly fixes the error process of v9fs
Target(s): …
> V9FS:Adjust some code implementations to fix bugs

- arch/x86_64/src/intel64/intel64_handlers.c
- arch/x86_64/src/intel64/intel64_irq.c
- arch/x86_64/src/intel64/intel64_vectors.S
arch/intel64: allow to attach handlers to ISR
we can attach interrupt handlers to ISR, this is required to support hardware breakpoints
intel hw and qemu
> arch/intel64: allow to attach handlers to ISR

- arch/x86_64/include/intel64/irq.h
align all definitions in intel64/irq.h
cosmetic change
local build
> arch/x86_64/include/intel64/irq.h: align definitions
