arch/xtensa/src/esp32/esp32_spiram.c, arch/xtensa/src/esp32/esp32_spiram.h, arch/xtensa/src/esp32/esp32_start.c, arch/xtensa/src/esp32s3/esp32s3_spiram.c, arch/xtensa/src/esp32s3/esp32s3_spiram.h, arch/xtensa/src/esp32s3/esp32s3_start.c
Enable SPIRAM test during boot of ESP32 and ESP32S3.
Verifies if SPIRAM is working as expected.
If it fails, a message shows SPIRAM test failed.
**ESP32 boot test:**
```
A[CPU0] __esp32_start: ESP32 chip revision is v3.1
[CPU0] psram_enable: This chip is ESP32-D0WD
[CPU0] psram_enable: SPI Defaults
[CPU0] psram_enable: clk_mode == PSRAM_CLK_MODE_DCLK
[CPU0] psram_enable: psram ID = 0x12535d0d
[CPU0] esp_spiram_init: Found 64MBit SPI RAM device
[CPU0] esp_spiram_init: SPI RAM mode: flash 40m sram 40m
[CPU0] esp_spiram_init: PSRAM initialized, cache is in even/odd (2-core) mode.
==> [CPU0] esp_spiram_test: SPI SRAM memory test OK!
B[CPU0] up_allocate_heap: Heap: start=3ffb59e8 end=3ffdfff0 size=173576
```
**ESP32S3 boot test:**
```
Aesp_spiram_init: Found 2MB SPI RAM device
esp_spiram_init: …
```
=> arch/xtensa: enable SPIRAM test during boot of ESP32|S3

arch/arm/src/CMakeLists.txt, arch/arm/src/qemu/CMakeLists.txt
This allows to build kernel mode NuttX with cmake for qemu-armv7a target.
None
- local check with config: qemu-armv7a:knsh
- CI checks
=> arch/qemu-armv7a: kernel mode cmake support

net/udp/udp_sendto_buffered.c
Notes:
1. This commit do the same thing as TCP did: https://github.com/apache/nuttx/pull/10627
2. UDP uses `iob_navail(false)` but TCP uses `iob_navail(true)`, this is because of a problem related to TCP recv window (https://github.com/apache/nuttx/pull/4142), so we don't need to change UDP now.
UDP
SIM
=> net/udp: Let cansend return EWOULDBLOCK when send buffer is full

boards/boardctl.c, libs/libbuiltin/Kconfig, libs/libbuiltin/libgcc/gcov.c
gcov: add reboot gcov storage coverage info
=> gcov: add reboot gcov storage coverage info

boards/risc-v/qemu-rv/rv-virt/src/qemu_rv_appinit.c
* risc-v/qemu-rv: Initialize the userleds without late initialization
If `CONFIG_BOARD_LATE_INITIALIZE` is not selected, the userleds will not be initialized. The userled initialization is not required to be done within `board_late_initialize()`, thus this commit enables initializing it in `board_app_initialize()` too.
Initialize the userleds even if `CONFIG_BOARD_LATE_INITIALIZE` is selected for `rv-virt` board. On the other hand, if `CONFIG_BOARD_LATE_INITIALIZE` is set, nothing changes.
Internal CI testing + `rv-virt:netnsh`:
Build it with:
```
$ make -j distclean && ./tools/configure.sh rv-virt:netnsh && kconfig-tweak -e EXAMPLES_LEDS && kconfig-tweak -e USERLED && kconfig-tweak -e USERLED_LOWER && make olddefconfig && make -j$(nproc)
```
The userleds are not being initialized:
```
$ …
```
=> risc-v/qemu-rv: Initialize the userleds without late initialization

sched/clock/clock_initialize.c
use atomic operation for g_system_ticks
g_system_ticks
ci
=> use atomic operation for g_system_ticks

arch/sim/src/sim/sim_copyfullstate.c
The current implementation of `sim_copyfullstate` uses a manual loop to copy memory from `src` to `dest`. This implementation does not account for cases where the `src` and `dest` memory regions overlap partially. In such cases, copying with the current method (*dest++ = *src++) can lead to undefined behavior as data in the source region may be overwritten before it is fully read.
If `sim_savestate` is invoked with overlapping memory regions for `CURRENT_REGS` and `rtcb->xcp.regs`, the loop in `sim_copyfullstate` can corrupt the copied data. This might happen if `CURRENT_REGS` and `rtcb->xcp.regs` are adjacent or partially overlapping due to memory layout.
The PR proposes replacing the manual loop in `sim_copyfullstate` with a call to `memmove` which internally determines whether to copy …
=> Fix Overlap Handling in sim_copyfullstate to Prevent Undefined Behavior

arch/xtensa/src/esp32s3/esp32s3_wdt.c
cpuint was allocated when register wdt handler, but not deallocated when unregister, which cause debug assert when checking DEBUGASSERT((*freeints & bitmask) == 0), so set cpuint to initial value after deallocate.
Impact watchdog handler register/unregister.
Test with running below test case WDTExceptionTest1() and WDTExceptionTest2() .
```
static void WDTExceptionTest1(void) {
// WDT Open
printf("---------- open ----------\n");
int wdt_handle = open("/dev/watchdog0", O_RDONLY);  // open
if (wdt_handle < 0) {
printf("open error. errno=%d\n", errno);
return -1;
}
// Set timeout
printf("---------- set timeout ----------\n");
unsigned long msec = 40 * 1000;  // 40 sec
int ret = ioctl(wdt_handle, WDIOC_SETTIMEOUT, msec);
if (ret < 0) {
printf("SetTimeout error. errno=%d\n", errno);
return -1; …
```
=> xtensa/esp32s3: set cpuint to initial value after deallocate

drivers/timers/rpmsg_rtc.c, include/nuttx/sched.h, sched/clock/clock.h, sched/clock/clock_gettime.c, sched/clock/clock_initialize.c, sched/clock/clock_settime.c, sched/clock/clock_systime_timespec.c, sched/group/group_create.c, sched/group/group_exitinfo.c, sched/group/group_join.c, sched/group/group_leave.c, sched/irq/irq_attach.c, sched/irq/irq_chain.c, sched/mqueue/mq_initialize.c, sched/mqueue/mq_msgfree.c, sched/mqueue/mq_send.c, sched/mqueue/mqueue.h, sched/signal/sig_default.c, sched/signal/sig_findaction.c, sched/task/task_setup.c, sched/timer/timer.h, sched/timer/timer_create.c, sched/timer/timer_initialize.c, sched/timer/timer_release.c
sched: remove all spin_lock_irqsave(NULL)
depends on https://github.com/apache/nuttx/pull/15413 https://github.com/apache/nuttx/pull/15414
sched
ci
=> sched: remove all spin_lock_irqsave(NULL)

Documentation/applications/system/nxdiag/index.rst, arch/risc-v/src/esp32h2/hal_esp32h2.mk, tools/Unix.mk, tools/espressif/chip_info.py, tools/host_info_dump.py, tools/host_info_parse.py
Related to https://github.com/apache/nuttx-apps/pull/2911 and https://github.com/apache/nuttx-apps/pull/2925
Add debug_info target support to parse and print `sysinfo.h` file which is output file of nxdiag application without flashing it to the device or even enabling `SYSTEM_NXDIAG` option. We can use this feature to have more information about user system environment when we are investigating issue. Users only need to run make debug_info on their problematic code.
- tools/Unix.mk: Add debug_info target to print nxdiag output
Common layer change
`esp32c6-devkitc:nsh` config selected and then run `make debug_info` command
=> tools/Unix.mk: Add debug_info target to print nxdiag output

arch/xtensa/src/esp32s3/esp32s3_spiflash_mtd.c, arch/xtensa/src/esp32s3/hardware/esp32s3_soc.h
porting of spi_flash_chip_generic_write_encrypted from ESP-IDF
Use spi_flash_write_encrypted_manu(...) instead of ROM Func spi_flash_write_encrypted(...)
tested by case of CONFIG_ESP32S3_SPIFLASH_ENCRYPTION_TEST, for <16MB and >16MB cases.
=> xtensa/esp32s3: porting of spi_flash_chip_generic_write_encrypted

drivers/sensors/gnss_uorb.c
Fix integer overflow error
```
CID 1309501: (#1 of 1): Overflow constant (INTEGER_OVERFLOW)
overflow_const: Expression upper->crefs, which is equal to 255, where enable ? 1 : -1 is known to be equal to -1, overflows the type that receives it, an unsigned integer 8 bits wide.
```
drivers/sensors/gnss
CI
=> drivers/sensors/gnss: Fix integer overflow error

arch/arm64/Kconfig, arch/arm64/src/common/arm64_mmu.c, mm/Kconfig
The TCMA flag is not critical, it will be set separately in "arm64_mte.c"
=> arm64/tbi: Unified TBI flags for MTE and software kasan

drivers/video/Kconfig, drivers/video/goldfish_gpu_fb.c
add bgra8888 color format support
reason:
for device needs
goldfish gpu fb
ci & goldfish
=> drivers/video: add BRGA8888 support for goldfish gpu fb

include/nuttx/lib/lib.h, libs/libc/misc/CMakeLists.txt, libs/libc/misc/Kconfig, libs/libc/misc/Make.defs, libs/libc/misc/lib_tempbuffer.c
rename lib_pathbuffer to lib_tempbuffer
None
./tools/configure.sh -l sim:nsh
make -j7
=> rename lib_pathbuffer to lib_tempbuffer

boards/xtensa/esp32/common/scripts/esp32_sections.ld, boards/xtensa/esp32/esp32-2432S028/scripts/Make.defs, boards/xtensa/esp32/esp32-audio-kit/scripts/Make.defs, boards/xtensa/esp32/esp32-devkitc/scripts/Make.defs, boards/xtensa/esp32/esp32-ethernet-kit/scripts/Make.defs, boards/xtensa/esp32/esp32-lyrat/scripts/Make.defs, boards/xtensa/esp32/esp32-pico-kit/scripts/Make.defs, boards/xtensa/esp32/esp32-sparrow-kit/scripts/Make.defs, boards/xtensa/esp32/esp32-wrover-kit/scripts/Make.defs, boards/xtensa/esp32/lilygo_tbeam_lora_gps/scripts/Make.defs, boards/xtensa/esp32/ttgo_eink5_v2/scripts/Make.defs, boards/xtensa/esp32/ttgo_lora_esp32/scripts/Make.defs, boards/xtensa/esp32/ttgo_t_display_esp32/scripts/Make.defs, boards/xtensa/esp32s2/common/scripts/esp32s2_sections.ld, boards/xtensa/esp32s2/esp32s2-kaluga-1/scripts/Make.defs, boards/xtensa/esp32s2/esp32s2-saola-1/scripts/Make.defs, boards/xtensa/esp32s2/franzininho-wifi/scripts/Make.defs
This PR merges the MCUBoot and Simple Boot linker scripts into one single file.
Affects ESP32 and ESP32S2 (S3 is already merged).
Simplify linker maintenance by using only one file for both simple boot and MCUBoot.
Modifies all ESP32 and ESP32S2 boards to use this new .ld.
Internal CI test on all boards.
=> boards/xtensa: unify linker script for MCUBoot and Simple Boot

net/bluetooth/bluetooth.h, net/bluetooth/bluetooth_conn.c, net/bluetooth/bluetooth_initialize.c, net/can/can_conn.c, net/devif/devif.h, net/devif/devif_callback.c, net/devif/devif_initialize.c, net/icmp/icmp.h, net/icmp/icmp_conn.c, net/icmpv6/icmpv6.h, net/icmpv6/icmpv6_conn.c, net/ieee802154/ieee802154.h, net/ieee802154/ieee802154_conn.c, net/ieee802154/ieee802154_initialize.c, net/ipforward/Kconfig, net/ipforward/ipfwd_alloc.c, net/net_initialize.c, net/netlink/netlink_conn.c, net/pkt/pkt_conn.c, net/tcp/Kconfig, net/tcp/tcp.h, net/tcp/tcp_conn.c, net/tcp/tcp_wrbuffer.c, net/udp/Kconfig, net/udp/udp.h, net/udp/udp_conn.c, net/udp/udp_wrbuffer.c, net/usrsock/usrsock_conn.c, net/utils/net_bufpool.c, net/utils/utils.h
- net/bufpool: Use `SEM_INITIALIZER` to init sem 
- net/bufpool: Call init automatically on alloc 
- net: Enable dynamic allocation of tcp/udp/ipfwd buffer by default
net/bufpool only.
With SIM and CMocka cases (may upstream later by @zs39)
=> net/bufpool: Some optimizations

arch/arm/src/stm32/stm32g4xxxx_rcc.c
In the file stm32g474xxxx_rcc.c, the enable PLL
code, according to the intent of the comment,
wants to keep the reserved bit, but the code
clears the reserved bit.
Avoid problems with clearing reservations.
arch/arm/src/stm32/stm2xxxx_rcc.c
static inline bool stm32_rcc_enablepll(void)
{
uint32_t regval;
uint32_t timeout;
/* Preserve reserved bits when altering the PLLCFGR register */
regval = getreg32(STM32_RCC_PLLCFGR);
regval &= RCC_PLLCFGR_RESERVED_MASK;
......
}
This part of the code changes will retain the reserved bits
No
No.
No.
No.
No.
No.
No.
ubuntu20.04
```
arm-none-eabi-gcc --version
arm-none-eabi-gcc (15:9-2019-q4-0ubuntu1) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
```
=> arch/arm/stm32: fix stm32g4 enable pll code.

.github/workflows/arch.yml
This PR increases the CI Jobs for Complex PRs from 50% to 100%, as explained here:
- https://github.com/apache/nuttx/issues/15451#issuecomment-2576576664
By increasing the CI Checks, we will have better quality PRs that won't fail the Daily Builds.
Complex PRs will now complete CI Checks in 2 hours 10 mins. (Instead of 1.5 hours previously)
No impact on Simple PRs that affect only One Single Architecture (arm32, risc-v, etc).
Complex PRs will now execute 100% of CI Jobs:
- https://github.com/lupyuen5/label-nuttx/actions/runs/12663293294
Simple PRs (Arm32) are not affected:
- https://github.com/lupyuen5/label-nuttx/actions/runs/12663305618
=> CI: Increase CI Jobs to 100% for Complex PRs

drivers/sensors/gnss_uorb.c
drivers/sensors/gnss: Macro `UINT8_MAX` for maximum value of `uint8_t crefs`
libs/libc/gnssutils/minmea/minmea.h:17:#include <stdint.h>
drivers/sensors/gnss
CI
=> drivers/sensors/gnss: Macro `UINT8_MAX` for maximum value of `uint8_t crefs`

arch/xtensa/src/esp32s3/esp32s3_wifi_adapter.c
esp32s3_wifi_adapter.c: Fix a deadlock
Fixes: https://github.com/apache/nuttx/issues/15314
esp32s3-devkit:wifi
=> esp32s3_wifi_adapter.c: Fix a deadlock

arch/risc-v/src/common/Toolchain.defs
Use findstring instead of direct equality checks for LLVM_CPUTYPE conditions to better handle ARCHCPUEXTFLAGS that may contain additional ISA extensions. This makes the CPU type detection more robust when dealing with extended instruction sets while still ensuring the required base ISA extensions are present.
For example, ARCHCPUEXTFLAGS="imc_zicsr_zifencei" will now correctly match as sifive-e20 rather than failing the exact match check.
Makefile only
GitHub CI and local machine
=> arch/risc-v: Improve LLVM CPU type detection with findstring

include/nuttx/mm/mm.h, mm/Kconfig
mm: default mm align 32->4,64->8
The modification at that time was because of x86-64, but the problem has been fixed elsewhere, and other architectures will not encounter any problems for the time being.
=> Revert "mm_heap: double malloced memory default alignment (4 -> 8, 8 -> 16)"

arch/arm/src/stm32/stm32_i2c.c, arch/arm/src/stm32/stm32_i2c_alt.c, arch/arm/src/stm32/stm32_i2c_v2.c, arch/arm/src/stm32/stm32f40xxx_i2c.c, arch/arm/src/stm32f0l0g0/stm32_i2c.c, arch/arm/src/stm32f7/stm32_i2c.c, arch/arm/src/stm32h5/stm32_i2c.c, arch/arm/src/stm32h7/stm32_i2c.c
Raise compilation error when I2C configuration is invalid. It's better to catch invalid clock configuration during compilation instead of producing binary that doesn't work as expected anyway.
instead of returning null pointer which must be caught during program execution, we now return an error during compilation
CI
=> arch/arm/stm32/i2c: raise compilation error when configuration is invalid

arch/xtensa/src/esp32s3/esp32s3_partition.c
arch/esp32s3_partition: Read data from SPI Flash at designated address (with decryption)
esp32s3 add  read partition interface with decryption
nsh> tc_ota_test --read_partion_decrypt
INFO: [label]:   otadataxx
OK:  get read decryption data from MTD
[CPU0] otadata (0x3ca02a00):
[CPU0] 0000  35 9b f2 07 b4 6d 40 89 28 b4 1e 22 98 7b 4a 36  5....m@.(..".{J6
[CPU0] 0010  ba 89 81 67 77 a3 60 5e 0a e7 51 01 b3 58 c2 f6  ...gw.`^..Q..X..
=> arch/esp32s3_partition: Read data from SPI Flash with decryption

Documentation/guides/index.rst, Documentation/guides/rust.rst
Add a new guide documenting how to integrate Rust with NuttX, including:
- Prerequisites and supported platforms
- Setup instructions for Rust toolchain
- Required NuttX configurations
- Example build and run instructions for RISCV32 target
The guide provides an experimental but working example of running
a Rust application on NuttX using the rv-virt:nsh board.
New doc
GitHub CI
=> Documentation: Add Rust integration guide for NuttX

arch/arm/src/stm32/stm32_spi.c
Add the stm32g4 series macros to the arch/arm/src/stm32/ stm32_spic.c file.
In the current code, there is no spi of stm32g4 series.
In the arch/arm/src/stm32/stm32_spi.c ,add CONFIG_STM32_STM32G4XXX.
NO
NO 
NO
NO 
NO 
NO
NO / YES 
ubuntu20.04
arm-none-eabi-gcc (15:9-2019-q4-0ubuntu1) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
This part of the code has passed the test BMI088 on stm32g4, and the SPI driver is used normally.
=> add the stm32g4 series spi

net/tcp/tcp_timer.c
when accept conn timeout, only accept conn itself should handle the event (send TCP_RESET), and there is no need to notify the listening conn. otherwise, the server's poll will return with POLLERR and POLLHUP. this may cause some applications to execute incorrect logic in the future.
cortex-m33 board
=> net/tcp_timer: remove tcp_callback(TIMEOUT) when accept conn timeout

boards/risc-v/esp32c3/esp32c3-generic/src/esp32c3_gpio.c, boards/risc-v/esp32c6/esp32c6-devkitc/src/esp32c6_gpio.c, boards/risc-v/esp32h2/esp32h2-devkit/src/esp32h2_gpio.c
Fixes https://github.com/apache/nuttx/issues/15456
Fix misconfigured pins for risc-v based esp chips
- esp32[c3|c6|h2]: Fix misconfigured gpio issue
ESP32C3, ESP32C6 and ESP32H2
`esp32c6-devkitc:gpio` configuration used with these commands:
```
gpio -t 1 /dev/gpio2
gpio -o 1 /dev/gpio0
gpio -o 1 /dev/gpio0
```
Output followed with an logic analyzer.
=> esp32[c3|c6|h2]: Fix misconfigured gpio issue

drivers/sensors/goldfish_sensor_uorb.c
Added the ability to set sampling rate for goldfish
Now goldfish sensor can adjust the sampling rate
qemu uorb_listener
=> goldfish_sensor_uorb.c: add set_interval for goldfish sensor

arch/arm64/include/irq.h, arch/arm64/src/common/arm64_initialstate.c, arch/arm64/src/common/arm64_vector_table.S, arch/arm64/src/common/arm64_vectors.S
```
The method is the same as the method of saving the current DAIF state of the thread
It will pave the way for the future implementation of hwasan's memory management
Allows each thread to independently control the mte switch function
```
=> arm64: Allows thread to independent control the switch of sctlr

boards/risc-v/esp32c6/esp32c6-devkitm/src/esp32c6_gpio.c
Fixes https://github.com/apache/nuttx/issues/15456
Fix misconfigured pins for esp32c6-devkitm
- esp32[c6]: Fix misconfigured pin functions for esp32c6-devkitm
Only ESP32C6-DevkitM
`esp32c6-devkitm:gpio` configuration used with these commands:
```
gpio -t 1 /dev/gpio2
gpio -o 1 /dev/gpio0
gpio -o 1 /dev/gpio0
```
Output followed with an logic analyzer.
=> esp32[c6]: Fix misconfigured pin functions for esp32c6-devkitm

arch/arm/src/armv7-a/arm_l2cc_pl310.c, arch/arm/src/armv7-r/arm_l2cc_pl310.c, arch/arm/src/armv8-r/arm_l2cc_pl310.c
Use small lock to protect register about l2cc, involving the following files:
arch/arm/src/armv7-a/arm_l2cc_pl310.c
arch/arm/src/armv7-r/arm_l2cc_pl310.c
arch/arm/src/armv8-r/arm_l2cc_pl310.c
arch/arm/src/armv7-a/arm_l2cc_pl310.c
arch/arm/src/armv7-r/arm_l2cc_pl310.c
arch/arm/src/armv8-r/arm_l2cc_pl310.c
CI
=> use small lock to protect register about l2cc in arch "arm"

arch/arm/src/armv6-m/arm_ramvec_attach.c, arch/arm/src/armv7-m/arm_ramvec_attach.c, arch/arm/src/armv8-m/arm_ramvec_attach.c
use small lock to protect g_ram_vectors,  involving armv6-m, armv7-m, armv8-m.
arch/arm/src/armv6-m/arm_ramvec_attach.c
arch/arm/src/armv7-m/arm_ramvec_attach.c
arch/arm/src/armv8-m/arm_ramvec_attach.c
CI
=> use small lock to protect g_ram_vectors

arch/arm/src/rp2040/rp2040_pio.c, include/nuttx/spinlock.h, sched/irq/irq_spinlock.c
sched: remove spin_lock_irqsave(NULL) support
sched
ci
=> sched: remove spin_lock_irqsave(NULL) support

tools/nxstyle.c
The zlib compression functions are used in network utilities for compression/decompression. These functions need to be added to the nxstyle white list to prevent style checking errors since they follow the zlib naming convention rather than NuttX's style guide.
Specifically, these functions are used in:
- apps/netutils/telnetc/telnetc.c for compressed data handling
nxstyle
Tested with apps/netutils/telnetc/telnetc.c , see https://github.com/apache/nuttx-apps/actions/runs/12707554430/job/35422711015?pr=2939
=> tools/nxstyle.c: Add missing zlib function names to white list

CMakeLists.txt
kconfiglib/mark: It should use pip instead of apt install
=> kconfiglib/mark: It should use pip instead of apt install

include/nuttx/nuttx.h
macro/align: Fix ALIGN_UP and ALIGN_DOWN
=> macro/align: Fix ALIGN_UP and ALIGN_DOWN

mm/mm_heap/mm.h, mm/mm_heap/mm_free.c, mm/mm_heap/mm_lock.c, mm/mm_heap/mm_malloc.c, mm/tlsf/mm_tlsf.c
mm: Add mm_lock_irq, mm_unlock_iq
=> mm: Add mm_lock_irq, mm_unlock_iq

arch/arm/src/common/Toolchain.defs, arch/arm/src/qemu/Kconfig, include/nuttx/addrenv.h, libs/libc/.gitignore, libs/libc/Makefile, libs/libc/modlib/Makefile, libs/libc/modlib/gnu-elf.ld.in
This allows apps for kernel mode NuttX (e.g. on arm/qemu-armv7a) can be built as executable type ELF files. Benefits of executable programs are smaller in size and easier GDB debugging.
Initial scope was only for qemu-armv7a but it used an almost duplicated `gnu-elf.ld` which differs only at `.text` and `.data` addresses from the `gnu-elf.ld` in modlib.  
To avoid such duplications, a preprocessed `gnu-elf.ld` in modlib is added  so that to adapt to target config. This requires minor tweaks for `addrenv.h` so that some macros can be included in `gnu-elf.ld.in`.
Hardware: qemu-armv7a or using kernel build.
- local checks with QEMU v6.2 on Ubuntu 22.04: `qemu-armv7a:knsh`, `bl602evb:elf`.
- CI checks
=> modlib: preprocess gnu-elf.ld for executable ELF

drivers/vhost/vhost-rng.c, drivers/vhost/vhost.c
vhost compile error as below:
```
vhost/vhost-rng.c:154:9: error: too few arguments to function 'virtio_create_virtqueues'
154 |   ret = vhost_create_virtqueues(hdev, 0, 1, vqnames, callback);
```
```
vhost/vhost.c: In function 'vhost_status_driver_ok': vhost/vhost.c:86:20: error: too few arguments to function 'virtio_get_status'
86 |   uint8_t status = vhost_get_status(hdev);
```
vhost
CI
=> drivers/vhost: fix compile error while get vhost status.

mm/mempool/mempool.c
If thread 1 is executing kasan_unpoison but a scheduling occurs and the block is trampled upon, the displayed backtracking may still be from the previously allocated backtracking
=> mempool: addbacktrace should be before kasan_unpoison

drivers/timers/Kconfig, drivers/timers/watchdog.c, include/nuttx/timers/watchdog.h
Add support for watchdog timer notifer chain so that users 
can customize the callback function when the watchdog timer 
times out which enabled by Auto-monitor.
Some watchdog timers support an interrupt on timeout and allow 
the user to perform some custom processing actions instead of 
immediately sending a reset signal. However, when watchdog 
timer is managed by auto-monitor, users can no longer register 
the timeout callback function implemented by users for watchdog 
timer through ioctl.
We provide CONFIG_WATCHDOG_TIMEOUT_NOTIFIER to enable 
or disable watchdog timer notifier chain, This option depends 
on CONFIG_WATCHDOG_AUTOMONITOR.
After the watchdog timer notifier chain is enabled, user can put the 
watchdog_automonitor_timeout function in the timeout interrupt handler 
of the …
=> drivers/timers/watchdog: add watchdog timer notifier chain

CMakeLists.txt, arch/sim/src/cmake/Toolchain.cmake
Hi,
The sim arch will generate warning when compiled with cmake in linux host. I'm use ubuntu, and the gcc version is 14.2.0, ld version is 2.43.1:
> [ 99%] Generating nuttx.rel
> **/usr/bin/ld: warning: arch_setjmp_x86_64.S.o: missing .note.GNU-stack section implies executable stack**
> **/usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker**
> [ 99%] Built target nuttx-rel
> [ 99%] Building C object CMakeFiles/nuttx.dir/empty.c.o
> [ 99%] Linking C executable nuttx
> **/usr/bin/ld: warning: nuttx.rel: requires executable stack (because the .note.GNU-stack section is executable)**
> [100%] Built target nuttx
The build command is as follows:
> cmake -B build -DBOARD_CONFIG=sim:nsh
>cmake --build build
One is a linking warning for nuttx, and …
=> sim: Fixes the linker 'noexecstack' warning

arch/risc-v/src/common/Toolchain.defs
This fix the issue that `-r` is blindly used when linking kernel build apps. The option should only be used when `BINFMT_ELF_RELOCATABLE` is selected.
RiscV kernel build with EXECUTABLE apps format.
- locally with `rv-virt:knsh64`
- CI checks
=> riscv/Toolchain.defs: guard -r use

arch/arm/src/imx9/imx9_lpi2c.c, arch/arm/src/imxrt/imxrt_lpi2c.c, arch/arm/src/s32k1xx/s32k1xx_lpi2c.c, arch/arm/src/s32k3xx/s32k3xx_lpi2c.c, arch/arm64/src/imx9/imx9_lpi2c.c, binfmt/binfmt_copyactions.c, libs/libbuiltin/libgcc/profile.c, mm/iob/iob.h, mm/iob/iob_alloc.c, mm/iob/iob_initialize.c, sched/misc/coredump.c
macro/align: Use ALIGN_UP and ALIGN_DOWN uniformly
=> macro/align: Use ALIGN_UP and ALIGN_DOWN uniformly

sched/clock/clock_timekeeping.c
clock_timekeeping: remove enter_critical_section in sched/clock/clock_timekeeping.c
reason:
clock_timekeeping
ci
=> clock_timekeeping: remove enter_critical_section in sched/clock/clock_timekeeping.c

sched/clock/clock_adjtime.c
clock_adjtime: use small lock to protect g_adjtime_ppb g_adjtime_wdog
reason:
clock_adjtime
ci ostest
=> clock_adjtime: use small lock to protect g_adjtime_ppb g_adjtime_wdog

arch/arm/src/rp23xx/rp23xx_irq.c
Fixes https://github.com/apache/nuttx/issues/15503.
rp23xx
Running `raspberrypi-pico-2:nsh` on feather rp2350
=> arch/arm/rp23xx: Set priority for svcall exception

arch/x86_64/src/intel64/intel64_handlers.c
When assembly code calls a C function, it needs to save the context. After enabling KASAN, the inserted __asan_load8_noabort function uses the rsi register, causing the value of rsi in the interrupt handler to be modified, which results in an incorrect interrupt number.
=> arch/x86_64:Resolve the issue of abnormal interrupt numbers triggered when KASAN is enabled

sched/sched/sched_timerexpiration.c
sched_processtimer: use atomic to protect g_timer_interval and g_timer_tick
reason:
sched_processtimer
ci ostest
=> sched_processtimer: use atomic to protect g_timer_interval and g_timer_tick

arch/arm/src/armv7-a/arm_gicv2.c, arch/arm/src/qemu/qemu_irq.c
armv7a: Amp mode support
reason:
In AMP mode, we can also use SGI as an inter-core interrupt, and ensure that arm_gic0_initialize is called only once.
armv7a
ci
=> armv7a: Amp mode support

sched/misc/assert.c
Revert "sched: misc: Remove sched_lock in _assert()"
reason:
This reverts commit d0820acbbba213dbb7e4d1b7f38b6564d265660e assert will call syslog
assert
ci
=> Revert "sched: misc: Remove sched_lock in _assert()"

arch/arm64/src/imx9/imx9_edma.c
arch/arm64: fix typo spin_lock_irqsave -> spin_unlock_irqrestore
should be spin_unlock_irqrestore
N/A
ci-check
=> arch/arm64: fix typo spin_lock_irqsave -> spin_unlock_irqrestore

sched/clock/clock_initialize.c
sched/clock: remove unlock logic to avoid relock
get time spec before protect g_basetime
N/A
ci-check
=> sched/clock: remove unlock logic to avoid relock

CMakeLists.txt
Revert "kconfiglib/mark: It should use pip instead of apt install"
pip source is deprecated from ubuntu 24.04
This reverts commit 7c7a64c84c3fe1db492ff84c727e15dd4f82f147.
N/A
ci-check
=> Revert "kconfiglib/mark: It should use pip instead of apt install"

arch/arm/src/imx9/imx9_flexcan.c
arm/imx9: sched_unlock should called after spin_unlock()
fix deadlock if sched_unlock switch out to other task
N/A
ci-check
=> arm/imx9: sched_unlock should called after spin_unlock()

drivers/note/note_driver.c
drivers/note: fix typo falgs and align local name to irq_mask
N/A
ci-check
=> drivers/note: fix typo falgs and align local name to irq_mask

arch/arm/src/stm32l4/stm32l4_qencoder.c
arch/arm: fix regression by spinlock change
| commit c96b8cdfdd6ee007ad60818565d5fd1e802dc2e5
| Date:   Mon Dec 23 16:59:20 2024 +0800
|
|     use small lock in following files:
N/A
ci-check
=> arch/arm: fix regression by spinlock change

drivers/sensors/CMakeLists.txt, drivers/sensors/Kconfig, drivers/sensors/Make.defs, drivers/sensors/bmi088.c, drivers/sensors/bmi088_base.c, drivers/sensors/bmi088_base.h, drivers/sensors/bmi088_uorb.c, include/nuttx/sensors/bmi088.h
drivers/sensors/bmi088: add bmi088 driver.
Increase the driver of BMI088, convenient for everyone to use. Can open it using the device file interface or use the uorb interface.Currently support SPI, IIC interface has not been tested. Open with the following macro definition:
```
#define CONFIG_SENSORS_BMI088 1
#define CONFIG_SENSORS_BMI088_UORB 1
#define CONFIG_SENSORS_BMI088_SPI 1
```
Yes.
NO.
NO.
YES,add bmi088 driver.
NO.
NO.
NO.
Acceleration and gyroscope data have been tested by opening the bmi088 device file.
Opening and reading accelerometer and gyroscope data using IO multiplexing via the uorb interface was also tested.
ubuntu20.04
arm-none-eabi-gcc (15:9-2019-q4-0ubuntu1) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
=> drivers/sensors/bmi088: add driver for Bosch BMI088 IMU

arch/arm/src/goldfish/goldfish_memorymap.h
Adjust VIRT_FLASH_PSECTION from 0x00000000-0x08000000 -> 0x00600000-0x08000000.
The above changes avoid the problem of directly restarting in goldfish when the process accesses/executes at address 0x0 without causing assert.
Adjusted the MPU range so we can better expose potential issues
Target(s): Goldfish-armv7a
Trigger assert when accessing an illegal address (0x0)
```
goldfish-armv7a-ap> xd 0x0 1024
Hex dump:
[   18.260700] [ 7] [ ALERT] [ap] arm_dataabort: Data abort. PC: 006332a0 DFAR: 00000000 DFSR: 00000005
[   18.261200] [ 7] [ ALERT] [ap] dump_assert_info: Current Version: NuttX  12.3.0 6d136cef66e Jan 14 2025 01:53:56 arm
[   18.261600] [ 7] [ ALERT] [ap] dump_assert_info: Assertion failed panic: at file: armv7-a/arm_dataabort.c:161 task: nsh_main …
```
=> goldfish_memorymap:Resize VIRT_FLASH_PSECTION

arch/risc-v/src/esp32c3-legacy/esp32c3_wifi_adapter.c, arch/risc-v/src/esp32c3/esp_wifi_adapter.c, arch/risc-v/src/esp32c6/esp_wifi_adapter.c, arch/xtensa/src/esp32/esp32_wifi_adapter.c, arch/xtensa/src/esp32s2/esp32s2_wifi_adapter.c
mirror a wifi deadlock fix to espressif variants.
not tested.
i don't have hardware handy.
=> mirror a wifi deadlock fix to espressif variants

fs/procfs/fs_procfs.c
This issue aims to fix some problems caused by the previously introduced fs_heap (https://github.com/apache/nuttx/pull/13722) feature.
Different modules in the kernel have their own procfs, such as net-procfs, and they may have their own private handles. When we use fs_heap, the kmm heap and fs heap are not in the same area. In this way, the corresponding destructor should be executed when procfs_closedir is executed uniformly, avoiding assertions caused by releasing in different heaps.
If the module's procfs provides a destructor, it is executed. Otherwise, priv is released via fs_heap_free
Adjusted the handling of procf_closedir in fs_procfs.c.
Target(s): Goldfish-armv7a
In a qemu configured with fs_heap, we use the command ifconfig (because it uses …
=> fs_procfs:Fix closedir should handle the release dir handle on a case-by-case basis

arch/arm/src/common/arm_fork.c
This tries to fix armv7-a kernel build `vfork()`. In kernel mode, forked child needs copying parents userspace stack instead.
Devices using armv7-a kernel mode, such as qemu-armv7a:knsh.
- local checks with `qemu-armv7a:knsh`
- CI checks
=> arch/armv7a: fix vfork for KERNEL build

libs/libc/modlib/gnu-elf.ld.in
```
arch/risc-v/src/common/riscv_addrenv.c:418:
{
...
database = resvbase + MM_PGALIGNUP(resvsize) + ARCH_DATA_RESERVE_SIZE;
...
}
```
if not add MM_PGALIGNUP(resvsize), will mismatch address load .data section
risc-v:fix modlib load exe elf data section mismatch
risc-v elf load
risc-v:knsh with hello apps:
```
static char test_static[] = "Testing Static Var";
int main(int argc, FAR char *argv[]) {
printf("test_static=%s\n", test_static);
printf("Address of test_static=%p\n", test_static);
return 0;
}
```
and output:
```
NuttShell (NSH) NuttX-12.7.2-vela
nsh> hello
test_static=Testing Static Var
Address of test_static=0xc0101200
nsh> QEMU: Terminated
```
fix it https://github.com/apache/nuttx/issues/15526
=> modlib:gnu-elf.ld.in load exe elf data section mismatch

tools/gcov.py
When the copy path is a subdirectory of the source path, the copy will occur recursively
=> gcov.py: add copy skip paths, prevent recursion

Documentation/components/drivers/special/sensors/mcp9600.rst, boards/arm/rp2040/common/src/rp2040_common_bringup.c, drivers/sensors/Kconfig, drivers/sensors/Make.defs, drivers/sensors/mcp9600.c, include/nuttx/sensors/mcp9600.h
This PR is from InSpace.
This pull request introduces a new sensor driver for the Mirochip MCP9600 thermocouple amplifier. It is on a popular Adafruit breakout for hobbyists and also happens to be the amplifier used on our hybrid rocket control system.
This PR also comes with a documentation page for how to use the `SNIOC` commands with this device.
This PR adds another usable device to the NuttX roster. It will be appreciated by hobbyists that own this board.
Tested using a Raspberry Pi Pico connected to the Adafruit breakout module. I connected the thermocouple owned by InSpace and verified that the temperature readings were correct.
Tested with K type thermocouple.
=> drivers/sensors: Wrote a driver for the MCP9600 thermocouple amplifier.

arch/avr/src/at90usb/at90usb_usbdev.c
Use small lock to protect usbdev and endpoint in AVR.
nuttx/arch/avr/src/at90usb/at90usb_usbdev.c
CI
=> Use small lock to protect usbdev and endpoint in AVR.

arch/sim/src/sim/sim_usbdev.c
Use small lock to protect usbdev and endpoint in sim.
nuttx/arch/sim/src/sim/sim_usbdev.c
CI
=> Use small lock to protect usbdev and endpoint in sim.

fs/fs_heap.c, fs/fs_heap.h, fs/procfs/fs_procfsproc.c
1. Added fs_heap_mallinfo_task implementation.
2. Change fs_heap_mallinfo_task in proc_heap back to kmm_mallinfo_task.
Passed the file system related syscall test
=> Add fs_heap_mallinfo_task and fix proc_heap bug

arch/mips/src/pic32mx/pic32mx_usbdev.c
Use small lock to protect usbdev and endpoint in mips.
nuttx/arch/mips/src/pic32mx/pic32mx_usbdev.c
CI
=> Use small lock to protect usbdev and endpoint in mips.

arch/arm/src/sama5/sam_hsmci.c, arch/arm/src/samv7/sam_hsmci.c, fs/mount/fs_automount.c, sched/wqueue/kwork_cancel.c, sched/wqueue/kwork_notifier.c, sched/wqueue/kwork_queue.c, sched/wqueue/kwork_thread.c, sched/wqueue/wqueue.h
we use small lock to replace enter_critical_section to avoid busywait
reason:
We decouple semcount from business logic
by using an independent counting variable,
which allows us to remove critical sections in many cases.
work queue
Build Host:
OS: Ubuntu 20.04
CPU: x86_64
Compiler: GCC 9.4.0
$ make
$ qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic
-machine virt,virtualization=on,gic-version=3
-net none -chardev stdio,id=con,mux=on -serial chardev:con
=> wqueue remove enter_critical_section 

drivers/syslog/syslog_intbuffer.c
Fixed the issue of using SPINLOCK + SYSLOG_INTBUFFER in single core causing recursive spinlock during assert.
```
dump_running_task
-> ...
-> syslog_write
-> syslog_add_intbuffer (spin_lock_irqsave_wo_note first)
-> syslog_flush_internal (spin_lock_irqsave_wo_note recursive)
```
Removed spinlock protection in syslog_flush_internal and added spinlock where it is called.
Target(s): …
=> syslog_intbuffer.c:Fixed recursive spinlock during assert

boards/xtensa/esp32s3/esp32s3-devkit/configs/usbnsh/defconfig, boards/xtensa/esp32s3/esp32s3-eye/configs/usbnsh/defconfig, boards/xtensa/esp32s3/esp32s3-lhcbit/configs/usbnsh/defconfig, boards/xtensa/esp32s3/esp32s3-meadow/configs/usbnsh/defconfig
ESP32S3 on the usbnsh defconfig fails to bring up the expected ttyACMx when DEBUG_ASSERTIONS are enabled.
After reset, the ACM0 comes up and quickly disconnects. Somehow, it worked without DEBUG_ASSERTIONS.
Issue was found to be a assignment of `/dev/console` on both CDC_ACM and DEV_CONSOLE setup, which would returned a negated ERRNO on `group_setupidlefiles`.
This PR disables `CONFIG_DEV_CONSOLE` and fixes the issue.
Allows use of esp32s3-devkit:usbnsh when DEBUG_ASSERTIONS are enabled.
Manually tested this defconfig in many reset scenarios.
Internal CI testing as well.
=> boards/xtensa: disable DEV_CONSOLE on usbnsh defconfig

arch/sim/src/sim/posix/sim_hostfs.c
This PR comes from the discussion of https://github.com/apache/nuttx/pull/15535#event-15924592365.
A common conversion interface `host_errno_convert` is provided in `arch/sim/posix`. Subsequent contributors with needs can add host to nuttx errno conversion here
Modified all places where errno is returned in `arch/sim/posix` to be converted via `host_errno_convert` before returning (current implementation is to return directly)
```
nsh> cmocka_fs_test
[==========] nuttx_fs_test_suites: Running 41 test(s).
[ RUN      ] test_nuttx_fs_creat01
[       OK ] test_nuttx_fs_creat01
[ RUN      ] test_nuttx_fs_dup01
[       OK ] test_nuttx_fs_dup01
[ RUN      ] test_nuttx_fs_fcntl01
[       OK ] test_nuttx_fs_fcntl01
[ RUN      ] test_nuttx_fs_fstat01
[ …
```
=> sim_hostfs:add host_errno_convert API for convert result

arch/arm/include/stm32h5/chip.h, arch/arm/src/stm32h5/Make.defs, arch/arm/src/stm32h5/chip.h, arch/arm/src/stm32h5/hardware/stm32_sbs.h, arch/arm/src/stm32h5/stm32_ethernet.c, arch/arm/src/stm32h5/stm32_ethernet.h, arch/arm/src/stm32h5/stm32_uid.c, arch/arm/src/stm32h5/stm32_uid.h, arch/arm/src/stm32h5/stm32h5xx_rcc.c, boards/arm/stm32h5/nucleo-h563zi/include/board.h
STM32H5 Ethernet Driver. This driver is heavily based on the STM32H7 because the Ethernet peripheral on the STM32H5 is essentially identical to that on the STM32H7. 
Differences from the STM32H7:
1. stm32_uid.c - Reading the device electronic signature 8-bits at a time (like the H7) caused an exception. The code was modified to access the device electronic signature 32-bits at a time. 
2. ETH_SEL_PHY - These bits are located in the SBS_PMCR register on the STM32H5. This is different on the STM32H7. This change also required enabling SBS peripheral when Ethernet is configured. 
Note: ICACHE and DCACHE not yet implemented on STM32H5. 
STM32H5 Architecture
Hardware:
1. Nucleo-H563ZI
2. USB-to-Ethernet adapter (for test device)
Software:
1. Ping
2. Phy Tool (mdio)
3. ifconfig
Configuration: …
=> Add STM32H5 Ethernet Driver

libs/libc/misc/lib_tempbuffer.c
libs/lib_tempbuffer: set `errno` when fails
lib_get_tempbuffer()
CI
=> libs/lib_tempbuffer: set `errno` when fails

libs/libc/gnssutils/Make.defs
- Removed explicit -std=c99 flag from Make.defs
- The project-wide C standard is already set at a higher level
- Keeps build configuration consistent across the codebase
- No functional changes to the code
- Maintains consistency with project-wide C standard settings
GitHub CI
=> libc/gnssutils: remove C99 standard flag from Make.defs

libs/libc/machine/risc-v/arch_elf.c
- Replace direct use of `fence.i` instruction with `__ISB()` macro for instruction synchronization
- This change improves portability while maintaining the same functionality
- No functional changes - both `fence.i` and `__ISB()` ensure instruction synchronization on RISC-V
- Makes the code more maintainable by using the architecture abstraction layer
GitHub CI and local test
=> risc-v: replace fence.i with __ISB for instruction sync

include/nuttx/wdog.h, sched/wdog/wd_cancel.c
sched/wdog: remove wd_cancel_irq() implement
we do not need this implement after change the lock from csec to spin_lock
N/A
ci-check
=> sched/wdog: remove wd_cancel_irq() implement

sched/wqueue/kwork_notifier.c
sched/wqueue: fix potential deadlock
sched_unlock() should called after spin_unlock
N/A
ci-check
=> sched/wqueue: fix potential deadlock

boards/arm/rp2040/common/src/rp2040_common_bringup.c, include/nuttx/sensors/msxxxx_crc4.h
This PR comes from InSpace.
For some reason, the CRC check in its current state fails for the MS5611 sensors that InSpace has. We've tested on four different sensors to confirm that this is not due to the sensors being faulty. The official CRC4 code from the manufacturer is slightly different than the NuttX implementation and it passes when used on the MS5611s.
MS56xx driver no longer fails to register due to faulty CRC.
Tested the previous version of the driver on 4 different MS5611s and viewed failing CRC in the debug logs. Then tested with this version from the manufacturer and had successful device registration.
=> Fix CRC and test on Raspberry Pi Pico

drivers/mtd/Kconfig, drivers/mtd/Make.defs, drivers/mtd/gd55.c, include/nuttx/mtd/mtd.h, include/nuttx/spi/qspi.h
This adds support for the GigaDevice QSPI GD55 NOR Flash devices
None, other than adding new device support
On a custom board using SAMA5D27C-D1G with a single GD55B01G 1Gbit device. Device has been partioned, fully and partially erased, written to and protected in various ways and checked that the protected areas report as locked correctly. Some performance measruerments taken and it behaves well.
Support has been added for the 2Gbit device "in good faith" but I have no board with this device to hand to check it.
=> Add GD55 QSPI NOR Flash support

Documentation/components/drivers/special/sensors/sht4x.rst, boards/arm/rp2040/common/src/rp2040_common_bringup.c, drivers/sensors/CMakeLists.txt, drivers/sensors/Kconfig, drivers/sensors/Make.defs, drivers/sensors/sht4x_uorb.c, include/nuttx/sensors/sht4x.h
This PR converts the SHT4X driver to the UORB framework.
The impact is that one more sensor is part of the UORB framework, which unifies the way that sensors are interacted with under NuttX and provides lots of beneficial features such as configurable sampling rates and buffering for free from the UORB upper half.
To test, I compiled and built the driver for the Raspberry Pi Pico W and included the `uorb_listener` application. The driver correctly registers the two topics (relative humidity and ambient temperature) which produce measurements at the configured interval. I tested using multiple different intervals from 1Hz to 100Hz.
```console
nsh> uorb_listener
Mointor objects num:2
object_name:sensor_temp, object_instance:0
object_name:sensor_humi, object_instance:0 …
```
=> sensors/sht4x: Converted SHT4X driver to UORB framework.

drivers/input/Kconfig, drivers/input/mouse_upper.c, drivers/misc/rpmsgdev.c, include/nuttx/fs/ioctl.h, include/nuttx/input/mouse.h
Support for the mouse ioctl interface
mouse driver
qemu
=> Support for the mouse ioctl interface

arch/Kconfig
This allows using FLASH_START and FLASH_SIZE configs for chips without MMU by relaxing the guarding conditions.
Devices without MMU can have FLASH config
- local checks with `rv-virt:nsh`, `qemu-armv7a:nsh`
- CI checks
=> arch/Kconfig: allow FLASH config w/o MMU

sched/wqueue/kwork_queue.c
sim: fix regression from https://github.com/apache/nuttx/pull/14623
reason:
work_timer_expiry may be called in thread context
sim
https://github.com/apache/nuttx/issues/15582
=> sim: fix regression from https://github.com/apache/nuttx/pull/14623

arch/arm/src/armv7-r/gic.h
This fixes compilation error:
```
/tmp/nuttx/arch/arm/src/armv7-r/gic.h:699:17: error: 'GIC_ICDSGIR_NSATT_GRP1' undeclared (first use in this function); did you mean 'GIC_ICDSGIR_NSATT'?
```
Allow armv7-r code to build
- local check when adding armv7-r support.
- CI checks
=> arch/armv7-r: fix gic.h build error

include/nuttx/addrenv.h, libs/libc/modlib/gnu-elf.ld.in
This fixes booting issue of qemu-armv7a:knsh + ELF_EXECUTABLE by aligning formula of armv7-a with its current addrenv layout.
This is a follow up of pull/15527.
Kernel mode with ELF_EXECUTABLE config selected.
- local checks with qemu-armv7a:knsh + ELF_EXECTUABLE, rv-virt:knsh
- CI checks
=> modlib: fix armv7a w/ unified gnu-elf.ld.in

tools/testbuild.sh
In the Msys2 (Windows) environment, this search filter is not sufficient.
https://github.com/apache/nuttx/blob/8f435a2941778a45e348cdea6453bd6b68680cbe/tools/testbuild.sh#L327
https://github.com/apache/nuttx/blob/8f435a2941778a45e348cdea6453bd6b68680cbe/tools/testbuild.sh#L350
$ grep _TOOLCHAIN_ .config | grep -v CONFIG_ARCH_TOOLCHAIN_* | grep =y 
CONFIG_TOOLCHAIN_WINDOWS=y
CONFIG_ARM_TOOLCHAIN_GNU_EABI=y
It is necessary to add
$ grep _TOOLCHAIN_ .config |  grep -v CONFIG_TOOLCHAIN_WINDOWS | grep -v CONFIG_ARCH_TOOLCHAIN_* | grep =y CONFIG_ARM_TOOLCHAIN_GNU_EABI=y
fixed
```
Cmake in present: nucleo-l152re/nsh,CONFIG_ARM_TOOLCHAIN_GNU_EABI
Configuration/Tool: nucleo-l152re/nsh,CONFIG_ARM_TOOLCHAIN_GNU_EABI …
```
=> [CI] testbuild.sh: Msys2 fix toolchain change

cmake/nuttx_mkconfig.cmake
cmake/mkconfig: add support of set custom command options to config.h
add support of set custom command options to config.h
Use the -D parameter to pass the config to header file.
NOTE which must begin with the CONFIG_ prefix.
eg:
```
cmake -DCONFIG_AAA=1 -DCONFIG_BBB=1 -B build -DBOARD_CONFIG=sim/nsh -GNinja
```
source file:
```
#include <nuttx/config.h>
{
#ifdef CONFIG_AAA
printf("Hello, World!! AAA: %d\n", CONFIG_AAA);
#endif
#ifdef CONFIG_BBB
printf("Hello, World!! BBB: %d\n", CONFIG_BBB);
#endif
return 0;
}
```
output:
```
$ ./build/nuttx 
NuttShell (NSH) NuttX-10.4.0
nsh> hello
Hello, World!! AAA: 1
Hello, World!! BBB: 1
nsh> 
```
N/A
ci-check
=> cmake/mkconfig: add support of set custom command options to config.h

arch/risc-v/src/mpfs/mpfs_entrypoints.c, arch/risc-v/src/mpfs/mpfs_opensbi.c, arch/risc-v/src/mpfs/mpfs_opensbi_utils.S
No reason to keep asking for these over and over. Also fix bumping the CPU booted counter when SBI is enabled.
MPFS bootloader only, performance optimization and fix issue with g_cpus_booted global variable.
MPFS
=> mpfs_opensbi_setup: Provide hartid and next_addr as parameters

cmake/nuttx_add_library.cmake, cmake/nuttx_mkconfig.cmake
cmake: Use EXTRAFLAGS to define customized compilation options
align them with the usage habits of makefile
cmake:
```
cmake -B build -DBOARD_CONFIG=sim/nsh -GNinja -DEXTRAFLAGS="-DCONFIG_AAA=1 -DCONFIG_BBB=1 -Werror"
```
makefile:
```
make -j12 EXTRAFLAGS="-DCONFIG_AAA=1 -DCONFIG_BBB=1 -Werror"
```
N/A
ci-check
=> cmake: Use EXTRAFLAGS to define customized compilation options

arch/arm/src/rp2040/rp2040_xosc.c, arch/arm/src/rp23xx/rp23xx_xosc.c, boards/arm/rp2040/adafruit-feather-rp2040/include/board.h, boards/arm/rp2040/adafruit-kb2040/include/board.h, boards/arm/rp2040/adafruit-qt-py-rp2040/include/board.h, boards/arm/rp2040/pimoroni-tiny2040/include/board.h, boards/arm/rp2040/raspberrypi-pico-w/include/board.h, boards/arm/rp2040/raspberrypi-pico/include/board.h, boards/arm/rp2040/seeed-xiao-rp2040/include/board.h, boards/arm/rp2040/w5500-evb-pico/include/board.h, boards/arm/rp2040/waveshare-rp2040-lcd-1.28/include/board.h, boards/arm/rp2040/waveshare-rp2040-zero/include/board.h, boards/arm/rp23xx/pimoroni-pico-2-plus/include/board.h, boards/arm/rp23xx/raspberrypi-pico-2/include/board.h
On some boards, the 1ms startup delay for the XOSC isn't sufficient, and NuttX can fail to start. (Depending on how the board was was reset.) To fix this, the delay has to be increased of affected boards, so this adds a configuration in `board.h`.
https://github.com/raspberrypi/pico-sdk/pull/457 changed this in pico-sdk, and talks a bit about why this is needed.
For the Adafruit RP2040 boards and the Seeed XIAO, affected boards should now boot properly. At the cost of about 64ms delay on start.
Behavior should be entirely unchanged on other boards.
* `adafruit-feather-rp2040:usbnsh` works on my unit before and after this change; so the one I have isn't affected, or it's very intermittent
* I needed this fix for NuttX to start properly on power on reset or when plugged in on my Feather …
=> arm/rp2040,rp2350: Allow configuring XOSC startup delay, and set similarly to pico-sdk

sched/misc/coredump.c
elf_emit_tcb_note: nitems(status.pr_regs) is 18, g_tcbinfo.regs_num is 17, then g_tcbinfo.reg_off.p[17] has been out of bounds, this will cause random failures of the coredump function
coredump
arm v7m
=> fix coredump failed when loop counts exceeds the limit

arch/arm/src/cxd56xx/cxd56_usbdev.c, arch/arm/src/dm320/dm320_usbdev.c, arch/arm/src/efm32/efm32_usbdev.c, arch/arm/src/imxrt/imxrt_usbdev.c, arch/arm/src/kinetis/kinetis_usbdev.c, arch/arm/src/lpc17xx_40xx/lpc17_40_usbdev.c, arch/arm/src/lpc214x/lpc214x_usbdev.c, arch/arm/src/lpc31xx/lpc31_usbdev.c, arch/arm/src/rp2040/rp2040_usbdev.c, arch/arm/src/rp23xx/rp23xx_usbdev.c, arch/arm/src/samv7/sam_usbdevhs.c, arch/arm/src/stm32/stm32_usbdev.c, arch/arm/src/stm32f0l0g0/stm32_usbdev.c, arch/arm/src/stm32l4/stm32l4_usbdev.c
Use small lock to protect usbdev and endpoint in arch ARM.
arch/arm/src/cxd56xx/cxd56_usbdev.c
arch/arm/src/dm320/dm320_usbdev.c
arch/arm/src/efm32/efm32_usbdev.c
arch/arm/src/imxrt/imxrt_usbdev.c
arch/arm/src/kinetis/kinetis_usbdev.c
arch/arm/src/lpc17xx_40xx/lpc17_40_usbdev.c
arch/arm/src/lpc214x/lpc214x_usbdev.c
arch/arm/src/lpc31xx/lpc31_usbdev.c
arch/arm/src/rp2040/rp2040_usbdev.c
arch/arm/src/rp23xx/rp23xx_usbdev.c
arch/arm/src/samv7/sam_usbdevhs.c
arch/arm/src/stm32/stm32_usbdev.c
arch/arm/src/stm32f0l0g0/stm32_usbdev.c
arch/arm/src/stm32l4/stm32l4_usbdev.c
include/nuttx/usb/usbdev.h
CI
=> Use small lock to protect usbdev and endpoint in arch ARM.

Documentation/applications/system/uorb/index.rst
Documentation: Replace NSH_LINELEN with LINE_MAX
forget in:
```
commit 38a0049f564edcfa5e68cf80256752b3c2bd790a
Author: Xiang Xiao <xiaoxiang@xiaomi.com>
Date:   Sun Jan 19 11:59:01 2025 +0800
Documentation: Replace NSH_LINELEN with LINE_MAX
```
N/A
ci-check
=> Documentation: Replace NSH_LINELEN with LINE_MAX

Documentation/components/filesystem/index.rst, Documentation/components/filesystem/v9fs.rst, fs/v9fs/CMakeLists.txt, fs/v9fs/Kconfig, fs/v9fs/Make.defs, fs/v9fs/client.c, fs/v9fs/client.h, fs/v9fs/socket_9p.c, fs/v9fs/transport.c, net/bluetooth/bluetooth_recvmsg.c, net/can/can_recvmsg.c, net/icmp/icmp_recvmsg.c, net/icmpv6/icmpv6_recvmsg.c, net/ieee802154/ieee802154_recvmsg.c, net/inet/inet_sockif.c, net/local/local_recvmsg.c, net/netlink/netlink_sockif.c, net/pkt/pkt_recvmsg.c, net/rpmsg/rpmsg_sockif.c, net/socket/recvmsg.c, net/tcp/tcp_recvfrom.c, net/udp/udp_recvfrom.c, net/usrsock/usrsock_recvmsg.c
In https://github.com/apache/nuttx/pull/13001, I added a new distributed file system in NuttX, which only supports VIRTIO as a data transmission method.
In this PR, I implemented a Socket-based transmission method, so that V9FS can access the content on the Host based on the Socket method, which is suitable for more scenarios.
I also added the V9FS document to explain how to use it.
In short:
- mplemented a socket-based v9fs driver
- Enhanced Net-related, now TCP supports multi-segment IOV sending
- Added V9FS Document
1. Enhanced NET related changes, now TCP supports multi-segment IOV mode sending.
2. V9FS supports socket as a transmission medium
3. Added V9FS Document
Target(s): qemu
Passed local file system related tests
=> v9fs:Add socket support

Documentation/guides/rust.rst
- Fixed a typo in the Rust guide ("Pleae" -> "Please")
- Improved list formatting for better readability and consistency
- Improves documentation quality and readability
- Ensures users have complete and accurate configuration information
- Maintains consistency with the actual requirements for Rust development in NuttX
GitHub CI and local doc build
=> Documentation: Fix typo and list format in Rust guide

drivers/syslog/syslog_intbuffer.c
syslog/intbuffer: fix spinlock deadlock
just read the code, still have the deadlock after below change:
```
| commit 3b6f463ce2b54d1934e4357b4ea1d81635161c95
| Author: chenrun1 <chenrun1@xiaomi.com>
| Date:   Tue Dec 31 14:31:46 2024 +0800
|
|     syslog_inbuffer:Fixed the lock reentry issue in single core + spinlock scenario
|
|     Summary:
|       When spinlock.h is enabled in a single-core scenario, spinlock reentry and exceptions may occur when spin_lock_irqsave_wo_note is used in syslog_add_intbuffer
|
|     Signed-off-by: chenrun1 <chenrun1@xiaomi.com>
```
N/A
ci-check
=> syslog/intbuffer: fix spinlock deadlock

drivers/sensors/bmi088_uorb.c, drivers/sensors/bmi160_uorb.c, drivers/sensors/ds18b20_uorb.c, drivers/sensors/goldfish_sensor_uorb.c, drivers/sensors/hyt271_uorb.c, drivers/sensors/l3gd20_uorb.c, drivers/sensors/sensor.c, drivers/sensors/sht4x_uorb.c, include/nuttx/sensors/sensor.h, include/nuttx/uorb.h
new sensor type:
SENSOR_TEMPERATURE
SENSOR_TYPE_ACCELEROMETER_UNCALIBRATED
SENSOR_TYPE_GYROSCOPE_UNCALIBRATED
SENSOR_TYPE_MAGNETIC_FILED_UNCALIBRATED
refs:
https://cs.android.com/android/_/android/platform/hardware/libhardware/+/0e67aa0caee9500b61b9c1c8b6e5cab18301364c:include_all/hardware/sensors-base.h
add new sensor type
local test
=> drivers/sensor: add new sensot type to align android sensor type

drivers/serial/serial_gdbstub.c, include/nuttx/gdbstub.h, libs/libc/gdbstub/lib_gdbstub.c
Add const to send buffer.
I have searched and corrected `gdb_state_init ` where the function signature should be changed.
Should not have impact on existing project.
Build pass locally. CI needs https://github.com/apache/nuttx-apps/pull/2958 to pass.
=> gdbstub: add const to send buffer

arch/risc-v/src/mpfs/mpfs_i2c.c, drivers/video/fb.c, include/pthread.h, libs/libc/pthread/pthread_barrierdestroy.c, libs/libc/pthread/pthread_conddestroy.c, sched/pthread/pthread.h, sched/pthread/pthread_condbroadcast.c, sched/pthread/pthread_condclockwait.c, sched/pthread/pthread_condsignal.c, sched/pthread/pthread_condwait.c
The load/compare and RMW to wait_count need protection. Using atomic
operations should resolve both issues.
NOTE:
The assumption that the user will call pthread_cond_signal / pthread_cond_broadcast with the mutex given to pthread_cond_wait held is simply not true. It MAY hold it, but it is not forced. Thus, using the user space lock for protecting the wait counter as well is not valid!
This fixes regression from https://github.com/apache/nuttx/pull/14581 and https://github.com/apache/nuttx/pull/14786
MPFS with multiple threads using pthread_cond.
rv-virt:smp64
Direct reference from POSIX:
The pthread_cond_signal() or pthread_cond_broadcast() functions may be called by a thread whether or not it currently owns the mutex that threads calling pthread_cond_wait() or pthread_cond_timedwait() …
=> pthread_cond_wait: Use atomic_t to protect the waiter count

drivers/ioexpander/mcp23x08.c, include/nuttx/ioexpander/mcp23x08.h
This patch fix mcp23x08 support. Issue #15592
=> drivers: mcp23x08 add missing header and fix some defines

libs/libc/gdbstub/lib_gdbstub.c
Minor fixed to GDB stub:
1. Fix all typo
2. Use lib_syslograwstream_s to output `\n` only when we want, to make debug easier.
No impact.
Tested on `mps3-an547:nsh` and `stm32f429i-disco:gdbstub`
=> gdbstub: typo and log fixes

Documentation/components/drivers/special/sensors/mcp9600.rst, boards/arm/rp2040/common/src/rp2040_common_bringup.c, drivers/sensors/Kconfig, drivers/sensors/Make.defs, drivers/sensors/mcp9600_uorb.c, include/nuttx/sensors/ioctl.h, include/nuttx/sensors/mcp9600.h, include/nuttx/uorb.h
This PR is from InSpace.
This PR moves the MCP9600 sensor implementation over to the UORB framework instead of the legacy structure, as per suggestions on #15525.
This also adds a dedicated `SNIOC` command for configuring the thermocouple type of a device (for amplifiers which support multiple types).
I have also updated the documentation of the MCP9600 to reflect the changes.
Finally, this also changes the `SENSOR_TYPE_AMBIENT_TEMPERATURE` macro to `SENSOR_TYPE_TEMPERATURE` macro, since the distinction is not required and prevents confusion about some sensor topics being for ambient temperature while others measure the direct temperature of an object.
I have deliberately split the PR into two commits since renaming the macro I believe deserves its own distinct commit with a different …
=> MCP9600 UORB implementation

Documentation/components/drivers/special/sensors/sensors_uorb.rst
update Documentation about uorb, is related to PR https://github.com/apache/nuttx/pull/15610
update doc
make html
=> Documentation/uorb: remove uncalibrated member

Documentation/guides/rust.rst
Please refer to https://github.com/rust-lang/rust/pull/135757
- Updated the supported platforms list in the Rust guide to reflect that ARMv7-A and AArch64 are ready
- Removed the "WIP" (Work In Progress) label from ARMv7-A and AArch64 in the supported platforms section
- Provides accurate information to developers about the current state of Rust support for ARMv7-A and AArch64 platforms
- Aligns the documentation with the latest developments in the Rust ecosystem
- No functional changes to the codebase, only documentation updates
Doc build
=> Documentation: Update supported platforms for Rust guide

boards/arm/qemu/qemu-armv7r/src/qemu_bringup.c
Fixes typo in comment: rename imx_bringup as qemu_bringup, as pointed out in #15593
None
CI checks
=> boards/qemu-armv7r: fix typo

arch/xtensa/src/esp32s3/esp32s3_psram_octal.c
* Fix wrong dummy length in mode register reading.
Corresponding link: https://github.com/espressif/esp-idf/commit/54a9386b2e6426e73b117144b430d225f4ab5735      
* Fix the issue of occasional initialization failure of SPIRAM
* Internal CI testing and ESP32-S3 DevKit SPIRAM configuration:  `./tools/configure.sh esp32s3-devkit:psram_octal`
=> xtensa/esp32s3: Fix wrong dummy length in mode register reading

libs/libc/time/lib_strftime.c
Corrects the month number output for the %F format specifier in lib_strftime.
- Disable NSH_DISABLE_DATE to enable the built-in date command.
- Enter the shell and set the date. Ex., nsh> date -s "Jan 21 00:00:00 2025"
- Specify the %F format: nsh> date +"%F", but unfortunately, we received the incorrect month number: 2025-**00**-21.
=> fix(libc): lib_strftime %F month number off-by-one

arch/arm/src/armv8-m/Kconfig
armv8m: Default open hardware stack check
Hardware detection will not have any performance impact
=> armv8m: Default open hardware stack check

drivers/loop/loop.c, drivers/misc/dev_null.c, drivers/misc/dev_zero.c
drivers/iovec: revert vector io implement from loop/null/zero driver
basic driver does not need such complex wrapper
improve the performance
test code on ubuntu 24.04 x86_64
```
static void timespec_sub(struct timespec *dest,
struct timespec *ts1,
struct timespec *ts2)
{
dest->tv_sec = ts1->tv_sec - ts2->tv_sec;
dest->tv_nsec = ts1->tv_nsec - ts2->tv_nsec;
if (dest->tv_nsec < 0)
{
dest->tv_nsec += 1000000000;
dest->tv_sec -= 1;
}
}
{
struct timespec result;
struct timespec start;
struct timespec end;
int fd = open("/dev/zero", O_RDONLY);
int loop = 0;
int i = 0;
char c;
while (loop++ < 10)
{
i = 0;
clock_gettime(CLOCK_MONOTONIC, &start);
while (i++ < 100000)
{
read(fd, &c, 1);
} …
```
=> drivers/iovec: revert vector io implement from loop/null/zero driver

arch/sim/src/sim/CMakeLists.txt
sim/virtio: fix typo sim_rpmsg_vritio.c -> sim_rpmsg_virtio.c
Build Error:
```
CMake Error at arch/sim/src/sim/CMakeLists.txt:278 (target_sources):
Cannot find source file:
/home/archer/code/nuttx/n3/nuttx/arch/sim/src/sim/sim_rpmsg_vritio.c
```
N/A
sim/rpserver_virtio:
```
cmake -B build -DBOARD_CONFIG=sim/rpserver_virtio -GNinja
cmake --build build
```
=> sim/virtio: fix typo sim_rpmsg_vritio.c -> sim_rpmsg_virtio.c

arch/risc-v/src/mpfs/mpfs_irq.c, arch/risc-v/src/mpfs/mpfs_irq_dispatch.c, arch/risc-v/src/mpfs/mpfs_plic.c, arch/risc-v/src/mpfs/mpfs_plic.h
Interrupts on MPFS platform are currently served on the hart, on which the up_enable_irq was called.
Call to up_disable_irq may execute on different hart than on which the up_enable_irq was executed. In this case the interrupt is not disabled currently.
While there is nothing fancy (irq affinity control or such), an easy way to fix this is to simply disable the irq on all harts.
This also changes the prototypes of mpfs_plic_get_iebase and mpfs_plic_get_claimbase to get the hart id as an argument, in order to accomplish this.
This fixes spurious interrupts & crashes on MPFS, in SMP build.
Tested on custom MPFS hardware, with SMP enabled on 4 harts (1-4).
=> arch/risc-v/src/mpfs: Disable external interrupts on all SMP harts

arch/risc-v/src/mpfs/mpfs_ddr.c
These are collection of MPFS patches from TII repositories for DDR training procedure.
Specifically, DDR training sometimes passed with incomplete / bad training result, these fix the issues
Improves reliability of DDR training on MPFS platform
Tested on icicle/nsh target and multiple custom HW configurations using different LPDDR chips.
=> Mpfs ddr training fixes

arch/x86_64/include/elf.h, arch/x86_64/src/common/x86_64_tcbinfo.c, libs/libc/machine/x86_64/CMakeLists.txt, sched/misc/coredump.c
Add coredump support for x86-64.
coredump now works on x86-64.
1. config
```patch
CONFIG_BOARD_LOOPSPERMSEC=999
CONFIG_BOOT_RUNFROMEXTSRAM=y
CONFIG_BUILTIN=y
CONFIG_CONSOLE_SYSLOG=y
+CONFIG_COREDUMP=y
+CONFIG_DEBUG_FEATURES=y
CONFIG_DEBUG_SYMBOLS=y
CONFIG_DEFAULT_TASK_STACKSIZE=4194304
+CONFIG_ELF=y
CONFIG_EXAMPLES_HELLO=y
CONFIG_FS_PROCFS=y
CONFIG_IDLETHREAD_STACKSIZE=4194304
@@ -58,4 +63,5 @@ CONFIG_SYSTEM_NSH=y
CONFIG_SYSTEM_TIME64=y
CONFIG_TESTING_OSTEST=y
CONFIG_TESTING_OSTEST_STACKSIZE=4194304
+CONFIG_TTY_FORCE_PANIC=y
CONFIG_USEC_PER_TICK=1
```
2. compile
cmake -Bbuild -GNinja -DBOARD_CONFIG=qemu-intel64:nsh nuttx
ninjia -Cbuild
3. run
```
qemu-system-x86_64 -m 2G -cpu …
```
=> x86-64 coredump support

fs/vfs/fs_read.c, fs/vfs/fs_uio.c, fs/vfs/fs_write.c, include/nuttx/fs/fs.h
fs/vfs: initialize uio only if lower implement readv/writev
to simple signle read/write logic, initialize uio only if lower implement readv/writev
N/A
nsh/sim
=> fs/vfs: initialize uio only if lower implement readv/writev

arch/arm64/src/imx9/imx9_lpuart.c
Call uart_xmitchars once already when tx interrupts are enabled, to push a character already existing in the uart buffers into uart fifo.
Specifically this fixes a serial console getting stuck issue on some custom builds, where console is disabled during runtime.
Only impacts imx9 lpuart
Tested on imx93-evk and on a custom imx93 based HW, using multiple uarts.
=> arch/arm64/src/imx9/imx9_lpuart.c: Call uart_xmitchars when txint is enabled

drivers/rpmsg/rpmsg_port_uart.c
drivers/rpmsg: fix compiler warning
```
In file included from nuttx/drivers/rpmsg/rpmsg_port_uart.c:27:
nuttx/drivers/rpmsg/rpmsg_port_uart.c: In function ‘rpmsg_port_uart_send_connect_req’:
nuttx/drivers/rpmsg/rpmsg_port_uart.c:219:16: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘ssize_t’ {aka ‘long int’} [-Wformat=]
219 |       rpmsgerr("Send connect request failed, ret=%d\n", ret);
|                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~
|                                                         |
|                                                         ssize_t {aka long int}
nuttx/drivers/rpmsg/rpmsg_port_uart.c:219:51: note: format string is defined here
219 |       rpmsgerr("Send connect request failed, ret=%d\n", ret);
| …
```
=> drivers/rpmsg: fix compiler warning

arch/risc-v/src/mpfs/mpfs_ddr.c
Set the LOCKED bit when the final ddr segmentatition is in place. Otherwise the system is prone to potential security issues if the config is altered later. Once the LOCKED bit is set, the register may no longer be changed.
DDR segmentations registers should be locked after DDR training. Otherwise they may be altered later, leading to potential security issues.
All mpfs and derived products.
This has been tested and used on multiple devices, including Polarfire Icicle.
=> risc-v/mpfs: ddr: lock segmentation registers

arch/arm/src/imx9/imx9_lpi2c.c, arch/arm/src/imxrt/imxrt_lpi2c.c, arch/arm/src/s32k1xx/s32k1xx_lpi2c.c, arch/arm/src/s32k3xx/s32k3xx_lpi2c.c, arch/arm64/src/imx9/imx9_lpi2c.c
Use small lock to protect resources related to lpi2c.
The underlying lpI2C logic of arch ARM.
CI
=> Use small lock to protect resources related to lpi2c.

arch/risc-v/src/common/riscv_exception_common.S, arch/risc-v/src/common/riscv_initialstate.c, arch/risc-v/src/common/riscv_internal.h
Restore kernel tp when an exception is taken, restore user tp when exception returns. Store kernel tp in CPU scratch
register when running user code.
This removes the need to call nxsched_self upon exception return. Later with a bit of added logic, it is possible to use tp in kernel to store and read the current tcb (read note).
- Tiny optimization for exception return. 
- Affects targets that have CONFIG_SYSCALL=y (kernel mode builds).
- Other targets are unaffected.
rv-virt:knsh64 + ostest
Note: setting tp in riscv_restorecontext is too late for this, as this_task() points to the (next) ready-to-run task, thus tp should be updated when the rtr list is updated (via up_update_task, which does not exist for risc-v yet)
=> riscv/context_switch: Set tp when a context switch occurs

Documentation/applications/system/gcov/index.rst, tools/gcov.py
Docu/gcov: Modify the description and fix the script error
=> Docu/gcov: Modify the description and fix the script error

arch/arm/src/arm/arm_syscall.c, arch/arm/src/armv6-m/arm_doirq.c, arch/arm/src/armv7-a/arm_doirq.c, arch/arm/src/armv7-a/arm_syscall.c, arch/arm/src/armv7-m/arm_doirq.c, arch/arm/src/armv7-r/arm_syscall.c, arch/arm/src/armv8-m/arm_doirq.c, arch/arm/src/armv8-r/arm_syscall.c, arch/arm64/src/common/arm64_doirq.c, arch/arm64/src/common/arm64_syscall.c, arch/ceva/src/common/ceva_doirq.c, arch/hc/src/common/hc_doirq.c, arch/risc-v/src/common/riscv_doirq.c, arch/risc-v/src/common/supervisor/riscv_perform_syscall.c, arch/tricore/src/common/tricore_doirq.c, arch/x86_64/src/intel64/intel64_handlers.c, arch/xtensa/src/common/xtensa_irqdispatch.c
arch: set (*running_task)->xcp.regs to NULL when exit from irq/exception
reason:
(*running_task)->xcp.regs is invalid when in threadcontext, we marke it as NULL to avoid misusage
arch
qemu-armv7a:smp
=> arch: set (*running_task)->xcp.regs to NULL when exit from irq/exception

cmake/savedefconfig.cmake
defconfig is created with CRLF EOL on Windows, even if LF EOL is used in the cmake file manipulation commands. 
```
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
(use "git push" to publish your local commits)
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   ../../boards/arm/stm32/nucleo-l152re/configs/nsh/defconfig
no changes added to commit (use "git add" and/or "git commit -a")
```
local
Without this PR
With this PR
=> [cmake] savedefconfig.cmake: fix EOL changes to defconfig files on Windows native

drivers/bch/bchdev_driver.c, drivers/misc/rwbuffer.c, drivers/mtd/ftl.c, include/nuttx/drivers/rwbuffer.h, include/nuttx/fs/ioctl.h
This forces the bch layer to read the sector from the physical device instead of using the cached values. It is necessary to call when the device is updated from the different source than bch, for example erased by the MTD ioctl command.
The application may now call the ioctl and obtain the correct read if it needs to read the cached sector again after it being erased.
Tested on SAMv7 with W25Q NOR flash. The first sector was read, erased, cache discarded, and then read again with `0xff` read correctly. Otherwise old values were present.
=> bch: add BIOC_DISCARD ioctl that discards cached sector

Documentation/guides/index.rst, Documentation/guides/stackcheck.rst
=> Doc: Stack overflow check

Documentation/guides/fortify.rst, Documentation/guides/index.rst
=> Doc: Fortify Instructions

arch/sim/src/sim/posix/sim_hostuart.c, arch/sim/src/sim/sim_internal.h
sim/posix/uart: add host_printf() to debug some critical issue
Sometimes we need to bypass the system to debug some issue in critical sections
N/A
sim/nsh
=> sim/posix/uart: add host_printf() to debug some critical issue

drivers/rpmsg/rpmsg_port_uart.c
drivers/rpmsg_port_uart: remove debug message of datalen
datalen message after file_read is always 0
N/A
sim/rpproxy_uart sim/rpserver_uart
=> drivers/rpmsg_port_uart: remove debug message of datalen

drivers/serial/uart_ram.c
serial/uart_ram: update lower buffer offset if previous send completes
UART RAM will have probabilistic bubble time during continuous transmission.
Update the offset after sending to avoid this problem.
N/A
sim/rpproxy_uart  sim/rpserver_uart
test cu command with out any delay
=> serial/uart_ram: update lower buffer offset if previous send completes

arch/x86_64/src/intel64/intel64_handlers.c
x86_64: fix regression https://github.com/apache/nuttx/pull/15651
reason:
In x86_64, tcb->xcp.regs is always valid, and we obtain the location where the context is saved through irq_xcp_regs every time an interrupt occurs.
x86_64
qemu-intel64:nsh
=> x86_64: fix regression https://github.com/apache/nuttx/pull/15651

arch/arm/src/lpc54xx/lpc54_i2c_master.c, arch/arm/src/rp2040/rp2040_i2c_slave.c, arch/arm/src/rp23xx/rp23xx_i2c_slave.c, arch/arm/src/samd2l2/sam_i2c_master.c, arch/arm/src/samd5e5/sam_i2c_master.c, arch/arm/src/stm32/stm32_i2c_alt.c, arch/arm/src/stm32/stm32_i2c_v2.c
Use small lock to protect resources related to i2c master and slave.
The underlying implementation of I2C master and slave.
CI
=> Use small lock to protect resources related to i2c master and slave.

arch/arm/src/samv7/sam_afec.c
ADC peripheral can be configured also for PWM trigger, so the `ifdef` should depend only on `CONFIG_SAMV7_AFEC_SWTRIG`. Also handle the situation when `ANIOC_TRIGGER` is called and the peripheral is not configured for SW trigger (but the other one may be, so config option is set).
Trigger values saved to the private structure are also changed to enums for better code clarity.
Handling of `ANIOC_TRIGGER` ioctl is now fixed.
Tested on SAMv7 board, CI passes for different trigger combinations.
=> samv7/adc: fix handling of ANIOC_TRIGGER ioctl

arch/arm/src/at32/at32_i2c.c, arch/arm/src/cxd56xx/cxd56_i2c.c, arch/arm/src/gd32f4/gd32f4xx_i2c.c, arch/arm/src/kinetis/kinetis_i2c.c, arch/arm/src/lc823450/lc823450_i2c.c, arch/arm/src/lpc17xx_40xx/lpc17_40_i2c.c, arch/arm/src/lpc2378/lpc23xx_i2c.c, arch/arm/src/lpc31xx/lpc31_i2c.c, arch/arm/src/lpc43xx/lpc43_i2c.c, arch/arm/src/rp2040/rp2040_i2c.c, arch/arm/src/rp23xx/rp23xx_i2c.c, arch/arm/src/stm32/stm32_i2c.c, arch/arm/src/stm32/stm32f40xxx_i2c.c, arch/arm/src/stm32f0l0g0/stm32_i2c.c, arch/arm/src/stm32f7/stm32_i2c.c, arch/arm/src/stm32h5/stm32_i2c.c, arch/arm/src/stm32h7/stm32_i2c.c, arch/arm/src/stm32l4/stm32l4_i2c.c, arch/arm/src/stm32u5/stm32_i2c.c, arch/arm/src/stm32wb/stm32wb_i2c.c, arch/arm/src/tiva/common/tiva_i2c.c, arch/arm/src/xmc4/xmc4_i2c.c, arch/mips/src/pic32mz/pic32mz_i2c.c, arch/risc-v/src/common/espressif/esp_i2c.c, arch/risc-v/src/esp32c3-legacy/esp32c3_i2c.c, arch/xtensa/src/esp32s2/esp32s2_i2c.c
Use small lock to protect resources related to i2c.
logic of i2c in all arch.
CI
=> Use small lock to protect resources related to i2c.

include/nuttx/coredump.h, sched/misc/coredump.c
Add a custom note for NuttX information including magic and coredump file data size, so when system reboots, we can check if the block device contains valid coredump file, and save it to file system.
Need apps repo to update correspondingly.
Tested when coredump is saved to block device and restored to filesystem after reboot.
=> misc/coredump: move coredump info to note

sched/Kconfig
Coredump doens't need CONFIG_ELF to be enabled, but need elf.h to include correct elf32.h or elf64.h.
Select `LIBC_ARCH_ELF` in `COREDUMP` to allow `LIBC_ARCH_ELF_64BIT` to be
defined correctly.
64bit coredump will work correctly without enabling `CONFIG_ELF`
Using exact method in https://github.com/apache/nuttx/pull/15638 but with `CONFIG_ELF` disabled.
Note, need to revert a095b1d6a6adf560894b27e953e02908305922c8 for unknown reason, which is currently under investigatement.
=> arch: select LIBC_ARCH_ELF when using COREDUMP

fs/inode/fs_files.c
fs/spinlock: replace no sched_lock() version to improve the performance
after below change merge to kernel, spin_lock() will turn off preemption by default,
but this change is not applicable to all scenarios. The locations in the kernel that
use spin_lock() extensively only require short critical sections and do not trigger
scheduling, which leads to serious performance degradation of NuttX in AMP mode.
In this PR, I try to expose similar problems and hope that each subsystem will carefully check the code coverage
https://github.com/apache/nuttx/pull/14578
```
|commit b69111d16a2a330fa272af8175c832e08881844b
|Author: hujun5 <hujun5@xiaomi.com>
|Date:   Thu Jan 23 16:14:18 2025 +0800
|
|    spinlock: add sched_lock to spin_lock_irqsave
|
|    reason:
|    We aim to replace big locks with …
```
=> [Critical] NuttX performance is greatly degraded in AMP mode

arch/arm/src/c5471/c5471_ethernet.c, arch/arm/src/lpc17xx_40xx/lpc17_40_ethernet.c, arch/arm/src/lpc43xx/lpc43_ethernet.c, arch/arm/src/lpc54xx/lpc54_ethernet.c, arch/arm/src/stm32f7/stm32_ethernet.c, arch/arm/src/stm32h5/stm32_ethernet.c, arch/arm/src/stm32h7/stm32_ethernet.c, arch/arm/src/tiva/lm/lm3s_ethernet.c, arch/hc/src/m9s12/m9s12_ethernet.c, arch/mips/src/pic32mx/pic32mx_ethernet.c, arch/mips/src/pic32mz/pic32mz_ethernet.c, arch/risc-v/src/mpfs/mpfs_ethernet.c
Use small lock to protect resources related to ethernet.
The underlying implementation of Ethernet.
CI
=> Use small lock to protect resources related to ethernet.

arch/arm/src/lpc54xx/lpc54_ethernet.c
Fix wrong variable name. lock -> eth_lock
None
CI
=> Fix wrong variable name. lock -> eth_lock

tools/Export.mk, tools/Unix.mk
- Moved the export of `ZIG` and `ZIGFLAGS` from `tools/Unix.mk` to `tools/Export.mk`
- Simplified the `export` target in `tools/Unix.mk` by removing redundant `ZIG` and `ZIGFLAGS` variables
- No functional changes - the `ZIG` and `ZIGFLAGS` variables are still exported correctly
- Improves code maintainability by centralizing environment variable exports in `Export.mk`
GitHub CI and local build
=> tools: Export ZIG/ZIGFLAGS in Export.mk instead

tools/Export.mk, tools/mkexport.sh
##Summary
- Added LLVM_ARCHTYPE, LLVM_CPUTYPE, and LLVM_ABITYPE to the exported build configuration in both `Export.mk` and `mkexport.sh`
- These flags are now included in the generated `makeinfo.sh`, `Make.defs`, and `target.cmake` files during the export process
##Impact
- Enables LLVM-specific build configurations to be properly exported and used in kernel builds
- Improves compatibility with LLVM-based toolchains by ensuring necessary architecture, CPU, and ABI information is available during the build process
- No functional changes for non-LLVM builds, as these flags are only used when LLVM toolchains are specified
GitHub CI and local board
=> tools: Export LLVM flags for kernel build

tools/mkexport.sh
This adds exported LDMODULEFLAGS so that kernel modules can build with Kernel mode NuttX. Without it, we have link errors like:
```sh
make[3]: Entering directory '/tmp/apps/examples/module/chardev'
LD:  /tmp/apps/bin/chardev arm-none-eabi-ld: warning: cannot find entry symbol _start; defaulting to 0000000000008000
arm-none-eabi-ld: chardev.c.tmp.apps.examples.module.chardev.o: in function `module_uninitialize':
/tmp/apps/examples/module/chardev/chardev.c:111: undefined reference to `unregister_driver'
arm-none-eabi-ld: chardev.c.tmp.apps.examples.module.chardev.o: in function `module_initialize':
/tmp/apps/examples/module/chardev/chardev.c:129: undefined reference to `register_driver'
arm-none-eabi-ld: /tmp/apps/import/startup/crt0.o: in function `__start': …
```
=> tools/mkexport: kernel mode module/elf flags

arch/x86/src/common/Toolchain.defs, arch/x86_64/src/cmake/Toolchain.cmake, arch/x86_64/src/common/Toolchain.defs
- Added LLVM target definitions (`LLVM_ARCHTYPE`, `LLVM_CPUTYPE`, `LLVM_ABITYPE`) to the x86 toolchain configuration file
- These definitions are necessary for compatibility with LLVM-based toolchains
- Enables support for LLVM toolchains when building for x86 targets
- No functional changes for existing GCC-based toolchains
- Improves cross-compilation flexibility by supporting additional toolchain options
qemu-i486 with rust/hello example
=> x86/Toolchain.defs: Add LLVM target definitions

boards/x86/qemu/qemu-i486/scripts/Make.defs
- Simplified `Make.defs` by including `Toolchain.defs` from the x86 common directory
- Removed redundant toolchain and flag definitions, consolidating them into a single shared file
- Reduces code duplication and improves maintainability by centralizing toolchain configurations
- No functional changes - the build process remains the same, but the configuration is now more modular and reusable
qemu-i486:nsh with ostest
=> qemu-i486: Simplify Make.defs by include Toolchain.defs

drivers/wireless/bluetooth/CMakeLists.txt
CMake build was broken with undefined reference to bt_bridge_register function.
```
[9/11] Linking C executable nuttx
FAILED: nuttx 
: && /usr/bin/cc  -Wl,--gc-sections -Wl,-no-pie -Wl,-Ttext-segment=0x40000000 -Wl,-z,noexecstack -T nuttx.ld @CMakeFiles/nuttx.rsp -o nuttx && :
/usr/bin/ld: nuttx.rel: in function `bt_driver_register_with_id':
/home/dan/priv/nuttx/nuttx/drivers/wireless/bluetooth/bt_driver.c:100: undefined reference to `bt_bridge_register'
```
It was because bt_bridge.c file is missing in drivers/wireless/bluetooth/CMakeLists.txt. 
Minor impact, makefile based build worked fine, CMake based build is fixed now.
Host used:
```
Linux 6.8.0-51-generic #52~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Dec  9 15:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
```
gcc (Ubuntu …
```
=> build: CMake fix for sim:btuart

arch/arm64/src/zynq-mpsoc/Kconfig, arch/arm64/src/zynq-mpsoc/Make.defs, arch/arm64/src/zynq-mpsoc/hardware/zynq_pll.h, arch/arm64/src/zynq-mpsoc/zynq_pll.c, arch/arm64/src/zynq-mpsoc/zynq_serial.c, boards/arm64/zynq-mpsoc/zcu111/include/board.h
The PS clocking system generates clocks for the processors, peripherals, interconnect, and
other system elements. There are five system PLLs to generate high-frequency signals that
are used as clock sources for the several dozen clock generators in the LPD and FPD.
Two system PLL clock units are in the LPD and three are in the FPD power domain. Each PLL
unit has two clock dividers on its output; one in the LPD and one in the FPD. These clock
dividers can provide two different clocking frequencies from one PLL (in the two clock
domains).
Each system PLL unit has a suggested usage, but the individual clock generators can select
from one of the three PLL clocks routed to it as defined by the registers listed in the Clock
Generator Control Registers section.The system PLL units reside in the …
=> zynq-mpsoc: add support for pll

arch/arm/src/armv7-a/arm_scu.c, arch/arm/src/armv7-r/arm_scu.c
arm/armv7: update percpu task only for co-processor
fix smp crash on sabre-6quad/smp, regression from:
```
|commit 1e49cb4828f3cdb26252eab3e68f7ca9962bc8ba
|Author: hujun5 <hujun5@xiaomi.com>
|Date:   Thu Dec 5 16:58:17 2024 +0800
|
|    armv7-a/armv7-r/armv8-r: percpu reg store this_task
|
|    This is continue work of https://github.com/apache/nuttx/pull/13726
|
|    We can utilize percpu storage to hold information about the
|    current running task. If we intend to implement this feature, we would
|    need to define two macros that help us manage this percpu information
|    effectively.
|
|    up_this_task: This macro is designed to read the contents of the percpu
|    register to retrieve information about the current
|    running task.This allows us to quickly access
| …
```
=> arm/armv7: update percpu task only for co-processor

Documentation/components/drivers/special/sensors.rst, Documentation/components/drivers/special/sensors/lis2mdl.rst, Documentation/components/drivers/special/sensors/sensors_legacy.rst, Documentation/components/drivers/special/sensors/sensors_uorb.rst, drivers/sensors/CMakeLists.txt, drivers/sensors/Kconfig, drivers/sensors/Make.defs, drivers/sensors/lis2mdl_uorb.c, include/nuttx/sensors/ioctl.h, include/nuttx/sensors/lis2mdl.h
This PR introduces a driver for the LIS2MDL magnetometer by ST Microelectronics. It is capable of being driven in interrupt mode, or use a kernel thread to poll the sensor in applications without an interrupt pin.
The following features are supported:
- Calibration
- Interval selection
- Activation/deactivation
- Interrupt or polling driven
- Setting of calibration values (hard iron offsets)
- Getting sensor information
- Custom commands for entering low-power mode/rebooting
This will add another UORB capable driver to NuttX, which allows more users to put it in their applications. Its interface being interrupt-driven or polled also gives flexibility to more applications.
This magnetometer is being used on both my flight computer and InSpace's flight computer for rocketry applications. We …
=> LIS2MDL UORB driver

arch/sim/src/cmake/Toolchain.cmake, boards/sim/sim/sim/scripts/Make.defs, tools/Rust.defs
- Unified the specification of LLVM architecture and ABI types across the CMake and Makefile configurations.
- Introduced `LLVM_ARCHTYPE` and `LLVM_CPUTYPE` variables in the CMake configuration to match the Makefile's approach.
- Standardized the ABI type (`LLVM_ABITYPE`) to `sysv` for both Linux and macOS host configurations.
- Ensures consistent LLVM target definitions across build systems (CMake and Makefile).
- Simplifies future maintenance by avoiding divergence in LLVM-related configurations.
- No functional changes to the build output; only the internal representation of LLVM target information is aligned.
GitHub CI and local build
=> sim: Align LLVM target info across CMake and Makefile

Documentation/applications/examples/hello_rust/index.rst, Documentation/applications/examples/rust/baremetal/index.rst, Documentation/applications/examples/rust/index.rst
- The `hello_rust` example has been moved to `rust/baremetal` to better reflect its purpose as a bare-metal Rust application.
- The move also helps in organizing the Rust examples more clearly, separating them into categories based on their environment (bare-metal vs. non-bare-metal).
- A new directory structure has been created under `rust/baremetal`, and the `index.rst` file has been updated to describe the `baremetal` example in detail.
- The top-level `rust/index.rst` file has been created to include the new `rust/baremetal` directory in the toctree.
- The new file structure and documentation improvements will help new contributors and users understand the purpose and setup of the example more easily.
- This change aligns the documentation with the actual codebase, enhancing the …
=> docs: Rename hello_rust to rust/baremetal to reflect the actual codebase

tools/gdb/nuttxgdb/protocols/wqueue.py, tools/gdb/nuttxgdb/utils.py, tools/gdb/nuttxgdb/wqueue.py
```
(gdb) worker
hpwork@0x40424b40, idle, 2 threads, 0 work
lpwork@0x40424a80, idle, 2 threads, 0 work
test@0x4045a8c0, running, 2 threads, 2 work
Running:
kworker_s@0x4045a908 work_s@0x406cf330: 0x0 arg=0x406cf300
Queued:
work_s@0x406cf370: 0x402f1954 <count_worker> arg=0x406cf318
work_s@0x406cf3b0: 0x402f1954 <count_worker> arg=0x406cf318
(gdb)
```
New tool.
=> gdb/workqueue: add basic workqueue dump support

tools/gdb/nuttxgdb/protocols/wdog.py, tools/gdb/nuttxgdb/wdog.py
List all wdog timers registered.
```
(gdb) wdog
WDog@0x404864e8: tick: 4294978078       0x402e36b0 <wdtest_callback> arg: 0x40462500
WDog@0x40462ef8: tick: 4294978078       0x402c7900 <nxsig_timeout> arg: 0x40462e70
WDog@0x40462d88: tick: 4294978078       0x402c7900 <nxsig_timeout> arg: 0x40462d00
WDog@0x4046e488: tick: 4294978079       0x402e36b0 <wdtest_callback> arg: 0x40462440
WDog@0x40462658: tick: 4294978079       0x402c7900 <nxsig_timeout> arg: 0x404625d0
(gdb)
```
New tool, no impact.
used for verification (arch, board:config, ..), …
=> gdb/wdog: add basic wdog dump command

drivers/mtd/w25qxxxjv.c
There was a missing QSPI locking for `w25qxxxjv_get_die_from_addr` function. We can't have the lock directly in `w25qxxxjv_get_die_from_addr` because the function is called from already locked function `w25qxxxjv_erase_sector`.
Fix missing lock, could prevent incorrect access to the flash in some cases.
Tested on SAMv7 custom board. I have encountered this problem with the flash and QSPI DMA with two threads accessing the flash (one SmartFS, other BCH layer on MTD device). Adding lock fixed the QSPI command transfer being stuck indefinitely waiting on the transfer to finished (the bit was probably clear by the other thread).
=> w25qxxxjv: fix missing QSPI locking

Documentation/platforms/arm/samv7/index.rst, arch/arm/src/samv7/sam_serial.c, arch/arm/src/samv7/sam_serial.h, boards/arm/samv7/common/Kconfig, boards/arm/samv7/common/include/board_uart_rxdma_poll.h, boards/arm/samv7/common/src/Make.defs, boards/arm/samv7/common/src/sam_uart_rxdma_poll.c
So far only USART drivers could use TX/RX DMA. This commit adds the support for UART drivers as well (with the exception of serial console).
UART peripheral does not have timeout interrupt, so external polling is required to flush the RX data from DMA buffers even if the buffer is not yet full. The board layer can do this by calling `sam_serial_dma_poll` function.
This adds the support for RX DMA polling from bord layer. The board initializes timer channel `SAMV7_UART_RXDMA_POLL_TIMER` with frequency `SAMV7_UART_RXDMA_POLL_FREQUENCY` that triggers DMA polling function.
UART peripherals on SAMv7 now support RX DMA, with the exception of the peripheral used as a console.
Tested on samv71-xult evaluation kit and custom samv7 board.
=> samv7: support RX/TX DMA for UART peripherals

arch/risc-v/src/mpfs/hardware/mpfs_wdog.h, arch/risc-v/src/mpfs/mpfs_ddr.c, arch/risc-v/src/mpfs/mpfs_start.c
Refining MPFS DDR training error handling
- Reset with WDT after completely failed training to avoid leaving "soft reset" status in the boot reason register
- Avoid unnecessary resets after failed DDR training. In most cases it is enough to reset the controller and try again. The expected failures return -EAGAIN. But also the unexpected ones typically can be re-covered by just re-training. So always re-try the ddr training after a failure, but add a re-try counter counting only the unexpected errors, just as a backup.
Impacts only mpfs platform with (LP)DDR memory, with stand-alone booting images (i.e. without HSS & u-boot, using CONFIG_MPFS_BOOTLOADER and CONFIG_MPFS_DDR_INIT). Improves boot time by avoiding unnecessary reboots, if the DDR training results in multiple failures in row. …
=> Mpfs ddr training refinement

include/nuttx/net/can.h, include/nuttx/net/netstats.h, net/can/can_callback.c, net/can/can_input.c, net/can/can_recvmsg.c, net/can/can_sendmsg.c, net/devif/devif_initialize.c, net/procfs/net_statistics.c
Add support for network statistics for CAN. It includes counters for received, sent and dropped frames.
This change was necessary for our application to monitor the dropped can frames reported in the field.
The implementation has mimicked the existing ones for tcp and udp statistics, adding a can_stats_s struct to store the recv, sent and drop counters with the already existing net_stats_t type.
With this change, users can access the CAN statistics through procfs, the same way they access to all the other network statistics. The CAN recv, sent, and drop counters have been added to the /proc/net/stat output following the same design already existing for other network devices. This change doesn't change any driver behavior beyond just adding the new statistics. It does not introduce any new …
=> net/can/: add statistics for recv, sent and drop

arch/risc-v/src/common/riscv_backtrace.c
Fix a compilation error when using -Wpointer-arith and CONFIG_SCHED_BACKTRACE
Makes code to compile when using -Werror.
Tested on MPFS target, with the following flags added:
Tested compilation of "icicle/nsh" target, after adding the "CONFIG_SCHED_BACKTRACE=y" to boards/risc-v/mpfs/icicle/configs/nsh/defconfig. 
The compilation command is:
"make EXTRAFLAGS=-Wpointer-arith -Werror"
With this patch, the compilation passes without warnings/errors. Without this patch the following warnings are produced:
common/riscv_backtrace.c:166:53: error: pointer of type 'void *' used in arithmetic [-Werror=pointer-arith]
166 |                                rtcb->stack_base_ptr + rtcb->adj_stack_size,
|                                                     ^
common/riscv_backtrace.c:186:52: error: pointer …
=> arch/risc-v/src/common/riscv_backtrace.c: Fix "error: pointer of type 'void *' used in arithmetic"

arch/arm/src/cxd56xx/cxd56_cpustart.c, arch/arm/src/lc823450/lc823450_cpustart.c, arch/arm/src/rp2040/rp2040_cpustart.c, arch/arm/src/rp23xx/rp23xx_cpustart.c, arch/arm/src/sam34/sam4cm_cpustart.c, arch/sparc/src/s698pm/s698pm_cpustart.c, arch/xtensa/src/esp32/esp32_cpustart.c, arch/xtensa/src/esp32s3/esp32s3_cpustart.c
What's really need is a done signal sent from the secondary cpu to the boot cpu, so let's simplify the logic by:
1. Change the spinlock to a bool flag
2. Set the flag to true in the secondary cpu
3. Wait the flag set in the boot cpu before continue booting
This also remove all bad usage of spinlock from the code base:
1. Lock spinlock in one thread, but unlock in a different thread
2. Lock spinlock twice in one thread, but unlock only once
Normalize the spinlock usage to avoid the future abuse by copy/paste
local
=> arch: Remove the abuse of spinlock in smp boot

arch/xtensa/src/lx6/Toolchain.defs, arch/xtensa/src/lx7/Toolchain.defs
- Added `--print-memory-usage` to `LDFLAGS` in `Toolchain.defs` for both `lx6` and `lx7` architectures
- This flag enables memory usage reporting during the linking phase, providing better visibility into memory allocation
- No functional changes - the flag only adds additional debug information during the build process
- Improves debugging and optimization capabilities by providing detailed memory usage statistics
- Maintains compatibility with existing build configurations and toolchains
Test result on esp32s3:
```
ROM:      556116 B   16777184 B      3.31%
iram0_0_seg:       23296 B       304 KB      7.48%
irom0_0_seg:      621652 B   16777184 B      3.71%
dram0_0_seg:       85780 B       288 KB     29.09%
drom0_0_seg:      157180 …
```
=> arch/xtensa: Add --print-memory-usage to LDFLAGS in Toolchain.defs

tools/pynuttx/nxgdb/fs.py
```
Use Inode.__repr__ for print and use single line for all information.
Add 'verbose' and 'nodetype' option to show more details and only print specifiy node type like PIPE.
Add / to name for pseudodir.
Catch memory error when accessing node element.
E.g.
(gdb) foreach inode --nodetype pipe
├── run/ 0x41a27a50 PSEUDODIR
│   ├── bt:bluetoothCS1fd26 0x4530c510 PIPE
│   ├── bt:bluetoothCS20 0x42daae40 PIPE
│   ├── socketpair0x457fd2e0SC20540 0x44ea27b0 PIPE
│   └── tmp/ 0x42dd7cf0 PSEUDODIR
│       │   └── usock/ 0x42dd6c10 PSEUDODIR
│       │       └── speech.usockHD 0x42dc8270 PIPE
│       ├── central_lite.socketCS5e 0x42e1e7b0 PIPE
│       ├── central_service_lite.socketSC86 …
```
=> nxgdb/fs: simpifiy inode print and add more command options

boards/Kconfig
While digging through code I've noticed that tricore board option was present on a stm32 chip config.
This is due to a missing depends on statement.
Mostly a preference/esthetic change?
None regarding build process
tricore board will only show (in menuconfig) if tricore chip (tc397) arch is also selected.
Manually.
Checked that the option is present if tc397 chip is selected, hidden otherwise.
=> feat: add arch depends for aurix tc397 board

arch/arm64/include/irq.h
zynq-mpsoc and zcu111 borad was broken by #15437, because #15437 changes ARM64_CONTEXT_REGS from 36 to 37, resulting in the stack no longer being 16-byte aligned which appears to violate the ARMv8-A architecture's requirement for 16-byte stack alignment. this PR changes ARM64_CONTEXT_REGS to 38 to fix the issues #15747.
Impact on user: YES, this PR changes ARM64_CONTEXT_REGS from 37 to 38 will consume 8 byte more memary, but the mpact is acceptable.
Impact on build: NO, this PR just changes the value of ARM64_CONTEXT_REGS.
Impact on hardware: YES. This impacts all the arm64 hardware,  but tested and passed on ZCU111 board.
Impact on documentation: NO,  there's no functionality or usage changes, so the documentation does not need to bo modified.
Impact on security: YES, this PR improved …
=> arch/arm64 Fix the SP unalignment issues

arch/arm64/include/irq.h
Make sure the registers context size is aligned to 16bytes as required by armv8-a. 
This issue has been reported earlier, thus make sense to make sure it won't happen in future.
No impact on existing code.
Tested with qemu build and pass.
```
cmake -Bbuild -GNinja -DBOARD_CONFIG=qemu-armv8a:nsh_smp nuttx
```
If `ARM64_CONTEXT_REGS` is configured to wrong value like `37`. It reports error.
```
In file included from /home/neo/projects/nuttx/nuttx/include/nuttx/irq.h:39,
from /home/neo/projects/nuttx/nuttx/sched/signal/sig_allocpendingsigaction.c:32:
/home/neo/projects/nuttx/build/include/arch/irq.h:165:4: error: #error "ARM64_CONTEXT_REGS must be even to make stack aligned to 16 …
```
=> arch/arm64: generate error if context size is not aligned to 16bytes

tools/pynuttx/nxgdb/memleak.py
This PR includes two changes to `nxgdb` memleak command.
1. Fix that we only need to check used node again leak, excluding free nodes.
2. Optimize memleak check performance by 35%, tested on an internal project that has 128MB memory.
The optimization uses below methods.
1. Use memoryview to avoid creating int objects, reducing overhead
2. Store checked pointers in a dictionary for efficient lookups, improving performance.
3. While dictionary operations have some cost, the overall speedup is significant.
Memleak check now should be faster on system has larger memory.
Tested internally with a coredump.
=> Nxgdb memleak optimization

sched/clock/clock_adjtime.c
The missing `<nuttx/spinlock.h>` header caused following compile errors:
```
CC:  clock/clock_adjtime.c clock/clock_adjtime.c: In function 'adjtime_wdog_callback': clock/clock_adjtime.c:67:11: error: implicit declaration of function 'spin_lock_irqsave' [-Wimplicit-function-declaration]
67 |   flags = spin_lock_irqsave(&g_adjtime_lock);
|           ^~~~~~~~~~~~~~~~~
clock/clock_adjtime.c:78:3: error: implicit declaration of function 'spin_unlock_irqrestore' [-Wimplicit-function-declaration]
78 |   spin_unlock_irqrestore(&g_adjtime_lock, flags);
```
`clock/clock_adjtime.c` now compiles.
=> clock/clock_adjtime.c: fix compile errors

tools/pynuttx/nxgdb/memdump.py, tools/pynuttx/nxgdb/mm.py
1. Add property of prevnode, nextnode to mempool block to make it has same behavior with heap node.
In this way, the memory analysis can have a unified way to inspect memory, no matter for heap or pool.
3. Add warning if corrupted memory node(with 0 size) found.
If the nodesize is 0, we cannot iterate to next node, siliently return None will cause memleak command to generate false positive report with no warnings.
Add log to indicate such case.
4. fix regular expression to parse memory dump log
There could be only one space ahead of address.
Now a warning is printed on corrupted memory node.
memdump log parsing will work insided GDB too.
Tested with below memory dump log, now it can parse correctly.
```
[2025-01-09 21:53:13] [12/23 07:42:07] [85] [ap]    PID        Size Overhead …
```
=> Nxgdb mm minor fixes

include/stdlib.h
* include/stdlib.h: define system()'s prototype for the flat build
The `$(APPDIR)` folder is added to the `$(KERNDEPDIRS)` when `CONFIG_BUILD_KERNEL=y`. The `depend` phase iterates over the `$(KERNDEPDIRS)` folders and executes the `depend` recipe of these folders (including the apps' recipes) with the `__KERNEL__` macro defined, which prevents `system()`'s prototype from being declared.
Impact architectures that build App's dependencies (the `depend` recipe) with `CONFIG_SYSTEM_SYSTEM=y`. This is the case, for instance, when building Python's library with support to the `system()` function.
This PR closes https://github.com/apache/nuttx/issues/15721
Internal CI testing + `rv-virt:python` with `system()` support:
```
make -j distclean && ./tools/configure.sh rv-virt:python && …
```
=> include/stdlib.h: define system()'s prototype for the flat build

Documentation/platforms/arm/mps/boards/mps3-an547/index.rst, arch/arm/src/cmake/gcc.cmake
1. cmake/pic: sync pic related compiler flags from makefile
PIC(Position-Independent-Code) board could work on cmake:
cmake -B ap -DBOARD_CONFIG=mps3-an547:ap -GNinja
2. mps/mps3-an547: correct command line of genromfs
genromfs -a 128 -f ../romfs.img -d pic
f: -f output
a: -a alignment
N/A
cmake -B ap -DBOARD_CONFIG=mps3-an547:ap -GNinja
cmake -B ap -DBOARD_CONFIG=mps3-an547:bl -GNinja
```
$ qemu-system-arm -M mps3-an547 -m 2G -nographic      -kernel bl/nuttx.bin -gdb tcp::1127      -device loader,file=romfs.img,addr=0x60000000
NuttShell (NSH) NuttX-10.4.0
bl> boot /pic/boot
modlib_init...
modlib_load...
modlib_bind...
add-symbol-file ap.elf -s .text 0x60001080 -s .data 0x21000000
NuttShell (NSH) NuttX-10.4.0
ap> 
```
=> cmake/pic: sync pic related compiler flags from makefile

arch/risc-v/Kconfig
The default mapping functions are needed for mpfs
Introducing the new Kconfig flags ARCH_RV_CPUID_MAP broke all mpfs targets, except if running on E51 monitor core, by removing the riscv_hartid_to_cpuid and riscv_cpuid_to_hartid functions. The application U54 harts are the harts 1-4.
Make mpfs bootable again by enabling the flag for all the MPFS targets.
This was requested to be separated from https://github.com/apache/nuttx/pull/15753
All  mpfs targets, make them boot again.
Tested on Microchip Icicle board w. MPFS250T-ES soc
=> arch/risc-v/Kconfig: Select ARCH_RV_CPUID_MAP for all mpfs targets

Documentation/platforms/risc-v/mpfs/boards/icicle/index.rst
This just documents one of the previously undocumented board configuration, icicle/hwtest.
Note: the configuration is documented according to the changes in #15753
Documentation only
CI
=> Documentation/platforms/risc-v/mpfs/boards/icicle/index.rst: Add documentation for "hwtest" board configuration

wireless/bluetooth/bt_netdev.c
bluetooth: miss carrier_[on/off] in bt_netdev
fix regression from https://github.com/apache/nuttx/pull/15237
bluetooth
ci
=> bluetooth: miss carrier_[on/off] in bt_netdev

boards/arm/stm32h7/linum-stm32h753bi/include/board.h
optimize display timings and memory configuration to linum-stm32h753bi board.
-  Optimize FMC/SDRAM configuration for faster memory access
- Improve overall display performance for LVGL applications
These changes aim to enhance the FPS in LVGL benchmark demos, 
for some screen tests it was possible double the fps.
build the example bellow and execute the lvgl beanchmark demo.
```
nuttx$ ./tools/configure.sh linum-stm32h753bi:lvgl
nsh> lvgl benchmark
```
=> boards/linum-stm32h753bi: optimize display timings and memory config

arch/arm/src/samv7/sam_mcan.c, boards/arm/samv7/common/scripts/flash.ld.template, boards/arm/samv7/common/scripts/kernel-space.ld
The message RAM does not behave correctly if lower 16 bits of buffer address overflow (upper 16 bits are set once in matrix driver for the entire CAN driver). For example message RAM starting at `0x2040fc20` would not work for buffers that go beyond `0x20410000` and MCAN would sent data located at `0x20400000` to the network. The same issue would occur even if TX buffers would start directly at `0x20410000`. The upper 16 bits would still have `0x2040` value because of RX buffers located in `0x2040ffff` range.
This commit ensures the RAM is always located at the beginning of the data section and thus the overflow mentioned above should never occur. The alternative would be to use larger alignment, but the message RAM can have up to 4352 words and this would cause a significant padding.
The …
=> samv7: ensure the correct location of message RAM

fs/littlefs/CMakeLists.txt
This fixes a build issue on Ubuntu 22.04 with cmake 3.22.1 for `qemu-armv7a:rpproxy_ivmshmem`:
```
$ cmake --version
cmake version 3.22.1
$ ninja
[129/1346] Building C object fs/CMakeFiles/fs.dir/fs_heap.c.obj
FAILED: fs/CMakeFiles/fs.dir/fs_heap.c.obj
/usr/bin/arm-none-eabi-gcc -D-DLFS_ASSERT=DEBUGASSERT -D-DLFS_CONFIG=/home/yf/Projects/Nuttx/nuttx/fs/littlefs/lfs_vfs.h -D-DLFS_DEBUG=finfo -D-DLFS_ERROR=ferr -D-DLFS_TRACE=finfo -D-DLFS_WARN=fwarn -DLFS_ATTR_MAX=1022 -DLFS_FILE_MAX=2147483647 -DLFS_NAME_MAX=32 -D__KERNEL__ -D__NuttX__ -I/home/yf/Projects/Nuttx/nuttx/openamp/open-amp/lib/include -I/home/yf/Projects/Nuttx/nuttx/fs/littlefs -I/home/yf/Projects/Nuttx/nuttx/fs -I/home/yf/Projects/Nuttx/nuttx/sched -isystem /home/yf/Projects/Nuttx/nuttx/include -isystem /tmp/aaa/include …
```
=> littlefs/cmake: fix compilation flag issue

net/devif/ipv6_input.c
6lowpan response for tcp and icmp was missing because of wrong evaluation of `dev->d_lltype`.
Allows use of ipv6 tcp and icmp over 6lowpan.
Tested on esp32 using espnow.
=> net: fix ipv6_input for 6lowpan

drivers/can/Kconfig, drivers/can/can.c, include/nuttx/can/can.h
For clearing some variables corresponding with the pollfds of the felip in can_close API, we modify poll logic by binding can_reader_s and pollfd.
The **problem scenario** and the **pros/cons** of this approach will be shown in **Impact** section.
Problem Scenario:
**At first** assuming that there is an app that includes main thread(we acquire fd about "/dev/can0" in main thread) and creates another thread named A, the code stream in thread A continuously polls the device node named "/dev/can0". 
**second** we exit this app(main thread will call close api to close "dev/can0"), some data struct about poll operation is not  cleared after operation system recycles the thread A.
**third** we execute the app again（execution number exceed "CONFIG_CAN_NPOLLWAITERS"），the poll API in thread named …
=> nuttx/can: Modify poll logic to bind can_reader_s and pollfd.

arch/risc-v/src/mpfs/hardware/mpfs_i2c.h, arch/risc-v/src/mpfs/mpfs_i2c.c
This removes several error conditions that can be present after a failed
i2c transaction. The most important of them is the priv->sem_isr semaphore
which can be signaled due to a race condition.
This also ensures the i2c device itself is in idle state before futzing
around with it.
Also, add a comment about the SI-flag in the I2C CTRL register; it has
a hidden dual meaning. Not only does it clear a pending interrupt, it
also moves the I2C IP state machine forward. This requires extra logic
in the driver to cope.
The second patch increases the transfer timeout margin, to account for system internal latencies (mainly interrupt latencies).
Impact is the MPFS platform's i2c driver only. No other targets are affected.
Tested with a downstream MPFS target with multiple i2c buses, which contain …
=> mpfs_i2c: Tweaks and fixes for the i2c driver

Documentation/components/drivers/special/sensors.rst, Documentation/components/drivers/special/sensors/lsm6dso32.rst, Documentation/components/drivers/special/sensors/sensors_uorb.rst, drivers/sensors/CMakeLists.txt, drivers/sensors/Kconfig, drivers/sensors/Make.defs, drivers/sensors/lsm6dso32_uorb.c, include/nuttx/sensors/lsm6dso32.h
Adds support for the LSM6DSO32 IMU by STM using the uORB framework. This only contains limited support for the I2C interface, interrupt and polling driven measurement and standard modes of operation (high performance ODRs). Features like interrupts besides DRDY, filtering, gesture recognition and acting as a bus master are not implemented.
Accompanying documentation included.
This PR adds another available uORB driver to the NuttX sensor drivers.
It impacts the build system by adding more Kconfig options and impacts the kernel with more driver source files.
All builds were performed on a Linux host. All testing was performed on an RP2040 MCU on a custom flight computer board.
Below is the script that was used for testing.
```c
#include <errno.h>
#include <fcntl.h>
#include <stdbool.h> …
```
=> drivers/sensors: Added uORB driver for LSM6DSO32 IMU.

arch/arm/src/stm32h7/stm32_ethernet.c, include/nuttx/net/mii.h
Check PHYID1 and PHYID2 for the configured PHY during init. Drivers on some of the other targets do this.
Fixes bug where stm32_phyinit will succeed even when no PHY is connected. This is because there is no check that a PHY is actually communicating and returning data. 
Tested on an [ARKV6X](https://arkelectron.com/product/arkv6x/) running PX4 main. This uses an STM32H743IIK processor.
Here is a snippet from the driver with debugging enabled
```
tm32_ifup: Bringing up: 192.168.0.4
stm32_ethconfig: Reset the Ethernet block
stm32_ethconfig: Initialize the PHY
stm32_phyinit: MII_MCR: phyval: 0 ret: 0
stm32_phyinit: Phy reset in 10 ms
stm32_phyinit: ERROR: Incorrect PHYID1: 0 expected: 7
netinit_monitor: Entry
netdev_ifr_ioctl: cmd: 1819
netdev_ifr_ioctl: cmd: 1828
netdev_ifr_ioctl: cmd: …
```
=> h7: eth: add checks for PHYID in stm32_phyinit

Documentation/guides/rust.rst
docs: enhance Rust guide with CPU optimization instructions
- Added a section to the Rust guide that explains how to use the `RUSTFLAGS` environment variable to specify the target CPU for optimization.
- Provides examples and instructions for setting `RUSTFLAGS` for different CPU models, such as Cortex-M33 and Cortex-M55, to generate performance-optimized code.
- Enhances the developer's ability to produce more efficient Rust applications on NuttX by leveraging CPU-specific optimizations.
- No runtime or functional changes; only documentation improvements to guide users in optimizing their build configurations for specific hardware.
local document build
=>  docs: enhance Rust guide

drivers/mtd/w25qxxxjv.c
Function `w25qxxxjv_erase` wasn't correctly handling an error in `w25qxxxjv_erase_sector` call and was returning success even on failure. Moreover this change does not return `EBUSY` but waits for the previous operation to finish. Returning `EBUSY` doesn't make much sense here as we approximately know how long to wait based on flash's parameters.
This fixes wrong error handling and ensures the erase waits for previous operation to finish.
Tested on SAMv7 custom board with W25Q512 and W25Q01 flashes (512 Mbits and 1 Gbit, the latter has two dies, so slightly different behavior).
=> mtd/w25q: ensure the correct behavior if erase sector fails

drivers/note/note_driver.c, drivers/note/noteram_driver.c, drivers/note/noterpmsg_driver.c, drivers/segger/config/SEGGER_RTT_Conf.h, drivers/syslog/syslog_intbuffer.c, fs/inode/fs_files.c, include/nuttx/irq.h, include/nuttx/spinlock.h, libs/libc/machine/arch_atomic.c, sched/irq/irq_csection.c, sched/sched/sched_process_delivered.c, sched/wqueue/kwork_queue.c, sched/wqueue/kwork_thread.c
Revert some changes to restore the original semantics of spin_lock_irqsave.
spinlock
ci
=> Revert some changes to restore the original semantics of spin_lock_irqsave.

Documentation/platforms/arm64/qemu/boards/qemu-armv8a/README.txt
qemu-armv8a/ivshmem: add ivshmem chapter
An example implementation for OpenAMP based on the Inter-VM share memory(ivshmem)::
rpproxy_ivshmem:  Remote slave(client) proxy process.
rpserver_ivshmem: Remote master(host) server process.
Please refer to the official Qemu ivshmem documentation for more information:
https://www.qemu.org/docs/master/system/devices/ivshmem.html
N/A
a. Start rpserver_ivshmem::
$ qemu-system-aarch64 -cpu cortex-a53 -nographic -machine virt,virtualization=on,gic-version=3 -kernel server/nuttx \
-device ivshmem-plain,id=shmem0,memdev=shmmem-shmem0,addr=0xb \
-object memory-backend-file,id=shmmem-shmem0,mem-path=/dev/shm/ivshmem0,size=4194304,share=yes
b. Start rpproxy_ivshmem::
$ qemu-system-aarch64 -cpu cortex-a53 …
=> qemu-armv8a/ivshmem: add ivshmem chapter

boards/arm/stm32/b-g431b-esc1/src/stm32_cansock.c
boards/b-g431b-esc1: configure CAN_TERM pin also for SocketCAN interface
CAN chardev already support this, but for socketcan it was missing
can network with SocketCAN works as expected
=> boards/b-g431b-esc1: configure CAN_TERM pin

libs/libc/modlib/modlib_bind.c
Addrenv is changed to the newly created process' one in the beginning of modlib_bind, and needs to be changed back always when returning from the function; also in error cases.
This fixes a system crash in case where linking of a new process fails in modlib_bind. In the error case the modlib_bind returned with error code, but with wrong address environment.
Fixes a crashing bug in platforms using CONFIG_ARCH_ADDRENV.
Tested on imx93 and mpfs platforms.
=> libs/libc/modlib/modlib_bind.c: Fix system crash if modlib_bind fails

arch/arm/src/imx9/Kconfig, arch/arm/src/imx9/imx9_gpioirq.c
This fixes crashes caused by receiving interrupt from unused/unassigned GPIO banks.
This is because on the IMX95 you can map the GPIO banks between A55, M7 and M33 cores. 
Thus disallowing a specific to access a particular GPIO bank.
This patch makes it configurable compile-time so that the M7 only access the GPIO it's assigned too.
IMX95 Arch only
Tested on IMX95-EVK board
=> imx95: make gpio irq configurable per bank

Documentation/guides/rust.rst
Summary
- Added a section on editor integration for Rust development in NuttX, focusing on VS Code and rust-analyzer
- Provides steps to configure `.vscode/settings.json` to recognize Rust project structure and optional settings for custom target specifications
Impact
- Enhances developer productivity by providing better IDE support for Rust in NuttX
- No impact on existing functionality; the guide is purely informational and configuration-based
Local doc build
=> docs: Add editor integration guide for Rust development in NuttX

Documentation/components/drivers/character/serial.rst, arch/arm/src/stm32/stm32_serial.c, drivers/serial/Kconfig, include/nuttx/serial/serial.h
*These commits add support to serial error reporting using the TIOCGICOUNT ioctl and an example implementation for STM32.
*Users will be able to get information about U[S]ART communication errors
*STM32F4Discovery board
=> Add support to Serial Error Reporting ioctl

Documentation/contributing/coding_style.rst
Unfortunately new contributors used to submit code with many coding issues. And in fact it is our guilt: our coding style documentation doesn't say to them how to use the checkpatch to find the issues.
Avoid friction when users try to submit their first PR and there are a lot of coding style issues
N/A
=> DOC: Fix documentation to include checkpatch.sh

arch/arm/src/samv7/sam_1wire.c
Fixes
```
chip/sam_1wire.c:921:7: warning: implicit declaration of function 'sam_usart0_enableclk' [-Wimplicit-function-declaration]
921 |       sam_usart0_enableclk();
```
The same warning applied for other uart/usart peripherals configured as 1 wire.
=> samv7/sam_1wire.c: fix compilation warnings

arch/arm/src/max326xx/hardware/max326_gpio.h, arch/arm/src/max326xx/max32660/max32660_gpio.h, arch/arm/src/max326xx/max32690/max32690_gpio.c, arch/arm/src/max326xx/max32690/max32690_gpio.h, arch/arm/src/max326xx/max32690/max32690_gpioirq.c, arch/arm/src/max326xx/max326_gpio.h
definitions for the max32660 moved to max32660_gpio.h
the max32690 has much more options for the gpios
so this is a complete new driver
adds support for the max32690 gpios
should have no impact
driver works on my dev board
=> arch/arm/max326xx: add max32690 gpio driver

arch/arm/src/imx9/imx9_scmi.c
The SCMI implementation for the iMX95 is updated to match the
SCMI 3.2 specification.
The SCMI implementation was based on an early unreleased version
of the BSP that has a slighty different API. Currently NuttX imx95 target is not compatible
with the latest BSP and results in pin control configurations not being made.
Pin control settings sent over SCMI now functions properly with the latest BSP
imx95-evk:nsh
enable CONFIG_IMX9_IOMUX_OVER_SCMI
=> imx9: scmi: update to scmi 3.2 spec

arch/arm/src/armv7-a/arm_addrenv_shm.c, arch/arm/src/armv7-a/arm_addrenv_utils.c
bugfix when test features in kernel build
fix when change CONFIG_ARCH_TEXT_NPAGES to 512 will cause crash in arm_addrenv_create_region with armv7a,
fix shm crash when use fb_demo in goldfish armv7a kernel build
ci-test, qemu-armv7a knsh & ostest, goldfish-armv7a fb_demo
=> armv7a kernel build bugfix, when shm & arm_addrenv_create_region

drivers/thermal/thermal_core.c, drivers/thermal/thermal_dummy.c, include/nuttx/thermal.h
1. Add support for passive trip point.
Spliting `THERMAL_NORMAL` to `THERMAL_ACTIVE` and `THERMAL_PASSIVE`, to support different update intervals for thermal zone, mainly for low-power.
Can save power by reducing times the worker was invoked.
2. Add another dummy passive cooling device.
For case that CPUFreq was not enabled.
drivers/thermal
1. Selftest PASSED with `sim:thermal`
Init
```
root@3cadb4421218:/workspace/nuttx# ./nuttx
[    0.000000] thermal_register_governor: Register governor step_wise
[    0.000000] thermal_register_governor: Default governor step_wise registered!
[    0.000000] thermal_cooling_device_register: Registered cooling device passive_dev
[    0.000000] thermal_cooling_device_register: Registered cooling device fan0
[    0.000000] thermal_zone_device_register: Set …
```
=> drivers/thermal: Add support for passive trip point

tools/pynuttx/nxgdb/mm.py
nqueue has been added to output.
E.g.
```
(gdb) mm pool
Total 16 pools
total blocksize     bsize  overhead     nused     nfree    nifree   nwaiter    nqueue
Umem@0x10048dc        4068        16        16         0         3       251         0         0         1
Umem@0x100493c        4068        32        32         0         3       124         0         0         1
Umem@0x100499c        4036        48        48         0        10        74         0         0         1
Umem@0x10049fc        4036        64        64         0         1        62         0         0         1
Umem@0x1004a5c           0        80        80         0         0         0         0         0         0
Umem@0x1004abc           0        96        96         0         0         0         0         0         0 …
```
=> nxgdb/mm: show pool expand queue size

arch/arm/include/spinlock.h, arch/or1k/include/mor1kx/irq.h, arch/xtensa/src/common/xtensa_backtrace.c, include/nuttx/compiler.h
arm/memory_barrier: fix build warning on GCC14
```
nuttx/include/arch/spinlock.h:66:9: warning: "UP_DSB" redefined
66 | #define UP_DSB() __asm__ __volatile__ ("dsb sy" : : : "memory")
|         ^~~~~~
In file included from nuttx/include/arch/barriers.h:37,
from nuttx/include/arch/spinlock.h:34:
nuttx/include/arch/armv8-m/barriers.h:42:9: note: this is the location of the previous definition
42 | #define UP_DSB()  arm_dsb(15)
|         ^~~~~~
nuttx/include/arch/spinlock.h:67:9: warning: "UP_DMB" redefined
67 | #define UP_DMB() __asm__ __volatile__ ("dmb st" : : : "memory")
|         ^~~~~~
nuttx/include/arch/armv8-m/barriers.h:41:9: note: this is the location of the previous definition
41 | #define UP_DMB()  arm_dmb()
|         ^~~~~~
```
nuttx/compiler: fix build warning on GCC14
``` …
```
=> nuttx/compiler: fix build warning on GCC14

Documentation/guides/gdb/irqinfo.rst, Documentation/guides/gdbwithpython.rst, Documentation/guides/qemugdb.rst, Documentation/platforms/risc-v/qemu-rv/boards/rv-virt/index.rst, Documentation/quickstart/debugging.rst, tools/pynuttx/nxgdb/irq.py, tools/pynuttx/nxgdb/protocols/irq.py, tools/pynuttx/nxgdb/utils.py
Similar to nsh command, `irqinfo` shows the registered IRQ callbacks and arguements.
Arguements is shown as a function when possible.
If intrumentation is enabled, it also prints the IRQ count etc.
```
(gdb) irqinfo
IRQ  COUNT      TIME   RATE   HANDLER                                          ARGUMENT
0    0          0      N/A    mps_reserved                             0x0 <sensor_unregister>
2    0          0      N/A    mps_nmi                                  0x0 <sensor_unregister>
3    0          0      N/A    arm_hardfault                            0x0 <sensor_unregister>
4    0          0      N/A    arm_memfault                             0x0 <sensor_unregister>
5 …
```
=> nxgdb/irq: add irqinfo command

arch/xtensa/src/esp32/esp32_wdt.c
Please to https://github.com/apache/nuttx/pull/15433
cpuint was allocated when register wdt handler, but not deallocated when unregister, which cause debug assert when checking `DEBUGASSERT((*freeints & bitmask) == 0)`, so set cpuint to initial value after deallocate.
This PR just cherry-picked the fix in esp32s3_wdt.c to esp32_wdt.c.
Impact watchdog handler register/unregister on ESP32
same to  https://github.com/apache/nuttx/pull/15433
=> xtensa/esp32: set cpuint to initial value after deallocate

boards/arm/rp2040/common/Kconfig, boards/arm/rp2040/common/src/rp2040_st7789.c
support config st7789 reset gpio pin
the LCD_RST gpio in number is define to gpio 12 in rp2040_st7789.c，add a Kconfig to support config the gpio pin number.
I have tested the funtion on a Pico-ResTouch-LCD-2.8 https://www.waveshare.com/wiki/Pico-ResTouch-LCD-2.8.
=> board/arm/rp2040: support config st7789 reset gpio pin

arch/risc-v/src/common/riscv_doirq.c, arch/risc-v/src/common/riscv_exception_common.S, arch/risc-v/src/common/riscv_getintstack.c, arch/risc-v/src/common/riscv_macros.S, arch/risc-v/src/qemu-rv/chip.h
This PR adds support for backtrace on RISC-V on certain build settings explained below.
Up to this point, it was not printing anything useful during crashes.
Adds backtrace for task and IRQs when the RISC-V system crashes.
Tested on Espressif RISC-V devices and rv-virt.
All tests are based on:
- defconfig: rv-virt:nsh
- CONFIG_SCHED_BACKTRACE=y
- CONFIG_FRAME_POINTER=y
- CONFIG_DEBUG_SYMBOLS=y
The test is executed as follows: build, run ostest and test the backtrace in two different ways:
- Task exception: simply do `*p = 0`; inside a simple test program.
- IRQ exception: set up an interrupt handler and trigger the IRQ. Inside the interrupt routine, do `*p = 0;`.
The backtrace is verified manually using `tools/btdecode.sh`.
- CONFIG_SMP=n
- CONFIG_ARCH_INTERRUPTSTACK=2048
Command: …
=> risc-v/backtrace: Support backtrace dump during IRQ

drivers/sensors/lsm6dso32_uorb.c
This issue was noticed while testing the LSM6DSO32 driver on the STM32H743 MCU, as part of issue #15826.
This is required to meet the communication requirements as per the LSM6DSO32 datasheet. It doesn't cause issues on some MCUs (RP2040), but prevents successful reads on others (STM32).
Now this driver works correctly on all MCUs and follows the communication spec from the sensor datasheet.
Here is an example output of the issue observed on the STM32H743. The added logging statements show that the buffers for x,y,z acceleration and temperature had the same contents before and after the I2C read operation.
```console
lsm6dso32_read_accel: x buffer: 0xFFFFF064
lsm6dso32_read_accel: y buffer: 0x2400
lsm6dso32_read_accel: z buffer: 0x0000
lsm6dso32_read_accel: Temp buffer: 0x0801 …
```
=> drivers/sensors/lsm6dso32: fixed byte read command to include start condition

libs/libnx/Makefile
libs/libnx: do not generate resource if CONFIG_NX is not enabled
To avoid generate resource if CONFIG_NX is disabled:
```
| $ make -j12
| Create version.h
| CPP:  nxfonts_convert.c-> nxfonts_convert_8bpp.i
| CPP:  nxfonts_convert.c-> nxfonts_convert_24bpp.i
```
N/A
./tools/configure.sh sim/libcxxtest
=> libs/libnx: do not generate resource if CONFIG_NX is not enabled

libs/libxx/libcxx/0001-libc-Fix-failures-with-GCC-14-92663.patch, libs/libxx/libcxx/CMakeLists.txt, libs/libxx/libcxx/Make.defs
libc/libcxx: fix failures with GCC 14
```
CXX:  libcxx/libcxx/src/random.cpp In file included from nuttx/include/libcxx/__filesystem/filesystem_error.h:15,
from nuttx/include/libcxx/__filesystem/directory_entry.h:20,
from nuttx/include/libcxx/filesystem:539,
from nuttx/include/libcxx/fstream:192,
from libcxx/libcxx/src/ios.instantiations.cpp:10:
nuttx/include/libcxx/__filesystem/path.h: In instantiation of 'std::__1::__fs::filesystem::path::_EnableIfPathable<_Source> std::__1::__fs::filesystem::path::append(const _Source&) [with _Source = std::__1::basic_string<char>]':
nuttx/include/libcxx/__filesystem/path.h:623:30: error: use of built-in trait '__remove_pointer(typename std::__1::decay<_Tp>::type)' in function signature; use library traits instead
623 |   _EnableIfPathable<_Source> …
```
=> libc/libcxx: fix failures with GCC 14

drivers/sensors/ms56xx_uorb.c
Longer delays (10ms) are performed with `nxsig_usleep()` instead of `up_udelay()`.
The waiting process in this driver is now more efficient since it does not rely on busy waiting using a loop for its longer delays.
Testing was performed on a custom STM32H743 flight computer where an issue was first observed with incorrect pressure readings because of an incorrect `CONFIG_BOARD_LOOPSPERMSEC` value. This closes #15826.
With the new changes, pressure is read correctly:
```console
NuttShell (NSH) NuttX-12.8.0
nsh> uorb_listener -r 50 -n 10 sensor_baro0
Mointor objects num:1
object_name:sensor_baro, object_instance:0
sensor_baro(now:7900000):timestamp:7900000,pressure:1003.309998,temperature:21.230000
sensor_baro(now:7970000):timestamp:7970000,pressure:1003.309998,temperature:21.280001 …
```
=> drivers/sensors/ms56xx: Use nxsig_usleep for long delays.

Documentation/platforms/arm/nrf52/boards/xiao-nrf52840/index.rst
Change XIAO nRF52840 name at Documentation to
match product name and other Seeed Studio boards.
This PR makes easier to users to find out the Seeed Studio XIAO nRF52840 
at Documentation by using the correct name.
Built the documentation and check it locally:
=> Documentation:Fix Seeed Studio XIAO nRF52840

drivers/net/lan9250.c
This fixes build warnings when different archs are used. Simply changes "lx" to "PRIx32" when using uint32_t.
Changed format specifiers from `%08x` to `PRIx32` for better compatibility.
Affects only a few log lines.
This is required since I'm working on a fix for #15755. 
Example of warning when applying the new data types for ESP32S3:
```
In file included from net/lan9250.c:34:
net/lan9250.c: In function 'lan9250_wait_ready':
net/lan9250.c:620:12: warning: format '%x' expects argument of type 'unsigned int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
620 |       nerr("ERROR: wait register:0x%02x, mask:0x%08x, expected:0x%08x\n",
|            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
621 |             address, mask, expected);
| …
```
=> drivers/net: change format specifiers macros on lan9250 driver

Documentation/applications/interpreters/python/index.rst
After https://github.com/apache/nuttx-apps/pull/2982, there is no need to mount the modules and manually set the required environment variables: they are all set by the new Python wrapper application.
Impact on user: YES. Users don't need to mount and set the environment variables anymore. Documentation should reflect it.
Impact on documentation: YES. Documentation is being fixed to reflect the current procedure to run Python.
Just build the documentation locally:
```
cd Documentation
make html
```
=> Documentation/python: Fix tutorial for running Python

drivers/thermal/thermal_core.c
Fix work not queued after getting temperature fails, the work will be stopped after `get_temp()` fails.
drivers/thermal
1. sim:thermal with mod below PASSED:
```diff
static int dummy_zdev_get_temp(FAR struct thermal_zone_device_s *zdev,
FAR int *temp)
{
+  return ERROR;
```
2. CI
=> drivers/thermal/core: Fix work not queued after getting temperature fails

net/devif/ipv6_input.c
Update the handling of tcp packets over sixlowpan. `tcp_ipv6_input()` can update the dev->d_iob, so use this to send the response.
When using tcp over sixlowpan (e.g. for telnet) the handling of packets trough `tcp_ipv6_input()` can modify `dev->d_iob`. The PR makes sure that the correct `dev->d_iob` is used as returned packets. 
Allows using tcp over sixlowpan, e.g. telnet over sixlowpan. No impact on build system or other parts.
Verified on esp32 using espnow as packet radio with telnetd and telnet.
=> sixlowpan: improve tcp support.

binfmt/binfmt.h, binfmt/binfmt_copyactions.c
We should not modify the input actions, casing when kernel build, userspace call posix_spawn touch kernel address.
with current code, within posix_spawn will modify the file_actions input from user space, we should not purpose to change it, also the flink in actions copy out is not correct.
fix when do adb shell in goldfish v7a kernel build, crash in posix_spawn_file_actions_destroy
ci-test, arm-v7a ostest, goldfish v7a adbd
=> binfmt/copyaction: fix prev->flink did not use from kmalloc.

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_coremmc.c, arch/risc-v/src/mpfs/mpfs_sdio_dev.h
This adds support to optimize SD/MMC speed on MPFS targets, utilizing Microchip's CoreMMC IP block on the FPGA.
If CONFIG_MMCSD_SDIOWAIT_WRCOMPLETE is defined, the coremmc driver uses SD card's dat0 line to detect whether the sd card is still busy.
This requires that the FPGA design using coremmc block wires dat0 line to some fabric irq; and configures CONFIG_MPFS_COREMMC_WRCOMPLETE_IRQNUM to point to that. Default for the irq number is 4. (MSS_INT_F2M_4)
This is the same mechanism which is used for several STM32 targets to optimize SD card speed.
Impacts only MPFS targets, using microchip's CoreMMC IP block on the FPGA. This is a feature which can be used to optimize the SD / MMC speed.
Tested on custom MPFS hardware, with SD card DAT0 line wired to PLIC interrupt on the FPGA
=> arch/risc-v/src/mpfs: Implement wrcomplete support for coremmc driver

arch/risc-v/src/mpfs/hardware/mpfs_plic.h, arch/risc-v/src/mpfs/mpfs_irq.c, arch/risc-v/src/mpfs/mpfs_plic.c, arch/risc-v/src/mpfs/mpfs_plic.h
- Move PLIC interrupt enable and disable functions into mpfs_plic.c
- Remove race conditions between irq enable/disable by adding spinlock
- An interrupt may trigger on one hart in the middle of enabling the interrupts - then the interrupt handler might call up_disable_irq.
- When enabling interrupts, always clear pending interrupt:
A pending interrupt would trigger immediately when enabling the interrupt source, but this is not expected. The interrupt source is level sensitive, so it should only trigger if the source is active at the time when it is enabled. Not if it was active sometime in the past but inactive at the time when the IRQ is enabled.
The issue becomes with devices where the interrupt source (the line connected to the PLIC) can't be masked / controlled, but the IRQ itself …
=> arch/risc-v/src/mpfs: Move PLIC interrupt enable/disable to mpfs_plic and handle pending interrupts

arch/arm/src/samv7/Kconfig, arch/arm/src/samv7/sam_pwm.c, arch/arm/src/samv7/sam_pwm.h
This adds configuration option for every fault input, that can be latched (kept even after the input value is below the threshold) or volatile (PWM is automatically enabled once the output polarity goes back to the normal state).
Fault inputs on SAMv7 PWM can now be configured as non volatile.
=> samv7/pwm: add support for latched fault inputs

arch/arm/src/samv7/sam_pwm.c
DTE (dead time enable) is the 17th bit in CMRx (channel mode) register. Function `pwm_set_polarity` did however read and write this register as 16 bit large, therefore dead time generation was always disabled. This fixes the issue, `pwm_set_polarity` now reads the register as 32 large.
Also set the initial value of CMRx correctly in `pwm_setup`.
SAMv7 PWM driver now has correctly enabled dead time generation. No impact on configuration/setup.
Dead time was not generated at all before this fix. Now the generated pulse with dead time looks correct at the oscilloscope.
=> samv7/pwm: fix incorrect write of CMRx register

drivers/lcd/st7789.c
If `st7789_wrram` is called with `count = 1`, then the entire buffer should be sent. However, in 3 wire mode, the driver has to send the buffer row by row because of additional data flag. The number of rows (count) can't be `ST7789_YRES` in this case, but only the number of rows in the buffer (this is write size / row size , where row size is `ST7789_XRES * ST7789_BYTESPP`). This also applies only if we want to write size larger than row size, because `st7789_putrun` allows to write just a part of a row.
This fixes the incorrect behavior of the display in 3 wire mode if the display is split into more buffer writes (as in LCD driver for example, FB driver did not face this issue).
Fixes the behavior of the display with LCD driver if the buffer is less than the entire display size (usually …
=> lcd/st7789: fix incorrect buffer count for 3 wire RAM write

arch/risc-v/src/common/espressif/esp_usbserial.c
Ths commit disable code optimization responsible for esp32c6 interruption serial register changes. Without this optimization, usbserial driver doesn't word. This is work around meanwhile we find properly fix.
This change disable compile optimization for function esp_txint, used in usbserial driver. This change was discussed in the issue: https://github.com/apache/nuttx/issues/15656.
Before this change, when you input any character to the console and press "enter", console will stuck.
Do usbserial feature for esp32c6 work properly
Use esp32c6 usbserial config. Build and flash. You will be able to use usb as serial console.
=> riscv/esp32c6: Fix issue related esp32c6 usbserial driver.

drivers/syslog/syslog_rpmsg_server.c
syslog/rpmsg_server: fix build break if enable SYSLOG_RPMSG/SYSLOG_RPMSG_SERVER
```
syslog/syslog_rpmsg_server.c:66:13: error: conflicting types for 'syslog_rpmsg_write';
have 'void(const char *, size_t,  const char *, size_t)' {aka 'void(const char *, unsigned int,  const char *, unsigned int)'}
66 | static void syslog_rpmsg_write(FAR const char *buf1, size_t len1,
|             ^~~~~~~~~~~~~~~~~~
In file included from syslog/syslog_rpmsg_server.c:36:
nuttx/include/nuttx/syslog/syslog_rpmsg.h:51:9: note: previous declaration of
'syslog_rpmsg_write' with type 'ssize_t(const syslog_channel_t *, const char *, size_t)' {aka 'int(const struct syslog_channel_s *, const char *, unsigned int)'}
51 | ssize_t syslog_rpmsg_write(FAR syslog_channel_t *channel,
|         ^~~~~~~~~~~~~~~~~~
``` …
=> syslog/rpmsg_server: fix build break if enable SYSLOG_RPMSG/SYSLOG_RPMSG_SERVER

arch/arm/src/cxd56xx/cxd56_i2c.c
During I2C communication between non-Spresense devices is performed,
the I2C bus may freeze after initialization of the Spresense I2C.
As a workaround, 
* switch the pin mode to I2C at the end of the i2c initialization function.
* add clock gating process and disable GPIO input to the I2C reset function.
Only for spresense board
=> arch: cxd56xx: Fix i2c bus freeze at i2c initialization

arch/arm64/src/common/arm64_head.S
`boot_stage_puts` used by early assembly head, calls `arm64_lowputc()` for each character of the string to be printed in a loop. During that loop it uses `x1` as the pointer to the next character to be printed. However, `x1` is clobbered<sup>[1]</sup> by `arm64_lowputc()`, resulting in undefined behaviour (only the first character of the string is guaranteed to be printed).
Fix this by using `x19` instead.
[1] Observed clobbering behaviour with `arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64`.
The change does not affect users, build processes, hardware, documentation or security compatibility.
The only notable effect should be the early console messages in arm64 builds being fully (and more reliably) visible when configured with `CONFIG_ARCH_EARLY_PRINT=y`.
- Toolchain: …
=> arch/arm64: fix boot stage prints with CONFIG_ARCH_EARLY_PRINT=y

include/nuttx/spinlock.h
sched/spin_lock: continue work to rename raw_spin* to spin_*_notrace
Some improvements are made to the following commits:
https://github.com/apache/nuttx/pull/15767
```
| commit f22b93b337c2f9de457904596688a04bd1ce12e5
| Date:   Fri Jan 31 07:01:07 2025 +0800
|
|     sched/spin_lock: rename raw_spin_lock to spin_lock_notrace
|
|     Signed-off-by: hujun5 <hujun5@xiaomi.com>
```
N/A
ci-check
=> sched/spin_lock: continue work to rename raw_spin* to spin_*_notrace

Documentation/applications/benchmarks/cyclictest/index.rst
Adding cyclictest documentation. This concerns [this pull request](https://github.com/apache/nuttx-apps/pull/3000) in nuttx-apps.
=> Documentation: add cyclictest benchmark utility documentation

Documentation/components/drivers/character/timers/pwm.rst, arch/arm/src/samv7/sam_pwm.c, include/nuttx/timers/pwm.h
This ioctl clears the active fault inputs. Some faults can be latched (still active even if the source is not active anymore), so they have to be cleared from the software. The argument is a pointer to unsigned long bitmask variable. This bitmask specifies which faults are to be cleared.
The ioctl also can fetch the faults active prior to the clear. These faults are saved to the argument specifying which faults are to be
cleared. Therefore passing zero bitmask means the driver will only return active faults and clear none. Passing NULL pointer means the driver will clear all active and return none.
The other commit implements the ioctl to samv7 PWM driver.
None to current implementations as this is a new ioctl call. Documentation updated with a proper description. Drivers not implementing …
=> pwm: add support for PWMIOC_FAULTS_FETCH_AND_CLEAR ioctl

arch/arm/src/tiva/common/tiva_pwm.c
This commit introduces support for complementary PWM mode on the Tiva C-Series microcontrollers. The feature allows configuring specific PWM generators to operate in complementary mode via Kconfig.
This change adds support for complementary PWM mode on Tiva C-Series microcontrollers in NuttX.
The feature allows configuring individual PWM generators to operate in complementary mode via Kconfig options.
The implementation preserves backward compatibility, ensuring that the default behavior remains unchanged.
The complementary mode can be enabled for each generator separately using:
- CONFIG_TIVA_PWM_COMPLEMENTARY_G0
- CONFIG_TIVA_PWM_COMPLEMENTARY_G1
- CONFIG_TIVA_PWM_COMPLEMENTARY_G2
- CONFIG_TIVA_PWM_COMPLEMENTARY_G3
The changes are contained within:
+ arch/arm/src/tiva/common/tiva_pwm.c …
=> arch/arm/tiva: Add complementary PWM mode support

boards/arm/rp2040/common/src/rp2040_spi.c
Board logic change.
This PR adds weak_function attributes to the RP2040 common SPI board logic.
This allows board developers to override and extend the SPI board logic.
This allows board developers to add custom SPI logic such as adding additional chip select pins.
Adding new SPI devices such as displays or custom SPI devices like external boards is now possible.
External custom boards will have the biggest impact, as these are typically not pushed.
This has been tested by building the code on linux with raspberrypi-pico:nsh config.
I also tested it on a custom board and it works.
However, my knowledge is not very big about compiler compatibility when weak_function is used.
Please let me know if there are issues.
=> boards/arm/rp2040/common: Add weak_function to SPI common logic

drivers/audio/es8388.c
Use `PRIu32` instead of `%u` for `uint32_t` to avoid build warnings on different architectures.
This is required as part of an effort to fix #15755.
- Impact on user: No.
- Impact on build: Yes, removes build warnings due to wrong data type depending on architecture.
- Impact on hardware: No.
- Impact on documentation: No.
- Impact on security: No.
- Impact on compatibility: No.
- ./tools/configure.sh esp32s3-korvo-2:audio
- make
Before this change:
```
In file included from audio/es8388.c:41:
audio/es8388.c: In function 'es8388_setmclkfrequency':
audio/es8388.c:533:15: error: format '%u' expects argument of type 'unsigned int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
533 |       audinfo("MCLK Freq: %u\n", priv->mclk);
| …
```
=> drivers/audio/es8388: set proper format specifier macro for logging

Documentation/components/drivers/character/leds/index.rst, Documentation/components/drivers/character/leds/userled.rst
The USERLED subsystem is responsible to register and to control the user LEDs on the board.
Improves Documentation
make html
=> doc: Add documentation to USERLED subsystem

Documentation/applications/benchmarks/cyclictest/index.rst
-q (--quiet) option added.
A simple documentation change. This concerns this [commit](https://github.com/apache/nuttx-apps/pull/3014).
=> Documentation/applications/benchmarks/cyclictest: -q

drivers/serial/ptmx.c
The alloctab can be looped, if the first check the corresponding bit is set, it will not continue to loop
ptmx
selftest
=> ptmx: When alloc minor, skip the start addr if it has been used

net/socket/getsockopt.c
check parameters at the top level to avoid errors when assigning values in si_getsockopt.
N/A
qemu:local
=> net/socket/getsockopt: move the options check to the upper layer

Documentation/platforms/risc-v/eic7700x/index.rst, arch/risc-v/Kconfig, arch/risc-v/include/eic7700x/chip.h, arch/risc-v/include/eic7700x/irq.h, arch/risc-v/src/eic7700x/Make.defs, arch/risc-v/src/eic7700x/chip.h, arch/risc-v/src/eic7700x/eic7700x_allocateheap.c, arch/risc-v/src/eic7700x/eic7700x_head.S, arch/risc-v/src/eic7700x/eic7700x_irq.c, arch/risc-v/src/eic7700x/eic7700x_irq_dispatch.c, arch/risc-v/src/eic7700x/eic7700x_memorymap.h, arch/risc-v/src/eic7700x/eic7700x_mm_init.c, arch/risc-v/src/eic7700x/eic7700x_mm_init.h, arch/risc-v/src/eic7700x/eic7700x_pgalloc.c, arch/risc-v/src/eic7700x/eic7700x_start.c, arch/risc-v/src/eic7700x/eic7700x_timerisr.c, arch/risc-v/src/eic7700x/hardware/eic7700x_memorymap.h, arch/risc-v/src/eic7700x/hardware/eic7700x_plic.h
This PR adds support for the ESWIN EIC7700X RISC-V SoC. This will be used by the upcoming port of NuttX for PINE64 StarPro64 SBC.
Most of the code was derived from NuttX for SOPHGO SG2000 SoC. [The modified code is explained here](https://lupyuen.github.io/articles/starpro64#appendix-port-nuttx-to-starpro64)
`Kconfig`: Added ARCH_CHIP_EIC7700X for EIC7700X SoC
`include/eic7700x/chip.h`: EIC7700X Definitions
`include/eic7700x/irq.h`: External Interrupts
`src/eic7700x/chip.h`: Interrupt Stack Macro
`src/eic7700x/eic7700x_allocateheap.c`: Kernel Heap
`src/eic7700x/eic7700x_head.S`: Linux Header and Boot Code
`src/eic7700x/eic7700x_irq.c`: Configure Interrupts
`src/eic7700x/eic7700x_irq_dispatch.c`: Dispatch Interrupts
`src/eic7700x/eic7700x_memorymap.h`: Memory Map …
=> arch/risc-v/eic7700x: Add support for ESWIN EIC7700X SoC

drivers/lcd/Kconfig, drivers/lcd/st7789.c
It is now possible to configure SPI delays for st7789 controller if `CONFIG_SPI_DELAY_CONTROL` is set. Default values for SPI peripheral may be too long or too short, therefore the display controller set its own values as required. The default values in configuration are taken from the reference manual, but it is possible they may require tuning for different revisions or temperatures for example.
None unless `CONFIG_SPI_DELAY_CONTROL` is set, otherwise the delays are determined by ST7789 config options. This brings new configuration options for ST7789, but these have no effect on current config files.
Tested on 320 x 240 large display connected as 3 wire on SPI bus with DMA and 135 x 240 large display connected as 4 wire on SPI with DMA.
=> drivers/lcd/st7789: add option for SPI delay control

drivers/usbhost/usbhost_cdcacm.c, drivers/usbhost/usbhost_composite.c
usb host support more cdcacm composite device descriptor.
usb host cdcacm
```
1. Build and start sim usbhost:  sim:usbhost
2. Build and start sim usbdev in another terminal:  sim:usbdev
3. input "conn 1" in usbdev terminal
```
```
$ sudo ./nuttx                                                                                                                                                                                                                                              
usbhost_registerclass: Registering class:0x4007c5a0 nids:4
NuttShell (NSH) NuttX-12.8.0
nsh> sim_usbhost_waittask: connected
sim_usbhost_enumerate: Enumerate the device
sim_usbhost_ctrlin: type: 80 req: 06 value: 0100 index: 0000 len: 0012
usbhost_enumerate: maxpacksetsize: 64
usbhost_devdesc: class:239 subclass:2 …
```
=> usbhost: recognize sim usb cdcacm composite device

include/strings.h
libc/strings: fix compile warning if enable -Wshadow
Replace inline functions with macros to avoid confilcts with builtin definition
```
nuttx/include/strings.h:80:28: warning: declaration of 'ffs' shadows a built-in function [-Wshadow]
80 | static inline_function int ffs(int j)
|                            ^~~
nuttx/include/strings.h:94:28: warning: declaration of 'ffsl' shadows a built-in function [-Wshadow]
94 | static inline_function int ffsl(long j)
|                            ^~~~
nuttx/include/strings.h:109:28: warning: declaration of 'ffsll' shadows a built-in function [-Wshadow]
109 | static inline_function int ffsll(long long j)
|                            ^~~~~
```
N/A
ci-check
=> libc/strings: fix compile warning if enable -Wshadow

arch/risc-v/src/common/riscv_exception_common.S
This fixes a regression on those 64-bit risc-v systems, which can't do non-8-byte aligned accesses to the stack.
The issue was found on mpfs platform, which stopped booting after https://github.com/apache/nuttx/commit/b4174952843c2ffd9776d02bd4357b118e2c55b9
Should have no functional impact, except for those systems which dont' boot
Tested booting and ostest on rv-virt:nsh, rv-virt:nsh64 and on a custom mpfs board.
Tested backtrace functionality on rv-virt:nsh and rv-virt:nsh64 with the following config changes:
CONFIG_SCHED_BACKTRACE=y
CONFIG_FRAME_POINTER=y
CONFIG_DEBUG_SYMBOLS=y
and increased CONFIG_ARCH_INTERRUPTSTACK on rv-virt64.
**Backtrace tests:**
1. Added "*(int *)0 = 0;" into "hello" test application
2. Added "*(int *)0 = 0;" into timer interrupt code (set to trigger with a …
=> arch/risc-v/common: Fix unaligned stack access on 64-bit risc-v

drivers/net/lan9250.c
Fix print statement for uint8 and uint16 types.
Required due to efforts on fixing #15755 .
I had recently sent a PR on this same driver but missed a couple of lines.
Error example:
```
In file included from net/lan9250.c:34:
net/lan9250.c: In function 'lan9250_wait_ready':
net/lan9250.c:620:12: warning: format '%x' expects argument of type 'unsigned int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
620 |       nerr("ERROR: wait register:0x%02x, mask:0x%08x, expected:0x%08x\n",
|            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
621 |             address, mask, expected);
|                      ~~~~
|                      |
|                      uint32_t {aka long unsigned int}
net/lan9250.c:620:52: note: format string is defined here …
```
=> drivers/net: update format specifier on lan9250 driver

arch/arm/src/samv7/sam_spi.c
`ifdelay` description (delay between frames) matches the DLYBCT field (delay between consecutive transfers without removing chip select) much better compared to `stopdelay` (delay between last CLK and CS innactive). The option for `stopdelay` does not seem to be configurable in SAMv7 peripheral.
Should be minimal, most of the drivers do not use `spi_setdelay` at all and even if, this is configurable option disabled by default.
Tested with ST7789 display, the delay is set up. The delay is put between the consecutive transfers, so the effect now matches the description.
=> arch/arm/samv7/spi: fix ifdelay setup in spi_setdelay call

Documentation/components/drivers/special/wireless.rst, Documentation/components/drivers/special/wireless/rn2xx3.rst, drivers/wireless/lpwan/Kconfig, drivers/wireless/lpwan/rn2xx3/CMakeLists.txt, drivers/wireless/lpwan/rn2xx3/Make.defs, drivers/wireless/lpwan/rn2xx3/rn2xx3.c, include/nuttx/wireless/ioctl.h, include/nuttx/wireless/lpwan/rn2xx3.h
Add support for the RN2903 and RN2483 family of LoRa radio transceivers. This initial support includes transmit and receive functionality and configuration and reading of radio parameters like frequency and bandwidth.
NuttX users can now use these radio transceivers!
This changes touches the build system, wireless drivers and documentation. The documentation includes examples of how to use the driver and its available commands.
Testing was performed from an RP2040 based custom flight computer. The chip this code was tested again was the RN2903, but commands for both modules are the same. The only difference is the values allowed for each command, but the radio module does its own error checking so the driver code will not need to change between modules.
The test script that was used to …
=> drivers/wireless: Add support for the RN903 and RN2483 LoRa modules

net/can/can_callback.c
Fix timestamp in socket CAN. Right now the timestamp is only generated if there is no reader and the frame is stored in the read ahead list. This is solved by moving the timestamp generation before the code flow branch.
This has no impact other than having the timestamp working again.
As discussed in the mailing list, I have tested this fix in our current branch that is older than main. I can't test it on main because our whole system would not even compile. Updating the system to the latest Nuttx is a pending task in our backlog but it will take quite some time. Nevertheless, since this is a small change that doesn't add any new code but just moves the timestamp generation it may be worth to consider it.
=> net/can: fix timestamp

sched/init/nx_bringup.c
Fix build error with the following condition.
- CONFIG_BOARD_CRASHDUMP_CUSTOM=y
- CONFIG_COREDUMP=n
The condition for calling `coredump_initialize()` is incorrect.
CONFIG_BOARD_CRASHDUMP_CUSTOM is not dependent on CONFIG_COREDUMP.
=> sched/init: Fix build error with CONFIG_BOARD_CRASHDUMP_CUSTOM

arch/arm/src/stm32f0l0g0/stm32_spi.c
I found an issue when using SPI with nbits=8: SPI reads return unreliable results because SPI ignores nbits value and always performs 16-bit reads. The problem is fixed by adding specific logic to spi_readword() to handle the 8-bit case similar to the one already present on spi_writeword(). See also: http://efton.sk/STM32/gotcha/g22.html
This allows drivers using SPI with nbits=8 to perform reads properly.
One of our drivers, which uses spi with nbits=8, works on the stm32u5 but didn't on stm32f0l0g0 since many spi reads return 0 (when they shouldn't) or other unexpected results. After quite some testing we found this issue and after fixing it (applying this patch) it started working flawlessly.
=> arch/arm/src/stm32f0l0g0: Fix SPI reads when nbits is 8

tools/csvparser.h
Line 106 of the **syscall/syscall.csv** file exceeds the 256 character limit
```
106: Unexpected end of line: "FAR char * co"
make[1]: *** [makefile:108: .context] Error 4
make[1]: Leaving directory 'C:/nxtest/nuttx/syscall'
make: *** [tools/Win.mk:468: syscall\.context] Error 2
```
fixed **tools/csvparser.h** from
#define LINESIZE      (PATH_MAX > 256 ? PATH_MAX : 256)
to
#define LINESIZE      (PATH_MAX > 512 ? PATH_MAX : 512)
local 
**Without this PR**
generate **105** files with error
mksyscall.exe -p syscall.csv
106: Unexpected end of line: "FAR char * co"
106: Unexpected end of line: "FAR char * co"
**With this PR** 
generate **214** files without error
mksyscall.exe -p syscall.csv
=> tools/mksyscall: fix 106: Unexpected end of line: "FAR char * co"

arch/arm64/src/common/arm64_fork.c
arm64: Initialize sctrl_el1 when running fork
If fork does not initialize sctrl_el1 in arm64 platform, it will cause the child process to start incorrectly and the system to crash.
CI
=> [Bug]arm64: Initialize sctrl_el1 when running fork

include/nuttx/wdog.h, include/nuttx/wqueue.h, sched/wdog/wd_start.c, sched/wqueue/kwork_queue.c
This commit added support for periodic wdog.
This commit added `wd_start_period` and `wd_cancel_period` functions, which has no effect on original implementation.
Tested on QEMU/x86_64.
=> sched/wdog: Support for periodic wdog.

arch/arm/src/stm32h5/Kconfig, arch/arm/src/stm32h5/Make.defs, arch/arm/src/stm32h5/hardware/stm32_icache.h, arch/arm/src/stm32h5/stm32.h, arch/arm/src/stm32h5/stm32_icache.c, arch/arm/src/stm32h5/stm32_icache.h, arch/arm/src/stm32h5/stm32_start.c
Add support for the STM32H5 ICACHE peripheral. The CortexM33 does not have typical embedded icache and dcache. Instead STM32H5 provides the ICACHE as a separate peripheral that needs to be configured. This commit adds the stm32h5 specific icache driver. 
The driver named functions like those in <nuttx/cache.h>. However since the CortexM33 does not have cache itself, ARCH_ICACHE is not enabled. Therefore these stm32h5 specific functions were developed. 
Impacts the STM32H5 Architecture. Changes made were:
1. Kconfig - Added options for enabling the ICACHE as well as ICACHE configuration options. Configuration included enabling interrupts, setting regions, and enabling the hit/miss counters. 
2. Make.defs - Build stm32_icache.c if ICACHE is configured. 
3. stm32.h - Add stm32_icache.h. …
=> arch/arm/STM32H5: Initial ICACHE Support

drivers/syslog/Kconfig, drivers/syslog/syslog_channel.c, drivers/usbdev/cdcacm.c, include/nuttx/usb/cdcacm.h
add cdcacm syslog channel
syslog cdcacm
selftest
=> drivers/syslog: add cdcacm channel

audio/pcm_decode.c
audio/pcm_decode: fix typo in assert condition
should be shutdown not start
N/A
ci-check
=> audio/pcm_decode: fix typo in assert condition

boards/arm/stm32/stm32f401rc-rs485/src/CMakeLists.txt, boards/arm/stm32/stm32f401rc-rs485/src/Make.defs, boards/arm/stm32/stm32f401rc-rs485/src/stm32_bringup.c, boards/arm/stm32/stm32f401rc-rs485/src/stm32_gpio.c, boards/arm/stm32/stm32f401rc-rs485/src/stm32f401rc-rs485.h
This PR adds support to GPIO Subsystem for STM32F401RC RS485 board.
Users will be able to use GPIO subsystem, including adding GPIO as Output, Input and Input with Interruption.
- Select NSH or USBNSH Config.
- Use Menuconfig to enable CONFIG_DEV_GPIO  and CONFIG_EXAMPLES_GPIO
- Build and load the firmware in the board
- Access NuttShell and use gpio command:
```
nsh> gpio -o 0 /dev/gpio1
Driver: /dev/gpio1
Output pin:    Value=1
Writing:       Value=0
Verify:        Value=0
nsh> gpio -o 1 /dev/gpio1
Driver: /dev/gpio1
Output pin:    Value=0
Writing:       Value=1
Verify:        Value=1
nsh> gpio /dev/gpio0
Driver: /dev/gpio0
Input pin:     Value=0
nsh> gpio -w 1 /dev/gpio2
Driver: /dev/gpio2
Interrupt pin: Value=0
Verify:        Value=1
```
=> boards/arm/stm32f401rc-rs485: Add support to GPIO Subsystem

arch/risc-v/src/common/riscv_mtimer.c
This updates the risc-v tick timer to use oneshot timer's tick_* interface, which is meant for this purpose.
This also fixes the same clock drifting issue on risc-v, which was earlier fixed for arm 64 in 429252152a4e4cd54c1fb8b4b981ed5b1d85de8d, using the same mechanism: as the irq handling delay is unknown, align the next mtimecmp on the tick duration boundary.
Syncs the risc-v code with arm64, fixes the clock drift issue. Impacts all real risc-v hardware, can't be tested on qemu where the timer accuracy hides the problem.
Tested on MPFS250T hardware; this is the only risc-v HW which I have available atm.
=> arch/risc-v: tick timer improvements

Documentation/applications/system/uorb/index.rst
Documentation/uorb: fix typo in uorb chapter
fix typo "Two Tpyes" -> "Two Types"
N/A
ci-check
=> Documentation/uorb: fix typo in uorb chapter

sched/semaphore/sem_recover.c, sched/semaphore/sem_wait.c, sched/semaphore/sem_waitirq.c
The kernel mapping should be performed in sem_wait (thread level) as virtual memory mappings cannot be added from interrupt, at least for now.
The reason?
kmm_map() depends on mm_map_add(), which in turn uses a mutex for mutual exclusion. Using mutexes from interrupt level is not permitted.
Mapping tcb->waitobj into kernel virtual memory directly in sem_wait() makes sense, since accessing tcb->waitobj via a user virtual address can lead to unexpected results (the wrong mappings can be in place).
The impact is a bug fix in semaphore handling. The impacted targets are any that have CONFIG_MM_KMAP and CONFIG_BUILD_KERNEL set.
User impact: none
Build system impact: none
Documentation: none
rv-virt:knsh64 / ostest
MPFS target board with the aforementioned configs set.
NXP93 target board with …
=> sched/sem_waitirq: Move kmm_map() call to sem_wait()

net/can/can_callback.c
In a recent patch the socketcan timestamp generation was moved 
to add it also when there is an active reader (previously the timestamp
was only added before storing the CAN frame in the read-ahead list).
It was working fine but I realized that the can_callback function is also
called when sending frames. In this case, the IO block is not allocated
yet and the code breaks.
This PR is to only generate the timestamp if the IO block is not NULL
(reading path) and skip it when it is NULL (sending path)
Fixes a potential issue avoiding de-referencing a NULL pointer
As commented in the mailing list, we are using an older branch so I was not
able to test it on master, but I have tested it in our branch, were we found
this problem
=> net/can: Fix NULL dereference for I/O Block

fs/v9fs/virtio_9p.c
When the operating environment does not support virtio-9p and the virtio-9p server driver is not provided, -ENODEV should be returned for virtio-9p to avoid crash caused by continued execution.
-ENODEV is returned when virtio-9p create fails
This test is on my goldfish environment. When 9p is in an unsupported environment, it will return an error normally, avoiding continued execution and eventually causing the system to crash.
=> fs/virtio-9p:When virtio-9p is not supported, return -ENODEV

arch/risc-v/src/esp32c3/hal_esp32c3.mk, arch/risc-v/src/esp32c6/hal_esp32c6.mk, arch/risc-v/src/esp32h2/hal_esp32h2.mk
Fixes [GH Issue](https://github.com/apache/nuttx/issues/15932)
* arch/esp32[c3|c6|h2]: Fix efuse issue on MCUBoot
Fix build and initialization issues on EFuses using MCUBoot for RISC-V based Espressif devices
Impact on user: No, it just fixes a bug
Impact on build: No, it is just bugfix
```
make distclean && ./tools/configure.sh esp32c6-devkitc:mcubbot_nsh && kconfig-tweak -e CONFIG_EFUSE && kconfig-tweak -e CONFIG_ESPRESSIF_EFUSE && make olddefconfig && make -n bootloader && make ESPTOOL_BINDIR=./ -s -j && make flash EXTRAFLAGS="-Wno-cpp -Werror" ESPTOOL_BINDIR=./ ESPTOOL_PORT=/dev/ttyUSB0 -s -j$(nproc) && minicom
```
System builds and boots without any issue and efuse driver can be …
=> arch/esp32[c3|c6|h2]: Fix efuse issue on MCUBoot

arch/xtensa/src/common/xtensa_initialstate.c
To avoid level-1 interrupt break retrieve PC/A0/SP/A2 register, PS.EXCM set to 1 by CPU HW while handling exception/interrupt.
But if context switching happens and new thread created, the thread initial value of PS.EXCM is used.
Same behevior as ESP-IDF code:
https://github.com/espressif/esp-idf/blob/master/
components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c#L366
PS.EXCM initial value while new thread created.
tested by internal test case as below code
```
static void *BusyThread(void *arg) {
(void)arg;  // Avoid compiler warning
while (1) {
}
return NULL;
}
//-----------------------------------------------------------------------------
static void *DebugTestThread(void *arg) {
printf("Test Thread\n");
return NULL;
}
//--------------------------------------------------------------- …
```
=> arch/xtensa: set PS.EXCM initial value to 1 while new thread created

drivers/wireless/lpwan/Kconfig
There is no 'UART' symbol to depend on, so this PR updates that dependency to the correct one, `SERIAL`.
Users can now actually select this driver.
Before this change, the RN2XX3 does not show up under the LPWAN configuration menu. After this change, it does for devices with `SERIAL`, and it builds successfully when selected. Testing performed with an STM32H743 image.
=> drivers/wireless/lpwan/rn2xx3: Fix UART dependency

arch/x86_64/include/intel64/arch.h, arch/x86_64/src/common/x86_64_internal.h, arch/x86_64/src/intel64/Kconfig, arch/x86_64/src/intel64/intel64_freq.c
This commit introduces support for querying TSC frequency using CPUID 0x40000010.
Only affects TSC frequency on x86/64 platforms: when `CONFIG_ARCH_INTEL64_TSC_FREQ_VMWARE` is enabled, TSC frequency is obtained through CPUID `X86_64_CPUID_TSC_VMWARE`.
Tested on QEMU/x86_64 and real x86_64 machine running ACRN Hypervisor.
This function can be tested with the following command: `sudo qemu-system-x86_64 -enable-kvm -cpu host,+invtsc,+vmware-cpuid-freq -m 2G -kernel nuttx -nographic -serial mon:stdio -s`
=> arch/x86_64: Implement TSC frequency query via CPUID 0x40000010

boards/Kconfig
In order to reduce the cost of using coredump, we disable `BOARD_COREDUMP_COMPRESSION` by default when it is not necessary.
So I adjusted the conditions for enable of `BOARD_COREDUMP_COMPRESSION`
`BOARD_COREDUMP_COMPRESSION` depends on `LIBC_LZF`, not select it, and when `BOARD_COREDUMP_SYSLOG` is enabled, it will be turned on by default
This tweak works fine in my environment and it is enabled/off as expected
=> coredump:adjust BOARD_COREDUMP_COMPRESSION

boards/arm/imx6/sabre-6quad/src/imx_bringup.c
**Summary:**  
* Automatically mount tmpfs during board bring-up when configured  
* Modifies board bring-up code to handle tmpfs initialization  
* Checks for `CONFIG_FS_TMPFS` and mounts tmpfs at `CONFIG_LIBC_TMPDIR`  
* Includes error logging for mount failures  
**Impact:**  
* **New feature added?** YES - Adds automatic tmpfs mounting support for the i.MX6 Sabre board.  
* **Impact on user?** YES - Users enabling `CONFIG_FS_TMPFS` no longer need to manually mount tmpfs.  
* **Impact on build?** NO - No build system changes; relies on existing configuration.  
* **Impact on hardware?** NO - Purely software/filesystem functionality.  
* **Impact on documentation?** NO - No documentation updates included in this change.  
* **Impact on security?** NO - Does not introduce security risks …
=> boards/imx6: Add support for mounting tmpfs file system

drivers/thermal/thermal_step_wise.c
Update state when temp is stable, fix cooling state not decreasing error when the temperature is kept at low trip(stable, not dropping).
drivers/thermal;
Test on "sim:thermal", log is from /proc/thermal/cpu-thermal.
Please see [thermal/thermal_dummy.c](https://github.com/apache/nuttx/blob/master/drivers/thermal/thermal_dummy.c#L111) for trip point details.
```bash
z:cpu-thermal t:71 t:1 h:16 l:0 c:fan0 s:16|16
z:cpu-thermal t:65 t:1 h:16 l:0 c:fan0 s:15|15
... ...
z:cpu-thermal t:65 t:1 h:16 l:0 c:fan0 s:15|15
z:cpu-thermal t:65 t:1 h:16 l:0 c:fan0 s:15|15
... ...
z:cpu-thermal t:65 t:1 h:16 l:0 c:fan0 s:0|0
```
=> drivers/thermal: Update state when temp is stable

Documentation/platforms/arm64/a527/index.rst, arch/arm64/Kconfig, arch/arm64/include/a527/chip.h, arch/arm64/include/a527/irq.h, arch/arm64/src/a527/CMakeLists.txt, arch/arm64/src/a527/Make.defs, arch/arm64/src/a527/a527_boot.c, arch/arm64/src/a527/a527_boot.h, arch/arm64/src/a527/a527_initialize.c, arch/arm64/src/a527/a527_lowputc.S, arch/arm64/src/a527/a527_serial.c, arch/arm64/src/a527/a527_textheap.c, arch/arm64/src/a527/a527_timer.c, arch/arm64/src/a527/chip.h
This PR adds support for the Allwinner A527 Arm64 SoC. This will be used by the upcoming port of NuttX for PINE64 Yuzuki Avaota-A1 SBC. And for Arm64 PR Test Bot.
Most of the code was derived from NuttX for QEMU Arm64 Kernel Build `qemu-armv8a:knsh`. [The modified code is explained here](https://lupyuen.github.io/articles/avaota#appendix-port-nuttx-to-avaota-a1)
`Kconfig`: Added ARCH_CHIP_SUNXI for Allwinner 64-bit SoCs. Added ARCH_CHIP_SUNXI_A527 for A527 SoC.
`include/a527/chip.h`: A527 Definitions
`include/a527/irq.h`: External Interrupts
`src/a527/chip.h`: Memory Map
`src/a527/a527_boot.c`, `a527_boot.h`: Startup Code
`src/a527/a527_initialize.c`: Power Management
`src/a527/a527_lowputc.S`: UART Output
`src/a527/a527_serial.c`: Serial Driver
`src/a527/a527_textheap.c`: Text Heap …
=> arch/arm64/a527: Add support for Allwinner A527 SoC

drivers/i2c/i2c_slave_driver.c, drivers/ipcc/ipcc_read.c, drivers/ipcc/ipcc_write.c, drivers/misc/goldfish_pipe.c, drivers/pipes/pipe_common.c, drivers/spi/spi_slave_driver.c, drivers/wireless/bluetooth/bt_slip.c, fs/notify/inotify.c
fs/drivers: Avoid causing a busy loop in the program due to context switching induced by sem_post.
examples:
There are two threads involved: thread A with a priority of 100 and thread B with a priority of 101. Here's how they interact:
When thread A releases a semaphore, thread B is scheduled to execute some code and may reacquire the semaphore. If no other tasks are ready, thread A will be scheduled to run.
This continuous process can lead to a busy loop.
```
errcode:
while (nxsem_get_value(&priv->wait, &semcount) >= 0 &&  semcount <= 0)                                                              
{                                                 
nxsem_post(&priv->wait);     
}
```
bug fix
localtest
=> fs/drivers: Avoid causing a busy loop due to context switching induced by sem_post.

CONTRIBUTING.md
* This change comes from vast mailing list discussions on low PR/COMMIT
quality, breaking changes, code quality, long term self-compatibility
and maintenance, review problems, and how to improve things.
* Contributing Guidelines updates vote history:
1. https://www.mail-archive.com/dev@nuttx.apache.org/msg12584.html
2. https://www.mail-archive.com/dev@nuttx.apache.org/msg12723.html
=> 202503 Apache NuttX RTOS Contributing Guidelines update.

Documentation/platforms/risc-v/esp32c3/index.rst, Documentation/platforms/risc-v/esp32c6/index.rst, Documentation/platforms/risc-v/esp32h2/index.rst, Documentation/platforms/xtensa/esp32/index.rst, Documentation/platforms/xtensa/esp32s2/index.rst, Documentation/platforms/xtensa/esp32s3/index.rst
This PR improve esptool installation docs and updates supported peripheral list.
- General improvements for documentation on Espressif devices.
- Adds sections to assist on esptool installation with guide for those unfamiliar with Python packages.
- Adds build and flash example.
- Update table of supported peripherals for each SoC.
- Impact on user: No.
- Impact on build: No.
- Impact on hardware: No.
- Impact on documentation: Yes. Updates documentation related to Espressif devices.
- Impact on security: No.
- Impact on compatibility: No.
Documentation was built as usual.
Used virtual environment with the packages available on the Pipfile.
Run `make html` on Documentation directory.
HTML build output:
```
$ make -j html
Removing everything under '_build'...
Running Sphinx v7.3.7
myst …
```
=>  documentation: update documentation on Espressif devices 

arch/arm64/src/imx9/Make.defs, arch/arm64/src/imx9/hardware/imx9_ele.h, arch/arm64/src/imx9/imx9_ele.c, arch/arm64/src/imx9/imx9_ele.h, arch/arm64/src/imx9/imx9_trdc.c, tools/imx9/Config.mk, tools/imx9/Makefile.host
Moved imx9 edgelock enclave (ELE) handling from imx9_trdc.c to own imx9_ele.c file.
Add some new messages to ele API.
Updated ele fw version to 1.3.0.
Fix channel bug on imx9_ele_sendmsg() and imx9_ele_receivemsg()
Impacts only imx93 bootloader sw.
New features, no impact on existing features.
Tested with custom imx93 hardware
=> arch/arm64/imx9: Support for imx9 edgelock enclave

drivers/syslog/vsyslog.c, sched/sched/sched_setscheduler.c
sched: simplify call of get current tcb
Replace get current tcb method from nxsched_get_tcb(nxsched_gettid()) to this_task(),
change two function calls with inline function to improve performance:
FAR struct tcb_s *tcb = nxsched_get_tcb(nxsched_gettid());
FAR struct tcb_s *tcb = this_task();
N/A
sim/nsh,ostest
=> sched: simplify call of get current tcb

fs/vfs/fs_poll.c
* fs/vfs/fs_poll: Add noinstrument_function to poll_notify function
Add the noinstrument_function attribute to the poll_notify function to avoid it looping if -finstrument-functions is set to the fs/vfs files.
Impact on user:YES. Prevent a failure when instrumentation is enabled.
First of all, enable instrumentation for fs/vfs files with the following patch:
```
diff --git a/fs/vfs/Make.defs b/fs/vfs/Make.defs
index 30292d787f..e00b361407 100644
--- a/fs/vfs/Make.defs
+++ b/fs/vfs/Make.defs
@@ -22,6 +22,8 @@
+CFLAGS += -finstrument-functions
+
CSRCS += fs_chstat.c fs_close.c fs_dup.c fs_dup2.c fs_fcntl.c fs_epoll.c
CSRCS += fs_fchstat.c fs_fstat.c fs_fstatfs.c …
```
=> fs/vfs/fs_poll: Add noinstrument_function to poll_notify function

tools/bdf-converter.c
Changing readingbitmap from bool to int, initializing it to the number of bitmaps allocated, decrementing it each time a bitmap is consumed, and using it as the termination condition for the while loop, ensures that loop termination does not depend on data from the file.
Note: Patch provided by @hartmannathan.
Fix user controllable chunk allocation condition when crafted input file is provided.
```
% uname -a
FreeBSD octagon 14.2-RELEASE-p1 FreeBSD 14.2-RELEASE-p1 GENERIC amd64
% cd tools
% gcc -o bdf-converter bdf-converter.c
% ./bdf-converter invalid.tff
Generated "nxfonts_myfont.h"
% cat nxfonts_myfont.h
%
```
=> tools/bdf-converter: Fix loop termination condition.

drivers/sensors/fakesensor_uorb.c
Allow fakesensor to read baro data and publish it in the same way as the other supported fakesensor data types. Adds a single function that reads from a CSV file and publishes new data.
Fakesensor now supports baro data. Slightly more convenient to debug systems that use barometers.
Testing was performed on the NuttX simulator with the sim:nsh configuration (and run on Ubuntu - WSL2). The changes were tested by creating a fakesensor and providing a CSV file with sample barometric data. The data was then collected and printed using the `uorb_listener` application
```
nsh> uorb_listener -r 50 -n 10 sensor_baro0
Mointor objects num:1
object_name:sensor_baro, object_instance:0
sensor_baro(now:68460409):timestamp:68460374,pressure:976.869995,temperature:24.600000 …
```
=> drivers/sensors/fakesensor: Add baro sensor type to fakesensor

tools/checkpatch.sh
* BSD has its own BSD Make that is incompatible with GNU Make.
* When BSD is detected use (gnu) gmake in place of (bsd) make.
* This fixes nxstyle build inside tools/checkpatch.sh.
* `tools/checkpatch.sh` now works correctly on BSD (`nxstyle` build).
```
% uname -a
FreeBSD octagon 14.2-RELEASE-p1 FreeBSD 14.2-RELEASE-p1 GENERIC amd64
```
Before:
```
% ../nuttx.git/tools/checkpatch.sh -f path/to/file.c
==> MAKE IS make
make: "/XXX/nuttx.git/tools/Makefile.host" line 25: Cannot open /tools/Config.mk
make: "/XXX/nuttx.git/tools/Makefile.host" line 29: Invalid line type
(..)
make: Fatal errors encountered -- cannot continue
```
After:
```
% uname -a
FreeBSD octagon 14.2-RELEASE-p1 FreeBSD 14.2-RELEASE-p1 GENERIC amd64
octagon% ./tools/checkpatch.sh
USAGE: ./tools/checkpatch.sh [options] …
```
=> tools/checkpatch: Use gmake on BSD, make otherwise.

arch/arm/src/mcx-nxxx/hardware/n236/n236_clock.h, arch/arm/src/mcx-nxxx/hardware/nxxx_lptmr.h
This adds memory mapped register definitions for:
- SYSCON_CLOCKCTRL (Controls internal FRO output)
- LPTMR (Low Power Timer)
Code impact is adding register definitions to control hardware, no new executable code, only headers.
User impact, build impact etc. are none
None, as no testing is needed (there is no executable code added).
=> arch/mcx-nxxx: Add register definitions for SYSCON_CLOCKCTRL and LPTMR

include/nuttx/lib/math.h
add missing HUGE_VALF and HUGE_VALL definitions to NuttX math.h
fix compilation errors for third party code that needs these definitions and we build with NuttX math library
lely-canopen compilation on x86 fails without these definitions
=> include/nuttx/math.h: add missing HUGE_VALF and HUGE_VALL

boards/arm/stm32/nucleo-f302r8/src/CMakeLists.txt, boards/arm/stm32/nucleo-f302r8/src/Make.defs, boards/arm/stm32/nucleo-f302r8/src/stm32_adc.c
Add ADC support for nucleo-f302r8.
CN8 pins 35, 36, 37 and 38 are used.
ADC can be used with nucleo-f302r8
nucleo-f302r8 with custom example
=> boards/nucleo-f302r8: add ADC support

Documentation/applications/benchmarks/mtd/index.rst
Add documentation entry for the `mtd` application (https://github.com/apache/nuttx-apps/pull/3033).
Impact on user: NO.
Impact on documentation: YES.
Build the documentation with:
```
$ cd Documentation; make HTML
Removing everything under '_build'...
Running Sphinx v8.1.3
loading translations [en]... done
Converting `source_suffix = ['.rst', '.md']` to `source_suffix = {'.rst': 'restructuredtext', '.md': 'restructuredtext'}`.
myst v4.0.1: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=set(), disable_syntax=[], all_links_external=False, links_external_new_tab=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), …
```
=> Documentation/benchmarks/mtd: Add MTD transfer rate test app docs.

Documentation/applications/system/uorb/index.rst
fix typo "Two Tpyes" -> "Two Types"
RELEASE
CI
=> {bp-15977] Documentation/uorb: fix typo in uorb chapter

audio/pcm_decode.c
should be shutdown not start
RELEASE
CI
=> {bp-15957} audio/pcm_decode: fix typo in assert condition

drivers/net/lan9250.c
Fix print statement for uint8 and uint16 types.
RELEASE
CI
=> {bp-15915} drivers/net: update format specifier on lan9250 driver

arch/arm/src/qemu/qemu_allocateheap.c, arch/risc-v/src/bl808/bl808_allocateheap.c, arch/risc-v/src/bl808/bl808_start.c, arch/risc-v/src/bl808/chip.h, arch/risc-v/src/c906/c906_allocateheap.c, arch/risc-v/src/jh7110/chip.h, arch/risc-v/src/jh7110/jh7110_allocateheap.c, arch/risc-v/src/jh7110/jh7110_start.c, arch/risc-v/src/k210/chip.h, arch/risc-v/src/k230/chip.h, arch/risc-v/src/k230/k230_allocateheap.c, arch/risc-v/src/litex/chip.h, arch/risc-v/src/mpfs/chip.h, arch/risc-v/src/mpfs/mpfs_allocateheap.c, arch/risc-v/src/qemu-rv/chip.h, arch/risc-v/src/qemu-rv/qemu_rv_allocateheap.c, arch/risc-v/src/qemu-rv/qemu_rv_start.c, arch/risc-v/src/sg2000/chip.h, arch/risc-v/src/sg2000/sg2000_allocateheap.c, arch/risc-v/src/sg2000/sg2000_start.c
This PR fixes the typos in the Code Comments of chip.h, allocateheap.c and start.c. The typos were discovered here:
- https://github.com/apache/nuttx/pull/15921
RELEASE
CI
=> {bp-15922} arch/arm, risc-v: Fix typos in Code Comments

drivers/serial/ptmx.c
The alloctab can be looped, if the first check the corresponding bit is set, it will not continue to loop
RELEASE
CI
=> {bp-15924} ptmx: When alloc minor, skip the start addr if it has been used

arch/risc-v/src/common/riscv_exception_common.S
This fixes a crash at boot on 64-bit risc-v systems which need to store 64-bit registers to the stack aligned to 8 byte boundary.
Specifically, this uses 8 bytes to store ra and s0 on rv32 and 16 bytes on rv64, and does the register stores and loads properly aligned acc. to the register size.
RELEASE
CI
=> {bp-15941} arch/risc-v/common: Fix unaligned stack access on 64-bit risc-v

include/strings.h
Replace inline functions with macros to avoid confilcts with builtin definition
nuttx/include/strings.h:80:28: warning: declaration of 'ffs' shadows a built-in function [-Wshadow]
80 | static inline_function int ffs(int j)
|                            ^~~
nuttx/include/strings.h:94:28: warning: declaration of 'ffsl' shadows a built-in function [-Wshadow]
94 | static inline_function int ffsl(long j)
|                            ^~~~
nuttx/include/strings.h:109:28: warning: declaration of 'ffsll' shadows a built-in function [-Wshadow]
109 | static inline_function int ffsll(long long j)
|                            ^~~~~
RELEASE
CI
=> {bp-15944} libc/strings: fix compile warning if enable -Wshadow

arch/arm/src/stm32f0l0g0/stm32_spi.c
I found an issue when using SPI with nbits=8: SPI reads return unreliable results because SPI ignores nbits value and always performs 16-bit reads.
RELEASE
CI
=> {bp-15949} arch/arm/src/stm32f0l0g0: Fix SPI reads when nbits is 8

CONTRIBUTING.md
* This change comes from vast mailing list discussions on low PR/COMMIT quality, breaking changes, code quality, long term self-compatibility and maintenance, review problems, and how to improve things.
* Contributing Guidelines updates vote history:
1. https://www.mail-archive.com/dev@nuttx.apache.org/msg12584.html
2. https://www.mail-archive.com/dev@nuttx.apache.org/msg12723.html
RELEASE
CI
=> {bp-15950} 202503 Apache NuttX RTOS Contributing Guidelines update.

sched/init/nx_bringup.c
Fix build error with the following condition.
- CONFIG_BOARD_CRASHDUMP_CUSTOM=y
- CONFIG_COREDUMP=n
The condition for calling `coredump_initialize()` is incorrect. CONFIG_BOARD_CRASHDUMP_CUSTOM is not dependent on CONFIG_COREDUMP.
RELEASE
CI
=> {bp-15951} sched/init: Fix build error with CONFIG_BOARD_CRASHDUMP_CUSTOM

tools/csvparser.h
line 106 exceeds the 256 character limit
106: Unexpected end of line: "FAR char * co"
make[1]: *** [makefile:108: .context] Error 4
make[1]: Leaving directory 'C:/nxtest/nuttx/syscall'
make: *** [tools/Win.mk:468: syscall\.context] Error 2
fixed tools/csvparser.h from
RELEASE
CI
=> {bp-15953} tools/mksyscall: fix 106: Unexpected end of line: "FAR char * co"

fs/v9fs/virtio_9p.c
When the operating environment does not support virtio-9p and the virtio-9p server driver is not provided, -ENODEV should be returned for virtio-9p to avoid crash caused by continued execution.
RELEASE
CI
=> {bp-15963} fs/virtio-9p:When virtio-9p is not supported, return -ENODEV

net/can/can_callback.c
In a recent patch the socketcan timestamp generation was moved to add it also when there is an active reader (previously the timestamp was only added before storing the CAN frame in the read-ahead list).
It was working fine but I realized that the can_callback function is also called when sending frames. In this case, the IO block is not allocated yet and the code breaks.
This PR is to only generate the timestamp if the IO block is not NULL (reading path) and skip it when it is NULL (sending path)
RELEASE
CI
=> {bp-15965} net/can: Fix NULL dereference for I/O Block

arch/risc-v/src/esp32c3/hal_esp32c3.mk, arch/risc-v/src/esp32c6/hal_esp32c6.mk, arch/risc-v/src/esp32h2/hal_esp32h2.mk
Fix build and initialization issues on EFuses using MCUBoot for RISC-V based Espressif devices
RELEASE
CI
=> {bp-15992} arch/esp32[c3|c6|h2]: Fix efuse issue on MCUBoot

tools/bdf-converter.c
Changing readingbitmap from bool to int, initializing it to the number of bitmaps allocated, decrementing it each time a bitmap is consumed, and using it as the termination condition for the while loop, ensures that loop termination does not depend on data from the file.
Note: Patch provided by Nathan Hartman.
RELEASE
CI
=> [bp-16000} tools/bdf-converter: Fix loop termination condition.

arch/risc-v/src/common/Make.defs
AIA releted source files in the Make.defs are not right. Replace them with the right source.
Fixes: 5f70307111 ("arch/risc-v: introduce AIA support")
RELEASE
CI
=> {bp-16014} arch/risc-v: Fix wrong source name in make script

tools/checkpatch.sh
* BSD has its own BSD Make that is incompatible with GNU Make.
* When BSD is detected use (gnu) gmake in place of (bsd) make.
* This fixes nxstyle build inside tools/checkpatch.sh.
RELEASE
CI
=> [bp-16015} tools/checkpatch: Use gmake on BSD, make otherwise.

arch/arm/src/at32/at32_start.c, arch/arm/src/cxd32xx/cxd32_start.c, arch/arm/src/eoss3/eoss3_start.c, arch/arm/src/gd32f4/gd32f4xx_start.c, arch/arm/src/stm32/stm32_start.c, arch/arm/src/stm32f7/stm32_start.c
add missing itm_syslog.h include for archs that use itm_syslog_initialize() to fix compiler errors:
error: implicit declaration of function 'itm_syslog_initialize'
Issue reported by rentzboy in https://github.com/apache/nuttx/issues/16017
RELEASE
CI
=> {bp-16018} arch/arm: add missing itm_syslog.h include

include/nuttx/lib/math.h
add missing HUGE_VALF and HUGE_VALL definitions to NuttX math.h
RELEASE
CI
=> {bp-16028} include/nuttx/math.h: add missing HUGE_VALF and HUGE_VALL

drivers/mtd/ramtron.c, include/nuttx/mtd/mtd.h
Adds a device ID to `ramtron_initialize`, which is stored in the `ramtron_dev_s` structure. This ID is used when calling SPI_SELECT to board specific logic to allow chip select on the SPI bus.
This change is NOT backwards compatible, as it changes the function signature of `ramtron_initialize`.
This implementation is based on the handling of chip select in `nuttx/drivers/mtd/sst26.c:sst26_initialize_spi()`.
Additional Changes:
- Add MB85RS64V to ramtron supported parts list.
Additional contributors: @ArrestedLightning 
This change makes the ramtron driver compatible with boards that have more than one memory device per SPI peripheral. Its implementation is based on other mtd …
=> driver/mtd: ramtron multi-device spi bus support

arch/arm64/src/a64/a64_timer.c, arch/arm64/src/bcm2711/bcm2711_timer.c, arch/arm64/src/common/arm64_arch_timer.c, arch/arm64/src/common/arm64_arch_timer.h, arch/arm64/src/common/arm64_cpustart.c, arch/arm64/src/common/arm64_smp.h, arch/arm64/src/fvp-v8r/fvp_timer.c, arch/arm64/src/goldfish/goldfish_timer.c, arch/arm64/src/imx8/imx8_timer.c, arch/arm64/src/imx9/imx9_timer.c, arch/arm64/src/qemu/qemu_timer.c, arch/arm64/src/rk3399/rk3399_timer.c, arch/arm64/src/zynq-mpsoc/zynq_timer.c
- Optimized the initialization process of percpu timer
- Fixed the time drift problem caused by integer division precision loss when USEC_PER_TICKS is set to a low value
This patch affects the behavior and timing accuracy of the Generic Timer on the ARM64 platform
Tested on QEMU/aarch64-qemu-virt and IMX8QM-MEK.
=> arch/arm64: Improvements on ARM generic timer drivers. 

arch/arm/src/samv7/sam_spi.c
ifdelay description (delay between frames) matches the DLYBCT field (delay between consecutive transfers without removing chip select) much better compared to stopdelay (delay between last CLK and CS innactive). The option for stopdelay does not seem to be configurable in SAMv7 peripheral.
RELEASE
CI
=> {bp-15900} arch/arm/samv7/spi: fix ifdelay setup in spi_setdelay call

drivers/serial/serial_gdbstub.c
bug fix, gdbstub can't use
gdbstub
gdbstub demo on stm32
=> serial:gdbstub need enable irq

tools/ci/cibuild.sh, tools/sethost.sh
After [MSYS2](https://github.com/msys2/setup-msys2/releases/tag/v2.27.0) updated the package on GitHub
there was a slowdown in building NuttX in the MSYS2 job.
It went from an average of 6 minutes to 10 minutes !!!
The purpose of this PR is to speed up the build to decrease the usage of the Windows runner.
Modified Files
tools/ci/cibuild.sh
tools/sethost.sh
make olddefconfig -j 4 -> make olddefconfig
workaround for remove
```
Cleaning...
Configuring...
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule. 
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```
before the change
https://github.com/NuttX/nuttx/actions/runs/13472281038/job/37647297902#lo …
=> CI: Improved speed to build nuttx on MSYS2 job

boards/arm/nrf52/nrf52840-dk/Kconfig, boards/arm/nrf52/nrf52840-dk/src/CMakeLists.txt, boards/arm/nrf52/nrf52840-dk/src/Make.defs, boards/arm/nrf52/nrf52840-dk/src/nrf52840-dk.h, boards/arm/nrf52/nrf52840-dk/src/nrf52_bringup.c, boards/arm/nrf52/nrf52840-dk/src/nrf52_gpio.c, boards/arm/nrf52/nrf52840-dk/src/nrf52_userleds.c
* boards/arm/nrf52/nrf52840-dk: add GPIO driver based on leds and buttons
With this change we can use on board leds and buttons with gpio driver
leds and buttons can be used with gpio driver when `CONFIG_NRF52840DK_BTNLEDS_GPIO=y`
nrf52840-dk with custom app that use gpio driver interface
=> boards/arm/nrf52/nrf52840-dk: add GPIO driver based on leds and buttons

arch/arm/src/imx6/imx_boot.c, arch/arm/src/imx9/imx9_start.c, arch/arm/src/imxrt/imxrt_start.c, arch/arm/src/kinetis/kinetis_start.c, arch/arm/src/lc823450/lc823450_start.c, arch/arm/src/mcx-nxxx/nxxx_start.c, arch/arm/src/mx8mp/mx8mp_start.c, arch/arm/src/s32k1xx/s32k1xx_start.c, arch/arm/src/s32k3xx/s32k3xx_start.c, arch/arm/src/sam34/sam_start.c, arch/arm/src/sama5/sam_boot.c, arch/arm/src/samd5e5/sam_start.c, arch/arm/src/samv7/sam_start.c, arch/arm/src/stm32f7/stm32_start.c, arch/arm/src/stm32h7/stm32_start.c, arch/arm/src/xmc4/xmc4_start.c, include/nuttx/compiler.h
Add `no_builtin` for `memcpy/memset` to the startup code of boards
with `CONFIG_ARCH_RAMFUNCS`, because certain compilers call `memcpy/memset`
instead of the explicit `for` loop. This will cause a crash if `memcpy/memset`
are mapped to RAM because the function that copies them to RAM is called later,
resulting in undefined code being executed.
- Using `memcpy/memset` as RAMFUNCS is possible
- The problem was observed with the following compiler: `arm-none-eabi-gcc (15:13.2.rel1-2) 13.2.1 20231009`
- This is the default `arm-none-eabi-gcc` that is currently used on Ubuntu Noble 
- Was tested with a STM32F765
Before the patch there was a call to `memset` in the startup:
```
0  0x000006c4 in memset (s=0x20021b00 <g_intstackalloc>, c=c@entry=0, n=91844) at …
```
=> arch/arm: Fix crash when using memcpy/memset as RAMFUNCS

arch/xtensa/src/esp32/esp32_spi.c, arch/xtensa/src/esp32/hardware/esp32_spi.h
arch/esp32_spi: Add check to see if the TX_FIFO is empty to avoid sending empty data
New Feature/Change: Issue fix (no new feature).
User Impact: No
Hardware Impact: Only ESP32; other architectures unaffected.
Security: No
Compatibility: Backward-compatible; no breaking changes.
ESP32-DevKitC, NuttX with SPI configurations, ESP32 as SPI master device send data.
=> arch/esp32_spi: Add check to see if the TX_FIFO is empty

arch/xtensa/include/esp32/partition.h, arch/xtensa/src/esp32/esp32_partition.c, arch/xtensa/src/esp32/esp32_spiflash.c, arch/xtensa/src/esp32/esp32_spiflash.h
arch/esp32_partition: 
- Relocate the enum ota_img_ctrl_e and ota_img_bootseq_e to a directory visible to the application.
- Inspect if the MTD partition (factory/ota_0/ota_1) is mapped as text.
- Adding an ioctl interface ota_invalidate_bootseq() to the ESP32 partitions, by deleting the corresponding otadata, makes the   boot sequence (ota_0/1) invalid.
- Read data from SPI Flash at designated address (with decryption)
- Related PR([#13601](https://github.com/apache/nuttx/pull/13601))([#14214](https://github.com/apache/nuttx/pull/14214))
when esp32 device enable legacy IDF bootloader
Enable configuration items such as CONFIG_ESP32_PARTITION_TABLE, and the application calls the relevant interfaces.
=> arch/esp32_partition: add some partition operation interfaces for esp32

arch/xtensa/src/esp32/Kconfig, arch/xtensa/src/esp32/esp32_start.c, arch/xtensa/src/esp32s2/Kconfig, arch/xtensa/src/esp32s2/esp32s2_start.c, arch/xtensa/src/esp32s3/Kconfig, arch/xtensa/src/esp32s3/esp32s3_start.c
A trivial change. Considering the CONFIG item is from [the ESP-IDF performance tuning guide,](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/performance/speed.html#improving-startup-time), it would be beneficial to include it in Nuttx as well. Begin by adding it to 'arch/xtensa', which currently lacks it.
- One more option for startup performance tuning.
- build against
- esp32-devkitc:psram
- _Skipped ESP32S2 since no existing board configure has SPIRAM enabled._
- esp32s3-devkit:psram_quad
=> feat(arch/xensa): add CONFIG_SPIRAM_MEMTEST from ESP-IDF

arch/arm/src/stm32/stm32_alarm.h, arch/arm/src/stm32/stm32_rtc_lowerhalf.c, arch/arm/src/stm32/stm32_rtcounter.c
Summary: 
stm32: support querying a previously set RTC alarm In the STM32F1xx series
Impact:
When using the stm32f1xx series MCU, the alarm function can be used, but when we enabled the CONFIG_RTC_ALARM configuration, an error was reported due to the inability to find the specific implementation of rdalarm.
Testing: 
In our own projects, we have done alarm verification using the STM32F103RE..
=>  arch/arm/stm32: fix stm32f1xx alarm support 

arch/arm/Kconfig, arch/arm/src/common/gnu/arm_signal_handler.S
This guards use of thumb_func with ARM_THUMB so that PROTECTED build can work in non-THUMB mode.
arm 32 bit devices w/o ARM_THUMB can do signal handling in PROTECTED mode now.
- local checks with qemu-armv7r:pnsh, qemu-armv7a:knsh with ARM_THUMB off, with apt-installed `gcc-arm-none-eabi` toolchain 10.3.1 on Ubuntu 22.04.
- CI checks
=> arch/arm: guard .thumb_func use

tools/espressif/check_esptool.py
- Replace version checking logic using pkg_resources and importlib with a subprocess call to `esptool.py version`
- This change enhances compatibility with esptool installed via pipx and simplifies the version retrieval process
- No functional changes; the script continues to prompt for installation if esptool is not found
- Increases maintainability by reducing dependency on Python version checks
GitHub CI and local build:
```
Create version.h
CPP:  /home/huang/Work/spark/nuttx/arch/xtensa/src/chip/esp-hal-3rdparty/components/esp_rom/esp32s3/ld/esp32s3.rom.api.ld-> /home/huang/Work/spark/nuttx/arch/xtensa/src/chip/esp-hal-3rdparty/components/esp_rom/espCPP:  /home/huang/Work/spark/nuttx/arch/xtensa/src/chip/esp-hal-3rdparty/components/esp_rom/esp32s3/ld/esp32s3.rom.ld-> …
```
=> tools/espressif: Improve version checking by subprocess

arch/xtensa/src/esp32/esp32_himem_chardev.c
arch/esp32_himemcdev: 
- Multiple instances of struct file for the same file share the inode, ensuring that the mapping status is associated with the file entity rather than a single descriptor.
- Avoid redundant mapping operations caused by multiple descriptors operating on the same file, reducing performance overhead.
Why: The original file-pointer-based check caused incorrect mapping behavior for multiple opens of the same device, leading to memory corruption or leaks.
Consequences: Repeated calls on the same device could corrupt mappings or leave stale resources.
New Feature/Change:
﻿Bug Fix: Corrects mapping logic for ESP32 himem (no new features).
User Impact:
﻿Functional Change: Users accessing the same himem device from multiple threads/processes will no longer encounter mapping …
=> arch/esp32_himemcdev: Replace file descriptor with node

drivers/serial/serial_gdbstub.c
bug fix, gdbstub can't use
RELEASE
CI
=> {bp-16077} drivers/serial: gdbstub need enable irq

arch/arm/src/sama5/sam_spi.c
ifdelay description (delay between frames) matches the DLYBCT field (delay between consecutive transfers without removing chip select) much better compared to stopdelay (delay between last CLK and CS inactive). The option for stopdelay does not seem to be configurable in SAMA5 peripheral.
RELEASE
CI
=> {bp-16078} arch/arm/sama5/spi: fix ifdelay setup in spi_setdelay call

drivers/mtd/mtd_cfi.c
drivers/mtd/mtd_cfi: Add MTDIOC_ERASESTATE
We need to give a default erase value when we register cfi flash for mtd devices
he pseudo-code is as follows：
register_cfi_driver(xxx)
find_mtddriver("xxx", &inode);
mtdconfig_register(inode->u.i_mtd);
https://github.com/Zhangshoukui/nuttx/blob/master/drivers/mtd/mtd_config.c#L1775C28-L1775C45
None
local test
=> drivers/mtd/mtd_cfi: Add MTDIOC_ERASESTATE

arch/arm/src/samv7/sam_gpio.c, arch/arm/src/samv7/sam_gpio.h, arch/arm/src/samv7/sam_gpioirq.c
GPIO peripheral clocks have to be enabled even if interrupt support on the peripheral is not enabled, otherwise GPIO input will not work. This is probably caused by input filters that need clock signal.
This commit moves the clock enable call from interrupt specific function to common initialization function that is called from `_start` entry point function.
GPIO inputs now work even if the peripheral is not configured with interrupt support (option `CONFIG_SAMV7_GPIOx_IRQ`).
Tested on custom SAMv7 board with GPIOD peripheral. Reading pins now work even if `CONFIG_SAMV7_GPIOD_IRQ` is disabled.
=> arch/arm/src/samv7: enable GPIO clock even if interrupt not enabled

arch/xtensa/src/esp32s3/Kconfig, arch/xtensa/src/esp32s3/esp32s3_spi.c
The MISO and C/S pins of SPI are optional.
- The MISO pin is optional.
- The C/S pin is unnecessary when `ESP32S3_SPI_UDCS` is enabled.
esp32s3
1. Selftest with `lckfb-szpi-esp32s3:lcd`(not upstreamed yet)
2. CI
=> arch/esp32s3: The MISO and C/S pins are optional

drivers/syslog/CMakeLists.txt, drivers/syslog/Kconfig, libs/libc/syslog/CMakeLists.txt, libs/libc/syslog/Make.defs, libs/libc/syslog/lib_syslog_none.c
Add an option to completely disable syslog() and replace it with an empty functions. This option can be useful for small systems when we don't have any logging support, but compiler is not able to remove useless code.
This way the final image also won't contain the strings that are present in syslog() calls when compiler optimization is enabled (for example from /boards where syslog is often used instead of debug macros). 
new option that must be explicitly selected by the user. No impact on code and configs.
some random upstream configuration compiled without warnings
=> syslog: add an option to completely disable syslog logic

arch/xtensa/src/common/espressif/Kconfig, arch/xtensa/src/common/espressif/Make.defs, boards/xtensa/esp32/esp32-2432S028/src/esp32_bringup.c, boards/xtensa/esp32/esp32-audio-kit/src/esp32_bringup.c, boards/xtensa/esp32/esp32-devkitc/src/esp32_bringup.c, boards/xtensa/esp32/esp32-ethernet-kit/src/esp32_bringup.c, boards/xtensa/esp32/esp32-lyrat/src/esp32_bringup.c, boards/xtensa/esp32/esp32-pico-kit/src/esp32_bringup.c, boards/xtensa/esp32/esp32-sparrow-kit/src/esp32_bringup.c, boards/xtensa/esp32/esp32-wrover-kit/src/esp32_bringup.c, boards/xtensa/esp32/lilygo_tbeam_lora_gps/src/esp32_bringup.c, boards/xtensa/esp32/ttgo_eink5_v2/src/esp32_bringup.c, boards/xtensa/esp32/ttgo_lora_esp32/src/esp32_bringup.c, boards/xtensa/esp32/ttgo_t_display_esp32/src/esp32_bringup.c, boards/xtensa/esp32s2/esp32s2-saola-1/src/esp32s2_bringup.c, boards/xtensa/esp32s3/esp32s3-box/src/esp32s3_bringup.c, boards/xtensa/esp32s3/esp32s3-devkit/src/esp32s3_bringup.c, boards/xtensa/esp32s3/esp32s3-eye/src/esp32s3_bringup.c, boards/xtensa/esp32s3/esp32s3-korvo-2/src/esp32s3_bringup.c, boards/xtensa/esp32s3/esp32s3-lcd-ev/src/esp32s3_bringup.c, boards/xtensa/esp32s3/lckfb-szpi-esp32s3/src/esp32s3_bringup.c
Add the possibility to configure (disable) the wlan device on esp32. By default this is enabled so it does not change the present behavior. This is added to allow disabling in some future configuration (e.g. when only espnow is used as the network device).
*Impact on users: None,
*Impact on build process: None,
*Impact on hardware: None,
*Impact on documentation: None,
*Impact on security: None,
*Impact on compatibility: None,
*The changes were tested on esp32-devkitc:wifi. All wifi operations (wapi, renew, telnet, ping) performed as expected.
=> arch/xtensa/src/common: Make esp32 wlan device configurable

boards/risc-v/esp32c3/common/src/esp_board_spiflash.c, boards/risc-v/esp32c6/common/src/esp_board_spiflash.c, boards/risc-v/esp32h2/common/src/esp_board_spiflash.c, boards/xtensa/esp32/common/src/esp32_board_spiflash.c, boards/xtensa/esp32s2/common/src/esp32s2_board_spiflash.c, boards/xtensa/esp32s3/common/src/esp32s3_board_spiflash.c
This PR enables the SPI Flash's MTD block driver, which enables testing the SPI Flash device without any associated filesystems. ESP32, ESP32-S2, ESP32-S3, ESP32-C3, ESP32-C6, and ESP32-H2 can be tested with MTD's benchmark and testing application introduced by https://github.com/apache/nuttx-apps/pull/3033.
Impact on user: YES. MTD's benchmark and testing application can be used with the MTD-based SPI flash partition.
Impact on hardware: YES. MTD-based SPI flash partition is exposed as a block device at `/dev/mtdblock0`.
Just unset any other filesystems and check for the MTD-based device at `/dev/mtdblock`. For ESP32-S3, for instance:
```
make -j distclean && ./tools/configure.sh …
```
=> espressif: Enable SPI Flash's MTD block driver for all supported SoCs

arch/risc-v/src/mpfs/hardware/mpfs_usb.h, arch/risc-v/src/mpfs/mpfs_coremmc.c, arch/risc-v/src/mpfs/mpfs_dsn.c, arch/risc-v/src/mpfs/mpfs_emmcsd.c, arch/risc-v/src/mpfs/mpfs_ethernet.c, arch/risc-v/src/mpfs/mpfs_sdio_dev.h, arch/risc-v/src/mpfs/mpfs_usb.c
This replaces the big kernel lock (enter/leave_critical_section()) with local spinlocks from all MPFS drivers that still use it. The reason is obviously to alleviate big kernel lock congestion which has a massive performance impact in SMP
Only the MPFS target is impacted.
App impact: No
Doc impact: No
Build system impact: No
Tested with private downstream MPFS target that uses all of the changed drivers.
=> arch/risc-v/mpfs: Remove big kernel lock from several drivers

drivers/lcd/st7789.c
Send RAMCTRL command only when RGB data in little endian.
Fix display error reported by @michallenc in https://github.com/apache/nuttx/pull/16094.
- drivers/lcd/st7789
1. Selftest
```
./tools/configure.sh -l lckfb-szpi-esp32s3:lvgl
make flash -j$(nproc) ESPTOOL_PORT=/dev/ttyUSB0
```
2. CI
=> drivers/lcd/st7789: Send RAMCTRL if little endian

drivers/lcd/Kconfig, drivers/lcd/st7789.c
Support mirror V, mirror X and V can rotate the screen 90 degrees.
- drivers/lcd/st7789
```bash
./tools/configure.sh -l lckfb-szpi-esp32s3:lvgl
make flash -j$(nproc) ESPTOOL_PORT=/dev/ttyUSB0
```
- Config lckfb-szpi-esp32s3:lvgl
- Config lckfb-szpi-esp32s3:lvgl whit changes below
```diff
+CONFIG_LCD_ST7789_MIRRORV=y
+CONFIG_LCD_ST7789_MIRRORX=y
```
=> drivers/lcd/st7789: Support mirror V

arch/xtensa/src/esp32/esp32_ble_adapter.c, arch/xtensa/src/esp32s2/esp32s2_wdt_lowerhalf.c, arch/xtensa/src/esp32s3/esp32s3_ble_adapter.c, arch/xtensa/src/esp32s3/esp32s3_wdt_lowerhalf.c, include/nuttx/clock.h
Patch from mailing list https://lists.apache.org/thread/xzor3tjy9jozlmox82frd27v969b37l4
Author: Kerogit
On AVR architecture, the compiler apparently sometimes truncates NSEC_PER_TICK to 16bit value, leading to clock_time2ticks returning incorrect results. This was encountered while attempting to add tickless OS support for AVR architecture but seemed to affect non-tickless mode of operation as well.
This patch marks NSEC_PER_USEC (and to be safe, USEC_PER_MSEC and MSEC_PER_SEC too) as long.
this change needs a thorough review, to make sure it doesn't accidentally break something
CI
=> nuttx/clock: make NSEC_PER_USEC and others long

arch/arm/src/armv8-r/arm_head.S
In the arm_el_init function, the FPU might be used, for example, the assembly optimization of memcpy uses FPU and NEON instructions and registers.
Therefore, it's important to initialize the
FPU as early as possible to prevent system hangs that could occur if the FPU is used without being initialized.
arch/arm/armv8-r  arch init
cortex-r52
=> arch/armv8-r: Enable fpu before arm_el_init

drivers/input/ft5x06.c
Fix the issue of incorrect comparison of the sampled Y value
RELEASE
CI
=> {bp-16106} fix(bug): fix ft5x06_sample error

arch/xtensa/src/esp32s3/Kconfig, arch/xtensa/src/esp32s3/esp32s3_spi.c
The MISO or MOSI pin is optional.
The C/S pin is unnecessary when `ESP32S3_SPI_UDCS` is enabled.
RELEASE
CI
=> {bp-16085} arch/esp32s3: The MISO, MOSI and C/S are optional

arch/arm/src/samv7/sam_gpio.c, arch/arm/src/samv7/sam_gpio.h, arch/arm/src/samv7/sam_gpioirq.c
GPIO peripheral clocks have to be enabled even if interrupt support on the peripheral is not enabled, otherwise GPIO input will not work. This is probably caused by input filters that need clock signal.
This commit moves the clock enable call from interrupt specific function to common initialization function that is called from _start entry point function.
RELEASE
CI
=> [bp-16079} arch/arm/src/samv7: enable GPIO clock even if interrupt not enabled

drivers/bch/Kconfig, drivers/bch/bchlib_write.c
The PR adds CONFIG_BCH_FORCE_INDIRECT which makes possible to force indirect writes in BCH driver.
The implementation is similar than CONFIG_FAT_FORCE_INDIRECT.
This is needed because in some use cases (e.g. when CONFIG_BUILD_KERNEL) it is not possible to write directly from user buffer.
This PR adds configuration option CONFIG_BCH_FORCE_INDIRECT which is disabled by default.
Enabling CONFIG_BCH_FORCE_INDIRECT forces indirect write in bchlib_write().
Tested with mkfatfs utility on the custom MPFS board, BUILD_KERNEL enabled.
=> drivers/bch: Add CONFIG_BCH_FORCE_INDIRECT

arch/risc-v/src/mpfs/mpfs_entrypoints.c
Otherwise we get an undefined symbol error when LIBC_ARCH_ATOMIC is defined.
RELEASE
CI
=> {bp-16126} mpfs/mpfs_entrypoints.c: Change atomic_load > atomic_read

arch/arm/src/armv8-r/arm_head.S
In the arm_el_init function, the FPU might be used, for example, the assembly optimization of memcpy in arm_tcm_load uses FPU and NEON instructions and registers.
Therefore, it's important to initialize the
FPU as early as possible to prevent system hangs that could occur if the FPU is used without being initialized.
RELEASE
CI
=> [bp-16120} arch/armv8-r: Enable fpu before arm_el_init

boards/xtensa/esp32s3/lckfb-szpi-esp32s3/src/Make.defs, boards/xtensa/esp32s3/lckfb-szpi-esp32s3/src/esp32s3-szpi.h, boards/xtensa/esp32s3/lckfb-szpi-esp32s3/src/esp32s3_bringup.c, boards/xtensa/esp32s3/lckfb-szpi-esp32s3/src/esp32s3_ft5x06.c, drivers/input/ft5x06.c
Add FT5X06 support for szpi-esp32s3.
1. drivers/ft5x06: Remove unused wakeup and nreset check of FT5X06.
2. boards/szpi-esp32s3: Add support for FT5X06 touchscreen driver.
For hardware details, please ref to https://wiki.lckfb.com/zh-hans/szpi-esp32s3/open-source-hardware/.
New configuration("lckfb-szpi-esp32s3:ft5x06" maybe) and doc will be added in the near future if needed.
1. drivers/ft5x06
2. boards/szpi-esp32s3
1. The config "lckfb-szpi-esp32s3:lvgl" with FT5X06 enabled
```bash
./tools/configure.sh -l lckfb-szpi-esp32s3:lvgl
make flash -j$(nproc) ESPTOOL_PORT=/dev/ttyUSB0
```
```diff
+CONFIG_FT5X06_POLLMODE=y
+CONFIG_FT5X06_SINGLEPOINT=y
+CONFIG_FT5X06_SWAPXY=y
+CONFIG_INPUT=y
+CONFIG_INPUT_FT5X06=y
```
2. CI
=> Add FT5X06 support for szpi-esp32s3

arch/Kconfig, libs/libc/machine/arm/CMakeLists.txt, libs/libc/machine/arm/Kconfig, libs/libc/machine/arm/Make.defs, libs/libc/machine/arm/arch_crc32.c, libs/libc/misc/lib_crc32.c
Optimize crc32 standard(poly:0x04C11DB7) and crc32 castagnoli(poly:0x1EDC6F41) with arm crc32 extension instructions.
For example, crc32 standard caculates(lookup crc32 table) 1812 bytes data, reduced the time from 118 us to 14 us through optimization.
Performance improved ~700%
No.
The new feature is disabled by default,  open it when your arm chip has crc32 extension
build:  fvp-armv8r-aarch32:nsh
tested on a cortex-r52 cpu
=> libc/arm: optimize crc32/crc32c for arm

arch/arm/src/stm32f0l0g0/stm32_adc.c
Fix and enable ADC calibration. The ADC voltage regulator must be enabled and regulator start-up time must be respected.
fix adc calibration.
tested on nucleo-c071rb and b-l072z-lrwan1 with examples/adc
=> arch/stm32f0l0g0/stm32_adc.c: fix ADC calibration

arch/arm/src/stm32f0l0g0/stm32_adc.c
Fix and enable ADC calibration. The ADC voltage regulator must be enabled and regulator start-up time must be respected.
tested on nucleo-c071rb and b-l072z-lrwan1
RELEASE
CI
=> {bp-16137} arch/stm32f0l0g0/stm32_adc.c: fix ADC calibration

Documentation/platforms/arm/stm32f4/boards/stm32f401rc-rs485/index.rst, boards/arm/stm32/common/src/stm32_bmp180.c, boards/arm/stm32/stm32f401rc-rs485/src/stm32_bringup.c
This commit adds support for the BMP180 sensor on the STM32F401RC-RS485 board and updates the board documentation accordingly. It also enables the BMP180 UORB driver in the STM32 common logic.
* Is new feature added? Is existing feature changed? Yes, Added BMP180 support to STM32F401RC-RS485 and
BMP180 UORB driver in the STM32 common logic. 
* Impact on user (will user need to adapt to change)? Yes, users will be able to user BMP180 on STM32F401RC-RS485
*  and BMP180 UORB on other STM32 boards.
* Impact on build (will build process change)? No
* Impact on hardware (will arch(s) / board(s) / driver(s) change)? Yes, STM32F401RC-RS485  and STM32 Common.
* Impact on documentation (is update required / provided)? Yes, STM32F401RC-RS485 was updated.
* Impact on security (any sort of …
=> boards/arm/stm32f401rc-rs485: Add support to BMP180 Sensor

include/nuttx/crc16.h, libs/libc/misc/Make.defs, libs/libc/misc/lib_crc16ibm.c
libs/libc/crc16: add support of CRC-16/ANSI(aka CRC-16/IBM)
Compatible CRC16 with Linux Kernel:
https://github.com/torvalds/linux/blob/master/lib/crc16.c
- CRC-16/CCITT, CRC-16/CCITT-TRUE, CRC-16/KERMIT
```
poly: 0x8005 (0xA001) initial seed: 0x0000, xor output: 0x0000
: width=16
: poly=0x8005
: init=0x0000
: refin=true
: refout=true
: xorout=0x0000
: check=0xbb3d
: residue=0x0000
: name="CRC-16/ARC"
```
https://reveng.sourceforge.io/crc-catalogue/16.htm#crc.cat.crc-16-arc
N/A
test crc check with linux kernel
=> libs/libc/crc16: add support of CRC-16/ANSI(aka CRC-16/IBM)

arch/arm/src/stm32l4/CMakeLists.txt, boards/arm/stm32l4/nucleo-l476rg/CMakeLists.txt, boards/arm/stm32l4/nucleo-l476rg/src/CMakeLists.txt
This pull request adds CMakeLists.txt files required to build for the `stm32l4` arch, specifically the `stm32l476rg` board.
There should be no adverse effects from this. Build details and flags were adapted from the existing Makefiles, using the `stm32f7` platform as a reference. 
* OS: Arch Linux
* CPU: amd64
* Toolchain: `arm-none-eabi-*`
* Arch: STM32L4
* Board: `nucleo-l476rg`
* Config: `nsh`
This target did not exist for CMake builds. I can provide Make results on request.
```sh
[pryre@ren] pms-r01> mkdir build
[pryre@ren] pms-r01> set -x NUTTX_DIR platform/nuttx
```
```sh
[pryre@ren] nuttx> 
./tools/configure.sh -l nucleo-l476rg:nsh
Copy files
Select CONFIG_HOST_LINUX=y
Refreshing...
CP: arch/dummy/Kconfig to /---/pms-r01/platform/nuttx/arch/dummy/dummy_kconfig
CP: …
```
=> arch/arm/stm32l4: Add CMakeLists for the STM32L4

boards/xtensa/esp32s3/lckfb-szpi-esp32s3/src/esp32s3-szpi.h, boards/xtensa/esp32s3/lckfb-szpi-esp32s3/src/esp32s3_board_lcd.c, boards/xtensa/esp32s3/lckfb-szpi-esp32s3/src/esp32s3_board_spi.c, boards/xtensa/esp32s3/lckfb-szpi-esp32s3/src/esp32s3_ft5x06.c, boards/xtensa/esp32s3/lckfb-szpi-esp32s3/src/esp32s3_pca9557.c
Set LCD default backlight brightness of szpi-esp32s3 to about 10%.
Users can set brightness at runtime throug "pwm" command or customed application by controlling "/dev/pwm0".
- boards/szpi-esp32s3
Test OK on both "lcd" and "lvgl" configuration.
```bash
./tools/configure.sh -l lckfb-szpi-esp32s3:lcd
make flash -j$(nproc) ESPTOOL_PORT=/dev/ttyUSB0
./tools/configure.sh -l lckfb-szpi-esp32s3:lvgl
make flash -j$(nproc) ESPTOOL_PORT=/dev/ttyUSB0
```
=> boards/szpi-esp32s3: Set LCD default backlight brightness

sched/pthread/pthread_mutexinit.c, sched/signal/sig_default.c, sched/task/task_exithook.c
This PR has two commits for sched:
- Set the mutex flag for pthread semaphores also when the PRIORITY_INHERITANCE flag is enabled. This has no functional impact for now, but it should still be set for the future if the semaphore is mutex to allow later optimizations
- Instead of accessing "semcount" directly from outside sched/semaphore, use the existing nxsem_get_value interface.
No functional impact
Tested on QEMU rv_virt:nsh64, rv_virt:nsh, i.MX93 (arm64) and MPFS (riscv 64-bit).
=> Sched small sem cleanups

libs/libc/semaphore/sem_getvalue.c
This is a small cleanup for libc nxsem_get_value, to use the provided macro to fetch the semaphore value instead of accessing semaphore internals directly outside of sched/semaphore.
No functional impact
This has obviously no functional impact, however, it has been tested together with all the changes in PR #16148 (in qemu and in real hardware).
=> libc/semaphore: Read semaphore value by using NXSEM_COUNT macro

arch/xtensa/src/esp32s2/esp32s2_lowputc.c, arch/xtensa/src/esp32s2/esp32s2_serial.c
The uart1 is found be in reset state, and the sysclk is not enabled for it.
When enable `CONFIG_ESP32S2_UART1` and connect an external usb-uart converter to UART1(TXPIN=17,RXPIN=18), it's found that the host can't communicate with the esp32s2 board.
esp32s2, uart1
enable `CONFIG_ESP32S2_UART1`, connect an external usb-uart converter to UART1(TXPIN=17,RXPIN=18) to test.
1. board send
run this command on the board, and observe data on host machine (in another minicom)
```
nsh> echo abc >/dev/ttyS1
```
2. board receive
run this command on the board, and press some keys on host machine (in another minicom) to send
```
nsh> cat /dev/ttyS1 &
```
=> xtensa/esp32s2: enable sysclk and deassert reset signal for uart1

include/nuttx/sched.h, include/nuttx/tls.h, include/sys/syscall_lookup.h, libs/libc/sched/CMakeLists.txt, libs/libc/sched/Make.defs, libs/libc/sched/task_gettid.c, sched/pthread/pthread_create.c, sched/task/task_init.c, sched/tls/tls_initinfo.c, syscall/syscall.csv
There is no need for a gettid() syscall, as the thread ID is stable through the life of the process. It is safe to put a copy of TID to TLS. This way a user processes can access TID quickly via its own stack, instead of having to use an expensive syscall.
Impact is to gettid() system call, this patch removes the call gate to kernel and moves the data into TLS for quick userspace access.
rv-virt:knsh64 + ostest
=> sched/gettid: Move thread ID to TLS

boards/arm/stm32f0l0g0/nucleo-c071rb/scripts/flash.ld, boards/arm/stm32f0l0g0/nucleo-f072rb/scripts/flash.ld, boards/arm/stm32f0l0g0/nucleo-f091rc/scripts/flash.ld, boards/arm/stm32f0l0g0/stm32f051-discovery/scripts/flash.ld, boards/arm/stm32f0l0g0/stm32f072-discovery/scripts/flash.ld
Unify liker scripts for all stm32f0l0g0.
This fixes crash due to unaligned access to rodata for these boards.
fix crash when initializing rodata and unify linker scripts
custom application with nucleo-c071rb
=> boards/stm32f0l0g0: unify liker scripts

fs/procfs/fs_procfs.c
Some entries have the opendir function set to NULL, for example g_mount_operations.
A null pointer dereference can be triggered by an opendir("/proc/fs/blocks") for example.
I tested this with the PX4 fork (https://github.com/PX4/NuttX), 10.3.0, on an STM32F7 board.
=> fs/procfs: fix potential null pointer access in procfs_opendir

tools/host_info_dump.py
fix
```
Traceback (most recent call last):
File "/home/ubuntu20042/nuttxspace/nuttx/tools/host_info_dump.py", line 575, in <module>
header = generate_header(args)
File "/home/ubuntu20042/nuttxspace/nuttx/tools/host_info_dump.py", line 466, in generate_header
sys.path.append(os.path.abspath(vendor_specific_module_path))
UnboundLocalError: local variable 'vendor_specific_module_path' referenced before assignment make: *** [tools/Unix.mk:644: host_info] Error 1
```
Impact on user: This PR fix make host_info.
Impact on build:  NO
local Ubuntu Linux
tools/configure.sh -l sim:nsh
**make host_info**
**Without this PR**
```
ubuntu20042@Unuttx:~/nuttxspace/nuttx$ make host_info
file sysinfo.h not …
```
=> tools/host_info_dump.py: fix UnboundLocalError: local variable 'vendor_specific_module_path' referenced before assignment

drivers/rpmsg/rpmsg_port_spi.c, drivers/rpmsg/rpmsg_port_spi_slave.c, drivers/rpmsg/rpmsg_port_uart.c
drivers/rpmsg: correct crc16 catalogue to CRC-16/IBM
This is the pair implementation relative to the Linux kernel
N/A
rpmsg spi/uart test with linux
=> drivers/rpmsg: correct crc16 catalogue to CRC-16/IBM

include/nuttx/compiler.h
nuttx/compiler: add support of deprecated attribute
Warning about usage of deprecated features.
since `__deprecated__` is a compiler built-in macro, so we define the deprecated with `__deprecated`
Break log:
```
| /usr/include/x86_64-linux-gnu/sys/cdefs.h:355:65: error: missing ')' after "__has_attribute"
|   355 | #if __GNUC_PREREQ (3,2) || __glibc_has_attribute (__deprecated__)
|       |                                                                 ^
| /usr/include/x86_64-linux-gnu/sys/cdefs.h:355:51: error: missing binary operator before token "("
|   355 | #if __GNUC_PREREQ (3,2) || __glibc_has_attribute (__deprecated__)
|       |                                                   ^~~~~~~~~~~~~~
```
N/A
ci-check
=> nuttx/compiler: add support of deprecated attribute

include/nuttx/crc16.h, libs/libc/misc/CMakeLists.txt, libs/libc/misc/Make.defs, libs/libc/misc/lib_crc16.c, libs/libc/misc/lib_crc16xmodem.c
libs/libc/crc16: Separate implementation of crc16xmodem from crc16
keep default crc16 catalogue for CRC-16/XMODEM
Mapping crc16 implement to crc16xmodem
crc16     -> crc16xmodem
crc16part -> crc16xmodempart
- CRC-16/ACORN, CRC-16/LTE, CRC-16/V-41-MSB, XMODEM, ZMODEM
poly: 0x1021 initial seed: 0x0000, xor output: 0x0000
: width=16
: poly=0x1021
: init=0x0000
: refin=false
: refout=false
: xorout=0x0000
: check=0x31c3
: residue=0x0000
: name="CRC-16/XMODEM"
https://reveng.sourceforge.io/crc-catalogue/16.htm#crc.cat.crc-16-xmodem
N/A
crc16 test via rpmsg uart
=> libs/libc/crc16: Separate implementation of crc16xmodem from crc16

arch/sim/src/sim/posix/sim_i2c.h
arch/sim: Add i2c setup and shutdown interface
https://github.com/apache/nuttx/pull/12848/commits/12b4340b009d55f30508b1ebb1da1c4faec674a7
This interface is required if you want to open an i2c node directly on the sim
sim_i2c
CI
=> arch/sim: Add i2c setup and shutdown interface

arch/risc-v/src/common/riscv_exception.c
If a process causes a fatal error when it's running a system call, the whole system should crash as the crash originated from the kernel.
Do this by running the PANIC() branch, if task is in syscall.
Don't perform user segfault if the user process crashes during syscall (which is kernel code..).
MPFS target with CONFIG_BUILD_KERNEL=y and >100 processes / threads running.
=> arch/risc-v: PANIC() on system call crash

drivers/wireless/bluetooth/bt_uart.c, wireless/bluetooth/bt_hcicore.c
Bluetooth HCI and UART driver fixes.
Wireless / Bluetooth: HCI and UART.
Build verified by @cederom on ESP32-DevkitC and Nucleo-WB55RG. Runtime verification by external party.
```
% uname -a
FreeBSD XXX 14.2-RELEASE-p1 FreeBSD 14.2-RELEASE-p1 GENERIC amd64
% git log -5 --oneline
2209ce8002 (HEAD -> 20250325-cederom-wireless_bluetooth_fixes, cederom/20250325-cederom-wireless_bluetooth_fixes)  wireless/bt_hcicore: Fix H4 header and data buffer length verification.
0d141f6285 wireless/bt_hcicore: Fix buffer type confusion on missing response.
c63a85239b wireless/bt_uart: Fix ACL data buffer length verification.
1b9e6a8563 (origin/master, origin/HEAD, master) boards/nucleo-c092rc: add minimal NSH configuration
e474569472 boards/nucleo-c071rb: add minimal NSH configuration
```
```
% …
```
=> wireless/bluetooth: bt_hcicore and bt_uart related fixes.

arch/arm/src/stm32h5/hardware/stm32_dts.h, arch/arm/src/stm32h5/stm32_dts.h
Add hardware register definitions for the digital temperature sensor (DTS) peripheral on the STM32H5.
The DTS register definitions added will be used for future driver development, and can be used in custom board implementations if needed. 
No functional impact. Used as building block for the future. 
Will not change build process, compatibility, security, etc. 
As this is just a register definition file, no testing was done. nxstyle check was performed and it passed.
=> arch/arm/stm32h5: DTS Hardware Files

libs/libc/semaphore/sem_trywait.c, libs/libc/semaphore/sem_wait.c
The DEBUGASSERTS in nxsem_wait and nxsem_trywait are non-functional, they don't check anything. These were broken in previous commits.
No functional impact, unless someone adds bugs and has CONFIG_DEBUG_ASSERTIONS enabled.
Tested that the code doesn't assert with CONFIG_DEBUG_ASSERTIONS enabled in rv_virt:nsh64 , mpfs and imx9 targets
=> libs/libc/semaphore: Fix DEBUGASSERTS

arch/risc-v/src/mpfs/hardware/mpfs_usb.h
This fixes a crash in the boot in non-smp mpfs configurations.
The alignment of the ctrlreq was correct by luck, and was broken when the spinlock was added to the structure.
In non-smp configurations the spinlock_t is 8 bits, which changed the alignment of the ctrlreq.
Impacts only MPFS targets where CONFIG_SMP is not set. Fixes a system crash in usb driver for those targets.
Tested on a custom HW and on Microchip MPFS Icicle kit (icicle:hwtest target).
=> arch/mpfs/usb: Align usb_ctrlreq_s properly to 32-bit boundary

arch/risc-v/src/common/riscv_exception.c
If a process causes a fatal error when it's running a system call, the whole system should crash as the crash originated from the kernel.
Do this by running the PANIC() branch, if task is in syscall.
RELEASE
CI
=> {bp-16173} arch/risc-v: PANIC() on system call crash

fs/procfs/fs_procfs.c
Some entries have the opendir function set to NULL, for example g_mount_operations.
A null pointer dereference can be triggered by an
opendir("/proc/fs/blocks") for example.
RELEASE
CI
=> {bp-16164} fs/procfs: fix potential null pointer access in procfs_opendir

arch/arm/src/stm32h5/Kconfig, arch/arm/src/stm32h5/Make.defs, arch/arm/src/stm32h5/hardware/stm32h5xxx_flash.h, arch/arm/src/stm32h5/hardware/stm32h5xxx_memorymap.h, arch/arm/src/stm32h5/stm32_flash.c, arch/arm/src/stm32h5/stm32h563xx_flash.c
H5 implementation of functions defined in `include/nuttx/progmem.h`. The driver supports a subset of the flash peripheral functions.
- Assumes non-secure memory accesses. Does not check for memory protection mechanisms.
References implementation in `arch/arm/src/stm32h7/stm32h743xx_flash.c`, with slight difference in how bank1/2 is handled because banks share registers on the H5 but are separate in the H7.
This adds a few new options to the H5 Kconfig, which will include the new flash file when progmem is enabled.
OS: Docker container of Ubuntu 24.04 running on Ubuntu 24.04 host.
CPU: STM32H563ZIT6U
Compiler: Arm GNU Toolchain 13.3.Rel1 (Build arm-13.24)
Target: Nucleo-H563ZI
Testing was done using a custom application, called from NSH, to write and erase flash blocks. Breakpoints were …
=> arch/arm/stm32h5: implement flash driver for progmem

boards/Kconfig, drivers/serial/Kconfig
We should add these depends to avoid compilation or functional errors
boards/boardctl.c：
```
#ifdef CONFIG_BOARDCTL_APP_SYMTAB
/* CMD:           BOARDIOC_APP_SYMTAB
* DESCRIPTION:   Select the application symbol table.  This symbol
*                table provides the symbol definitions exported to
*                application code from application space.
* ARG:           A pointer to an instance of struct boardioc_symtab_s
* CONFIGURATION: CONFIG_BOARDCTL_APP_SYMTAB
* DEPENDENCIES:  None
*/
case BOARDIOC_APP_SYMTAB:
{
FAR const struct boardioc_symtab_s *symdesc =
(FAR const struct boardioc_symtab_s *)arg;
DEBUGASSERT(symdesc != NULL);
exec_setsymtab(symdesc->symtab, symdesc->nsymbols);
}
break;
#endif
```
drivers/serial/serial.c：
```
#ifdef CONFIG_TTY_LAUNCH_ENTRY …
```
=> boards/Kconfig &&  drivers/serial/Kconfig Add depends on

boards/arm/tiva/tm4c123g-launchpad/CMakeLists.txt, boards/arm/tiva/tm4c123g-launchpad/src/CMakeLists.txt
This commit introduces CMake build support for the TI TM4C123G LaunchPad development board within the NuttX RTOS. It achieves this by adding a CMakeLists.txt file to the boards/arm/tiva/tm4c123g-launchpad & boards/arm/tiva/tm4c123g-launchpad directory. This new file does not introduce CMake support from scratch but rather integrates the existing CMake configurations already present in the arch folders. The primary purpose is to enable building NuttX for this specific board using the CMake build system.
This change primarily affects the build process for the tm4c123g-launchpad board. Developers who prefer or need to use CMake for their NuttX builds will now have this option for this specific target. It does not remove the existing build system but provides an alternative. This change …
=> boards/arm/tiva/tm4c123g-launchpad: add CMakeLists.txt

arch/arm/src/imx9/imx9_flexcan.c, arch/arm/src/imxrt/imxrt_flexcan.c, arch/arm/src/kinetis/kinetis_flexcan.c, arch/arm/src/s32k1xx/s32k1xx_flexcan.c, arch/arm/src/s32k3xx/s32k3xx_flexcan.c, arch/arm/src/stm32h7/stm32_fdcan_sock.c, arch/arm64/src/imx9/imx9_flexcan.c, net/netdev/netdev_ioctl.c
In Linux, CAN bitrate is set with netlink, not ioctl, and you need to
set a bitrate before bringing the interface up (make sense). In Nuttx,
you can begin the interface up (it uses a default bitrate) and then
you can change it. My guess is calling ifup at the end is precisely to
avoid requiring another ifdown/ifup cycle from app code.
SocketCAN is a Linux thing, so we should try to mimic the behaviour.
Implementing netlink would be overkill (and moreover, it is common in
Linux to use libsocketcan to abstract the netlink internals anyways)
but at least we should have similar semantics
The change makes changing bitrate on an up interface fails. This is done on the portable, architecture-independent section of ioctl handling, so it affects all the drivers and makes the semantics clear.
Al …
=> net/netdev: Change SIOCSCANBITRATE to require interface down.

arch/arm/src/stm32h5/Kconfig, arch/arm/src/stm32h5/stm32_uart.h
Original code by @ArrestedLightning https://github.com/ArrestedLightning/nuttx/tree/h5_uart_driver_config
This adds USART6 Kconfig options that were missed in the original PR. 
Allows selecting USART6 on the H5 architecture. 
Board: Custom board.
Chip: STM32H563ZI
=> arch/arm/stm32h5: Add USART6 serial driver config.

arch/arm/src/stm32h5/stm32_i2c.c
Add missing break statements to i2c driver to avoid complaints from compiler.
Original Author: @ArrestedLightning 
This fixes a compiler warning, `error: label at end of compound statement`, that occurs due to the missing break statements in default cases in the i2c driver.
Small bug fix. 
Board: Custom board.
Chip: STM32H563ZI
=> arch/arm/stm32h5: Fix i2c compiler warnings.

arch/arm/src/stm32h7/hardware/stm32_ethernet.h
This adds Ethernet support for the STM32H7X7. This was missing.
Makes it work for me, not sure.
Tested downstream in PX4.
=> stm32h7: enable Ethernet for STM32H7X7XX

arch/arm/src/rp23xx/hardware/rp23xx_pwm.h, arch/arm/src/rp23xx/rp23xx_pwm.c
Fix offset alignment and correct the PWM enable register name
Current PWM on rp23xx implementation is broken this pull fixes this.
Working PWM
Tested on pico2 with single channel and multichannel (2) setup via pwm app.
=> arch/arm/rp23xx: Fix PWM registers access

arch/arm/src/rp23xx/rp23xx_irq.c
Fixes the reg addresses that were copied from armv6m rp2040 to the actual armv8m spec
Current IRQ prioritize routine failed to compile and broken.
`CONFIG_ARCH_IRQPRIO=y`
Working IRQ prioritize on rp23xx
=> arch/arm/rp23xx: Fix IRQ prioritize

arch/xtensa/src/Makefile, arch/xtensa/src/common/Make.defs, arch/xtensa/src/common/crt0.c, arch/xtensa/src/lx6/Toolchain.defs, arch/xtensa/src/lx7/Toolchain.defs
add crt0 to initialize environment for xtensa arch
we use crt0 inside of start hook in pr https://github.com/apache/nuttx/pull/16154, so xtensa also need add it.
fix xtensa elf build
build esp32-devkitc:elf
=> arch/xtensa: add crt0 to initialize environment

arch/arm/src/stm32h5/Kconfig
Added menus for usart, I2C, and SPI selection to make the peripheral selection submenu easier to navigate.
Added DMA1 and DMA2 selection options.
This improves usability by grouping peripherals with many instances into their own menus. Just like the timer selection was already implemented.
Old Peripheral Selection:
New Menus:
This change modifies the user interaction with peripheral configuration through `make menuconfig`.
It does not remove any functionality, but adds DMA menu options.
OS: Ubuntu 24.04 container
Host OS: Ubuntu 24.04 on WSL2
Compiler: arm-none-eabi-gcc 13
Arch: STM32H5
Chip: STM32H563ZIT6
Board: Nucleo-H563ZI
Config: `nucleo-h563zi:nsh`
=> arch/arm/stm32h5: organize peripheral Kconfig selection

libs/libc/semaphore/sem_trywait.c, libs/libc/semaphore/sem_wait.c
* Revert "libs/libc/semaphore: Fix DEBUGASSERTS"
This reverts commit 300992203ac0a14602c8cf744ec87d5525fe4dfb to fix a problem with `esp32-devkitc:blewifi`, which fails to boot up if `CONFIG_DEBUG_ASSERTIONS=y`. 
Introduced by https://github.com/apache/nuttx/pull/16176 with the following description:
> The DEBUGASSERTS in nxsem_wait and nxsem_trywait are non-functional, they don't check anything. These were broken in previous commits.
The above statements are not valid. Originally, there was no problem calling [`nxsem_trywait`](https://github.com/apache/incubator-nuttx/blob/73ee052b3f4b5a7e72ebedfe03e8b66ea6002299/sched/semaphore/sem_trywait.c#L135) from the interrupt and the `DEBUGASSERT` simply checked a corner case: if ran from the interrupt context, the current (interrupted) task may …
=> Revert "libs/libc/semaphore: Fix DEBUGASSERTS"

drivers/video/vnc/vnc_updater.c
Replace direct semaphore value access with nxsem_get_value().
This blocks CI for #16194 
No functional impact
Built and executed sim:vncserver test, which uses this.
=> drivers/video/vnc: Replace direct semcount access with nxsem_get_value

arch/arm/src/imx9/imx9_flexcan.c, arch/arm/src/imxrt/imxrt_flexcan.c, arch/arm/src/kinetis/kinetis_flexcan.c, arch/arm/src/s32k1xx/s32k1xx_flexcan.c, arch/arm/src/s32k3xx/s32k3xx_flexcan.c, arch/arm/src/stm32h7/stm32_fdcan_sock.c, arch/arm64/src/imx9/imx9_flexcan.c, include/net/if.h
This makes SocketCAN bitrate units compatible with what Linux uses (bps instead of previous kbps) and allows representing usual Single Wire Can (SAE J2411) usual bitrates of 33333 and 83333 bps.
All calls to bitrate-related ioctl need to be updated. I have updated all affected drivers in this PR, and made a separate PR to update tools (https://github.com/apache/nuttx-apps/pull/3061)
* Is new feature added? NO Is existing feature changed? YES
* Impact on build: NO
* Impact on hardware: NO. The setting programmed on the HW is unaffected, only how this is represented on user space does.
* Impact on documentation: YES, but minimal. The affected IOCTLs are Nuttx-specific, and the data stuctures providing the info (and thus determining the units) were only described on header files, which the …
=> net: use bps units for bitrate in SocketCAN interfaces.

boards/xtensa/esp32/common/src/esp32_board_spiflash.c
* boards/xtensa/esp32: Fix the SPI Flash MTD block device number
This PR fixes the SPI flash MTD block device number if OTA's partitions are present. In this case, the OTA partitions are registered first and the corresponding MTD block device drivers are assigned with the numbers corresponding to those partitions. Then, the additional SPI flash partition should consider that when registering its own corresponding MTD block device driver.
Impact on user: YES. Register the SPI flash partition successfully.
Impact on hardware: YES. Impacts ESP32 SPI flash device driver registration.
Before applying this patch, `esp32-devkitc:mcuboot_slot_confirm` defconfig failed to mount the SPI flash …
=> boards/xtensa/esp32: Fix the SPI Flash MTD block device number

include/nuttx/atomic.h
This fixes useless -Wpointer-sign errors with clang when doing atomic operations on unsigned datatypes.
Possible alternatives to this:
- the pointer type cast could be done in every place where unsigned atomics would be used
- play with "pragma clang diagnostic ignored" with clang in every place where unsigned atomics would be used
No functional impact, fixes compilation on clang when passing pointers to unsigned data types to the atomics. Fixes CI errors on https://github.com/apache/nuttx/pull/16194 
Tested on qemu: rv-virt:nsh and rv-virt:nsh64, compilation also on mps3-an547:gcov / clang
=> include/nuttx/atomic.h: For each ATOMIC func, cast the parameter to (FAR intXX_t *) of correct size

Documentation/platforms/risc-v/esp32c3/index.rst, Documentation/platforms/risc-v/esp32c6/index.rst, Documentation/platforms/risc-v/esp32h2/index.rst, Documentation/platforms/xtensa/esp32/index.rst, Documentation/platforms/xtensa/esp32s2/index.rst, Documentation/platforms/xtensa/esp32s3/index.rst, arch/risc-v/src/common/espressif/Kconfig, arch/xtensa/src/esp32/Kconfig, arch/xtensa/src/esp32s2/Kconfig, arch/xtensa/src/esp32s3/Kconfig, boards/risc-v/esp32c3/common/scripts/esp32c3_flat_memory.ld, boards/risc-v/esp32c3/common/scripts/esp32c3_sections.ld, boards/risc-v/esp32c6/common/scripts/esp32c6_flat_memory.ld, boards/risc-v/esp32c6/common/scripts/esp32c6_sections.ld, boards/risc-v/esp32h2/common/scripts/esp32h2_flat_memory.ld, boards/risc-v/esp32h2/common/scripts/esp32h2_sections.ld, boards/xtensa/esp32/common/scripts/esp32_sections.ld, boards/xtensa/esp32/common/scripts/flat_memory.ld, boards/xtensa/esp32s2/common/scripts/esp32s2_sections.ld, boards/xtensa/esp32s2/common/scripts/flat_memory.ld, boards/xtensa/esp32s3/common/scripts/esp32s3_sections.ld, boards/xtensa/esp32s3/common/scripts/flat_memory.ld
This PR adds new fields to the metadata section used by MCUBoot. The openocd-esp32 project requires these fields to properly map the flash segments and enable using SW breakpoints and flash through openocd-esp32.
MCUboot version was also updated and the corresponding documentation for each SoC too.
Impact on user: YES. Now users can add SW-defined breakpoints (in addition to the already existing HW breakpoints)
Impact on hardware: YES. It enables it for all supported Espressif SoCS.
Impact on documentation: YES. The command used for `openocd-esp32` has changed. Documentation is provided for it.
Please, follow documentation for debugging each SoC. For ESP32-S3, for instance, the instructions are available …
=> boards/[xtensa|risc-v]/esp32[|s2|s3|c3|c6|h2]: Update flash mappings for MCUboot

fs/littlefs/lfs_vfs.c
Little fs Add read-only parameter and fs/littlefs: Code comment correction
Little fs
Test command:
./tools/configure.sh -l sim:tcpblaster
make -j
umount /mnt/lfs
mount -t littlefs -o ro /dev/rammtd /data
=> fs/littlefs: Add read-only parameter

arch/arm/src/tiva/CMakeLists.txt, arch/arm/src/tiva/cc13xx/CMakeLists.txt, arch/arm/src/tiva/common/CMakeLists.txt, arch/arm/src/tiva/lm/CMakeLists.txt, arch/arm/src/tiva/tm4c/CMakeLists.txt, boards/arm/tiva/tm4c1294-launchpad/CMakeLists.txt, boards/arm/tiva/tm4c1294-launchpad/src/CMakeLists.txt
added TI/Stellaris Tiva
CMake added **tm4c1294-launchpad** and **tm4c123g-launchpad board**.
this implementation #16195 is incorrect and broken.
Impact on user: This PR adds **tm4c1294-launchpad and tm4c123g-launchpad board** with CMake build
Impact on build: This PR Implement CMake build of Tiva arch
Locally and on GitHub
Locally
```
D:\nuttx>cmake -B build -DBOARD_CONFIG=tm4c1294-launchpad:nsh -GNinja
--   CMake:  3.31.5
--   Ninja:  1.12.1
--   Board:  tm4c1294-launchpad
--   Config: nsh
--   Appdir: D:/apps
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler …
```
=> Cmake: Implement CMake build of Tiva arch

Documentation/platforms/sim/network_linux.rst
It is not recommend to just copy defconfig to .config instead of running ./tools/configure.sh. The configure script will do more than just copying the defconfig, it will create backup config, it will check if apps/ dir exists, etc.
End users will void mistakes
DOC
=> Documentation: Fix bad practice instructions

drivers/sensors/lis2mdl_uorb.c
This call to syslog was missing the '%' in its format string, and also was using the wrong format string (lu instead of d) to print the `cmd` argument. It is corrected and the compiler warning resolved.
Syslog call will now work correctly and the build output has one less error.
Built locally.
Before, the compiler output included:
```console
sensors/lis2mdl_uorb.c: In function 'lis2mdl_control':
sensors/lis2mdl_uorb.c:1143:13: warning: too many arguments for format [-Wformat-extra-args]
1143 |       snerr("Unknown command for LIS2MDL: lu\n", cmd);
```
Now there is no warning.
=> drivers/sensors/lis2mdl: Fix SYSLOG call.

Documentation/platforms/arm/rp23xx/index.rst
Mark i2c and PWM as Working
i2c and PWM tested on Pico2 board.
=> Documentation: update rp2350 peripheral status

arch/arm/src/rp23xx/rp23xx_start.c, arch/arm/src/rp23xx/rp23xx_testset.c
Due to Errata RP2350-E2 use only safe spinlocks during start and testset
=> arch/arm/rp23xx: Address the spinlock errata RP2350-E2

arch/arm/include/rp23xx/chip.h
The RP2350 datasheet (Table 198) states that IRQ priority levels are represented using 4 bits in their M33 config
Correct irq priority levels defined
=> arch/arm/rp23xx: fix irq priority levels

arch/risc-v/src/esp32c3/hal_esp32c3.mk, arch/risc-v/src/esp32c6/hal_esp32c6.mk, arch/risc-v/src/esp32h2/hal_esp32h2.mk
When the CONFIG_ESPRESSIF_FLASH_MODE_QIO option is turned on, the compilation error：
bootloader_flash_config_esp32c6.c:(.text.bootloader_init_spi_flash+0x32): undefined reference to `bootloader_enable_qio_mode'
The reason is missing flash_qio_mode.c, which has the bootloader_enable_qio_mode function.
esp32c6、esp32c3、esp32h2 which use esp-hal-3rdparty lib.
Tested on esp32c6-devkitc board.
=> risc-v/esp32{c6,c3,h2}: Fix bootloader flash compiler error

boards/risc-v/esp32c3/common/scripts/esp32c3_sections.ld, boards/risc-v/esp32c6/common/scripts/esp32c6_sections.ld, boards/risc-v/esp32h2/common/scripts/esp32h2_sections.ld, boards/xtensa/esp32/common/scripts/esp32_sections.ld, boards/xtensa/esp32s3/common/scripts/esp32s3_sections.ld
* boards/[risc-v|xtensa]/esp32[|c3|c6|h2|s3]: set coexiram sections
This PR sets the coexiram (from libcoexist.a) sections on IRAM.
Before this patch, no other rules matched such sections and the sections could be placed outside markers that denote the end of the text sections, causing unexpected errors.
Impact on user: YES. Avoid unexpected errors when BLE + Wi-Fi are enabled.
Impact on hardware: YES. Affect devices with coexistence (Wi-Fi, Bluetooth, or 802.15.4): ESP32, ESP32-C3, ESP32-C6, ESP32-H2 and ESP32-S3.
Build the `blewifi` defconfig before and after applying the patch, checking where `.coexiram` setions are being placed on `nuttx.map`. Taking `esp32-devkitc:blewifi` as an …
=> boards/[risc-v|xtensa]/esp32[|c3|c6|h2|s3]: set coexiram sections

boards/arm/rp23xx/raspberrypi-pico-2/scripts/memmap_copy_to_ram.ld, boards/arm/rp23xx/raspberrypi-pico-2/scripts/memmap_default.ld, boards/arm/rp23xx/raspberrypi-pico-2/scripts/memmap_no_flash.ld
Compiling with --print-memory-usage always shows 100% RAM
Upstream bug https://github.com/raspberrypi/pico-sdk/issues/1871
```
LD: nuttx
FLASH:      414516 B         4 MB      9.88%
RAM:        512 KB       512 KB    100.00%
SCRATCH_X:           0 B         4 KB      0.00%
SCRATCH_Y:           0 B         4 KB      0.00%
CP: nuttx.asm
Generating: nuttx.uf2
Done.
```
```
LD: nuttx
FLASH:      414516 B         4 MB      9.88%
RAM:       39152 B       512 KB      7.47%
SCRATCH_X:           0 B         4 KB      0.00%
SCRATCH_Y:           0 B         4 KB      0.00%
CP: nuttx.asm
Generating: nuttx.uf2
Done.
```
=> arch/arm/rp23xx: fix linker scripts 100% RAM usage bug

net/tcp/tcp_conn.c
net/tcp/tcp_conn.c: optimize the port conflict detection rules for tcp_listener().
Fixed potential conflict between implicit binding and port conflict detection.
Implicit binding automatically allocates an interface address during connection,but port conflict detection occurs before binding/connecting. This can cause issues when creating multiple TCP connections in succession. If the first connection uses a random port via implicit binding, subsequent connections might reuse the same port under current filtering rules, leading to connect() failures.
New Feature/Change: Issue fix (no new feature).
User Impact: optimize the port conflict detection rules for tcp_listener().
Security: No
Compatibility: Backward-compatible; no …
=> net/tcp/tcp_conn.c: optimize the port conflict detection rules for tcp_listener()

boards/xtensa/esp32/common/scripts/esp32_sections.ld, boards/xtensa/esp32s2/common/scripts/esp32s2_sections.ld, boards/xtensa/esp32s3/common/scripts/esp32s3_sections.ld
* boards/xtensa/esp32[|s2|s3]: Fix unknown disassembling instructions
This PR adds sections used by the debugger and disassembler to get more information about raw data present in the code.
Impact on user: YES. It fixes the issue https://github.com/apache/nuttx/issues/16235 and enables proper debugging of the generated code.
Impact on hardware: YES. It impacts all Xtensa-based Espressif SoCs (ESP32, ESP32-S2 and ESP32-S3)
Testing it like it was reported at https://github.com/apache/nuttx/issues/16235, comparing the disassembler's result before and after applying this patch. Taking ESP32-S3 as an example:
```
make -j distclean && ./tools/configure.sh esp32s3-devkit:nsh && make -j$(nproc) …
```
=> boards/xtensa/esp32[|s2|s3]: Fix unknown disassembling instructions

drivers/ioexpander/icjx.c, drivers/ioexpander/icjx.h, include/nuttx/ioexpander/icjx.h
This adds `filters` field to `icjx_config_s` structure that is passed as an argument in `icjx_initialize` function. This field allows to configure I/O filters (control world 1 and 3) with three possible filters or disable them at all.
The filter configuration is currently only configurable during the initialization, not at run time (the same as current source).
It is now possible to set up filtering on icjx I/Os. This has no impact on current implementations in BSP layer.
Tested on SAMv7 custom board with icjx expander.
=> drivers/ioexpander/icjx: add option to set filters during initialization

sched/sched/sched_backtrace.c, sched/sched/sched_setpriority.c, sched/sched/sched_suspend.c, sched/signal/sig_dispatch.c, sched/task/task_restart.c, sched/task/task_terminate.c
For some SMP calls it is necessary to lock the current CPU for the process receiving the SMP call. This is done by setting the CPU affinity to the current CPU and preventing the CPU selection algorithm from switching CPUs.
dtcb->flags |= TCB_FLAG_CPU_LOCKED;
CPU_SET(dtcb->cpu, &dtcb->affinity);
However, this logic is currently broken, as CPU_SET is defined as:
#define CPU_SET(c,s) do { *(s) |= (1u << (c)); } while (0)
In order to assign tcb->cpu (the current CPU) to the affinity mask, the mask must be cleared first by calling CPU_ZERO.
This fixes a bug in SMP mode where the kernel attempts to lock CPU for a process, but the CPU can still change. Impact
is a bug fix in the kernel. No user / documentation / API changes and so forth.
Testing and bug hunting was done by @jlaitine by running …
=> sched/affinity: Fix CPU_LOCKED functionality for some SMP calls

arch/risc-v/src/common/riscv_fpu.S
To fix a fpu illegal instruction exception due to fcsr have invalid rounding-mode,  restore fcsr/f0~f31 with a random value from stack because fpu context is not save into stack when mstatus.fs is clean(not dirty).
The number of save/restore fpu context operations is not equal. In fact, CONFIG_ARCH_LAZYFPU is a performance optimization mechanism aimed at minimizing the saving and restoring of FPU registers. In some cases, it may only need to be saved once but must be restored multiple times. Therefore, this optimization mechanism dictates that saving cannot be done on the stack; it must be stored at a fixed location(e.g. task control block buffer), as the stack requires push/pop operations to be matched.
In case of that CONFIG_ARCH_LAZYFPU is off, save/restore FPU registers always into …
=> arch/risc-v: save/restore fpu registers always when CONFIG_ARCH_LAZYFPU is off

arch/xtensa/src/esp32/esp32_partition.c
arch/esp32_partition.c:
- There are six possible sequence arrangements for switching the boot sequence of the three partitions (factory/ota_0/ota_1) through the ota_set_bootseq() and ota_get_bootseq() interfaces. However, it has been discovered that after executing the switch from factory to ota_1, the result read by ota_get_bootseq() is ota_0.
- The current solution is to directly use the target partition's number (num) as next_seq to ensure the correct increment logic of seq. Ensure the formula:(seq-1) % OTA_DATA_NUM + OTA_IMG_BOOT_OTA_0 correctly maps to ota_0 or ota_1
New Feature/Change: Issue fix (no new feature).
User Impact: when exist three OTA partitions (factory/ota_0/ota_1).
Hardware Impact: Only ESP32; other …
=> arch/esp32_partition.c:  fix the incorrect boot sequence when switching from Factory to OTA_1

boards/arm/stm32h7/linum-stm32h753bi/src/stm32_usb.c, boards/arm/stm32h7/nucleo-h743zi/src/stm32_usb.c, boards/arm/stm32h7/openh743i/src/stm32_usb.c, boards/arm/stm32h7/stm32h747i-disco/src/stm32_usb.c, boards/arm/stm32h7/weact-stm32h743/src/stm32_usb.c
Changed usbhost stack sizes to 2048 for affected STM32H7 boards. This was previously causing stack overflows when usb is inserted.
When USB host was enabled on STM32H7 boards, memory corruption happened due a stack overflow in the usbhost thread.
This was because the default stacksize was set to 1024. This is now 2048, which should be big enough.
This was discovered in issue https://github.com/apache/nuttx/issues/16256
It is also discovered that the **usbhost_stacksize** configuration is not added to board specific Kconfig while it should be. I decided to not add these in this commit because I am unable to test them all. It is a safer option to simply change all stacksizes to something safe initially.
Impacts all STM32H7 hardware users (Except the boards were it was already 2048). They …
=> boards/arm/stm32h7: Fix too small usbhost stack size

Documentation/guides/customboards.rst
This PR updates the minor remark in the documentation for the custom board porting process.
documentation
I've tried to port NuttX for custom-based board on STM32H743 and faced that the doc seems to be outdated
=> Corrected configure.sh call in customboards.rst

drivers/serial/uart_pci_16550.c
- serial/uart_pci_16550.c: fix multiport ax99100
ax99100 export each serial port as a separate PCI device function so we have to handle this properly.
fix using multiple ports at once for ax99100 serial PCI cards
tested in a setup where one port is used as a console, the other as gdbstub interface
=> serial/uart_pci_16550.c: fix multiport ax99100

Documentation/components/drivers/character/analog/dac/index.rst, Documentation/components/drivers/character/analog/dac/mcp47x6/index.rst, drivers/analog/CMakeLists.txt, drivers/analog/Kconfig, drivers/analog/Make.defs, drivers/analog/mcp47x6.c, include/nuttx/analog/dac.h, include/nuttx/analog/ioctl.h, include/nuttx/analog/mcp47x6.h
The MCP47X6 series consists of the following single channel DAC chips:
- MCP4706 (8 bit)
- MCP4716 (10 bit)
- MCP4726 (12 bit)
The driver supports the following configurations:
- gain
- power down
- voltage reference
Persistent configuration storage in the internal EEPROM is not implemented.
Support for a new DAC device is added.
The device differs from similar devices:
* MCP48xx: SPI instead of I2C
* DAC7571: lacks features for voltage reference selection and gain
The new driver is loosely based on the MCP48xx driver.
Tested on a custom rp2040 board:
* Reference voltage selection.
* Set DAC value.
=> drivers/analog/mcp47x6: Add support for MCP47X6 DAC series

arch/x86_64/Kconfig, arch/x86_64/src/common/CMakeLists.txt, arch/x86_64/src/common/Make.defs, arch/x86_64/src/common/x86_64_hwdebug.c, arch/x86_64/src/common/x86_64_hwdebug.h, arch/x86_64/src/common/x86_64_initialize.c, arch/x86_64/src/intel64/intel64_cpustart.c
- arch/x86_64: add debug interface
add hardware debug interface for x86_64 which can be used with gdbstub
interface required to support gdbstub over serial port for x86
tested with gdbstub over serial port on x86 hardware
=> arch/x86_64: add debug interface

arch/x86_64/include/intel64/irq.h, arch/x86_64/src/intel64/intel64_checkstack.c, arch/x86_64/src/intel64/intel64_cpustart.c, arch/x86_64/src/intel64/intel64_fullcontextrestore.S, arch/x86_64/src/intel64/intel64_initialstate.c, arch/x86_64/src/intel64/intel64_start.c, arch/x86_64/src/intel64/intel64_vectors.S
Add support for stack canaries for x86.
This includes mostly fixes for TLS support that are required for stack canaries in x86. The FSBASE register must be unique per thread so we have to keep it in thread registers area.
stack canaries works on x86
tested with `qemu-intel64/jumbo` and `CONFIG_STACK_CANARIES=y`. Without these changes the system crashes
=> x86_64: support for stack canaries

Documentation/platforms/risc-v/k230/boards/canmv230/index.rst
fix typo
remove a `)` that should not be here
the documentation only
The origin command causes an error `bash: syntax error near unexpected token ')'`, and this PR fixed this problem
=> risc-v/k230: update documents

tools/process_config.sh
This commit fixed empty line handling in the config file for being able to used KConfig-based defconfigs with the empty lines in them
While trying to port NuttX to the custom board I've faced with the issue which resulted into the deeper debugging of the buildsystem internals in the NuttX. Essentially, the issue was that for some reason I was not able to configure the build for the board from scratch. At the same time, it was possible to used existing defconfigs for WeAct STM32H743 board. So that, I've decided to figure out what's the difference between the configurations, since initially everything was copied more or less identical to the board in the repo.
I managed to trace …
=> Fixed empty line handling process_config.sh

fs/procfs/fs_procfs.c
This patch fixes https://github.com/apache/nuttx/issues/16237, where cd'ing to a non-directory prefix of a procfs entry would succeed.
I've read the contributing guidelines, and I think I'm short a mandatory build log; the problem is that there other (minor) issues that prevent building nuttx for my board out of the box. Advice welcome here!
I did run `checkpatch.sh`.
As described in #16237 , the current procfs implementation allows nonsensical chdir operations to succeed. For example, if `/proc/thermal` exists but `/proc/t` doesn't, `cd /proc/t` will succeed and indicate that there is a `ermal` subdirectory.
This is confusing and may potentially cause other bugs.
This minimal fix simply adds two extra conditions in places where we think we recognized a directory prefix, ensuring that …
=> fs/procfs: Improve subdirectory recognition

arch/arm/src/rp23xx/rp23xx_i2c.c
Fix a bug that I2C driver can not transfer after TX abort error. It caused by remaining NO_STOP flag status.
same as done in commit 0df0a10 for cxd56xx
Working i2c transfer after TX abort error.
Tested with custom i2c slave device causing this issues. (15-minutes i2c poll test)
=> arch/arm/rp23xx: fix not restart after TX error

libs/libc/misc/lib_backtrace.c
Fix the compilation error of `lib_backtrace.c` when setting `CONFIG_LIBC_BACKTRACE_BUFFSIZE`.
Hello, I was trying to configure `CONFIG_LIBC_BACKTRACE_BUFFSIZE` when using `backtrace`, but a compilation error warning was triggered. After checking the source code, I found that in `lib_backtrace.c`, the lock is acquired using `flags = spin_lock_irqsave(&bp->lock);`, but when releasing the lock, `spin_unlock_irqrestore(&pool->lock, flags);` is used. I couldn't find any local or global variables related to `pool`. After changing `pool` to `bp`, the compilation error warning disappeared and the compilation was successful.
When `CONFIG_LIBC_BACKTRACE_BUFFSIZE` is set, there is no compilation error warning, and the compilation can be successfully completed. This may impact to all architectures.
I …
=> libc/backtrace: Fix compilation error when set LIBC_BACKTRACE_BUFFSIZE

arch/arm/include/kinetis/chip.h, arch/arm/src/stm32h7/stm32_rptun.c, libs/libc/locale/lib_langinfo.c, tools/simwifi/udhcpc.script
The introduction of [codespell](https://github.com/codespell-project/codespell/) led me to a few minor issues hidden in the nuttx code base.
This changeset fixes these fairly obvious issues.
* one compile error message now works as intended
* a define for the the kinetis platform is valid now
* one udhcpc log message contains the previously missing network interface name
* the spelling of "February" (as returned by `nl_langinfo`) is correct now
All of the above issues were well hidden edge cases. They are probably quite hard to trigger.
Since all of them are easy to spot and extremly trivial, I did not test anything here.
=> Fix problematic spelling issues

.codespell-ignore-lines, .codespellrc, .github/workflows/check.yml, .pre-commit-config.yaml
These commits add a `.codespellrc` configuration file with suitable defaults and comments for all relevant use-cases in nuttx.
Additionally the github workflow "check" is extended to run the codespell check on changed files.
The log message of the check refers to the `.codespellrc` file in order to help people skip valid false positives.
At the moment, 1990 out of 25838 files in the `nuttx` repository are reported by codespell as containing errors. I already prepared two pull requests, which will reduce the number of reported files to 630. In case I can keep the mood up, I may grind this number down to zero in the next days.
CI tests will start to fail, if a file contains a spelling problem (as detected by codespell).
In case of a problem the PR submitter will:
1. Notice the failed CI …
=> CI: enable codespell

arch/risc-v/src/common/espressif/Kconfig, arch/risc-v/src/common/espressif/esp_config.h, arch/risc-v/src/common/espressif/esp_lowputc.c, arch/risc-v/src/common/espressif/esp_lowputc.h, arch/risc-v/src/common/espressif/esp_serial.c
Add missing RS485 support for Risc-V based Espressif devices 
* arch/risc-v/espressif: Fix Serial IFLOW build issue
Serial IFLOW build error fixed for risc-v based Espressif devices
* arch/risc-v/espressif: Add RS485 support for esp32[c3|c6|h2]
Add RS485 support for Risc-V based Espressif devices
Impact on user: No, missing feature added
Impact on build: Current builds works fine, new option added for new feature
Impact on hardware: Serial peripheral got affected, new feature added
Impact on compatibility: No, it is compatible between older defconfigs
This command used to build:
```
./tools/configure.sh esp32c6-devkitc:nsh && kconfig-tweak -e CONFIG_ESPRESSIF_UART1 && kconfig-tweak -e CONFIG_ESPRESSIF_UART1_RS485 && kconfig-tweak -e …
```
=> arch/risc-v: Add RS485 support for esp32[-c3|-c6|h2]

tools/process_config.sh
tools/process_config: remove unused unnecessary printing
Too much unnecessary printing that meaningless to non-builder developers
Restore the configure print as before
```
nuttx$ ./tools/configure.sh  sim/nsh
Copy files
Appended # to /home/archer/code/nuttx/n1/nuttx/tools/../.config
Appended # This file is autogenerated: PLEASE DO NOT EDIT IT. to /home/archer/code/nuttx/n1/nuttx/tools/../.config
Appended # to /home/archer/code/nuttx/n1/nuttx/tools/../.config
Appended # You can use "make menuconfig" to make any modifications to the installed .config file. to /home/archer/code/nuttx/n1/nuttx/tools/../.config
Appended # You can then do "make savedefconfig" to generate a new defconfig file that includes your to …
```
=> tools/process_config: remove unused unnecessary printing

boards/xtensa/esp32s3/common/scripts/esp32s3_sections.ld
Modify rtc_data_seg to rtc_slow_seg to fix RTC problems. The proper location for those is in RTC slow memory.
This PR essentially fix the issue of using MCUBoot + RTC defconfig on the ESP32S3.
Impact on user: Allows use of MCUBoot + RTC defconfig.
Impact on hardware: No.
Impact on compatibility: No.
Use this defconfig which has MCUBoot and RTC enabled:
```
CONFIG_ARCH="xtensa"
CONFIG_ARCH_BOARD="esp32s3-devkit"
CONFIG_ARCH_BOARD_COMMON=y
CONFIG_ARCH_BOARD_ESP32S3_DEVKIT=y
CONFIG_ARCH_CHIP="esp32s3"
CONFIG_ARCH_CHIP_ESP32S3=y
CONFIG_ARCH_CHIP_ESP32S3WROOM1N4=y
CONFIG_ARCH_INTERRUPTSTACK=2048
CONFIG_ARCH_STACKDUMP=y
CONFIG_ARCH_XTENSA=y
CONFIG_BOARDCTL_RESET=y
CONFIG_BOARD_LOOPSPERMSEC=16717
CONFIG_BUILTIN=y …
```
=> boards/esp32s3: fix rtc segment on linker script

arch/risc-v/src/common/espressif/Bootloader.mk, arch/xtensa/src/esp32/Bootloader.mk, arch/xtensa/src/esp32s2/Bootloader.mk, arch/xtensa/src/esp32s3/Bootloader.mk
* espressif: Add variable to override MCUboot version and URL
The version and the git repository of Espressif's MCUboot port can be changed by setting the `MCUBOOT_VERSION` and `MCUBOOT_URL` environment variables before running the `make bootloader` command.
Impact on user: NO.
Impact on build: YES. If the environment variables `MCUBOOT_VERSION` and `MCUBOOT_URL` are set, use them instead of the default values.
This can be tested by setting it to other values and checking the folder where MCUboot is cloned. For ESP32-S3, for instance, the default values for `MCUBOOT_VERSION` and `MCUBOOT_URL` are defined by, respectively, by `CONFIG_ESP32S3_MCUBOOT_VERSION` (which currently is set to …
=> espressif: Add variable to override MCUboot version and URL

include/nuttx/wdog.h, include/nuttx/wqueue.h, libs/libc/wqueue/work_cancel.c, libs/libc/wqueue/work_queue.c, libs/libc/wqueue/work_usrthread.c, libs/libc/wqueue/wqueue.h, sched/wdog/wd_start.c, sched/wqueue/kwork_cancel.c, sched/wqueue/kwork_queue.c, sched/wqueue/kwork_thread.c, sched/wqueue/wqueue.h
This commit refactors the delayed and the periodic workqueue, and changes the timer to be set in `work_thread`. The improvements of this change are as follows:
- Fix the memory reuse problem of the original periodic workqueue implementation.  https://github.com/apache/nuttx/pull/15937#issuecomment-2808973151
- By removing the `wdog_s` structure in the `work_s` structure, the memory overhead of each `work_s` structure is reduced by about 30 bytes.
- Set the timer for each workqueue instead of each work, which improves system performance.
- Simplified the workqueue cancel processing.
This modification mainly affects modules that use workqueue, and may affect the timing of workqueue execution and workqueue cancel semantics.
`wqueue_test` tested on QEMU/x86_64. Periodical workqueue can work …
=> sched/wqueue: Refactor delayed and periodic workqueue.

arch/arm/src/sama5/sam_systemreset.h
This adds the function `sam_get_reset_cause` to arch/arm/src/sama5 to allow a board to determine the reason for a reset. This is useful in NXboot, for example.
The function, in keeping with other ARM devices, reads the reset status register to determine the cause,
This only applies to ARM:SAMA5
This function has not existed for this arch until now, so there will be no impact to existing software.
No writes to any registers are made so system behaviour will not be affected.
This has been tested on my custom board, using a SAMA5D27C-D1G, in combination with NXboot. Power, manual, and I can confirm that software resets are correctly determined and reported.
It should apply to SAMA5D3 and SAMA5D4 family processors, and work, but I have no boards with these processors. However a check of the …
=> arch/arm/sama5: Add support for reset reason logging

boards/arm/stm32h5/nucleo-h563zi/include/board.h
This adds the ability to use USART2 as a console if wanting to use a console without going through the ST-Link VCOM port. This required when using an external debugger or trace with this board.
The Nucleo H563ZI development board supports using an external debugger or trace over the onboard MIPI20 connector (CN5) when a jumper is applied to JP1. However, this removes RX from onboard ST-Link VCOM port. This change allows configuring USART2 as the serial console to allow full serial console connection when using an external debugger.
Also organized a couple of defines in `board.h` to align with their location in other STM32 board files.
Makes Nucleo H563ZI board support compatible with external debuggers while maintaining serial console.
- Host: Ubuntu 24.04 Docker container on Ubuntu 24.04 …
=> boards/stm32h5/nucleo-h563zi: Add USART2 board defines.

.asf.yaml
* Strict master branch protection requires all PR to be in sync with latest master even if changes are not related and there are no conflicts.
* Because we have lots of daily merges this blocks most of the PRs as they are forced to be rebased on top of current master.
* This also causes unnecessary automatic CI rebuild of each rebase.
* Therefore we are setting strict status checks setting to false.
* required_signatures in github means not only `git commit -s` but also
cryptographic signature which is not required by us, seeting false.
* Disable "contexts" checks enforcement, that cause CI problems, mark TODO.
* This tunes parameters introduced in https://github.com/apache/nuttx/pull/16324.
References:
https://github.com/apache/infrastructure-asfyaml?tab=readme-ov-file …
=> github: master branch protection tune.

arch/arm/Kconfig, arch/arm/src/stm32f0l0g0/Kconfig, arch/arm/src/stm32f0l0g0/Make.defs, arch/arm/src/stm32f0l0g0/hardware/stm32g0_flash.h, arch/arm/src/stm32f0l0g0/stm32_flash.c, arch/arm/src/stm32f0l0g0/stm32_flash.h, arch/arm/src/stm32f0l0g0/stm32g0_flash.c
Add arch files and Kconfig options to interface with the progmem driver on STM32G0 MCUs.
This PR adds the ability to program and erase blocks of flash memory using the progmem interface from application code. To do this, needed to enable selecting chip flash configuration in KConfig. The interface is enabled by selecting the menu option in the system type menu. Selecting it in system type will enable the proper MTD progmem option automatically.
This driver assumes non-secure memory access. Does not check for memory protection mechanisms.
Similar to implementation used for STM32H5.
This change only effects the G0 portion of the `stm32f0l0g0` directory. Other architectures in this directory may share similar flash interfaces, but I did not have the boards to test them so I isolated the G0. …
=> arch/arm/stm32f0l0g0: Add STM32G0 Flash driver.

tools/ci/testlist/sim-01.dat
macOS sim:can compilation is not currently supported.
#16285 is used socketcan package an implementation of the CAN (Controller Area Network) protocols for Linux.
[SocketCAN - Controller Area Network](https://www.kernel.org/doc/html/latest/networking/can.html)
[Linux-CAN / SocketCAN ](https://github.com/linux-can/can-utils)
macOS (sim-01) in NuttX mirror is broken
https://github.com/NuttX/nuttx/actions/runs/14874088222/job/41768036360#step:7:1511
GitHub macOS (sim-01) 
[macOS13 (sim-01)](https://github.com/simbit18/nuttx_test_pr/actions/runs/14881621718/job/41790928553#logs)
=> tools/ci/testlist/sim-01.dat: skip build sim:can for macOS

arch/arm/src/rp23xx/rp23xx_clock.c, arch/arm/src/rp23xx/rp23xx_usbdev.c
RP2350 datasheet and upstream pico-sdk suggests higher VCO freq to
better output stability.
Increase the VCO and update PLL divs according to specs and calculation.
Higher VCO freq is more stable, lower VCO freq is more power friendly.
Also it's possible to use 120/6/5 with VCO 1440MHz for USB PLL to even
higher output stability.
USB setup changes from rp2040
Must clear the MAIN_CTRL.PHY_ISO bit at startup and after power down
events.
More stable USB operations
```
[280432.642035] usb 1-1: new full-speed USB device number 118 using xhci_hcd
[280432.792214] usb 1-1: New USB device found, idVendor=0525, idProduct=a4a7, bcdDevice= 1.01
[280432.792240] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[280432.792243] usb 1-1: Product: CDC/ACM Serial
[280432.792246] usb 1-1: …
```
=> arch/arm/rp23xx: update USB PLL/VCO/FBDIV

arch/arm/src/rp23xx/rp23xx_cpustart.c
On SMP systems we should enable FPU on each core
FPU extenstion support must be enabled on each core as stated on 4.6.5 arm m33 devices generic user guide.
=> arch/arm/rp23xx: add missing fpu init for smp cores

sched/sched/queue.h
`pre` vs `prev` macro param mismatch 
Was only used in `nxsched_process_delivered` and by coincidental match of variable `prev` already  defined in the scope  worked fine.
=> sched/queue: fix typo in dq_insert_mid macro

sched/signal/sig_allocpendingsigaction.c, sched/signal/sig_dispatch.c
The critical section scope was widened before to avoid race conditions between signal dispatch and signal delivery,
which were especially harmful for SMP systems (but exist also for single CPU).
This PR makes the scope a bit smaller by removing thigs which don't need to be inside the critical section, to more
appropriate places.
The nxsig_find_action can be done before entering the protected section, and the found action can be just passed in.
The memory allocations which are done as a backup if one runs out of preallocated pending structures can be done
beforehand, and the dynamically allocated structures simply injected into the free structure lists. This has the downside
that it may leave a dynamically allocated pending structure in the free list for some period of time, in case it is …
=> sched/signal: signal dispatch cleanups

sched/group/group_signal.c, sched/signal/sig_dispatch.c, sched/signal/sig_pending.c, sched/signal/sig_removependingsignal.c, sched/signal/sig_tgkill.c, sched/signal/sig_unmaskpendingsignal.c, sched/signal/signal.h
When using pthread_kill, the signal should be delivered to the specified thread. Current implementation, however, may add the signal to the groups pending list, if the signal is masked at the time of dispatch. From the group's pending list it can be delivered to any thread of the group, which is wrong.
Fix this by adding a new field "FAR struct tcb_s *tcb" to "struct sigpendq", marking if the signal needs to be delivered to a specific thread. Use NULL for the value if delivery to any thread in the group is ok.
This fixes operation of pthread_kill
Tested with ostest in qemu on a real HW (MPFS, risc-v 64-bit, smp 4 cores) and in rv-virt:smp with the patch https://github.com/apache/nuttx-apps/pull/3070. The ostest fails after a few rounds without this patch, and passes with this one.
=> sched/signal: Fix signal delivered to a wrong thread

Documentation/guides/index.rst, Documentation/guides/optee.rst, arch/arm64/include/syscall.h, drivers/misc/CMakeLists.txt, drivers/misc/Kconfig, drivers/misc/Make.defs, drivers/misc/optee.c, drivers/misc/optee.h, drivers/misc/optee_smc.c, drivers/misc/optee_smc.h, drivers/misc/optee_socket.c, include/nuttx/tee.h
So far NuttX has supported OP-TEE interfacing over local and RPMsg sockets. This PR introduces support for direct invocation of OP-TEE through arm SMCs and can be enabled via `CONFIG_DEV_OPTEE_SMC`.
The IOCTL interface remains the same except for the addition of `TEE_IOC_SHM_REGISTER` which enables the registration of dynamically allocated shared memory to the driver (for automatic cleanup) and to OP-TEE (for use in invocations).
The PR introduces also IOCTL argument memory checks to prevent the user from specifying virtual addresses not belonging to the caller user task. The checks are performed on all OP-TEE drivers implemented in NuttX, not just SMC.
For users with no `CONFIG_DEV_OPTEE_*` configuration:
- No impact / no related changes
For users of `CONFIG_DEV_OPTEE_{LOCAL, RPMSG}`:
- …
=> drivers/misc/optee.c: Add an SMC driver for arm

arch/arm/src/rp2040/rp2040_gpio.c
The previous interrupt implementation allowed only one single interrupt mode to be selected. The debug assertion is now updated to allow the entire range of possible interrupt combinations (a 4-bit field), up to 0xf.
The `DEBUGASSERT` will no longer fail for users who are making use of the multiple interrupt mode selection.
This affects all RP2040 boards where code is using more than one interrupt type (no such code exists in the kernel or apps yet, only for users). No other systems affected.
Successful build locally, verified that the assertion no longer fails when `DEBUGASSERT` is enabled on a W5500-EVB Pico.
```console
$ ./tools/configure.sh w5500-evb-pico:usbnsh
$ make menuconfig
$ make -j
/usr/lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/bin/ld: warning: …
```
=> rp2040/gpio: Fix debug assertion for interrupts.

.codespellrc, arch/arm64/include/imx9/imx9_ahab.h, arch/arm64/include/imx9/imx9_romapi.h, arch/arm64/src/Toolchain.defs, arch/arm64/src/cmake/Toolchain.cmake, arch/arm64/src/imx9/Kconfig, arch/arm64/src/imx9/Make.defs, arch/arm64/src/imx9/hardware/imx9_ele.h, arch/arm64/src/imx9/imx9_ahab.c, arch/arm64/src/imx9/imx9_boot.c, arch/arm64/src/imx9/imx9_ele.c, arch/arm64/src/imx9/imx9_ele.h, arch/arm64/src/imx9/imx9_romapi.c, include/imx_container.h
This PR extends the i.MX9 ELE API with commands required for AHAB authentication. A new file, `imx9_ahab.c`, encapsulates the AHAB-specific image authentication logic, building on top of the lower-level ELE API.
In addition, `imx9_romapi.c` introduces support for the i.MX ROM API to enable boot device–agnostic image loading. This allows BL2 to load container headers from the boot device and authenticate them using the new AHAB and ELE infrastructure. **For now the ROM API is required by AHAB boot to load the images from the boot device.**
Finally, this PR adds an option to disable MMU support for i.MX9 builds. Disabling the MMU is appropriate in BL2/SPL stages, where TF-A will reinitialize the MMU in EL3, rendering early setup redundant. Omitting the MMU also reduces memory usage by …
=> arch/arm64/imx9: Support for AHAB authentication + ROMAPI

arch/arm/src/arm/arm_cache.S
Fixed a typo in the comment of arch/arm/src/arm/arm_cache.S and standardized cache terminology from "D-cache"/"I-cache" to "Dcache"/"Icache" for consistency.
No functional changes. Just a comment and style fix for clarity.
No new testing needed. Successfully compiled without issues.
=> style: fix typos in comment.

libs/libc/wqueue/work_queue.c, sched/wqueue/kwork_cancel.c, sched/wqueue/kwork_queue.c, sched/wqueue/wqueue.h
This commit fixed work_cancel_sync at a very rare boundary case. When a worker thread re-enqueues the work data structure during the execution of work, the user thread cannot directly dequeue the work in `work_cancel_sync`. Instead, it should wait until all workers' references to the work data structure have been eliminated after dequeuing.
Besides, this commit improve the performance of the work_queue by reducing unnecessary timer setting.
This modification mainly affects modules that use workqueue, and may affect the timing of workqueue execution and workqueue cancel semantics.
Tested on `esp32s3`, `sim` and `qemu/x86_64`.
Issues mentioned in `https://github.com/apache/nuttx/issues/16337` should be fixed.
=> sched/wqueue: Fix wd_cancel_sync and improve work_queue performance.

include/nuttx/clock.h, include/nuttx/timers/oneshot.h, libs/libc/time/lib_daysbeforemonth.c, sched/Kconfig, sched/clock/clock_systime_ticks.c, sched/group/group_continue.c, sched/sched/sched_timerexpiration.c, sched/semaphore/sem_tickwait.c, sched/signal/sig_timedwait.c, sched/timer/timer_settime.c, sched/wdog/wd_start.c, sched/wqueue/kwork_queue.c
- 1. Simplified the `nxsched_timer_process` function to enhance readability and maintainability.
- 2. Improved absolute timer accuracy by moving the `tick++` operation to the relative watchdog timer, removing unnecessary tick increments for absolute timers.
- 3. Added `CONFIG_TIMER_ADJUST_USEC` to support time compensation for watchdog timers, reducing interrupt latency by setting the timer adjustment value to the Best-Case Execution Time (BCET).
- 1. Improves code maintainability and readability without functional changes.
- 2. Improves the accuracy of absolute timers by optimizing the tick increment process.
- 3. Enhances timer precision by compensating for interrupt latency.
Tested on `QEMU/x86_64` and `sim`.
=> sched/wdog: watchdog timer improvements.

drivers/usbdev/Kconfig
Option `COMPOSITE_VENDORSTR` should be described as composite vendor string, not vendor id. This is consistent with other USB devices.
Also fixes a typo in `USBDEV_EPBUFFER_ALIGNMENT`.
None on existing code and configuration. Just changes description of config.
=> drivers/usbdev/Kconfig: fix COMPOSITE_VENDORSTR description

libs/libc/semaphore/sem_post.c, libs/libc/semaphore/sem_trywait.c, libs/libc/semaphore/sem_wait.c
This PR completes the semaphore "fast path" in libc, by enabling the fast path also for counting semaphores, when they
have the priority inheritance disabled.
This is beneficial for the performance especially in SMP and memory protected builds, in cases where the signalling semaphore is used as a counter. For example a "multiple writer <-> single reader" queue, where a lower priority reader sleeps on a semaphore when the queue is empty, and several high-speed writers post to the queue. As long as the semaphore value remains >= 0, the operations reduce to simple atomic increase/decrease without need for a syscall to kernel, or aquire the big kernel lock in SMP system.
This optimization opportunity was discussed in https://github.com/apache/nuttx/pull/16194#issuecomment-2853322370 .
This …
=> libs/libc/semaphore: Enable semaphore fast wait/post paths for counting semaphores

include/nuttx/can.h
- include/nuttx/can.h: remove dependency on CONFIG_NET_CAN
Definitions from this file are also used by `arch/sim` CAN implementation, which is based on host socketCAN interface.
With this change CONFIG_NET and CONFIG_NET_CAN don't need to be enabled to support CAN character driver on sim.
CAN application on simulator with CAN character driver enabled and socketCAN disabled
=> include/nuttx/can.h: remove dependency on CONFIG_NET_CAN

libs/libc/misc/Kconfig, libs/libc/misc/lib_fdcheck.c
* libc/fdcheck: cause system to panic when a double close occurs
There are many close calls in application without checking return value,
and wrong code causes the same fd to be closed multi times, we should detect
this situation and avoud effecting the fd in other threads.
* libs/fdcheck: add dependency LIBC_OPEN_MAX <= 256
The maximum of file desciptor is 255 for current fdcheck design
fix bug about fdcheck
openvela monkey
=> libc/fdcheck: fix issue about  a double close check

arch/arm/src/rp23xx/rp23xx_wdt.c
The watchdog auto-monitor sets up during the register phase, so we should be prepared before calling register.
Working watchdog auto-monitor
Tested on pico 2 with auto-monitor set to 6sec timeout and panic disabled.
=> arch/arm/rp23xx: wdog: Ensure setup before register phase

sched/wdog/wd_cancel.c
In case the wdog has already completed when calling cancel, the cancel is supposed to just return OK.
Currently watchdogs are broken due to this in master, the issue is easy to demonstrate in qemu smp targets. For example ostest in rv-virt:smp fails due to this.
Fixes a bug in wd_cancel
Tested in rv-virt:smp
=> sched/wdog/wd_cancel: Return 0 (OK) when cancelling an inactive wdog

arch/arm/src/rp23xx/Kconfig, arch/arm/src/rp23xx/rp23xx_timerisr.c
Add ability to use arv8m systick lowerhalf driver
Fix wrong macro for systick current register in initialize
tested on pico 2
=> arch/arm/src/rp23xx: allow to use armv8m systick lowerhalf

arch/sim/Kconfig
arch/sim/Kconfig: simulated CAN depends on LINUX host
in reference to https://github.com/apache/nuttx/issues/16317
CI
=> arch/sim/Kconfig: simulated CAN depends on LINUX host

arch/risc-v/src/common/espressif/esp_pcnt.c
In #15079, support for PCNT pulse counter was introduced, an implementation for the counter accumulation functionality is included, but due to a bug, the counter value is not accumulated and overflows at pulse counter's respective MIN and MAX limits.
This is caused by all interrupt events being disabled during the initialization of the PCNT unit and the interrupt events associated with limit overflows are not enabled on the periphery, therefore the ISR responsible for the accumulation never gets called.
Fixed by enabling the associated interrupt events during the PCNT unit initialization when the `accum_count` field in  the `esp_pcnt_unit_config_s` config structure is set to true by the board code.
This PR enables PCNT pulse counter value accumulation in Espressif boards.
The fix was …
=> arch/risc-v/src/common/espressif/esp_pcnt.c: counter accumulation fix

arch/arm64/src/imx9/hardware/imx9_ele.h, arch/arm64/src/imx9/imx9_ele.c, arch/arm64/src/imx9/imx9_ele.h
This PR extends the ELE API with support for Random Number Generation for i.MX9.
It includes 3 new calls:
1. `imx9_ele_start_rng()` -> Request ELE  to initialize the RNG context so it can generate random numbers
2. `imx9_ele_get_trng_state()` -> Poll the state of the random generator
3. `imx9_ele_get_random()` -> Request generation of a random number of arbitrary size.
The initial need to create this PR stemmed from optee requiring prior initialization of the RNG engine in order to generate the 
ASLR seed. It seemed logical to include the rest of the associated functions as well for completion.
Users that want to build a custom nuttx BL2 bootloader (for a TF-A setup) can now also initialize the Random Number Generator through `imx9_ele_start_rng()`, in order to have it usable for later …
=> arch/arm64/imx9: Extend ELE API with RNG support

drivers/can/ctucanfd_pci.c
This revises the post-IRQ interruption control logic so that to balance the disable/enable operations for both chardev and socketcan cases. This also resolves endless IRQ with socketcan on some ARM platform.
Devices using CTUCAN driver
Checked with chardev and socketcan with `qemu-intel64` target on Ubuntu 22.04 host.
=> drivers/ctucan: fix IRQ ctrl

.codespellrc, Documentation/platforms/arm/nrf53/boards/thingy53/index.rst, boards/arm/nrf53/common/include/nrf53_bme688.h, boards/arm/nrf53/common/src/CMakeLists.txt, boards/arm/nrf53/common/src/Make.defs, boards/arm/nrf53/common/src/nrf53_bme688.c, boards/arm/nrf53/thingy53/src/nrf53_sensors.c, drivers/sensors/CMakeLists.txt, drivers/sensors/Kconfig, drivers/sensors/Make.defs, drivers/sensors/bme688_uorb.c, include/nuttx/sensors/bme688.h
-  sensors: add support for BME688 sensor  
Add support for BME688 sensor based on BME680 implementation.
The BME688 is nearly identical to the BME680, and this implementation
reuses much of the existing BME680 code. However, there are some differences
related to gas measurements that make it impractical to use the same driver
without significantly complicating it. BME688 also supports parallel mode
which isn't yet supported.
- boards/thingy53: add BME688 sensor support
new feature
sensor tested on thingy53
=> sensors: add BME688 gas sensor

tools/CMakeLists.txt
More aligned to the tools/Makefile.host file
Added:
- The option() command  It provides a way to enable or disable targets of the project based on the user's preference.
Default
option(NUTTX_INCLUDE_ALL_TOOLS "Build all NuttX Host Tools" ON)
- Checking host system for compilation options.
- Tools -> configure, mkconfig, mksymtab and mkversion.
locally  MSYS2  and Windows Native
building only mkversion
cmake -B build -DNUTTX_INCLUDE_ALL_TOOLS=OFF -DNUTTX_INCLUDE_MKVERSION=ON
```
test@TEST MSYS ~/nuttx/tools
$ cmake -B build -DNUTTX_INCLUDE_ALL_TOOLS=OFF -DNUTTX_INCLUDE_MKVERSION=ON
-- The C compiler identification is GNU 13.2.0
-- Detecting C compiler …
```
=> tools/CMakeLists.txt: Improvements to CMakeLists.txt file

Documentation/applications/examples/nximage/index.rst, Documentation/applications/graphics/nxwidgets/index.rst, Documentation/applications/graphics/twm4nx/index.rst, Documentation/applications/interpreters/minibasic/index.rst, Documentation/applications/nsh/login.rst, Documentation/applications/nsh/running_apps.rst, Documentation/applications/system/i2c/index.rst, Documentation/applications/system/ymodem/index.rst, Documentation/applications/system/zmodem/index.rst, Documentation/applications/tools/index.rst, Documentation/applications/wireless/i8sak/index.rst, Documentation/contributing/coding_style.rst, Documentation/contributing/making-changes.rst, Documentation/implementation/simulation.rst, Documentation/introduction/about.rst, Documentation/introduction/development_environments.rst, Documentation/platforms/arm64/fvp-v8r/boards/fvp-armv8r/README.txt, Documentation/platforms/arm64/qemu/boards/qemu-armv8a/README.txt, Documentation/platforms/avr/at32uc3/boards/avr32dev1/README.txt
Currently there are a few pieces of documentation written in the first person perspective.
This phrasing may be misunderstood as belonging to a single person project (instead of a community project).
Changed wording of documentation.
Fewer sections in the documentation contain the first person perspective.
This pull request is just a minimal start correcting only a few files. It is intended to collect early feedback.
My questions:
* Do you consider this kind of change to be useful?
* Do you have any feedback regarding my phrasing? (I am not a native speaker)
Based on your feedback I will go through the other files and finalize this pull request.
=> WIP: Documentation: replace first person perspectives

arch/arm/src/sama5/Kconfig, boards/arm/sama5/sama5d3-xplained/src/sam_usb.c
Delete the board-specific usb host waiters and use the common code.
Only affects users of sama5d3-xplained
Add this to the sama5d3-xplained/configs/nsh/defconfig
CONFIG_SAMA5_EHCI=y
CONFIG_SAMA5_OHCI=y
CONFIG_SAMA5_UHPHS=y
CONFIG_USBHOST_MSC=y
Load and run nuttx.bin at 0x20008000 using u-boot
Plug in a USB storage device.
If "sda" is listed, the waiter is working. (Unplugging will remove the "sda")
nsh> ls /dev
/dev:
console
null
sda
ttyDBGU
zero
=> boards/sama5d3-xplained: Use common usb host waiter.

Documentation/platforms/arm/sama5/boards/sam5d3-xplained/index.rst, Documentation/platforms/arm/sama5/boards/sama5d3-xplained/index.rst
There were two sama5d3-xplained links in the Supported Boards section.
None
Only one sama5d3-xplained link seen in the file generated by make html.
=> Documentation/sama5d3-xplained: Remove duplicate link.

drivers/can/ctucanfd_pci.c
Fix frame reception when CANFD is not enabled and there are many message in the RX buffer.
The previous implementation assumed that the size of the data in the RX buffer is constant, which is not true. Fortunately, the amount of data in the buffer can be easily read from frame->fmt.rwcnt.
fix CAN CTU FD when used in non CANFD mode.
CAN network simulated on host doesn't lose frames:
- qemu-x86 with canctufd and candump tool
- qemu-arm and canctufd runs simple CAN node with socketcan
- arm and canctufd runs simple CAN node with char dev
- sim runs simple CAN node with socketcan
- sim runs simple CAN node with char dev
=> drivers/ctucanfd_pci.c: fix frame reception

arch/arm/src/stm32h5/stm32_start.c, arch/arm/src/stm32h5/stm32h563xx_flash.c
Properly select physical bank for block erase based on block number.
Previously, it would configure flash erase bank select based on the logical bank. If banks were swapped, and user application tried to erase the first block of logical bank 2 (expecting to erase starting at 0x08100000), it would actually erase starting at 0x0800000. This is fixed in this commit.
This is the fix for the bug reported in #16417.
- Fix for #16417
- Allows progmem interface on STM32H5 MCUs when flash banks are swapped with option byte `SWAP_BANK = 1`
Target: STM32H563ZIT6U
Board: Nucleo H563ZI
Config: Modified version of nucleo-h563zi:nsh
- Enables progmem driver in system type and MTD device driver.
- Adds access to custom app for testing (See below)
Result of ostest from this build: …
=> arch/stm32h5: Fix FLASH bank logic during erase operations.

sched/semaphore/sem_holder.c, sched/semaphore/sem_post.c, sched/semaphore/sem_waitirq.c
This PR contains two bugfixes and one cleanup commit for semaphore/mutex code:
- There was a bug in sem_post for a mutex, setting "blocking" bit incorrectly. This may cause errors in SMP systems
- There is no need to clear the "blocking" bit in sem_waitirq, this is just extra code
- Holders for mutex were not freed correctly, leading to consuming extra holder structures and in worst case a crash if
a leftover holder was pointing to a deleted thread/task
These errors were found in our internal reliability testing and debugging the issues found.
This fixes some (rare) stability issues after PR #16194
Tested on rv-virt:smp and on real hardware (mpfs 250t, SMP), with real application and with ostest
=> Semaphore corrections

tools/ci/testlist/arm-05.dat
Removed from the arm-05.dat file the entries:
CMake,nrf52832-dk:buttons
CMake,nrf52832-dk:wdog
CMake,nrf52840-dk:adc
CMake,nrf52840-dk:buttons
CMake,nrf52840-dk:pwm
CMake,nrf52840-dk:qspi
CMake,nrf52840-dk:timer
present in the jumbo configuration
locally
=> tools/ci/testlist/arm-05.dat: removed missing entries

tools/nxstyle.c
fix defined but not used warning from CI:
Warning: nxstyle.c:767:13: warning: ‘backslash_to_slash’ defined but not used [-Wunused-function]
767 | static void backslash_to_slash(char *str)
fix warning
CI
=> tools/nxstyle.c: fix defined but not used warning

drivers/usbdev/cdcncm.c
See issue 16345 [here](https://github.com/apache/nuttx/issues/16345).
I found that the CDC-NCM link only successfully established on the first connection. If the USB was unplugged then replugged the link was not re-established.
@zhhyu7 provided the fix which I validated, and is now submitted here for all..
The change is simple, involving the reset of the CDC-NCM configuration on a disconnect; it is then able to be reconfigured at the next connect. Impact should only be positive.
After this fix I have had several weeks of ongoing development using CDC-NCM with 100's of connect/disconnect cycles with NO repeats of the issue.
=> drivers/usbdev/cdcncm.c: Fix issue with USB unplug/replug not restarted link

fs/vfs/fs_epoll.c, fs/vfs/fs_poll.c, include/nuttx/fs/fs.h, include/sys/poll.h
Resolving the issue of fdcheck reporting errors when an epoll file descriptor (fd) is closed.
The primary cause of the error is as follows: 
When a task exits by calling exit, it closes all file descriptors (fds) associated with the current task. 
When the epoll fd is closed, if there are still fds in the epoll queue that have values greater than the epoll fd, these fds may be closed first. This can lead to fdcheck failures when call epoll_close
To resolve this, we should use a file-based approach instead of directly managing fds in epoll.
fix epoll fdcheck issue
open vela monkey
=> Resolving the issue of fdcheck reporting errors when an epoll file descriptor (fd) is closed

Documentation/applications/examples/gps/index.rst, Documentation/applications/testing/getprime/index.rst
Include some documentation for example applications, as part of #11081.
Impacts only documentation by completing two documentation pages.
Local documentation build.
=> DOCS: Application documentation

arch/avr/src/avr/Toolchain.defs, arch/avr/src/avr/avr_saveusercontext.S, arch/avr/src/avr/excptmacros.h, arch/avr/src/avrdx/avrdx_serial.c, boards/avr/avrdx/breadxavr/include/board.h
0001 - this patch fixes LED constants for breadxavr board. The code was
developed based on other AVR boards, LED constants were taken from board
that apparently has multiple status LEDs and used on a board that only
has one.
The functionality that was not working properly is blinking LED on
panic, which works correctly now
0002 - while digging around in the code trying to figure out how PANIC()
works, I noticed a bug in up_saveusercontext function that is called
from _assert.
The function makes use of USER_SAVE macro but that macro is designed to
be only a first half of the context switch. It is unsuitable to be used
standalone like it was in up_saveusercontext, it pops return address
from the stack and does not return, meaning that the function also did
not return.
The patch adds what is …
=> arch/avr: fix up_saveusercontext and other smaller changes

arch/arm64/src/Toolchain.defs, arch/arm64/src/cmake/Toolchain.cmake
Add -fstack-usage to arch/arm64/src/Toolchain.defs for stack analysis. The problem is that after `CONFIG_STACK_USAGE` enabled, no "*.su" file was generated, tools/showstack.sh output nothing.
**Referenced to https://github.com/apache/nuttx/pull/8177**
arm64/toolchain
=> arm64/toolchain: Add -fstack-usage for stack analysis

arch/arm64/src/imx9/Kconfig, arch/arm64/src/imx9/imx9_boot.c
Originally the i.MX9 bootloader was only supposed to run at EL3. However in some scenarios, for instance in a TF-A
deployment, the nuttx bootloader is the BL33 payload and runs at EL1.
To make the bootloader run at EL1 we need to remove parts of the initialization that are only expected to happen at EL3.
This PR is minimal, and  doesn't auto select DDR training and FIQ decoding if   `ARCH_ARM64_EXCEPTION_LEVEL != 3`.
Additionally `arm64_chip_boot()` excludes `imx9_mix_powerup()`, `imx9_ccm_clock_init()`, `imx9_trdc_init()` and `imx9_dram_init()` if `ARCH_ARM64_EXCEPTION_LEVEL != 3`
Boards without `CONFIG_IMX9_BOOTLOADER` or boards with `CONFIG_IMX9_BOOTLOADER=y` that already run the bootloader at EL3 behave exactly as before.
Boards built with `CONFIG_IMX9_BOOTLOADER=y` and …
=> arch/arm64/imx9: Guard EL3-only features when booting at EL1

arch/arm/src/imxrt/hardware/rt117x/imxrt117x_iomuxc.h, arch/arm/src/imxrt/imxrt_clockconfig_ver2.c
Fixes issues with CPU hanging when accessing OCRAM M7 ECC memory region.
And corruption from eDMA writing into DTCM memory.
This was caused because FlexRAM peripheral was incorrectly clocked and turned during off M7 sleep. 
This patch fixes clock setting and ensure that clock stays on during M7 for backdoor access from for example eDMA.
rt117x
V6X-RT with memory testing tools
=> arch/arm/imxrt: rt117x fix TCM/OCRAM ECC backdoor access

Documentation/reference/user/02_task_scheduling.rst
Remove repeated word in
> Sporadic scheduling scheduling is more complex
in the _[Task Scheduling Interfaces](https://nuttx.apache.org/docs/latest/reference/user/02_task_scheduling.html#task-scheduling-interfaces)_ page in the documentation.
Just slightly easier reading.
None. Would like to verify that docs render correctly.
Should I reflow the text to fit a specific line width?
=> Fix typo in scheduling docs

audio/audio_comp.c
audio/comp: fix build warning caused by invalid return value
```
audio/audio_comp.c:958:14: warning: returning ‘int’ from a function with return
type ‘struct audio_lowerhalf_s *’ makes pointer
from integer without a cast [-Wint-conversion]
958 |       return -EINVAL;
|              ^
```
N/A
enable CONFIG_AUDIO_COMP without warning
=> audio/comp: fix build warning caused by invalid return value

arch/arm/src/samv7/sam_serial_spi.c
Bitfield `CPHA` has to be set to run SPI in mode 0. This is a default mode, therefore it should be set during the peripheral initialization.
Samv7 only. SPI on USART is now initialized in a correct mode.
Tested against icjx io expander. The mode selection is now correct also according to an oscilloscope (previous behavior had data change on leading edge and sampled on falling edge)
=> arch/arm/src/samv7/sam_serial_spi.c: set correct SPI mode during init

Documentation/conf.py
Add `nuttx_versions` back into the `html_context` variable after it was re-defined in #16440 to include more options. This fixes the failing Pphinx autobuild. I also moved the options into the HTML option section.
`make autobuild` now works properly again. This change only affects the Documentation system.
Tested by performing `make autobuild` locally after the change an observing a successful build and render.
=> docs/conf.py: Fix missing `nuttx_versions`

drivers/mtd/mtd_rwbuffer.c
drivers/mtd: fix compile warning
```
mtd/mtd_rwbuffer.c:42:
mtd/mtd_rwbuffer.c: In function 'mtd_erase':
mtd/mtd_rwbuffer.c:189:9: warning: format '%zx' expects argument of type 'size_t', but argument 3 has type 'long long int' [-Wformat=]
189 |   finfo("block: %08zx nsectors: %zu\n",
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
190 |         (intmax_t)block, nsectors);
|         ~~~~~~~~~~~~~~~
|         |
|         long long int
mtd/mtd_rwbuffer.c:189:21: note: format string is defined here
189 |   finfo("block: %08zx nsectors: %zu\n",
|                 ~~~~^
|                     |
|                     unsigned int
|                 %08llx
mtd/mtd_rwbuffer.c: In function 'mtd_ioctl':
mtd/mtd_rwbuffer.c:298:21: warning: format '%d' expects argument of type 'int', but argument 3 has type …
```
=> drivers/mtd: fix compile warning

.gitmessage, Documentation/contributing/making-changes.rst
Introduces a commit message template with instructions in the contributing documentation about how to set it up. This way users are reminded of what makes a "good" NuttX commit as they write their commit, and don't need to re-consult the documentation every time.
Impacts the Documentation for contributing, and also creates a template that users will be using for (presumably) every commit they write once they configure git templates.
Tested locally by:
1) Verifying documentation build and render
2) Running the provided command in the documentation to set the template, and then using it to write this PR's commit message
=> docs/contributing: Add a commit message template

arch/risc-v/Kconfig, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_perf.c
Add up_perf_ functions for MPFS, which don't rely on alarm/oneshot interface.
Also add optimized up_udelay and up_ndelay functions, which use the MTIMER directly to measure time; making them accurate and more multithreading friendly.
Only for MPFS platform;
- makes up_perf_gettime faster, when the call doesn't go through the alarm framework. which in turns helps profiling
- uses the 1MHz MTIME counter on MPFS to directly measure up_udelay, preventing unnecessary delays when call is pre-empted by another task or interrupt.
Tested on a custom MPFS250T based board & segger system view tool to compare the overhead  with and without this patch.
=> arch/risc-v/mpfs: Add optimized perf timer functions

drivers/note/note_driver.c, drivers/segger/Kconfig, drivers/segger/config/SEGGER_RTT_Conf.h, drivers/segger/config/SEGGER_SYSVIEW_Conf.h
I recently tested segger sysview on MPFS platform, and found out some issues with the driver.
This is a collection of patches which I made in order to make it usable for my purpose, including:
- Compilation errors with -Werr
- In SMP, the driver deadlocks due to entering spinlock recursively. Changed this to critical section, didn't see much performance degredation with that
- up_perf_gettime was assumed to be always nanosecods, this is not true, but segger driver can scale the timestamps correctly. Just need to configure the frequency
- added support to configure "post-mortem" mode, which essentially traces continuously to a circular buffer until the tracing is stopped
Impacts only using Segger System View tool to profile a running system
Tested on MPFS platform, by configuring …
=> Segger sysview improvements

include/nuttx/spinlock.h
As our previous discussion, we should use a new API spin_lock_irqsave_nopreempt to handle the spin_lock with sched locked, and did not change the default behavior of original spin_lock_irqsave.
Also for the drivers etc. those by design need recursive lock behavior, if we did not support recursive API call, have to use critical_section, that is not a good idea. critical_section should not be abused for this scene. 
For drivers implement those possible recusive, native spinlock
will cause deadlock directly, critial_section is use globally,
will make lock parallel to serial, add API to keep recursive
support but isolate each other.
for example #16483
Only add API in .h, did not change or modify user usage.
Able to call new API with spinlock & sched disabled with one call.
Able to support …
=> add spin_lock_irqsave_nopreempt rspin_lock_irqsave_noprempt implement.

arch/arm/src/imxrt/imxrt_serial.c
In singlewire mode the ops were only for non-dma usecases. But if rxdma is enabled we can use that.
For TXDMA it's not possible because we've to change pin direction immediately after transmission is done.
IMXRT
MIMXRT1064
=> arch/arm/imxrt: Serial add RXDMA support for singlewire mode

net/utils/utils.h
the address is 0x3c270203, cause unaligned access usage Fault (gdb) p g_tcp_connections
$1 = {pool = 0x3c270203 <g_tcp_connections_buffer> <error: Cannot access memory at address 0x3c270203>, prealloc = 8, dynalloc = 1, nodesize = -376, sem = {semcount = 32767, flags = 0 '\000', waitlist = {head = 0x0, tail = 0x0}}, freebuffers = {head = 0x0, tail = 0x0}}
manual alignment has been added.
cortex-m33 and local:sim
=> net/utils: avoid unalign access g_tcp_connections_buffer

include/nuttx/spinlock.h
So that the same code can be used with and without spinlocks.
This complements the commit 225d6fb0a73, which missed the spin_unlock()
Allows compiling non-smp target, which calls spin_unlock.
Fixes compilation on a custom target
=> nuttx/spinlock: Define empty macro for spin_unlock

arch/arm/src/stm32f7/stm32_capture.c
Enabling the Timer Capture feature causes the compilation to fail due to undeclared RCC stuff.
This PR aims to fix this issue,
Thanks to @acassis for assisting me, 
Adds the include of "stm32_rcc." to the "stm32_capture.c" to fix the undeclared RCC settings.
Before PR:
After PR:
=> arch/arm/stm32f7: Add missing RCC include

arch/arm/src/samv7/sam_start.c
`__start` should call `up_perf_init`, initialization of hardware performance counter, if `CONFIG_ARCH_PERF_EVENTS` option is set. This allows the usage of ARM cycle count register `DWT_CYCCNT` in benchmark measurements instead of software clock.
SAMv7 MCU can now utilize `DWT_CYCCNT` register as hardware performance counter.
Tested on a custom board with SAMv7 MCU and `osperf` applications. Results without hardware performance counter (normal mode with `CONFIG_USEC_PER_TICK=100`)
```
NuttShell (NSH) NuttX-12.9.0
brcg2> 
brcg2> osperf
OS performance args: count:100, detail:false
==============================================================
Describe                                Max        Min        Avg
pthread-create                       100000          0      19000
pthread-switch …
```
=> arch/arm/src/samv7/sam_start.c: init perf events if enabled

arch/risc-v/src/common/riscv_exception.c
This helps in debugging loaded elf files in CONFIG_BUILD_KERNEL. If a user space exception occurs, one would beed the process name in order to debug the correct process/elf file.
Only dumping the pid and name of the crashed task/thread doesn't help, since different processes may have helper threads with the same name.
Only risc-v exception output in user-space
Tested on MPFS platform with CONFIG_BUILD_KERNEL, by artificially generating null-pointer reference in user-space applications and monitoring the output.
=> arch/riscv/ricv_exception.c: Dump the process name at exception in user space

.gitignore
Like VSCode, Jetbrains IDEs store local configuration inside a folder called ".idea".
This folder should be ignored by git.
Adds the ".idea" entry inside the .gitignore file
/
=> chore: update gitignore for .idea folder

arch/risc-v/src/common/espressif/.gitignore, arch/risc-v/src/common/espressif/Bootloader.mk, arch/xtensa/src/esp32/.gitignore, arch/xtensa/src/esp32/Bootloader.mk, arch/xtensa/src/esp32s2/.gitignore, arch/xtensa/src/esp32s2/Bootloader.mk, arch/xtensa/src/esp32s3/.gitignore, arch/xtensa/src/esp32s3/Bootloader.mk
- **arch/risc-v: decouple common source for Espressif's MCUBoot port**
Decouples the NuttX build from the MCUBoot common source on RISC-V Espressif
devices. Allows using different branches for each.
- **arch/xtensa: decouple common source for Espressif's MCUBoot port**
Decouples the NuttX build from the MCUBoot common source on Xtensa
devices. Allows using different branches for each.
This PR changes MCUBoot build process for Xtensa and RISC-V Espressif devices.
No changes on user side or build process.
- Impact on user: No.
- Impact on build: MCUBoot shared the same esp-hal-3rdparty repository as the Nuttx build. It now clones this repository to a different directory so we can have MCUBoot and Nuttx operate in different hal versions.
- Impact on hardware: Espressif Xtensa and RISC-V …
=> Update MCUBoot build process for Espressif devices

fs/vfs/fs_close.c
Double free occurred in `lib_put_pathbuffer` if `CONFIG_FS_NOTIFY` option was enabled. The second if statement has to be called only if the close operation returned error. The bug was introduced in 14f5c48 and was causing `misc/lib_tempbuffer.c:141` debug assertion.
Fixed system failing on assertion during close operation if `CONFIG_FS_NOTIFY` is set. This should close #16531.
System doesn't fail on an assertion with this change. GDB backtrace for samv7 custom board before the change showing the double free.
```gdb
Breakpoint 2, lib_put_tempbuffer (buffer=0x20400eb4 <g_tempbuffer+4> "tmpc000001") at misc/lib_tempbuffer.c:137
137	{
(gdb) bt
#0  lib_put_tempbuffer (buffer=0x20400eb4 <g_tempbuffer+4> "tmpc000001") at misc/lib_tempbuffer.c:137
#1  0x0043749c in file_close (filep=0x20419808) …
```
=> fs/vfs/fs_close.c: avoid double free if CONFIG_FS_NOTIFY is set

Documentation/applications/system/syslogd/index.rst
The documentation for `syslogd` is now updated to reflect its use of `posix_spawn` to run the daemon in the background.
Impacts only user documentation, making it more accurate.
Tested with local documentation build.
=> docs/syslogd: Update syslogd docs to reflect implementation

arch/Kconfig, arch/avr/Kconfig, drivers/serial/Kconfig, drivers/serial/Kconfig-usart, drivers/serial/serial.c, include/nuttx/serial/serial.h
While going through the code in drivers/serial/serial.c, I noticed this 
comment:
The head and tail pointers are 16-bit values.  The only time that
the following could be unsafe is if the CPU made two non-atomic
8-bit accesses to obtain the 16-bit head index.
This is what happens for (at least) AVR architecture. These are 8bit 
microcontrollers and as such, they will fetch the 16-bit value in two 
8-bit load instructions; interrupt routine may execute between those and 
change the value being read. This will result in corrupted read (one 
byte of the value will be from pre-interrupt state and the other from 
post-interrupt state.)
This patch introduces CONFIG_ARCH_LD_16BIT_NOT_ATOMIC configuration 
option, which is automatically selected for architectures known to be 
unable to load 16bit …
=> drivers/serial: fix race conditions 

sched/misc/assert.c
When Stack pointer value not within the stack, the default methon ignored, while will be discard this information for debug.
and runtime logs …
=> sched: assert: Print Stack pointer value when not within the stack

tools/refresh.sh
This modification will simplify the case where the developer wants to update all board configs from a specific board.
Avoid updating each config manually
Tested with this board:
$ ./tools/refresh.sh --silent board:nucleo-wl55jc
=> tools: Modify refresh.sh to support update all configs from a board

Documentation/platforms/risc-v/qemu-rv/boards/rv-virt/index.rst, arch/risc-v/src/common/riscv_swint.c, boards/risc-v/qemu-rv/rv-virt/scripts/ld-nuttsbi.script
* boards/risc-v/qemu-rv: Add missing section on `ld-nuttsbi.script`
* Fix an issue regarding the `rv-virt:nsbi` defconfig, which wasn't booting properly because `sbi_set_mtimecmp` failed to get the `mtimecmp`'s register address when evaluating `g_mtimecmp`. This variable, which should be located at the `.noinit` section, wasn't being set accordingly by the linker script, ending up on `bss` section which is zero-initialized, overwriting its value previously set by `sbi_init_mtimer`.
* Documentation/rv-virt: Add entries for `nsbi[|64]` defconfigs
* arch/risc-v: Fix debugging syscall info
Impact on user: YES. Fix boot problem on `rv-virt:nsbi[|64]`
Impact on documentation: YES. Adds related documentation about such configurations.
Impact on …
=> arch/risc-v: Fix `rv-virt:nsbi[|64]` defconfigs

arch/xtensa/src/esp32s3/esp32s3_lcd.c
The PR aims to fix an issue with the framebuffer resolution, which was inverted.
Probably this impacts the ESP32S3_LCD_EV board, but considering the resolution (480x480), nothing changes  
I tested during the contribution of a new board with similar hardware (ESP32S3-WROOM1 and TFT LCD RGB).
- https://github.com/apache/nuttx/pull/16558) 
https://github.com/user-attachments/assets/93d4b0a3-4424-4d3f-93a3-901dda42da69
=> [Fix] Esp32S3 LCD FB resolution.

libs/libc/netdb/lib_dnsquery.c
netdb/lib_dnsquery.c: In the IPv6 or IPv4 dns_query_callback() block, if dns_recv_response() fails, dns_bind() is called again at try_stream to create a new socket. However, the original socket descriptor sd isn't closed.
New Feature/Change: Issue fix (no new feature).
User Impact: Prevent file descriptor leakage.
Hardware Impact: No
Security: No
Compatibility: Backward-compatible; no breaking changes.
When DNS query fails and a switch from UDP to TCP streaming mode is required, UDP connections will continue to increase as follows:
Afer fix, UDP connections do not increase like before.
=> netdb/lib_dnsquery.c: prevent file descriptor leakage

arch/xtensa/src/esp32s3/esp32s3_lcd.c
The PR aims to fix the output format in lcdinfo: change PRIx32 to PRIuPTR/PRIu32 for data type compatibility 
None
=> [ESP32S3] Remove LCD Warnings.

drivers/input/button_upper.c, drivers/segger/config/SEGGER_RTT_Conf.h, drivers/segger/segger.c, include/nuttx/notifier.h, include/nuttx/sched_note.h, include/nuttx/spinlock.h, include/nuttx/spinlock_type.h, sched/clock/clock_initialize.c, sched/misc/panic_notifier.c
This commit provided a better recursive spinlock implementation with less memory-overhead and better performance.
E.g.
**Memory-overhead**: 32 + 32(padding) + 64 + 32 = 160 bits decrease to 32 bits on AArch64.
**Performance**: 160-bits data may cross the cache-line, result in significant performance degradation. 32-bits lock-data will not cross the cache-line in any case.
This commit may have an impact on memory usage and performance on SMP systems.
Tested on `qemu-armv8a:nsh_smp`.
Tested on `qemu-intel64:nsh` using `sudo qemu-system-x86_64 -enable-kvm -cpu host,+invtsc,+vmware-cpuid-freq,kvmclock=off -m 2G -kernel nuttx -nographic -serial mon:stdio` (`kvm`).
The simple 1M lock-and-add loop test result on a Intel Core 12700 machine shows the latency of per-operation under no contention:
| …
=> spinlock: Better recursive spinlock implementation.

drivers/segger/CMakeLists.txt
Segger SysView has been upgraded to version V3.5.6
PR #13847
CI
=> drivers/segger/CMakeLists.txt: Aligned Cmake with Make

Kconfig, sched/irq/irq_initialize.c
Implemented using up_debugpoint_add
Use watchpoint to protect address 0, which is used as a debugging method in some scenarios
None
1. enable CONFIG_ARCH_PROTECT_ZERO_ADDRESS，if access 0 address panic()
=> debug/0 address: Add 0 address access panic configuration

drivers/serial/ptmx.c, fs/inode/fs_files.c, fs/mqueue/mq_open.c, fs/vfs/fs_open.c
fs/vfs: clear filep when call file_open/file_mq_open to avoid random value
[drivers/serial: fix the issue of the refs count for filep being zeroed out by utilizing dup2
bug fix
qemu-glodfish armv7a-eabi 
include adb and romfs test
=> fs/vfs: clear filep when call file_open/file_mq_open to avoid random value[bug fix]

include/nuttx/sensors/cxd5602pwbimu.h
There is insufficient definition information for a dependency, so add the include header file.
Only cases using IMU driver. 
Build check.
=> Add a header file as a dependency

sched/group/group_setuptaskfiles.c
bugfix: share kernel thread group should not dup files from caller group
after this commits
commit e7fa4cae6cbf567266985c8072db1f51ad480943
Author: Yanfeng Liu <yfliu2008@qq.com>
Date: Fri May 17 06:11:52 2024 +0800
sched/tcb: use shared group for kthreads
all kernel thread share group 
and should not dup filelist to this group
https://github.com/apache/nuttx/issues/16560, bug fix
test code:
add test code to dev_zero driver
add test code to examples hello:
=> bugfix: share kernel thread group should not dup files from caller group

tools/ci/docker/linux/Dockerfile
Bump risc-v toolchain to 14.2.0-3
=> ci/docker: bump risc-v toolchain

arch/arm64/src/fvp-v8r/CMakeLists.txt, boards/arm64/fvp-v8r/fvp-armv8r/CMakeLists.txt, boards/arm64/fvp-v8r/fvp-armv8r/src/CMakeLists.txt
arm64/fvp-v8r: support cmake compile
No
ci
=> arch/arm64/fvp-v8r: support cmake compile

arch/arm/Kconfig, arch/arm/include/armv7-a/cp14.h, arch/arm/src/armv7-a/CMakeLists.txt, arch/arm/src/armv7-a/Make.defs, arch/arm/src/armv7-a/arm_dataabort.c, arch/arm/src/armv7-a/arm_hwdebug.c, arch/arm/src/armv7-a/arm_prefetchabort.c, arch/arm/src/armv7-a/mmu.h, arch/arm/src/common/arm_internal.h
1. Enhance armv7a's dataaboart to adapt to debug mode
2. Enhance armv7a's prefetchaboart to adapt to debug mode
3. arm: Support hardware debug
4. arm: Add support for CP14
To enhance the gdbstub breakpoint function of arm32
We can use gdbstub to test this function, or api:
1. up_debugpoint_add
2. up_debugpoint_remove
Usage:
https://github.com/apache/nuttx/blob/master/Documentation/applications/system/debugpoint/index.rst
=> arch/arm/armv7-a: Support hardware debugpoint to  enhance gdbstub

arch/Kconfig, arch/arm64/Kconfig, arch/arm64/src/a527/a527_boot.c, arch/arm64/src/common/arm64_arch.h, arch/arm64/src/common/arm64_mmu.h, arch/arm64/src/common/arm64_mte.c, arch/arm64/src/qemu/qemu_boot.c, drivers/virtio/virtio-mmio.c, include/nuttx/arch.h, include/nuttx/mm/kasan.h, libs/libc/machine/arm64/arch_elf.c, mm/kasan/CMakeLists.txt, mm/kasan/Kconfig, mm/kasan/Make.defs, mm/kasan/generic.c, mm/kasan/hook.c, mm/kasan/hw_tags.c, mm/kasan/sw_tags.c, mm/mempool/mempool_multiple.c, mm/mm_heap/mm_free.c, mm/mm_heap/mm_heapmember.c, mm/mm_heap/mm_lock.c, mm/mm_heap/mm_malloc_size.c, mm/mm_heap/mm_memalign.c, mm/mm_heap/mm_realloc.c
1. Introduced the implementation of ARM64 MTE KASan to support hardware detection of memory errors
2. Software kasan supports mapping of initialization flags to solve kasan early access errors caused by non-on-chip memory
3. Fixed some kasan errors
no
ci
=> Enhanced Kasan

drivers/wireless/bluetooth/bt_uart.c, drivers/wireless/bluetooth/bt_uart.h
Read as much data as possible initially, then process each packet individually. Defined the read buffer within the structure and added a rx_len variable to indicate the current read offset. After processing each complete packet, leftover data is moved to rxbuf[0] and rx_len is reduced by the length of the processed packet. The next packet process will start from rxbuf[0] after the read ends at new rxbuf[rx_len].
PR picks from https://github.com/open-vela/nuttx/pull/38
=> Refactored the btuart_rxwork function to improve data reception stability.

arch/arm64/src/imx9/imx9_lpuart.c
Commit 83a119160 fixed SMP by removing call to uart_xmitchars from inside spinlock.
This only works for SMP, since uart_xmitchars has a lock only in SMP and the irq lock is ifdeffed away in a single-core system: https://github.com/apache/nuttx/blob/3d37e85b13fb57ae8f1b8f6917e5aaac918d0982/drivers/serial/serial_io.c#L61 . 
Thus, in a single-core configuration the uart_xmitchars can now be called in parallel from the interrupt handler and from the imx9_txint.
Fix this by filling the uart buffers already before enabling the interrupt, this way it is not possible to get the function called in parallel for the same device.
Fixes a regression in lpuart for single-core configuration, due to SMP enabling.
Tested on a custom imx93 based device, for both SMP 2 cores and in single-core …
=> imx9/lpuart: Fix race condition / regression in imx9_txint

tools/process_config.sh
Ignore commented-out lines when deleting repeated defines in defconfig
As reported [here](https://github.com/apache/nuttx/pull/14552#issuecomment-2627446272) on #14552, there are cases where a sed error would be thrown while processing the defconfig.  
After further investigation, it seems to be happening when commented-out lines contain the / character. sed would then interpret the following character as a command and crash.
This PR fixes this behaviour by ignoring all commented-out lines when removing duplicates.
Minimal.  
In case where a configuration is defined in both commented and uncommented formats, the uncommented entries will now stay present in the defconfig.
Tested on Ubuntu 22, with sed 4.8, on a custom target (STM32F7-based).
configure output before this fix
```
Copy files …
```
=> tools/process_config.sh: Fix sed errors

arch/arm/src/stm32/stm32_fdcan_sock.c, arch/arm/src/stm32f0l0g0/stm32_fdcan_sock.c, arch/arm/src/stm32h7/stm32_fdcan_sock.c
Previous code was failing to disable error interrupts which due to standard CAN retransmissions might trigger continusouly (for example, with a disconnected CAN interface) flooding the system and preventing other operations to continue.
Fixes: https://github.com/apache/nuttx/issues/16668
This patch fixes the bug on al the affected platforms. Normal behavior on non-bug conditions is not affected.
After applying the patch, the test program provided on the bug description runs as expected (counting continues after frames are send, and using gdb I have checked `fdcan_interrupt` is only triggered once).
=> arch/arm/src/*/stm32_fdcan_sock.c: prevent interrupt flood on errors.

arch/arm/src/stm32f0l0g0/Kconfig, arch/arm/src/stm32f0l0g0/stm32_adc.c
- arch/arm/stm32f0l0g0/adc: move ADC_MAX_SAMPLES to Kconfig
move ADC_MAX_SAMPLES to Kconfig so user can fine tune memory usage
User can fine-tune ADC memory usage, default behavior remains unchanged.
nucleo-c071rb
=> arch/arm/stm32f0l0g0/adc: move ADC_MAX_SAMPLES to Kconfig

tools/checkpatch.sh
Currently only .py files are supported. Non-Python files will report "format not implemented".
Signed-off-by: zhongzhijie1 <zhongzhijie1@xiaomi.com>
=> tools/checkpatch.sh: add -x option to auto-format Python files.

net/local/local_recvmsg.c, net/local/local_sendmsg.c
local: correct shutdown state when use UDP mode (To fix issue: https://github.com/apache/nuttx/issues/16555)
local socket
See the https://github.com/apache/nuttx/issues/16555
=> net/local: correct shutdown state when use UDP mode (To fix issue: https://github.com/apache/nuttx/issues/16555)

Documentation/components/drivers/special/sensors.rst, Documentation/components/drivers/special/sensors/l86xxx.rst, drivers/sensors/CMakeLists.txt, drivers/sensors/Kconfig, drivers/sensors/Make.defs, drivers/sensors/l86xxx_uorb.c, include/nuttx/sensors/ioctl.h, include/nuttx/sensors/l86xxx.h
This pull request adds support for the Quectel L86-M33 GNSS module. It is written to be used with the uORB sensor framework and provides implementations for the `orb_control`, `orb_activate` and `orb_set_interval` commands. Additional
This change will allow NuttX developers to make use of the Quectel L86-M33 GNSS module using the uORB sensor framework
This driver was tested on an STM32H743 MCU. Testing was done using the `uorb_listener` application and it was verified that under the appropriate circumstances (GNSS module was able to get a satellite fix) that the correct information was received and reported. Further testing was done using an external application to verify the …
=> drivers/sensors: add Quectel L86-XXX GNSS uORB sensor driver

Documentation/platforms/risc-v/esp32c6/boards/esp32c6-devkitc/index.rst, Documentation/platforms/risc-v/esp32c6/boards/esp32c6-devkitm/index.rst, Documentation/platforms/risc-v/esp32c6/index.rst, arch/risc-v/src/common/espressif/Kconfig, arch/risc-v/src/common/espressif/esp_i2c.c, arch/risc-v/src/common/espressif/esp_i2c.h, arch/risc-v/src/common/espressif/esp_i2c_slave.c, arch/risc-v/src/esp32c6/hal_esp32c6.mk, arch/xtensa/src/common/espressif/esp_i2c_slave.c, boards/risc-v/esp32c6/common/src/esp_board_i2c.c
Add LP_I2C support for ESP32-C6 to ahve multiple option on I2C peripheral and increase coverage of ESP32-C6's peripherals
Fix I2C Slave build error that happened after Espressif's common layer update.
* arch/xtensa: Bugfix I2C Slave build error for esp32[-|-s2|-s3]
Fix build error for Xtensa based Espressif devices
* arch/risc-v: Bugfix I2C Slave build error for esp32[-c3|-c6|-h2]
Fix build error for risc-v based Espressif devices
* arch/risc-v: Add LP I2C for esp32c6
Add LP I2C peripheral support for esp32c6
Impact on user: No, just new peripheral support added
Impact on hardware: Yes, new hardware support added into NuttX
Impact on documentation: Yes, related peripheral docs added
Command used to build and flash:
``` …
```
=> arch/risc-v: Add LP_I2C support for esp32[-c6]

Documentation/components/drivers/special/sensors/l86xxx.rst, drivers/sensors/Kconfig, drivers/sensors/l86xxx_uorb.c
This PR removes the termios dependency of the command to set fix rate. It makes the MINMEA dependency present in the Kconfig options for the driver, and it also adds a retry limit to the boot message verification of 3 times. The documentation has been updated to reflect the correct signature for the registration function and fix some formatting.
Closes #16699.
Closes #16698.
Closes #16697.
Makes the L86xxx driver more usable and configurable. Impacts only this driver and its documentation.
Tested by compiling the driver without termios support and with the other changes from scratch on an RP2040 based board (flight computer) and verifying that the driver was registered correctly and outputted information using `uorb_listener`.
This driver was a new addition to my project so I had to go …
=> drivers/sensors/l86xxx: Fix Kconfig options and dependencies

arch/arm/src/rp23xx/rp23xx_gpio.h, arch/xtensa/src/common/espressif/esp_dedic_gpio.c
RP2350B has 48 gpio, highers 16 accessed by "HI" registers
=> arch/arm/rp23xx :  Fix gpio  for RP2350B

libs/libc/machine/arm/arch_mcount.S
libc/mcount: add armv6m mcount implementation
armv6m does not support the complete Thumb-2 instruction set, resulting in compilation errors
CC:  dirent/lib_alphasort.c mcount.S: Assembler messages:
mcount.S:33: Error: cannot honor width suffix -- `bic r1,lr,#1'
mcount.S:35: Error: cannot honor width suffix -- `bic r0,r0,#1'
mcount.S:37: Error: cannot honor width suffix -- `pop {r0,r1,r2,r3,ip,lr}'
raspberrypi-pico/nsh
=> libc/mcount: add armv6m mcount implementation

Documentation/platforms/arm/stm32f4/boards/stm32f401rc-rs485/index.rst, boards/arm/stm32/stm32f401rc-rs485/src/CMakeLists.txt, boards/arm/stm32/stm32f401rc-rs485/src/Make.defs, boards/arm/stm32/stm32f401rc-rs485/src/stm32_bringup.c, boards/arm/stm32/stm32f401rc-rs485/src/stm32_hx711.c, boards/arm/stm32/stm32f401rc-rs485/src/stm32f401rc-rs485.h
This commit adds support for the HX711 ADC in the STM32F401RC-RS485 board and updates the board documentation accordingly.
Is new feature added? Is existing feature changed? Yes, Added HX711 support to STM32F401RC-RS485.
Impact on user (will user need to adapt to change)? Yes, users will be able to user HX711 on STM32F401RC-RS485.
Impact on build (will build process change)? No
Impact on hardware (will arch(s) / board(s) / driver(s) change)? Yes, ARM/STM32F401RC-RS485.
Impact on documentation (is update required / provided)? Yes, STM32F401RC-RS485 was updated.
Impact on security (any sort of implications)? No.
Impact on compatibility (backward/forward/interoperability)? No
I confirm that changes are verified on the local setup and work as intended:
Build Host(s): OS: Ubuntu 24.04, CPU: …
=> boards/arm/stm32f401rc-rs485: Add support to HX711 ADC

libs/libc/misc/lib_idr.c
libc lib_idr maintains 2 RB trees to efficiently handle node allocations. Removed nodes are not freed, but rather added to the "removed" RB tree, for potential re-use during subsequent allocations.
`idr_destroy()` would loop over the nodes of the "removed" and "alloced" RB trees, freeing them but not removing them from the trees. From the perspective of the RB tree those nodes would remain valid, while in fact, they were dangling pointers. This would cause (seemingly random) memory corruption crashes during subsequent iterations within the same tree triggered by the RB tree code trying to access linkage fields (`left`, `right`, `parent`) from the dangling pointers
Fix this by removing the nodes before freeing them.
I have observed this issue when using the optee driver with an app I …
=> libc/idr: Fix Use-After-Free during idr_destroy()

arch/arm64/src/zynq-mpsoc/zynq_serial.c
arm64/zynq-mpsoc: fix race condition in txint handler
The tx int handler will call uart_xmitchars() to make a fake interrupt event,
but this is unsafe after enabling interrupts. This PR will add a critical section
to ensure that the txint process will not be interrupted by the IRQ
N/A
Testing on z19-p FPGA, Check that the UART terminal output without garbled
=> arm64/zynq-mpsoc: fix race condition in txint handler

Documentation/components/drivers/character/analog/adc/ads1115/index.rst, drivers/analog/ads1115.c, include/nuttx/analog/ads1115.h
Since the ADS1115 has a relatively slow conversion rate, this additional ioctl command makes it possible to trigger a conversion before reading the reading the conversion result, allowing the user to perform other computation in between instead of waiting for the conversion time to complete. It improves sampling time.
Users can parallelize sampling of the ADS1115 ADC to avoid delays from sleeping while waiting for the conversion time duration.
Tested on a rocketry system with 4 ADS1115s in the sensor array. This change allowed parallezation to speed up sampling from 10Hz to 15Hz per channel per ADC.
@bskdany performed this testing, as did I.
=> drivers/analog/ads1115.h: Add ioctl for conversion trigger

tools/espressif/chip_info.py
* tools/espressif: Add risc-v compiler info dump for Espressif devices
Add xpack risc-v compiler info on diagnostic tool
Impact on user: No, addition just added on diagnostic tool
Command used to build:
```
make -j distclean && ./tools/configure.sh esp32s3-devkit:nsh && kconfig-tweak -e CONFIG_SYSTEM_NXDIAG && kconfig-tweak -e CONFIG_SYSTEM_NXDIAG_ESPRESSIF && make olddefconfig -s -j && make -j && make download ESPTOOL_PORT=/dev/ttyUSB0 ESPTOOL_BAUD=921600 ESPTOOL_BINDIR=../esp-bin
```
Alternatively `make host_info` command can be used after configuration.
`nxdiag --all` command used
Output before:
```
...
Toolchain version:
clang: Not found
gcc: gcc (Ubuntu …
```
=> tools/espressif: Add risc-v compiler info dump for Espressif devices

Documentation/applications/examples/mcuboot/index.rst
Updates the example documentation for a new example: local update agent. This example allows the user to update MCUBoot image from a locally stored file.
Relates to the pull request on `nuttx-apps`: [link](https://github.com/apache/nuttx-apps/pull/3135)
- Impact on user: No.
- Impact on build: No.
- Impact on hardware: No.
- Impact on documentation: Yes. Updates documentation for MCUBoot examples.
- Impact on security: No.
- Impact on compatibility: No.
Built fine locally using `make html` on Documentation directory.
=> documentation: update MCUBoot docs for local update agent example

arch/arm64/src/qemu/qemu_boot.c
arm64/qemu: decouple qemu board from chip
decouple qemu board from chip to support custom boards
add support of custom board
enable CONFIG_ARCH_BOARD_CUSTOM and check the build
fix build issue:
```
[1177/1180] Linking CXX executable nuttx
FAILED: nuttx
: && prebuilts/gcc/linux/arm64/bin/aarch64-none-elf-g++  --entry=__start -nostdlib -Wl,--gc-sections -Wl,-cref,-Map=nuttx.map -Wl,--print-memory-usage -Wl,--no-warn-rwx-segments @CMakeFiles/nuttx.rsp -o nuttx && :
prebuilts/gcc/linux/arm64/bin/../lib/gcc/aarch64-none-elf/14.2.1/../../../../aarch64-none-elf/bin/ld: arch/libarch.a(qemu_boot.c.obj): in function `arm64_chip_boot':
nuttx/arch/arm64/src/qemu/qemu_boot.c:180:(.text.arm64_chip_boot+0x30): undefined reference to …
```
=> arm64/qemu: decouple qemu board from chip

tools/ci/platforms/darwin.sh, tools/ci/platforms/darwin_arm64.sh, tools/ci/platforms/linux.sh, tools/ci/platforms/msys2.sh, tools/ci/platforms/ubuntu.sh
Bump Xtensa esp-14.2.0_20241119
ci/platforms/darwin.sh
ci/platforms/darwin_arm64.sh
ci/platforms/linux.sh
ci/platforms/msys2.sh
ci/platforms/ubuntu.sh
aligned with docker #16643
CI
=> ci/platforms: bump Xtensa esp toolchain

tools/ci/testlist/xtensa-01.dat
esp32-devkitc:nxlooper is currently failing CI due to a linker error, causing esptool to crash.
The fix requires updating esptool to version 5.0.x which is in progress, currently under test.
Temporarily, we should disable this defconfig from CI since it is causing issue with open pull requests.
Removes one defconfig from CI.
=> tools/ci: temporarily disable test of esp32-devkitc:nxlooper

arch/arm/src/cmake/gcc.cmake
when libcxx or uClib++ is not selected, we use the default NUTTX cxx
this should fix issue https://github.com/apache/nuttx/issues/16221
bugfix for  https://github.com/apache/nuttx/issues/16221
CI test
=> cmake(bugfix):add default c++ search path

arch/arm/src/cxd56xx/cxd56_gpioint.c
Set level high for unused interrupt trigger to avoid waking up from cold sleeping.
Only for spresense.
=> arch: cxd56xx: Fix bug that causes wake-up by unused gpio interrupt

drivers/segger/CMakeLists.txt, drivers/segger/Kconfig, drivers/segger/Make.defs
update:
CMakeLists.txt
Make.defs
Kconfig
It allows the same version of SystemView target sources to be used for CMake and Make, to avoid discrepancies in the future.
https://github.com/apache/nuttx/pull/16620#issuecomment-3004602498
CI
```
Configuration/Tool: sim/segger
2025-07-22 10:32:20
Cleaning...
Configuring...
[1/1] Normalize sim/segger
``` …
=> drivers/segger: Add a kconfig to override Segger SystemView target sources version

arch/risc-v/src/common/espressif/Kconfig, arch/xtensa/src/common/espressif/Kconfig, boards/risc-v/esp32c6/common/src/esp_board_pcnt.c, boards/risc-v/esp32h2/common/src/esp_board_pcnt.c, boards/xtensa/esp32/common/src/esp32_board_pcnt.c, boards/xtensa/esp32s2/common/src/esp32s2_board_pcnt.c, boards/xtensa/esp32s3/common/src/esp32s3_board_pcnt.c
update:
Kconfig
esp_board_pcnt.c
This PR adds possibility of changing low and high PCNT limits in Kconfig. This could help decrease interrupt load in specific applications. Set the default high limit to 1024 and default low limit to -1024.
Impact on user: YES, new Kconfig options
Testing was performed on ESP32-C6 with `qencoder` defconfig. Output of `tools/configure.sh -l esp32c6-devkitc:qencoder` to check for proper parsing of Kconfig:
```
$ tools/configure.sh -l esp32c6-devkitc:qencoder
Copy files
Select CONFIG_HOST_LINUX=y
Refreshing...
CP: arch/dummy/Kconfig to /home/martin/nuttx-upstream-2/nuttx/arch/dummy/dummy_kconfig
CP: boards/dummy/Kconfig to …
```
=> espressif: PCNT: add high and low limit Kconfig options

.github/workflows/build.yml
CI does not compile everything for a simple modification of the AUTHORS file.
https://github.com/apache/nuttx/pull/16728#issuecomment-3074044118
CI
=> build.yml: Excludes the workflow run if the file is AUTHORS

tools/nxstyle.c
Update nxstyle whitelist to allow MixedCase identifiers used by the Xedge (Barracuda App Server) example.
The following prefixes were added to g_white_prefix[]:
- Ba
- Thread
- LThread
- Http
- Disk
- Xedge
The following exact identifiers were added to g_white_content_list[]:
- baGetUnixTime
- baParseDate
- setDispExit
- xedgeInitDiskIo
- xedgeOpenAUX
- platformInitDiskIo
- ltMgr
- Lt
Developers working with Xedge examples will no longer encounter nxstyle violations
This PR is part of a series and requires the following PRs to be applied for proper testing:
nuttx-apps#3120: https://github.com/apache/nuttx-apps/pull/3120 (Barracuda App Server library)
nuttx#16665: https://github.com/apache/nuttx/pull/16665 (Xedge example implementation)
With both dependency PRs applied, run the following …
=> tools/nxstyle.c: Updating white list to xedge example

arch/xtensa/src/esp32s3/esp32s3_extraheaps.c
esp32s3_extraheaps.c: add a missing include for xtensa_imm_initialize
build fix
i have had an equivalent of this in my local tree for a while without noticing any issues.
=> esp32s3_extraheaps.c: add a missing include for xtensa_imm_initialize

crypto/cryptosoft.c
Initializing aadlen fix uninitialized warning
=> crypto/cryptosoft: fix aadlen used uninitialized warning

Documentation/guides/index.rst, Documentation/guides/nix_flake.rst, flake.lock, flake.nix
This pull request introduces a Nix flake (`flake.nix` and `flake.lock`) to provide a reproducible development shell for NuttX using Nix and flakes.
- Adds a `devShell` with all required build tools and dependencies for NuttX, including CMake, Ninja, GNU Make, clang-tools, ARM toolchain, and other utilities (automake, bison, flex, genromfs, gettext, gperf, kconfig-frontends, libelf, expat, gmp, isl, libmpc, mpfr, ncurses, zlib, kconfiglib).
- Uses `flake-utils` to support multiple platforms.
- Sets up a shell hook to enable CMake compile commands and provide a welcome message.
- Based on `nixpkgs` `nixos-unstable` for up-to-date packages.
**Purpose:**  
This change simplifies onboarding and ensures a consistent build environment across contributors. By pinning dependencies, it reduces …
=> tools/nix: Add Nix flake for reproducible dev environment

boards/arm/stm32h7/nucleo-h743zi/include/board.h, boards/arm/stm32h7/nucleo-h743zi/src/stm32_adc.c
Updates `nucleo-stm32h743zi/include/board.h` and `nucleo-stm32h743zi` to add initialization for ADC2 and more channels and their pin mappings.
This change makes it easier for newcommers to use all ADCs of the board, and hopefully enables better CI.
Tested by building with `cmake` a custom NuttX app that reads /dev/adc0 and /dev/adc1 and sends them through serial for me to view them. Board used is the `nucleo H753ZI` (identical to 743).
Ran `git diff --cached | ./tools/checkpatch.sh -` to check for formatting rules adherence.
=> nucleo-h743zi: Add ADC2 support and expand ADC channel list

Documentation/platforms/arm/stm32f4/boards/stm32f4discovery/index.rst, boards/arm/stm32/stm32f4discovery/src/CMakeLists.txt, boards/arm/stm32/stm32f4discovery/src/Make.defs, boards/arm/stm32/stm32f4discovery/src/stm32_bringup.c, boards/arm/stm32/stm32f4discovery/src/stm32_hx711.c, boards/arm/stm32/stm32f4discovery/src/stm32f4discovery.h
This commit adds support for the HX711 ADC in the STM32F4-Discovery board and updates the board documentation accordingly.
Is new feature added? Is existing feature changed? Yes, added HX711 support to STM32F4-Discovery .
Impact on user (will user need to adapt to change)? Yes, users will be able to use HX711 on STM32F4-Discovery.
Impact on build (will build process change)? No
Impact on hardware (will arch(s) / board(s) / driver(s) change)? Yes, ARM/STM32F4-Discovery 
Impact on documentation (is update required / provided)? Yes, STM32F4-Discovery  was updated.
Impact on security (any sort of implications)? No.
Impact on compatibility (backward/forward/interoperability)? No
I confirm that changes are verified on the local setup and work as intended:
Build Host(s): OS: Ubuntu 24.04, CPU: …
=> boards/arm/stm32f4discovery: Add support to HX711 ADC

arch/arm/src/imxrt/CMakeLists.txt, boards/arm/imxrt/arcx-socket-grid/CMakeLists.txt, boards/arm/imxrt/arcx-socket-grid/src/CMakeLists.txt
CMake added board ARCX Socket Grid
Impact on user: This PR adds ARCX Socket Grid board with CMake build
Impact on build: This PR Implement CMake build for the i.MX RT series
Locally and on GitHub
Locally
=> arm: CMake build for the i.MX RT series implemented.

fs/vfs/fs_rename.c
* Recurrency is removed from filesystem directory rename.
* Fixes use after free in buffer that was used as output and argument.
* Patch provided by @richyliu.
fs/vfs bug fix of possible use after free.
@cederom: esp32c6-xiao:usbnsh.
@richyliu: STM32 Nucleo H743ZI + FTP.
Reviewers please double check locally if the issue is reproducible and there are no side effects after patch :-)
=> fs/vfs/fs_rename: fix directory move operation.

drivers/pci/pci_epc.c, drivers/pci/pci_epf.c, drivers/pci/pci_qemu_epc.c, include/nuttx/pci/pci_epc.h
add pci epc dma heap,The PCI inbound address space and the CPU cache need to maintain cache coherence.
and runtime logs from before and after …
=> drivers/pci: epc add dma heap

arch/arm/src/stm32h5/stm32_adc.c, arch/arm/src/stm32h5/stm32_dma.c, arch/arm/src/stm32h5/stm32_dma.h
This patch introduces optional double-buffered DMA support for STM32H5 ADC drivers when operating in circular mode. When `CONFIG_STM32H5_ADCx_DMA_CFG` is enabled, the DMA buffer size is doubled and half-transfer interrupts are enabled to allow the CPU to process one half of the buffer while DMA fills the other.
In one-shot mode (non-circular), DMA and ADC are restarted after each complete transfer using the new helper `adc_restart_dma()`. This avoids code duplication and ensures correctness in single-shot conversions.
The DMA configuration has been improved:
- `ntransfers` now accounts for `circular` mode buffer doubling.
- Interrupt flags are now unconditionally cleared to prevent re-entry or missed interrupts.
- Removed legacy circular DMA logic using `circ_addr_1`, which was unused and …
=> arch/arm/stm32h5: Use double-buffer for ADC DMA in Circular Mode

arch/arm/src/armv6-m/arm_sigdeliver.c, arch/arm/src/armv7-a/arm_sigdeliver.c, arch/arm/src/armv7-m/arm_sigdeliver.c, arch/arm/src/armv7-r/arm_sigdeliver.c, arch/arm/src/armv8-m/arm_sigdeliver.c, arch/arm/src/armv8-r/arm_sigdeliver.c, arch/arm64/src/common/arm64_sigdeliver.c, arch/risc-v/src/common/riscv_sigdeliver.c, arch/sparc/src/sparc_v8/sparc_v8_sigdeliver.c
I just realized that the same issue, which just happened to manifest on me on xtensa, is there for other platforms as well.
Even though I haven't experienced crashes on these platforms, I believe that it is just pure luck, and this same race
should be fixed also for these. I boldly made the same correction only based on code inspection/review, I don't have a change to really test it on all of these architectures.
So, this fixes the same issue for other targets, which was already fixed for xtensa in commit 50d94863.
After the signals have been delivered, the local irqs need to be disabled until the context switch. But just calling leave_critical_section(regs[xx]) will enable them if they were enabled in the context.
Impacts the signal delivery, fixing a possible full system crash in case …
=> arch/*/*_sigdeliver.c: Fix a race condition is signal delivery for SMP

Documentation/components/drivers/special/sensors.rst, Documentation/components/drivers/special/sensors/gnss_lowerhalf.rst, Documentation/components/drivers/special/sensors/sensors_uorb.rst
The GNSS lower-half driver for facilitating the implementation of uORB GPS/GNSS device drivers was lacking documentation. Contributors cannot be expected to implement their drivers correctly with this framework if it is undocumented. This change adds documentation for how to use the lower-half GNSS driver, provides an example and also adds a notice for users to use this framework if implementing their own GNSS driver.
This was mentioned in PR #16605.
Only impacts the documentation. Provides information on how to use the lower-half GNSS driver so that contributors can now be expected to use this framework. Also indicates that GNSS drivers should be implemented with this lower-half.
Closes #16702.
Performed a local documentation build and viewed the generated HTML in my browser to confirm …
=> docs/gnss_lowerhalf: Documentation for the lower-half GNSS uORB driver

Documentation/applications/testing/unity/index.rst
The documentation for using the Unity testing framework previously just linked to the official Unity website. In using Unity, I noticed there were much more extensive docs on the actual GitHub page. This PR includes references to those docs and also provides a short-winded explanation of how to make a Unity test suite on NuttX.
Only impacts the documentation for Unity by making it easier for users to get ststarted with it on NuttX.
Performed a local build and verified that the HTML rendered correctly in my browser.
=> docs/unity: Improved documentation for using Unity testing framework

drivers/syslog/syslog_channel.c
Use typedef `syslog_channel_t` instead of `struct syslog_channel_s`. The error occurred if `CONFIG_SYSLOG_CDCACM` was set.
```console
CC:  dirent/lib_telldir.c syslog/syslog_channel.c:151:3: error: initialization of ‘int (*)(const syslog_channel_t *, int)’ {aka ‘int (*)(const struct syslog_channel_s *, int)’} from incompatible pointer type ‘int (*)(struct syslog_channel_s *, int)’ [-Wincompatible-pointer-types]
151 |   syslog_cdcacm_putc,
|   ^~~~~~~~~~~~~~~~~~
syslog/syslog_channel.c:151:3: note: (near initialization for ‘g_cdcacm_channel_ops.sc_putc’)
syslog/syslog_channel.c:152:3: error: initialization of ‘int (*)(const syslog_channel_t *, int)’ {aka ‘int (*)(const struct syslog_channel_s *, int)’} from incompatible pointer type ‘int (*)(struct syslog_channel_s *, int)’ …
```
=> drivers/syslog/syslog_channel.c: fix incompatible-pointer-types compile errors

arch/arm/src/stm32h7/CMakeLists.txt, arch/arm/src/stm32h7/Kconfig, arch/arm/src/stm32h7/stm32_capture.c, arch/arm/src/stm32h7/stm32_capture.h, arch/arm/src/stm32h7/stm32_capture_lowerhalf.c, boards/arm/stm32h7/nucleo-h743zi/include/board.h, boards/arm/stm32h7/nucleo-h743zi/src/stm32_bringup.c, drivers/timers/capture.c
This commit introduces a timer capture driver for the STM32H7 series ported from the STM32 F series.
The current implementation is based on a driver originally for PWM input, and as such, it calculates duty cycle and frequency. It is also limited to a single capture channel per timer.
This serves as a foundation for future development of more comprehensive input capture capabilities on STM32H7 platforms.
The main changes include:
- A new generic timer capture driver for STM32H7.
- A lower-half driver to integrate with the NuttX capture subsystem.
- Kconfig options to enable and configure capture for various timers.
- Pin definitions for TIM1-4 capture inputs on the nucleo-h743zi.
- An update to `cap_register_multiple` to handle multiple device registration.
- An update to `stm32_bringup` …
=> arch/arm/stm32h7: Port timer capture driver from stm32

drivers/sensors/Kconfig, drivers/sensors/l86xxx_uorb.c
Fix mutex locking bugs and improve performance. Fix interval no longer set statically since it is available via `set_interval` uORB function. Activation/deactivation no longer triggers standby/hotstart since this functionality was very unstable.
Makes the GPS driver much more reliable, but removes having standby mode when sensor is deactivated. In fairness, this feature didn't work properly and caused failures.
Also removes build system option for fix interval, which is still an available feature, just cannot be configured at compile time. This was removed because waiting for the ACK at driver registration slows down boot time significantly.
Tested on STM32H743 based board, verified in console with `uorb_listener` and also via custom telemetry application.
=> drivers/l86xxx: Mutex fixes & performance improvements

drivers/sensors/Kconfig, drivers/sensors/lis2mdl_uorb.c, drivers/sensors/lsm6dso32_uorb.c
Updates internal buffer size for two high-ODR sensors.
Makes these drivers usable at a high ODR. Only affects these two drivers by increasing buffer size.
Verified compiling with these sensors still works.
=> Increase buffer sizes for uORB devices

fs/vfs/fs_lock.c
Sometimes we need to `flock` a driver node, which we can support easily.
Allow `flock` to be used on driver node.
With https://github.com/apache/nuttx-apps/pull/3156 , which uses `flock` on uinput.
=> fs/lock: Allow driver lock

Documentation/platforms/arm/rp2040/boards/raspberrypi-pico-w/index.rst, Documentation/platforms/arm/rp2040/boards/raspberrypi-pico/index.rst, Documentation/platforms/arm/rp2040/index.rst, Documentation/platforms/arm/rp23xx/boards/raspberrypi-pico-2/index.rst, Documentation/platforms/arm/rp23xx/boards/xiao-rp2350/index.rst, Documentation/platforms/arm/rp23xx/index.rst, Documentation/platforms/risc-v/rp23xx-rv/boards/raspberrypi-pico-2-rv/index.rst, Documentation/platforms/risc-v/rp23xx-rv/index.rst
RP2040, RP2350, Pico, Pico W, Pico 2 and Pico 2 W are all produced by [Raspberry Pi](https://www.raspberrypi.com) which is [a separate organisation](https://www.raspberrypi.com/news/new-raspberry-pi-website/) from the [Raspberry Pi Foundation](https://www.raspberrypi.org).
This PR updates the NuttX documentation to change "the Raspberry Pi Foundation" to "Raspberry Pi".
It also removes "RTC" from the list of peripherals not supported by `raspberrypi-pico-2` and `raspberrypi-pico-2-rv`, as the RP2350 doesn't contain an RTC. (This was probably just a copy'n'paste mistake from the RP2040 boards?)
No testing was performed, as this only makes small wording tweaks to the …
=> doc: Small Raspberry Pi fixes

arch/arm/src/rp2040/Kconfig, arch/arm/src/rp2040/hardware/rp2040_adc.h, arch/arm/src/rp2040/hardware/rp2040_io_bank0.h, boards/arm/rp2040/common/src/rp2040_common_bringup.c
The strings "RP**C**2040" and "RP2040_IO_BANK0_GPIO**0**" were being used, probably by mistake, in some macros. In the latter case, the affected macros were not resolving correctly at all.
Users that changed `RP2040_ADC_*` options in their configs will face a conflict and, I suppose, will probably need to update their respective entries.
These changes were tested on a Linux host, targeting a custom Cortex-M0+ (RP2040) board using NuttX v12.8.0 as the baseline. They were then manually ported to the current master branch.
=> arch/arm/rp2040: Fix typos in ADC and GPIO macro names

crypto/hmac.c, include/crypto/hmac.h
In the crypto implementations, "hmac" was mistyped as "hmca". This was breaking the linkage to the respective [prototype functions](https://github.com/apache/nuttx/blob/25fe6b07494a3fc5291c0c170637517aa2996954/include/crypto/hmac.h#L51) in the headers. Also, a couple of necessary includes were missing.
Built-in HMAC crypto functions will become usable again.
These changes were tested on a Linux host, targeting a custom Cortex-M0+ (RP2040) board using NuttX v12.8.0 as the baseline. They were then manually ported to the current master branch.
=> crypto/hmac: Fix typo in function implementation names

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_coremmc.c, arch/risc-v/src/mpfs/mpfs_emmcsd.c
Fix several issues in mpfs_coremmc:
- Driver polls data lines ready in busyloop when command is being send. This prevents upper lever mmcsd driver to poll card busy status prior next activity. This causes high cpu load.
- Fix check of incorrect fifo depth bits of VR register
- Enable 4bit bus width support
- Define CONFIG_MPFS_FPGA_FIC0_CLK_FREQ for FPGA FIC0 clock freq. Default freq to 125MHz.
Fix for mpfs_emmcsd:
- Ignore unsupported WRCOMPLETE event in case CONFIG_MMCSD_SDIOWAIT_WRCOMPLETE is enabled for coremmc.
mpfs_coremmc fixes improves data transfer speed and fixes high cpu load issue.
mpfs_emmcsd fix solves data transfer performance issue in case CONFIG_MMCSD_SDIOWAIT_WRCOMPLETE feature flag is enabled for coremmc.
Tested with custom MPFS hardware
=> arch/risc-v/src/mpfs: fixes for coremmc and emmcsd

boards/risc-v/esp32c3/common/src/esp_board_spiflash.c, boards/risc-v/esp32c6/common/src/esp_board_spiflash.c, boards/risc-v/esp32h2/common/src/esp_board_spiflash.c, boards/xtensa/esp32/common/src/esp32_board_spiflash.c, boards/xtensa/esp32s2/common/src/esp32s2_board_spiflash.c, boards/xtensa/esp32s3/common/src/esp32s3_board_spiflash.c
Fixing wrong deletion for creating raw mtd partition.
* boards/xtensa: Revert mdtblock initialization for esp32[-|-s2|-s3]
boards/risc-v: Revert mdtblock initialization for Xtensa based Espressif devices
* boards/risc-v: Revert mdtblock initialization for esp32[-c3|-c6|-h2]
boards/risc-v: Revert mdtblock initialization for risc-v based Espressif devices
Impact on user: Yes, reverting back mtdblock registiration for needed applications.
Impact on hardware: Yes, mtdblock char driver is reverting back
=> board/esp: Revert mtdblock registeration

arch/xtensa/src/esp32s2/hal.mk
* arch/xtensa/esp32s2: Remove duplicated lines to fix warning
Remove duplicated lines to fix build warning for esp32s2
Impact on user: Yes, warning during build fixed
Impact on build: Yes, warning during build fixed
`esp32s2-saola-1:nsh` config used to test it. Here is the command:
```
make distclean && ./tools/configure.sh esp32s2-saola-1:nsh && make -j
```
Just build commands applied. This fix related to a build warning.
These warnings should not appear on build logs.
```
Makefile:145: target 'chip/esp-hal-3rdparty/components/efuse/src/esp_efuse_utility.o' given more than once in the same rule
Makefile:145: target 'chip/esp-hal-3rdparty/components/efuse/src/esp_efuse_api.o' given more …
```
=> arch/xtensa/esp32s2: Remove duplicated lines to fix warning

arch/risc-v/src/mpfs/mpfs_usb.c
Currently the irq handler checks many reserved bits, which is a waste of resources:
1. pending_rx_ep bit 0 is reserved (always 0)
2. pending_rx_ep and pending_tx_ep have only bits 1, 2, 3 and 4 defined, no need to scan MPFS_USB_NENDPOINTS (9) bits as the rest are reserved
Fix this by checking only the relevant bits.
Only mpfs usb driver, no functional impact, just performance improvement.
Tested on mpfs250t based HW using USB MSC and TTYACM. This patch has actually been in use for a long time in many device configurations at TII.
=> risc-v/mpfs: usb: don't try nonexistent ep int flags

drivers/pci/Kconfig, drivers/pci/pci_epf_test.c
pci: epf test default a function
=> pci: epf test default a function

arch/risc-v/src/rp23xx-rv/rp23xx_rom.h, boards/risc-v/rp23xx-rv/common/src/rp23xx_reset.c
Update board reset with BOOTROM functions calls
- normal reboot
- reboot to bootloader
normal reboot and reboot bootloader now possible from nsh
=> boards/risc-v/rp23xx-rv/common: update board reset via BOOTROM functions

arch/arm/src/common/Toolchain.defs, arch/arm64/src/Toolchain.defs, arch/avr/src/avr/Toolchain.defs, arch/avr/src/avr32/Toolchain.defs, arch/mips/src/mips32/Toolchain.defs, arch/misoc/src/lm32/Toolchain.defs, arch/misoc/src/minerva/Toolchain.defs, arch/or1k/src/mor1kx/Toolchain.defs, arch/risc-v/src/common/Toolchain.defs, arch/sparc/src/sparc_v8/Toolchain.defs, arch/tricore/src/common/ToolchainGnuc.defs, arch/tricore/src/common/ToolchainTasking.defs, arch/x86/src/common/Toolchain.defs, arch/x86_64/src/common/Toolchain.defs, arch/xtensa/src/lx6/Toolchain.defs, arch/xtensa/src/lx7/Toolchain.defs, arch/z80/src/ez80/Toolchain.defs, arch/z80/src/z180/Toolchain.defs, arch/z80/src/z80/Toolchain.defs, boards/renesas/rx65n/rx65n-grrose/scripts/Make.defs, boards/renesas/rx65n/rx65n-rsk1mb/scripts/Make.defs, boards/renesas/rx65n/rx65n-rsk2mb/scripts/Make.defs, boards/renesas/rx65n/rx65n/scripts/Make.defs, boards/renesas/sh1/us7032evb1/scripts/Make.defs
Use this command to extract archives.
Not all architectures are modified, only those commands I know or could be logically deducted from the rest were added.
A useful multiplatform variable to extract the archives. I plan to use it in this pull request: https://github.com/apache/nuttx-apps/pull/3154, where I need to unpack all archives to create one big archive, containing all .o files.
I still need to add cmake support, and support for other architectures. The problem is I do not know the syntax of all the used commands, especially those proprietary ones for rare architectures.
Please let me know whether you agree with the name of this variable.
=> Make/Toolchain.defs: add the AR_EXTRACT command

Documentation/platforms/arm/rp2040/index.rst, Documentation/platforms/arm/rp23xx/boards/raspberrypi-pico-2/index.rst, arch/arm/src/rp2040/boot2/Make.defs
Version 2.2.0 of the pico-sdk seems to have unified some RP2040 and RP2350 headers under a new path. Now both the old and the new paths are searched during compilation.
The commands in the documentation have been updated and a tip about not necessarily having to compile picotool manually has been added. The RP2040 has SDK instructions in its main arch page, while the RP2350 has them in a board page; due to the smaller number of RP230 boards currently documented, this may not be an issue (yet).
It will now be possible to compile RP2040 binaries with newer pico-sdk versions (namely 2.2.0). Compatibility with version 2.1.1 has been preserved.
These changes were tested on a Linux host, targeting a custom RP2040 board using today's NuttX master as the baseline. The pico-sdk versions tested …
=> arch/arm/rp2040: Support pico-sdk 2.2.0

drivers/ioexpander/CMakeLists.txt
Add:
iC-JX driver #11590
ISO1H812G driver #10426
ISO1I813T driver #10435
PCA9557 driver #16042
mcp23008 driver #10532
Impact on build: This PR Aligned Cmake with Make
locally
=> drivers/ioexpander/CMakeLists.txt: Aligned Cmake with Make

Documentation/applications/examples/xedge_demo/index.rst, Documentation/platforms/arm64/qemu/boards/qemu-armv8a/index.rst
Fixed RST (reStructuredText) formatting issues in xedge_demo documentation 
Fixes broken formatting that was affecting the visual presentation of the docs
Verified if RST syntax is valid and follows formatting rules
```bash
~/nuttxspace/nuttx$ ./tools/checkpatch.sh -g HEAD~...HEAD
```
=> Documentation/xedge_demo: Fix RST formatting issues

arch/arm64/src/bcm2711/CMakeLists.txt, boards/arm64/bcm2711/raspberrypi-4b/CMakeLists.txt, boards/arm64/bcm2711/raspberrypi-4b/src/CMakeLists.txt
closed previous pull request and just reopen this new pull request
Add:
arch/arm64/src/bcm2711/CMakeLists.txt
boards/arm64/bcm2711/raspberrypi-4b/CMakeLists.txt 
boards/arm64/bcm2711/raspberrypi-4b/src/CMakeLists.txt
add cmake build support for bcm2711 chip and raspberrypi-4b board
people can enjoy cmake build for raspberrypi-4b board
**cmake build pass log:**
```
[ 97%] Building C object libs/libc/CMakeFiles/c.dir/wchar/lib_mbsrtowcs.c.obj
[ 97%] Building C object libs/libc/CMakeFiles/c.dir/wchar/lib_mbsinit.c.obj
[ 97%] Building C object libs/libc/CMakeFiles/c.dir/wchar/lib_wcsrtombs.c.obj
[ 97%] Building C object libs/libc/CMakeFiles/c.dir/wchar/lib_wcscpy.c.obj
[ 97%] …
```
=> arch: Add Cmake build support for raspberrypi-4b board & bcm2711 chip

arch/arm/include/arm/barriers.h
This commit adds the missing `barriers.h` for arm.
Change-Id: Ia8c33ccbac47830ac179108a2d59fd75f5ede400
In the arch/arm/include/barriers.h file, there is the following
statement:
41 # include <arch/arm/barriers.h>
But arch/arm/barriers.h file does not actually exist, so this commit
has added an arch/arm/barriers.h file
NA
NA
=> arch/arm: Add missing barriers.h

arch/tricore/include/arch.h, arch/tricore/include/irq.h, include/nuttx/compiler.h
include/nuttx/compiler.h:
fix nooptimiziation_function definition problem for tricore gnu compiler
arch/tricore:
move tricore_csa2addr and tricore_addr2csa definition from include/arch.h to include/irq.h to fix build error
change nooptimiziation_function definition in include/nuttx/compiler.h and relocate tricore_csa2addr and tricore_addr2csa definition in tricore/arch to fix tc397 bord build error
fix tc397 bord build error
**before updating include/nuttx/compiler.h:**
```
[  5%] Building C object fs/CMakeFiles/fs.dir/procfs/fs_procfstcbinfo.c.obj
cd /home/lixiang/repos/nuttxspace/output/fs && /home/lixiang/repos/avatar_master_linux/prebuilts/linux/gcc/tricore/bin/tricore-elf-g …
```
=> include/nuttx/compiler.h:

arch/xtensa/src/esp32/esp32_partition.c
esp32/esp32_partition.c: based on the latest revision, in the ESP32 compilation environment, uint32_t is defined as long unsigned int (i.e., unsigned long)
New Feature/Change: No
User Impact: No
Hardware Impact: No
Security: No
Compatibility: Backward-compatible; no breaking changes.
```
chip/esp32_partition.c:348:18: warning: format '%d' expects argument of type 'int', but argument 3 has type 'uint32_t' {aka 'long unsigned int'} [-Wformat=]
348 |             ferr("ERROR: Failed to erase OTA%d data error=%d\n", sec, ret);
|                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~
|                                                                  |
| …
```
=> arch/xtensa/esp32: fix some compilation warnings

arch/tricore/Kconfig, arch/tricore/src/common/tricore_irq.c
Add up_trigger_irq in arch/tricore/src/common/tricore_irq.c
Select ARCH_HAVE_IRQTRIGGER in config ARCH_TC3XX
add up_trigger_irq for tricore arch
tricore arch will have up_trigger_irq 
**build pass:**
[ 99%] Linking C executable nuttx
/home/lixiang/downloads/cmake-3.27.1-linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/nuttx.dir/link.txt --verbose=1
/home/lixiang/repos/avatar_master_linux/prebuilts/linux/gcc/tricore/bin/tricore-elf-gcc -mcpu=tc39xx -mtc162 -I/home/lixiang/repos/nuttxspace/nuttx/arch/tricore/src/tc3xx/tc397/Libraries/iLLD/TC39B/Tricore/Cpu/Std -I/home/lixiang/repos/nuttxspace/nuttx/arch/tricore/src/tc3xx/tc397/Libraries/Infra/Platform …
=> arch/tricore: add up_trigger_irq

drivers/can/Kconfig, drivers/can/kvaser_pci.c
Configure number of passes in interrupt handler logic to avoid losing RX frames in QEMU environment.
Fixes the problem with lost frames when flooding the CAN network with messages.
qemu-x86_64
=> drivers/can/kvaser_pci: configure number of passes in interrupt handler

arch/xtensa/src/esp32/esp32_spiflash.c, arch/xtensa/src/esp32s3/esp32s3_spiflash.c
This fixes a bug where esp32_spiflash driver starts on a wrong CPU, before it's affinity gets set.
This solution first creates the thread, then sets the affinity and finally activates the task.
Only for esp32 spiflash
Tested on qemu that the tasks start on correct CPUs
=> arch/xtensa/esp32,esp32s3: Start the "spiflash_op" thread with corret affinity

arch/arm64/src/imx9/imx9_lpi2c.c
imx9_lpi2c_reset didn't quite work. It tried to toggle scl line as GPIO, but the line was not even muxed properly.
Instead, set the bus to relaxed mode, and drive address 0 to the bus. This toggles the clock, and also generates start and stop sequences on the bus.
"Relaxed mode" is a new feature on the LPI2C block used in imx93.
Only imx9 lpspi. Improves i2c bus error recovery.
Tested on imx93 board with a broken i2c led driver device which causes bus to get stuck occasionally.
=> arch/arm64/src/imx9/imx9_lpi2c.c: Fix bus reset

arch/arm/src/stm32f7/stm32_ethernet.c
Fix an "unused variable" compiler warning when CONFIG_STM32F7_AUTONEG is not set
No functional impact, enables building with CONFIG_STM32F7_AUTONEG=n and -Werr.
Tested building on stm32f7 (pixhawk 5x) board.
=> arch/arm/src/stm32f7/stm32_ethernet.c: Fix "unused variable" warning

arch/arm/src/samv7/sam_emac.c
The following warning occurred if `ARCH_CHIP_PIC32CZCA70` option was selected. The variable is not used in case of PIC32CZ CA70 series.
```
CC:  task/task_getgroup.c chip/sam_emac.c: In function ‘sam_emac_initialize’: chip/sam_emac.c:4758:12: warning: unused variable ‘regval’ [-Wunused-variable]
4758 |   uint32_t regval;
|
```
SAMv7 code only. Fixes compile warnings.
Build passes without warnings.
=> arch/arm/src/samv7/sam_emac.c: fix compile warning

drivers/net/ksz9477.c, drivers/net/ksz9477_reg.h
This improves the functionality of the ksz9477 i2c controlled ethernet switch driver, by implementing manufacturer's recommended errata workarounds.
Impacts only using ksz9477. Fixes connection issues and random failures after boot/initialization.
Tested on a custom hardware, where ksz9477 is initialized by NuttX via I2C on an MFPS250T SoC, and connects to several etherenet devices on the same board.
=> Drivers net ksz9477 fixes

net/can/can_callback.c, net/can/can_recvmsg.c
These are cherry-picks from TII repositories. The patches simplify readahead queue handling and fix
an error in buffer length calculation in can_callback when CONFIG_NET_TIMESTAMP is enabled.
Reduces complexity a bit, fixes a bug in net timestamp handling in socketcan.
These patches have been tested with UAVCAN library, using Zubax Myxa ESCs (CAN motor controllers), together with MPFS platform.
=> net/can: fixes and cleanups

boards/arm/imxrt/imxrt1060-evk/CMakeLists.txt, boards/arm/imxrt/imxrt1060-evk/src/CMakeLists.txt, boards/arm/imxrt/imxrt1064-evk/CMakeLists.txt, boards/arm/imxrt/imxrt1064-evk/src/CMakeLists.txt, boards/arm/imxrt/imxrt1170-evk/CMakeLists.txt, boards/arm/imxrt/imxrt1170-evk/src/CMakeLists.txt
Added CMake build for boards:
- imxrt1060-evk
- imxrt1064-evk
- imxrt1170-evk
Impact on user: This PR adds imxrt1060-evk, imxrt1064-evk, and imxrt1170-evk boards with CMake build
Locally
**imxrt1060-evk**
```
D:\nuttximxrt\nuttx>cmake -B build -DBOARD_CONFIG=imxrt1060-evk:nsh -GNinja
--   CMake:  3.31.5
--   Ninja:  1.12.1
--   Board:  imxrt1060-evk
--   Config: nsh
--   Appdir: D:/nuttximxrt/apps
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- The ASM compiler identification is GNU
-- Found assembler: …
```
=> boards/arm/imxrt: CMake added imxrt1060-evk imxrt1064-evk imxrt1170-evk boards

boards/arm/imxrt/imxrt1020-evk/CMakeLists.txt, boards/arm/imxrt/imxrt1020-evk/src/CMakeLists.txt, boards/arm/imxrt/imxrt1050-evk/CMakeLists.txt, boards/arm/imxrt/imxrt1050-evk/src/CMakeLists.txt
Added CMake build for boards:
imxrt1020-evk
imxrt1050-evk
Impact on user: This PR adds imxrt1020-evk and imxrt1050-evk boards with CMake build
Locally
**imxrt1020-evk**
```
D:\nuttximxrt\nuttx>cmake -B build -DBOARD_CONFIG=imxrt1020-evk:nsh -GNinja
--   CMake:  3.31.5
--   Ninja:  1.12.1
--   Board:  imxrt1020-evk
--   Config: nsh
--   Appdir: D:/nuttximxrt/apps
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- The ASM compiler identification is GNU
-- Found assembler: …
```
=> boards/arm/imxrt: CMake added imxrt1020-evk imxrt1050-evk boards

drivers/ioexpander/CMakeLists.txt, drivers/ioexpander/Kconfig, drivers/ioexpander/Make.defs, drivers/ioexpander/aw9523b.c, drivers/ioexpander/aw9523b.h, include/nuttx/ioexpander/aw9523b.h
This is an I2C driver for the Awinic AW9523B I/O expander. As well as the supporting usual digital I/Os, this device features the ability to drive LEDs directly, and can control the drive current to each LED individually. The driver was derived from the PCA9555 driver, provides all the standard interfaces of an i/o expander driver. It also features support for the special features of the AW9523B through pin direction IOEXPANDER_DIRECTION_OUT_LED and IOEXPANDER_OPTION_NONGENERIC with AW9523B_OPTION_* options.
The driver has a number of configurable features including interrupt handling and a shadow register mode based on the PCA9555 driver, plus new LED/dimming support.
Adds configurable support for the AW9523B. It shouldn't affect any existing code.
Testing was done using a custom ESP32S3 …
=> drivers/ioexpander/aw9523b: New driver for AW9523B i/o expander

tools/checkpatch.sh
check git commit format with CI:
1. line length less than 80 for commit title
2. affected subsystem (detecting colon in commit title ":")
3. Signed-off-by line
4. no [VELAPLATO-*|WIP:] string in commit body
Reference: https://github.com/apache/nuttx/issues/16908
automation of boring activities
CI on private fork
examples: 
https://github.com/raiden00pl/nuttx/actions/runs/17235852791/job/48900430219
https://github.com/raiden00pl/nuttx/actions/runs/17233782590/job/48893753448
https://github.com/raiden00pl/nuttx/actions/runs/17237377138/job/48905319722
=> tools/checkpatch.sh: check git commit format

include/nuttx/semaphore.h, libs/libc/semaphore/sem_init.c
Allow user to init semaphore value to negative value, this is needed in some use cases
Update nxsem_init api param type to allow a semaphore to be initialized to a negative value
Semaphore can be initialized to a negative value
N/A
=> libs/libc/semaphore:  allow nxsem_init to negative value

Documentation/applications/boot/nxboot/index.rst
Fixes incorrect `nxboot_get_confirm` function description (it was a copy paste from `nxboot_confirm` function).
Documentation fix.
=> Documentation/applications/boot/nxboot: fix incorrect fnc description

Documentation/reference/os/events.rst, include/nuttx/event.h, sched/event/event.h, sched/event/event_wait.c
There are cases that user do not want the event wait object to be allocated automatically
in the stack as a temporary variable in nxevent_tickwait, since multiple threads will
access the variable, they want to allocate the object as a global variable for safety
control or easy debug. To solve this problem, this patch updated the nvevent_tickwait
implementaion to give user the chance to  pass the global wait object to it.
sched/event/event_wait.c:
add one more nxevent_wait_t *wait param to nvevent_tickwait.
nxevent_trywait create a temprary wait variable and then pass it to nxevent_wait_t.
nxevent_wait create a temprary wait variable and then pass it to nxevent_wait_t.
There are …
=> sched/event: move the temporary even_wait variable out of nxevent_tickwait

Documentation/reference/user/05_counting_semaphore.rst, include/nuttx/semaphore.h, include/semaphore.h, libs/libc/semaphore/CMakeLists.txt, libs/libc/semaphore/Make.defs, libs/libc/semaphore/sem_init.c, libs/libc/semaphore/sem_setmaxvalue.c, sched/Kconfig, sched/semaphore/sem_post.c
Curernt implementation default semaphore max allowed value to SEM_VALUE_MAX.
In some cases, user may want to change this, so provide a function to do this: sem_setmaxvalue
In some cases, user may want to change semaphore max allowed value, so provide a function to do this: sem_setmaxvalue
New api added, no impact to current functions 
**Switch on new config**
**ostest PASS**
=> sched/semaphore: add support to customize semaphore max allowed value

tools/configure.sh
Add include patch to configure.sh when processing deconfig file to keep alignment with
CmakeLists.txt
Align tools/configure.sh with  CmakeLists.txt when processing the defconfig
Built scripts update, improving processing of defconfig,  no impact to other parts
N/A
=> tools/configure.sh: align tools/configure.sh with CmakeLists.txt

include/nuttx/event.h, sched/event/event_init.c, sched/event/event_post.c, sched/event/event_wait.c
sched: remove csection in event
We hope to replace the large lock with a small lock to improve concurrency performance.
ostest
=> sched: remove csection in event

arch/tricore/src/common/tricore_doirq.c
`struct tcb_s **running_task = &g_running_tasks[this_cpu()];`
was updated to
`struct tcb_s *running_task = g_running_tasks[this_cpu()];`
```
if (*running_task != NULL)
{
( *running_task)->xcp.regs = regs;
}
```
was updated to
```
if (running_task != NULL)
{
running_task->xcp.regs = regs;
}
```
Remove redundant and misleading pointer usage in tricore_doirq()
Fix typo issue in arch tricore implementation, no impact to other nuttx parts
**a2g-tc397-5v-tft board ostest passed**
=> arch/tricore: remove redundant and misleading pointer usage in tricore_doirq()

Documentation/reference/os/events.rst, include/nuttx/event.h, sched/event/CMakeLists.txt, sched/event/Make.defs, sched/event/event_clear.c
Add nxevent_clear to clear event mask to an event object.
new event api is added: nxevent_clear, which can be used to manually clear event mask
A new event module api is added.
**add event clear test**
**Enable event:**
**ostest pass**
=> sched/event: add nxevent_clear api

Documentation/reference/os/events.rst, include/nuttx/event.h, sched/event/CMakeLists.txt, sched/event/Make.defs, sched/event/event_getmask.c
In certain cases, when the event-wait thread is awakened,
it needs to know the specific mask bit that triggered it,
so that it can branch to different paths accordingly.
This patch introduces the nxevent_getmask function to address this requirement.
Add a new function: `nxevent_getmask() `to address requirement that user may need to know 
the specific mask bit that triggered it, so that it can branch to different paths accordingly.
A new function is added, no impact to any other parts
**add test cases**
**ostest passed on a2g-tc397-5v-tft**
=> sched/event: add nxevent_getmask api

libs/libc/stdio/lib_fclose.c
Stream pointer is provided by user side code. Passing an invalid pointer, for example an already closed stream, to fclose would cause heap corruption and in CONFIG_BUILD_FLAT a full system crash.
This validates the passed stream pointer by checking that it exists in the streams list.
Impacts all platforms, prevents crash in case an invalid argument is passed.
Tested with real HW on MPFS and IMX93 platforms, with qemu on rv-virt:nsh (ostest)
=> libc/fclose: Validate the user provided stream pointer

arch/tricore/src/cmake/ToolchainTasking.cmake, arch/tricore/src/common/ToolchainTasking.defs
Add "add_link_options(--no-default-libraries)" ToolchainTasking.cmake
Add "LDFLAGS += --no-default-libraries" in ToolchainTasking.defs
Update tasking compiler linker option to avoid linking compiler lib in default
tricore arch compiling issue fix, no impact to other parts
**enable tasking compiler on board a2g-tc397-5v-tft **
**before this fix patch**
**after this fix patch**
**ostest passed**
=> arch/tricore: fix tasking compiler linking error

drivers/syslog/syslog_write.c
In current implementation, when do syslog_write(), there may
be more than one channel, the syslog will iterate each channel,
but only return the bytes writen through the last channel, the
better way should be returning the maximum bytes writen
through one channel.
Let syslog_write() return the maximum bytes writen through a channel, when have multiple syslog channels
Fix syslog_write() return value issue when there are multiple syslog channels
**defconfig for fvp-armv8r-aarch32 board**
**ostest passed**
=> drivers/syslog: let syslog_write() return the maximum bytes writen through a channel

arch/tricore/src/common/tricore_checkstack.c
before:
|   start = (alloc + 3) & ~3;
|   end   = (alloc + size) & ~3;
after:
|   start = STACK_ALIGN_UP((uintptr_t)alloc);
|   end   = STACK_ALIGN_DOWN((uintptr_t)alloc + size);
tricore arch code implemention optimization
tricore arch code optimization，no impact to other nuttx parts
**ostest passed on a2g-tc397-5v-tft board:**
=> arch/tricore: remove magic number in tricore_checkstack.c

arch/arm/src/common/arm_usestack.c, arch/tricore/src/common/tricore_usestack.c
The stack alignment operation in tricore and arm porting
only aligns the size of the stack, forget to align the start addr
of the stack, this patch fixes it.
fix the stack alignment bugs in arm/tricore arch implementation.
arm and tricore arch implementation update, no impact to other parts
**ostest passed for a2g-tc397-5v-tft**
**ostest passed for fvp-armv8r-aarch32**
=> arch: fix stack alignment bug for arm and tricore arch

arch/arm/src/stm32h7/CMakeLists.txt
This PR adds conditional compilation support for the STM32H7 LTDC (LCD-TFT Display Controller) driver in the CMake build system. Specifically, it includes stm32_ltdc.c in the source list (SRCS) when CONFIG_STM32H7_LTDC is enabled in the NuttX configuration.
The LTDC driver for STM32H7 is already implemented in the codebase, but it was not being built via CMake due to missing inclusion in CMakeLists.txt. This change ensures that the driver can be compiled and linked properly when the configuration option is selected, enabling display support for STM32H7-based boards without build errors. This aligns with ongoing efforts to improve STM32H7 peripheral support in NuttX.
Tested on host: Linux Mint 22.2 Zara base: Ubuntu 24.04 noble, with CMake version 3.28.3 and arm-none-eabi-gcc …
=> cmake/stm32h7: Add LTDC support to CMakeLists.txt

arch/arm64/src/common/arm64_usestack.c, arch/avr/src/avr32/avr_usestack.c, arch/ceva/src/common/ceva_usestack.c, arch/hc/src/common/hc_usestack.c, arch/mips/src/common/mips_usestack.c, arch/misoc/src/lm32/lm32_usestack.c, arch/misoc/src/minerva/minerva_usestack.c, arch/or1k/src/common/or1k_usestack.c, arch/renesas/src/common/renesas_usestack.c, arch/risc-v/src/common/riscv_usestack.c, arch/sim/src/sim/sim_usestack.c, arch/sparc/src/common/sparc_usestack.c, arch/x86/src/i486/i486_usestack.c, arch/x86_64/src/intel64/intel64_usestack.c, arch/xtensa/src/common/xtensa_usestack.c, arch/z16/src/common/z16_usestack.c, arch/z80/src/common/z80_usestack.c
These archs only align the size of the stack, forgeting to do the
stack start addr alignment, this patch fixes it.
This patch fixes the stack alignment bug for all archs that need
do stack addr alignment
This patch fixed bugs in the arch level, on impact on other parts
This patch fixes the alignment bugs for all arches, there is no way to do the test for
all archs...., I will resort to the CI to verify that this fix is OK.
=> arch: fix alignment bug for archs that need stack alignment

arch/arm/src/stm32h7/hardware/stm32_wdg.h, arch/arm/src/stm32h7/stm32_wwdg.c, arch/arm/src/stm32h7/stm32h7x3xx_rcc.c
This patch addresses several issues and adds enhancements to the WWDG (Window Watchdog) implementation for the STM32H7 platform. 
The changes were necessary to make the WWDG work correctly on the STM32H7 platform. Without them, it was not possible to correctly initialize and use the watchdog.
The changes include:
- Fix and extend the definitions of WWDG_CFR_PCLK1 macros to support dividers up to 128, and update the `stm32_settimeout()` function to consider this extended range.
- Fix the "elapsed" calculations in the stm32_getstatus() function to ensure correct calculations of the remaining time.
- Clear the EWIF (Early Wakeup Interrupt Flag) bit in the stm32_start() function, as this bit might be set by hardware before the watchdog is actually started.
- Initialize the WWDG clock in the …
=> arch/arm/stm32h7: Fix and enhance WWDG (Window Watchdog) support

Documentation/platforms/risc-v/esp32c3/boards/esp32c3-generic/index.rst, Documentation/platforms/risc-v/esp32c6/boards/esp32c6-devkitc/index.rst, Documentation/platforms/risc-v/esp32c6/boards/esp32c6-devkitm/index.rst, Documentation/platforms/risc-v/esp32h2/boards/esp32h2-devkit/index.rst, boards/risc-v/esp32c3/esp32c3-generic/src/esp32c3_buttons.c, boards/risc-v/esp32c6/esp32c6-devkitc/src/esp32c6_buttons.c, boards/risc-v/esp32c6/esp32c6-devkitm/src/esp32c6_buttons.c, boards/risc-v/esp32h2/esp32h2-devkit/src/esp32h2_buttons.c
* boards/esp32[c3|c6|h2]: Fix GPIO function used by the button
- Fixes the function to select the GPIO behavior for the pins associated to the board's button.
- Please note that for [ESP32-C3](https://www.espressif.com/sites/default/files/documentation/esp32-c3_technical_reference_manual_en.pdf#section.5.12), [ESP32-C6](https://www.espressif.com/sites/default/files/documentation/esp32-c6_technical_reference_manual_en.pdf#section.7.12) and [ESP32-H2](https://www.espressif.com/sites/default/files/documentation/esp32-h2_technical_reference_manual_en.pdf#section.6.13), the pin `Function 1` corresponds to the GPIO mapping for all pins. That function should be used when selecting the pin function. Please note that the pin function on TRM starts from `0`. On NuttX, on the other hand, it starts …
=> boards/esp32[c3|c6|h2]: Fix GPIO function used by the button

CMakeLists.txt, arch/arm/src/rp2040/.gitignore, arch/arm/src/rp2040/CMakeLists.txt, arch/arm/src/rp2040/boot2/rp2040_boot_stage2.cmake, boards/arm/rp2040/adafruit-feather-rp2040/src/rp2040_pico.h, boards/arm/rp2040/adafruit-kb2040/src/rp2040_pico.h, boards/arm/rp2040/adafruit-qt-py-rp2040/src/rp2040_pico.h, boards/arm/rp2040/common/CMakeLists.txt, boards/arm/rp2040/common/include/rp2040_common_pico.h, boards/arm/rp2040/common/src/CMakeLists.txt, boards/arm/rp2040/common/src/rp2040_common_bringup.c, boards/arm/rp2040/pimoroni-tiny2040/src/rp2040_pico.h, boards/arm/rp2040/raspberrypi-pico-w/src/rp2040_pico.h, boards/arm/rp2040/raspberrypi-pico/CMakeLists.txt, boards/arm/rp2040/raspberrypi-pico/src/CMakeLists.txt, boards/arm/rp2040/raspberrypi-pico/src/rp2040_pico.h, boards/arm/rp2040/seeed-xiao-rp2040/src/rp2040_pico.h, boards/arm/rp2040/w5500-evb-pico/src/rp2040_pico.h, boards/arm/rp2040/waveshare-rp2040-lcd-1.28/src/rp2040_pico.h, boards/arm/rp2040/waveshare-rp2040-zero/src/rp2040_pico.h, tools/ci/testlist/arm-06.dat
- CMake added board Raspberry Pi Pico
- Added the entry:
CMake,raspberrypi-pico:bmp280
to the file arm-06.dat.
- Moved the search for the Python 3 interpreter to the root CMakefile to avoid unnecessary repetition.
-  fix
```
src/rp2040_common_bringup.c: In function 'rp2040_common_bringup':
Error: src/rp2040_common_bringup.c:652:9: error: implicit declaration of function 'rp2040_dev_gpio_init' [-Werror=implicit-function-declaration]
652 |   ret = rp2040_dev_gpio_init();
|         ^~~~~~~~~~~~~~~~~~~~
```
Impact on user: This PR adds Raspberry Pi Pico board with CMake build
Impact on build: This PR Implement CMake build for the Raspberry Pi RP2040
Locally (Linux, Msys2 and Windows Native) …
=> arm/rp2040: CMake build for Raspberry Pi RP2040 implemented

arch/risc-v/src/common/espressif/esp_lowputc.c, arch/risc-v/src/common/espressif/esp_lowputc.h, arch/risc-v/src/common/espressif/esp_serial.c, arch/risc-v/src/common/espressif/esp_usbserial.c, arch/risc-v/src/esp32c3/hal_esp32c3.mk, arch/risc-v/src/esp32h2/hal_esp32h2.mk
* risc-v/espressif/uart: Update common source code functions
- Updates the common source code for the UART peripheral used by Espressif's RISC-Vs SoCs. This enables newer SoCs to be supported in the future while maintaining backwards compatibility.
Testing can be performed using any of the `nsh` or `usbconsole` defconfigs available for any of Espressif's RISC-V-based devices (ESP32-C3, ESP32-C6, or ESP32-H2). The behavior of the UART-related peripherals didn't change, and this PR's results are the same of the results before it. This can …
=> risc-v/espressif/uart: Update common source code functions

arch/tricore/src/common/ToolchainTasking.defs
Allow Make to gen .srec and .hex for tasking compiler
Allow Make to generate .srec and .hex for tasking compiler
Make scripts improvement for tricore arch and tasking compiler, no impact
to other nuttx parts
**enable srec and hex file generation and tasking compiler**
**build success**
=> arch/tricore: Allow Make to gen .srec and .hex for tasking compiler

arch/tricore/src/common/tricore_doirq.c
Fix the tircore arch build error introduced by [PR17060](https://github.com/apache/nuttx/pull/17060)
It looks like the tricore arch related board is not in CI, so the build issue 
was not checked
This patch fixed the build error.
Fixed build error introduced by new PR merged
**Before this PR**
**After this PR**
**Ostest Passed**
=> arch/tricore: Fix tricore arch build error 

Documentation/debugging/stackcheck.rst, Kconfig, arch/arm/src/common/arm_checkstack.c, arch/arm64/src/common/arm64_checkstack.c, arch/avr/src/avr/avr_checkstack.c, arch/ceva/src/common/ceva_checkstack.c, arch/or1k/src/common/or1k_checkstack.c, arch/risc-v/src/common/riscv_checkstack.c, arch/sim/src/sim/sim_checkstack.c, arch/sparc/src/common/sparc_checkstack.c, arch/tricore/src/common/tricore_checkstack.c, arch/x86_64/src/intel64/intel64_checkstack.c, arch/xtensa/src/common/xtensa_checkstack.c, fs/procfs/fs_procfsproc.c, include/nuttx/arch.h, sched/misc/assert.c, sched/misc/coredump.c, sched/sched/sched_suspendscheduler.c
I add a software method for stack overflow detection, which will detect the sp register and the bottom stack memory of the thread.
Add stack overflow detection on context switching. If enable `STACKCHECK_SOFTWARE`, this check will be turned on. By default, the bottom 16 bytes of the stack will be checked. This parameter can be configured through `STACKCHECK_MARGIN`
```c
#include <pthread.h>
#include <sched.h>
#include <stdint.h>
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>
#define STACK_SIZE (8192)
static unsigned char stack[STACK_SIZE];
void *thread_func(void *arg) {
puts("haha");
return NULL;
}
int main(int argc, char *argv[]) {
pthread_t thread;
pthread_attr_t attr;
uint32_t stack_color = 0xdeadbeef;
pthread_attr_init(&attr);
pthread_attr_setstack(&attr, stack, …
```
=> sched: add stack overflow check on switch context

arch/risc-v/src/common/espressif/esp_temperature_sensor.c, arch/xtensa/src/common/espressif/esp_temperature_sensor.c
Why change is necessary (fix, update, new feature)? Fix - The temperature sensor driver was using direct pointer casting which could lead to incorrect memory access and potential runtime crashes.
What functional part of the code is being changed? ESP temperature sensor driver in arch/xtensa/src/common/espressif/esp_temperature_sensor.c.
How does the change exactly work (what will change and how)? Replaced direct casting of lower half structure pointer with container_of macro to safely derive the private structure pointer, ensuring proper type safety.
Is new feature added? Is existing feature changed? NO - Bug fix only, no functional changes.
Impact on user (will user need to adapt to change)? NO - Internal implementation change only.
Impact on build (will build process change)? NO - No …
=> {bp-17049} arch/xtensa: espressif: temperature: Fix incorrect pointer casting

arch/arm64/src/imx9/imx9_usbdev.c
The interrupt handler accesses the device as well as the driver's private data. Use critical_section for mutual exclusion with drivers/usbdev, which also protects the same data with critical_section.
RELEASE
CI
=> {bp-17037} imx9/imx9_usbdev.c: Fix interrupt handling in SMP mode

arch/arm64/src/common/arm64_usestack.c, arch/avr/src/avr32/avr_usestack.c, arch/ceva/src/common/ceva_usestack.c, arch/hc/src/common/hc_usestack.c, arch/mips/src/common/mips_usestack.c, arch/misoc/src/lm32/lm32_usestack.c, arch/misoc/src/minerva/minerva_usestack.c, arch/or1k/src/common/or1k_usestack.c, arch/renesas/src/common/renesas_usestack.c, arch/risc-v/src/common/riscv_usestack.c, arch/sim/src/sim/sim_usestack.c, arch/sparc/src/common/sparc_usestack.c, arch/x86/src/i486/i486_usestack.c, arch/x86_64/src/intel64/intel64_usestack.c, arch/xtensa/src/common/xtensa_usestack.c, arch/z16/src/common/z16_usestack.c, arch/z80/src/common/z80_usestack.c
These archs only align the size of the stack, forgeting to do the
stack start addr alignment, this patch fixes it.
RELEASE
CI
=> [bp-17034} arch: fix alignment bug for archs that need stack alignment

arch/arm/src/common/arm_usestack.c, arch/tricore/src/common/tricore_usestack.c
The stack alignment operation in tricore and arm porting
only aligns the size of the stack, forget to align the start addr
of the stack, this patch fixes it.
RELEASE
CI
=> {bp-17029} arch: fix stack alignment bug for arm and tricore arch

arch/tricore/src/cmake/ToolchainTasking.cmake
prefix compiler with ${TOOLCHAIN_PREFIX}
RELEASE
CI
=> {bp-17006} arch/tricore: allow user defined compiler path

arch/arm/src/rp2040/hardware/rp2040_address_mapped.h, arch/arm/src/rp2040/rp2040_gpio.h, boards/arm/rp2040/common/src/rp2040_uniqueid.c
The functions `hw_write_masked` and `hw_xor_bits` (as defined in pico-sdk) were defined in NuttX twice.
Additionally these definitions were in conflict (one lacked the `volatile` modifier).
Now these functions and their dependencies are defined in a new header file.
Its name is based on the filename of the original definition in pico-sdk:
src/rp2_common/hardware_base/include/hardware/address_mapped.h
This change should fix the potential issue of GPIO operations failing due to compiler optimizations caused by the absence of `volatile`.
RELEASE
CI
=> {bp-16997} arch/arm/rp2040: merge conflicting definitions of `hw_*` functions

arch/sim/src/sim/sim_canchar.c
fix CAN flags decoding for SIM CAN
RELEASE
CI
=> {Bp-16988} arch/sim/sim_canchar.c: fix CAN flags decoding for message

sched/signal/sig_dispatch.c
Use of this_task() to identify which thread the signal should be delivered to is just wrong. Replace is with stcb.
Fixes signal delivery from uart driver (tty), e.g. ctrl-c.
Tested on qemu
=> {Bp-16939} sched/signal/sig_dispatch.c: Correct signal dispatch to specific thread

arch/arm64/src/bcm2711/CMakeLists.txt, arch/arm64/src/bcm2711/Make.defs, arch/arm64/src/bcm2711/bcm2711_mailbox.c, arch/arm64/src/bcm2711/bcm2711_mailbox.h, arch/arm64/src/bcm2711/hardware/bcm2711_mailbox.h, arch/arm64/src/bcm2711/hardware/bcm2711_memmap.h, boards/Kconfig, boards/arm64/bcm2711/raspberrypi-4b/include/board.h, boards/arm64/bcm2711/raspberrypi-4b/src/CMakeLists.txt, boards/arm64/bcm2711/raspberrypi-4b/src/Makefile, boards/arm64/bcm2711/raspberrypi-4b/src/rpi4b_autoleds.c, boards/arm64/bcm2711/raspberrypi-4b/src/rpi4b_boardinitialize.c, boards/arm64/bcm2711/raspberrypi-4b/src/rpi4b_bringup.c
This PR contains two commits:
1. A basic implementation of mailbox API with some helpers for accessing properties implemented. Uses busy-wait due to documentation challenges with mailbox API.
2. Added autoled implementation for the Pi4B. Status LED is used as NuttX start indicator, while power LED is used for panic/assert indication.
Closes #17053.
This BCM2711 mailbox API is a base implementation which currently allows some important properties to be read (such as MAC address, CPU temperature, etc.). It has the necessary internals to be extended with more features (i.e setting power domains, clock frequencies, etc.) as necessary. This allows other parts of the RPi4B to be used (EMMC2 is my goal next).
The autoled implementation is simply included in this PR as a visual of the testing …
=> bcm2711/mailbox: BCM2711 VideoCore mailbox API implementation

arch/xtensa/src/common/espressif/esp_wlan_netdev.c
- arch/xtensa: fix Wi-Fi netpkt copy error
Fix an issue where netpkt copy would fail due to wrong return checking condition.
Fixes #17113.
- Impact on user: Yes. Fixes bug preventing Wi-Fi connection.
- Impact on build: No.
- Impact on hardware: ESP32|S2|S3 only.
- Impact on documentation: No.
- Impact on security: No.
- Impact on compatibility: No.
Simply build the wifi defconfig, connect to an AP and ping it.
- ./tools/configure.sh esp32s3-devkit:wifi
- make and flash
Connect to a network, obtain an IP address with renew and attempt a ping:
```
wapi psk wlan0 <pass> 3 3
wapi essid wlan0 <ssid> 1
renew wlan0
```
Pings normally:
```
nsh> renew wlan0
nsh> ifconfig
wlan0    Link encap:Ethernet HWaddr 70:b8:f6:12:bf:44 at RUNNING mtu 1500
inet addr:192.168.0.84 DRaddr:192.168.0.1 …
```
=> arch/xtensa/espressif: fix Wi-Fi netpkt copy error

fs/mmap/fs_mmap.c
add missing NULL pointer for msync to match `struct mm_map_entry_s` definition
pure cosmetic change
CI
=> fs/mmap/fs_mmap.c: add missing NULL pointer

sched/signal/sig_pending.c
Previously sigpending() returned all pending signals in the group, which is not POSIX compliant. It should return signals pending only for the caller, so a signal send with pthread_kill() intended for another thread should not be returned (it's not pending for a caller).
This fixes the pthread_create.c/test9 test case from PSE52 Open Group Threads Test Suite.
POSIX compliance
PSE52 test suite.
The test case looks like this:
```
function test():
setup_signals()       // block signals, set SIGTERM handler
start thread1
join thread1
restore_signals()     // restore original signal mask and handler
------------------------------
thread1 ():
block all signals
send SIGTERM to self   // signal becomes pending, pthread_kill(pthread_self(), SIGTERM)
start thread2
join thread2           // thread2 …
```
=> sched/sig_pending: sigpending() should return caller pending signals only

arch/risc-v/src/common/espressif/esp_gpio.c
* risc-v/espressif/gpio: Update common source code functions
- Updates the common source code for the GPIO peripheral used by Espressif's RISC-Vs SoCs. This enables newer SoCs to be supported in the future while maintaining backwards compatibility.
Build the corresponding `buttons` defconfig for the devices and press the `BOOT` button in the board.
```
make -j distclean && ./tools/configure.sh esp32c3-generic:buttons && make flash ESPTOOL_PORT=/dev/ttyUSB0 && picocom -b 115200 /dev/ttyUSB0
```
```
make -j distclean && …
```
=> risc-v/espressif/gpio: Update common source code functions

cmake/nuttx_add_subdirectory.cmake
Closes: #17074.
This PR extends the nuttx_add_subdirectory() CMake helper to support excluding specific directories from being added to the build.
Previously, nuttx_add_subdirectory() added all available subdirectories, which could be undesirable in cases where certain apps or components should be skipped.
With this change, developers can now pass an EXCLUDE argument to specify directories that should not be included.
Example usage:
```
nuttx_add_subdirectory(EXCLUDE dir_to_ignore)
```
This improves flexibility in project configurations, particularly in out-of-tree builds and when fine-grained control of the build process is needed.
- Build system: Adds the ability to ignore …
=> cmake: pass exclusion list to nuttx_add_subdirectory

boards/arm/rp23xx/xiao-rp2350/CMakeLists.txt, boards/arm/rp23xx/xiao-rp2350/src/CMakeLists.txt
- Added CMake build for Seeed Studio XIAO RP2350
Impact on user: This PR adds the Seeed Studio XIAO RP2350 board with CMake build.
xiao-rp2350:nsh
```
D:\nuttxpico\nuttx>cmake -B build -DBOARD_CONFIG=xiao-rp2350:nsh -GNinja
-- Found Python3: C:/Users/bit/AppData/Local/Programs/Python/Python313/python.exe (found version "3.13.3") found components: Interpreter
-- Processing includes: D:/nuttxpico/nuttx/boards/arm/rp23xx/xiao-rp2350/configs/nsh/defconfig -> D:/nuttxpico/nuttx/build/.defconfig.processed
-- Skipping OOTCpp project
--   CMake:  3.31.5
--   Ninja: …
```
=> boards/arm/rp23xx: CMake added Seeed Studio XIAO RP2350 board

boards/arm/rp23xx/pimoroni-pico-2-plus/CMakeLists.txt, boards/arm/rp23xx/pimoroni-pico-2-plus/src/CMakeLists.txt
Added CMake build for Pimoroni Pico Plus 2
#17155
Impact on user: This PR adds the Pimoroni Pico Plus 2 board with CMake build.
pimoroni-pico-2-plus:nsh
```
D:\nuttxpico\nuttx>cmake -B build -DBOARD_CONFIG=pimoroni-pico-2-plus:nsh -GNinja
-- Found Python3: C:/Users/bit/AppData/Local/Programs/Python/Python313/python.exe (found version "3.13.3") found components: Interpreter
-- Processing includes: D:/nuttxpico/nuttx/boards/arm/rp23xx/pimoroni-pico-2-plus/configs/nsh/defconfig -> D:/nuttxpico/nuttx/build/.defconfig.processed
-- Skipping OOTCpp project
--   CMake: …
```
=> boards/arm/rp23xx: CMake added Pimoroni Pico Plus 2 board

arch/xtensa/src/esp32s3/esp32s3_pm.c
This PR fixes a bug in the ESP32-S3 UART driver suspend logic that could
lead to deadlocks when power management (PM) was enabled.
The issue was caused by an incorrect check of the UART FSM status register
during suspend. As a result, the driver could block indefinitely while
waiting for a state transition that never occurred.
Changes include:
- Corrected FSM status register check in suspend path
- Ensures suspend/resume completes reliably under PM
Impact
Build impact: None.
Runtime impact: Prevents potential deadlocks when UARTs are suspended
with PM enabled.
API impact: None.
Area impacted: ESP32-S3 UART driver suspend logic.
=> arch/xtensa/esp32s3: fix FSM check to avoid PM deadlocks

boards/arm/rp23xx/pimoroni-pico-2-plus/include/rp23xx_spisd.h
Added missing header file rp23xx_spisd.h
fix
src/rp23xx_common_bringup.c: In function 'rp23xx_common_bringup': Error: src/rp23xx_common_bringup.c:390:9: error: implicit declaration of function 'board_spisd_initialize'; did you mean 'board_spidev_initialize'? [-Werror=implicit-function-declaration]
390 |   ret = board_spisd_initialize(0, CONFIG_RP23XX_SPISD_SPI_CH);
|         ^~~~~~~~~~~~~~~~~~~~~~
Linux (arm-06)
https://github.com/apache/nuttx/actions/runs/18284202662/job/52054851120#logs
Impact on build: Fix CMake and Make build (audiopack,composite and usbmsc)
Locally and GitHub
./tools/configure.sh -l pimoroni-pico-2-plus:audiopack …
=> boards/arm/rp23xx/pimoroni-pico-2-plus: fix implicit declaration of function 'board_spisd_initialize'

arch/xtensa/src/common/espressif/esp_efuse.c
* arch/xtensa/espressif: Fix efuse build warning for esp32
Fix build warning while building efuse for esp32
Impact on user: No, just build warning fixed
Any config can be used which is based on esp32. `nsh` config used for example and here is the build command:
```
make distclean && ./tools/configure.sh esp32-devkitc:nsh && make -j
``` 
During build process here is logs before this change:
```
CC:  vfs/fs_rmdir.c In file included from common/espressif/esp_efuse.c:43:
.../nuttx/arch/xtensa/src/chip/esp-hal-3rdparty/components/soc/esp32/register/soc/apb_ctrl_reg.h:9:2: warning: #warning "apb_ctrl_reg is deprecated due to duplicated with syscon_reg, please use syscon_reg …
```
=> arch/xtensa/espressif: Fix efuse build warning for esp32

boards/arm/rp23xx/pimoroni-pico-2-plus/include/board.h
Added missing #include ‘rp23xx_spisd.h’ in board.h
(forgotten in PR #17167)
Impact on build: Fix CMake and Make build (audiopack,composite and usbmsc)
pimoroni-pico-2-plus:audiopack 
CMake
```
D:\nuttxpico\nuttx>cmake -B build -DBOARD_CONFIG=pimoroni-pico-2-plus:audiopack -GNinja
-- Found Python3: C:/Users/bit/AppData/Local/Programs/Python/Python313/python.exe (found version "3.13.3") found components: Interpreter
-- Processing includes: D:/nuttxpico/nuttx/boards/arm/rp23xx/pimoroni-pico-2-plus/configs/audiopack/defconfig -> D:/nuttxpico/nuttx/build/.defconfig.processed
-- Skipping OOTCpp project
Select …
```
=> boards/arm/rp23xx/pimoroni-pico-2-plus: added ‘rp23xx_spisd.h’ in board.h
