apache/nuttx

arch/arm/src/stm32h7/Kconfig, arch/arm/src/stm32h7/Make.defs, arch/arm/src/stm32h7/hardware/stm32_qspi.h, arch/arm/src/stm32h7/stm32_qspi.c, arch/arm/src/stm32h7/stm32_qspi.h
The code is copy and modified from STM32F7.
I tested on my board with W25Q128 flash chip.
=> Implement QSPI for STM32H7

include/nuttx/fs/fs.h
Replace with the description taken from fs_write.c
Signed-off-by: junmin-kim <junmindd.kim@samsung.com>
=> Update the file_write description in fs.h

boards/arm/stm32/stm32f4discovery/scripts/Make.defs
Signed-off-by: Yusuke Mitsuki <ym.sp9@connectfree.co.jp>
=> Add clang support to stm32f4discovery board

net/arp/arp_send.c, net/neighbor/neighbor_out.c, net/netdev/netdev_ioctl.c, net/netdev/netdev_lladdrsize.c, net/pkt/pkt_sockif.c
Change-Id: I13cc4cbfc1e305e17c0630f11a1173afe96e8a03
=> net: complement wireless handling as ethernet

net/bluetooth/bluetooth_poll.c, net/icmp/icmp_sendto.c, net/icmpv6/icmpv6_autoconfig.c, net/icmpv6/icmpv6_poll.c, net/icmpv6/icmpv6_radvertise.c, net/icmpv6/icmpv6_sendto.c, net/ieee802154/ieee802154_poll.c, net/igmp/igmp_input.c, net/neighbor/neighbor_globals.c, net/route/net_fileroute.c, net/sixlowpan/sixlowpan_globals.c, net/sixlowpan/sixlowpan_hc06.c, net/sixlowpan/sixlowpan_send.c, net/socket/setsockopt.c, net/tcp/tcp_backlog.c, net/tcp/tcp_input.c, net/tcp/tcp_setsockopt.c, net/tcp/tcp_timer.c, net/usrsock/usrsock_close.c
There have been numerous changes under net/ recently as well as improvements to tools/nxstyle.  It is important to assure that all files can pass nxstyle without problems.
=> net/:  Run all .c files under net/ through tools/nxstyle and fix all resulting complaints.

boards/arm/stm32/stm32f4discovery/README.txt, boards/arm/stm32/stm32f4discovery/src/Makefile, boards/arm/stm32/stm32f4discovery/src/stm32_bringup.c, boards/arm/stm32/stm32f4discovery/src/stm32_spi.c, boards/arm/stm32/stm32f4discovery/src/stm32_sx127x.c, boards/arm/stm32/stm32f4discovery/src/stm32f4discovery.h, drivers/wireless/lpwan/sx127x/sx127x.c
Note: because I'm using a hand soldered wires I'm getting errors like this:
nsh> sx127x
Start sx127x_demo
ERROR: Failed to open device! Error: 61
But eventually it works:
nsh> sx127x
Start sx127x_demo
LORA modulation
Set frequency to 915000000
Set power to 14
Waiting for data
=> Add board support to external LoRa NiceRF module

arch/sim/src/sim/up_netdriver.c
Change-Id: Ia9011b62ea61d15bd66aa063e4165d9d3baacb51
=> sim/net: do not do any critical operations in idle

README.txt, tools/configure.bat
Update configure.bat so that it works like configure.sh and integrates properly with configure.c.  Also update the README.txt file with a few native build clarifications.
=> tools/configure.bat: Update

drivers/can/can.c, include/nuttx/can/can.h
=> can driver: fix errors with pointers when using internal OS interface

mm/iob/iob_notifier.c, net/netdev/netdown_notifier.c, net/netlink/netlink_conn.c, net/netlink/netlink_notifier.c, net/netlink/netlink_sockif.c, net/tcp/tcp_notifier.c, net/udp/udp_notifier.c
usage changed after commit 90c52e6f8f7efce97ac718c0f98addc13ec880d2
Change-Id: Ifb0d739b046a6794b5b3ac177f489fb9a1c5c799
=> wqueue/notifier: update the work notifier usage

arch/sim/Kconfig
Change-Id: Ic2d42d29fc84bef1cc279ef443897d5191888e72
=> sim/netdev: dependens on LPWORK by default

libs/libc/Makefile
Change-Id: Ie2a3af4f532f07612d68d3a1bf1353cdb44a0a67
=> libs/MT: correct the dependents path

tools/README.txt, tools/testbuild.sh
1.Scan the folder under nuttx/boards by prefix /
2.Skip the specified configuration by prefix -
Change-Id: Ibb67f2c6b96cd8e439d94bf71d098c1fd9e5a79d
=> Enhance the syntax of testlist-file for testbuild.sh

tools/testbuild.sh
This capability was erroneously removed by a previous commit.  This setting is necessary when the C++ code generated by the compiler uses the new and delete operators provided in libs/libxx.
Here is an example of an error scenario where this capability is required:
1. CONFIG_CXX_NEWLONG=y in the defconfig file
2. This causes libs/libxx to to generate a delete operator of this form:
void delete(void*, unsigned long);
3. But the compiler expects to link with a delete operator of this form:
void delete(void*, unsigned int);
That results in a link-time failure and the ONLY solution for avoiding that link time failure (short of some complete redesign) is to have a control over the CONFIG_CXX_NEWLONG setting and make sture that it is always disabled for that toolchain.
Other toolchains will …
=> tools/testbuild.sh:  Restore ability to select type of new and delete operators

boards/sim/sim/sim/README.txt
Fix some typos and grammar. Rewrap the text to 80 columns for
consistency with the rest of the file.
=> boards/sim/sim/sim/README.txt: Improve and rewrap text.

tools/testbuild.sh
Change-Id: I8f2c3c3b2c3a3ac2d3be0330f3c79feb2c775c43
=> tools/testbuild.sh: update fail to return the error value instead

drivers/net/phy_notify.c, include/nuttx/net/phy.h
Change-Id: Ib5687b34986f764b9e11ba658a039a1893886b4b
=> Replace CONFIG_PHY_NOTIFICATION_MAXINTFLEN with IFNAMSIZ

libs/libc/Makefile, libs/libnx/Makefile, mm/Makefile, tools/Config.mk, tools/Makefile.unix, tools/Makefile.win
Change-Id: I41eb8003a386e83ef3afd94bf8f0ebb5348f79e0
=> Config.mk: add DEFINE macro like INCDIR

drivers/1wire/Kconfig, drivers/Kconfig, drivers/can/Kconfig, drivers/contactless/Kconfig, drivers/eeprom/Kconfig, drivers/i2c/Kconfig, drivers/mmcsd/Kconfig, drivers/rptun/Kconfig, drivers/spi/Kconfig, drivers/timers/Kconfig, drivers/usbmonitor/Kconfig, drivers/video/Kconfig, drivers/wireless/Kconfig
1.Move subsystem config into sub folder
2.Remove the duplicated if/endif
Change-Id: I0b96ac0570ee1ba62bbb95586381f5410b90bcf0
=> Refine Kconfig under drivers folder

arch/arm/src/kinetis/kinetis_enet.c, drivers/net/Kconfig, include/nuttx/net/mii.h
Based on #160 splitted up to kinetis, imxrt & s32k
=> Kinetis renamed TJA1100 to TJA110X registers

tools/testbuild.sh
Change-Id: I50cbc335254be0f2388b4bb6af8a874e74ba98c2
=> tools/testbuild.sh: use function to call make and fail handle in common

tools/testbuild.sh
Change-Id: I9754a797e9bbf45749d19b0fd53ce7dd2693e476
=> tools/testbuild.sh: make sure fail get the real return error value

arch/sim/src/Makefile, arch/sim/src/sim/up_lcd.c
and compile up_spiflash.c and up_qspiflash.c conditionally
Change-Id: Ice45c2e47141bb47d5332e7fcc2e7eb279b3be84
=> Rename board_lcd.c to up_lcd.c like other sim code

tools/checkpatch.sh
Do not use pipeline way and make sure fail to record the real exit error value.
Change-Id: Id84aab923f5ce03c76cd42d1a24a3005608c6a9e
=> tools/checkpatch.sh: make sure fail get the real return error value

drivers/net/telnet.c
=> drivers/net/telnet.c: correct typo error to fix build break

arch/arm/src/armv7-a/arm_vectors.S
This should resolve one of two problems noted by @masayuki2009 in #207
=> arch/arm/src/armv7-a/arm_vectors.S:  Fix clobbered register in SMP mode.

boards/arm/tiva/lm3s6965-ek/src/Makefile, boards/arm/tiva/lm3s6965-ek/src/lm3s6965-ek.h, boards/arm/tiva/lm3s6965-ek/src/lm_appinit.c, boards/arm/tiva/lm3s6965-ek/src/lm_boot.c, boards/arm/tiva/lm3s6965-ek/src/lm_bringup.c
A shrinked copy of the sim version.
=> tiva/lm3s6965-ek: Add CONFIG_BOARD_LATE_INITIALIZE

mm/mm_heap/mm_mallinfo.c, mm/mm_heap/mm_malloc.c
@yamt Please, make sure no other issue was included by this PR.
=> mm/mm_heap: Fix warnings included by #266

arch/sim/src/sim/up_hosttime.c, arch/sim/src/sim/up_internal.h, arch/sim/src/sim/up_rtc.c
Change-Id: I5166735ea7efa0594979809a8905934cd8114688
=> sim/rtc: Don't change the host wall clock in sim_rtc_settime

arch/arm/include/tiva/chip.h
This fixes some typos in comments.
No functional changes.
=> arch/arm/include/tiva/chip.h: Fix typos

include/sys/file.h
Change-Id: I08253dbf5e8b62ceffb511d64645e19a98653241
=> fcntl: add O_CLOEXEC flag

fs/vfs/fs_ioctl.c, include/nuttx/fs/ioctl.h
Change-Id: Ic04eaaa2a134a050ad5a8379561a733ae7891d8a
=> net/ioctl: add FIONBIO support

sched/Kconfig
Change-Id: Ifca654f0f62ad1425c772f9e8ca29252abf12c52
=> Kconfig: add PATH_MAX config

libs/libc/stdio/lib_getdelim.c
Change-Id: I84ddd3c88f6a9e72860e9f1214ce816851aa6a9f
=> stdio/getline: correct the character slash

arch/arm/src/armv6-m/up_signal_dispatch.c, arch/arm/src/armv6-m/up_svcall.c, arch/arm/src/armv7-a/arm_signal_dispatch.c, arch/arm/src/armv7-a/arm_syscall.c, arch/arm/src/armv7-m/up_signal_dispatch.c, arch/arm/src/armv7-m/up_svcall.c, arch/arm/src/armv7-r/arm_syscall.c, arch/risc-v/src/rv64gc/up_signal_dispatch.c, arch/risc-v/src/rv64gc/up_swint.c
Also, fix typos and copy-and-paste errors.
=> Update the comments (the location of trampoline code)

fs/vfs/fs_fcntl.c, include/fcntl.h, net/socket/net_vfcntl.c, net/socket/socket.h, sched/group/Make.defs, sched/group/group_setuptaskfiles.c
Change-Id: I08253dbf5e8b62ceffb511d64645e19a98653241
=> fcntl: add O_CLOEXEC/FD_CLOEXEC support

README.txt
=> README.txt: add MacOS section for flock installation

binfmt/binfmt_exec.c
Change-Id: I8fce3b34bde8f96896cf206d2dbfd238d2f42ff4
=> binfmt/exec: fix build break in kernel build

tools/zds/zdsar.c
This zdsar librarian wrapper is code complete and has no known bugs.  However, there are still some build instabilities so perhaps there are still some bug to be identified.  Or perhaps there are other undiscovered bugs unrelated to zdsar which appears to be behaving correctly in all cases.
It will take some additional testing know for sure.
=> tools/zds/zdsar.c:  Fix several errors

tools/checkpatch.sh
=> Add code spell check to checkpatch.sh

net/netlink/netlink_route.c
Change-Id: I60ef35dd658f7db25894702c4c7958547cd17d63
=> netlink: correct the return value

tools/LibTargets.mk
"all" and "depend" targets should not be made concurrently.
I occasionally see APPDIR build failures because of this.
=> Fix make target dependencies

tools/LibTargets.mk
This reverts commit 5f540d79a1c07696672246ba5acab3f24099f205.
=> Revert "Fix make target dependencies"

arch/xtensa/src/common/xtensa_schedsigaction.c
This fixes various crashes in ostest.
=> xtensa: Fix up_schedule_sigaction

boards/arm/stm32/stm32f4discovery/src/stm32_romfs_initialize.c
=> boards/arm/stm32/stm32f4discovery: Fix build errors

tools/nxstyle.c
https://www.youtube.com/watch?v=Jne9t8sHpUc
=> nxstyle:nxstyle should pass nxstyle checks!

drivers/mtd/w25.c
Verifed with 8Mbit AMIC A25L080 part.
=> drivers/mtd/w25.c:  Add support for work-alike AMIC parts

drivers/usbhost/usbhost_xboxcontroller.c
https://github.com/apache/incubator-nuttx/issues/483
=> Fixed compilation issue with poll fds notification.

boards/z80/ez80/z20x/src/w25_main.c
Code Complete but still things to be verify before I can claim Functionality Complete.
=> boards/z80/ez80/z20x:  W25 Bootler is Code Complete

tools/nxstyle.c
fixed coloumn number of error messages PR #487
fixed lineno_min = lineno_min
=> nxstyle fixes

arch/z80/src/ez80/ez80_spi.c, boards/z80/ez80/z20x/src/w25_main.c
boards/z80/ez80/z20x/src/w25_main.c:  Improve user interface.
There is still an error occurring while downloading Intex HEX files to FLASH.  That is unrelated to this and appears to be a problem libs/libc/hex2gbin/lib_hex2bin.c
=> z80x:  W25 Bootloader Improvements

sched/semaphore/sem_holder.c
#if 0 cannot be followed by a multi-line comment to the right.  Well, not without raising some odd coding standard/nxstyle issues.
=> sched/semaphore/sem_holder.c:  Fix bad line separation.

sched/irq/irq_procfs.c, sched/task/task_vfork.c
Fix new coding standard issues found by new, revised nxstyle.
=> sched/:  Fix some new coding standard issues.

boards/z80/ez80/z20x/src/w25_main.c
boards/z80/ez80/z20x/src/w25_main.c:  (1)  Correct size comparison typo:  Should have been >= not != (2) Fix sizeof():  Was getting the sizeof the pointer instead of the sizeof the pointed at structure. (3) Improve some comments.
=> z20x:  Correct issues loading code from FLASH

libs/libc/net/lib_inetaddr.c
Standards-compliant inetaddr().
=> inetaddr() more compliant with standards (especially error handling).

sched/sched/sched_mergepending.c
And change to Apache 2.0 license.
=> sched/sched/sched_mergepending.c:  Fix nxstyle complaints.

sched/timer/Make.defs, sched/timer/timer.h, sched/timer/timer_create.c, sched/timer/timer_delete.c, sched/timer/timer_getoverrun.c, sched/timer/timer_gettime.c, sched/timer/timer_initialize.c, sched/timer/timer_release.c, sched/timer/timer_settime.c, sched/wdog/Make.defs, sched/wdog/wd_cancel.c, sched/wdog/wd_create.c, sched/wdog/wd_delete.c, sched/wdog/wd_gettime.c, sched/wdog/wd_initialize.c, sched/wdog/wd_recover.c, sched/wdog/wd_start.c, sched/wdog/wdog.h, sched/wqueue/Make.defs, sched/wqueue/kwork_cancel.c, sched/wqueue/kwork_hpthread.c, sched/wqueue/kwork_inherit.c, sched/wqueue/kwork_lpthread.c, sched/wqueue/kwork_notifier.c, sched/wqueue/kwork_process.c, sched/wqueue/kwork_queue.c, sched/wqueue/kwork_signal.c, sched/wqueue/wqueue.h
Also run files through nxstyle to assurand coding standard compliance.
=> sched/wqueue:  Update to Apache 2.0 headers.

tools/refresh.sh
Change-Id: I2e2ba7da7d06e4c3221a44c93ec1eebf121be7f6
=> tools: Support invoke refresh.sh from any directory

tools/nxstyle.c
Should fix problems like the ones arised with PR #548 .
=> nxstyle: Added assembly header detection.

arch/arm/src/s32k1xx/hardware/s32k1xx_ftm.h
Added S32K1XX FlexTimer register definitions needed for high resolution timer implementation.
=> Added S32K1XX FlexTimer register definitions

binfmt/libelf/libelf_addrenv.c, binfmt/libelf/libelf_bind.c, binfmt/libelf/libelf_ctors.c, binfmt/libelf/libelf_dtors.c, binfmt/libelf/libelf_init.c, binfmt/libelf/libelf_load.c, binfmt/libelf/libelf_sections.c, binfmt/libelf/libelf_symbols.c, binfmt/libelf/libelf_verify.c
=> libelf: Appease nxstyle complaints

drivers/usbhost/usbhost_cdcacm.c, drivers/usbhost/usbhost_devaddr.c, drivers/usbhost/usbhost_hidkbd.c, drivers/usbhost/usbhost_hidmouse.c, drivers/usbhost/usbhost_max3421e.c, drivers/usbhost/usbhost_skeleton.c, drivers/usbhost/usbhost_storage.c, drivers/usbhost/usbhost_xboxcontroller.c
Resolution of Issue 619 will require multiple steps, this part of the first step in that resolution:  Every call to nxsem_wait_uninterruptible() must handle the return value from nxsem_wait_uninterruptible properly.  This commit is only for those files under drivers/usbhost.
=> Check return from nxsem_wait_initialize()

tools/nxstyle.c
Checking for white-listed prefixes is also simpler now because the check is table driver.  New data structure:  g_white_prefix[] and new function white_prefix().
=> tools/nxstyle.c:  Add fixedmath.h defines to white-listed prefixes

drivers/1wire/1wire.c, drivers/1wire/1wire_internal.h, drivers/1wire/ds28e17.c, drivers/bch/bch.h, drivers/bch/bchdev_driver.c, drivers/bch/bchlib_sem.c, drivers/can/mcp2515.c, drivers/mmcsd/mmcsd_sdio.c, drivers/mmcsd/mmcsd_spi.c
This commit is only for those files under drivers/1wire, drivers/bch,
drivers/can and drivers/mmcsd.
=> Check return from nxsem_wait_uninterruptible

drivers/rwbuffer.c
This file is a work in progress and was accidentally committed with some other files.  This PR backs out those changes until I can better verify the changes.
=> drivers/rwbuffer.c:  Back out unfinished changes

.github/workflows/build.yml
Testlist update in https://github.com/apache/incubator-nuttx-testing/pull/26
=> CI: update matrix boards accordingly since testlist updated

include/stdint.h
I found a trivial mistake in stdint.h  and fixed it.
=> fix INTPTR_MAX define

arch/arm/src/efm32/efm32_dma.c, arch/arm/src/imxrt/imxrt_edma.c, arch/arm/src/lpc17xx_40xx/lpc17_40_gpdma.c, arch/arm/src/lpc43xx/lpc43_gpdma.c, arch/arm/src/sam34/sam_dmac.c, arch/arm/src/sama5/sam_dmac.c, arch/arm/src/samd2l2/sam_dmac.c, arch/arm/src/samd5e5/sam_dmac.c, arch/arm/src/samv7/sam_xdmac.c, arch/arm/src/stm32/stm32_dma_v1.c, arch/arm/src/stm32/stm32_dma_v2.c, arch/arm/src/stm32f0l0g0/stm32_dma_v1.c, arch/arm/src/stm32f7/stm32_dma.c, arch/mips/src/pic32mz/pic32mz-dma.c
This commit is for all DMA drivers under arch/.
=> Check return from nxsem_wait_uninterruptible()

arch/arm/src/cxd56xx/cxd56_udmac.c, arch/arm/src/s32k1xx/s32k1xx_edma.c, arch/arm/src/sama5/sam_xdmac.c, arch/arm/src/samd2l2/sam_dmac.c, arch/arm/src/stm32l4/stm32l4x6xx_dma.c
This commit is for the DMA files under arch/ that were missing from an
earlier PR.
=> Check the return of nxsem_wait_uninterruptible().

arch/arm/src/samv7/sam_progmem.c, arch/arm/src/stm32/hardware/stm32_flash.h, arch/arm/src/stm32/stm32f10xxf30xx_flash.c, arch/arm/src/stm32/stm32f20xxf40xx_flash.c, arch/arm/src/stm32/stm32l15xx_flash.c, arch/arm/src/stm32f7/hardware/stm32_flash.h, arch/arm/src/stm32f7/stm32_flash.c, arch/arm/src/stm32h7/stm32_flash.c, arch/arm/src/stm32l4/stm32l4_flash.c, arch/arm/src/stm32l4/stm32l4_flash.h
This commit is for all flash/progmem drivers under arch/.
=> Check the return of nxsem_wait_uninterruptible()

arch/arm/src/sam34/sam4cm_tc.c, arch/arm/src/sama5/sam_tc.c, arch/arm/src/samv7/sam_tc.c
This commit is for all tc drivers under arch/.
=> Check the return of nxsem_wait_unterruptible()

tools/nxstyle.c
This resolves issue #718:  nxstyle line width check was ignoring the line width check for single line comments.
This turned out to be an artifact in parsing.  Usually when parsing character by character, the file character to be parsed was '/n'.  Howefver, in the case of parsing single line comments, the final character was the NUL terminator.  This means that the lenth check was not being performed in the case of single line comments.
NOTE:  Currently, I have suppressed error reports for single line right-hand comments.  My fear is that this will unmask more standard violations than we can cope with.  It is easy to re-enable and perhaps we should do that in the future:
/* Check for long lines
*
* REVISIT:  Long line checks suppressed on right hand comments
* for now.  This just prevents …
=> tools/nxstyle.c:  Fix detection of long single line comments.

tools/zipme.sh
- Rename the final tarball to add incubating and apache to their names
- Make the tool usuable from a development repo.
- Add a list of patterns(files and folders) to exclude and
a command line argument to pass aditional patterns.
- Add a command to run silently.
- If the build number was not provided let version.sh figure it out.
=> tools/zipme.sh: Improve the tool to make it usuable from a development repo and for future Apache releases.

arch/xtensa/src/esp32/esp32_serial.c, arch/xtensa/src/esp32/hardware/esp32_dport.h, arch/xtensa/src/esp32/hardware/esp32_gpio.h, arch/xtensa/src/esp32/hardware/esp32_rtccntl.h, arch/xtensa/src/esp32/hardware/esp32_soc.h, arch/xtensa/src/esp32/hardware/esp32_uart.h
esp32 nxstyle fixes
Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>
=> arch: xtensa: esp32: nxstyle fixes

.github/workflows/build.yml
This is a sync from testing repo.
=> CI: Add macOS builds

tools/README.txt, tools/checkpatch.sh
=> checkpatch: Update checkpatch readme and remove addition blank line

arch/arm/src/stm32l4/stm32l4_i2c.c, boards/arm/cxd56xx/drivers/audio/cxd56_audio_analog.c, boards/arm/lpc214x/zp214xpa/src/lpc2148_spi1.c, net/local/local_netpoll.c
=> nuttx: Fix the nightly build warning again

arch/risc-v/src/common/up_initialize.c, arch/risc-v/src/common/up_internal.h
Signed-off-by: zhongan <zhongan@xiaomi.com>
=> risc-v: add pm initialization functions.

.github/workflows/check.yml
=> CI: refine checkpatch commits in check.yml

arch/README.txt
* Added missing architectures and directories.
* Corrected a few mistakes.
* Rewrapped some text for consistency.
=> arch/README.txt: Various improvements to the text

net/sixlowpan/sixlowpan_framer.c, net/sixlowpan/sixlowpan_utils.c
=> Backport #805 to releases/9.0

.github/workflows/build.yml
=> build.yml: Remove the tail space

Documentation/NuttxUserGuide.html
=> Backport #814 to releases/9.0

Documentation/NuttxUserGuide.html
=> Backport #813 to releases/9.0

arch/arm/include/kinetis/kinetis_pmc.h
=> Backport #809 to releases/9.0

TODO
My understanding is the Xiao Xiang has corrected this problem so it should no longer be carried as a bug
=> TODO:  Remove simulator SMP bug

arch/sim/src/Makefile, arch/sim/src/sim/up_simsmp.c
=> arch/sim: All cpu core need conform to CONFIG_SIM_WALLTIME behaviour

.github/PULL_REQUEST_TEMPLATE.md
@xiaoxiang781216 - Sorry this is so long overdue. Please add the links to running checkpatch in the 2 places indicated or just add the the `commands`
=> github: Add PR Template

.github/workflows/build.yml
since arm-12 finish more quickly than arm-11
=> build.yaml: Change arm-11 to arm-12

tools/testbuild.sh
ensure the distclean remove all generated stuff
=> tools/testbuild.sh: check status after make distclean

arch/renesas/src/rx65n/rx65n_sbram.c
Corrected build error in rx65n_sbram_open()
Following the guidelines for writting good commit messages (https://chris.beams.io/posts/git-commit/) and creating a meaningful title is key in effective team communication.
**do's**
- stm32h7:  Add SDMMC Support
- nsh:  Separate `source` and `sh` for POSIX compliance
- nxstyle:  Fixed Camel case detection
- drivers/serial:  Fixed style violation
**dont's**
- fixed bug
- nxstyle
- PR #12
**Describe problem solved by the PR**
A clear and concise description of the problem, if any, this PR will solve. Please also include relevant motivation and context: E.g. The current nsh sh command violates the POSIX ...
List any dependencies that are required for this change.
**Describe your solution**
A clear and concise description of what you have …
=> Corrected build error in rx65n_sbram.c

.github/workflows/build.yml, .github/workflows/check.yml
I had to bring some other commits to avoid conflicts.
I could have copied the latest change, but I wanted to keep master's history.
Once this one is merged, I'll rebase #849
=> Backport CI changes to releases/9.0

include/nuttx/mm/mm.h, mm/mm_heap/mm_initialize.c
=> Backport #843 to releases/9.0

sched/timer/timer_gettime.c
fix a bug :change the timer->pt_last to timer->pt_delay,
Following the guidelines for writting good commit messages (https://chris.beams.io/posts/git-commit/) and creating a meaningful title is key in effective team communication.
**do's**
- stm32h7:  Add SDMMC Support
- nsh:  Separate `source` and `sh` for POSIX compliance
- nxstyle:  Fixed Camel case detection
- drivers/serial:  Fixed style violation
**dont's**
- fixed bug
- nxstyle
- PR #12
**Describe problem solved by the PR**
A clear and concise description of the problem, if any, this PR will solve. Please also include relevant motivation and context: E.g. The current nsh sh command violates the POSIX ...
List any dependencies that are required for this change.
**Describe your solution**
A clear and concise description of what you …
=> fix a bug in timer_gettime.c

README.txt
* Add INTRODUCTION section with a brief summary of Apache NuttX
(Incubating), a link to documentation at the project wiki, and
a note about the project's incubation status. Most of this
text is copied from the project website, with some minor edits
for this README format.
* Add COMMUNITY section with information on Getting Help, the
project's Mailing Lists, Issue Tracker, Source Code, and
Website Source Code. Like the text in INTRODUCTION, most of
this text is copied from the project website, with some minor
edits for this README format.
* Update download and GIT locations.
=> README.txt: Address issues raised in -RC0 review

NOTICE
NOTICE: Move "This product includes software developed at the ASF” to the top
=> Modify NOTICE

tools/README.txt, tools/zipme.sh
Simplify the version handling.
=> tools/zipme.sh: Let major.minor.patch argument optional

.github/workflows/build.yml, boards/xtensa/esp32/esp32-core/scripts/Make.defs, libs/libnx/nxfonts/Make.defs, libs/libnx/nxfonts/Makefile.sources, tools/Makefile.unix, tools/Makefile.win, tools/refresh.sh, tools/testbuild.sh
=> build.yml: Remove -G from cibuild.sh command line

arch/arm/src/arm/up_allocpage.c, boards/arm/lpc31xx/ea3131/locked/Makefile, sched/paging/Make.defs
ea3131:pgnsh could build successfully.
=> Fix buildbreak

Kconfig, libs/libc/builtin/Kconfig, libs/libc/dlfcn/Kconfig, libs/libc/wqueue/Kconfig, mm/Kconfig, sched/Kconfig
=> Kconfig: Refine BUILD_FLAT, BUILD_PROTECTED and BUILD_KERNEL usage

sched/paging/pg_worker.c
=> sched/paging: Fix error: variable 'result' set but not used

arch/arm/src/sama5/sam_tsd.c
=> sama5/sam_tsd: Fix error: 'ret' may be used uninitialized

fs/hostfs/hostfs_rpmsg_server.c, include/errno.h
=> rpmsg/hostfs: fix the warning found by https://github.com/apache/incubator-nuttx-testing/pull/37

.asf.yaml, .github/workflows/build.yml
=> Refine the github related setting

arch/arm/src/cxd56xx/Make.defs, arch/risc-v/src/nr5m100/chip.h, boards/arm/cxd56xx/spresense/src/cxd56_ostest.c
Remove the not existent CONFIG_XXX_CMNVECTOR
Hopefully it should not change original behavior of existent code
Verify it still working if your board is affected
=> Remove the not existent CONFIG_XXX_CMNVECTOR

Documentation/NuttxUserGuide.html, binfmt/binfmt_exec.c, binfmt/binfmt_execmodule.c, boards/arm/lpc17xx_40xx/pnev5180b/src/lpc17_40_symtab.c, fs/vfs/fs_close.c, fs/vfs/fs_fcntl.c, fs/vfs/fs_ioctl.c, fs/vfs/fs_lseek.c, fs/vfs/fs_poll.c, fs/vfs/fs_stat.c, include/errno.h, include/nuttx/binfmt/binfmt.h, include/nuttx/fs/fs.h, libs/libc/libc.csv, sched/errno/Make.defs, sched/errno/errno_errno.c, sched/errno/errno_get.c, sched/errno/errno_set.c, sched/pthread/pthread_create.c, sched/task/task_create.c, sched/task/task_exit.c, sched/task/task_init.c, sched/task/task_posixspawn.c, syscall/syscall.csv
Will be used in the furture patch to clean up errno usage
No
=> Add nx_ variant for fs API

libs/libc/stdio/lib_vasprintf.c
VA_LIST is getting clobbered because it is a pointer to a structure
on the stack and we must traverse it twice.  Clone it like we do
for x86_32
This was first noticed using the `ps` command.
Correct output is now generated by the `vasprintf` function on x86_64.
From NSH I was able to run `ps` and not have the print output corrupted.
=> x86_64: Make sure to clone ap list in vasprintf

openamp/libmetal.defs
=> openamp: Fix libmetal build break for arm

tools/LibTargets.mk, tools/mksyscall.c
=> Unify the fixed and variable arguments process

net/tcp/tcp_conn.c
tcp/conn: request arp before the 3-way handshake
Since the request address was not properly resolved before the handshake,
every time of connection, the handshake data will be overwitten into
arp packet and retransmitted until the next tcp timer.
Request the arp address before the handshake to avoid the retransmission.
Change-Id: I80118b9a8096c126c8e16cdf2f7b3d98fca92437
=> tcp/conn: request arp before the 3-way handshake

include/sys/syscall_lookup.h, sched/sched/sched.h, sched/sched/sched_mergepending.c, sched/sched/sched_mergeprioritized.c, sched/sched/sched_roundrobin.c
PRs 1017 and 1018 messed up some spacing in a few places.  This PR fixes those.
None
N/A
=> Fix minor spacing problems from 1017 and 1018

drivers/mtd/filemtd.c
=> drivers/mtd/filemtd.c: fix build error

arch/arm/src/cxd56xx/cxd56_dmac.c, arch/arm/src/cxd56xx/cxd56_spi.c, boards/arm/cxd56xx/common/src/cxd56_gs2200m.c, drivers/wireless/gs2200m.c
- Recently I noticed that GS2200M driver does not use SPI-DMA on Spresense.
- This PR consists of 3 commits.
- The first commit is regarding cxd56_spi.c and cxd56_dmac.c which I had to merge the latest ones from Spresense SDK1.5.1 to avoid SPI-DMA bug.
- The second commit is to enable SPI-DMA in board specific file (i.e. cxd56_gs2200m.c). Because SPI-DMA is disabled by default even though it is enabled in defconfig. (NOTE: For STM32F4Discovery, we can enable SPI-DMA by defconfig only)
- The final commit is to improve performance for gs2200m driver so that it can handle multiple incoming packet in work queue handler.
- This PR affects GS2200M configurations such as (spresense:wifi, stm32f4discovery:wifi) 
- I tested this PR with spresense:wifi and stm32f4discovery:wifi
=> Add SPI-DMA support to spresense with gs2200m

arch/sim/src/sim/up_internal.h, arch/sim/src/sim/up_netdriver.c, arch/sim/src/sim/up_tapdev.c, net/netdev/netdev_register.c, net/tcp/tcp_accept.c, net/udp/udp_recvfrom.c
netdev/register: configurable net packet size
sim/tapdev: follow the tunnel MTU size
net: remove unnecessary spaces
=>  sim/tapdev: follow the tunnel MTU size

net/netdev/netdev_ioctl.c
update after LIBC_IOCTL_VARIADIC removal.
=> netdev_ioctl: Update a comment

libs/libc/netdb/Kconfig, libs/libc/netdb/lib_gethostentbynamer.c
=> getaddrinfo related improvements

net/netdev/netdev_register.c
This commit adds some short comments to explain some perplexing logic of PR #1047.
None
N/A
=> net/netdev/netdev_register.c:  Add some comments.

arch/arm/include/armv8-m/irq_cmnvector.h, arch/arm/include/armv8-m/irq_lazyfpu.h, arch/arm/src/armv8-m/Kconfig, arch/arm/src/armv8-m/arm_exception.S, arch/arm/src/armv8-m/arm_initialstate.c, arch/arm/src/armv8-m/arm_lazyexception.S
armv8-m: Add stack overflow by stack pointer limit register
Signed-off-by: qiaowei <qiaowei@xiaomi.com>
Change-Id: I0f0ae0fb8edb8e1690b3c5e3e8b3189d51a318b0
=> armv8-m: Add stack overflow by stack pointer limit register

arch/risc-v/src/common/riscv_usestack.c, arch/sim/src/sim/up_usestack.c, arch/xtensa/src/common/xtensa.h, arch/xtensa/src/common/xtensa_createstack.c, arch/xtensa/src/common/xtensa_usestack.c
complete logic in create/use stack to support stack coloration.
=> arch: complete logic in create/use stack to support stack coloration.

tools/mkexport.sh
to avoid the duplication in apps/imports/Make.defs
=> build: mkexport.sh copy Config.mk to tools folder too

arch/arm/src/stm32/stm32_serial.c
nxstyle fixes in arch/arm/src/stm32/stm32_serial.c, mostly for long lines.
No functional changes.
File passes nxstyle.
=> stm32: serial: nxstyle fixes

boards/arm/stm32/olimex-stm32-p407/src/olimex-stm32-p407.h, tools/LibTargets.mk, tools/Makefile.unix, tools/Makefile.win
Update make dependency based on @yamt https://github.com/apache/incubator-nuttx/pull/707
=> Redo "Fix make target dependencies"

arch/arm/src/stm32/hardware/stm32_adc_v2.h, arch/arm/src/stm32/hardware/stm32_i2c_v2.h, arch/arm/src/stm32/hardware/stm32_tim.h
arch/arm/src/stm32/hardware/stm32_adc_v2.h
arch/arm/src/stm32/hardware/stm32_i2c_v2.h
arch/arm/src/stm32/hardware/stm32_tim.h
* nxstyle fixes, mostly long lines and misaligned comments
Removes numerous nxstyle errors. No functional changes.
Changes pass nxstyle.
=> stm32: nxstyle fixes

arch/arm/src/stm32h7/stm32_ethernet.c
I think the uid port to H7 followed the Ethernet on the time line, so using the UUID for MAC was omitted.
=> stm32h7:ethernet Use UUID for MAC

tools/mkdeps.c
=> tools/mkdeps: Always look in the current directory

arch/arm/src/tiva/Make.defs, arch/arm/src/tiva/common/tiva_idle.c
- This PR introduces tiva_idle.c 
- This PR affects tiva platform.
- I tested this PR with lm3s9665-ek:discover with QEMU.
=> arch: tiva: Introduce tiva_idle.c

fs/vfs/fs_stat.c
=> fs/vfs/fs_stat.c: correct style

drivers/usbhost/usbhost_ft232r.c
Cosmetic changes to alignment.  Also fixes some C89 non-compliance.  Sorry to be so OCD.
=> drivers/usbhost/usbhost_ft232r.c:  Cosmetic

arch/arm/src/stm32h7/stm32_spi.c
1) 574b25 broke the internal DMA buffers usage that solved the following problem: The DMA capable interface does not know the buffers extent. It calculates it from size.  The user may need to transfer less than a cacheline bytes,  but STILL have a DMA capable buffer. The user is therefore
forced to transfer more data then needed to "trick" the  DMA capable function. This is a wast of bus bandwidth and may not work will all devices. The internal buffer, solve this issue.
2) Reduce clock sag while chip selected: The H7 tri-states the clock output on SPI disable and unfortunately the Chip Select (CS) is active.  So we keep the device disabled for the minimum time, that meets the DMA setup sequence criteria. If the clock line is not loaded, the may an issues, it the CLK line is loaded at < …
=> stm32h7:stm32_spi Restores internal DMA buffer broken in 574b25 and improvements.

fs/fat/fs_fat32.c
=> Do not rewrite the root directory if it has not changed

fs/fat/fs_fat32.c, fs/fat/fs_fat32.h, fs/fat/fs_fat32attrib.c, fs/fat/fs_fat32dirent.c, fs/fat/fs_fat32util.c
Run all .c and .h files through nxstyle and correct all reported issues.
None expected
Verifed using sim:nsh
=> fs/fat:  Run all .c and .h files through nxstyle

drivers/wireless/gs2200m.c
- This PR introduces a new flow control based on total bulk size in gs2200m.c
- In previous implementation, flow control was done based on packet queue size.
- However, packet size was not considered in the queue.
- This PR affects gs2200m driver.
- I tested this PR with spresense:wifi (dhcp client, telnetd, webserver, wget, nxplayer)
=> drivers: wireless: New flow control based on total bulk size in gs2200m.c

net/inet/inet_sockif.c
=> Correct debugassertion in inet_sockif

include/stdint.h
=> stdint.h: Fix a comment

include/threads.h
And fix the minor typo error
Change-Id: Ic554b51beb7430db08f9c8a02798bc53eb998f5e
=> threads.h: Support mtx_timedlock and recursive mutex

libs/libc/stdio/lib_libvsprintf.c
=> Implement %ju/%jd printf format

arch/sim/src/sim/up_hostfs.c
Don't forget to convert the host convention (-1/errno) to
the nuttx kernel convention. (negative errno)
=> sim: Fix hostfs errno

drivers/audio/cxd56.c
Replace semaphore with spinlock in the DMA buffer handling code
since it is called from an interrupt.
CXD56 (spresense board)
spresense board
=> cxd56: Fix lock issue in Spresense audio driver

include/nuttx/sched.h, sched/task/task_atexit.c, sched/task/task_exithook.c, sched/task/task_onexit.c
=> Simplify atexit and onexit code logic

arch/arm/src/cxd56xx/cxd56_adc.c, arch/arm/src/stm32/stm32_hrtim.c
This PR is for files under arch/, please refer to https://cwiki.apache.org/confluence/display/NUTTX/ENOTTY+ioctl%28%29+Return+Value for details.
=> ioctl function should return ENOTTY when the command is not recognized.

boards/arm/lpc17xx_40xx/u-blox-c027/src/lpc17_40_ubxmdm.c
Fix lpc17_40_ubxmdm.c board driver to return -ENOTTY
Minor/None
=> Fix lpc17_40_ubxmdm.c board driver to return -ENOTTY

arch/arm/include/inttypes.h, arch/avr/include/avr/inttypes.h, arch/avr/include/avr32/inttypes.h, arch/hc/include/inttypes.h, arch/mips/include/inttypes.h, arch/misoc/include/inttypes.h, arch/or1k/include/inttypes.h, arch/renesas/include/m16c/inttypes.h, arch/renesas/include/rx65n/inttypes.h, arch/renesas/include/sh1/inttypes.h, arch/risc-v/include/inttypes.h, arch/sim/include/inttypes.h, arch/x86/include/i486/inttypes.h, arch/x86_64/include/intel64/inttypes.h, arch/xtensa/include/inttypes.h, arch/z16/include/inttypes.h, arch/z80/include/ez80/inttypes.h, arch/z80/include/z180/inttypes.h, arch/z80/include/z8/inttypes.h, arch/z80/include/z80/inttypes.h, include/stdint.h
and move PRIxMAX and SCNxMAX to common place
=> Add INTx_C macro defintion

drivers/analog/dac.c, drivers/leds/ncp5623c.c, drivers/leds/pca9635pw.c, include/nuttx/leds/pca9635pw.h
Fix some drivers mode privileges.  It's not used but it's better to get it right.
The change should have no impact.
=> Fix the mode priviliges when registring a driver

drivers/usbhost/Kconfig, drivers/usbhost/Make.defs, drivers/usbhost/usbhost_cdcmbim.c, include/nuttx/net/net.h, include/nuttx/usb/cdc.h, net/Kconfig, net/netdev/netdev_register.c
Add support to CDC-MBIM USB host driver
This driver was created by Adam Porter and posted on NuttX
mailing list at Google Group on Nov 14 2019
USB and NET modifications
In progress
=> Add support to CDC-MBIM USB host driver

mm/kmm_heap/kmm_mallinfo.c
build fix after https://github.com/apache/incubator-nuttx/pull/1236
CI
=> Add a missing stdlib.h -> malloc.h change for mallinfo

sched/pthread/pthread_cancel.c, sched/signal/sig_default.c, sched/task/Make.defs, sched/task/task.h, sched/task/task_cancelpt.c, sched/task/task_delete.c, sched/task/task_setcancelstate.c
=> sched: Consolidate the cancellation notification logic

drivers/audio/cxd56.c
- In the previous implementation, cxd56_stop() checked the internal
state before sending AUDIO_MSG_STOP to the message queue. However,
if the worker thread took time to turn on AMP, cxd560_stop() was
not able to send the message and caused a deadlock.
- This commit fixes this issue by always sending AUDIO_MSG_STOP
regardless of the internal state.
- This PR affects cxd56.c audio driver.
- I tested this PR with nxrecorder and nxplayer with spresense.
=> drivers: audio: Fix cxd56_stop in cxd56.c

drivers/syslog/note_driver.c
=> drivers/syslog/note_driver.c: nxstyle fix

arch/arm/src/kinetis/kinetis_enet.c
After 20 mn to an hr, the device would not respond to ping.
Initial issue was filed in [PX4 here](https://github.com/PX4/Firmware/issues/15036)
When any error was detected the buffers descriptors were
blindly initialized. This caused the TX of the MAC to
be in a bad state. The correct thing to do, we disable
the MAC, init the bufffers and re-eanable the MAC.
The interrupts were being throttled at the NVIC. This been cleaned up.
The Interfaces will now work if there are any errors in the data, It could be induced by unplugging a cable on on a switch (not connected to the device)
Test we done on nxp_fmuk66. [See](https://github.com/PX4/Firmware/issues/15036#issuecomment-645206980)
=> kinetis:Ethernet fixed & better interrupt management

ReleaseNotes
Update ReleaseNotes in preparation for the 9.1 release.
N/A
N/A
=> Update ReleaseNotes in preparation for the 9.1 release.

Documentation/NuttX.html, Documentation/README.html, README.txt, boards/README.txt
=> [Backport PR-1277] Document new support for STM32G474 and B-G474E-DPOW1

tools/Makefile.export, tools/mkexport.sh
build/export: correct the export path
make/export: copy mkdeps.c for export build
make/export: do not extract object from librarys
make/export: support export extra library 
make export enhance
=> make/export: support export extra library 

arch/arm/src/stm32l4/stm32l4x6xx_rcc.c
Flash wait states setting on STM32L4 clock configuration routine was done too late: MSI clock range selection was being performed before this, which means that using MSI as system clock (the default) but requesting a higher frequency would lead to use a number of wait states equal to zero (the default) until the wait states setting code was reached. This led to corruption of execution state, which was actually only observed on non-optimized code (possibly due to the longer execution time between clock increase and flash configuration). This changes moves flash configuration to the top of the clock configuration routine.
STM32L4 on non-default MSI frequency as system clock.
Tested on STM32L476.
=> stm32l4 RCC: configure flash wait states early

tools/nxstyle.c
and add _Exit to the white list
Fix issue: https://github.com/apache/incubator-nuttx/issues/1235
=> tools/nxstyle: Support the white list

TODO
Remove an issues that has recently be resolved.
None.. this effects documentation only
N/A
=> Udate TODO List

arch/sim/src/nuttx-names.in
Change-Id: I81e75532db1953584124142763f9d07ddb788898
=> sim: add __cxa_atexit into the name list

boards/arm/imxrt/imxrt1050-evk/include/board.h, boards/arm/imxrt/imxrt1060-evk/include/board.h
Fix LCD pins to work correctly
None
With LVGL demo
=> Fix LCD pins to work correctly

include/nuttx/arch.h
Just some typos correction.
N/A
N/A
=> include/nuttx/arch.h:  Trivial typo fixes.

drivers/can/can.c, include/nuttx/can/can.h
As described in
https://github.com/apache/incubator-nuttx/issues/1354#issuecomment-654436457
=> Fix issues with semaphores in can driver

boards/arm/imxrt/imxrt1050-evk/configs/libcxxtest/Make.defs, boards/arm/imxrt/imxrt1060-evk/configs/libcxxtest/Make.defs, boards/arm/lpc43xx/bambino-200e/configs/netnsh/Make.defs, boards/arm/stm32/stm32f4discovery/README.txt, boards/arm/stm32/stm32f4discovery/configs/cxxtest/Make.defs, boards/arm/stm32/stm32f4discovery/configs/testlibcxx/Make.defs, boards/arm/stm32l4/nucleo-l476rg/scripts/Make.defs, boards/sim/sim/sim/README.txt, boards/sim/sim/sim/configs/cxxtest/Make.defs, boards/sim/sim/sim/configs/cxxtest/defconfig, libs/libxx/Kconfig, libs/libxx/Makefile, libs/libxx/cxx.defs
code just need check CONFIG_CXX_EXCEPTION/CONFIG_CXX_LIBSUPCXX now,
instead uClibc++/libc++ specific config
No functionality change.
=> libxx: Unify uClibc++ and libc++ config

include/sys/statvfs.h, include/sys/types.h, libs/libc/unistd/Make.defs, libs/libc/unistd/lib_fstatvfs.c, libs/libc/unistd/lib_statvfs.c
specified here:
https://pubs.opengroup.org/onlinepubs/009695399/basedefs/sys/statvfs.h.html
Add statvfs/fstatvfs, but no other code change.
=> fs/vfs: Implement statvfs and fstatvfs

arch/arm/src/imxrt/hardware/imxrt_gpio.h, arch/arm/src/imxrt/imxrt_gpio.h, arch/arm/src/imxrt/imxrt_gpioirq.c, boards/arm/imxrt/imxrt1060-evk/src/imxrt1060-evk.h, boards/arm/imxrt/imxrt1060-evk/src/imxrt_bringup.c, boards/arm/imxrt/imxrt1060-evk/src/imxrt_buttons.c
Add buttons support to iMXRT1060
None
iMXRT1060-EVK
=> Add buttons support to iMXRT1060

tools/checkrelease.sh
- checkrelease.sh script now builds sim:nsh
- usage has changed to use command line options
- can check a directory on disk as well as a URL or release name
- none if you don't use the script
- script usage options have changed
```
Usage: /home/adam/src/nuttx/nuttx-sama5d3-xplained/nuttx/tools/checkrelease.sh [--verbose] [--gpg-output] [--url <URL-of-release-dir>] [--release <name-of-release] [--dir <path-to-directory>] [--tempdir <path-to-directory>]
Given release full URL, release name, or a local directory, downloads or copies
all files in that directory (which for a release should include nuttx and nuttx-apps, sha512, 
asc, and tar.gz files), checks the release SHA512 and GPG signatures, checks the unpacked 
directories for required files, and tries to build NuttX for sim:nsh.
If …
```
=> checkrelease.sh script now tries to build sim:nsh

tools/checkrelease.sh
The method is suggested by @btashton here: https://github.com/apache/incubator-nuttx/pull/1382
=> tools/checkrelease.sh: auto import KEYS from the release server

boards/avr/atmega/arduino-mega2560/src/Makefile, boards/renesas/m16c/skp16c26/src/Makefile, boards/renesas/rx65n/rx65n-grrose/src/Makefile, boards/renesas/rx65n/rx65n-rsk1mb/src/Makefile, boards/renesas/rx65n/rx65n-rsk2mb/src/Makefile, boards/renesas/rx65n/rx65n/src/Makefile, boards/renesas/sh1/us7032evb1/src/Makefile
=> board: Let avr/renesas utilize boards/Board.mk

arch/arm/src/arm/Toolchain.defs, boards/arm/stm32/stm32f4discovery/scripts/Make.defs, boards/arm/stm32f7/stm32f746g-disco/scripts/Make.defs
Minor fix in CPP and ARCHCFLAGS target/machine arguments from PR #1426
Minor
=> Minor fix in CPP and ARCHCFLAGS arguments from PR #1426

net/socket/getpeername.c, net/socket/getsockname.c, net/socket/recvfrom.c, net/socket/send.c, net/socket/sendto.c
* Add sanity checks in socket interface
* Fix nxstyle issue
Tested by spresense:wifi
=> Fix sanity checks

arch/arm/src/stm32f7/stm32_dma.c
=> arch/arm/src/stm32f7/stm32_dma.c: fix debug ifdef

tools/incdir.c
=> tools/incdir: Fix the memory leak

drivers/lcd/Kconfig, graphics/Kconfig
See the commit message for more info
No functionality change
=> Minor fix for lcd's Kconfig

drivers/video/fb.c
=> drivers/video: fb_read/fb_write need consider the current file position

arch/sim/src/sim/up_simsmp.c
The main change is used semaphore to notify the idle thread finish the initialization instead of mutex.
No
=> arch/sim: Minor SMP code fix

drivers/syslog/Kconfig, drivers/syslog/ramlog.c
Add new buffer handling option to RAM log feature.
Tested by spresense board
=> ramlog: Add overwrite option to ramlog

arch/xtensa/src/esp32/Kconfig, arch/xtensa/src/esp32/Make.defs, arch/xtensa/src/esp32/esp32_i2c.c, arch/xtensa/src/esp32/esp32_i2c.h, arch/xtensa/src/esp32/hardware/esp32_i2c.h
This driver was implemented by Dong Heng <dongheng@espressif.com>
and modified to fix coding style by Alan Carvalho de Assis.
Add I2C to ESP32
ESP-WROVER-KIT
=> ESP32: Add driver support to I2C

drivers/syslog/syslog_write.c, fs/driver/fs_blockproxy.c
Fix a few issues found by clang-check
They look like real bugs
CI only
=> Fix a few issues found by clang-check

fs/mqueue/mq_close.c, libs/libc/modlib/modlib_sections.c, libs/libc/stdio/lib_libfread.c, net/devif/devif_callback.c, net/icmp/icmp_recvfrom.c, sched/sched/sched_waitpid.c
fix random issues reported by clang-check
the one in icmp_recvfrom might be serious
(i haven't investigated if it can actually be triggered)
compile tested only
=> Fix random issues reported by clang-check

boards/arm/cxd56xx/common/src/cxd56_imageproc.c, boards/arm/cxd56xx/drivers/camera/isx012.c, boards/arm/cxd56xx/spresense/include/cxd56_imageproc.h, drivers/video/video.c, include/nuttx/video/isx012_reg.h, include/nuttx/video/video_controls.h
- Add features on CXD5602 image processing driver
- Fix bugs ISX012 image sensor
Tested by Spresense board
=> Fix video driver

arch/sim/src/sim/up_exit.c, drivers/usbhost/hid_parser.c, net/tcp/tcp_timer.c
Random fixes for issues reported by clang-check
None of these seems critical
Compile tested only
=> Random fixes for issues reported by clang-check

include/strings.h, libs/libc/string/Make.defs, libs/libc/string/lib_index.c, libs/libc/string/lib_rindex.c
to avoid the confliction with the same name variable, report here: https://github.com/apache/incubator-nuttx/issues/1511
=> libc: Change index/rindex from macro to function

include/nuttx/wireless/gs2200m.h
Add flags member to take recv() flags from daemon.
not tested.
=> wireless: gs2200m: Add flags member

Documentation/NuttxPortingGuide.html
SocketCAN device driver documentation
=> Added SocketCAN Device driver porting guide

tools/gencromfs.c
=> tools/gencromfs: Change the generated code to Apache license

arch/sim/src/sim/up_framebuffer.c, drivers/lcd/Kconfig, drivers/lcd/lcd_framebuffer.c, drivers/video/Kconfig, drivers/video/fb.c, graphics/Kconfig, graphics/nxbe/Make.defs, graphics/nxbe/nxbe.h, graphics/nxbe/nxbe_bitmap.c, graphics/nxbe/nxbe_configure.c, graphics/nxbe/nxbe_fill.c, graphics/nxbe/nxbe_filltrapezoid.c, graphics/nxbe/nxbe_move.c, graphics/nxbe/nxbe_notify_rectangle.c, graphics/nxbe/nxbe_setpixel.c, graphics/vnc/server/Kconfig, graphics/vnc/server/vnc_fbdev.c, graphics/vnc/server/vnc_server.h, include/nuttx/nx/nx.h, include/nuttx/nx/nxglib.h, include/nuttx/video/fb.h, libs/libnx/nxglib/Make.defs, libs/libnx/nxglib/nxgl_area2rect.c, libs/libnx/nxglib/nxgl_rect2area.c
1.Expose the notification through fb_vtable_s::updatearea
2.Incorporate old nx_notify_rectangle into the new updatearea callback
3.Migrate the calle of nx_notify_rectangle to fb_vtable_s::updatearea
=> drivers/video: Refine the update region notification mechanism

drivers/wireless/gs2200m.c
- This commit is a workaround to avoid errors in gs2200m_send_cmd()
- See the actual sequence in Testing for details
- gs2200m driver
- Test with spresense:wifi
- 1-1 Run tcpclient on NuttX and run nc on Linux
- 1-2 Stop nc on Linux then tcpclient also stops
- 1-3 Run tcpclient then the first AT+NCTCP will fail
- 1-4 But the second AT+NCTCP will succeed
- 2-1 Run tcpclient on NuttX and run nc on Linux
- 2-2 Stop nc on Linux then tcpclient also stops
- 2-3 Run tcpserver then the first AT+NSTCP will fail
- 2-4 But the second AT+NSTCP will succeed
=> drivers: wireless: Add retry sequence in gs2200m_send_cmd()

sched/group/group_getgid.c, sched/group/group_getuid.c, sched/group/group_setgid.c, sched/group/group_setuid.c
=> sched/group: Fix the typo error

drivers/rptun/rptun.c, include/nuttx/rptun/rptun.h
=> Minor fix for rptun driver

arch/risc-v/src/rv32im/riscv_syscall.S
Replace spaces with a tab
hifive1-revb:nsh
on QEMU
=> arch/risc-v/src: Cosmetic change

arch/arm/src/cxd56xx/cxd56_farapi.c
- This commit adds SMP support to cxd56_farapi.c
- nxplayer now works in SMP mode
- Spresense in SMP mode only
- Add the following configs to spresense:wifi
```
+CONFIG_SCHED_INSTRUMENTATION=yy
+CONFIG_SCHED_INSTRUMENTATION_BUFFER=y
+CONFIG_SMP=y
+CONFIG_SMP_NCPUS=2
+CONFIG_SPINLOCK_IRQ=y
```
- Run nxplayer and play an WAV file on uSD card
- NOTE: http streaming playback would cause deadlocks
=> arch: cxd56xx: Add SMP support to cxd56_farapi.c

libs/libxx/.gitignore, libs/libxx/0001-libcxx-Port-to-NuttX-https-nuttx.apache.org-RTOS.patch, libs/libxx/Makefile, libs/libxx/libcxx.defs, libs/libxx/libxx_impure.cxx, libs/libxx/uClibc++.defs
See discussion here:
https://lists.apache.org/thread.html/r2c3b7d31cddec16ba31e50748207826bfe1908bc90d4dfc6e232144c%40%3Cdev.nuttx.apache.org%3E
=> libxx: Integrate libc++ latest official release

fs/littlefs/Make.defs
=> fs/littlefs: enable the low level log only on debug mode

drivers/mmcsd/mmcsd_sdio.c
When CONFIG_MMCSD_MULTIBLOCK_DISABLE is lit, all SD
read/write failed. The function return the number of
blocks in `ret`, set on entry to nsectors. That was
then wiped out by using the ret for the mmcsd_takesem.
Since the code had many path setting return, the choices for
the fix could have been add a new varaible or simple init it
were used. I choose the latter.
Since 2020-03-31 SD cards not using multi block (i.e with CONFIG_MMCSD_MULTIBLOCK_DISABLE) are broken.
was done on nxp_fmuk66-v3
Before PR
After PR:
mount is fine
=> mmcsd_sdio:Fix breakage from 997d4 SD not functional

include/nuttx/pthread.h, include/pthread.h, libs/libc/pthread/Make.defs, libs/libc/pthread/pthread_attr_getdetachstate.c, libs/libc/pthread/pthread_attr_setdetachstate.c, sched/pthread/pthread_create.c
specified here:
https://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_attr_getdetachstate.html
New API.
=> sched/pthread: Implement pthread_attr_[get|set]detachstate

fs/mqueue/mq_open.c
Signed-off-by: Esteban Zamora <esteban.zamora@hpe.com>
=> Fix inverted errno in mq_open

include/signal.h
improve the compatibility for glibc
New typedef
=> sched/signal: Add sighandler_t typedef

mm/mm_heap/Make.defs, mm/mm_heap/mm_malloc_usable_size.c
defined here:
https://man7.org/linux/man-pages/man3/malloc_usable_size.3.html
New API.
=> mm: Implement malloc_usable_size

fs/vfs/fs_epoll.c, include/sys/epoll.h
see here: https://linux.die.net/man/2/epoll_pwait
New API and flag
=> Implement epoll_pwait API and EPOLLONESHOT flag

arch/arm/src/stm32f7/stm32_can.c
this PR extends the support for RTR also in cases where the extended id is used.
=> RTR extension

arch/arm/src/cxd56xx/cxd56_rtc.c
- This commit improves cxd56_rtc performance in SMP mode.
- This commit affects SMP mode only.
- Tested with spresense:smp
=> arch: cxd56xx: Use spinlock API in cxd56_rtc.c

arch/xtensa/src/common/xtensa_idle.c
Remove "kludge" code that came from PIC32
Improve code quality
ESP32 Ethernet board
=> Remove "kludge" code that came from PIC32

libs/libc/unistd/Make.defs, libs/libc/unistd/lib_utimes.c
Add stub for utimes need by https://github.com/apache/incubator-nuttx-apps/pull/372
None
Tested on sim
=> libs/libc/time: Add stub for utimes

fs/tmpfs/fs_tmpfs.c
Signed-off-by: anatasluo <luolongjuna@gmail.com>
After testing, I am sure some codes here are redundant.
No impact
Check the logic here and do some simple tests to compare the addresses.
=> fs/tmpfs: Remove duplicated code

drivers/sensors/mpu60x0.c, include/nuttx/sensors/mpu60x0.h
Correct comments left behind by a previous PR.
N/A
N/A
=> drivers/sensors/mpu60x0.c: Correct comments.

INVIOLABLES.md
Fix a simple alignment and change occurrences of Nuttx to NuttX.
N/A
N/A
=> INVIOLABLES.md: Fix a simple alignment and change occurrences of Nuttx to NuttX.

arch/renesas/src/rx65n/rx65n_rtc.c
Resolved pre-check warnings in rx65n_rtc.c file.
=> RX65N RTC Pre-check Warnings Resolved

fs/vfs/fs_dupfd.c
Close the fd2 return by dup() would segment fault since filep->f_priv null access, while file_dup2 handle this rightly.
Test and verify under sim
=> fs/vfs: reuse file_dup2 directly in file_dup to fix segfault issue

arch/arm/src/tiva/common/tiva_adclib.c
arch/arm/src/tiva/common/tiva_adclib.c:
No functional changes.
nxstyle.
=> tiva: tiva_adclib.c: Fix nxstyle warnings

arch/sim/src/sim/up_tapdev.c
Change-Id: I8d5a176671f78464c057155edace5eabbb382c5c
=> arch/sim/src/sim/up_tapdev.c: fix compile error

arch/arm/src/cxd56xx/cxd56_gpioint.c
- This commit improves cxd56_gpioint performance in SMP mode.
- This commit affects SMP mode only.
- Tested with spresense:wifi_smp
=> arch: cxd56xx: Use spinlock API in cxd56_gpioint.c

arch/arm/src/tiva/common/tiva_eeprom.c
arch/arm/src/tiva/common/tiva_eeprom.c:
Removes nxstyle errors when this file receives maintenance.
nxstyle
=> tiva: tiva_eeprom.c: Fix nxstyle warnings

arch/arm/src/tiva/common/tiva_lowputc.c, arch/arm/src/tiva/common/tiva_qencoder.c
arch/arm/src/tiva/common/tiva_lowputc.c:
arch/arm/src/tiva/common/tiva_qencoder.c:
Removes nxstyle warnings.
nxstyle
=> tiva: tiva_lowputc.c, tiva_qencoder.c: Fix nxstyle warnings

sched/Kconfig, sched/sched/Make.defs, sched/sched/sched_note.c
follow up PR: https://github.com/apache/incubator-nuttx/pull/1746
=> sched: Refine the comment for SCHED_INSTRUMENTATION_EXTERNAL

arch/renesas/src/rx65n/rx65n_eth.c
Resolved RX65N pre-check warnings in rx65n_eth.c
=> RX65N Ethernet pre-check warnings resolved

arch/xtensa/src/esp32/esp32_spiflash.c, arch/xtensa/src/esp32/hardware/esp32_spi.h
- Cosmetic changes
- Comment out (actually #if 0) unused code.
- Remove an old license.
N/A
=> esp32_spiflash: Some cosmetic changes.

boards/xtensa/esp32/esp32-core/scripts/Make.defs, boards/xtensa/esp32/esp32-core/scripts/esp32.template.ld, boards/xtensa/esp32/esp32-core/src/Makefile
- Correct some some addresses in the linker script.
- Rename the linker script to add the .ld extension (this helps with auto highlighting with text editors.)
- Generate a Map file.
=> esp32-core: Update the linker script.

arch/renesas/src/rx65n/rx65n_cgc.c, boards/renesas/rx65n/rx65n-grrose/src/rx65n_bringup.c, boards/renesas/rx65n/rx65n-rsk2mb/src/rx65n_appinit.c
Pre-check warnings in RX65N resolved.
=> RX65N Pre-check Warnings Resolved

Documentation/reference/user/06_clocks_timers.rst, include/cxx/cunistd, include/stdio.h, include/sys/time.h, include/termios.h, include/unistd.h, libs/libc/time/Make.defs, libs/libc/time/lib_gethrtime.c, libs/libc/unistd/Make.defs, libs/libc/unistd/lib_getrlimit.c, libs/libc/unistd/lib_setrlimit.c
Add  gethrtime() and dummy getrlimit() setrlimit(), add some dependency
=> Add  gethrtime() and dummy getrlimit() setrlimit(), add some dependency

arch/arm/src/tiva/common/tiva_ssi.c
arch/arm/src/tiva/common/tiva_ssi.c:
Removes nxstyle warnings when this file receives maintenance.
nxstyle
=> tiva: tiva_ssi.c: Fix nxstyle warnings

fs/vfs/fs_rename.c, fs/vfs/fs_stat.c
=> fs: Call RELEASE_SEARCH to free resource in pseudorename

tools/Config.mk
=> tools/Config.mk: Replace tab with space

README.md
- link giant-board into board tree
- missed doing this in previous PR
- looked at text file
=> link giant-board into board tree

arch/arm/src/tiva/tiva_eeprom.h
arch/arm/src/tiva/tiva_eeprom.h:
Remove nxstyle warnings.
nxstyle.
=> tiva: tiva_eeprom.h: Fix nxstyle warnings

tools/configure.sh, tools/sethost.sh
=> configure.sh/sethost.sh: add set -e so that the script aborts on any error

CONTRIBUTING.md
CONTRIBUTING.md:
* Replace "you" with "your"
* Replace "this" with "these"
* Add one period
Text only. No functional changes.
Ran spelling checker.
=> CONTRIBUTING.md: Minor grammar fixes.

include/nuttx/wireless/wireless.h
nuttx/wireless: add wireless event member length helper 
wifi scan result (struct iw_event) reassembly.
verified on wireless driver module
```
static int wl_format_scan_results(struct wl_dev_s *priv, struct iwreq *iwr)
{
rtw_scan_result_t *cache;
struct iw_event *iwe;
char *start, *stop;
int i;
start = iwr->u.data.pointer;
stop = (char *)iwr->u.data.pointer + iwr->u.data.length;
for (i = 0; i < priv->scan_count; i++)
{
cache = &priv->scan_data[i];
iwe = (struct iw_event *)start;
iwe->cmd = SIOCGIWAP;
iwe->u.ap_addr.sa_family = ARPHRD_ETHER;
memcpy(&iwe->u.ap_addr.sa_data, cache->BSSID.octet, IFHWADDRLEN);
start = wl_iwe_add_event(start, stop, iwe, IW_EV_LEN(ap_addr));
iwe = (struct iw_event *)start;
iwe->cmd = SIOCGIWESSID;
iwe->u.essid.flags = 0;
iwe->u.essid.length = cache->SSID.len; …
```
=> nuttx/wireless: add wireless event member length helper 

arch/xtensa/src/common/xtensa_coproc.S, arch/xtensa/src/common/xtensa_cpuint.S, arch/xtensa/src/common/xtensa_cpupause.c, arch/xtensa/src/common/xtensa_int_handlers.S, arch/xtensa/src/esp32/esp32_start.c, arch/xtensa/src/lx6/Toolchain.defs
Trivial typos and style fixes found while browsing the code.
N/A
N/A
=> arch/xtensa: Few typos and style fixes.

libs/libc/unistd/lib_access.c
Specified here:
https://pubs.opengroup.org/onlinepubs/009695399/functions/access.html
access may return ERROR now
=> libc: Implement access function correctly

arch/arm/src/tiva/tiva_timer.h
arch/arm/src/tiva/tiva_timer.h:
nxstyle.
=> tiva: tiva_timer.h: Fix nxstyle warnings

arch/arm/src/tiva/tiva_ssi.h
arch/arm/src/tiva/tiva_ssi.h:
Removes nxstyle warnings.
nxstyle.
=> tiva: tiva_ssi.h: Fix nxstyle warnings

arch/renesas/src/rx65n/Kconfig, arch/renesas/src/rx65n/Make.defs, arch/renesas/src/rx65n/rx65n_cgc.c, arch/renesas/src/rx65n/rx65n_cgc.h, arch/renesas/src/rx65n/rx65n_definitions.h, arch/renesas/src/rx65n/rx65n_irq.c, arch/renesas/src/rx65n/rx65n_port.c, arch/renesas/src/rx65n/rx65n_usbdev.c, arch/renesas/src/rx65n/rx65n_usbdev.h, boards/renesas/rx65n/rx65n-grrose/README.txt, boards/renesas/rx65n/rx65n-grrose/include/rx65n_gpio.h, boards/renesas/rx65n/rx65n-grrose/src/rx65n_bringup.c, boards/renesas/rx65n/rx65n-grrose/src/rx65n_gpio.c, boards/renesas/rx65n/rx65n-rsk2mb/README.txt, boards/renesas/rx65n/rx65n-rsk2mb/include/rx65n_gpio.h, boards/renesas/rx65n/rx65n-rsk2mb/src/rx65n_bringup.c, boards/renesas/rx65n/rx65n-rsk2mb/src/rx65n_gpio.c
Added Support for USB Device Mode driver on RX65N
Porting the RX65N Device Mode driver
=> USB Device Mode Driver Support for RX65N

arch/arm/src/stm32f7/stm32_serial.c
When the Head to Tail relationship was H < T, then
only the tail to end of buffer was sent.
The fix is: In the txdma completion to do a second
the DMA operation using nbuffer if the nlength is
non zero.
stm32f7:serial UART5 use actual size
UART5 was using the CONFIG_UART5_TXBUFSIZE
not the UART5_TXBUFSIZE_ADJUSTED.
Since the buffer size was adjusted up, this
has no dcache implications.
If the UART5_TXBUFSIZE_ADJUSTED is larger
then CONFIG_UART5_TXBUFSIZE it will present
a larger usable buffer to the system's
serial driver.
master has critical data loss with TX DMA, this PR fixes that. 
PX4FMUv5X - serial test.
=> stm32f7:serial Bug Fix: Ensure next buffer is processed

arch/renesas/src/rx65n/Kconfig, arch/renesas/src/rx65n/Make.defs, arch/renesas/src/rx65n/rx65n_definitions.h, arch/renesas/src/rx65n/rx65n_dtc.c, arch/renesas/src/rx65n/rx65n_dtc.h, boards/renesas/rx65n/rx65n-grrose/src/rx65n_bringup.c, boards/renesas/rx65n/rx65n-rsk2mb/src/rx65n_bringup.c
RX65N DTC driver support added
Porting the RX65N DTC driver
=> RX65N DTC Driver Support Added

arch/xtensa/src/common/xtensa_sigdeliver.c
Fix task signal process preemption A0 modification error.
Fix issue:
```c
Task1 --> process
--> xtensa_context_save(S1)
--> s32i a0, a2, (4 * REG_A0)
--> rtcb->xcp.regs[REG_A0] = A0
Task preemption
Task2 --> Post signal to Task1
--> Wake up Task1
Task1 --> xtensa_sig_deliver
--> up_irq_enable()
--> Task preemption
Task preemption --> xtensa_context_save
--> rtcb->xcp.regs[REG_A0] = A0 of "xtensa_sig_deliver"
= _xtensa_sig_trampoline + 6
= "j 1b"
Process ...
Task1 --> xtensa_sig_deliver
--> xtensa_context_restore
--> xtensa_context_save(S1)
--> l32i a0, a2, (4 * REG_A0)
--> a0 = "j 1b"
--> ret
--> run "j 1b"
```
=> arch/xtensa: Fix task signal process preemption A0 modification error

.github/workflows/build.yml
Add Renesas pre-check for RX65N-GRROSE and RX65N-RSK2MB.
=> Add Renesas pre-check

arch/xtensa/include/esp32/irq.h, arch/xtensa/src/common/xtensa_assert.c, arch/xtensa/src/common/xtensa_exit.c, arch/xtensa/src/common/xtensa_sigdeliver.c, arch/xtensa/src/esp32/esp32_cpuint.c, arch/xtensa/src/esp32/esp32_irq.c
Fixing trivial typos while browsing the code.
N/A
N/A
=> arch/xtensa: Fix some typos and correct some comments.

sched/signal/sig_dispatch.c
Cosmetic changes
No impact
Build with hifive1-revb:nsh
=> sched/signal: Cosmetic changes

libs/libc/net/lib_inetntop.c
Endian-ness issues are mind boggling sometimes.  I have been confused by the logic in inet_ntop() a few times so I thought I would add some comments so that I (and others) will understand the endian-ness issues in the future.  No change to logic, only comments changed.
None.. only adds some comments.
N/A
=> Add some comments to inet_ntop()

sched/task/task_exit.c
- During Wi-Fi audio streaming test, I found a deadlock in nxtask_exit()
- Actually, nxtask_exit() was called and tried to enter critical section
- In enter_critical_section(), there is a deadlock avoidance logic
- However, if switched to a new rtcb with irqcount=0, the logic did not work
- Because the 2nd critical section was treated as if it were the 1st one
- Actually, it tried to run the deadlock avoidance logic
- But nxtask_exit() was called with critical section (i.e. IRQ already disabled)
- So the logic did not work as expected because up_irq_restore() did not enable the IRQ.
- This commit fixes this issue by incrementing irqcount before calling nxtask_terminate()
- Also it adjusts g_cpu_irqlock and g_cpu_lockset
- Affects SMP only
- Tested with spresense:wifi_smp (smp, ostest, …
=> sched: task: Fix nxtask_exit() for SMP

libs/libc/signal/sig_wait.c
=> libs/libc/signal/sig_wait.c: Fix a typo

boards/arm/kinetis/freedom-k64f/src/k64_buttons.c
More changes to come
Change-Id: Ie60fd97083c4bc1b5b631d2e812b93bff304760a
Signed-off-by: Philippe Coval <rzr@users.sf.net>
=> Close statement with semicolon in board_buttons

boards/arm/kinetis/freedom-k64f/include/board.h
Change-Id: I99429d0e6d8bccc18358465eb192e739bf82881a
Signed-off-by: Philippe Coval <rzr@users.sf.net>
=> freedom-k64f: Declare missing NUM_BUTTONS

libs/libxx/libcxx.defs
Switch rc1 to official release(11.0.0).
=> libxx: Switch the package downloading from 11.0.0.rc1 to 11.0.0

arch/arm/src/tiva/cc13xx/cc13xx_prcm.h
arch/arm/src/tiva/cc13xx/cc13xx_prcm.h:
nxstyle
=> tiva: Fix nxstyle warnings

Documentation/components/drivers/character/timer.rst
This PR adds detailed instructions on how to use the Timer Driver.
N/A
N/A
=> Documentation for the Timer Driver

arch/sim/src/Makefile
=> [BACKPORT-1949]sim: Fix make export

arch/arm/src/cxd56xx/cxd56_cpupause.c, boards/arm/cxd56xx/common/src/cxd56_gs2200m.c
=> [BACKPORT-1950]Fix spresense SMP

sched/task/task_exit.c
=> [BACKPORT-1951]sched: task: Fix nxtask_exit() for SMP

arch/arm/src/tiva/hardware/tiva_adc.h, arch/arm/src/tiva/hardware/tiva_ssi.h
arch/arm/src/tiva/hardware/tiva_adc.h,
arch/arm/src/tiva/hardware/tiva_ssi.h:
* Fix nxstyle errors.
nxstyle.
=> tiva/cc13xx: Fix nxstyle errors

Documentation/components/nxflat.rst, Documentation/components/nxgraphics/appendix.rst, Documentation/index.rst, Documentation/introduction/about.rst, Documentation/introduction/detailed_support.rst, Documentation/introduction/resources.rst, Documentation/introduction/supported_platforms.rst, Documentation/introduction/trademarks.rst
* Remove the wrong comment about 64bit sim
* Change 32bit arch to 64bit arch
* Format introduction/supported_platforms.rst
* Fix the broken link in introduction/
=> Correct the links in Documentation folder

libs/libc/stdio/lib_freopen.c
to avoid FILE pointer change after this commit:
commit b0797263ca2817cf536be8b843ac5b5aac5d4d9c
Author: Xiang Xiao <xiaoxiang@xiaomi.com>
Date:   Thu Aug 13 18:17:29 2020 +0800
libc/stdio: Allocate file_struct dynamically
1.Reduce the default size of task_group_s(~512B each task)
2.Scale better between simple and complex application
=> libc: Don't fclose and fopen file in freopen

arch/xtensa/src/esp32/esp32_dma.h, arch/xtensa/src/esp32/esp32_wlan.h
esp32: Fix a few #endif comments
only comments
i guess the CI is enough.
=> esp32: Fix a few #endif comments

arch/arm/src/a1x/a1x_serial.c, arch/arm/src/am335x/am335x_serial.c, arch/arm/src/cxd56xx/cxd56_serial.c, arch/arm/src/efm32/efm32_serial.c, arch/arm/src/imxrt/imxrt_serial.c, arch/arm/src/kinetis/kinetis_serial.c, arch/arm/src/lc823450/lc823450_serial.c, arch/arm/src/lpc17xx_40xx/lpc17_40_serial.c, arch/arm/src/nrf52/nrf52_serial.c, arch/arm/src/nuc1xx/nuc_serial.c, arch/arm/src/s32k1xx/s32k1xx_serial.c, arch/arm/src/sam34/sam_serial.c, arch/arm/src/sama5/sam_flexcom_serial.c, arch/arm/src/sama5/sam_serial.c, arch/arm/src/samv7/sam_serial.c, arch/arm/src/stm32/stm32_serial.c, arch/arm/src/stm32f7/stm32_serial.c, arch/arm/src/stm32h7/stm32_serial.c, arch/arm/src/stm32l4/stm32l4_serial.c, arch/arm/src/tiva/common/tiva_hciuart.c, arch/arm/src/tiva/common/tiva_serial.c, arch/arm/src/tiva/hardware/cc13x0/cc13x0_uart.h, arch/arm/src/tiva/hardware/cc13x2_cc26x2/cc13x2_cc26x2_uart.h, arch/arm/src/tiva/hardware/lm/lm_uart.h, arch/arm/src/tiva/hardware/tm4c/tm4c_uart.h, arch/arm/src/tms570/tms570_serial.c, arch/xtensa/src/esp32/esp32_serial.c
=> [BACKPORT-2040]arch: serial: fix all TCGETS retrieving zero baud rate

sched/signal/sig_procmask.c
=> sched/signal/sig_procmask.c: Fix a typo

sched/signal/sig_procmask.c
Remove an unnecessary variable
no impact
=> sched/signal/sig_procmask.c: Remove an unnecessary variable

libs/libc/string/lib_strsignal.c
=> libs/libc/string/lib_strsignal.c: Fix a comment

Documentation/introduction/detailed_support.rst
Fix non-working URL in documentation
Documentation
linkcheck
=> documentation: change non-working URL

fs/vfs/fs_epoll.c
modify return value of epoll_api according to  posix rule.
daily test
=> epoll_create: mofidy return value for epoll_create1

boards/sim/sim/sim/README.txt
Update simulator loadable/module/sotest configs readme accordingly.
=> sim: update loadable/module/sotest configs readme

libs/libxx/README.txt
This doc seems a bit outdated to me.
This commit is my best attempt to update it.
=> libxx: Update README

libs/libxx/cxx.defs, libs/libxx/libxx_delete.cxx, libs/libxx/libxx_deletea.cxx
=> libxx: fix/suppresss warnings

libs/libc/stdio/lib_fclose.c
See the disscussion here: https://github.com/apache/incubator-nuttx-apps/pull/425
=> libc: Skip close stdin/stdout/stderr in fclose

libs/libc/signal/sig_pause.c
=> libs/libc/signal/sig_pause.c: Fix a comment

tools/README.txt, tools/testbuild.sh
To fix the issue: https://github.com/apache/incubator-nuttx/issues/2094
The automation build
=> tools/testbuild.sh: Support the blacklist for the specific host

drivers/serial/Kconfig
=> drivers/serial/Kconfig: Fix typos

sched/signal/sig_default.c
=> sched/signal/sig_default.c: Fix a typo

arch/arm/src/stm32l4/stm32l4_adc.c, arch/arm/src/stm32l4/stm32l4_adc.h
Adds low level function to allow external event configuration for regular group.
=> STM32L4 ADC driver: extenal event configuration

drivers/wireless/gs2200m.c
Summary:
- This commit enables gs2200m driver re-associate to the access point when disassociated
Impact:
- Affects gs2200m only
Testing:
- Tested with spresense:wifi
@masayuki2009
=> gs2200m: Check disassociation from AP and enable rejoin

drivers/wireless/gs2200m.c
Summary:
- This commit enables gs2200m driver to get IWNWID/IWFREQ/IWSENS information
Impact:
- Affects gs2200m only
Testing:
- Tested with spresense:wifi
@masayuki2009
=> gs2200m: Add function to get IWNWID / IWFREQ / IWSENS information

sched/signal/sig_releasependingsigaction.c, sched/signal/sig_releasependingsignal.c
=> sched/signal: Fix typos

arch/xtensa/src/esp32/esp32_spiflash.c
SPI Flash driver uses global sem for all MTD。
Because all MTDs operate the main SPI Flash, so not only MTD internal function should be mutex, but also MTDs should be mutex.
Fix CPUs call different MTDs' functions operate SPI Flash without mutex protection.
SPI Flash file system testing.
=> xtensa/esp32: SPI Flash driver uses global sem for all MTD

arch/xtensa/src/esp32/Kconfig, arch/xtensa/src/esp32/Make.defs, arch/xtensa/src/esp32/esp32_partition.c, arch/xtensa/src/esp32/esp32_partition.h, boards/xtensa/esp32/esp32-core/src/esp32_bringup.c
Add Partition and OTA device.
Add new features about ESP32's partition and OTA management.
=> xtensa/esp32: Add Partition and OTA device

drivers/audio/cxd56.c, drivers/audio/cxd56.h
cleanup for the Spresense board audio implementation
Spresense board audio implementation
Compiled locally and tested on Spresense
=> drivers: audio: cxd56: cleanup for the spresense audio implementation

sched/sched/sched_waitpid.c
=> sched/sched/sched_waitpid.c: Fix a typo

arch/arm/src/imxrt/Kconfig, arch/arm/src/imxrt/imxrt_wdog.c, arch/arm/src/imxrt/imxrt_wdog.h
Based on work done by Jake Choy.
Adds lower-half driver implementation for Watchdog 1 for IMXRT family.
Does not affect existing watchdog code in imxrt_wdog.c
Builds clean and checkpatch.sh is also clean
=> arch/arm/src/imxrt: adds support for WDOG1

include/nuttx/mtd/mtd.h
Fixed coding style and some minor documentation issues in mtd.h
No change in functionality. Standards compliance.
No change in functionality. Standards compliance.
=> mtd.h: Coding style fixes and some more

tools/Makefile.unix, tools/Makefile.win
Backports #2221
Less shell noise at the end of build.
CI
=> [BACKPORT #2221] Avoid messing the final binary nuttx.(bin,hex,...) compilation msg

libs/libxx/0001-libcxx-Port-to-NuttX-https-nuttx.apache.org-RTOS.patch
All changes come from:
from YAMAMOTO Takashi <yamamoto@midokura.com>
See the dissussion here: https://github.com/apache/incubator-nuttx/pull/2111
=> libcxx: Update 0001-libcxx-Port-to-NuttX-https-nuttx.apache.org-RTOS.patch

arch/arm/src/stm32f7/stm32_qspi.c, arch/arm/src/stm32h7/stm32_qspi.c, arch/avr/src/avr32/up_exceptions.S, drivers/lcd/memlcd.c, drivers/serial/serial_dma.c, drivers/usbdev/cdcacm.c, fs/fat/fs_fat32.c, fs/hostfs/hostfs.c, fs/nxffs/nxffs.h, fs/nxffs/nxffs_unlink.c, fs/smartfs/smartfs_smart.c, include/nuttx/lcd/memlcd.h, include/nuttx/net/netconfig.h
Minor typo fixes and run few files through nxstyle
No functional change
=> Minor typo and nxstyle fixes

include/sys/uio.h
sys/uio: include-able from C++ files 
Include from C++ source code.
Compile pass if include from C++ code
=> sys/uio: include-able from C++ files 

Documentation/components/drivers/character/watchdog.rst, boards/xtensa/esp32/esp32-core/README.txt
This PR aims to add more details to the WDT documentation.
N/A
N/A
=> Documentation for Watchdog Timer Driver

libs/libc/stdio/lib_libvsprintf.c
Introduced by C99 for ptrdiff_t.
tested with a local app
=> lib_libvsprintf.c: Implement "t" modifier for printf

sched/pthread/pthread_join.c
- I noticed 'pthread_rwlock test' in ostest sometimes stops
- This issue happened with spresense:wifi_smp (NCPUS=4) and sim:smp
- Finally, I found an issue in pthread_join()
- In pthread_join(), sched_lock() is used to avoid pre-emption
- However, this is not enough for SMP
- Because another CPU would continue the pthread and exit sequences
- So we need to protect it with a critical section
- Affect SMP only
- Tested with ostest with the following configurations
- spresnese:smp
- spresense:wifi_smp (NCPUS=2, NCPUS=4)
- sabre-6quad:smp (QEMU)
- esp32-core:smp (QEMU)
- maix-bit:smp (QEMU)
- sim:smp
- lc823450-xgevk:rndis
=> sched: pthread: Fix pthread_join() for SMP

fs/vfs/fs_eventfd.c
eventfd: remove the unique minor limit
The unique minor limit of 255 will overflow easily in
some scenarios where eventfd needs to be create/destroy
frequently:
```
while (1)
{
fd = eventfd(0, 0);  // minor++
sleep(1);
close(fd);
}
```
remove the unique minor limit.
Change-Id: I0ea1c825ce9b542c883166cb3e72574455ffdd0d
eventfd create/destroy test.
=> eventfd: remove the unique minor limit

arch/arm/src/stm32/stm32_bbsram.h
arch/arm/src/stm32/stm32_bbsram.h:
* Fix nxstyle errors.
nxstyle
=> stm32/stm32_bbsram.c: Fix nxstyle errors

arch/arm/src/stm32h7/stm32_otghost.c
=> arch/arm/src/stm32h7/stm32_otghost.c: Fix undeclared "ret".

drivers/wireless/gs2200m.c, libs/libc/uuid/lib_uuid_from_string.c
extracted from https://github.com/apache/incubator-nuttx/pull/2319
=> Fix a few scanf format warnings

CONTRIBUTING.md
Mention the preferred commit message as "<keyword>: <message>"
Contributing document
N/A
=> CONTRIBUTING.md: talk about preferred commit message format

arch/arm/src/imxrt/imxrt_enet.c, drivers/net/Kconfig, include/nuttx/net/mii.h
Adds support for DP83825I PHY on i.MX RT MCU.
Tested on Teensy 4.1 board.
=> imxrt: Added support for DP83825I PHY

include/getopt.h, include/unistd.h, libs/libc/libc.csv, libs/libc/unistd/Make.defs, libs/libc/unistd/lib_getopt.c, libs/libc/unistd/lib_getopterrp.c
1.Support opterr variable
2.Support getopt_long
the getopt user get more functionality and compatibility automatically
=> libc: Enhance getopt function

TODO, arch/arm/src/common/arm_interruptcontext.c, boards/arm/imx6/sabre-6quad/README.txt, sched/irq/irq_csection.c
=> [BACKPORT #2346] Fix comments on armv7-a smp

TODO, arch/arm/src/armv7-a/arm_cpupause.c, arch/arm/src/cxd56xx/cxd56_cpupause.c, arch/arm/src/lc823450/lc823450_cpupause.c, arch/risc-v/src/k210/k210_cpupause.c, arch/xtensa/src/common/xtensa_cpupause.c
=> [BACKPORT #2348]Fix pause handler for SMP

binfmt/libelf/libelf_bind.c, binfmt/libelf/libelf_symbols.c, drivers/mtd/ftl.c, fs/nxffs/nxffs_cache.c, fs/nxffs/nxffs_open.c, fs/nxffs/nxffs_pack.c, fs/nxffs/nxffs_read.c, fs/nxffs/nxffs_reformat.c, fs/nxffs/nxffs_stat.c, fs/nxffs/nxffs_write.c, fs/romfs/fs_romfs.c, fs/romfs/fs_romfsutil.c, libs/libc/machine/arm/armv7-m/arch_elf.c, libs/libc/modlib/modlib_bind.c, libs/libc/modlib/modlib_symbols.c, sched/module/mod_modhandle.c
Extracted from https://github.com/apache/incubator-nuttx/pull/2347
=> Syslog format and nxstyle fixes

drivers/rc/lirc_dev.c
Fix bug about lirc_read
Normal reading.
daily test.
=> driver/rc: fix bug about lirc_read

tools/nuttx-gdbinit
Backport #2380 tools: Fix nuttx-gdbinit for armv7-m with FPU
Tested on STM32H7 with FPU
=> [BACKPORT #2380] tools: Fix nuttx-gdbinit for armv7-m with FPU

Documentation/quickstart/debugging.rst
I've improved the debugging section by describing the procedure of using openocd and gdb to have nuttx aware debugging.
Also, I removed the section about JTAG which I think is unnecessary as it describes a very specific tool and does not add much
to the documentation (also, it could be done via openocd).
Documentation
Local build
=> Documentation: improve debugging section

TODO, arch/arm/src/armv7-a/arm_cpupause.c, arch/arm/src/cxd56xx/cxd56_cpupause.c, arch/arm/src/lc823450/lc823450_cpupause.c, arch/risc-v/src/k210/k210_cpupause.c, arch/xtensa/src/common/xtensa_cpupause.c
=> [BACKPORT #2395]Revert "Fix pause handler for SMP"

arch/arm/src/arm/arm_dataabort.c, arch/arm/src/arm/arm_prefetchabort.c, arch/arm/src/arm/arm_syscall.c, arch/arm/src/arm/arm_undefinedinsn.c, arch/arm/src/armv7-m/arm_ramvec_initialize.c, arch/arm/src/efm32/efm32_timer.c, arch/arm/src/lpc17xx_40xx/lpc17_40_can.c, arch/arm/src/lpc17xx_40xx/lpc17_40_ethernet.c, arch/arm/src/lpc17xx_40xx/lpc17_40_sdcard.c, arch/arm/src/lpc17xx_40xx/lpc17_40_serial.c, arch/arm/src/lpc17xx_40xx/lpc17_40_ssp.c, arch/arm/src/lpc17xx_40xx/lpc17_40_usbhost.c, binfmt/libnxflat/libnxflat_bind.c, binfmt/libnxflat/libnxflat_load.c, drivers/can/can.c, drivers/mtd/m25px.c, drivers/net/dm90x0.c, drivers/usbdev/cdcecm.c, fs/binfs/fs_binfs.c, fs/nfs/nfs_util.c, fs/nfs/nfs_vfsops.c, fs/nfs/rpc_clnt.c, fs/unionfs/fs_unionfs.c, net/tcp/tcp_appsend.c, net/tcp/tcp_input.c, net/tcp/tcp_send_buffered.c
Extracted from https://github.com/apache/incubator-nuttx/pull/2347
=> Syslog format, variable name errors, nxstyle fixes

ReleaseNotes
This contains the release notes for the 10.0.0 release.
=> Add release notes for NuttX-10.0.0

ReleaseNotes
This brings the release notes from #2308 to the 10.0 branch.
=> [releases/10.0] Add release notes for NuttX-10.0.0

sched/signal/sig_allocpendingsigaction.c, sched/signal/sig_dispatch.c
Remove redundant checks
no impact, I think
=> sched/signal: Remove redundant checks

net/neighbor/neighbor_ethernet_out.c
Patch fixes following build error when
CONFIG_NET_IPv6 && !CONFIG_NET_ICMPv6 && CONFIG_NET_ETHERNET:
```
nuttx/staging/libnet.a(neighbor_ethernet_out.o): In function `neighbor_ethernet_out':
nuttx/net/neighbor/neighbor_ethernet_out.c:188: undefined reference to `icmpv6_solicit'
```
IPv6 without ICMPv6 is not very useful, but at least this patch
allows neighbor_ethernet_out() to be used with a packet socket or
with multicast address (point-to-point IPv6 links) even in that case.
=> net/neighbor/neighbor_ethernet_out.c: fix build error without ICMPv6

arch/arm/src/arm/arm_dataabort.c, arch/arm/src/arm/arm_prefetchabort.c, arch/arm/src/lpc43xx/lpc43_serial.c, arch/arm/src/lpc43xx/lpc43_ssp.c, arch/arm/src/lpc43xx/lpc43_timer.c, arch/arm/src/lpc54xx/lpc54_ethernet.c, arch/arm/src/lpc54xx/lpc54_i2c_master.c, arch/arm/src/lpc54xx/lpc54_lcd.c, arch/arm/src/nrf52/nrf52_pwm.c, arch/arm/src/nrf52/nrf52_spi.c, arch/arm/src/nrf52/nrf52_wdt_lowerhalf.c, arch/arm/src/stm32/stm32_adc.c, arch/arm/src/stm32/stm32_otghsdev.c, boards/arm/lpc214x/mcu123-lpc214x/src/lpc2148_spi1.c, boards/arm/lpc214x/zp214xpa/src/lpc2148_spi1.c, boards/arm/lpc214x/zp214xpa/src/lpc2148_ug2864ambag01.c, boards/arm/lpc43xx/bambino-200e/src/lpc43_ssp.c, boards/arm/stm32/stm32f103-minimum/src/stm32_lcd_backpack.c, boards/arm/stm32/stm32f334-disco/src/stm32_smps.c, drivers/sensors/max31855.c
Extracted from https://github.com/apache/incubator-nuttx/pull/2347
=> Fix syslog formats, nxstyle, and a missing semicolon

arch/xtensa/src/common/xtensa_createstack.c, arch/xtensa/src/common/xtensa_stackframe.c, arch/xtensa/src/common/xtensa_usestack.c, arch/xtensa/src/common/xtensa_window_vector.S, arch/xtensa/src/common/xtensa_windowspill.S
- Fix alignment in usestack and stackframe .
- Include ESP32 files through the chip symbolic link.
Impacts only Xtensa arch.
ostest.
=> Couple of Xtensa fixes

include/fixedmath.h
The comment was stating 16 bit for a 32 bit usecase
=> fix comment to match with #define

include/fixedmath.h
=> Fix nxstyle warning in include/fixedmath.h

arch/arm/src/stm32/stm32_pwm.c, arch/arm/src/stm32h7/stm32_pwm.c
The previous implementation didn't work properly when subsequent channels were not enabled (eg. CH1 and CH2 disabled, CH3 enabled).
stm32 and stm32h7 only. 
nucleo-f103rb/pwm
=> stm32/stm32h7: fix the configuration of PWM outputs when subsequent channels are not enabled 

tools/configure.c, tools/configure.sh
Also add custom board build with absolute path support in addtion
to relative path.
Verified with custom board with relative path and absolute path.
=> configure.sh: support custom board build config with absolute path

libs/libc/pthread/pthread_mutexattr_getprotocol.c
Modify the return value according to posix standard.
Daily test.
=> pthread_mutexattr_getprotocol: modify prototype

drivers/leds/ws2812.c
Complete or improve some explanations and fix some typos
I believe @btashton wrote this in the first place. Could you double-check whether the stuff I've fixed makes sense?
Thanks!
Just comments
Just comments
=> drivers/led/ws2812: fix comments

arch/xtensa/src/esp32/Kconfig, arch/xtensa/src/esp32/Make.defs, arch/xtensa/src/esp32/esp32_rt_timer.c, arch/xtensa/src/esp32/esp32_rt_timer.h, arch/xtensa/src/esp32/esp32_wifi_adapter.c, arch/xtensa/src/esp32/esp32_wifi_adapter.h, arch/xtensa/src/esp32/esp32_wlan.c, arch/xtensa/src/esp32/esp32_wlan.h, arch/xtensa/src/esp32/hardware/esp32_dport.h, boards/xtensa/esp32/esp32-core/src/esp32_bringup.c
Refactor ESP32 Wi-Fi driver.
1. increase UDP/TX throughput.
2. decrease packet lost
Using iperf to test TCP/UDP throughput.
=> xtensa/esp32: Refactor ESP32 Wi-Fi driver

include/sys/wait.h
- Follow the POSIX description.
- No impact as P_GID and P_PGID are not used.
- Built with hifive1-revb:nsh
=> include/sys/wait.h: Modify P_GID to P_PGID

arch/renesas/src/rx65n/Kconfig, arch/renesas/src/rx65n/Make.defs, arch/renesas/src/rx65n/rx65n_definitions.h, arch/renesas/src/rx65n/rx65n_hardware_setup.c, arch/renesas/src/rx65n/rx65n_usbhost.c, arch/renesas/src/rx65n/rx65n_usbhost.h, boards/renesas/rx65n/rx65n-grrose/README.txt, boards/renesas/rx65n/rx65n-grrose/src/rx65n_bringup.c, boards/renesas/rx65n/rx65n-grrose/src/rx65n_gpio.c, boards/renesas/rx65n/rx65n-rsk2mb/README.txt, boards/renesas/rx65n/rx65n-rsk2mb/src/rx65n_bringup.c, boards/renesas/rx65n/rx65n-rsk2mb/src/rx65n_gpio.c
RX65N USB Host Driver Support
Tested on RX65N Reference board
=> RX65N USB Host Driver Support

net/inet/ipv4_setsockopt.c
net/igmp: add MULTICAST_TTL support
setsockopt IPPROTO_IP  IP_MULTICAST_TTL
IGMP setsockopt IPPROTO_IP  IP_MULTICAST_TTL
=> net/igmp: add MULTICAST_TTL support

arch/arm/src/arm/arm_assert.c, arch/arm/src/armv7-m/arm_assert.c, arch/arm/src/lpc17xx_40xx/lpc17_40_can.c, arch/arm/src/stm32/stm32_adc.c, arch/arm/src/stm32f0l0g0/stm32_adc.c, arch/x86_64/src/common/up_assert.c, boards/arm/lpc214x/zp214xpa/src/lpc2148_spi1.c, drivers/video/ov2640.c, fs/spiffs/src/spiffs_core.c, include/debug.h, include/nuttx/compiler.h, include/syslog.h, libs/libc/machine/arm/armv6-m/arch_elf.c, libs/libc/machine/risc-v/rv64/arch_elf.c, wireless/bluetooth/bt_conn.c, wireless/bluetooth/bt_hcicore.c, wireless/bluetooth/bt_hcicore.h, wireless/bluetooth/bt_smp.c
=> Enable format check for syslog

tools/discover.py, tools/flash_writer.py, tools/ocdconsole.py
=> Remove unneeded semicolons from Python files

include/time.h, sched/clock/clock_getres.c, sched/clock/clock_gettime.c, sched/timer/timer_create.c
clock/time: add CLOCK_BOOTTIME definition 
N/A
N/A
=> clock/time: add CLOCK_BOOTTIME definition 

arch/arm/src/stm32/stm32l15xxx_rcc.c
arch/arm/src/stm32/stm32l15xxx_rcc.c:
* Fix nxstyle errors.
nxstyle
=> arch/stm32: Fix nxstyle errors

include/netinet/ether.h, libs/libc/net/Make.defs, libs/libc/net/lib_etheraton.c
libs/libc/net: implement ether_aton/ether_aton_r 
Reference here:
https://www.unix.com/man-page/linux/3/ether_aton
N/A
ether_ntoa() -> ether_aton()
ether_aton() -> ether_ntoa()
=> libs/libc/net: implement ether_aton/ether_aton_r 

include/fcntl.h, libs/libc/unistd/Make.defs, libs/libc/unistd/lib_posix_fallocate.c
as specified here:
https://pubs.opengroup.org/onlinepubs/007904875/functions/posix_fallocate.html
=> libc: Implement posix_fallocate

.asf.yaml, .github/workflows/build.yml, .github/workflows/check.yml, .github/workflows/doc.yml, .github/workflows/lint.yml, .yamllint
Lint some YAML
Add a `.yamllint` config file
=> feat: add a GitHub action to lint the YAML files

.github/SECURITY.md
=> .github/SECURITY.md: Fix a typo.

arch/xtensa/src/esp32/esp32_wifi_adapter.c
esp32 wifi related small fixes
esp32 only
tested on a local board
=> Esp32 wifi fixes

tools/version.sh
See #2529 for details.
Close #2529
Get version from master and a release branch.
=> tools/version.sh: Fix the version retrieved from GIT.

fs/spiffs/src/spiffs_vfs.c
minor typos in comment and message
spiffs
tested locally
=> spiffs: fix minor typos

include/sys/syscall_lookup.h, include/unistd.h, sched/task/Make.defs, sched/task/task_getppid.c, syscall/syscall.csv
as specified here:
https://pubs.opengroup.org/onlinepubs/009695399/functions/getppid.html
=> libc: Implement getppid

arch/arm/src/stm32/stm32g4xxxx_rcc.c
When architectural support for STM32G4 family was added, the reference manual (RM0440) was at revision 2. Since then, it has undergone several revisions. One significant change is in the table of FLASH wait states: section 3.3.3 table 9. The outcome of this change is that fewer FLASH wait states are needed for most CPU clock (HCLK) frequencies. Notably, if running the CPU clock at the maximum 170 MHz, only 4 FLASH wait states are needed, rather than the previously programmed 8 wait states. This gives a noticeable performance boost when executing code from FLASH.
arch/arm/src/stm32/stm32g4xxxx_rcc.c:
- FLASH_ACR_LATENCY_SETTING: Reimplement compile-time logic that selects the required wait state setting to use the new updated table.
- Update all comments to indicate that RM0440 Rev 5 is …
=> stm32g4: Fix incorrect FLASH wait states

libs/libc/netdb/lib_getaddrinfo.c
The length of hostbuffer come from Kconfig, it isn't safe to
allocate this variable on the stack.
The stack consumption for getaddrinfo become small
=> libc/netdb: Move hostbuffer out of the stack

include/debug.h, libs/libc/misc/Make.defs, libs/libc/misc/lib_dumpbuffer.c, libs/libc/misc/lib_dumpvbuffer.c
libs/libc/dumpbuffer: add support to dump the buffer to file descriptor.
libs/libc: add lib_dumpvbuffer support
libs/libc/dumpbuffer: remove the unnecessary printable characters traversal
libs/libc/dumpbuffer: fix nxstyle warning
libs/libc/dumpbuffer: add support to recognizable from wireshark
e.g: Encapsulation Type: Bluetooth H4: add packet type dump support
From:
`lib_dumpvbuffer(NULL, data, len);`
```
[    2.196000] 0000: 030c00                                                            ...
[    2.514600] 0000: 0e0401030c00                                                      ......
[    2.514600] 0000: 031000                                                            ...
[    2.517600] 0000: 0e0c01031000ffff8ffedbff5b87                                      ............[.
[ …
```
=> libs/libc/dumpbuffer: dump buffer enhancement

arch/sim/src/sim/up_rptun.c, include/nuttx/signal.h
fix  compile break when using some features.
no
daily test
=> fix  compile break when using some features.

fs/mount/fs_umount2.c
=> Fix inode lock at umount2

drivers/wireless/bluetooth/bt_uart.c, drivers/wireless/bluetooth/bt_uart.h, drivers/wireless/bluetooth/bt_uart_bcm4343x.c, drivers/wireless/bluetooth/bt_uart_cc2564.c, drivers/wireless/bluetooth/bt_uart_generic.c, include/nuttx/wireless/bluetooth/bt_buf.h, include/nuttx/wireless/bluetooth/bt_core.h, include/nuttx/wireless/bluetooth/bt_driver.h, include/nuttx/wireless/bluetooth/bt_gatt.h, include/nuttx/wireless/bluetooth/bt_hci.h, include/nuttx/wireless/bluetooth/bt_ioctl.h, include/nuttx/wireless/bluetooth/bt_null.h, include/nuttx/wireless/bluetooth/bt_uart.h, include/nuttx/wireless/bluetooth/bt_uart_shim.h, include/nuttx/wireless/bluetooth/bt_uuid.h, wireless/bluetooth/bt_buf.c, wireless/bluetooth/bt_l2cap.h, wireless/bluetooth/bt_uuid.c
Please check the commit message for more info.
No function change.
=> Minor fix to bluetooth stack

fs/mount/fs_mount.c, fs/vfs/fs_stat.c, fs/vfs/fs_unlink.c, include/nuttx/fs/fs.h
add nx_unlink
remove INODE_IS_SPECIAL() use INODE_IS_PSEUDODIR instead
file operation who use INODE_IS_SPECIAL
Test pass on sim
=> remove INODE_IS_SPECIAL() use INODE_IS_PSEUDODIR instead

arch/arm/src/cxd56xx/cxd56_charger.c, arch/arm/src/cxd56xx/cxd56_ge2d.c, arch/arm/src/cxd56xx/cxd56_rtc_lowerhalf.c, arch/arm/src/cxd56xx/cxd56_scu.c, arch/arm/src/cxd56xx/cxd56_sfc.c, arch/arm/src/cxd56xx/cxd56_sysctl.c, arch/arm/src/cxd56xx/cxd56_uart0.c, arch/arm/src/kinetis/kinetis_rtc_lowerhalf.c, arch/arm/src/max326xx/common/max326_rtc_lowerhalf.c, arch/arm/src/nrf52/nrf52_adc.c, arch/arm/src/stm32/stm32_rtc_lowerhalf.c, arch/renesas/src/rx65n/rx65n_rtc_lowerhalf.c, arch/z80/src/ez80/ez80_rtc_lowerhalf.c, drivers/leds/ws2812.c, drivers/sensors/adt7320.c, drivers/sensors/adxl372.c, drivers/sensors/lsm330_spi.c, fs/fat/fs_fat32attrib.c, fs/vfs/fs_eventfd.c, mm/mm_heap/mm_sem.c
instead to change errno value by calling set_errno
No function change.
=> OS internal function should indicate the error by return negative value

arch/arm/src/stm32h7/stm32_bbsram.h
arch/arm/src/stm32h7/stm32_bbsram.h:
- Fix nxstyle issues.
nxstyle
=> arch/stm32h7: Fix nxstyle errors

include/sys/socket.h, libs/libc/net/Make.defs, libs/libc/net/lib_socketpair.c
Reference here:
https://www.freebsd.org/cgi/man.cgi?apropos=0&sektion=2&query=socketpair&manpath=FreeBSD+7.0-current&format=html
Change-Id: I959b4d661cd436f5d5050baf9e821db84139d482
Signed-off-by: danguanghua <danguanghua@xiaomi.com>
=> libs/libc/net: implement socketpair

boards/renesas/rx65n/rx65n-rsk2mb/README.txt
=> Updated README.txt for RSK2M

boards/arm/imx6/sabre-6quad/README.txt
- This commit updates how to build the u-boot
- Also adds tftpboot
- No impact
- Tested with sabre-6quad board
=> boards: sabre-6quad: Update README.txt

drivers/serial/ptmx.c, fs/vfs/fs_open.c, include/nuttx/fs/fs.h
let's replace the content of file in place instead
No functional change
=> fs: Remove the special hack for pty in nx_vopen

arch/sim/src/sim/up_setjmp32.S, arch/sim/src/sim/up_setjmp64.S
=> arch/sim: Simplify SYMBOL macro definition

drivers/serial/pty.c, fs/vfs/fs_fcntl.c, fs/vfs/fs_ioctl.c, fs/vfs/fs_open.c, include/nuttx/fs/fs.h
these functions are the implementation detail and then don't need expose to external
code reorganization, no functional change.
=> fs: Make nx_vxxx and file_vxxx as internal functions

include/nuttx/compiler.h, include/time.h
Enable more compile time check
Pass the build
=> time.h: Sprinkle strftime format attribute

tools/esp32/backtrace.gdbscript
Just for my convenience. Hopefully useful for others too.
=> esp32: Add a gdb script to show backtrace

arch/sim/src/Makefile, boards/sim/sim/sim/scripts/Make.defs
Extracted from https://github.com/apache/incubator-nuttx/pull/2063
See https://github.com/apache/incubator-nuttx/pull/2063
=> Fix libcxx for sim/macOS (less controversial parts)

arch/xtensa/src/esp32/esp32_wifi_adapter.c, arch/xtensa/src/esp32/esp32_wlan.c, net/devif/devif_poll.c, net/tcp/tcp_close.c
Some typos and cosmetic changes only.
N/A
N/A
=> net/ & esp32/wlan: Fix some typos and nxstyle issues.

libs/libxx/libxx_new.cxx, libs/libxx/libxx_newa.cxx
Signed-off-by: dingxintong <dingddding@163.com>
=> Add placement new and new[] function.

drivers/Kconfig, drivers/Makefile, drivers/efuse/Kconfig, drivers/efuse/Make.defs, drivers/efuse/efuse.c, include/nuttx/efuse/efuse.h, include/nuttx/fs/ioctl.h
Add generic efuse driver for NuttX
Add a new efuse subsystem to NuttX
ESP32
=> Add generic efuse driver for NuttX

net/bluetooth/bluetooth_sockif.c, net/can/can_sockif.c, net/devif/devif_poll.c, net/ieee802154/ieee802154_sockif.c, net/local/local_sockif.c, net/pkt/pkt_send.c, net/pkt/pkt_sockif.c, net/utils/net_chksum.c, net/utils/net_lock.c
Correct some comments.
N/A
N/A
=> net/: Fix typos in comments.

tools/lwl/README.txt, tools/lwl/ocdconsole.py
Move the LWL console communication script to tools/lwl
It will make clear the purpose of ocdconsole.py and clear the mess inside tools/
STM32F103-Minimum board
=> Move LWL python script to tools/lwl and add README.txt

net/pkt/pkt.h, net/tcp/tcp.h
Remove two duplicate forward references.
N/A
N/A
=> net/: Remove duplicate forward references.

include/netpacket/if_addr.h, include/netpacket/netlink.h
netpacket/if_addr: add interface address header 
N/A
CI check is enough
=> netpacket/if_addr: add interface address header 

boards/arm/imxrt/imxrt1020-evk/src/imxrt_bringup.c, boards/arm/stm32/stm32f4discovery/src/stm32_hciuart.c, boards/arm/tiva/tm4c1294-launchpad/src/tm4c_hciuart.c, drivers/wireless/bluetooth/bt_uart_bcm4343x.c, drivers/wireless/bluetooth/bt_uart_cc2564.c, drivers/wireless/bluetooth/bt_uart_generic.c, drivers/wireless/bluetooth/bt_uart_shim.c, include/nuttx/wireless/bluetooth/bt_uart_shim.h
=> Minor fix for bluetooth driver

drivers/syslog/vsyslog.c
Re-arranged fields in syslog, as discoussed in #2698.
None.
N/A.
=> Re-arranged syslog fields.

arch/sim/src/sim/up_hcitty.c, arch/sim/src/sim/up_internal.h, boards/sim/sim/sim/src/sim_bringup.c
Read the commit message for more info
sim coofig which use bt hci tty driver
=> Minor fix for sim hcitty driver

tools/esp32/backtrace.gdbscript
Add some comments
locally tested
=> tools/esp32/backtrace.gdbscript: Add comments

fs/tmpfs/fs_tmpfs.c
to avoid readdir return the wrong entry in the following code:
```
void rmdir_recursive(FAR const char *path)
{
FAR DIR *dir = opendir(path);
while (1)
{
char fullpath[MAX_PATH];
FAR dirent *ent = readdir(dir);
if (ent == NULL)
{
break;
}
sprintf(fullpath, "%s/%s", path, ent->d_name);
if (DIRENT_ISDIRECTORY(ent->d_type))
{
rmdir_recursive(fullpath);
}
else
{
unlink(fullpath);
}
}
}
```
tmpfs
All child can be removed by the above code.
=> fs/tmpfs: Iterate the entry reversely in readdir

arch/xtensa/src/esp32/esp32_spiram.c
Fix himem debug assert error
Himem with work when SMP is enabled
ESP32
=> Fix himem debug assert error

arch/arm/src/arm/arm_schedulesigaction.c, arch/arm/src/armv6-m/arm_schedulesigaction.c, arch/arm/src/armv7-a/arm_schedulesigaction.c, arch/arm/src/armv7-m/arm_schedulesigaction.c, arch/arm/src/armv7-r/arm_schedulesigaction.c, arch/arm/src/armv8-m/arm_schedulesigaction.c, arch/avr/src/avr/up_schedulesigaction.c, arch/avr/src/avr32/up_schedulesigaction.c, arch/mips/src/mips32/mips_schedulesigaction.c, arch/misoc/src/lm32/lm32_schedulesigaction.c, arch/misoc/src/minerva/minerva_schedulesigaction.c, arch/or1k/src/common/up_schedulesigaction.c, arch/renesas/src/m16c/m16c_schedulesigaction.c, arch/renesas/src/rx65n/rx65n_schedulesigaction.c, arch/renesas/src/sh1/sh1_schedulesigaction.c, arch/risc-v/src/gap8/gap8_schedulesigaction.c, arch/risc-v/src/nr5m100/nr5_schedulesigaction.c, arch/risc-v/src/rv32im/riscv_schedulesigaction.c, arch/risc-v/src/rv64gc/riscv_schedulesigaction.c, arch/sim/src/sim/up_schedulesigaction.c, arch/x86/src/i486/up_schedulesigaction.c, arch/x86_64/src/intel64/up_schedulesigaction.c, arch/xtensa/src/common/xtensa_schedsigaction.c, arch/z16/src/common/z16_schedulesigaction.c, arch/z80/src/ez80/ez80_schedulesigaction.c, arch/z80/src/z180/z180_schedulesigaction.c, arch/z80/src/z8/z8_schedulesigaction.c, arch/z80/src/z80/z80_schedulesigaction.c
since nxsig_tcbdispatch already hold it for us
No
=> arch: Remove critical section inside up_schedule_sigaction

sched/task/task_setup.c
- During reviewing sched_lock() in nxtask_assign_pid(),
I noticed that g_pidhash is not protected by a critical section
- Because g_pidhash is accessed in an interrupt context,
it should be protected by a critical section.
- Actually, nxsched_foreach(), nxsched_get_tcb() and so on
use a critical section.
- No impact
- Tested with spresense:wifi (non-SMP) and spresense:wifi_smp
=> sched: task: Fix a potential bug in nxtask_assign_pid()

libs/libc/pthread/pthread_conddestroy.c
pthread/cond: enhance pthread_cond_destroy
follow: https://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_cond_destroy.html
=> pthread/cond: enhance pthread_cond_destroy

libs/libc/unistd/lib_pathconf.c
unistd/fpathconf: enhance fpathconf
=> unistd/fpathconf: enhance fpathconf

libs/libc/netdb/lib_dnsaddserver.c, libs/libc/netdb/lib_dnsforeach.c
netdb: A few build fixes
locally build-tested
=> netdb: A few build fixes

drivers/mtd/at24xx.c, drivers/mtd/at25.c, drivers/mtd/at45db.c, drivers/mtd/gd5f.c, drivers/mtd/hamming.c, drivers/mtd/is25xp.c, drivers/mtd/m25px.c, drivers/mtd/mtd_modeltab.c, drivers/mtd/mtd_nandecc.c, drivers/mtd/mtd_nandmodel.c, drivers/mtd/mtd_nandscheme.c, drivers/mtd/mtd_rwbuffer.c, drivers/mtd/mx25lx.c, drivers/mtd/mx25rxx.c, drivers/mtd/mx35.c, drivers/mtd/n25qxxx.c, drivers/mtd/rammtd.c, drivers/mtd/ramtron.c, drivers/mtd/s25fl1.c, drivers/mtd/sector512.c, drivers/mtd/skeleton.c, drivers/mtd/sst25.c, drivers/mtd/sst26.c, drivers/mtd/w25.c, drivers/mtd/w25qxxxjv.c, include/nuttx/mtd/nand_scheme.h
drivers: mtd: nxstyle error fixes
none
local run of nxstyle
=> drivers: mtd: nxstyle error fixes

arch/arm/src/imx6/imx_enet.c
- Since imx_enet.c is based on imxrt_enet.c and still under debugging,
the differences should be minimum to keep tracking the changes
- None
- Tested with sabre-6quad:netnsh with QEMU
=> arch: imx6: Apply the latest imxrt/imxrt_enet.c to imx6/imx_enet.c

libs/libc/pthread/pthread_barrierwait.c, libs/libc/pthread/pthread_conddestroy.c, libs/libc/pthread/pthread_condinit.c
the error code may change to reflect the real issue.
=> pthread: Return get_errno instead the hardcode value

boards/risc-v/k210/maix-bit/README.txt
- Update README.txt regarding the kflash_gui
- None
- None
=> boards: maix-bit: Update README.txt regarding the kflash_gui

boards/risc-v/bl602/bl602evb/README.txt
Add more friendly notes for getting started with the bl602evb board.  Including both flashing and using the debugger.
=> boards: bl602evb flash and debug notes

arch/arm/src/samv7/sam_mcan.c
The MCAN driver private structure has been renamed to struct sam_mcan_s,
but some functions reference sam_can_s. There are missing defines
of return variable in some functions.
No testing we do not have evaluation kit nor own device based on SAM7 yet.
But it is in purchase. We need functional CAN and CAN FD support.
If there is somebody who can test the driver  or used it on older NuttX version
before compile break by rename it would be great.
=> arch/arm/src/samv7/sam_mcan.c: fix some mismatches caused by renaming.

libs/libc/machine/risc-v/rv64/arch_elf.c
Signed-off-by: hotislandn <hotislandn@hotmail.com>
This patch is for the abosulte address loading code piece in RV64 elf like:
lui a0, 0
...
addi a0, a0, 0
...
Note: there may be other instructions between lui and addi.
RV64 elf relocateadd function.
Verified on RV64GC core with qemu.
=> RV64: add R_RISCV_HI20 and R_RISCV_LO12_I to elf relocateadd for absolute address loading.

sched/group/group_killchildren.c
- During testing iperf -s with lc823450-xgevk:rndis,
I noticed that hard fault happens
- Finally, I found that group_kill_children() is not
not protected by a critical section
- This commit fixes this issue
- SMP only
- Tested with iperf with the following configurations
- lc823450-xgevk:rndis, spresense:rndis_smp
- Tested with ostest with the following configurations
- lc823450-xgevk:rndis, esp32-devkitc:smp (QEMU)
- sabre-6quad:smp (QEMU), maix-bit:smp (QEMU)
- spresense:rndis_smp, sim:smp
=> sched: group: Fix group_kill_children() for SMP

arch/arm/src/stm32f7/stm32_qspi.c
See title
None
Tested on stm32f746g-disco
=> stm32f7/stm32_qspi.c: Fix warning of format strings

fs/Kconfig
=> fs/eventfd: Convert the indent under EVENT_FD_VFS_PATH option to tab

Documentation/quickstart/install.rst
Small fixes for documentation page
Correct some typos
=> Fix Ubuntu name and use Windows in upper case

arch/xtensa/src/esp32/esp32_allocateheap.c
esp32: comment and assertion about heaps
tested locally (with other unrelated changes)
=> esp32: comment and assertion about heaps

arch/xtensa/src/esp32/esp32_spiflash.c
Fix the issue of `PSRAM` heap being destroyed when operating `SPI flash` APIs.
Enable `SPI flash` encryption in  `Partition`,  `PSRAM` heap will be destroyed when operating `SPI flash` .
NOTE: The CI will fail because are some pre-existing Mixed Case in the esp32_spiflash.c file
=> xtensa/esp32: Writeback PSRAM data when mapping SPI Flash address to ESP32's address bus

drivers/sensors/Kconfig, drivers/sensors/Make.defs, drivers/sensors/fakesensor.c, include/nuttx/sensors/fakesensor.h
This driver can read sensor data from csv file.
Signed-off-by: buyuer <dingddding@163.com>
=> Add fakesensor driver.

include/nuttx/mqueue.h, libs/libnx/nxmu/nx_connect.c, libs/libnx/nxmu/nx_disconnect.c, libs/libnx/nxmu/nx_eventhandler.c
and replace mq_open, mq_close and mq_unlink with these in libnx
=> mqueue: Add _MQ_OPEN, _MQ_CLOSE and _MQ_UNLINK macro

include/nuttx/mqueue.h, include/nuttx/net/net.h, libs/libc/netdb/lib_dnsquery.c, libs/libnx/nxmu/nx_eventhandler.c, libs/libnx/nxmu/nxmu_sendserver.c
reuse the definition come from include/nuttx/fs/fs.h
Shold no real impact
=> Remove the duplicated _NX_ and _MQ_ macro

boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_bringup.c
Add tmpfs mounting when bringing up.
=> boards/esp32c3: Add tmpfs mounting when bringing up

arch/risc-v/Kconfig, arch/risc-v/src/esp32c3/Make.defs, arch/risc-v/src/esp32c3/esp32c3_resetcause.c, arch/risc-v/src/esp32c3/esp32c3_resetcause.h, arch/risc-v/src/esp32c3/esp32c3_systemreset.c, boards/risc-v/esp32c3/esp32c3-devkit/src/Makefile, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_reset.c
Add software system reset.
N/A
Testing with the `reboot` command.
=> esp32c3: Add system reset.

drivers/sensors/l3gd20.c, drivers/sensors/sensor.c, drivers/sensors/wtgahrs2.c, include/nuttx/sensors/ioctl.h, include/nuttx/sensors/sensor.h
Sensor Driver model update.
Key modification points:
1. replace lower->buffer_size with lower->buffer_number.
2. add sanity checks for fetch(with O_NONBLOCK), it will directly return when sensor is disable.
3. gets the capacity of the hardware fifo, set it to lower->batch_number. And app can get this number by IOCTL cmd:SNIOC_GET_NEVENTBUF
daily test.
=> sensor driver model update

libs/libc/modlib/modlib_init.c, sched/module/mod_insmod.c
fix fd leak in dlopen.
tested with my local app on an esp32 board.
=> fix fd leak in dlopen

include/signal.h
we can catch signal SIGRTMIN by this path.
daily test
=> signal: change SIGRTMIN to 1 because signo 0 don't catch.

arch/z80/src/ez80/ez80_emac.c
IRQs cannot be individually disabled on the eZ80, so using
`up_disable_irq()` had no effect. This left the IRQ handler being
constantly triggered without the lower half handler running.
The macro for EMAC stats was incompatible with Clang. The simplified
form gives identical results under ZDS-II.
The MII clock speed must be set before trying to read MII registers.
It's now done before resetting the PHY using the Mode Control Register.
MII initialization waited on the auto-neogotiate restart bit being set
but PHY hardware is frequently fast enough to have cleared the bit
before the first read of it. It now instead just waits on auto-negotiate
completing. The MII poll loop now uses `up_mdelay` because it was far
too fast at 50MHz using a busy loop, giving time for a link to be
established. …
=> ez80: fix several bugs in emac driver

libs/libc/unistd/lib_getcwd.c
Enhance getcwd.
Reference: https://pubs.opengroup.org/onlinepubs/007904975/functions/getcwd.html
daily test
=> unistd/getcwd: enhance getcwd when buf is NULL

arch/arm/src/armv6-m/arm_schedulesigaction.c, arch/arm/src/armv6-m/arm_sigdeliver.c
- This commit applies armv7-m signal handling logic
- armv6-m signal handling
- Tested with ostest with the following configs
- raspberrypi-pico:nsh, raspberrypi-pico:smp
=> arch: armv6-m: Apply armv7-m signal handling logic

arch/arm/src/cxd56xx/cxd56_gnss.c
=> arm/cxd56xx: Beautify the coding style in cxd56_gnss.c

tools/convert-comments.c
=> tools/convert-comments:Fix breakage from Style fixes

sched/task/task_exithook.c
- During investigating critical section with semaphores, I noticed
that nxtask_flushstreams() is called with a critical section.
- The function calls lib_flushall() which handles a semaphore
in userspace.
- So it should be done without a critical section
- SMP only
- Tested with ostest the following configs
- esp32-devkitc:smp (QEMU), sabre-6quad:smp (QEMU)
- maix-bit:smp (QEMU), sim:smp
- spresense:smp
- Tested with nxplayer and stress test with spresense:wifi_smp
=> sched: task: Call nxtask_flushstreams() without critical section

arch/arm/src/stm32h7/hardware/stm32h7xxx_dbgmcu.h
This adds the DBGMCU
Missing from master. 
with https://github.com/apache/incubator-nuttx/pull/2943
=> stm32h7:Add DBGMCU missing from master

libs/libc/misc/lib_filesem.c
- I noticed that nxplayer with sprensense:rndis_smp is unstable, though spresense:wifi_smp seems stable.
- So let me revert #2938 until I find the root cause 
- SMP only
- Tested with spresense:rndis_smp
=> Revert "libs: misc: Remove critical section in lib_filesem.c for SMP"

fs/mqueue/Kconfig, fs/mqueue/mq_open.c, fs/vfs/fs_poll.c, include/nuttx/mqueue.h, sched/mqueue/mq_rcvinternal.c, sched/mqueue/mq_sndinternal.c
mqueue: add poll support
mqeue, can support poll
=> mqueue: add poll support

arch/xtensa/src/common/xtensa_hostfs.c
xtensa hostfs: Make host_stat populate st_size
A clumsy implementation using lseek.
This would allow more applications to use hostfs directly.
Tested lightly with CONFIG_EXAMPLES_STAT.
=> xtensa hostfs: Make host_stat populate st_size

binfmt/Kconfig, binfmt/binfmt.h, binfmt/binfmt_copyargv.c, binfmt/binfmt_dumpmodule.c, binfmt/libelf/Kconfig, libs/libc/machine/arm/arm/arch_elf.c, libs/libc/machine/arm/armv6-m/arch_elf.c, libs/libc/machine/arm/armv7-a/arch_elf.c, libs/libc/machine/arm/armv7-m/arch_elf.c, libs/libc/machine/arm/armv7-r/arch_elf.c, libs/libc/machine/arm/armv8-m/arch_elf.c, libs/libc/machine/risc-v/common/arch_elf.c, libs/libc/machine/sim/arch_elf.c, libs/libc/machine/sim/arch_elf64.c, libs/libc/machine/x86/arch_elf.c, libs/libc/machine/xtensa/arch_elf.c
Fix few typos in binfmt and libc/machine.
N/A
N/A
=> Fix few typos in binfmt and libc/machine.

fs/hostfs/Kconfig
hostfs: Document the backends and restrictions
Kconfig documentation only
the CI jobs should be enough
=> hostfs: Document the backends and restrictions

arch/xtensa/src/common/xtensa_backtrace.S
Fix xtensa_backtrace.S file header.
N/A
N/A
=> xtensa_backtrace.S: Fix the file header.

mm/iob/Kconfig, mm/iob/iob_trimhead.c
Fix typos in IOB Kconfig and comment
build-tested
=> Fix typos in IOB Kconfig and comment

arch/arm/src/lc823450/Kconfig, boards/arm/sama5/sama5d4-ek/src/sam_at25.c, boards/arm/samv7/same70-xplained/src/sam_bringup.c, boards/arm/samv7/samv71-xult/src/sam_bringup.c, boards/arm/stm32l4/stm32l476vg-disco/src/stm32_appinit.c, boards/z80/ez80/z20x/src/ez80_w25.c, drivers/bch/Make.defs, drivers/bch/bchlib_cache.c, fs/driver/Make.defs, fs/vfs/fs_open.c
Separate CONFIG_BCH from CONFIG_DISABLE_MOUNTPOINT
=> Separate CONFIG_BCH from CONFIG_DISABLE_MOUNTPOINT

boards/arm/lpc17xx_40xx/mbed/include/board.h
regression https://github.com/apache/incubator-nuttx/pull/3091 by:
```
commit 6f14299dd06d548df878827a02513f516ddb10a7
Author: Alin Jerpelea <alin.jerpelea@sony.com>
Date:   Thu Mar 18 09:57:48 2021 +0100
boards: nxstyle fixes
nxstyle fixes to pass the CI check
Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>
```
Pass the CI.
=> board/arm/mbed: Fix the typo error

sched/pthread/pthread_condclockwait.c
- This commit removes a redundant critical section in pthread_condclockwait.c
- None
- Tested with ostest with the following configs
- maix-bit:smp, esp32-devkitc:smp, sabre-6quad:smp
- spresense:smp, sim:smp
- maix-bit:nsh, sabre-6quad:nsh
- sprsesnse:wifi, sim:ostest
- Tested with nxplayer with the folowing configs
- spresense:wifi_smp, spresense:rndis_smp
=> sched: pthread: Remove a redundant critical section in pthread_condclockwait.c

boards/arm/stm32l4/nucleo-l496zg/src/stm32_dfsdm.c
Change format only
No
Pass the CI
=> boards/arm/stm32l4: Fix nxstyle warning

net/tcp/tcp_conn.c
net/tcp: correct the port byte order 
1. correct the port byte order
2. Do not re-select the port if the local port has been bind()
tcp connect()/bind()
socketpair SOCK_STREAM  stress testing
=> net/tcp: correct the port byte order 

mm/mm_heap/mm.h, mm/mm_heap/mm_malloc.c, mm/mm_heap/mm_sem.c
mm/heap: Change nxsem_init to _SEM_INIT
mm/heap: Add FAR to the pointer type
Minor code change, should no real difference
Pass the CI build
=> Minor fix for heap manager

libs/libc/time/lib_localtime.c
libs/libc/time/localtime: fix race condition 
fix race condition on create the instance of lcl/gmt
N/A
localtime test
=> libs/libc/time/localtime: fix race condition 

fs/littlefs/lfs_vfs.c
New function
dup don't return -ENOSYS anymore.
=> fs/littlefs: Suppport the duplication function

arch/sim/src/sim/up_smpsignal.c
- In the previous implementation, signal handling for SMP was done
in a critical section that is not correct
- This commit fixes this issue
- Signal handling for SMP
- Tested with ostest
=> arch: sim: Fix sim_sigdeliver() for SMP

arch/arm/src/stm32h7/stm32_spi.c
The STM32H7  SPI driver was not using the HW correctly. Albeit the manual is super confusing, the bottom line is this.
That a memory access  of 8, 16 and 32 bits, will write 1 byte, 2 bytes or 4 bytes to the FIFIO.
With a frame size of 16 (CFG1_DSIZE == 0xf) a 32 bit write to SPI_TXDR will place 2 16 bit values into the FIFO.
So the date sent on the wire was the correct first 16 bit  word followed by an incorrect 16 bit  word of 0x0000. This can be observed on master with an STM32H7 in the first image.
I believe the STM32F7  (and all SoC's sharing the same IP) have the same issues but that is TBD. 
Master on STM32H7 note the 32 clocks on a 16 bit transfer.
After this PR on STM32H7 as expected 16 bits and 16 clock edges. 
PX4 cuav_x7pro with ADIS16470
=> stm32h7:SPI Fix 16 bit SPI mode

drivers/usbdev/rndis.c
Previous fix #3162 to RNDIS response queueing caused unaligned access to response buffer in some configurations. On ARM Cortex-M, this would cause hardfault if optimizer used `strd` instruction.
Fix by allocating the buffer as `uint32_t`. RNDIS messages are always a multiple of 4 bytes in size, so this ensures alignment.
Also added alignment logic for `RNDIS_QUERY_MSG` replies, where the payload may not be multiple of 4 bytes, but the message can be padded.
Fixes hardfaults caused by the previous commit.
Tested on custom board and on STM32F4 discovery using the `stm32f4discovery:rndis` configuration.
Tested on Linux kernel 5.7.0 and on Windows 10.0.18363.
@masayuki2009 Can you test this one also on `spresense:rndis`?
=> USBDEV RNDIS: Fix unaligned access caused by 4f66624

arch/arm/src/armv7-a/arm_allocpage.c, arch/arm/src/armv7-a/cp15_cacheops.h, arch/arm/src/armv7-a/sctlr.h, arch/arm/src/armv7-r/cp15_cacheops.h, arch/arm/src/armv7-r/sctlr.h, arch/arm/src/armv8-m/etm.h
Follow up @jerpelea  licenses
No, only style change
Pass CI
=> arch/arm: Fix the style warning

include/netdb.h
Fix the style issue from https://github.com/apache/incubator-nuttx/commit/33005897baafef810d2d6a5803a6134977bea5eb
Style change only
Pass the CI
=> netdb.h: Change all tab to space

Documentation/Makefile, Documentation/_static/custom.css, Documentation/contributing/documentation.rst, Documentation/reference/user/13_logging.rst
See commit list for details.
Doc
Built docs
=> Documentation: add syslog user API and other minor improvements

include/sys/stat.h
to be more compatible with BSD libc
Minor, new flags alias
Pass CI
=> sys/stat.h: Add S_IREAD, S_IWRITE and S_IEXEC macro

arch/arm/src/stm32/Kconfig, arch/arm/src/stm32/hardware/stm32_tim.h
Cosmetic changes in stm32/Kconfig and stm32/hardware/stm32_tim.h
=> stm32: cosmetics changes for Kconfig and hardware/stm32_tim.h

mm/mm_heap/mm_checkcorruption.c
mm/mm_heap: fix compile failed when open DEBUG_MM
=> mm/mm_heap: fix compile failed when open DEBUG_MM

include/signal.h, sched/signal/sig_deliver.c, sched/signal/sig_dispatch.c
See the info here:
https://pubs.opengroup.org/onlinepubs/007904875/functions/sigaction.html
New funcitonality
Pass CI and ostest
=> sched/signal: Implement SA_NODEFER

libs/libc/pthread/pthread_once.c
OpenGroup specification was updated regarding the return value for pthread_once, which after Issue 7 states that "the [EINVAL] error for an uninitialized pthread_once_t object is removed; this condition results in undefined behavior".
https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_once.html
No impact to NuttX code, since `pthread_once` is not used anywhere.
Successful build for `sim:ostest`
=> libs/libc: Update pthread_once according to the specification

tools/nxstyle.c
nxstyle: Fix typos in reported errors.
N/A
N/A
=> nxstyle: Fix typos in reported errors.

include/dspb16.h, libs/libdsp/lib_motor_b16.c
Add the missing open-loop support for fixed16 libdsp.
FOC test app, not yet in upstream.
=> libdsp/fixed16: add open-loop handler

Kconfig, arch/arm/src/stm32/stm32_foc.c, arch/sim/src/sim/up_foc.c, boards/arm/stm32/common/src/stm32_ihm07m1.c, boards/arm/stm32/common/src/stm32_ihm08m1.c, drivers/motor/foc/foc_dev.c, include/debug.h
Add support for motor debug messages and use them in all FOC files.
=> Add support for motor debug messages

libs/libc/unistd/lib_getopt_common.c
1. Null pointer dereference:
```
-  for (ndx = 0; longopts[ndx].name[0] != '\0'; ndx++)
+  for (ndx = 0; longopts[ndx].name != NULL; ndx++)
```
Effects only getopt_long() and getopt_long_only()
2. Handle single character long options.  An option like -x could be either a short option or a long option (under getopt_long_only()).  This case was not being handled correctly.
3. Add missing support for optional arguments to short options (indicated with two "::").
This effects all members of the getopt() family of APIs.
Tested on the simulator using extensions to apps/testing/ostest.  Extensions were made to the getopt() testing in OS test to verify the changes of this PR but these have not yet been merged  (see apached/incubator-nuttx-apps PR 646).  This PR does not depend on those changes in …
=> Correct some getopt() logic

.github/workflows/build.yml
Adapt to testlist changes from https://github.com/apache/incubator-nuttx-testing/pull/92
CI
CI
=> CI: adapt to testlist changes

fs/aio/aio_cancel.c, fs/nfs/nfs.h, fs/nfs/nfs_mount.h, fs/nfs/rpc.h, fs/nfs/rpc_clnt.c, fs/nfs/xdr_subs.h, fs/smartfs/smartfs_utils.c, fs/spiffs/src/spiffs.h, fs/spiffs/src/spiffs_cache.c, tools/nxstyle.c
fixes for several errors reported by the nxstyle tool
NONE
NONE
=> fs: nxstyle fixes

graphics/nxterm/nxterm.h, graphics/vnc/server/vnc_receiver.c, tools/nxstyle.c
fix errors reported by nxstyle
NONE
NONE
=> graphics: fix nxstyle errors

libs/libc/unistd/lib_getopt_common.c
Found a place in getopt_common() where the option string is used before it is checked if it is NULL.  This can happen because the short option string is optional for getopt_long() and getopt_long_only()
If optstring is NULL, that would be an ERROR for getopt(), but not for the getopt_long() versions.
Should effect only the getopt() APIs
Tested on the simulator using apps/testing/ostest.
=> getopt():  Fix Use of Pointer before NULL check

libs/libc/unistd/lib_getopt_common.c
Add a trivial comment about handling in certain corner cases where I am not certain what the correct behavior should be.
None
N/A
=> getopt_commont():  Add some comments

libs/libc/unistd/lib_getopt_common.c
The Linux man page requires that the getopt_long() and getopt_long_only() functions accept arguments to options in a form like:
--option=argument
This PR adds that missing functionality.
This change effects only getopt_long() and getopt_long_only()
Tested on a simulator NSH configuration with a modified version of the getopt() test in apps/testing/ostest.
=> getopt_long():  Add support for required argument format

arch/arm/src/armv8-m/arm_exception.S
No, minor change.
Pass Ci and ostest
=> arch/armv8-m: Merge ite instruction to the previous one

net/tcp/tcp_netpoll.c
tcp_netpoll.c: Fix a performance issue with CONFIG_NET_TCP_WRITE_BUFFERS
non blocking i/o with CONFIG_NET_TCP_WRITE_BUFFERS.
Tested with a modified version of webclient, which uses non-blocking i/o.
The packet dumps look more reasonable with this change.
=> tcp_netpoll.c: Fix a performance issue with CONFIG_NET_TCP_WRITE_BUFFERS

arch/arm/src/armv7-a/arm_vectors.S, arch/arm/src/armv7-r/arm_vectors.S
=> arch/arm: Minor style fix

arch/arm/src/armv7-a/arm_vectors.S
@masayuki2009 I think this change shouldn't need anymore, can you confirm it?
Should no
ostest
=> arch/armv7-a: Remove the special process of the nest level

arch/arm/src/arm/arm_vectors.S, arch/arm/src/armv7-a/arm_vectors.S, arch/arm/src/armv7-r/arm_fullcontextrestore.S, arch/arm/src/armv7-r/arm_vectors.S, arch/arm/src/c5471/c5471_vectors.S
unify the SPSR register usage
No, since spsr_cxsf equal spsr
Pass CI
=> arch/arm: Change all spsr_cxsf to spsr

boards/xtensa/esp32/esp32-devkitc/Kconfig, boards/xtensa/esp32/esp32-devkitc/README.txt, boards/xtensa/esp32/esp32-ethernet-kit/Kconfig, boards/xtensa/esp32/esp32-ethernet-kit/README.txt, boards/xtensa/esp32/esp32-wrover-kit/Kconfig, boards/xtensa/esp32/esp32-wrover-kit/README.txt
Update some comments and instructions in READMEs and Kconfig.
N/A
N/A
=> boards/esp32: Update some comments and instructions

libs/libc/stdio/lib_ftell.c
Update  lib_getoffset under lib_ftell.c to handle write case  besides read case.
Verified under sim and local m33 board.
=> libc: update stream getoffset to handle write case

drivers/syslog/syslog_device.c
Previously `syslog_dev_uninitialize()` was using `syslog_dev_outputready()` to check whether the device is in proper state for uninitialization.
This is wrong for a couple of reasons:
* `syslog_dev_outputready()` may try to open the device again if it is in `SYSLOG_REOPEN` state, while what we want is to just close it.
* If `syslog_dev_outputready()` returned false, the uninitialization was aborted. This was unconditional and although the device is in a state that it cannot perform any writes, it may be perfectly able to be closed.
* To make matters worse `syslog_dev_uninitialize()` does not return anything, so the caller is not able to tell whether the device is actually uninitialized and whether the resources were actually freed. The only think left is to assume that it succeeded which …
=> syslog: Proper uninit of syslog_device.

LICENSE, arch/x86/include/i486/arch.h, arch/x86/src/i486/up_irq.c, arch/xtensa/include/esp32/core-isa.h, arch/xtensa/include/esp32/tie-asm.h, arch/xtensa/include/esp32/tie.h, arch/xtensa/include/xtensa/core.h, arch/xtensa/include/xtensa/xtensa_coproc.h, arch/xtensa/include/xtensa/xtensa_corebits.h
Add 3rd party licenses for Cadence Design Systems to the LICENSE file.
Add 3rd party licenses for Tensilica Inc to the LICENSE file.
NONE
NONE
=> LICENSE: add 3rd party license for Cadence Design Systems

LICENSE, arch/mips/src/pic32mz/pic32mz_excptmacros.h
Add 3rd party licenses for Broadcom to the LICENSE file.
NONE
NONE
=> LICENSE: add 3rd party license for Broadcom

Documentation/platforms/xtensa/esp32/index.rst
Add supported peripherals for ESP32 documentation and fix some typos.
N/A
N/A
=> Documentation/esp32: Add supported peripherals

arch/arm/src/lpc43xx/spifi/src/spifilib_fam_standard_cmd.c
Add 3rd party licenses for NXP Semiconductors to the LICENSE file.
NONE
NONE
=> LICENSE: add 3rd party license for NXP Semiconductors

arch/xtensa/src/esp32/esp32_spi.c
This PR intends to improve the SPI Exchange via Polling method.
ESP32 SPI controller is capable of exchanging up to 64 bytes in a single transaction, but the current implementation only performs transfers of 2 bytes at most, resulting in a higher number of transactions. This imposes a huge burden on the CPU, making it spend unnecessary time in polling state.
Performance improvement for the ESP32 SPI driver transferring data via polling.
`esp32-wrover-kit:lvgl` to be upstreamed.
=> xtensa/esp32: Improve SPI polling to use the entire HW buffer

drivers/syslog/syslog_device.c
Syslog_device has logic to open the device in a later time, in case initialization fails.  
However, after this initial opening, no further checks were done. The state `SYSLOG_FAILURE` was not actually used anywhere.
If the device was opened successfully, but there was a problem occurring at a later time, during actual logging, the driver was not able to detect this. There was no way to recover from this state, and the user couldn't know of the failure.  
Eventually all subsequent logging is lost.
The changes in this PR properly set the driver state in `SYSLOG_FAILURE` when any fault occurs.  
At a later point, the device will be properly closed, and marked again as `SYSLOG_REOPEN`. So the initialization process can be executed again, and have the channel recover from the problem.
*Note!* …
=> syslog_device: Device is re-opened in case of failure.

.github/linters/setup.cfg, .github/workflows/lint.yml, Documentation/conf.py, tools/discover.py, tools/flash_writer.py, tools/ide_exporter.py, tools/licensing/apachize.py, tools/licensing/check.py, tools/lwl/ocdconsole.py, tools/parsecallstack.py
=> Lint Python code with flake8 and isort

arch/risc-v/src/esp32c3/esp32c3_allocateheap.c, arch/risc-v/src/esp32c3/hardware/esp32c3_rom_layout.h, boards/risc-v/esp32c3/esp32c3-devkit/scripts/esp32c3.template.ld
=> [BACKPORT #3524]riscv/esp32c3: Fix heap end address

boards/arm/stm32/nucleo-g431rb/src/Make.defs, boards/arm/stm32/nucleo-g431rb/src/nucleo-g431rb.h, boards/arm/stm32/nucleo-g431rb/src/stm32_appinit.c, boards/arm/stm32/nucleo-g431rb/src/stm32_boot.c, boards/arm/stm32/nucleo-g431rb/src/stm32_bringup.c, boards/arm/stm32/nucleo-g431rb/src/stm32_buttons.c
nucleo-g431rb: refactor bringup logic for consistency with other boards
nucleo-g431rb: add button support
=> nucleo-g431rb: refactor bringup logic and add button support

arch/arm/src/stm32/Kconfig, arch/arm/src/stm32/hardware/stm32_dbgmcu.h, arch/arm/src/stm32/stm32_foc.c
stm32g4xx: add DBGMCU definitions
stm32g4xx: add support for FOC
ihm07m1 + nucleo-g431rb
=> stm32g4xx: add DBGMCU definitions and add support for FOC

Documentation/faq/index.rst, Documentation/index.rst
Add FAQ entry to Documentation
User will get a FAQ in the Documentation
N/A
=> Documentation: Add FAQ entry

Documentation/faq/index.rst
Add more questions/answers to the FAQ
New docs for users
=> Add more questions/answers to the FAQ

arch/arm/src/stm32/stm32_uart.h
Fixed typos the effect the DMA config
It will work now :)
Inspection and CI
=> stm32:Serial DMA config USART{4578} -> UART{4578}

ReleaseNotes
Add the initial release notes for the 10.1.0 release
=> Documentation: Add release notes for 10.1.0 release

drivers/wireless/gs2200m.c
=> [BACKPORT #3559]  drivers: wireless: Fix AT command response handling in gs2200m.c

drivers/wireless/gs2200m.c
=> [BACKPORT #3535]  drivers: wireless: Fix to receive a UDP packet partially in gs2200m.c

ReleaseNotes
Improve formatting and organization of ReleaseNotes.
- Improve organization by sorting architectures and boards into alphabetical order.
- Improve consistency of newlines between headings and contents.
- In sections that include subsections for new features and bugfixes, list the new features (or major/significant improvements) first, followed by bugfixes.
- In Compatibility Concerns section, rewrap the lines and add backticks around identifiers that should print in a fixed-width typeface.
No functional changes.
None.
=> ReleaseNotes: Improve organization and other minor fixes

net/local/local_sendmsg.c
net/local: correct the sendto() return length
return length should be data length 
sendto(2) on local/UNIX naming socket
sendto(2) test
=> net/local: correct the sendto() return length

include/nuttx/arch.h
arch: remove up_irq{save|restore} these come from irq.h
IRQ
NONE
=> [BP-3580]arch: remove up_irq{save|restore} these come from irq.h

ReleaseNotes
Improve organization by sorting architectures and boards into alphabetical
order. Improve consistency of newlines between headings and contents. In
sections that include subsections for new features and bugfixes, list the
new features (or major/significant improvements) first, followed by
bugfixes. In Compatibility Concerns section, rewrap the lines and add
backticks around identifiers that should print in a fixed-width typeface. 
Documentation
NONE
=> [BP-3570]ReleaseNotes: Improve organization and other minor fixes

boards/arm/cxd56xx/common/src/cxd56_gs2200m.c, boards/arm/cxd56xx/spresense/Kconfig
Support different hardware version of Wi-Fi add-on board (iS110B)
WiFi
Spresense
=> [BP-3542] Support different hardware version of Wi-Fi add-on board (iS110B)

arch/xtensa/src/esp32/Kconfig
This PR intends to address some minor issues with the ESP32 Kconfig.
It does not bring any functional change, should have no impact.
Menuconfig navigation test.
=> xtensa/esp32: Address some minor issues with Kconfig

net/local/local_sendmsg.c
return length should be data length
10.1
Backport
=> [bp-3258]net/local: correct the sendto() return length

arch/arm/src/efm32/efm32_usbdev.c, arch/arm/src/lpc54xx/lpc54_ethernet.c, arch/arm/src/stm32h7/stm32_otgdev.c, arch/arm/src/stm32l4/stm32l4_otgfsdev.c
arch: fix some printf format errors
=> arch: fix some printf format errors

tools/esp32/mk_qemu_img.sh
Refactor the dd commands and suppress the status output.
N/A
esp32-devkitc:snh with ESP32_QEMU_IMAGE
=> tools/esp32/mk_qemu_img.sh: Refactor the dd commands.

net/inet/inet_sockif.c
inet:sockif Fix warning
Will compile now
CI
=> inet:sockif Fix warning

fs/cromfs/fs_cromfs.c
fs:cromf Use inttypes in printing macros
Will compile now
CI
=> fs:cromf Use inttypes in printing macros

arch/arm/src/stm32/stm32_adc.c
stm32_adc.c: rename a struct member in struct adccmn_data_s from 'initialized' to 'refcount'
CI
=> stm32_adc.c: rename a struct member in struct adccmn_data_s

libs/libc/termios/lib_tcsetattr.c
1. call tcdrain for TCSADRAIN
2. call tcflush for TCSAFLUSH
New terminal functionality
With libssh
=> libc/termios: Implement TCSADRAIN and TCSAFLUSH for tcsetattr

include/pwd.h
Like other libc implemenation
Minor, new macro
Pass CI
=> libc/pwd: Add NSS_BUFLEN_PASSWD macro

Documentation/platforms/risc-v/esp32c3/boards/esp32c3-devkit/index.rst, Documentation/platforms/risc-v/esp32c3/index.rst
Fix a couple of issues from https://github.com/apache/incubator-nuttx/pull/3700
N/A
N/A
=> Documentation/esp32c3: Fix a couple of issues from #3700

include/pty.h, libs/libc/stdlib/Make.defs, libs/libc/stdlib/lib_openpty.c
see here:
https://man7.org/linux/man-pages/man3/openpty.3.html
New function
with libssh
=> libc: Implement openpty function

.github/workflows/build.yml, tools/ci/testlist/sim-01.dat, tools/ci/testlist/sim-02.dat
To avoid the build break sim0x.dat will remove in the upcoming patch
CI for sim
Pass CI
=> tools/ci: Rename sim0x.dat to sim-0x.dat to align with arm-xx.dat

include/spawn.h, sched/task/task_posixspawn.c, sched/task/task_spawn.c, sched/task/task_spawnparms.c
=> Don't include errno.h from spawn.h

drivers/modem/altair/altmdm_spi.c
Even in the case of a conflict between a reset packet
and a send packet, the send size is compared and the
larger size is sent as the payload.
drivers/modem/altair
=> drivers/modem/altair: Fix behavior when a reset packet conflicts with a send packet

arch/arm/src/stm32f7/stm32_i2c.c, arch/arm/src/stm32h7/stm32_i2c.c
Fixes build for stm32f7 and stm32h7 i2c driver.
Fixes warning
Pass CI
=> Use inttypes stm32fx i2c

arch/arm/src/imx6/Kconfig, arch/arm/src/imx6/imx_serial.c
- This commit adds termios support to imx6
- None
- Tested with QEMU
=> arch: imx6: Add termios support to imx6

sched/clock/clock_timekeeping.c, sched/clock/clock_timekeeping.h, video/videomode/videomode_lookup.c, video/videomode/videomode_sort.c
Gregory Nutt is the copyright holder for those files and he has submitted the
SGA as a result we can migrate the licenses to Apache.
Licenses
None
=> update licenses to Apache

include/nuttx/spi/slave.h
This PR intends to fix some typos and provide some consistency improvements to the SPI Slave documentation.
Documentation only.
Not applicable.
=> spi: Improve SPI Slave interface documentation

drivers/eeprom/spi_xx25xx.c
Remove a warning
None
Tested in our own board.
=> use correct printf specifiers

arch/risc-v/src/bl602/Kconfig, arch/risc-v/src/bl602/Make.defs, arch/risc-v/src/bl602/bl602_hbn.c, arch/risc-v/src/bl602/bl602_rtc.c, arch/risc-v/src/bl602/bl602_rtc.h, arch/risc-v/src/bl602/bl602_rtc_lowerhalf.c, boards/risc-v/bl602/bl602evb/src/bl602_bringup.c
Add RTC Driver for BL602
risc-v/bl602
BL602 Boards
=> risc-v/bl602: Add RTC driver

Documentation/reference/user/02_task_scheduling.rst
Improve documentation to make clear about the priorities
Documentation only
N/A
=> Doc: Improve documentation to make clear about the priorities

net/devif/devif_poll.c, net/tcp/tcp_callback.c, net/tcp/tcp_recvfrom.c, net/tcp/tcp_recvwindow.c
Add some comments in tcp code
only comments and whitespaces
=> Add some comments in tcp code

net/tcp/tcp_recvwindow.c
tcp_get_recvwindow: Add a revisit comment
comment only
build tested
=> tcp_get_recvwindow: Add a revisit comment

net/tcp/tcp.h, net/tcp/tcp_send.c, net/tcp/tcp_send_buffered.c, net/tcp/tcp_send_unbuffered.c
tcp: Move buffered/unbuffered common code to tcp_send.c
=> tcp: Move buffered/unbuffered common code to tcp_send.c

boards/xtensa/esp32/common/include/esp32_ht16k33.h, boards/xtensa/esp32/common/src/Make.defs, boards/xtensa/esp32/common/src/esp32_ht16k33.c, boards/xtensa/esp32/esp32-devkitc/src/esp32_bringup.c, drivers/lcd/Kconfig, drivers/lcd/Make.defs, drivers/lcd/ht16k33_14seg.c, include/nuttx/lcd/ht16k33.h
Add Holtek HT16K33 14-segment display driver
Users will be able to use Holtek HT16K33 as SLCD on NuttX
ESP32-Devkitc
=> Add Holtek HT16K33 14-segment display driver

drivers/serial/serial.c
Simplify the code logic
No, the behaviour is same as before
=> serial: Remove the unnecessary err_out label

drivers/lcd/ht16k33_14seg.c
Fix ht16k33 driver to support multi-modules
User will be able to connect up to 8 modules to create larger display
ESP32-Devkitc
=> Fix ht16k33 driver to support multi-modules

net/icmp/icmp_recvmsg.c, net/icmp/icmp_sockif.c, net/icmpv6/icmpv6_recvmsg.c, net/icmpv6/icmpv6_sockif.c
net/icmp: fix race condition in icmp recvmsg
net/icmp: add nonblocking support
net/icmp: consume the data length to avoid duplicate packet
net/icmp: fix invalid condition comparison
ping/ping6
ping/ping6 works as expected
=> net/icmp: icmp bug fix and enhancement

arch/arm/src/stm32f7/stm32_bbsram.c, arch/arm/src/stm32h7/stm32_bbsram.c
Fix Breakage from https://github.com/apache/incubator-nuttx/pull/3738
master broken
CI / built localy
=> Fix Breakage from https://github.com/apache/incubator-nuttx/pull/3738

libs/libc/netdb/lib_dnsquery.c
fix unaligned access in dns query
=> net/dns:fix unaligned access in dns query

Documentation/reference/os/iob.rst, include/nuttx/mm/iob.h, mm/iob/Make.defs, mm/iob/iob_free_queue_qentry.c
mm/iob: rename the iob_free_queue() to iob_destroy_queue()
mm/iob: add iob_free_queue() interface
make the semantics more precise
N/A
IOB testing
=> mm/iob: add iob_free_queue() interface

net/local/local.h, net/local/local_conn.c, net/local/local_connect.c
net/local: add local_nextconn() helper
N/A
local connections foreach
=> net/local: add local_nextconn() helper

Documentation/platforms/risc-v/mpfs/index.rst, arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/hardware/mpfs_i2c.h, arch/risc-v/src/mpfs/mpfs_i2c.c, arch/risc-v/src/mpfs/mpfs_i2c.h, boards/risc-v/mpfs/icicle/src/Makefile, boards/risc-v/mpfs/icicle/src/mpfs_i2c.c, boards/risc-v/mpfs/icicle/src/mpfsicicle.h
=> Add i2c driver to PolarFire SoC and Icicle board

arch/risc-v/include/c906/irq.h, arch/risc-v/include/esp32c3/irq.h, arch/risc-v/include/irq.h, arch/risc-v/include/mpfs/irq.h, arch/risc-v/src/bl602/Make.defs, arch/risc-v/src/bl602/bl602_irq.c, arch/risc-v/src/c906/c906_irq.c, arch/risc-v/src/esp32c3/esp32c3_irq.c, arch/risc-v/src/fe310/fe310_irq.c, arch/risc-v/src/k210/k210_irq.c, arch/risc-v/src/litex/litex_irq.c, arch/risc-v/src/mpfs/mpfs_irq.c, arch/risc-v/src/rv32m1/rv32m1_irq.c
riscv adds inline IRQ process functions.
=> riscv: Add inline IRQ process functions

arch/xtensa/src/esp32/esp32_i2c.c
This MR only implements the Bit banging approach to perform I2C reset.
NOTE: ESP32 doesn't support neither fms reset neither clear bus via hardware.
Users: ESP32'S I2C users.
Feature: From now on, if a slave gets stuck, master will clock out 9 cycles to clear bus.
I tested using a LA and I2C tool via command `i2c reset`:
=> xtensa/esp32: Adds I2C Bit banging reset

include/limits.h, include/unistd.h, libs/libc/unistd/Make.defs, libs/libc/unistd/lib_getpriority.c, libs/libc/unistd/lib_nice.c, libs/libc/unistd/lib_setpriority.c
And map the nice value more correctly
Add new API(nice) and correct the return value of setpriorty/getpriority
=> libc/sched: Implement nice API

include/net/if.h, libs/libc/net/Make.defs, libs/libc/net/lib_freenameindex.c, libs/libc/net/lib_nameindex.c, net/netdev/netdev.h
Specified here:
https://man7.org/linux/man-pages/man3/if_nameindex.3.html
New API
Internal test case.
=> net: Add if_nameindex and if_freenameindex API

include/nuttx/kthread.h, sched/task/task_create.c
let caller customize the stack buffer
new kernel API
=> sched: Add kthread_create_with_stack

net/tcp/tcp_input.c
* It doesn't make sense to have this conditional on our own
SO_KEEPALIVE support. (CONFIG_NET_TCP_KEEPALIVE)
Actually we don't have a control on the peer tcp stack,
who decides to send us keep-alive probes.
* We should respond them for non ESTABLISHED states. eg. FIN_WAIT_2
See also:
https://github.com/apache/incubator-nuttx/pull/3919#issuecomment-868248576
extracted from https://github.com/apache/incubator-nuttx/pull/3991
tcp
tested on esp32, with the rest of https://github.com/apache/incubator-nuttx/pull/3991
also, @masayuki2009 kindly tested the identical patch with spresense:rndis_smp in telnet character mode.
=> tcp: always responds to keep-alive segments

arch/risc-v/src/bl602/Make.defs, arch/risc-v/src/bl602/bl602_netdev.c
Update wifi firmware version
bl602
BL602 boards
=> risc-v/bl602: update wifi firmware version

fs/mmap/Make.defs, fs/mmap/fs_mmap.c, fs/mmap/fs_mmisc.c, fs/mmap/fs_munmap.c, fs/mmap/fs_rammap.c, fs/mmap/fs_rammap.h
and initialize fs_allmaps_s::exclsem in declaration directly 
New API is added
=> mmap: Implement the minial but reasonable mlock/munlock/mprotect

drivers/sensors/fakesensor.c
1.fix crash casued by closing the handle during the reading.
2.fix set_interval fail sometime:When fakesensor was activated, csv file is not opened timely, so
the sensor->interval that set_interval() seted will be coverd by
interval form csv file.
Signed-off-by: buyuer <dingddding@163.com>
=> driver/fakesensor: fix bugs.

drivers/sensors/hyt271.c
drivers/sensors/hyt271.c:
- struct hyt271_dev_s: Identifier `lock_measure_cylce` was misspelled. Fix to `lock_measure_cycle` and update all instances in the file.
- `hyt271_mr()`, `hyt271_cmd()`, `hyt271_change_addr()`, `hyt271_measure_read()`, `hyt271_thread()`: Update instances of the renamed `lock_measure_cycle` variable and fix various typos in comments.
Improves readability.
nxstyle.
=> drivers/sensors/hyt271: Fix typos in comments and identifier

include/nuttx/lib/lib.h, libs/libc/libc.h, libs/libnx/nxcontext.h, libs/libxx/libxx.hxx
=> libc: Remove the duplication lib_xxx macro

fs/procfs/fs_procfsproc.c
fs/procfs: add StackAlloc field for task stack info
debug
daily test
=> fs/procfs: add StackAlloc field for task stack info

fs/vfs/fs_dup2.c
fs/fs_dup2: correct check before calling dup.
Sanity check
daily test.
=> fs/fs_dup2: (sanity check )correct check before calling dup

drivers/serial/serial.c
=> serial: add ioctl TIOCNOTTY

crypto/random_pool.c
=> Fix asan report error

drivers/lcd/st7789.c
add st7789_putarea()
Signed-off-by: Peter Bee <bijunda1@xiaomi.com>
=> Add putarea() method for st7789

arch/risc-v/src/bl602/Make.defs, arch/risc-v/src/bl602/bl602_efuse.c, arch/risc-v/src/bl602/bl602_efuse.h, arch/risc-v/src/bl602/bl602_netdev.c, arch/risc-v/src/bl602/bl602_romapi.h
Add BL602 efuse driver and separate bl602_romapi.h 
risc-v/bl602
BL602 boards
=> risc-v/bl602: add efuse driver

Kconfig, mm/mm_heap/mm_checkcorruption.c, sched/init/nx_start.c
Add heap & stack check to idle thread
idle
=> Add heap & stack check to idle thread

net/tcp/tcp_send_unbuffered.c
Attempt to fix race condition reported in issue #3647
None.
=> Attempt to fix race condition reported in issue #3647

mm/umm_heap/umm_malloc.c
to reuse the sbrk logic inside memalign
No, code refactor
ostest
=> mm: Call memalign in malloc if ARCH_ADDRENV and BUILD_KERNEL are defined

arch/sim/src/sim/up_heap.c, include/nuttx/kmalloc.h, include/nuttx/lib/lib.h, include/nuttx/mm/mm.h, mm/kmm_heap/Make.defs, mm/kmm_heap/kmm_malloc_size.c, mm/umm_heap/Make.defs, mm/umm_heap/umm_malloc_size.c
make malloc_size implementation align with malloc
Minor change, code reorganization
=> mm: Add kmm_malloc_size and mm_malloc_size

binfmt/binfmt_unloadmodule.c, binfmt/builtin.c, binfmt/elf.c, binfmt/libelf/libelf_init.c, binfmt/libelf/libelf_load.c, binfmt/libelf/libelf_read.c, binfmt/libelf/libelf_uninit.c, binfmt/libnxflat/libnxflat_init.c, binfmt/libnxflat/libnxflat_load.c, binfmt/libnxflat/libnxflat_read.c, binfmt/libnxflat/libnxflat_uninit.c, binfmt/libnxflat/libnxflat_unload.c, binfmt/nxflat.c, fs/mmap/fs_mmap.c, fs/mmap/fs_munmap.c, fs/mmap/fs_rammap.c, fs/mmap/fs_rammap.h, include/nuttx/binfmt/elf.h, include/nuttx/binfmt/nxflat.h, include/nuttx/fs/fs.h
since binfmt is a kernel component and add file_mmap and file_munmap API
binfmt should same as before
=> binfmt: Replace all nx_ API with file_ API

arch/arm/src/armv7-a/arm_doirq.c, boards/arm/imx6/sabre-6quad/README.txt
See the dissussion here: https://github.com/apache/incubator-nuttx/issues/207
Remove the unreachable code
=> arch/armv7-a: Remove the special SMP SGI process

drivers/syslog/syslog_intbuffer.c
syslog/intbuf: force output log when syslog interrupt buffer is full instead 
of adding overrun memssage:"[truncated]\n" to the end.
Change-Id: Ie27cdf0ca902d9ba203619a95162f01222e371c5
=> syslog/intbuf: force output log when syslog interrupt buffer is full

net/tcp/tcp_sendfile.c
quote from https://man7.org/linux/man-pages/man2/sendfile.2.html:
If offset is not NULL, then it points to a variable holding the
file offset from which sendfile() will start reading data from
in_fd.  When sendfile() returns, this variable will be set to the
offset of the byte following the last byte that was read.  If
offset is not NULL, then sendfile() does not modify the file
offset of in_fd; otherwise the file offset is adjusted to reflect
the number of bytes read from in_fd.
If offset is NULL, then data will be read from in_fd starting at
the file offset, and the file offset will be updated by the call.
The change also align with the implementation at:
libs/libc/misc/lib_sendfile.c
Make sendfile more confirm to the standard
=> net/tcp: tcp_sendfile need restore the file location at the end

include/nuttx/wireless/bluetooth/bt_hci.h
=> bluetooth: add more OGF definition

include/sys/poll.h
=> sys/poll: add POLLRDHUP definition

include/netinet/in.h, include/nuttx/net/netconfig.h, net/icmp/icmp_sendmsg.c, net/sixlowpan/sixlowpan_tcpsend.c, net/tcp/tcp_send.c, net/udp/udp_conn.c
=> include/netinet: Add missing IP_TTL definition

include/crc8.h, libs/libc/misc/Make.defs, libs/libc/misc/lib_crc8.c, libs/libc/misc/lib_crc8ccitt.c, libs/libc/misc/lib_crc8table.c
Increase the function of crc8 to use custom polynomials
=> libc: Increase the function of crc8 to use custom polynomials

arch/xtensa/src/esp32/esp32_serial.c
This MR fixes a configuration issue that was found when testing termios example.
The issue was happening because CONF 0 and CONF 1 registers were temporarily cleared in shutdown function
and RX_FIFO_FULL interrupt was being enabled before CONF 1 has been reconfigured in setup function.
This was leading to trigger RX_FIFO_FULL interrupt constantly and hanging the code.
It was solved by changing the sequence of interrupt configuration, placing it after the configuration of registers conf 0 and conf 1. Besides that, although not necessary anymore, the clearance of CONF 0 and CONF 1 registers was removed because setup function overwrites them, it doesn't modify, so this was actually unnecessary code. 
From now on, termios support is working on ESP32.
Termios example.
=> xtensa/esp32: Fixes termios issue.

boards/risc-v/bl602/bl602evb/src/bl602_appinit.c
=> risc-v/bl602: add boardctl support

drivers/rptun/rptun.c
To improve the speed and stability
rptun driver
=> drivers/rptun: replace the notification mech from signal to semaphore

arch/arm/src/lpc17xx_40xx/hardware/lpc17_40_wdt.h
Style fix, as requested [here](https://github.com/apache/incubator-nuttx/pull/4072#discussion_r664032202).
None.
None.
=> lpc17_40: style fix in WDT definitions.

boards/sim/sim/sim/src/sim_bringup.c, drivers/sensors/fakesensor.c
Currently, can only analyze GGA statement.
=> Fakesensor: support gps by read nema csv and delete fakesensor init.

arch/sim/src/sim/up_simsmp.c
Remove the dead code
None, code clean up
ostest with smp
=> arch/sim: Remove the unused sim_host_timer_handler

arch/arm/src/arm/arm_assert.c, arch/arm/src/armv6-m/arm_assert.c, arch/arm/src/armv7-a/arm_assert.c, arch/arm/src/armv7-m/arm_assert.c, arch/arm/src/armv7-r/arm_assert.c, arch/arm/src/armv8-m/arm_assert.c, arch/avr/src/common/up_assert.c, arch/hc/src/m9s12/m9s12_assert.c, arch/mips/src/mips32/mips_assert.c, arch/misoc/src/lm32/lm32_assert.c, arch/misoc/src/minerva/minerva_assert.c, arch/or1k/src/common/up_assert.c, arch/renesas/src/common/up_assert.c, arch/risc-v/src/rv32im/riscv_assert.c, arch/risc-v/src/rv64gc/riscv_assert.c, arch/sim/src/sim/up_assert.c, arch/x86/src/common/up_assert.c, arch/x86_64/src/common/up_assert.c, arch/xtensa/src/common/xtensa_assert.c, arch/z16/src/common/z16_assert.c, arch/z80/src/common/z80_assert.c
use the same condition check in declaration and reference
Fix the compile error in some config combination
Pass internal build
=> arch: Fix rtcb can't found error 

net/rpmsg/rpmsg_sockif.c
Add multi-iov support for rpmsg sockets
=> net/rpmsg: add multi-iov support

net/rpmsg/rpmsg_sockif.c
socket_rpmsg: fix recv block when remote close early
socket_rpmsg: add lock to bind list, reject if list more than backlog
=> Update socket rpmsg

arch/arm/src/kinetis/Kconfig, arch/arm/src/kinetis/kinetis_lpserial.c, arch/arm/src/kinetis/kinetis_lpuart.h
Adds RX DMA for LPUART
None not use in tree
nxp_fmu_k66-xx
=> kinetis lpserial add RX DMA

include/sys/times.h, libs/libc/unistd/Make.defs, libs/libc/unistd/lib_sysconf.c, libs/libc/unistd/lib_times.c
https://pubs.opengroup.org/onlinepubs/009604599/functions/times.html
Note: per task timing isn't supported yet.
New API.
=> libc: Implement times function

arch/sim/src/sim/up_simsmp.c
- I noticed that sim:smp does not work correctly on macOS
due to the recent changes https://github.com/apache/incubator-nuttx/pull/4161
- Actually, it can not receive the IPI host signal, so if
a new task is scheduled on CPU1/2/3, it hangs.
- Finally, I found the issue depends on pthread stack settings
and perhaps it might affect the host signal handling.
- This commit fixes this issue by just reverting the pthread
stack setting only for macOS.
- sim:smp on macOS
- Stack usage for CPU1/2/3 IDLE will be incorrect
- Tested with ostest on macOS 11.4 (x86_64)
=> arch: sim: Workaround to make the IPI work on macOS

sched/irq/irq_spinlock.c, sched/semaphore/spinlock.c
=> sched/*/*spinlock.c: Fix some typos.

boards/xtensa/esp32/common/include/esp32_ht16k33.h, boards/xtensa/esp32/esp32-devkitc/include/board.h, boards/xtensa/esp32/esp32-devkitc/src/esp32-devkitc.h, drivers/lcd/Kconfig
Fix small typos on esp32-devkitc and on HT16K33 driver
none
esp32-devkitc
=> Fix small typos on esp32-devkitc and on HT16K33 driver

arch/arm/src/stm32/Kconfig, arch/arm/src/stm32/stm32_foc.c, arch/arm/src/stm32f0l0g0/hardware/stm32_adc.h, arch/arm/src/stm32h7/Kconfig, arch/arm/src/stm32h7/stm32_allocateheap.c, arch/arm/src/stm32h7/stm32_fmc.c, arch/arm/src/stm32h7/stm32_pmstandby.c, arch/arm/src/stm32h7/stm32_spi.h, arch/arm/src/stm32h7/stm32_spi_slave.c, arch/arm/src/stm32h7/stm32_wwdg.c, arch/arm/src/stm32l4/stm32l4_adc.h, arch/arm/src/stm32l5/Kconfig, arch/arm/src/stm32l5/hardware/stm32l562xx_rcc.h, arch/arm/src/stm32l5/stm32l5_gpio.c, arch/arm/src/stm32l5/stm32l5_gpio.h, arch/arm/src/stm32l5/stm32l5_irq.c, arch/arm/src/stm32l5/stm32l5_rcc.c, arch/arm/src/stm32l5/stm32l5_rcc.h, arch/arm/src/stm32l5/stm32l5_serial.c, arch/arm/src/stm32l5/stm32l5_spi.c
STM32 (various families): Fix typos in code comments and Kconfig help texts.
Improves readability. No functional changes.
nxstyle.
=> Fix typos in code comments and Kconfig help texts.

Documentation/platforms/risc-v/bl602/index.rst, tools/bl602/partition_cfg_2M_nuttx.toml
- Documentation/bl602: Update some imformation;
- Add partition.toml in tool/bl602
None
- Compile ok
- Run demo ok
=> Documentation/bl602: Update some imformation

include/nl_types.h, libs/libc/locale/Kconfig, libs/libc/locale/Make.defs, libs/libc/locale/lib_catalog.c
See the description here:
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/nl_types.h.html
New API
=> libc: Support message catalog function

include/nuttx/tls.h, libs/libc/misc/lib_umask.c
Like how getopt save it's state.
The result is same as before
=> fs: Save umask to tls_task_s for non kernel mode only

mm/mm_heap/mm.h, mm/mm_heap/mm_addfreechunk.c, mm/mm_heap/mm_initialize.c, mm/mm_heap/mm_malloc.c
mm/mm_heap/mm.h: Fix some typos.
N/A
N/A
=> mm: Fix some typos.

libs/libc/time/lib_localtime.c
tzset: avoid taking semaphore in interrupt for non-kernel mode
Change-Id: Ic72819eddb38621751e462fe32e9e433288fb33c
=> tzset: avoid taking semaphore in interrupt for non-kernel mode

arch/arm/src/imxrt/imxrt_flexpwm.c
This commit changes the FLexPWM driver for iMXRT MCU so that LDOK bits in Master Control Register are set at once after all channels are configured. Setting LDOK bit enables the driver to load prescaler, modulus and PWM values of corresponging submodule and start PWM output. Setting all bits at once instead of doing it separately can help avoiding the channels to
be out of sync with each other.
iMXRT PWM driver only.
Tested with Teensy 4.1 board.
=> arch/arm/src/imxrt/imxrt_flexpwm.c: Set LDOK bits after all channels are set

arch/arm/src/stm32/stm32_pwm.c
Fix a problem that happens when we try to stop and restart a PWM signal. The problem seems to be related with pwm_stop() function. This function set PWM frequency to zero and reset TIMER peripheral to it's default state. From my understanding the pwm_start() funtion is not able to reconfigure the timer to a functional state. So I change this function to disable the timer and timer outputs.
This change may break stm32_pwm driver.
Tested on:
- nucleo-g431:pwm
- stm32f334-disco:powerled
=> stm32_pmw: fix pwm_stop() function to enable multiple PWM start and stop

arch/arm/include/armv6-m/irq.h, arch/arm/include/armv7-m/irq.h, arch/arm/include/armv8-m/irq.h, arch/arm/src/cxd56xx/cxd56_start.c, arch/arm/src/efm32/efm32_start.c, arch/arm/src/eoss3/eoss3_start.c, arch/arm/src/imxrt/imxrt_start.c, arch/arm/src/kinetis/kinetis_start.c, arch/arm/src/lpc17xx_40xx/lpc17_40_start.c, arch/arm/src/lpc43xx/lpc43_start.c, arch/arm/src/lpc54xx/lpc54_start.c, arch/arm/src/max326xx/common/max326_start.c, arch/arm/src/nrf52/nrf52_start.c, arch/arm/src/s32k1xx/s32k1xx_start.c, arch/arm/src/sam34/sam_start.c, arch/arm/src/samd5e5/sam_start.c, arch/arm/src/samv7/sam_start.c, arch/arm/src/stm32/stm32_start.c, arch/arm/src/stm32f7/stm32_start.c, arch/arm/src/stm32h7/stm32_start.c, arch/arm/src/stm32l4/stm32l4_start.c, arch/arm/src/stm32l5/stm32l5_start.c, arch/arm/src/tiva/cc13xx/cc13xx_start.c, arch/arm/src/tiva/common/lmxx_tm4c_start.c, arch/arm/src/xmc4/xmc4_start.c
and replace all hardcode value
code refector, no real change
=> arch/arm: Add CONTROL register bit field definition

Documentation/faq/index.rst
Add more entries about board initialization
It will help user to get their applications initialized
N/A
=> Doc/FAQ: Add more entries about board initialization

fs/hostfs/hostfs_rpmsg_server.c
Minor refactor, no real change
=> fs/hostfs: Change all priv_ to priv

drivers/mtd/mtd_partition.c, drivers/mtd/smart.c
Fix compilation warning
Improve compilation
sim:smartfs
=> mtd/smartfs: Fix compilation warning

fs/unionfs/fs_unionfs.c
Follow up PR: #4153
New feature
=> fs/unionfs: Support fchstat and chstat callback

fs/userfs/fs_userfs.c, include/nuttx/fs/userfs.h, libs/libc/userfs/lib_userfs.c
Follow up PR: https://github.com/apache/incubator-nuttx/pull/4153
New feature
=> fs/userfs: Support fchstat and chstat callback

Documentation/platforms/xtensa/esp32/index.rst
Fix wapi psk command, value 1 is for open WEP
Now users will able to connect
ESP32-Devkit
=> Doc/esp32: Fix wapi psk command, value 1 is for WEP

fs/driver/fs_blockpartition.c
Follow up PR: https://github.com/apache/incubator-nuttx/pull/4248
block partition return the partition info too.
=> fs/partition: Support BIOC_PARTINFO

arch/arm/src/arm/arm_reprioritizertr.c, arch/arm/src/armv6-m/arm_reprioritizertr.c, arch/arm/src/armv7-a/arm_reprioritizertr.c, arch/arm/src/armv7-m/arm_reprioritizertr.c, arch/arm/src/armv7-r/arm_reprioritizertr.c, arch/arm/src/armv8-m/arm_reprioritizertr.c, arch/avr/src/avr/up_reprioritizertr.c, arch/avr/src/avr32/up_reprioritizertr.c, arch/hc/src/common/up_reprioritizertr.c, arch/mips/src/mips32/mips_reprioritizertr.c, arch/misoc/src/lm32/lm32_reprioritizertr.c, arch/misoc/src/minerva/minerva_reprioritizertr.c, arch/or1k/src/common/up_reprioritizertr.c, arch/renesas/src/common/up_reprioritizertr.c, arch/risc-v/src/rv32im/riscv_reprioritizertr.c, arch/risc-v/src/rv64gc/riscv_reprioritizertr.c, arch/sim/src/sim/up_reprioritizertr.c, arch/x86/src/common/up_reprioritizertr.c, arch/x86_64/src/common/up_reprioritizertr.c, arch/xtensa/src/common/xtensa_reprioritizertr.c, arch/z16/src/common/z16_reprioritizertr.c, arch/z80/src/common/z80_reprioritizertr.c, include/nuttx/arch.h, sched/sched/sched_processtimer.c, sched/sched/sched_timerexpiration.c
Fix few typos in arch/ and sched/
N/A
N/A
=> Fix few typos in arch/ and sched/

fs/littlefs/Kconfig, fs/littlefs/lfs_vfs.c
=> fs/littlefs: improve littlefs flash block erase balance performance

arch/arm/src/armv7-m/nvic.h, arch/arm/src/armv8-m/nvic.h, arch/arm/src/cxd56xx/cxd56_start.c, arch/arm/src/efm32/efm32_start.c, arch/arm/src/eoss3/eoss3_start.c, arch/arm/src/imxrt/imxrt_start.c, arch/arm/src/kinetis/kinetis_start.c, arch/arm/src/lpc17xx_40xx/lpc17_40_start.c, arch/arm/src/lpc43xx/lpc43_start.c, arch/arm/src/lpc54xx/lpc54_start.c, arch/arm/src/max326xx/common/max326_start.c, arch/arm/src/nrf52/nrf52_start.c, arch/arm/src/s32k1xx/s32k1xx_start.c, arch/arm/src/sam34/sam_start.c, arch/arm/src/samd5e5/sam_start.c, arch/arm/src/samv7/sam_start.c, arch/arm/src/stm32/stm32_start.c, arch/arm/src/stm32f7/stm32_start.c, arch/arm/src/stm32h7/stm32_start.c, arch/arm/src/stm32l4/stm32l4_start.c, arch/arm/src/stm32l5/stm32l5_start.c, arch/arm/src/tiva/cc13xx/cc13xx_start.c, arch/arm/src/tiva/common/lmxx_tm4c_start.c, arch/arm/src/xmc4/xmc4_start.c
=> arch/arm: Add NVIC_FPCCR_XXX macro to avoid the hard code value

tools/esp32/backtrace.gdbscript
tools/esp32/backtrace.gdbscript: Add a few convenient functions
tools/esp32/backtrace.gdbscript only
a slight variation was tested with esp32-devkitc + openocd + gdb
=> tools/esp32/backtrace.gdbscript: Add a few convenient functions

arch/risc-v/src/bl602/bl602_netdev.c
Fix that AP cannot be start when STA have been started.
none
none
=> riscv/bl602: Fix that AP cannot be start when STA have been started.

fs/driver/fs_blockpartition.c, fs/driver/fs_mtdpartition.c, include/nuttx/fs/fs.h
Follow up PR: https://github.com/apache/incubator-nuttx/pull/4193
64bit support
=> fs: Support 64bit in register_[block|mtd]partition

Kconfig, drivers/video/Kconfig
This commit adds the possibility to isolate the GPL code from Apache/BSD/MIT code
LICENSE
Compiled
=> Kconfig: add NuttX License setup

arch/risc-v/src/common/riscv_internal.h
riscv/common: add CURRENT_REGS declare in RV32 
N/A
CI-Check is enough
=> riscv/common: add CURRENT_REGS declare in RV32 

boards/arm/sama5/sama5d3x-ek/configs/ov2640/defconfig
Fix the build break by: https://github.com/apache/incubator-nuttx/pull/4352
Pass CI
=> sama5d3x-ek/ov2640: Enable CONFIG_ALLOW_GPL_COMPONENT

arch/arm/src/armv8-m/arm_sau.c, arch/arm/src/armv8-m/sau.h
Secure Attribute Unit is a new component to speicfiy the non-secure/non-secure callable region.
New API for secure mode
=> arch/armv8-m: Add SAU support

arch/risc-v/src/rv32im/riscv_assert.c, arch/risc-v/src/rv64gc/riscv_assert.c
arch/riscv/assert: enhance the assert dump 
enhance the assert dump to show the all tasks info including backtrace and registers
assert dump
```
[    4.649000] [ EMERG] riscv_exception: PANIC!!! Exception = 00000005
[    4.649000] [ EMERG] up_assert: Assertion failed at file:rv32im/riscv_exception.c line: 94 task: init
[    4.649000] [ EMERG] riscv_dumpstate: Call Trace:
[    4.649000] [  INFO] [BackTrace| 3|0]:  0x42020026 0x42007cbc 0x42005782 0x42000fe2 0x403801e2 0x403800e2 0x4200bdd8 0x4200989c
[    4.649000] [  INFO] [BackTrace| 3|1]:  0x4200a636 0x42008e92 0x42008426 0x42008328 0x42005ad0 0x42001a56
[    4.649000] [ EMERG] riscv_registerdump: EPC:4200bdd8 
[    4.649000] [ EMERG] riscv_registerdump: A0:ffffffff A1:00000010 A2:3fc9a95c A3:00000031 A4:00000009 A5:00000002 A6:00000001 …
```
=> arch/riscv/assert: enhance the assert dump 

Documentation/platforms/risc-v/esp32c3/index.rst
Update ESP32-C3 supported peripheral list.
N/A
N/A
=> Documentation: Update ESP32-C3 supported peripheral list.

Documentation/index.rst
Contributing is an important thing and should be at a more visible position
It will easier for people with ADHD (myself inclusive) to find it.
N/A
=> Move "Contributing" to be after getting started

arch/arm/src/armv7-a/arm_testset.S, arch/arm/src/armv7-m/gnu/arm_testset.S, arch/arm/src/armv7-m/iar/arm_testset.S, arch/arm/src/armv7-r/arm_testset.S, arch/arm/src/armv8-m/arm_testset.S, arch/arm/src/cxd56xx/cxd56_testset.c, arch/arm/src/lc823450/lc823450_testset.c, arch/arm/src/rp2040/rp2040_testset.c, arch/risc-v/src/rv64gc/riscv_testset.S, arch/sim/src/sim/up_testset.c, arch/xtensa/src/common/xtensa_testset.c, include/nuttx/spinlock.h
arch/*_testset: Fix few typos.
N/A
N/A
=> arch/*_testset: Fix few typos.

net/tcp/tcp.h, net/tcp/tcp_input.c, net/tcp/tcp_send_buffered.c
tcp: some fixes in snd_wnd processing
see the commit messages for details.
tcp
tested with the rest of https://github.com/apache/incubator-nuttx/pull/4184
=> tcp: some fixes in snd_wnd processing

arch/arm/src/arm/Toolchain.defs, arch/arm/src/armv6-m/Toolchain.defs, arch/arm/src/armv7-a/Toolchain.defs, arch/arm/src/armv7-m/Toolchain.defs, arch/arm/src/armv7-r/Toolchain.defs, arch/arm/src/armv8-m/Toolchain.defs, arch/avr/src/avr/Toolchain.defs, arch/avr/src/avr32/Toolchain.defs, arch/hc/src/Makefile, arch/mips/src/mips32/Toolchain.defs, arch/misoc/src/lm32/Toolchain.defs, arch/misoc/src/minerva/Toolchain.defs, arch/or1k/src/mor1kx/Toolchain.defs, arch/renesas/src/Makefile, arch/risc-v/src/rv32im/Toolchain.defs, arch/risc-v/src/rv64gc/Toolchain.defs, arch/x86/src/Makefile, arch/x86_64/src/Makefile, arch/xtensa/src/lx6/Toolchain.defs, arch/xtensa/src/lx7/Toolchain.defs, boards/arm/stm32/stm32f4discovery/README.txt, libs/libxx/Kconfig, libs/libxx/Makefile
align with other Kconfig(e.g. LIBCXXABI, LIBCXX, UCLIBCXX)
One seldom used option name change
Pass C++ project CI
=> libxx: Change CXX_LIBSUPCXX to LIBSUPCXX

drivers/sensors/lsm6dsl.c
Modified the logic of the selftest according to the ST manual.
Signed-off-by: yangjiukui <yangjiukui@xiaomi.com>
Change-Id: Id55139abf173728de4647533b26f7ab5e9a6b1fe
lsm6dsl selftest result.
daily test.
=> sensor: fix the bug that lsm6dsl selftest is invalid in nuttx.

openamp/Makefile, openamp/libmetal.defs, openamp/open-amp.defs, tools/Directories.mk, tools/Makefile.unix, tools/Makefile.win
Follow up PR: https://github.com/apache/incubator-nuttx/pull/4369
OpenAMP library and user
Pass CI
=> openamp: Move the download to context target

libs/libxx/libcxx.defs, libs/libxx/libcxxabi.defs, libs/libxx/uClibc++.defs
and move libcxxabi special setting from libcxx.defs to libcxxabi.defs
Build system
Pass CI
=> libxx: Give VERSION make variable prefix to avoid the conflict

libs/libxx/0001-uClibcxx-basic_definitions-fix-GCC-specific-definiti.patch, libs/libxx/0002-uClibc-add-weak-function-for-new-del-operations.patch, libs/libxx/uClibc++.defs
=> uClibcxx: add weak attribute for new/del ops

AUTHORS, drivers/net/ftmac100.c, drivers/wireless/ieee802154/at86rf23x/at86rf23x.c, drivers/wireless/ieee802154/at86rf23x/at86rf23x.h, fs/vfs/fs_epoll.c, include/nuttx/net/ftmac100.h
Anton D. Kachalov has submitted the ICLA
Matt Poppe has submitted the ICLA 
as a result we can migrate the licenses to Apache.
LICENSE
NONE
=> author: Anton D. Kachalov: update licenses to Apache

AUTHORS, Kconfig, arch/arm/src/stm32/stm32_1wire.c, arch/arm/src/stm32/stm32_1wire.h, arch/arm/src/stm32l4/stm32l4_1wire.c, arch/arm/src/stm32l4/stm32l4_1wire.h, include/nuttx/1wire/1wire.h
Aleksandr Vyhovanec has submitted the ICLA
as a result we can migrate the licenses to Apache.
LICENSE
NONE
=> author: Aleksandr Vyhovanec: update licenses to Apache

drivers/mmcsd/mmcsd_sdio.c
Unify the prefix usage
Minor
Pass CI.
=> drivers/mmcsd: Change mmsd_ prefix to mmcsd_ prefix

sched/wdog/wd_start.c
Recent change presented in commit 9116ed9247 (PR #4413) moved wd_expiration() outside
while loop. This was causing hard faults when running configuration with
enabled Tickless Mode with Alarm. The current change fixes this problem.
Tested on Teensy 4.1 board. Probably worthy to do some other tests on different platforms with Alarm turn on if anyone has them available.
=> sched/wdog/wd_start.c: prevent accessing watch-dog lag if head is NULL

include/nuttx/video/fb.h
Signed-off-by: liushuai25 <liushuai25@xiaomi.com>
=> modify comments

tools/checkpatch.sh
Add check gerrit Change-Id support, issue an error when a Change-Id line is encountered.
Test this patch with Change-Id firstly.
=> checkpatch.sh: add check gerrit Change-Id support

net/rpmsg/rpmsg_sockif.c
Let's add prefix "rpmsg-socket" for the name of rpmsg endpoint because it's so ugly when rp_path is just numbers.
The user interface is not affected
daily test.
=> rpmsg_socket: add prefix "rpmsg-socket" for the name of rpmsg endpoint

libs/libc/stdio/lib_libfread.c
Return the number of bytes actually read when error occurs.
Avoiding data lose
daily test.
=> lib_fread: return the number of bytes actually read when error occurs.

drivers/lcd/Kconfig, drivers/lcd/lcd_dev.c, drivers/video/Kconfig, drivers/video/fb.c, include/nuttx/lcd/lcd.h, include/nuttx/lcd/lcd_dev.h, include/nuttx/video/fb.h
* add get and set panel power interface for fb driver.
* add get and set framerate interface for fb driver.
* add panel information at videoinfo for fb driver.
* add get and set framerate interface for lcd dev driver.
=> add new interface for fb driver and lcd dev driver

AUTHORS, LICENSE, boards/arm/tiva/tm4c123g-launchpad/src/tm4c_mcp2515.c, drivers/analog/dac7571.c, drivers/input/ft5x06.c, drivers/input/ft5x06.h, drivers/modem/Make.defs, drivers/sensors/kxtj9.c
ICLA has been received and we can update licenses to Apache
LICENSE
NONE
=> LICENSE: update licenses to Apache

include/sys/socket.h
sys/socket/scm: add more socket message control helper
N/A, socket control message define
compile pass
=> sys/socket/scm: add more socket message control helper

net/local/local_sockif.c
net/local: add FIONSPACE support 
N/A just api forward
ioctl FIONSPACE on local socket
=> net/local: add FIONSPACE support 

drivers/lcd/Kconfig, drivers/lcd/Make.defs, drivers/lcd/gc9a01.c, drivers/lcd/gc9a01.h, drivers/lcd/st7735.h, include/nuttx/lcd/gc9a01.h
Added custom resolution, offset and BGR mode for ST7735 driver
Added GC9A01 driver (based on ST7789 driver)
Tested on ESP32C3
=> drivers/lcd: Add GC9A01 driver and refine ST7735

arch/xtensa/src/common/xtensa_backtrace.c
The registers may be in window when in interrupt.
Flush window stack to stack first.
And fix warning in build.
Change-Id: I45f3a8e6aa4f8baa1d54871a02bd6defc8915144
No
Test with  xtensa interrupt
=> xtensa:backtrace: flush to stack when in interrupt

include/nuttx/irq.h, sched/irq/irq_csection.c
sched/irq/irq_csection.c: Fix typos and correct some comments.
N/A
N/A
=> sched/irq/irq_csection.c: Fix typos and correct some comments.

arch/arm/src/cxd56xx/cxd56_serial.c
- This commit replaces the critical section with spinlock in cxd56_serial.c
- None
- Tested with spresense:rndis_smp, spresense:rndis
and spresense:rndis_wifi
=> arch: cxd56xx: Replace the critical section with spinlock in cxd56_serial.c

fs/procfs/fs_procfsproc.c
Follow task_state in tcb_s.
No
=> fs:procfs: add waiting_paging_fill state names

arch/risc-v/src/esp32c3/esp32c3_rt_timer.c
Fix on esp32c3_rt_timer.c:  Group static variables into a struct and prevent an uninitialized thread to be deleted.
Organization.
Prevent a potential bug.
Internal rt_timer test.
=> risc-v/esp32-c3: Group static variables into a struct and prevent an uninitialized thread to be deleted

arch/arm/src/armv7-m/Toolchain.defs, arch/arm/src/armv8-m/Toolchain.defs
since -mcpu is enough https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58869
Should be same as before
=> arch/arm: Remove -march and -mtune

include/glob.h, libs/libc/misc/Make.defs, libs/libc/misc/lib_glob.c
Add `glob`.
Reference:
https://man7.org/linux/man-pages/man7/glob.7.html
=> libc/misc: add lib_glob

include/nuttx/input/touchscreen.h
Signed-off-by: futerigele <futerigele@xiaomi.com>
- Added IO command to get the firmware version of the touch IC.
=> input/touch: add io command for touch firmware version

tools/lwl/ocdconsole.py
This patch simply transfers copyright of this module from myself to Greg Nutt.
=> Copyright transfer

arch/arm/src/cxd56xx/cxd56_charger.c, arch/arm/src/cxd56xx/cxd56_gauge.c, include/nuttx/power/battery_charger.h, include/nuttx/power/battery_gauge.h, include/nuttx/power/battery_ioctl.h, include/nuttx/power/battery_monitor.h
so the userspace program can handle the different battery driver equally
Same as before
=> power/battery: Move the enumurate to the common place

arch/sim/src/sim/up_idle.c
Open CONFIG_PM compilation sim failed
=> power: Open CONFIG_PM compilation failed

drivers/mtd/m25px.c
Adds support for MT25Q256 SPI NOR
Tested with LittleFS filesystem.
=> drivers/mtd/m25px.c: add support for MT25Q256 SPI NOR

include/nuttx/lib/lib.h, sched/init/nx_start.c
=> libc: Remove the empty lib_initialize

arch/arm/src/stm32h7/hardware/stm32_dmamux.h
Correct bit fields for Dmamux registers
=> stm32h7/dmamux: correct bit fields

mm/mm_heap/mm_realloc.c
mm: fix realloc overwrite memcpy when use a new block
mm
=> mm: fix realloc overwrite memcpy when use a new block

boards/arm/stm32/b-g431b-esc1/README.txt, boards/arm/stm32/b-g431b-esc1/include/board.h, boards/arm/stm32/b-g431b-esc1/src/b-g431b-esc1.h, boards/arm/stm32/b-g431b-esc1/src/stm32_bringup.c, boards/arm/stm32/b-g431b-esc1/src/stm32_foc.c
boards/b-g431b-esc1: add Hall and Qenco support
=> boards/b-g431b-esc1: add Hall and Qenco support

drivers/wireless/ieee80211/bcm43xxx/bcmf_sdio.c
Fix for my previous PR #4690.
bcm43xxx driver
=> bcm43xxx: corrected SDIO_CCCR_HIGHSPEED_SHS bit handling

Documentation/platforms/risc-v/esp32c3/index.rst
List the supported ESP32-C3 boards.
ESP32-C3 Documentation.
=> Documentation/esp32c3: List the supported ESP32-C3 boards.

drivers/input/Kconfig, drivers/input/Make.defs, drivers/input/touchscreen_upper.c, include/nuttx/input/touchscreen.h
Separate the interface for user interaction, touch upper half provides the interface uniformly.
It was successfully tested on my custom board.
=> input/touchscreen: separate the interface for user interaction

drivers/note/Kconfig, drivers/note/notectl_driver.c, sched/Kconfig
Fix some typos in the note driver.
N/A
N/A
=> drivers/note:  Fix typos.

arch/xtensa/src/common/xtensa_backtrace.c
=> xtensa_backtrace: fix typ error

include/nuttx/input/touchscreen.h
added time stamp for touchscreen event
Signed-off-by: futerigele <futerigele@xiaomi.com>
added time stamp for touchscreen event
=> input/touchscreen: added time stamp for touchscreen event

arch/xtensa/include/setjmp.h
=> xtensa: add setjmp.h include file

libs/libc/stdio/lib_fgetpos.c, libs/libc/stdio/lib_fseek.c, libs/libc/stdio/lib_fseeko.c, libs/libc/stdio/lib_fsetpos.c, libs/libc/stdio/lib_ftell.c, libs/libc/stdio/lib_ftello.c
=> lib/stdio: Handle 64bits off_t correctly

arch/arm/src/stm32/stm32_foc.c, arch/sim/src/sim/up_foc.c, drivers/motor/foc/foc_dev.c, drivers/motor/motor.c, include/nuttx/motor/foc/foc.h, include/nuttx/motor/motor.h
driver/motor: add upperhalf structure and optimize code.
optimize code
daily test
=> driver/motor: add upperhalf structure

sched/sched/sched_addreadytorun.c, sched/sched/sched_cpuselect.c, sched/sched/sched_lock.c, sched/sched/sched_mergeprioritized.c, sched/sched/sched_unlock.c
Fix some typos in comments.
N/A
N/A
=> sched/sched: Fix some typos in comments.

libs/libc/stdio/Make.defs, libs/libc/stdio/lib_sprintf.c
=> libc/stdio: Move source files to the right Makefile section

drivers/audio/cxd56.c, drivers/audio/cxd56_src.c, drivers/audio/cxd56_src.h
several patches to improve audio on the Sony Spresense board
Spresense
Spresense
=> drivers: audio: cxd56: various audio fixes

arch/arm/include/elf.h, arch/sim/include/elf.h, include/elf.h, include/elf32.h, include/elf64.h
elf: add elf define of Note Section
arch/arm: add more arch elf define
arch/sim: add arch elf define
N/A, just new elf definitions
compile pass
=> elf: add elf define of Note Section

include/nuttx/streams.h, libs/libc/stdio/lib_memoutstream.c, libs/libc/stdio/lib_rawsostream.c, libs/libc/stdio/lib_stdoutstream.c
libs/libc: add interface to support output stream as buffer style
Interface extension for  struct lib_outstream_s
run lib_outstream_s on stream mode
=> libs/libc: add interface to support output stream as buffer style

arch/arm/src/stm32f7/stm32_sdmmc.c
The FAT was not coherent. Resulting in a write failed
with errno:28 No space left on device.
It is unclear how the memory is acesses prior to the DMA
completion. But this restructuring ensures the data
is coherent.
This issue was not detected on the stm32h7
Random files system failures have been resolved.
px4_fmu-v5
=> stm32f7:sdmmc defer invalidate until after DMA completion

drivers/power/battery_charger.c, drivers/power/battery_gauge.c, drivers/power/battery_monitor.c, include/nuttx/power/battery_charger.h, include/nuttx/power/battery_gauge.h, include/nuttx/power/battery_ioctl.h, include/nuttx/power/battery_monitor.h
=> improve charger interface

arch/risc-v/src/esp32c3/esp32c3_adc.c
Use calibration parameters from efuse rather than self-calibration.
=> risc-v/esp32c3: Refactor ADC calibration

include/string.h, libs/libc/machine/Kconfig, libs/libc/string/Make.defs, libs/libc/string/lib_strlcat.c
=> libc/str:add strlcat to libc

include/netinet/in.h
add net mask define and use `in_addr_t` insdie of `uint32 ` in `IN_CLASSD(i)`
dliaytest
=> inculude/netinet:add net mask define

include/sys/stat.h, libs/libc/misc/Make.defs, libs/libc/misc/lib_mknod.c
Define here:
https://pubs.opengroup.org/onlinepubs/007904875/functions/mknod.html
New API.
=> libc: Add mknod implementation

include/nuttx/net/mii.h
=> Cerrypick ksz8061 regs

include/cxx/cinttypes
Signed-off-by: buyuer <dingddding@163.com>
=> Add cinttypes header file for mini-cxxlib.

include/nuttx/input/touchscreen.h
added touchscreen gesture
Signed-off-by: futerigele <futerigele@xiaomi.com>
=> input/touchscreen: added touchscreen gesture

LICENSE, tools/size_report
Add a resource statistics script, which can be used to
analyze the resource occupation of ELF files, including
BSS, data, ROM, etc.
Signed-off-by: Lingao Meng <menglingao@xiaomi.com>
=> tools: Add size report script

arch/risc-v/src/esp32c3/Kconfig, arch/risc-v/src/esp32c3/Make.defs, arch/risc-v/src/esp32c3/esp32c3_ble.c, arch/risc-v/src/esp32c3/esp32c3_ble_adapter.c, arch/risc-v/src/esp32c3/esp32c3_irq.c, arch/risc-v/src/esp32c3/esp32c3_partition.c, arch/risc-v/src/esp32c3/esp32c3_spiflash.c, arch/risc-v/src/esp32c3/esp32c3_spiflash_mtd.c, arch/risc-v/src/esp32c3/esp32c3_spiflash_mtd.h, arch/risc-v/src/esp32c3/esp32c3_wireless.c, arch/risc-v/src/esp32c3/esp32c3_wireless.h, arch/risc-v/src/esp32c3/hardware/extmem_reg.h, arch/risc-v/src/esp32c3/rom/esp32c3_spiflash.h, boards/risc-v/esp32c3/esp32c3-devkit/scripts/esp32c3.ld, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3-devkit.h, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_bringup.c, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_spiflash.c
This can fix BLE assert when erase SPI Flash.
=> risc-v/esp32c3: Refactor SPI Flash to support umask interrupt when R/W/E SPI Flash

arch/arm/src/arm/arm_tcbinfo.c, arch/arm/src/armv6-m/arm_tcbinfo.c, arch/arm/src/armv7-a/arm_tcbinfo.c, arch/arm/src/armv7-m/arm_tcbinfo.c, arch/arm/src/armv7-r/arm_tcbinfo.c, arch/arm/src/armv8-m/arm_tcbinfo.c, arch/risc-v/src/common/riscv_tcbinfo.c, include/nuttx/sched.h
Change-Id: I942bb882b6e52f43a461883dd0d26775a7654343
=> arch/tcbinfo: fix build break if task name disabled

arch/arm/src/armv7-m/nvic.h, arch/arm/src/armv8-m/nvic.h
cortex-m/fault: add CFSR(Configurable Fault Status Register) Definitions
N/A
ci check pass
=> cortex-m/fault: add CFSR(Configurable Fault Status Register) Definitions

drivers/syslog/vsyslog.c
make the output format consistent
Minor change
internal device
=> syslog: Add [] around the prefix like others

fs/hostfs/hostfs.c
hostfs: add lock to hostfs_rewinddir
hostfs
VELA
=> hostfs: add lock to hostfs_rewinddir

audio/audio_comp.c
audio/audio_comp.c: capbility should use collections
audio/audio_comp
VELA
=> audio/audio_comp.c: capbility should use collections

drivers/rptun/rptun.c, openamp/0006-openamp-fix-scenario-case.patch, openamp/open-amp.defs
rptun: support can_recursive check for openamp
rptun
VELA
=> rptun: support can_recursive check for openamp

net/netdev/netdev_ioctl.c, net/rpmsg/rpmsg_sockif.c
socket rpmsg add ioctl & fix unblock connect crash
socket rpmsg
VELA
=> socket rpmsg add ioctl & fix unblock connect crash

include/nuttx/semaphore.h, sched/wqueue/kwork_thread.c
wqueue: update wqueue to support using wqueue before wqueue start
wqueue
VELA
=> wqueue: update wqueue to support using wqueue before wqueue start

include/nuttx/sched_note.h, sched/Kconfig, sched/sched/sched_note.c
trace: and sched note dump
note_type NOTE_DUMP_STRING API:
```
sched_note_string
sched_note_vprintf
sched_note_printf
```
note_type NOTE_DUMP_BINARY API:
```
sched_note_dump
sched_note_vbprintf
sched_note_bprintf
```
Pair with https://github.com/apache/incubator-nuttx-apps/pull/916
=> trace: and sched note dump

drivers/mtd/mtd_nand.c, drivers/net/enc28j60.c, drivers/net/encx24j600.c, include/nuttx/mtd/nand.h
=> typo: fix type for word "instance"

include/stdlib.h, libs/libc/stdlib/Make.defs, libs/libc/stdlib/lib_getprogname.c
defined here:
https://www.freebsd.org/cgi/man.cgi?query=getprogname&sektion=3
New API
Pass CI
=> libc: Add getprogname function

drivers/ioexpander/Kconfig, drivers/ioexpander/Make.defs, drivers/ioexpander/ioe_rpmsg.c, include/nuttx/ioexpander/ioe_rpmsg.h
=> ioe expander: add ioe_rpmsg server and client

include/nuttx/net/netconfig.h, include/sys/syscall_lookup.h, libs/libc/net/Make.defs, libs/libc/net/lib_indextoname.c, libs/libc/net/lib_nametoindex.c, net/netdev/Make.defs, net/netdev/netdev.h, syscall/syscall.csv
And implement them on top of SIOCGIFINDEX and SIOCGIFNAME
Implementation detail, the result is same as before
Pass CI
=> net: Move if_nametoindex and if_indextonameto to libc 

arch/arm/src/samv7/hardware/sam_uart.h, arch/arm/src/samv7/sam_serial.c, include/nuttx/serial/tioctl.h
Initial support for LIN Master
No impact. None of the example applications use this feature
Pass CI
=> arch/arm/samv7: initial support for LIN bus communication (Master only)

include/ifaddrs.h, include/net/if.h, libs/libc/net/Make.defs, libs/libc/net/lib_freeifaddrs.c, libs/libc/net/lib_getifaddrs.c
specify here:
https://man7.org/linux/man-pages/man3/getifaddrs.3.html
New API
Pass CI
=> net: Implement getifaddrs and freeifaddrs

drivers/power/regulator.c
=> regulator: fix warning in RPIu32

drivers/clk/clk_rpmsg.c, drivers/power/Kconfig, drivers/power/regulator_rpmsg.c, include/nuttx/clk/clk_provider.h, include/nuttx/power/regulator.h
regulator/clk rpmsg: pending on wait IPC channel ready
Add new feature
=> regulator/clk rpmsg: pending on wait IPC channel ready

Documentation/platforms/xtensa/esp32/index.rst
Add documentation about BLE for ESP32
Users will be able to test BLE
N/A
=> doc/esp32: Add documentation about BLE for ESP32

arch/xtensa/src/esp32/esp32_systemreset.h, arch/xtensa/src/esp32/esp32_wifi_adapter.c, arch/xtensa/src/esp32/esp32_wifi_adapter.h, arch/xtensa/src/esp32/esp32_wireless.c, arch/xtensa/src/esp32/esp32_wlan.c, boards/xtensa/esp32/esp32-devkitc/src/esp32_reset.c
1. Fix the issue that Wi-Fi can't connect to some special routers occasionally.
2. Update Wi-Fi driver code to fix issue of failure to send pkt.
3. Replace software random with hardware random
Fix some ESP32 Wi-Fi driver issues
`esp32-devkitc`
=> xtensa/esp32: Fix some Wi-Fi issues

arch/arm/src/common/arm_backtrace_thumb.c
=> arch/arm: Fix rebase error in arm_backtrace_thumb.c

drivers/wireless/ieee80211/bcm43xxx/Kconfig, drivers/wireless/ieee80211/bcm43xxx/Make.defs, drivers/wireless/ieee80211/bcm43xxx/bcmf_chip_43362.c, drivers/wireless/ieee80211/bcm43xxx/bcmf_chip_43455.c, drivers/wireless/ieee80211/bcm43xxx/bcmf_core.c, drivers/wireless/ieee80211/bcm43xxx/bcmf_core.h, drivers/wireless/ieee80211/bcm43xxx/bcmf_sdio.c, drivers/wireless/ieee80211/bcm43xxx/bcmf_sdio.h, drivers/wireless/ieee80211/bcm43xxx/bcmf_sdio_core.h
Supported ARM CR4 core in bcm43xxx driver and bcm43455 chip in particular.
bcm43xxx driver
=> bcm43xxx: supported ARM CR4 core and bcm43455 chip in particular

graphics/vnc/server/vnc_fbdev.c, graphics/vnc/server/vnc_server.c, graphics/vnc/server/vnc_server.h, graphics/vnc/server/vnc_updater.c
Support vsync on virtual device vnc server to avoid tearing.
VNC server only
Tested on sim with custom configuration.
=> graphics/vncserver: Implement vsync

include/nuttx/serial/uart_16550.h
Allow register address width up to 64 bit 
uart16550 only.
CI and custom boards.
=> drivers/serial/uart16550: Support 64bit platform

net/tcp/tcp_send_unbuffered.c
Fast retransmit on duplicate acknowledgments (RFC 5681).
This PR is like PR #2414, but for unbuffered mode.
TCP
Activate emulating packet loss on Linux host:
`$ sudo iptables -A INPUT -p tcp --dport 5471 -m statistic --mode random --probability 0.01 -j DROP`
Build NuttX:
```
$ ./tools/configure.sh -l sim:tcpblaster
$ make menuconfig (disable CONFIG_NET_TCP_WRITE_BUFFERS, enable CONFIG_NETUTILS_IPERF, set CONFIG_NETUTILS_IPERFTEST_DEVNAME=eth0)
$ make
```
Enable TUN/TAP on Linux host:
```
$ sudo setcap cap_net_admin+ep ./nuttx
$ sudo ./tools/simhostroute.sh wlan0 on
```
Start iperf on Linux host:
`$ iperf -s -p 5471 -i 1 -w 416K`
Run NuttX on Linux host:
```
$ ./nuttx
NuttShell (NSH) NuttX-10.2.0
nsh> ifconfig eth0 10.0.1.2
nsh> ifup eth0
ifup eth0...OK
```
Start Wireshark (or tcpdump) and …
=> net/tcp(unbuffered): fast retransmit on duplicate acknowledgments

arch/arm/src/common/arm_internal.h, arch/arm/src/samv7/Kconfig, arch/avr/src/common/up_internal.h, arch/mips/src/common/mips_internal.h, arch/or1k/src/common/up_internal.h, arch/risc-v/src/common/riscv_internal.h, arch/x86/src/common/up_internal.h, arch/x86_64/src/common/up_internal.h, arch/xtensa/src/common/xtensa.h, boards/arm/imxrt/imxrt1050-evk/kernel/imxrt_userspace.c, boards/arm/imxrt/imxrt1060-evk/kernel/imxrt_userspace.c, boards/arm/imxrt/imxrt1064-evk/kernel/imxrt_userspace.c, boards/arm/imxrt/teensy-4.x/kernel/imxrt_userspace.c, boards/arm/lpc17xx_40xx/lpc4088-devkit/kernel/lpc17_40_userspace.c, boards/arm/lpc17xx_40xx/lpc4088-quickstart/kernel/lpc17_40_userspace.c, boards/arm/lpc17xx_40xx/open1788/kernel/lpc17_40_userspace.c, boards/arm/lpc17xx_40xx/pnev5180b/kernel/lpc17_40_userspace.c, boards/arm/sam34/sam3u-ek/kernel/sam_userspace.c, boards/arm/samv7/same70-qmtech/kernel/sam_userspace.c, boards/arm/samv7/same70-xplained/kernel/sam_userspace.c, boards/arm/samv7/samv71-xult/kernel/sam_userspace.c, boards/arm/stm32/mikroe-stm32f4/kernel/stm32_userspace.c, boards/arm/stm32/stm3240g-eval/kernel/stm32_userspace.c
Fix few typos in comments
No functional changes
Pass CI
=> userspace: fix typos in comments

arch/arm/src/sam34/sam4cm_tc.h, arch/arm/src/samd5e5/sam_tc.h, arch/arm/src/samv7/Kconfig, arch/arm/src/samv7/hardware/sam_tc.h, arch/arm/src/stm32/stm32_qencoder.c, arch/arm/src/tiva/common/tiva_qencoder.c, boards/arm/kinetis/freedom-k28f/src/k28_automount.c, boards/arm/kinetis/freedom-k64f/src/k64_automount.c, boards/arm/kinetis/freedom-k66f/src/k66_automount.c, boards/arm/kinetis/twr-k64f120m/src/k64_automount.c, boards/arm/sama5/sama5d4-ek/src/sam_automount.c, boards/arm/samd5e5/metro-m4/src/sam_automount.c, boards/arm/samv7/common/src/sam_automount.c, boards/arm/samv7/same70-qmtech/README.txt, boards/arm/samv7/same70-xplained/README.txt, boards/arm/samv7/samv71-xult/README.txt, boards/arm/stm32/clicker2-stm32/src/stm32_automount.c, drivers/analog/ad5410.c, include/nuttx/sensors/hall3ph.h, include/nuttx/sensors/qencoder.h
Fix typos in many files
No functional changes
Pass CI
=> typos: fix typos in many files

net/bluetooth/bluetooth_conn.c, net/can/can_conn.c, net/icmp/icmp_conn.c, net/icmpv6/icmpv6_conn.c, net/ieee802154/ieee802154_conn.c, net/netlink/netlink_conn.c, net/pkt/pkt_conn.c
net/misc: add support for CONFIG_NET_ALLOC_CONNS
N/A
CI-Check
=> net/misc: add support for CONFIG_NET_ALLOC_CONNS

drivers/serial/uart_rpmsg.c
uart_rpmsg: fix data loss
get console output by cmd:cu correctly.
daily test
=> uart_rpmsg: fix data loss

tools/Makefile.win
This PR improved dirlinks dependencies for Makefile.unix: https://github.com/apache/incubator-nuttx/pull/5069
This PR copies the changes into Makefile.win
I'm relying on CI to verify the changes since I don't currently have a windows env setup.
=> Improve dirlinks dependencies for Makefile.win

include/nuttx/can.h, include/nuttx/can/can.h, net/can/Kconfig
SocketCAN: add CAN error definitions
=> SocketCAN: add CAN error definitions

arch/arm/src/max326xx/Kconfig, libs/libc/modlib/Kconfig
Fix typos in Kconfig files
MAX326XX users
Pass CI
=> typos: fix typos in Kconfig files

drivers/serial/serial.c, drivers/serial/serial_dma.c, drivers/serial/serial_io.c, include/nuttx/serial/serial.h
serial: merge serial check signo to one place
serial
VELA
=> serial: merge serial check signo to one place

libs/libxx/libcxxmini/libxx_new.cxx, libs/libxx/libcxxmini/libxx_newa.cxx
Signed-off-by: buyuer <dingddding@163.com>
=> libcxx-mini: operator new will assert when alloc failed.

arch/xtensa/src/esp32s2/Kconfig
Fix data cache option in menuconfig
User will see the right information
N/A
=> esp32s2: Fix data cache option in menuconfig

drivers/serial/Kconfig-16550, include/nuttx/serial/uart_16550.h
=> serial/uart_16550: Allow uintptr_t as addr width

arch/risc-v/src/common/riscv_cpuindex.c, arch/risc-v/src/k210/Make.defs
=> arch/risc-v: Refine riscv_cpuindex.c

Documentation/platforms/risc-v/mpfs/index.rst
Update the risc-v/mpfs documentation to match the current work.
Documentation update
Better visibility over the mpfs target
No testing
=> Documentation: risc-v/mpfs: update documentation

arch/arm/src/samv7/Kconfig, arch/arm/src/samv7/Make.defs, arch/arm/src/samv7/hardware/sam_tc.h, arch/arm/src/samv7/sam_oneshot.c, arch/arm/src/samv7/sam_qencoder.c, arch/arm/src/samv7/sam_qencoder.h, arch/arm/src/samv7/sam_tc.c, arch/arm/src/samv7/sam_tc.h
Implement SAMv7 Quadrature Encoder driver
None since feature is not used
Tested on SAME70-QMTECH board
=> arch/arm/samv7: implement quadrature encoder driver

drivers/timers/rpmsg_rtc.c
=> rpmsg_rtc: fix typo

drivers/timers/rpmsg_rtc.c
rpmsg_rtc: dirctly call rpmsg_rtc_server_xx() in server_ept_cb()
rpmsg_rtc
VELA
=> rpmsg_rtc: dirctly call rpmsg_rtc_server_xx() in server_ept_cb()

arch/arm/src/armv6-m/arm_vectors.c
Fixed detected typo
None
Pass CI
=> arch/arm/src/armv6-m: fix typo

arch/arm/src/stm32f7/stm32_serial.c
=> stm32f7 serial fix PM_CONFIG build

arch/sim/Kconfig, arch/sim/src/sim/up_touchscreen.c
update simtouchscreen, using touch_upperhalf，simplified simulator touchscreen driver
=> driver/up_touchscreen: update up_touchscreen, using touch_upperhalf

Documentation/guides/simulator.rst
Documentation: added "Testing / capturing TCP network traffic" section, including packet loss emulation.
Documentation
=> Documentation: added "Testing / capturing TCP network traffic" section, including packet loss emulation

Documentation/guides/cpp_cmake.rst, arch/sparc/src/sparc_v8/Toolchain.defs, boards/risc-v/bl602/bl602evb/scripts/Make.defs, boards/risc-v/c906/smartl-c906/scripts/Make.defs, boards/risc-v/esp32c3/esp32c3-devkit/scripts/Make.defs, boards/risc-v/mpfs/icicle/scripts/Make.defs, boards/risc-v/mpfs/m100pfsevp/scripts/Make.defs, boards/sim/sim/sim/scripts/Make.defs, boards/sparc/bm3803/xx3803/scripts/Make.defs, boards/sparc/bm3823/xx3823/scripts/Make.defs, boards/xtensa/esp32/esp32-devkitc/scripts/Make.defs, boards/xtensa/esp32/esp32-ethernet-kit/scripts/Make.defs, boards/xtensa/esp32/esp32-wrover-kit/scripts/Make.defs, boards/xtensa/esp32/ttgo_lora_esp32/scripts/Make.defs, boards/xtensa/esp32s2/esp32s2-saola-1/scripts/Make.defs
- board/bl602: Remove -fshort-enums 
- board: Remove -fstrict-volatile-bitfields 
- board: Remove -fno-omit-frame-pointer from Make.defs
Unify the config in all Make.defs
=> Update board Make.defs

arch/risc-v/src/Makefile, arch/risc-v/src/mpfs/mpfs_opensbi.c, arch/risc-v/src/opensbi/Kconfig, arch/risc-v/src/opensbi/Make.defs, arch/risc-v/src/opensbi/nuttx_sbi_types.h
switch to NuttX types for opensbi 
No impact
Pass CI
=> risc-v/mpfs: switch to NuttX types for opensbi 

arch/sim/src/sim/up_netdriver.c
Retrieve all the queued RX frames from the network device on every poll. As a result, the RX throughput is increased significantly w/o harming the TX throughput.
The previous RX throughput in case of TCP was 1 Mbit/s. Now it is 159 Mbit/s on my Linux setup.
This PR extends PR #5226.
arch/sim/netdev(tun/tap)
Build NuttX:
```
$ ./tools/configure.sh -l sim:tcpblaster
$ make menuconfig (enable CONFIG_NETUTILS_IPERF, set CONFIG_NETUTILS_IPERFTEST_DEVNAME=eth0)
$ make
```
Enable TUN/TAP on Linux host:
```
$ sudo setcap cap_net_admin+ep ./nuttx
$ sudo ./tools/simhostroute.sh wlan0 on
```
Run NuttX on Linux host:
```
$ ./nuttx
NuttShell (NSH) NuttX-10.2.0
nsh> ifconfig eth0 10.0.1.2
nsh> ifup eth0
ifup eth0...OK
nsh> nsh> iperf -s -p 5471 -i 1
```
Start iperf on Linux host:
```
$ iperf -c …
```
=> sim/netdev: retrieve all the queued RX frames from the network device on every poll

boards/arm/samv7/same70-qmtech/README.txt, sched/task/task_setup.c
Fix MCUboot slot size in README.txt for same70-qmtech board
None
Pass CI
=> boards/arm/samv7/same70-qmtech: fix description in README.txt

boards/arm/samv7/common/Kconfig, boards/arm/samv7/same70-qmtech/src/sam_bringup.c, boards/arm/samv7/same70-xplained/src/sam_bringup.c, boards/arm/samv7/samv71-xult/src/sam_bringup.c
Add HSMCI0 boot mount configuration option
SAMv7 based boards
Pass CI
=> boards/arm/samv7/common: add HSMCI0 boot mount configuration option

libs/libxx/0001-uclibxx-use-overload-constructor-of-filebuf-ostream.patch, libs/libxx/uClibc++.defs
overload constructor of filebuf & ostream in uclibxx
Bug fix in uclibxx initalize
=> libxx:uclibxx: add patch use overload constructor of filebuf & ostream

boards/Board.mk
=> board/Board.mk: Make romfs_img 4 byte aligned

net/tcp/tcp_sendfile.c
sendfile_txnotify() function in tcp_sendfile.c was excessive. There is the same tcp_send_txnotify() function in tcp_send.c.
TCP sendfile
=> net/tcp/tcp_sendfile: optimized out sendfile_txnotify() function

arch/arm/src/arm/Toolchain.defs, arch/arm/src/armv6-m/Toolchain.defs, arch/arm/src/armv7-a/Toolchain.defs, arch/arm/src/armv7-m/Toolchain.defs, arch/arm/src/armv7-r/Toolchain.defs, arch/arm/src/armv8-m/Toolchain.defs, arch/avr/src/avr/Toolchain.defs, arch/avr/src/avr32/Toolchain.defs, arch/hc/src/Makefile, arch/mips/src/mips32/Toolchain.defs, arch/misoc/src/lm32/Toolchain.defs, arch/misoc/src/minerva/Toolchain.defs, arch/or1k/src/mor1kx/Toolchain.defs, arch/renesas/src/Makefile, arch/risc-v/src/common/Toolchain.defs, arch/x86/src/Makefile, arch/x86_64/src/Makefile, arch/xtensa/src/lx6/Toolchain.defs, arch/xtensa/src/lx7/Toolchain.defs
=> arch/Toolchain.defs: Simplify addition builtin library to EXTRA_LIBS

drivers/syslog/Kconfig
=> drivers/syslog: Refine Kconfig option

drivers/serial/pty.c
serial/pty: fix the lock handling 
N/A
CI check
=> serial/pty: fix the lock handling 

tools/ci/cibuild.sh, tools/ci/docker/linux/Dockerfile
add sparc to the cibuild.sh
sparc architecture's daily ci
tested every command of function sparc-gcc-toolchain in cibuild.sh
=> add sparc to the daily ci

include/stdlib.h, libs/libc/stdlib/lib_openpty.c
specify here:
https://pubs.opengroup.org/onlinepubs/009695399/functions/posix_openpt.html
New API
Pass CI
=> libc: Implement posix_openpt

boards/arm/samv7/common/src/sam_automount.c, fs/Kconfig, fs/mount/fs_automount.c, include/nuttx/fs/automount.h, include/nuttx/fs/ioctl.h
Add options for signaling when volume is mounted and unmounted by auto-mounter
None. Feature is disabled by default
Tested with SAME70-QMTECH board
=> fs_automount: add options for signaling when volume is mounted and unmounted

boards/arm/samv7/same70-qmtech/src/sam_bringup.c
Add buttons interface to SAME70-QMTECH
SAME70-QMTECH users
Pass CI
=> boards/arm/samv7/same70-qmtech: add buttons interface

net/local/Kconfig, net/local/local_fifo.c
align with other similar config which suffix with _VFS_PATH. See: https://github.com/apache/incubator-nuttx/pull/5422
Minor, since nobody change the default setting.
Pass CI
=> net/local: Rename NET_LOCAL_PATH_PREFIX to NET_LOCAL_VFS_PATH

drivers/serial/serial.c
serial: fix cu crash caused by ioctl is NULL
serial
VELA
=> serial: fix cu crash caused by ioctl is NULL

arch/sim/src/sim/up_usestack.c
See the discussion here: https://github.com/apache/incubator-nuttx/pull/5365
up_use_stack on sim
=> arch/sim: Adjust the stack size for up_use_stack too

include/sys/syscall_lookup.h, include/sys/sysinfo.h, sched/sched/Make.defs, sched/sched/sched_sysinfo.c, syscall/syscall.csv
specify here:
https://man7.org/linux/man-pages/man2/sysinfo.2.html
New API
Local test
=> sched: Implement sysinfo function

libs/libc/spawn/lib_psfa_adddup2.c
=> libc/spawn: Fix typo in comments

drivers/serial/pty.c
so the other side can get the hang up notification
This patch fix "adb shell" can't terminate with exit command. 
adb shell
=> serial/pty: Close the internal pipe when reference count drop to zero

LICENSE, arch/arm/src/lpc2378/Make.defs, arch/arm/src/moxart/Make.defs, arch/sim/src/sim/up_checkstack.c, arch/sim/src/sim/up_netdriver.c, arch/sim/src/sim/up_tapdev.c, arch/sim/src/sim/up_wpcap.c, boards/arm/lpc2378/olimex-lpc2378/scripts/Make.defs
LICENSE: document licenses to LICENSE file
RELEASE
NONE
=> LICENSE: document licenses to LICENSE file

drivers/input/uinput.c
input/uinput: fix codesyle issue
N/A
local test
=> input/uinput: fix codesyle issue

fs/romfs/fs_romfs.c, fs/romfs/fs_romfs.h, fs/romfs/fs_romfsutil.c
romfs: add FAR for all pointer and optimize some code
modify some style
daily test
=> romfs: add FAR for all pointer and optimize some code

fs/vfs/fs_epoll.c
fs/epoll_fd: support dup file descriptor
when user uses epoll_create or epoll_create1 without EPOLL_CLOEXEC, if create task in current task, epoll_fd will be duplicated, so we need support it.
daily test
=> fs/epoll_fd: support dup file descriptor

arch/risc-v/src/bl602/Make.defs, arch/risc-v/src/c906/Make.defs, arch/risc-v/src/esp32c3/Make.defs, arch/risc-v/src/litex/Make.defs, arch/risc-v/src/mpfs/Make.defs
=> risc-v: Fix style issue in SoC's Make.defs

arch/arm/src/rtl8720c/amebaz_depend.c, arch/ceva/src/common/up_assert.c, arch/sparc/src/common/up_assert.c
=> arch: Replace nx_vsyslog with vsyslog

tools/configure.sh
Fix typo in condition which affects search custom apps directory location.
=> Fix configure.sh for custom apps dir.

arch/arm/src/armv8-m/arm_secure_irq.c
Call up_secure_irq witch the special irq
local config
=> arm/armv8-m: Handle the special irq correctly in up_secure_irq
