apache/nuttx

drivers/wireless/gs2200m.c
- I received an issue report that multiwebcam in Spresense SDK 2.4.0
has a problem with the Chrome browser
- Actually, the browser tries to establish 2 connections but
the multiwebcam can handle only 1 connection. And if accept() for
the second connection is delayed, the connection no longer exists
in the gs2200m hardware
- This commit fixes this issue by checking if the cid is valid or not.
- gs2200m driver only
- Tested with spresense:wifi_smp
=> drivers: wireless: Fix gs2200m_ioctl_accept()

drivers/mtd/filemtd.c
`filemtd` use 128 bytes buffers for caching in `filemtd_write` and `filemtd_erase` implementations, but `erasesize` and `blocksize` does not have a requirement to be a multiple of 128 bytes. This PR fixes write and erase access for `erasesize` and `blocksize` that are not multiples of 128.
`filemtd` users
Tested with file MTD device with 32 bytes sector size and 64 bytes block size
=> mtd/filemtd: improve write and erase access

arch/arm/src/armv7-a/arm_addrenv.c, arch/arm/src/armv7-a/arm_addrenv_utils.c, arch/arm/src/armv7-a/arm_pgalloc.c
- This commit adds debug messages for addrenv
- None
- Tested with sabre-6quad:netknsh (not merged yet)
=> arch: armv7-a: Add debug messages for addrenv

Documentation/guides/cpp_cmake.rst, arch/risc-v/src/common/Toolchain.defs, boards/risc-v/bl602/bl602evb/scripts/Make.defs, include/nuttx/serial/uart_rpmsg.h
since it's already defined in Config.mk, and minor style fix.
No
Pass CI
=> Remove -D__NuttX__ from Makefile

Kconfig, boards/sim/sim/sim/configs/nimble/defconfig, tools/Config.mk
Align NDEBUG with CONFIG_DEBUG_ASSERTIONS
assert macro
Pass CI
=> Add CONFIG_NDEBUG Kconfig to control NDEBUG definition 

arch/sparc/src/common/up_createstack.c, arch/sparc/src/common/up_stackframe.c, arch/sparc/src/common/up_usestack.c
since adj_stack_ptr doesn't exist anymore
Change comment only
Pass CI
=> arch/sparc: Replace adj_stack_ptr with stack_base_ptr

tools/Config.mk
Assuming, there's some interest to use Rust within NuttX (similar to ideas Linux is looking at), this is a small first step for a simple "hello_rust" example in apps.
nothing as it's new
Simulation on MacBook Air M1 with Monterey 12.2.1 using rustc 1.60.0-nightly via Homebrew.
=> tools: Default macro to compile one Rust file.

drivers/ioexpander/ioe_dummy.c, drivers/ioexpander/ioe_rpmsg.c, drivers/ioexpander/skeleton.c, include/nuttx/ioexpander/ioexpander.h
Fix some issues for IO-expander found during code review
No functional changes
Pass CI
=> drivers/ioexpander: minor initialize and styling fixes

LICENSE, include/nuttx/input/x11_xf86keysym.h
from:
https://github.com/freedesktop/xorg-x11proto/blob/master/XF86keysym.h
continue the work:
https://github.com/apache/incubator-nuttx/pull/4881
Minor, new x11 keysym
Pass CI
=> input: Add x11_xf86keysym.h header file

boards/sim/sim/sim/scripts/Make.defs
follow other board files usage
Code refactor
Pass CI
=> boards/sim: Rename ARCHCPUFLAGS[XX] to ARCHC[XX]FLAGS

drivers/serial/pty.c
Remove the dead code
No
Pass CI
=> serial/pty: Remove the unused code related to CONFIG_PSEUDOTERM_FULLBLOCKS

arch/ceva/src/Makefile
=> arch/ceva: Replace OUTDIR with TOPDIR

tools/ci/docker/linux/Dockerfile
Reverts apache/incubator-nuttx#5567
=> Revert "ci: Install Rust via RUN."

libs/libc/sched/task_setcanceltype.c, sched/group/group_create.c
Fix function name in comment
None
Pass CI
=> libc/sched/task_setcanceltype: fix function name in comment

drivers/analog/adc.c, drivers/analog/dac.c
Fix license ADC/DAC
None
checkpatch
=> Fix license ADC/DAC

LICENSE
Document non Apache licenses from drivers folder
LICENSE
NONE
=> LICENSE: add remainig licenses found in drivers

tools/ci/cibuild.sh, tools/ci/docker/linux/Dockerfile
Get rust copied to final image.
PR created following the discussions in PR https://github.com/apache/incubator-nuttx/pull/5576
ci configuration
via ci itself
=> ci: get rust copied to final image.

drivers/serial/pty.c
since it is fully suppported now: https://github.com/apache/incubator-nuttx/pull/5573
Minor
Pass CI
=> serial/pty: Remove the TODO comment for O_NONBLOCK

drivers/serial/pty.c
to simplify the code logic
pty
sim:adb
=> pty: Move the post process after reading the buffer

AUTHORS, LICENSE, drivers/i2c/pca9540bdp.c, drivers/i2c/pca9540bdp.h, drivers/sensors/ltc4151.c, include/nuttx/i2c/pca9540bdp.h, include/nuttx/sensors/ina219.h, include/nuttx/sensors/ina226.h, include/nuttx/sensors/ltc4151.h
Gregory Nutt has submitted the SGA
Giorgio Gross has submitted the ICLA
as a result we can migrate the licenses to Apache
LICENSE
NONE
=> drivers: Giorgio Gross : update licenses to Apache 

include/nuttx/sched_note.h, sched/Kconfig, sched/sched/sched_note.c
Signed-off-by: zhanghu6 <zhanghu6@xiaomi.com>
API
static inline int note_isenabled_switch(void);
static inline int note_isenabled_dump(void);
=> sched/note:add switch and dump instrumentation

include/nuttx/tls.h, include/sys/syscall_lookup.h, libs/libc/tls/Kconfig, libs/libc/tls/tls_alloc.c, libs/libc/tls/tls_destruct.c, libs/libc/tls/tls_getvalue.c, sched/group/group_leave.c, sched/task/Make.defs, sched/task/task_tls_alloc.c, syscall/syscall.csv
Implement a non-standard thread local storage like task local storage API for some software that required per-task storage (like libuv).
None, new API
Custom application.
=> sched: Implement task local storage

.github/workflows/build.yml, .github/workflows/docker_linux.yml
Use docker actions to build docker.
Docker image
Tested the same steps in another workflow, CI will build again.
=> docker_linux.yml: Use docker actions to build docker image.

tools/checkpatch.sh
add rustfmt to checkpatch
checkpatch
check patch tested on MacBook M1
=> tools: add rustfmt to checkpatch

drivers/input/button_upper.c, drivers/input/touchscreen_upper.c
- input/button: Remove the couple from uinput
- input/touch: Remove the couple from uinput
Minor
Pass CI
=> input: Remove the couple from uinput

arch/sim/src/Makefile, boards/sim/sim/sim/scripts/Make.defs
Minor, code refactor
Pass CI sim:ostest
=> board/sim: Remove CCLINKFLAGS, use CFLAGS/CXXFLAGS instead

arch/arm/src/nrf52/Kconfig, fs/Kconfig, libs/libc/stdio/Kconfig, sched/Kconfig
=> Simplify DEFAULT_SMALL usage in Kconfig

arch/arm/src/imx6/Kconfig, arch/arm/src/imx6/Make.defs, arch/arm/src/imx6/imx_pgalloc.c
- This commit adds the pgheap for imx6
- None
- Tested with sabre-6quad:netknsh (not merged yet)
=> arch: imx6: Add the pgheap for imx6

LICENSE
cleanup the license file:
- remove Authors
- add missing delimiters
- add missing spaces
- remove duplicate licenses
NONE
NONE
=> LICENSE: cleanup

LICENSE, libs/libc/fixedmath/lib_ubsqrt.c
Document licenses found in libs/libc
LICENSE
NONE
=> LICENSE: document licenses found in libs/libc

arch/sim/src/sim/up_idle.c, arch/sim/src/sim/up_initialize.c, sched/group/group_create.c, sched/group/group_setupidlefiles.c, sched/group/group_setupstreams.c, sched/group/group_setuptaskfiles.c, sched/init/nx_start.c
sched/group: Move files_initlist/lib_stream_initialize to group_alloc
sim: add loop thread to handle dev loops
For some dev loops will call sem_wait/sem_trywait
group init & sim idle
VELA sim
=>  sim: add loop thread to handle dev loops

LICENSE, include/nuttx/analog/adc.h, include/nuttx/analog/dac.h
Document licenses found in libs/libc
LICENSE
NONE
=> LICENSES: document licenses for include files

libs/libc/locale/lib_gettext.c
=> libc/gettext: Support the plural format 

drivers/input/ajoystick.c, drivers/input/button_upper.c, drivers/input/djoystick.c
it's wrong to protect by au_exclsem in some case and remove ao_closing
=> joystck/buttons: Always protect the open list by critical section

arch/risc-v/src/mpfs/mpfs_usb.c
PR#5688 review fixes are in this patch. The PR was already
merged so the fixes are addresses here as a separate patch.
Co-authored-by: Petro Karashchenko <petro.karashchenko@gmail.com>
This patch addresses the review fixes into PR#5688. That pull request was modified a couple of times and thus the review comments were accidentally missed.
More coherent coding style on MPFS USB driver.
Tested successfully with Polarfire Icicle kit against Ubuntu 21.04 with all the review suggestions included.
=> risc-v/mpfs: usb: apply review fixes

drivers/power/Kconfig, drivers/power/Make.defs, drivers/power/pm.h, drivers/power/pm_activity.c, drivers/power/pm_changestate.c, drivers/power/pm_checkstate.c, drivers/power/pm_governor.c, include/nuttx/power/pm.h
For mult domains scene,,
activity and greety can be used at same time.
Let user to select domain governor.
=> power:govorner: add govorner to per domain.

drivers/Kconfig, drivers/Makefile, drivers/misc/Kconfig, drivers/misc/Make.defs, drivers/misc/addrenv.c, drivers/misc/dev_null.c, drivers/misc/dev_zero.c, drivers/misc/lwl_console.c, drivers/misc/mkrd.c, drivers/misc/ramdisk.c, drivers/misc/rwbuffer.c
code refactor
Minor change
Pass CI
=> drivers: Move the common driver to misc folder

arch/z16/include/arch.h, arch/z16/src/common/z16_internal.h, arch/z80/include/arch.h, arch/z80/src/common/z80_internal.h
=> arch/z[80|16]: Move up_getsp declaration to arch.h

arch/Kconfig, boards/sim/sim/sim/scripts/Make.defs
board/sim: add support of custom optimization level
N/A
CI-check
=> board/sim: add support of custom optimization level 

arch/arm/include/syscall.h, arch/ceva/include/syscall.h, arch/mips/include/syscall.h, arch/misoc/include/syscall.h, arch/risc-v/include/syscall.h, arch/sparc/include/syscall.h, arch/xtensa/include/syscall.h
=> arch: Make the comment and definition of CONFIG_SYS_RESERVED correctly

arch/arm/src/lpc43xx/lpc43_timer.c, arch/arm/src/samv7/sam_afec.c, arch/arm/src/samv7/sam_tc.h, arch/arm/src/stm32f7/stm32_tim.h, arch/arm/src/stm32f7/stm32_tim_lowerhalf.c, arch/arm/src/stm32l4/stm32l4_tim_lowerhalf.c, arch/arm/src/stm32l5/stm32l5_tim_lowerhalf.c, arch/arm/src/stm32u5/stm32_tim_lowerhalf.c, arch/mips/src/pic32mz/pic32mz_timer_lowerhalf.c, arch/risc-v/src/bl602/bl602_tim_lowerhalf.c, arch/risc-v/src/bl602/bl602_tim_lowerhalf.h, arch/sparc/src/bm3803/bm3803_tim_lowerhalf.c, arch/xtensa/src/esp32/esp32_tim_lowerhalf.c, arch/xtensa/src/esp32s2/esp32s2_tim_lowerhalf.c, arch/xtensa/src/esp32s3/esp32s3_tim_lowerhalf.c, boards/arm/stm32l4/b-l475e-iot01a/src/stm32_timer.c
Minor improvements for timer lowerhalf
None
Pass CI
=> timer_lowerhalf: minor improvements

arch/risc-v/src/mpfs/mpfs_usb.c
Fix EP0 stall and resume properly. EP0 wasn't clearly addressed
on stall / resume operations.
Also fix data reads that provide garbage for the first request.
It has always random data as it's completed prior to any read
operation.
USB stack testing caught a few issues that are fixed here.
MPFS USB CDC/ACM
Polarfire Icicle Kit against Ubuntu 21.04 and Windows 10
=> risc-v/mpfs: usb: fix ep0 stall/resume and rx reads

drivers/mtd/filemtd.c
Fix compilation warnings
None
Pass CI
=> drivers/mtd/filemtd: fix compilation warnings

include/resolv.h, libs/libc/netdb/Make.defs, libs/libc/netdb/lib_dn.c
Add lib_dn.c to libs/libc/netdb
dhcp6c depends on lib_dn.c
dhcp6c test passed
=> Add dn resolution function

libs/libc/machine/arch_atomic.c
Remove GCC ignored warning and fix
=> arch:lib_atomic: remove and fix gcc warning `declaration-mismatch`

include/unistd.h, libs/libc/unistd/lib_execl.c
prototype here: https://pubs.opengroup.org/onlinepubs/9699919799/functions/exec.html
Pass CI
=> Fix error: conflicting types for built-in function 'execl'; expected 'int(const char *, const char *, ...)

sched/module/mod_insmod.c
sched/module: correct the check condition
N/A
ci-check
=> sched/module: correct the check condition 

arch/xtensa/src/common/xtensa_releasepending.c
Remove commented out code.
N/A
N/A
=> xtensa_releasepending.c: Remove commented out code.

fs/rpmsgfs/rpmsgfs_client.c
fs/rpmsgfs: minor refine the return value
N/A
CI-check
=> fs/rpmsgfs: minor refine the return value

drivers/syslog/syslog_channel.c
syslog/channel: minor fix to avoid unreachabled return
N/A
CI-check
=> syslog/channel: minor fix to avoid unreachabled return

drivers/syslog/syslog_channel.c
=> syslog: Change g_syslog_default_sem to static function variable

tools/nxstyle.c
=> tools/nxstyle: Order g_white_prefix by alphanum

boards/arm/samv7/same70-qmtech/src/sam_gpio.c
=> boards/arm/same70-qmtech: Remove dead code

drivers/mtd/mtd_config.c
Currently the same format version value is used for both named and ID based modes for MTD config device. This leads to a situation when ID mode is used and configuration is changed to named the SW can't detect this and makes faulty data representation.
Solution: select `CONFIGDATA_FORMAT_VERSION` value based on `CONFIG_MTD_CONFIG_NAMED` option.
MTD config users
Tested with SAME70-QMTECH board
=> drivers/mtd/mtd_config: set different format versions for named and ID modes

libs/libc/machine/risc-v/common/arch_elf.c
The jump instruction relocation had an assert that tests for jumps with
an offset of 0. This makes it so that a while(1); statement causes an
assert because the jump instruction points to the same address, which
is perfectly legal.
Addend was not handled correctly in several reloc types.
Add ADD32/64 + SUB32/64 relocations, for some reason the compiler
I use likes to add them.
Fixes some relocation issues
Tested with MPFS icicle:knsh (CONFIG_BUILD_KERNEL=y) / not released yet
=> RISC-V: Add/fix implementation for arch_elf.c

tools/minidumpserver.py
this is a tool,when crash help you to debug.
This tool can help you analyze the call stack information when the system crashes
After the ELF file and crash log file are processed by the python script, a gdb server is established, and gdb is used to connect to the gdb server for debugging
save crash log，like this:
```
[   38.995788] [27] [ EMERG] [ap] arm_registerdump: R0: 00000002 R1: 3c4927c4 R2: 3c480684  R3: 3c4927c4
[   38.996961] [27] [ EMERG] [ap] arm_registerdump: R4: 3c49fbc0 R5: 3c492718 R6: 000000e0  FP: 3c49fbc0
[   38.998134] [27] [ EMERG] [ap] arm_registerdump: R8: 3c49fc30 SB: 00000001 SL: 00000001 R11: 00000000
[   38.999306] [27] [ EMERG] [ap] arm_registerdump: IP: 00020040 SP: 3c49fba0 LR: 2c5198ef  PC: 2c54468a
[   39.000479] …
```
=> tools:use dump log creat a gdbsever to debug

include/sys/random.h, include/unistd.h, libs/libc/misc/Make.defs, libs/libc/misc/lib_getrandom.c, libs/libc/unistd/Make.defs, libs/libc/unistd/lib_getentropy.c, libs/libc/uuid/lib_uuid_create.c
- libc: Implement getrandom on top of "/dev/[u]random" 
- libc/uuid: Call getrandom instaed arc4random_buf
New API
Pass CI
=> libc: Implement getrandom on top of "/dev/[u]random" 

drivers/rptun/rptun.c, net/rpmsg/rpmsg_sockif.c
Fix a few warnings related to RPMSG.
No functional changes
Compile-time only
=> Rpmsg warnings

arch/risc-v/src/common/riscv_exception_common.S, arch/risc-v/src/common/riscv_schedulesigaction.c
Just code style, no functional changes.
N/A
qemu
=> arch/risc-v: Minor style change

arch/arm/src/armv7-m/arm_perf.c, arch/arm/src/armv8-m/arm_perf.c, boards/arm/stm32/axoloti/src/stm32_boot.c, boards/arm/stm32/omnibusf4/src/Make.defs, boards/arm/stm32/omnibusf4/src/stm32_boot.c, boards/arm/stm32/stm32f4discovery/src/Make.defs, boards/arm/stm32/stm32f4discovery/src/stm32_boot.c, include/nuttx/arch.h
armv7-m/armv8-m: move up_pref* api to common place
N/A
CI check
=> armv7-m/armv8-m: move up_pref* api to common place

crypto/random_pool.c
and include the used header files(nuttx/clock.h and nuttx/semaphore.h)
Minor
Pass CI
=> crypto/random_pool: Remove the unused header file(unistd.h and nuttx/arch.h)

libs/libc/time/lib_strftime.c
Update description of `strftime`
None
Pass CI
=> libs/libc/time: update description of strftime

boards/arm/kinetis/freedom-k64f/src/k64_uid.c, boards/arm/stm32/nucleo-f303re/src/stm32_uid.c, boards/arm/stm32/omnibusf4/src/stm32_uid.c, boards/arm/stm32/stm32f4discovery/src/stm32_uid.c, boards/arm/stm32h7/nucleo-h743zi/src/stm32_uid.c, boards/arm/stm32h7/stm32h747i-disco/src/stm32_uid.c, boards/arm/stm32l4/nucleo-l432kc/src/stm32_appinit.c, boards/arm/stm32l4/nucleo-l476rg/src/stm32_appinit.c, boards/arm/stm32l4/stm32l476-mdk/src/stm32_bringup.c, boards/arm/stm32l4/stm32l476vg-disco/src/stm32_appinit.c, boards/arm/stm32l4/stm32l4r9ai-disco/src/stm32_appinit.c
Fix pointer to int compare
None. Refactoring only
Pass CI
=> boards/arm/uid: fix pointer to int compare

arch/arm/src/armv7-m/arm_perf.c, arch/arm/src/armv8-m/arm_perf.c
Follow https://github.com/apache/incubator-nuttx/pull/5720
Pass CI
=> arch/arm: Change arm_arch.h to arm_internal.h in arm_perf.c

arch/arm/src/arm/Toolchain.defs, arch/arm/src/armv6-m/Toolchain.defs, arch/arm/src/armv7-a/Toolchain.defs, arch/arm/src/armv7-m/Toolchain.defs, arch/arm/src/armv7-r/Toolchain.defs, arch/arm/src/armv8-m/Toolchain.defs, arch/risc-v/src/common/Toolchain.defs, arch/xtensa/src/lx6/Toolchain.defs, arch/xtensa/src/lx7/Toolchain.defs
Move the ksan compiler option to common place
Pass CI
=> arch: Add -fsanitize=kernel-address to ARCHCPUFLAGS if CONFIG_MM_KASAN=y

arch/arm/Kconfig, arch/arm/src/armv8-m/Toolchain.defs
New flags for Cortex M55
Pass CI
=> nuttx: Add new config ARM_HAVE_MVE for MVE instruction

drivers/input/touchscreen_upper.c
=> input/touchscreen: Fix the typo error

arch/xtensa/src/common/xtensa.h
VELAPLATFO-1922
Change-Id: Ie36944a513aae6decad2040647435668fe18be90
=> xtensa: add xtensa_spill_window declaration

libs/libc/netdb/lib_rexec.c
rexec: fix free error in error handing
rexec
VELA
=> rexec: fix free error in error handing

fs/littlefs/lfs_vfs.c
littlefs: unify lfs error code to nuttx
Convenient debug
CI test
=> littlefs: unify lfs error code to nuttx

drivers/syslog/syslog_rpmsg.c
syslog_rpmsg related update
1. syslog_rpmsg: change head & tail NON-wrap
2. syslog: use & instead of % when calculate offset
syslog rpmsg
VELA
=> syslog_rpmsg related update

fs/inode/fs_files.c
add _POSIX_OPEN_MAX limit to files_extend
N/A
VELA
=> fs:add _POSIX_OPEN_MAX limit to files_extend

include/nuttx/wqueue.h, sched/wqueue/kwork_thread.c, sched/wqueue/wqueue.h
workqueue: add work_foreach support
workqueue new API
VELA
=> workqueue: add work_foreach support

ReleaseNotes
This is a local copy taken from the confluence notes
https://cwiki.apache.org/confluence/display/NUTTX/NuttX+10.3
Release 
None
=> documentation: Add release notes for 10.3.0 release

fs/romfs/fs_romfsutil.c
Fs/romfs: fix bug about compare path with same prefix.
Fix mismatch when search name with same prefix, examples:
local test
=> Fs/romfs: fix bug about compare path with same prefix

fs/rpmsgfs/rpmsgfs.c, fs/rpmsgfs/rpmsgfs_client.c
rpmsgfs related update
1. add wait ready to rpmsgfs
2. add timeout when mount in rpmsgfs
3. fix blocked when connecting
4. use rptun_wait/post to resolve deadlock with usrsock rpmsg
This depends on:
https://github.com/apache/incubator-nuttx/pull/5847/
rpmsgfs
VELA
=> rpmsgfs related update

sched/signal/sig_action.c
sigact: get free sigact from freelist always successful
Ci test
=> sigact: get free sigact from freelist always successful

fs/unionfs/fs_unionfs.c
fs/unionfs: fix some warning and bug
N/A
local test
=> fs/unionfs: fix some warning and bug

libs/libc/misc/lib_err.c
call va_copy,after need call va_end
=> libs/libc/lib_err.c:add va_end to vwarn

net/local/local_listen.c
Avoid panic in the final production
Minor
=> local socket: cancel assert about backlog exceed 255

drivers/power/Make.defs, drivers/power/activity_governor.c, drivers/power/greedy_governor.c, drivers/power/pm.h, drivers/power/pm_activity.c, drivers/power/pm_changestate.c, drivers/power/pm_lock.c, drivers/power/pm_register.c, drivers/power/pm_unregister.c, include/nuttx/power/pm.h
=> power: unify lock sates and move pm_auto_update to outer dir

libs/libc/unistd/lib_chdir.c
=> lib_chdir:change ret judgment method

libs/libc/modlib/modlib_bind.c
=> modlib/modlib_bind:fix unsigned_compare with zero

drivers/mmcsd/mmcsd_sdio.c, include/nuttx/sdio.h
- mmcsd: Add gotextcsd callback to sdio_dev_s 
- mmcsd: Fix mmc card error but system can not catch it
Pass CI
=> Minor improve for mmcsd

arch/risc-v/src/esp32c3/esp32c3_irq.c
This PR intends to fix a regression on the `esp32c3-devkit` platform introduced by https://github.com/apache/incubator-nuttx/pull/5913.
Closes https://github.com/apache/incubator-nuttx/issues/5942
Fix for currently broken `esp32c3-devkit`.
`esp32c3-devkit:nsh` boots fine again.
=> risc-v/esp32c3: Fix regression on IRQ handling for ECALL instruction

net/devif/devif_iobsend.c
Signed-off-by: zhanghongyu <zhanghongyu@xiaomi.com>
=> fix:Remove udp send large pkt assert

arch/risc-v/include/csr.h, arch/risc-v/include/mode.h, arch/risc-v/include/syscall.h, arch/risc-v/src/common/riscv_exception_common.S, arch/risc-v/src/common/riscv_internal.h, arch/risc-v/src/common/riscv_macros.S, arch/risc-v/src/common/riscv_percpu.c, arch/risc-v/src/common/riscv_swint.c, arch/risc-v/src/common/supervisor/Make.defs, arch/risc-v/src/common/supervisor/riscv_syscall_dispatch.S
Address the last comment in #5782
Minor, rename and style change
Pass CI
=> Minor fix for riscv

sched/module/mod_insmod.c, sched/sched/sched_note.c
=> fix coverify warning

arch/sim/src/sim/up_usrsock.c, include/nuttx/net/usrsock.h, net/usrsock/usrsock_dev.c
This PR mainly contains some USRSOCK related changes
This submission depends on the app's submission！
=> This PR mainly contains some USRSOCK related changes

net/arp/arp_send.c, net/netdev/netdev_ifconf.c, net/netdev/netdev_ioctl.c, net/netdev/netdev_register.c, net/netlink/netlink_route.c, net/rpmsg/rpmsg_sockif.c, net/socket/connect.c, net/utils/net_ipchksum.c
Signed-off-by: hejianliang3 <[hejianliang3@xiaomi.com](mailto:hejianliang3@xiaomi.com)>
=> net:fix coverity warning

arch/arm/src/arm/arm_tcbinfo.c, arch/arm/src/armv6-m/arm_tcbinfo.c, arch/arm/src/armv7-a/arm_tcbinfo.c, arch/arm/src/armv7-m/arm_tcbinfo.c, arch/arm/src/armv7-r/arm_tcbinfo.c, arch/arm/src/armv8-m/arm_tcbinfo.c, arch/risc-v/src/common/riscv_tcbinfo.c, arch/xtensa/src/common/xtensa_tcbinfo.c, include/nuttx/sched.h, tools/jlink-nuttx.c
arch:tcbinfo: update tcbinfo as xcpcontext update
jlink-nuttx: update regs as nuttx regs save path change
=> arch:tcbinfo: update tcbinfo as xcpcontext update

arch/risc-v/src/common/riscv_exception.c
* Add `Private Data` comment block
* Remove unneeded #include
* Update description text of irq 10 
No
CI
=> arch/riscv: Minor style change and text correction

tools/checkrelease.sh
since all license is clean up now. Follow up the change:
https://github.com/apache/incubator-nuttx/pull/5911
https://github.com/apache/incubator-nuttx/pull/5910
https://github.com/apache/incubator-nuttx-apps/pull/1110
https://github.com/apache/incubator-nuttx-apps/pull/1109
=> tools/checkrelease.sh: Don't check DISCLAIMER-WIP anymore

arch/arm/src/lpc17xx_40xx/Make.defs, arch/arm/src/stm32h7/Make.defs, boards/arm/lpc17xx_40xx/lx_cpu/src/lpc17_40_boardinitialize.c, boards/arm/stm32h7/nucleo-h743zi2/src/stm32_boot.c, sched/irq/irq_dispatch.c, sched/wqueue/kwork_thread.c
And other minor fix, replace PR https://github.com/apache/incubator-nuttx/pull/5955
Minor
Pass CI
=> sched/irq: Fix array overrun in coverity check

.github/workflows/check.yml, tools/checkpatch.sh
and enable Change-ID check explicitly in check.yml.
Same as before
Pass CI
=> checkpatch.sh: add -m option to enable/disable Change-Id check

tools/mkdeps.c
To handle the large file path
Minor
Pass CI
=> tools/mkdeps: Extend MAX_SHQUOTE to 3072

libs/libc/time/lib_localtime.c
isdst always is false. remove it
=> libc/lib_localtime:fix deadcode

.github/gcc.json
.github/gcc.json: Fix space/tab inconsistency
no functional changes are expected
=> .github/gcc.json: Fix space/tab inconsistency

libs/libc/time/lib_localtime.c
=> lib_localtime:fix unsigned compare with zero

LICENSE, include/time.h, libs/libc/time/Make.defs, libs/libc/time/lib_strptime.c
=> libc:add strptime support

arch/risc-v/src/mpfs/mpfs_irq.c, arch/risc-v/src/mpfs/mpfs_timerisr.c
Fixes IRQ handling (mtimer, exception/fault) for MPFS
MPFS only
MPFS icicle:nsh
=> MPFS: Fix timer and exception/fault handling

LICENSE, libs/libc/string/lib_strstr.c
=> libc/string: Use Byte-Shift algorithm for very long needles

fs/vfs/fs_fcntl.c
fcntl with O_APPEND
local testing
=> fs/fcntl: add O_APPEND flag judge in fcntl

arch/arm/src/arm/Toolchain.defs, arch/arm/src/armv6-m/Toolchain.defs, arch/arm/src/armv7-a/Toolchain.defs, arch/arm/src/armv7-m/Toolchain.defs, arch/arm/src/armv7-r/Toolchain.defs, arch/arm/src/armv8-m/Toolchain.defs, arch/avr/src/avr/Toolchain.defs, arch/avr/src/avr32/Toolchain.defs, arch/mips/src/mips32/Toolchain.defs, arch/misoc/src/lm32/Toolchain.defs, arch/misoc/src/minerva/Toolchain.defs, arch/or1k/src/mor1kx/Toolchain.defs, arch/risc-v/src/common/Toolchain.defs, arch/xtensa/src/lx6/Toolchain.defs, arch/xtensa/src/lx7/Toolchain.defs, arch/z16/src/z16f/Toolchain.defs, arch/z80/src/ez80/Toolchain.defs, arch/z80/src/z8/Toolchain.defs
arch/armv[7|8]m: enhance the clang support
arm clang
ToolChain:
https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm
./tools/configure.sh lm3s6965-ek:qemu-flat
CONFIG_ARMV7M_TOOLCHAIN_CLANGL=y
=> arch/armv[7|8]m: enhance the clang support

include/nuttx/streams.h, libs/libc/stream/Make.defs, libs/libc/stream/lib_blkoutstream.c
=> libc/blockstream: add block out stream backend

arch/arm/src/common/arm_blocktask.c, arch/arm/src/common/arm_exit.c, arch/arm/src/common/arm_releasepending.c, arch/arm/src/common/arm_reprioritizertr.c, arch/arm/src/common/arm_unblocktask.c
Follow up #6089
Fix the issue that address environment change too early, see https://github.com/apache/incubator-nuttx/pull/5913 for more info.
Pass CI
=> arch/arm: Remove unneeded group_addrenv call which handled by arm_doirq

arch/risc-v/src/common/riscv_addrenv_kstack.c, arch/risc-v/src/common/riscv_saveusercontext.c, arch/risc-v/src/esp32c3/esp32c3_oneshot_lowerhalf.c, arch/risc-v/src/mpfs/mpfs_allocateheap.c, arch/risc-v/src/mpfs/mpfs_ethernet.c, arch/risc-v/src/mpfs/mpfs_usb.c, boards/risc-v/bl602/bl602evb/src/bl602_bringup.c, boards/risc-v/bl602/bl602evb/src/bl602_gpio.c, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_board_spi.c, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_board_spidev.c, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_board_spislavedev.c, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_gc9a01.c, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_gpio.c, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_i2c.c, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_oneshot.c, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_spiflash.c, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_st7735.c, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_st7789.c, boards/risc-v/fe310/hifive1-revb/src/fe310_buttons.c, boards/risc-v/k210/maix-bit/src/k210_gpio.c, boards/risc-v/litex/arty_a7/src/litex_automount.c, boards/risc-v/mpfs/common/src/mpfs_emmcsd.c, boards/risc-v/mpfs/common/src/mpfs_i2c.c, boards/risc-v/rv32m1/rv32m1-vega/src/rv32m1_buttons.c
Style change only
Minor
Pass CI
=> arch/risc-v: Remove FAR from chip and board folder

libs/libc/unistd/lib_execle.c
=> libc: Fix typo error in execle

tools/parsememdump.py
fix bug,match mem error,can't show all addr2line
use log and elf to test
=> tools:fix parsememdump.py match error

Documentation/reference/user/04_message_queue.rst
=> Documentation:fix error describe on message queue

arch/risc-v/src/bl602/bl602_pwm_lowerhalf.c, arch/risc-v/src/bl602/bl602_serial.c, arch/risc-v/src/esp32c3/esp32c3_usbserial.c, arch/sim/src/sim/up_keyboard.c, boards/mips/pic32mx/pic32mx7mmb/src/pic32_touchscreen.c
=> Correct the code alignment found in review

sched/mqueue/mq_timedsend.c
=> sched:fix mq_timedsend describe

arch/arm/src/Makefile, arch/arm/src/arm/Toolchain.defs, arch/arm/src/armv6-m/Toolchain.defs, arch/arm/src/armv7-a/Toolchain.defs, arch/arm/src/armv7-m/Toolchain.defs, arch/arm/src/armv7-r/Toolchain.defs, arch/arm/src/armv8-m/Toolchain.defs
arch/arm: add support for GCC LTO
1. Enable GCC link-time optimizer
2. Enable use of a linker plugin during link-time optimization
GCC link-time optimizer
1. sabre-6quad/smp  (CORTEXA9)
```
+CONFIG_LTO_FULL=y
```
2. lm3s6965-ek/qemu-flat (CORTEXM3)
```
-CONFIG_EXAMPLES_ELF=y
-CONFIG_EXAMPLES_MODULE=y
-CONFIG_SYSTEM_NTPC=y
-CONFIG_BOARDCTL_APP_SYMTAB=y
+CONFIG_LTO_FULL=y
```
3. spresense/smp (CORTEXM4)
```
+CONFIG_LTO_FULL=y
```
CPU frequency:    `200MHz`
Core:                    `Cortex-M55`
GCC Options: 
`-march=armv8.1-m.main+mve.fp+fp.dp  -mtune=cortex-m55 -mthumb -mfpu=fpv5-d16 -mfloat-abi=hard`
Clang Configuration:
`--config armv8.1m.main_hard_fp_nosys`
[gen_defconfig.txt](https://github.com/apache/incubator-nuttx/files/8518309/gen_defconfig.txt)
1. Code Size
2. Coremark
3. LVGL …
=> arch/arm: add support for GCC LTO

net/tcp/tcp_conn.c
Signed-off-by: 田昕 <tianxin7@xiaomi.com>
tcp_selectport choose initial port based on system time, this is not so random if a tcp connection is established just after system is booted. Especially when we have a relatively low freq cpu timer(in our case, 10ms per tick).
If tcp port remains the same after a reset, there is a great chance tcp connection fails.
tcp port selection, tcp connection
Vela tested
=> net/tcp:make initial tcp port more random

Kconfig, arch/Kconfig
Correct the dependence
minor fix
Pass CI
=> Correct the dependence in Kconfig

arch/arm/src/stm32l4/hardware/stm32l4_flash.h, arch/arm/src/stm32l4/hardware/stm32l4_rtcc.h, arch/arm/src/stm32l4/hardware/stm32l4_tim.h, arch/arm/src/stm32l4/hardware/stm32l4x3xx_rcc.h, arch/arm/src/stm32l4/hardware/stm32l4x5xx_rcc.h, arch/arm/src/stm32l4/hardware/stm32l4x6xx_rcc.h, arch/arm/src/stm32l4/hardware/stm32l4xrxx_dmamux.h, arch/arm/src/stm32l4/hardware/stm32l4xrxx_rcc.h, arch/arm/src/stm32l4/stm32l4_tim.c, arch/arm/src/stm32l4/stm32l4x3xx_rcc.c, arch/arm/src/stm32l4/stm32l4x5xx_rcc.c, arch/arm/src/stm32l4/stm32l4x6xx_rcc.c, arch/arm/src/stm32l4/stm32l4xrxx_rcc.c
I use stm32l4 code as a reference for another chip ([stm32wb](https://github.com/onegray/nuttx/tree/feature/stm32wb)) and have found some minor issues.
=> stm32l4 minor fixes

arch/mips/src/pic32mz/pic32mz_oneshot_lowerhalf.c, arch/risc-v/src/bl602/bl602_oneshot_lowerhalf.c, arch/risc-v/src/esp32c3/esp32c3_oneshot_lowerhalf.c, arch/sim/src/sim/up_oneshot.c, arch/sparc/src/bm3803/bm3803_oneshot_lowerhalf.c, arch/sparc/src/bm3803/bm3803_tim_lowerhalf.c, arch/xtensa/src/esp32/esp32_oneshot_lowerhalf.c, arch/xtensa/src/esp32s2/esp32s2_oneshot_lowerhalf.c
=> arch: Fix the style found in review

arch/arm/src/arm/arm_vectors.S, arch/arm/src/armv7-a/arm_vectors.S, arch/arm/src/armv7-a/cp15_flush_dcache_all.S, arch/arm/src/armv7-a/cp15_invalidate_dcache_all.S, arch/arm/src/armv7-r/arm_vectors.S, arch/arm/src/armv7-r/cp15_clean_dcache_all.S, arch/arm/src/armv7-r/cp15_flush_dcache_all.S, arch/arm/src/armv7-r/cp15_invalidate_dcache_all.S
patches added:
https://github.com/apache/incubator-nuttx/pull/6107
https://github.com/apache/incubator-nuttx/pull/5896
NuttX 10.3 RELEASE
NONE
=> BACKPORT: cortex-[a|r]/armv7/r: fixes

arch/xtensa/include/syscall.h, arch/xtensa/src/common/xtensa_swint.c, libs/libc/machine/xtensa/arch_setjmp.S
=> libc:xtensa: move syscall to swint call

arch/arm/src/tlsr82/Kconfig, arch/arm/src/tlsr82/hardware/tlsr82_pwm.h, arch/arm/src/tlsr82/tlsr82_pwm.c, boards/arm/tlsr82/tlsr8278adk80d/src/tlsr8278_bringup.c
1. add pulse count support for pwm0;
2. add more detailed config for pwm;
3. pwm configuration and start process optimize;
4. tlsr82/Kconfig format;
arm tlsr82xx chip pwm
local test with pwm example
1. pwm max/min duty test;
2. pwm max/min frequency test;
3. pwm0 pulse count test;
=> arm/tlsr82: pwm driver optimize and add pulse count support.

arch/risc-v/src/mpfs/mpfs_ihc.c
PR#6249 was already merged without the review fixes. Provide the
fixes here on a separate patch.
Co-authored-by: Petro Karashchenko <petro.karashchenko@gmail.com>
Apply the review fixes here, better late than not at all to keep the code in line
No impact
Tested on Polarfire Icicle
=> risc-v/mpfs: apply IHC review fixes

sched/pthread/pthread_completejoin.c, sched/pthread/pthread_create.c, sched/pthread/pthread_detach.c, sched/pthread/pthread_join.c
=> sched: Replace pthread_sem_take with nxsem_wait_uninterruptible

arch/arm/src/am335x/am335x_i2c.c, arch/arm/src/efm32/efm32_i2c.c, arch/arm/src/imxrt/imxrt_lpi2c.c, arch/arm/src/s32k1xx/s32k1xx_lpi2c.c, arch/arm/src/stm32/stm32_i2c.c, arch/arm/src/stm32/stm32_i2c_alt.c, arch/arm/src/stm32/stm32_i2c_v2.c, arch/arm/src/stm32/stm32f40xxx_i2c.c, arch/arm/src/stm32f0l0g0/stm32_i2c.c, arch/arm/src/stm32f7/stm32_i2c.c, arch/arm/src/stm32h7/stm32_i2c.c, arch/arm/src/stm32l4/stm32l4_i2c.c, arch/arm/src/tiva/common/tiva_i2c.c, arch/mips/src/pic32mz/pic32mz_i2c.c
=> arch/i2c: Change xxx_i2c_tousecs to xxx_i2c_toticks

include/nuttx/kmalloc.h
kmalloc.h: Remove extra semicolons
=> kmalloc.h: Remove extra semicolons

arch/xtensa/src/esp32/esp32_cpuidlestack.c
Remove an unused `#ifded`.
N/A
N/A
=> esp32_cpuidlestack.c: Remove unnecessary code.

arch/arm/src/cxd56xx/cxd56_cisif.c, boards/arm/cxd56xx/common/src/cxd56_i2cdev.c, boards/arm/cxd56xx/common/src/cxd56_isx012.c, boards/arm/cxd56xx/spresense/include/cxd56_isx012.h, boards/arm/cxd56xx/spresense/src/cxd56_bringup.c, drivers/video/isx012.c, drivers/video/isx012_reg.h, drivers/video/video.c, include/nuttx/video/imgsensor.h, include/nuttx/video/isx012.h, include/nuttx/video/video.h
various improvements for the video implementation
video implementation
Spresense
=> Video: various updates

libs/libc/wchar/lib_swprintf.c, libs/libc/wchar/lib_wmemchr.c, libs/libc/wchar/lib_wmemcpy.c, libs/libc/wchar/lib_wmemmove.c, libs/libc/wchar/lib_wmemset.c
=> libc/wchar: Fix the minor style issue

arch/risc-v/src/bl602/Make.defs, arch/risc-v/src/c906/Make.defs, arch/risc-v/src/common/Make.defs, arch/risc-v/src/esp32c3/Make.defs, arch/risc-v/src/fe310/Make.defs, arch/risc-v/src/k210/Make.defs, arch/risc-v/src/litex/Make.defs, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/qemu-rv/Make.defs, arch/risc-v/src/rv32m1/Make.defs
Follow #6165 
Refactor only
CI
=> arch/risc-v: Unify common source include

arch/arm/src/tlsr82/Kconfig, arch/arm/src/tlsr82/tlsr82_flash.c, arch/arm/src/tlsr82/tlsr82_flash.h, arch/arm/src/tlsr82/tlsr82_flash_mtd.c
1. add flash protection support;
2. add flash voltage calibration support;
tlsr82
Flash test pass with tlsr82 self-contained flash test function tlsr82_flash_test().
=> arm/tlsr82: support flash protection and flash voltage calibration.

include/signal.h, sched/Kconfig
signal: add define of SIGHUP/SIGTTIN
N/A
ci-check
=> signal: add define of SIGHUP/SIGTTIN 

include/netpacket/packet.h, include/nuttx/wireless/wireless.h
wireless: add Wireless statistics definition
N/A
ci check
=> wireless: add Wireless statistics definition

libs/libc/stdio/lib_libfwrite.c
fwrite speed low than write,becuase it internal buffer is no use good.
ci
=> libc:Optimize the behavior of fwrite

arch/risc-v/src/esp32c3/Kconfig
Remove duplicate wireless config.
N/A
N/A
=> esp32c3/Kconfig: Remove duplicate wireless config

drivers/lcd/Kconfig, drivers/lcd/Make.defs, drivers/lcd/ssd1680.c, drivers/lcd/ssd1680.h, include/nuttx/lcd/ssd1680.h
E-ink driver for chipsed sssd 1680
No BSP files
None
On ESP32 lilygo tty t5v2.2
=> e-ink ssd1680 driver

include/nuttx/mqueue.h, sched/Kconfig, sched/mqueue/mq_msgqalloc.c, sched/mqueue/mq_notify.c, sched/mqueue/mq_sndinternal.c
sched/mqueue: configurable mqueue notification
N/A
mq_send performance test (cycle count)
=> sched/mqueue: configurable mqueue notification

fs/procfs/fs_procfsmeminfo.c, include/nuttx/fs/procfs.h, include/nuttx/mm/mm.h, mm/mm_heap/mm.h, mm/mm_heap/mm_initialize.c, mm/mm_heap/mm_sem.c
=> mm: Add mm_uninitialize to release the resource

drivers/wireless/ieee80211/bcm43xxx/bcmf_ioctl.h
wireless/bcm43xxx: add extended join parameters
N/A
ci-check
=> wireless/bcm43xxx: add extended join parameters 

drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.h, drivers/wireless/ieee80211/bcm43xxx/bcmf_netdev.c, drivers/wireless/ieee80211/bcm43xxx/bcmf_netdev.h, drivers/wireless/ieee80211/bcm43xxx/bcmf_sdpcm.c
To remove the code duplication
Mine
=> bcm43xxx: Remove bcmf_txavail_work and resue bcmf_tx_poll_work

drivers/wireless/ieee80211/bcm43xxx/bcmf_netdev.c
wireless/bcm43xxx: improve throughput of net driver
1. Wake up tx if there is data alreay to sent after rx update
2. Try tx queue again after every data frame sent
iperf test:
```
TCP RX  4M->16M
⁣TCP TX  2M->14M
⁣UDP RX 18M->26M
UDP TX  2M->18M
```
data throughput
bcm43013 iperf test
=> wireless/bcm43xxx: improve throughput of net driver

drivers/wireless/ieee80211/bcm43xxx/Kconfig, drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.c
wireless/bcm43xxx: configurable buffer size of escan result
N/A
bcm43xxx scan
=> wireless/bcm43xxx: configurable buffer size of escan result 

drivers/wireless/ieee80211/bcm43xxx/bcmf_sdio.c
wireless/bcm43xxx: remove global variable for bcmf_sdio_thread
N/A
bcm43013 iperf test
=> wireless/bcm43xxx: remove global variable for bcmf_sdio_thread

arch/risc-v/src/mpfs/mpfs_userspace.c
The old implementation needed a contiguous memory block for user
ROM/RAM. This is because there was only 1 L3 page table which can only
map a contiguous memory area.
Also, remove the PMP configuration which just complicates things,
rely on the MMU mappings instead.
Minor change to CONFIG_BUILD_PROTECTED for mpfs target
Allows mapping RAM/ROM from different, non-contiguous memory locations
icicle:pnsh
=> mpfs: Allow mapping of RAM/ROM regions from different memory areas

drivers/wireless/ieee80211/bcm43xxx/Kconfig, drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.c, drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.h, drivers/wireless/ieee80211/bcm43xxx/bcmf_netdev.c
wireless/bcm43xxx: add auto power saving support
switch firmware power mode between PM_MAX/PM_FAST
N/A
bcm43013 iperf test
=> wireless/bcm43xxx: add auto power saving support

tools/ci/cibuild.sh, tools/ci/docker/linux/Dockerfile
1. add aarch64-none-elf toolchain for cibuild rule
No impact
NA
Signed-off-by: qinwei <qinwei1@xiaomi.com>
=> tools: ci : add cibuild rule for arm64

drivers/serial/uart_bth4.c
Signed-off-by: Lingao Meng <menglingao@xiaomi.com>
=> drivers: serial: Add error for insuff buffer

.gitignore, arch/arm/Kconfig, arch/arm/src/rp2040/Kconfig, arch/arm/src/rp2040/Make.defs, arch/arm/src/rp2040/hardware/rp2040_pwm.h, arch/arm/src/rp2040/rp2040_pwm.c, arch/arm/src/rp2040/rp2040_pwm.h, boards/arm/rp2040/common/include/rp2040_pwmdev.h, boards/arm/rp2040/common/src/Make.defs, boards/arm/rp2040/common/src/rp2040_pwmdev.c, boards/arm/rp2040/pimoroni-tiny2040/Kconfig, boards/arm/rp2040/pimoroni-tiny2040/README.txt, boards/arm/rp2040/pimoroni-tiny2040/src/rp2040_bringup.c, boards/arm/rp2040/raspberrypi-pico/Kconfig, boards/arm/rp2040/raspberrypi-pico/README.txt, boards/arm/rp2040/raspberrypi-pico/src/rp2040_bringup.c
Added PWM support for rp2040
This code should not impact other modules
Generated wave forms for both A and B ports in two port mode and the A port in single port mode.   Generated inverted and phase correct waveforms.
=> Added PWM for rp2040

tools/initialconfig.c
Fix warning while compiling NuttX tools
Small improvements
Compiling ESP32 and STM32 boards
=> tools: Fix warnings and replace deprecated readdir_r()

drivers/wireless/ieee80211/bcm43xxx/bcmf_netdev.c
wireless/bcm43xxx: correct the return value 
N/A
bcm43013 ifup/ifdown test
=> wireless/bcm43xxx: correct the return value 

net/netdev/netdev_carrier.c
netdev/carrier: check the IF stautus before carrier
N/A
netdev_carrier_on/off test
=> netdev/carrier: check the IF stautus before carrier

drivers/wireless/ieee80211/bcm43xxx/bcmf_sdio.c, drivers/wireless/ieee80211/bcm43xxx/bcmf_sdio.h
wireless/bcm43xxx: remove unused tx_queue_count
N/A
bcm43013
=> wireless/bcm43xxx: remove unused tx_queue_count

arch/arm/src/stm32wl5/Kconfig, arch/arm/src/stm32wl5/Make.defs, arch/arm/src/stm32wl5/hardware/stm32wl5_spi.h, arch/arm/src/stm32wl5/stm32wl5.h, arch/arm/src/stm32wl5/stm32wl5_spi.c, arch/arm/src/stm32wl5/stm32wl5_spi.h
Stm32wl55 SPI driver
Tested using sigrock on Nucleo Wl55JC board
=> Stm32wl55JC SPI driver

drivers/syslog/vsyslog.c
When `CONFIG_SYSLOG_COLOR_OUTPUT` is enabled, the terminal color is set before the message is printed, and it is reset at the end of the print.
It can happen that the log output may be interrupted (e.g. system crash, external reset etc). In this case, the color reset escape sequence will not be sent. On the next boot, all output on the terminal is presented on the wrong color (the terminal remembers the last setting, while the firmware assumes that everything is in a clean state).
This fix resets the terminal color every time a syslog channel is added, so even the very first print will be correct.
Handles the case where a syslog message is printed with an incorrect color.
I logged the bytes sent from the logger, and indeed the escape sequence is sent the moment the channel is added.
=> Added color reset when a syslog channel is added.

arch/xtensa/src/esp32s3/esp32s3_spi.c
Fix IOMUX function number for SPI
Only ESP32S3
ESP32S3-Devkit
=> esp32s3: Fix IOMUX function number for SPI

drivers/wireless/ieee80211/bcm43xxx/bcmf_sdio.c, drivers/wireless/ieee80211/bcm43xxx/bcmf_sdpcm.c
wireless/bcm43xxx: remove flowctrl check
remove flowctrl check since credit is enough to check flow control status
N/A
bcm43013
=> wireless/bcm43xxx: remove flowctrl check

drivers/wireless/ieee80211/bcm43xxx/bcmf_netdev.c, drivers/wireless/ieee80211/bcm43xxx/bcmf_sdio.c, drivers/wireless/ieee80211/bcm43xxx/bcmf_sdio.h, drivers/wireless/ieee80211/bcm43xxx/bcmf_sdpcm.c, drivers/wireless/ieee80211/bcm43xxx/bcmf_utils.c, drivers/wireless/ieee80211/bcm43xxx/bcmf_utils.h
2. wireless/bcm43xxx: allocate tx frame with nonblock mode
3. wireless/bcm43xxx: replace private queue implement to list_node
N/A
bcm43013 iperf test
=> wireless/bcm43xxx: replace private queue implement to list_node

drivers/wireless/ieee80211/bcm43xxx/bcmf_sdpcm.c
wireless/bcm43xxx: fix memory leak if tx fail
N/A
bcm43013
=> wireless/bcm43xxx: fix memory leak if tx fail 

drivers/lcd/lcd_framebuffer.c
See the discussion at: https://github.com/apache/incubator-nuttx/pull/6551
The full screen update
=> drivers/lcd_framebuffer: Optimize updateearea for the full screan case

boards/arm/rp2040/pimoroni-tiny2040/src/rp2040_bringup.c, boards/arm/rp2040/raspberrypi-pico/src/rp2040_bringup.c
Added ws2812 driver bringup to other RP2040 boards.
No impact to other boards.
Tested with RaspberryPi Pico.
=> Add  ws2812 bringup logic to all RP2040 boards.

.gitignore, arch/arm/src/rp2040/Make.defs, arch/arm/src/rp2040/hardware/rp2040_adc.h, arch/arm/src/rp2040/rp2040_adc.c, arch/arm/src/rp2040/rp2040_adc.h, arch/arm/src/rp2040/rp2040_ws2812.h, boards/Kconfig, boards/arm/rp2040/adafruit-feather-rp2040/README.txt, boards/arm/rp2040/adafruit-feather-rp2040/src/rp2040_bringup.c, boards/arm/rp2040/adafruit-kb2040/README.txt, boards/arm/rp2040/adafruit-kb2040/src/rp2040_bringup.c, boards/arm/rp2040/common/Kconfig, boards/arm/rp2040/pimoroni-tiny2040/README.txt, boards/arm/rp2040/pimoroni-tiny2040/src/rp2040_bringup.c, boards/arm/rp2040/raspberrypi-pico/README.txt, boards/arm/rp2040/raspberrypi-pico/src/rp2040_bringup.c, drivers/analog/adc.c
Added support for Analogue to Digital conversion for the RP2040.
Should not impact other functionality.
Build and tested with NSH and SMP profiles.  Tested reading 0-3.3 volts and reading processor temp sensor.
=> Added ADC support to RP2040

boards/xtensa/esp32s3/esp32s3-devkit/src/Make.defs, boards/xtensa/esp32s3/esp32s3-devkit/src/esp32s3_board_spi.c, boards/xtensa/esp32s3/esp32s3-devkit/src/esp32s3_bringup.c, boards/xtensa/esp32s3/esp32s3-devkit/src/esp32s3_st7735.c
Add support to ST7735 SPI LCD
Only ESP32S3
ESP32S3-Devkit
=> esp32s3-devkit: Add support to ST7735 SPI LCD

drivers/lcd/ssd1680.c
Displays with resolution that is not a multiplication of 8 had some issues in landscape mode
Fixed LANDSCAPE mode.
Some performance improvement in landscape mode.
None
On 2.13 inch display with STM nucleo WL55
=> SSD1680 Landscape mode bugfix

boards/xtensa/esp32/esp32-devkitc/include/board.h, boards/xtensa/esp32/esp32-ethernet-kit/include/board.h, boards/xtensa/esp32/esp32-wrover-kit/include/board.h, boards/xtensa/esp32/ttgo_eink5_v2/include/board.h, boards/xtensa/esp32/ttgo_lora_esp32/include/board.h, boards/xtensa/esp32s2/esp32s2-saola-1/include/board.h, boards/xtensa/esp32s3/esp32s3-devkit/include/board.h, boards/xtensa/esp32s3/esp32s3-eye/include/board.h
boards/xtensa: Remove outdated information.
N/A
N/A
=> boards/xtensa: Remove outdated information.

drivers/video/vnc/Kconfig, drivers/video/vnc/Make.defs, drivers/video/vnc/vnc_fbdev.c, drivers/video/vnc/vnc_kbd.c, drivers/video/vnc/vnc_receiver.c, drivers/video/vnc/vnc_server.h
* Support keyboard driver 
vncserver only
sim:vncserver
=> vncserver enhancement

arch/risc-v/src/esp32c3/esp32c3_partition.c, arch/risc-v/src/esp32c3/esp32c3_wifi_adapter.c, arch/xtensa/src/esp32/esp32_partition.c, arch/xtensa/src/esp32/esp32_spi_slave.c, arch/xtensa/src/esp32/esp32_spiflash.c, arch/xtensa/src/esp32/esp32_wifi_adapter.c, arch/xtensa/src/esp32/hardware/esp32_dport.h, boards/risc-v/bl602/bl602evb/src/bl602_bringup.c
This PR intends to fix some typos related to the word *register*.
No impact, just documentation fixes.
CI build pass.
=> Fix typo in "register" word 

include/sys/syscall_lookup.h, syscall/syscall.csv
- This commit adds socketpair to syscall.csv
- None
- Tested with adb (not merged net)
=> syscall: Add socketpair to syscall.csv

drivers/mmcsd/mmcsd_sdio.c
to avoid the check of CONFIG_HAVE_LONG_LONG in many place
Minor
Pass CI
=> mmcsd: Remove the not really used capacity field

fs/partition/fs_gpt.c
=> partition/gpt: Replace PRI?LBA with PRI?OFF

fs/mount/fs_procfs_mount.c
See the discuss here: https://github.com/apache/incubator-nuttx/issues/5253
Minor change
Pass CI
=> procfs/mount: Unify uint[32|64]_t to fsblkcnt_t for the code simplification

drivers/bch/bchdev_driver.c
Fix the problem reported by:
https://github.com/apache/incubator-nuttx/issues/6619
Minor
Pass CI
=> drivers/bch: Adjust f_pos with the correct value

arch/arm/src/phy62xx/log.h, arch/risc-v/src/bl602/bl602_os_hal.h, arch/risc-v/src/esp32c3/esp32c3_start.c, arch/risc-v/src/esp32c3/esp32c3_wifi_adapter.c, arch/xtensa/src/esp32/esp32_start.c, arch/xtensa/src/esp32/esp32_wifi_adapter.c, arch/xtensa/src/esp32s2/esp32s2_start.c, drivers/usbdev/usbdev_trprintf.c, fs/mount/fs_procfs_mount.c, include/debug.h, include/err.h, include/nuttx/fs/procfs.h, include/nuttx/usb/usbdev_trace.h, libs/libc/stdio/lib_libvsprintf.c, net/procfs/net_procfs_route.c
Enable more compiler time check
Pass CI
=> Add printflike and scanflike to all printf/scanf like functions

drivers/lcd/apa102.c
Add putarea() support for faster rendering
Now it can refresh the display very fast
APA102 LED Matrix
=> lcd/apa102: Add putarea() support for faster rendering

libs/libc/stdio/lib_libflushall.c
stdio: need also flush stdio when flushall
printf
VELA
=> stdio: need also flush stdio when flushall

sched/task/task_init.c, sched/task/task_setup.c, sched/task/task_vfork.c
sched: handle nxtask_setup_arguments return values
task setup
VELA
=> sched: handle nxtask_setup_arguments return values

fs/vfs/fs_unlink.c
unlink: don't do unlink with inode_semtake
fs/unlink
VELA
=> unlink: don't do unlink with inode_semtake

sched/sched/sched_critmonitor.c
sched_critmonitor: remove check zero in sched_critmonitor
Cause of up_perf_gettime() may return 0
sched_critmonitor
VELA
=> sched_critmonitor: remove check zero in sched_critmonitor

include/nuttx/mm/circbuf.h, mm/circbuf/circbuf.c
mm/circbuf: support circbuf_is_init and circ_peekat
support new api about circbuf
Vela CI
=> mm/circbuf: support circbuf_is_init and circ_peekat

drivers/timers/rpmsg_rtc.c
rtc/rpmsg: when a client connection, server initiates time sync
time sync to client
Vela Ci
=> rtc/rpmsg: when a client connection, server initiates time sync

fs/vfs/fs_poll.c
poll: defalut set POLLERR POLLHUP to events
poll
VELA
=> poll: defalut set POLLERR POLLHUP to events

sched/sched/sched_timerexpiration.c
=> sched: Remove the not really used cmptime

net/tcp/tcp_input.c
Signed-off-by: zhanghongyu <zhanghongyu@xiaomi.com>
Change-Id: I67eb94228c32f70eb5622426e680ed562eb9d42d
=> tcp: check option length before d_len update

boards/arm/stm32/common/src/stm32_bh1750.c
Fix mistakes in comments and snerr
none
=> boards/arm/stm32/common/src/stm32_bh1750.c: Fix mistakes in comments and snerr

libs/libc/machine/arm/armv8-m/Make.defs, libs/libc/math/Make.defs
libs/libc: correct config name
N/A
ci-check
=> libs/libc: correct config name

arch/risc-v/src/mpfs/mpfs_ihc.c, drivers/clk/clk_rpmsg.c, drivers/input/uinput.c, drivers/ioexpander/ioe_rpmsg.c, drivers/net/rpmsgdrv.c, drivers/power/regulator_rpmsg.c, drivers/rptun/rptun.c, drivers/rptun/rptun_dump.c, drivers/rptun/rptun_ping.c, drivers/serial/uart_rpmsg.c, drivers/syslog/syslog_rpmsg.c, drivers/syslog/syslog_rpmsg_server.c, drivers/timers/rpmsg_rtc.c, fs/rpmsgfs/rpmsgfs_client.c, fs/rpmsgfs/rpmsgfs_server.c, include/nuttx/rptun/openamp.h, include/nuttx/rptun/rptun.h, net/rpmsg/rpmsg_sockif.c
rptun: add dump vring info support
rptun: use seperated lock
rptun: add ns_match callback to resolve rptun deadlock
IPC
VELA
This must commit with:
https://github.com/apache/incubator-nuttx-apps/pull/1237
=> rptun related update

arch/arm/src/stm32f7/stm32_start.c
stm32f7: add showprogress in __start
none
=> stm32f7: add showprogress in __start

boards/arm/stm32/common/src/stm32_ina219.c, boards/arm/stm32/common/src/stm32_max31855.c, boards/arm/stm32/common/src/stm32_max6675.c, boards/arm/stm32/common/src/stm32_mlx90614.c
Fix mistakes in comments, snerr and  syslog
none
=> boards/arm/stm32/common/src: Fix mistakes in comments, snerr and syslog

drivers/power/battery_charger.c, drivers/power/battery_gauge.c, drivers/power/battery_monitor.c, include/nuttx/list.h
since it may happen before battery_xxx_register sometime
Some corner case
Internal test
=> drivers/battery: Handle the early changed event correctly

arch/sim/include/limits.h
=> arch: fix typo

arch/arm/src/lpc17xx_40xx/lpc17_40_can.c
Adds SocketCAN support to LPC17_40 CAN driver
Minimal compile switch allows to still use the old character device driver
Tested on custom LPC1768 board.
=> LPC17_40 CAN driver SocketCAN support

arch/arm/src/common/arm_checkstack.c
- I noticed that ps shows incorrect stack usage when running
getprime in the background.
- With CONFIG_ARCH_ADDRENV=y, a user task including pthread
allocates its stack in the user space that needs to be
accessed with a correct address environment.
- CONFIG_ARCH_ADDRENV=y only
- Tested with sabre-6quad:knsh on qemu-6.2
=> arch: common: Fix up_check_tcbstack() for CONFIG_ARCH_ADDRENV=y

arch/arm/src/imxrt/Kconfig, arch/arm/src/imxrt/hardware/imxrt_lpi2c.h, arch/arm/src/imxrt/imxrt_lpi2c.c, arch/arm/src/imxrt/imxrt_lpspi.c, arch/arm/src/imxrt/imxrt_serial.c, arch/arm/src/imxrt/imxrt_serial.h
Adds Add DMA on LPSPI, LPUART, LPI2C
Should be none
PX4 nxp_fmurt1062-v1
=> IMX.RT Add DMA on LPSPI, LPUART, LPI2C

arch/arm/src/phy62xx/Make.defs, arch/arm/src/phy62xx/bus_dev.h, arch/arm/src/phy62xx/clock.c, arch/arm/src/phy62xx/irq.c, arch/arm/src/phy62xx/phy6222_irq.h, arch/arm/src/phy62xx/phy6222_patch.c, arch/arm/src/phy62xx/phy62xx_exception.S, arch/arm/src/phy62xx/rom_sym_def.h, arch/arm/src/phy62xx/timer.c, arch/arm/src/phy62xx/uart.c, boards/arm/phy62xx/phy6222/scripts/flash.ld
=> remove unused lib

arch/arm/src/phy62xx/phy6222_patch.c
=> remove unused lib,fix compile warning, fix dos2unix

include/err.h, libs/libc/misc/Make.defs
let linker remove the unused object files from the final image
Minor
Pass CI
=> libc: Remove CONFIG_LIBC_ERR

include/fcntl.h, include/sys/memfd.h, libs/libc/misc/Kconfig, libs/libc/misc/Make.defs, libs/libc/misc/lib_memfd.c
https://man7.org/linux/man-pages/man2/memfd_create.2.html
New API
Pass CI
=> libc: Implement memfd on top of tmpfs

Kconfig, LICENSE, include/sys/queue.h
=> include:add sys/queue.h support form openbsd

arch/risc-v/src/mpfs/mpfs_ihc.c
OpenSBI vendor extension calls must not cause scheduling, as they're
part of M-mode trap handling. Thus, comment out nxsig_usleep() as
well, which is occasionally taken and crashes the system in that
case. Fix this by commenting out lines that have the potential to
cause scheduling.
Fix for bootloader-mode OpenSBI vendor extension path
MPFS with IHC
Polarfire Icicle kit
=> risc-v/mpfs: ihc: don't use semaphores with OpenSBI vendor calls

include/nuttx/net/snoop.h, net/utils/Make.defs, net/utils/net_snoop.c
Signed-off-by: chengkai <chengkai@xiaomi.com>
add btsnoop and snoop  feature
NO
1. wireshark   could load btsnoop pass
2. ellisys import btsnoop pass
=> net:add btsnoop and snoop

drivers/serial/uart_bth4.c, include/nuttx/wireless/bluetooth/bt_driver.h
Signed-off-by: chengkai <chengkai@xiaomi.com>
add h4 ioctl interface
pass ci
=> serial/uart/h4: add ioctl interface

arch/arm/src/tiva/common/tiva_serial.c
arch/tiva/serial: Fix a few incorrect comments and minor code formatting.
Improves documentation within code.
nxstyle
=> arch/tiva: Fix typo and minor code formatting

drivers/syslog/Kconfig, drivers/syslog/Make.defs, drivers/syslog/ramlog.c, mm/iob/Kconfig, mm/iob/Make.defs, mm/iob/iob_initialize.c
1.Remove the default value(.bss)
2.Remove !ARCH_SIM dependence
Refactor only
Pass CI
=> Refine how to specify iob and ramlog data section

boards/risc-v/k210/maix-bit/README-qemu.txt
=> boards/k210/maix-bit: Fix a typo in README

drivers/wireless/bluetooth/Kconfig, drivers/wireless/bluetooth/Make.defs, drivers/wireless/bluetooth/bt_bridge.c, include/nuttx/wireless/bluetooth/bt_bridge.h
Signed-off-by: chengkai <chengkai@xiaomi.com>
add bt bridge feature， with which  two bt protocol stacks could coexist.
NO
ci pass
=> wireless/bluetooth:add bt bridge codes

sched/sched/sched_processtimer.c, sched/sched/sched_timerexpiration.c
cpuload: fix cpuload error
cpuload
VELA
=> cpuload: fix cpuload error

fs/littlefs/Make.defs, libs/libxx/libcxx.defs, libs/libxx/libcxxabi.defs, openamp/libmetal.defs, openamp/open-amp.defs
Follow https://github.com/apache/incubator-nuttx-apps/pull/1295
3rd party projects
CI and custom board
=> Don't download tarballs if a local git repo found

arch/risc-v/include/mode.h, arch/risc-v/src/common/riscv_exception.c
Dump trap val in exception handler
Exception message only
CI and custom board
=> riscv: Dump trap val in exception handler

sched/semaphore/sem_post.c
Add temporary variable sem_count to improve sem post performance
Code Size:
before:
```
text	   data	    bss	    dec	    hex	filename
109708	    224	  24940	 134872	  20ed8	nuttx
```
after:
```
text	   data	    bss	    dec	    hex	filename
109708	    224	  24940	 134872	  20ed8	nuttx
```
Performance:
sem_post -> sem_wait (cycle count):
before:
`195`
after:
`192`
sabre-6quad:nsh
=> sched/semaphore: add sem_count temporary variable to improve performance

include/endian.h
add openbsd style to endian.h
CI
=> include:endian.h add openbsd style

include/string.h, libs/libc/string/Make.defs, libs/libc/string/lib_timingsafe_bcmp.c
add timingsafe_bcmp to libc
CI
=> libc:add timingsafe_bcmp to libc

ReleaseNotes
This is a local copy taken from the confluence notes
https://cwiki.apache.org/confluence/display/NUTTX/NuttX+11.0.0
RELEASE
NONE
=> documentation: Add release notes for 11.0.0 release

ReleaseNotes
In the ReleaseNotes, fix link errors to each pull request.
Issue https://github.com/apache/incubator-nuttx/issues/7008
Replaced (fixed) all previous released versions.
=> documentation: Fix links to pull requests in release notes

arch/arm/src/armv6-m/barriers.h, arch/arm/src/rp2040/rp2040_cyw43439.c
Added code to resolve a race condition when writing data to the Pico W's WiFi chip.
No impact to other software.
Built and run on RaspberryPi Pico W.
=> Fix race condition in RaspberryPi Pico W WiFi 

drivers/ipcc/ipcc_read.c, drivers/ipcc/ipcc_write.c
drivers/ipcc: enter/leave critical section should in pairs
N/A
N/A
=> drivers/ipcc: enter/leave critical section should in pairs 

arch/risc-v/src/mpfs/mpfs_usb.c
Issuing the following commands doesn't succeed:
- conn
- disconn
- conn
This USB driver doesn't even disconnect without this patch.
If the USB driver has been started from another hart, closing it will not disable the PLIC interrupt. This means it's possible many harts get the USB interrupt and thus make the USB look very unstable.
Fix these problems by disconnecting the USB via the USB_POWER register at shutdown and disabling the interrupt at shutdown. Also clear the software internals via the mpfs_sw_setup() for the conn / disconect loop to succeed.
This fixes USB restart and starting / stopping USB on different harts
MPFS Polarfire
MPFS Polarfire kit against Ubuntu 22.04
=> risc-v/mpfs: usb: fix usb restart

ReleaseNotes
In the ReleaseNotes, fix link errors to each pull request.
RELEASE
NONE
=> [BP] documentation: Fix links to pull requests in release notes

tools/Config.mk
See also: https://github.com/apache/incubator-nuttx-apps/pull/1315
Zig only
Custom sim
=> Config.mk: Add COMPILEZIG

arch/risc-v/src/mpfs/mpfs_emmcsd.c
If the system starts up using the SD-card, and later wants to switch to use the eMMC, it's not going to happen. SD-card will be kept selected within the FPGA making the transition fail.
It's been possible to switch from eMMC to SD, but now the transition is possible for both directions.
Switching from SD-card -> eMMC is possible. Fix this issue. At power-on, eMMC is selected. If SD-card is used by a hart, and later eMMC is needed, this doesn't happen.
MPFS Icicle
Icicle Polarfire kit, NuttX bootloader at hart0 which loads data from SD card, and starts another NuttX (hart1) that uses eMMC.
=> risc-v/mpfs: emmcsd: allow switching from SD to eMMC

arch/arm/src/armv7-a/arm_cache.c, arch/arm/src/armv7-r/arm_cache.c
cache: fix up_clean_dcache() slowly
dcache
VELA
=> cache: fix up_clean_dcache() slowly

arch/arm/src/armv7-a/Make.defs, arch/arm/src/armv7-a/arm_timer.c, arch/arm/src/armv7-a/arm_timer.h, arch/arm/src/armv7-r/Kconfig, arch/arm/src/armv7-r/Make.defs, arch/arm/src/armv7-r/arm_timer.c, arch/arm/src/armv7-r/arm_timer.h
armv7-a/r: use generic timer to realize arm_timer
New driver
VELA
=> armv7-a/r: use generic timer to realize arm_timer

drivers/serial/uart_rpmsg.c
uart_rpmsg: add mutex to dmatx
uart_rpmsg
VELA
=> uart_rpmsg: add mutex to dmatx

mm/kasan/kasan.c
kasan: use init value to avoid kasan used before bss clear
kasan
VELA
=> kasan: use init value to avoid kasan used before bss clear

drivers/usrsock/usrsock_dev.c, net/usrsock/usrsock_accept.c, net/usrsock/usrsock_bind.c, net/usrsock/usrsock_close.c, net/usrsock/usrsock_connect.c, net/usrsock/usrsock_devif.c, net/usrsock/usrsock_getpeername.c, net/usrsock/usrsock_getsockname.c, net/usrsock/usrsock_getsockopt.c, net/usrsock/usrsock_ioctl.c, net/usrsock/usrsock_listen.c, net/usrsock/usrsock_poll.c, net/usrsock/usrsock_recvmsg.c, net/usrsock/usrsock_sendmsg.c, net/usrsock/usrsock_setsockopt.c, net/usrsock/usrsock_socket.c
- net/usrsock: Remove the unnecessary extra space
- net/usrsock: Remove the unnecessary label
No, code refactor
Pass CI
=> net/usrsock: Code refactor

tools/b16.c
Fix some typos in user-visible usage text printed by the tools/b16.c utility.
Improves readability.
nxstyle
=> tools/b16.c: Fix usage text

boards/arm/tlsr82/tlsr8278adk80d/scripts/flash_boot_ble.ld
Add specific section for discribe information, current use for factory test.
Signed-off-by: Lingao Meng <menglingao@xiaomi.com>
=> boards: tlsr: Add specific section for discribe information

mm/mm_heap/mm_free.c, mm/shm/shmget.c
=> mm: Fix minor style issue

arch/arm/src/common/arm_assert.c, arch/arm/src/imxrt/imxrt_enc.c, arch/arm/src/imxrt/imxrt_lpi2c.c, arch/arm/src/imxrt/imxrt_lpspi.c, arch/arm/src/lpc17xx_40xx/lpc17_40_can.c, arch/arm/src/rp2040/rp2040_adc.c, arch/arm/src/rp2040/rp2040_adc.h, arch/arm/src/rp2040/rp2040_cyw43439.c, arch/arm/src/rp2040/rp2040_cyw43439.h, arch/arm/src/rp2040/rp2040_ws2812.c, arch/arm/src/rp2040/rp2040_ws2812.h, arch/arm/src/stm32wl5/stm32wl5_allocateheap.c, arch/arm/src/stm32wl5/stm32wl5_ipcc.c, arch/arm/src/stm32wl5/stm32wl5_irq.c, arch/arm/src/stm32wl5/stm32wl5_serial.c, arch/arm/src/stm32wl5/stm32wl5_tim.c, arch/arm/src/stm32wl5/stm32wl5_tim.h, arch/arm/src/stm32wl5/stm32wl5_tim_lowerhalf.c, arch/risc-v/src/common/riscv_assert.c, arch/sim/src/sim/up_usrsock.c, arch/sparc/src/bm3803/bm3803_wdg.c, arch/xtensa/src/common/xtensa_dumpstate.c, boards/arm/s32k3xx/mr-canhubk3/src/s32k3xx_dma_alloc.c, boards/arm/samv7/common/src/sam_gpio_enc.c, boards/arm/stm32/stm32f4discovery/src/stm32_capture.c, boards/arm/stm32/stm32f4discovery/src/stm32f4discovery.h, boards/arm/stm32h7/nucleo-h743zi/src/stm32_boot_image.c, boards/arm/stm32h7/nucleo-h743zi/src/stm32_progmem.c, boards/arm/stm32wl5/nucleo-wl55jc/src/stm32_flash.c, boards/xtensa/esp32/common/src/esp32_st7789.c
=> boards/arch: Remove FAR from 32bit/64bit arch

libs/libc/misc/Kconfig
forget in https://github.com/apache/incubator-nuttx/pull/6805
Mine
Pass CI
=> libc: Remove LIBC_ERR from libs/libc/misc/Kconfig

arch/arm/src/samv7/sam_hsmci.c
1. Fix random corruption of data after SDIO RX DMA transaction by invalidating the cache on memory updated by the DMA
2. Use time based timeout calculation instead of cycle based
3. Minor styling fixes
SAMv7 based boards
Custom SAMe70 based board
=> arch/arm/samv7: fix random corruption of data after SDIO RX DMA transaction

arch/arm/src/common/Toolchain.defs, arch/arm/src/tlsr82/Make.defs, arch/risc-v/src/common/Make.defs, arch/sparc/src/sparc_v8/Toolchain.defs, arch/xtensa/src/common/Make.defs, boards/arm/phy62xx/phy6222/scripts/Make.defs, boards/arm/stm32/b-g431b-esc1/src/Make.defs, boards/arm/stm32l5/stm32l562e-dk/scripts/Make.defs, boards/arm/stm32u5/b-u585i-iot02a/scripts/Make.defs
nxstyle: correct the file path
N/A
CI check
=> nxstyle: correct the file path

Documentation/platforms/xtensa/esp32/index.rst
Added instructions on how to enable Secure Boot and Flash Encryption on ESP32 boards.
=> documentation/esp32: Added Secure Boot and Flash Encryption section

arch/arm/src/armv7-a/arm_head.S, arch/arm/src/armv7-a/arm_scu.c
mmu: mmu enable should after enable SMP
SMP
VELA
=> mmu: mmu enable should after enable SMP

net/socket/getsockopt.c
=> net: Implement SO_RCVBUF and SO_SNDBUF for getsockopt

include/netinet/in.h
defined here:
https://pubs.opengroup.org/onlinepubs/009695399/basedefs/netinet/in.h.html
New macro
=> net: Add IN6_IS_ADDR_LINKLOCAL macro

arch/arm/src/stm32wl5/stm32wl5_rcc.h
Code fixing for the conditional compilation term (#else)
=> arch/arm: stm32wl5: fix conditional compilation term (#else)

arch/arm/src/stm32l5/stm32l5_rcc.h
Code fixing for the conditional compilation term (#else)
=> arch/arm: stm32l5: fix conditional compilation term (#else)

tools/ci/testlist/arm-13.dat
ci/testcase: add launchxl-tms57004/nsh(Cortex-R4) into build list
N/A
ci check
=> ci/testcase: add launchxl-tms57004/nsh(Cortex-R4) into build list

AUTHORS
Hi, I might have forgot to touch this file
while I committed previously.
IIRC I already signed Apache paperworks too.
Relate-to: https://rzr.github.io/rzr-presentations/docs/nuttx
Relate-to: https://github.com/apache/incubator-nuttx/pulls?q=author%3Arzr
Signed-off-by: Philippe Coval <rzr@users.sf.net>
=> AUTHORS: Add myself to file as suggested at event

boards/arm/tiva/tm4c129e-launchpad/README.txt
Expand the README.txt for `tm4c129e-launchpad`.
(The main motivation was to add the elusive `openocd` incantation to flash program this board. However, I also added useful documentation about toolchains, debugging, clocking, and the ICDI virtual serial interface.)
Improve documentation.
The openocd incantation works. :-)
=> boards/tm4c129e-launchpad: Expand README.txt

tools/ci/cibuild.sh, tools/ci/docker/linux/Dockerfile
Signed-off-by: nietingting <nietingting@xiaomi.com>
enable pytest support on docker
no
test on local
=> ci: enable pytest on docker file

net/local/local_recvmsg.c
net/local: remove dead code
N/A
ci check
=> net/local: remove dead code

Documentation/reference/os/time_clock.rst, arch/arm/src/lc823450/lc823450_timer.c, include/nuttx/clock.h, sched/clock/clock.h, sched/clock/clock_initialize.c, sched/clock/clock_systime_ticks.c
=> sched/clock: Rename g_system_timer to g_system_ticks

tools/ci/cibuild.sh, tools/ci/docker/linux/Dockerfile
Add python dependency library in ci to generate symbol table
=> tools/ci: add pyelftools and cxxfilt

arch/arm/src/Makefile, arch/risc-v/src/Makefile, arch/xtensa/src/Makefile
arch/makefile: preprocess link script to make configure more flexibly
N/A
ci-check
=> arch/makefile: preprocess link script to make configure more flexibly 

arch/arm/src/armv7-m/arm_cache.c, arch/arm/src/armv8-m/arm_cache.c
=> arch/armv[7|8]-m: Implement up_invalidate_icache

include/stdint.h
include/stdint.h: add sig_atomic_t limits
None
CI
=> include/stdint.h: add sig_atomic_t limits

Documentation/platforms/xtensa/esp32/index.rst
Fix typo in the softap
Now people will use the right command to create a WiFi Soft AP
N/A
=> doc/esp32: Fix typo in the softap

arch/risc-v/src/common/riscv_percpu.c
- This commit introduces g_percpu_spin in riscv_percpu.c instead of using the global spinlock.
- None
- Tested with rv-virt:knsh64 and rv-virt:ksmp64 (will be added later)
=> arch: risc-v: Introduce g_percpu_spin in riscv_percpu.c

include/nuttx/list.h
Report here: https://github.com/apache/incubator-nuttx/pull/7238
Pass CI
=> list.h: Add local temp variable to avoid the double evaluation

arch/risc-v/src/qemu-rv/qemu_rv_timerisr.c
- I noticed that the OS timer sometimes proceeds fast when a task is scheduled to run on CPUO via IPI.
- Actually, qemu-rv implementation shares supervisor software interrupt for both timer and IPI on CPU0.
- qemu-rv only
- Tested with qemu-6.2
=> arch: qemu-rv: Fix timer and IPI handling for BUILD_KERNEL+SMP

.github/workflows/build.yml, tools/ci/testlist/codechecker.dat, tools/testbuild.sh
Add CodeChecker to CI
Increase the rigor with which code is reviewed
It may increase the time of CI
=> Add CodeChecker to CI

Documentation/guides/customapps.rst, Documentation/guides/customboards.rst, Documentation/guides/index.rst
Adds new RST files to document creating custom boards out of tree, and custom apps in and out of tree
Improved documentation
HTML created and viewed
Examples from this documentation tried and  proven.
=> Documentation for  Custom Boards and Apps

net/usrsock/usrsock_connect.c, net/usrsock/usrsock_devif.c, net/usrsock/usrsock_event.c, net/usrsock/usrsock_socket.c
Correct some status exceptions in non-blocking mode usrsock connect
Depends on https://github.com/apache/incubator-nuttx-apps/pull/1345
=> usrsock: Correct some status exceptions in non-blocking mode usrsock connect

fs/vfs/fs_rename.c
An alternative to https://github.com/apache/incubator-nuttx/pull/7311
Bug fix
Tested with FAT FS on SD-CARD
=> fs/vfs: fix case when file to rename does not exist

include/net/if.h, include/nuttx/net/ioctl.h, include/nuttx/net/net.h, net/Kconfig, net/netdev/netdev_ioctl.c, net/netdev/netdev_register.c
Add Cellular link layer support
1.Add cellular link layer enum definition and register flow 2.Add ioctl flow to set cellular NICs parameters
Signed-off-by: luojun1 <luojun1@xiaomi.com>
N/A
cellular ioctl
=> Add Cellular link layer support

include/spawn.h
=> sched/spawn: Add the dummy task_spawnattr_xxxstackyyy in the kernel mode

fs/vfs/fs_rename.c
Found in reviewing https://github.com/apache/incubator-nuttx/pull/7312
- fs/vfs: Free subdir before allocate new one in pseudorename
- fs/vfs: Remove the redundancy file name comparison in mountptrename 
Minor
=> Refine the implementation of rename

boards/risc-v/qemu-rv/rv-virt/README.txt
- This commit updates README.txt regarding how to build kernel and apps for BUILD_KERNEL
- Also update on parallel build for BUILD_FLAT
- None
- Tested with qemu-7.1.0
=> boards: rv-virt: Update README.txt

arch/xtensa/src/esp32/esp32_qencoder.c
Fix small issues and typos
Only for esp32_qencoder
esp32-devkitc
=> esp32_qencoder: Fix small issues and typos reported by Tiago Medicci

tools/ci/docker/linux/Dockerfile
Signed-off-by: nietingting <nietingting@xiaomi.com>
install qemu on docker
no
test on local host
=> install qemu on docker

arch/arm/src/stm32/stm32_can_sock.c, arch/arm/src/stm32/stm32_fdcan_sock.c
=> stm32/socketcan: fixes for arm_netinitialize

libs/libc/time/lib_strftime.c
Enhanced `strftime()` with support for the `%w` format specifier.
New functionality.
Tested prints on simulator.
=> strftime: Added support for the %w format specifier.

net/inet/inet_sockif.c, net/socket/setsockopt.c, net/socket/socket.c, net/socket/socketpair.c
=> Some relatively reasonable error code modifications

net/can/can_getsockopt.c, net/can/can_setsockopt.c
net/can/can_xxxsockopt.c: correct the code alignment
None
CI
=> net/can/can_xxxsockopt.c: correct the code alignment

AUTHORS
I have submitted ICLA in Jun 27, 2022, I'm glad to contribute code to nuttx
nothing
ci
=> AUTHORS: Add myself into authors list

tools/ci/cibuild.sh, tools/ci/docker/linux/Dockerfile
=> ci: Install LLVM Embedded Toolchain for Arm

drivers/modem/alt1250/alt1250.c
Notify only when there are available events.
modem/alt1250 only
spresense lte works well.
=> drivers/modem/alt1250: Fix poll function

arch/risc-v/src/mpfs/hardware/mpfs_usb.h, include/sys/queue.h, sched/semaphore/sem_holder.c
Fix few style issues in multiple files
None
Pass CI
=> Style fixes

drivers/modem/alt1250/alt1250.c
Changed the return type to bool pointed out in the review comments for https://github.com/apache/incubator-nuttx/pull/7402.
None
=> drivers/modem/alt1250: Change return type of bool function

boards/arm/cxd56xx/drivers/audio/Make.defs, drivers/clk/Make.defs, drivers/modem/alt1250/Make.defs, drivers/motor/foc/Make.defs
This parameter is invalid
See git commit # 5eae32577e5d5226e5d3027c169eeb369f83f77d
=> Makefile: Remove INCDIROPT

arch/arm/src/imx6/imx_enet.c, arch/arm/src/imxrt/imxrt_enet.c, arch/arm/src/s32k1xx/s32k1xx_enet.c, arch/arm/src/s32k1xx/s32k1xx_lpspi.c, arch/arm/src/s32k3xx/s32k3xx_lpspi.c
Code refactor only
same as before
Pass CI
=> arch: Replace __builtin_bswapxx with bswapxx

drivers/timers/capture.c
=> drivers/timers/capture: Fix mutual exclusion lock

net/socket/recvmsg.c, net/socket/sendmsg.c
Follow the change: https://github.com/apache/incubator-nuttx/pull/7438
=> net: Remove the unused nx_[send|recv]msg

include/nuttx/mm/mempool.h, mm/mempool/Make.defs, mm/mempool/mempool.c, mm/mempool/mempool_multiple.c, mm/mempool/mempool_procfs.c
1. support multiple-mempool, it includes a series of mempool.
2. support custom alloc and free api about the mempool. 
3. do realloc and alloc_size about the mempool.
4. add kasan check for the mempool.
Enhance mempool and support multiple mempool.
local CI
=> mempool: support multiple-mempool and enhance mempool

include/nuttx/kmalloc.h, include/nuttx/mm/mm.h, mm/kmm_heap/Make.defs, mm/kmm_heap/kmm_memdump.c, mm/umm_heap/Make.defs, mm/umm_heap/umm_memdump.c, sched/Kconfig, sched/task/task_exithook.c
Print all unreleased memory blocks when the task exits
=> Check for memory leaks in tasks

tools/ci/testrun/script/test_os/test_os.py
Signed-off-by: nietingting <nietingting@xiaomi.com>
fix PytestUnknownMarkWarning issue
ci test
test on local
=> fix PytestUnknownMarkWarning issue

fs/semaphore/sem_unlink.c, libs/libnx/nxmu/nx_bitmap.c, libs/libnx/nxmu/nx_getrectangle.c, sched/pthread/pthread_condbroadcast.c, sched/pthread/pthread_condsignal.c, sched/pthread/pthread_condwait.c, sched/pthread/pthread_mutexconsistent.c, sched/pthread/pthread_mutexdestroy.c, sched/pthread/pthread_mutexinit.c
=> sched: Remove the unnecessary (FAR sem_t *) cast

include/nuttx/sched.h, mm/mm_heap/mm.h, wireless/ieee802154/mac802154_device.c
=> Change the type of tg_joinlock, mm_lock and md_lock from sem_t to mutex_t

arch/arm/src/cxd56xx/cxd56_timer.c, libs/libc/machine/arm/armv6-m/arch_elf.c, libs/libc/machine/arm/armv7-a/arch_elf.c, libs/libc/machine/arm/armv7-m/arch_elf.c, libs/libc/machine/arm/armv8-m/arch_elf.c
=> Fix the format string mismatch warning 

boards/arm/cxd56xx/common/src/cxd56_isx012.c, boards/arm/cxd56xx/spresense/Kconfig, boards/arm/cxd56xx/spresense/src/cxd56_bringup.c
* boards: cxd56xx: Fix power-off time of video driver
* boards: cxd56xx: Add CXD56_CAMERA_LATE_INITIALIZE config
* boards/cxd56xx/spresense: Add CXD56_LTE_LATE_INITIALIZE config
Only spresense board
=> boards: cxd56xx: Minor update for video and lte driver

boards/arm/stm32h7/nucleo-h743zi/src/stm32_bringup.c
Signed-off-by: Andrés Sánchez Pascual <tito97_sp@hotmail.com>
Initialize wdg in STM32H743ZI board
STM32H743ZI board
=> board: stm32h7: Initialization of wdg

arch/arm/src/armv7-m/nvic.h, arch/arm/src/armv8-m/nvic.h
Adds DHCSR register definitions for ARMv7 & ARMv8.
References:  
* ARMv7: https://developer.arm.com/documentation/ddi0337/e/CEGCJAHJ
* ARMv8: http://kib.kiev.ua/x86docs/ARM/ARMARMv8m/DDI0553B_o_armv8m_arm.pdf
N/A
N/A
=> Added DHCSR definitions for ARMv7 & ARMv8.

sched/clock/clock_systime_ticks.c, sched/clock/clock_systime_timespec.c
When CONFIG_SCHED_TICKLESS_TICK_ARGUMENT enabled, we can use up_timer_gettick to get ticks for better performance.
N/A
IMX6Q sabre-6quad:nsh
=> clock: adjust clock function to support tick

arch/arm/src/lpc17xx_40xx/lpc176x_clockconfig.c, arch/arm/src/lpc17xx_40xx/lpc17_40_sdcard.c, arch/arm/src/lpc17xx_40xx/lpc17_40_serial.c, drivers/usbhost/usbhost_hidmouse.c, include/nuttx/usb/usb.h, net/sixlowpan/sixlowpan_internal.h
Fix the compiler waring
Minor
Pass CI
=> Fix the warning found by https://github.com/apache/incubator-nuttx/pull/7391

arch/arm/include/inttypes.h
Suggest in https://github.com/apache/incubator-nuttx/pull/7476
Comment only
=> arch/arm: Document the clever trick of PRI?32 macros

Documentation/faq/index.rst
Add how to configure network MTU size
Users will know how to setup network MTU on NuttX
N/A
=> Doc: Add how to configure network MTU size

mm/kasan/kasan.c
kasan: fix kasan race-condition
KASAN
VELA
=> kasan: fix kasan race-condition

arch/arm/src/lpc17xx_40xx/lpc17_40_serial.c, arch/arm/src/lpc17xx_40xx/lpc17_40_spi.c, boards/arm/lpc17xx_40xx/mcb1700/src/mcb1700.h
Report from https://github.com/apache/incubator-nuttx/pull/7391
Minor change
Pass CI
=> Fix the compiler warning found by clang

arch/renesas/src/rx65n/rx65n_sbram.c, drivers/lcd/ft80x.c, drivers/lcd/pcf8574_lcd_backpack.c, drivers/serial/serial.c, drivers/usbhost/usbhost_skeleton.c, drivers/video/video.c, drivers/wireless/ieee802154/xbee/xbee_mac.c, wireless/ieee802154/mac802154_scan.c
nxmutex: minor fix for mutex lock mismatch
N/A
ci check
=> nxmutex: minor fix for mutex lock mismatch

arch/renesas/src/rx65n/rx65n_usbhost.c, fs/unionfs/fs_unionfs.c
fix mistake
nothing
ci
this mistake brought by this #6965
=> fix a mistake about nxmutex & sem

include/nuttx/fs/ioctl.h, include/nuttx/video/video.h
to align with other drivers
code refactor
pass CI
=> video: Move _VIDIOCBASE and _VIDIOC to include/nuttx/fs/ioctl.h

include/endian.h
add this macro bemtoh htobem lemtoh htolem
add some endian macro
nothing
ci
=> include/endian:add openbsd style macro

arch/arm/include/types.h
regressed by: https://github.com/apache/incubator-nuttx/pull/7476
arm
Pass CI
=> arch/arm: Fix types.h:61:9: error: unknown type name '__UINT32_TYPE__'

include/nuttx/net/netconfig.h, net/tcp/Kconfig
=> net/tcp: Make TCP_MAXRTX and TCP_MAXSYNRTX configurable

drivers/sensors/mpu60x0.c
call nxmutex_lock and nxmutex_unlock directly
code refactor
Pass CI
=> sensors/mpu60x0: Remove the simple mpu_lock/mpu_unlock

mm/mm_heap/mm.h
=> mm: Remove the unused macro MM_IS_ALLOCATED

fs/vfs/fs_epoll.c
- vfs/epoll: Replace sem_t with mutex_t for locking usage 
- vfs/epoll: Protect epoll_ctl by mutex 
epoll
=> Correct epoll lock usage

tools/Win.mk
fix shell conditional
Windows native build
ci
=> tools/Win.mk Fix error in Windows native build

libs/libc/semaphore/sem_init.c, sched/mqueue/mq_send.c, sched/semaphore/sem_clockwait.c, sched/semaphore/sem_destroy.c, sched/semaphore/sem_post.c, sched/semaphore/sem_trywait.c, sched/semaphore/sem_wait.c
move param check to sem_xx level
for the speed improve
sem
mqueue
signal
VELA
=> move param check to sem_xx level

arch/arm/src/armv7-r/arm_gicv2.c
armv7-r: fix arm_gic_nlines redefines
armv7r
VELA
=> armv7-r: fix arm_gic_nlines redefines

drivers/rptun/rptun.c
rptun: fix rptun sem post too much
rptun: fix race-condition on g_rptun_cb & g_rptun_priv
both rptun_dev_start() & rpmsg_register_callback() will use
these two lists
rptun IPC
VELA
=> rptun bug fix

net/rpmsg/rpmsg_sockif.c
rpmsg socket: add lock to poll & poll_notify
rpmsg scoket
VELA
=> rpmsg socket: add lock to poll & poll_notify

tools/configure.bat, tools/configure.c, tools/incdir.c
Add some Windows native compilation fixes
Improve Windows native build
Can successfully configure project on Win8.1 with cmd
=> tools: Add some Windows native compilation fixes

fs/procfs/fs_procfsproc.c, include/nuttx/sched.h, sched/irq/irq_dispatch.c
align with other flags naming convention
Minor
Pass CI
=> mm/heap: Change TCB_FLAG_HEAPCHECK to TCB_FLAG_HEAP_CHECK

arch/arm/src/armv8-m/arm_cache.c, arch/arm/src/imxrt/imxrt_lpspi.c, arch/arm/src/max326xx/max32660/max32660_serial.c, arch/arm/src/nuc1xx/nuc_serial.c, arch/arm/src/nuc1xx/nuc_timerisr.c, arch/arm/src/rp2040/rp2040_clock.c, arch/arm/src/rp2040/rp2040_cyw43439.c, arch/arm/src/rp2040/rp2040_ws2812.c, arch/arm/src/s32k1xx/s32k1xx_lpi2c.c, arch/arm/src/s32k1xx/s32k1xx_lpspi.c, arch/arm/src/s32k3xx/s32k3xx_lpspi.c, arch/arm/src/sam34/sam_udp.c, arch/arm/src/sama5/sam_adc.c, arch/arm/src/sama5/sam_udphs.c, arch/arm/src/samd2l2/sam_usb.c, arch/arm/src/samd5e5/sam_usb.c, arch/arm/src/samv7/sam_afec.c, arch/arm/src/samv7/sam_dac.c, arch/arm/src/samv7/sam_serial.c, arch/arm/src/samv7/sam_tc.c, arch/arm/src/samv7/sam_usbdevhs.c, drivers/wireless/ieee802154/mrf24j40/mrf24j40_radif.c, include/nuttx/compiler.h
Found by https://github.com/apache/incubator-nuttx/pull/7391
Minor
Pass CI
=> Fix warning reported by clang

tools/configure.bat
=> tools/configure.bat: Update USAGE

drivers/misc/rpmsgdev.c
rpmsgdev support blocked read/write operation.
old code: if open device with blocked mode, the server rptun thread will blocked in read/write operation.
new code: open device with nonblocked mode by default and using poll to simulate the blocked read/write operation.
rpmsgdev
sim:rpserver and sim:rpproxy
=> rpmsgdev: support blocked read/write operation

drivers/motor/foc/foc_dummy.c
drivers/motor/foc/foc_dummy.c: remove unused variable
CI
=> drivers/motor/foc/foc_dummy.c: remove unused variable

arch/arm64/src/common/arm64_blocktask.c, arch/arm64/src/common/arm64_exit.c, arch/arm64/src/common/arm64_releasepending.c, arch/arm64/src/common/arm64_reprioritizertr.c, arch/arm64/src/common/arm64_syscall.c, arch/arm64/src/common/arm64_unblocktask.c
See the discussion here: https://github.com/apache/incubator-nuttx/pull/7599
Code refactor
Pass CI
=> arch/arm64: Move group_addrenv to arm64_syscall_switch

arch/arm/src/stm32f0l0g0/stm32_serial_v2.c, arch/arm/src/stm32f0l0g0/stm32_spi.c, arch/arm/src/stm32f0l0g0/stm32_tim_lowerhalf.c, arch/arm/src/stm32f7/stm32_qencoder.c, arch/arm/src/stm32h7/stm32_serial.c, arch/arm/src/stm32l4/stm32l4_dfumode.c, arch/arm/src/stm32l4/stm32l4_pwr.c, arch/arm/src/stm32l5/stm32l562xx_rcc.c, arch/arm/src/stm32l5/stm32l5_pwr.c, boards/arm/stm32/hymini-stm32v/src/stm32_r61505u.c, boards/arm/stm32/hymini-stm32v/src/stm32_ssd1289.c, boards/arm/stm32/olimex-stm32-p407/src/stm32_sram.c, boards/arm/stm32/photon/src/dfu_signature.c, boards/arm/stm32/stm3220g-eval/src/stm32_selectsram.c, boards/arm/stm32/stm3240g-eval/src/stm32_selectsram.c, boards/arm/stm32/viewtool-stm32f107/src/stm32_ssd1289.c, drivers/audio/wm8994.c, drivers/sensors/mpu60x0.c
Found by https://github.com/apache/incubator-nuttx/pull/7391
Minor
Pass CI
=> Fix the clang warning

arch/arm/src/gd32f4/gd32f4xx_gpio.c, arch/arm/src/stm32u5/stm32_serial.c, arch/arm/src/stm32wl5/stm32wl5_serial.c, boards/arm/gd32f4/gd32f450zk-eval/src/gd32f4xx_buttons.c, boards/arm/gd32f4/gd32f450zk-eval/src/gd32f4xx_gpio.c, boards/arm/s32k1xx/rddrone-bms772/src/s32k1xx_smbus_sbd.c, boards/risc-v/esp32c3/esp32c3-devkit-rust-1/src/esp32c3_apds9960.c, boards/xtensa/esp32s3/esp32s3-devkit/src/esp32s3_djoystick.c
boards: enter/leave critical section should in pairs
N/A
ci-check
=> boards: enter/leave critical section should in pairs

include/pthread.h, libs/libc/pthread/pthread_attr_getstack.c, libs/libc/pthread/pthread_attr_setstack.c
follow the standard prototype:
https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_attr_getstack.html
Minor
Pass CI
=> phtread: Change stacksize type from long to size_t

boards/arm/stm32/hymini-stm32v/src/stm32_r61505u.c, boards/arm/stm32/hymini-stm32v/src/stm32_ssd1289.c, boards/arm/stm32/viewtool-stm32f107/src/stm32_ssd1289.c, boards/arm/stm32f7/stm32f746g-disco/src/stm32_wm8994.c
Report here: https://github.com/apache/incubator-nuttx/pull/7391
Minor
Pass CI
=> Fix warning find by clang

mm/mm_heap/mm_size2ndx.c
using flsl to calculate the ndx.
mm
nucleo-144:f746 mm pass
sim:nsh mm pass
=> mm_size2ndx: using flsl to calculate the ndx

net/local/local_sockif.c
support FIONWRITE for domain socket ioctl
domain socket
sim
=> net/local: support FIONWRITE for domain socket ioctl

net/can/can_recvmsg.c, net/can/can_sendmsg.c, net/rpmsg/rpmsg_sockif.c, net/socket/net_sendfile.c, net/socket/socket.h, net/tcp/tcp_accept.c, net/tcp/tcp_monitor.c, net/tcp/tcp_netpoll.c, net/tcp/tcp_send_unbuffered.c, net/tcp/tcp_sendfile.c, net/udp/udp_sendto_unbuffered.c
net: remove psock reference from connect
N/A
ci check
=> net: remove psock reference from connect

tools/ci/testrun/script/test_example/test_example.py
Signed-off-by: nietingting <nietingting@xiaomi.com>
update usrsocktest expect value to "FAILED:0" 
ci 
test on local
=> test: update usrsocktest script

include/nuttx/streams.h
- libc/streams: Ensure the different stream type has the common layout 
- libc/streams: Add lib_[si]gets_t callback 
The real implementation will provide in the next
Minor, new callback
Pass CI
=> Minor stream interface improvement

drivers/syslog/Make.defs, drivers/syslog/syslog.h, drivers/syslog/vsyslog.c, include/nuttx/streams.h, include/nuttx/syslog/syslog.h, libs/libc/stream/Make.defs, libs/libc/stream/lib_syslogstream.c
Continue the work: https://github.com/apache/incubator-nuttx/pull/4992
internal test
=> syslog: Move syslog stream to libc like other stream implementation

fs/vfs/fs_epoll.c
bug fix: should consider the teardown list in EPOLL_CTL_ADD and EPOLL_CTL_MOD operation too.
epoll
local test in sim.
=> fs_epoll: [bug fix] EPOLL_CTL_ADD/MOD consider the teardown list too

binfmt/libelf/libelf_coredump.c, include/nuttx/streams.h, libs/libc/hex2bin/lib_hex2bin.c, libs/libc/misc/lib_kbddecode.c, libs/libc/misc/lib_slcddecode.c, libs/libc/stdio/lib_libvscanf.c
Provide simple macros for unified stream read and write interfaces
=> include: unified stream read and write interface

drivers/segger/Make.defs, drivers/segger/stream_rtt.c, include/nuttx/segger/rtt.h
Read and write Segger RTT data through the stream interface
=> drivers/segger: Add Segger RTT stream support

libs/libc/signal/sig_set.c, libs/libc/signal/sig_signal.c
signal: correct the return values for sigset() & signal()
signal
VELA ltp
=> signal: correct the return values

drivers/segger/Kconfig
let segger RTT kconfig sink one level
=> let segger RTT kconfig sink one level

net/local/local_listen.c
local: add net_lock to local_listen
local socket
VELA
=> local: add net_lock to local_listen

include/nuttx/mm/iob.h, mm/iob/Make.defs, mm/iob/iob_reserve.c, mm/iob/iob_update_pktlen.c
mm/iob: new function iob_reserve() to adjust headroom offset
mm/iob: new function iob_update_pktlen() to update packet length of the iob
N/A
CI-check
=> mm/iob: new function iob_reserve() to adjust headroom offset

drivers/input/touchscreen_upper.c
Add missing function code comments.
None.
None.
=> drivers/input/touchscreen_upper: add missing function code comments

arch/arm/src/sama5/sam_adc.c, arch/arm/src/sama5/sam_tsd.c
Late feedback on PR #7702
none
none
=> Style changes for sam_adc.c and sam_tsd.c

arch/arm/src/s32k3xx/hardware/s32k3xx_edma.h, arch/arm/src/s32k3xx/s32k3xx_edma.c, arch/arm/src/s32k3xx/s32k3xx_edma.h
Cleaned up s32k3xx EDMA. Added looping and Error handling
Correct performance and error termination
PX4 nxp_mr-canhubk3_fmu
=> s32k3xx EDMA add looping and Error handling

drivers/video/video.c, include/nuttx/video/video.h, include/sys/videoio.h
Added missing ioctls and rearrange them according to Linux standard.
Currently no impact
=> drivers/video: enhance v4l2 compatibility

arch/arm/src/armv7-r/arm_initialstate.c, arch/arm/src/armv7-r/arm_schedulesigaction.c, libs/libc/machine/arm/armv7-r/arch_elf.c
arm/cortex-r: sync ARM_THUMB support from cortex-a
N/A
ci-check
=> arm/cortex-r: sync ARM_THUMB support from cortex-a

arch/arm/src/arm/arm_initialstate.c, arch/arm/src/arm/arm_schedulesigaction.c, libs/libc/machine/arm/arm/arch_elf.c
arm/arm: sync ARM_THUMB support from cortex-a
N/A
ci-check
=> arm/arm: sync ARM_THUMB support from cortex-a

net/devif/devif_poll.c
net/devif: reprepare iob buffer before polling connections
Loopback device will consume the d_iob packet in upper layer protocol,
in order to avoid null pointer access, reprepare iob buffer before polling connections
N/A
icmp loopback test
=> net/devif: reprepare iob buffer before polling connections

include/hex2bin.h
=> libc/hex2bin: Remove the unused declaration

arch/sim/src/Makefile, arch/sim/src/sim/posix/sim_alsa.c, arch/sim/src/sim/posix/sim_hosthcisocket.c, arch/sim/src/sim/posix/sim_hostmemory.c, arch/sim/src/sim/posix/sim_hostmisc.c, arch/sim/src/sim/posix/sim_hostsmp.c, arch/sim/src/sim/posix/sim_hosttime.c, arch/sim/src/sim/posix/sim_hostusrsock.c, arch/sim/src/sim/posix/vpnkit/sim_negotiate.c, arch/sim/src/sim/posix/vpnkit/sim_protocol.c, arch/sim/src/sim/posix/vpnkit/sim_protocol.h, arch/sim/src/sim/sim_assert.c, arch/sim/src/sim/sim_backtrace.c, arch/sim/src/sim/sim_hcisocket.c, arch/sim/src/sim/sim_head.c, arch/sim/src/sim/sim_heap.c, arch/sim/src/sim/sim_hosthcisocket.h, arch/sim/src/sim/sim_hostusrsock.h, arch/sim/src/sim/sim_initialize.c, arch/sim/src/sim/sim_internal.h, arch/sim/src/sim/sim_oneshot.c, arch/sim/src/sim/sim_rptun.c, arch/sim/src/sim/sim_rtc.c, arch/sim/src/sim/sim_smpsignal.c, arch/sim/src/sim/sim_usrsock.c, arch/sim/src/sim/win/sim_hostmemory.c, arch/sim/src/sim/win/sim_hostmisc.c, arch/sim/src/sim/win/sim_hosttime.c, arch/sim/src/sim/win/sim_wpcap.c
- arch/sim: Move host files to the correct location 
- arch/sim: Change sim_host_ prefix to host_
- arch/sim: Change usrsock_host_ prefix to host_usrsock_ 
Code refactor only
Pass CI
=> arch/sim: Make the naming consistent with each other

net/ipforward/ipfwd_dropstats.c, net/ipforward/ipv6_forward.c
net/ipforward: update IP buffer offset
N/A
ci-check
=> net/ipforward: update IP buffer offset 

arch/xtensa/src/esp32/hardware/esp32_soc.h
Optimizes and fixes potential buffer overflow introduced by #7790. Sorry about that 😓 
Avoids buffer overflow.
CI build pass and local testing.
=> arch/xtensa/esp32: Optimize macro and ensure overwrite protection

arch/arm/src/sama5/sam_adc.c, arch/arm/src/sama5/sam_tc.c, arch/arm/src/sama5/sam_tsd.c
The feedback is still coming!
In double checking it all, I found an error in sam_tc.c as (perhaps some other change meant) "int ret" had not been declared.
None
Re run my SAMA5D2 board TSD and ADC tests
Leaving as a draft as I expect more things will be found.
=> SAMA5D2 TDC, ADC and TC Corrections

net/can/can_sendmsg.c, net/devif/devif_cansend.c, net/devif/devif_iobsend.c, net/devif/devif_pktsend.c, net/devif/devif_send.c, net/pkt/pkt_sendmsg.c, net/tcp/tcp_send_buffered.c, net/tcp/tcp_send_unbuffered.c, net/udp/udp_sendto_unbuffered.c
net/devif_send: replace all block send to nonblock mode
N/A
iperf test
=> net/devif_send: replace all block send to nonblock mode

include/nuttx/net/ioctl.h, net/netdev/netdev_ioctl.c
Follow LinuxOS:linux-5.10.152\include\uapi\linux\sockios.h 
Add SIOCSIFMTU and SIOCSIFNAME
No
Selftest
=> Add mtu set and interface name set in ioctl

include/net/if.h, include/nuttx/fs/ioctl.h, include/nuttx/net/ioctl.h, include/nuttx/wireless/cellular/cellular.h, net/netdev/netdev_ioctl.c
Add SIOCGCELLNETDEV
Give a uint8_t[136] for cellular to save data
No
Selftest
=> Adjust ioctl function of cellular

drivers/note/notelog_driver.c
Most of them are duplicated, making them call common functions for simplification
=> drivers/note: unify spinlock related functions

.github/workflows/build.yml, tools/ci/cibuild.sh
=> Fix ccache: error: Could not find compiler "x86_64-elf-gcc" in PATH

Documentation/platforms/arm/a64/boards/pinephone/index.rst, Documentation/quickstart/install.rst, tools/checkrelease.sh
Follow up https://github.com/apache/nuttx/pull/7863
Minor
Pass CI
=> Remove incubat.* from the code base

tools/ci/docker/linux/Dockerfile
=> tools/ci/docker/linux/Dockerfile: add libv4l-dev

net/arp/arp.h, net/arp/arp_out.c, net/arp/arp_send.c, net/arp/arp_table.c, net/netdev/netdev_ioctl.c, net/netlink/netlink_route.c
=> arp rules bind to nics

sched/sched/sched_addprioritized.c, sched/sched/sched_addreadytorun.c, sched/sched/sched_mergepending.c, sched/sched/sched_removereadytorun.c, sched/sched/sched_setpriority.c, sched/semaphore/sem_holder.c, sched/signal/sig_default.c, sched/task/task_delete.c, sched/wqueue/kwork_thread.c
- Remove unnecessary type cast
- Fix code style issues
None
Pass CI
=> sched: remove unnecessary type cast

arch/arm/src/lpc54xx/lpc54_ethernet.c, arch/arm/src/sam34/sam_crypto.c, arch/arm/src/tiva/lm/lm3s_ethernet.c, arch/renesas/src/common/renesas_allocateheap.c, arch/renesas/src/common/renesas_createstack.c, arch/renesas/src/common/renesas_exit.c, arch/renesas/src/common/renesas_releasestack.c, arch/renesas/src/common/renesas_stackframe.c, arch/renesas/src/m16c/m16c_dumpstate.c, arch/renesas/src/m16c/m16c_initialstate.c, arch/renesas/src/rx65n/rx65n_dtc.h, arch/renesas/src/rx65n/rx65n_dumpstate.c, arch/renesas/src/rx65n/rx65n_eth.c, arch/renesas/src/rx65n/rx65n_riic.c, arch/renesas/src/rx65n/rx65n_riic.h, arch/renesas/src/rx65n/rx65n_rspi.c, arch/renesas/src/rx65n/rx65n_rspi.h, arch/renesas/src/rx65n/rx65n_rspi_sw.c, arch/renesas/src/rx65n/rx65n_rtc.c, arch/renesas/src/rx65n/rx65n_rtc.h, arch/renesas/src/rx65n/rx65n_rtc_lowerhalf.c, arch/renesas/src/rx65n/rx65n_sbram.c, arch/renesas/src/rx65n/rx65n_serial.c, arch/renesas/src/rx65n/rx65n_usbdev.c, arch/renesas/src/rx65n/rx65n_usbhost.c, arch/renesas/src/rx65n/rx65n_usbhost.h, arch/renesas/src/sh1/sh1_dumpstate.c, arch/renesas/src/sh1/sh1_serial.c
Remove FAR  from ARM and Renesas files.
Apply code formatting
None
Pass CI
=> Remove FAR and apply formatting

sched/sched/sched_releasetcb.c
Fix style issue from here: #7877
=> sched/sched_releasetcb: Fix code style issue from prior patch

drivers/wireless/ieee802154/mrf24j40/mrf24j40_interrupt.c, drivers/wireless/ieee802154/xbee/xbee.c, drivers/wireless/spirit/drivers/spirit_netdev.c, libs/libc/stream/lib_syslogstream.c, net/sixlowpan/sixlowpan_framelist.c, wireless/ieee802154/mac802154.c, wireless/ieee802154/mac802154_assoc.c, wireless/ieee802154/mac802154_device.c
mm/iob: iob members are initialized after allocate 
N/A
ci-check
=> mm/iob: iob members are initialized after allocate 

drivers/note/note_driver.c, drivers/note/notelog_driver.c, include/nuttx/sched_note.h, sched/Kconfig, sched/irq/irq_csection.c, sched/semaphore/spinlock.c
replace all sched_note_spinxxx with sched_note_spincommon
=> merge sched_note_spinxxx 

drivers/note/note_driver.c, include/nuttx/sched_note.h
improve the speed
Minor
Pass CI
=> sched/note: Change sched_note_[begin|end] to macro

arch/arm/src/lc823450/lc823450_start.c, arch/arm/src/sam34/sam_start.c, arch/arm/src/samv7/sam_start.c, arch/arm/src/stm32f7/stm32_start.c, arch/arm/src/stm32h7/stm32_start.c
Fix typos in start files
None
Pass CI
=> arch/arm: fix typos in start files

include/nuttx/compiler.h, include/nuttx/mm/mm.h, include/stdio.h, include/stdlib.h, include/string.h
and compiler.h: Add fopen_like and popen_like macro 
malloc related functions
Pass CI
=> compiler.h: Add malloc_likex and realloc_like macro

Documentation/contributing/making-changes.rst
Explain how to rebase and squash PR's commits
It will be easier to new contributors understand how to squash the commits
N/A
=> Doc: Explain how to rebase and squash PR's commits

arch/arm/src/imxrt/imxrt_serial.c
oflow and iflow was swapped 
Most likley nothing if both were on
inspection
=> imxrt:serial:Fix selection of RTS to iflow

arch/arm/src/s32k1xx/s32k1xx_serial.c
oflow and iflow was swapped 
Most likley nothing if both were on
inspection
=> s32k1xx:serial:Fix selection of RTS to iflow

sched/semaphore/sem_post.c, sched/semaphore/sem_wait.c
Check sem flags before enable priority inheritance
NA
sabre-6quad:nsh
=> sched/semaphore: check sem flags before enable priority inheritance

arch/sim/src/sim/posix/sim_alsa.c, arch/sim/src/sim/posix/sim_hostmisc.c
sim: don't let switch out when do poweroff & alsa mixer open
sim
VELA
=> sim: don't let switch out when do poweroff & alsa mixer open

arch/arm/src/s32k3xx/Kconfig, arch/arm/src/s32k3xx/s32k3xx_lowputc.c, arch/arm/src/s32k3xx/s32k3xx_serial.c, arch/arm/src/s32k3xx/s32k3xx_serial.h
Adds DMA support for LPUART0-15
Better performance. 
PX4 nxp_mr-canhubk3_fmu
=> s32k3xx:Serial add DMA

drivers/video/fb.c, include/nuttx/video/fb.h
add struct fix_screeninfo and var_screeninfo, and related ioctl, macro.
Signed-off-by: jihandong <jihandong@xiaomi.com>
=> driver/fb: support linux info.

arch/sim/src/sim/posix/sim_hostuart.c, arch/sim/src/sim/sim_internal.h, arch/sim/src/sim/sim_uart.c, arch/sim/src/sim/win/sim_hostuart.c
sim_uart: fix printf error when use irq mode
sim printf
VELA
=> sim_uart: fix printf error when use irq mode

drivers/net/tun.c, include/nuttx/net/ioctl.h
Signed-off-by: zhanghongyu <zhanghongyu@xiaomi.com>
=> tun: add ioctl cmd TUNGETIFF implement

tools/minidumpserver.py
update the minidumpserver script after PR #7875
minidumpserver
vela
=> minidumpserver: sync the stackdump search string after #7875

Documentation/reference/os/iob.rst, include/nuttx/mm/iob.h, mm/iob/Make.defs, mm/iob/iob_count.c
new iob function
minor
iperf test on qemu-armv8a/netnsh
=> mm/iob: add a helper function to get iob count in chain

arch/arm/src/samv7/sam_mcan.c
While working on MCAN support for SAMA5D2 found these errors for SAMV7
Fix things
NONE - I don't have a suitable board, but I think this are hopefully obvious errors.
=> Update SAMV7 sam_mcan.c

arch/arm/src/phy62xx/log.h, arch/risc-v/src/bl602/bl602_os_hal.h, arch/risc-v/src/esp32c3/esp32c3_start.c, arch/risc-v/src/esp32c3/esp32c3_wifi_adapter.c, arch/xtensa/src/esp32/esp32_start.c, arch/xtensa/src/esp32/esp32_wifi_adapter.c, arch/xtensa/src/esp32/esp32_wireless.h, arch/xtensa/src/esp32s2/esp32s2_start.c, fs/mount/fs_procfs_mount.c, include/debug.h, include/err.h, include/libintl.h, include/nuttx/compiler.h, include/nuttx/fs/procfs.h, include/nuttx/sched_note.h, include/nuttx/streams.h, include/nuttx/usb/usbdev_trace.h, include/obstack.h, include/stdio.h, include/syslog.h, include/time.h, libs/libc/stdio/lib_libvsprintf.c, net/procfs/net_procfs_route.c, sched/Kconfig
align with other macro naming style, need merge with https://github.com/apache/nuttx-apps/pull/1461
format specifier
local
=> compiler.h: Add _ between format|printf|syslog|scanf|strftime and like

arch/xtensa/src/esp32s3/esp32s3_start.c, include/debug.h, include/err.h, include/nuttx/note/note_driver.h, include/nuttx/usb/usbdev_trace.h, libs/libc/misc/lib_debug.c
Add some missing `FAR`
Improvement
Pass CI
=> nuttx: add some missing FAR

arch/arm/src/lpc17xx_40xx/lpc17_40_can.c
The SocketCAN driver expects a FIFO behaviour yet LPC17_40 didn't enforce this.
This changes enables prioritization on transmit function to enforce this.
Fix transmit behaviour
Tested on a LPC1768
=> LPC17_40 CAN driver SocketCAN enforce TX fifo behaviour

sched/misc/assert.c
Instantiate the correct address environment when reading the process's argument vector. Otherwise doing this will crash the system every time, causing a recursive assert loop.
Also try to do a bit of sanity checking before attempting to read the process's memory, it might be in a bad state in which case this will fail anyway.
Fixes a recursive assert loop, when address environments are in use
icicle:knsh
=> sched/assert: Fix printing argv when address environments are in use

Documentation/guides/simulator.rst
Fix ping to external IP on simulator
Help users to get the network working in the simulator
SIM
=> Doc: Fix ping to external IP on simulator

arch/arm/src/s32k3xx/Kconfig, arch/arm/src/s32k3xx/s32k3xx_emac.c, arch/arm/src/s32k3xx/s32k3xx_flexcan.c
S32K3XX EMAC Driver add MDIO and TJA1103 Phy support
Minimal
Tested with netinit for phy link status
=> S32K3XX PHY MII/MMD support and TJA1103 support

tools/ci/cibuild.sh
Fix MAC OS CI errors
MAC OS CI works with no errors
Pass CI
=> tools: Ensure removing Python related commands for macOS

libs/libc/netdb/lib_gethostentbynamer.c, mm/mempool/mempool_multiple.c, mm/mm_heap/mm_mallinfo.c
Suppress -Wsign-compare warning on a few places
=> Suppress -Wsign-compare warning on a few places

arch/z16/src/common/z16_registerdump.c, arch/z80/src/ez80/ez80_registerdump.c, arch/z80/src/z180/z180_registerdump.c, arch/z80/src/z80/z80_registerdump.c
Add volatile for regs in up_dump_register function
NA
CI
=> arch: add volatile for regs in up_dump_register function

net/inet/ipv4_setsockopt.c
Signed-off-by: zhanghongyu <zhanghongyu@xiaomi.com>
=> net: Separate IP_PKTINFO from NET_IGMP

sched/misc/Make.defs, sched/misc/panic_notifier.c
=> sched/misc: Rename panic.c to panic_notifier.c

Documentation/platforms/risc-v/esp32c3/boards/esp32c3-devkit/index.rst
Add documentation about using BLE on ESP32-C3
Users will be able to test BLE on ESP32-C3
esp32c3-devkit
=> Doc: Add documentation about using BLE on ESP32-C3

include/signal.h, include/string.h
1. support strdupa and strndupa api.
2. support sigisemptyset, sigandset, sigorset api.
support new api
local test.
=> Add new api for signal and string

drivers/note/Make.defs, drivers/note/note_driver.c, drivers/note/note_initialize.c, drivers/segger/Kconfig, drivers/segger/Make.defs, drivers/segger/config/SEGGER_SYSVIEW_Conf.h, drivers/segger/note_sysview.c, drivers/segger/sysview.c, include/nuttx/note/note_driver.h, include/nuttx/segger/sysview.h
register sysview to note drivers list
still only one note driver can be used
multi-channel functionality needs to wait for sysview changes to complete
sim:note
=> register sysview to note drivers list

arch/arm/include/armv7-m/irq.h, arch/arm/include/armv8-m/irq.h
add faultmask register operation to armv7-m & armv8-m
nothing
vela
=> arch:add faultmask register operation to armv7-m & armv8-m

include/netinet/arp.h, include/netpacket/netlink.h, libs/libc/net/Make.defs, libs/libc/net/lib_inetnetwork.c
=> net: add some network-related definitions

arch/xtensa/src/esp32/Kconfig, arch/xtensa/src/esp32/esp32_wlan.c
xtensa/esp32: Optimize WLAN device buffer
Use malloc buffer to save memory
=> xtensa/esp32: Optimize WLAN device buffer

fs/vfs/fs_timerfd.c
Report here: https://github.com/apache/nuttx/pull/8032/files#r1063246453
Minor
Pass CI
=> fs/timerfd: Reverse truncate and mmap field

mm/mm_heap/mm.h, mm/mm_heap/mm_extend.c, mm/mm_heap/mm_foreach.c, mm/mm_heap/mm_free.c, mm/mm_heap/mm_memalign.c, mm/mm_heap/mm_shrinkchunk.c
- mm/heap: Changee mmchunk_handler_t to mm_node_handler_t 
- mm/heap: Skip memset backtrace buffer 
- mm/heap: Fix the minor style issue
heap
internal test
=> Minor heap fix

drivers/wireless/bluetooth/bt_bridge.c, include/nuttx/net/snoop.h, net/utils/Kconfig, net/utils/net_snoop.c
Signed-off-by: chengkai <chengkai@xiaomi.com>
add bt bridge snoop 
none
pass
=> wireless/bluetooth: add interrupt_context hander for netsnoop

arch/risc-v/src/esp32c3/esp32c3_wlan.c
risc-v/esp32c3: correct receive buffer size
1. correct receive buffer size, d_len should keep the l2 header size
2. fix race condition issue of de/enqueue rx queue
N/A
esp32c3 iperf server/client test
=> risc-v/esp32c3: correct receive buffer size

ReleaseNotes
This is a local copy taken from the confluence notes https://cwiki.apache.org/confluence/display/NUTTX/NuttX+12.0.0
RELEASE
NONE
=> documentation: Add release notes for 12.0.0 release

net/mld/Kconfig, net/mld/mld_group.c, net/mld/mld_join.c, net/mld/mld_query.c, net/mld/mld_report.c, net/mld/mld_send.c
net/mld: fix build break of mld router
N/A
basic v6 mld test
=> net/mld: fix build break of mld router

drivers/usrsock/usrsock_rpmsg_server.c, drivers/video/vnc/vnc_server.c, include/nuttx/net/net.h, include/sys/socket.h, include/sys/syscall_lookup.h, net/inet/inet_sockif.c, net/socket/accept.c, syscall/syscall.csv
specified here: https://linux.die.net/man/2/accept4
new API
internal product
=> net_socket: Add an implementation of the accept4 method

include/nuttx/mutex.h, include/semaphore.h, libs/libc/semaphore/sem_getprotocol.c, sched/semaphore/sem_holder.c, sched/semaphore/sem_post.c, sched/semaphore/sem_setprotocol.c, sched/semaphore/sem_wait.c
and refine the code to prepare the support of new flags, which is required by https://github.com/apache/nuttx/pull/7426.
Pass CI
=> sem: Remove PRIOINHERIT_FLAGS_ENABLE and use SEM_PRIO_INHERIT instead

net/local/local_fifo.c
This is the next step of https://github.com/apache/nuttx/pull/8052
When local udp socket is used, this threshold will avoid non-blocking read failed with -EAGAIN when only preamble len is sent and read by reader. To do so, local udp socket should set threshold to be sizeof preamble len.
Local udp socket only
Tested on ESP32C3 after removing some #warning macro in local udp socket
=> net/local:set POLLIN/POLLOUT threshold for local fifo

arch/sim/src/sim/posix/sim_linuxspi.c
Fixed missing `SPI_SELECT` method and incorrect sending behavior in sim_linuxspi
N/A
N/A
=> sim/posix/sim_linuxspi.c: fix select not work and incorrect behaviour

boards/sim/sim/sim/README.txt
follow up https://github.com/apache/nuttx/pull/8022
Document
=> boards/sim: Update usrsock related stuff in README.txt

libs/libc/stdlib/lib_strtold.c
I accidentally changed it when I was optimizing the code
fix some bug
=> fix the some else bug of strtold

drivers/video/mipidsi/mipi_dsi_device_driver.c
Signed-off-by: liushuai25 <liushuai25@xiaomi.com>
Fix scope issues with "switch ... case"
=> Fix scope issues with "switch ... case"

include/dirent.h, include/string.h, libs/libc/dirent/Make.defs, libs/libc/dirent/lib_versionsort.c, libs/libc/string/Make.defs, libs/libc/string/lib_strverscmp.c
libc/versionsort: support versionsort and strverscmp
Signed-off-by: dongjiuzhu1 <dongjiuzhu1@xiaomi.com>
support new api  versionsort and strverscmp
daily test.
=> libc/versionsort: support versionsort and strverscmp

libs/libc/stdlib/lib_strtold.c
=> Fixbug strtold

crypto/cryptodev.c
add read & write function to crypto
crypto
vela
=> crypto:add read & write function aviod check flag failed

arch/xtensa/src/esp32/esp32_partition.c, arch/xtensa/src/esp32/esp32_partition.h
Partition device supports encryption mode.
=> xtensa/esp32: Partition device supports encryption mode

arch/arm/src/common/Toolchain.defs, arch/arm64/src/Toolchain.defs, arch/avr/src/avr/Toolchain.defs, arch/avr/src/avr32/Toolchain.defs, arch/mips/src/mips32/Toolchain.defs, arch/misoc/src/lm32/Toolchain.defs, arch/or1k/src/mor1kx/Toolchain.defs, arch/risc-v/src/common/Toolchain.defs, arch/sparc/src/sparc_v8/Toolchain.defs, arch/xtensa/src/lx6/Toolchain.defs, arch/xtensa/src/lx7/Toolchain.defs, boards/sim/sim/sim/scripts/Make.defs, libs/libxx/Kconfig, libs/libxx/libcxx.defs
and default to "c++17"
New compiler flag for c++
Pass CI
=> libxx: Add CXX_STANDARD to select -std=c++??

drivers/power/pm/activity_governor.c, drivers/power/pm/greedy_governor.c, drivers/power/pm/pm.h, drivers/power/pm/pm_activity.c, drivers/power/pm/pm_autoupdate.c, drivers/power/pm/pm_changestate.c, drivers/power/pm/pm_initialize.c, drivers/power/pm/pm_lock.c, drivers/power/pm/pm_procfs.c, drivers/power/pm/pm_register.c, drivers/power/pm/pm_unregister.c
pm: add lock for pm_auto_updatestate_cb()
pm: add pm_domain_lock/unlock support
power: avoid sem_wait called in IRQ handler
power
VELA
=> power related update

tools/minidumpserver.py
minidumpserver: replace stackdump to stack_dump
debug tools: minidumpserver
VELA
=> minidumpserver: replace stackdump to stack_dump

sched/misc/assert.c
crash dump message added
add stack base, add uname info
crash dump message
VELA
=> crash dump message added

net/tcp/tcp_send.c
net/tcp: move drop send source code to correct place
Merge conflicts lead to code being placed in thre wrong place
The debug code should placed in tcp_send() not tcp_synack()
N/A
iperf test
=> net/tcp: move drop send source code to correct place

arch/xtensa/src/esp32/esp32_spi.c, arch/xtensa/src/esp32/esp32_spi_slave.c
1. Fix SPI master/slave clock init/deinit error
2. Fix SPI slave RX process error
=> xtensa/esp32: Fix SPI bugs

arch/risc-v/src/esp32c3/esp32c3_libc_stubs.c, drivers/modem/alt1250/alt1250.c, drivers/usrsock/usrsock_dev.c, include/nuttx/modem/alt1250.h, include/nuttx/mutex.h, include/nuttx/net/net.h, include/nuttx/semaphore.h, include/semaphore.h, libs/libc/semaphore/sem_getprotocol.c, libs/libc/semaphore/sem_init.c, libs/libc/wqueue/work_usrthread.c, net/usrsock/usrsock_devif.c, net/utils/net_lock.c
=> Revert "add holder for mutex"

include/dirent.h
and map DTYPE_xxx to DT_xxx like other OS
no real change
Pass CI
=> fs: Define DT_xxx to number directly

boards/risc-v/esp32c3/common/scripts/esp32c3_rom.ld, boards/risc-v/esp32c3/common/scripts/flat_memory.ld, boards/risc-v/esp32c3/common/scripts/kernel-space.ld, boards/risc-v/esp32c3/common/scripts/user-space.ld, boards/xtensa/esp32/common/scripts/esp32_rom.ld, boards/xtensa/esp32/esp32-devkitc/src/Make.defs, boards/xtensa/esp32/esp32-ethernet-kit/src/Make.defs, boards/xtensa/esp32/esp32-lyrat/src/Make.defs, boards/xtensa/esp32/esp32-sparrow-kit/src/Make.defs, boards/xtensa/esp32/esp32-wrover-kit/src/Make.defs, boards/xtensa/esp32/lilygo_tbeam_lora_gps/src/Make.defs, boards/xtensa/esp32/ttgo_eink5_v2/src/Make.defs, boards/xtensa/esp32/ttgo_lora_esp32/src/Make.defs, boards/xtensa/esp32/ttgo_t_display_esp32/src/Make.defs, boards/xtensa/esp32s2/common/scripts/esp32s2_peripherals.ld, boards/xtensa/esp32s2/common/scripts/esp32s2_rom.ld, boards/xtensa/esp32s2/common/scripts/flat_memory.ld, boards/xtensa/esp32s2/common/scripts/legacy_sections.ld, boards/xtensa/esp32s3/common/scripts/esp32s3_peripherals.ld, boards/xtensa/esp32s3/common/scripts/esp32s3_rom.ld, boards/xtensa/esp32s3/common/scripts/flat_memory.ld, boards/xtensa/esp32s3/common/scripts/legacy_sections.ld, boards/xtensa/esp32s3/common/scripts/mcuboot_sections.ld
This PR brings some changes to Makefiles and Linker Scripts for cleaning up and synchronizing documentation across Espressif's chips.
No changes to source code, no impact expected.
CI build pass to validate removal of Makefile variable.
=> Espressif: Clean ups and minor fixes to comments 

.gitignore, Kconfig, arch/arm/src/common/Toolchain.defs, arch/risc-v/src/common/Toolchain.defs, arch/xtensa/src/lx6/Toolchain.defs, arch/xtensa/src/lx7/Toolchain.defs, boards/sim/sim/sim/scripts/Make.defs, tools/showstack.sh
https://github.com/HBehrens/puncover can give the graph report.
New optiion
Pass CI
=> build: Add STACK_USAGE(-fstack-usage) to assist the stack analysis

arch/xtensa/src/esp32s3/Kconfig, arch/xtensa/src/esp32s3/Make.defs, arch/xtensa/src/esp32s3/esp32s3_efuse.c, arch/xtensa/src/esp32s3/esp32s3_efuse.h, arch/xtensa/src/esp32s3/esp32s3_efuse_lowerhalf.c, arch/xtensa/src/esp32s3/esp32s3_efuse_table.c, boards/xtensa/esp32s3/esp32s3-devkit/src/esp32s3_bringup.c
Add support to efuse
User will be able to use efuse
esp32-s3-devkit
=> esp32s3: Add support to efuse

arch/xtensa/src/esp32s2/Kconfig, arch/xtensa/src/esp32s2/Make.defs, arch/xtensa/src/esp32s2/esp32s2_efuse.c, arch/xtensa/src/esp32s2/esp32s2_efuse.h, arch/xtensa/src/esp32s2/esp32s2_efuse_lowerhalf.c, arch/xtensa/src/esp32s2/esp32s2_efuse_table.c, boards/xtensa/esp32s2/esp32s2-saola-1/src/esp32s2_bringup.c
Add support to efuse
User will be able to use efuse
esp32s2-saola-1
=> esp32s2: Add support to efuse

include/sys/mman.h
https://man7.org/linux/man-pages/man2/madvise.2.html
New macro
Pass CI
=> fs: Map madvice to posix_madvice

include/nuttx/mm/mempool.h, mm/mempool/mempool_multiple.c
=> mm/mempool: Fix the minor style issue

AUTHORS
add Heath Petersen to the AUTHORS file.
NONE
NONE
=> AUTHORS: add Heath Petersen

arch/arm64/src/a64/a64_mipi_dsi.c, arch/arm64/src/a64/a64_mipi_dsi.h, arch/sim/src/sim/sim_heap.c, arch/xtensa/src/esp32/esp32_wlan.c, boards/arm/sama5/jupiter-nano/src/sam_ajoystick.c, boards/arm/sama5/jupiter-nano/src/sam_at25.c, boards/arm/sama5/jupiter-nano/src/sam_bringup.c, boards/arm/sama5/jupiter-nano/src/sam_buttons.c, boards/arm/sama5/jupiter-nano/src/sam_ethernet.c, boards/arm/sama5/jupiter-nano/src/sam_nandflash.c, boards/arm/sama5/jupiter-nano/src/sam_ostest.c, boards/arm/sama5/jupiter-nano/src/sam_sdmmc.c, boards/arm/sama5/jupiter-nano/src/sam_spi.c, boards/arm/sama5/jupiter-nano/src/sam_usb.c, boards/arm64/a64/pinephone/src/pinephone_touch.c, boards/renesas/rx65n/rx65n-grrose/src/rx65n_bringup.c, boards/renesas/rx65n/rx65n-grrose/src/rx65n_sbram.c, boards/renesas/rx65n/rx65n-rsk2mb/src/rx65n_bringup.c, boards/renesas/rx65n/rx65n-rsk2mb/src/rx65n_sbram.c, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_gpio.c, boards/xtensa/esp32/common/src/esp32_es8388.c
=> board/arch: Remove FAR decorator

boards/arm/cxd56xx/common/src/cxd56_crashdump.c, boards/arm/stm32/nucleo-f429zi/src/stm32_bbsram.c, boards/arm/stm32f7/nucleo-144/src/stm32_bbsram.c, boards/renesas/rx65n/rx65n-grrose/src/rx65n_sbram.c, boards/renesas/rx65n/rx65n-rsk2mb/src/rx65n_sbram.c, include/nuttx/board.h, sched/misc/assert.c
continue the follow work(https://github.com/apache/nuttx/pull/8213):
```
commit 43e7b13697195c37166de09e508b71fe6cbb424a
Author: Xiang Xiao <xiaoxiang@xiaomi.com>
Date:   Sun Jan 22 19:31:32 2023 +0800
assert: Log the assertion expression in case of fail
```
board_crashdump
Pass CI
=> board: Pass the assertion expression to board_crashdump too

drivers/serial/serial.c, sched/init/nx_bringup.c
to share the code with the code path of posix_spawn
code refactor
Pass CI
=> Launch the initial task through task_spawn instead of nxtask_create

arch/arm/src/cxd56xx/cxd56_timer.c, arch/arm/src/imxrt/imxrt_usdhc.c, arch/arm/src/nrf52/nrf52_radio.c, arch/arm/src/sama5/sam_sdmmc.c, arch/arm/src/stm32h7/stm32_dma.c, arch/risc-v/src/c906/c906_irq.c, arch/risc-v/src/esp32c3/esp32c3_rtc.c, arch/risc-v/src/fe310/fe310_clockconfig.c, arch/risc-v/src/fe310/fe310_irq.c, arch/risc-v/src/k210/k210_irq.c, arch/risc-v/src/litex/litex_irq.c, arch/risc-v/src/mpfs/mpfs_irq.c, arch/risc-v/src/qemu-rv/qemu_rv_irq.c, drivers/wireless/gs2200m.c, drivers/wireless/lpwan/sx127x/sx127x.c, libs/libc/machine/risc-v/arch_elf.c
Switch from `ASSERT(0/false)` to `PANIC()`
Code refactoring
Pass CI
=> assert: switch from ASSERT(0/false) to PANIC

arch/xtensa/src/esp32/esp32_spi.c, arch/xtensa/src/esp32s2/esp32s2_spi.c, arch/xtensa/src/esp32s3/esp32s3_spi.c, drivers/mtd/mtd_config.c, drivers/sensors/msa301.c, wireless/ieee802154/mac802154_device.c
Switch from semaphore to mutex for exclusive access
N/A
Pass CI
=> Switch from semaphore to mutex for exclusive access

arch/arm/src/gd32f4/Kconfig, arch/arm/src/stm32/Kconfig, arch/arm/src/tiva/Kconfig, boards/arm/rp2040/common/Kconfig, boards/arm/tiva/tm4c123g-launchpad/src/tm4c_can.c, boards/arm/tiva/tm4c1294-launchpad/src/tm4c_can.c, fs/shm/shm_open.c, fs/shm/shm_unlink.c, fs/shm/shmfs_alloc.c, sched/misc/assert.c
Apply misc fixes in code noticed during code review
N/A
Pass CI
=> nuttx: apply misc fixes in code noticed during code review

include/time.h
see the spec here:
https://pubs.opengroup.org/onlinepubs/000095399/functions/clock_getres.html
new macro
Pass CI
=> time.h: Add CLOCK_PROCESS_CPUTIME_ID and CLOCK_THREAD_CPUTIME_ID definition

boards/renesas/rx65n/rx65n-grrose/include/README.TXT, boards/renesas/rx65n/rx65n-rsk2mb/include/README.TXT, boards/risc-v/esp32c3/esp32c3-devkit/src/README.txt, boards/sim/sim/sim/src/README.txt
continue the change: https://github.com/apache/nuttx/pull/6843
Minor
=> boards: Update Administrator tea result to 8Tv+Hbmr3pLVb5HHZgd26D

arch/arm/Kconfig, arch/arm/src/armv8-m/Toolchain.defs
arm specific Toolchain.defs
Same as before by default
Pass CI
=> arch/arm: make DSP arch extension configurable

drivers/sensors/sensor_rpmsg.c
- driver/sensor: using recursive lock to fix deadlock beacuse rptun reentrancy
- driver/sensor: sync set buffer number to remote proc 
rpmsg sensor
XiaoMi watch
=> Fix sensor bug in production environment

drivers/sensors/fakesensor.c
=> sensors/fakesensor: fix timestamp is woring when batch.

drivers/power/battery/battery_charger.c, include/nuttx/power/battery_charger.h, include/nuttx/power/battery_ioctl.h
report the charging voltage
battery charger
Pass CI
=> charge: add support for voltage infomation

arch/arm/src/Makefile, arch/risc-v/src/Makefile, arch/sim/src/Makefile, arch/xtensa/src/Makefile
Paired with https://github.com/apache/nuttx-apps/pull/1509 to support the external library
build system, but off by default.
Pass CI
=> arch/EXTRA_LIBS: link all staging library

drivers/power/battery/axp202.c, drivers/power/battery/battery_charger.c, include/nuttx/fs/fs.h, include/nuttx/power/battery_charger.h, include/nuttx/power/battery_monitor.h
Add missing `FAR` and `CODE`
N/A
Pass CI
=> nuttx: Add missing FAR and CODE

arch/x86_64/src/intel64/intel64_handlers.c, include/signal.h, sched/Kconfig
- sched: Add SIGFPE, SIGILL and SIGSEGV definition
- signal: add marco _NSIG
new macro
CI
=> sched: Add _NSIG, SIGFPE, SIGILL and SIGSEGV definition

libs/libc/netdb/lib_rexec.c
=> netdb: Add return check in rexec_af

Documentation/platforms/arm/rp2040/boards/waveshare-rp2040-lcd-1.28/index.rst
Missing blank line in waveshare-rp2040-lcd-1.28
=> Doc/rp2040: fix typo

net/tcp/tcp_send_buffered.c
tcp fast retransmit
Xiaomi Watch S1 Pro
=> tcp: fix trans data error when fast retrans

tools/mkdeps.c
- update MAX_SHQUOTE to 4096
- nuttx: increase MAX_BUFFER to 10240 for CI build 
mkdep
CI
=> Extend mkdep buffer

drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.c, include/nuttx/wireless/ieee80211/ieee80211.h
wireless/ieee80211: update ieee80211 header
N/A
ci-check
=> wireless/ieee80211: update ieee80211 header 

mm/mm_heap/mm_malloc.c
Already done in mm_size2ndx
Same as before
CI
=> mm/mm_heap: do this check in mm_size2ndx

libs/libc/spawn/lib_psfa_adddup2.c
=> libc: Add return check in posix_spawn_file_actions_adddup2

net/local/local_connect.c
When using PIPE connect to a file, ENOTSOCK or ECONNREFUSED should be returned and when using PIPE connect to invalid pipe name, ENOENT should be returned in libuv
Minor, error case
libuv test
=> net/local_connect:Align the returned error code with Linux

net/udp/udp_conn.c
dual ipv4/ipv6 stack
Internal testing
=> udp: Ipv4/6 can be bound to the same port

include/netinet/in.h, include/nuttx/net/ip.h, include/nuttx/net/net.h, net/icmp/icmp_reply.c, net/icmp/icmp_sendmsg.c, net/icmpv6/icmpv6_advertise.c, net/icmpv6/icmpv6_radvertise.c, net/icmpv6/icmpv6_reply.c, net/icmpv6/icmpv6_rsolicit.c, net/icmpv6/icmpv6_sendmsg.c, net/icmpv6/icmpv6_solicit.c, net/igmp/igmp_send.c, net/inet/Make.defs, net/inet/inet.h, net/inet/inet_sockif.c, net/inet/ipv4_build_header.c, net/inet/ipv4_setsockopt.c, net/inet/ipv6_build_header.c, net/inet/ipv6_getsockopt.c, net/inet/ipv6_setsockopt.c, net/mld/mld_send.c, net/tcp/tcp.h, net/tcp/tcp_input.c, net/tcp/tcp_send.c, net/udp/udp_send.c
=> support ipv4 ToS and ipv6 TrafficClass

net/tcp/tcp_conn.c, net/udp/udp_conn.c
Behavior alignment to Linux
connect
=> tcp/udp_connect: If the remote addr is ANY, change it to LOOPBACK

include/net/route.h
refs:
https://students.mimuw.edu.pl/SO/Linux/Kod/include/linux/route.h.html https://nxmnpg.lemoda.net/9/rtentry
Pass CI
=> net/route.h: add RTF_XX flags and rt_dev member

net/icmpv6/icmpv6_input.c
to support the different icmpv6 option
icmpv6
sim with ipv6
=> Fix ICMPv6 RA parsing procedure

arch/sim/src/sim/sim_usrsock.c
=> sim: init events field when send ack/dack

include/nuttx/net/dns.h, libs/libc/netdb/lib_dnsquery.c
avoid the unalignment issue
Minor
Pass CI
=> dns: packed dns_header_s and dns_question_s

include/nuttx/audio/audio.h
add AUDIOIOC_SETPARAMTER iotcl command in include/nuttx/audio/audio.h
New IOCTL code
Xiaomi Watch S1 Pro
=> feature:add audio AUDIOIOC_SETPARAMTER ioctl command

include/nuttx/lib/math32.h
New macro for the compile time log computation
CI
=> lib/math32.h: support LOG2_CEIL/LOG2_FLOOR function at compile time

arch/sim/src/sim/posix/sim_x11framebuffer.c, arch/sim/src/sim/sim_framebuffer.c, arch/sim/src/sim/sim_internal.h, arch/sim/src/sim/sim_lcd.c
Fix the initialization issue when enabling host signal.
sim
sim:lvgldemo
=> arch: fix sim_x11events calls but sim_x11initialize() hasn't ready 

net/netdev/netdev_txnotify.c, net/tcp/tcp.h, net/tcp/tcp_appsend.c, net/tcp/tcp_close.c, net/tcp/tcp_devpoll.c, net/tcp/tcp_ipselect.c, net/tcp/tcp_send.c, net/tcp/tcp_send_buffered.c, net/tcp/tcp_send_unbuffered.c, net/tcp/tcp_timer.c
net/tcp: reuse common api to replace some ip select code
N/A
ipv4/v6 iperf test
=> net/tcp: reuse common api to replace some ip select code

arch/risc-v/src/common/Toolchain.defs
=> risc-v/Toolchain.defs: Correct indent

arch/arm/src/cxd56xx/cxd56_cisif.c, arch/sim/src/sim/sim_video.c, drivers/video/isx012.c, drivers/video/isx019.c, drivers/video/video.c, include/nuttx/video/imgdata.h, include/nuttx/video/imgsensor.h
Make video driver model close other driver framework and support the multiple instances from one driver.
video capture
sim:camera and spresense:camera
=> drivers/camera: Support the private data for imgsensor and imgdata

arch/xtensa/src/esp32/esp32_rtc_gpio.c
This PR aims to fix a potential problem with the execution of 2nd level RTC IRQ handlers.
Some drivers might need to re-check the RTC status register. This patch propagates the current status register inside the interruption context.
Nothing is affected by this currently.
Avoids possible problems that might occur in the future.
Tested using the `esp32-lyrat:buttons` defconfig.
=> arch/xtensa/esp32: Propagate RTC IRQ status register to lower levels

tools/ci/docker/linux/Dockerfile
Signed-off-by: qiaohaijiao1 <qiaohaijiao1@xiaomi.com>
add libmp3lame-dev:i386
N/A
N/A
=> tools/ci/docker/linux/Dockerfile: add libmp3lame-dev:i386

fs/mqueue/mq_open.c
- I noticed that sometimes mqueue_test failed with rv-virt:smp.
- SMP only
- Tested with ostest on QEMU-7.1
=> fs: mqueue: Fix file_mq_open() for SMP

libs/libc/stdio/lib_getdelim.c
Correct name in getline's comments.
No
CI
=> libc/stdio: Minor comments fix

boards/arm/sama5/jupiter-nano/Kconfig
arm/sama5/jupiter-nano: correct config name
N/A
ci-check
=> arm/sama5/jupiter-nano: correct config name 

tools/checkpatch.sh
and  check the spell and encoding for rust file too 
checkpatch.sh
CI
=> tools/checkpatch.sh: Check the source code doesn't set executable bit

.github/workflows/check.yml
PR #8379 adds encoding check in `checkpatch.sh`.  
This PR also enables this check in CI.
*Also see [here](https://github.com/apache/nuttx/pull/8379#issuecomment-1412011491).*
Added checks.
CI.
=> Enabled UTF check in CI.

fs/vfs/fs_dup.c, fs/vfs/fs_fcntl.c, include/fcntl.h, include/nuttx/fs/fs.h, include/sys/socket.h, net/local/local_recvmsg.c
https://pubs.opengroup.org/onlinepubs/9699919799/functions/fcntl.html
https://linux.die.net/man/2/recvmsg
new F_DUPFD_CLOEXEC
internal test
=> vfs: Suppoprt F_DUPFD_CLOEXEC

arch/arm/src/tiva/common/tiva_serial.c
This is a follow-up to PR #6548, which added UART CTS/RTS support for Tiva (TI TM4C12x) microcontrollers.
This follow-up makes it possible, when termios support is enabled with `CONFIG_SERIAL_TERMIOS` and CTS/RTS support is enabled with `CONFIG_SERIAL_OFLOWCONTROL` and/or `CONFIG_SERIAL_IFLOWCONTROL`, to query whether CTS/RTS are on/off at runtime by utilizing ioctl `TCGETS` and to turn CTS/RTS on/off at runtime by utilizing ioctl `TCSETS`.
Allow turning CTS/RTS on and off at runtime in the Tiva serial driver.
Custom board.
=> tiva/serial: Allow changing CTS/RTS with termios

tools/parsememdump.py
tools/parsememdump.py
Internal user
=> tools: parsememdump.py support show total pid memory

include/nuttx/spinlock.h, mm/mempool/mempool.c
=> spinlock: Move spinlock_init to public macros

include/nuttx/input/touchscreen.h
=> touch: Add ioctl to enable/disable gesture

fs/procfs/fs_procfscpuload.c
Fix cpu loading on SMP
Pass CI
=> fs/procfs: fix the issue of /proc/cpuload in SMP

include/nuttx/sensors/sensor.h
- fix: sensor: update hall data type 
- sensor: Add the calibration status flag 
- sensor: Enable ambient light sensor report ir strength
- sensor: fix miwear sensor bb
- sensor: Report more gps info
New fields
Pass CI
=> Minor sensor improvement

net/tcp/tcp_input.c
Receiving an ACK indicating TCP Window Update will not set ACKDATA flag (because tx_unacked is 0) in our TCP stack. Then this ACK won't let us send anything after receiving it, even if it updates snd_wnd. So we need to check whether we can send data immediately when our snd_wnd is updated (especially from 0), otherwise we will only send next data after timer expiry.
TCP between two NuttX sim is slow because the TCP stream will stuck frequently once after TCP window is full and wait timer to recover. This patch fixes this.
`iperf` between two `sim:rpserver` with config
```Kconfig
CONFIG_NET_RECV_BUFSIZE=16384  # default size can also trigger, but smaller value is easier
CONFIG_SCHED_TICKLESS=y        # let performance be maximized
```
Without this patch
```
Interval         Transfer …
```
=> net/tcp: Regard snd_wnd update as ACKDATA

arch/sim/src/sim/posix/sim_alsa.c, drivers/lcd/ssd1351.c, fs/partition/fs_gpt.c
Cotinue the work https://github.com/apache/nuttx/pull/8397
Minor
CI
=> Remove the remain MIN/MAX like macro

tools/Config.mk
tools/Config: silent print of archive objects
N/A
Before:
```
$ make -j
AR (add): libapps.a    nsh_init.c.home.archer.code.nuttx.n8.apps.nshlib.o nsh_parse.c.home.archer.code.nuttx.n8.apps.nshlib.o nsh_console.c.home.archer.code.nuttx.n8.apps.nshlib.o nsh_script.c.home.archer.code.nuttx.n8.apps.nshlib.o nsh_system.c.home.archer.code.nuttx.n8.apps.nshlib.o nsh_command.c.home.archer.code.nuttx.n8.apps.nshlib.o nsh_fscmds.c.home.archer.code.nuttx.n8.apps.nshlib.o nsh_ddcmd.c.home.archer.code.nuttx.n8.apps.nshlib.o nsh_proccmds.c.home.archer.code.nuttx.n8.apps.nshlib.o nsh_mmcmds.c.home.archer.code.nuttx.n8.apps.nshlib.o nsh_timcmds.c.home.archer.code.nuttx.n8.apps.nshlib.o nsh_envcmds.c.home.archer.code.nuttx.n8.apps.nshlib.o …
```
=> tools/Config: silent print of archive objects

fs/vfs/fs_dir.c, include/fcntl.h, include/stdio.h, include/sys/stat.h, include/sys/time.h, include/unistd.h, libs/libc/libc.h, libs/libc/misc/Make.defs, libs/libc/misc/lib_fchmodat.c, libs/libc/misc/lib_fstatat.c, libs/libc/misc/lib_getfullpath.c, libs/libc/misc/lib_mkdirat.c, libs/libc/misc/lib_openat.c, libs/libc/misc/lib_utimensat.c, libs/libc/stdio/Make.defs, libs/libc/stdio/lib_renameat.c, libs/libc/unistd/Make.defs, libs/libc/unistd/lib_access.c, libs/libc/unistd/lib_fchownat.c, libs/libc/unistd/lib_linkat.c, libs/libc/unistd/lib_readlinkat.c, libs/libc/unistd/lib_symlinkat.c, libs/libc/unistd/lib_unlinkat.c
fs: support openat/fchmodat/mkfifoat/fstatat/...at api
Refs to:
https://linux.die.net/man/2/openat
support file api with relative directory path spicified dirfd
local test
=> fs: support openat/fchmodat/mkfifoat/fstatat/...at api

arch/mips/src/pic32mz/pic32mz_serial.c
Previously, it was impossible to build for PIC32MZ architecture with `CONFIG_SERIAL_TERMIOS` because it introduced compiler errors in the lower half driver.
Fixing the compiler errors and adding an implementation of the `TIOCSERGSTRUCT`, `TCGETS`, and `TCSETS` ioctl calls.
When building with `CONFIG_SERIAL_TERMIOS `, build is fixed and we support `TIOCSERGSTRUCT`, `TCGETS`, and `TCSETS` ioctl calls. When not activated, no effect.
Custom board.
=> arch/pic32mz: Serial support for termios

arch/sim/Kconfig, arch/sim/src/sim/posix/sim_hosttime.c, arch/sim/src/sim/sim_initialize.c, arch/sim/src/sim/sim_internal.h, arch/sim/src/sim/sim_oneshot.c, arch/sim/src/sim/win/sim_hosttime.c
sim: realize sim timer tickless
sim: set loop task duration to 10ms
Sim timer
VELA
=> sim: realize sim timer tickless

arch/arm/src/cxd56xx/cxd56_cisif.c, arch/sim/src/sim/sim_video.c, drivers/video/video.c, include/nuttx/video/imgdata.h
Added timestamp and sequence number to captured frame.
=> Add v4l2_buffer timestamp and sequence

arch/arm/src/sama5/sam_ehci.c, arch/arm/src/sama5/sam_ohci.c
Fixes errors in PR #8480
Make it work as intended
Custom board with SAMA5D27C-D1G
=> Fixes to PR that enables SAMA5 OTG/DRP support

net/udp/udp_conn.c
UDP: Support binding to same addr/port if SO_REUSEADDR is specified.
Ref: On Linux, if SO_REUSEADDR(sk_reuse) is set for both sockets, port will not be regarded as inuse and can be bound again. https://github.com/torvalds/linux/blob/v6.1/net/ipv4/udp.c#L146
UDP bind logic will change if SO_REUSEADDR is set.
CI, iperf3's server mode with UDP client
=> net/udp: Support binding to same addr/port if SO_REUSEADDR is specified.

drivers/usbhost/usbhost_cdcacm.c
1. fixed cdcacm build issue
2. unregister uart driver when usbhost destroy
usbhost
sim usbhost
=> usbhost: fixed cdcacm issue

drivers/video/video.c, drivers/video/video_framebuff.c, drivers/video/video_framebuff.h
=> NONBLOCK and POLLIN support for video device

AUTHORS
Since I've signed the ICLA on 09/11/2020, shouldn't be in the authors list?  
If so, this PR takes care of it.
N/A
N/A
=> Added myself in AUTHORS file.

AUTHORS
Adding myself to AUTHORS file.
None.
N/A
=> Adding myself to AUTHORS

include/limits.h
correct SIZE_MAX and SSIZE_MAX/SSIZE_MIN definition
SSIZE_MAX and SSIZE_MIN
CI
=> limits.h: Map _POSIX_[S]SIZE_M[AX|IN] to [U]LONG_M[AX|IN]

Documentation/guides/simulator.rst
The merged code had Repeated Command.
=> doc:sim Repeated Command "sudo port install"

boards/arm/sam34/flipnclick-sam3x/README.txt, boards/arm/sam34/flipnclick-sam3x/include/board.h, boards/arm/sam34/flipnclick-sam3x/src/flipnclick-sam3x.h, boards/mips/pic32mz/chipkit-wifire/include/board.h, boards/mips/pic32mz/chipkit-wifire/src/chipkit-wifire.h, boards/mips/pic32mz/flipnclick-pic32mz/README.txt, boards/mips/pic32mz/flipnclick-pic32mz/include/board.h, boards/mips/pic32mz/flipnclick-pic32mz/src/flipnclick-pic32mz.h
Fix copy-paste typo.
None.
nxstyle
=> Fix typo: s/then/them/

include/string.h, libs/libc/string/Make.defs, libs/libc/string/lib_mempcpy.c
libc/lib_memcpy.c:Add mempcpy method.
=> libc/lib_memcpy.c:Add mempcpy method.

tools/nxstyle.c
https://github.com/apache/nuttx-apps/pull/1575 need this
nxstyle
checkpatch.sh with PR https://github.com/apache/nuttx-apps/pull/1575
=> nxstyle: add "CMUnitTest" to nxstyle white list

drivers/usbmisc/fusb302.c, include/nuttx/usb/fusb302.h
I better understand ioctl #defines now, so have corrected some inconsistencies.
None.
=> FUSB302 - correct ioctl inconsistencies

arch/arm/src/stm32/stm32_eth.c
Fixes alignment issues reported in #8551, in STM32F4 Ethernet driver.
Properly aligned data in Ethernet driver.
Tested on custom target based on the STM32F427.
So far no issues. Network communications work correctly.
=> stm32_eth: Fixed alignment of Ethernet descriptors & buffers.

include/sys/resource.h
=> sys/resource.h:Added ru_maxrss type

Documentation/quickstart/organization.rst
update tip incorrect permalink
N/A
=> Doc organization.rst

libs/libc/stdlib/lib_strtold.c
follow this : https://github.com/apache/nuttx/pull/8495
=> fix a bug of strtof

Documentation/applications/nsh/nsh.rst
update tip incorrect links
N/A
=> Docs:nsh.rst Update links

include/assert.h, include/nuttx/compiler.h
Add a branches predicted compiler attribute
=> Add branch prediction for assert 

drivers/rptun/rptun.c
rptun: fix rptun_start() failed
rptun
VELA
=> rptun: fix rptun_start() failed

include/string.h, libs/libc/string/Make.defs, libs/libc/string/lib_rawmemchr.c
=> libc/lib_rawmemchr.c:Add rawmemchr methon.

include/signal.h, sched/Kconfig, sched/signal/sig_default.c
Expanding SIGNAL to be consistent with Linux
=> include/signal.h:Expanding SIGNAL to be consistent with Linux

include/strings.h, libs/libc/string/Make.defs, libs/libc/string/lib_bzero.c
Implement the bzero function as an alternative to macro expansion.
=> libc/lib_bzero:Add bzero prototype.

tools/ci/docker/linux/Dockerfile
Add libusb1.0 package for sim usb host
NA
CI Pass
=> tools/ci: add libusb1.0 package

drivers/usbdev/adb.c
Fixed adb build issue when configure CONFIG_USBADB_COMPOSITE.
NA
CI Pass
=> usbdev/adb: fixed adb build issue

arch/arm/src/nrf52/Make.defs, arch/risc-v/src/bl602/Make.defs, arch/risc-v/src/esp32c3/Make.defs, arch/risc-v/src/opensbi/Make.defs, arch/xtensa/src/esp32/Make.defs
Don't download tarball if a local git repo found as apps does
Minor
=> Don't download tarball if a local git repo found

net/bluetooth/bluetooth_conn.c, net/can/can_conn.c, net/icmp/icmp_conn.c, net/icmpv6/icmpv6_conn.c, net/ieee802154/ieee802154_conn.c, net/netlink/netlink_conn.c, net/pkt/pkt_conn.c, net/udp/udp_conn.c, net/usrsock/usrsock_conn.c
Implements some performance optimizations, as noted [here](https://github.com/apache/nuttx/pull/7525#discussion_r1113605986).
Better performance when dynamic connections allocation is enabled.
Build test only.
=> Performance optimizations in connection allocations.

arch/arm/src/cxd56xx/cxd56_gnss.c
Fix an issue that poll with timeout=0 cannot detect events that have already occurred.
Spresense GPS works well.
=> arch: cxd56xx: Fix gnss poll when an event has already occurred

drivers/note/note_driver.c, include/nuttx/sched_note.h
Add tag to sched_note to support runtime filtering
ci will fail and need to rely on the patch of apps，https://github.com/apache/nuttx-apps/pull/1605
=> note: support note filtering at runtime

Documentation/platforms/risc-v/mpfs/boards/icicle/index.rst, Documentation/platforms/risc-v/mpfs/index.rst
This fixes a few naming issues with MPFS. requested by the vendor
None
Not needed
=> MPFS naming / documentation issues

drivers/note/noteram_driver.c
optimize noteram_add, copy as much content as possible at a time
In the past, noteram was copied to the buffer byte by byte, and now it is optimized to two memcpy to improve efficiency
sim:note
=> note: optimize noteram_add, copy as much content as possible at a time

libs/libc/stream/lib_meminstream.c, libs/libc/stream/lib_memsistream.c, libs/libc/stream/lib_memsostream.c, libs/libc/stream/lib_nullinstream.c, libs/libc/stream/lib_nulloutstream.c, libs/libc/stream/lib_rawinstream.c, libs/libc/stream/lib_rawsistream.c, libs/libc/stream/lib_rawsostream.c, libs/libc/stream/lib_stdinstream.c, libs/libc/stream/lib_stdoutstream.c, libs/libc/stream/lib_stdsistream.c, libs/libc/stream/lib_stdsostream.c, libs/libc/stream/lib_zeroinstream.c
Implement gets/puts for all streams
=> libc/stream: Implement gets/puts for all streams

drivers/serial/serial.c, include/nuttx/serial/serial.h
Works with https://github.com/apache/nuttx-apps/pull/1608 
nsh
nsh and telnet
=> drivers/serial: Echo input in driver layer

tools/ci/cibuild.sh, tools/ci/docker/linux/Dockerfile
tools/ci: setup wasi-sdk/wamrc into cibuild
wasi-sdk:
https://github.com/WebAssembly/wasi-sdk
wamrc:
https://github.com/bytecodealliance/wasm-micro-runtime
N/A
ci-check
=> tools/ci: setup wasi-sdk/wamrc into cibuild

arch/arm64/Kconfig, arch/arm64/src/a64/a64_boot.h, arch/arm64/src/a64/a64_lowputc.S, arch/arm64/src/a64/a64_serial.c, arch/arm64/src/common/arm64_head.S, arch/arm64/src/common/arm64_internal.h, arch/arm64/src/fvp-v8r/fvp_boot.h, arch/arm64/src/fvp-v8r/fvp_lowputc.S, arch/arm64/src/fvp-v8r/serial_pl011.c, arch/arm64/src/qemu/qemu_boot.h, arch/arm64/src/qemu/qemu_lowputc.S, arch/arm64/src/qemu/qemu_serial.c, arch/renesas/src/common/renesas_internal.h, boards/renesas/m16c/skp16c26/src/m16c_lcdconsole.c, boards/renesas/rx65n/rx65n-grrose/src/rx65n_sbram.c, boards/renesas/rx65n/rx65n-rsk2mb/src/rx65n_sbram.c
follow other arch coding style
code refactory only
CI
=> arch/boards: Rename up_lowputc to [arm64|renesas]_lowputc

boards/arm64/fvp-v8r/fvp-armv8r/README.txt
Updating Readme.TXT for FVP platform.
None
NA
=> arm64: Update readme.txt for FVP platform

arch/arm/src/sam34/sam_twi.c
The sam34 twi driver was missing I2C_M_NOSTART support.
The similar driver for the SAM7V series controller had that support, therefor I merged the relevant parts over.
Without that support some I2C device drivers fail to work correctly because the TWI driver inserts unwanted stop/start.
E.g. the eeprom/24xx driver.
I tested this change on my own SAM4E board with an FM24CL16 chip
=> Copy I2C_M_NOSTART support from sam7v/sam_twihs.c driver

drivers/ioexpander/Kconfig, drivers/ioexpander/mcp23x17.c, drivers/ioexpander/mcp23x17.h
Bug fixes and improved interrupt support for the mcp23x17 driver.
mcp23x17 driver only
Tested on the EdgeProMX mechanical keyboard.
=> Bug fixes and improved interrupt support for mcp23x17 driver

mm/ubsan/ubsan.c
ubsan: Implement __ubsan_handle_invalid_builtin
ubsan
QEMU
=> ubsan: Implement __ubsan_handle_invalid_builtin

net/netdev/netdev_ioctl.c
net/arp: Only parse ioctl request for valid cmd.
Try to fix https://github.com/apache/nuttx/issues/8719
Don't access req for invalid cmd.
CI & manually
=> net/arp: Only parse ioctl request for valid cmd.

arch/arm/src/armv8-m/Toolchain.defs
arm/armv8-m: add missing zig flags
N/A
ci-check
=> arm/armv8-m: add missing zig flags 

net/netdev/netdev_ioctl.c
Continue the work: https://github.com/apache/nuttx/pull/6976. https://github.com/apache/nuttx/pull/8728 contain additional information.
Handle FIONBIO more correctly for socket case
=> net: Finish FIONBIO default action if si_ioctl return OK

arch/arm/src/imx6/imx_enet.c, arch/arm/src/sama5/Kconfig, arch/arm/src/sama5/sam_twi.c, arch/arm/src/samv7/sam_emac.c, arch/sim/src/sim/posix/sim_offload.c, drivers/mtd/filemtd.c, drivers/usbmisc/fusb302.c, include/nuttx/mm/mempool.h, include/nuttx/mtd/mtd.h, sched/sched/sched_get_stackinfo.c
Fix misc issues in code (style mostly)
N/A
Pass CI
=> Fix misc issues in code

tools/parsetrace.py
Fix exceptions when parsetrace.py parses sched_switch
=> tools/parsetrace: fix context swtich parsing error

arch/arm/src/nrf53/Make.defs, arch/arm/src/nrf53/nrf53_pminitialize.c
=> arch/nrf53: initialize PM

libs/libc/stream/lib_syslogstream.c
patch1：syslogstream add length check
patch2：fix style error
=> syslogstream add length check

drivers/timers/arch_timer.c
Fixed build issue when enable tickless
NA
CI Pass
=> arch_timer: fixed build issue when enable tickless

net/route/net_fileroute.c
Use NXRMUTEX_INITIALIZER for rmutex init.
NA
CI Pass
=> net: use NXRMUTEX_INITIALIZER for rmutex init

drivers/serial/Kconfig
See https://github.com/apache/nuttx/pull/8843#event-8788711967
Minor
ci
=> drivers/serial: Fix some typo error report in https://github.com/apache/nuttx/pull/8843

Documentation/quickstart/install.rst
Update link for USB Device support(USBIP) in WSL2.
N/A
=> Documentation/quickstart: update link for USBIP in WSL2

arch/arm/src/arm/arm_cache.S, arch/arm/src/armv7-a/arm_cache.c, arch/arm/src/armv7-a/arm_l2cc_pl310.c, arch/arm/src/armv7-a/cp15_cacheops.c, arch/arm/src/armv7-a/cp15_cacheops.h, arch/arm/src/armv7-a/l2cc.h, arch/arm/src/armv7-m/arm_cache.c, arch/arm/src/armv7-r/arm_cache.c, arch/arm/src/armv7-r/arm_l2cc_pl310.c, arch/arm/src/armv7-r/cp15_cacheops.c, arch/arm/src/armv7-r/cp15_cacheops.h, arch/arm/src/armv7-r/l2cc.h, arch/arm/src/armv8-m/arm_cache.c, arch/arm64/src/common/arm64_cache.c, arch/xtensa/src/common/xtensa_cache.c, include/nuttx/cache.h
cache: add up_get_xcache_linesize() support
cache
VELA
=> cache: add up_get_xcache_linesize() support

drivers/serial/pty.c
Align the pty behavior to linux/bsd,
Also fix the ECHO issue with microadb after https://github.com/apache/nuttx/pull/8691.
adb shell will echo normally with this patch.
pty based application
telnel and adb shell on rv-virt:netnsh_smp
=> drivers/pty: Echo input by default

boards/arm/stm32/viewtool-stm32f107/src/stm32_highpri.c
=> fix typo cyles -> cycles

include/assert.h, include/nuttx/compiler.h
Replace likely to predict_true ，likely may have duplicate definitions in external libraries
=> include/compiler: replace likely to predict_true 

arch/xtensa/src/esp32/Make.defs, libs/libxx/libcxx.defs, tools/ci/cibuild.sh, tools/ci/docker/linux/Dockerfile
Upgrade Xtensa ESP32 toolchains on CI
Hope to be none
Pass CI
=> tools/ci: upgrade to the latest Xtensa ESP32 toolchains

libs/libc/modlib/modlib_bind.c, sched/paging/paging.h, sched/paging/pg_worker.c
Add missing `FAR` and fix indentation issue
None
Pass CI
=> Fix misc issues

arch/arm/src/sama5/sam_ohci.c, drivers/usbhost/usbhost_hub.c
Prevent the crash seen when USB devices are removed or inserted.
Change to usbhost_hub.c affects other platforms.
SAMA5D3 Xplained board (USB A port)
Test 1) Repeat insertion and removal of USB keyboard.
Test 2) Repeat insertion and removal of USB HUB with a keyboard attached to HUB.
Test 4) Attach a HUB. Repeat insertion and removal of USB keyboard (into HUB port).
At least two 100% reproducible problems were fixed.
1) A crash that happened when a USB hub was unplugged.
2) A crash when a keyboard was plugged into the USB port on the board just after removing it.
=> boards/sama5d3-xplained: Make hot plugging more reliable.

arch/arm/src/stm32h7/stm32_sdmmc.c
stm32h7/stm32_sdmmc.c: fix compilation
CI
=> stm32h7/stm32_sdmmc.c: fix compilation

boards/arm/imxrt/imxrt1064-evk/src/imxrt_boot_image.c, boards/arm/samv7/common/src/sam_boot_image.c, boards/arm/stm32h7/nucleo-h743zi/src/stm32_boot_image.c
=> boards: Replace open/pread with file_open/file_pread

libs/libc/machine/Kconfig, libs/libc/string/lib_strcasecmp.c, libs/libc/string/lib_strcat.c, libs/libc/string/lib_strncasecmp.c, libs/libc/string/lib_strncat.c
libs/libc: correct config define of arch functions 
N/A
ci-check
=> libs/libc: correct config define of arch functions 

sched/misc/assert.c
=> sched/assert: Simplify the fatal detection logic

arch/risc-v/src/espressif/esp_hr_timer.c
This PR intends to improve the HR Timer by defining critical sections via spinlock APIs, which are more efficient than the standard critical section APIs in regards to protecting the HR Timer resources (e.g. timer list) and hardware registers (SYSTIMER) against concurrent accesses.
Besides, the use of a device-local spinlock improves the driver SMP-awareness and paves the way to supporting newer multicore chips (e.g. ESP32-P4).
Only to the HR Timer, which is not yet used by any other Kernel component.
Validating via internal CI testing.
=> risc-v/espressif: Use spinlock APIs for defining critical sections

arch/xtensa/src/esp32/esp32_wifi_adapter.c, arch/xtensa/src/esp32s3/esp32s3_wifi_adapter.c, drivers/net/telnet.c, fs/inode/fs_inodesearch.c, fs/inode/inode.h, fs/unionfs/fs_unionfs.c, fs/vfs/fs_dir.c, fs/vfs/fs_rename.c
Make asprintf and lib_free corresponding.
=> xtensa/esp32: Make asprintf and lib_free corresponding

ReleaseNotes
This is a local copy taken from the confluence notes https://cwiki.apache.org/confluence/display/NUTTX/NuttX+12.1.0
12.1.0 release
None
=> documentation: Add release notes for 12.1.0 release

arch/sim/src/sim/win/sim_hosttime.c
sim/win/hosttime: calculate sec/ms independently to avoid overflow 
In the previous implementation, PerformanceCounter would cause overflow
after running for a long time, This commit will separate the calculation
of the sec/ms part to avoid this issue, Reference:
https://github.com/cygwin/cygwin/blob/main/winsup/cygwin/clock.cc#L194-L217
N/A
cmake + msvc
=> sim/win/hosttime: calculate sec/ms independently to avoid overflow 

arch/xtensa/src/common/xtensa_schedsigaction.c
While delivering a signal to a task that is currently running on the other core (SMP-enabled), the xtensa_sig_deliver needs to leave the critical section first. This should use the interrupt state (PS register) of the previously saved registers from the moment that the other CPU was paused.
The Inter-Processor Interrupt that pauses the other CPU generates a level-1 interrupt which sets the PS.EXCM. This level-1 interrupt is treated as an Exception and the bit PS.EXCM bit is automatically reset on return from Exception. However, this is not the case here because we are changing the execution to the signal trampoline. Restoring the PS register with the PS.EXCM bit set would cause any other exception to deviate execution to the DEC (double exception vector), avoiding it to be treated …
=> xtensa/sigdeliver: fix signal deliver when task is running on ther CPU

sched/sched/sched_lock.c, sched/sched/sched_mergepending.c
Do not allow context switch to happen while scheduler is locked
This change depends on https://github.com/apache/nuttx-apps/pull/1714
Fix the bug. Priority inheritance and other parts of the system that rely on scheduler lock/unlock behaviour.
Testes on spresense board with https://github.com/apache/nuttx-apps/pull/1711
=> sched: fix context switching with locked scheduler

fs/inode/fs_inodesearch.c, fs/vfs/fs_dir.c, fs/vfs/fs_rename.c, libs/libc/stdio/lib_tempnam.c, tools/gencromfs.c
Fixes the usage of asprintf, wherever the return value was not checked correctly.
More information [here](https://lists.apache.org/thread/0m2llcc6osj8wlpnsojkvbfg2ltwj48w).
Potential bug fixes.
CI / build only.
=> Fixes in asprintf usage.

boards/risc-v/esp32c3/common/include/esp32c3_board_mpu60x0_i2c.h, boards/risc-v/esp32c3/common/src/Make.defs, boards/risc-v/esp32c3/common/src/esp32c3_board_mpu60x0_i2c.c, boards/risc-v/esp32c3/esp32c3-devkit/src/esp32c3_bringup.c
Add MPU60x0 IMU sensors support for ESP32C3
ESP32C3
ESP32-C3-WROOM-02
=> Add MPU60x0 IMU sensors support for ESP32C3

Documentation/platforms/sim/sim/boards/sim/index.rst, Documentation/platforms/sim/sim/index.rst
=> Migrate sim board README.txt to Documentation

drivers/audio/Kconfig, drivers/audio/Make.defs, drivers/audio/audio_dma.c, include/nuttx/audio/audio_dma.h
add audio dma driver which base on common dma ops.
local
=> audio: add audio_dma device driver.

include/nuttx/mm/circbuf.h, mm/circbuf/circbuf.c
circbuf support write or read buffer direct
noting
use it by myself
avoid memory copy
=> circbuf support write or read buffer direct

arch/arm64/src/common/arm64_cpupause.c
pthread_cancel may block forever
In smp when cpu0 calls up_cpu_resume to release the cpu1 lock, another locked cpu1 did not execute immediately, and soon cpu0 called up_cpu_resume again,  now cpu1 unable to respond to the interrupt at this time, resulting in a deadlock. Our solution is to restore cpu1 execution from asynchronous to synchronous to ensure that cpu1 is restored.
none
ostest
=> cpu:  in smp pthread_cancel occasionally deadlock

libs/libm/Kconfig, libs/libm/Makefile, libs/libm/newlib/0001-newlib-libm-fix-__RCSID-build-error.patch, libs/libm/newlib/0002-newlib-libm-remove-include-reent.h.patch, libs/libm/newlib/Kconfig, libs/libm/newlib/Make.defs, libs/libm/newlib/include/complex.h, libs/libm/newlib/include/ieeefp.h, libs/libm/newlib/include/machine/ieeefp.h, libs/libm/newlib/include/math.h, libs/libm/newlib/include/tgmath.h, tools/Config.mk, tools/nxstyle.c
Add  newlib support to libm/newlib
How to open the config:
(1)make menuconfig  (2)close math.h:build setup->Customize Header Files->math.h (3) select Newlib:Library Rountines->Select math library->Math library from Newlib (4)make
=> libm/newlib: add newlib/libm support

libs/libc/stdlib/lib_exit.c
copy from pthread_exit to avoid the resource leak
Fix the resource leak
Internal test case
=> libc: Cleanup per-thread resource in exit/quick_exit

arch/arm/src/imxrt/Make.defs, arch/arm/src/imxrt/hardware/imxrt_flexio.h, arch/arm/src/imxrt/imxrt_flexio.c, arch/arm/src/imxrt/imxrt_flexio.h
Support for i.MX FlexIO peripheral. FlexIO is a powerful peripheral, capable of implementing various communication protocols with the help of shifters and timers.
NA
NA
=> i.MX RT FlexIO support

arch/arm/src/armv7-r/Make.defs, arch/arm/src/armv7-r/arm_cpuhead.S, arch/arm/src/armv7-r/arm_cpuidlestack.c, arch/arm/src/armv7-r/arm_cpuindex.c, arch/arm/src/armv7-r/arm_cpupause.c, arch/arm/src/armv7-r/arm_cpustart.c, arch/arm/src/armv7-r/arm_schedulesigaction.c, arch/arm/src/armv7-r/arm_scu.c, arch/arm/src/armv7-r/arm_sigdeliver.c, arch/arm/src/armv7-r/arm_vectors.S, arch/arm/src/armv7-r/sctlr.h, arch/arm/src/armv7-r/scu.h, arch/arm/src/armv7-r/smp.h
This PR add armv7-r smp support.
ARMV7-R SMP
Verify in vdk ARM R8 SMP environment.
=> arch/armv7-r: add armv7-r smp support

drivers/pipes/pipe.c
Fix https://github.com/apache/nuttx/issues/9129
Similar to the fix introduced by https://github.com/apache/nuttx/pull/8985, it's necessary to set one end of the `file_pipe` as non-blocking temporarily while opening the other end to avoid it blocking unexpectedly.
Fix https://github.com/apache/nuttx/issues/9129
Internal CI, [`pipe`](https://github.com/apache/nuttx-apps/pull/1729) app and SIM, with:
```
./tools/configure.sh sim:adb
make -j8
./nuttx
adbd &
```
and, 
```
sudo apt-get install adb
adb kill-server
adb shell
```
=> drivers/pipe: fix blocking file_pipe

arch/arm/src/sama5/Kconfig, arch/arm/src/sama5/Make.defs, arch/arm/src/sama5/hardware/sam_classd.h, arch/arm/src/sama5/hardware/sam_pmc.h, arch/arm/src/sama5/sam_classd.c, arch/arm/src/sama5/sam_classd.h, include/nuttx/audio/audio.h
Adds ClassD audio driver support for Microchip ATSAMA5D2 family
None expected
Custom board with SAMA5D27C-D1G, with audio output stage
=> SAMA5D2 Class D

drivers/mtd/mtd_nand.c
- mtd/nand: Implement MTDIOC_ERASESTATE ioctl
- mtd/nand: Implement MTDIOC_ERASESECTORS ioctl
New function
Internal test
=> Implement MTDIOC_ERASESTATE and MTDIOC_ERASESECTORS

arch/arm/src/sama5/sam_ohci.c
Unplugging a USB device from an OHCI root hub will cause a deadlock if DRVR_EPFREE is called from am_rhsc_bottomhalf. A typical call chain looks like this: sam_rhsc_bottomhalf->CLASS_DISCONNECTED->usbhost_destroy->DRVR_EPFREE. In this case DRVR_EPFREE tries to lock a locked mutex. A recursive mutex prevents this deadlock.
mutex_t vs rmutex_t 
After repeated hotplugging, keyboard and mass storage were still functional.
=> arch/arm/sama5: Use a recursive mutex to fix OHCI deadlock.

include/netinet/ip.h
=> ip: add iphdr definition

include/netinet/ip6.h
=> ip6: add ip6-related definition

include/netinet/udp.h
=> udp: add udphdr definition

include/netinet/icmp6.h
=> icmp6: add icmp6-related definition

sched/signal/sig_timedwait.c
remove useless assert
Noting
ci
=> sig_timewait:remove useless assert

net/netlink/netlink_route.c
=> netlink: convert lltype to device type

fs/mqueue/mq_open.c, fs/nxffs/nxffs_write.c, fs/shm/shm_open.c, fs/unionfs/fs_unionfs.c, fs/vfs/fs_close.c, fs/vfs/fs_dir.c, fs/vfs/fs_dup2.c, fs/vfs/fs_open.c
to avoid set fields to zero one by one
code refactor
CI
=> fs/vfs: Zero file struct field with memset

Kconfig, arch/arm/src/imxrt/Kconfig, arch/arm/src/sama5/Kconfig, arch/arm/src/stm32h7/Kconfig, arch/risc-v/src/mpfs/Kconfig, arch/xtensa/src/esp32/Kconfig, arch/xtensa/src/esp32s3/Kconfig
Remove spaces from Kconfig files
Replace help => ---help---
Add TABs
none
=> Fix Kconfig style

drivers/usbhost/usbhost_cdcacm.c
drivers/usbhost/usbhost_cdcacm.c: fix warning
CI
=> drivers/usbhost/usbhost_cdcacm.c: fix warning

arch/xtensa/src/esp32s3/esp32s3_psram_octal.c
Fix code style of esp32s3_psram_octal.c
=> xtensa/esp32s3: Fix code style of esp32s3_psram_octal.c

sched/mqueue/mqueue.h, sched/task/task_terminate.c
=> sched: Fix nxstyle errors

arch/arm/src/lpc43xx/lpc43_spifi.c, drivers/mtd/gd25.c, drivers/mtd/sector512.c, drivers/mtd/sst25.c, drivers/mtd/w25.c
Fix typo -EACESS -> -EACCES
Avoid compilation error
N/A
=> Fix typo -EACESS -> -EACCES

arch/arm/src/stm32f7/stm32_usbhost.c
=> arch/arm/src/stm32f7/stm32_usbhost.c:  Fix nxstyle errors

net/inet/ipv6_setsockopt.c
modify the assignment logic to make it easier to extend new options later.
sim:local
=> ipv6_setsockopt: Merge similarity logic

drivers/net/netdev_upperhalf.c
Before `atomic` is ready on every platform, we need a way to protect `quota`, previously it's protected by `net_lock`, but this makes `netpkt_xxx` interfaces unable to be called under interrupt context, so changed to spin lock. Also, we can easily change them into atomic under this implementation.
netdev_upperhalf (currently only used on sim)
manually on sim
=> netdev_upper: Protect quota by spin lock to allow netpkt_xxx be called in interrupt context

arch/arm/include/arm/irq.h, arch/arm/include/armv7-m/irq.h, arch/arm/include/armv8-m/irq.h, arch/arm/src/tiva/common/lm4xx_tm3c_sysctrl.c, arch/arm/src/tiva/common/tiva_eeprom.c
Notify the compiler that the condition flag has changed to prevent the compiler from optimizing and reordering instructions, which may cause exceptions.
NA
CI Pass
=> arch/arm: Add a "cc" flag

libs/libm/Makefile, libs/libm/bin/Makefile, libs/libm/kbin/Makefile
fix error: Relative file path does not match actual file
none
=> libs/libm: fix nxstyle

arch/arm/src/stm32h7/stm32_usbhost.c
=> arch/arm/src/stm32h7/stm32_usbhost.c: Fix nxstyle errors

arch/arm64/src/common/arm64_cache.c
When the address is not cache line aligned, a flush operation is required.
Cache
fvp-armv8r:nsh
=> arm64/cache: Support unalign cache clean.

boards/arm/nrf53/nrf5340-audio-dk/src/nrf5340-audio-dk.h, boards/arm/nrf53/nrf5340-dk/src/nrf5340-dk.h
Cosmetic changes for nrf5340-dk and nrf5340-audio-dk
CI
=> boards/nrf53: cosmetics

libs/libc/netdb/lib_gethostentbynamer.c
- Linux: What inside /etc/hosts comes first.
- NuttX: Even if we write a domain in /etc/hosts, we still use DNS result instead of hosts lines.
This patch changes this behavior.
Minor change to `gethostentbyname_r`
Manually.
=> netdb: Regard hosts file prior to DNS when resolving

include/nuttx/mm/mempool.h, mm/mempool/mempool_multiple.c, mm/mm_heap/mm_malloc.c
Support when malloc failed dump mempool info
mempool
nsh with mempool
=> Support when malloc failed dump mempool info

mm/mempool/mempool_multiple.c
mempool:fix bug when calculating mempool delta
mempool
nsh with mempool
=> mempool:fix bug when calculating mempool delta

drivers/usbhost/usbhost_enumerate.c
See #3644. Code from:
https://github.com/apache/nuttx/compare/master...btashton:libusb
Fix issue #3644
Plug in USB mouse+keyboard dongle.
/dev/kbda and /dev/mouse0 can be seen in nsh. Only kbda device was seen before this change.
=> usbhost: Can now handle multiple interface descriptors.

drivers/serial/Kconfig-16550, drivers/serial/uart_16550.c, include/nuttx/serial/uart_16550.h
drivers: serial :16550 uart
This commit adds support for DMA on 16550 uart
=> dma support 16550 uart

Documentation/reference/os/time_clock.rst
Documentation: Discussion of _Tickless OS_ was missing an example Kconfig code block. Also, some minor typo and grammar fixes.
Improves documentation.
Viewed in GitHub's reStructuredText viewer.
=> Documentation: Minor fixes in Tickless OS documentation

binfmt/libelf/libelf_coredump.c
elf/coredump: add sanity checks for stack pointer
stack pointer may be invalid value if in SMP mode, add sanity checks to avoid invalid access
N/A
sabre-6quad/smp
=> elf/coredump: add sanity checks for stack pointer

arch/xtensa/src/esp32s3/esp32s3_spiram.c
Support 32MB PSRAM, considering ESP32-S3 totally has 32MB MMU, and flash(.text and .rodata) also need use some parts of MMU, so not whole PSRAM's 32MB physical space can be mapped by MMU.
=> xtensa/esp32s3: Support 32MB PSRAM

drivers/can/mcp2515.c
Fix https://github.com/apache/nuttx/issues/9391
mcp2515
=> drivers/can/mcp2515.c Fix Configure Spi Bus on every bus lock

arch/xtensa/src/esp32s3/Kconfig, arch/xtensa/src/esp32s3/Make.defs, arch/xtensa/src/esp32s3/esp32s3_dma.c, arch/xtensa/src/esp32s3/esp32s3_spi.h, arch/xtensa/src/esp32s3/esp32s3_spi_slave.c
=> xtensa/esp32s3: SPI slave driver

libs/libc/stdio/lib_fopen.c
add fdsan protection for all file pointers
none
none
=> libc/fdsan: add fdsan protection for all file pointers

fs/driver/driver.h, fs/driver/fs_blockpartition.c, fs/driver/fs_mtdpartition.c, fs/partition/fs_gpt.c, fs/partition/fs_mbr.c, fs/partition/fs_partition.c
to avoid the duplication of common logic
New function
sim:mtdpart
=> fs/partition: register partition device if caller doesn't provide handler

mm/mm_heap/mm_realloc.c
bug fix,their have a read out of bounds
noting
sim:nsh with testin_mm & kasan
=> mempool:fix bug read out of bounds when realloc

drivers/mtd/mtd_config_fs.c
mtd_config_fs: check configdata before use
=> driver/mtd : check args for nvs read

libs/libc/wchar/lib_swprintf.c
Implement vswprintf and let swprintf based on it.
swprintf and a new function
local machine
=> libc/wchar: Implement vswprintf

drivers/sensors/Kconfig, drivers/sensors/Make.defs, drivers/sensors/bh1749nuc.c, include/nuttx/sensors/bh1749nuc.h
drivers/sensors: add bh1749nuc color sensor support
thingy53
=> drivers/sensors: add bh1749nuc color sensor support

mm/kmap/kmm_map.c
Fix style error pointed out in #9368
Cosmetic
None
=> mm/kmm_map: Fix code style error

drivers/virtio/virtio-mmio-net.c
- Remove unused code and fix comments in virtio-mmio-net.c
- None
- Tested with qemu-7.1
=> Remove unused code and fix comments in virtio-mmio-net.c

drivers/mtd/Kconfig
=> driver/mtd : mtd_config name len max changed to NAME_MAX

arch/arm/src/am335x/am335x_lowputc.c, arch/xtensa/src/esp32/esp32_serial.c, drivers/usbdev/cdcacm.c, sched/semaphore/sem_destroy.c
Fix style issues found during code review
N/A
Pass CI
=> style: fix style issues found during code review

libs/libc/string/lib_memcmp.c, libs/libc/string/lib_memcpy.c, libs/libc/string/lib_memmem.c, libs/libc/string/lib_mempcpy.c, libs/libc/string/lib_memrchr.c, libs/libc/string/lib_skipspace.c, libs/libc/string/lib_stpcpy.c, libs/libc/string/lib_stpncpy.c, libs/libc/string/lib_strcasestr.c, libs/libc/string/lib_strchr.c, libs/libc/string/lib_strchrnul.c, libs/libc/string/lib_strcpy.c, libs/libc/string/lib_strlcat.c, libs/libc/string/lib_strlcpy.c, libs/libc/string/lib_strlen.c, libs/libc/string/lib_strncat.c, libs/libc/string/lib_strnlen.c, libs/libc/string/lib_strsep.c, libs/libc/string/lib_strstr.c, libs/libc/string/lib_strtok.c, libs/libc/string/lib_strtokr.c, libs/libc/string/lib_strxfrm.c
1. Add missing `FAR` to pointers
2. Fix style issues
3. Update to use `'\0'` comparison
N/A
Pass CI
=> libs/libc/string: fix various style issues in code

arch/xtensa/src/esp32s3/Kconfig, arch/xtensa/src/esp32s3/esp32s3_spiflash.c, arch/xtensa/src/esp32s3/hardware/esp32s3_soc.h
Flash functions in ROM just can access 24-bit address.
=> xtensa/esp32s3: Support 32MB SPI flash

boards/arm/cxd56xx/common/src/cxd56_crashdump.c, boards/arm/stm32/nucleo-f429zi/src/stm32_bbsram.c, boards/arm/stm32f7/nucleo-144/src/stm32_bbsram.c, boards/renesas/rx65n/rx65n-grrose/src/rx65n_sbram.c, boards/renesas/rx65n/rx65n-rsk2mb/src/rx65n_sbram.c
Remove the unnecessary FAR added in #9516
NA
CI Pass
=> boards: remove unnecessary FAR

libs/libc/misc/lib_fdcheck.c
fdcheck compatibility enhancement
none
none
=> fdcheck compatibility enhancement

fs/vfs/fs_signalfd.c
Use sigandset function instead of & operation, because the sigset_t structure has been changed.
This PR is to adapt to the changes made in #8885.
vfs
BES board test with vfs.
=> fs/vfs: Proper use of sigisemptyset

arch/sim/src/sim/sim_heap.c, fs/procfs/fs_procfsmeminfo.c, fs/procfs/fs_procfsproc.c, include/malloc.h, include/nuttx/mm/mempool.h, include/nuttx/mm/mm.h, mm/kmm_heap/kmm_mallinfo.c, mm/mempool/mempool.c, mm/mempool/mempool_multiple.c, mm/mm_heap/mm_initialize.c, mm/mm_heap/mm_mallinfo.c, mm/mm_heap/mm_malloc.c, mm/mm_heap/mm_memdump.c, mm/tlsf/mm_tlsf.c, mm/umm_heap/umm_mallinfo.c
align with the naming of mallinfo_task and
rename MM_BACKTRACE_XXX_PID to PID_MM_XXX 
sim:kasan
=> mm: Rename mm_memdump_s to malltask

include/malloc.h, mm/mempool/mempool.c, mm/mm_heap/mm_mallinfo.c, mm/mm_heap/mm_malloc.c, mm/mm_heap/mm_memdump.c, mm/tlsf/mm_tlsf.c
to express the intent more clear
sim:adb and sim:kasan
=> mm: Rename PID_MM_INVALID to PID_MM_LEAK

sched/sched/sched_idletask.c
Fix typo of sched_idletask
None
=> sched/sched/sched_idletask: fix typo

libs/libc/misc/Kconfig, libs/libc/misc/lib_memfd.c
since shm can work in protected and kernel mode too
memfd
internal
=> libc: Prefer to implement memfd on top of shm 

drivers/virtio/virtio-mmio-net.c
- In this implementation, only one descriptor is used for RX.
- NOTE: we still use two descriptors for TX
- None
- Tested with qemu-7.1
=> drivers: virtio: Use one dscriptor for RX in virtio-mmio-net.c

sched/misc/assert.c
to unify the way to get include directories and define macros in Makefile
ci
=> sched/assert: Change show_xxx to dump_xxx

mm/mm_heap/mm_lock.c
=> mm_lock.c: reformat preprocessor

drivers/sensors/apds9960.c
Fix resource leak in error handling
=> drivers/sensors/apds9960.c: Fix resource leak in error handling

arch/risc-v/src/litex/litex_emac.c
In the default configuration, the Litex ethernet peripheral contains two RX and two TX buffers. The active buffer for the peripheral should be swapped as soon as possible, in order to reduce packet loss.
This modification acknowledges the receive buffer as soon as the pending data is copied into the NuttX device data buffer. Improving reliability under heavy load.
Lower chance of filling up all ethernet RX slots when under heavy load.
arty_a7:knsh with IPV6 stack and ping6, whilst using `ping -f` from host.
=> risc-v/litex: Improve ethernet packet reception.

tools/callstack.py
Add 'callstack.py' script for parsing stack dump log to callstack.
Nothing
Spresense assert log with Ubuntu environment.
=> tools: Add script to parse callstack

mm/kasan/kasan.c
mm/kasan: replace load/store methods to marco 
N/A
ci-check
=> mm/kasan: replace load/store methods to macro 

fs/aio/aio_write.c
1. make the aio_write implementation can pass the lpt/open_posix_testsuite/aio_write testcases
2. the modification are referred to https://pubs.opengroup.org/onlinepubs/9699919799/functions/aio_write.html
=> libs/libc/aio: fix aio_write compatible bug

fs/aio/aio_write.c
1. make the determination more clear
=> libs/libc/aio: adjust the flags determination method

Documentation/guides/nfs.rst
Change the command format to the actual one in the system
=> documentation: correct the nfs command format

tools/Unix.mk, tools/Win.mk
Reverts apache/nuttx#9572 to fix regression described in https://github.com/apache/nuttx/issues/9670
=> Revert "tools: Fix CONFIG_BASE_DEFCONFIG generation"

boards/arm/cxd56xx/common/src/cxd56_alt1250.c, drivers/modem/alt1250/altmdm.c, include/nuttx/modem/alt1250.h
Change the power on sequence according to ALT1250 modem spec.
Alt1250 modem driver on CXD5602 only.
Modem power on / off test.
=> cxd56/alt1250: Change power on sequence

binfmt/libelf/libelf_verify.c, libs/libc/modlib/modlib_verify.c
to avoid the duplication of the magic number.
ci
=> elf: Replace {0x7f, 'E', 'L', 'F'} to EI_MAGIC

binfmt/libelf/libelf_init.c, fs/vfs/fs_fstat.c, include/nuttx/fs/fs.h, libs/libc/modlib/modlib_init.c
since kernel code prefer to use file_ API
minor
ci
=> binfmt/elf: Replace nx_stat with file_stat

libs/libc/dlfcn/lib_dlopen.c, libs/libc/machine/arm/armv7-m/arch_elf.c, libs/libc/modlib/modlib.h
Fix coding style issues from PR #7202
Fix pre-CI
compiling sim/sotest
=> Fix coding style issues from PR #7202

tools/Unix.mk, tools/Win.mk
This reverts commit bc4266fa485e02b6e711a385167294d0c9055261.
RELEASE
NONE
=> {BP-9673} Revert "tools: Fix CONFIG_BASE_DEFCONFIG generation"

boards/arm/cxd56xx/common/src/cxd56_alt1250.c, drivers/modem/alt1250/altmdm.c, include/nuttx/modem/alt1250.h
Change the power on sequence according to ALT1250 modem spec.
RELEASE
NONE
=> {BP-9713} cxd56/alt1250: Change power on sequence

arch/sim/src/sim/posix/sim_alsa.c, include/nuttx/audio/audio.h
audio: add AUDIOIOC_FLUSH ioctl
N/A
vela
=> audio: add AUDIOIOC_FLUSH ioctl

drivers/sensors/apds9960.c
=> {BP-9613} drivers/sensors/apds9960.c: Fix resource leak in error handling

arch/arm/src/armv7-a/arm_timer.c, arch/arm/src/armv7-r/arm_timer.c, arch/arm/src/armv7-r/gic.h, arch/arm/src/armv8-r/arm_arch_timer.h, arch/arm/src/lc823450/lc823450_spifi2.h, arch/arm/src/lpc2378/lpc23xx_pinsel.h, arch/arm/src/lpc2378/lpc23xx_uart.h
Remove TABs
Fix indentation
none
=> arch/arm/src: Fix nuttx coding style

arch/arm/include/elf.h, arch/sim/include/elf.h, include/elf.h, include/elf32.h, include/elf64.h, include/nuttx/lib/modlib.h, include/nuttx/symtab.h, libs/libc/machine/risc-v/arch_elf.c, libs/libc/symtab/Kconfig, libs/libc/unistd/Kconfig
Make code and config in the same location
minor
ci
=> libc/symtab: Move SYMTAB_XXX from unistd/Kconfig to symtab/Kconfig

sched/misc/assert.c
Added missing semicolon in dead-lock detection logic.
Code now builds properly.
Build test only.
=> Added missing semicolon to dead-lock detection.

drivers/timers/arch_alarm.c, drivers/timers/arch_timer.c
add up_perf_init weak_function
=> time: add up_perf_init weak_function

drivers/serial/serial.c
fix driver/serial/serial.c logic error
=> serial:fix driver/serial/serial.c logic error

drivers/drivers_initialize.c, drivers/misc/Kconfig, drivers/misc/Make.defs, drivers/misc/dev_ascii.c
It will return all characters between ' '(0x20)-'~'(0x7e).
=> drivers: return sequential characters for /dev/zero device

arch/arm/src/armv8-m/arm_hardfault.c
add arm_gen_nonsecurefault information
=> armv8m/arm_hardfault:add arm_gen_nonsecurefault information

include/elf.h, include/elf32.h, include/elf64.h, include/nuttx/lib/modlib.h, libs/libc/dlfcn/lib_dlclose.c, libs/libc/dlfcn/lib_dlopen.c, libs/libc/modlib/modlib_bind.c
This patch fixes some issues found by Mark Stevens and improve the dynamic loader.
People will be able to use dynamic / shared libraries on NuttX
N/A
Please ignore CamelCase errors
=> Fix and improve dynamic loader

include/nuttx/compiler.h
win/MSVC: add packed_struct macro implement
N/A
ci-check
=> win/MSVC: add packed_struct macro implement

libs/libc/stdio/lib_libgetstreams.c
nxstyle: covert utf-8 to ascii
libs/libc/stdio/lib_libgetstreams.c: C source, UTF-8 Unicode text
->
libs/libc/stdio/lib_libgetstreams.c: C source, ASCII text
N/A
ci-check
=> nxstyle: covert utf-8 to ascii

net/local/local_accept.c, net/local/local_listen.c, net/local/local_netpoll.c
Support the abstract path to connect
=> net/local: Support the abstract path to connect

include/nuttx/sched.h, libs/libc/libgen/lib_basename.c
=> libc/basename: Change len type from int to size_t

net/local/local_release.c
if client is a noblocking socket, user can do close when server has not yet invoke accept interface, so we need remove this socket from server.lc_waiters. avoid server socket access the freed memory.
==936564==ERROR: AddressSanitizer: heap-use-after-free on address 0xf23071c8 at pc 0x58eaac3b bp 0xf0b9e218 sp 0xf0b9e208 READ of size 4 at 0xf23071c8 thread T0
#0 0x58eaac3a in dq_remfirst queue/dq_remfirst.c:45
#1 0x58fd1efe in local_accept local/local_accept.c:141
#2 0x58f66df6 in psock_accept socket/accept.c:149
#3 0x58f672a4 in accept4 socket/accept.c:280
#4 0x5be9ee0c in accept net/lib_accept.c:50
#5 0x592d6a5d in uv__accept libuv/src/unix/core.c:502
#6 0x5930d83b in uv__server_io libuv/src/unix/stream.c:550
#7 0x592efbde in uv__io_poll libuv/src/unix/posix-poll.c:335
#8 0x592d649a in …
=> net/local: remove client from server.lc_waiters when client close

drivers/usbhost/usbhost_hub.c
DRVR_CTRLIN buffer must have been allocated using DRVR_ALLOC.  For example, some mcu memory should align cache line.
only usb host hub.
=> drivers: usbhost_hub: usb communication memory should use DRVR_ALLOC

tools/ci/cibuild.sh
=> CI: workaround Cython issue

Documentation/quickstart/debugging.rst
add gdb python script documentation
Noting
ci
=> Documentation:add gdb python script documentation

arch/arm/src/arm/arm_tcbinfo.c, arch/arm/src/armv6-m/arm_tcbinfo.c, arch/arm/src/armv7-a/arm_tcbinfo.c, arch/arm/src/armv7-m/arm_tcbinfo.c, arch/arm/src/armv7-r/arm_tcbinfo.c, arch/arm/src/armv8-m/arm_tcbinfo.c, arch/risc-v/src/common/riscv_tcbinfo.c, arch/xtensa/src/common/xtensa_tcbinfo.c, include/nuttx/sched.h, tools/jlink-nuttx.c
sched/tcbinfo: add stack info to tcbinfo
tcbinfo
sim:nsh
=> sched/tcbinfo: add stack info to tcbinfo 

arch/arm/src/armv6-m/CMakeLists.txt, arch/arm/src/stm32f0l0g0/CMakeLists.txt, boards/arm/stm32f0l0g0/b-l072z-lrwan1/CMakeLists.txt, boards/arm/stm32f0l0g0/b-l072z-lrwan1/src/CMakeLists.txt, boards/arm/stm32f0l0g0/nucleo-f072rb/CMakeLists.txt, boards/arm/stm32f0l0g0/nucleo-f072rb/src/CMakeLists.txt, boards/arm/stm32f0l0g0/nucleo-f091rc/CMakeLists.txt, boards/arm/stm32f0l0g0/nucleo-f091rc/src/CMakeLists.txt, boards/arm/stm32f0l0g0/nucleo-g070rb/CMakeLists.txt, boards/arm/stm32f0l0g0/nucleo-g070rb/src/CMakeLists.txt, boards/arm/stm32f0l0g0/nucleo-g071rb/CMakeLists.txt, boards/arm/stm32f0l0g0/nucleo-g071rb/src/CMakeLists.txt, boards/arm/stm32f0l0g0/nucleo-l073rz/CMakeLists.txt, boards/arm/stm32f0l0g0/nucleo-l073rz/src/CMakeLists.txt, boards/arm/stm32f0l0g0/stm32f051-discovery/CMakeLists.txt, boards/arm/stm32f0l0g0/stm32f051-discovery/src/CMakeLists.txt, boards/arm/stm32f0l0g0/stm32f072-discovery/CMakeLists.txt, boards/arm/stm32f0l0g0/stm32f072-discovery/src/CMakeLists.txt, boards/arm/stm32f0l0g0/stm32g071b-disco/CMakeLists.txt, boards/arm/stm32f0l0g0/stm32g071b-disco/src/CMakeLists.txt, boards/arm/stm32f0l0g0/stm32l0538-disco/CMakeLists.txt, boards/arm/stm32f0l0g0/stm32l0538-disco/src/CMakeLists.txt
=> cmake: port stm32f0l0g0

libs/libc/pthread/pthread_atfork.c
fix the incorrect comments info
=> pthread_atfork: fix the incorrect description in comments

arch/sim/src/sim/sim_tcbinfo.c
sim/tcbinfo:add ebp to tcbinfo
sim32
sim with tcbinfo,use tools/gdb/__init__.py
=> sim/tcbinfo:add ebp to tcbinfo

drivers/usbhost/usbhost_hidkbd.c
- usbhost_send_request(): data should using DRVR_ALLOC buffer
- fix usbhost_cralloc() assert variable
hidkbd
Internal Test.
=> drivers: usbhost: fix usbhost_hidkbd some errors

cmake/nuttx_add_application.cmake, cmake/nuttx_add_library.cmake, cmake/nuttx_add_romfs.cmake, cmake/nuttx_add_symtab.cmake, cmake/nuttx_parse_function_args.cmake
cmake: format docstrings
none
CI
=> cmake: format docstrings

fs/procfs/fs_procfs.c
fs/procfs: call the close of each component when procfs_close
daily test
=> fs/procfs: call the close of each component when procfs_close

drivers/misc/rpmsgblk.c, drivers/misc/rpmsgblk_server.c
add support for mmc_ioc_cmd/mmc_multi_ioc_cmd ioctl
rpsmgblk
internel testing
=> Rpmsgblk: add support for mmc_ioc_cmd/mmc_multi_ioc_cmd ioctl

net/rpmsg/rpmsg_sockif.c
net/rpmsg: get credentials between client and server
support to get credentials, like local socket.
local test
=> net/rpmsg: get credentials between client and server

fs/vfs/fs_dup2.c
vfs/dup: add nonblock flag to avoid happening block when dup
avoid dup block when child task creating.
daily test
=> vfs/dup: add nonblock flag to avoid happening block when dup

fs/mmap/fs_mmap.c, fs/mmap/fs_munmap.c, fs/tmpfs/fs_tmpfs.c
mmap/tmpfs: support mmap for tmpfs
support mmap for tmpfs
add sanity check for munmap
local test and ltp.
=> mmap/tmpfs: support mmap for tmpfs

graphics/nxterm/nxterm_kbdin.c
in smp sched_lock is not enough to prevent preemption
none
ostest
=> graphics: remove sched_[un]lock

include/stdlib.h, libs/libc/stdlib/lib_srand.c
libc/rand_r: support rand_r api
Refs to https://pubs.opengroup.org/onlinepubs/7908799/xsh/rand.html
add new api rand_r
local test
=> libc/rand_r: support rand_r api

arch/arm/src/cxd56xx/cxd56_cisif.c, arch/sim/src/sim/sim_camera.c, boards/sim/sim/sim/src/sim_bringup.c, drivers/video/video.c, include/nuttx/video/imgdata.h, include/nuttx/video/video.h, include/nuttx/video/video_controls.h
depends on https://github.com/apache/nuttx-apps/pull/1859
video subsystem
internal testing
=> video driver support multiple instance

drivers/mtd/ftl.c
=> driver/mtd/ftl: Modify erasure result processing error issue

arch/arm/src/rtl8720c/amebaz_depend.c, arch/risc-v/src/mpfs/mpfs_ihc.c, boards/arm/sama5/jupiter-nano/src/sam_usb.c, boards/arm/stm32f7/stm32f746-ws/src/stm32_usb.c, boards/arm/stm32f7/stm32f746g-disco/src/stm32_usb.c, boards/arm/stm32f7/stm32f777zit6-meadow/src/stm32_usb.c, boards/arm/stm32h7/stm32h745i-disco/src/stm32_usb.c, drivers/modem/alt1250/alt1250.c, drivers/rptun/rptun.c, drivers/sensors/ds18b20.c, drivers/sensors/fakesensor.c, drivers/sensors/hyt271.c, drivers/sensors/ltr308.c, drivers/sensors/mpu9250.c, drivers/sensors/ms5611.c, drivers/sensors/wtgahrs2.c, sched/wqueue/kwork_thread.c
=> drivers: Format pointer through "%p" for kthread_create

fs/nfs/nfs_vfsops.c
fs/nfs: support seek, fsync operation
support  seek and fsync.
daily test
=> fs/nfs: support seek, fsync operation

boards/arm/cxd56xx/drivers/sensors/ak09912_scu.c, boards/arm/cxd56xx/drivers/sensors/apds9930_scu.c, boards/arm/cxd56xx/drivers/sensors/bh1721fvc_scu.c, boards/arm/cxd56xx/drivers/sensors/lt1pa01_scu.c, boards/arm/cxd56xx/drivers/sensors/rpr0521rs_scu.c, include/nuttx/video/video_controls.h
=> Fix nuttx coding style

fs/nfs/nfs_vfsops.c
fs/nfs: fix coding style issue
N/A
local test
=> fs/nfs: fix coding style issue

arch/arm/src/stm32/stm32_rtcounter.c
Optimize stm32 RTC accuracy
chip
stm32f103ret6
board
et-stm32-stamp:nsh
config
CONFIG_RTC_DRIVER=y
CONFIG_STM32_BKP=y
CONFIG_STM32_PWR=y
CONFIG_STM32_RTC=y
=> Optimize stm32 RTC accuracy

drivers/sensors/bmi270.c
fix BMI160_TEMPERATURE_0 ->BMI270_TEMPERATURE_0
fix BMI160_TEMPERATURE_1 ->BMI270_TEMPERATURE_1
none
=> drivers/sensors/bmi270.c: fix define BMI270_TEMPERATURE

libs/libc/pwd/lib_getpwent.c, libs/libc/signal/sig_altstack.c, libs/libc/string/lib_strsignal.c, mm/umm_heap/umm_malloc.c, mm/umm_heap/umm_memalign.c, mm/umm_heap/umm_realloc.c, mm/umm_heap/umm_zalloc.c
fix last PR review qeustions
unionfs
unionfs
=> ltp: fix review questions

drivers/serial/serial.c
=> serial: Simplify the echo process

fs/aio/aio_cancel.c, fs/mqueue/mq_unlink.c, fs/procfs/fs_procfs.c, fs/semaphore/sem_open.c, fs/semaphore/sem_unlink.c
fs: modify or remove sched_[un]lock
none
ostest
=> fs: modify or remove sched_[un]lock

net/local/local_recvmsg.c
Add support for MSG_DONTWAIT to SOCK_STREAM
minor
=> net/local:Add support for MSG_DONTWAIT to SOCK_STREAM

arch/sim/src/sim/posix/sim_alsa.c
when executing ioctl AUDIOIOC_GETBUFFERINFO,the priv->pcm is still NULL, so it will return -ENXIO,we can remove this check at the start of ioctl and add in the case where it is used.
=> alsa/sim_alsa.c:fix ioctl AUDIOIOC_GETBUFFERINFO error

drivers/timers/Kconfig, drivers/timers/Make.defs, drivers/timers/pl031.c, include/nuttx/timers/pl031.h
=> qemu:add qemu rtc driver.

arch/xtensa/src/esp32/Kconfig
Fix some ESP32 Peripheral help comments
Only ESP32
N/A
=> Fix some ESP32 Peripheral help comments

Documentation/components/filesystem.rst
Add doc for TXTABLE partition table.
Local test and CI (of forked repo) passed, and viewed ok.
=> Partition: Add doc for TXTABLE

drivers/1wire/1wire.c
=> 1wrie:fix typo

fs/mqueue/mq_open.c, include/mqueue.h, sched/mqueue/mq_rcvinternal.c, sched/mqueue/mq_receive.c, sched/mqueue/mq_send.c, sched/mqueue/mq_sndinternal.c, sched/mqueue/mq_timedsend.c
fix some mqueue issues to following standard POSIX specification.
=> POSIX: fix some issues for ltp mqueue testcases.

crypto/crypto.c, crypto/cryptodev.c
=> fix nuttx crypto stability bug

crypto/Makefile, crypto/curve25519.c, include/crypto/curve25519.h
porting Curve25519 algorithm to support key arrangment
=> crypto: porting Curve25519

net/inet/inet_sockif.c
libuvtestcase:
```
TEST_IMPL(tcp_listen_without_bind) {
int r;
uv_tcp_t server;
r = uv_tcp_init(uv_default_loop(), &server);
ASSERT(r == 0);
r = uv_listen((uv_stream_t*)&server, 128, NULL);
ASSERT(r == 0);
MAKE_VALGRIND_HAPPY();
return 0;
}
```
libuv testcase
=> inet/inet_sockif.c:In tcp protocol, Add random ports during the listening phase, if no ports are bound

boards/arm/stm32/common/src/stm32_bh1750.c, boards/arm/xmc4/xmc4500-relax/src/xmc4_max6675.c, boards/xtensa/esp32/common/src/esp32_max6675.c, boards/xtensa/esp32s2/common/src/esp32s2_max6675.c
stm32_bh1750.c: barometer -> ambient light sensor
xmc4_max6675.c: barometer -> temperature
esp32_max6675.c: barometer -> temperature
esp32s2_max6675.c: barometer -> temperature
none
=> fix incorrect comments

drivers/power/pm/pm_activity.c, include/nuttx/queue.h
pm: fix second time add wakelock dq caused error
power
VELA
=>  pm: fix second time add wakelock dq caused error

arch/sim/src/sim/posix/sim_x11framebuffer.c, arch/sim/src/sim/sim_framebuffer.c, arch/sim/src/sim/sim_internal.h
The window opens when the fb opens and closes when the fb closes.
None.
Run fb demo.
=> sim framebuffer: Optimize the timing of window to open and to close

arch/arm/src/armv7-a/arm_head.S, arch/arm/src/armv7-a/arm_perf.c, arch/arm/src/armv7-m/arm_perf.c, arch/arm/src/armv7-r/arm_head.S, arch/arm/src/armv7-r/arm_perf.c, arch/arm/src/armv8-m/arm_perf.c, arch/xtensa/src/common/xtensa_perf.c
armv7-r: idle stack should align with 8
armv7-a: align stack_top code with armv7-r
perf: avoid div zero if up_perf_init() hasn't init
armv7a/r
VELA
=> armv7 updated

libs/libc/machine/arm/armv7-m/gnu/arch_memset.S, libs/libc/machine/arm/armv8-m/gnu/arch_memset.S
Use the memset function in bionic for better performance.
based on PR #10053.
memset
BES board
=> arm-m: update memset function

crypto/cryptodev.c, crypto/cryptosoft.c, crypto/xform.c, include/crypto/cryptodev.h, include/crypto/xform.h
refer to commit https://github.com/openbsd/src/commit/649dc2d9858d48bf78fc404b6fab58ba4e01d29c
(1) import hash method
(2) separate the update and finish processes
=> crypto: export MD5/SHA1/SHA256/SHA512 via /dev/crypto

arch/sim/src/sim/sim_camera.c, drivers/video/video.c, include/nuttx/video/imgdata.h, include/nuttx/video/imgsensor.h
=> drivers/video: video driver supports NV12

drivers/usbdev/CMakeLists.txt, drivers/usbdev/Make.defs, drivers/usbdev/adb.c, drivers/usbdev/cdcacm.c, drivers/usbdev/cdcecm.c, drivers/usbdev/composite.c, drivers/usbdev/dfu.c, drivers/usbdev/pl2303.c, drivers/usbdev/rndis.c, drivers/usbdev/usbdev_req.c, drivers/usbdev/usbmsc.c, include/nuttx/usb/usbdev.h
Move usbdev_req function to common code, Reduce duplicated code.
USB
BES Board
=> usbdev: move usbdev_req function to common code

LICENSE
add curve25519 implementation, and the implementation are ported from open-bsd
Signed-off-by: makejian [makejian@xiaomi.com](mailto:makejian@xiaomi.com)
=> crypto: add curve25519 license

include/nuttx/sensors/sensor.h
=> fix SIM sensor rpmsg runtime error by asan report.

drivers/note/note_driver.c, drivers/note/noteram_driver.c, include/nuttx/note/noteram_driver.h
change 1: Change ni_buffer to point to reduce flash size
change 2：reduce global variable references 
change 3: support multi-instance
=> noteram multi-instance support

include/nuttx/note/noteram_driver.h
Made by https://github.com/apache/nuttx/pull/10076
ci
=> noteram: Remove the unnessary inclusion and declaration from header file

arch/xtensa/src/common/Make.defs, arch/xtensa/src/common/xtensa_mpu.c
compile xtensa_mpu.c
xtensa
VELA
=> xtensa: fix compile miss file

drivers/mtd/mtd_config_fs.c, include/nuttx/mtd/configdata.h
=> driver/mtd_config : add mtdconfig_register_by_path()

wireless/bluetooth/bt_gatt.c
wireless/bluetooth: correct judgment conditions
N/A
ci-check
=> wireless/bluetooth: correct judgment conditions 

drivers/mtd/mtd_config.c, drivers/mtd/mtd_config_fs.c
=> driver/mtd_config : just query when data is null or len is zero

audio/Kconfig, include/nuttx/audio/audio.h
=> audio:add format sbc support

arch/arm/src/armv7-r/CMakeLists.txt, arch/arm/src/tms570/CMakeLists.txt, boards/arm/tms570/launchxl-tms57004/CMakeLists.txt, boards/arm/tms570/launchxl-tms57004/src/CMakeLists.txt, boards/arm/tms570/tms570ls31x-usb-kit/CMakeLists.txt, boards/arm/tms570/tms570ls31x-usb-kit/src/CMakeLists.txt
=> cmake:support armv7-r and tms570 chip

audio/Kconfig
Remove spaces from Kconfig
none
=> audio/Kconfig: Fix Kconfig style

drivers/usbdev/Kconfig, drivers/usbdev/composite.h
Add COMPOSITE_DEVICES config for composite device, mentioned in the https://github.com/apache/nuttx/pull/10070.
composite device.
sim:usbdev
=> composite: add COMPOSITE_DEVICES config for composite device

drivers/video/Kconfig, drivers/video/Make.defs, drivers/video/goldfish_camera.c, include/nuttx/video/goldfish_camera.h
=> drivers/video: add nuttx goldfish camera driver

crypto/blake2s.c
crypto:fix typo for blake2s
Noting
Noting
=> crypto:fix typo for blake2s

crypto/cryptodev.c, crypto/cryptosoft.c, crypto/sha2.c, crypto/xform.c, include/crypto/cryptodev.h, include/crypto/sha2.h, include/crypto/xform.h
(1)add sha224 algorithm in sha2.c
(2)export sha224/sha384
=> crypto: export SHA224/SHA384 via /dev/crypto
